! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE FPTRATOD(KFPXFLD,YDFPGEO_DEP,YDFPGIND,YDFPGEO,KFLDS,PFIELD_ARR,PFIELD_DEP)


!**** *FPTRATOD*  - FULL-POS TRANSPOSITION.
!                   Arrival geometry DM-distribution towards
!                   Departure geometry DM-distribution.

!     PURPOSE.
!     --------

!**   INTERFACE.
!     ----------
!       *CALL* *FPTRATOD*

!        EXPLICIT ARGUMENTS
!        --------------------
!         INPUT:
!          KFPXFLD : maximum number of fields to extract at a time
!          KFLDS:      number of fields to be transposed.
!          PFIELD_ARR: array with arrival geometry DM-distribution.

!         OUTPUT:
!          PFIELD_DEP: array with departure geometry DM-distribution.

!        IMPLICIT ARGUMENTS
!        --------------------
!        See lower #include.

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS
!        Documentation about FULL-POS.

!     AUTHOR.
!     -------
!        K. Yessad (CNRM/GMAP)
!        ORIGINAL : 21-Mar-2007

!     MODIFICATIONS.
!     --------------
!        R. El Khatib 04-Aug-2016 rewrite from fptrdtoa
!     End modifications
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK

USE YOMMP0   , ONLY : MYPROC   ,NPRCIDS, NPROC
USE YOMFPGEO, ONLY : TFPGEO
USE YOMFPGIND, ONLY : TFPGIND
USE MPL_MODULE,ONLY : MPL_RECV, MPL_SEND, MPL_WAIT, JP_NON_BLOCKING_STANDARD, MPL_WAITANY

!     ------------------------------------------------------------------

IMPLICIT NONE

INTEGER(KIND=JPIM), INTENT(IN) :: KFPXFLD
TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO_DEP
TYPE (TFPGIND),  INTENT(IN) :: YDFPGIND
TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLDS
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFIELD_ARR(YDFPGEO%NFPROMA,KFLDS,YDFPGEO%NFPBLOCS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFIELD_DEP(YDFPGEO_DEP%NFPROMA,KFLDS,YDFPGEO_DEP%NFPBLOCS)

!     ------------------------------------------------------------------

INTEGER(KIND=JPIM) :: JROC, IOFF, JI, IFLDLOC
INTEGER(KIND=JPIM) :: IOFFPROC_SND(NPROC), IOFFPROC_RCV(NPROC)
INTEGER(KIND=JPIM) :: IFLDSCH, JCH, IFLDOFF, IFIELDS, IFLDG
INTEGER(KIND=JPIM) :: ILENBUFSEND, ILENBUFRECV, IGP2RECV, IGP2SEND, ICOUNT
INTEGER(KIND=JPIM) :: IRECVS(NPROC), ISENDS(NPROC), IREQRCV(NPROC), IOFFRECV(NPROC), IOFFSEND(NPROC)
INTEGER(KIND=JPIM), ALLOCATABLE :: IBLOC_DEP(:), IBLOC_ARR(:) ! bloc number
INTEGER(KIND=JPIM), ALLOCATABLE :: IGP_DEP(:), IGP_ARR(:) ! location in the current bloc

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('FPTRATOD',0,ZHOOK_HANDLE)
ASSOCIATE(NFPROMA_DEP=>YDFPGEO_DEP%NFPROMA, &
 & NFP2RECV=>YDFPGIND%NFP2RECV, NFP2SEND=>YDFPGIND%NFP2SEND, NFPSOURCE=>YDFPGIND%NFPSOURCE, &
 & NFPTARGET=>YDFPGIND%NFPTARGET, &
 & NFPBLOCS=>YDFPGEO%NFPBLOCS, NFPROMA=>YDFPGEO%NFPROMA)

IGP2SEND=SUM(NFP2RECV(:))
IGP2RECV=SUM(NFP2SEND(:))
ALLOCATE(IBLOC_DEP(IGP2RECV))
ALLOCATE(IBLOC_ARR(IGP2SEND))
ALLOCATE(IGP_DEP(IGP2RECV))
ALLOCATE(IGP_ARR(IGP2SEND))

IOFFSEND(1)=0
IOFFRECV(1)=0
DO JROC = 1, NPROC-1
  IOFFSEND(JROC+1)=IOFFSEND(JROC)+NFP2RECV(JROC)
  IOFFRECV(JROC+1)=IOFFRECV(JROC)+NFP2SEND(JROC)
ENDDO

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JROC,JI)
DO JROC = 1, NPROC
  DO JI=1,NFP2SEND(JROC)
    IBLOC_DEP(JI+IOFFRECV(JROC))=(NFPSOURCE(JI,JROC)-1)/NFPROMA_DEP+1
    IGP_DEP  (JI+IOFFRECV(JROC))=NFPSOURCE(JI,JROC)-((IBLOC_DEP(JI+IOFFRECV(JROC))-1)*NFPROMA_DEP)
  ENDDO
  DO JI=1,NFP2RECV(JROC)
    IBLOC_ARR(JI+IOFFSEND(JROC))=(NFPTARGET(JI,JROC)-1)/NFPROMA+1
    IGP_ARR  (JI+IOFFSEND(JROC))=NFPTARGET(JI,JROC)-((IBLOC_ARR(JI+IOFFSEND(JROC))-1)*NFPROMA)
  ENDDO
ENDDO
!$OMP END PARALLEL DO

IF (KFPXFLD <= 0) THEN
  IFLDSCH=KFLDS
ELSE
  IFLDSCH=KFPXFLD
ENDIF

DO JCH=1,(KFLDS-1)/IFLDSCH+1

  IFLDOFF=(JCH-1)*IFLDSCH
  IFIELDS=MIN(JCH*IFLDSCH,KFLDS)-IFLDOFF

  DO JROC = 1, MYPROC-1
    IRECVS(JROC)=NFP2SEND(JROC)*IFIELDS
    ISENDS(JROC)=NFP2RECV(JROC)*IFIELDS
  ENDDO
  IRECVS(MYPROC)=0
  ISENDS(MYPROC)=0
  DO JROC = MYPROC+1,NPROC
    IRECVS(JROC)=NFP2SEND(JROC)*IFIELDS
    ISENDS(JROC)=NFP2RECV(JROC)*IFIELDS
  ENDDO

  ILENBUFRECV=SUM(IRECVS(:))
  ILENBUFSEND=SUM(ISENDS(:))

  CALL FPTRATOD_COMM

ENDDO

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FPTRATOD',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE FPTRATOD_COMM

INTEGER(KIND=JPIM) :: IREQSND(NPROC)
INTEGER(KIND=JPIM) :: IREQINDX(NPROC), JNR, INR, IRRCV
REAL(KIND=JPRB) :: ZBUFSEND(ILENBUFSEND), ZBUFRECV(ILENBUFRECV)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('FPTRATOD:FPTRATOD_COMM',0,ZHOOK_HANDLE)
ASSOCIATE(NFP2RECV=>YDFPGIND%NFP2RECV, NFP2SEND=>YDFPGIND%NFP2SEND)

!      1.1 Post recv first

IOFFPROC_RCV(1)=0
IOFFPROC_SND(1)=0
DO JROC = 1, NPROC-1
  IOFFPROC_RCV(JROC+1)=IOFFPROC_RCV(JROC)+IRECVS(JROC)
  IOFFPROC_SND(JROC+1)=IOFFPROC_SND(JROC)+ISENDS(JROC)
ENDDO


IRRCV=0
DO JROC = 1, NPROC
  IF (IRECVS(JROC) > 0 .AND. JROC /= MYPROC) THEN
    IRRCV=IRRCV+1
    IREQINDX(IRRCV)=JROC
    CALL MPL_RECV(ZBUFRECV(IOFFPROC_RCV(JROC)+1:IOFFPROC_RCV(JROC)+IRECVS(JROC)), &
     & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQRCV(IRRCV), &
     & KOUNT=ICOUNT,KSOURCE=NPRCIDS(JROC),KTAG=JROC,CDSTRING='FPTRATOD:FPTRATOD_COMM')
  ENDIF
ENDDO

!      1.2 Sends

DO JROC = 1, NPROC
  IF (ISENDS(JROC) > 0 .AND. JROC /= MYPROC) THEN
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(IFLDLOC,IOFF,IFLDG,JI)
    DO IFLDLOC=1,IFIELDS
      IOFF=IOFFPROC_SND(JROC)+(IFLDLOC-1)*NFP2RECV(JROC)
      IFLDG=IFLDLOC+IFLDOFF
      DO JI=1,NFP2RECV(JROC)
        ZBUFSEND(JI+IOFF)=PFIELD_ARR(IGP_ARR(JI+IOFFSEND(JROC)),IFLDG,IBLOC_ARR(JI+IOFFSEND(JROC)))
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL MPL_SEND(ZBUFSEND(IOFFPROC_SND(JROC)+1:IOFFPROC_SND(JROC)+ISENDS(JROC)), &
     & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQSND(JROC), &
     & KTAG=MYPROC,KDEST=NPRCIDS(JROC),CDSTRING='FPTRATOD:FPTRATOD_COMM')
  ENDIF
ENDDO

!      1.3 Local contribution

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JI,IFLDLOC,IFLDG)
DO IFLDLOC=1,IFIELDS
  IFLDG=IFLDLOC+IFLDOFF
  DO JI=1,NFP2SEND(MYPROC)
    PFIELD_DEP(IGP_DEP(JI+IOFFRECV(MYPROC)),IFLDG,IBLOC_DEP(JI+IOFFRECV(MYPROC)))= &
    & PFIELD_ARR(IGP_ARR(JI+IOFFSEND(MYPROC)),IFLDG,IBLOC_ARR(JI+IOFFSEND(MYPROC)))
  ENDDO
ENDDO
!$OMP END PARALLEL DO

!      1.4 Actual recv

DO JNR=1,IRRCV
  CALL MPL_WAITANY(KREQUEST=IREQRCV(1:IRRCV),KINDEX=INR,CDSTRING='FPTRATOD:FPTRATOD_COMM: WAIT FOR ANY RECVS')
  JROC=IREQINDX(INR)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JI,IFLDLOC,IOFF,IFLDG)
  DO IFLDLOC=1,IFIELDS
    IOFF=IOFFPROC_RCV(JROC)+(IFLDLOC-1)*NFP2SEND(JROC)
    IFLDG=IFLDLOC+IFLDOFF
    DO JI=1,NFP2SEND(JROC)
      PFIELD_DEP(IGP_DEP(JI+IOFFRECV(JROC)),IFLDG,IBLOC_DEP(JI+IOFFRECV(JROC)))=ZBUFRECV(JI+IOFF)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
ENDDO

!      1.5 Wait completion of sends

DO JROC = 1, NPROC
  IF (ISENDS(JROC) > 0 .AND. JROC /= MYPROC) THEN
    CALL MPL_WAIT(KREQUEST=IREQSND(JROC),CDSTRING='FPTRATOD:FPTRATOD_COMM: WAIT FOR SENDS')
  ENDIF
ENDDO

! ---------------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FPTRATOD:FPTRATOD_COMM',1,ZHOOK_HANDLE)

END SUBROUTINE FPTRATOD_COMM

END SUBROUTINE FPTRATOD
