! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE FPTRGTOA(YDFPGEO_DEP,YDFPGIND,YDFPGEO,KNFD,KFLDOFF,KBFA,KFIELDS,PREALG,PFIELD_ARR)


!**** *FPTRGTOA*  - FULL-POS TRANSPOSITION.
!                   Global geometry field -distribution towards
!                   arrival geometry-distribution.

!     PURPOSE.
!     --------

!**   INTERFACE.
!     ----------
!       *CALL* *FPTRGTOA*

!        EXPLICIT ARGUMENTS
!        --------------------
!         INPUT:
!          KNFD:    number of local fields for each MPI task
!          KFLDOFF: offset to the first local field for each MPI task
!          KBFA   : Absolute first field to be transposed
!          PREALG:  array with global departure geometry
!          KFIELDS: total number of fields in output buffer

!         OUTPUT:
!          PFIELD_ARR: array with arrival geometry DM-distribution.

!        IMPLICIT ARGUMENTS
!        --------------------
!        See lower #include.

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS
!        Documentation about FULL-POS.

!     AUTHOR.
!     -------
!        R. El Khatib (CNRM/GMAP)
!        ORIGINAL : 10-Aug-2016 from fptrdtoa

!     MODIFICATIONS.
!     --------------
!     End modifications
!     ------------------------------------------------------------------

USE PARKIND1  , ONLY : JPIM     ,JPRB
USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK

USE YOMMP0    , ONLY : MYPROC   ,NPRCIDS, NPROC
USE YOMFPGEO, ONLY : TFPGEO
USE YOMFPGIND, ONLY : TFPGIND
USE MPL_MODULE, ONLY : MPL_SEND, MPL_RECV, MPL_WAIT, JP_NON_BLOCKING_STANDARD, MPL_WAITANY

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO_DEP
TYPE (TFPGIND),  INTENT(IN) :: YDFPGIND
TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO
INTEGER(KIND=JPIM), INTENT(IN)    :: KNFD(NPROC)
INTEGER(KIND=JPIM), INTENT(IN)    :: KFLDOFF(NPROC)
INTEGER(KIND=JPIM), INTENT(IN)    :: KBFA
INTEGER(KIND=JPIM), INTENT(IN)    :: KFIELDS
REAL(KIND=JPRB)   , INTENT(IN)    :: PREALG(YDFPGEO_DEP%NFPRGPG,KNFD(MYPROC))
REAL(KIND=JPRB)   , INTENT(INOUT) :: PFIELD_ARR(YDFPGEO%NFPROMA,KFIELDS,YDFPGEO%NFPBLOCS)

!     ------------------------------------------------------------------

INTEGER(KIND=JPIM) :: JROC, IOFF, JI, IFLDLOC, IFLDG, JFP, JBL
INTEGER(KIND=JPIM) :: IOFFPROC_SND(NPROC), IOFFPROC_RCV(NPROC)
INTEGER(KIND=JPIM) :: ILENBUFRECV, ILENBUFSEND, IGP2SEND, IGP2RECV, ICOUNT
INTEGER(KIND=JPIM) :: ISENDS(NPROC), IREQRCV(NPROC), IOFFSEND(NPROC)
INTEGER(KIND=JPIM), ALLOCATABLE :: IBLOC_ARR(:) ! bloc number
INTEGER(KIND=JPIM), ALLOCATABLE :: IGP_DEP(:), IGP_ARR(:) ! location in the current bloc

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('FPTRGTOA',0,ZHOOK_HANDLE)
ASSOCIATE(NFP2SENDG=>YDFPGIND%NFP2SENDG, NFPSOURCEG=>YDFPGIND%NFPSOURCEG, &
 & NFPBLOCS=>YDFPGEO%NFPBLOCS, NFPROMA=>YDFPGEO%NFPROMA, NFPEND=>YDFPGEO%NFPEND, &
 & NFPRGPL=>YDFPGEO%NFPRGPL)

IGP2SEND=SUM(NFP2SENDG(:))
IGP2RECV=NFPRGPL
ALLOCATE(IBLOC_ARR(IGP2RECV))
ALLOCATE(IGP_DEP(IGP2SEND))
ALLOCATE(IGP_ARR(IGP2RECV))

IOFFSEND(1)=0
DO JROC = 1, NPROC-1
  IOFFSEND(JROC+1)=IOFFSEND(JROC)+NFP2SENDG(JROC)
ENDDO

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JROC,JI)
DO JROC = 1, NPROC
  DO JI=1,NFP2SENDG(JROC)
    IGP_DEP (JI+IOFFSEND(JROC))=NFPSOURCEG(JI,JROC)
  ENDDO
ENDDO
!$OMP END PARALLEL DO

DO JROC = 1,NPROC
  ISENDS(JROC)=NFP2SENDG(JROC)*KNFD(MYPROC)
ENDDO
ISENDS(MYPROC)=0

ILENBUFRECV=NFPRGPL*SUM(KNFD(:))
ILENBUFSEND=SUM(ISENDS(:))

CALL FPTRGTOA_COMM

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FPTRGTOA',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE FPTRGTOA_COMM

INTEGER(KIND=JPIM) :: IREQSND(NPROC), IRSND
INTEGER(KIND=JPIM) :: IREQINDX(NPROC), JNR, INR, IRRCV
REAL(KIND=JPRB) :: ZBUFSEND(ILENBUFSEND), ZBUFRECV(ILENBUFRECV)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('FPTRGTOA:FPTRGTOA_COMM',0,ZHOOK_HANDLE)
ASSOCIATE(NFPBLOCS=>YDFPGEO%NFPBLOCS, NFPROMA=>YDFPGEO%NFPROMA, NFPEND=>YDFPGEO%NFPEND, &
 & NFPRGPL=>YDFPGEO%NFPRGPL, NFP2SENDG=>YDFPGIND%NFP2SENDG)

!      1.1 Post recv first

IOFFPROC_RCV(1)=0
IOFFPROC_SND(1)=0
DO JROC = 1, NPROC-1
  IOFFPROC_RCV(JROC+1)=IOFFPROC_RCV(JROC)+NFPRGPL*KNFD(JROC)
  IOFFPROC_SND(JROC+1)=IOFFPROC_SND(JROC)+ISENDS(JROC)
ENDDO


IRRCV=0
DO JROC = 1, NPROC
  IF (NFPRGPL*KNFD(JROC) > 0 .AND. JROC /= MYPROC) THEN
    IRRCV=IRRCV+1
    IREQINDX(IRRCV)=JROC
    CALL MPL_RECV(ZBUFRECV(IOFFPROC_RCV(JROC)+1:IOFFPROC_RCV(JROC)+NFPRGPL*KNFD(JROC)), &
     & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQRCV(IRRCV), &
     & KOUNT=ICOUNT,KSOURCE=NPRCIDS(JROC),KTAG=JROC,CDSTRING='FPTRGTOA:FPTRGTOA_COMM')  
  ENDIF
ENDDO

!      1.2 Sends

IRSND=0
DO JROC = 1, NPROC
  IF (ISENDS(JROC) > 0 .AND. JROC /= MYPROC) THEN
    IRSND=IRSND+1
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(IFLDLOC,IOFF,JI)
    DO IFLDLOC=1,KNFD(MYPROC)
      IOFF=IOFFPROC_SND(JROC)+(IFLDLOC-1)*NFP2SENDG(JROC)
      DO JI=1,NFP2SENDG(JROC)
        ZBUFSEND(JI+IOFF)=PREALG(IGP_DEP(JI+IOFFSEND(JROC)),IFLDLOC)
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL MPL_SEND(ZBUFSEND(IOFFPROC_SND(JROC)+1:IOFFPROC_SND(JROC)+ISENDS(JROC)), &
     & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQSND(IRSND), &
     & KTAG=MYPROC,KDEST=NPRCIDS(JROC),CDSTRING='FPTRGTOA:FPTRGTOA_COMM')
  ENDIF
ENDDO

!      1.3 Local contribution

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JI,IFLDLOC,IFLDG)
DO IFLDLOC=1,KNFD(MYPROC)
  IFLDG=IFLDLOC+KFLDOFF(MYPROC)+KBFA-1
  DO JBL=1,NFPBLOCS
    DO JFP=1,NFPEND(JBL)
      JI=(JBL-1)*NFPROMA+JFP
      PFIELD_ARR(JFP,IFLDG,JBL)=PREALG(IGP_DEP(JI+IOFFSEND(MYPROC)),IFLDLOC)
    ENDDO
  ENDDO
ENDDO
!$OMP END PARALLEL DO

!      1.4 Actual recv

DO JNR=1,IRRCV
  CALL MPL_WAITANY(KREQUEST=IREQRCV(1:IRRCV),KINDEX=INR,CDSTRING='FPTRGTOA:FPTRGTOA_COMM: WAIT FOR ANY RECVS')
  JROC=IREQINDX(INR)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JI,IFLDLOC,IOFF,IFLDG)
  DO IFLDLOC=1,KNFD(JROC)
    IOFF=IOFFPROC_RCV(JROC)+(IFLDLOC-1)*NFPRGPL
    IFLDG=IFLDLOC+KFLDOFF(JROC)+KBFA-1
    DO JBL=1,NFPBLOCS
      DO JFP=1,NFPEND(JBL)
        JI=(JBL-1)*NFPROMA+JFP
        PFIELD_ARR(JFP,IFLDG,JBL)=ZBUFRECV(JI+IOFF)
      ENDDO
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
ENDDO

!      1.5 Wait completion of sends

IF (IRSND > 0) THEN
  CALL MPL_WAIT(KREQUEST=IREQSND(1:IRSND),CDSTRING='FPTRGTOA:FPTRGTOA_COMM: WAIT FOR SENDS')
ENDIF

! ---------------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FPTRGTOA:FPTRGTOA_COMM',1,ZHOOK_HANDLE)

END SUBROUTINE FPTRGTOA_COMM

END SUBROUTINE FPTRGTOA
