! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE READ_SPEC_RESTART(YDSPEC,CDFNAME,CDFPATH,KNUM_PROCS_PER_IO_PROC,&
                             YD_IOSTREAM,YD_IOREQUEST)

!     Purpose.
!     --------
!       Read in restart spectral fields

!     Author.
!     -------
!       Marcin Chrust *ECMWF*

!     Modifications.
!     --------------
!       Original  : 08-04-2020
! ------------------------------------------------------------------

USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE PARKIND1           , ONLY : JPIM, JPRB
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMMP0             , ONLY : MYPROC, NPROC
USE YOMLUN             , ONLY : NULOUT
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, SPECTRAL_FIELD_CONTAINER
USE IOSTREAM_MIX       , ONLY : SETUP_IOSTREAM, SETUP_IOREQUEST, IO_GET,&
 &                              CLOSE_IOSTREAM, TYPE_IOSTREAM , TYPE_IOREQUEST,&
 &                              CLOSE_IOREQUEST
USE GENERIC_CTLVEC_MOD,  ONLY : MULTI_IO

IMPLICIT NONE

TYPE(SPECTRAL_FIELD_CONTAINER), INTENT(INOUT)                :: YDSPEC(:)
CHARACTER(LEN=*),               INTENT(IN)                   :: CDFNAME
CHARACTER(LEN=*),               INTENT(IN), OPTIONAL         :: CDFPATH
INTEGER(KIND=JPIM),             INTENT(IN), OPTIONAL         :: KNUM_PROCS_PER_IO_PROC
TYPE(TYPE_IOSTREAM),            INTENT(IN), OPTIONAL, TARGET :: YD_IOSTREAM
TYPE(TYPE_IOREQUEST),           INTENT(IN), OPTIONAL, TARGET :: YD_IOREQUEST

LOGICAL                       :: LL_SETUP_IOREQUEST
CHARACTER (LEN = 256)         :: CLFN
CHARACTER (LEN = 5)           :: CLMYPROC
INTEGER(KIND=JPIM )           :: IBUF(1)
INTEGER(KIND=JPIM)            :: JK,JFLDS,IPROC,INUMFLDS
INTEGER(KIND=JPIM)            :: NUM_PROCS_PER_IO_PROC,NUM_IO_PROCS
INTEGER(KIND=JPIM), ALLOCATABLE :: NIOPROCS(:),NSH2D(:),NSH3D(:)
REAL(KIND=JPRB), ALLOCATABLE  :: ZBUFSP2D(:),ZBUFSP3D(:)
TYPE(MULTI_IO)                :: YL_MULTI_IO_2D, YL_MULTI_IO_3D
TYPE(TYPE_IOSTREAM),  POINTER :: YL_IOSTREAM
TYPE(TYPE_IOREQUEST), POINTER :: YL_IOREQUEST
REAL(KIND=JPHOOK)             :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('READ_SPEC_RESTART',0,ZHOOK_HANDLE)

NUM_PROCS_PER_IO_PROC=1
IF(PRESENT(KNUM_PROCS_PER_IO_PROC)) & 
  & NUM_PROCS_PER_IO_PROC=KNUM_PROCS_PER_IO_PROC
IF (MOD(NPROC,NUM_PROCS_PER_IO_PROC)/=0) &
  & CALL ABOR1('FIELD_CONTAINER_WRITE_RESTART WRONG I/O LAYOUT')
NUM_IO_PROCS=NPROC/NUM_PROCS_PER_IO_PROC
ALLOCATE(NIOPROCS(NUM_IO_PROCS))
IPROC=0
DO JK = NUM_PROCS_PER_IO_PROC,NPROC,NUM_PROCS_PER_IO_PROC
  IPROC=IPROC+1
  NIOPROCS(IPROC) = JK
  IF(PRESENT(CDFPATH)) THEN
    WRITE(CLMYPROC,'(I5.5)')MYPROC
    CLFN=TRIM(CDFPATH)//'/'//CLMYPROC//'/'//TRIM(CDFNAME)
  ELSE
    WRITE(CLMYPROC,'(A1,I4.4)')'.',MYPROC
    CLFN=TRIM(CDFNAME)//CLMYPROC
  ENDIF  
ENDDO
INUMFLDS=SIZE(YDSPEC)

LL_SETUP_IOREQUEST=.TRUE.
IF(PRESENT(YD_IOSTREAM).AND.PRESENT(YD_IOREQUEST)) THEN
  YL_IOSTREAM=>YD_IOSTREAM
  YL_IOREQUEST=>YD_IOREQUEST
  LL_SETUP_IOREQUEST=.FALSE.
  WRITE(UNIT=NULOUT,FMT='('' READ SPECTRAL FIELD '',A)') CDFNAME
ELSE
  ALLOCATE(YL_IOSTREAM)
  ALLOCATE(YL_IOREQUEST)
  CALL SETUP_IOSTREAM(YL_IOSTREAM,'CIO',TRIM(CLFN),CDMODE='r', &
    &                 KIOPROCS=NIOPROCS(1:NUM_IO_PROCS))
  CALL SETUP_IOREQUEST(YL_IOREQUEST,'RAW')
  WRITE(UNIT=NULOUT,FMT='('' READ SPECTRAL FIELD '',A)') CLFN
ENDIF  

IF(NUM_PROCS_PER_IO_PROC>1) THEN
  ! SP2D
  NSH2D=SHAPE(YDSPEC(1)%OBJ%SP2D)
  CALL YL_MULTI_IO_2D%SETUP('S',NSH2D(1)*NSH2D(2),NIOPROCS,NUM_IO_PROCS)
  ! SP3D
  NSH3D=SHAPE(YDSPEC(1)%OBJ%SP3D)
  CALL YL_MULTI_IO_3D%SETUP('S',NSH3D(1)*NSH3D(2)*NSH3D(3),NIOPROCS,NUM_IO_PROCS)
  DO JFLDS=1,INUMFLDS
    IBUF(:)=0
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,KR1=IBUF)
    IF(IBUF(1)>0.AND..NOT.ALLOCATED(ZBUFSP2D)) ALLOCATE(ZBUFSP2D(IBUF(1)))
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,PR1=ZBUFSP2D)
    CALL YL_MULTI_IO_2D%SCATTER(YDSPEC(JFLDS)%OBJ%SP2D, ZBUFSP2D, SIZE(ZBUFSP2D))
    
    IBUF(:)=0
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,KR1=IBUF)
    IF(IBUF(1)>0 .AND..NOT.ALLOCATED(ZBUFSP3D)) ALLOCATE(ZBUFSP3D(IBUF(1)))
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,PR1=ZBUFSP3D)
    CALL YL_MULTI_IO_3D%SCATTER(YDSPEC(JFLDS)%OBJ%SP3D, ZBUFSP3D, SIZE(ZBUFSP3D))
  ENDDO  
  CALL YL_MULTI_IO_2D%RESET()
  CALL YL_MULTI_IO_3D%RESET()
  IF(ALLOCATED(ZBUFSP2D)) DEALLOCATE(ZBUFSP2D)
  IF(ALLOCATED(ZBUFSP3D)) DEALLOCATE(ZBUFSP3D)
ELSE
  DO JFLDS=1,INUMFLDS
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,KR1=IBUF)
    IF(IBUF(1) /= YDSPEC(JFLDS)%OBJ%NSPSIZEG) &
      & CALL ABOR1('READ_SPEC_RESTART = WRONG SIZE')
    CALL IO_GET(YL_IOSTREAM,YL_IOREQUEST,&
      &         PR2=YDSPEC(JFLDS)%OBJ%SP2D,&
      &         PR3=YDSPEC(JFLDS)%OBJ%SP3D)
  ENDDO  
ENDIF

IF(LL_SETUP_IOREQUEST) THEN
  CALL CLOSE_IOREQUEST(YL_IOREQUEST)
  CALL CLOSE_IOSTREAM(YL_IOSTREAM)
  DEALLOCATE(YL_IOREQUEST)
  DEALLOCATE(YL_IOSTREAM)
ENDIF
IF (LHOOK) CALL DR_HOOK('READ_SPEC_RESTART',1,ZHOOK_HANDLE)

END SUBROUTINE READ_SPEC_RESTART
