! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

!define ISRCHFLTPV_N
!define ISRCHFLTPV_ARRAY(I)
!define ISRCHFLTPV_INC
!define ISRCHFLTPV_TARGET
!define ISRCHFLTPV_NBITER
!define ISRCHFLTPV_RESULT
      ISRCHFLTPV_RESULT = -1
      IF (ISRCHFLTPV_N.LE.0) THEN
        ISRCHFLTPV_RESULT=0
      ELSE


        IF (ISRCHFLTPV_NBITER.EQ.8) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I  ))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+2))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+3))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+4))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+5))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+6))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+7))<ISRCHFLTPV_TARGET)THEN
             ISRCHFLTPV_RESULT=ISRCHFLTPV_I
             EXIT
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT < 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &<ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF


        ELSEIF (ISRCHFLTPV_NBITER.EQ.6) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I  ))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+2))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+3))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+4))<ISRCHFLTPV_TARGET)THEN
          IF(ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+5))<ISRCHFLTPV_TARGET)THEN
             ISRCHFLTPV_RESULT=ISRCHFLTPV_I
             EXIT
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT < 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &<ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF

        ELSEIF (ISRCHFLTPV_NBITER.EQ.5) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+2))&
          &<ISRCHFLTPV_TARGET ) THEN
           IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+3))&
          &<ISRCHFLTPV_TARGET ) THEN
           IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+4))&
          &<ISRCHFLTPV_TARGET ) THEN
            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT < 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &<ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF



        ELSEIF (ISRCHFLTPV_NBITER.EQ.4) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+2))&
          &<ISRCHFLTPV_TARGET ) THEN
           IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+3))&
          &<ISRCHFLTPV_TARGET ) THEN

            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
          ENDIF
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT < 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &<ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF


        ELSEIF (ISRCHFLTPV_NBITER.EQ.3) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+2))&
          &<ISRCHFLTPV_TARGET ) THEN
            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT < 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &<ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF

        ELSEIF (ISRCHFLTPV_NBITER.EQ.2) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I+1))&
          &<ISRCHFLTPV_TARGET ) THEN
            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT < 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &<ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF

        ELSEIF (ISRCHFLTPV_NBITER.EQ.1) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &<ISRCHFLTPV_TARGET ) THEN
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I))&
          &<ISRCHFLTPV_TARGET ) THEN
            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
          ENDIF
        ENDDO

        IF (ISRCHFLTPV_RESULT < 0) THEN
          DO ISRCHFLTPV_I=ISRCHFLTPV_N-ISRCHFLTPV_NBITER+1,ISRCHFLTPV_N
            IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
            &<ISRCHFLTPV_TARGET ) THEN
              ISRCHFLTPV_RESULT=ISRCHFLTPV_I
              EXIT
            ENDIF
          ENDDO
        ENDIF

        ELSEIF (ISRCHFLTPV_NBITER.EQ.0) THEN

        DO ISRCHFLTPV_I=1,ISRCHFLTPV_N-ISRCHFLTPV_NBITER
          IF ( ISRCHFLTPV_ARRAY(1+ISRCHFLTPV_INC*(ISRCHFLTPV_I-1))&
          &<ISRCHFLTPV_TARGET ) THEN
            ISRCHFLTPV_RESULT=ISRCHFLTPV_I
            EXIT
          ENDIF
        ENDDO

        ELSE
        CALL ABOR1('ISRCHFLTPV: ERROR WITH NBITER VALUE')
        ENDIF

        IF (ISRCHFLTPV_RESULT < 0) THEN
        ISRCHFLTPV_RESULT=ISRCHFLTPV_N+1
        ENDIF

      ENDIF
