! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE FALSIFY_SURF_FLDS(YDSURF)

!**** *FALSIFY_SURF_FLDS*  - Falsify definition of surface fields

!     Purpose.
!     --------

!**   Interface.
!     ----------
!        *CALL* FALSIFY_SURF_FLDS

!        Explicit arguments :
!        --------------------

!        Implicit arguments :
!        --------------------
!        MODULE SURFACE_FIELDS_MIX

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!        None

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!        Ryad El Khatib *METEO-FRANCE*

!     Modifications.
!     --------------
!        Original : 22-Jun-2018
!     ------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE SURFACE_FIELDS_MIX , ONLY : TSURF

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(TSURF), INTENT(INOUT) :: YDSURF

REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('FALSIFY_SURF_FLDS',0,ZHOOK_HANDLE)
ASSOCIATE(YSP_SBD=>YDSURF%YSP_SBD, YSD_VXD=>YDSURF%YSD_VXD, YSD_SFOD=>YDSURF%YSD_SFOD, &
 & YSD_SFLD=>YDSURF%YSD_SFLD, YSD_WWD=>YDSURF%YSD_WWD, YSD_VDD=>YDSURF%YSD_VDD, &
 & YSP_RR=>YDSURF%YSP_RR, YSD_WS=>YDSURF%YSD_WS, NPROGSURFL=>YDSURF%NPROGSURFL, &
 & YSP_OM=>YDSURF%YSP_OM, YSP_EP=>YDSURF%YSP_EP, YSP_CL=>YDSURF%YSP_CL, &
 & YSP_CLD=>YDSURF%YSP_CLD, YSD_VFD=>YDSURF%YSD_VFD, YSP_CI=>YDSURF%YSP_CI, &
 & YSD_WSD=>YDSURF%YSD_WSD, YSD_VC=>YDSURF%YSD_VC, YSD_VP=>YDSURF%YSD_VP, &
 & YSP_SB=>YDSURF%YSP_SB, YSD_VX=>YDSURF%YSD_VX, YSP_X2D=>YDSURF%YSP_X2D, &
 & YSD_VA=>YDSURF%YSD_VA, YSD_XR=>YDSURF%YSD_XR, NSURFL=>YDSURF%NSURFL, &
 & YSD_VND=>YDSURF%YSD_VND, YSD_VHD=>YDSURF%YSD_VHD, YSD_VKD=>YDSURF%YSD_VKD, &
 & YSD_VF=>YDSURF%YSD_VF, YSD_VD=>YDSURF%YSD_VD, &
 & YSP_OMD=>YDSURF%YSP_OMD, YSD_VH=>YDSURF%YSD_VH, YSD_VK=>YDSURF%YSD_VK, &
 & YSD_XA=>YDSURF%YSD_XA, YSD_VN=>YDSURF%YSD_VN, YSD_V3=>YDSURF%YSD_V3, &
 & YSD_SM=>YDSURF%YSD_SM, YSD_SMD=>YDSURF%YSD_SMD, YSD_V2=>YDSURF%YSD_V2, &
 & YSP_SG=>YDSURF%YSP_SG, YSP_RRD=>YDSURF%YSP_RRD, YSD_DID=>YDSURF%YSD_DID, &
 & YSP_SGD=>YDSURF%YSP_SGD, NDIMSURFL=>YDSURF%NDIMSURFL, NPROGSURF=>YDSURF%NPROGSURF, &
 & NDIMSURF=>YDSURF%NDIMSURF, YSP_CID=>YDSURF%YSP_CID, YSD_WW=>YDSURF%YSD_WW, &
 & YSD_V2D=>YDSURF%YSD_V2D, YSD_X2D=>YDSURF%YSD_X2D, YSD_X2=>YDSURF%YSD_X2, &
 & YSD_VV=>YDSURF%YSD_VV, YSD_VCD=>YDSURF%YSD_VCD, YSP_X2=>YDSURF%YSP_X2, &
 & YSD_V3D=>YDSURF%YSD_V3D, YSD_SFO=>YDSURF%YSD_SFO, YSD_VVD=>YDSURF%YSD_VVD, &
 & YSD_SFL=>YDSURF%YSD_SFL, YSD_VPD=>YDSURF%YSD_VPD, YSD_XAD=>YDSURF%YSD_XAD, &
 & YSD_VAD=>YDSURF%YSD_VAD, YSD_DI=>YDSURF%YSD_DI, YSP_EPD=>YDSURF%YSP_EPD, &
 & YSD_XRD=>YDSURF%YSD_XRD, NSURF=>YDSURF%NSURF, &
 & YSD_PFD=>YDSURF%YSD_PFD, YSP_SL=>YDSURF%YSP_SL, YSD_PF=>YDSURF%YSD_PF, &
 & YSP_SLD=>YDSURF%YSP_SLD, YSD_OC=>YDSURF%YSD_OC, YSD_OCD=>YDSURF%YSD_OCD)

!     ------------------------------------------------------------------

! * Group SB=SOILB

IF (ASSOCIATED(YSP_SB%YSB)) THEN
  DEALLOCATE(YSP_SB%YSB)
  NULLIFY(YSP_SB%YSB)
ENDIF

! * Group SG=SNOWG

IF (ASSOCIATED(YSP_SG%YSG)) THEN
  DEALLOCATE(YSP_SG%YSG)
  NULLIFY(YSP_SG%YSG)
ENDIF

! * Group SL=LAKEG

IF (ASSOCIATED(YSP_SL%YSL)) THEN
  DEALLOCATE(YSP_SL%YSL)
  NULLIFY(YSP_SL%YSL)
ENDIF

! * Group RR=RESVR

IF (ASSOCIATED(YSP_RR%YRR)) THEN
  DEALLOCATE(YSP_RR%YRR)
  NULLIFY(YSP_RR%YRR)
ENDIF
  
! * Group CL=CLS

IF (ASSOCIATED(YSP_CL%YCL)) THEN
  DEALLOCATE(YSP_CL%YCL)
  NULLIFY(YSP_CL%YCL)
ENDIF

IF (ASSOCIATED(YSP_OM%YOM)) THEN
  DEALLOCATE(YSP_OM%YOM)
  NULLIFY(YSP_OM%YOM)
ENDIF

! * Group EP=EXTRP

IF (ASSOCIATED(YSP_EP%YEP)) THEN
  DEALLOCATE(YSP_EP%YEP)
  NULLIFY(YSP_EP%YEP)
ENDIF

! * Group X2=XTRP2

IF (ASSOCIATED(YSP_X2%YX2)) THEN
  DEALLOCATE(YSP_X2%YX2)
  NULLIFY(YSP_X2%YX2)
ENDIF

! * Group CI=CANRI

IF (ASSOCIATED(YSP_CI%YCI)) THEN
  DEALLOCATE(YSP_CI%YCI)
  NULLIFY(YSP_CI%YCI)
ENDIF

! * Group VF=VARSF

IF (ASSOCIATED(YSD_VF%YVF)) THEN
  DEALLOCATE(YSD_VF%YVF)
  NULLIFY(YSD_VF%YVF)
ENDIF

! * Group VP=VCLIP

IF (ASSOCIATED(YSD_VP%YVP)) THEN
  DEALLOCATE(YSD_VP%YVP)
  NULLIFY(YSD_VP%YVP)
ENDIF

! * Group VV=VCLIV

IF (ASSOCIATED(YSD_VV%YVV)) THEN
  DEALLOCATE(YSD_VV%YVV)
  NULLIFY(YSD_VV%YVV)
ENDIF

! * Group VN=VCLIN

! - call to INI_SFLP2, allocation:
IF (ASSOCIATED(YSD_VN%YVN)) THEN
  DEALLOCATE(YSD_VN%YVN)
  NULLIFY(YSD_VN%YVN)
ENDIF

! * Group VH=VCLIH

! - call to INI_SFLP2, allocation:
IF (ASSOCIATED(YSD_VH%YVH)) THEN
  DEALLOCATE(YSD_VH%YVH)
  NULLIFY(YSD_VH%YVH)
ENDIF


! * Group VK=VCLIK

! - call to INI_SFLP2, allocation:
IF (ASSOCIATED(YSD_VK%YVK)) THEN
  DEALLOCATE(YSD_VK%YVK)
  NULLIFY(YSD_VK%YVK)
ENDIF

! * Group VA=VCLIA

! - call to INI_SFLP2, allocation:
IF (ASSOCIATED(YSD_VA%YVA)) THEN
  DEALLOCATE(YSD_VA%YVA)
  NULLIFY(YSD_VA%YVA)
ENDIF


! * Group VC=VO3ABC

! - call to INI_SFLP2, allocation:
IF (ASSOCIATED(YSD_VC%YVC)) THEN
  DEALLOCATE(YSD_VC%YVC)
  NULLIFY(YSD_VC%YVC)
ENDIF


! * Group V2=VDIAGO2 (KPP)

! - call to INI_SFLP2, allocation:
IF (ASSOCIATED(YSD_V2%YV2)) THEN
  DEALLOCATE(YSD_V2%YV2)
  NULLIFY(YSD_V2%YV2)
ENDIF

! - call to INI_SFLP3, allocation:
IF (ASSOCIATED(YSD_V3%YV3)) THEN
  DEALLOCATE(YSD_V3%YV3)
  NULLIFY(YSD_V3%YV3)
ENDIF

! * Group OCEAN (coupled ocean model)

! - call to INI_SFLP2, allocation:
IF (ASSOCIATED(YSD_OC%YOC)) THEN
  DEALLOCATE(YSD_OC%YOC)
  NULLIFY(YSD_OC%YOC)
ENDIF

! * Group VD=VDIAG

! - call to INI_SFLP2, allocation:
IF (ASSOCIATED(YSD_VD%YVD)) THEN
  DEALLOCATE(YSD_VD%YVD)
  NULLIFY(YSD_VD%YVD)
ENDIF

IF (ASSOCIATED(YSD_SM%YSM)) THEN
  DEALLOCATE(YSD_SM%YSM)
  NULLIFY(YSD_SM%YSM)
ENDIF

! * Group WS=WAVES (for IFS)

! - call to INI_SFLP2, allocation:
IF (ASSOCIATED(YSD_WS%YWS)) THEN
  DEALLOCATE(YSD_WS%YWS)
  NULLIFY(YSD_WS%YWS)
ENDIF

! * Group WW=WAVES (for WAM)

! - call to INI_SFLP2, allocation:
IF (ASSOCIATED(YSD_WW%YWW)) THEN
  DEALLOCATE(YSD_WW%YWW)
  NULLIFY(YSD_WW%YWW)
ENDIF


! * Group VX=VCLIX

! - call to INI_SFLP2, allocation:
IF (ASSOCIATED(YSD_VX%YVX)) THEN
  DEALLOCATE(YSD_VX%YVX)
  NULLIFY(YSD_VX%YVX)
ENDIF

! * Group DI= Phys DIagnostics

IF (ASSOCIATED(YSD_DI%YXA)) THEN
  DEALLOCATE(YSD_DI%YXA)
  NULLIFY(YSD_DI%YXA)
ENDIF


! * Group XA=VEXTRA

IF (ASSOCIATED(YSD_XA%YXA)) THEN
  DEALLOCATE(YSD_XA%YXA)
  NULLIFY(YSD_XA%YXA)
ENDIF

! * Group PF= precip fraction 

IF (ASSOCIATED(YSD_PF%YXA)) THEN
  DEALLOCATE(YSD_PF%YXA)
  NULLIFY(YSD_PF%YXA)
ENDIF

! * Group XR=VEXTRA-radiation

IF (ASSOCIATED(YSD_XR%YXA)) THEN
  DEALLOCATE(YSD_XR%YXA)
  NULLIFY(YSD_XR%YXA)
ENDIF

! * Group X2=VEXTR2

IF (ASSOCIATED(YSD_X2%YX2)) THEN
  DEALLOCATE(YSD_X2%YX2)
  NULLIFY(YSD_X2%YX2)
ENDIF

! * Group SFL=SFLUX

IF (ASSOCIATED(YSD_SFL%YSFL)) THEN
  DEALLOCATE(YSD_SFL%YSFL)
  NULLIFY(YSD_SFL%YSFL)
ENDIF

! * Group SFO=SFORC

IF (ASSOCIATED(YSD_SFO%YSFO)) THEN
  DEALLOCATE(YSD_SFO%YSFO)
  NULLIFY(YSD_SFO%YSFO)
ENDIF

!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FALSIFY_SURF_FLDS',1,ZHOOK_HANDLE)

END SUBROUTINE FALSIFY_SURF_FLDS
