! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUAFN2(LDNHDYN,YDAFN,KFPCONF)

!**** *SUAFN2*  - INITIALIZE ARPEGE FIELD DESCRIPTORS : 
!                 CONCATENATE INDIVIDUAL TYPES INTO A SINGLE TYPE ARRAY

!     PURPOSE.
!     --------

!**   INTERFACE.
!     ----------
!       *CALL* *SUAFN2*

!        EXPLICIT ARGUMENTS
!        --------------------
!           KFPCONF : configuration of the post-processing :
!                     0 : vertical interpolation only (<CFPFMT='MODEL'>)
!                     1 : gridpoint post-processing, possibly with spectral filters (<NFPOS=1>)
!                     2 : gridpoint/spectral post-processing (spectral outputs possible) (<NFPOS=2>)

!        IMPLICIT ARGUMENTS
!        --------------------
!        See #include below.

!     METHOD.
!     -------
!        See documentation about FULL-POS.

!     EXTERNALS.
!     ----------
!      No external.
!      Called by SUAFN.

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!        K. YESSAD and J. NICOLAU
!        after routine SUAFN of RYAD EL KHATIB *METEO-FRANCE*
!        ORIGINAL : 97-09-03

!     MODIFICATIONS.
!     --------------
!        R. El Khatib : 01-05-04 Duration of total precipitations, HUn, HUx
!        R. El Khatib : 01-08-04 Montgomery potential on theta surfaces only
!        R. El Khatib : 01-08-07 Pruning options
!        R. El Khatib : 02-21-20 Fpos B-level distribution + remove IO scheme
!        F. Vana      : 02-07-03 Virtual potential temperature
!        R. El Khatib : 02-09-04 Iso -10 Celsius
!        D. Dent      : 02-05-15 Extend extra field options
!        JJMorcrette  : 02-10-29 PAR, UVB, CAPE
!        R. El Khatib : 03-04-17 Fullpos improvemnts
!        M.Hamrud     : 03-10-01 CY28 Cleaning
!        F. Taillefer : 04-05-26 Add ozone and aerosols fields
!        Y.Bouteloup  : 04-03-26 Introduction of MTS radiance
!        G. Hello     : 05-01-25 Adding snow, rain,graupel, tke
!        R. Engelen   : 05-03-15 Greenhouse gases (ECMWF)
!        A. Untch     : 05-03-15 Aerosols (ECMWF)
!        J. Flemming  : 05-04-11 Aerosols replaced with reactive gases
!        R. El Ouaraini: 05-07-28 Adding fields for the monitoring of update frequency of the coupling files for Aladin
!        A. Alias     : 05-12-21 Add sulfate and volcano aerosols fields
!        M. Bellus    : 28-Sep-2006 Add prognostic convection fields (ALARO-0)
!        S. Serrar    : 05-06-23 CO2 surface fluxes added
!        S. Serrar    : 05-09-26 Add CO2 and SF6 total column
!        R. Engelen   : 02-Jun-06  CO2 replaced by generic GHG
!        JJMorcrette    20060625 MODIS albedo
!        JJMorcrette    20060715 Dust climatological fields
!        JJMorcrette    20060721 PP of clear-sky PAR and TOA incident solar radiation
!        JJMorcrette    20060807 PP of VIMD
!        JJMorcrette    20060925 DU, BC, OM, SO2, VOL, SOA climatological fields
!        G. Balsamo     20070115 Soil type
!        S. Serrar    : 22-03-2007 physics tendencies post-processable as GFL fields for ERA40
!        S. Serrar   20070717 methane variables made post-processable (GEMS)
!        P. Lopez    26-06-2009 Added 100m wind components
!        JJMorcrette 20090217 PP of aerosol and UV-processor outputs
!        P. Lopez    22-10-2008 Added ducting diagnostic fields 
!        JJMorcrette 20091201 Total and clear-sky direct SW radiation flux at surface 
!        H. Hersbach 04-Dec-2009 10-m neutral wind and friction velocity
!        S. Boussetta/G.Balsamo      May 2009   Added variable LAI field
!        Y. Bouteloup  : 01-05-2009 Add Total (radiative) cloud water and ice
!        K. Yessad (Aug 2009): name TFP%EXT for extra-GFL.
!        R. Forbes   01-Mar-2010 Added TCRW, TCSW diagnostics
!        JJMorcrette 20100212 PP of CBASE, 0DEGL and VISIH 
!        T. Wilhelmsson: 25-Mar-2010 Add 6 hourly min/max fields
!        T. Wilhelmsson: 20-Dec-2010 Add 3 hourly min/max fields
!        G.Balsamo/S.Boussetta: 17-Apr-2011 Add land carbon dioxide
!        Y. Bouteloup : 03-Oct-2013 Add LCONV, ICONV, RCONV and SCONV
!        P.Bechtold    : 09-Aug-2011 Add CIN, Convective Indices
!        M Ahlgrimm 31 Oct 2011 Clear-sky downward radiation at surface
!        A. Inness  23 Mar 2012 Add total column chemistry fields TCCHEM
!        JJMorcrette 20130213 PP optical depths GEMS/MACC aerosols
!        G. Balsamo 11-Jan-2014 Add lake model fields
!        R. Forbes  01-Mar-2014 Added precip rates/type, TCSLW,I10FG,PEV
!        R. El Khatib 15-Mar-2013 Enable CUF post-processing in NFPOS=2
!        JJMorcrette 20130730 15-variable aerosol model + oceanic DMS
!      R. El Khatib 17-Jul-2013 FABEC post-processing
!      R. El Khatib 09-Aug-2013 Bugfix
!        A. Agusti-Panareda: 3 Nov 2013 Add GPP/REC flux adjustment coefficients
!      R. El Khatib 04-Aug-2014 Pruning of the conf. 927/928
!      P.Marguinaud 01-Oct-2014 Setup of PREP fields to be interpolated
!      P.Marguinaud 10-Oct-2014 More fields
!      R. El Khatib 27-Nov-2014 Discriminate PHY/CFU/XFU by start/end index
!        R. Forbes  10-Jan-2015 Add freezing rain FZRA
!        S.Remy 28-Jan-2015 Add injection height for bb emissions
!        P. Lopez 16-Nov-2015 Added lightning density fields
!      A. Bozzo Jan 2016 Add surface shortwave direct beam
!        S.Remy 09-Mar-2016 Add aer SO2 dry dep velocity
!        S.Remy 21-Apr-2017 Add altitude of volcanoes
!        S. Rémy, 25/4/2017, add fraction of calcite over dust 1 and 2
!      R. El Khatib 17-Aug-2016 Cleaning
!        R. El Khatib 12-Mar-2018 total albedo
!      R. Brozkova Sep-2018 Added convective temperature, global normal
!                           irradiance and mean radiant temperature
!      R. El Khatib 15-Feb-2019 Bugfix : dissociate the configurations of fullpos for the pp levels to discard
!      R. El Khatib 23-Apr-2019 Restrict 'HTB' field to isothermic levels (though it could be generalized as "altitude")
!      P. Bechtold 01-01-2020 Add M10DEGL and more CAPE/CIN parameters
!      A.Agusti-Panareda : 23-06-2021 Add CO2 photosynthesis type (C3/C4)
!      R. Forbes    May-2022  Added precip-type most-frequent and most-severe
!     ------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE PARFPOS  , ONLY : JPOSSCVA, JPOSVX2, JPOSFSU, JPOSGHG, JPOSAERO, JPOSCHEM, &
 & JPOSCHEMFLX, JPOSERA40, JPOSNOGW, JPOSAEROUT, JPOSUVP, JPOSEZDIAG, &
 & JPOSAERAOT, JPOSAERLISI, JPOSAERO_WVL_DIAG, JPOSAERO_WVL_DIAG_TYPES, JPOSAERODIAG, &
 & JPOSEDRP, JPOSEMIS2D, JPOSEMIS2DAUX, JPOSEMIS3D
USE YOMAFN, ONLY : TAFN
USE YOMLUN   , ONLY : NULOUT
USE FULLPOS_MIX, ONLY : CTRL_TFP
USE TYPE_FPDSPHYS, ONLY : CTRL_GFP

!     ------------------------------------------------------------------

IMPLICIT NONE

LOGICAL         ,INTENT(IN)    :: LDNHDYN
TYPE (TAFN),  INTENT(INOUT)    :: YDAFN
INTEGER(KIND=JPIM), INTENT(IN) :: KFPCONF

CHARACTER(LEN=4) :: CL_FORBID_SURFACE_DEPENDENT_LEVELS
CHARACTER(LEN=3) :: CL_FORBID_SURFACE_FREE_LEVELS
CHARACTER(LEN=6) :: CL_LIMIT_TO_ETA_LEVELS
INTEGER(KIND=JPIM) :: I, JJ, IMAX, JDIAG
LOGICAL :: LLSF
REAL(KIND=JPRB) :: Z0
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "abor1.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUAFN2',0,ZHOOK_HANDLE)
ASSOCIATE(TFP=>YDAFN%TFP, TFP_DYNDS=>YDAFN%TFP_DYNDS, GFP=>YDAFN%GFP, GFP_PHYDS=>YDAFN%GFP_PHYDS, &
 & MSTARTGFP_PHY=>YDAFN%MSTARTGFP_PHY, MSTARTGFP_CFU=>YDAFN%MSTARTGFP_CFU, &
 & MSTARTGFP_XFU=>YDAFN%MSTARTGFP_XFU, MENDGFP_PHY=>YDAFN%MENDGFP_PHY, MENDGFP_CFU=>YDAFN%MENDGFP_CFU, &
 & MENDGFP_XFU=>YDAFN%MENDGFP_XFU,NSFXPRE_CNT=>YDAFN%NSFXPRE_CNT)
!     ------------------------------------------------------------------

!        1. Dynamics :

! TFP%*%CLNIL is used to remove some fields from the requests : 
!  - Remove trivial fields (X on X=constant level)
!  - Vertical divergence can be computed only on eta levels
!  - Remove wind-related fields that cannot be computed 
!    after horizontal interpolations (conf. 'Z', 'E' or 'L') because 
!    at that time horizontal derivatives are lost
!  - Remove true vertical velocity in the hydrostatic model if it should 
!    be computed after horizontal interpolations (conf. 'Z', 'E' or 'L') because
!    at that time horizontal derivatives are lost (in the NH model it works
!    because then the vertical divergence is a pronostic field)
!  - 2D fields should be split in 2 flows : 
!    * those which are surface-dependent (like surface pressure) 
!    cannot be computed within pressure, theta or Pv scans 
!    (conf. 'B', 'T', 'V') because these scans are so that vertical 
!    interpolations take place before the horizontal interpolations ; 
!    * those which are surface-independent (like MSL pressure) or which 
!    are defined with respect to the model (map factor, orography)
!    cannot be computed within height, eta, isothermic or flight levels scans
!    (conf. 'H', 'S', 'K' or 'F') because these scans are so that various model
!    facilities are lost (spectral fit, derivatives, geometry)
! Remark : in the following configurations, most things are possible :
!  'H' = pp. on height levels in the horizontal model geometry 
!  'S' = pp. on eta    levels in the horizontal model geometry 

CL_FORBID_SURFACE_DEPENDENT_LEVELS=' '
CL_FORBID_SURFACE_FREE_LEVELS=' '
IF (KFPCONF /= 0) THEN
  CL_FORBID_SURFACE_DEPENDENT_LEVELS='HSKF'
  CL_FORBID_SURFACE_FREE_LEVELS='BVT'
ENDIF
CL_LIMIT_TO_ETA_LEVELS='BVTHKF'

Z0=0.0_JPRB

LLSF=.TRUE.

IMAX=SIZE(TFP_DYNDS)
I=0

! Notice : the code is still dependent of the ordering of the following lines :
! - 2D fields should be set after 3D fields
! -U/V of the same pair should be set consecutively
! ... I don t understand completely why.
CALL CTRL_TFP(TFP%U,   I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%V,   I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%KHI, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%PSI, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%T,   I,'K     ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%Q,   I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%O3MX,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%CPF ,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SPF ,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%L,   I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%I,   I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%LRAD,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%IRAD,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%CLF, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SN,  I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%RR,  I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%GR,  I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%HL,  I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%TKE, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%PHYCTY, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%EFB1,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%EFB2,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%EFB3,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%Z,   I,'HF    ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%WND, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%HU,  I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%TH,  I,'T     ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%THPW,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%TPW, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%ETH, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%IET, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SRE, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SREDB, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%THV, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%P,   I,'B     ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%PD,  I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%VD,  I,CL_LIMIT_TO_ETA_LEVELS,LLSF,TFP_DYNDS,IMAX)

CALL CTRL_TFP(TFP%MG,  I,'BVSHKF',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%PTB, I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
! By definition the field below has been restricted to isothermic levels (though it could be generalized as "altitude" :
CALL CTRL_TFP(TFP%HTB, I,'BVTHSF',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%RHO, I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%QNH, I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
!
CALL CTRL_TFP(TFP%DAL,  I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%DOM,  I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%UAL,  I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%UOM,  I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%UEN,  I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%UNEBH,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%TTE  ,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MXL  ,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%LCONV,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%ICONV,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%RCONV,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SCONV,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SHTUR,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%FQTUR,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%FSTUR,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%RKTH ,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%RKTQV,I,'      ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%RKTQC,I,'      ',LLSF,TFP_DYNDS,IMAX)
!----------------------------------------------------------
DO JJ=1,JPOSEMIS3D
  CALL CTRL_TFP(TFP%EMIS3D(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSGHG
  CALL CTRL_TFP(TFP%GHG(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSEZDIAG
  CALL CTRL_TFP(TFP%EZDIAG(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSCHEM
  CALL CTRL_TFP(TFP%CHEM(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSAERO
  CALL CTRL_TFP(TFP%AERO(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
CALL CTRL_TFP(TFP%LRCH4,I,' ',LLSF,TFP_DYNDS,IMAX)
DO JJ=1,JPOSERA40
  CALL CTRL_TFP(TFP%ERA40(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSNOGW
  CALL CTRL_TFP(TFP%NOGW(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSEDRP
  CALL CTRL_TFP(TFP%EDRP(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSAERAOT
  CALL CTRL_TFP(TFP%AERAOT(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSAERLISI
  CALL CTRL_TFP(TFP%AERLISI(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSAEROUT
  CALL CTRL_TFP(TFP%AEROUT(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSUVP
  CALL CTRL_TFP(TFP%UVP(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSSCVA
  CALL CTRL_TFP(TFP%EXT(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
DO JJ=1,JPOSVX2
  CALL CTRL_TFP(TFP%FUA(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
CALL CTRL_TFP(TFP%EDR, I,'   ',LLSF,TFP_DYNDS,IMAX)
IF (LDNHDYN) THEN
  CALL CTRL_TFP(TFP%VW,  I, '   ' ,LLSF,TFP_DYNDS,IMAX)
  CALL CTRL_TFP(TFP%WWS, I, CL_FORBID_SURFACE_FREE_LEVELS ,LLSF,TFP_DYNDS,IMAX)
ELSE
  CALL CTRL_TFP(TFP%VW,  I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
  CALL CTRL_TFP(TFP%WWS, I, 'BVTHSKF' ,LLSF,TFP_DYNDS,IMAX)
ENDIF
CALL CTRL_TFP(TFP%PV,  I,'VHKF',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%VV,  I,'    ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%ETAD,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%STD, I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SHD, I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%ABS, I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%VOR, I,'   ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%DIV, I,'   ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SP,  I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%LNSP,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SPNH,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSL, I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSLNH,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%CUF1,I,'   ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%CUF2,I,'   ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%CUF3,I,'   ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%CUF4,I,'   ',LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%CUF5,I,'   ',LLSF,TFP_DYNDS,IMAX)
IF (KFPCONF==1) THEN
! specsurfgeopotential is either the gp-interpolated or the spectral model orography
  CALL CTRL_TFP(TFP%FIS, I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
ELSE
! specsurfgeopotential is the output (usually spectral) orography
  CALL CTRL_TFP(TFP%FIS, I,' ',LLSF,TFP_DYNDS,IMAX)
ENDIF

CALL CTRL_TFP(TFP%PJET,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%TCAO,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%PCAO,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%HTPW,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%HTPW1,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%HTPW2,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%GM,  I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%FOL, I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%UCLS,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%VCLS,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%TCLS,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%QCLS,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%RCLS,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%FCLS,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSK, I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%TX  ,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%TN  ,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%HUX ,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%HUN ,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SREX,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SREDBX,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%TOPR,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%CAPE,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)

CALL CTRL_TFP(TFP%SRH, I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%STRMMU, I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%STRMMV, I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)

CALL CTRL_TFP(TFP%CIEN,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%TCVS,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MOCO,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%TWV, I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%UGST,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%VGST,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%FGST,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%HCLP,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%VEIN,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%SMC ,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%ASMC,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%VSMC,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT7C1,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT7C2,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT8C1,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT8C2,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT8C3,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT8C4,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT8C5,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT8C6,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT8C7,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT8C8,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT9C1,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT9C2,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT9C3,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT9C4,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT9C5,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT9C6,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT9C7,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MSAT9C8,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%GOES11C1,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%GOES11C2,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%GOES11C3,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%GOES11C4,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%GOES12C1,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%GOES12C2,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%GOES12C3,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%GOES12C4,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MTSAT1C1,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MTSAT1C2,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MTSAT1C3,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%MTSAT1C4,I,CL_FORBID_SURFACE_DEPENDENT_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%LCL,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%FCL,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%EL,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
DO JJ=1,JPOSFSU
  CALL CTRL_TFP(TFP%FSU(JJ),I,' ',LLSF,TFP_DYNDS,IMAX)
ENDDO
CALL CTRL_TFP(TFP%UJET,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)
CALL CTRL_TFP(TFP%VJET,I,CL_FORBID_SURFACE_FREE_LEVELS,LLSF,TFP_DYNDS,IMAX)

IF (I < 1) THEN
  CALL ABOR1('SUAFN2 : INTERNAL ERROR I<1')
ELSEIF (I > IMAX) THEN
  WRITE(UNIT=NULOUT,FMT='('' I= '',I4,'' IMAX= '',I4)') I, IMAX
  CALL ABOR1('SUAFN2 : TFP_DYNDS TOO SMALL !')
ELSE
  DO WHILE (I < IMAX)
    CALL CTRL_TFP(TFP_DYNDS(I+1),I,' ',LLSF,TFP_DYNDS,IMAX)
  ENDDO
ENDIF

!     ------------------------------------------------------------------

!        3. Physical fields, cumulated fluxes, instantaneous fluxes/diagnostics

IMAX=SIZE(GFP_PHYDS)
I=0

! Physical fields :
MSTARTGFP_PHY=I+1
CALL CTRL_GFP(I,IMAX,GFP%SDFOR,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CGPP,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CREC,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC10FG ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC10FG3,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC10FG6,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%I10FG,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC10U  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC10V  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC10SI ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC100U ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC100V ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC100SI,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC200U ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC200V ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC200SI,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ZUST ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC10NU ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC10NV ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC2D   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC2SH  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC2T   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ACOT ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%AL   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALB  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALS  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALSN ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALUVP,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALUVD,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALNIP,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALNID,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALUVI,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALUVV,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALUVG,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALNII,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALNIV,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALNIG,GFP_PHYDS)

CALL CTRL_GFP(I,IMAX,GFP%AERDEP,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%AERLTS,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%AERSCC,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%DSF  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%DSZ  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SO2DD ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%DMSO ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%URBF ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%FCA1 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%FCA2 ,GFP_PHYDS)

CALL CTRL_GFP(I,IMAX,GFP%ODSS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ODDU ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ODOM ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ODBC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ODSU ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ODNI ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ODAM ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ODSOA,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ODVFA,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ODVSU,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ODTOACC,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%AEPM1 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%AEPM25,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%AEPM10,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%UVBED,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%UVBEDCS,GFP_PHYDS)

CALL CTRL_GFP(I,IMAX,GFP%ALV  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ANOR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ARG  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ASN  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%BAAL ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALBHIS,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%BLD  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%BLH  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%BSR  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%BV   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CBASE,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CCC  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CDSW ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CHAR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CI   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CP   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CRR  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSFR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSF  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSSW ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CVH  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CVL  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CUR  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CO2TYP,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%FWET ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LAIL ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LAIH ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%D2   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%D2MX ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%DPAT ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%DST  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%DSW  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%E    ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EMIS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ES   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EWSS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%FDSW ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%FSSW ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%FZRA ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%GFIS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%GWD  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%HCC  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%HV   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%IC   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%IDZ0 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%IE   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%IEWSS,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%INCHN,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%INCHX,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%INCTN,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%INCTX,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%INSSS,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ISOR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ISSHF,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ISTL1,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ISTL2,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ISTL3,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ISTL4,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ITZ0 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%IVEG ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LAI  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LAN  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LCC  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LGWS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LSRR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TPR  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LSSFR,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LSF  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LSM  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LSP  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LSPF ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ILSPF,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LSRH ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LZ0H ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MCC  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MGWS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MN2T ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MN2T3,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MN2T6,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MNTPR,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MNTPR3,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MNTPR6,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MSLD ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SP   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MX2T ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MX2T3,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MX2T6,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MXTPR,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MXTPR3,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MXTPR6,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%NSSS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PADOU,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PADOV,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PCAAG,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PCAPG,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PEV  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PSRHU,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PTYPE,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PURB ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PVGMX,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%RDST ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%RDSW ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%RO   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SRO  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SSRO ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%NEE  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%GPP  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%REC  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%INEE ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%IGPP ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%IREC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ICH4 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%RSMIN,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SAB  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SDOG ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SF   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SFIS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SKT  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SLHF ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SLOR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SMLT ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SNDE ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SOTY ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CLK  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%DL   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LMLT ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LMLD ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LBLT ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LTLT ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LSHF ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LICT ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LICD ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SR   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SRC  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SSHF ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SSR  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SSRC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SSRD ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SSRDC,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SST  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SSW  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ST   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%UCUR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%VCUR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%STL1 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%STL2 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%STL3 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%STL4 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%STR  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%STRC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%STRD ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%STRDC,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SUND ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SWL1 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SWL2 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SWL3 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SWL4 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TCC  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TCO3 ,GFP_PHYDS)

CALL CTRL_GFP(I,IMAX,GFP%SD   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SDSL ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TSN  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%RSN  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%WSN  ,GFP_PHYDS)

DO JJ=1,JPOSGHG
  CALL CTRL_GFP(I,IMAX,GFP%TCGHG(JJ) ,GFP_PHYDS)
ENDDO
DO JJ=1,JPOSCHEM
  CALL CTRL_GFP(I,IMAX,GFP%TCCHEM(JJ) ,GFP_PHYDS)
ENDDO
DO JJ=1,JPOSCHEMFLX
  CALL CTRL_GFP(I,IMAX,GFP%CHEMFLXO(JJ) ,GFP_PHYDS)
ENDDO
DO JJ=1,JPOSCHEMFLX
  CALL CTRL_GFP(I,IMAX,GFP%CHEMWDFLX(JJ) ,GFP_PHYDS)
ENDDO
DO JJ=1,JPOSCHEMFLX
  CALL CTRL_GFP(I,IMAX,GFP%CHEMDDFLX(JJ) ,GFP_PHYDS)
ENDDO
DO JDIAG=1,JPOSAERODIAG
  DO JJ=1,JPOSAERO
    CALL CTRL_GFP(I,IMAX,GFP%AERODIAG(JJ,JDIAG) ,GFP_PHYDS)
  ENDDO
ENDDO
DO JDIAG=1,JPOSAERO_WVL_DIAG_TYPES
  DO JJ=1,JPOSAERO_WVL_DIAG
    CALL CTRL_GFP(I,IMAX,GFP%AERO_WVL_DIAG(JJ,JDIAG) ,GFP_PHYDS)
  ENDDO
ENDDO
DO JJ=1,JPOSEMIS2D
  CALL CTRL_GFP(I,IMAX,GFP%EMIS2D(JJ) ,GFP_PHYDS)
ENDDO
DO JJ=1,JPOSEMIS2DAUX
  CALL CTRL_GFP(I,IMAX,GFP%EMIS2DAUX(JJ) ,GFP_PHYDS)
ENDDO

CALL CTRL_GFP(I,IMAX,GFP%TCW  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TCWV ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TCLW ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TCIW ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TCRW ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TCSW ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TCSLW,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TP   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%VIWVE,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%VIWVN,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TSR  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TSRC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TTR  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TTRC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TVH  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TVL  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%VEG  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%VIMD ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%VISIH,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%Z0F  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%Z0H  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%Z0V  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC0DEGL,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ECM10DEGL,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CIN  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MLCIN50,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MLCIN100,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%KINDEX ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TTINDEX,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CBASEA,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTOPC,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ZTWETB0,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ZTWETB1,GFP_PHYDS)

CALL CTRL_GFP(I,IMAX,GFP%ASEA ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ALAN ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ASOO ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ADES ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ASUL ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%AVOL ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%O3A  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%O3B  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%O3C  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SPAR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SUVB ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CAPE ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MUCAPE,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MLCAPE50,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MLCAPE100,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PDEPL,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CAPES,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SPARC,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%STINC,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MXCAP6,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MXCAPS6,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TROPOTP,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SFDIR,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SCDIR,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%DNDZN,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%DNDZA,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%DCTB ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TPLB ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TPLT ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LITOTI ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LITOTA1,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LITOTA3,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LITOTA6,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LICGI  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LICGA1 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LICGA3 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%LICGA6 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PTYPEMODE1,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PTYPEMODE3,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PTYPEMODE6,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PTYPESEVR1,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PTYPESEVR3,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%PTYPESEVR6,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SDSRP,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CLBT ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSBT ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ICTH ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SSH  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%EC20D,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MLD  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SSS  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%TEM3 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%SAL3 ,GFP_PHYDS)

DO JJ=1,NSFXPRE_CNT
  CALL CTRL_GFP(I,IMAX,GFP%SFXPRE(JJ),GFP_PHYDS)
ENDDO

DO JJ=1,JPOSVX2
  CALL CTRL_GFP(I,IMAX,GFP%VX2(JJ),GFP_PHYDS)
ENDDO
DO JJ=1,JPOSFSU
  CALL CTRL_GFP(I,IMAX,GFP%FSU(JJ),GFP_PHYDS)
ENDDO

MENDGFP_PHY=I

! Cumulated fluxes :
MSTARTGFP_CFU=I+1
CALL CTRL_GFP(I,IMAX,GFP%CLSP ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CCP  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CLSS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CLSG ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CLSH ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CCSF ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CCSG ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CCSH ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CUSS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CVSS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSSH ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSLH ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTSP ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTCC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CBLD ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSSR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSTR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTSR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTTR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CCCC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CHCC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CMCC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CLCC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CUGW ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CVGW ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CUTO ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CVTO ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CE   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CS   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CT   ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CLHE ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CLHS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CLHT ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CWS  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSNS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CQTO ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTO3 ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTME ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CICE ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CLI  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CCVU ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CCVV ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CCVQ ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CCVS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTUQ ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTUS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSOC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTHC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSOP ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CDNI ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CGNI ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTOP ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSOD ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTHD ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CFON ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CCHS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CEAS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSRU ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CDRU ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CIRU ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CETP ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTP  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CSMR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTSOC,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CTTHC,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CDUTP,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%CFLASH,GFP_PHYDS)
MENDGFP_CFU=I

! Instantaneous fluxes :
MSTARTGFP_XFU=I+1
CALL CTRL_GFP(I,IMAX,GFP%XTCC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%X10U ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%X10V ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%X10NU,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%X10NV,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%X2T  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%X2TPW,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%X2SH ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%X2RH ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCCC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XHCC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XMCC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XLCC ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XX2T ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XN2T ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCVU ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCVV ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCVQ ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCVS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XTUU ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XTUV ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XTUQ ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XTUS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XGDU ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XGDV ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XLSP ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCP  ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XLSS ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XLSG ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XLSH ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCSF ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCSG ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCSH ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XSSR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XSTR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XTSR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XTTR ,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%X10FF,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCAPE,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCTOP,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XMOCO,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XCLPH,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XVEIN,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XGUST,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XUGST,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XVGST,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XX2HU,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XN2HU,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XUGST2,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XVGST2,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XTHW,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XXDIAGH,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%ACCGREL,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XMRT,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%VISICLD,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%VISIHYD,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MXCLWC,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%VISICLD2,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%VISIHYD2,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%MXCLWC2,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XPTYPE,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XPTYPESEV,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XPTYPE2,GFP_PHYDS)
CALL CTRL_GFP(I,IMAX,GFP%XPTYPESEV2,GFP_PHYDS)
MENDGFP_XFU=I


IF (I < 1) THEN
  CALL ABOR1('SUAFN2 : INTERNAL ERROR I<1')
ELSEIF (I > IMAX) THEN
  WRITE(UNIT=NULOUT,FMT='('' I= '',I4,'' IMAX= '',I4)') I, IMAX
  CALL ABOR1('SUAFN2 : GFP_PHYDS TOO SMALL !')
ELSE
  DO WHILE (I < IMAX)
    CALL CTRL_GFP(I,IMAX,GFP_PHYDS(I+1),GFP_PHYDS)
  ENDDO
ENDIF

!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUAFN2',1,ZHOOK_HANDLE)
END SUBROUTINE SUAFN2
