! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUALMP1(YDGEOMETRY)

!**** *SUALMP1 * - Routine to allocate space for some distributed memory arrays

!     Purpose.
!     --------
!           Allocate space for most of the distributed memory control arrays

!**   Interface.
!     ----------
!        *CALL* *SUALMP1*

!     Explicit arguments :  None
!     --------------------

!     Implicit arguments :
!     --------------------

!     Method.
!     -------
!     Externals.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      MPP Group *ECMWF*
!      Original : 95-10-01

!     Modifications.
!     --------------
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      T. Wilhelmsson and K. Yessad (Oct 2013) Geometry and setup refactoring.
!      K. Yessad (July 2014): Move some variables.
!     ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCT0   , ONLY : LALLOPR
USE YOMMP0   , ONLY : NPRINTLEV, NPRTRW, NPRTRNS, NPRTRV, N_REGIONS_NS, N_REGIONS_EW
USE YOMLUN   , ONLY : NULOUT

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
INTEGER(KIND=JPIM) :: ISMAX, IU, JSMAX
LOGICAL :: LLP
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
#ifdef __INTEL_COMPILER
INTRINSIC :: SHAPE ! Fails with Intel compiler as it thinks we use ATLAS shape function
#endif


!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUALMP1',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP)
ASSOCIATE(NFLEVG=>YDDIMV%NFLEVG, &
 & NCMAX=>YDDIM%NCMAX, NDGENG=>YDDIM%NDGENG, NDGLG=>YDDIM%NDGLG, &
 & NDGSAG=>YDDIM%NDGSAG, NSMAX=>YDDIM%NSMAX, NMSMAX=>YDDIM%NMSMAX)
!     ------------------------------------------------------------------

LLP = NPRINTLEV >= 1.OR. LALLOPR
IU = NULOUT
ALLOCATE(YDMP%NUMLL(NPRTRV+1))
IF(LLP)WRITE(IU,9) 'NUMLL    ',SIZE(YDMP%NUMLL    ),SHAPE(YDMP%NUMLL    )
ALLOCATE(YDMP%NPSURF(NPRTRV))
IF(LLP)WRITE(IU,9) 'NPSURF   ',SIZE(YDMP%NPSURF   ),SHAPE(YDMP%NPSURF   )
ALLOCATE(YDMP%NUMPP(NPRTRW))
IF(LLP)WRITE(IU,9) 'NUMPP    ',SIZE(YDMP%NUMPP    ),SHAPE(YDMP%NUMPP    )
ALLOCATE(YDMP%NPROCM(0:NCMAX))
IF(LLP)WRITE(IU,9) 'NPROCM   ',SIZE(YDMP%NPROCM   ),SHAPE(YDMP%NPROCM   )
ALLOCATE(YDMP%NPTRMS(NPRTRW))
IF(LLP)WRITE(IU,9) 'NPTRMS   ',SIZE(YDMP%NPTRMS   ),SHAPE(YDMP%NPTRMS   )
ALLOCATE(YDMP%NPOSSP(NPRTRW+1))
IF(LLP)WRITE(IU,9) 'NPOSSP   ',SIZE(YDMP%NPOSSP   ),SHAPE(YDMP%NPOSSP   )
ISMAX=MAX(NSMAX,NMSMAX)
ALLOCATE(YDMP%NALLMS(ISMAX+1))
IF(LLP)WRITE(IU,9) 'NALLMS   ',SIZE(YDMP%NALLMS   ),SHAPE(YDMP%NALLMS   )
ALLOCATE(YDMP%NDIM0G(0:ISMAX))
IF(LLP)WRITE(IU,9) 'NDIM0G   ',SIZE(YDMP%NDIM0G   ),SHAPE(YDMP%NDIM0G   )

ALLOCATE(YDMP%NPTRLS(NPRTRNS))
IF(LLP)WRITE(IU,9) 'NPTRLS   ',SIZE(YDMP%NPTRLS   ),SHAPE(YDMP%NPTRLS   )
ALLOCATE(YDMP%NPTRSV(NPRTRV+1))
IF(LLP)WRITE(IU,9) 'NPTRSV   ',SIZE(YDMP%NPTRSV   ),SHAPE(YDMP%NPTRSV   )
ALLOCATE(YDMP%NPTRSVF(NPRTRV+1))
IF(LLP)WRITE(IU,9) 'NPTRSVF  ',SIZE(YDMP%NPTRSVF  ),SHAPE(YDMP%NPTRSVF  )
ALLOCATE(YDMP%NPTRMF(NPRTRV+1))
IF(LLP)WRITE(IU,9) 'NPTRMF   ',SIZE(YDMP%NPTRMF   ),SHAPE(YDMP%NPTRMF   )
JSMAX=MAX(NSMAX,NMSMAX)
ALLOCATE(YDMP%NSPSTAF(0:JSMAX))
IF(LLP)WRITE(IU,9) 'NSPSTAF  ',SIZE(YDMP%NSPSTAF  ),SHAPE(YDMP%NSPSTAF  )
ALLOCATE(YDMP%NPTRLL(NPRTRV+1))
IF(LLP)WRITE(IU,9) 'NPTRLL   ',SIZE(YDMP%NPTRLL   ),SHAPE(YDMP%NPTRLL   )
ALLOCATE(YDMP%NSTA(NDGSAG:NDGENG+N_REGIONS_NS-1,N_REGIONS_EW))
IF(LLP)WRITE(IU,9) 'NSTA     ',SIZE(YDMP%NSTA     ),SHAPE(YDMP%NSTA     )
ALLOCATE(YDMP%NONL(NDGSAG:NDGENG+N_REGIONS_NS-1,N_REGIONS_EW))
IF(LLP)WRITE(IU,9) 'NONL     ',SIZE(YDMP%NONL     ),SHAPE(YDMP%NONL     )
ALLOCATE(YDMP%NPTRFRSTLAT(N_REGIONS_NS))
IF(LLP)WRITE(IU,9) 'NPTRFRSTLAT',SIZE(YDMP%NPTRFRSTLAT),SHAPE(YDMP%NPTRFRSTLAT)
ALLOCATE(YDMP%NPTRLSTLAT(N_REGIONS_NS))
IF(LLP)WRITE(IU,9)'NPTRLSTLAT',SIZE(YDMP%NPTRLSTLAT),SHAPE(YDMP%NPTRLSTLAT)
ALLOCATE(YDMP%NPTRLAT(NDGLG))
IF(LLP)WRITE(IU,9) 'NPTRLAT  ',SIZE(YDMP%NPTRLAT  ),SHAPE(YDMP%NPTRLAT  )
ALLOCATE(YDMP%LSPLITLAT(NDGLG))
IF(LLP)WRITE(IU,9) 'LSPLITLAT',SIZE(YDMP%LSPLITLAT),SHAPE(YDMP%LSPLITLAT)
ALLOCATE(YDMP%NFRSTLAT(N_REGIONS_NS))
IF(LLP)WRITE(IU,9) 'NFRSTLAT ',SIZE(YDMP%NFRSTLAT ),SHAPE(YDMP%NFRSTLAT )
ALLOCATE(YDMP%NLSTLAT(N_REGIONS_NS))
IF(LLP)WRITE(IU,9) 'NLSTLAT  ',SIZE(YDMP%NLSTLAT  ),SHAPE(YDMP%NLSTLAT  )
ALLOCATE(YDMP%NBSETLEV(NFLEVG))
IF(LLP)WRITE(IU,9) 'NBSETLEV ',SIZE(YDMP%NBSETLEV ),SHAPE(YDMP%NBSETLEV )
ALLOCATE(YDDIM%NDLUNL(NDGSAG:NDGENG+N_REGIONS_NS-1,N_REGIONS_EW))
IF(LLP)WRITE(IU,9) 'NDLUNL   ',SIZE(YDDIM%NDLUNL   ),SHAPE(YDDIM%NDLUNL   )
ALLOCATE(YDDIM%NDLUXL(NDGSAG:NDGENG+N_REGIONS_NS-1,N_REGIONS_EW))
IF(LLP)WRITE(IU,9) 'NDLUXL   ',SIZE(YDDIM%NDLUXL   ),SHAPE(YDDIM%NDLUXL   )
ALLOCATE(YDGEM%NGPTOTL(N_REGIONS_NS,N_REGIONS_EW))
IF(LLP)WRITE(IU,9) 'NGPTOTL  ',SIZE(YDGEM%NGPTOTL  ),SHAPE(YDGEM%NGPTOTL  )
!     ------------------------------------------------------------------
9 FORMAT(1X,'ARRAY ',A10,' ALLOCATED ',8I8)

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUALMP1',1,ZHOOK_HANDLE)
END SUBROUTINE SUALMP1
