! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUCFU(YDGEOMETRY,YDCFU,YDRIP,YDERAD,YDPHY,KULOUT)

!**** *SUCFU  * - ROUTINE TO INITIALIZE THE CONTROL OF CUMULATED FLUXES

!     PURPOSE.
!     --------
!        SET DEFAULT VALUES, THEN READS NAMELIST NAMCFU AND
!        INITIALIZE POINTERS

!**   INTERFACE.
!     ----------
!        *CALL* *SUCFU(...)*

!     EXPLICIT ARGUMENTS :  KULOUT
!     --------------------

!     IMPLICIT ARGUMENTS :
!     --------------------
!        COMMON  YOMCFU

!     METHOD.
!     -------
!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF RESEARCH DEPARTMENT DOCUMENTATION OF THE IFS

!     AUTHOR.
!     -------
!      MATS HAMRUD AND PHILIPPE COURTIER  *ECMWF*
!      ORIGINAL : 91-05-23

!     MODIFICATIONS.
!     --------------
!      Modified: 01-08-07 by R. El Khatib - pruning options
!      R. El Khatib : 03-04-17 Fullpos improvemnts
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      Modified: 04-09-15 by F.Bouyssel - LCUMFU forced to false if LMPHYS=F
!      Y.Seity      15-Jan-2007 add Graupel and Hail in CFU 
!      R. El Khatib : 10-Aug-2011 NIOLEVG management
!      R. El Khatib : 01-Mar-2012 LFPOS => NFPOS
!      T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!      R. Brozkova  : 09-2018 Added global normal irradiance
!      Y. Seity     : 10-2019 Bf for AROME fullpos offline linked with LGWD 
!-----------------------------------------------------------------------

USE YOMCFU      , ONLY : TCFU, JPFUST
USE YOMRIP      , ONLY : TRIP
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE PARKIND1    , ONLY : JPIM     ,JPRB
USE YOMHOOK     , ONLY : LHOOK    ,DR_HOOK, JPHOOK
USE YOMLUN      , ONLY : NULNAM
USE YOMPHY      , ONLY : TPHY
USE YOERAD      , ONLY : TERAD
USE YOMCT0      , ONLY : LECMWF    ,NFPOS
USE YOMFA       , ONLY : YFA_CBLD ,YFA_CCCC ,YFA_CCHS ,YFA_CWS  ,YFA_CVSS ,&
 &                       YFA_CCSG ,YFA_CLSG ,YFA_CCSH,YFA_CLSH ,YFA_CCP  ,YFA_CCSF ,&
 &                       YFA_CCVQ ,YFA_CCVS ,&
 &                       YFA_CCVU ,YFA_CCVV ,YFA_CDRU ,YFA_CE   ,YFA_CEAS ,YFA_CETP ,&
 &                       YFA_CFON ,YFA_CHCC ,YFA_CICE ,YFA_CIRU ,YFA_CLCC ,YFA_CLHE ,&
 &                       YFA_CLHS ,YFA_CLI  ,YFA_CLSP ,YFA_CLSS ,YFA_CMCC ,YFA_CQTO ,&
 &                       YFA_CS   ,YFA_CDUTP,YFA_CSLH ,YFA_CSMR ,YFA_CSNS ,YFA_CSOC ,&
 &                       YFA_CSOD ,YFA_CSOP ,YFA_CSRU ,YFA_CSSH ,YFA_CSSR ,YFA_CSTR ,&
 &                       YFA_CTCC ,YFA_CTHC ,YFA_CTHD ,YFA_CTME ,YFA_CTO3 ,YFA_CTOP ,&
 &                       YFA_CTP  ,YFA_CTSP ,YFA_CTUQ ,YFA_CTUS ,YFA_CUGW ,YFA_CUSS ,&
 &                       YFA_CVGW ,YFA_CDNI ,YFA_CGNI ,YFA_CFLASH
  
IMPLICIT NONE

TYPE(GEOMETRY)    , INTENT(INOUT) :: YDGEOMETRY
TYPE(TCFU),TARGET , INTENT(INOUT) :: YDCFU
TYPE(TRIP)        , INTENT(INOUT) :: YDRIP
TYPE(TERAD)       , INTENT(INOUT) :: YDERAD
TYPE(TPHY)        , INTENT(INOUT) :: YDPHY
INTEGER(KIND=JPIM), INTENT(IN)    :: KULOUT 

INTEGER(KIND=JPIM), PARAMETER :: JPKIND=6
INTEGER(KIND=JPIM) :: IP, J, IPAR, IK, INF550, INF850, JF, JL, IADD
INTEGER(KIND=JPIM) :: INLEV(YDGEOMETRY%YRDIMV%NFLEVG+1,JPKIND), ILEV(JPKIND)

CHARACTER(LEN=4) ::  CLPRE(YDGEOMETRY%YRDIMV%NFLEVG+1,JPKIND), CLEVS(1)
CHARACTER(LEN=16) ::  CLSU
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "posnam.intfb.h"
#include "seapre.intfb.h"
#include "sufpcfu.intfb.h"

LOGICAL, POINTER :: LCUMFU, LSTRD, LSTRC, LSTRT, LFPLC, LFPLCG, LFPLCH, LFPLS,&
 & LFPLSG, LFPLSH, LFR, LAMIP, LFRRC, LRAYS, LNEBTT, LFSF, LFSOIL, LNEBPAR,&
 & LTSTRD, LTSTRC, LTSTRT, LTFPLC, LTFPLS, LTFR, LTNEB, LFDUTP, LMOON, LRAYD,&
 & LFLASH
INTEGER(KIND=JPIM), POINTER :: NFRCFU, NCFUTS(:)
INTEGER(KIND=JPIM), POINTER :: NMTFLASH
REAL(KIND=JPRB), POINTER :: CALFLASH1, CALFLASH2

#include "namcfu.nam.h"
!      ----------------------------------------------------------------

!*       1.    SET DEFAULT VALUES.
!              -------------------

!        1.1 Set implicit default values

IF (LHOOK) CALL DR_HOOK('SUCFU',0,ZHOOK_HANDLE)
ASSOCIATE(YDGEM=>YDGEOMETRY%YRGEM, YDSTA=>YDGEOMETRY%YRSTA,&
 & YDDIMV=>YDGEOMETRY%YRDIMV)
ASSOCIATE(NRADFR=>YDERAD%NRADFR, &
 & LREACFU=>YDCFU%LREACFU, NFDCFU=>YDCFU%NFDCFU, &
 & NFRRC=>YDCFU%NFRRC,  NTYPCFU=>YDCFU%NTYPCFU, &
 & TYPE_CFU=>YDCFU%TYPE_CFU, & 
 & NFLEVG=>YDDIMV%NFLEVG, NIOLEVG=>YDDIMV%NIOLEVG, &
 & STPRE=>YDSTA%STPRE, LCONDWT=>YDPHY%LCONDWT, &
 & LFGEL=>YDPHY%LFGEL, LMPHYS=>YDPHY%LMPHYS, &
 & LNEIGE=>YDPHY%LNEIGE, LOZONE=>YDPHY%LOZONE,&
 & LRAYFM15=>YDPHY%LRAYFM15, LSOLV=>YDPHY%LSOLV,&
 & LGWD=>YDPHY%LGWD)
 
! Associate pointers for variables in namelist
LCUMFU  => YDCFU%LCUMFU
LSTRD   => YDCFU%LSTRD
LSTRC   => YDCFU%LSTRC
LSTRT   => YDCFU%LSTRT
LFPLC   => YDCFU%LFPLC
LFPLCG  => YDCFU%LFPLCG
LFPLCH  => YDCFU%LFPLCH
LFPLS   => YDCFU%LFPLS
LFPLSG  => YDCFU%LFPLSG
LFPLSH  => YDCFU%LFPLSH
LFR     => YDCFU%LFR
LAMIP   => YDCFU%LAMIP
LFRRC   => YDCFU%LFRRC
LRAYS   => YDCFU%LRAYS
LNEBTT  => YDCFU%LNEBTT
LFSF    => YDCFU%LFSF
LFSOIL  => YDCFU%LFSOIL
LNEBPAR => YDCFU%LNEBPAR
LTSTRD  => YDCFU%LTSTRD
LTSTRC  => YDCFU%LTSTRC
LTSTRT  => YDCFU%LTSTRT
LTFPLC  => YDCFU%LTFPLC
LTFPLS  => YDCFU%LTFPLS
LTFR    => YDCFU%LTFR
LTNEB   => YDCFU%LTNEB
NFRCFU  => YDCFU%NFRCFU 
NCFUTS  => YDCFU%NCFUTS
LFDUTP  => YDCFU%LFDUTP
LMOON   => YDCFU%LMOON
LRAYD   => YDCFU%LRAYD
LFLASH  => YDCFU%LFLASH
NMTFLASH=>YDCFU%NMTFLASH
CALFLASH1=>YDCFU%CALFLASH1
CALFLASH2=>YDCFU%CALFLASH2

LCUMFU = .FALSE.
LREACFU= .FALSE.
LSTRD  = .FALSE.
LTSTRD = .FALSE.
LSTRC  = .FALSE.
LTSTRC = .FALSE.
LSTRT  = .FALSE.
LTSTRT = .FALSE.
LFPLC  = .FALSE.
LFPLCG  = .FALSE.
LFPLCH  = .FALSE.
LTFPLC = .FALSE.
LFPLS  = .FALSE.
LFPLSG = .FALSE.
LFPLSH = .FALSE.
LTFPLS = .FALSE.
LFR    = .FALSE.
LTFR   = .FALSE.
LTNEB  = .FALSE.
LNEBTT = .FALSE.
LNEBPAR= .FALSE.
LFSF   = .FALSE.
LAMIP  = .FALSE.
LRAYS  = .FALSE.
LRAYD  = .FALSE.
LMOON  = .FALSE.
LFSOIL = .FALSE.
LFDUTP = .FALSE.
LFRRC  = .FALSE.
LFLASH = .FALSE.
DO J=0,JPFUST
  NCFUTS(J)=0
ENDDO
NFRCFU   =20

NMTFLASH=1
CALFLASH1=1.0_JPRB
CALFLASH2=1.0_JPRB


!        1.2 Modify default values according to LECMWF

IF (LECMWF) THEN
ELSE
  NFRCFU=9999999
  NCFUTS(0)=1
  NCFUTS(1)=1
ENDIF

!      ----------------------------------------------------------------

!*       2.    MODIFIES DEFAULT VALUES.
!              ------------------------

CALL POSNAM(NULNAM,'NAMCFU')
READ(NULNAM,NAMCFU)

IF (NFPOS /= 0) THEN
  CALL SUFPCFU(YDCFU,YDRIP,YDPHY)
ENDIF
IF (LCUMFU .AND. .NOT.LMPHYS) THEN
  LCUMFU=.FALSE.
ENDIF

LSTRD  =LSTRD  .AND.LCUMFU
LSTRC  =LSTRC  .AND.LCUMFU
LSTRT  =LSTRT  .AND.LCUMFU
LFPLC  =LFPLC  .AND.LCUMFU
LFPLS  =LFPLS  .AND.LCUMFU
LFR    =LFR    .AND.LCUMFU
LTNEB  =LTNEB  .AND.LCUMFU
LNEBTT =LNEBTT .AND.LCUMFU
LNEBPAR=LNEBPAR.AND.LCUMFU
LFSF   =LFSF   .AND.LCUMFU
LFSOIL =LFSOIL .AND.LCUMFU
LFRRC  =LFRRC  .AND.LCUMFU
LAMIP  =LAMIP  .AND.LCUMFU
LFDUTP =LFDUTP .AND.LCUMFU
LMOON  =LMOON  .AND.LCUMFU
LRAYD  =LRAYD  .AND.LCUMFU
LFLASH =LFLASH .AND.LCUMFU

IF (LFRRC) THEN
  NFRRC=NRADFR
ELSE
  NFRRC=0
ENDIF
!      ----------------------------------------------------------------

!*       3.    INITIALIZE DESCRIPTORS
!              ----------------------

!        3.1 Preinitialize the vertical levels and prefixes for *FA* files

CLEVS(1) ='S   '

! On each half level :
IK=1
ILEV(IK)=NFLEVG+1
DO J=1,ILEV(IK)
  CLPRE(J,IK)=CLEVS(1)
  INLEV(J,IK)=J-1+NIOLEVG-NFLEVG
ENDDO
! At the surface
IK=2
ILEV(IK)=1
CLPRE(1,IK)='SURF'
INLEV(1,IK)=NIOLEVG
! On each full level :
IK=3
ILEV(IK)=NFLEVG
DO J=1,ILEV(IK)
  CLPRE(J,IK)=CLEVS(1)
  INLEV(J,IK)=J+NIOLEVG-NFLEVG
ENDDO
! At the top and the surface :
IK=4
ILEV(IK)=2
CLPRE(1,IK)='SOMM'
CLPRE(2,IK)='SURF'
INLEV(1,IK)=NIOLEVG-NFLEVG
INLEV(2,IK)=NIOLEVG
! At a given model level
IK=5
ILEV(IK)=1
CLPRE(1,IK)=CLEVS(1)

!        3.2 Setup descripors

IP=0
IADD=1

!        3.2.1 STRess of gravity wave Drag :

YDCFU%YCFUPT%MSTRDU=0
YDCFU%YCFUPT%MSTRDV=0
IF ((LSTRD.OR.LAMIP).AND.(LECMWF.OR.LGWD)) THEN
  IF (LTSTRD) THEN
!   On each half level : 
    IK=1 
  ELSE
!   At the surface :
    IK=2 
  ENDIF
  IPAR=1
  CLSU=YFA_CUGW%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDCFU%YCFUPT%MSTRDU)
  CLSU=YFA_CVGW%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDCFU%YCFUPT%MSTRDV)
ENDIF

!        3.2.2 STRess of Convection :

YDCFU%YCFUPT%MSTRCU=0
YDCFU%YCFUPT%MSTRCV=0
YDCFU%YCFUPT%MFDICQ=0
YDCFU%YCFUPT%MFDICS=0
IF (LSTRC) THEN
  IF (LTSTRC) THEN
!   On each half level :
    IK=1
  ELSE
!   At the model level the closest to 550 hPa :
    IK=5
    CALL SEAPRE(55000._JPRB,INF550,STPRE,NFLEVG)
    INLEV(1,IK)=INF550-1
  ENDIF
  CLSU=YFA_CCVU%CLNAME(5:)
  IPAR=1
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDCFU%YCFUPT%MSTRCU)
  CLSU=YFA_CCVV%CLNAME(5:)
  IPAR=1
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDCFU%YCFUPT%MSTRCV)
  IF (LTSTRC) THEN
!   On each half level :
    IK=1
  ELSE
!   At the model level the closest to 850 hPa :
    IK=5
    CALL SEAPRE(85000._JPRB,INF850,STPRE,NFLEVG)
    INLEV(1,IK)=INF850-1
  ENDIF
  CLSU=YFA_CCVQ%CLNAME(5:)
  IPAR=0
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDCFU%YCFUPT%MFDICQ)
  CLSU=YFA_CCVS%CLNAME(5:)
  IPAR=0
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDCFU%YCFUPT%MFDICS)
ENDIF

!        3.2.3 STRess of Turbulence, or Surface Fluxes

YDCFU%YCFUPT%MSTRTU=0
YDCFU%YCFUPT%MSTRTV=0
YDCFU%YCFUPT%MFDITQ=0
YDCFU%YCFUPT%MFDITS=0
IF (LFSF.OR.LSTRT.OR.LAMIP) THEN
  IF (LTSTRT) THEN
!   On each half level :
    IK=1
  ELSE
!   At the surface :
    IK=2
  ENDIF
  CLSU=YFA_CUSS%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),1,YDCFU%YCFUPT%MSTRTU)
  CLSU=YFA_CVSS%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),1,YDCFU%YCFUPT%MSTRTV)
  IF (LSTRT.OR.LAMIP) THEN
    CLSU=YFA_CTUQ%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFDITQ)
    CLSU=YFA_CTUS%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFDITS)
  ENDIF
ENDIF

!        3.2.4 Flux de PLuie neige graupel et grele Convective 
!               (Convective rain snow graupel and hail)

YDCFU%YCFUPT%MFPLCL=0
YDCFU%YCFUPT%MFPLCN=0
YDCFU%YCFUPT%MFCCQL=0
YDCFU%YCFUPT%MFCCQN=0
YDCFU%YCFUPT%MFPLCG=0
YDCFU%YCFUPT%MFPLCH=0
IF (LFPLC.OR.LAMIP.OR.LFDUTP) THEN
  IF (LTFPLC) THEN
!   On each half level :
    IK=1
  ELSE
!   At the surface :
    IK=2
  ENDIF
  CLSU=YFA_CCP%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFPLCL)
  IF (LCONDWT) THEN
    CLSU='FL.COND.L.CONV  '
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFCCQL)
  ENDIF
  IF (LNEIGE) THEN
    CLSU=YFA_CCSF%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFPLCN)
    IF (LCONDWT) THEN
      CLSU='FL.COND.N.CONV  '
      CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFCCQN)
    ENDIF
  ENDIF
  IF (LFPLCG) THEN
    CLSU=YFA_CCSG%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFPLCG)
  ENDIF
  IF (LFPLCH) THEN
    CLSU=YFA_CCSH%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFPLCH)
  ENDIF
ENDIF

!        3.2.5 Flux de PLuie et neige Stratiforme (Stratiform rain and snow)

YDCFU%YCFUPT%MFPLSL=0
YDCFU%YCFUPT%MFPLSN=0
YDCFU%YCFUPT%MFCSQL=0
YDCFU%YCFUPT%MFCSQN=0
YDCFU%YCFUPT%MFPLSG=0
YDCFU%YCFUPT%MFPLSH=0
IF (LFPLS.OR.LAMIP.OR.LFDUTP) THEN
  IF (LTFPLS) THEN
!   On each half level :
    IK=1
  ELSE
!   At the surface :
    IK=2
  ENDIF
  CLSU=YFA_CLSP%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFPLSL)
  IF (LCONDWT) THEN
    CLSU='FL.COND.L.GECH  '
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFCSQL)
  ENDIF
  IF (LNEIGE) THEN
    CLSU=YFA_CLSS%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFPLSN)
    IF (LCONDWT) THEN
      CLSU='FL.COND.N.GECH  ' 
      CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFCSQN)
    ENDIF
  ENDIF
  IF (LFPLSG) THEN
    CLSU=YFA_CLSG%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFPLSG)
  ENDIF
  IF (LFPLSH) THEN
    CLSU=YFA_CLSH%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDCFU%YCFUPT%MFPLSH)
  ENDIF
ENDIF

!        3.2.6 Fluxes of Radiation

YDCFU%YCFUPT%MFRSO=0
YDCFU%YCFUPT%MFRTH=0
IF (LFR.OR.LAMIP) THEN
  IF (LTFR) THEN
!   On each half level :
    IK=1
  ELSE
    IK=4
  ENDIF
  IPAR=0
  CLSU=YFA_CSSR%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDCFU%YCFUPT%MFRSO)
  CLSU=YFA_CSTR%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDCFU%YCFUPT%MFRTH)
ENDIF

!        3.2.7 NEBulosite (Cloudiness)  : as a 3D variable

YDCFU%YCFUPT%MFNEB=0
IF (LTNEB) THEN
! On each full level :
  IK=3
  IPAR=0
  CLSU='NEBULOSI.CFU'
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDCFU%YCFUPT%MFNEB)
ENDIF

!        3.2.8 NEBulosite Totale (Total Cloudiness) : as seen from bottom

YDCFU%YCFUPT%MFNEBT=0
IF (LNEBTT.OR.LAMIP) THEN
  CALL NEXTYPE1(YFA_CTCC%CLNAME(1:4),YFA_CTCC%CLNAME(5:),0,YDCFU%YCFUPT%MFNEBT)
ENDIF

!        3.2.9 Surface Fluxes

YDCFU%YCFUPT%MFCLL=0
YDCFU%YCFUPT%MFCLN=0
YDCFU%YCFUPT%MFEVL=0
YDCFU%YCFUPT%MFEVN=0
IF (LFSF) THEN
  CALL NEXTYPE1(YFA_CLHE%CLNAME(1:4),YFA_CLHE%CLNAME(5:),0,YDCFU%YCFUPT%MFCLL)
  CALL NEXTYPE1(YFA_CLHS%CLNAME(1:4),YFA_CLHS%CLNAME(5:),0,YDCFU%YCFUPT%MFCLN)
  CALL NEXTYPE1(YFA_CE%CLNAME(1:4),YFA_CE%CLNAME(5:),0,YDCFU%YCFUPT%MFEVL)
  CALL NEXTYPE1(YFA_CS%CLNAME(1:4),YFA_CS%CLNAME(5:),0,YDCFU%YCFUPT%MFEVN)
ENDIF

!        3.2.10 SOIL fluxes

YDCFU%YCFUPT%MFONTE=0
YDCFU%YCFUPT%MFCHSP=0
YDCFU%YCFUPT%MFLWSP=0
YDCFU%YCFUPT%MRUISS=0
YDCFU%YCFUPT%MRUISP=0
YDCFU%YCFUPT%MFEVV =0
YDCFU%YCFUPT%MFTR  =0
YDCFU%YCFUPT%MRUISL=0
YDCFU%YCFUPT%MFGEL =0
YDCFU%YCFUPT%MFGELS=0
IF (LFSOIL) THEN
  CALL NEXTYPE1(YFA_CFON%CLNAME(1:4),YFA_CFON%CLNAME(5:),0,YDCFU%YCFUPT%MFONTE)
  CALL NEXTYPE1(YFA_CCHS%CLNAME(1:4),YFA_CCHS%CLNAME(5:),0,YDCFU%YCFUPT%MFCHSP)
  CALL NEXTYPE1(YFA_CEAS%CLNAME(1:4),YFA_CEAS%CLNAME(5:),0,YDCFU%YCFUPT%MFLWSP)
  CALL NEXTYPE1(YFA_CSRU%CLNAME(1:4),YFA_CSRU%CLNAME(5:),0,YDCFU%YCFUPT%MRUISS)
  CALL NEXTYPE1(YFA_CDRU%CLNAME(1:4),YFA_CDRU%CLNAME(5:),0,YDCFU%YCFUPT%MRUISP)
  IF (LSOLV) THEN
    CALL NEXTYPE1(YFA_CETP%CLNAME(1:4),YFA_CETP%CLNAME(5:),0,YDCFU%YCFUPT%MFEVV )
    CALL NEXTYPE1(YFA_CTP%CLNAME(1:4),YFA_CTP%CLNAME(5:),0,YDCFU%YCFUPT%MFTR  )
    CALL NEXTYPE1(YFA_CIRU%CLNAME(1:4),YFA_CIRU%CLNAME(5:),0,YDCFU%YCFUPT%MRUISL)
    IF (LFGEL) THEN
      CALL NEXTYPE1('PROF','FLUX DE GEL     ',0,YDCFU%YCFUPT%MFGEL)
      CALL NEXTYPE1('SURF','FLUX DE GEL     ',0,YDCFU%YCFUPT%MFGELS)
    ENDIF
  ENDIF
ENDIF

!        3.2.11 Surface Fluxes or AMIP specific fluxes

YDCFU%YCFUPT%MFCS=0
YDCFU%YCFUPT%MWS   =0
YDCFU%YCFUPT%MSNS  =0
YDCFU%YCFUPT%MQTOT =0
YDCFU%YCFUPT%MSPRES=0
YDCFU%YCFUPT%MFCL  =0
YDCFU%YCFUPT%MFDISH=0
YDCFU%YCFUPT%MFTOPH=0
YDCFU%YCFUPT%MQICE =0
YDCFU%YCFUPT%MQLI  =0
YDCFU%YCFUPT%MOZONT=0
IF (LFSF.OR.LAMIP) THEN
  CALL NEXTYPE1(YFA_CSSH%CLNAME(1:4),YFA_CSSH%CLNAME(5:),0,YDCFU%YCFUPT%MFCS)
  IF (LAMIP) THEN
    CALL NEXTYPE1(YFA_CWS%CLNAME(1:4),YFA_CWS%CLNAME(5:),0,YDCFU%YCFUPT%MWS   )
    CALL NEXTYPE1(YFA_CSNS%CLNAME(1:4),YFA_CSNS%CLNAME(5:),0,YDCFU%YCFUPT%MSNS  )
    CALL NEXTYPE1(YFA_CQTO%CLNAME(1:4),YFA_CQTO%CLNAME(5:),0,YDCFU%YCFUPT%MQTOT )
    CALL NEXTYPE1(YFA_CTSP%CLNAME(1:4),YFA_CTSP%CLNAME(5:),0,YDCFU%YCFUPT%MSPRES)
    CALL NEXTYPE1(YFA_CSLH%CLNAME(1:4),YFA_CSLH%CLNAME(5:),0,YDCFU%YCFUPT%MFCL  )
    CALL NEXTYPE1(YFA_CBLD%CLNAME(1:4),YFA_CBLD%CLNAME(5:),0,YDCFU%YCFUPT%MFDISH)
    CALL NEXTYPE1(YFA_CTME%CLNAME(1:4),YFA_CTME%CLNAME(5:),0,YDCFU%YCFUPT%MFTOPH)
    CALL NEXTYPE1(YFA_CICE%CLNAME(1:4),YFA_CICE%CLNAME(5:),0,YDCFU%YCFUPT%MQICE )
    CALL NEXTYPE1(YFA_CLI%CLNAME(1:4),YFA_CLI%CLNAME(5:),0,YDCFU%YCFUPT%MQLI  )
    IF (LOZONE) THEN
      CALL NEXTYPE1(YFA_CTO3%CLNAME(1:4),YFA_CTO3%CLNAME(5:),0,YDCFU%YCFUPT%MOZONT)
    ENDIF
  ENDIF
ENDIF

!        3.2.12 FRequency for Radiation of Clear sky (top and bottom)

YDCFU%YCFUPT%MFRSOC0=0
YDCFU%YCFUPT%MFRTHC0=0
YDCFU%YCFUPT%MFRSOC1=0
YDCFU%YCFUPT%MFRTHC1=0
IF (LFRRC) THEN
  CALL NEXTYPE1(CLEVS(1),YFA_CSOC%CLNAME(5:),0,YDCFU%YCFUPT%MFRSOC0)
  CALL NEXTYPE1B(CLEVS(1),YFA_CSOC%CLNAME(5:),0,YDCFU%YCFUPT%MFRSOC1)
  CALL NEXTYPE1(CLEVS(1),YFA_CTHC%CLNAME(5:),0,YDCFU%YCFUPT%MFRTHC0)
  CALL NEXTYPE1B(CLEVS(1),YFA_CTHC%CLNAME(5:),0,YDCFU%YCFUPT%MFRTHC1)
ENDIF

!        3.2.13 RAYonnements (more dariative fluxes)

YDCFU%YCFUPT%MFRSDNI=0
YDCFU%YCFUPT%MFRSGNI=0
YDCFU%YCFUPT%MFRSOPS=0
YDCFU%YCFUPT%MFRSOPT=0
YDCFU%YCFUPT%MFRSODS=0
YDCFU%YCFUPT%MFRTHDS=0
IF (LRAYS) THEN
  CALL NEXTYPE1(YFA_CSOP%CLNAME(1:4),YFA_CSOP%CLNAME(5:),0,YDCFU%YCFUPT%MFRSOPS)
  CALL NEXTYPE1(YFA_CTOP%CLNAME(1:3),YFA_CTOP%CLNAME(4:),0,YDCFU%YCFUPT%MFRSOPT)
  CALL NEXTYPE1(YFA_CDNI%CLNAME(1:4),YFA_CDNI%CLNAME(5:),0,YDCFU%YCFUPT%MFRSDNI)
  CALL NEXTYPE1(YFA_CGNI%CLNAME(1:4),YFA_CGNI%CLNAME(5:),0,YDCFU%YCFUPT%MFRSGNI)
ENDIF
IF (LRAYD) THEN
  CALL NEXTYPE1(YFA_CSOD%CLNAME(1:4),YFA_CSOD%CLNAME(5:),0,YDCFU%YCFUPT%MFRSODS)
  CALL NEXTYPE1(YFA_CTHD%CLNAME(1:4),YFA_CTHD%CLNAME(5:),0,YDCFU%YCFUPT%MFRTHDS)
ENDIF

YDCFU%YCFUPT%MFRSOLU=0
IF (LMOON) THEN
  CALL NEXTYPE1(YFA_CSMR%CLNAME(1:4),YFA_CSMR%CLNAME(5:),0,YDCFU%YCFUPT%MFRSOLU)
ENDIF

!        3.2.14 NEBulosite PARtielles (partial cloudiness)

YDCFU%YCFUPT%MNEBCON=0
YDCFU%YCFUPT%MNEBHAU=0
YDCFU%YCFUPT%MNEBMOY=0
YDCFU%YCFUPT%MNEBBAS=0
IF (LNEBPAR) THEN
  CALL NEXTYPE1(YFA_CCCC%CLNAME(1:4),YFA_CCCC%CLNAME(5:),0,YDCFU%YCFUPT%MNEBCON)
  CALL NEXTYPE1(YFA_CHCC%CLNAME(1:4),YFA_CHCC%CLNAME(5:),0,YDCFU%YCFUPT%MNEBHAU)
  CALL NEXTYPE1(YFA_CMCC%CLNAME(1:4),YFA_CMCC%CLNAME(5:),0,YDCFU%YCFUPT%MNEBMOY)
  CALL NEXTYPE1(YFA_CLCC%CLNAME(1:4),YFA_CLCC%CLNAME(5:),0,YDCFU%YCFUPT%MNEBBAS)
ENDIF

!        3.2.16 Filtered duration of total precipitations

YDCFU%YCFUPT%MFDUTP=0
IF (LFDUTP) THEN
  CALL NEXTYPE1(YFA_CDUTP%CLNAME(1:4),YFA_CDUTP%CLNAME(5:),0,YDCFU%YCFUPT%MFDUTP)
ENDIF

!         3.2.17 Lighnting diagnostics
YDCFU%YCFUPT%MFLASH=0
IF (LFLASH) THEN
  CALL NEXTYPE1(YFA_CFLASH%CLNAME(1:4),YFA_CFLASH%CLNAME(5:),0,YDCFU%YCFUPT%MFLASH)
ENDIF

!        3.4 Count fields

NTYPCFU=IP
NFDCFU=IADD-1
LCUMFU=(NFDCFU > 0)

!      -----------------------------------------------------------

!*       4.    PRINT FINAL VALUES.
!              -------------------

WRITE(UNIT=KULOUT,FMT='('' COMMON YOMCFU '')')
WRITE(UNIT=KULOUT,FMT='('' LCUMFU = '',L2,'' LREACFU = '',L2)') LCUMFU, LREACFU
WRITE(UNIT=KULOUT,FMT='('' NFDCFU = '',I6,'' NTYPCFU = '',I6)') NFDCFU, NTYPCFU
WRITE(UNIT=KULOUT,FMT='('' NFRCFU = '',I7)')NFRCFU
WRITE(KULOUT,*) ' NCFUTS =  ',NCFUTS(0),(NCFUTS(J),J=1,ABS(NCFUTS(0)))
IF (LCUMFU) THEN
  WRITE(UNIT=KULOUT,FMT='('' LSTRD  = '',L2,'' LSTRC  = '',L2&
   & ,'' LSTRT  = '',L2,'' LFPLC  = '',L2,'' LFPLCG  = '',L2&
   & ,'' LFPLCH = '',L2,'' LFPLS  = '',L2,'' LFPLSG  = '',L2&
   & ,'' LFPLSH = '',L2,'' LFR    = '',L2,'' LFSOIL = '',L2&
   & ,'' LNEBTT = '',L2,'' LFSF   = '',L2,'' LNEBPAR= '',L2&
   & ,'' LAMIP  = '',L2,'' LRAYS  = '',L2,'' LFRRC  = '',L2&
   & ,'' LFDUTP = '',L2,'' LMOON  = '',L2,'' LRAYD  = '',L2&
   & ,'' LFLASH = '',L2&
   & )')&
   & LSTRD,LSTRC,LSTRT,LFPLC,LFPLCG,LFPLCH,LFPLS,LFPLSG,LFPLSH,&
   & LFR,LFSOIL,LNEBTT,LFSF,LNEBPAR,LAMIP,LRAYS,LFRRC,LFDUTP,LMOON,LRAYD,LFLASH
  WRITE(UNIT=KULOUT,FMT='('' LTSTRD  = '',L2,'' LTSTRC  = '',L2&
   & ,'' LTSTRT  = '',L2,'' LTFPLC  = '',L2,'' LTFPLS  = '',L2&
   & ,'' LTFR    = '',L2,'' LTNEB   = '',L2)')&
   & LTSTRD,LTSTRC,LTSTRT,LTFPLC,LTFPLS,LTFR,LTNEB  
  WRITE(UNIT=KULOUT,FMT='('' NFRRC = '',I8)') NFRRC
  WRITE(UNIT=KULOUT,FMT='('' NMTFLASH = '',I8)') NMTFLASH
  WRITE(UNIT=KULOUT,FMT='('' MSTRDU = '',I2,'' MSTRDV = '',I2&
   & ,'' MSTRCU = '',I2,'' MSTRCV = '',I2,'' MFDICQ = '',I2,'' MFDICS = '',I2&
   & ,'' MSTRTU = '',I2,'' MSTRTV = '',I2,'' MFDITQ = '',I2,'' MFDITS = '',I2&
   & ,'' MFPLCL = '',I2,'' MFPLSL = '',I2,'' MFPLCN = '',I2,'' MFPLSN = '',I2&
   & ,'' MFCCQL = '',I2,'' MFCCQN = '',I2,'' MFCSQL = '',I2,'' MFCSQN = '',I2&
   & ,'' MFRSO  = '',I2,'' MFRTH  = '',I2,'' MFNEB  = '',I2,'' MWS    = '',I2&
   & ,'' MSNS   = '',I2,'' MQTOT  = '',I2,'' MFNEBT = '',I2,'' MOZONT = '',I2&
   & ,'' MSPRES = '',I2,'' MFCL   = '',I2,'' MFCS   = '',I2,'' MFDISH = '',I2&
   & ,'' MFTOPH = '',I2,'' MQICE  = '',I2,'' MQLI   = '',I2,'' MFRSOC0= '',I2&
   & ,'' MFRTHC0= '',I2,'' MFRSOPS= '',I2,'' MFRSOPT= '',I2,'' MFRSOLU= '',I2&
   & ,'' MFRSODS= '',I2,'' MFRTHDS= '',I2,'' MFCLL  = '',I2,'' MFCLN  = '',I2&
   & ,'' MFEVL  = '',I2,'' MFEVN  = '',I2,'' MFONTE = '',I2,'' MFCHSP = '',I2&
   & ,'' MFEVV  = '',I2,'' MFLWSP = '',I2,'' MFTR   = '',I2,'' MRUISL = '',I2&
   & ,'' MRUISP = '',I2,'' MRUISS = '',I2,'' MNEBCON= '',I2,'' MNEBHAU= '',I2&
   & ,'' MNEBMOY= '',I2,'' MFGEL  = '',I2,'' MFGELS = '',I2,'' MNEBBAS= '',I2&
   & ,'' MFRSOC1= '',I2,'' MFRTHC1= '',I2,'' MFDUTP = '',I2,'' MFRSDNI= '',I2&
   & ,'' MFRSGNI= '',I2,'' MFLASH= '',I2&
   &)')&
   & YDCFU%YCFUPT%MSTRDU ,YDCFU%YCFUPT%MSTRDV ,YDCFU%YCFUPT%MSTRCU ,YDCFU%YCFUPT%MSTRCV ,YDCFU%YCFUPT%MFDICQ ,YDCFU%YCFUPT%MFDICS ,&
   & YDCFU%YCFUPT%MSTRTU ,YDCFU%YCFUPT%MSTRTV ,YDCFU%YCFUPT%MFDITQ ,YDCFU%YCFUPT%MFDITS ,YDCFU%YCFUPT%MFPLCL ,YDCFU%YCFUPT%MFPLSL ,&
   & YDCFU%YCFUPT%MFPLCN ,YDCFU%YCFUPT%MFPLSN ,YDCFU%YCFUPT%MFCCQL ,YDCFU%YCFUPT%MFCCQN ,YDCFU%YCFUPT%MFCSQL ,YDCFU%YCFUPT%MFCSQN ,&
   & YDCFU%YCFUPT%MFRSO  ,YDCFU%YCFUPT%MFRTH  ,YDCFU%YCFUPT%MFNEB  ,YDCFU%YCFUPT%MWS    ,YDCFU%YCFUPT%MSNS   ,YDCFU%YCFUPT%MQTOT  ,&
   & YDCFU%YCFUPT%MFNEBT ,YDCFU%YCFUPT%MOZONT ,YDCFU%YCFUPT%MSPRES ,YDCFU%YCFUPT%MFCL   ,YDCFU%YCFUPT%MFCS   ,YDCFU%YCFUPT%MFDISH ,&
   & YDCFU%YCFUPT%MFTOPH ,YDCFU%YCFUPT%MQICE  ,YDCFU%YCFUPT%MQLI   ,YDCFU%YCFUPT%MFRSOC0,YDCFU%YCFUPT%MFRTHC0,YDCFU%YCFUPT%MFRSOPS,&
   & YDCFU%YCFUPT%MFRSOPT,YDCFU%YCFUPT%MFRSOLU,YDCFU%YCFUPT%MFRSODS,YDCFU%YCFUPT%MFRTHDS,YDCFU%YCFUPT%MFCLL  ,YDCFU%YCFUPT%MFCLN  ,&
   & YDCFU%YCFUPT%MFEVL  ,YDCFU%YCFUPT%MFEVN  ,YDCFU%YCFUPT%MFONTE ,YDCFU%YCFUPT%MFCHSP ,YDCFU%YCFUPT%MFEVV  ,YDCFU%YCFUPT%MFLWSP ,&
   & YDCFU%YCFUPT%MFTR   ,YDCFU%YCFUPT%MRUISL ,YDCFU%YCFUPT%MRUISP ,YDCFU%YCFUPT%MRUISS ,YDCFU%YCFUPT%MNEBCON,YDCFU%YCFUPT%MNEBHAU,&
   & YDCFU%YCFUPT%MNEBMOY,YDCFU%YCFUPT%MFGEL  ,YDCFU%YCFUPT%MFGELS ,YDCFU%YCFUPT%MNEBBAS,YDCFU%YCFUPT%MFRSOC1,YDCFU%YCFUPT%MFRTHC1,&
   & YDCFU%YCFUPT%MFDUTP ,YDCFU%YCFUPT%MFRSDNI ,YDCFU%YCFUPT%MFRSGNI,YDCFU%YCFUPT%MFLASH
  WRITE(UNIT=KULOUT,&
   & FMT='('' ADDITIONAL CFU OPTIONS : '')')
  WRITE(UNIT=KULOUT,FMT='('' CALFLASH1 = '',F7.2,'' CALFLASH2 = '',F7.2)') CALFLASH1,CALFLASH2
  WRITE(UNIT=KULOUT,&
   & FMT='('' THE FOLLOWING CUMULATED FLUXES WILL BE HANDLED : '')')  
  DO JF=1,NTYPCFU
    DO JL=1,TYPE_CFU(JF)%ILEV
      IF (TYPE_CFU(JF)%CLPREF(JL) == CLEVS(1)) THEN
        WRITE(UNIT=KULOUT,FMT='(A1,I3.3,A12,10X, ''PARITY = '',I1)')&
         & TRIM(TYPE_CFU(JF)%CLPREF(JL)),TYPE_CFU(JF)%INUMLEV(JL),&
         & TYPE_CFU(JF)%CLSUFF,TYPE_CFU(JF)%IPARITY  
      ELSE
        WRITE(UNIT=KULOUT,FMT='(A16,10X, ''PARITY = '',I1)')&
         & TRIM(TYPE_CFU(JF)%CLPREF(JL))//TYPE_CFU(JF)%CLSUFF,&
         & TYPE_CFU(JF)%IPARITY  
      ENDIF
    ENDDO
  ENDDO
ENDIF

ALLOCATE (YDCFU%GFUBUF (YDGEOMETRY%YRDIM%NPROMA, NFDCFU, YDGEOMETRY%YRDIM%NGPBLKS))

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUCFU',1,ZHOOK_HANDLE)

!     ------------------------------------------------------------------

CONTAINS

SUBROUTINE NEXTYPE3(CDPREF,CDSUFF,KNLEV,KLEV,KPAR,KX)

INTEGER(KIND=JPIM), INTENT(IN)  :: KLEV,KPAR
INTEGER(KIND=JPIM), INTENT(IN)  :: KNLEV(KLEV)
CHARACTER(LEN=*),   INTENT(IN)  :: CDPREF(KLEV)
CHARACTER(LEN=*),   INTENT(IN)  :: CDSUFF
INTEGER(KIND=JPIM), INTENT(OUT) :: KX

INTEGER(KIND=JPIM) :: J, ILEN
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SUCFU:NEXTYPE3',0,ZHOOK_HANDLE)
ASSOCIATE(TYPE_CFU=>YDCFU%TYPE_CFU)

IF (ALL((CDPREF(:) /= ' ' .AND. CDSUFF(:) /= ' '))) THEN
  IP=IP+1
  DO J=1,KLEV
    ILEN=MIN(4,LEN(CDPREF(J)))
    TYPE_CFU(IP)%CLPREF(J)=CDPREF(J)(1:ILEN)
    TYPE_CFU(IP)%INUMLEV(J)=KNLEV(J)
  ENDDO
  ILEN=MIN(16,LEN(CDSUFF))
  TYPE_CFU(IP)%CLSUFF=CDSUFF(1:ILEN)
  TYPE_CFU(IP)%ILEV=KLEV
  TYPE_CFU(IP)%IPARITY=KPAR
  KX=IADD
  IADD=IADD+KLEV
ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUCFU:NEXTYPE3',1,ZHOOK_HANDLE)

END SUBROUTINE NEXTYPE3

SUBROUTINE NEXTYPE1(CDPREF,CDSUFF,KPAR,KX)

INTEGER(KIND=JPIM), INTENT(IN)  :: KPAR
CHARACTER(LEN=*),   INTENT(IN)  :: CDPREF
CHARACTER(LEN=*),   INTENT(IN)  :: CDSUFF
INTEGER(KIND=JPIM), INTENT(OUT) :: KX

INTEGER(KIND=JPIM) :: ILEN
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SUCFU:NEXTYPE1',0,ZHOOK_HANDLE)
ASSOCIATE(TYPE_CFU=>YDCFU%TYPE_CFU, &
 & NIOLEVG=>YDGEOMETRY%YRDIMV%NIOLEVG, NFLEVG=>YDGEOMETRY%YRDIMV%NFLEVG)

IF (CDPREF /= ' ' .AND. CDSUFF /= ' ') THEN
  IP=IP+1
  ILEN=MIN(4,LEN(CDPREF))
  TYPE_CFU(IP)%CLPREF(1)=CDPREF(1:ILEN)
  TYPE_CFU(IP)%INUMLEV(1)=1+NIOLEVG-NFLEVG
  ILEN=MIN(16,LEN(CDSUFF))
  TYPE_CFU(IP)%CLSUFF=CDSUFF(1:ILEN)
  TYPE_CFU(IP)%ILEV=1
  TYPE_CFU(IP)%IPARITY=KPAR
  KX=IADD
  IADD=IADD+1
ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUCFU:NEXTYPE1',1,ZHOOK_HANDLE)

END SUBROUTINE NEXTYPE1

SUBROUTINE NEXTYPE1B(CDPREF,CDSUFF,KPAR,KX)

INTEGER(KIND=JPIM), INTENT(IN)  :: KPAR
CHARACTER(LEN=*),   INTENT(IN)  :: CDPREF
CHARACTER(LEN=*),   INTENT(IN)  :: CDSUFF
INTEGER(KIND=JPIM), INTENT(OUT) :: KX

INTEGER(KIND=JPIM) :: ILEN
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SUCFU:NEXTYPE1B',0,ZHOOK_HANDLE)
ASSOCIATE(TYPE_CFU=>YDCFU%TYPE_CFU, &
 & NIOLEVG=>YDGEOMETRY%YRDIMV%NIOLEVG)

IF (CDPREF /= ' ' .AND. CDSUFF /= ' ') THEN
  IP=IP+1
  ILEN=MIN(4,LEN(CDPREF))
  TYPE_CFU(IP)%CLPREF(1)=CDPREF(1:ILEN)
  TYPE_CFU(IP)%INUMLEV(1)=NIOLEVG
  ILEN=MIN(16,LEN(CDSUFF))
  TYPE_CFU(IP)%CLSUFF=CDSUFF(1:ILEN)
  TYPE_CFU(IP)%ILEV=1
  TYPE_CFU(IP)%IPARITY=KPAR
  KX=IADD
  IADD=IADD+1
ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUCFU:NEXTYPE1B',1,ZHOOK_HANDLE)

END SUBROUTINE NEXTYPE1B

END SUBROUTINE SUCFU

