! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUCPL0(YDGEOMETRY,YDDPHY)

!**** *SUCPL00 * - ROUTINE TO RESET TO 0 THE COUPLED FIELDS

!     PURPOSE.
!     --------
!        RESET YOMCPL ARRAY TO 0

!**   INTERFACE.
!     ----------
!        *CALL* *SUCPL0*

!     EXPLICIT ARGUMENTS :  NONE
!     --------------------

!     IMPLICIT ARGUMENTS :
!     --------------------
!        COMMON  YOMCPL

!     METHOD.
!     -------
!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF RESEARCH DEPARTMENT DOCUMENTATION OF THE
!     "IN CORE MODEL"

!     AUTHOR.
!     -------
!        /CNRM/GMGEC/EAC/JPh Piedelievre 2000-11-30

!     Modifications:
!     --------------
!        Modified : 01-12-07 P. Marquet - Modifications for Climat-V4
!        Modified : 05-10-07 A. Alias   - ajout de FCCHLL/FCCHLN/FCEVAP
!        Modified : 14-10-09 A. Alias   - FCWIMO/FCSUBL added
!        K. Yessad (Jan 2010): remove useless variables.
!        K. Yessad (July 2014): Move some variables.
!-----------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMLUN   , ONLY : NULOUT
USE YOMDPHY  , ONLY : TDPHY
USE YOMMP0   , ONLY : NPRINTLEV
USE YOMCT0   , ONLY : LALLOPR
USE YOMCPL   , ONLY : FCSTSU       ,FCSTSV    ,FCCHAS    ,&
 & FCRSOS   ,FCHUMS       ,FCRUIS    ,FCCHSS    ,&
 & FCHUML   ,FCHUMN       ,FCTSUR2   ,FCTSTS    ,&
 & FCTSFL   ,FCCHLL       ,FCCHLN    ,FCWIMO,  FCSUBL

!      ----------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TDPHY)    ,INTENT(INOUT):: YDDPHY

INTEGER(KIND=JPIM) :: IU

LOGICAL :: LLP
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
#ifdef __INTEL_COMPILER
INTRINSIC :: SHAPE ! Fails with Intel compiler as it thinks we use ATLAS shape function
#endif


!      ----------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUCPL0',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP)
ASSOCIATE(NDGLG=>YDDIM%NDGLG, NDLON=>YDDIM%NDLON, &
 & NTSSG=>YDDPHY%NTSSG, &
 & NGPTOT=>YDGEM%NGPTOT)
!      ----------------------------------------------------------------

LLP=NPRINTLEV >= 1.OR. LALLOPR
IU=NULOUT

IF (.NOT.ALLOCATED (FCSTSU) ) THEN
  ALLOCATE(FCSTSU(NGPTOT))
  IF(LLP)WRITE(IU,9) 'FCSTSU    ',SIZE(FCSTSU),SHAPE(FCSTSU)
ENDIF
IF (.NOT.ALLOCATED (FCSTSV) ) THEN
  ALLOCATE(FCSTSV(NGPTOT))
  IF(LLP)WRITE(IU,9) 'FCSTSV    ',SIZE(FCSTSV),SHAPE(FCSTSV)
ENDIF
IF (.NOT.ALLOCATED (FCCHAS) ) THEN
  ALLOCATE(FCCHAS(NGPTOT,NTSSG+1))
  IF(LLP)WRITE(IU,9) 'FCCHAS    ',SIZE(FCCHAS),SHAPE(FCCHAS)
ENDIF
IF (.NOT.ALLOCATED (FCRSOS) ) THEN
  ALLOCATE(FCRSOS(NGPTOT,NTSSG+1))
  IF(LLP)WRITE(IU,9) 'FCRSOS    ',SIZE(FCRSOS),SHAPE(FCRSOS)
ENDIF
IF (.NOT.ALLOCATED (FCHUMS) ) THEN
  ALLOCATE(FCHUMS(NGPTOT,NTSSG+1))
  IF(LLP)WRITE(IU,9) 'FCHUMS    ',SIZE(FCHUMS),SHAPE(FCHUMS)
ENDIF
IF (.NOT.ALLOCATED (FCRUIS) ) THEN
  ALLOCATE(FCRUIS(NGPTOT))
  IF(LLP)WRITE(IU,9) 'FCRUIS    ',SIZE(FCRUIS),SHAPE(FCRUIS)
ENDIF
IF (.NOT.ALLOCATED (FCCHSS) ) THEN
  ALLOCATE(FCCHSS(NGPTOT,NTSSG+1))
  IF(LLP)WRITE(IU,9) 'FCCHSS    ',SIZE(FCCHSS),SHAPE(FCCHSS)
ENDIF
IF (.NOT.ALLOCATED (FCHUML) ) THEN
  ALLOCATE(FCHUML(NGPTOT))
  IF(LLP)WRITE(IU,9) 'FCHUML    ',SIZE(FCHUML),SHAPE(FCHUML)
ENDIF
IF (.NOT.ALLOCATED (FCHUMN) ) THEN
  ALLOCATE(FCHUMN(NGPTOT))
  IF(LLP)WRITE(IU,9) 'FCHUMN    ',SIZE(FCHUMN),SHAPE(FCHUMN)
ENDIF
IF (.NOT.ALLOCATED (FCTSUR2) ) THEN
  ALLOCATE(FCTSUR2(NGPTOT))
  IF(LLP)WRITE(IU,9) 'FCTSUR2    ',SIZE(FCTSUR2),SHAPE(FCTSUR2)
ENDIF
IF (.NOT.ALLOCATED (FCTSTS) ) THEN
  ALLOCATE(FCTSTS(NGPTOT))
  IF(LLP)WRITE(IU,9) 'FCTSTS     ',SIZE(FCTSTS),SHAPE(FCTSTS)
ENDIF
IF (.NOT.ALLOCATED (FCTSFL) ) THEN
  ALLOCATE(FCTSFL(NGPTOT))
  IF(LLP)WRITE(IU,9) 'FCTSFL     ',SIZE(FCTSFL),SHAPE(FCTSFL)
ENDIF
IF (.NOT.ALLOCATED (FCCHLL) ) THEN
  ALLOCATE(FCCHLL(NDLON,NDGLG))
  IF(LLP)WRITE(IU,9) 'FCCHLL     ',SIZE(FCCHLL),SHAPE(FCCHLL)
ENDIF
IF (.NOT.ALLOCATED (FCCHLN) ) THEN
  ALLOCATE(FCCHLN(NDLON,NDGLG))
  IF(LLP)WRITE(IU,9) 'FCCHLN     ',SIZE(FCCHLN),SHAPE(FCCHLN)
ENDIF
IF (.NOT.ALLOCATED (FCWIMO) ) THEN
  ALLOCATE(FCWIMO(NGPTOT))
  IF(LLP)WRITE(IU,9) 'FCWIMO     ',SIZE(FCWIMO),SHAPE(FCWIMO)
ENDIF
IF (.NOT.ALLOCATED (FCSUBL) ) THEN
  ALLOCATE(FCSUBL(NGPTOT))
  IF(LLP)WRITE(IU,9) 'FCSUBL     ',SIZE(FCSUBL),SHAPE(FCSUBL)
ENDIF

9 FORMAT(1X,'ARRAY ',A10,' ALLOCATED ',8I8)

!*       1.    SET YOMCPL TO 0.
!              ---------------

FCCHAS=0.0_JPRB
FCRSOS=0.0_JPRB
FCHUMS=0.0_JPRB
FCCHSS=0.0_JPRB

FCSTSU=0.0_JPRB
FCSTSV=0.0_JPRB
FCRUIS=0.0_JPRB
FCHUML=0.0_JPRB
FCHUMN=0.0_JPRB
FCTSUR2=0.0_JPRB
FCTSTS =0.0_JPRB
FCTSFL =0.0_JPRB
FCWIMO =0.0_JPRB
FCSUBL =0.0_JPRB

!      ----------------------------------------------------------------
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUCPL0',1,ZHOOK_HANDLE)
END SUBROUTINE SUCPL0
