! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUDCMIP16_GU(YDGEOMETRY,YDDIMF,YDSPEC,KTESTCASE,PQ)

!     Purpose.
!     --------
!           uuper air grid point fields for DCMIP16 test cases

!        Explicit arguments :
!        --------------------


!     Author.
!     -------
!        S.Malardel *ECMWF*

!     Modifications.
!     --------------

USE GEOMETRY_MOD, ONLY : GEOMETRY
USE PARKIND1  , ONLY : JPIM, JPRB
USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN    , ONLY : NULOUT
USE YOMDIMF   , ONLY : TDIMF
USE YOMCST    , ONLY : RPI, RD, RG
USE SPECTRAL_FIELDS_MOD, ONLY : ASSIGNMENT(=), SPECTRAL_FIELD
USE INTDYN_MOD, ONLY : YYTXYB
IMPLICIT NONE

TYPE(GEOMETRY),     INTENT(IN)     :: YDGEOMETRY
TYPE(TDIMF)        ,INTENT(INOUT)  :: YDDIMF
TYPE(SPECTRAL_FIELD),INTENT(INOUT) :: YDSPEC
INTEGER(KIND=JPIM), INTENT(IN)     :: KTESTCASE
REAL(KIND=JPRB),    INTENT(INOUT)  :: PQ(YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIMV%NFLEVG)
!     ------------------------------------------------------------------

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
INTEGER(KIND=JPIM) :: JLEV, JWORD
! baroclinic case
REAL(KIND=JPRB) ::    ZQ0,ZPHIW,ZVPW,ZVP00
! Supercell
REAL(KIND=JPRB) ::    ZXYB   (YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYB%NDIM)
REAL(KIND=JPRB) ::    ZPRESH(YDGEOMETRY%YRGEM%NGPTOT,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ::    ZPRESF (YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ::    ZPHI(YDGEOMETRY%YRGEM%NGPTOT,0:YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ::    ZPHIF(YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ::    ZRDGAZ(YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ::    ZT(YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) ::    ZTEMP(YDGEOMETRY%YRDIMV%NFLEVL,YDGEOMETRY%YRDIM%NSPEC2)
REAL(KIND=JPRB) ::    ZZZ,ZQS, ZZR, Zf2x, ZZTOP
REAL(KIND=JPRB) ::    ZVETAF(YDGEOMETRY%YRGEM%NGPTOT,YDGEOMETRY%YRDIMV%NFLEVG)

#include "gphpre.intfb.h"
#include "speree.intfb.h"
#include "gpgeo.intfb.h"

IF (LHOOK) CALL DR_HOOK('SUDCMIP16_GU',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM, YDDIMV=>YDGEOMETRY%YRDIMV, YDGEM=>YDGEOMETRY%YRGEM, &
 & YDGSGEOM_NB=>YDGEOMETRY%YRGSGEOM_NB, YDVAB=>YDGEOMETRY%YRVAB, YDVETA=>YDGEOMETRY%YRVETA, &
 & YDCVER=>YDGEOMETRY%YRCVER,YDVERT_GEOM=>YDGEOMETRY%YRVERT_GEOM)
ASSOCIATE( &
 & NFLEVG=>YDDIMV%NFLEVG, &
 & NGPTOT=>YDGEM%NGPTOT, & 
 & NSPEC2=>YDDIM%NSPEC2, &
 & NFLEVL=>YDDIMV%NFLEVL )

!==================================================================
! Case 162:  Baroclinic waves (moist) 
IF((KTESTCASE == 162)) THEN
!==================================================================
ZPHIW=2._JPRB*RPI/9._JPRB
ZQ0=0.018_JPRB
ZVP00 = 1.E5_JPRB
ZVPW = 34000._JPRB
!ZPT=10000._JPRB
!ZQT=1.E12_JPRB

!!! SURFACE PRESSURE
ZVP00 = 1.E5_JPRB
DO JWORD = 1,NGPTOT
  ZPRESH(JWORD,NFLEVG)=ZVP00
ENDDO
CALL GPHPRE (NGPTOT,NFLEVG,1,NGPTOT,YDVAB,YDCVER,ZPRESH,PXYB=ZXYB,PRESF=ZPRESF)
DO JWORD = 1,NGPTOT
   DO JLEV = 1, NFLEVG
      ZVETAF(JWORD,JLEV)=ZPRESF(JWORD,JLEV)/ZVP00
   ENDDO
ENDDO
DO JWORD = 1,NGPTOT
  DO JLEV = 1, NFLEVG
      PQ(JWORD,JLEV) = ZQ0 * exp(-(YDGSGEOM_NB%GELAT(JWORD)/ZPHIW)**4) &
 &                     *exp(-((ZVETAF(JWORD,JLEV)-1._JPRB)*ZVP00/ZVPW)**2)
      PQ(JWORD,JLEV) = MAX(PQ(JWORD,JLEV),1.E-12_JPRB)
  ENDDO
ENDDO

  WRITE(NULOUT,'(''END OF GFL setup in sugridug2 for NTESTCASE=162'')')
ENDIF

!==================================================================
! Case 181:  Supercell
IF((KTESTCASE == 181)) THEN
!==================================================================
! T from spectral space
ZTEMP(:,:) = YDSPEC%T(:,:)

CALL SPEREE(YDGEOMETRY,NFLEVL,NFLEVG,ZTEMP,ZT)

ZRDGAZ = RD
DO JWORD = 1,NGPTOT
  ZPHI(JWORD,NFLEVG) = 0.0_JPRB
ENDDO
!!! SURFACE PRESSURE
ZVP00 = 1.E5_JPRB
DO JWORD = 1,NGPTOT
  ZPRESH(JWORD,NFLEVG)=ZVP00
ENDDO
CALL GPHPRE (NGPTOT,NFLEVG,1,NGPTOT,YDVAB,YDCVER,ZPRESH,PXYB=ZXYB,PRESF=ZPRESF)
CALL GPGEO (NGPTOT,1,NGPTOT,NFLEVG,&
          & ZPHI, ZPHIF, &
          & ZT,ZRDGAZ,ZXYB(1,1,YYTXYB%M_LNPR),&
          & ZXYB(1,1,YYTXYB%M_ALPH),YDVERT_GEOM)

!Start with relative humidity profile 
! and convert to specific humidity
ZZR=12000._JPRB
ZZTOP=20000._JPRB
Zf2x=17.27_JPRB
DO JLEV = 1, NFLEVG
DO JWORD = 1,NGPTOT
  ZZZ = ZPHIF(JWORD,JLEV )/RG
  IF (ZZZ<ZZR) THEN
    PQ(JWORD,JLEV) = 1._JPRB-3._JPRB/4._JPRB*(ZZZ/ZZR)**(5._JPRB/4._JPRB) 
  ELSEIF (ZZZ<ZZTOP) THEN
    PQ(JWORD,JLEV) = 1._JPRB/4._JPRB
  ELSE
    PQ(JWORD,JLEV) = 1.E-12_JPRB
  ENDIF
  IF (ZZZ<ZZTOP) THEN
    ZQS = (380.0_JPRB/ZPRESF(JWORD,JLEV))* &
 &      exp(Zf2x*(ZT(JWORD,JLEV)-273._JPRB)/(ZT(JWORD,JLEV)-36.0_JPRB))

    PQ(JWORD,JLEV) = PQ(JWORD,JLEV) *ZQS
    PQ(JWORD,JLEV) = MIN(0.014_JPRB,MAX(PQ(JWORD,JLEV),0._JPRB))
  ENDIF
ENDDO
ENDDO

  WRITE(NULOUT,'(''END OF GFL setup in sugridug2 for NTESTCASE=182'')')
ENDIF
!     ------------------------------------------------------------------
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUDCMIP16_GU',1,ZHOOK_HANDLE)
END SUBROUTINE SUDCMIP16_GU
