! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUFPILMOD(YDTFP,LDNHDYN,KLMOD,YDGFLD,YDPHY,KCUFNR,KFLEVG,YDQTYPE)

!**** *SUFPILMOD*  - Setup the list of primitive variables for the post-processing

!     PURPOSE.
!     --------
!        To indicate, for each post-processable dynamic fields, whether it is a primitive variable
!        for the post-processing (ICOD > 0) and if so, if it is a surface field (1) or an upper-air field (2)
!        Primitive variables will be first horizontally interpolated on the model levels. 
!        Then, initialise the post-processing request of these primitive variables

!**   INTERFACE.
!     ----------
!       *CALL* *SUFPILMOD*

!        EXPLICIT ARGUMENTS
!        --------------------
!          LDNHDYN : .TRUE. if NH fields present
!          KLMOD : model/post-processing dynamic primitive variable indicator for each fullpos field :
!                  2 : upper air primitive dynamic variable
!                  1 : surface primitive dynamic variable
!                  0 : not a primitive variable

!        IMPLICIT ARGUMENTS
!        --------------------
!        See #include below.

!     METHOD.
!     -------
!        See documentation about FULL-POS.

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!        ORIGINAL : R. El Khatib 21-Jul-2017 from suafn1 *METEO-FRANCE*

!     MODIFICATIONS.
!     --------------
!     ------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE PARFPOS  , ONLY : JPOSSCVA,  JPOSAERO, JPOSGHG, JPOSEZDIAG, JPOSCHEM, JPOSDYN, JPOSEMIS3D
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMPHY   , ONLY : TPHY
USE YOMAFN   , ONLY : ALL_FULLPOS_TYPES
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN

!     ------------------------------------------------------------------ 

IMPLICIT NONE

TYPE(ALL_FULLPOS_TYPES), INTENT(IN) :: YDTFP
LOGICAL,            INTENT(IN) :: LDNHDYN
INTEGER(KIND=JPIM), INTENT(OUT) :: KLMOD(JPOSDYN)
TYPE(TPHY)         ,INTENT(IN) :: YDPHY
TYPE(TYPE_GFLD)    ,INTENT(IN) :: YDGFLD
INTEGER(KIND=JPIM), INTENT(IN) :: KCUFNR
INTEGER(KIND=JPIM),INTENT(IN)  :: KFLEVG
TYPE (TYPE_FPRQDYN),  INTENT(INOUT) :: YDQTYPE

INTEGER(KIND=JPIM) :: JVAR, JLEV, J, IJ

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------ 

IF (LHOOK) CALL DR_HOOK('SUFPILMOD',0,ZHOOK_HANDLE)
ASSOCIATE(YI=>YDGFLD%YI, YH=>YDGFLD%YH, YAERO=>YDGFLD%YAERO, YL=>YDGFLD%YL, &
 & YEZDIAG=>YDGFLD%YEZDIAG, &
 & YEXT=>YDGFLD%YEXT, YGHG=>YDGFLD%YGHG, YA=>YDGFLD%YA, YSPF=>YDGFLD%YSPF, &
 & YRKTQV=>YDGFLD%YRKTQV, YG=>YDGFLD%YG, &
 & NACTAERO=>YDGFLD%NACTAERO, NAEROUT=>YDGFLD%NAEROUT, NNOGW=>YDGFLD%NNOGW, &
 & NUVP=>YDGFLD%NUVP, YMXL=>YDGFLD%YMXL, YCHEM=>YDGFLD%YCHEM, YQ=>YDGFLD%YQ, &
 & YCPF=>YDGFLD%YCPF, YR=>YDGFLD%YR, &
 & NEMIS3D=>YDGFLD%NEMIS3D, YEMIS3D=>YDGFLD%YEMIS3D, &
 & YLRCH4=>YDGFLD%YLRCH4, NGHG=>YDGFLD%NGHG, YDOM=>YDGFLD%YDOM, YUNEBH=>YDGFLD%YUNEBH, &
 & YIRAD=>YDGFLD%YIRAD, NGFL_EXT=>YDGFLD%NGFL_EXT, &
 & YRKTQC=>YDGFLD%YRKTQC, YTKE=>YDGFLD%YTKE, YUOM=>YDGFLD%YUOM, YAEROUT=>YDGFLD%YAEROUT, &
 & YLCONV=>YDGFLD%YLCONV, YICONV=>YDGFLD%YICONV, YRCONV=>YDGFLD%YRCONV, YSCONV=>YDGFLD%YSCONV, & 
 & YNOGW=>YDGFLD%YNOGW, YDAL=>YDGFLD%YDAL, NAERO=>YDGFLD%NAERO, YSHTUR=>YDGFLD%YSHTUR, &
 & NERA40=>YDGFLD%NERA40, YUEN=>YDGFLD%YUEN, YUAL=>YDGFLD%YUAL, YTTE=>YDGFLD%YTTE, &
 & YERA40=>YDGFLD%YERA40, NCHEM=>YDGFLD%NCHEM, YS=>YDGFLD%YS, YFQTUR=>YDGFLD%YFQTUR, &
 & YO3=>YDGFLD%YO3, YUVP=>YDGFLD%YUVP, YRKTH=>YDGFLD%YRKTH, &
 & NGFL_EZDIAG=>YDGFLD%NGFL_EZDIAG, &
 & YFSTUR=>YDGFLD%YFSTUR, &
 & YLRAD=>YDGFLD%YLRAD, YEFB1=>YDGFLD%YEFB1, YEFB2=>YDGFLD%YEFB2, YEFB3=>YDGFLD%YEFB3, &
 & LEDR=>YDPHY%LEDR,NEDRP=>YDGFLD%NEDRP)
!     ------------------------------------------------------------------ 

KLMOD(:)=0

KLMOD(YDTFP%FIS%ICOD)=1
KLMOD(YDTFP%LNSP%ICOD)=1
KLMOD(YDTFP%U%ICOD)=2
KLMOD(YDTFP%V%ICOD)=2
KLMOD(YDTFP%T%ICOD)=2
! NH fields (pressure departure, vertical divergence and surface true vertical velocity)
! become unconditionally primitive for the post-processing if upper air NH fields are requested 
IF (LDNHDYN) THEN
  ! NH Pressure departure
  KLMOD(YDTFP%PD%ICOD)=2
  ! True vertical velocity ON UPPER HALF LEVELS +  True vertical velocity ON SURFACE
  KLMOD(YDTFP%VW%ICOD)=2
  KLMOD(YDTFP%WWS%ICOD)=1
ENDIF
! certain of the next ones could be deactivated under certain conditions (use the target YDQTYPE%LLs)
IF (LEDR) THEN
  KLMOD(YDTFP%EDR%ICOD)=2
ENDIF
IF (YQ%LACTIVE) THEN
  KLMOD(YDTFP%Q%ICOD)=2
ENDIF
IF (YL%LACTIVE) THEN
  KLMOD(YDTFP%L%ICOD)=2
ENDIF
IF (YI%LACTIVE) THEN
  KLMOD(YDTFP%I%ICOD)=2
ENDIF
IF (YLRAD%LACTIVE) THEN
  KLMOD(YDTFP%LRAD%ICOD)=2
ENDIF
IF (YIRAD%LACTIVE) THEN
  KLMOD(YDTFP%IRAD%ICOD)=2
ENDIF
IF (YA%LACTIVE) THEN
  KLMOD(YDTFP%CLF%ICOD)=2
ENDIF
IF (YS%LACTIVE) THEN
  KLMOD(YDTFP%SN%ICOD)=2
ENDIF
IF (YR%LACTIVE) THEN
  KLMOD(YDTFP%RR%ICOD)=2
ENDIF
IF (YG%LACTIVE) THEN
  KLMOD(YDTFP%GR%ICOD)=2
ENDIF
IF (YH%LACTIVE) THEN
  KLMOD(YDTFP%HL%ICOD)=2
ENDIF
IF (YTKE%LACTIVE) THEN
  KLMOD(YDTFP%TKE%ICOD)=2
ENDIF
IF (YEFB1%LACTIVE) THEN
  KLMOD(YDTFP%EFB1%ICOD)=2
ENDIF
IF (YEFB2%LACTIVE) THEN
  KLMOD(YDTFP%EFB2%ICOD)=2
ENDIF
IF (YEFB3%LACTIVE) THEN
  KLMOD(YDTFP%EFB3%ICOD)=2
ENDIF
IF (YO3%LACTIVE) THEN
  KLMOD(YDTFP%O3MX%ICOD)=2
ENDIF
IF (YCPF%LACTIVE) THEN
  KLMOD(YDTFP%CPF%ICOD)=2
ENDIF
IF (YSPF%LACTIVE) THEN
  KLMOD(YDTFP%SPF%ICOD)=2
ENDIF
! Prognostic convection
IF (YDAL%LACTIVE) THEN
  KLMOD(YDTFP%DAL%ICOD)=2
ENDIF
IF (YDOM%LACTIVE) THEN
  KLMOD(YDTFP%DOM%ICOD)=2
ENDIF
IF (YUAL%LACTIVE) THEN
  KLMOD(YDTFP%UAL%ICOD)=2
ENDIF
IF (YUOM%LACTIVE) THEN
  KLMOD(YDTFP%UOM%ICOD)=2
ENDIF
IF (YUEN%LACTIVE) THEN
  KLMOD(YDTFP%UEN%ICOD)=2
ENDIF
IF (YUNEBH%LACTIVE) THEN
  KLMOD(YDTFP%UNEBH%ICOD)=2
ENDIF
IF (YTTE%LACTIVE) THEN
  KLMOD(YDTFP%TTE%ICOD)=2
ENDIF
IF (YMXL%LACTIVE) THEN
  KLMOD(YDTFP%MXL%ICOD)=2
ENDIF
IF (YSHTUR%LACTIVE) THEN
  KLMOD(YDTFP%SHTUR%ICOD)=2
ENDIF
IF (YFQTUR%LACTIVE) THEN
  KLMOD(YDTFP%FQTUR%ICOD)=2
ENDIF
IF (YFSTUR%LACTIVE) THEN
  KLMOD(YDTFP%FSTUR%ICOD)=2
ENDIF
IF (YRKTH%LACTIVE) THEN
  KLMOD(YDTFP%RKTH%ICOD)=2
ENDIF
IF (YRKTQV%LACTIVE) THEN
  KLMOD(YDTFP%RKTQV%ICOD)=2
ENDIF
IF (YRKTQC%LACTIVE) THEN
  KLMOD(YDTFP%RKTQC%ICOD)=2
ENDIF
IF(YLRCH4%LACTIVE) THEN
  KLMOD(YDTFP%LRCH4%ICOD)=2
ENDIF
IF (YLCONV%LACTIVE) THEN
  KLMOD(YDTFP%LCONV%ICOD)=2
ENDIF
IF (YICONV%LACTIVE) THEN
  KLMOD(YDTFP%ICONV%ICOD)=2
ENDIF
IF (YRCONV%LACTIVE) THEN
  KLMOD(YDTFP%RCONV%ICOD)=2
ENDIF
IF (YSCONV%LACTIVE) THEN
  KLMOD(YDTFP%SCONV%ICOD)=2
ENDIF
IF (YUAL%LACTIVE) THEN
  KLMOD(YDTFP%UAL%ICOD)=2
ENDIF
IF (YUOM%LACTIVE) THEN
  KLMOD(YDTFP%UOM%ICOD)=2
ENDIF
IF (YDAL%LACTIVE) THEN
  KLMOD(YDTFP%DAL%ICOD)=2
ENDIF
IF (YDOM%LACTIVE) THEN
  KLMOD(YDTFP%DOM%ICOD)=2
ENDIF
DO JVAR=1,NERA40
  KLMOD(YDTFP%ERA40(JVAR)%ICOD)=2
ENDDO
DO JVAR=1,NNOGW
  KLMOD(YDTFP%NOGW(JVAR)%ICOD)=2
ENDDO
DO JVAR=1,NEDRP
  KLMOD(YDTFP%EDRP(JVAR)%ICOD)=2
ENDDO
DO JVAR=1,NAEROUT
  KLMOD(YDTFP%AEROUT(JVAR)%ICOD)=2
ENDDO
DO JVAR=1,NUVP
  KLMOD(YDTFP%UVP(JVAR)%ICOD)=2
ENDDO
IF (NEMIS3D > 0) THEN
  IF (NEMIS3D <= JPOSEMIS3D) THEN
    DO JVAR=1,NEMIS3D
      KLMOD(YDTFP%EMIS3D(JVAR)%ICOD)=2
    ENDDO
  ELSE
    CALL ABOR1('SUFPILMOD : TOO MANY EMIS3D GFLs FOR POST-PROCESSING')
  ENDIF
ENDIF
IF (NGHG > 0) THEN
  IF (NGHG <= JPOSGHG) THEN
    DO JVAR=1,NGHG
      KLMOD(YDTFP%GHG(JVAR)%ICOD)=2
    ENDDO
  ELSE
    CALL ABOR1('SUFPILMOD : TOO MANY GHG GFLs FOR POST-PROCESSING')
  ENDIF
ENDIF
IF (NGFL_EZDIAG > 0) THEN
  IF (NGFL_EZDIAG <= JPOSEZDIAG) THEN
    DO JVAR=1,NGFL_EZDIAG
      KLMOD(YDTFP%EZDIAG(JVAR)%ICOD)=2
    ENDDO
  ELSE
    CALL ABOR1('SUFPILMOD : TOO MANY EZDIAG GFLs FOR POST-PROCESSING')
  ENDIF
ENDIF
IF (NAERO > 0) THEN
  IF (NAERO <= JPOSAERO) THEN
    DO JVAR=1,NAERO
      KLMOD(YDTFP%AERO(JVAR)%ICOD)=2
    ENDDO
  ELSE
    CALL ABOR1('SUFPILMOD : TOO MANY AEROSOL GFLs FOR POST-PROCESSING')
  ENDIF
ENDIF
IF (NCHEM > 0) THEN
  IF (NCHEM <= JPOSCHEM) THEN
    DO JVAR=1,NCHEM
      KLMOD(YDTFP%CHEM(JVAR)%ICOD)=2
    ENDDO
  ELSE
    CALL ABOR1('SUFPILMOD : TOO MANY CHEM  GFLs FOR POST-PROCESSING')
  ENDIF
ENDIF
IF (NGFL_EXT > 0) THEN
  IF (NGFL_EXT <= JPOSSCVA) THEN
    DO JVAR=1,NGFL_EXT
      KLMOD(YDTFP%EXT(JVAR)%ICOD)=2
    ENDDO
  ELSE
    CALL ABOR1('SUFPILMOD : TOO MANY EXTRA GFL FOR POST-PROCESSING')
  ENDIF
ENDIF
IF (KCUFNR >=1) THEN
  KLMOD(YDTFP%CUF1%ICOD)=1
ENDIF
IF (KCUFNR >=2) THEN
  KLMOD(YDTFP%CUF2%ICOD)=1
ENDIF
IF (KCUFNR >=3) THEN
  KLMOD(YDTFP%CUF3%ICOD)=1
ENDIF
IF (KCUFNR >=4) THEN
  KLMOD(YDTFP%CUF4%ICOD)=1
ENDIF
IF (KCUFNR >=5) THEN
  KLMOD(YDTFP%CUF5%ICOD)=1
ENDIF

!*       2.4 Request of model primitive variables for the post-processing

YDQTYPE%IFIT=0
DO J=1, JPOSDYN
  YDQTYPE%ISF(J)=0
  YDQTYPE%LL(J)=(KLMOD(J) >= 1)
  IF (KLMOD(J) >=2) THEN
    YDQTYPE%ILEV(J)=KFLEVG
  ELSE
    YDQTYPE%ILEV(J)=KLMOD(J)
  ENDIF
  DO JLEV=1,YDQTYPE%ILEV(J)
    YDQTYPE%ILVP(JLEV,J)=JLEV
    YDQTYPE%IDOM(JLEV,J)=1
    YDQTYPE%IDMP(1,JLEV,J)=1
  ENDDO
ENDDO
YDQTYPE%NFPOSDYN=COUNT(YDQTYPE%LL(1:JPOSDYN))
IJ=0
DO J=1,JPOSDYN
  IF (YDQTYPE%LL(J)) THEN
    IJ=IJ+1
    YDQTYPE%NFPTRDYN(IJ)=J
  ENDIF
ENDDO

!     ------------------------------------------------------------------ 
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPILMOD',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPILMOD
