! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

!OCL  NOPREEX
SUBROUTINE SUGEM2(YDGEOMETRY)

!**** *SUGEM2*  - Initialize geometry parameters - part 2

!     Purpose.
!     --------
!        Initialize geometry
!        In particuliar, fills YRGSGEOM and YRCSGEOM

!**   Interface.
!     ----------
!        *CALL* *SUGEM2

!        Explicit arguments :
!        --------------------
!        None

!        Implicit arguments :
!        --------------------
!        YOMGEM

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!        None

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Mats Hamrud and Philippe Courtier  *ECMWF*
!      Original : 87-10-15

!     Modifications.
!     --------------
!      Modified 03-08-25 by F. Vana: Geographical correction for SLHD
!      Modified 06-06-08 by F. Vana: Consistent setting of SLHDP with LAM
!      Modified 05-09-12 by A. Alias : GMGEC modif. introduced
!      S. Tyteca  - new diagnostics
!      P. Marquet - Cloud Forcing diagnostics
!      G.Mozdzynski (Feb 2011): OOPS cleaning, use of derived types TGSGEOM, TCSGEOM and TCSGLEG
!      K. Yessad (Jul 2011): all YRGSGEOM and YRCSGEOM attributes now set-up there.
!      K. Yessad (jul 2011): reorder calculations for better consistency LAM/global model.
!      K. Yessad (dec 2011): ensure consistency with LAM model (comments).
!      R. El Khatib 13-Mar-2012 : let YRCSGEOM(IBL)%RINDX and
!                                 YRCSGEOM(IBL)%RINDY point somewhere for Arpege 
!      K. Yessad (June 2013): YOMGCO arrays allocated in a new routine SUALGCO.
!      T. Wilhelmsson and K. Yessad (Oct 2013) Geometry and setup refactoring.
!      F. Vana 11-Jul-2019: All cast in double precision to maintain consistency across SP and DP.
!      M. Diamantakis 2020: Add cartesian geometry option for departure point iterations
!     ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST   , ONLY : RPI, ROMEGA, RA
USE YOMLUN   , ONLY : NULOUT
USE YOMMP0   , ONLY : LOUTPUT, MY_REGION_EW

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
INTEGER(KIND=JPIM) :: IENDLAT, IGLG, IROF, ISTLAT, JGL, JLON
INTEGER(KIND=JPIM) :: JKGLO, IEND, IBL

REAL(KIND=JPRD) :: ZZRCORI   (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZRCORIC  (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGEMU    (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGSQM2   (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGELAT   (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGELAM   (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGESLO   (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGECLO   (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGM      (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGOMVRL  (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGOMVRM  (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGNORDL  (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGNORDM  (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGNORDLCL(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGNORDMCL(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGNORDMCM(YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZGAW     (YDGEOMETRY%YRGEM%NGPTOT)
INTEGER(KIND=JPIM) :: IIGPLAT   (YDGEOMETRY%YRGEM%NGPTOT)
INTEGER(KIND=JPIM) :: IIUNIQUEGP(YDGEOMETRY%YRGEM%NGPTOT)

REAL(KIND=JPRD) :: ZZRCOLON  (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZRSILON  (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZRINDX   (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZRINDY   (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZRATATH  (YDGEOMETRY%YRGEM%NGPTOT)
REAL(KIND=JPRD) :: ZZRATATX  (YDGEOMETRY%YRGEM%NGPTOT)

REAL(KIND=JPRD), ALLOCATABLE    :: ZZXCO(:), ZZYCO(:), ZZZCO(:)

REAL(KIND=JPRD) :: Z2C, Z2OMR, ZA, ZB, ZC2M1, ZC2P1, ZCA1, ZCLABNE, ZCLAC,&
 & ZCLAP, ZCLO, ZCLOC, ZCLOP, ZD, ZGEMU,&
 & ZGM, ZGOMVRL, ZGSQM2, ZINCR, ZMUDEN,&
 & ZMUNUM, ZQM2, ZRCORI, ZRCORIC, ZSA1, ZSLABNE, ZSLAC, ZSLAP,&
 & ZSLO, ZSLOC, ZSLOP, ZTLABNE, ZUS2C, ZUSA, ZUSCLABNE  

REAL(KIND=JPRD) :: ZLON

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "abor1.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUGEM2',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP,  &
 & YDCSGLEG=>YDGEOMETRY%YRCSGLEG, YDVAB=>YDGEOMETRY%YRVAB,  &
 & YDVETA=>YDGEOMETRY%YRVETA, YDVFE=>YDGEOMETRY%YRVFE, YDSTA=>YDGEOMETRY%YRSTA, &
 & YDLAP=>YDGEOMETRY%YRLAP, &
 & YDSPGEOM=>YDGEOMETRY%YSPGEOM)
ASSOCIATE(NDGENL=>YDDIM%NDGENL, NDGLG=>YDDIM%NDGLG, NDLON=>YDDIM%NDLON, &
 & NGPBLKS=>YDDIM%NGPBLKS, NPROMA=>YDDIM%NPROMA, NSMAX=>YDDIM%NSMAX, &
 & NGPTOT=>YDGEM%NGPTOT, NLOENG=>YDGEM%NLOENG, NSTAGP=>YDGEM%NSTAGP, &
 & NSTTYP=>YDGEM%NSTTYP, RC2M1=>YDGEM%RC2M1, RC2P1=>YDGEM%RC2P1, &
 & RLOCEN=>YDGEM%RLOCEN, RMUCEN=>YDGEM%RMUCEN, RSTRET=>YDGEM%RSTRET, &
 & SLHDP=>YDGEM%SLHDP, &
 & MYLATS=>YDMP%MYLATS, NONL=>YDMP%NONL, NPTRFLOFF=>YDMP%NPTRFLOFF, &
 & NSTA=>YDMP%NSTA)
!     ------------------------------------------------------------------

!*       2.    Initialize part of YOMGC: YRGSGEOM
!              ----------------------------------

! ky: the LAM counterpart of these calculations is in part 7 of SUEGEM2.
!     Note that in LAM models YRGSGEOM should be computed before YRCSGEOM.

ISTLAT=1
IENDLAT=NDGENL

ALLOCATE(ZZXCO(YDGEOMETRY%YRGEM%NGPTOT))
ALLOCATE(ZZYCO(YDGEOMETRY%YRGEM%NGPTOT))
ALLOCATE(ZZZCO(YDGEOMETRY%YRGEM%NGPTOT))

IF(NSTTYP == 1)THEN

  !     2.1  Case NSTTYP=1.

  IF (LOUTPUT) WRITE(UNIT=NULOUT,FMT='('' ******** NSTTYP=1'')')
  ZUS2C = 0.5_JPRD / RSTRET
  ZUSA  = 1.0_JPRD/RA
  CALL GSTATS(1405,0)
!$OMP PARALLEL DO SCHEDULE(STATIC)&
!$OMP&PRIVATE(JGL,IGLG,ZINCR,ZLON,ZMUNUM,ZMUDEN,ZGEMU,&
!$OMP& ZGSQM2,ZGM,ZRCORI,ZRCORIC,ZGOMVRL,IROF,JLON)
  DO JGL = ISTLAT,IENDLAT
    IGLG=MYLATS(JGL)
    IF ((IGLG <= 0).OR.(IGLG >= NDGLG+1)) THEN
      ZINCR=RPI
    ELSE
      ZINCR=0._JPRD
    ENDIF
    ZMUNUM = RC2M1 + RC2P1 * YDCSGLEG%RMU(IGLG)
    ZMUDEN = RC2P1 + RC2M1 * YDCSGLEG%RMU(IGLG)
    ZGEMU  = ZMUNUM / ZMUDEN
    ZGSQM2 = SQRT(1.0_JPRD-ZGEMU*ZGEMU)
    ZGM    = ZMUDEN*ZUS2C
    ZRCORI = 2.0_JPRD*ROMEGA*ZGEMU
    ZRCORIC= 2.0_JPRD*ROMEGA*ZGSQM2
    ZGOMVRL= 2.0_JPRD*ROMEGA*RA*ZGSQM2
    IROF=NSTAGP(JGL)-1
    DO JLON = NSTA(NPTRFLOFF+JGL,MY_REGION_EW),&
       & NSTA(NPTRFLOFF+JGL,MY_REGION_EW)+NONL(NPTRFLOFF+JGL,MY_REGION_EW)-1  
      IROF=IROF+1
      ZZRCORI(IROF)=ZRCORI
      ZZRCORIC(IROF)=ZRCORIC
      ZZGEMU (IROF)=ZGEMU
      ZZGSQM2(IROF)=ZGSQM2
      ZLON = REAL(ZINCR,JPRD)+REAL(RPI,JPRD)*REAL(2*(JLON-1),JPRD)/REAL(NLOENG(IGLG),JPRD) 
      ZZGELAM(IROF)=ZLON
      ZZGELAT(IROF)=ASIN(ZGEMU)
      ZZGECLO(IROF)=COS(ZLON)
      ZZGESLO(IROF)=SIN(ZLON)
      ZZGM   (IROF)=ZGM
      IIUNIQUEGP(IROF)=NDLON*(IGLG-1)+JLON
      IIGPLAT(IROF)=IGLG
      ZZGOMVRL(IROF)=ZGOMVRL
      ZZGOMVRM(IROF)=0.0_JPRD
      ZZGNORDL(IROF)=0.0_JPRD
      ZZGNORDM(IROF)=1.0_JPRD
      ZZGNORDLCL(IROF)=0.0_JPRD
      ZZGNORDMCL(IROF)=0.0_JPRD
      ZZGNORDMCM(IROF)=-ZUSA*ZGEMU
      ZZGAW(IROF)=YDCSGLEG%RW(IGLG)/(REAL(NLOENG(IGLG),JPRD)*ZZGM(IROF)**2)
      ZZXCO(IROF)=RA*ZZGSQM2(IROF)*ZZGECLO(IROF)
      ZZYCO(IROF)=RA*ZZGSQM2(IROF)*ZZGESLO(IROF)
      ZZZCO(IROF)=RA*ZZGEMU(IROF)
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
  CALL GSTATS(1405,1)

ELSEIF(NSTTYP == 2)THEN

  !     2.2  Case NSTTYP=2.

  IF (LOUTPUT) WRITE(UNIT=NULOUT,FMT='('' ******** NSTTYP=2'')')

  Z2C   = 2.0_JPRD * RSTRET
  ZC2P1 = RSTRET* RSTRET+1.0_JPRD
  ZC2M1 = RSTRET* RSTRET-1.0_JPRD
  ZSLAP = RMUCEN
  ZCLAP = SQRT(1.0_JPRD - ZSLAP*ZSLAP)
  ZSLOP = SIN(RLOCEN)
  ZCLOP = COS(RLOCEN)
  Z2OMR = 2.0_JPRD*ROMEGA*RA
  ZUSA  = 1.0_JPRD/RA

  DO  JGL = ISTLAT,IENDLAT
    IGLG  = MYLATS(JGL)
    IF ((IGLG <= 0).OR.(IGLG >= NDGLG+1)) THEN
      ZINCR=RPI
    ELSE
      ZINCR=0._JPRD
    ENDIF
    ZSLAC = YDCSGLEG%RMU(IGLG)
    ZCLAC = SQRT(1.0_JPRD-YDCSGLEG%RMU(IGLG)*YDCSGLEG%RMU(IGLG))
    ZA    = 1.0_JPRD / (ZC2P1 + ZC2M1 * ZSLAC)
    ZGM   = (ZC2P1 + ZC2M1 * ZSLAC) / Z2C
    ZB    = ZC2M1 + ZC2P1 * ZSLAC
    ! * "theta_bne" is the latitude on the tilted unstretched sphere associated
    !   with the computational sphere; one computes ZCLABNE=cos(theta_bne),
    !   ZSLABNE=sin(theta_bne), ZTLABNE=tan(theta_bne),
    !   ZUSCLABNE=1/cos(theta_bne).
    ZCLABNE=ZCLAC/ZGM
    ZUSCLABNE=1.0_JPRD/ZCLABNE
    ZSLABNE=ZB*ZA
    ZTLABNE=ZSLABNE/ZCLABNE

    IROF=NSTAGP(JGL)-1
    DO JLON = NSTA(NPTRFLOFF+JGL,MY_REGION_EW),&
       & NSTA(NPTRFLOFF+JGL,MY_REGION_EW)+NONL(NPTRFLOFF+JGL,MY_REGION_EW)-1  
      IROF=IROF+1
      ZLON = REAL(ZINCR,JPRD)+REAL(RPI,JPRD)*REAL(2*(JLON-1),JPRD)/REAL(NLOENG(IGLG),JPRD)
      ZSLOC= SIN(ZLON)
      ZCLOC= COS(ZLON)
      ZZGEMU(IROF)  = ZA*(Z2C*ZCLAP*ZCLAC*ZCLOC+ZB*ZSLAP)
      ZZGELAT(IROF) = ASIN(ZZGEMU(IROF))
      ZZGSQM2(IROF) = SQRT(1.0_JPRD-ZZGEMU(IROF)*ZZGEMU(IROF))
      ZQM2        = 1.0_JPRD / ZZGSQM2(IROF)
      ZZRCORI(IROF) = 2.0_JPRD * ROMEGA * ZZGEMU(IROF)
      ZZRCORIC(IROF)= 2.0_JPRD * ROMEGA * ZZGSQM2(IROF)
      ZZGM   (IROF) = ZGM
      IIUNIQUEGP(IROF)=NDLON*(IGLG-1)+JLON
      IIGPLAT(IROF)= IGLG

      ZD = ZA * ZQM2
      ZCLO = ZD *( ZB*ZCLAP*ZCLOP - Z2C*ZCLAC*&
       & (ZSLAP*ZCLOC*ZCLOP-ZSLOP*ZSLOC) )  
      ZSLO = ZD *( ZB*ZCLAP*ZSLOP - Z2C*ZCLAC*&
       & (ZSLAP*ZCLOC*ZSLOP+ZCLOP*ZSLOC) )  
      ZSLO = MIN(1.0_JPRD,MAX(-1.0_JPRD,ZSLO))
      ZZGECLO(IROF) = ZCLO
      ZZGESLO(IROF) = ZSLO
      ZZGELAM(IROF) = SIGN(1.0_JPRD,ZCLO) * ASIN(ZSLO) - RPI *&
       & ( MIN(SIGN(1.0_JPRD,ZCLO),0.0_JPRD) + MIN(SIGN(2.0_JPRD,ZSLO),0.0_JPRD)&
       & +MIN(SIGN(1.0_JPRD,ZCLO),0.0_JPRD) * MIN(SIGN(2.0_JPRD,ZSLO),0.0_JPRD) )  
      ZCA1 = (Z2C*ZSLAP*ZCLAC-ZB*ZCLAP*ZCLOC) * ZA
      ZSA1 = -ZCLAP*ZSLOC
      ZZGOMVRL(IROF) =  Z2OMR * ZCA1
      ZZGOMVRM(IROF) = -Z2OMR * ZSA1
      ZZGNORDL(IROF) = ZSA1 * ZQM2
      ZZGNORDM(IROF) = ZCA1 * ZQM2
      ZZGAW(IROF)=YDCSGLEG%RW(IGLG)/(REAL(NLOENG(IGLG),JPRD)*ZZGM(IROF)**2)
      ZZGNORDLCL(IROF)=-(ZUSA*ZCLAP*ZUSCLABNE)*ZCLOC
      ZZGNORDMCL(IROF)=(ZUSA*ZCLAP*ZTLABNE)*ZSLOC
      ZZGNORDMCM(IROF)=-ZUSA*(ZSLAP*ZSLABNE+ZCLAP*ZCLABNE*ZCLOC)
      ZZXCO(IROF)=RA*ZZGSQM2(IROF)*ZCLO
      ZZYCO(IROF)=RA*ZZGSQM2(IROF)*ZSLO
      ZZZCO(IROF)=RA*ZZGEMU(IROF)
    ENDDO
  ENDDO

ELSE

  !     2.3  Case NSTTYP >2 or <1.

  WRITE(UNIT=NULOUT,FMT='('' ERROR NSTTYP '')')
  CALL ABOR1(' SUGEM2 ')

ENDIF

! Allocate YRGSGEOM_NB:
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%RCORI(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%RCORIC(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GEMU(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GSQM2(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GELAM(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GELAT(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GECLO(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GESLO(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GM(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GMAPPA(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GOMVRL(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GOMVRM(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GNORDL(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GNORDM(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GNORDLCL(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GNORDMCL(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GNORDMCM(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GAW(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%NGPLAT(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%NUNIQUEGP(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GEXCO(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GEYCO(NGPTOT))
ALLOCATE(YDGEOMETRY%YRGSGEOM_NB%GEZCO(NGPTOT))

! Allocate natively NPROMA-blocked copy of geometry
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%RCORI(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%RCORIC(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GEMU(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GSQM2(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GELAM(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GELAT(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GECLO(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GESLO(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GM(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GMAPPA(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GOMVRL(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GOMVRM(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GNORDL(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GNORDM(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GNORDLCL(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GNORDMCL(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GNORDMCM(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GAW(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%NGPLAT(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%NUNIQUEGP(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GEXCO(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GEYCO(NPROMA,NGPBLKS))
ALLOCATE(YDGEOMETRY%YRGSGEOM_B%GEZCO(NPROMA,NGPBLKS))

! Allocate YRGSGEOM:
ALLOCATE(YDGEOMETRY%YRGSGEOM(NGPBLKS))

! Copy items to non-blocked form of YRGSGEOM
YDGEOMETRY%YRGSGEOM_NB%RCORI    (:)=REAL(ZZRCORI   (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%RCORIC   (:)=REAL(ZZRCORIC  (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GEMU     (:)=REAL(ZZGEMU    (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GSQM2    (:)=REAL(ZZGSQM2   (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GELAM    (:)=REAL(ZZGELAM   (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GELAT    (:)=REAL(ZZGELAT   (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GECLO    (:)=REAL(ZZGECLO   (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GESLO    (:)=REAL(ZZGESLO   (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GM       (:)=REAL(ZZGM      (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GMAPPA   (:)=REAL(RSTRET*RSTRET,JPRB)
YDGEOMETRY%YRGSGEOM_NB%GOMVRL   (:)=REAL(ZZGOMVRL  (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GOMVRM   (:)=REAL(ZZGOMVRM  (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GNORDL   (:)=REAL(ZZGNORDL  (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GNORDM   (:)=REAL(ZZGNORDM  (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GNORDLCL (:)=REAL(ZZGNORDLCL(:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GNORDMCL (:)=REAL(ZZGNORDMCL(:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GNORDMCM (:)=REAL(ZZGNORDMCM(:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GAW      (:)=REAL(ZZGAW     (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%NGPLAT   (:)=IIGPLAT   (:)
YDGEOMETRY%YRGSGEOM_NB%NUNIQUEGP(:)=IIUNIQUEGP(:)
YDGEOMETRY%YRGSGEOM_NB%GEXCO  (:)=REAL(ZZXCO     (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GEYCO  (:)=REAL(ZZYCO     (:),JPRB)
YDGEOMETRY%YRGSGEOM_NB%GEZCO  (:)=REAL(ZZZCO     (:),JPRB)

! Point to items initialised above
DO JKGLO=1,NGPTOT,NPROMA
  IEND=MIN(NPROMA,NGPTOT-JKGLO+1)
  IBL=(JKGLO-1)/NPROMA+1
  YDGEOMETRY%YRGSGEOM(IBL)%RCORI    =>YDGEOMETRY%YRGSGEOM_NB%RCORI    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%RCORIC   =>YDGEOMETRY%YRGSGEOM_NB%RCORIC   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GEMU     =>YDGEOMETRY%YRGSGEOM_NB%GEMU     (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GSQM2    =>YDGEOMETRY%YRGSGEOM_NB%GSQM2    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GELAM    =>YDGEOMETRY%YRGSGEOM_NB%GELAM    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GELAT    =>YDGEOMETRY%YRGSGEOM_NB%GELAT    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GECLO    =>YDGEOMETRY%YRGSGEOM_NB%GECLO    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GESLO    =>YDGEOMETRY%YRGSGEOM_NB%GESLO    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GM       =>YDGEOMETRY%YRGSGEOM_NB%GM       (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GMAPPA   =>YDGEOMETRY%YRGSGEOM_NB%GMAPPA   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GOMVRL   =>YDGEOMETRY%YRGSGEOM_NB%GOMVRL   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GOMVRM   =>YDGEOMETRY%YRGSGEOM_NB%GOMVRM   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GNORDL   =>YDGEOMETRY%YRGSGEOM_NB%GNORDL   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GNORDM   =>YDGEOMETRY%YRGSGEOM_NB%GNORDM   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GNORDLCL =>YDGEOMETRY%YRGSGEOM_NB%GNORDLCL (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GNORDMCL =>YDGEOMETRY%YRGSGEOM_NB%GNORDMCL (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GNORDMCM =>YDGEOMETRY%YRGSGEOM_NB%GNORDMCM (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GAW      =>YDGEOMETRY%YRGSGEOM_NB%GAW      (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%NGPLAT   =>YDGEOMETRY%YRGSGEOM_NB%NGPLAT   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%NUNIQUEGP=>YDGEOMETRY%YRGSGEOM_NB%NUNIQUEGP(JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GEXCO  =>YDGEOMETRY%YRGSGEOM_NB%GEXCO    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GEYCO  =>YDGEOMETRY%YRGSGEOM_NB%GEYCO    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM(IBL)%GEZCO  =>YDGEOMETRY%YRGSGEOM_NB%GEZCO    (JKGLO:JKGLO+IEND-1)
ENDDO

! Copy blocks into native NPROMA-allocated arrays
DO JKGLO=1,NGPTOT,NPROMA
  IEND=MIN(NPROMA,NGPTOT-JKGLO+1)
  IBL=(JKGLO-1)/NPROMA+1

  YDGEOMETRY%YRGSGEOM_B%RCORI(1:IEND,IBL)     = YDGEOMETRY%YRGSGEOM_NB%RCORI    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%RCORIC(1:IEND,IBL)    = YDGEOMETRY%YRGSGEOM_NB%RCORIC   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GEMU(1:IEND,IBL)      = YDGEOMETRY%YRGSGEOM_NB%GEMU     (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GSQM2(1:IEND,IBL)     = YDGEOMETRY%YRGSGEOM_NB%GSQM2    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GELAM(1:IEND,IBL)     = YDGEOMETRY%YRGSGEOM_NB%GELAM    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GELAT(1:IEND,IBL)     = YDGEOMETRY%YRGSGEOM_NB%GELAT    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GECLO(1:IEND,IBL)     = YDGEOMETRY%YRGSGEOM_NB%GECLO    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GESLO(1:IEND,IBL)     = YDGEOMETRY%YRGSGEOM_NB%GESLO    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GM(1:IEND,IBL)        = YDGEOMETRY%YRGSGEOM_NB%GM       (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GMAPPA(1:IEND,IBL)    = YDGEOMETRY%YRGSGEOM_NB%GMAPPA   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GOMVRL(1:IEND,IBL)    = YDGEOMETRY%YRGSGEOM_NB%GOMVRL   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GOMVRM(1:IEND,IBL)    = YDGEOMETRY%YRGSGEOM_NB%GOMVRM   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GNORDL(1:IEND,IBL)    = YDGEOMETRY%YRGSGEOM_NB%GNORDL   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GNORDM(1:IEND,IBL)    = YDGEOMETRY%YRGSGEOM_NB%GNORDM   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GNORDLCL(1:IEND,IBL)  = YDGEOMETRY%YRGSGEOM_NB%GNORDLCL (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GNORDMCL(1:IEND,IBL)  = YDGEOMETRY%YRGSGEOM_NB%GNORDMCL (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GNORDMCM(1:IEND,IBL)  = YDGEOMETRY%YRGSGEOM_NB%GNORDMCM (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GAW(1:IEND,IBL)       = YDGEOMETRY%YRGSGEOM_NB%GAW      (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%NGPLAT(1:IEND,IBL)    = YDGEOMETRY%YRGSGEOM_NB%NGPLAT   (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%NUNIQUEGP(1:IEND,IBL) = YDGEOMETRY%YRGSGEOM_NB%NUNIQUEGP(JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GEXCO(1:IEND,IBL)     = YDGEOMETRY%YRGSGEOM_NB%GEXCO    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GEYCO(1:IEND,IBL)     = YDGEOMETRY%YRGSGEOM_NB%GEYCO    (JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRGSGEOM_B%GEZCO(1:IEND,IBL)     = YDGEOMETRY%YRGSGEOM_NB%GEZCO    (JKGLO:JKGLO+IEND-1)
ENDDO

!     ------------------------------------------------------------------

!*       3.    Initialize YRCSGEOM
!              --------------------

! ky: the LAM counterpart of these calculations is in part 8 of SUEGEM2.
!     RINDX and RINDY are required only if LRPLANE=T.
! REK : unfortunately RINDX and RINDY are passed in subroutines as pointer, so
!       they have to point to a well-known address.
!       Therefore it is better to compute them anyway (it is cheap).

CALL GSTATS(1406,0)
!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(JGL,IGLG,ZINCR,IROF,JLON,ZLON)
DO JGL = ISTLAT,IENDLAT
  IGLG=MYLATS(JGL)
  IF ((IGLG <= 0).OR.(IGLG >= NDGLG+1)) THEN
    ZINCR=RPI
  ELSE
    ZINCR=0._JPRD
  ENDIF
  IROF=NSTAGP(JGL)-1
  DO JLON=NSTA(NPTRFLOFF+JGL,MY_REGION_EW),NSTA(NPTRFLOFF+JGL,MY_REGION_EW)&
     & +NONL(NPTRFLOFF+JGL,MY_REGION_EW)-1  
    IROF=IROF+1
    ZLON = REAL(ZINCR,JPRD)+REAL(RPI,JPRD)*REAL(2*(JLON-1),JPRD)/REAL(NLOENG(IGLG),JPRD)
    ZZRCOLON(IROF)=COS(ZLON)
    ZZRSILON(IROF)=SIN(ZLON)
    ZZRINDX(IROF)=REAL(JLON,JPRD)
    ZZRINDY(IROF)=REAL(IGLG,JPRD)
    ZZRATATH(IROF)=(RC2M1+YDCSGLEG%RMU(IGLG)*RC2P1)/(RSTRET*RA*YDCSGLEG%RSQM2(IGLG))
    ZZRATATX(IROF)=0.0_JPRD
  ENDDO
ENDDO
!$OMP END PARALLEL DO
CALL GSTATS(1406,1)

! Allocate YRCSGEOM_NB:
ALLOCATE(YDGEOMETRY%YRCSGEOM_NB%RCOLON(NGPTOT))
ALLOCATE(YDGEOMETRY%YRCSGEOM_NB%RSILON(NGPTOT))
ALLOCATE(YDGEOMETRY%YRCSGEOM_NB%RINDX(NGPTOT))
ALLOCATE(YDGEOMETRY%YRCSGEOM_NB%RINDY(NGPTOT))
ALLOCATE(YDGEOMETRY%YRCSGEOM_NB%RATATH(NGPTOT))
ALLOCATE(YDGEOMETRY%YRCSGEOM_NB%RATATX(NGPTOT))

! Allocate YRCSGEOM:
ALLOCATE(YDGEOMETRY%YRCSGEOM(NGPBLKS))

! Copy items to non-blocked form of YRCSGEOM
YDGEOMETRY%YRCSGEOM_NB%RCOLON(:)=REAL(ZZRCOLON(:),JPRB)
YDGEOMETRY%YRCSGEOM_NB%RSILON(:)=REAL(ZZRSILON(:),JPRB)
YDGEOMETRY%YRCSGEOM_NB%RINDX(:)=REAL(ZZRINDX(:),JPRB)
YDGEOMETRY%YRCSGEOM_NB%RINDY(:)=REAL(ZZRINDY(:),JPRB)
YDGEOMETRY%YRCSGEOM_NB%RATATH(:)=REAL(ZZRATATH(:),JPRB)
YDGEOMETRY%YRCSGEOM_NB%RATATX(:)=REAL(ZZRATATX(:),JPRB)

! Point to items in YRCSGEOM
DO JKGLO=1,NGPTOT,NPROMA
  IEND=MIN(NPROMA,NGPTOT-JKGLO+1)
  IBL=(JKGLO-1)/NPROMA+1
  YDGEOMETRY%YRCSGEOM(IBL)%RCOLON=>YDGEOMETRY%YRCSGEOM_NB%RCOLON(JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRCSGEOM(IBL)%RSILON=>YDGEOMETRY%YRCSGEOM_NB%RSILON(JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRCSGEOM(IBL)%RINDX =>YDGEOMETRY%YRCSGEOM_NB%RINDX(JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRCSGEOM(IBL)%RINDY =>YDGEOMETRY%YRCSGEOM_NB%RINDY(JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRCSGEOM(IBL)%RATATH=>YDGEOMETRY%YRCSGEOM_NB%RATATH(JKGLO:JKGLO+IEND-1)
  YDGEOMETRY%YRCSGEOM(IBL)%RATATX=>YDGEOMETRY%YRCSGEOM_NB%RATATX(JKGLO:JKGLO+IEND-1)
ENDDO

DEALLOCATE(ZZXCO)
DEALLOCATE(ZZYCO)
DEALLOCATE(ZZZCO)
!     ------------------------------------------------------------------

!*       4.    Resolution correction for SLHD.
!              -------------------------------

! * This formula should be 2*RPI*SQRT(RA*RA/(NSMAX*(NSMAX+1)))
!   For the consistency reasons with the existing LAM tuning
!   it has been multiplied by SQRT(2.)
!   The LAM counterpart of this calculation is in part 9 of SUEGEM2:

SLHDP=REAL(RPI*SQRT(8.0_JPRD*RA*RA/(NSMAX*(NSMAX+1))),JPRB)

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUGEM2',1,ZHOOK_HANDLE)
END SUBROUTINE SUGEM2
