! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUPP(YGFL,YDPHY,YDEAERATM)

!**** *SUPP*   - Sets-up modules YOMPPC

!     Purpose.
!     --------
!         Sets-up modules YOMPPC

!**   Interface.
!     ----------
!        *CALL* *SUPP(...)

!        Explicit arguments :
!        -------------------

!        Implicit arguments :
!        --------------------
!         output modules: YOMPPC

!     Method.
!     -------
!        See documentation

!     Externals.   None.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Mats Hamrud and Philippe Courtier  *ECMWF*
!      Original : 89-01-19

!     Modifications.
!     --------------
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      A.Tompkins    11-02-04    Add TCLW, TCIW
!      S. Serrar    : 05-09-26 total colum CO2 and SF6 for postprocessing
!      R.Engelen      02-Jun-06   GHG generic fields for TC
!      N. Wedi and K. Yessad (Jan 2008): different dev for NH model and PC scheme
!      P. Lopez : 26-Jun-2009 Added 100m wind components
!      P. Lopez : 22-Oct-2008 Added ducting diagnostic fields
!      R. El Khatib   12-Jan-2009 Bugfix on reading the namelist
!      JJMorcrette 20091201 Total and clear-sky direct SW radiation flux at surface 
!      H. Hersbach   04-Dec-2009 10-m neutral wind and friction velocity
!      K. Yessad (Jan 2010): remove useless variables.
!      R.Forbes      01-Mar-2010 Add TCRW, TCSW diagnostics
!      JJMorcrette 20100212 PP of CBASE, 0DEGL and VISIH
!      P. Bechtold   09-Aug-2011 Add CIN, Convective Indices
!      M Ahlgrimm 31 Oct 2011 Clear-sky downward radiation at surface 
!      R. El Khatib : 01-Mar-2012 LFPOS => LECFPOS
!      A. Inness     28-Mar-2012 Add Total column CHEM fields
!      JJMorcrette 20130213 PP optical depths GEMS/MACC aerosols
!      G. Balsamo :  23-Jun-2013 Added lake prognostic fields
!      R. Forbes   01-Mar-2014 Added precip rates/type, TCSLW,I10FG,PEV
!      T. Wilhelmsson and K. Yessad (Oct 2013) Geometry and setup refactoring.
!      JJMorcrette 20130730 15-variable aerosol model
!      F. Vana     12-Dec-2014  Fix for single precision
!      R. Forbes   10-Jan-2015 Added FZRA freezing rain
!      P. Lopez    16-Nov-2015 Added lightning density fields
!      P. Bechtold 10-Nov-2015 Add CBASEA, CTOPC, ZTWETB0,1 and set NO2DGG=JPO2DGG
!      A. Bozzo    Jan 2016 Added surface shortwave direct beam 
!      R. Forbes   01-Apr-2017 Added TPR total precipitation rate
!      R. El Khatib : 07-Mar-2016 protection against simultaneous write of dirlst to disk
!      R. El Khatib 07-Mar-2016 Pruning of ISP
!      R. Forbes    May-2022  Added precip-type most-frequent and most-severe
!     ------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM     , JPRB
USE YOMHOOK  , ONLY : LHOOK    , DR_HOOK, JPHOOK
USE YOMCT0   , ONLY : LECMWF
USE YOMLUN   , ONLY : NULOUT   ,NULNAM
USE YOM_GRIB_CODES  , ONLY : NGRBBV    ,NGRBZ    ,NGRBT    ,NGRBQ    ,&
 & NGRBW    ,NGRBVIWVE,NGRBVIWVN,NGRBTCW  ,NGRBTCWV ,NGRBTCLW ,NGRBTCIW ,&
 & NGRBTCRW ,NGRBTCSW ,NGRBTCSLW,NGRBVO   ,NGRBSTL1 ,&
 & NGRBSWVL1,NGRBSD   ,NGRBSDSL ,NGRBLSP  ,NGRBCP   ,NGRBSF   ,NGRBFZRA ,&
 & NGRBBLD  ,NGRBSSHF ,NGRBSLHF ,NGRBMSL  ,NGRBLNSP ,&
 & NGRBD    ,NGRBTCC  ,NGRB10U  ,NGRB10V  ,NGRB10SI ,NGRBSP   ,&
 & NGRB2T   ,NGRB2D   ,NGRB2SH  ,&
 & NGRBSSRD ,NGRBSSRDC,NGRBSTL2 ,NGRBSWVL2,&
 & NGRBSR   ,NGRBAL   ,NGRBSTRD ,NGRBSTRDC,NGRBSSR  ,NGRBSTR  ,& 
 & NGRBTSR  ,NGRBTTR  ,NGRBEWSS ,NGRBNSSS ,NGRBE    ,NGRBPEV  ,&
 & NGRBSTL3 ,NGRBSWVL3,NGRBCCC  ,NGRBLCC  ,NGRBMCC ,&
 & NGRBHCC  ,NGRBLGWS ,NGRBMGWS ,NGRBGWD  ,NGRBSRC  ,&
 & NGRBMX2T ,NGRBMN2T ,NGRBMX2T3,NGRBMN2T3,NGRBMX2T6,NGRBMN2T6,&
 & NGRBRO   ,NGRBTCO3 ,NGRBIEWS ,&
 & NGRBINSS,NGRBISHF ,NGRBIE   ,NGRBSKT  ,&
 & NGRBSTL4 ,NGRBSWVL4,NGRBFAL  ,NGRBFSR  ,NGRBFLSR ,&
 & NGRBBLH  ,NGRBCAPE ,NGRBCAPES,NGRBMXCAP6,NGRBMXCAPS6,&
 & NGRBMUCAPE,NGRBMLCAPE50,NGRBMLCAPE100,NGRBMLCIN50,NGRBMLCIN100,NGRBMUDEPL,&
 & NGRBTROPOTP,&
 & NGRBSUND ,NGRBCBASE,NGRB0DEGL,NGRBM10DEGL,NGRBVISIH,&
 & NGRBCIN  ,NGRBKINDEX, NGRBTTINDEX      ,&
 & NGRBCBASEA,NGRBCTOPC, NGRBZTWETB0, NGRBZTWETB1    ,&
 & NGRBISTL1,NGRBISTL2,NGRBISTL3,NGRBISTL4,&
 & NGRBASN  ,NGRBRSN  ,NGRBTP   ,NGRBTSN  ,NGRBWSN   ,&
 & NGRBCI   ,NGRBSSTK ,NGRBUCUR ,NGRBVCUR ,&
 & NGRBTSRC ,NGRBTTRC ,NGRBSSRC ,NGRBSTRC ,&
 & NGRBES   ,NGRBSMLT ,NGRB10FG ,NGRB10FG3,NGRB10FG6,NGRBI10FG,NGRBLSPF, &
 & NGRBMXTPR,NGRBMNTPR,NGRBMXTPR3,NGRBMNTPR3,NGRBMXTPR6,NGRBMNTPR6,&
 & NGRBTPR  ,NGRBLSRR ,NGRBCRR  ,NGRBLSSFR,NGRBCSFR,NGRBPTYPE,NGRBILSPF,&
 & NGRB100U ,NGRB100V ,NGRB100SI,NGRB200U ,NGRB200V ,NGRB200SI,&
 & NGRB10NU ,NGRB10NV, NGRBZUST, NGRBFDIR ,NGRBCDIR ,NGRBDSRP,&
 & NGRBAODPR, NGRBAODSM, NGRBAODLG,&
 & NGRBAEODTO,NGRBAEODSS,NGRBAEODDU,NGRBAEODOM,NGRBAEODBC,NGRBAEODSU,&
 & NGRBAEODNI,NGRBAEODAM, NGRBAEODSOA, &
 & NGRBAEODVFA,NGRBAEODVSU,NGRBAEPM1 ,NGRBAEPM25,NGRBAEPM10,&
 & NGRBUVBED,NGRBUVBEDCS,&
 & NGRBDNDZN, NGRBDNDZA, NGRBDCTB, NGRBTPLB, NGRBTPLT, NGRBCLBT, NGRBCSBT, &   
 & NGRBLMLT ,NGRBLMLD ,NGRBLBLT ,&
 & NGRBLTLT ,NGRBLSHF ,NGRBLICT ,NGRBLICD, &
 & NGRBICETK, NGRBMLD, NGRBSL, NGRB20D, NGRBSSSO, &
 & NGRBCVL, NGRBCVH, NGRBTVL, NGRBTVH, &
 & NGRBLITOTI, NGRBLITOTA1, NGRBLITOTA3, NGRBLITOTA6, &
 & NGRBLICGI, NGRBLICGA1, NGRBLICGA3, NGRBLICGA6, NGRBCH4WET, &
 & NGRBPTYPEMODE1, NGRBPTYPEMODE3, NGRBPTYPEMODE6, &
 & NGRBPTYPESEVR1, NGRBPTYPESEVR3, NGRBPTYPESEVR6
USE MPL_MODULE
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMPHY   , ONLY : TPHY
USE YOEAERATM, ONLY : TEAERATM
USE YOMPPC   , ONLY : JPO2DGG   ,JPO3DSPM ,JPO3DGG  ,JPO2DSPA  ,JPO3DSPA  ,JPO3DGGA  ,&
 & M2DGGP   ,M3DSPM   ,M2DGGPL  ,M3DGGM   ,M2DSPE   ,M3DSPE   ,M3DGGE   ,& 
 & NO2DGG   ,NO3DSPM  ,NO2DGGL  ,NO3DGGM  ,NO2DSPE  ,NO3DSPE  ,NO3DGGE  ,&
 & LRSUP    ,LRSACC   ,NRSACCFRQ,NRSACCOFF

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(TPHY)        ,INTENT(INOUT) :: YDPHY
TYPE(TYPE_GFLD)   ,INTENT(INOUT) :: YGFL
TYPE(TEAERATM)    ,INTENT(IN)    :: YDEAERATM

!     ------------------------------------------------------------------

INTEGER(KIND=JPIM) :: ILAGO, INLAGO, IO3DSPM, IPAR, J

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

LOGICAL :: LLFIRST
DATA LLFIRST/.TRUE./

!     ------------------------------------------------------------------

#include "posnam.intfb.h"
#include "namppc.nam.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUPP',0,ZHOOK_HANDLE)
!     ------------------------------------------------------------------

!*       1.    Set default values of control parameters.
!              -----------------------------------------

!        1.2 Set implicit default values for LRSUP, LRSACC (YOMPPC)

LRSUP  = .TRUE.
LRSACC = .FALSE. ! seems useless

!        1.3 Set implicit default values for NO2.., NO3.., M2D.., M3D.. (YOMPPC)

DO J=1,JPO2DGG
  M2DGGP(J) = 0
ENDDO
DO J=1,JPO3DSPM
  M3DSPM(J) = 0
ENDDO
DO J=1,JPO3DGG
  M3DGGM(J)  = 0
ENDDO

IF (LECMWF) THEN
  NO2DGG = JPO2DGG
  M2DGGP(1)  = NGRBBV
  M2DGGP(2)  = NGRBSTL1
  M2DGGP(3)  = NGRBSWVL1
  M2DGGP(4)  = NGRBSD
  M2DGGP(5)  = NGRBLSP
  M2DGGP(6)  = NGRBCP
  M2DGGP(7)  = NGRBSF
  M2DGGP(8)  = NGRBBLD
  M2DGGP(9)  = NGRBSSHF
  M2DGGP(10) = NGRBSLHF
  M2DGGP(11) = NGRBMSL
  M2DGGP(12) = NGRBTCC
  M2DGGP(13) = NGRB10U
  M2DGGP(14) = NGRB10V
  M2DGGP(15) = NGRB2T
  M2DGGP(16) = NGRB2D
  M2DGGP(17) = NGRBSTL2
  M2DGGP(18) = NGRBSWVL2
  M2DGGP(19) = NGRBSR
  M2DGGP(20) = NGRBAL
  M2DGGP(21) = NGRBSSR
  M2DGGP(22) = NGRBSTR
  M2DGGP(23) = NGRBTSR
  M2DGGP(24) = NGRBTTR
  M2DGGP(25) = NGRBEWSS
  M2DGGP(26) = NGRBNSSS
  M2DGGP(27) = NGRBE
  M2DGGP(28) = NGRBSTL3
  M2DGGP(29) = NGRBSWVL3
  M2DGGP(30) = NGRBCCC
  M2DGGP(31) = NGRBLCC
  M2DGGP(32) = NGRBMCC
  M2DGGP(33) = NGRBHCC
  M2DGGP(34) = NGRBLGWS
  M2DGGP(35) = NGRBMGWS
  M2DGGP(36) = NGRBGWD
  M2DGGP(37) = NGRBSRC
  M2DGGP(38) = NGRBMX2T
  M2DGGP(39) = NGRBMN2T
  M2DGGP(40) = NGRBRO
  M2DGGP(41) = NGRBSKT
  M2DGGP(42) = NGRBSTL4
  M2DGGP(43) = NGRBSWVL4
  M2DGGP(44) = NGRBSSRD
  M2DGGP(45) = NGRBSTRD
  M2DGGP(46) = NGRBBLH
  M2DGGP(47) = NGRBSUND
  M2DGGP(48) = NGRBCVL
  M2DGGP(49) = NGRBCVH
  M2DGGP(50) = NGRBTVL
  M2DGGP(51) = NGRBTVH
  M2DGGP(52) = NGRBCI
  M2DGGP(53) = NGRBSSTK
  M2DGGP(54) = NGRBASN
  M2DGGP(55) = NGRBRSN
  M2DGGP(56) = NGRBTSN
  M2DGGP(57) = NGRBISTL1
  M2DGGP(58) = NGRBISTL2
  M2DGGP(59) = NGRBISTL3
  M2DGGP(60) = NGRBISTL4
  M2DGGP(61) = NGRBTSRC
  M2DGGP(62) = NGRBTTRC
  M2DGGP(63) = NGRBSSRC
  M2DGGP(64) = NGRBSTRC
  M2DGGP(65) = NGRBES
  M2DGGP(66) = NGRBSMLT
  M2DGGP(67) = NGRB10FG
  M2DGGP(68) = NGRBLSPF
  M2DGGP(69) = NGRBUCUR
  M2DGGP(70) = NGRBVCUR
  M2DGGP(71) = NGRB100U
  M2DGGP(72) = NGRB100V
  M2DGGP(73) = NGRBDNDZN
  M2DGGP(74) = NGRBDNDZA
  M2DGGP(75) = NGRBDCTB
  M2DGGP(76) = NGRBTPLB
  M2DGGP(77) = NGRBTPLT
  M2DGGP(78) = NGRBCBASE
  M2DGGP(79) = NGRB0DEGL
  M2DGGP(80) = NGRBVISIH
  M2DGGP(81) = NGRB10NU
  M2DGGP(82) = NGRB10NV
  M2DGGP(83) = NGRBZUST
  M2DGGP(84) = NGRBFDIR
  M2DGGP(85) = NGRBCDIR
  M2DGGP(86) = NGRBTP
  M2DGGP(87) = NGRBSP
  M2DGGP(88) = NGRBMX2T3
  M2DGGP(89) = NGRBMN2T3
  M2DGGP(90) = NGRB10FG3
  M2DGGP(91) = NGRBMX2T6
  M2DGGP(92) = NGRBMN2T6
  M2DGGP(93) = NGRB10FG6
  M2DGGP(94) = NGRBCAPE
  M2DGGP(95) = NGRBSSRDC
  M2DGGP(96) = NGRBSTRDC
  M2DGGP(97) = NGRBCIN
  M2DGGP(98) = NGRBKINDEX
  M2DGGP(99) = NGRBTTINDEX
  M2DGGP(100)= NGRBAEODTO
  M2DGGP(101)= NGRBAEODSS
  M2DGGP(102)= NGRBAEODDU
  M2DGGP(103)= NGRBAEODOM
  M2DGGP(104)= NGRBAEODBC
  M2DGGP(105)= NGRBAEODSU
  M2DGGP(106)= NGRBAEODNI
  M2DGGP(107)= NGRBAEODAM
  M2DGGP(108)= NGRBAEODSOA
  M2DGGP(109)= NGRBAEODVFA
  M2DGGP(110)= NGRBAEODVSU
  M2DGGP(111)= NGRBAEPM1
  M2DGGP(112)= NGRBLMLT
  M2DGGP(113)= NGRBLMLD
  M2DGGP(114)= NGRBLBLT
  M2DGGP(115)= NGRBLTLT 
  M2DGGP(116)= NGRBLSHF 
  M2DGGP(117)= NGRBLICT
  M2DGGP(118)= NGRBLICD
  M2DGGP(119)= NGRBMXTPR
  M2DGGP(120)= NGRBMNTPR
  M2DGGP(121)= NGRBMXTPR3
  M2DGGP(122)= NGRBMNTPR3
  M2DGGP(123)= NGRBMXTPR6
  M2DGGP(124)= NGRBMNTPR6
  M2DGGP(125)= NGRBLSRR
  M2DGGP(126)= NGRBCRR
  M2DGGP(127)= NGRBLSSFR
  M2DGGP(128)= NGRBCSFR
  M2DGGP(129)= NGRBPTYPE
  M2DGGP(130)= NGRBILSPF
  M2DGGP(131)= NGRBTCSLW
  M2DGGP(132)= NGRBI10FG
  M2DGGP(133)= NGRBPEV
  M2DGGP(134)= NGRBAEPM25
  M2DGGP(135)= NGRBAEPM10
  M2DGGP(136)= NGRBFZRA
  M2DGGP(137)= NGRBLITOTI
  M2DGGP(138)= NGRBLITOTA1
  M2DGGP(139)= NGRBLICGI
  M2DGGP(140)= NGRBLICGA1
  M2DGGP(141)= NGRBCBASEA
  M2DGGP(142)= NGRBCTOPC
  M2DGGP(143)= NGRBZTWETB0
  M2DGGP(144)= NGRBZTWETB1
  M2DGGP(145)= NGRBDSRP
  M2DGGP(146)= NGRBCLBT
  M2DGGP(147)= NGRBCSBT
  M2DGGP(148)= NGRBCAPES
  M2DGGP(149)= NGRB10SI
  M2DGGP(150)= NGRB100SI
  M2DGGP(151)= NGRBUVBED
  M2DGGP(152)= NGRBUVBEDCS
  M2DGGP(153)= NGRBICETK
  M2DGGP(154)= NGRBMLD
  M2DGGP(155)= NGRBSL
  M2DGGP(156)= NGRB20D
  M2DGGP(157)= NGRBSSSO
  M2DGGP(158)= NGRBTPR
  M2DGGP(159)= NGRBMXCAP6
  M2DGGP(160)= NGRBMXCAPS6
  M2DGGP(161)= NGRBVIWVE
  M2DGGP(162)= NGRBVIWVN
  M2DGGP(163)= NGRBLITOTA3
  M2DGGP(164)= NGRBLITOTA6
  M2DGGP(165)= NGRBLICGA3
  M2DGGP(166)= NGRBLICGA6
  M2DGGP(167)= NGRB200U
  M2DGGP(168)= NGRB100V
  M2DGGP(169)= NGRB100SI
  M2DGGP(170)= NGRB2SH
  M2DGGP(171)= NGRBM10DEGL
  M2DGGP(172)= NGRBMUCAPE
  M2DGGP(173)= NGRBMLCAPE50
  M2DGGP(174)= NGRBMLCAPE100
  M2DGGP(175)= NGRBMLCIN50
  M2DGGP(176)= NGRBMLCIN100
  M2DGGP(177)= NGRBMUDEPL
  M2DGGP(178)= NGRBTROPOTP
  M2DGGP(179)= NGRBSDSL
  M2DGGP(180)= NGRBWSN
  M2DGGP(181)= NGRBCH4WET
  M2DGGP(182)= NGRBPTYPEMODE1
  M2DGGP(183)= NGRBPTYPEMODE3
  M2DGGP(184)= NGRBPTYPEMODE6
  M2DGGP(185)= NGRBPTYPESEVR1
  M2DGGP(186)= NGRBPTYPESEVR3
  M2DGGP(187)= NGRBPTYPESEVR6
ELSE
  NO2DGG=11
  M2DGGP(1) =170
  M2DGGP(2) =171
  M2DGGP(3) =139
  M2DGGP(4) =140
  M2DGGP(5) =141
  M2DGGP(6) =173
  M2DGGP(7) =174
  M2DGGP(8) =17
  M2DGGP(9) =200
  M2DGGP(10)=172
  M2DGGP(11)=199
ENDIF


IO3DSPM=0
IO3DSPM=IO3DSPM+1
M3DSPM(IO3DSPM) = NGRBT
IF( YGFL%YQ%LSP )THEN
  IO3DSPM=IO3DSPM+1
  M3DSPM(IO3DSPM) = NGRBQ
ENDIF
IO3DSPM=IO3DSPM+1
M3DSPM(IO3DSPM) = NGRBVO
IO3DSPM=IO3DSPM+1
M3DSPM(IO3DSPM) = NGRBD
IO3DSPM=IO3DSPM+1
M3DSPM(IO3DSPM) = NGRBW
IO3DSPM=IO3DSPM+1
M3DSPM(IO3DSPM) = NGRBLNSP
IO3DSPM=IO3DSPM+1
M3DSPM(IO3DSPM) = NGRBZ
NO3DSPM = IO3DSPM

NO3DGGM  = 0

!        1.4 Set implicit default values for NRSACCFRQ, NRSACCOFF (YOMPPC)

NRSACCFRQ = 0
NRSACCOFF = 0

!      ----------------------------------------------------------------

!*       2.    Read NAMPPC and modifies default values.
!              ----------------------------------------

CALL POSNAM(NULNAM,'NAMPPC')
READ(NULNAM,NAMPPC)

IF(NO2DGG == 0) THEN
  LRSUP = .FALSE.
ENDIF

!*       2.2   Split surface fields into fields written before or after calling physics

! This piece of code modifies (NO2DGG, M2DGGP) and computes (NO2DGGL, M2DGGPL).
ILAGO  = 0
INLAGO = 0
DO J=1,NO2DGG
  IPAR = M2DGGP(J)
  IF  ((IPAR == NGRBTCC   ).OR.(IPAR == NGRB10U    ).OR.&
     & (IPAR == NGRB10V   ).OR.(IPAR == NGRB2T     ).OR.&
     & (IPAR == NGRB2D    ).OR.(IPAR == NGRB2SH    ).OR.&
     & (IPAR == NGRBCCC   ).OR.&
     & (IPAR == NGRBLCC   ).OR.(IPAR == NGRBMCC    ).OR.&
     & (IPAR == NGRBHCC   ).OR.(IPAR == NGRBBLH    ).OR.&
     & (IPAR == NGRBIEWS  ).OR.(IPAR == NGRBINSS   ).OR.&
     & (IPAR == NGRBISHF  ).OR.(IPAR == NGRBIE     ).OR.&
     & (IPAR == NGRBBV    ).OR.(IPAR == NGRBFAL    ).OR.&
     & (IPAR == NGRBMSL   ).OR.(IPAR == NGRBSP     ).OR.&
     & (IPAR == NGRBFSR   ).OR.(IPAR == NGRBFLSR   ).OR.&
     & (IPAR == NGRBVIWVE ).OR.(IPAR == NGRBVIWVN  ).OR.&
     & (IPAR == NGRBTCW   ).OR.(IPAR == NGRBTCWV   ).OR.&
     & (IPAR == NGRBTCLW  ).OR.(IPAR == NGRBTCIW   ).OR.&
     & (IPAR == NGRBCAPE  ).OR.(IPAR == NGRBTCO3   ).OR.&
     & (IPAR == NGRBTCRW  ).OR.(IPAR == NGRBTCSW   ).OR.&
     & (IPAR == NGRB100U  ).OR.(IPAR == NGRB100V   ).OR.&
     & (IPAR == NGRBZUST  ).OR.(IPAR == NGRBCBASE  ).OR.&
     & (IPAR == NGRB0DEGL ).OR.(IPAR == NGRBVISIH  ).OR.&
     & (IPAR == NGRBM10DEGL ).OR.&
     & (IPAR == NGRBCIN   ).OR.(IPAR == NGRBCAPES  ).OR.&
     & (IPAR == NGRBMXCAP6).OR.(IPAR == NGRBMXCAPS6).OR.&
     & (IPAR == NGRBMUCAPE).OR.(IPAR == NGRBMUDEPL).OR.&
     & (IPAR == NGRBMLCAPE50).OR.(IPAR == NGRBMLCAPE100).OR.&
     & (IPAR == NGRBMLCIN50).OR.(IPAR == NGRBMLCIN100).OR.&
     & (IPAR == NGRBKINDEX).OR.(IPAR == NGRBTTINDEX).OR.&
     & (IPAR == NGRBCBASEA).OR.(IPAR == NGRBCTOPC).OR.&
     & (IPAR == NGRBTROPOTP).OR.&
     & (IPAR == NGRBZTWETB0).OR.(IPAR == NGRBZTWETB1).OR.&
     & (IPAR == NGRB10NU  ).OR.(IPAR == NGRB10NV   ).OR.&
     & (IPAR == NGRBDNDZN ).OR.(IPAR == NGRBDNDZA  ).OR.&
     & (IPAR == NGRBDCTB  ).OR.&
     & (IPAR == NGRBLMLT  ).OR.(IPAR == NGRBLMLD   ).OR.&
     & (IPAR == NGRBLBLT  ).OR.(IPAR == NGRBLTLT   ).OR.&
     & (IPAR == NGRBLSHF  ).OR.(IPAR == NGRBLICT   ).OR.&
     & (IPAR == NGRBLICD  ).OR.&
     & (IPAR == NGRBTPLB  ).OR.(IPAR == NGRBTPLT   ).OR.&
     & (IPAR == NGRBTPR   ).OR.&
     & (IPAR == NGRBLSRR  ).OR.(IPAR == NGRBCRR    ).OR.&
     & (IPAR == NGRBLSSFR ).OR.(IPAR == NGRBCSFR   ).OR.&
     & (IPAR == NGRBPTYPE ).OR.(IPAR == NGRBILSPF  ).OR.&
     & (IPAR == NGRBTCSLW ).OR.(IPAR == NGRBI10FG  ).OR.&
     & (IPAR == NGRBCLBT  ).OR.(IPAR == NGRBCSBT   ).OR.&
     & (IPAR == NGRB10SI  ).OR.(IPAR == NGRB100SI  ).OR.&
     & (IPAR == NGRBLITOTI).OR.(IPAR == NGRBLICGI).OR.&
     & (IPAR == NGRBAODPR     ).OR.(IPAR == NGRBAODSM     ).OR.&
     & (IPAR == NGRBAODLG     ).OR.&
     & (IPAR == NGRBAEODSS    ).OR.(IPAR == NGRBAEODSOA    ).OR.&
     & (IPAR == NGRBAEODDU    ).OR.(IPAR == NGRBAEODOM     ).OR.&
     & (IPAR == NGRBAEODBC    ).OR.(IPAR == NGRBAEODSU     ).OR.&
     & (IPAR == NGRBAEODVFA   ).OR.(IPAR == NGRBAEODVSU    ).OR.&
     & (IPAR == NGRBAEPM1     ).OR.(IPAR == NGRBAEPM25     ).OR.&
     & (IPAR == NGRBAEPM10    ).OR.&
     & (IPAR == NGRBUVBED     ).OR.(IPAR == NGRBUVBEDCS    ).OR.&
     & (IPAR == NGRBCH4WET    )) THEN
    ILAGO = ILAGO+1
    M2DGGPL(ILAGO) = IPAR
  ELSE
    INLAGO = INLAGO+1
    M2DGGP(INLAGO) = IPAR
  ENDIF
ENDDO
NO2DGG  = INLAGO
NO2DGGL = ILAGO

!      -----------------------------------------------------------

!*       3.    Print final values for module YOMPPC.
!              -------------------------------------

WRITE(NULOUT,'('' SUBROUTINE SUPP '')')
WRITE(NULOUT,'('' NAMELIST NAMPPC, MODULE YOMPPC '')')
WRITE(NULOUT,'('' NO3DGGM ='',I4,'' NO2DGG ='',I4,'' NO2DGGL ='',I4,'' NO3DSPM ='',I4)')&
 & NO3DGGM,NO2DGG,NO2DGGL,NO3DSPM  
IF(NO2DGG /= 0) THEN
  WRITE(NULOUT,'('' THE FOLLOWING '',I6,'' SURFACE FIELDS'',&
   & '' WILL BE WRITTEN OUT AT BEGINNING OF TIME-STEP'')')NO2DGG
  WRITE(NULOUT,'(''M2DGGP '')')
  WRITE(NULOUT,'(24(1X,I6))') M2DGGP(1:NO2DGG)
ENDIF
IF(NO2DGGL /= 0) THEN
  WRITE(NULOUT,'('' THE FOLLOWING '',I6,'' SURFACE FIELDS'',&
   & '' WILL BE WRITTEN OUT AT END OF TIME-STEP'')')NO2DGGL  
  WRITE(NULOUT,'(''M2DGGPL '')')
  WRITE(NULOUT,'(24(1X,I6))') M2DGGPL(1:NO2DGGL)
ENDIF
IF(NO3DSPM /= 0) THEN
  WRITE(NULOUT,'(''M3DSPM '')')
  WRITE(NULOUT,'(24(1X,I6))') M3DSPM(1:NO3DSPM)
ENDIF
IF(NO3DGGM /= 0) THEN
  WRITE(NULOUT,'(''M3DGGM '')')
  WRITE(NULOUT,'(24(1X,I6))') M3DGGM(1:NO3DGGM)
ENDIF
IF(NO2DSPE /= 0) THEN
  IF (NO2DSPE > JPO2DSPA) CALL ABOR1('SUPP: TOO MANY 2D SPECTRAL ECV FIELDS - INCREASE JPO2DSPA')
  WRITE(NULOUT,'(''M2DSPE '')')
  WRITE(NULOUT,'(24(1X,I6))') M2DSPE(1:NO2DSPE)
ENDIF
IF(NO3DSPE /= 0) THEN
  IF (NO3DSPE > JPO3DSPA) CALL ABOR1('SUPP: TOO MANY 3D SPECTRAL ECV FIELDS - INCREASE JPO3DSPA')
  WRITE(NULOUT,'(''M3DSPE '')')
  WRITE(NULOUT,'(24(1X,I6))') M3DSPE(1:NO3DSPE)
ENDIF
IF(NO3DGGE /= 0) THEN
  IF (NO3DGGE > JPO3DGGA) CALL ABOR1('SUPP: TOO MANY 3D GRIDPOINT ECV FIELDS - INCREASE JPO3DGGA')
  WRITE(NULOUT,'(''M3DGGE '')')
  WRITE(NULOUT,'(24(1X,I6))') M3DGGE(1:NO3DGGE)
ENDIF

WRITE(NULOUT,'('' LRSUP ='',L2)') LRSUP
WRITE(NULOUT,'('' NRSACCFRQ  ='',I6,'' NRSACCOFF  ='',I6)') NRSACCFRQ,NRSACCOFF

!!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SUPP',1,ZHOOK_HANDLE)

END SUBROUTINE SUPP
