! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUSC2B(YDGEOMETRY,YDMODEL)

!**** *SUSC2B*  Initialize control of calc in gridpoint space

!     Purpose.
!     -------
!           Initialize the module that controls the
!           grid - point calculations under SCAN2M.
!           Also prepare memory buffers.

!     Interface.
!     ---------
!        *CALL*  *SUSC2B*

!        Explicit arguments : None
!        ------------------
!        Implicit arguments :
!        ------------------
!        see above "USE MODULE"

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------

!     Author.
!     ------
!        Mats Hamrud  * ECMWF *
!        Original  : 91-01-15

!     Modifications.
!     -------------
!        N. Wedi and K. Yessad (Jan 2008): different dev for NH model and PC scheme
!        M. Janiskova  10-Apr-08 fields for the linearized LW radiation
!        30-Jun-2008 J. Masek    Auxiliary quantities for SLHD interpolators.
!        K. Yessad (Sep 2008): prune enhanced diffusion (lfrein), rm lpc_xidt.
!        13-Oct-2008 J. Masek    Fix for NUNDEFLD=1 case.
!        K.Yessad (Aug 2009): remove NTRSLTYPE/=2 cases
!        K. Yessad (Aug 2009): remove LPC_OLD in TL and AD codes.
!        K. Yessad (Aug 2009): use RIPI, RSLD
!        K. Yessad (Nov 2009): prune lpc_old.
!        K. Yessad (Jan 2010): revised code for obs horiz interpolator (first draft)
!        H.Varella : 2010-04-20 Divergence included
!        04-Dec-2009 H. Hersbach Add +2 to NFLDOBB1
!        M. Janiskova  21-Sep-09 fields for TL/AD of non-orog.gravity wave
!        O. Spaniel  27-Sep-10 fix the array allocation size for NSLCORE
!        G. Mozdzynski (Jan 2011): OOPS cleaning, use of derived type SL_STRUCT
!        F. Vana  22-Feb-2011: Auxiliary quantities for horizontal turbulence.
!        R. El Khatib 20-Aug-2012 GAUXBUF removed and replaced by HFPBUF
!        T.Wilhelmsson (Aug 2011): Move some allocations to new routine SUSC2C
!        F. Vana  28-Nov-2013 : Redesigned trajectory handling
!        M. Janiskova  13-Jul-11 perturbation of top layer surf.fields GPTSKINx
!        M. Janiskova  03-May-13 fields for TL/AD of simp.surf.scheme
!        K. Yessad (July 2013): Allocation of FTHSOR moved there.
!        T. Wilhelmsson and K. Yessad (Oct 2013) Geometry and setup refactoring.
!        J. Masek, 2013-11: Allocation of ACRANEB2 intermittent storage.
!        K. Yessad (July 2014): Move some variables.
!        R. El Khatib 07-Mar-2016 Pruning of ISP
!        K. Yessad (Dec 2016): Prune obsolete options.
!        2017-09, J. Masek: Shifted dimensioning of YDTRC%GMU0.
!        F. Vana  11-Sep-2020 SLAVEPP in TL/AD, trajectories for CLOUD
! End Modifications
!     ------------------------------------------------------------------

USE TYPE_MODEL   , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE PARDIM   , ONLY : JPSLWIDE
USE YOMLUN   , ONLY : NULOUT
USE YOMMP0   , ONLY : LOUTPUT, MY_REGION_NS, MY_REGION_EW, NPRINTLEV,LSLONDEM
USE YOMCST   , ONLY : RPI, RA
USE YOMCT0   , ONLY : LR2D, NCONF, LALLOPR, LELAM,LSFORC
USE YOMVAR   , ONLY : LSLADREP
USE YOMIOPNH , ONLY : NG3NH95, LTRAJNH
USE YOMINI   , ONLY : LDFI
USE YOMGPPCB , ONLY : GPPCBUF

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(MODEL)    ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM) :: IU, JL, IDWIDE, ISLWM2, ILEN, IS,&
 & IFLDSGSR, INUMLEV, IFLDSNH95,&
 & ISLWIDE, INFGPPC, INFGPPC5, IDGSAH, IDGENH

LOGICAL :: LLP

REAL(KIND=JPRB) :: ZDL, ZISLWM2, ZLTRAJ, ZRAPVMAX

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
#ifdef __INTEL_COMPILER
INTRINSIC :: SHAPE ! Fails with Intel compiler as it thinks we use ATLAS shape function
#endif


!    -------------------------------------------------------------------

#include "abor1.intfb.h"
#include "slcset.intfb.h"
#include "suptrgppc.intfb.h"
#include "suslad1.intfb.h"
#include "suslad2.intfb.h"
#include "suslb.intfb.h"
#include "suslb2.intfb.h"

!    -------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUSC2B',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM, YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP, &
 &  YDCSGLEG=>YDGEOMETRY%YRCSGLEG, YDEGEO=>YDGEOMETRY%YREGEO, YDPHY=>YDMODEL%YRML_PHY_MF%YRPHY, &
 & YDPTRSLB1=>YDMODEL%YRML_DYN%YRPTRSLB1,YDPTRSLB2=>YDMODEL%YRML_DYN%YRPTRSLB2,YDSLPHY=>YDMODEL%YRML_PHY_G%YRSLPHY, &
 & YDRIP=>YDMODEL%YRML_GCONF%YRRIP,YDRCOEF=>YDMODEL%YRML_PHY_RAD%YRRCOEF,YDPTRSLB15=>YDMODEL%YRML_DYN%YRPTRSLB15, &
 & YDDYN=>YDMODEL%YRML_DYN%YRDYN,YDDYNA=>YDMODEL%YRML_DYN%YRDYNA,YDTNH=>YDMODEL%YRML_DYN%YRTNH, &
 & YDEWCOU=>YDMODEL%YREWCOU, YDEPHY=>YDMODEL%YRML_PHY_EC%YREPHY,&
 & YDSRFTLAD=>YDMODEL%YRML_PHY_SLIN%YRSRFTLAD,YDLDDH=>YDMODEL%YRML_DIAG%YRLDDH,YDTRC=>YDMODEL%YRML_PHY_RAD%YRTRC, &
 & YDPTRGPPC=>YDMODEL%YRML_DYN%YRPTRGPPC, &
 & YDPHNC=>YDMODEL%YRML_PHY_SLIN%YRPHNC, YDML_PHY_SLIN=>YDMODEL%YRML_PHY_SLIN)

ASSOCIATE( &
 & NDGENG=>YDDIM%NDGENG, NDGENL=>YDDIM%NDGENL, NDGLG=>YDDIM%NDGLG, &
 & NDGSAG=>YDDIM%NDGSAG, NDGSAL=>YDDIM%NDGSAL, NDGSUR=>YDDIM%NDGSUR, &
 & NDGUNG=>YDDIM%NDGUNG, NDGUXG=>YDDIM%NDGUXG, NDGUXL=>YDDIM%NDGUXL, &
 & NDLON=>YDDIM%NDLON, NDLSUR=>YDDIM%NDLSUR, NDLUNG=>YDDIM%NDLUNG, &
 & NDLUXG=>YDDIM%NDLUXG, NDSUR1=>YDDIM%NDSUR1, NGPBLKS=>YDDIM%NGPBLKS, &
 & NPROMA=>YDDIM%NPROMA, NPROMM=>YDDIM%NPROMM, &
 & NFLEVG=>YDDIMV%NFLEVG, &
 & NSORAYFR=>YDPHY%NSORAYFR, NRAY=>YDPHY%NRAY, NTHRAYFR=>YDPHY%NTHRAYFR, &
 & NRAUTOEV=>YDPHY%NRAUTOEV, LRAY=>YDPHY%LRAY, LRPROX=>YDPHY%LRPROX, &
 & EDELX=>YDEGEO%EDELX, EDELY=>YDEGEO%EDELY, &
 & LWCOU=>YDEWCOU%LWCOU, &
 & NGPTOT=>YDGEM%NGPTOT, NLOENG=>YDGEM%NLOENG, RSTRET=>YDGEM%RSTRET, &
 & LSDDH=>YDLDDH%LSDDH, &
 & MYFRSTACTLAT=>YDMP%MYFRSTACTLAT, MYLSTACTLAT=>YDMP%MYLSTACTLAT, &
 & NFRSTLAT=>YDMP%NFRSTLAT, NFRSTLOFF=>YDMP%NFRSTLOFF, NLSTLAT=>YDMP%NLSTLAT, &
 & NONL=>YDMP%NONL, NPTRFLOFF=>YDMP%NPTRFLOFF, NPTRFRSTLAT=>YDMP%NPTRFRSTLAT, &
 & NSTA=>YDMP%NSTA, &
 & LEGWWMS2=>YDPHNC%LEGWWMS2, LENCLD2=>YDPHNC%LENCLD2, LEPCLD2=>YDPHNC%LEPCLD2, &
 & LERADLW2=>YDPHNC%LERADLW2, LESURF2=>YDPHNC%LESURF2, LETRAJP=>YDPHNC%LETRAJP, &
 & MGPPC=>YDPTRGPPC%MGPPC, MGPPC5=>YDPTRGPPC%MGPPC5, &
 & MGPPCF_BBC=>YDPTRGPPC%MGPPCF_BBC, MGPPCF_CP=>YDPTRGPPC%MGPPCF_CP, &
 & MGPPCF_GFLP=>YDPTRGPPC%MGPPCF_GFLP, &
 & MGPPCF_NHX=>YDPTRGPPC%MGPPCF_NHX, MGPPCF_SP=>YDPTRGPPC%MGPPCF_SP, &
 & MGPPCF_SP5=>YDPTRGPPC%MGPPCF_SP5, MGPPCF_SPD=>YDPTRGPPC%MGPPCF_SPD, &
 & MGPPCF_SPD5=>YDPTRGPPC%MGPPCF_SPD5, MGPPCF_SVD=>YDPTRGPPC%MGPPCF_SVD, &
 & MGPPCF_SVD5=>YDPTRGPPC%MGPPCF_SVD5, MGPPCF_T=>YDPTRGPPC%MGPPCF_T, &
 & MGPPCF_T5=>YDPTRGPPC%MGPPCF_T5, MGPPCF_TP=>YDPTRGPPC%MGPPCF_TP, &
 & MGPPCF_U=>YDPTRGPPC%MGPPCF_U, MGPPCF_U5=>YDPTRGPPC%MGPPCF_U5, &
 & MGPPCF_UP=>YDPTRGPPC%MGPPCF_UP, MGPPCF_V=>YDPTRGPPC%MGPPCF_V, &
 & MGPPCF_V5=>YDPTRGPPC%MGPPCF_V5, MGPPCF_VP=>YDPTRGPPC%MGPPCF_VP, &
 & NFGPPC=>YDPTRGPPC%NFGPPC, &
 & NFLDSLB1=>YDPTRSLB1%NFLDSLB1, &
 & NFLDSLB15=>YDPTRSLB15%NFLDSLB15, &
 & NFLDSLB2=>YDPTRSLB2%NFLDSLB2, &
 & LGLOBRAD=>YDRCOEF%LGLOBRAD, LRCOEF=>YDRCOEF%LRCOEF, NG3SR=>YDRCOEF%NG3SR, &
 & NLENGSRB=>YDRCOEF%NLENGSRB, NLENGTRB=>YDRCOEF%NLENGTRB, &
 & NSTOP=>YDRIP%NSTOP, TSTEP=>YDRIP%TSTEP, &
 & NVTEND=>YDSLPHY%NVTEND, &
 & NGSKIN=>YDSRFTLAD%NGSKIN, &
 & NLENNH95B=>YDTNH%NLENNH95B, &
 & VMAX1=>YDDYN%VMAX1, VMAX2=>YDDYN%VMAX2, &
 & GDEOSI=>YDTRC%GDEOSI, GUEOSI=>YDTRC%GUEOSI, &
 & GMU0=>YDTRC%GMU0, GMU0_MIN=>YDTRC%GMU0_MIN, &
 & GMU0_MAX=>YDTRC%GMU0_MAX, YDSL=>YDMODEL%YRML_DYN%YRSL)
!    -------------------------------------------------------------------

!*        2. INITIALIZE
!            ----------

CALL GSTATS(1939,0)

!*        2.1   CONTROL FOR SCAN2, START ADRESSES FOR ROWS IN BUFFERS ETC.

LLP = NPRINTLEV >= 1.OR. LALLOPR
IU = NULOUT

IDWIDE=NDGLG/2 

!*        2.2   INTERPOLATION BUFFERS SETUP, NUMBER OF BUFFERS ETC.

!         2.2.1 Computation of NFLDSLB1.

IF ( NCONF/100  ==  7 ) THEN
  NFLDSLB1 = 0
  NFLDSLB2 = 0
  NFLDSLB15 = 0
ELSE  
  IF (LR2D) THEN
    CALL SUSLB2(YDMODEL%YRML_DYN)
  ELSE
    CALL SUSLB(YDGEOMETRY%YRDIMV,YDGEOMETRY%YRCVER,YDMODEL)
  ENDIF
ENDIF

!         2.2.2 Computation of YR...%NSLWIDE.

! ky: calculation of all the YR...%NSLWIDE must be now done there.
!     Each value can be computed independently.
!     - SL scheme required: YRSL%NSLWIDE > 2 (depending on VMAX2)
!     - Eulerian scheme (or no advection scheme if no temporal advance): YRSL%NSLWIDE=0.
!     - AD of SL scheme required and LSLADREP=T: YRAD%NSLWIDE=YRSL%NSLWIDE*2; otherwise YRAD%NSLWIDE=0.
!     - Radiation interpolator required: YRRI%NSLWIDE=2; otherwise YRRI%NSLWIDE=0.

YDSL%LSLONDEM = LSLONDEM
YDSL%NSLWIDE = 0

  ! * configurations between 1 and 699 or between 801 and 999.

IF (YDDYNA%LSLAG) THEN
  IF (YDDYNA%LTWOTL) THEN
    ZLTRAJ=1._JPRB
  ELSE
    ZLTRAJ=2._JPRB
  ENDIF
  IF (LELAM) THEN
    IF ( LSFORC ) THEN
      YDSL%NSLWIDE = IDWIDE
    ELSE
      ISLWM2=INT(ZLTRAJ*VMAX2*TSTEP*RSTRET/MIN(EDELX,EDELY))
      YDSL%NSLWIDE = ISLWM2 + 2
    ENDIF
  ELSE
    ZDL=ZLTRAJ*VMAX2*TSTEP*RSTRET/RA
    IF (ZDL > (0.5_JPRB*RPI)) THEN
      WRITE(NULOUT,*)'VMAX2 OR TSTEP TOO BIG, TAKE LOWER VALUES.'
      CALL ABOR1('SUSC2B : ABOR1 CALLED')
    ENDIF
    ZISLWM2 = ZDL * (REAL(NDGLG,JPRB) + 0.5_JPRB)/RPI
    ISLWM2 = CEILING(ZISLWM2)
    YDSL%NSLWIDE = ISLWM2 + NDGSUR
    ! EH: Need this here for T639 inner loops - need to understand this hack!
    YDSL%NSLWIDE = YDSL%NSLWIDE - 1
    ! EH: End hack
    ! ----------------------------------------------------------
    ! recompute VMAX1, VMAX2 to take full advantage of YDSL%NSLWIDE:
    ZRAPVMAX=VMAX1/VMAX2
    ZDL = REAL(ISLWM2,JPRB) * RPI/(REAL(NDGLG,JPRB) + 0.5_JPRB)
    IF (TSTEP /= 0.0_JPRB) THEN
      VMAX2 = ZDL * RA/(ZLTRAJ * TSTEP * RSTRET)
      VMAX1 = MIN(ZRAPVMAX * VMAX2, 250.0_JPRB)
      WRITE(NULOUT,'('' REVISED VALUES:'',&
       & '' VMAX1  = '',F6.2,'' VMAX2  = '',F6.2)') VMAX1,VMAX2  
    ENDIF
    ! ----------------------------------------------------------
  ENDIF
  
ENDIF

ISLWIDE=YDSL%NSLWIDE


IF (YDDYNA%LSLAG) THEN  ! WHAT ABOUT LOBSC1 ???

  ! * slcset is called to compute a halo based on a standard or double halo width

  ! * call of slcset for a halo based on a standard halo width
  YDSL%CVER='SL'
  ISLWIDE=YDSL%NSLWIDE
  IDGSAH = MAX(NDGSAG,NDGSAL+NFRSTLOFF-YDSL%NSLWIDE)-NFRSTLOFF
  IDGENH = MIN(NDGENG,NDGENL+NFRSTLOFF+YDSL%NSLWIDE)-NFRSTLOFF
  CALL SLCSET(YDGEOMETRY,YDSL,MY_REGION_NS,MY_REGION_EW,&
   & NDGLG,NDLON,NDGSAG,NDGENG,NDGSAL,NDGENL,IDGSAH,IDGENH,&
   & NDGUXL,NDLUNG,NDLUXG,NDGUNG,NDGUXG,&
   & NDSUR1,NDLSUR,NDGSUR,NGPTOT,&
   & NPTRFLOFF,NFRSTLOFF,MYFRSTACTLAT,MYLSTACTLAT,&
   & NSTA,NONL,NLOENG,NPTRFRSTLAT,NFRSTLAT,NLSTLAT,&
   & YDCSGLEG%RMU,YDCSGLEG%RSQM2,YDSLREP=YDMODEL%YRML_DYN%YRSLREP)

  IF (LSLADREP.AND.YDDYNA%LSLAG) THEN  
    ! * call of slcset for a halo based on a double standard halo width
    YDMODEL%YRML_DYN%YRAD%LSLONDEM=LSLONDEM
    YDMODEL%YRML_DYN%YRAD%CVER='AD'
    YDMODEL%YRML_DYN%YRAD%NSLWIDE=YDSL%NSLWIDE*2
    ISLWIDE=YDMODEL%YRML_DYN%YRAD%NSLWIDE
    IDGSAH = MAX(NDGSAG,NDGSAL+NFRSTLOFF-YDMODEL%YRML_DYN%YRAD%NSLWIDE)-NFRSTLOFF
    IDGENH = MIN(NDGENG,NDGENL+NFRSTLOFF+YDMODEL%YRML_DYN%YRAD%NSLWIDE)-NFRSTLOFF
    CALL SLCSET(YDGEOMETRY,YDMODEL%YRML_DYN%YRAD,MY_REGION_NS,MY_REGION_EW,&
     & NDGLG,NDLON,NDGSAG,NDGENG,NDGSAL,NDGENL,IDGSAH,IDGENH,&
     & NDGUXL,NDLUNG,NDLUXG,NDGUNG,NDGUXG,&
     & NDSUR1,NDLSUR,NDGSUR,NGPTOT,&
     & NPTRFLOFF,NFRSTLOFF,MYFRSTACTLAT,MYLSTACTLAT,&
     & NSTA,NONL,NLOENG,NPTRFRSTLAT,NFRSTLAT,NLSTLAT,&
     & YDCSGLEG%RMU,YDCSGLEG%RSQM2,YDSLREP=YDMODEL%YRML_DYN%YRSLREP)

    CALL SUSLAD1(YDGEOMETRY, YDMODEL%YRML_DYN%YRSLREP, YDSL, YDMODEL%YRML_DYN%YRAD )
    ! Initialise constant arrays for SL adjoint interpolations
    CALL SUSLAD2(YDGEOMETRY, YDMODEL%YRML_DYN%YRSLREP, YDMODEL%YRML_DYN%YRAD, YDMODEL%YRML_DYN%YRDYN)

  ENDIF

ENDIF

ISLWIDE=MAX(ISLWIDE,YDMODEL%YRML_PHY_RAD%YRRI%NSLWIDEN,YDMODEL%YRML_PHY_RAD%YRRI%NSLWIDES)

!*        2.3   CHECKINGS

IF (YDSL%NSLWIDE > JPSLWIDE) THEN
  WRITE(NULOUT,'('' YDSL%NSLWIDE ='',I4 ,'' JPSLWIDE ='',I4)') YDSL%NSLWIDE,JPSLWIDE
  CALL ABOR1(' SUSC2B 2.2a: YDSL%NSLWIDE too big: reduce VMAX2 or increase JPSLWIDE')
ENDIF
IF (ISLWIDE > JPSLWIDE) THEN
  WRITE(NULOUT,'('' ISLWIDE ='',I4 ,'' JPSLWIDE ='',I4)') ISLWIDE,JPSLWIDE
  CALL ABOR1(' SUSC2B 2.2b: insufficient value of JPSLWIDE')
ENDIF
IF( YDSL%NSLWIDE > IDWIDE )THEN
  WRITE(NULOUT,'('' SUSC2B : YDSL%NSLWIDE > IDWIDE, '',2I6)')YDSL%NSLWIDE,IDWIDE
  CALL ABOR1(' SUSC2B 2.2c: YDSL%NSLWIDE > IDWIDE')
ENDIF

!*        2.4   PRINTS ON OUTPUT

IF (LOUTPUT) THEN
  WRITE(NULOUT,'('' Modules PTRSLB1, PTRSLB2, PTRSLB15 '')')
  WRITE(NULOUT,'(''ISLWIDE ='',I4&
   & ,'' NFLDSLB1 ='',I4,'' NFLDSLB2 ='',I4,'' NFLDSLB15 ='',I4)')&
   & ISLWIDE,NFLDSLB1,NFLDSLB2,NFLDSLB15
ENDIF

!    -------------------------------------------------------------------

!*        3.  BUFFER ALLOCATIONS.
!         -----------------------

!*        3.2   TIMESTEP T - DT

!*        3.2.2 INTER TIMESTEP HISTORY VARIABLES FOR SIMPL. PHYSICS

ALLOCATE (YDML_PHY_SLIN%GPHIST(NGPBLKS))
DO JL=1,NGPBLKS
  IF (LENCLD2 .AND. .NOT.LEPCLD2 .AND. LETRAJP) THEN
    !  Cloud characteristics for simple cloud scheme used in the TL only
    ALLOCATE(YDML_PHY_SLIN%GPHIST(JL)%YA5(NPROMA,NFLEVG))
    ALLOCATE(YDML_PHY_SLIN%GPHIST(JL)%YL5(NPROMA,NFLEVG))
    ALLOCATE(YDML_PHY_SLIN%GPHIST(JL)%YI5(NPROMA,NFLEVG))
    ! Initialize to prevent SL from going crazy during the initial timestep
    YDML_PHY_SLIN%GPHIST(JL)%YA5(:,:)=0._JPRB
    YDML_PHY_SLIN%GPHIST(JL)%YL5(:,:)=0._JPRB
    YDML_PHY_SLIN%GPHIST(JL)%YI5(:,:)=0._JPRB
  ELSEIF (LEPCLD2 .AND. LETRAJP) THEN
    !  Cloud characteristics for simple cloud scheme used in the TL only
    ALLOCATE(YDML_PHY_SLIN%GPHIST(JL)%YA5(NPROMA,NFLEVG))
    ! Initialize to prevent SL from going crazy during the initial timestep
    YDML_PHY_SLIN%GPHIST(JL)%YA5(:,:)=0._JPRB
  ENDIF
  IF (LERADLW2) THEN
    ! Longwave radiation for TL/AD
    ALLOCATE(YDML_PHY_SLIN%GPHIST(JL)%RADLWM (NPROMA,0:NFLEVG))
    ALLOCATE(YDML_PHY_SLIN%GPHIST(JL)%RADLWM5(NPROMA,0:NFLEVG))
  ENDIF
  IF (LEGWWMS2) THEN
    ! Non-orographic gravity wave scheme for TL/AD
    ALLOCATE(YDML_PHY_SLIN%GPHIST(JL)%TGWDWMSU (NPROMA,NFLEVG))
    ALLOCATE(YDML_PHY_SLIN%GPHIST(JL)%TGWDWMSU5(NPROMA,NFLEVG))
    ALLOCATE(YDML_PHY_SLIN%GPHIST(JL)%TGWDWMSV (NPROMA,NFLEVG))
    ALLOCATE(YDML_PHY_SLIN%GPHIST(JL)%TGWDWMSV5(NPROMA,NFLEVG))
  ENDIF
ENDDO

IF (LETRAJP) THEN
  IF (LESURF2) THEN
    NGSKIN = 4
  ELSE
    NGSKIN = 1
  ENDIF
  ALLOCATE(YDSRFTLAD%GPTSKIN0(NPROMA,NGSKIN,NGPBLKS))
  ALLOCATE(YDSRFTLAD%GPTSKIN9(NPROMA,NGSKIN,NGPBLKS))
ENDIF

!*        3.2.6 RADIATION COEFFICIENTS

!         Solar radiation coefficients and correction for
!         thermal radiation

IF (LRCOEF) THEN

  IFLDSGSR = NG3SR*NFLEVG
  ILEN=0
  DO JL=1,NGPTOT,NPROMA
    IS=MIN(NGPTOT-JL+1,NPROMA)
    ILEN=ILEN+IS
  ENDDO
  NLENGSRB = ILEN    * IFLDSGSR

  ALLOCATE(YDRCOEF%SOLRAD(NLENGSRB))
  IF (LLP) WRITE(IU,9) 'SOLRAD ',SIZE(YDRCOEF%SOLRAD),SHAPE(YDRCOEF%SOLRAD)

!          Matrix of thermal radiation coefficients

  NLENGTRB = NGPBLKS

  INUMLEV=(NFLEVG+1)*(NFLEVG+1)

  IF (LGLOBRAD) THEN
    ALLOCATE(YDRCOEF%THERRAD(1,INUMLEV))
    YDRCOEF%THERRAD(:,:)=0.0_JPRB
    IF (LLP) WRITE(IU,9) 'THERRAD ',SIZE(YDRCOEF%THERRAD),SHAPE(YDRCOEF%THERRAD)

    ALLOCATE(YDRCOEF%TRWEIGHT(NFLEVG+1,NFLEVG+1))
    YDRCOEF%TRWEIGHT(:,:)=0.0_JPRB
    IF(LLP) WRITE(IU,9) 'TRWEIGHT ',SIZE(YDRCOEF%TRWEIGHT),SHAPE(YDRCOEF%TRWEIGHT)

    ALLOCATE(YDRCOEF%TRMATSUM(NFLEVG+1,NFLEVG+1))
    YDRCOEF%TRMATSUM(:,:)=0.0_JPRB
    IF(LLP) WRITE(IU,9) 'TRMATSUM ',SIZE(YDRCOEF%TRMATSUM),SHAPE(YDRCOEF%TRMATSUM)
  ELSE
    ALLOCATE(YDRCOEF%THERRAD(NLENGTRB,INUMLEV))
    YDRCOEF%THERRAD(:,:)=0.0_JPRB
    IF (LLP) WRITE(IU,9) 'THERRAD ',SIZE(YDRCOEF%THERRAD),SHAPE(YDRCOEF%THERRAD)
  ENDIF

ENDIF

!*        3.2.7   TIMESTEP T-DT FOR TRAJECTORY
!                 (NON-HYDROSTATIC AND ITERATION IN NHS)

IF(LTRAJNH) THEN
  IFLDSNH95 = NG3NH95*NFLEVG+1
  ILEN=0
  DO JL=1,NGPTOT,NPROMA
    IS=MIN(NGPTOT-JL+1,NPROMA)
    ILEN=ILEN+IS
  ENDDO
  NLENNH95B = ILEN    * IFLDSNH95
  ALLOCATE(YDTNH%TRAJNH(NLENNH95B,0:NSTOP))
  IF(LLP) WRITE(IU,9) 'TRAJNH ',SIZE(YDTNH%TRAJNH),SHAPE(YDTNH%TRAJNH)
ENDIF


!*        3.5   Buffer SAVTEND

!IF(YDDYNA%LSLAG) THEN
IF(YDEPHY%LSLPHY) THEN  ! this makes more sense
  ALLOCATE(YDSLPHY%SAVTEND(NPROMA,NFLEVG,NVTEND,NGPBLKS))
  IF (LLP) WRITE(IU,9) 'SAVTEND  ',SIZE(YDSLPHY%SAVTEND  ),SHAPE(YDSLPHY%SAVTEND  )
  YDSLPHY%SAVTEND(:,:,:,:) = 0.0_JPRB
  IF( NCONF == 131 .OR. NCONF == 401 .OR. NCONF == 501 .OR.&
    & NCONF == 601 .OR. NCONF == 801 )THEN
    ALLOCATE(YDSLPHY%SAVTEND5(NPROMA,NFLEVG,NVTEND,NGPBLKS))
    IF (LLP) WRITE(IU,9) 'SAVTEND5  ',SIZE(YDSLPHY%SAVTEND5  ),SHAPE(YDSLPHY%SAVTEND5  )
    YDSLPHY%SAVTEND5(:,:,:,:) = 0.0_JPRB
  ENDIF
ENDIF

!*        3.6   MODELS WITH PC scheme (GPPCBUF)

! * Compute NFGPPC and the pointers of PTRGPPC.

NFGPPC=0

CALL SUPTRGPPC(YDGEOMETRY%YRDIMV,YDMODEL%YRML_GCONF%YGFL,YDMODEL%YRML_DYN%YRDYNA,YDEPHY%LSLPHY,MGPPC,&
 & MGPPCF_U,MGPPCF_V,MGPPCF_T,MGPPCF_SPD,MGPPCF_SVD,MGPPCF_SP,MGPPCF_CP,&
 & MGPPCF_NHX,MGPPCF_UP,MGPPCF_VP,MGPPCF_TP,MGPPCF_GFLP,MGPPCF_BBC,&
 & INFGPPC)
IF (NPRINTLEV >= 1) THEN
  WRITE(UNIT=IU,FMT='('' MGPPC ='',I6)') MGPPC
  WRITE(UNIT=IU,FMT='('' MGPPCF_U ='',I6)') MGPPCF_U
  WRITE(UNIT=IU,FMT='('' MGPPCF_V ='',I6)') MGPPCF_V
  WRITE(UNIT=IU,FMT='('' MGPPCF_T ='',I6)') MGPPCF_T
  WRITE(UNIT=IU,FMT='('' MGPPCF_SPD ='',I6)') MGPPCF_SPD
  WRITE(UNIT=IU,FMT='('' MGPPCF_SVD ='',I6)') MGPPCF_SVD
  WRITE(UNIT=IU,FMT='('' MGPPCF_SP ='',I6)') MGPPCF_SP
  WRITE(UNIT=IU,FMT='('' MGPPCF_CP ='',I6)') MGPPCF_CP
  WRITE(UNIT=IU,FMT='('' MGPPCF_NHX ='',I6)') MGPPCF_NHX
  WRITE(UNIT=IU,FMT='('' MGPPCF_UP ='',I6)') MGPPCF_UP
  WRITE(UNIT=IU,FMT='('' MGPPCF_VP ='',I6)') MGPPCF_VP
  WRITE(UNIT=IU,FMT='('' MGPPCF_TP ='',I6)') MGPPCF_TP
  WRITE(UNIT=IU,FMT='('' MGPPCF_GFLP ='',I6)') MGPPCF_GFLP
  WRITE(UNIT=IU,FMT='('' MGPPCF_BBC ='',I6)') MGPPCF_BBC
ENDIF

IF( NCONF == 131 .OR. NCONF == 401 .OR. NCONF == 501 .OR.&
 & NCONF == 601 .OR. NCONF == 801 )THEN
  ! * This is required for all configurations calling CPGTL or CPGAD.
  CALL SUPTRGPPC(YDGEOMETRY%YRDIMV,YDMODEL%YRML_GCONF%YGFL,YDMODEL%YRML_DYN%YRDYNA,YDEPHY%LSLPHY,MGPPC5,&
   & MGPPCF_U5,MGPPCF_V5,MGPPCF_T5,MGPPCF_SPD5,MGPPCF_SVD5,MGPPCF_SP5,&
   ! this line to be updated
   & MGPPCF_CP,&
   & MGPPCF_NHX,MGPPCF_UP,MGPPCF_VP,MGPPCF_TP,MGPPCF_GFLP,MGPPCF_BBC,&
   & INFGPPC5)
  IF (NPRINTLEV >= 1) THEN
    WRITE(UNIT=IU,FMT='('' MGPPC5 ='',I6)') MGPPC5
    WRITE(UNIT=IU,FMT='('' MGPPCF_U5 ='',I6)') MGPPCF_U5
    WRITE(UNIT=IU,FMT='('' MGPPCF_V5 ='',I6)') MGPPCF_V5
    WRITE(UNIT=IU,FMT='('' MGPPCF_T5 ='',I6)') MGPPCF_T5
    WRITE(UNIT=IU,FMT='('' MGPPCF_SPD5 ='',I6)') MGPPCF_SPD5
    WRITE(UNIT=IU,FMT='('' MGPPCF_SVD5 ='',I6)') MGPPCF_SVD5
    WRITE(UNIT=IU,FMT='('' MGPPCF_SP5 ='',I6)') MGPPCF_SP5
  ENDIF
ENDIF

NFGPPC=INFGPPC
WRITE(UNIT=IU,FMT='('' NFGPPC ='',I6)') NFGPPC

! * Allocate GPPCBUF.

! ky: this test should be consistent with the one done for SI setup (SUDYN)
!     and what is done in CNT4.
IF ( (NFGPPC > 0.AND.((NSTOP > 0).OR.LDFI.OR.(NSTOP==0.AND.LSDDH).OR.&
  & (NSTOP==0.AND.LWCOU))) ) THEN
  ALLOCATE (GPPCBUF (YDGEOMETRY%YRDIM%NPROMA, NFGPPC, YDGEOMETRY%YRDIM%NGPBLKS))
ENDIF

!*        3.7 GLOBAL STORAGE FOR INTERMITTENT ACRANEB2 RADIATION SCHEME

IF (LRAY.AND.NRAY > 1 ) THEN

  ! storage for solar gaseous transmissions
  IF (NSORAYFR /= 1) THEN
    ALLOCATE(YDTRC%GDEOSI  (NPROMM,0:NFLEVG,  2,NGPBLKS))
    ALLOCATE(YDTRC%GUEOSI  (NPROMM,0:NFLEVG,  2,NGPBLKS))
    ALLOCATE(YDTRC%GMU0    (NPROMM,0:NSORAYFR-1,NGPBLKS))
    ALLOCATE(YDTRC%GMU0_MIN(NPROMM             ,NGPBLKS)) 
    ALLOCATE(YDTRC%GMU0_MAX(NPROMM             ,NGPBLKS))
    IF (LLP) THEN 
      WRITE(IU,9) 'GDEOSI   ',SIZE(YDTRC%GDEOSI  ),SHAPE(GDEOSI  )
      WRITE(IU,9) 'GUEOSI   ',SIZE(YDTRC%GUEOSI  ),SHAPE(GUEOSI  ) 
      WRITE(IU,9) 'GMU0     ',SIZE(YDTRC%GMU0    ),SHAPE(GMU0    )
      WRITE(IU,9) 'GMU0_MIN ',SIZE(YDTRC%GMU0_MIN),SHAPE(GMU0_MIN)
      WRITE(IU,9) 'GMU0_MAX ',SIZE(YDTRC%GMU0_MAX),SHAPE(GMU0_MAX)
    ENDIF
  ENDIF

  ! storage for gaseous transmissions
  IF (NTHRAYFR /= 1) THEN
    ALLOCATE(YDTRC%GRSURF  (NPROMM,         NGPBLKS))
    ALLOCATE(YDTRC%GDEOTI  (NPROMM,0:NFLEVG,NGPBLKS))
    ALLOCATE(YDTRC%GDEOTI2 (NPROMM,0:NFLEVG,NGPBLKS))
    ALLOCATE(YDTRC%GUEOTI  (NPROMM,0:NFLEVG,NGPBLKS))
    ALLOCATE(YDTRC%GUEOTI2 (NPROMM,0:NFLEVG,NGPBLKS))
    ALLOCATE(YDTRC%GEOXT   (NPROMM,  NFLEVG,NGPBLKS))
    IF (LLP) THEN
      WRITE(IU,9) 'GRSURF   ',SIZE(YDTRC%GRSURF ),SHAPE(YDTRC%GRSURF )
      WRITE(IU,9) 'GDEOTI   ',SIZE(YDTRC%GDEOTI ),SHAPE(YDTRC%GDEOTI )
      WRITE(IU,9) 'GDEOTI2  ',SIZE(YDTRC%GDEOTI2),SHAPE(YDTRC%GDEOTI2)
      WRITE(IU,9) 'GUEOTI   ',SIZE(YDTRC%GUEOTI ),SHAPE(YDTRC%GUEOTI )
      WRITE(IU,9) 'GUEOTI2  ',SIZE(YDTRC%GUEOTI2),SHAPE(YDTRC%GUEOTI2)
      WRITE(IU,9) 'GEOXT    ',SIZE(YDTRC%GEOXT  ),SHAPE(YDTRC%GEOXT  )
    ENDIF
    IF (LRPROX) THEN
      ALLOCATE(YDTRC%GEOLT (NPROMM,  NFLEVG,NGPBLKS))
      ALLOCATE(YDTRC%GRPROX(NPROMM,0:NFLEVG,NGPBLKS))
      IF (LLP) THEN
        WRITE(IU,9) 'GEOLT    ',SIZE(YDTRC%GEOLT ),SHAPE(YDTRC%GEOLT )
        WRITE(IU,9) 'GRPROX   ',SIZE(YDTRC%GRPROX),SHAPE(YDTRC%GRPROX)
      ENDIF
    ENDIF
  ENDIF

  ! storage for bracketing weights and offset
  IF ((NRAUTOEV == 0.AND.NTHRAYFR          /= 1).OR.&
   &  (NRAUTOEV >  0.AND.NTHRAYFR*NRAUTOEV /= 1)) THEN
    ALLOCATE(YDTRC%GMIXP (NPROMM,0:NFLEVG,NGPBLKS))
    ALLOCATE(YDTRC%GFLUXC(NPROMM,0:NFLEVG,NGPBLKS))
    IF (LLP) THEN
      WRITE(IU,9) 'GMIXP    ',SIZE(YDTRC%GMIXP ),SHAPE(YDTRC%GMIXP )
      WRITE(IU,9) 'GFLUXC   ',SIZE(YDTRC%GFLUXC),SHAPE(YDTRC%GFLUXC)
    ENDIF
  ENDIF

ENDIF

9 FORMAT(1X,'ARRAY ',A10,' ALLOCATED ',8I8)

!    -------------------------------------------------------------------

CALL GSTATS(1939,1)
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUSC2B',1,ZHOOK_HANDLE)
END SUBROUTINE SUSC2B

