! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

#ifdef VPP
!OCL SCALAR
#endif
SUBROUTINE SUSI(YDGEOMETRY,YDRIP,YDDYN,YDDYNA,YDEDYN,KULOUT)

!**** *SUSI*   - Initialize constants and control for the dynamics:
!                semi-implicit scheme operators.

!     Purpose.
!     --------
!        Computes the operator B=mu*nu+gamma*tau which is used in
!        the semi-implicit scheme in order to work on the Hough space.
!        The inverse 1/B and also the eigenvalues and the eigenvectors
!        of B are computed.
!        * B is stored in array SIB.
!        * The eigenvalues of B are stored in array SIVP.
!        * The eigenvectors of B are stored in array SIMO.
!        * The inverse of SIMO is stored in array SIMI.
!        * The inverse of B is stored in array SIBI.
!        * The call to SUHEG fills the arrays SIHEG and SIHEG2.
!        In the hydrostatic model, only the content of SIHEG and SIHEG2
!         depend on "Delta t".

!**   Interface.
!     ----------
!        *CALL* *SUSI(KULOUT)

!     Explicit arguments :
!     --------------------
!        KULOUT : Logical unit for the output

!     Implicit arguments :
!     --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!        K. YESSAD (after old part 7 of SUDYN).

! Modifications
! -------------
!   Original : 08-Dec-2004
!   I. Santos, I. Martinez (Mar 2010): Variable map factor for RTM.
!   K. Yessad (Dec 2011): Use GPHPRE.
!   M. Fisher   7-March-2012 Move SIBI out of Jb (to allow late Jb setup)
!     ------------------------------------------------------------------

USE YOMRIP       , ONLY : TRIP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMDYN   , ONLY : TDYN
USE YOMDYNA  , ONLY : TDYNA
USE YEMDYN   , ONLY : TEDYN
USE YOMCST   , ONLY : RD, RPI      
USE INTDYN_MOD,ONLY : YYTXYB

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY), INTENT(INOUT)    :: YDGEOMETRY
TYPE(TDYN)     ,INTENT(INOUT)    :: YDDYN
TYPE(TDYNA)    ,INTENT(INOUT)    :: YDDYNA
TYPE(TEDYN)    ,INTENT(INOUT)    :: YDEDYN
TYPE(TRIP)     ,INTENT(INOUT)    :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN)    :: KULOUT

!     ------------------------------------------------------------------

INTEGER(KIND=JPIM) :: JPLL
PARAMETER(JPLL=1)

REAL(KIND=JPRB) :: ZPRES(JPLL,0:YDGEOMETRY%YRDIMV%NFLEVG),ZPRESF(JPLL,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZXYB(JPLL,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYB%NDIM)
REAL(KIND=JPRB) :: ZWO(YDGEOMETRY%YRDIMV%NFLEVG+1),ZA(YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIMV%NFLEVG),&
 & ZFR(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZFI(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZMO(YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRD) :: ZMOD(YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIMV%NFLEVG)

INTEGER(KIND=JPIM) :: IWO(YDGEOMETRY%YRDIMV%NFLEVG+1)
INTEGER(KIND=JPIM) :: IER, ISIGN, JL1, JL2, JLEV, JLON, J

REAL(KIND=JPRB) :: ZSUM, ZTES

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "abor1.intfb.h"
#include "eigsol.h"
#include "minv_caller.h"
#include "gphpre.intfb.h"
#include "scordo.intfb.h"
#include "submat.intfb.h"
#include "sueheg.intfb.h"
#include "suheg.intfb.h"
#include "sudyn_stability.intfb.h"

!     ------------------------------------------------------------------


IF (LHOOK) CALL DR_HOOK('SUSI',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP,  &
 & YDVAB=>YDGEOMETRY%YRVAB, YDVETA=>YDGEOMETRY%YRVETA, YDVFE=>YDGEOMETRY%YRVFE, YDSTA=>YDGEOMETRY%YRSTA,  &
 & YDLAP=>YDGEOMETRY%YRLAP, YDCSGLEG=>YDGEOMETRY%YRCSGLEG,YDCVER=>YDGEOMETRY%YRCVER,  &
 & YDCSGEOM=>YDGEOMETRY%YRCSGEOM, &
 & YDCSGEOM_NB=>YDGEOMETRY%YRCSGEOM_NB, YDGSGEOM=>YDGEOMETRY%YRGSGEOM, YDGSGEOM_NB=>YDGEOMETRY%YRGSGEOM_NB,  &
 & YDSPGEOM=>YDGEOMETRY%YSPGEOM)
ASSOCIATE(NFLEVG=>YDDIMV%NFLEVG, &
 & LSIDG=>YDDYN%LSIDG, SIALPH=>YDDYN%SIALPH, SIB=>YDDYN%SIB, SIBI=>YDDYN%SIBI, &
 & SIDELP=>YDDYN%SIDELP, SIDPHI=>YDDYN%SIDPHI, SILNPR=>YDDYN%SILNPR, &
 & SIMI=>YDDYN%SIMI, SIMO=>YDDYN%SIMO, SIPR=>YDDYN%SIPR, SIRDEL=>YDDYN%SIRDEL, &
 & SITIME=>YDDYN%SITIME, SITLAF=>YDDYN%SITLAF, SITLAH=>YDDYN%SITLAH, &
 & SITR=>YDDYN%SITR, SIVP=>YDDYN%SIVP, VNORM=>YDDYN%VNORM, &
 & LESIDG=>YDEDYN%LESIDG)
!     ------------------------------------------------------------------

!*       1.    INITIALIZE SEMI-IMPLICIT AND VERTICAL NORMAL MODES
!              FOR THE 3D PRIMITIVE EQUATION MODEL.
!              --------------------------------------------------

!*       1.1   INITIALIZE SEMI-IMPLICIT COMPUTATION.

IER=0
ZTES=0.0_JPRB

DO JLON=1,JPLL
  ZPRES(JLON,NFLEVG)=SIPR
ENDDO

CALL GPHPRE(JPLL,NFLEVG,JPLL,JPLL,YDVAB,YDCVER,ZPRES,PXYB=ZXYB,PRESF=ZPRESF)

DO JLEV=1,NFLEVG
  SIDELP(JLEV)=ZXYB(1,JLEV,YYTXYB%M_DELP)
  SIRDEL(JLEV)=ZXYB(1,JLEV,YYTXYB%M_RDELP)
  SILNPR(JLEV)=ZXYB(1,JLEV,YYTXYB%M_LNPR)
  SIALPH(JLEV)=ZXYB(1,JLEV,YYTXYB%M_ALPH)
  SITLAH(JLEV)=ZPRES(1,JLEV)
ENDDO
DO JLEV=1,NFLEVG
  SITLAF(JLEV)=ZXYB(1,JLEV,YYTXYB%M_DELP)/ZXYB(1,JLEV,YYTXYB%M_LNPR)
  SIDPHI(JLEV)=RD*SITR*ZXYB(1,JLEV,YYTXYB%M_LNPR)
ENDDO

DO JLEV=1,NFLEVG
  WRITE(UNIT=KULOUT,FMT='('' JLEV = '',I3.3,&
   & '' SITLAF = '',E14.8,'' SIDPHI = '',E14.8)')&
   & JLEV,SITLAF(JLEV),SIDPHI(JLEV)  
ENDDO

SITLAH(0)=ZPRES(1,0)

!*       1.2   INITIALIZE MATRIX B (SIB)

CALL SUBMAT(YDGEOMETRY,YDDYN)
  
!*       1.3   SOLVE EIGEN PROBLEM

DO JL1=1,NFLEVG
  DO JL2=1,NFLEVG
    ZA(JL1,JL2)=SIB(JL1,JL2)
  ENDDO
ENDDO

CALL EIGSOL(NFLEVG,NFLEVG,ZA,ZFR,ZFI,1,ZMO,IWO,ZWO,IER)
IF(IER /= 0)THEN
  CALL ABOR1('SUSI: ABORT IN SUSI AFTER CALL TO RG')
ENDIF
CALL SCORDO(NFLEVG,ZFR,ZFI,ZMO,ZA)

DO JL1=1,NFLEVG
  DO JL2=1,NFLEVG
    SIMO(JL1,NFLEVG+1-JL2)=ZMO(JL1,JL2)
  ENDDO
ENDDO

DO JL1=1,NFLEVG
  SIVP(NFLEVG+1-JL1)=ZFR(JL1)
ENDDO

ZTES=MAXVAL(ZFI)

!        1.4   NORMALIZE THE VERTICAL MODES
!                               --
! NEW SCALING     , > X(J)**2 *DP(J)/PSOL = VNORM
!                               --
!  (PRESERVING THE AMPLITUDE OF THE EIGENMODE AS THE VERTICAL RESOLUTION
!   -NFLEVG- CHANGES , C.TEMPERTON  09/91)

DO JL1=1,NFLEVG
  ZSUM = 0._JPRB
  DO JL2=1,NFLEVG
    ZSUM=ZSUM+SIMO(JL2,JL1)*SIMO(JL2,JL1)*SIDELP(JL2)
  ENDDO
  ZSUM = ZSUM/SIPR/VNORM
  ZSUM = SQRT(ZSUM)
  DO JL2=1,NFLEVG
    SIMO(JL2,JL1) = SIMO(JL2,JL1)/ZSUM
  ENDDO
ENDDO

!        1.5   CHECK SIGNS OF VERTICAL MODES

DO JL1=1,NFLEVG
  ISIGN = +1
  IF (SIMO(NFLEVG,JL1) < 0.0_JPRB) ISIGN = -ISIGN
  IF (ISIGN == -1) THEN
    DO JL2=1,NFLEVG
      SIMO(JL2,JL1) = -SIMO(JL2,JL1)
    ENDDO
  ENDIF
ENDDO

!*       1.6   INVERSE MODE MATRIX

CALL MINV_CALLER(.TRUE.,NFLEVG,SIMO,SIMI)

!*       1.7   PRINT OUT INFORMATION ON VERTICAL MODES

WRITE(KULOUT,481) SITR,SIPR,(J,YDVAB%VAH(J-1),YDVAB%VBH(J-1),SIVP(J),J=1,NFLEVG)
481 FORMAT('1VERTICAL MODES FOR SITR=',F6.1,' K;   SIPR=',F8.0,&
 & ' PA'///,' VERTICAL RESOLUTION         A(K)            B(K)',&
 & 26X,'EIGENVALUES '/&
 & (20X,I4,G13.5,4X,G13.5,18X,G13.5))  
WRITE(KULOUT,482) ZTES
482 FORMAT(///'0LARGEST IMAGINARY PART OF EIGENVALUES:',G13.5)
IF (ZTES /= 0.0_JPRB) THEN
  ! * Print the imaginary part of eigenvalues.
  WRITE(UNIT=KULOUT,FMT='('' IMAGINARY PARTS OF EIGENVALUES'')')
  WRITE(KULOUT,FMT='(14(1X,E8.2))')(ZFI(NFLEVG+1-J),J=1,NFLEVG)
  ! * For the non-zero imaginary parts, print the eigenvectors.
  DO JL2=1,NFLEVG
    IF (ABS(ZFI(NFLEVG+1-JL2)) > 0.0_JPRB) THEN
      WRITE(UNIT=KULOUT,FMT='(1X)')
      WRITE(KULOUT,FMT='(A,I4)') ' SIMO for VP number ',JL2
      WRITE(KULOUT,FMT='(14(1X,E8.2))')(SIMO(JL1,JL2),JL1=1,NFLEVG)
    ENDIF
  ENDDO
  WRITE(UNIT=KULOUT,FMT='(1X)')
  CALL ABOR1(' SUSI: Eigenvalues of B are not all real > 0')
ENDIF

!*       1.8   SOLVE INVERSE HELMOLTZ EQUATION IF LSIDG=.T.

IF (LSIDG) THEN
  SITIME=-1.0_JPRB
  CALL SUHEG(YDGEOMETRY,YDRIP,YDDYN,YDDYNA)
ENDIF
IF (LESIDG) THEN
  SITIME=-1.0_JPRB
  CALL SUEHEG(YDGEOMETRY,YDDYN,YDEDYN,YDRIP) 
ENDIF

!*       1.9   CALCULATE INVERSE OF THE B MATRIX.

CALL MINV_CALLER(.TRUE.,NFLEVG,SIB,SIBI)

IF(YDGEOMETRY%YRCVER%LDYN_ANALYSIS_STABILITY)THEN
  CALL SUDYN_STABILITY(YDGEOMETRY, YDDYN, YDDYNA%LNHDYN,YDDYNA%LNESC, KULOUT)
ENDIF

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUSI',1,ZHOOK_HANDLE)
END SUBROUTINE SUSI

!========================================
! J. Vivoda personal staff
!========================================

SUBROUTINE HY_MATRIX(YDGEOMETRY,YDDYN,LVERB,KFLEV,PKWAVE, &
                       &PSITR,PSIPR,MDIM,MM)

!------------------------------------------------------
! * CONSTRUCTION OF LINEAR MODEL MATRIX
!------------------------------------------------------
! Author: J.Vivoda, 2019
!------------------------------------------------------
!
! Input: 
!        KFLEV  - number of model levels
!        PKWAVE - horizontal wave number
!        PSITR   - semi-implicit temperature profile
!        PSIPR  - semi-implicit surface pressure
!        MDIM   - dimension of matrix MM (MDIM=4*KFLEV+1 - NH, 2*KFLEV + 1 - HY)
!
! Output:
!        MM     - model matrix
!------------------------------------------------------


USE PARKIND1 , ONLY : JPRB, JPIM
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN   , ONLY : TDYN
USE YOMLUN   , ONLY : NULOUT
USE INTDYN_MOD,ONLY : YYTXYB
USE YOMCST   , ONLY : RD, RG

IMPLICIT NONE

INTEGER(KIND=JPIM)      :: IPROMA, IPROFS
PARAMETER( IPROMA=1)

! * input arguments
TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TDYN)        ,INTENT(INOUT) :: YDDYN
LOGICAL           ,INTENT(IN)    :: LVERB
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEV
REAL(KIND=JPRB)   ,INTENT(IN)    :: PKWAVE                   
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSITR 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSIPR
INTEGER(KIND=JPIM),INTENT(IN)    :: MDIM
REAL(KIND=JPRB)   ,INTENT(OUT)   :: MM(MDIM,MDIM)

! * sigma levels or eta levels

INTEGER(KIND=JPIM)               I, J, K, IST, IEND, IMM, II, JLEV, JROF

REAL(KIND=JPRB)                  ZLAPL

INTEGER(KIND=JPIM) INDX_D, INDX_VD, INDX_T, INDX_PD, INDX_PS

REAL(KIND=JPRB)  ZVECTOR  (MDIM)

!-------------------------------------
! aux. premenne
!-------------------------------------
LOGICAL LDGWADV, LLSI

REAL(KIND=JPRB)    ZDUM    ( KFLEV)

REAL(KIND=JPRB)    SPDIV_SI( KFLEV)
REAL(KIND=JPRB)    SPSVD_SI( KFLEV)
REAL(KIND=JPRB)    SPSPD_SI( KFLEV)
REAL(KIND=JPRB)    SPT_SI  ( KFLEV)
REAL(KIND=JPRB)    SPSP_SI(IPROMA) 

REAL(KIND=JPRB)    PREDIV(IPROMA), PRCORI(IPROMA)
REAL(KIND=JPRB)    ZSTORAGE_SIPR
REAL(KIND=JPRB)    ZSTORAGE_SITR

REAL(KIND=JPRB)    ZSTORAGE_SITLAH(0:KFLEV)
REAL(KIND=JPRB)    ZSTORAGE_SITLAF(  KFLEV)
REAL(KIND=JPRB)    ZSTORAGE_SIDELP(  KFLEV)
REAL(KIND=JPRB)    ZSTORAGE_SIDPHI(  KFLEV)
REAL(KIND=JPRB)    ZSTORAGE_SIRDEL(  KFLEV)
REAL(KIND=JPRB)    ZSTORAGE_SILNPR(  KFLEV)
REAL(KIND=JPRB)    ZSTORAGE_SIALPH(  KFLEV)
REAL(KIND=JPRB)    ZSTORAGE_SIRPRN, ZSTORAGE_SIRPRG

REAL(KIND=JPRB) :: ZPRES(IPROMA,0:KFLEV),ZPRESF(IPROMA,KFLEV)

REAL(KIND=JPRB) :: ZSVDT(IPROMA, KFLEV)
REAL(KIND=JPRB) :: MDIV (IPROMA, KFLEV)
REAL(KIND=JPRB) :: MSPD (IPROMA, KFLEV)
REAL(KIND=JPRB) :: MSPDL(IPROMA, KFLEV)
REAL(KIND=JPRB) :: MTL  (IPROMA, KFLEV)
REAL(KIND=JPRB) :: MSVD (IPROMA, KFLEV)
REAL(KIND=JPRB) :: MSPL (IPROMA)

REAL(KIND=JPRB) :: ZXYB(IPROMA,KFLEV,YYTXYB%NDIM)


!--------------------------------------------------

#include "gphpre.intfb.h"
#include "sigam.intfb.h"
#include "sitnu.intfb.h"


! Dimensions
IST    = 1
IEND   = 1

! store values 
ZSTORAGE_SIPR  = YDDYN%SIPR
ZSTORAGE_SITR  = YDDYN%SITR
ZSTORAGE_SIDELP = YDDYN%SIDELP
ZSTORAGE_SIRDEL = YDDYN%SIRDEL
ZSTORAGE_SILNPR = YDDYN%SILNPR
ZSTORAGE_SIALPH = YDDYN%SIALPH
ZSTORAGE_SITLAH = YDDYN%SITLAH
ZSTORAGE_SITLAF = YDDYN%SITLAF
ZSTORAGE_SIDPHI = YDDYN%SIDPHI
ZSTORAGE_SIRPRN = YDDYN%SIRPRN
ZSTORAGE_SIRPRG = YDDYN%SIRPRG

! redefine values by new values from arguments

YDDYN%SIPR   = PSIPR
YDDYN%SITR   = PSITR

! recompute SI quantities with respect to this SITR a SIPR
DO I=1,IPROMA
  ZPRES(I,KFLEV)=YDDYN%SIPR
ENDDO

LLSI=.TRUE.

CALL GPHPRE(IPROMA,KFLEV,IPROMA,IPROMA,YDGEOMETRY%YRVAB,YDGEOMETRY%YRCVER,ZPRES,PXYB=ZXYB,PRESF=ZPRESF)

DO JLEV=1,KFLEV
  YDDYN%SIDELP(JLEV)=ZXYB(1,JLEV,YYTXYB%M_DELP)
  YDDYN%SIRDEL(JLEV)=ZXYB(1,JLEV,YYTXYB%M_RDELP)
  YDDYN%SILNPR(JLEV)=ZXYB(1,JLEV,YYTXYB%M_LNPR)
  YDDYN%SIALPH(JLEV)=ZXYB(1,JLEV,YYTXYB%M_ALPH)
  YDDYN%SITLAH(JLEV)=ZPRES(1,JLEV)
ENDDO
DO JLEV=1,KFLEV
  YDDYN%SITLAF(JLEV)=ZXYB(1,JLEV,YYTXYB%M_DELP)/ZXYB(1,JLEV,YYTXYB%M_LNPR)
  YDDYN%SIDPHI(JLEV)=RD*YDDYN%SITR*ZXYB(1,JLEV,YYTXYB%M_LNPR)
ENDDO

YDDYN%SITLAH(0)=ZPRES(1,0)

YDDYN%SIRPRN = 1.0_JPRB/YDDYN%SIPR

YDDYN%SIRPRG = RD*YDDYN%SITR

! DO I = 1, KFLEV
!     WRITE(NULOUT,'("(MODEL MATRIX) ",7(1X,F12.5))') &
!      & SIDELP(I), SIRDEL(I), SILNPR(I), SIALPH(I), SITLAH(I), SITLAF(I), SIDPHI(I)
! ENDDO

! pointers 

ZLAPL   = -PKWAVE**2

INDX_D  = 0*KFLEV
INDX_T  = 1*KFLEV
INDX_PS = 2*KFLEV

LDGWADV  = .FALSE.

PREDIV = 1.0_JPRB
PRCORI = 0.0_JPRB

DO IMM = 1,MDIM

  ZVECTOR       = 0.0_JPRB
  ZVECTOR(IMM)  = 1.0_JPRB
  
  DO II=1,IPROMA
    MDIV (II, 1:KFLEV) = ZVECTOR(INDX_D +1:INDX_D +KFLEV)
    MTL  (II, 1:KFLEV) = ZVECTOR(INDX_T +1:INDX_T +KFLEV)
    MSPL (II )         = ZVECTOR(INDX_PS+1)
  ENDDO

  ! only for LSPRT (not used)
  SPDIV_SI = 0.0_JPRB
  SPSVD_SI = 0.0_JPRB
  SPT_SI   = 0.0_JPRB
  SPSPD_SI = 0.0_JPRB
  SPSP_SI  = 0.0_JPRB

  IPROFS=IEND-IST+1

  CALL SITNU(YDGEOMETRY,YDDYN,1,1,MDIV,SPT_SI,SPSP_SI,1)
  CALL SIGAM(YDGEOMETRY,YDDYN,1,1,SPDIV_SI,MTL,MSPL,1,KFLEV)

  MM(INDX_D +1:INDX_D +KFLEV,IMM) = -ZLAPL*SPDIV_SI(1:KFLEV)  
  MM(INDX_T +1:INDX_T +KFLEV,IMM) = -SPT_SI  (1:KFLEV)  
  MM(INDX_PS+1,IMM)               = -SPSP_SI(1)


ENDDO

! DO I=1,MDIM
!   WRITE(NULOUT,'(1000F8.4)') ( MM(I,J),J=1,MDIM )
! ENDDO

! restore original values
YDDYN%SIPR  = ZSTORAGE_SIPR
YDDYN%SITR  = ZSTORAGE_SITR
YDDYN%SIDELP = ZSTORAGE_SIDELP
YDDYN%SIRDEL = ZSTORAGE_SIRDEL
YDDYN%SILNPR = ZSTORAGE_SILNPR
YDDYN%SIALPH = ZSTORAGE_SIALPH
YDDYN%SITLAH = ZSTORAGE_SITLAH
YDDYN%SITLAF = ZSTORAGE_SITLAF
YDDYN%SIDPHI = ZSTORAGE_SIDPHI
YDDYN%SIRPRN = ZSTORAGE_SIRPRN
YDDYN%SIRPRG = ZSTORAGE_SIRPRG

RETURN
END 
