! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SUXFU(YDGEOMETRY,YDXFU,YDRIP,YDPHY,KULOUT)

!**** *SUXFU  * - ROUTINE TO INITIALIZE THE CONTROL OF INSTANTANEOUS FLUXES

!     PURPOSE.
!     --------
!        SET DEFAULT VALUES, THEN READS NAMELIST NAMXFU AND INITIALIZE POINTERS

!**   INTERFACE.
!     ----------
!        *CALL* *SUXFU(...)*

!     EXPLICIT ARGUMENTS :  KULOUT
!     --------------------

!     IMPLICIT ARGUMENTS :
!     --------------------
!        COMMON  YOMCFU

!     METHOD.
!     -------

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF RESEARCH DEPARTMENT DOCUMENTATION OF THE IFS

!     AUTHOR.
!     -------
!      O.CLARY 06/92
!      ORIGINAL : 06/92

!     MODIFICATIONS.
!     --------------
!      R. El Khatib : 01-04-23 LXQCLS,HUn,HUx
!      R. El Khatib : 01-08-07 pruning options
!      R. El Khatib : 03-04-17 Fullpos improvments
!      M.Hamrud     : 01-Oct-2003 CY28 Cleaning
!      Y.Bouteloup  : 26-Mars-2004 introduction of MTS radiance
!      F.Bouyssel   : 04-09-15 LXFU forced to false if .NOT.LMPHYS
!      R. El Khatib : 05-02-21 specific frequency array to reset extreme T2m and HU2m
!      F.Bouyssel   : 05-11-10 Introduction of  QICE and QLI
!      Y.Seity      : 07-01-15  add Graupel and Hail in XFU
!      S. Riette    : 09-05-05 extreme gusts and mean wind added
!      S. Riette    : 24-02-2010 extreme gusts over NXGSTPERIOD seconds
!      Y.Seity      : 04-01-11  add Hail diagnostic in XFU
!      R. El Khatib : 10-Aug-2011 NIOLEVG management
!      R. El Khatib : 01-Mar-2012 LFPOS => NFPOS
!      T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!      R. Brozkova  : 07-2018 Added mean radiant temperature.
!      I. Etchevers : 04-2019 Add Visibilities, Ptype (frequent and severe) and T'W at 2 meters
!-----------------------------------------------------------------------

USE YOMRIP       , ONLY : TRIP
USE YOMXFU       , ONLY : TXFU, JPFUXT
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM     ,JPRB
USE YOMHOOK      , ONLY : LHOOK    ,DR_HOOK, JPHOOK
USE YOMLUN       , ONLY : NULNAM
USE YOMPHY       , ONLY : TPHY
USE YOMCT0       , ONLY : NFPOS    ,LECMWF, NCONF
USE YOMFA        , ONLY : YFA_X10U ,YFA_X10V ,YFA_X10NU,YFA_X10NV,&
 &                        YFA_X2RH ,YFA_X2SH ,YFA_X2T  ,YFA_X2TPW ,YFA_XCAPE,&
 &                        YFA_XCTOP,YFA_XCCC ,YFA_XCLPH,YFA_XCP  ,YFA_XCSF ,YFA_XN2HU,&
 &                        YFA_XCVQ ,YFA_XCVS ,YFA_XCVU ,YFA_XCVV ,YFA_XGDU ,YFA_XGDV ,&
 &                        YFA_XHCC ,YFA_XLCC ,YFA_XLSP ,YFA_XLSS ,YFA_XLSG ,YFA_XCSG ,&
 &                        YFA_XLSH ,YFA_XCSH ,YFA_XMCC ,YFA_XX2HU,YFA_XTHW ,YFA_XXDIAGH,&
 &                        YFA_XMOCO,YFA_XN2T ,YFA_XSSR ,YFA_XSTR ,YFA_XTCC ,YFA_XTUQ ,&
 &                        YFA_XTUS ,YFA_XTUU ,YFA_XTUV ,YFA_XUGST,YFA_XVGST,&
 &                        YFA_XUGST2 ,YFA_XVGST2 ,YFA_XX2T ,YFA_XVEIN ,YFA_XMRT,&
 &                        YFA_VISICLD ,YFA_VISIHYD ,YFA_MXCLWC ,YFA_XPTYPE ,YFA_XPTYPESEV,&
 &                        YFA_VISICLD2,YFA_VISIHYD2,YFA_MXCLWC2,YFA_XPTYPE2,YFA_XPTYPESEV2

IMPLICIT NONE

TYPE(GEOMETRY)    , INTENT(INOUT) :: YDGEOMETRY
TYPE(TXFU),TARGET , INTENT(INOUT) :: YDXFU
TYPE(TRIP)        , INTENT(INOUT) :: YDRIP
TYPE(TPHY)        , INTENT(INOUT) :: YDPHY
INTEGER(KIND=JPIM), INTENT(IN)    :: KULOUT 

INTEGER(KIND=JPIM), PARAMETER :: JPKIND=6
INTEGER(KIND=JPIM) :: IP, J, IPAR, IK, INF550, INF850, JF, JL, IADD
INTEGER(KIND=JPIM) :: INLEV(YDGEOMETRY%YRDIMV%NFLEVG+1,JPKIND), ILEV(JPKIND)

CHARACTER(LEN=4) :: CLPRE(YDGEOMETRY%YRDIMV%NFLEVG+1,JPKIND), CLEVS(1)
CHARACTER(LEN=16) :: CLSU
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

LOGICAL, POINTER :: LXFU, LXTRD, LXTRC, LXTRT, LXPLC, LXPLCG, LXPLCH, LXPLS,&
 & LXPLSG, LXPLSH, LXR, LXNEBTT, LXNEBPA, LXCLS, LXTTCLS,LXHHCLS, LXTPWCLS, LXQCLS,&
 & LXSOIL, LTXTRD, LTXTRC, LTXTRT, LTXR, LTXNEB, LTXQICE, LTXQLI, LXICV, LXCTOP,&
 & LXCLP, LXTGST, LXXGST, LXXGST2, LXTHW, LXXDIAGH, LXMWINDCLS, LXNUVCLS,&
 & LXVEIN, LXMRT, LXVISI, LXVISI2
INTEGER(KIND=JPIM), POINTER :: NFRXFU, NXFUTS(:), NFRRAZ, NRAZTS(:), N1RAZ,&
 & MEANPERIOD, NXGSTPERIOD, NXGSTPERIOD2, NVISIPERIOD,NVISIPERIOD2

#include "namxfu.nam.h"

#include "posnam.intfb.h"
#include "seapre.intfb.h"
#include "sufpxfu.intfb.h"

!      ----------------------------------------------------------------

!*       1.    SET DEFAULT VALUES.
!              -------------------

!        1.1 Set implicit default values

IF (LHOOK) CALL DR_HOOK('SUXFU',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM, &
  & YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, &
  & YDMP=>YDGEOMETRY%YRMP, YDSTA=>YDGEOMETRY%YRSTA)
ASSOCIATE(NGPTOT=>YDGEM%NGPTOT, &
 & STPRE=>YDSTA%STPRE, & 
 & LREAXFU=>YDXFU%LREAXFU, &
 & NFDXFU=>YDXFU%NFDXFU, NMEANSTEPS=>YDXFU%NMEANSTEPS, &
 & NTYPXFU=>YDXFU%NTYPXFU, &
 & TYPE_XFU=>YDXFU%TYPE_XFU, &
 & NIOLEVG=>YDDIMV%NIOLEVG, NFLEVG=>YDDIMV%NFLEVG, &
 & LMPHYS=>YDPHY%LMPHYS, LNEIGE=>YDPHY%LNEIGE, &
 & LSOLV=>YDPHY%LSOLV,TSTEP=>YDRIP%TSTEP,&
 & LDPRECIPS=>YDPHY%LDPRECIPS,LDPRECIPS2=>YDPHY%LDPRECIPS2)
! Associate pointers for variables in namelist
LXFU        => YDXFU%LXFU
NFRXFU      => YDXFU%NFRXFU
NXFUTS      => YDXFU%NXFUTS
NFRRAZ      => YDXFU%NFRRAZ
NRAZTS      => YDXFU%NRAZTS
N1RAZ       => YDXFU%N1RAZ
LXTRD       => YDXFU%LXTRD
LXTRC       => YDXFU%LXTRC
LXTRT       => YDXFU%LXTRT
LXPLC       => YDXFU%LXPLC
LXPLCG      => YDXFU%LXPLCG
LXPLCH      => YDXFU%LXPLCH
LXPLS       => YDXFU%LXPLS
LXPLSG      => YDXFU%LXPLSG
LXPLSH      => YDXFU%LXPLSH
LXR         => YDXFU%LXR
LXNEBTT     => YDXFU%LXNEBTT
LXNEBPA     => YDXFU%LXNEBPA
LXCLS       => YDXFU%LXCLS
LXNUVCLS    => YDXFU%LXNUVCLS
LXTTCLS     => YDXFU%LXTTCLS
LXHHCLS     => YDXFU%LXHHCLS
LXTPWCLS    => YDXFU%LXTPWCLS
LXQCLS      => YDXFU%LXQCLS
LXSOIL      => YDXFU%LXSOIL
LTXTRD      => YDXFU%LTXTRD
LTXTRC      => YDXFU%LTXTRC
LTXTRT      => YDXFU%LTXTRT
LTXR        => YDXFU%LTXR
LTXNEB      => YDXFU%LTXNEB
LTXQICE     => YDXFU%LTXQICE
LTXQLI      => YDXFU%LTXQLI
LXICV       => YDXFU%LXICV
LXCTOP      => YDXFU%LXCTOP
LXCLP       => YDXFU%LXCLP
LXVEIN      => YDXFU%LXVEIN
LXMRT       => YDXFU%LXMRT
LXTGST      => YDXFU%LXTGST
LXXGST      => YDXFU%LXXGST
LXXGST2     => YDXFU%LXXGST2
LXTHW       => YDXFU%LXTHW
LXXDIAGH    => YDXFU%LXXDIAGH
LXMWINDCLS  => YDXFU%LXMWINDCLS
MEANPERIOD  => YDXFU%MEANPERIOD
NXGSTPERIOD => YDXFU%NXGSTPERIOD
NXGSTPERIOD2=> YDXFU%NXGSTPERIOD2
LXVISI      => YDXFU%LXVISI
LXVISI2     => YDXFU%LXVISI2
NVISIPERIOD => YDXFU%NVISIPERIOD
NVISIPERIOD2=> YDXFU%NVISIPERIOD2

LXFU   = .FALSE.
LREAXFU= .FALSE.
LXTRD  = .FALSE.
LTXTRD = .FALSE.
LXTRC  = .FALSE.
LTXTRC = .FALSE.
LXTRT  = .FALSE.
LTXTRT = .FALSE.
LXPLC  = .FALSE.
LXPLCH = .FALSE.
LXPLCG = .FALSE.
LXPLS  = .FALSE.
LXPLSH = .FALSE.
LXPLSG = .FALSE.
LXR    = .FALSE.
LTXR   = .FALSE.
LTXNEB = .FALSE.
LTXQICE= .FALSE.
LTXQLI = .FALSE.
LXNEBTT= .FALSE.
LXNEBPA= .FALSE.
LXSOIL = .FALSE.
LXICV  = .FALSE.
LXCTOP = .FALSE.
LXCLS  = .FALSE.
LXNUVCLS = .FALSE.
LXMWINDCLS = .FALSE.
LXQCLS = .FALSE.
LXTTCLS= .FALSE.
LXHHCLS= .FALSE.
LXTPWCLS= .FALSE.
LXCLP  = .FALSE.
LXVEIN = .FALSE.
LXMRT  = .FALSE.
LXTGST = .FALSE.
LXXGST = .FALSE.
LXXGST2 = .FALSE.
LXTHW  = .FALSE.
LXXDIAGH= .FALSE.
LXVISI = .FALSE.
LXVISI2= .FALSE.

DO J=0,JPFUXT
  NXFUTS(J)=0
  NRAZTS(J)=0
ENDDO
NFRXFU   =20
NFRRAZ   =20
N1RAZ    =1
NMEANSTEPS=1_JPIM
MEANPERIOD=600_JPIM
NXGSTPERIOD=3600_JPIM ! max gusts calculation over one hour until next IHISTS event...
NXGSTPERIOD2=900_JPIM ! max gusts calculation over 15 minutes (reset every 15')
NVISIPERIOD=3600_JPIM ! min visi and max CLWC over one hour
NVISIPERIOD2=900_JPIM ! min visi and max CLWC over 15 minutes

!        1.2 Modify default values according to LECMWF

IF (LECMWF) THEN
ELSE
  NFRXFU=9999999
  NXFUTS(0)=1
  NXFUTS(1)=1
  NRAZTS(0)=-27
! Reset every 3 hours until H54, then every 6 hours.
  NFRRAZ=1
  NRAZTS(1)=-0
  NRAZTS(2)=-3
  NRAZTS(3)=-6
  NRAZTS(4)=-9
  NRAZTS(5)=-12
  NRAZTS(6)=-15
  NRAZTS(7)=-18
  NRAZTS(8)=-21
  NRAZTS(9)=-24
  NRAZTS(10)=-27
  NRAZTS(11)=-30
  NRAZTS(12)=-33
  NRAZTS(13)=-36
  NRAZTS(14)=-39
  NRAZTS(15)=-42
  NRAZTS(16)=-45
  NRAZTS(17)=-48
  NRAZTS(18)=-51
  NRAZTS(19)=-54
  NRAZTS(20)=-60
  NRAZTS(21)=-66
  NRAZTS(22)=-72
  NRAZTS(23)=-78
  NRAZTS(24)=-84
  NRAZTS(25)=-90
  NRAZTS(26)=-96
  NRAZTS(27)=-102
ENDIF

!      ----------------------------------------------------------------

!*       2.    MODIFIES DEFAULT VALUES.
!              ------------------------

CALL POSNAM(NULNAM,'NAMXFU')
READ(NULNAM,NAMXFU)

IF (NFPOS /= 0) THEN
  CALL SUFPXFU(YDXFU,YDRIP,YDPHY)
ENDIF
IF (LXFU .AND. .NOT.LMPHYS) THEN
  LXFU=.FALSE.
ENDIF
   
LXTRD  =LXTRD  .AND.LXFU
LXTRC  =LXTRC  .AND.LXFU
LXTRT  =LXTRT  .AND.LXFU
LXPLC  =LXPLC  .AND.LXFU
LXPLS  =LXPLS  .AND.LXFU
LXR    =LXR    .AND.LXFU
LTXNEB =LTXNEB .AND.LXFU
LTXQICE=LTXQICE.AND.LXFU
LTXQLI =LTXQLI .AND.LXFU
LXNEBTT=LXNEBTT.AND.LXFU
LXNEBPA=LXNEBPA.AND.LXFU
LXSOIL =LXSOIL .AND.LXFU
LXICV  =LXICV  .AND.LXFU 
LXCTOP =LXCTOP .AND.LXFU 
LXCLS  =LXCLS  .AND.LXFU
LXNUVCLS=LXNUVCLS  .AND.LXFU
LXTTCLS=LXTTCLS.AND.LXFU
LXQCLS =LXQCLS .AND.LXFU
LXHHCLS=LXHHCLS.AND.LXFU
LXTPWCLS=LXTPWCLS.AND.LXFU
LXCLP  =LXCLP  .AND.LXFU
LXVEIN =LXVEIN .AND.LXFU
LXMRT  =LXMRT  .AND.LXFU
LXTGST =LXTGST .AND.LXFU
LXXGST =LXXGST .AND.LXFU
LXXGST2=LXXGST2.AND.LXFU
LXVISI =LXVISI .AND.LXFU
LXVISI2=LXVISI2.AND.LXFU
LXXDIAGH=LXXDIAGH.AND.LXFU
!mean winds require instanteneous winds
LXMWINDCLS=LXMWINDCLS.AND.(LXCLS.OR.LXNUVCLS)
IF (NCONF /= 903) THEN
  ! For compatibility with older files, in offline pp, a field should be deactivated unless explicitely requested.
  ! However, the activation of basic CLS fields will trigger tpwcls in other cases :
  LXTPWCLS=LXCLS.AND.LXFU
ENDIF

IF(LXXGST.AND.MOD(TSTEP,REAL(NXGSTPERIOD))/=0.) THEN
  WRITE(KULOUT,*)'WARNING NGSTPERIOD DO NOT EXACTLY DIVIDE TSTEP'
  WRITE(KULOUT,*)'MAX GUST CALCULATION MAY BE WRONG',&
                       &MOD(TSTEP,REAL(NXGSTPERIOD))
ENDIF
IF(LXXGST2.AND.MOD(TSTEP,REAL(NXGSTPERIOD2))/=0.) THEN
  WRITE(KULOUT,*)'WARNING NGSTPERIOD2 DO NOT EXACTLY DIVIDE TSTEP'
  WRITE(KULOUT,*)'MAX GUST CALCULATION MAY BE WRONG',&
                       &MOD(TSTEP,REAL(NXGSTPERIOD2))
ENDIF

IF(LXVISI.AND.MOD(TSTEP,REAL(NVISIPERIOD))/=0.) THEN
   WRITE(KULOUT,*)'WARNING NVISIPERIOD DO NOT EXACTLY DIVIDE TSTEP'
   WRITE(KULOUT,*)'MIN VISI CALCULATION MAY BE WRONG',&
                        &MOD(TSTEP,REAL(NVISIPERIOD))
ENDIF
IF(LXVISI2.AND.MOD(TSTEP,REAL(NVISIPERIOD2))/=0.) THEN
   WRITE(KULOUT,*)'WARNING NVISIPERIOD2 DO NOT EXACTLY DIVIDE TSTEP'
   WRITE(KULOUT,*)'MIN VISI CALCULATION MAY BE WRONG',&
                        &MOD(TSTEP,REAL(NVISIPERIOD2))
ENDIF

IF(LXXGST.AND.MOD(TSTEP,REAL(NXGSTPERIOD))/=0.) THEN
  WRITE(KULOUT,*)'WARNING NGSTPERIOD DO NOT EXACTLY DIVIDE TSTEP'
  WRITE(KULOUT,*)'MAX GUST CALCULATION MAY BE WRONG',&
                       &MOD(TSTEP,REAL(NXGSTPERIOD))
ENDIF
IF(LXXGST2.AND.MOD(TSTEP,REAL(NXGSTPERIOD2))/=0.) THEN
  WRITE(KULOUT,*)'WARNING NGSTPERIOD2 DO NOT EXACTLY DIVIDE TSTEP'
  WRITE(KULOUT,*)'MAX GUST CALCULATION MAY BE WRONG',&
                       &MOD(TSTEP,REAL(NXGSTPERIOD2))
ENDIF

IF(LXVISI.AND.MOD(TSTEP,REAL(NVISIPERIOD))/=0.) THEN
   WRITE(KULOUT,*)'WARNING NVISIPERIOD DO NOT EXACTLY DIVIDE TSTEP'
   WRITE(KULOUT,*)'MIN VISI CALCULATION MAY BE WRONG',&
                        &MOD(TSTEP,REAL(NVISIPERIOD))
ENDIF
IF(LXVISI2.AND.MOD(TSTEP,REAL(NVISIPERIOD2))/=0.) THEN
   WRITE(KULOUT,*)'WARNING NVISIPERIOD2 DO NOT EXACTLY DIVIDE TSTEP'
   WRITE(KULOUT,*)'MIN VISI CALCULATION MAY BE WRONG',&
                        &MOD(TSTEP,REAL(NVISIPERIOD2))
ENDIF


!      ----------------------------------------------------------------

!*       3.    INITIALIZE DESCRIPTORS
!              ----------------------

!        3.1 Preinitialize the vertical levels and prefixes for *FA* files

CLEVS(1) = 'S   '

! On each half level :
IK=1
ILEV(IK)=NFLEVG+1
DO J=1,ILEV(IK)
  CLPRE(J,IK)=CLEVS(1)
  INLEV(J,IK)=J-1+NIOLEVG-NFLEVG
ENDDO
! At the surface
IK=2
ILEV(IK)=1
CLPRE(1,IK)='SURF'
INLEV(1,IK)=NIOLEVG
! On each full level :
IK=3
ILEV(IK)=NFLEVG
DO J=1,ILEV(IK)
  CLPRE(J,IK)=CLEVS(1)
  INLEV(J,IK)=J+NIOLEVG-NFLEVG
ENDDO
! At the top and the surface :
IK=4
ILEV(IK)=2
CLPRE(1,IK)='SOMM'
CLPRE(2,IK)='SURF'
INLEV(1,IK)=NIOLEVG-NFLEVG
INLEV(2,IK)=NIOLEVG
! At a given model level
IK=5
ILEV(IK)=1
CLPRE(1,IK)=CLEVS(1)

!        3.2 Setup descripors

IP=0
IADD=1

!        3.2.1 STRess of gravity wave Drag :

YDXFU%YXFUPT%MXTRDU=0
YDXFU%YXFUPT%MXTRDV=0
IF (LXTRD) THEN
  IF (LTXTRD) THEN
!   On each half level : 
    IK=1 
  ELSE
!   At the surface :
    IK=2 
  ENDIF
  IPAR=1
  CLSU=YFA_XGDU%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDXFU%YXFUPT%MXTRDU)
  CLSU=YFA_XGDV%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDXFU%YXFUPT%MXTRDV)
ENDIF

!        3.2.2 STRess of Convection :

YDXFU%YXFUPT%MXTRCU=0
YDXFU%YXFUPT%MXTRCV=0
YDXFU%YXFUPT%MXDICQ=0
YDXFU%YXFUPT%MXDICS=0
IF (LXTRC) THEN
  IF (LTXTRC) THEN
!   On each half level :
    IK=1
  ELSE
!   At the model level the closest to 550 hPa :
    IK=5
    CALL SEAPRE(55000._JPRB,INF550,STPRE,NFLEVG)
    INLEV(1,IK)=INF550-1
  ENDIF
  CLSU=YFA_XCVU%CLNAME(5:)
  IPAR=1
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDXFU%YXFUPT%MXTRCU)
  CLSU=YFA_XCVV%CLNAME(5:)
  IPAR=1
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDXFU%YXFUPT%MXTRCV)
  IF (LTXTRC) THEN
!   On each half level :
    IK=1
  ELSE
!   At the model level the closest to 850 hPa :
    IK=5
    CALL SEAPRE(85000._JPRB,INF850,STPRE,NFLEVG)
    INLEV(1,IK)=INF850-1
  ENDIF
  CLSU=YFA_XCVQ%CLNAME(5:)
  IPAR=0
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDXFU%YXFUPT%MXDICQ)
  CLSU=YFA_XCVS%CLNAME(5:)
  IPAR=0
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDXFU%YXFUPT%MXDICS)
ENDIF

!        3.2.3 STRess of Turbulence, or Surface Fluxes

YDXFU%YXFUPT%MXTRTU=0
YDXFU%YXFUPT%MXTRTV=0
YDXFU%YXFUPT%MXDITQ=0
YDXFU%YXFUPT%MXDITS=0
IF (LXTRT) THEN
  IF (LTXTRT) THEN
!   On each half level :
    IK=1
  ELSE
!   At the surface :
    IK=2
  ENDIF
  CLSU=YFA_XTUU%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),1,YDXFU%YXFUPT%MXTRTU)
  CLSU=YFA_XTUV%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),1,YDXFU%YXFUPT%MXTRTV)
  IF (LXTRT) THEN
    CLSU=YFA_XTUQ%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDXFU%YXFUPT%MXDITQ)
    CLSU=YFA_XTUS%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDXFU%YXFUPT%MXDITS)
  ENDIF
ENDIF

!        3.2.4 Flux de PLuie  neige graupel et grele Convective 
!          (Convective rain snow graupel and hail) 

YDXFU%YXFUPT%MXPLCL=0
YDXFU%YXFUPT%MXPLCN=0
YDXFU%YXFUPT%MXPLCG=0
YDXFU%YXFUPT%MXPLCH=0
IF (LXPLC) THEN
  IK=2
  CLSU=YFA_XCP%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDXFU%YXFUPT%MXPLCL)
  IF (LNEIGE) THEN
    CLSU=YFA_XCSF%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDXFU%YXFUPT%MXPLCN)
  ENDIF
  IF (LXPLCG) THEN
    CLSU=YFA_XCSG%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDXFU%YXFUPT%MXPLCG)
  ENDIF
  IF (LXPLCH) THEN
    CLSU=YFA_XCSH%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDXFU%YXFUPT%MXPLCH)
  ENDIF
ENDIF

!        3.2.5 Flux de PLuie et neige graupel et grele Stratiforme
!               (Stratiform rain snow graupel and hail)

YDXFU%YXFUPT%MXPLSL=0
YDXFU%YXFUPT%MXPLSN=0
YDXFU%YXFUPT%MXPLSG=0
YDXFU%YXFUPT%MXPLSH=0
IF (LXPLS) THEN
  IK=2
  CLSU=YFA_XLSP%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDXFU%YXFUPT%MXPLSL)
  IF (LNEIGE) THEN
    CLSU=YFA_XLSS%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDXFU%YXFUPT%MXPLSN)
  ENDIF
  IF (LXPLSG) THEN
    CLSU=YFA_XLSG%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDXFU%YXFUPT%MXPLSG)
  ENDIF
  IF (LXPLSH) THEN
    CLSU=YFA_XLSH%CLNAME(5:)
    CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),0,YDXFU%YXFUPT%MXPLSH)
  ENDIF
ENDIF

!        3.2.6 Fluxes of Radiation

YDXFU%YXFUPT%MXRSO=0
YDXFU%YXFUPT%MXRTH=0
IF (LXR) THEN
  IF (LTXR) THEN
!   On each half level :
    IK=1
  ELSE
    IK=4
  ENDIF
  IPAR=0
  CLSU=YFA_XSSR%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDXFU%YXFUPT%MXRSO)
  CLSU=YFA_XSTR%CLNAME(5:)
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDXFU%YXFUPT%MXRTH)
ENDIF

!        3.2.7 NEBulosite (Cloudiness),Qice,Qliq  : as 3D variables

YDXFU%YXFUPT%MXNEB=0
IF (LTXNEB) THEN
! On each full level :
  IK=3
  IPAR=0
  CLSU='NEBULOSI.TOT'
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDXFU%YXFUPT%MXNEB)
ENDIF

YDXFU%YXFUPT%MXQICE=0
IF (LTXQICE) THEN
! On each full level :
  IK=3
  IPAR=0
  CLSU='HUMISOLI.TOT'
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDXFU%YXFUPT%MXQICE)
ENDIF

YDXFU%YXFUPT%MXQLI=0
IF (LTXQLI) THEN
! On each full level :
  IK=3
  IPAR=0
  CLSU='HUMILIQU.TOT'
  CALL NEXTYPE3(CLPRE(1,IK),CLSU,INLEV(1,IK),ILEV(IK),IPAR,YDXFU%YXFUPT%MXQLI)
ENDIF

!        3.2.8 NEBulosite Totale (Total Cloudiness) : as seen from bottom

YDXFU%YXFUPT%MXNEBT=0
IF (LXNEBTT) THEN
  CALL NEXTYPE1(YFA_XTCC%CLNAME(1:4),YFA_XTCC%CLNAME(5:),0,YDXFU%YXFUPT%MXNEBT)
ENDIF

!        3.2.9 SOIL fluxes

YDXFU%YXFUPT%MXFONTE=0
YDXFU%YXFUPT%MXFCHSP=0
YDXFU%YXFUPT%MXFLWSP=0
YDXFU%YXFUPT%MXFEVL =0
YDXFU%YXFUPT%MXRUISS=0
YDXFU%YXFUPT%MXRUISP=0
YDXFU%YXFUPT%MXFEVV =0
YDXFU%YXFUPT%MXFTR  =0
YDXFU%YXFUPT%MXRUISL=0
IF (LXSOIL) THEN
  CALL NEXTYPE1('SURF','XFONTE NEIGE    ',0,YDXFU%YXFUPT%MXFONTE)
  CALL NEXTYPE1('SURF','XCHAL. DS SOL   ',0,YDXFU%YXFUPT%MXFCHSP)
  CALL NEXTYPE1('SURF','XEAU DANS SOL   ',0,YDXFU%YXFUPT%MXFLWSP)
  CALL NEXTYPE1('SURF','XFLU.MEVAP.EAU  ',0,YDXFU%YXFUPT%MXFEVL)
  CALL NEXTYPE1('SURF','XRUISSELLEMENT  ',0,YDXFU%YXFUPT%MXRUISS)
  CALL NEXTYPE1('PROF','XRUISSELLEMENT  ',0,YDXFU%YXFUPT%MXRUISP)
  IF (LSOLV) THEN
    CALL NEXTYPE1('SURF','XEVAPOTRANSPIRAT',0,YDXFU%YXFUPT%MXFEVV )
    CALL NEXTYPE1('SURF','XTRANSPIRATION  ',0,YDXFU%YXFUPT%MXFTR  )
    CALL NEXTYPE1('SURF','XRUISS. INTERCEP',0,YDXFU%YXFUPT%MXRUISL)
  ENDIF
ENDIF

!        3.2.10 NEBulosite PARtielles (partial cloudiness)

YDXFU%YXFUPT%MXNBCON=0
YDXFU%YXFUPT%MXNBHAU=0
YDXFU%YXFUPT%MXNBMOY=0
YDXFU%YXFUPT%MXNBBAS=0
IF (LXNEBPA) THEN
  CALL NEXTYPE1(YFA_XCCC%CLNAME(1:4),YFA_XCCC%CLNAME(5:),0,YDXFU%YXFUPT%MXNBCON)
  CALL NEXTYPE1(YFA_XHCC%CLNAME(1:4),YFA_XHCC%CLNAME(5:),0,YDXFU%YXFUPT%MXNBHAU)
  CALL NEXTYPE1(YFA_XMCC%CLNAME(1:4),YFA_XMCC%CLNAME(5:),0,YDXFU%YXFUPT%MXNBMOY)
  CALL NEXTYPE1(YFA_XLCC%CLNAME(1:4),YFA_XLCC%CLNAME(5:),0,YDXFU%YXFUPT%MXNBBAS)
ENDIF

!        3.2.11 Indexes of ConVection

YDXFU%YXFUPT%MXCAPE =0
YDXFU%YXFUPT%MXCTOP =0
YDXFU%YXFUPT%MXMOCON=0
IF (LXICV) THEN
  CALL NEXTYPE1(YFA_XCAPE%CLNAME(1:4),YFA_XCAPE%CLNAME(5:),0,YDXFU%YXFUPT%MXCAPE)
  CALL NEXTYPE1(YFA_XMOCO%CLNAME(1:3),YFA_XMOCO%CLNAME(4:),0,YDXFU%YXFUPT%MXMOCON)
ENDIF
IF (LXCTOP) THEN
  CALL NEXTYPE1(YFA_XCTOP%CLNAME(1:3),YFA_XCTOP%CLNAME(4:),0,YDXFU%YXFUPT%MXCTOP)
ENDIF

!        3.2.12 PBL fields 

YDXFU%YXFUPT%MXUCLS=0
YDXFU%YXFUPT%MXVCLS=0
YDXFU%YXFUPT%MXNUCLS=0
YDXFU%YXFUPT%MXNVCLS=0
YDXFU%YXFUPT%MXTCLS=0
YDXFU%YXFUPT%MXTPWCLS=0
YDXFU%YXFUPT%MXQCLS=0
YDXFU%YXFUPT%MXRHCLS=0
YDXFU%YXFUPT%MXTN=0
YDXFU%YXFUPT%MXTX=0
YDXFU%YXFUPT%MXHUN=0
YDXFU%YXFUPT%MXHUX=0
IF (LXCLS) THEN
  CALL NEXTYPE1(YFA_X10U%CLNAME(1:3),YFA_X10U%CLNAME(4:),1,YDXFU%YXFUPT%MXUCLS)
  CALL NEXTYPE1(YFA_X10V%CLNAME(1:3),YFA_X10V%CLNAME(4:),1,YDXFU%YXFUPT%MXVCLS)
  IF (LXMWINDCLS) THEN
    ALLOCATE(YDXFU%RMWINDCALC(NGPTOT))
  ENDIF
ENDIF
IF (LXCLS) THEN
  CALL NEXTYPE1(YFA_X2T%CLNAME(1:3),YFA_X2T%CLNAME(4:),0,YDXFU%YXFUPT%MXTCLS)
  CALL NEXTYPE1(YFA_X2RH%CLNAME(1:3),YFA_X2RH%CLNAME(4:),0,YDXFU%YXFUPT%MXRHCLS)
  IF (LXQCLS) THEN
    CALL NEXTYPE1(YFA_X2SH%CLNAME(1:3),YFA_X2SH%CLNAME(4:),0,YDXFU%YXFUPT%MXQCLS)
  ENDIF
ENDIF
IF (LXNUVCLS) THEN
  CALL NEXTYPE1(YFA_X10NU%CLNAME(1:3),YFA_X10NU%CLNAME(4:),1,YDXFU%YXFUPT%MXNUCLS)
  CALL NEXTYPE1(YFA_X10NV%CLNAME(1:3),YFA_X10NV%CLNAME(4:),1,YDXFU%YXFUPT%MXNVCLS)
  IF (LXMWINDCLS) THEN
    ALLOCATE(YDXFU%RMNWINDCALC(NGPTOT))
  ENDIF
ENDIF
IF (LXTTCLS) THEN
  CALL NEXTYPE1(YFA_XN2T%CLNAME(1:3),YFA_XN2T%CLNAME(4:),0,YDXFU%YXFUPT%MXTN)
  CALL NEXTYPE1(YFA_XX2T%CLNAME(1:3),YFA_XX2T%CLNAME(4:),0,YDXFU%YXFUPT%MXTX)
ENDIF
IF (LXHHCLS) THEN
  CALL NEXTYPE1(YFA_XN2HU%CLNAME(1:3),YFA_XN2HU%CLNAME(4:),0,YDXFU%YXFUPT%MXHUN)
  CALL NEXTYPE1(YFA_XX2HU%CLNAME(1:3),YFA_XX2HU%CLNAME(4:),0,YDXFU%YXFUPT%MXHUX)
ENDIF
IF (LXTPWCLS) THEN
  CALL NEXTYPE1(YFA_X2TPW%CLNAME(1:3),YFA_X2TPW%CLNAME(4:),0,YDXFU%YXFUPT%MXTPWCLS)
ENDIF

!        3.2.13 PBL height 

YDXFU%YXFUPT%MXCLPH=0
IF (LXCLP) THEN
  CALL NEXTYPE1(YFA_XCLPH%CLNAME(1:3),YFA_XCLPH%CLNAME(4:),0,YDXFU%YXFUPT%MXCLPH)
ENDIF
YDXFU%YXFUPT%MXVEIN=0
IF (LXVEIN) THEN
  CALL NEXTYPE1(YFA_XVEIN%CLNAME(1:3),YFA_XVEIN%CLNAME(4:),0,YDXFU%YXFUPT%MXVEIN)
ENDIF
YDXFU%YXFUPT%MXMRT=0
IF (LXMRT) THEN
  CALL NEXTYPE1(YFA_XMRT%CLNAME(1:3),YFA_XMRT%CLNAME(4:),0,YDXFU%YXFUPT%MXMRT)
ENDIF

!        3.2.14 Gusts 

YDXFU%YXFUPT%MXUGST=0
YDXFU%YXFUPT%MXVGST=0
IF (LXTGST.OR.LXXGST) THEN
  CALL NEXTYPE1(YFA_XUGST%CLNAME(1:3),YFA_XUGST%CLNAME(4:),1,YDXFU%YXFUPT%MXUGST)
  CALL NEXTYPE1(YFA_XVGST%CLNAME(1:3),YFA_XVGST%CLNAME(4:),1,YDXFU%YXFUPT%MXVGST)
ENDIF

YDXFU%YXFUPT%MXUGST2=0
YDXFU%YXFUPT%MXVGST2=0
IF (LXXGST2) THEN
  CALL NEXTYPE1(YFA_XUGST2%CLNAME(1:3),YFA_XUGST2%CLNAME(4:),1,YDXFU%YXFUPT%MXUGST2)
  CALL NEXTYPE1(YFA_XVGST2%CLNAME(1:3),YFA_XVGST2%CLNAME(4:),1,YDXFU%YXFUPT%MXVGST2)
ENDIF

!        3.2.16 Theta'w' 

YDXFU%YXFUPT%MXTHW=0
IF (LXTHW) THEN
  CALL NEXTYPE1(YFA_XTHW%CLNAME(1:3),YFA_XTHW%CLNAME(4:),0,YDXFU%YXFUPT%MXTHW)
ENDIF

!        3.2.17 Hail diagnostic

YDXFU%YXFUPT%MXXDIAGH=0
IF (LXXDIAGH) THEN
  CALL NEXTYPE1(YFA_XXDIAGH%CLNAME(1:3),YFA_XXDIAGH%CLNAME(4:),0,YDXFU%YXFUPT%MXXDIAGH)
ENDIF

!        3.2.18 Visibilities diagnostics

YDXFU%YXFUPT%MXVISICLD=0
YDXFU%YXFUPT%MXVISIHYD=0
YDXFU%YXFUPT%MXCLWC=0
IF (LXVISI) THEN
  CALL NEXTYPE1(YFA_VISICLD%CLNAME(1:3),YFA_VISICLD%CLNAME(4:),0,YDXFU%YXFUPT%MXVISICLD)
  CALL NEXTYPE1(YFA_VISIHYD%CLNAME(1:3),YFA_VISIHYD%CLNAME(4:),0,YDXFU%YXFUPT%MXVISIHYD)
  CALL NEXTYPE1(YFA_MXCLWC%CLNAME(1:3),YFA_MXCLWC%CLNAME(4:),0,YDXFU%YXFUPT%MXCLWC)
ENDIF

YDXFU%YXFUPT%MXVISICLD2=0
YDXFU%YXFUPT%MXVISIHYD2=0
YDXFU%YXFUPT%MXCLWC2=0
IF (LXVISI2) THEN
  CALL NEXTYPE1(YFA_VISICLD2%CLNAME(1:3),YFA_VISICLD2%CLNAME(4:),0,YDXFU%YXFUPT%MXVISICLD2)
  CALL NEXTYPE1(YFA_VISIHYD2%CLNAME(1:3),YFA_VISIHYD2%CLNAME(4:),0,YDXFU%YXFUPT%MXVISIHYD2)
  CALL NEXTYPE1(YFA_MXCLWC2%CLNAME(1:3),YFA_MXCLWC2%CLNAME(4:),0,YDXFU%YXFUPT%MXCLWC2)
ENDIF

!        3.2.19 Precipitation type diagnostics
YDXFU%YXFUPT%MXPTYPE=0
YDXFU%YXFUPT%MXPTYPESEV=0
IF (LDPRECIPS) THEN
  CALL NEXTYPE1(YFA_XPTYPE%CLNAME(1:3),YFA_XPTYPE%CLNAME(4:),0,YDXFU%YXFUPT%MXPTYPE)
  CALL NEXTYPE1(YFA_XPTYPESEV%CLNAME(1:3),YFA_XPTYPESEV%CLNAME(4:),0,YDXFU%YXFUPT%MXPTYPESEV)
ENDIF

YDXFU%YXFUPT%MXPTYPE2=0
YDXFU%YXFUPT%MXPTYPESEV2=0
IF (LDPRECIPS2) THEN
  CALL NEXTYPE1(YFA_XPTYPE2%CLNAME(1:3),YFA_XPTYPE2%CLNAME(4:),0,YDXFU%YXFUPT%MXPTYPE2)
  CALL NEXTYPE1(YFA_XPTYPESEV2%CLNAME(1:3),YFA_XPTYPESEV2%CLNAME(4:),0,YDXFU%YXFUPT%MXPTYPESEV2)
ENDIF


!        3.4 Count fields

NTYPXFU=IP
NFDXFU=IADD-1
LXFU=LXFU.AND.(NFDXFU > 0)

!      -----------------------------------------------------------

!*       4.    PRINT FINAL VALUES.
!              -------------------

WRITE(UNIT=KULOUT,FMT='('' COMMON YOMXFU '')')
WRITE(UNIT=KULOUT,FMT='('' LXFU = '',L2,'' LREAXFU = '',L2)') LXFU, LREAXFU
WRITE(UNIT=KULOUT,FMT='('' NFDXFU = '',I6,'' NTYPXFU = '',I6)') NFDXFU, NTYPXFU
WRITE(UNIT=KULOUT,FMT='('' NFRXFU = '',I7)') NFRXFU
WRITE(KULOUT,*) ' NXFUTS =  ',NXFUTS(0),(NXFUTS(J),J=1,ABS(NXFUTS(0)))
WRITE(UNIT=KULOUT,FMT='('' NFRRAZ = '',I6,'' N1RAZ = '',I6)') NFRRAZ, N1RAZ
WRITE(KULOUT,*) ' NRAZTS =  ',NRAZTS(0),(NRAZTS(J),J=1,ABS(NRAZTS(0)))
IF (LXFU) THEN
  WRITE(UNIT=KULOUT,FMT='('' LXTRD  = '',L2,'' LXTRC  = '',L2&
   & ,'' LXTRT  = '',L2,'' LXPLC  = '',L2,'' LXPLSG = '',L2&
   & ,'' LXTRCH = '',L2,'' LXPLS  = '',L2,'' LXPLSG = '',L2&
   & ,'' LXPLSH = '',L2,'' LXR    = '',L2,'' LXSOIL = '',L2&
   & ,'' LXNEBTT= '',L2,'' LXNEBPA= '',L2,'' LXICV  = '',L2&
   & ,'' LXCLS  = '',L2,'' LXCLP  = '',L2, '' LXVEIN = '',L2&
   & ,'' LXTGST = '',L2,'' LXTTCLS= '',L2,'' LXHHCLS= '',L2&
   & ,'' LXQCLS = '',L2,'' LXTHW  = '',L2,'' LXXGST = '',L2&
   & ,'' LXXGST2= '',L2,'' LXMWINDCLS = '',L2,'' LXNUVCLS  = '',L2&
   & ,'' LXXDIAGH = '',L2,'' LXMRT = '',L2,'' LXCTOP = '',L2&
   & , '' LXVISI= '',L2, '' LXVISI2= '',L2,'' LDPRECIPS = '',L2&
   & ,'' LDPRECIPS2 = '',L2,'' LXTPWCLS = '',L2)')&
   & LXTRD,LXTRC,LXTRT,LXPLC,LXPLCG,LXPLCH,LXPLS,LXPLSG,LXPLSH,LXR,LXSOIL,&
   & LXNEBTT,LXNEBPA,LXICV,LXCLS,LXCLP,LXVEIN,LXTGST,LXTTCLS,LXHHCLS,LXQCLS,&
   & LXTHW,LXXGST,LXXGST2,LXMWINDCLS,LXNUVCLS,LXXDIAGH,LXMRT,LXCTOP,LXVISI,LXVISI2,&
   & LDPRECIPS,LDPRECIPS2,LXTPWCLS
  WRITE(UNIT=KULOUT,FMT='('' LTXTRD  = '',L2,'' LTXTRC  = '',L2&
   & ,'' LTXTRT  = '',L2,'' LTXR    = '',L2,'' LTXNEB  = '',L2&
   & ,'' LTXQICE = '',L2,'' LTXQLI  = '',L2)')&
   & LTXTRD,LTXTRC,LTXTRT,LTXR,LTXNEB,LTXQICE,LTXQLI
  WRITE(UNIT=KULOUT,FMT='('' MXTRDU ='',I3,'' MXTRDV ='',I3&
   & ,'' MXTRCU ='',I3,'' MXTRCV ='',I3,'' MXDICQ ='',I3,'' MXDICS ='',I3&
   & ,'' MXTRTU ='',I3,'' MXTRTV ='',I3,'' MXDITQ ='',I3,'' MXDITS ='',I3&
   & ,'' MXPLCL ='',I3,'' MXPLSL ='',I3,'' MXPLCN ='',I3,'' MXPLSN ='',I3&
   & ,'' MXRSO  ='',I3,'' MXRTH  ='',I3,'' MXNEB  ='',I3,'' MXNEBT ='',I3&
   & ,'' MXFEVL ='',I3,'' MXFONTE='',I3,'' MXFCHSP='',I3,'' MXFEVV ='',I3&
   & ,'' MXFLWSP='',I3,'' MXFTR  ='',I3,'' MXRUISL='',I3,'' MXRUIS ='',I3&
   & ,'' MXRUISS='',I3,'' MXNBCON='',I3,'' MXNBHAU='',I3,'' MXNBMOY='',I3&
   & ,'' MXNBBAS='',I3,'' MXCAPE ='',I3&
   & ,'' MXCTOP ='',I3,'' MXMOCON='',I3,'' MXCLPH ='',I3&
   & ,'' MXVEIN ='',I3,'' MXUGST ='',I3,'' MXVGST ='',I3,'' MXUGST2='',I3&
   & ,'' MXVGST2='',I3,'' MXUCLS ='',I3,'' MXVCLS ='',I3,'' MXNUCLS='',I3&
   & ,'' MXNVCLS='',I3,'' MXTCLS ='',I3,'' MXQCLS ='',I3,'' MXRHCLS='',I3&
   & ,'' MXTN   ='',I3,'' MXTX   ='',I3,'' MXHUN  ='',I3,'' MXHUX  ='',I3&
   & ,'' MXQICE ='',I3,'' MXQLI  ='',I3,'' MXTHW  ='',I3,'' MXXDIAGH='',I3&
   & ,'' MXMRT  ='',I3&
   & ,'' MXVISICLD='',I3,'' MXVISIHYD='',I3 ,'' MXCLWC='',I3 &
   & ,'' MXPTYPE ='',I3,'' MXPTYPESEV ='',I3,'' MXVISICLD2='',I3 &
   & ,'' MXVISIHYD2='',I3 ,'' MXCLWC2='',I3,'' MXPTYPE2 ='',I3,'' MXPTYPESEV2 ='',I3,'' MXTPWCLS ='',I3 &
   & ,'' MEANPERIOD ='',I8,'' NXGSTPERIOD ='',I8,'' NXGSTPERIOD2 ='',I8&
   & ,'' NVISIPERIOD ='',I8,'' NVISIPERIOD2 ='',I8)')&
   & YDXFU%YXFUPT%MXTRDU, YDXFU%YXFUPT%MXTRDV, YDXFU%YXFUPT%MXTRCU, YDXFU%YXFUPT%MXTRCV, YDXFU%YXFUPT%MXDICQ, YDXFU%YXFUPT%MXDICS, &
   & YDXFU%YXFUPT%MXTRTU, YDXFU%YXFUPT%MXTRTV, YDXFU%YXFUPT%MXDITQ, YDXFU%YXFUPT%MXDITS, YDXFU%YXFUPT%MXPLCL, YDXFU%YXFUPT%MXPLSL, &
   & YDXFU%YXFUPT%MXPLCN, YDXFU%YXFUPT%MXPLSN, YDXFU%YXFUPT%MXRSO,  YDXFU%YXFUPT%MXRTH,  YDXFU%YXFUPT%MXNEB,  YDXFU%YXFUPT%MXNEBT, &
   & YDXFU%YXFUPT%MXFEVL, YDXFU%YXFUPT%MXFONTE,YDXFU%YXFUPT%MXFCHSP,YDXFU%YXFUPT%MXFEVV, YDXFU%YXFUPT%MXFLWSP,YDXFU%YXFUPT%MXFTR,  &
   & YDXFU%YXFUPT%MXRUISL,YDXFU%YXFUPT%MXRUISP,YDXFU%YXFUPT%MXRUISS,YDXFU%YXFUPT%MXNBCON,YDXFU%YXFUPT%MXNBHAU,YDXFU%YXFUPT%MXNBMOY,&
   & YDXFU%YXFUPT%MXNBBAS,YDXFU%YXFUPT%MXCAPE, YDXFU%YXFUPT%MXCTOP, &
   & YDXFU%YXFUPT%MXMOCON,YDXFU%YXFUPT%MXCLPH, YDXFU%YXFUPT%MXVEIN, YDXFU%YXFUPT%MXUGST, &
   & YDXFU%YXFUPT%MXVGST, YDXFU%YXFUPT%MXUGST2,YDXFU%YXFUPT%MXVGST2,YDXFU%YXFUPT%MXUCLS, YDXFU%YXFUPT%MXVCLS, YDXFU%YXFUPT%MXNUCLS,&
   & YDXFU%YXFUPT%MXNVCLS,YDXFU%YXFUPT%MXTCLS, YDXFU%YXFUPT%MXQCLS, YDXFU%YXFUPT%MXRHCLS,YDXFU%YXFUPT%MXTN,   YDXFU%YXFUPT%MXTX,   &
   & YDXFU%YXFUPT%MXHUN,  YDXFU%YXFUPT%MXHUX  ,YDXFU%YXFUPT%MXQICE, YDXFU%YXFUPT%MXQLI,  YDXFU%YXFUPT%MXTHW,  YDXFU%YXFUPT%MXXDIAGH, YDXFU%YXFUPT%MXMRT,&
   & YDXFU%YXFUPT%MXVISICLD,YDXFU%YXFUPT%MXVISIHYD,YDXFU%YXFUPT%MXCLWC,YDXFU%YXFUPT%MXPTYPE,YDXFU%YXFUPT%MXPTYPESEV,&
   & YDXFU%YXFUPT%MXVISICLD2,YDXFU%YXFUPT%MXVISIHYD2,YDXFU%YXFUPT%MXCLWC2,YDXFU%YXFUPT%MXPTYPE2,YDXFU%YXFUPT%MXPTYPESEV2,YDXFU%YXFUPT%MXTPWCLS,&
   & MEANPERIOD,NXGSTPERIOD,NXGSTPERIOD2,NVISIPERIOD,NVISIPERIOD2
  WRITE(UNIT=KULOUT,&
   & FMT='('' THE FOLLOWING INSTANTANEOUS FLUXES WILL BE HANDLED : '')')  
  DO JF=1,NTYPXFU
    DO JL=1,TYPE_XFU(JF)%ILEV
      IF (TYPE_XFU(JF)%CLPREF(JL) == CLEVS(1)) THEN
        WRITE(UNIT=KULOUT,FMT='(A1,I3.3,A12,10X, ''PARITY = '',I1)')&
         & TRIM(TYPE_XFU(JF)%CLPREF(JL)),TYPE_XFU(JF)%INUMLEV(JL),&
         & TYPE_XFU(JF)%CLSUFF,TYPE_XFU(JF)%IPARITY  
      ELSE
        WRITE(UNIT=KULOUT,FMT='(A16,10X, ''PARITY = '',I1)')&
         & TRIM(TYPE_XFU(JF)%CLPREF(JL))//TYPE_XFU(JF)%CLSUFF,&
         & TYPE_XFU(JF)%IPARITY  
      ENDIF
    ENDDO
  ENDDO
ENDIF

ALLOCATE (YDXFU%XFUBUF (YDDIM%NPROMA, NFDXFU, YDDIM%NGPBLKS))

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUXFU',1,ZHOOK_HANDLE)

!     ------------------------------------------------------------------

CONTAINS

SUBROUTINE NEXTYPE3(CDPREF,CDSUFF,KNLEV,KLEV,KPAR,KX)
                     
INTEGER(KIND=JPIM), INTENT(IN)  :: KLEV,KPAR
INTEGER(KIND=JPIM), INTENT(IN)  :: KNLEV(KLEV)
CHARACTER(LEN=*),   INTENT(IN)  :: CDPREF(KLEV)
CHARACTER(LEN=*),   INTENT(IN)  :: CDSUFF
INTEGER(KIND=JPIM), INTENT(OUT) :: KX

INTEGER(KIND=JPIM) :: J, ILEN
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SUXFU:NEXTYPE3',0,ZHOOK_HANDLE)
ASSOCIATE(TYPE_XFU=>YDXFU%TYPE_XFU)

IF (ALL((CDPREF(:) /= ' ' .AND. CDSUFF(:) /= ' '))) THEN
  IP=IP+1
  DO J=1,KLEV
    ILEN=MIN(4,LEN(CDPREF(J)))
    TYPE_XFU(IP)%CLPREF(J)=CDPREF(J)(1:ILEN)
    TYPE_XFU(IP)%INUMLEV(J)=KNLEV(J)
  ENDDO
  ILEN=MIN(16,LEN(CDSUFF))
  TYPE_XFU(IP)%CLSUFF=CDSUFF(1:ILEN)
  TYPE_XFU(IP)%ILEV=KLEV
  TYPE_XFU(IP)%IPARITY=KPAR
  KX=IADD
  IADD=IADD+KLEV
ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUXFU:NEXTYPE3',1,ZHOOK_HANDLE)

END SUBROUTINE NEXTYPE3

SUBROUTINE NEXTYPE1(CDPREF,CDSUFF,KPAR,KX)

INTEGER(KIND=JPIM), INTENT(IN)  :: KPAR
CHARACTER(LEN=*),   INTENT(IN)  :: CDPREF
CHARACTER(LEN=*),   INTENT(IN)  :: CDSUFF
INTEGER(KIND=JPIM), INTENT(OUT) :: KX

INTEGER(KIND=JPIM) :: ILEN
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SUXFU:NEXTYPE1',0,ZHOOK_HANDLE)
ASSOCIATE(TYPE_XFU=>YDXFU%TYPE_XFU, &
 & NIOLEVG=>YDGEOMETRY%YRDIMV%NIOLEVG, NFLEVG=>YDGEOMETRY%YRDIMV%NFLEVG)

IF (CDPREF /= ' ' .AND. CDSUFF /= ' ') THEN
  IP=IP+1
  ILEN=MIN(4,LEN(CDPREF))
  TYPE_XFU(IP)%CLPREF(1)=CDPREF(1:ILEN)
  TYPE_XFU(IP)%INUMLEV(1)=1+NIOLEVG-NFLEVG
  ILEN=MIN(16,LEN(CDSUFF))
  TYPE_XFU(IP)%CLSUFF=CDSUFF(1:ILEN)
  TYPE_XFU(IP)%ILEV=1
  TYPE_XFU(IP)%IPARITY=KPAR
  KX=IADD
  IADD=IADD+1
ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUXFU:NEXTYPE1',1,ZHOOK_HANDLE)

END SUBROUTINE NEXTYPE1

END SUBROUTINE SUXFU
