! (C) Copyright 2009- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Numerical Integrator (Time-Stepping) File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!     Variable naming changed to ECMWF conventions by V. Huijnen
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! INTEGRATE - Integrator routine
!   Arguments :
!      TIN       - Start Time for Integration
!      TOUT      - End Time for Integration
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!
!  Rosenbrock - Implementation of several Rosenbrock methods:             !
!               * Ros2                                                    !
!               * Ros3                                                    !
!               * Ros4                                                    !
!               * Rodas3                                                  !
!               * Rodas4                                                  !
!  By default the code employs the KPP sparse linear algebra routines     !
!  Compile with -DFULL_ALGEBRA to use full linear algebra (LAPACK)        !
!                                                                         !
!    (C)  Adrian Sandu, August 2004                                       !
!    Virginia Polytechnic Institute and State University                  !
!    Contact: sandu@cs.vt.edu                                             !
!    Revised by Philipp Miehe and Adrian Sandu, May 2006                  !                               !
!    This implementation is part of KPP - the Kinetic PreProcessor        !
!                                                                         !
!    Coding standards have been adapted to make this tuned for C-IFS      !
!    Applications (V. Huijnen, KNMI)                                      !
!                                                                         !
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!

SUBROUTINE BASCOE_KPP_INTEGRATOR( PTIN, PTOUT, &
   & KCNTRL_U, PRCNTRL_U, KSTATUS_U, PRSTATUS_U, KERR_U, PVAR, PFIX, PRCONST, PCFACTOR )

   USE PARKIND1  ,ONLY : JPIM, JPRB, JPRD
   USE YOMHOOK   ,ONLY : LHOOK, DR_HOOK, JPHOOK
   USE BASCOE_KPP_Parameters, ONLY: NVAR, NFIX, NHEXIT, NREACT
   USE BASCOE_KPP_Global,     ONLY: RTOL, ATOL,STEPMIN

   IMPLICIT NONE

   REAL(KIND=JPRD), INTENT(IN) :: PTIN  ! Start Time
   REAL(KIND=JPRB), INTENT(IN) :: PTOUT ! End Time
   ! Optional input parameters and statistics
   INTEGER(KIND=JPIM),    INTENT(IN),  OPTIONAL :: KCNTRL_U(20)
   REAL(KIND=JPRD), INTENT(IN),  OPTIONAL :: PRCNTRL_U(20)
   INTEGER(KIND=JPIM),       INTENT(OUT), OPTIONAL :: KSTATUS_U(20)
   REAL(KIND=JPRD), INTENT(OUT), OPTIONAL :: PRSTATUS_U(20)
   INTEGER(KIND=JPIM), INTENT(OUT), OPTIONAL :: KERR_U

   REAL(KIND=JPRD),       INTENT(INOUT) :: PVAR(NVAR),PFIX(NFIX)
   REAL(KIND=JPRD),       INTENT(IN)    :: PRCONST(NREACT)
   REAL(KIND=JPRD),       INTENT(IN)    :: PCFACTOR

   REAL(KIND=JPRD) :: ZTOUT
   REAL(KIND=JPRD) :: ZRCNTRL(20), ZRSTATUS(20)
   INTEGER(KIND=JPIM)     :: ICNTRL(20), ISTATUS(20), IERR

   ! INTEGER(KIND=JPIM), SAVE :: Ntotal = 0

   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

#include "bascoe_kpp_rosenbrock.intfb.h"

!    --------------------------------------------------------
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('BASCOE_KPP_INTEGRATOR',0,ZHOOK_HANDLE)
#endif

   ICNTRL(:)   = 0
   ZRCNTRL(:)  = 0.0_JPRD
   ISTATUS(:)  = 0
   ZRSTATUS(:) = 0.0_JPRD
   ZTOUT=PTOUT ! Convert to DP

    !~~~> fine-tune the integrator:
   ICNTRL(1) = 0        ! 0 - non-autonomous, 1 - autonomous
   ICNTRL(2) = 0        ! 0 - vector tolerances, 1 - scalars

   ! If optional parameters are given, and if they are >0, 
   ! then they overwrite default settings. 
   IF (PRESENT(KCNTRL_U)) THEN
     WHERE(KCNTRL_U(:) > 0) ICNTRL(:) = KCNTRL_U(:)
   ENDIF
   IF (PRESENT(PRCNTRL_U)) THEN
     WHERE(PRCNTRL_U(:) > 0) ZRCNTRL(:) = PRCNTRL_U(:)
   ENDIF

   CALL BASCOE_KPP_ROSENBROCK(PVAR,PFIX, PRCONST, PTIN,ZTOUT,   &
      &   ATOL,RTOL, PCFACTOR, &
      &   ZRCNTRL,ICNTRL,ZRSTATUS,ISTATUS,IERR)

   !~~~> Debug option: show no of steps
   ! Ntotal = Ntotal + KSTATUS(Nstp)
   ! PRINT*,'NSTEPS=',KSTATUS(Nstp),' (',Ntotal,')','  O3=', VAR(ind_O3)

   STEPMIN = ZRSTATUS(Nhexit)
   ! if optional parameters are given for output they 
   ! are updated with the return information
   IF (PRESENT(KSTATUS_U)) KSTATUS_U(:) = ISTATUS(:)
   IF (PRESENT(PRSTATUS_U)) PRSTATUS_U(:) = ZRSTATUS(:)
   IF (PRESENT(KERR_U))    KERR_U       = IERR

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('BASCOE_KPP_INTEGRATOR',1,ZHOOK_HANDLE)
#endif

END SUBROUTINE BASCOE_KPP_INTEGRATOR

