! (C) Copyright 2009- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


SUBROUTINE BASCOE_V0_KPP_UPDATE_CIFS_CONC(YGFL,PVAR,PCVM)

   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  , ONLY : JPIM     ,JPRB, JPRD
   USE BASCOE_KPP_PARAMETERS, ONLY:  NVAR,&
&   IND_CO2,   IND_HF,    IND_N2O,   IND_CCL4,&
&   IND_CFC11, IND_CFC12, IND_CFC113,IND_CFC114,&
&   IND_CFC115,IND_HA1301,IND_N,     IND_HA1211,&
&   IND_CH3CCL3,IND_CHBR3,IND_CH3,   IND_CH3O,&
&   IND_CLNO2, IND_HCFC22,IND_CL2O2, IND_HCO,&
&   IND_CH3CL, IND_CH3BR, IND_BRCL,  IND_BRONO2,&
&   IND_BR2,   IND_HO2NO2,IND_N2O5,  IND_CH3OOH,&
&   IND_CLOO,  IND_CO,    IND_H2O2,  IND_CH4,&
&   IND_CH3O2, IND_HNO3,  IND_CL2,   IND_H2,&
&   IND_H2O,   IND_CLONO2,IND_HOBR,  IND_OCLO,&
&   IND_CH2O,  IND_H,     IND_HBR,   IND_HOCL,&
&   IND_HCL,   IND_NO,    IND_CLO,   IND_NO2,&
&   IND_O,     IND_BRO,   IND_O3,    IND_BR,&
&   IND_OH,    IND_NO3,   IND_CL,    IND_HO2,&
&   IND_O1D,   IND_CH2BR2,IND_OCS,   IND_SO2,&
&   IND_SO3,   IND_H2SO4     

   
   USE YOM_YGFL , ONLY : TYPE_GFLD
   USE BASCOE_MODULE, ONLY :   IO3,  IH2O2,&
& ICH4,    ICO,     IHNO3,   ICH3OOH,&
& ICH2O,   INO ,    IHO2 ,   ICH3 ,&
& ICH3O ,  IHCO ,   ICH3O2 , IOH ,&
& INO2 ,   IN2O5 ,  IHO2NO2 ,INO3 ,&
& IN2O ,   IH2O ,   IOCLO ,  IHCL ,&
& ICLONO2 ,IHOCL ,  ICL2 ,   IHBR ,&
& IBRONO2, ICL2O2,  IHOBR,   IBRCL ,&
& ICFC11 , ICFC12 , ICFC113 ,ICFC114 ,&
& ICFC115 ,ICCL4 ,  ICLNO2 , ICH3CCL3,&
& ICH3CL , IHCFC22 ,ICH3BR , IHF ,&
& IHA1301 ,IHA1211 ,ICHBR3 , ICLOO ,&
& IO ,     IO1D ,   IN ,     ICLO ,&
& ICL ,    IBR ,    IBRO ,   IH ,&
& IH2 ,    ICO2 ,   IBR2 ,   ICH2BR2,&
& IOCS,    ISO2,    ISO3,    IH2SO4


   IMPLICIT NONE

TYPE(TYPE_GFLD)   ,INTENT(INOUT)  :: YGFL
   REAL(KIND=JPRD),INTENT(IN)     :: PVAR(NVAR)
   REAL(KIND=JPRB),INTENT(OUT)    :: PCVM(YGFL%NCHEM)

!*       0.5   LOCAL PVARIABLES
!              ---------------

REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('BASCOE_V0_KPP_UPDATE_CIFS_CONC',0,ZHOOK_HANDLE )

   PCVM(ICO2 )     = PVAR(IND_CO2)
   PCVM(IHF )      = PVAR(IND_HF)
   PCVM(IN2O )     = PVAR(IND_N2O)
   PCVM(ICCL4 )    = PVAR(IND_CCL4)
   PCVM(ICFC11 )   = PVAR(IND_CFC11)
   PCVM(ICFC12 )   = PVAR(IND_CFC12)
   PCVM(ICFC113 )  = PVAR(IND_CFC113)
   PCVM(ICFC114 )  = PVAR(IND_CFC114)
   PCVM(ICFC115 )  = PVAR(IND_CFC115)
   PCVM(IHA1301 )  = PVAR(IND_HA1301)
   PCVM(IN )       = PVAR(IND_N)
   PCVM(IHA1211 )  = PVAR(IND_HA1211)
   PCVM(ICH3CCL3)  = PVAR(IND_CH3CCL3)
   PCVM(ICHBR3 )   = PVAR(IND_CHBR3)
   PCVM(ICH3 )     = PVAR(IND_CH3)
   PCVM(ICH3O )    = PVAR(IND_CH3O)
   PCVM(ICLNO2 )   = PVAR(IND_CLNO2)
   PCVM(IHCFC22 )  = PVAR(IND_HCFC22)
   PCVM(ICL2O2 )   = PVAR(IND_CL2O2)
   PCVM(IHCO )     = PVAR(IND_HCO)
   PCVM(ICH3CL )   = PVAR(IND_CH3CL)
   PCVM(ICH3BR )   = PVAR(IND_CH3BR)
   PCVM(IBRCL )    = PVAR(IND_BRCL)
   PCVM(IBRONO2 )  = PVAR(IND_BRONO2)
   PCVM(IBR2 )     = PVAR(IND_BR2)
   PCVM(IHO2NO2 )  = PVAR(IND_HO2NO2)
   PCVM(IN2O5 )    = PVAR(IND_N2O5)
   PCVM(ICH3OOH )  = PVAR(IND_CH3OOH)
   PCVM(ICLOO )    = PVAR(IND_CLOO)
   PCVM(ICO )      = PVAR(IND_CO)
   PCVM(IH2O2 )    = PVAR(IND_H2O2)
   PCVM(ICH4 )     = PVAR(IND_CH4)
   PCVM(ICH3O2 )   = PVAR(IND_CH3O2)
   PCVM(IHNO3 )    = PVAR(IND_HNO3)
   PCVM(ICL2 )     = PVAR(IND_CL2)
   PCVM(IH2 )      = PVAR(IND_H2)
   PCVM(IH2O )     = PVAR(IND_H2O)
   PCVM(ICLONO2 )  = PVAR(IND_CLONO2)
   PCVM(IHOBR )    = PVAR(IND_HOBR)
   PCVM(IOCLO )    = PVAR(IND_OCLO)
   PCVM(ICH2O )    = PVAR(IND_CH2O)
   PCVM(IH )       = PVAR(IND_H)
   PCVM(IHBR )     = PVAR(IND_HBR)
   PCVM(IHOCL )    = PVAR(IND_HOCL)
   PCVM(IHCL )     = PVAR(IND_HCL)
   PCVM(INO )      = PVAR(IND_NO)
   PCVM(ICLO )     = PVAR(IND_CLO)
   PCVM(INO2 )     = PVAR(IND_NO2)
   PCVM(IO )       = PVAR(IND_O)
   PCVM(IBRO )     = PVAR(IND_BRO)
   PCVM(IO3 )      = PVAR(IND_O3)
   PCVM(IBR )      = PVAR(IND_BR)
   PCVM(IOH )      = PVAR(IND_OH)
   PCVM(INO3 )     = PVAR(IND_NO3)
   PCVM(ICL )      = PVAR(IND_CL)
   PCVM(IHO2 )     = PVAR(IND_HO2)
   PCVM(IO1D )     = PVAR(IND_O1D)
   PCVM(ICH2BR2)   = PVAR(IND_CH2BR2)
   PCVM(IOCS)      = PVAR(IND_OCS)
   PCVM(ISO2)      = PVAR(IND_SO2)
   PCVM(ISO3)      = PVAR(IND_SO3)
   PCVM(IH2SO4)    = PVAR(IND_H2SO4)
   !VH Not in BASCOE-only chemistry scheme, hence no need for update.
   !VH PCVM(IHCN)     = PVAR(IND_HCN)
   !VH PCVM(ICH3CN)   = PVAR(IND_CH3CN)

 
IF (LHOOK) CALL DR_HOOK('BASCOE_V0_KPP_UPDATE_CIFS_CONC',1,ZHOOK_HANDLE )
    
END SUBROUTINE BASCOE_V0_KPP_UPDATE_CIFS_CONC
