! (C) Copyright 2009- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! BASCOE_KPP_FUN - time derivatives of variables - Agregate form
!   Arguments :
!      PV        - Concentrations of variable species (local)
!      PF        - Concentrations of fixed species (local)
!      PRCT      - Rate constants (local)
!      PVdot     - Time derivative of variable species concentrations
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE BASCOE_KPP_FUN ( PV, PF, PRCT, PVdot )

  USE PARKIND1, ONLY : JPIM, JPRB, JPRD
  USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK

  USE BASCOE_KPP_PARAMETERS,  ONLY : NVAR, NREACT, NFIX

  IMPLICIT NONE

! PV - Concentrations of variable species (local)
  REAL(KIND=JPRD), INTENT(IN) :: PV(NVAR)
! PF - Concentrations of fixed species (local)
  REAL(KIND=JPRD), INTENT(IN) :: PF(NFIX)
! PRCT - Rate constants (local)
  REAL(KIND=JPRD), INTENT(IN) :: PRCT(NREACT)
! PVdot - Time derivative of variable species concentrations
  REAL(KIND=JPRD), INTENT(OUT) :: PVdot(NVAR)


! Local variables
! ZA - Rate for each equation
  REAL(KIND=JPRD)    :: ZA(NREACT)
#ifdef WITH_COMPO_DR_HOOK
  REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE 

  IF (LHOOK) CALL DR_HOOK('BASCOE_KPP_FUN',0,ZHOOK_HANDLE) 
#endif

! Computation of equation rates
  ZA(1) = PRCT(1)*PV(56)*PF(1)
  ZA(2) = PRCT(2)*PV(56)*PV(64)
  ZA(3) = PRCT(3)*PV(60)*PF(2)
  ZA(4) = PRCT(4)*PV(60)*PF(2)
  ZA(5) = PRCT(5)*PV(60)*PF(1)
  ZA(6) = PRCT(6)*PV(60)*PV(64)
  ZA(7) = PRCT(7)*PV(60)*PV(64)
  ZA(8) = PRCT(8)*PV(50)*PV(60)
  ZA(9) = PRCT(9)*PV(42)*PV(60)
  ZA(10) = PRCT(10)*PV(38)*PV(60)
  ZA(11) = PRCT(11)*PV(38)*PV(60)
  ZA(12) = PRCT(12)*PV(38)*PV(60)
  ZA(13) = PRCT(13)*PV(2)*PV(60)
  ZA(14) = PRCT(14)*PV(2)*PV(60)
  ZA(15) = PRCT(15)*PV(56)*PV(56)
  ZA(16) = PRCT(16)*PV(47)*PF(1)
  ZA(17) = PRCT(17)*PV(47)*PV(64)
  ZA(18) = PRCT(18)*PV(42)*PV(58)
  ZA(19) = PRCT(19)*PV(58)*PV(64)
  ZA(20) = PRCT(20)*PV(56)*PV(58)
  ZA(21) = PRCT(21)*PV(58)*PV(58)
  ZA(22) = PRCT(22)*PV(58)*PV(58)
  ZA(23) = PRCT(23)*PV(56)*PV(63)
  ZA(24) = PRCT(24)*PV(63)*PV(64)
  ZA(25) = PRCT(25)*PV(47)*PV(63)
  ZA(26) = PRCT(26)*PV(47)*PV(63)
  ZA(27) = PRCT(27)*PV(47)*PV(63)
  ZA(28) = PRCT(28)*PV(58)*PV(63)
  ZA(29) = PRCT(29)*PV(63)*PV(63)
  ZA(30) = PRCT(30)*PV(36)*PV(58)
  ZA(31) = PRCT(31)*PV(36)*PV(56)
  ZA(32) = PRCT(32)*PV(42)*PV(56)
  ZA(33) = PRCT(33)*PV(52)*PV(64)
  ZA(34) = PRCT(34)*PV(52)*PV(63)
  ZA(35) = PRCT(35)*PV(56)*PV(61)
  ZA(36) = PRCT(36)*PV(56)*PV(61)
  ZA(37) = PRCT(37)*PV(61)*PV(64)
  ZA(38) = PRCT(38)*PV(58)*PV(61)
  ZA(39) = PRCT(39)*PV(61)*PV(63)
  ZA(40) = PRCT(40)*PV(56)*PV(57)
  ZA(41) = PRCT(41)*PV(52)*PV(57)
  ZA(42) = PRCT(42)*PV(57)*PV(61)
  ZA(43) = PRCT(43)*PV(30)
  ZA(44) = PRCT(44)*PV(41)*PV(58)
  ZA(45) = PRCT(45)*PV(29)*PV(58)
  ZA(46) = PRCT(46)*PV(29)
  ZA(47) = PRCT(47)*PV(57)*PV(58)
  ZA(48) = PRCT(48)*PV(57)*PV(63)
  ZA(49) = PRCT(49)*PV(57)*PV(63)
  ZA(50) = PRCT(50)*PV(10)*PV(52)
  ZA(51) = PRCT(51)*PV(10)*PF(1)
  ZA(52) = PRCT(52)*PV(52)*PV(56)
  ZA(53) = PRCT(53)*PV(54)*PF(1)
  ZA(54) = PRCT(54)*PV(54)*PV(64)
  ZA(55) = PRCT(55)*PV(42)*PV(54)
  ZA(56) = PRCT(56)*PV(38)*PV(54)
  ZA(57) = PRCT(57)*PV(49)*PV(54)
  ZA(58) = PRCT(58)*PV(54)*PV(63)
  ZA(59) = PRCT(59)*PV(54)*PV(63)
  ZA(60) = PRCT(60)*PV(36)*PV(54)
  ZA(61) = PRCT(61)*PV(51)*PV(54)
  ZA(62) = PRCT(62)*PV(51)*PV(54)
  ZA(63) = PRCT(63)*PV(46)*PV(54)
  ZA(64) = PRCT(64)*PV(40)*PV(54)
  ZA(65) = PRCT(65)*PV(40)*PV(54)
  ZA(66) = PRCT(66)*PV(56)*PV(62)
  ZA(67) = PRCT(67)*PV(58)*PV(62)
  ZA(68) = PRCT(68)*PV(58)*PV(62)
  ZA(69) = PRCT(69)*PV(62)*PV(63)
  ZA(70) = PRCT(70)*PV(52)*PV(62)
  ZA(71) = PRCT(71)*PV(61)*PV(62)
  ZA(72) = PRCT(72)*PV(62)*PV(62)
  ZA(73) = PRCT(73)*PV(62)*PV(62)
  ZA(74) = PRCT(74)*PV(62)*PV(62)
  ZA(75) = PRCT(75)*PV(62)*PV(62)
  ZA(76) = PRCT(76)*PV(40)
  ZA(77) = PRCT(77)*PV(57)*PV(62)
  ZA(78) = PRCT(78)*PV(37)
  ZA(79) = PRCT(79)*PV(55)*PV(58)
  ZA(80) = PRCT(80)*PV(55)*PV(56)
  ZA(81) = PRCT(81)*PV(46)*PV(56)
  ZA(82) = PRCT(82)*PV(46)*PV(58)
  ZA(83) = PRCT(83)*PV(46)*PV(52)
  ZA(84) = PRCT(84)*PV(51)*PV(56)
  ZA(85) = PRCT(85)*PV(51)*PV(58)
  ZA(86) = PRCT(86)*PV(43)*PV(58)
  ZA(87) = PRCT(87)*PV(45)*PV(56)
  ZA(88) = PRCT(88)*PV(45)*PV(58)
  ZA(89) = PRCT(89)*PV(45)*PV(54)
  ZA(90) = PRCT(90)*PV(54)*PV(61)
  ZA(91) = PRCT(91)*PV(54)*PV(57)
  ZA(92) = PRCT(92)*PV(43)*PV(60)
  ZA(93) = PRCT(93)*PV(55)*PV(60)
  ZA(94) = PRCT(94)*PV(37)*PV(54)
  ZA(95) = PRCT(95)*PV(37)*PV(58)
  ZA(96) = PRCT(96)*PV(53)*PV(64)
  ZA(97) = PRCT(97)*PV(53)*PV(63)
  ZA(98) = PRCT(98)*PV(49)*PV(53)
  ZA(99) = PRCT(99)*PV(46)*PV(53)
  ZA(100) = PRCT(100)*PV(56)*PV(59)
  ZA(101) = PRCT(101)*PV(59)*PV(63)
  ZA(102) = PRCT(102)*PV(52)*PV(59)
  ZA(103) = PRCT(103)*PV(59)*PV(61)
  ZA(104) = PRCT(104)*PV(59)*PV(62)
  ZA(105) = PRCT(105)*PV(59)*PV(62)
  ZA(106) = PRCT(106)*PV(59)*PV(62)
  ZA(107) = PRCT(107)*PV(59)*PV(59)
  ZA(108) = PRCT(108)*PV(59)*PV(59)
  ZA(109) = PRCT(109)*PV(48)*PV(58)
  ZA(110) = PRCT(110)*PV(48)*PV(56)
  ZA(111) = PRCT(111)*PV(44)*PV(56)
  ZA(112) = PRCT(112)*PV(27)*PV(58)
  ZA(113) = PRCT(113)*PV(58)*PV(59)
  ZA(114) = PRCT(114)*PV(48)*PV(60)
  ZA(115) = PRCT(115)*PV(34)*PV(56)
  ZA(116) = PRCT(116)*PV(37)*PV(53)
  ZA(117) = PRCT(117)*PV(35)*PV(58)
  ZA(118) = PRCT(118)*PV(38)*PV(58)
  ZA(119) = PRCT(119)*PV(49)*PV(58)
  ZA(120) = PRCT(120)*PV(49)*PV(56)
  ZA(121) = PRCT(121)*PV(23)*PF(1)
  ZA(122) = PRCT(122)*PV(18)*PF(1)
  ZA(123) = PRCT(123)*PV(22)*PF(1)
  ZA(124) = PRCT(124)*PV(39)*PV(52)
  ZA(125) = PRCT(125)*PV(39)*PV(63)
  ZA(126) = PRCT(126)*PV(31)*PV(58)
  ZA(127) = PRCT(127)*PV(31)*PV(58)
  ZA(128) = PRCT(128)*PV(49)*PV(57)
  ZA(129) = PRCT(129)*PV(35)*PV(56)
  ZA(130) = PRCT(130)*PV(3)*PV(60)
  ZA(131) = PRCT(131)*PV(4)*PV(60)
  ZA(132) = PRCT(132)*PV(5)*PV(60)
  ZA(133) = PRCT(133)*PV(6)*PV(60)
  ZA(134) = PRCT(134)*PV(7)*PV(60)
  ZA(135) = PRCT(135)*PV(8)*PV(60)
  ZA(136) = PRCT(136)*PV(21)*PV(60)
  ZA(137) = PRCT(137)*PV(21)*PV(58)
  ZA(138) = PRCT(138)*PV(13)*PV(60)
  ZA(139) = PRCT(139)*PV(9)*PV(60)
  ZA(140) = PRCT(140)*PV(24)*PV(58)
  ZA(141) = PRCT(141)*PV(24)*PV(54)
  ZA(142) = PRCT(142)*PV(14)*PV(58)
  ZA(143) = PRCT(143)*PV(25)*PV(60)
  ZA(144) = PRCT(144)*PV(25)*PV(58)
  ZA(145) = PRCT(145)*PV(15)*PV(58)
  ZA(146) = PRCT(146)*PV(16)*PV(58)
  ZA(147) = PRCT(147)*PV(26)*PV(56)
  ZA(148) = PRCT(148)*PV(26)*PV(58)
  ZA(149) = PRCT(149)*PV(33)*PV(58)
  ZA(150) = PRCT(150)*PV(33)*PV(64)
  ZA(151) = PRCT(151)*PV(28)*PV(50)
  ZA(152) = PRCT(152)*PV(11)*PV(58)
  ZA(153) = PRCT(153)*PV(12)*PV(58)
  ZA(154) = PRCT(154)*PV(11)
  ZA(155) = PRCT(155)*PV(12)
  ZA(156) = PRCT(156)*PV(45)
  ZA(157) = PRCT(157)*PV(45)*PV(55)
  ZA(158) = PRCT(158)*PV(30)
  ZA(159) = PRCT(159)*PV(30)*PV(55)
  ZA(160) = PRCT(160)*PV(51)*PV(55)
  ZA(161) = PRCT(161)*PV(34)
  ZA(162) = PRCT(162)*PV(44)*PV(55)
  ZA(163) = PRCT(163)*PV(44)*PV(48)
  ZA(164) = PRCT(164)*PV(48)*PV(51)
  ZA(165) = PRCT(165)*PF(1)
  ZA(166) = PRCT(166)*PV(64)
  ZA(167) = PRCT(167)*PV(64)
  ZA(168) = PRCT(168)*PV(63)
  ZA(169) = PRCT(169)*PV(36)
  ZA(170) = PRCT(170)*PV(61)
  ZA(171) = PRCT(171)*PV(57)
  ZA(172) = PRCT(172)*PV(57)
  ZA(173) = PRCT(173)*PV(30)
  ZA(174) = PRCT(174)*PV(41)
  ZA(175) = PRCT(175)*PV(29)
  ZA(176) = PRCT(176)*PV(43)
  ZA(177) = PRCT(177)*PV(27)
  ZA(178) = PRCT(178)*PV(46)
  ZA(179) = PRCT(179)*PV(37)
  ZA(180) = PRCT(180)*PV(51)
  ZA(181) = PRCT(181)*PV(45)
  ZA(182) = PRCT(182)*PV(32)
  ZA(183) = PRCT(183)*PV(34)
  ZA(184) = PRCT(184)*PV(49)
  ZA(185) = PRCT(185)*PV(49)
  ZA(186) = PRCT(186)*PV(31)
  ZA(187) = PRCT(187)*PV(29)
  ZA(188) = PRCT(188)*PV(45)
  ZA(189) = PRCT(189)*PV(59)
  ZA(190) = PRCT(190)*PV(3)
  ZA(191) = PRCT(191)*PV(4)
  ZA(192) = PRCT(192)*PV(6)
  ZA(193) = PRCT(193)*PV(7)
  ZA(194) = PRCT(194)*PV(8)
  ZA(195) = PRCT(195)*PV(5)
  ZA(196) = PRCT(196)*PV(25)
  ZA(197) = PRCT(197)*PV(14)
  ZA(198) = PRCT(198)*PV(24)
  ZA(199) = PRCT(199)*PV(38)
  ZA(200) = PRCT(200)*PV(15)
  ZA(201) = PRCT(201)*PV(20)
  ZA(202) = PRCT(202)*PV(40)
  ZA(203) = PRCT(203)*PV(62)
  ZA(204) = PRCT(204)*PV(50)
  ZA(205) = PRCT(205)*PV(13)
  ZA(206) = PRCT(206)*PV(9)
  ZA(207) = PRCT(207)*PV(21)
  ZA(208) = PRCT(208)*PV(55)
  ZA(209) = PRCT(209)*PV(44)
  ZA(210) = PRCT(210)*PV(2)
  ZA(211) = PRCT(211)*PV(52)
  ZA(212) = PRCT(212)*PF(1)
  ZA(213) = PRCT(213)*PV(34)
  ZA(214) = PRCT(214)*PV(19)
  ZA(215) = PRCT(215)*PV(16)
  ZA(216) = PRCT(216)*PV(36)
  ZA(217) = PRCT(217)*PV(26)
  ZA(218) = PRCT(218)*PV(17)
  ZA(219) = PRCT(219)*PV(28)

! Aggregate function
  PVdot(1) = ZA(131)+2*ZA(132)+3*ZA(133)+4*ZA(134)+5*ZA(135)+2*ZA(136)+2*ZA(138)+3*ZA(139)+ZA(191)+3*ZA(192)+4*ZA(193)+5&
               &*ZA(194)+2*ZA(195)+2*ZA(205)+3*ZA(206)+2*ZA(207)
  PVdot(2) = ZA(4)-ZA(13)-ZA(14)-ZA(210)
  PVdot(3) = -ZA(130)-ZA(190)
  PVdot(4) = -ZA(131)-ZA(191)
  PVdot(5) = -ZA(132)-ZA(195)
  PVdot(6) = -ZA(133)-ZA(192)
  PVdot(7) = -ZA(134)-ZA(193)
  PVdot(8) = -ZA(135)-ZA(194)
  PVdot(9) = -ZA(139)-ZA(206)
  PVdot(10) = -ZA(50)-ZA(51)+ZA(211)
  PVdot(11) = -ZA(152)-ZA(154)
  PVdot(12) = -ZA(153)-ZA(155)
  PVdot(13) = -ZA(138)-ZA(205)
  PVdot(14) = -ZA(142)-ZA(197)
  PVdot(15) = -ZA(145)-ZA(200)
  PVdot(16) = -ZA(146)-ZA(215)
  PVdot(17) = ZA(151)-ZA(218)
  PVdot(18) = ZA(12)+ZA(56)+ZA(118)-ZA(122)+ZA(196)+ZA(198)+ZA(199)
  PVdot(19) = ZA(117)+ZA(129)+ZA(148)+ZA(152)+ZA(153)+ZA(154)+ZA(155)-ZA(214)
  PVdot(20) = ZA(90)+ZA(159)-ZA(201)
  PVdot(21) = -ZA(136)-ZA(137)-ZA(207)
  PVdot(22) = ZA(10)-ZA(123)+ZA(124)+ZA(186)
  PVdot(23) = ZA(57)+ZA(98)+ZA(119)+ZA(120)-ZA(121)+ZA(184)
  PVdot(24) = -ZA(140)-ZA(141)-ZA(198)
  PVdot(25) = -ZA(143)-ZA(144)-ZA(196)
  PVdot(26) = -ZA(147)-ZA(148)-ZA(217)
  PVdot(27) = ZA(108)-ZA(112)+ZA(163)-ZA(177)
  PVdot(28) = ZA(149)+ZA(150)-ZA(151)+ZA(218)-ZA(219)
  PVdot(29) = ZA(39)-ZA(45)-ZA(46)-ZA(175)-ZA(187)
  PVdot(30) = ZA(42)-ZA(43)-ZA(158)-ZA(159)-ZA(173)
  PVdot(31) = ZA(125)-ZA(126)-ZA(127)-ZA(186)
  PVdot(32) = ZA(106)+ZA(116)+ZA(162)+ZA(164)-ZA(182)
  PVdot(33) = ZA(147)+ZA(148)-ZA(149)-ZA(150)+ZA(217)+ZA(219)
  PVdot(34) = ZA(103)-ZA(115)-ZA(161)-ZA(183)-ZA(213)
  PVdot(35) = -ZA(117)+ZA(121)+ZA(128)-ZA(129)+ZA(147)+ZA(185)+ZA(214)+ZA(217)
  PVdot(36) = ZA(22)+ZA(29)-ZA(30)-ZA(31)-ZA(60)-ZA(169)-ZA(216)
  PVdot(37) = ZA(75)-ZA(78)-ZA(94)-ZA(95)-ZA(116)-ZA(179)
  PVdot(38) = -ZA(10)-ZA(11)-ZA(12)-ZA(56)-ZA(118)-ZA(199)
  PVdot(39) = ZA(122)-ZA(124)-ZA(125)+ZA(126)
  PVdot(40) = ZA(53)-ZA(64)-ZA(65)+ZA(73)-ZA(76)+ZA(77)+ZA(87)+ZA(95)+ZA(105)+ZA(116)+ZA(179)-ZA(202)
  PVdot(41) = ZA(38)-ZA(44)+ZA(49)+ZA(128)+ZA(156)+ZA(157)+2*ZA(158)+ZA(159)+ZA(161)-ZA(174)
  PVdot(42) = -ZA(9)+ZA(11)-ZA(18)+ZA(27)-ZA(32)-ZA(55)+ZA(185)
  PVdot(43) = ZA(61)+ZA(64)+ZA(74)-ZA(86)+ZA(89)-ZA(92)+ZA(94)+ZA(157)+ZA(160)-ZA(176)
  PVdot(44) = ZA(101)-ZA(111)+ZA(112)+ZA(161)-ZA(162)-ZA(163)-ZA(209)
  PVdot(45) = ZA(71)-ZA(87)-ZA(88)-ZA(89)-ZA(156)-ZA(157)-ZA(181)-ZA(188)
  PVdot(46) = -ZA(63)+ZA(72)-ZA(81)-ZA(82)-ZA(83)-ZA(99)+ZA(104)-ZA(178)
  PVdot(47) = ZA(9)+ZA(10)-ZA(16)-ZA(17)+ZA(18)+ZA(20)-ZA(25)-ZA(26)-ZA(27)+ZA(32)+ZA(55)+ZA(184)+ZA(199)+ZA(204)&
                &+ZA(208)+ZA(216)
  PVdot(48) = ZA(97)+ZA(98)-ZA(109)-ZA(110)-ZA(114)-ZA(163)-ZA(164)
  PVdot(49) = ZA(11)-ZA(57)-ZA(98)-ZA(119)-ZA(120)+ZA(123)+ZA(127)-ZA(128)-ZA(184)-ZA(185)
  PVdot(50) = -ZA(8)+ZA(18)+ZA(21)+ZA(26)+ZA(28)+ZA(30)+ZA(44)+ZA(45)+ZA(79)+ZA(85)+ZA(109)+ZA(118)+ZA(119)+ZA(126)&
                &+ZA(127)+ZA(137)+ZA(142)+ZA(144)+ZA(145)+ZA(146)-ZA(151)+ZA(160)+ZA(162)+ZA(163)+ZA(164)-ZA(204)+ZA(218)
  PVdot(51) = -ZA(61)-ZA(62)+ZA(69)+ZA(82)-ZA(84)-ZA(85)+ZA(86)+ZA(88)+ZA(95)+ZA(156)-ZA(160)-ZA(164)-ZA(180)
  PVdot(52) = 2*ZA(14)-ZA(33)-ZA(34)+ZA(35)-ZA(41)-ZA(50)+ZA(51)-ZA(52)-ZA(70)-ZA(83)-ZA(102)-ZA(124)+ZA(170)+ZA(172)&
                &-ZA(211)
  PVdot(53) = -ZA(96)-ZA(97)-ZA(98)-ZA(99)+ZA(100)+ZA(102)+ZA(104)+ZA(105)+2*ZA(107)+ZA(109)+ZA(110)+ZA(112)+ZA(113)&
                &+ZA(114)-ZA(116)+ZA(138)+ZA(139)+ZA(143)+ZA(144)+3*ZA(145)+2*ZA(146)+2*ZA(177)+ZA(182)+ZA(183)+ZA(189)&
                &+ZA(196)+3*ZA(200)+ZA(205)+ZA(206)+ZA(209)+2*ZA(215)
  PVdot(54) = -ZA(53)-ZA(54)-ZA(55)-ZA(56)-ZA(57)-ZA(58)-ZA(59)-ZA(60)-ZA(61)-ZA(62)-ZA(63)-ZA(64)-ZA(65)+ZA(66)+ZA(67)&
                &+ZA(70)+ZA(72)+ZA(73)+ZA(76)+ZA(79)+ZA(80)+ZA(86)-ZA(89)-ZA(90)-ZA(91)+ZA(92)+ZA(93)+4*ZA(130)+3*ZA(131)+2&
                &*ZA(132)+3*ZA(133)+2*ZA(134)+ZA(135)+ZA(136)+ZA(137)+ZA(138)+ZA(140)-ZA(141)+3*ZA(142)+2*ZA(176)+ZA(179)&
                &+ZA(180)+ZA(181)+ZA(182)+4*ZA(190)+3*ZA(191)+3*ZA(192)+2*ZA(193)+ZA(194)+2*ZA(195)+3*ZA(197)+ZA(198)&
                &+ZA(201)+ZA(203)+ZA(205)+ZA(207)+ZA(208)
  PVdot(55) = ZA(55)+ZA(56)+ZA(57)+ZA(58)+ZA(60)+ZA(62)+ZA(68)-ZA(79)-ZA(80)-ZA(93)+2*ZA(141)-ZA(157)-ZA(159)-ZA(160)&
                &-ZA(162)-ZA(208)
  PVdot(56) = -ZA(1)-ZA(2)+ZA(3)+ZA(5)+2*ZA(7)-2*ZA(15)-ZA(20)+ZA(21)-ZA(23)+ZA(26)-ZA(31)-ZA(32)-ZA(35)-ZA(36)-ZA(40)&
                &+ZA(50)+ZA(51)-ZA(52)-ZA(66)-ZA(80)-ZA(81)-ZA(84)-ZA(87)-ZA(100)-ZA(110)-ZA(111)-ZA(115)-ZA(120)-ZA(129)&
                &-ZA(147)+2*ZA(165)+ZA(166)+ZA(168)+ZA(170)+ZA(171)+ZA(178)+ZA(189)+ZA(202)+ZA(203)+ZA(211)+ZA(212)+ZA(219)
  PVdot(57) = ZA(36)+ZA(37)-ZA(40)-ZA(41)-ZA(42)+ZA(43)+ZA(44)-ZA(47)-ZA(48)-ZA(49)-ZA(77)+ZA(88)+ZA(89)-ZA(91)+ZA(115)&
                &-ZA(128)-ZA(171)-ZA(172)+ZA(173)+ZA(181)+ZA(183)+ZA(187)
  PVdot(58) = 2*ZA(8)+ZA(9)+ZA(12)+ZA(17)-ZA(18)-ZA(19)-ZA(20)-2*ZA(21)-2*ZA(22)+ZA(23)+ZA(24)+2*ZA(25)-ZA(28)-ZA(30)&
                &+ZA(31)+ZA(32)+ZA(34)-ZA(38)-ZA(44)-ZA(45)-ZA(47)+ZA(48)+ZA(59)+ZA(61)-ZA(67)-ZA(68)-ZA(79)+ZA(80)-ZA(82)&
                &+ZA(84)-ZA(85)-ZA(86)-ZA(88)+ZA(93)-ZA(95)-ZA(109)+ZA(110)+ZA(111)-ZA(112)-ZA(113)+ZA(114)-ZA(117)-ZA(118)&
                &-ZA(119)+ZA(120)-ZA(126)-ZA(137)-ZA(140)-ZA(142)-ZA(144)-ZA(145)-ZA(146)-ZA(148)-ZA(149)-ZA(152)-ZA(153)&
                &+ZA(168)+2*ZA(169)+ZA(174)+ZA(180)+ZA(186)+ZA(187)+ZA(204)+ZA(209)
  PVdot(59) = ZA(96)+ZA(99)-ZA(100)-ZA(101)-ZA(102)-ZA(103)-ZA(104)-ZA(105)-ZA(106)-2*ZA(107)-2*ZA(108)+ZA(111)-ZA(113)&
                &+ZA(115)-ZA(189)+ZA(213)
  PVdot(60) = -ZA(3)-ZA(4)-ZA(5)-ZA(6)-ZA(7)-ZA(8)-ZA(9)-ZA(10)-ZA(11)-ZA(12)-ZA(13)-ZA(14)-ZA(92)-ZA(93)-ZA(114)&
                &-ZA(130)-ZA(131)-ZA(132)-ZA(133)-ZA(134)-ZA(135)-ZA(136)-ZA(138)-ZA(139)-ZA(143)+ZA(167)+ZA(210)+ZA(212)&
                &+ZA(214)
  PVdot(61) = ZA(33)+ZA(34)-ZA(35)-ZA(36)-ZA(37)-ZA(38)-ZA(39)+ZA(40)+2*ZA(41)-ZA(42)+ZA(43)+ZA(45)+ZA(46)+ZA(47)+ZA(48)&
                &+ZA(52)+ZA(70)-ZA(71)+ZA(77)+ZA(83)+ZA(87)-ZA(90)+ZA(91)+ZA(102)-ZA(103)+ZA(124)-ZA(170)+ZA(171)+ZA(173)&
                &+ZA(174)+ZA(175)+ZA(188)+ZA(201)+ZA(213)
  PVdot(62) = ZA(54)+ZA(59)+ZA(62)+2*ZA(63)+2*ZA(65)-ZA(66)-ZA(67)-ZA(68)-ZA(69)-ZA(70)-ZA(71)-2*ZA(72)-2*ZA(73)-2&
                &*ZA(74)-2*ZA(75)-ZA(77)+2*ZA(78)+ZA(81)+ZA(83)+ZA(84)+ZA(85)+ZA(91)+ZA(92)+ZA(99)-ZA(104)-ZA(105)-ZA(106)&
                &+ZA(178)+ZA(188)+ZA(202)-ZA(203)
  PVdot(63) = ZA(16)+ZA(19)-ZA(23)-ZA(24)-ZA(25)-ZA(26)-ZA(27)-ZA(28)-2*ZA(29)+ZA(30)+ZA(31)-ZA(34)-ZA(39)+ZA(46)+ZA(47)&
                &-ZA(48)-ZA(49)-ZA(58)-ZA(59)+ZA(60)+ZA(67)-ZA(69)-ZA(97)-ZA(101)+ZA(113)+ZA(117)+ZA(121)+ZA(123)-ZA(125)&
                &+ZA(128)+ZA(140)+ZA(149)-ZA(168)+ZA(175)+ZA(216)
  PVdot(64) = ZA(1)-ZA(2)-ZA(6)-ZA(7)-ZA(17)-ZA(19)-ZA(24)-ZA(33)-ZA(37)-ZA(54)-ZA(96)-ZA(150)-ZA(166)-ZA(167)


#ifdef WITH_COMPO_DR_HOOK
  IF (LHOOK) CALL DR_HOOK('BASCOE_KPP_FUN',1,ZHOOK_HANDLE) 
#endif
      
END SUBROUTINE BASCOE_KPP_FUN

! End of BASCOE_KPP_FUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


