! (C) Copyright 2009- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE CHEM_NEGAT &
 & ( KIDIA  , KFDIA , KLON, KLEV,&
 &   PTSPHY , &
 &   PCCHEMO , PTCHEMI, PAPHP1, &
 &   PFCHEMNG, PTCHEMO )  

!**** *CHEM_NEGAT* - AVOIDS NEGATIVE VALUES FOR Chemistry Fields CONCENTRATION.

!     JJMorcrette  ECMWF 2005/08/16
!     from QNEGAT by B.RITTER     E.C.M.W.F.     29/04/83.

!     PURPOSE.
!     --------

!          THIS ROUTINE RESETS TO A VERY SMALL MINIMUM VALUE ALL THE
!     Chemistry Fields MIXING RATIOS SMALLER THAN THIS (IN PARTICULAR ALL THE
!     NEGATIVE VALUES THAT MIGHT HAVE APPEARED IN THE COURSE OF THE
!     TIME STEP).

!**   INTERFACE.
!     ----------

!          *CHEM_NEGAT* IS CALLED FROM *CALLPAR*.
!          THE ROUTINE TAKES ITS INPUT FROM THE LONG-TERM STORAGE: PCCHEMO
!     AT T+1 AND P ON LEVEL BOUNDARIES AT T+1. IT RETURNS ITS OUTPUT
!     TO THE SAME SPACE: CORRECTED PTCHEMO TENDENCIES.
!     THE TEMPERATURE WILL NOT BE ADJUSTED AND SURFACE
!     FLUXES (OF Chemistry FieldsS) WILL NOT BE MODIFIED.

!     METHOD.
!     -------

!          FOR EACH LAYER (FROM TOP TO BOTTOM) THE Chemistry Fields CONCENTRATION 
!     IS COMPARED WITH ITS CRITICAL VALUE. IF NECESSARY THE ADJUSTMENT IS
!     PERFORMED AND THE NECESSARY WATER IS TAKEN FROM THE LAYER UNDERNEATH.

!     EXTERNALS.
!     ----------

!          NONE.

!     REFERENCE.
!     ----------

!          SEE RELEVANT PART OF THE DOCUMENTATION.

!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB, JPRD
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMCST   , ONLY : RG
USE YOMLUN   , ONLY : NULOUT
USE YOMCHEM  , ONLY : REPSCHEM

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)  :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)  :: KLEV 
INTEGER(KIND=JPIM),INTENT(IN)  :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)  :: KFDIA 

REAL(KIND=JPRB)   ,INTENT(IN)  :: PTSPHY 
REAL(KIND=JPRB)   ,INTENT(IN)  :: PCCHEMO(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)  :: PTCHEMI(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)  :: PAPHP1(KLON,0:KLEV) 

REAL(KIND=JPRB)   ,INTENT(OUT) :: PTCHEMO(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT) :: PFCHEMNG(KLON,0:KLEV) 

!*         flux outputs

! PFCHEMNG  : PSEUDO-FLUX OF Chemistry FieldsS TO CORRECT FOR NEGATIVE Chemistry Fields CONCENTRATION


!REAL(KIND=JPRB) :: ZDP(KLON), ZDPO(KLON)
REAL(KIND=JPRB) ::  ZREPSCCHEM


INTEGER(KIND=JPIM) :: JK, JL

REAL(KIND=JPRB) :: ZGDPH
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-------------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('CHEM_NEGAT',0,ZHOOK_HANDLE)

DO JK=1,KLEV
  DO JL=KIDIA,KFDIA
     !! Following PD in naj_CY47R1_SP_test
     IF(JPRB==JPRD)THEN
       ZREPSCCHEM=MAX(ABS(PCCHEMO(JL,JK)) * 1.0E-10_JPRB, REPSCHEM)
     ELSE
       ZREPSCCHEM = MAX(ABS(PCCHEMO(JL,JK)) * 5E-7_JPRB, REPSCHEM)
     ENDIF
     IF ((PCCHEMO(JL,JK) +PTSPHY*PTCHEMI(JL,JK)) < ZREPSCCHEM ) THEN
      PTCHEMO(JL,JK)= (ZREPSCCHEM-PCCHEMO(JL,JK) )/PTSPHY
     ELSE
       PTCHEMO(JL,JK) = PTCHEMI (JL,JK)   
     ENDIF
  IF ( PTCHEMO(JL,JK) * PTSPHY + PCCHEMO(JL,JK) < 0.0_JPRB ) THEN
    WRITE (NULOUT,*) ' NEGFIX FAILED 00'
    WRITE (NULOUT,*) JL, JK
    WRITE (NULOUT,*) PTCHEMI(JL,JK),  PTCHEMI(JL,JK) * PTSPHY, PCCHEMO(JL,JK) , PTCHEMI(JL,JK) * PTSPHY + PCCHEMO(JL,JK)  
  ENDIF 

  ENDDO
ENDDO


!*         3.       FLUX COMPUTATIONS

DO JL=KIDIA,KFDIA
  PFCHEMNG(JL,0)=0.0_JPRB
ENDDO
DO JK=1,KLEV
  DO JL=KIDIA,KFDIA
    ZGDPH = -RG  /(PAPHP1(JL,JK)-PAPHP1(JL,JK-1))
    PFCHEMNG(JL,JK)=(PTCHEMO(JL,JK)-PTCHEMI(JL,JK))/ZGDPH + PFCHEMNG(JL,JK-1)
  ENDDO
ENDDO

!-------------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('CHEM_NEGAT',1,ZHOOK_HANDLE)
END SUBROUTINE CHEM_NEGAT
