! (C) Copyright 2009- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Numerical Integrator (Time-Stepping) File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!     Variable naming changed to ECMWF conventions by V. Huijnen
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! INTEGRATE - Integrator routine
!   Arguments :
!      TIN       - Start Time for Integration
!      TOUT      - End Time for Integration
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!
!  Rosenbrock - Implementation of several Rosenbrock methods:             !
!               * Ros2                                                    !
!               * Ros3                                                    !
!               * Ros4                                                    !
!               * Rodas3                                                  !
!               * Rodas4                                                  !
!  By default the code employs the KPP sparse linear algebra routines     !
!  Compile with -DFULL_ALGEBRA to use full linear algebra (LAPACK)        !
!                                                                         !
!    (C)  Adrian Sandu, August 2004                                       !
!    Virginia Polytechnic Institute and State University                  !
!    Contact: sandu@cs.vt.edu                                             !
!    Revised by Philipp Miehe and Adrian Sandu, May 2006                  !                               !
!    This implementation is part of KPP - the Kinetic PreProcessor        !
!                                                                         !
!    Coding standards have been adapted to make this tuned for C-IFS      !
!    Applications (V. Huijnen, KNMI)                                      !
!                                                                         !
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~!

SUBROUTINE TM5_KPP_INTEGRATOR( PTIN, PTOUT, &
   & KCNTRL_U, PRCNTRL_U, KSTATUS_U, PRSTATUS_U, KERR_U, PVAR, PRCONST, PCFACTOR )

   USE PARKIND1  ,ONLY : JPIM, JPRB, JPRD
   USE YOMHOOK   ,ONLY : LHOOK, DR_HOOK, JPHOOK
   USE TM5_KPP_Parameters, ONLY: NVAR, NREACT, NHEXIT
   USE TM5_KPP_Global,     ONLY: RTOL, ATOL,STEPMIN

   IMPLICIT NONE

   REAL(KIND=JPRD), INTENT(IN) :: PTIN  ! Start Time
   REAL(KIND=JPRB), INTENT(IN) :: PTOUT ! End Time
   ! Optional input parameters and statistics
   INTEGER(KIND=JPIM),    INTENT(IN),  OPTIONAL :: KCNTRL_U(20)
   REAL(KIND=JPRD), INTENT(IN),  OPTIONAL :: PRCNTRL_U(20)
   INTEGER(KIND=JPIM),       INTENT(OUT), OPTIONAL :: KSTATUS_U(20)
   REAL(KIND=JPRD), INTENT(OUT), OPTIONAL :: PRSTATUS_U(20)
   INTEGER(KIND=JPIM), INTENT(OUT), OPTIONAL :: KERR_U

   REAL(KIND=JPRD),       INTENT(INOUT) :: PVAR(NVAR)
   REAL(KIND=JPRD),       INTENT(IN)    :: PRCONST(NREACT)
   REAL(KIND=JPRB),       INTENT(IN)    :: PCFACTOR

   REAL(KIND=JPRD) :: ZTOUT
   REAL(KIND=JPRD) :: ZRCNTRL(20), ZRSTATUS(20)
   INTEGER(KIND=JPIM)     :: ICNTRL(20), ISTATUS(20), IERR

   ! INTEGER(KIND=JPIM), SAVE :: Ntotal = 0

#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_INTEGRATOR',0,ZHOOK_HANDLE)
#endif

   ICNTRL(:)   = 0
   ZRCNTRL(:)  = 0.0_JPRD
   ISTATUS(:)  = 0
   ZRSTATUS(:) = 0.0_JPRD
   ZTOUT=PTOUT ! Convert to DP

    !~~~> fine-tune the integrator:
   ICNTRL(1) = 0        ! 0 - non-autonomous, 1 - autonomous
   ICNTRL(2) = 0        ! 0 - vector tolerances, 1 - scalars

   ! If optional parameters are given, and if they are >0, 
   ! then they overwrite default settings. 
   IF (PRESENT(KCNTRL_U)) THEN
     WHERE(KCNTRL_U(:) > 0) ICNTRL(:) = KCNTRL_U(:)
   ENDIF
   IF (PRESENT(PRCNTRL_U)) THEN
     WHERE(PRCNTRL_U(:) > 0) ZRCNTRL(:) = PRCNTRL_U(:)
   ENDIF

   CALL TM5_KPP_ROSENBROCK(PVAR,PRCONST, PTIN,ZTOUT,   &
      &   ATOL,RTOL, PCFACTOR, &
      &   ZRCNTRL,ICNTRL,ZRSTATUS,ISTATUS,IERR)

   !~~~> Debug option: show no of steps
   ! Ntotal = Ntotal + KSTATUS(Nstp)
   ! PRINT*,'NSTEPS=',KSTATUS(Nstp),' (',Ntotal,')','  O3=', VAR(ind_O3)

   STEPMIN = ZRSTATUS(Nhexit)
   ! if optional parameters are given for output they 
   ! are updated with the return information
   IF (PRESENT(KSTATUS_U)) KSTATUS_U(:) = ISTATUS(:)
   IF (PRESENT(PRSTATUS_U)) PRSTATUS_U(:) = ZRSTATUS(:)
   IF (PRESENT(KERR_U))    KERR_U       = IERR

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_INTEGRATOR',1,ZHOOK_HANDLE)
#endif

END SUBROUTINE TM5_KPP_INTEGRATOR

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE TM5_KPP_ROSENBROCK(PY,PRCONST, PTSTART,PTEND, &
      &     PABSTOL,PRELTOL, PCFACTOR,                        &
      &     PRCNTRL,KCNTRL,PRSTATUS,KSTATUS,KERR)
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!    Solves the system y'=F(t,y) using a Rosenbrock method defined by:
!
!     G = 1/(H*gamma(1)) - Jac(t0,Y0)
!     T_i = t0 + Alpha(i)*H
!     Y_i = Y0 + \sum_{j=1}^{i-1} A(i,j)*K_j
!     G * K_i = Fun( T_i, Y_i ) + \sum_{j=1}^S C(i,j)/H * K_j +
!         gamma(i)*dF/dT(t0, Y0)
!     Y1 = Y0 + \sum_{j=1}^S M(j)*K_j
!
!    For details on Rosenbrock methods and their implementation consult:
!      E. Hairer and G. Wanner
!      "Solving ODEs II. Stiff and differential-algebraic problems".
!      Springer series in computational mathematics, Springer-Verlag, 1996.
!    The codes contained in the book inspired this implementation.
!
!    (C)  Adrian Sandu, August 2004
!    Virginia Polytechnic Institute and State University
!    Contact: sandu@cs.vt.edu
!    Revised by Philipp Miehe and Adrian Sandu, May 2006                  
!    This implementation is part of KPP - the Kinetic PreProcessor
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!~~~>   INPUT ARGUMENTS:
!
!-     PY(N)    = vector of initial conditions (at T=Tstart)
!-    [Tstart,Tend]  = time range of integration
!     (if Tstart>Tend the integration is performed backwards in time)
!-    PRELTOL, PABSTOL = user precribed accuracy
!- SUBROUTINE  Fun( T, Y, Ydot ) = ODE function,
!                       returns Ydot = Y' = F(T,Y)
!- SUBROUTINE  Jac( T, Y, Jcb ) = Jacobian of the ODE function,
!                       returns Jcb = dFun/dY
!-    KCNTRL(1:20)    = integer inputs parameters
!-    PRCNTRL(1:20)    = real inputs parameters
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!~~~>     OUTPUT ARGUMENTS:
!
!-    Y(N)    -> vector of final states (at T->Tend)
!-    KSTATUS(1:20)   -> integer output parameters
!-    RSTATUS(1:20)   -> real output parameters
!-    KERR            -> job status upon return
!                        success (positive value) or
!                        failure (negative value)
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!~~~>     INPUT PARAMETERS:
!
!    Note: For input parameters equal to zero the default values of the
!       corresponding variables are used.
!
!    KCNTRL(1) = 1: F = F(y)   Independent of T (AUTONOMOUS)
!              = 0: F = F(t,y) Depends on T (NON-AUTONOMOUS)
!
!    KCNTRL(2) = 0: PABSTOL, PRELTOL are N-dimensional vectors
!              = 1: PABSTOL, PRELTOL are scalars
!
!    KCNTRL(3)  -> selection of a particular Rosenbrock method
!        = 0 :    Rodas3 (default)
!        = 1 :    Ros2
!        = 2 :    Ros3
!        = 3 :    Ros4
!        = 4 :    Rodas3
!        = 5 :    Rodas4
!
!    KCNTRL(4)  -> maximum number of integration steps
!        For KCNTRL(4)=0) the default value of 100000 is used
!
!    PRCNTRL(1)  -> Hmin, lower bound for the integration step size
!          It is strongly recommended to keep Hmin = ZERO
!    PRCNTRL(2)  -> Hmax, upper bound for the integration step size
!    PRCNTRL(3)  -> Hstart, starting value for the integration step size
!
!    PRCNTRL(4)  -> FacMin, lower bound on step decrease factor (default=0.2)
!    PRCNTRL(5)  -> FacMax, upper bound on step increase factor (default=6)
!    PRCNTRL(6)  -> FacRej, step decrease factor after multiple rejections
!                          (default=0.1)
!    PRCNTRL(7)  -> FacSafe, by which the new step is slightly smaller
!         than the predicted value  (default=0.9)
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
!
!    OUTPUT ARGUMENTS:
!    -----------------
!
!    T           -> T value for which the solution has been computed
!                     (after successful return T=Tend).
!
!    PY(N)       -> Numerical solution at T
!
!    IDID        -> Reports on successfulness upon return:
!                    = 1 for success
!                    < 0 for error (value equals error code)
!
!    KSTATUS(1)  -> No. of function calls
!    KSTATUS(2)  -> No. of jacobian calls
!    KSTATUS(3)  -> No. of steps
!    KSTATUS(4)  -> No. of accepted steps
!    KSTATUS(5)  -> No. of rejected steps (except at very beginning)
!    KSTATUS(6)  -> No. of LU decompositions
!    KSTATUS(7)  -> No. of forward/backward substitutions
!    KSTATUS(8)  -> No. of singular matrix decompositions
!
!    RSTATUS(1)  -> Texit, the time corresponding to the
!                     computed Y upon return
!    RSTATUS(2)  -> Hexit, last accepted step before exit
!    RSTATUS(3)  -> Hnew, last predicted step (not yet taken)
!                   For multiple restarts, use Hnew as Hstart 
!                     in the subsequent run
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  USE TM5_KPP_Parameters, only:NREACT,NVAR 
  USE TM5_KPP_Global, only : ROUNDOFF_STORE
  ! USE TM5_KPP_LinearAlgebra
  USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
  USE YOMLUN,     ONLY : NULERR
  USE PARKIND1  , ONLY : JPIM   ,JPRB  ,JPRD
  IMPLICIT NONE

!~~~>  Arguments
   REAL(KIND=JPRD), INTENT(INOUT) :: PY(NVAR)
   REAL(KIND=JPRD), INTENT(IN)    :: PRCONST(NREACT)
   REAL(KIND=JPRD), INTENT(IN)    :: PTSTART,PTEND
   REAL(KIND=JPRD), INTENT(IN)    :: PABSTOL(NVAR),PRELTOL(NVAR)
   INTEGER(KIND=JPIM),       INTENT(IN)    :: KCNTRL(20)
   REAL(KIND=JPRD), INTENT(IN)    :: PRCNTRL(20)
   INTEGER(KIND=JPIM),       INTENT(INOUT) :: KSTATUS(20)
   REAL(KIND=JPRB), INTENT(IN)    :: PCFACTOR
   REAL(KIND=JPRD), INTENT(INOUT) :: PRSTATUS(20)
   INTEGER(KIND=JPIM), INTENT(OUT)   :: KERR
!~~~>  Parameters of the Rosenbrock method, up to 6 stages
   INTEGER(KIND=JPIM) ::  IROS_S, IrosMethod
   INTEGER(KIND=JPIM), PARAMETER :: IRS2=1, IRS3=2, IRS4=3, IRD3=4, IRD4=5
   REAL(KIND=JPRD) :: Z_ROS_A(15), Z_ROS_C(15), Z_ROS_M(6), Z_ROS_E(6), &
&                    Z_ROS_ALPHA(6), Z_ROS_GAMMA(6), Z_ROS_ELO
   LOGICAL :: LL_ROS_NEWF(6)
   CHARACTER(LEN=12) :: CL_ROS_NAME
!~~~>  Local variables
   REAL(KIND=JPRD) :: ZRoundoff, ZFacMin, ZFacMax, ZFacRej, ZFacSafe
   REAL(KIND=JPRD) :: ZHmin, ZHmax, ZHstart
   REAL(KIND=JPRD) :: ZTexit
   INTEGER(KIND=JPIM)       :: i, IUplimTol, KMax_no_steps
   LOGICAL       :: LD_Autonomous, LD_VectorTol
!~~~>   Parameters
   REAL(KIND=JPRD), PARAMETER :: ZERO = 0.0_JPRD
   REAL(KIND=JPRD), PARAMETER :: ZDeltaMin = 1.0E-5_JPRD
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif


#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',0,ZHOOK_HANDLE) 
#endif

!~~~>  Initialize statistics
   KSTATUS(1:8) = 0
   PRSTATUS(1:3) = ZERO

!~~~>  Autonomous or time dependent ODE. Default is time dependent.
   LD_Autonomous = .NOT.(KCNTRL(1) == 0)

!~~~>  For Scalar tolerances (KCNTRL(2).NE.0)  the code uses PABSTOL(1) and PRELTOL(1)
!   For Vector tolerances (KCNTRL(2) == 0) the code uses PABSTOL(1:NVAR) and PRELTOL(1:NVAR)
   IF (KCNTRL(2) == 0) THEN
      LD_VectorTol = .TRUE.
      IUplimTol  = NVAR
   ELSE
      LD_VectorTol = .FALSE.
      IUplimTol  = 1
   ENDIF

!~~~>   Initialize the particular Rosenbrock method selected
   SELECT CASE (KCNTRL(3))
     CASE (1)
       CALL Ros2
     CASE (2)
       CALL Ros3
     CASE (3)
       CALL Ros4
     CASE (0,4)
       CALL Rodas3
     CASE (5)
       CALL Rodas4
     CASE DEFAULT
       WRITE(NULERR,*) 'Unknown Rosenbrock method: KCNTRL(3)=',KCNTRL(3) 
       CALL ROS_ERRORMSG(-2,PTSTART,ZERO,KERR)
#ifdef WITH_COMPO_DR_HOOK
       IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',1,ZHOOK_HANDLE) 
#endif
       RETURN
   END SELECT

!~~~>   The maximum number of steps admitted
   IF (KCNTRL(4) == 0) THEN
      KMax_no_steps = 200000
   ELSEIF (KCNTRL(4) > 0) THEN
      KMax_no_steps=KCNTRL(4)
   ELSE
      WRITE(NULERR,*)'User-selected max no. of steps: KCNTRL(4)=',KCNTRL(4)
      CALL ROS_ERRORMSG(-1,PTSTART,ZERO,KERR)
#ifdef WITH_COMPO_DR_HOOK
      IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',1,ZHOOK_HANDLE) 
#endif
      RETURN
   ENDIF

!~~~>  Unit roundoff (1+Roundoff>1)
!VH There is an issue when runnng KPP in parallel with 'FIRST'
!VH   Roundoff = WLAMCH('E')
!VH Instead use 'stored' roundoff value, which is computed elsewhere.
    ZRoundoff = Roundoff_STORE

!~~~>  Lower bound on the step size: (positive value)
   IF (PRCNTRL(1) == ZERO) THEN
      ZHmin = ZERO
   ELSEIF (PRCNTRL(1) > ZERO) THEN
      ZHmin = PRCNTRL(1)
   ELSE
      WRITE(NULERR,*) 'User-selected Hmin: PRCNTRL(1)=', PRCNTRL(1)
      CALL ROS_ERRORMSG(-3,PTSTART,ZERO,KERR)
#ifdef WITH_COMPO_DR_HOOK
      IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',1,ZHOOK_HANDLE) 
#endif
      RETURN
   ENDIF
!~~~>  Upper bound on the step size: (positive value)
   IF (PRCNTRL(2) == ZERO) THEN
      ZHmax = ABS(PTEND-PTSTART)
   ELSEIF (PRCNTRL(2) > ZERO) THEN
      ZHmax = MIN(ABS(PRCNTRL(2)),ABS(PTEND-PTSTART))
   ELSE
      WRITE(NULERR,*) 'User-selected Hmax: PRCNTRL(2)=', PRCNTRL(2)
      CALL ROS_ERRORMSG(-3,PTSTART,ZERO,KERR)
#ifdef WITH_COMPO_DR_HOOK
      IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',1,ZHOOK_HANDLE) 
#endif
      RETURN
   ENDIF
!~~~>  Starting step size: (positive value)
   IF (PRCNTRL(3) == ZERO) THEN
      ZHstart = MAX(ZHmin,ZDeltaMin)
   ELSEIF (PRCNTRL(3) > ZERO) THEN
      ZHstart = MIN(ABS(PRCNTRL(3)),ABS(PTEND-PTSTART))
   ELSE
      WRITE(NULERR,*) 'User-selected Hstart: PRCNTRL(3)=', PRCNTRL(3)
      CALL ROS_ERRORMSG(-3,PTSTART,ZERO,KERR)
#ifdef WITH_COMPO_DR_HOOK
      IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',1,ZHOOK_HANDLE) 
#endif
      RETURN
   ENDIF
!~~~>  Step size can be changed s.t.  FacMin < Hnew/Hold < FacMax
   IF (PRCNTRL(4) == ZERO) THEN
      ZFacMin = 0.2_JPRD
   ELSEIF (PRCNTRL(4) > ZERO) THEN
      ZFacMin = PRCNTRL(4)
   ELSE
      WRITE(NULERR,*) 'User-selected FacMin: PRCNTRL(4)=', PRCNTRL(4)
      CALL ROS_ERRORMSG(-4,PTSTART,ZERO,KERR)
#ifdef WITH_COMPO_DR_HOOK
      IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',1,ZHOOK_HANDLE) 
#endif
      RETURN
   ENDIF
   IF (PRCNTRL(5) == ZERO) THEN
      ZFacMax = 6.0_JPRD
   ELSEIF (PRCNTRL(5) > ZERO) THEN
      ZFacMax = PRCNTRL(5)
   ELSE
      WRITE(NULERR,*) 'User-selected FacMax: PRCNTRL(5)=', PRCNTRL(5)
      CALL ROS_ERRORMSG(-4,PTSTART,ZERO,KERR)
#ifdef WITH_COMPO_DR_HOOK
      IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',1,ZHOOK_HANDLE) 
#endif
      RETURN
   ENDIF
!~~~>   FacRej: Factor to decrease step after 2 succesive rejections
   IF (PRCNTRL(6) == ZERO) THEN
      ZFacRej = 0.1_JPRD
   ELSEIF (PRCNTRL(6) > ZERO) THEN
      ZFacRej = PRCNTRL(6)
   ELSE
      WRITE(NULERR,*) 'User-selected FacRej: PRCNTRL(6)=', PRCNTRL(6)
      CALL ROS_ERRORMSG(-4,PTstart,ZERO,KERR)
#ifdef WITH_COMPO_DR_HOOK
      IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',1,ZHOOK_HANDLE) 
#endif
      RETURN
   ENDIF
!~~~>   FacSafe: Safety Factor in the computation of new step size
   IF (PRCNTRL(7) == ZERO) THEN
      ZFacSafe = 0.9_JPRD
   ELSEIF (PRCNTRL(7) > ZERO) THEN
      ZFacSafe = PRCNTRL(7)
   ELSE
      WRITE(NULERR,*) 'User-selected FacSafe: PRCNTRL(7)=', PRCNTRL(7)
      CALL ROS_ERRORMSG(-4,PTSTART,ZERO,KERR)
#ifdef WITH_COMPO_DR_HOOK
      IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',1,ZHOOK_HANDLE) 
#endif
      RETURN
   ENDIF
!~~~>  Check if tolerances are reasonable
    DO i=1,IUplimTol
      IF ( (PABSTOL(i) <= ZERO) .OR. (PRELTOL(i) <= 10.0_JPRD*ZRoundoff) &
&         .OR. (PRELTOL(i) >= 1.0_JPRD) ) THEN
        WRITE(NULERR,*) ' AbsTol(',i,') = ',PABSTOL(i)
        WRITE(NULERR,*) ' RelTol(',i,') = ',PRELTOL(i)
        CALL ROS_ERRORMSG(-5,PTstart,ZERO,KERR)
#ifdef WITH_COMPO_DR_HOOK
        IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',1,ZHOOK_HANDLE) 
#endif
       RETURN
      ENDIF
    ENDDO


!~~~>  CALL Rosenbrock method
   CALL TM5_KPP_ROS_INTEGRATOR(PY, PRCONST, PCFACTOR, PTSTART, PTEND, ZTEXIT,   &
    &    PABSTOL, PRELTOL,                        &
!  Integration parameters
    &    LD_Autonomous, LD_VectorTol, KMax_no_steps,     &
    &    ZRoundoff, ZHmin, ZHmax, ZHstart,        &
    &    ZFacMin, ZFacMax, ZFacRej, ZFacSafe,     &
!  Error indicator
    &    KERR)

#ifdef WITH_COMPO_DR_HOOK
IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK',1,ZHOOK_HANDLE) 
#endif

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CONTAINS !  SUBROUTINES internal to Rosenbrock
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   
 SUBROUTINE ROS_ERRORMSG (K_Code,PT,PH,KERR)
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   
!    Handles all error messages
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~   
  
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  ,ONLY : JPIM, JPRB,   JPRD
   USE YOMLUN    ,ONLY : NULERR
   
   REAL(KIND=JPRD), INTENT(IN) :: PT, PH
   INTEGER(KIND=JPIM), INTENT(IN)  :: K_Code
   INTEGER(KIND=JPIM), INTENT(OUT) :: KERR
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:ROS_ERRORMSG',0,ZHOOK_HANDLE) 
#endif
   KERR = K_Code
   WRITE(NULERR,*)'Forced exit from Rosenbrock due to the following error:' 
     
   SELECT CASE (K_Code)
    CASE (-1)    
      WRITE(NULERR, *) '--> Improper value for maximal no of steps'
    CASE (-2)    
      WRITE(NULERR, *) '--> Selected Rosenbrock method not implemented'
    CASE (-3)    
      WRITE(NULERR, *) '--> Hmin/Hmax/Hstart must be positive'
    CASE (-4)    
      WRITE(NULERR, *) '--> FacMin/FacMax/FacRej must be positive'
    CASE (-5) 
      WRITE(NULERR, *) '--> Improper tolerance values'
    CASE (-6) 
      WRITE(NULERR, *) '--> No of steps exceeds maximum bound'
    CASE (-7) 
      WRITE(NULERR, *) '--> Step size too small: T + 10*H = T', &
         &   ' or H < Roundoff'
    CASE (-8)    
      WRITE(NULERR, *) '--> Matrix is repeatedly singular'
     CASE (-9)    
!      happens sometimes, should be reported by user's calling routine
!      WRITE(NULERR, *) , '       Irrealistic (out-of-range) values reached'
!      WRITE(NULERR,'(a,2(e9.1,a))')   &
!         & 'using range [',vmr_bad_small,',',vmr_bad_large,'] hardcoded in TM5_KPP_Integrator.f90'
   CASE DEFAULT
      WRITE(NULERR, *) 'Unknown Error code: ', K_Code
   END SELECT
   
   WRITE(NULERR,*) "T=", PT, "and H=", PH
     
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:ROS_ERRORMSG',1,ZHOOK_HANDLE) 
#endif
 END SUBROUTINE ROS_ERRORMSG

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 SUBROUTINE TM5_KPP_ROS_INTEGRATOR (PY, PRCONST, PCFACTOR, PTSTART, PTEND, PT,  &
&        PABSTOL, PRELTOL,                        &
!~~~> Integration parameters
&        LD_Autonomous, LD_VectorTol, KMax_no_steps,     &
&        PRoundoff, PHmin, PHmax, PHstart,         &
&        PFacMin, PFacMax, PFacRej, PFacSafe,     &
!~~~> Error indicator
&        KERR )
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   Template for the implementation of a generic Rosenbrock method
!      defined by IROS_S (no of stages)
!      and its coefficients ros_{A,C,M,E,Alpha,Gamma}
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  , ONLY : JPIM  , JPRB   ,JPRD
   USE TM5_KPP_Parameters, ONLY : NREACT,NVAR,NHEXIT,LU_NONZERO, NSTP,Nfun,Njac,Nacc,&
&      Nhnew,Ntexit,Nrej  
   USE CIFS_KPP_IntParam, ONLY : VMR_BAD_LARGE

  IMPLICIT NONE

!~~~> Input: the initial condition at Tstart; Output: the solution at T
   REAL(KIND=JPRD), INTENT(INOUT) :: PY(NVAR)
!~~~> Input: reaction rates
   REAL(KIND=JPRD), INTENT(IN) ::PRCONST(NREACT)
! Density (molec/cm3)
   REAL(KIND=JPRB), INTENT(IN) :: PCFACTOR
!~~~> Input: integration interval
   REAL(KIND=JPRD), INTENT(IN) :: PTSTART,PTEND
!~~~> Output: time at which the solution is returned (T=TENDIF success)
   REAL(KIND=JPRD), INTENT(OUT) ::  PT
!~~~> Input: tolerances
   REAL(KIND=JPRD), INTENT(IN) ::  PABSTOL(NVAR), PRELTOL(NVAR)
!~~~> Input: integration parameters
   LOGICAL, INTENT(IN) :: LD_Autonomous, LD_VectorTol
   REAL(KIND=JPRD), INTENT(IN) :: PHstart, PHmin, PHmax
   INTEGER(KIND=JPIM), INTENT(IN) :: KMax_no_steps
   REAL(KIND=JPRD), INTENT(IN) :: PRoundoff, PFacMin, PFacMax, PFacRej, PFacSafe
!~~~> Output: Error indicator
   INTEGER(KIND=JPIM), INTENT(OUT) :: KERR
! ~~~~ Local variables
   REAL(KIND=JPRD) :: ZYnew(NVAR), ZFcn0(NVAR), ZFcn(NVAR)
   REAL(KIND=JPRD) :: ZK(NVAR*IROS_S), ZdFdT(NVAR)
#ifdef FULL_ALGEBRA    
   REAL(KIND=JPRD) :: ZJac0(NVAR,NVAR), ZGhimj(NVAR,NVAR)
#else
   REAL(KIND=JPRD) :: ZJac0(LU_NONZERO), ZGhimj(LU_NONZERO)
#endif
   REAL(KIND=JPRD) :: ZH, ZHnew, ZHC, ZHG, ZFac, ZTau
   REAL(KIND=JPRD) :: ZErr, ZYerr(NVAR)
   INTEGER(KIND=JPIM) :: KPIVOT(NVAR), K_Direction, ioffset, j, istage
   LOGICAL :: LL_RejectLastH, LL_RejectMoreH, LL_Singular
!~~~>  Local parameters
   REAL(KIND=JPRD), PARAMETER :: ZERO = 0.0_JPRD, Z_ONE  = 1.0_JPRD
   REAL(KIND=JPRD), PARAMETER :: ZDeltaMin = 1.0E-5_JPRD
!~~~>  Locally called functions
!    REAL(KIND=JPRD) WLAMCH
!    EXTERNAL WLAMCH
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_INTEGRATOR',0,ZHOOK_HANDLE) 
#endif

!~~~>  Initial preparations
   PT = PTSTART
   PRSTATUS(Nhexit) = ZERO
   ZH = MIN( MAX(ABS(PHmin),ABS(PHstart)) , ABS(PHmax) )
   IF (ABS(ZH) <= 10.0_JPRD*PRoundoff) ZH = ZDeltaMin

   IF (PTEND  >=  PTSTART) THEN
     K_Direction = +1
   ELSE
     K_Direction = -1
   ENDIF
   ZH = K_Direction*ZH

   LL_RejectLastH=.FALSE.
   LL_RejectMoreH=.FALSE.

!~~~> Time loop begins below

TimeLoop: DO WHILE ( (K_Direction > 0).AND.((PT-PTEND)+PRoundoff <= ZERO) &
    &   .OR. (K_Direction < 0).AND.((PTEND-PT)+PRoundoff <= ZERO) )

!   ~~~ YC20100816 : *** added a test on realistic values for number densities (Y)

    !VH - not necesary: IF( ANY (ISNAN(PY)) .OR. ANY (PY > (PCFACTOR*vmr_bad_large)) .OR. ANY (PY < PCFACTOR*vmr_bad_small) ) THEN
    IF( ANY (PY > (PCFACTOR*vmr_bad_large))  ) THEN
!        write(*,'(a,i)'), '********************* ROS_INTEGRATOR error: ISNAN(Y) or Y out-of-range at sub-step ',KSTATUS(nstp)
        CALL ROS_ERRORMSG(-9,PT,ZH,KERR)
#ifdef WITH_COMPO_DR_HOOK
        IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_INTEGRATOR',1,ZHOOK_HANDLE) 
#endif
        RETURN
    ENDIF    

!   ~~~ YC20100816

   IF ( KSTATUS(Nstp) > KMax_no_steps ) THEN  ! Too many steps
      CALL ROS_ERRORMSG(-6,PT,ZH,KERR)
#ifdef WITH_COMPO_DR_HOOK
        IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_INTEGRATOR',1,ZHOOK_HANDLE) 
#endif
      RETURN
   ENDIF
   IF ( ((PT+0.1_JPRD*ZH) == PT).OR.(ZH <= PRoundoff) ) THEN  ! Step size too small
      CALL ROS_ERRORMSG(-7,PT,ZH,KERR)
#ifdef WITH_COMPO_DR_HOOK
      IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_INTEGRATOR',1,ZHOOK_HANDLE) 
#endif
      RETURN
   ENDIF

!~~~>  Limit H if necessary to avoid going beyond PTEND
   ZH = MIN(ZH,ABS(PTEND-PT))

!~~~>   Compute the function at current time
   CALL TM5_KPP_FunTemplate(PT,PY,ZFcn0, PRCONST)
   KSTATUS(Nfun) = KSTATUS(Nfun) + 1

!~~~>  Compute the function derivative with respect to T
   IF (.NOT.LD_Autonomous) THEN
      CALL TM5_KPP_ros_FunTimeDerivative ( PT, PRoundoff, PY, &
&                ZFcn0, ZdFdT, PRCONST )
   ENDIF

!~~~>   Compute the Jacobian at current time
   CALL TM5_KPP_JacTemplate(PT,PY,ZJac0,PRCONST)
   KSTATUS(Njac) = KSTATUS(Njac) + 1

!~~~>  Repeat step calculation until current step accepted
UntilAccepted: DO

   CALL TM5_KPP_ros_PrepareMatrix(ZH,K_Direction,Z_ROS_GAMMA(1), &
    &      ZJac0,ZGhimj,KPIVOT,LL_Singular)
   IF (LL_Singular) THEN ! More than 5 consecutive failed decompositions
       CALL ROS_ERRORMSG(-8,PT,ZH,KERR)
#ifdef WITH_COMPO_DR_HOOK
       IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_INTEGRATOR',1,ZHOOK_HANDLE) 
#endif
       RETURN
   ENDIF

!~~~>   Compute the stages
Stage: DO istage = 1, IROS_S

      ! Current istage offset. Current istage vector is K(ioffset+1:ioffset+N)
       ioffset = NVAR*(istage-1)

      ! For the 1st istage the function has been computed previously
       IF ( istage == 1 ) THEN
         !slim CALL WCOPY(N,Fcn0,1,Fcn,1)
         ZFcn(1:NVAR) = ZFcn0(1:NVAR)
      ! istage>1 and a new function evaluation is needed at the current istage
       ELSEIF ( LL_ROS_NEWF(istage) ) THEN
         !slim CALL WCOPY(N,PY,1,Ynew,1)
         ZYnew(1:NVAR) = PY(1:NVAR)
         DO j = 1, istage-1
           CALL TM5_KPP_WAXPY(NVAR,Z_ROS_A((istage-1)*(istage-2)/2+j), &
&            ZK(NVAR*(j-1)+1),1,ZYnew,1)
         ENDDO
         ZTau = PT + Z_ROS_Alpha(istage)*K_Direction*ZH
         CALL TM5_KPP_FunTemplate(ZTau,ZYnew,ZFcn,PRCONST)
         KSTATUS(Nfun) = KSTATUS(Nfun) + 1
       ENDIF ! if istage == 1 elseif LL_ROS_NEWF(istage)
       !slim: CALL WCOPY(N,Fcn,1,K(ioffset+1),1)
       ZK(ioffset+1:ioffset+NVAR) = ZFcn(1:NVAR)
       DO j = 1, istage-1
         ZHC = Z_ROS_C((istage-1)*(istage-2)/2+j)/(K_Direction*ZH)
         CALL TM5_KPP_WAXPY(NVAR,ZHC,ZK(NVAR*(j-1)+1),1,ZK(ioffset+1),1)
       ENDDO
       IF ((.NOT. LD_Autonomous).AND.(Z_ROS_GAMMA(istage) /= ZERO)) THEN
         ZHG = K_Direction*ZH*Z_ROS_GAMMA(istage)
         CALL TM5_KPP_WAXPY(NVAR,ZHG,ZdFdT,1,ZK(ioffset+1),1)
       ENDIF
       CALL TM5_KPP_ROS_SOLVE(ZGhimj, KPIVOT, ZK(ioffset+1))

   ENDDO Stage


!~~~>  Compute the new solution
   !slim: CALL WCOPY(N,PY,1,Ynew,1)
   ZYnew(1:NVAR) = PY(1:NVAR)
   DO j=1,IROS_S
         CALL TM5_KPP_WAXPY(NVAR,Z_ROS_M(j),ZK(NVAR*(j-1)+1),1,ZYnew,1)
   ENDDO

!~~~>  Compute the error estimation
   !slim CALL WSCAL(NVAR,ZERO,Yerr,1)
   ZYerr(1:NVAR) = ZERO
   DO j=1,IROS_S
        CALL TM5_KPP_WAXPY(NVAR,Z_ROS_E(j),ZK(NVAR*(j-1)+1),1,ZYerr,1)
   ENDDO
   ZErr = TM5_KPP_ros_ErrorNorm ( PY, ZYnew, ZYerr, PABSTOL, PRELTOL, LD_VectorTol )

!~~~> New step size is bounded by FacMin <= Hnew/H <= FacMax
   ZFac  = MIN(PFacMax,MAX(PFacMin,PFacSafe/ZErr**(Z_ONE/Z_ROS_ELO)))
   ZHnew = ZH*ZFac

!~~~>  Check the error magnitude and adjust step size
   KSTATUS(Nstp) = KSTATUS(Nstp) + 1
   IF ( (ZErr <= Z_ONE).OR.(ZH <= PHmin) ) THEN  !~~~> Accept step
      KSTATUS(Nacc) = KSTATUS(Nacc) + 1
      ! mz_rs_20061212+
      ! old version did allow negative values here:
      !slim: CALL WCOPY(N,Ynew,1,Y,1)
      !Y(1:NVAR) = Ynew(1:NVAR)
      ! new value is positive definite:
      PY = MAX(ZYnew,ZERO)
      ! mz_rs_20061212-
      PT = PT + K_Direction*ZH
      ZHnew = MAX(ZHmin,MIN(ZHnew,ZHmax))
      IF (LL_RejectLastH) THEN  ! No step size increase after a rejected step
         ZHnew = MIN(ZHnew,ZH)
      ENDIF
      PRSTATUS(Nhexit) = ZH
      PRSTATUS(Nhnew)  = ZHnew
      PRSTATUS(Ntexit) = PT
      LL_RejectLastH = .FALSE.
      LL_RejectMoreH = .FALSE.
      ZH = ZHnew
      EXIT UntilAccepted ! EXIT THE LOOP: WHILE STEP NOT ACCEPTED
   ELSE           !~~~> Reject step
      IF (LL_RejectMoreH) THEN
         ZHnew = ZH*PFacRej
      ENDIF
      LL_RejectMoreH = LL_RejectLastH
      LL_RejectLastH = .TRUE.
      ZH = ZHnew
      IF (KSTATUS(Nacc) >= 1)  KSTATUS(Nrej) = KSTATUS(Nrej) + 1
   ENDIF ! Err <= 1

   ENDDO UntilAccepted

   ENDDO TimeLoop

!~~~> Succesful exit
   KERR = 1  !~~~> The integration was successful

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_INTEGRATOR',1,ZHOOK_HANDLE) 
#endif
  END SUBROUTINE TM5_KPP_ROS_INTEGRATOR


!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  REAL(KIND=JPRD) FUNCTION TM5_KPP_ros_ErrorNorm ( PY, PYnew, PYerr, &
&                               PABSTOL, PRELTOL, LD_VectorTol )
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~> Computes the "scaled norm" of the error vector Yerr
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  , ONLY : JPIM     ,JPRD
   USE TM5_KPP_Parameters, ONLY : NVAR
   IMPLICIT NONE

! Input arguments
   REAL(KIND=JPRD), INTENT(IN) :: PY(NVAR), PYnew(NVAR), &
&          PYerr(NVAR), PABSTOL(NVAR), PRELTOL(NVAR)
   LOGICAL, INTENT(IN) ::  LD_VectorTol
! Local variables
   REAL(KIND=JPRD) :: ZErr, ZScale, ZYmax
   INTEGER(KIND=JPIM)  :: i
   REAL(KIND=JPRD), PARAMETER :: ZERO = 0.0_JPRD
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_ERRORNORM',0,ZHOOK_HANDLE) 
#endif

   ZErr = ZERO
   DO i=1,NVAR
     ZYmax = MAX(ABS(PY(i)),ABS(PYnew(i)))
     IF (LD_VectorTol) THEN
       ZScale = PABSTOL(i)+PRELTOL(i)*ZYmax
     ELSE
       ZScale = PABSTOL(1)+PRELTOL(1)*ZYmax
     ENDIF
     ZErr = ZErr+(PYerr(i)/ZScale)**2
   ENDDO
   ZErr  = SQRT(ZErr/NVAR)

   TM5_KPP_ros_ErrorNorm = MAX(ZErr,1.0E-10_JPRD)
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_ERRORNORM',1,ZHOOK_HANDLE) 
#endif

  END FUNCTION TM5_KPP_ros_ErrorNorm


!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE TM5_KPP_ros_FunTimeDerivative ( PT, PRoundoff, PY, &
    &            PFcn0, PdFdT,PRCONST )
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!~~~> The time partial derivative of the function by finite differences
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  , ONLY : JPIM  ,JPRB   ,JPRD
   USE TM5_KPP_PARAMETERS, ONLY : NREACT,Nfun,NVAR
   IMPLICIT NONE

!~~~> Input arguments
   REAL(KIND=JPRD), INTENT(IN) :: PT, PRoundoff, PY(NVAR), PFcn0(NVAR),PRCONST(NREACT)
!~~~> Output arguments
   REAL(KIND=JPRD), INTENT(OUT) :: PdFdT(NVAR)
!~~~> Local variables
   REAL(KIND=JPRD) :: ZDelta
   REAL(KIND=JPRD), PARAMETER :: Z_ONE = 1.0_JPRD, ZDeltaMin = 1.0E-6_JPRD
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_FUNTIMEDERIVATIVE',0,ZHOOK_HANDLE) 
#endif
   ZDelta = SQRT(PRoundoff)*MAX(ZDeltaMin,ABS(PT))
   CALL TM5_KPP_FunTemplate(PT+ZDelta,PY,PdFdT,PRCONST)
   KSTATUS(Nfun) = KSTATUS(Nfun) + 1
   CALL TM5_KPP_WAXPY(NVAR,(-Z_ONE),PFcn0,1,PdFdT,1)
   CALL TM5_KPP_WSCAL(NVAR,(Z_ONE/ZDelta),PdFdT,1)
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_FUNTIMEDERIVATIVE',1,ZHOOK_HANDLE) 
#endif

  END SUBROUTINE TM5_KPP_ros_FunTimeDerivative


!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE TM5_KPP_ros_PrepareMatrix ( PH, K_Direction, Pgam, &
     &        PJac0, PGhimj, KPIVOT, LD_Singular )
! --- --- --- --- --- --- --- --- --- --- --- --- ---
!  Prepares the LHS matrix for stage calculations
!  1.  Construct Ghimj = 1/(H*ham) - Jac0
!      "(Gamma H) Inverse Minus Jacobian"
!  2.  Repeat LU decomposition of Ghimj until successful.
!       -half the step size if LU decomposition fails and retry
!       -exit after 5 consecutive fails
! --- --- --- --- --- --- --- --- --- --- --- --- ---
   USE YOMHOOK,    ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE YOMLUN,     ONLY : NULOUT
   USE PARKIND1,   ONLY : JPIM  , JPRB   ,JPRD
   USE TM5_KPP_JACOBIANSP, ONLY : LU_DIAG
   USE TM5_KPP_PARAMETERS, ONLY : LU_NONZERO,NVAR, Nsng
   IMPLICIT NONE

!~~~> Input arguments
#ifdef FULL_ALGEBRA    
   REAL(KIND=JPRD), INTENT(IN) ::  PJac0(NVAR,NVAR)
#else
   REAL(KIND=JPRD), INTENT(IN) ::  PJac0(LU_NONZERO)
#endif   
   REAL(KIND=JPRD), INTENT(IN) ::  Pgam
   INTEGER(KIND=JPIM), INTENT(IN) ::  K_Direction
!~~~> Output arguments
#ifdef FULL_ALGEBRA    
   REAL(KIND=JPRD), INTENT(OUT) :: PGhimj(NVAR,NVAR)
#else
   REAL(KIND=JPRD), INTENT(OUT) :: PGhimj(LU_NONZERO)
#endif   
   LOGICAL, INTENT(OUT) ::  LD_Singular
   INTEGER(KIND=JPIM), INTENT(OUT) ::  KPIVOT(NVAR)
!~~~> Inout arguments
   REAL(KIND=JPRD), INTENT(INOUT) :: PH   ! step size is decreased when LU fails
!~~~> Local variables
   INTEGER(KIND=JPIM)  :: i, ising, INconsecutive
   REAL(KIND=JPRD) :: Zghinv
   REAL(KIND=JPRD), PARAMETER :: Z_ONE  = 1.0_JPRD, ZHALF = 0.5_JPRD
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_PREPAREMATRIX',0,ZHOOK_HANDLE) 
#endif

   INconsecutive = 0
   LD_Singular = .TRUE.

   DO WHILE (LD_Singular)

!~~~>    Construct Ghimj = 1/(H*gam) - Jac0
#ifdef FULL_ALGEBRA    
     !slim: CALL TM5_KPP_WCOPY(NVAR*NVAR,Jac0,1,PGhimj,1)
     !slim: CALL TM5_KPP_WSCAL(NVAR*NVAR,(-Z_ONE),PGhimj,1)
     PGhimj = -PJac0
     Zghinv = Z_ONE/(K_Direction*PH*gam)
     DO i=1,N
       PGhimj(i,i) = PGhimj(i,i)+Zghinv
     ENDDO
#else
     !slim: CALL TM5_KPP_WCOPY(LU_NONZERO,PJac0,1,PGhimj,1)
     !slim: CALL TM5_KPP_WSCAL(LU_NONZERO,(-Z_ONE),PGhimj,1)
     PGhimj(1:LU_NONZERO) = -PJac0(1:LU_NONZERO)
     Zghinv = Z_ONE/(K_Direction*PH*Pgam)
     DO i=1,NVAR
       PGhimj(LU_DIAG(i)) = PGhimj(LU_DIAG(i))+Zghinv
     ENDDO
#endif   
!~~~>    Compute LU decomposition
     CALL TM5_KPP_ros_Decomp( PGhimj, KPIVOT, ising )
     IF (ising == 0) THEN
!~~~>    If successful done
        LD_Singular = .FALSE.
     ELSE ! ising .ne. 0
!~~~>    If unsuccessful half the step size; if 5 consecutive fails then return
        KSTATUS(Nsng) = KSTATUS(Nsng) + 1
        INconsecutive = INconsecutive+1
        LD_Singular = .TRUE.
        WRITE(NULOUT,*) 'TM5_KPP Warning: LU Decomposition returned ising = ',ising
        IF (INconsecutive <= 5) THEN ! Less than 5 consecutive failed decompositions
           PH = PH*ZHALF
        ELSE  ! More than 5 consecutive failed decompositions
#ifdef WITH_COMPO_DR_HOOK
           IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_PREPAREMATRIX',1,ZHOOK_HANDLE) 
#endif
           RETURN
        ENDIF  ! INconsecutive
      ENDIF    ! ising

   ENDDO ! WHILE Singular

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_PREPAREMATRIX',1,ZHOOK_HANDLE) 
#endif

  END SUBROUTINE TM5_KPP_ros_PrepareMatrix


!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE TM5_KPP_ROS_DECOMP( PA, KPIVOT, KSING )
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  Template for the LU decomposition
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   USE YOMHOOK,    ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1,   ONLY : JPIM     ,JPRB, JPRD
   USE TM5_KPP_PARAMETERS, ONLY : NVAR,LU_NONZERO , Ndec
   IMPLICIT NONE
!~~~> Inout variables
#ifdef FULL_ALGEBRA    
   REAL(KIND=JPRD), INTENT(INOUT) :: PA(NVAR,NVAR)
#else   
   REAL(KIND=JPRD), INTENT(INOUT) :: PA(LU_NONZERO)
   REAL(KIND=JPRD)                :: ZA(LU_NONZERO)
#endif
!~~~> Output variables
   INTEGER(KIND=JPIM), INTENT(OUT) :: KPIVOT(NVAR), KSING
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_DECOMP',0,ZHOOK_HANDLE) 
#endif

#ifdef FULL_ALGEBRA    
   CALL  DGETRF( N, N, PA, N, KPIVOT, KSING )
#else   
   IF (JPRD==JPRD) THEN
     CALL TM5_KPP_KppDecomp ( PA, KSING )
   ELSE
     ! Cast SP into DP variable..
     ZA(:)=PA(:)
     CALL TM5_KPP_KppDecomp ( ZA, KSING )
     PA(:)=ZA(:)
   ENDIF
   KPIVOT(1) = 1
#endif
   KSTATUS(Ndec) = KSTATUS(Ndec) + 1
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_DECOMP',1,ZHOOK_HANDLE) 
#endif

  END SUBROUTINE TM5_KPP_ROS_DECOMP


!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE TM5_KPP_ROS_SOLVE( PA, KPIVOT, PB )
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  Template for the forward/backward substitution (using pre-computed LU decomposition)
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  ,ONLY : JPIM,    JPRB, JPRD
   USE TM5_KPP_PARAMETERS, ONLY : NVAR,LU_NONZERO, Nsol
   IMPLICIT NONE
!~~~> Input variables
   REAL(KIND=JPRD), INTENT(IN) :: PA(LU_NONZERO)
   INTEGER(KIND=JPIM), INTENT(IN) :: KPIVOT(NVAR)
!~~~> InOut variables
   REAL(KIND=JPRD), INTENT(INOUT) :: PB(NVAR)
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_SOLVE',0,ZHOOK_HANDLE) 
#endif

#ifdef FULL_ALGEBRA    
   CALL  DGETRS( 'N', N , 1, PA, NVAR, KPIVOT, PB, NVAR, 0 )
#else   
   CALL TM5_KPP_KppSolve( PA, PB )
#endif

   KSTATUS(Nsol) = KSTATUS(Nsol) + 1
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_ROS_SOLVE',1,ZHOOK_HANDLE) 
#endif

  END SUBROUTINE TM5_KPP_ROS_SOLVE



!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE Ros2
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! --- AN L-STABLE METHOD, 2 stages, order 2
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  ,ONLY : JPIM,  JPRB,  JPRD
   IMPLICIT NONE
   REAL(KIND=JPRD) :: Zg
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:ROS2',0,ZHOOK_HANDLE) 
#endif
    Zg = 1.0_JPRD + 1.0_JPRD/SQRT(2.0_JPRD)
    IrosMethod = IRS2
!~~~> Name of the method
    CL_ROS_NAME = 'ROS-2'
!~~~> Number of stages
    IROS_S = 2

!~~~> The coefficient matrices A and C are strictly lower triangular.
!   The lower triangular (subdiagonal) elements are stored in row-wise order:
!   A(2,1) = Z_ROS_A(1), A(3,1)=Z_ROS_A(2), A(3,2)=Z_ROS_A(3), etc.
!   The general mapping formula is:
!       A(i,j) = Z_ROS_A( (i-1)*(i-2)/2 + j )
!       C(i,j) = Z_ROS_C( (i-1)*(i-2)/2 + j )

    Z_ROS_A(1) = (1.0_JPRD)/Zg
    Z_ROS_C(1) = (-2.0_JPRD)/Zg
!~~~> Does the stage i require a new function evaluation (LL_ROS_NEWF(i)=TRUE)
!   or does it re-use the function evaluation from stage i-1 (LL_ROS_NEWF(i)=FALSE)
    LL_ROS_NEWF(1) = .TRUE.
    LL_ROS_NEWF(2) = .TRUE.
!~~~> M_i = Coefficients for new step solution
    Z_ROS_M(1)= (3.0_JPRD)/(2.0_JPRD*Zg)
    Z_ROS_M(2)= (1.0_JPRD)/(2.0_JPRD*Zg)
! E_i = Coefficients for error estimator
    Z_ROS_E(1) = 1.0_JPRD/(2.0_JPRD*Zg)
    Z_ROS_E(2) = 1.0_JPRD/(2.0_JPRD*Zg)
!~~~> Z_ROS_ELO = estimator of local order - the minimum between the
!    main and the embedded scheme orders plus one
    Z_ROS_ELO = 2.0_JPRD
!~~~> Y_stage_i ~ Y( T + H*Alpha_i )
    Z_ROS_Alpha(1) = 0.0_JPRD
    Z_ROS_Alpha(2) = 1.0_JPRD
!~~~> Gamma_i = \sum_j  gamma_{i,j}
    Z_ROS_GAMMA(1) = Zg
    Z_ROS_GAMMA(2) =-Zg

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:ROS2',1,ZHOOK_HANDLE) 
#endif
 END SUBROUTINE Ros2


!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE Ros3
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! --- AN L-STABLE METHOD, 3 stages, order 3, 2 function evaluations
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  ,ONLY : JPIM,  JPRB,  JPRD
  IMPLICIT NONE
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:ROS3',0,ZHOOK_HANDLE) 
#endif

   IrosMethod = IRS3
!~~~> Name of the method
   CL_ROS_NAME = 'ROS-3'
!~~~> Number of stages
   IROS_S = 3

!~~~> The coefficient matrices A and C are strictly lower triangular.
!   The lower triangular (subdiagonal) elements are stored in row-wise order:
!   A(2,1) = Z_ROS_A(1), A(3,1)=Z_ROS_A(2), A(3,2)=Z_ROS_A(3), etc.
!   The general mapping formula is:
!       A(i,j) = Z_ROS_A( (i-1)*(i-2)/2 + j )
!       C(i,j) = Z_ROS_C( (i-1)*(i-2)/2 + j )

   Z_ROS_A(1)= 1.0_JPRD
   Z_ROS_A(2)= 1.0_JPRD
   Z_ROS_A(3)= 0.0_JPRD

   Z_ROS_C(1) = -0.10156171083877702091975600115545E+01_JPRD
   Z_ROS_C(2) =  0.40759956452537699824805835358067E+01_JPRD
   Z_ROS_C(3) =  0.92076794298330791242156818474003E+01_JPRD
!~~~> Does the stage i require a new function evaluation (LL_ROS_NEWF(i)=TRUE)
!   or does it re-use the function evaluation from stage i-1 (LL_ROS_NEWF(i)=FALSE)
   LL_ROS_NEWF(1) = .TRUE.
   LL_ROS_NEWF(2) = .TRUE.
   LL_ROS_NEWF(3) = .FALSE.
!~~~> M_i = Coefficients for new step solution
   Z_ROS_M(1) =  0.1E+01_JPRD
   Z_ROS_M(2) =  0.61697947043828245592553615689730E+01_JPRD
   Z_ROS_M(3) = -0.42772256543218573326238373806514_JPRD
! E_i = Coefficients for error estimator
   Z_ROS_E(1) =  0.5_JPRD
   Z_ROS_E(2) = -0.29079558716805469821718236208017E+01_JPRD
   Z_ROS_E(3) =  0.22354069897811569627360909276199_JPRD
!~~~> Z_ROS_ELO = estimator of local order - the minimum between the
!    main and the embedded scheme orders plus 1
   Z_ROS_ELO = 3.0_JPRD
!~~~> Y_stage_i ~ Y( T + H*Alpha_i )
   Z_ROS_Alpha(1)= 0.0_JPRD
   Z_ROS_Alpha(2)= 0.43586652150845899941601945119356_JPRD
   Z_ROS_Alpha(3)= 0.43586652150845899941601945119356_JPRD
!~~~> Gamma_i = \sum_j  gamma_{i,j}
   Z_ROS_GAMMA(1)= 0.43586652150845899941601945119356_JPRD
   Z_ROS_GAMMA(2)= 0.24291996454816804366592249683314_JPRD
   Z_ROS_GAMMA(3)= 0.21851380027664058511513169485832E+01_JPRD

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:ROS3',1,ZHOOK_HANDLE) 
#endif
  END SUBROUTINE Ros3

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE Ros4
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!     L-STABLE ROSENBROCK METHOD OF ORDER 4, WITH 4 STAGES
!     L-STABLE EMBEDDED ROSENBROCK METHOD OF ORDER 3
!
!      E. HAIRER AND G. WANNER, SOLVING ORDINARY DIFFERENTIAL
!      EQUATIONS II. STIFF AND DIFFERENTIAL-ALGEBRAIC PROBLEMS.
!      SPRINGER SERIES IN COMPUTATIONAL MATHEMATICS,
!      SPRINGER-VERLAG (1990)
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  ,ONLY : JPIM, JPRB,   JPRD
   IMPLICIT NONE
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:ROS4',0,ZHOOK_HANDLE) 
#endif

   IrosMethod = IRS4
!~~~> Name of the method
   CL_ROS_NAME = 'ROS-4'
!~~~> Number of stages
   IROS_S = 4

!~~~> The coefficient matrices A and C are strictly lower triangular.
!   The lower triangular (subdiagonal) elements are stored in row-wise order:
!   A(2,1) = Z_ROS_A(1), A(3,1)=Z_ROS_A(2), A(3,2)=Z_ROS_A(3), etc.
!   The general mapping formula is:
!       A(i,j) = Z_ROS_A( (i-1)*(i-2)/2 + j )
!       C(i,j) = Z_ROS_C( (i-1)*(i-2)/2 + j )

   Z_ROS_A(1) = 0.2000000000000000E+01_JPRD
   Z_ROS_A(2) = 0.1867943637803922E+01_JPRD
   Z_ROS_A(3) = 0.2344449711399156_JPRD
   Z_ROS_A(4) = Z_ROS_A(2)
   Z_ROS_A(5) = Z_ROS_A(3)
   Z_ROS_A(6) = 0.0_JPRD

   Z_ROS_C(1) =-0.7137615036412310E+01_JPRD
   Z_ROS_C(2) = 0.2580708087951457E+01_JPRD
   Z_ROS_C(3) = 0.6515950076447975_JPRD
   Z_ROS_C(4) =-0.2137148994382534E+01_JPRD
   Z_ROS_C(5) =-0.3214669691237626_JPRD
   Z_ROS_C(6) =-0.6949742501781779_JPRD
!~~~> Does the stage i require a new function evaluation (LL_ROS_NEWF(i)=TRUE)
!   or does it re-use the function evaluation from stage i-1 (LL_ROS_NEWF(i)=FALSE)
   LL_ROS_NEWF(1)  = .TRUE.
   LL_ROS_NEWF(2)  = .TRUE.
   LL_ROS_NEWF(3)  = .TRUE.
   LL_ROS_NEWF(4)  = .FALSE.
!~~~> M_i = Coefficients for new step solution
   Z_ROS_M(1) = 0.2255570073418735E+01_JPRD
   Z_ROS_M(2) = 0.2870493262186792_JPRD
   Z_ROS_M(3) = 0.4353179431840180_JPRD
   Z_ROS_M(4) = 0.1093502252409163E+01_JPRD
!~~~> E_i  = Coefficients for error estimator
   Z_ROS_E(1) =-0.2815431932141155_JPRD
   Z_ROS_E(2) =-0.7276199124938920E-01_JPRD
   Z_ROS_E(3) =-0.1082196201495311_JPRD
   Z_ROS_E(4) =-0.1093502252409163E+01_JPRD
!~~~> Z_ROS_ELO  = estimator of local order - the minimum between the
!    main and the embedded scheme orders plus 1
   Z_ROS_ELO  = 4.0_JPRD
!~~~> Y_stage_i ~ Y( T + H*Alpha_i )
   Z_ROS_Alpha(1) = 0.0_JPRD
   Z_ROS_Alpha(2) = 0.1145640000000000E+01_JPRD
   Z_ROS_Alpha(3) = 0.6552168638155900_JPRD
   Z_ROS_Alpha(4) = Z_ROS_Alpha(3)
!~~~> Gamma_i = \sum_j  gamma_{i,j}
   Z_ROS_GAMMA(1) = 0.5728200000000000_JPRD
   Z_ROS_GAMMA(2) =-0.1769193891319233E+01_JPRD
   Z_ROS_GAMMA(3) = 0.7592633437920482_JPRD
   Z_ROS_GAMMA(4) =-0.1049021087100450_JPRD
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:ROS4',1,ZHOOK_HANDLE) 
#endif

  END SUBROUTINE Ros4

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE Rodas3
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! --- A STIFFLY-STABLE METHOD, 4 stages, order 3
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  ,ONLY : JPIM, JPRB,   JPRD
   IMPLICIT NONE

#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:RODAS3',0,ZHOOK_HANDLE) 
#endif

   IrosMethod = IRD3
!~~~> Name of the method
   CL_ROS_NAME = 'RODAS-3'
!~~~> Number of stages
   IROS_S = 4

!~~~> The coefficient matrices A and C are strictly lower triangular.
!   The lower triangular (subdiagonal) elements are stored in row-wise order:
!   A(2,1) = Z_ROS_A(1), A(3,1)=Z_ROS_A(2), A(3,2)=Z_ROS_A(3), etc.
!   The general mapping formula is:
!       A(i,j) = Z_ROS_A( (i-1)*(i-2)/2 + j )
!       C(i,j) = Z_ROS_C( (i-1)*(i-2)/2 + j )

   Z_ROS_A(1) = 0.0_JPRD
   Z_ROS_A(2) = 2.0_JPRD
   Z_ROS_A(3) = 0.0_JPRD
   Z_ROS_A(4) = 2.0_JPRD
   Z_ROS_A(5) = 0.0_JPRD
   Z_ROS_A(6) = 1.0_JPRD

   Z_ROS_C(1) = 4.0_JPRD
   Z_ROS_C(2) = 1.0_JPRD
   Z_ROS_C(3) =-1.0_JPRD
   Z_ROS_C(4) = 1.0_JPRD
   Z_ROS_C(5) =-1.0_JPRD
   Z_ROS_C(6) =-(8.0_JPRD/3.0_JPRD)

!~~~> Does the stage i require a new function evaluation (LL_ROS_NEWF(i)=TRUE)
!   or does it re-use the function evaluation from stage i-1 (LL_ROS_NEWF(i)=FALSE)
   LL_ROS_NEWF(1)  = .TRUE.
   LL_ROS_NEWF(2)  = .FALSE.
   LL_ROS_NEWF(3)  = .TRUE.
   LL_ROS_NEWF(4)  = .TRUE.
!~~~> M_i = Coefficients for new step solution
   Z_ROS_M(1) = 2.0_JPRD
   Z_ROS_M(2) = 0.0_JPRD
   Z_ROS_M(3) = 1.0_JPRD
   Z_ROS_M(4) = 1.0_JPRD
!~~~> E_i  = Coefficients for error estimator
   Z_ROS_E(1) = 0.0_JPRD
   Z_ROS_E(2) = 0.0_JPRD
   Z_ROS_E(3) = 0.0_JPRD
   Z_ROS_E(4) = 1.0_JPRD
!~~~> Z_ROS_ELO  = estimator of local order - the minimum between the
!    main and the embedded scheme orders plus 1
   Z_ROS_ELO  = 3.0_JPRD
!~~~> Y_stage_i ~ Y( T + H*Alpha_i )
   Z_ROS_Alpha(1) = 0.0_JPRD
   Z_ROS_Alpha(2) = 0.0_JPRD
   Z_ROS_Alpha(3) = 1.0_JPRD
   Z_ROS_Alpha(4) = 1.0_JPRD
!~~~> Gamma_i = \sum_j  gamma_{i,j}
   Z_ROS_GAMMA(1) = 0.5_JPRD
   Z_ROS_GAMMA(2) = 1.5_JPRD
   Z_ROS_GAMMA(3) = 0.0_JPRD
   Z_ROS_GAMMA(4) = 0.0_JPRD

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:RODAS3',1,ZHOOK_HANDLE) 
#endif
  END SUBROUTINE Rodas3

!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  SUBROUTINE Rodas4
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!     STIFFLY-STABLE ROSENBROCK METHOD OF ORDER 4, WITH 6 STAGES
!
!      E. HAIRER AND G. WANNER, SOLVING ORDINARY DIFFERENTIAL
!      EQUATIONS II. STIFF AND DIFFERENTIAL-ALGEBRAIC PROBLEMS.
!      SPRINGER SERIES IN COMPUTATIONAL MATHEMATICS,
!      SPRINGER-VERLAG (1996)
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  ,ONLY : JPIM, JPRB,   JPRD
   IMPLICIT NONE
#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:RODAS4',0,ZHOOK_HANDLE) 
#endif

    IrosMethod = IRD4
!~~~> Name of the method
    CL_ROS_NAME = 'RODAS-4'
!~~~> Number of stages
    IROS_S = 6

!~~~> Y_stage_i ~ Y( T + H*Alpha_i )
    Z_ROS_Alpha(1) = 0.000_JPRD
    Z_ROS_Alpha(2) = 0.386_JPRD
    Z_ROS_Alpha(3) = 0.210_JPRD
    Z_ROS_Alpha(4) = 0.630_JPRD
    Z_ROS_Alpha(5) = 1.000_JPRD
    Z_ROS_Alpha(6) = 1.000_JPRD

!~~~> Gamma_i = \sum_j  gamma_{i,j}
    Z_ROS_GAMMA(1) = 0.2500000000000000_JPRD
    Z_ROS_GAMMA(2) =-0.1043000000000000_JPRD
    Z_ROS_GAMMA(3) = 0.1035000000000000_JPRD
    Z_ROS_GAMMA(4) =-0.3620000000000023E-01_JPRD
    Z_ROS_GAMMA(5) = 0.0_JPRD
    Z_ROS_GAMMA(6) = 0.0_JPRD

!~~~> The coefficient matrices A and C are strictly lower triangular.
!   The lower triangular (subdiagonal) elements are stored in row-wise order:
!   A(2,1) = Z_ROS_A(1), A(3,1)=Z_ROS_A(2), A(3,2)=Z_ROS_A(3), etc.
!   The general mapping formula is:  A(i,j) = Z_ROS_A( (i-1)*(i-2)/2 + j )
!                  C(i,j) = Z_ROS_C( (i-1)*(i-2)/2 + j )

    Z_ROS_A(1) = 0.1544000000000000E+01_JPRD
    Z_ROS_A(2) = 0.9466785280815826_JPRD
    Z_ROS_A(3) = 0.2557011698983284_JPRD
    Z_ROS_A(4) = 0.3314825187068521E+01_JPRD
    Z_ROS_A(5) = 0.2896124015972201E+01_JPRD
    Z_ROS_A(6) = 0.9986419139977817_JPRD
    Z_ROS_A(7) = 0.1221224509226641E+01_JPRD
    Z_ROS_A(8) = 0.6019134481288629E+01_JPRD
    Z_ROS_A(9) = 0.1253708332932087E+02_JPRD
    Z_ROS_A(10) =-0.6878860361058950_JPRD
    Z_ROS_A(11) = Z_ROS_A(7)
    Z_ROS_A(12) = Z_ROS_A(8)
    Z_ROS_A(13) = Z_ROS_A(9)
    Z_ROS_A(14) = Z_ROS_A(10)
    Z_ROS_A(15) = 1.0_JPRD

    Z_ROS_C(1) =-0.5668800000000000E+01_JPRD
    Z_ROS_C(2) =-0.2430093356833875E+01_JPRD
    Z_ROS_C(3) =-0.2063599157091915_JPRD
    Z_ROS_C(4) =-0.1073529058151375_JPRD
    Z_ROS_C(5) =-0.9594562251023355E+01_JPRD
    Z_ROS_C(6) =-0.2047028614809616E+02_JPRD
    Z_ROS_C(7) = 0.7496443313967647E+01_JPRD
    Z_ROS_C(8) =-0.1024680431464352E+02_JPRD
    Z_ROS_C(9) =-0.3399990352819905E+02_JPRD
    Z_ROS_C(10) = 0.1170890893206160E+02_JPRD
    Z_ROS_C(11) = 0.8083246795921522E+01_JPRD
    Z_ROS_C(12) =-0.7981132988064893E+01_JPRD
    Z_ROS_C(13) =-0.3152159432874371E+02_JPRD
    Z_ROS_C(14) = 0.1631930543123136E+02_JPRD
    Z_ROS_C(15) =-0.6058818238834054E+01_JPRD

!~~~> M_i = Coefficients for new step solution
    Z_ROS_M(1) = Z_ROS_A(7)
    Z_ROS_M(2) = Z_ROS_A(8)
    Z_ROS_M(3) = Z_ROS_A(9)
    Z_ROS_M(4) = Z_ROS_A(10)
    Z_ROS_M(5) = 1.0_JPRD
    Z_ROS_M(6) = 1.0_JPRD

!~~~> E_i  = Coefficients for error estimator
    Z_ROS_E(1) = 0.0_JPRD
    Z_ROS_E(2) = 0.0_JPRD
    Z_ROS_E(3) = 0.0_JPRD
    Z_ROS_E(4) = 0.0_JPRD
    Z_ROS_E(5) = 0.0_JPRD
    Z_ROS_E(6) = 1.0_JPRD

!~~~> Does the stage i require a new function evaluation (LL_ROS_NEWF(i)=TRUE)
!   or does it re-use the function evaluation from stage i-1 (LL_ROS_NEWF(i)=FALSE)
    LL_ROS_NEWF(1) = .TRUE.
    LL_ROS_NEWF(2) = .TRUE.
    LL_ROS_NEWF(3) = .TRUE.
    LL_ROS_NEWF(4) = .TRUE.
    LL_ROS_NEWF(5) = .TRUE.
    LL_ROS_NEWF(6) = .TRUE.

!~~~> Z_ROS_ELO  = estimator of local order - the minimum between the
!        main and the embedded scheme orders plus 1
    Z_ROS_ELO = 4.0_JPRD
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:RODAS4',1,ZHOOK_HANDLE) 
#endif

  END SUBROUTINE Rodas4


!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE TM5_KPP_FunTemplate( PT, PY, PYdot,PRCONST )
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  Template for the ODE function call.
!  Updates the rate coefficients (and possibly the fixed species) at each call
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 USE YOMHOOK,   ONLY : LHOOK,   DR_HOOK, JPHOOK
 USE PARKIND1,  ONLY : JPIM, JPRB,   JPRD
 USE TM5_KPP_Parameters, ONLY: NVAR,NREACT
 USE TM5_KPP_Global, ONLY: FIX

 IMPLICIT NONE

! USE TM5_KPP_Function, ONLY: Fun
! USE TM5_KPP_Rates, ONLY: Update_SUN, Update_RCONST
!~~~> Input variables
   REAL(KIND=JPRD),INTENT(IN) :: PT, PY(NVAR),PRCONST(NREACT)
!~~~> Output variables
   REAL(KIND=JPRD), INTENT(OUT) :: PYdot(NVAR)
!~~~> Local variables
!   REAL(KIND=JPRD) :: ZTold

#ifdef WITH_COMPO_DR_HOOK
   REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#include "tm5_kpp_Fun.intfb.h"

#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_FUNTEMPLATE',0,ZHOOK_HANDLE)
#endif

!   ZTold = TIME
!   TIME = T
!   CALL Update_SUN()
!   CALL Update_RCONST()
   CALL TM5_KPP_Fun( PY, FIX, PRCONST, PYdot )
!   TIME = Told
#ifdef WITH_COMPO_DR_HOOK
   IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_FUNTEMPLATE',1,ZHOOK_HANDLE)
#endif

END SUBROUTINE TM5_KPP_FunTemplate


!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
SUBROUTINE TM5_KPP_JacTemplate( PT, PY, PJcb, PRCONST )
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!  Template for the ODE Jacobian call.
!  Updates the rate coefficients (and possibly the fixed species) at each call
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  , ONLY : JPIM     ,JPRD, JPRB
 USE TM5_KPP_Parameters, ONLY: NVAR, NREACT, LU_NONZERO
 USE TM5_KPP_Global, ONLY: FIX
 USE TM5_KPP_JacobianSP, ONLY: LU_IROW, LU_ICOL
! USE TM5_KPP_LinearAlgebra

! USE TM5_KPP_Rates, ONLY: Update_SUN, Update_RCONST
   IMPLICIT NONE
!~~~> Input variables
    REAL(KIND=JPRD), INTENT(IN) :: PT, PY(NVAR),PRCONST(NREACT)
!~~~> Output variables
#ifdef FULL_ALGEBRA    
    REAL(kind=JPRD)             :: ZJV(LU_NONZERO)
    REAL(kind=JPRD),INTENT(OUT) ::  PJcb(NVAR,NVAR)
#else
    REAL(KIND=JPRD), INTENT(OUT) :: PJcb(LU_NONZERO)
#endif   
!~~~> Local variables
#ifdef FULL_ALGEBRA    
    INTEGER(KIND=JPIM) :: i, j
#endif   
!*       0.5   LOCAL VARIABLES
!              ---------------

#ifdef WITH_COMPO_DR_HOOK
REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE
#endif

#include "tm5_kpp_Jacobian.intfb.h"

#ifdef WITH_COMPO_DR_HOOK
IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_JACTEMPLATE',0,ZHOOK_HANDLE)
#endif

#ifdef FULL_ALGEBRA    
    CALL TM5_KPP_Jacobian(PY, FIX, PRCONST, ZJV)
    DO j=1,NVAR
      DO i=1,NVAR
         PJcb(i,j) = 0.0_JPRD
      ENDDO
    ENDDO
    DO i=1,LU_NONZERO
       PJcb(LU_IROW(i),LU_ICOL(i)) = ZJV(i)
    ENDDO
#else
    CALL TM5_KPP_Jacobian( PY, FIX, PRCONST, PJcb )
#endif   
#ifdef WITH_COMPO_DR_HOOK
IF (LHOOK) CALL DR_HOOK('TM5_KPP_ROSENBROCK:TM5_KPP_JACTEMPLATE',1,ZHOOK_HANDLE)
#endif

END SUBROUTINE TM5_KPP_JacTemplate


!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!   End of the set of internal Rosenbrock subroutines
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
END SUBROUTINE TM5_KPP_Rosenbrock
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

! End of INTEGRATE function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
