! (C) Copyright 2009- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!     Variable naming changed to ECMWF conventions by V. Huijnen
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


SUBROUTINE TM5_KPP_FUN ( PV, PF, PRCT, PVdot )

  USE PARKIND1, ONLY : JPIM, JPRB, JPRD
  USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK

  USE TM5_KPP_PARAMETERS,  ONLY : NVAR, NREACT, NFIX
  USE TM5_CHEM_MODULE, ONLY: ZALPHA, ZBETA1,ZBETA2,ZGAMMA1,ZGAMMA2, ZDELTA, &
    & ZEPSILON1, ZEPSILON2,ZCHI1,ZCHI2,ZPHI1,ZPHI2 

  IMPLICIT NONE

! PV - Concentrations of variable species (local)
  REAL(KIND=JPRD), INTENT(IN) :: PV(NVAR)
! PF - Concentrations of fixed species (local)
  REAL(KIND=JPRD), INTENT(IN) :: PF(NFIX)
! PRCT - Rate constants (local)
  REAL(KIND=JPRD), INTENT(IN) :: PRCT(NREACT)
! PVdot - Time derivative of variable species concentrations
  REAL(KIND=JPRD), INTENT(OUT) :: PVdot(NVAR)


! Local variables
! ZA - Rate for each equation
  REAL(KIND=JPRD)    :: ZA(NREACT)
#ifdef WITH_COMPO_DR_HOOK
  REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE 

  IF (LHOOK) CALL DR_HOOK('TM5_KPP_FUN',0,ZHOOK_HANDLE) 
#endif

! Computation of equation rates
  ZA(1) = PRCT(1)*PV(62)*PV(63)
  ZA(2) = PRCT(2)*PV(62)*PV(64)
  ZA(3) = PRCT(3)*PV(63)*PV(64)
  ZA(4) = PRCT(4)*PV(64)*PV(64)
  ZA(5) = PRCT(5)*PV(14)*PV(63)
  ZA(6) = PRCT(6)*PV(63)
  ZA(7) = PRCT(7)*PV(62)*PV(66)
  ZA(8) = PRCT(8)*PV(62)*PV(67)
  ZA(9) = PRCT(9)*PV(66)*PV(68)
  ZA(10) = PRCT(10)*PV(67)*PV(68)
  ZA(11) = PRCT(11)*PV(19)
  ZA(12) = PRCT(12)*PV(63)*PV(66)
  ZA(13) = PRCT(13)*PV(20)*PV(63)
  ZA(14) = PRCT(14)*PV(64)*PV(66)
  ZA(15) = PRCT(15)*PV(63)*PV(67)
  ZA(16) = PRCT(16)*PV(64)*PV(67)
  ZA(17) = PRCT(17)*PV(64)*PV(68)
  ZA(18) = PRCT(18)*PV(40)*PV(63)
  ZA(19) = PRCT(19)*PV(27)
  ZA(20) = PRCT(20)*PV(27)*PV(63)
  ZA(21) = PRCT(21)*PV(66)*PV(71)
  ZA(22) = PRCT(22)*PV(71)*PV(71)
  ZA(23) = PRCT(23)*PV(50)*PV(66)
  ZA(24) = PRCT(24)*PV(64)*PV(71)
  ZA(25) = PRCT(25)*PV(50)*PV(64)
  ZA(26) = PRCT(26)*PV(50)*PV(71)
  ZA(27) = PRCT(27)*PV(50)
  ZA(28) = PRCT(28)*PV(9)*PV(63)
  ZA(29) = PRCT(29)*PV(25)*PV(63)
  ZA(30) = PRCT(30)*PV(64)*PV(65)
  ZA(31) = PRCT(31)*PV(64)*PV(65)
  ZA(32) = PRCT(32)*PV(65)*PV(66)
  ZA(33) = PRCT(33)*PV(65)*PV(67)
  ZA(34) = PRCT(34)*PV(29)
  ZA(35) = PRCT(35)*PV(65)*PV(68)
  ZA(36) = PRCT(36)*PV(30)*PV(63)
  ZA(37) = PRCT(37)*PV(53)*PV(63)
  ZA(38) = PRCT(38)*PV(53)*PV(68)
  ZA(39) = PRCT(39)*PV(44)*PV(63)
  ZA(40) = PRCT(40)*PV(31)*PV(63)
  ZA(41) = PRCT(41)*PV(65)*PV(65)
  ZA(42) = PRCT(42)*PV(68)*PV(71)
  ZA(43) = PRCT(43)*PV(16)*PV(63)
  ZA(44) = PRCT(44)*PV(32)*PV(62)
  ZA(45) = PRCT(45)*PV(32)*PV(63)
  ZA(46) = PRCT(46)*PV(66)*PV(69)
  ZA(47) = PRCT(47)*PV(67)*PV(69)
  ZA(48) = PRCT(48)*PV(68)*PV(69)
  ZA(49) = PRCT(49)*PV(21)
  ZA(50) = PRCT(50)*PV(69)*PV(69)
  ZA(51) = PRCT(51)*PV(64)*PV(69)
  ZA(52) = PRCT(52)*PV(64)*PV(69)
  ZA(53) = PRCT(53)*PV(24)*PV(70)
  ZA(54) = PRCT(54)*PV(23)*PV(63)
  ZA(55) = PRCT(55)*PV(17)*PV(63)
  ZA(56) = PRCT(56)*PV(10)*PV(63)
  ZA(57) = PRCT(57)*PV(43)*PV(66)
  ZA(58) = PRCT(58)*PV(43)*PV(64)
  ZA(59) = PRCT(59)*PV(47)*PV(62)
  ZA(60) = PRCT(60)*PV(47)*PV(63)
  ZA(61) = PRCT(61)*PV(39)*PV(66)
  ZA(62) = PRCT(62)*PV(39)*PV(64)
  ZA(63) = PRCT(63)*PV(47)*PV(68)
  ZA(64) = PRCT(64)*PV(33)*PV(63)
  ZA(65) = PRCT(65)*PV(55)*PV(64)
  ZA(66) = PRCT(66)*PV(55)*PV(65)
  ZA(67) = PRCT(67)*PV(55)*PV(66)
  ZA(68) = PRCT(68)*PV(55)*PV(71)
  ZA(69) = PRCT(69)*PV(56)*PV(63)
  ZA(70) = PRCT(70)*PV(63)*PV(70)
  ZA(71) = PRCT(71)*PV(28)
  ZA(72) = PRCT(72)*PV(28)
  ZA(73) = PRCT(73)*PV(46)*PV(63)
  ZA(74) = PRCT(74)*PV(46)*PV(62)
  ZA(75) = PRCT(75)*PV(46)*PV(68)
  ZA(76) = PRCT(76)*PV(61)*PV(63)
  ZA(77) = PRCT(77)*PV(57)*PV(63)
  ZA(78) = PRCT(78)*PV(57)*PV(68)
  ZA(79) = PRCT(79)*PV(51)*PV(62)
  ZA(80) = PRCT(80)*PV(51)*PV(68)
  ZA(81) = PRCT(81)*PV(52)*PV(63)
  ZA(82) = PRCT(82)*PV(36)*PV(63)
  ZA(83) = PRCT(83)*PV(36)*PV(62)
  ZA(84) = PRCT(84)*PV(36)*PV(68)
  ZA(85) = PRCT(85)*PV(38)*PV(63)
  ZA(86) = PRCT(86)*PV(38)*PV(62)
  ZA(87) = PRCT(87)*PV(38)*PV(68)
  ZA(88) = PRCT(88)*PV(54)*PV(66)
  ZA(89) = PRCT(89)*PV(54)*PV(54)
  ZA(90) = PRCT(90)*PV(54)*PV(64)
  ZA(91) = PRCT(91)*PV(54)*PV(71)
  ZA(92) = PRCT(92)*PV(15)*PV(63)
  ZA(93) = PRCT(93)*PV(51)*PV(63)
  ZA(94) = PRCT(94)*PV(59)
  ZA(95) = PRCT(95)*PV(59)
  ZA(96) = PRCT(96)*PV(58)
  ZA(97) = PRCT(97)*PV(58)
  ZA(98) = PRCT(98)*PV(59)*PV(64)
  ZA(99) = PRCT(99)*PV(59)*PV(66)
  ZA(100) = PRCT(100)*PV(58)*PV(64)
  ZA(101) = PRCT(101)*PV(58)*PV(66)
  ZA(102) = PRCT(102)*PV(48)*PV(63)
  ZA(103) = PRCT(103)*PV(41)*PV(63)
  ZA(104) = PRCT(104)*PV(42)*PV(63)
  ZA(105) = PRCT(105)*PV(45)*PV(63)
  ZA(106) = PRCT(106)*PV(34)*PV(63)
  ZA(107) = PRCT(107)*PV(37)*PV(63)
  ZA(108) = PRCT(108)*PV(37)
  ZA(109) = PRCT(109)*PV(34)
  ZA(110) = PRCT(110)*PV(45)
  ZA(111) = PRCT(111)*PV(45)
  ZA(112) = PRCT(112)*PV(41)
  ZA(113) = PRCT(113)*PV(42)
  ZA(114) = PRCT(114)*PV(48)
  ZA(115) = PRCT(115)*PV(49)*PV(63)
  ZA(116) = PRCT(116)*PV(49)*PV(62)
  ZA(117) = PRCT(117)*PV(49)*PV(68)
  ZA(118) = PRCT(118)*PV(60)*PV(63)
  ZA(119) = PRCT(119)*PV(60)*PV(62)
  ZA(120) = PRCT(120)*PV(60)*PV(68)
  ZA(121) = PRCT(121)*PV(22)*PV(63)
  ZA(122) = PRCT(122)*PV(22)*PV(63)
  ZA(123) = PRCT(123)*PV(22)*PV(68)
  ZA(124) = PRCT(124)*PV(26)*PV(63)
  ZA(125) = PRCT(125)*PV(26)*PV(62)
  ZA(126) = PRCT(126)*PV(4)
  ZA(127) = PRCT(127)*PV(13)*PV(63)
  ZA(128) = PRCT(128)*PV(18)*PV(63)
  ZA(129) = PRCT(129)*PV(35)*PV(66)
  ZA(130) = PRCT(130)*PV(35)*PV(67)
  ZA(131) = PRCT(131)*PV(35)*PV(64)
  ZA(132) = PRCT(132)*PV(35)*PV(63)
  ZA(133) = PRCT(133)*PV(35)
  ZA(134) = PRCT(134)*PV(1)
  ZA(135) = PRCT(135)*PV(11)*PV(63)
  ZA(136) = PRCT(136)*PV(12)*PV(63)
  ZA(137) = PRCT(137)*PV(62)
  ZA(138) = PRCT(138)*PV(67)
  ZA(139) = PRCT(139)*PV(19)
  ZA(140) = PRCT(140)*PV(40)
  ZA(141) = PRCT(141)*PV(68)
  ZA(142) = PRCT(142)*PV(68)
  ZA(143) = PRCT(143)*PV(27)
  ZA(144) = PRCT(144)*PV(20)
  ZA(145) = PRCT(145)*PV(30)
  ZA(146) = PRCT(146)*PV(53)
  ZA(147) = PRCT(147)*PV(53)
  ZA(148) = PRCT(148)*PV(14)
  ZA(149) = PRCT(149)*PV(33)
  ZA(150) = PRCT(150)*PV(33)
  ZA(151) = PRCT(151)*PV(21)
  ZA(152) = PRCT(152)*PV(21)
  ZA(153) = PRCT(153)*PV(52)
  ZA(154) = PRCT(154)*PV(61)
  ZA(155) = PRCT(155)*PV(57)
  ZA(156) = PRCT(156)*PV(56)
  ZA(157) = PRCT(157)*PV(60)
  ZA(158) = PRCT(158)*PV(29)
  ZA(159) = PRCT(159)*PV(19)
  ZA(160) = PRCT(160)*PV(68)

! Aggregate function
  PVdot(1) = -ZA(134)
  PVdot(2) = ZA(134)
  PVdot(3) = ZA(126)
  PVdot(4) = ZA(124)+ZA(125)-ZA(126)
  PVdot(5) = 0.25*ZA(122)
  PVdot(6) = ZALPHA*ZA(79)+ZDELTA*ZA(93)+ZEPSILON1*ZA(115)+ZEPSILON2*ZA(116)
  PVdot(7) = ZBETA2*ZA(82)+ZPHI2*ZA(83)+ZGAMMA2*ZA(85)+ZCHI2*ZA(86)+1.15*ZA(92)
  PVdot(8) = ZA(3)+ZA(22)+ZA(26)+ZA(27)+ZA(53)+ZA(68)+ZA(89)+ZA(91)+ZA(129)+ZA(130)+ZA(132)+ZA(135)
  PVdot(9) = -ZA(28)
  PVdot(10) = -ZA(56)
  PVdot(11) = -ZA(135)+0.3*ZA(136)
  PVdot(12) = -ZA(136)
  PVdot(13) = -ZA(127)
  PVdot(14) = ZA(4)-ZA(5)-ZA(148)
  PVdot(15) = ZBETA1*ZA(82)+ZPHI1*ZA(83)+ZGAMMA1*ZA(85)+ZCHI1*ZA(86)-ZA(92)
  PVdot(16) = -ZA(43)
  PVdot(17) = -ZA(55)
  PVdot(18) = -ZA(128)+ZA(131)
  PVdot(19) = ZA(10)-ZA(11)-ZA(139)-ZA(159)
  PVdot(20) = ZA(12)-ZA(13)-ZA(144)
  PVdot(21) = ZA(47)-ZA(49)-ZA(151)-ZA(152)
  PVdot(22) = -ZA(121)-ZA(122)-ZA(123)
  PVdot(23) = ZA(52)-ZA(54)+0.125*ZA(107)
  PVdot(24) = -ZA(53)+ZA(69)+0.11*ZA(70)+2.1*ZA(71)+0.7*ZA(73)+ZA(74)+ZA(75)+1.98*ZA(76)+1.98*ZA(154)+1.98*ZA(156)
  PVdot(25) = -ZA(29)+0.63*ZA(41)+0.5*ZA(66)
  PVdot(26) = ZA(121)+0.75*ZA(122)+ZA(123)-ZA(124)-ZA(125)+ZA(127)
  PVdot(27) = ZA(16)-ZA(19)-ZA(20)-ZA(143)
  PVdot(28) = 0.76*ZA(70)-0.98*ZA(71)-ZA(72)
  PVdot(29) = ZA(33)-ZA(34)-ZA(158)
  PVdot(30) = ZA(30)-ZA(36)-ZA(145)
  PVdot(31) = -ZA(40)+0.52*ZA(44)+0.25*ZA(59)+0.17*ZA(106)+0.125*ZA(107)
  PVdot(32) = -ZA(44)-ZA(45)
  PVdot(33) = 0.82*ZA(57)-ZA(64)-ZA(149)-ZA(150)
  PVdot(34) = -ZA(106)-ZA(109)+0.5*ZA(112)+0.5*ZA(113)
  PVdot(35) = ZA(128)-ZA(129)-ZA(130)-ZA(131)-ZA(132)-ZA(133)
  PVdot(36) = -ZA(82)-ZA(83)-ZA(84)
  PVdot(37) = -ZA(107)-ZA(108)+0.5*ZA(112)+0.5*ZA(113)
  PVdot(38) = -ZA(85)-ZA(86)-ZA(87)
  PVdot(39) = ZA(60)-ZA(61)-ZA(62)
  PVdot(40) = ZA(15)+ZA(17)-ZA(18)+ZA(38)+ZA(76)+ZA(78)+0.15*ZA(120)+ZA(123)-ZA(140)+2*ZA(159)+ZA(160)
  PVdot(41) = ZA(94)+0.37*ZA(99)-ZA(103)-ZA(112)
  PVdot(42) = ZA(96)+0.37*ZA(101)-ZA(104)-ZA(113)
  PVdot(43) = ZA(56)-ZA(57)-ZA(58)
  PVdot(44) = ZA(37)-ZA(39)+0.24*ZA(44)+0.56*ZA(59)+0.62*ZA(73)+0.65*ZA(74)+0.56*ZA(75)+0.066*ZA(79)+ZA(81)+1.26*ZA(105)&
                &+0.5*ZA(106)+0.05*ZA(107)+ZA(109)+2*ZA(110)+ZA(111)+0.47*ZA(115)+0.211*ZA(116)+0.47*ZA(117)+0.334*ZA(118)&
                &+0.225*ZA(119)+0.643*ZA(120)+ZA(146)+ZA(147)+ZA(149)+ZA(153)+ZA(155)+0.825*ZA(157)
  PVdot(45) = ZA(88)+ZA(90)+0.3*ZA(102)+0.25*ZA(103)+0.25*ZA(104)-ZA(105)+0.17*ZA(106)-ZA(110)-ZA(111)+0.5*ZA(113)
  PVdot(46) = -ZA(73)-ZA(74)-ZA(75)
  PVdot(47) = -ZA(59)-ZA(60)-ZA(63)
  PVdot(48) = ZA(98)+ZA(100)-ZA(102)-ZA(114)
  PVdot(49) = -ZA(115)-ZA(116)-ZA(117)
  PVdot(50) = -ZA(23)-ZA(25)-ZA(26)-ZA(27)+0.009*ZA(43)+0.13*ZA(70)+0.04*ZA(71)+0.09*ZA(75)+0.25*ZA(115)+0.18*ZA(116)&
                &+0.25*ZA(117)
  PVdot(51) = -ZA(79)-ZA(80)-ZA(93)
  PVdot(52) = 0.5*ZA(66)+ZA(67)+0.19*ZA(69)-ZA(81)+ZA(87)+0.33*ZA(88)+0.4*ZA(102)+0.1*ZA(103)+0.1*ZA(104)+0.75*ZA(107)&
                &+0.5*ZA(112)+0.168*ZA(118)+0.85*ZA(119)-ZA(153)
  PVdot(53) = ZA(29)+ZA(31)+ZA(32)+ZA(35)+0.4*ZA(36)-ZA(37)-ZA(38)+1.37*ZA(41)+ZA(44)+1.56*ZA(45)+0.1*ZA(55)+0.54*ZA(59)&
                &+ZA(61)+0.8*ZA(73)+0.74*ZA(74)+ZA(75)+0.6*(1.-ZALPHA)*ZA(79)+ZA(95)+ZA(97)+0.51*ZA(99)+0.51*ZA(101)+0.67*ZA(106)&
                &+ZA(108)+ZA(109)+ZA(111)+ZA(112)+ZA(113)+0.69*ZA(114)+1.22*ZA(115)+1.8*ZA(116)+0.167*ZA(118)+0.15*ZA(119)&
                &+0.282*ZA(120)+ZA(145)-ZA(146)-ZA(147)+0.5*ZA(157)+0.5*ZA(158)
  PVdot(54) = 1.*(1.-ZBETA1-ZBETA2)*ZA(82)+1.*(1.-ZPHI1-ZPHI2)*ZA(83)+1.*(1.-ZGAMMA1-ZGAMMA2)*ZA(85)+1.*(1.-ZCHI1-ZCHI2)*ZA(86)-ZA(88)-2*ZA(89)-ZA(90)-ZA(91)
  PVdot(55) = ZA(64)-ZA(65)-ZA(66)-ZA(67)-ZA(68)
  PVdot(56) = ZA(24)+ZA(25)+ZA(58)+ZA(62)+ZA(65)-ZA(69)+ZA(90)-ZA(156)
  PVdot(57) = 0.991*ZA(43)+0.22*ZA(45)+ZA(55)+0.27*ZA(57)+0.5*ZA(59)+ZA(61)+0.7*ZA(66)+0.04*ZA(69)+0.11*ZA(70)+1.1&
                &*ZA(71)+0.95*ZA(73)+0.5*ZA(74)+0.91*ZA(75)+0.3*ZA(76)-ZA(77)-ZA(78)+0.8*ZA(80)+0.47*ZA(115)+0.21*ZA(116)&
                &+0.47*ZA(117)+0.273*ZA(118)+0.02*ZA(119)+0.357*ZA(120)+0.3*ZA(154)-ZA(155)+0.3*ZA(156)
  PVdot(58) = 0.35*(1.-ZDELTA)*ZA(93)-ZA(96)-ZA(97)-ZA(100)-ZA(101)+0.08*ZA(102)
  PVdot(59) = 0.65*(1.-ZDELTA)*ZA(93)-ZA(94)-ZA(95)-ZA(98)-ZA(99)+0.12*ZA(102)
  PVdot(60) = 0.65*(1.-ZALPHA)*ZA(79)+0.2*ZA(80)+ZA(95)+ZA(97)+0.55*ZA(99)+0.55*ZA(101)+0.69*ZA(114)-ZA(118)-ZA(119)-ZA(120)&
                &-ZA(157)
  PVdot(61) = ZA(23)+ZA(63)-ZA(76)+0.8*ZA(80)+ZA(84)+ZA(87)+0.08*ZA(99)+0.08*ZA(101)+0.53*ZA(117)+0.85*ZA(120)-ZA(154)
  PVdot(62) = -ZA(1)-ZA(2)-ZA(7)-ZA(8)-ZA(44)+ZA(52)-ZA(59)-ZA(74)-ZA(79)-ZA(83)-ZA(86)-ZA(116)-ZA(119)-ZA(125)-ZA(137)&
                &+ZA(138)+ZA(141)
  PVdot(63) = -ZA(1)+ZA(2)-ZA(3)-ZA(5)-ZA(6)-ZA(12)-ZA(13)+ZA(14)-ZA(15)-ZA(18)-ZA(20)-ZA(28)-ZA(29)-0.6*ZA(36)-ZA(37)&
                &-ZA(39)-ZA(40)-ZA(43)+0.12*ZA(44)-ZA(45)+ZA(51)-ZA(54)-ZA(55)-ZA(56)+0.33*ZA(59)-ZA(60)-ZA(64)-0.77*ZA(69)&
                &-ZA(70)-ZA(73)+0.1*ZA(74)-ZA(76)-ZA(77)+0.266*ZA(79)-ZA(81)-ZA(82)-ZA(85)-ZA(92)-ZA(93)+ZA(95)+ZA(97)&
                &-ZA(102)-ZA(103)-ZA(104)-ZA(105)-0.75*ZA(106)-0.9*ZA(107)+ZA(112)+ZA(113)-ZA(115)+0.57*ZA(116)-ZA(118)&
                &+0.268*ZA(119)-ZA(121)-ZA(122)-ZA(124)-ZA(127)-ZA(128)-ZA(132)-ZA(135)-ZA(136)+2*ZA(137)+ZA(140)+ZA(144)&
                &+ZA(145)+2*ZA(148)+ZA(156)
  PVdot(64) = ZA(1)-ZA(2)-ZA(3)-2*ZA(4)+ZA(5)+ZA(6)-ZA(14)-ZA(16)-ZA(17)+ZA(19)-ZA(24)-ZA(25)+ZA(29)-ZA(30)-ZA(31)&
                &+ZA(32)+ZA(35)+ZA(37)+ZA(39)+ZA(40)+0.74*ZA(41)+ZA(43)+0.22*ZA(44)+ZA(45)-ZA(51)-ZA(52)+ZA(55)+ZA(57)&
                &-ZA(58)+0.19*ZA(59)+ZA(61)-ZA(62)-ZA(65)+0.5*ZA(66)+ZA(67)+0.11*ZA(70)+0.94*ZA(71)+ZA(72)+1.57*ZA(73)+0.76&
                &*ZA(74)+0.56*ZA(75)+0.9*ZA(76)+0.066*ZA(79)+0.8*ZA(80)-ZA(90)+ZA(94)+ZA(96)-ZA(98)+ZA(99)-ZA(100)+ZA(101)&
                &+0.63*ZA(105)+0.75*ZA(106)+0.825*ZA(107)+ZA(108)+2*ZA(109)+2*ZA(110)+ZA(112)+ZA(113)+ZA(114)+1.22*ZA(115)&
                &+0.28*ZA(116)+0.75*ZA(117)+0.503*ZA(118)+0.154*ZA(119)+0.925*ZA(120)+ZA(124)-ZA(131)+ZA(143)+ZA(145)+2&
                &*ZA(147)+ZA(153)+0.9*ZA(154)+ZA(155)+0.9*ZA(156)+ZA(157)+0.5*ZA(158)
  PVdot(65) = ZA(28)-ZA(30)-ZA(31)-ZA(32)-ZA(33)+ZA(34)-ZA(35)+0.6*ZA(36)-2*ZA(41)+ZA(46)+ZA(48)+2*ZA(50)+ZA(51)+ZA(54)&
                &+0.31*ZA(59)-ZA(66)+0.74*ZA(76)+0.4*ZA(81)+0.125*ZA(107)+0.39*ZA(116)+2*ZA(149)+ZA(150)+ZA(152)+0.74&
                &*ZA(154)+ZA(155)+0.74*ZA(156)+0.325*ZA(157)+0.5*ZA(158)
  PVdot(66) = -ZA(7)-ZA(9)-ZA(12)-ZA(14)-ZA(21)-ZA(23)-ZA(32)-ZA(46)-ZA(57)-ZA(61)-ZA(67)-ZA(88)-ZA(99)-ZA(101)-ZA(129)&
                &+ZA(133)+ZA(138)+ZA(142)+ZA(144)
  PVdot(67) = ZA(7)-ZA(8)+2*ZA(9)-ZA(10)+ZA(11)+ZA(13)+ZA(14)-ZA(15)-ZA(16)+ZA(19)+ZA(20)+ZA(21)+ZA(32)-ZA(33)+ZA(34)&
                &+ZA(35)+ZA(42)+ZA(46)-ZA(47)+ZA(48)+ZA(49)+ZA(57)+ZA(61)+ZA(67)+ZA(75)+0.2*ZA(80)+ZA(88)+0.92*ZA(99)+0.92&
                &*ZA(101)+0.47*ZA(117)-ZA(130)-ZA(138)+ZA(139)+ZA(140)+ZA(141)+ZA(143)+ZA(151)+ZA(154)+0.5*ZA(158)
  PVdot(68) = ZA(8)-ZA(9)-ZA(10)+ZA(11)-ZA(17)+ZA(18)-ZA(35)-ZA(38)-ZA(42)-ZA(48)-ZA(63)-ZA(75)-ZA(78)-ZA(80)-ZA(84)&
                &-ZA(87)-ZA(117)-ZA(120)-ZA(123)+ZA(139)-ZA(141)-ZA(142)+ZA(152)+0.5*ZA(158)-ZA(160)
  PVdot(69) = -ZA(46)-ZA(47)-ZA(48)+ZA(49)-2*ZA(50)-ZA(51)-ZA(52)+0.3*ZA(66)+0.74*ZA(76)+ZA(77)+ZA(78)+0.2*(1.-ZALPHA)*ZA(79)&
                &+0.6*ZA(81)+0.3*ZA(105)+ZA(108)+0.39*ZA(116)+0.5*ZA(118)+0.114*ZA(119)+0.075*ZA(120)+ZA(150)+ZA(151)&
                &+ZA(153)+0.74*ZA(154)+0.74*ZA(156)+0.174*ZA(157)
  PVdot(70) = -ZA(53)+0.6*ZA(66)-ZA(70)+0.35*(1.-ZALPHA)*ZA(79)+2.4*ZA(80)+5.*(1.-ZBETA1-ZBETA2)*ZA(82)+5.*(1.-ZPHI1-ZPHI2)*ZA(83)+ZA(84)+5.*(1.-ZGAMMA1-ZGAMMA2)*ZA(85)&
                &+5.*(1.-ZCHI1-ZCHI2)*ZA(86)+ZA(87)+5.*(1.-ZEPSILON1)*ZA(115)+6.*(1.-ZEPSILON2)*ZA(116)+6*ZA(117)+1.565*ZA(118)+0.36*ZA(119)+1.282*ZA(120)
  PVdot(71) = -ZA(21)-2*ZA(22)-ZA(24)-ZA(26)-ZA(42)+0.991*ZA(43)+ZA(45)+0.1*ZA(55)-ZA(68)+0.77*ZA(69)+0.87*ZA(70)+0.96&
                &*ZA(71)+0.8*ZA(73)+0.22*ZA(74)+0.91*ZA(75)+0.51*ZA(76)+0.2*(1.-ZALPHA)*ZA(79)+ZA(80)-ZA(91)+0.1*ZA(102)+0.65&
                &*ZA(103)+0.65*ZA(104)+1.25*ZA(115)+0.76*ZA(116)+1.03*ZA(117)+0.5*ZA(118)+0.064*ZA(119)+0.075*ZA(120)+0.51&
                &*ZA(154)+0.5*ZA(156)+0.5*ZA(157)

#ifdef WITH_COMPO_DR_HOOK
  IF (LHOOK) CALL DR_HOOK('TM5_KPP_FUN',1,ZHOOK_HANDLE) 
#endif

      
END SUBROUTINE TM5_KPP_FUN

! End of TM5_KPP_FUN function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


