! (C) Copyright 2009- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Initialization File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


SUBROUTINE TM5_V0_KPP_UPDATE_CIFS_CONC(YGFL,PVAR,PCVM,LAERSOA_COUPLED)

   USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
   USE PARKIND1  , ONLY : JPIM     ,JPRB, JPRD
   USE TM5_KPP_PARAMETERS, ONLY:  NVAR,&
&   IND_SO4   , IND_CH3SO3H   ,  IND_NH3   , IND_CH4 ,&
&   IND_C3H8  , IND_SO2   , IND_H2O2  , IND_PAN   , IND_DMS   , IND_C2H6,&
&   IND_C2H5OH    , IND_N2O5  , IND_MCOOH , IND_HCOOH , IND_RXPAR , IND_CH3OH,&
&   IND_HNO4  , IND_ROR   , IND_CH3OOH    , IND_C2H4,&
&   IND_CH3COCH3  , IND_NH2   , IND_HNO3  , IND_HYPROPO2,&
&   IND_CO   , IND_MGLYOX   , IND_IC3H7O2  , IND_OLE  , IND_C3H6 ,&
&   IND_C10H16   , IND_C5H8 , IND_ISPD , IND_HCHO , IND_PAR  , IND_ORGNTR   ,&
&   IND_ALD2 , IND_ACO2 , IND_O3  , IND_ROOH ,&
&   IND_OH   , IND_CH3O2    , IND_XO2  , IND_HO2  , IND_NO3  , IND_XO2N , IND_C2O3 ,&
&   IND_NO   , IND_NO2  , IND_RN, IND_PB, &
&   IND_SO3 , &   
&   IND_HONO    , IND_CH3O2NO2, IND_XYL, IND_TOL, IND_AROO2, IND_HCN, IND_CH3CN , &
&     IND_ISOPBO2,IND_ISOPDO2, IND_HPALD1 , IND_HPALD2 ,IND_ISOPOOH,IND_GLY,IND_GLYALD, IND_HYAC, &   
&   IND_SOG1, IND_SOG2A, IND_SOG2B   

   
   USE YOM_YGFL , ONLY : TYPE_GFLD
   USE TM5_CHEM_MODULE, ONLY :  IO3, IH2O2,&
    & ICH4, ICO, IHNO3, ICH3O2H, ICH2O, IPAR, IETH,IOLE,&
    & IALD2, IPAN, IROOH, IORGNTR, IISOP, ISO2, IDMS, INH3,&
    & ISO4, IMSA, IMGLY,   IRN222, IPB210, INO,  IHO2,&
    & ICH3O2, IOH, INO2, INO3, IN2O5,  IHNO4,  IC2O3,  IROR,&
    & IRXPAR, IXO2, IXO2N,  INH2, ICH3OH, IHCOOH,IMCOOH,&
    & IC2H6,  IETHOH, IC3H8,  IC3H6,  ITERP,  IISPD,  IACET,  IACO2,&
    & IIC3H7O2,  IHYPROPO2, &
    & ISO3, IHONO, ICH3O2NO2, &
    & IXYL, ITOL, IAROO2, IHCN, ICH3CN , &
    & IISOPBO2,IISOPDO2, IHPALD1 , IHPALD2 ,IISOPOOH,IGLY,IGLYALD, IHYAC, &   
    & ISOG1, ISOG2A, ISOG2B   

   IMPLICIT NONE

   TYPE(TYPE_GFLD)   ,INTENT(INOUT)  :: YGFL
   REAL(KIND=JPRD),INTENT(IN)     :: PVAR(NVAR)
   REAL(KIND=JPRB),INTENT(INOUT)  :: PCVM(YGFL%NCHEM)
   LOGICAL, INTENT(IN)            :: LAERSOA_COUPLED

!*       0.5   LOCAL PVARIABLES
!              ---------------

REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('TM5_V0_KPP_UPDATE_CIFS_CONC',0,ZHOOK_HANDLE )

   PCVM(IRN222 ) = PVAR(IND_RN)
   PCVM(IPB210 ) = PVAR(IND_PB)
   PCVM(ISO4 )   = PVAR(IND_SO4)
   PCVM(IMSA )   = PVAR(IND_CH3SO3H)
   PCVM(INH3 )   = PVAR(IND_NH3)
   PCVM(ICH4 )   = PVAR(IND_CH4)
   PCVM(IC3H8 )  = PVAR(IND_C3H8)
   PCVM(ISO2 )   = PVAR(IND_SO2)
   PCVM(IH2O2 )  = PVAR(IND_H2O2)
   PCVM(IDMS )   = PVAR(IND_DMS)
   PCVM(IC2H6 )  = PVAR(IND_C2H6)
   PCVM(IETHOH ) = PVAR(IND_C2H5OH)
   PCVM(IN2O5 )  = PVAR(IND_N2O5)
   PCVM(IPAN )   = PVAR(IND_PAN)
   PCVM(IMCOOH ) = PVAR(IND_MCOOH) 
   PCVM(IHCOOH ) = PVAR(IND_HCOOH) 
   PCVM(ICH3OH ) = PVAR(IND_CH3OH) 
   PCVM(IHNO4 )  = PVAR(IND_HNO4) 
   PCVM(IROR )   = PVAR(IND_ROR) 
   PCVM(ICH3O2H ) = PVAR(IND_CH3OOH) 
   PCVM(IRXPAR ) = PVAR(IND_RXPAR) 
   PCVM(IETH )   = PVAR(IND_C2H4) 
   PCVM(IACET )  = PVAR(IND_CH3COCH3) 
   PCVM(INH2 )   = PVAR(IND_NH2) 
   PCVM(IHNO3 )  = PVAR(IND_HNO3) 
   PCVM(IHYPROPO2 )= PVAR(IND_HYPROPO2) 
   PCVM(IIC3H7O2 )= PVAR(IND_IC3H7O2) 
   PCVM(IMGLY )  = PVAR(IND_MGLYOX) 
   PCVM(IC3H6 )  = PVAR(IND_C3H6) 
   PCVM(IOLE )   = PVAR(IND_OLE) 
   PCVM(ICO )    = PVAR(IND_CO)
   PCVM(IISOP )  = PVAR(IND_C5H8)
   PCVM(IISPD )  = PVAR(IND_ISPD)
   PCVM(IXO2N )  = PVAR(IND_XO2N)
   PCVM(ITERP )  = PVAR(IND_C10H16)
   PCVM(ICH2O )  = PVAR(IND_HCHO)
   PCVM(IPAR )   = PVAR(IND_PAR)
   PCVM(IACO2 )  = PVAR(IND_ACO2)
   PCVM(INO2 )   = PVAR(IND_NO2)
   PCVM(IC2O3 )  = PVAR(IND_C2O3)
   PCVM(IALD2 )  = PVAR(IND_ALD2)
   PCVM(IORGNTR )= PVAR(IND_ORGNTR)
   PCVM(ICH3O2 ) = PVAR(IND_CH3O2)
   PCVM(IROOH )  = PVAR(IND_ROOH)
   PCVM(INO3 )   = PVAR(IND_NO3)
   PCVM(IHO2 )   = PVAR(IND_HO2)
   PCVM(IXO2 )   = PVAR(IND_XO2)
   PCVM(IOH )    = PVAR(IND_OH)
   PCVM(IO3 )    = PVAR(IND_O3)
   PCVM(INO )    = PVAR(IND_NO)
   !VH PCVM(IOCS)    = PVAR(IND_OCS)   ! Don't use OCS in CB05-tropospheric chemistry only
   PCVM(ISO3)    = PVAR(IND_SO3) 
   PCVM(IHONO)   = PVAR(IND_HONO) 
   PCVM(ICH3O2NO2)= PVAR(IND_CH3O2NO2) 
   PCVM(IXYL )   = PVAR(IND_XYL)
   PCVM(ITOL )   = PVAR(IND_TOL) 
   PCVM(IAROO2)  = PVAR(IND_AROO2)    
   PCVM(IHCN )   = PVAR(IND_HCN)
   PCVM(ICH3CN ) = PVAR(IND_CH3CN)   

   PCVM(IISOPBO2 )=  PVAR(IND_ISOPBO2)  
   PCVM(IISOPDO2 )=  PVAR(IND_ISOPDO2)    
   PCVM(IHPALD1 ) =  PVAR(IND_HPALD1) 
   PCVM(IHPALD2 ) =  PVAR(IND_HPALD2)     
   PCVM(IISOPOOH )=  PVAR(IND_ISOPOOH)    
   PCVM(IGLY )    =  PVAR(IND_GLY)     
   PCVM(IGLYALD ) =  PVAR(IND_GLYALD)     
   PCVM(IHYAC )   =  PVAR(IND_HYAC)    

   IF (LAERSOA_COUPLED) THEN
     PCVM(ISOG1 )   =  PVAR(IND_SOG1)    
     PCVM(ISOG2A )  =  PVAR(IND_SOG2A)    
     PCVM(ISOG2B )  =  PVAR(IND_SOG2B)    
   ENDIF


 
IF (LHOOK) CALL DR_HOOK('TM5_V0_KPP_UPDATE_CIFS_CONC',1,ZHOOK_HANDLE )
    
END SUBROUTINE TM5_V0_KPP_UPDATE_CIFS_CONC
