! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

!OPTIONS XOPT(HSFUN)
SUBROUTINE RADACT &
 & ( YDEAERD,YDERAD,YDEAERSNK,YDRIP,YDSPP_CONFIG,KIDIA , KFDIA , KLON , KLEV,&
 & KRINT , KDLON , KDLONP2 , KSHIFT, KCF,&
 & PAPRS , PGELAM, PSIN  , PCLON, PSLON , PTH,&
 & PQ    , PQS   , PECPO3,&
 & PAER  , PAERO , POZON, &
 & PPERT &
 & )  

!***********************************************************************
! CAUTION: THIS ROUTINE WORKS ONLY ON A NON-ROTATED, UNSTRETCHED GRID
!***********************************************************************

!**** *RADACT  - COMPUTES DISTRIBUTION OF AEROSOLS AND OZONE

!     PURPOSE.
!     --------

!**   INTERFACE.
!     ----------
!        CALL *RADACT* FROM *RADINT*

!        EXPLICIT ARGUMENTS :
!        --------------------
!     ==== INPUTS ===
!     ==== OUTPUTS ===

!        IMPLICIT ARGUMENTS :   NONE
!        --------------------

!     METHOD.
!     -------

!     EXTERNALS.
!     ----------

!          NONE

!     REFERENCE.
!     ----------

!        SEE RADIATION'S PART OF THE MODEL'S DOCUMENTATION AND
!        ECMWF RESEARCH DEPARTMENT DOCUMENTATION OF THE "I.F.S"

!     AUTHOR.
!     -------
!      J.-J. MORCRETTE  E.C.M.W.F.    91/03/15

!     MODIFICATIONS.
!     --------------
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      JJMorcrette 20080206 revised use of GISS history of volcanic aerosols
!      JJMorcrette 20080325 RH effect on new SO4 aerosol
!      Hans Hersbach: 20110401 CMIP5-recommended SO4 tropospheric aerosols
!      JJMorcrette&ABozzo 2014/2015: changes to include MACC-derived
!                                    aerosol climatology
!      M. Leutbecher & S.-J. Lock (Jan 2016) Introduced SPP scheme (LSPP)
!      A Bozzo Jan 2018: introduced 3D aerosol climatology from CAMS
!      Bechtold/Hogan 2020: corrected bug in vert interp of input 3D clim aerosol
!      M Leutbecher (Oct 2020) SPP abstraction
!-----------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM, JPRB, JPRD
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST   , ONLY : RPI,RG
USE YOMRIP   , ONLY : TRIP
USE YOEAERD  , ONLY : TEAERD
USE YOERAD   , ONLY : TERAD
USE YOEAERCLI, ONLY : NAERADJDU, RDUMULF, RWGHTDU1, RWGHTDU2, RWGHTDU3
USE YOEAEROP , ONLY : ALF_SU
USE YOEAERSNK, ONLY : TEAERSNK
USE SPP_MOD  , ONLY : TSPP_CONFIG
USE SPP_GEN_MOD, ONLY : SPP_PERT
USE REGLATLON_FIELD_MIX,ONLY : INTPOL_REGLATLON

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(TEAERD)      ,INTENT(INOUT) :: YDEAERD
TYPE(TEAERSNK)    ,INTENT(INOUT) :: YDEAERSNK
TYPE(TERAD)       ,INTENT(INOUT) :: YDERAD
TYPE(TRIP)        ,INTENT(INOUT) :: YDRIP
TYPE(TSPP_CONFIG) ,INTENT(IN)    :: YDSPP_CONFIG
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDLONP2 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KRINT 
INTEGER(KIND=JPIM),INTENT(IN)    :: KSHIFT 
INTEGER(KIND=JPIM),INTENT(IN)    :: KCF 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRS(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGELAM(KLON) 
REAL(KIND=JPRD)   ,INTENT(IN)    :: PSIN(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLON(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSLON(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTH(KDLONP2,KLEV+1)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQ(KDLONP2,KLEV), PQS(KDLONP2,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PECPO3(KDLONP2,KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PAER(KDLON,6,KLEV) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PAERO(KDLON,KLEV,YDERAD%NMCVAR)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: POZON(KDLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN),OPTIONAL    :: PPERT(KLON, YDSPP_CONFIG%SM%NRFTOTAL_RADGRID)   !SPP: 2D random pattern fields

!     -----------------------------------------------------------------

INTEGER(KIND=JPIM) :: IINLA1(KDLON), IINLA2(KDLON)
INTEGER(KIND=JPIM) :: IINLO1(KDLON), IINLO2(KDLON)

INTEGER(KIND=JPIM) :: KLEV_AER
PARAMETER (KLEV_AER=60)

REAL(KIND=JPRB) :: ZAED  (KDLON), ZAEL  (KDLON), ZAES  (KDLON), ZAEU  (KDLON)
REAL(KIND=JPRB) :: ZAEQDN(KDLON), ZAEQDO(KDLON), ZAEQLN(KDLON), ZAEQLO(KDLON)
REAL(KIND=JPRB) :: ZAEQSN(KDLON), ZAEQSO(KDLON), ZAEQUN(KDLON), ZAEQUO(KDLON)
REAL(KIND=JPRB) :: ZSO4SN(KDLON), ZSO4SO(KDLON)

REAL(KIND=JPRB) :: ZAERBC(KDLON), ZAEROR(KDLON), ZAERSD(KDLON)
REAL(KIND=JPRB) :: ZAERSS(KDLON), ZAERSU(KDLON), ZAERVO(KDLON)

!-- related to CAMS-derived aerosol climatology

REAL(KIND=JPRB) :: ZAERBCA3D(KDLON,KLEV_AER), ZAERBCB3D(KDLON,KLEV_AER)
REAL(KIND=JPRB) :: ZAERORA3D(KDLON,KLEV_AER), ZAERORB3D(KDLON,KLEV_AER)
REAL(KIND=JPRB) :: ZAERSDA3D(KDLON,KLEV_AER), ZAERSDB3D(KDLON,KLEV_AER), ZAERSDC3D(KDLON,KLEV_AER)
REAL(KIND=JPRB) :: ZAERSSA3D(KDLON,KLEV_AER), ZAERSSB3D(KDLON,KLEV_AER), ZAERSSC3D(KDLON,KLEV_AER)
REAL(KIND=JPRB) :: ZAERSUA3D(KDLON,KLEV_AER), ZREF_AER_PR(KDLON,0:KLEV_AER), ZREF_AER_DPR(KDLON,KLEV_AER)

REAL(KIND=JPRB) :: ZAERBCA3D_VI_input(KDLON,0:KLEV_AER),ZAERBCB3D_VI_input(KDLON,0:KLEV_AER)
REAL(KIND=JPRB) :: ZAERORA3D_VI_input(KDLON,0:KLEV_AER),ZAERORB3D_VI_input(KDLON,0:KLEV_AER)
REAL(KIND=JPRB) :: ZAERSDA3D_VI_input(KDLON,0:KLEV_AER),ZAERSDB3D_VI_input(KDLON,0:KLEV_AER),ZAERSDC3D_VI_input(KDLON,0:KLEV_AER)
REAL(KIND=JPRB) :: ZAERSSA3D_VI_input(KDLON,0:KLEV_AER),ZAERSSB3D_VI_input(KDLON,0:KLEV_AER),ZAERSSC3D_VI_input(KDLON,0:KLEV_AER)
REAL(KIND=JPRB) :: ZAERSUA3D_VI_input(KDLON,0:KLEV_AER)

REAL(KIND=JPRB) :: ZAERBCA3D_VI(KDLON,0:KLEV),ZAERBCB3D_VI(KDLON,0:KLEV)
REAL(KIND=JPRB) :: ZAERORA3D_VI(KDLON,0:KLEV),ZAERORB3D_VI(KDLON,0:KLEV)
REAL(KIND=JPRB) :: ZAERSDA3D_VI(KDLON,0:KLEV),ZAERSDB3D_VI(KDLON,0:KLEV),ZAERSDC3D_VI(KDLON,0:KLEV)
REAL(KIND=JPRB) :: ZAERSSA3D_VI(KDLON,0:KLEV),ZAERSSB3D_VI(KDLON,0:KLEV),ZAERSSC3D_VI(KDLON,0:KLEV)
REAL(KIND=JPRB) :: ZAERSUA3D_VI(KDLON,0:KLEV)


REAL(KIND=JPRB) :: ZAERBCA(KDLON), ZAERBCB(KDLON)
REAL(KIND=JPRB) :: ZAERORA(KDLON), ZAERORB(KDLON)
REAL(KIND=JPRB) :: ZAERSDA(KDLON), ZAERSDB(KDLON), ZAERSDC(KDLON)
REAL(KIND=JPRB) :: ZAERSSA(KDLON), ZAERSSB(KDLON), ZAERSSC(KDLON)
REAL(KIND=JPRB) :: ZAERSUA(KDLON)

REAL(KIND=JPRB) :: ZAERS1O(KDLON), ZAERS2O(KDLON), ZAERS3O(KDLON)
REAL(KIND=JPRB) :: ZAERD1O(KDLON), ZAERD2O(KDLON), ZAERD3O(KDLON)
REAL(KIND=JPRB) :: ZAERO1O(KDLON), ZAERO2O(KDLON)
REAL(KIND=JPRB) :: ZAERB1O(KDLON), ZAERB2O(KDLON)
REAL(KIND=JPRB) :: ZAERSUO(KDLON)
REAL(KIND=JPRB) :: ZAERS1N(KDLON), ZAERS2N(KDLON), ZAERS3N(KDLON)
REAL(KIND=JPRB) :: ZAERD1N(KDLON), ZAERD2N(KDLON), ZAERD3N(KDLON)
REAL(KIND=JPRB) :: ZAERO1N(KDLON), ZAERO2N(KDLON)
REAL(KIND=JPRB) :: ZAERB1N(KDLON), ZAERB2N(KDLON)
REAL(KIND=JPRB) :: ZAERSUN(KDLON)

REAL(KIND=JPRB) :: ZAERBC1A, ZAERBC1B, ZAERBC2A, ZAERBC2B
REAL(KIND=JPRB) :: ZAEROR1A, ZAEROR1B, ZAEROR2A, ZAEROR2B
REAL(KIND=JPRB) :: ZAERSD1A, ZAERSD1B, ZAERSD2A, ZAERSD2B, ZAERSD3A, ZAERSD3B
REAL(KIND=JPRB) :: ZAERSS1A, ZAERSS1B, ZAERSS2A, ZAERSS2B, ZAERSS3A, ZAERSS3B
REAL(KIND=JPRB) :: ZAERSU1A, ZAERSU1B
REAL(KIND=JPRB) :: ZREF_AER_PRA, ZREF_AER_PRB, ZREF_AER_DPRA, ZREF_AER_DPRB
REAL(KIND=JPRB) :: ZAERSDT

!--

REAL(KIND=JPRB) :: ZAETRN(KDLON), ZAETRO(KDLON)

REAL(KIND=JPRB) :: ZPRS(KLON,0:KLEV)
REAL(KIND=JPRD) :: ZALP(66)
REAL(KIND=JPRB) :: ZDPN(KDLON)  , ZDPO(KDLON)
REAL(KIND=JPRB) :: ZFAED(21)    , ZFAEL(21)    , ZFAES(21)    , ZFAEU(21)
REAL(KIND=JPRB) :: ZFOZQ(11)    , ZFOZH(11)
REAL(KIND=JPRB) :: ZGRTH(KDLON)
REAL(KIND=JPRB) :: ZLON(KDLON)  , ZLONR(360)    , ZNLO1(KDLON) , ZNLO2(KDLON)

REAL(KIND=JPRB) :: ZOZH (KDLON) , ZOZQ (KDLON)
REAL(KIND=JPRB) :: ZQOFN(KDLON) , ZQOFO(KDLON)
REAL(KIND=JPRB) :: ZSILAT(KDLON), ZSINR(181), ZSTRDEP(KDLON)
REAL(KIND=JPRB) :: ZRH(KDLON)
INTEGER(KIND=JPIM) :: IRH(KDLON)

INTEGER(KIND=JPIM) :: IL, IMM, IMNC, IMNS, INLA, INLA1, INLA2, INLO1, INLO2, &
 & ITOTPT, JAER, JK, JL, JLR, JMM, JNN, JTAB, JV, &
 & INLATR, INLONR, ITOT, IC, JC
!Local SPP array integers
INTEGER(KIND=JPIM) :: IPZHSVDAERO, IPDELTAAERO  

REAL(KIND=JPRB) :: ZAETR, ZAETRV, ZCOS1, ZCOS10, ZCOS2, ZCOS3, ZCOS4,&
 & ZCOS5, ZCOS6, ZCOS7, ZCOS8, ZCOS9, ZCPHN3, &
 & ZCPHO3, ZDPNMO, ZDP, ZINT, ZGRIDR, ZLATR, ZSDPN3, ZSDPO3
REAL(KIND=JPRD) :: ZSIN, ZSIN1, ZSIN10, ZSIN2, ZSIN3, ZSIN4, &
 & ZSIN5, ZSIN6, ZSIN7, ZSIN8, ZSIN9  
REAL(KIND=JPRB) :: ZSSIN
REAL(KIND=JPRB) :: ZAERBC1, ZAERBC2, ZAEROR1, ZAEROR2, ZAERSD1, ZAERSD2, &
 & ZAERSS1, ZAERSS2, ZAERSU1, ZAERSU2, ZDSO4S
REAL(KIND=JPRB) :: ZVDAEL, ZVDAES, ZVDAEU, ZVDAED
REAL(KIND=JPRB) :: ZVDAESU, ZVDAESS, ZVDAEDU, ZVDAEOM, ZVDAEBC
REAL(KIND=JPRB) :: ZXAERSU(KDLON), ZXAERSS(KDLON), ZXAEROR(KDLON), ZXAERBC(KDLON), ZXAERSD(KDLON)
REAL(KIND=JPRB), DIMENSION(KDLON) :: ZXAERSUA, ZXAERSSA, ZXAERSSB, ZXAERSSC, ZXAERSDA, ZXAERSDB, ZXAERSDC, &
     &                               ZXAERORA, ZXAERORB, ZXAERBCA, ZXAERBCB
!Local SPP fields
INTEGER(KIND=JPIM) :: IPN
TYPE(SPP_PERT)     :: PN1ZHS_VD, PN1DELTA
REAL(KIND=JPRB) :: ZRRVD(KDLON), ZRDELTA
!Local switches to activate SPP perturbations
LOGICAL :: LLPERT_ZHS_VDAERO, LLPERT_DELTA_AERO

REAL(KIND=JPRB) :: ZDLONR
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE


!     ------------------------------------------------------------------

#include "abor1.intfb.h"
#include "legtri.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('RADACT',0,ZHOOK_HANDLE)
ASSOCIATE(CVDAED=>YDEAERD%CVDAED, CVDAEL=>YDEAERD%CVDAEL, &
 & CVDAES=>YDEAERD%CVDAES, CVDAEU=>YDEAERD%CVDAEU, RAEDC=>YDEAERD%RAEDC, &
 & RAEDS=>YDEAERD%RAEDS, RAELC=>YDEAERD%RAELC, RAELS=>YDEAERD%RAELS, &
 & RAESC=>YDEAERD%RAESC, RAESS=>YDEAERD%RAESS, RAEUC=>YDEAERD%RAEUC, &
 & RAEUS=>YDEAERD%RAEUS, RCAEOPD=>YDEAERD%RCAEOPD, RCAEOPL=>YDEAERD%RCAEOPL, &
 & RCAEOPS=>YDEAERD%RCAEOPS, RCAEOPU=>YDEAERD%RCAEOPU, &
 & RCSTBGA=>YDEAERD%RCSTBGA, RCTRBGA=>YDEAERD%RCTRBGA, RCTRPT=>YDEAERD%RCTRPT, &
 & RCVOBGA=>YDEAERD%RCVOBGA, RRHTAB=>YDEAERSNK%RRHTAB, &
 & CVDAEBC=>YDERAD%CVDAEBC, CVDAEDU=>YDERAD%CVDAEDU, CVDAEOM=>YDERAD%CVDAEOM, &
 & CVDAESS=>YDERAD%CVDAESS, CVDAESU=>YDERAD%CVDAESU, &
 & LAERADJDU=>YDERAD%LAERADJDU, LESO4HIS=>YDERAD%LESO4HIS, &
 & LHVOLCA=>YDERAD%LHVOLCA, LNEWAER=>YDERAD%LNEWAER, &
 & LVOLCDAMP=>YDERAD%LVOLCDAMP, LVOLCSPEC=>YDERAD%LVOLCSPEC, &
 & NAERMACC=>YDERAD%NAERMACC, NMCLAT=>YDERAD%NMCLAT, NMCLON=>YDERAD%NMCLON, &
 & NMCVAR=>YDERAD%NMCVAR, NVOLCVERT=>YDERAD%NVOLCVERT, &
 & RVOLCSPEC=>YDERAD%RVOLCSPEC, STBKG=>YDERAD%STBKG, &
 & NSTADD=>YDRIP%NSTADD,LAER3D=>YDERAD%LAER3D)
!     ------------------------------------------------------------------

!*         1.     "NEW AEROSOL DISTRIBUTION" PARAMETERS COMPUTATIONS
!                 --------------------------------------------------

!*         1.1    VOLCANIC AEROSOL DISTRIBUTION PARAMETERS
!                 ----------------------------------------

!                 GISS CLIMATOLOGY, APPLIED TO SULPHATE AEROSOLS
!                 ----------------------------------------------

IF (LHVOLCA) THEN
  INLATR=46
  ZGRIDR=180._JPRB/(INLATR-1)
  DO JLR=1,INLATR
    ZLATR=90._JPRB-(JLR-1)*ZGRIDR
    ZSINR(JLR)=SIN(ZLATR*RPI/180._JPRB)
  ENDDO

  IL=KSHIFT
  DO JL=KIDIA,KFDIA,KRINT
    IL=IL+1
    INLA=0
    ZSILAT(IL)=-9999._JPRB
    ZSIN=PSIN(JL)
    DO JLR=1,INLATR-1
      IF (ZSIN <= ZSINR(JLR) .AND. ZSIN > ZSINR(JLR+1)) THEN
        INLA=JLR
        ZSILAT(IL)=(ZSIN-ZSINR(INLA))/(ZSINR(INLA+1)-ZSINR(INLA))
        ZAERVO(IL)=YDRIP%YREAERC_TEGEN%RTAEVO(INLA)+ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAEVO(INLA+1)-YDRIP%YREAERC_TEGEN%RTAEVO(INLA))
      ENDIF
    ENDDO
    IF (ZSIN <= ZSINR(INLATR-1) .AND. ZSIN >= ZSINR(INLATR))THEN
      INLA=INLATR
      ZSILAT(IL)=(ZSIN-ZSINR(INLA-1))/(ZSINR(INLA)-ZSINR(INLA-1))
      ZAERVO(IL)=YDRIP%YREAERC_TEGEN%RTAEVO(INLA-1)&
       & +ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAEVO(INLA)-YDRIP%YREAERC_TEGEN%RTAEVO(INLA-1))  
    ENDIF
    IF (INLA == 0) THEN
      CALL ABOR1(' Problem with lat. interpolation in radact!')
    ENDIF
    IF(LVOLCSPEC) THEN
      IF(ZSIN > 0.64_JPRB) THEN
        ZAERVO(IL)=RVOLCSPEC(1)
      ELSEIF(ZSIN > 0.34_JPRB) THEN
        ZSILAT(IL)=(ZSIN-0.34_JPRB)/(0.3_JPRB)
        ZAERVO(IL)=RVOLCSPEC(2)+ZSILAT(IL)*(RVOLCSPEC(1)-RVOLCSPEC(2))
      ELSEIF(ZSIN > -0.34_JPRB) THEN
        ZAERVO(IL)=RVOLCSPEC(2)
      ELSEIF(ZSIN > -0.64_JPRB) THEN
        ZSILAT(IL)=(-ZSIN-0.34_JPRB)/(0.3_JPRB)
        ZAERVO(IL)=RVOLCSPEC(2)+ZSILAT(IL)*(RVOLCSPEC(3)-RVOLCSPEC(2))
      ELSE
        ZAERVO(IL)=RVOLCSPEC(3)
      ENDIF
      IF(LVOLCDAMP) THEN
        ZAERVO(IL)=STBKG+(ZAERVO(IL)-STBKG)*EXP(-NSTADD/400.0_JPRB)
      ENDIF
    ENDIF
    ZDPO(IL)=PAPRS(JL,1)
    ZAETRO(IL)=1.0_JPRB
    ZSTRDEP(IL)=0.0_JPRB
  ENDDO


!-- define how thick the stratosphere is in pressure units
  DO JK=1,KLEV
    IL=KSHIFT
    IF (KCF == 0) THEN
      DO JL=KIDIA,KFDIA,KRINT
        IL=IL+1
        ZGRTH(IL)= PTH(JL,JK)/PTH(JL,JK+1)
      ENDDO
    ELSEIF (KCF == 1) THEN
      DO JL=KIDIA,KFDIA,KRINT
        IL=IL+1
        ZGRTH(IL)= PTH(IL,JK)/PTH(IL,JK+1)
      ENDDO
    ENDIF
    IL=KSHIFT
    DO JL=KIDIA,KFDIA,KRINT
      IL=IL+1
      ZDPN(IL)=PAPRS(JL,JK+1)
      IF (0.5_JPRB*(PAPRS(JL,JK+1)+PAPRS(JL,JK)) < 999._JPRB) THEN
        ZAETRN(IL)=1.0_JPRB
      ELSE
        ZAETRN(IL)=ZAETRO(IL)*(MIN(1.0_JPRB, ZGRTH(IL )))**RCTRPT
      ENDIF
      ZAETR=SQRT(ZAETRN(IL)*ZAETRO(IL))

      IF(NVOLCVERT==0) THEN
        ZAETRV=ZAETR
      ELSEIF(NVOLCVERT==1) THEN
! Use temperature profile, but no volcanic aerosol above 10hPa
        IF (0.5_JPRB*(PAPRS(JL,JK)+PAPRS(JL,JK+1)) < 999._JPRB) THEN
          ZAETRV=0.0_JPRB
        ELSE
          ZAETRV=ZAETR
        ENDIF
      ELSEIF(NVOLCVERT==2) THEN
! Use prognostic ozone to define lower edge of aerosol distribution
        IF (0.5_JPRB*(PAPRS(JL,JK)+PAPRS(JL,JK+1)) < 999._JPRB) THEN
          ZAETRV=0.0_JPRB
        ELSEIF(0.5_JPRB*(PAPRS(JL,JK)+PAPRS(JL,JK+1)) < 7000._JPRB) THEN
          ZAETRV=1.0_JPRB
        ELSEIF(PAPRS(JL,JK) > 40000._JPRB) THEN
          ZAETRV=0.0_JPRB
        ELSE
          IF(PECPO3(JL,JK) > 0.4E-6_JPRB) THEN
            ZAETRV=1.0_JPRB
          ELSEIF(PECPO3(JL,JK) > 0.2E-6_JPRB) THEN
            ZAETRV=(PECPO3(JL,JK)-0.2E-6_JPRB)/0.2E-6_JPRB
          ELSE
            ZAETRV=0.0_JPRB
          ENDIF
        ENDIF
      ENDIF

      ZDPNMO=ZDPN(IL)-ZDPO(IL)
      ZSTRDEP(IL)=ZSTRDEP(IL)+ZAETRV*ZDPNMO
    ENDDO
    IL=KSHIFT
    DO JL=KIDIA,KFDIA,KRINT
      IL = IL+1
      ZDPO(IL)  =ZDPN(IL)
      ZAETRO(IL)=ZAETRN(IL)
    ENDDO
  ENDDO
!-- 
  IL = KSHIFT
  DO JL=KIDIA,KFDIA,KRINT
    IL = IL+1
    ZAERVO(IL)=ZAERVO(IL)/ZSTRDEP(IL)
  ENDDO

!                 TANRE ET AL. CLIMATOLOGY 
!                 ------------------------

ELSE
  IL = KSHIFT
  DO JL=KIDIA,KFDIA,KRINT
    IL = IL+1
    ZAERVO(IL)=RCSTBGA
  ENDDO
ENDIF
ITOTPT=IL

!*         1.2    TROPOSPHERIC AEROSOL DISTRIBUTION PARAMETERS
!                 --------------------------------------------

!-- if LNEWAER Tegen aerosol climatology is always done

IF (LNEWAER) THEN

!* -- Tegen et al. 1997 aerosol climatology


!-- latitude       
  INLATR=46
  ZGRIDR=180._JPRB/(INLATR-1)
  DO JLR=1,INLATR
    ZLATR=90._JPRB-(JLR-1)*ZGRIDR
    ZSINR(JLR)=SIN(ZLATR*RPI/180._JPRB)
  ENDDO
  INLONR=72
  ZDLONR=2._JPRB*RPI/INLONR
  DO JLR=1,INLONR
    ZLONR(JLR)=(JLR-1)*ZDLONR
  ENDDO

  IL=KSHIFT
  DO JL=KIDIA,KFDIA,KRINT         
    IL=IL+1
    IINLA1(IL)=0
    IINLA2(IL)=0
    ZSILAT(IL)=-9999._JPRB
    ZSIN=PSIN(JL)
    DO JLR=1,INLATR-1
      IF (ZSIN <= ZSINR(JLR) .AND. ZSIN > ZSINR(JLR+1)) THEN
        INLA=JLR
        IINLA1(IL)=JLR
        IINLA2(IL)=JLR+1
        ZSILAT(IL)=(ZSIN-ZSINR(INLA))/(ZSINR(INLA+1)-ZSINR(INLA))
      ENDIF
    ENDDO
    IF (ZSIN <= ZSINR(INLATR-1) .AND. ZSIN >= ZSINR(INLATR))THEN
      INLA=INLATR
      IINLA1(IL)=INLATR-1
      IINLA2(IL)=INLATR
      ZSILAT(IL)=(ZSIN-ZSINR(INLA-1))/(ZSINR(INLA)-ZSINR(INLA-1))
    ENDIF    
    IF (INLA == 0) THEN 
      CALL ABOR1(' Problem with lat. interpolation in radact!')
    ENDIF
  ENDDO  

!-- longitude
  IL=KSHIFT
  DO JL=KIDIA,KFDIA,KRINT
    IL=IL+1
    IINLO1(IL)=0
    IINLO2(IL)=0
    ZLON(IL)=-9999.
    DO JLR=1,71
      IF (PGELAM(JL) < ZLONR(JLR+1) .AND. PGELAM(JL) >= ZLONR(JLR))&
         & THEN  
        IINLO1(IL)=JLR
        IINLO2(IL)=JLR+1
        ZNLO1(IL)=ZLONR(JLR)
        ZNLO2(IL)=ZLONR(JLR+1)
      ENDIF
    ENDDO      
    IF (PGELAM(JL) >= ZLONR(72)) THEN
      IINLO1(IL)=72
      IINLO2(IL)= 1
      ZNLO1(IL)=ZLONR(72)
!      ZNLO2(IL)=ZLONR(72)+2.*RPI
      ZNLO2(IL)=ZLONR(72)+ZDLONR
    ENDIF
  ENDDO  
 
  IL=KSHIFT
  DO JL=KIDIA,KFDIA,KRINT        
    IL=IL+1
    IF (IINLO1(IL) == 0 .OR. IINLO2(IL) == 0) THEN 
      CALL ABOR1(' Problem with long. interpolation in radact!')
    ENDIF
    ZLON(IL)=(PGELAM(JL)-ZNLO1(IL))/(ZNLO2(IL)-ZNLO1(IL))
    INLO1=IINLO1(IL)
    INLO2=IINLO2(IL)
    INLA1=IINLA1(IL)
    INLA2=IINLA2(IL)
    
    ZAERBC1=YDRIP%YREAERC_TEGEN%RTAEBC(INLO1,INLA1)&
     & +ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAEBC(INLO1,INLA2)-YDRIP%YREAERC_TEGEN%RTAEBC(INLO1,INLA1))    
    ZAERBC2=YDRIP%YREAERC_TEGEN%RTAEBC(INLO2,INLA1)&
     & +ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAEBC(INLO2,INLA2)-YDRIP%YREAERC_TEGEN%RTAEBC(INLO2,INLA1))    
    ZAERBC(IL)=ZAERBC1+ZLON(IL)*(ZAERBC2-ZAERBC1)
        
    ZAEROR1=YDRIP%YREAERC_TEGEN%RTAEOR(INLO1,INLA1)&
     & +ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAEOR(INLO1,INLA2)-YDRIP%YREAERC_TEGEN%RTAEOR(INLO1,INLA1))    
    ZAEROR2=YDRIP%YREAERC_TEGEN%RTAEOR(INLO2,INLA1)&
     & +ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAEOR(INLO2,INLA2)-YDRIP%YREAERC_TEGEN%RTAEOR(INLO2,INLA1))    
    ZAEROR(IL)=ZAEROR1+ZLON(IL)*(ZAEROR2-ZAEROR1)
        
    ZAERSD1=YDRIP%YREAERC_TEGEN%RTAESD(INLO1,INLA1)&
     & +ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAESD(INLO1,INLA2)-YDRIP%YREAERC_TEGEN%RTAESD(INLO1,INLA1))    
    ZAERSD2=YDRIP%YREAERC_TEGEN%RTAESD(INLO2,INLA1)&
     & +ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAESD(INLO2,INLA2)-YDRIP%YREAERC_TEGEN%RTAESD(INLO2,INLA1))    
    ZAERSD(IL)=ZAERSD1+ZLON(IL)*(ZAERSD2-ZAERSD1)
        
    ZAERSS1=YDRIP%YREAERC_TEGEN%RTAESS(INLO1,INLA1)&
     & +ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAESS(INLO1,INLA2)-YDRIP%YREAERC_TEGEN%RTAESS(INLO1,INLA1))    
    ZAERSS2=YDRIP%YREAERC_TEGEN%RTAESS(INLO2,INLA1)&
     & +ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAESS(INLO2,INLA2)-YDRIP%YREAERC_TEGEN%RTAESS(INLO2,INLA1))    
    ZAERSS(IL)=ZAERSS1+ZLON(IL)*(ZAERSS2-ZAERSS1)
        
    ZAERSU1=YDRIP%YREAERC_TEGEN%RTAESU(INLO1,INLA1)&
     & +ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAESU(INLO1,INLA2)-YDRIP%YREAERC_TEGEN%RTAESU(INLO1,INLA1))    
    ZAERSU2=YDRIP%YREAERC_TEGEN%RTAESU(INLO2,INLA1)&
     & +ZSILAT(IL)*(YDRIP%YREAERC_TEGEN%RTAESU(INLO2,INLA2)-YDRIP%YREAERC_TEGEN%RTAESU(INLO2,INLA1))    
    ZAERSU(IL)=ZAERSU1+ZLON(IL)*(ZAERSU2-ZAERSU1)
          
  ENDDO       
ENDIF



!- replacing TEGEN climatology by MACC-derived mmr climatology in the 
!  troposphere

! AB2014 attention here with the initialization!!The KSHIFT parameter has to
! be correctly applied otherwise the KPROMA slices are not correctly 
! filled and this will overwrite values


!THIS IS RIGHT
IL=KSHIFT
DO JL=KIDIA,KFDIA,KRINT         
   IL=IL+1
   DO JV=1,NMCVAR
      DO JK=1,KLEV
      PAERO(IL,JK,JV)=0._JPRB
      ENDDO
   ENDDO
ENDDO

IF (LNEWAER .AND. NAERMACC == 1) THEN

!* -- MACC-derived aerosol climatology

!-- latitude       
  INLATR=NMCLAT
  ZGRIDR=180._JPRB/(INLATR-1)
  DO JLR=1,INLATR
    ZLATR=90._JPRB-(JLR-1)*ZGRIDR
    ZSINR(JLR)=SIN(ZLATR*RPI/180._JPRB)
  ENDDO
  INLONR=NMCLON
  ZDLONR=2._JPRB*RPI/INLONR
  DO JLR=1,INLONR
    ZLONR(JLR)=(JLR-1)*ZDLONR
  ENDDO

  IL=KSHIFT
  DO JL=KIDIA,KFDIA,KRINT         
    IL=IL+1
    IINLA1(IL)=0
    IINLA2(IL)=0
    ZSILAT(IL)=-9999._JPRB
    ZSIN=PSIN(JL)
    DO JLR=1,INLATR-1
      IF (ZSIN <= ZSINR(JLR) .AND. ZSIN > ZSINR(JLR+1)) THEN
        INLA=JLR
        IINLA1(IL)=JLR
        IINLA2(IL)=JLR+1
        ZSILAT(IL)=(ZSIN-ZSINR(INLA))/(ZSINR(INLA+1)-ZSINR(INLA))
      ENDIF
    ENDDO
    IF (ZSIN <= ZSINR(INLATR-1) .AND. ZSIN >= ZSINR(INLATR))THEN
      INLA=INLATR
      IINLA1(IL)=INLATR-1
      IINLA2(IL)=INLATR
      ZSILAT(IL)=(ZSIN-ZSINR(INLA-1))/(ZSINR(INLA)-ZSINR(INLA-1))
    ENDIF    
    IF (INLA == 0) THEN 
      CALL ABOR1(' Problem with lat. interpolation in radact!')
    ENDIF
   
  ENDDO  

!-- longitude
  IL=KSHIFT
  DO JL=KIDIA,KFDIA,KRINT
    IL=IL+1
    IINLO1(IL)=0
    IINLO2(IL)=0
    ZLON(IL)=-9999.
    DO JLR=1,NMCLON-1
      IF (PGELAM(JL) < ZLONR(JLR+1) .AND. PGELAM(JL) >= ZLONR(JLR))&
         & THEN  
        IINLO1(IL)=JLR
        IINLO2(IL)=JLR+1
        ZNLO1(IL)=ZLONR(JLR)
        ZNLO2(IL)=ZLONR(JLR+1)
      ENDIF
    ENDDO      
    IF (PGELAM(JL) >= ZLONR(NMCLON)) THEN
      IINLO1(IL)=NMCLON
      IINLO2(IL)= 1
      ZNLO1(IL)=ZLONR(NMCLON)
!      ZNLO2(IL)=ZLONR(NMCLON)+2.*RPI
      ZNLO2(IL)=ZLONR(NMCLON)+ZDLONR
    ENDIF
  ENDDO  
 
  IL=KSHIFT
  DO JL=KIDIA,KFDIA,KRINT        
    IL=IL+1
    IF (IINLO1(IL) == 0 .OR. IINLO2(IL) == 0) THEN 
      CALL ABOR1(' Problem with long. interpolation in radact!')
    ENDIF
    ZLON(IL)=(PGELAM(JL)-ZNLO1(IL))/(ZNLO2(IL)-ZNLO1(IL))
    INLO1=IINLO1(IL)
    INLO2=IINLO2(IL)
    INLA1=IINLA1(IL)
    INLA2=IINLA2(IL)

    IF (.NOT.LAER3D) THEN


!- BC hydrophilic, hydrophobic
    
       ZAERBC1A=YDRIP%YREAERC_MACC%RMAEBC1(INLO1,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEBC1(INLO1,INLA2)-YDRIP%YREAERC_MACC%RMAEBC1(INLO1,INLA1))    
       ZAERBC1B=YDRIP%YREAERC_MACC%RMAEBC1(INLO2,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEBC1(INLO2,INLA2)-YDRIP%YREAERC_MACC%RMAEBC1(INLO2,INLA1))    
       ZAERBCA(IL)=ZAERBC1A+ZLON(IL)*(ZAERBC1B-ZAERBC1A)
       
       ZAERBC2A=YDRIP%YREAERC_MACC%RMAEBC2(INLO1,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEBC2(INLO1,INLA2)-YDRIP%YREAERC_MACC%RMAEBC2(INLO1,INLA1))    
       ZAERBC2B=YDRIP%YREAERC_MACC%RMAEBC2(INLO2,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEBC2(INLO2,INLA2)-YDRIP%YREAERC_MACC%RMAEBC2(INLO2,INLA1))    
       ZAERBCB(IL)=ZAERBC2A+ZLON(IL)*(ZAERBC2B-ZAERBC2A)
       
       !- OC hydrophilic, hydrophobic
       
       ZAEROR1A=YDRIP%YREAERC_MACC%RMAEOR1(INLO1,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEOR1(INLO1,INLA2)-YDRIP%YREAERC_MACC%RMAEOR1(INLO1,INLA1))    
       ZAEROR1B=YDRIP%YREAERC_MACC%RMAEOR1(INLO2,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEOR1(INLO2,INLA2)-YDRIP%YREAERC_MACC%RMAEOR1(INLO2,INLA1))    
       ZAERORA(IL)=ZAEROR1A+ZLON(IL)*(ZAEROR1B-ZAEROR1A)
       
       ZAEROR2A=YDRIP%YREAERC_MACC%RMAEOR2(INLO1,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEOR2(INLO1,INLA2)-YDRIP%YREAERC_MACC%RMAEOR2(INLO1,INLA1))    
       ZAEROR2B=YDRIP%YREAERC_MACC%RMAEOR2(INLO2,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEOR2(INLO2,INLA2)-YDRIP%YREAERC_MACC%RMAEOR2(INLO2,INLA1))    
       ZAERORB(IL)=ZAEROR2A+ZLON(IL)*(ZAEROR2B-ZAEROR2A)
       
       !- SD 3 bins
       
       ZAERSD1A=YDRIP%YREAERC_MACC%RMAESD1(INLO1,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD1(INLO1,INLA2)-YDRIP%YREAERC_MACC%RMAESD1(INLO1,INLA1))    
       ZAERSD1B=YDRIP%YREAERC_MACC%RMAESD1(INLO2,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD1(INLO2,INLA2)-YDRIP%YREAERC_MACC%RMAESD1(INLO2,INLA1))    
       ZAERSDA(IL)=ZAERSD1A+ZLON(IL)*(ZAERSD1B-ZAERSD1A)
       
       ZAERSD2A=YDRIP%YREAERC_MACC%RMAESD2(INLO1,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD2(INLO1,INLA2)-YDRIP%YREAERC_MACC%RMAESD2(INLO1,INLA1))    
       ZAERSD2B=YDRIP%YREAERC_MACC%RMAESD2(INLO2,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD2(INLO2,INLA2)-YDRIP%YREAERC_MACC%RMAESD2(INLO2,INLA1))    
       ZAERSDB(IL)=ZAERSD2A+ZLON(IL)*(ZAERSD2B-ZAERSD2A)
       
       ZAERSD3A=YDRIP%YREAERC_MACC%RMAESD3(INLO1,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD3(INLO1,INLA2)-YDRIP%YREAERC_MACC%RMAESD3(INLO1,INLA1))    
       ZAERSD3B=YDRIP%YREAERC_MACC%RMAESD3(INLO2,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD3(INLO2,INLA2)-YDRIP%YREAERC_MACC%RMAESD3(INLO2,INLA1))    
       ZAERSDC(IL)=ZAERSD3A+ZLON(IL)*(ZAERSD3B-ZAERSD3A)
       
       IF (LAERADJDU) THEN
          ZAERSDT=ZAERSDA(IL)+ZAERSDB(IL)+ZAERSDC(IL)
          IF (NAERADJDU == 1) THEN
             ZAERSDT=ZAERSDT*RDUMULF
          ENDIF
          ZAERSDA(IL)=RWGHTDU1*ZAERSDT
          ZAERSDB(IL)=RWGHTDU2*ZAERSDT
          ZAERSDC(IL)=RWGHTDU3*ZAERSDT
       ENDIF
       
       !- SS 3 bins
       
       ZAERSS1A=YDRIP%YREAERC_MACC%RMAESS1(INLO1,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS1(INLO1,INLA2)-YDRIP%YREAERC_MACC%RMAESS1(INLO1,INLA1))    
       ZAERSS1B=YDRIP%YREAERC_MACC%RMAESS1(INLO2,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS1(INLO2,INLA2)-YDRIP%YREAERC_MACC%RMAESS1(INLO2,INLA1))    
       ZAERSSA(IL)=ZAERSS1A+ZLON(IL)*(ZAERSS1B-ZAERSS1A)
       
       ZAERSS2A=YDRIP%YREAERC_MACC%RMAESS2(INLO1,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS2(INLO1,INLA2)-YDRIP%YREAERC_MACC%RMAESS2(INLO1,INLA1))    
       ZAERSS2B=YDRIP%YREAERC_MACC%RMAESS2(INLO2,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS2(INLO2,INLA2)-YDRIP%YREAERC_MACC%RMAESS2(INLO2,INLA1))    
       ZAERSSB(IL)=ZAERSS2A+ZLON(IL)*(ZAERSS2B-ZAERSS2A)
       
       ZAERSS3A=YDRIP%YREAERC_MACC%RMAESS3(INLO1,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS3(INLO1,INLA2)-YDRIP%YREAERC_MACC%RMAESS3(INLO1,INLA1))    
       ZAERSS3B=YDRIP%YREAERC_MACC%RMAESS3(INLO2,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS3(INLO2,INLA2)-YDRIP%YREAERC_MACC%RMAESS3(INLO2,INLA1))    
       ZAERSSC(IL)=ZAERSS3A+ZLON(IL)*(ZAERSS3B-ZAERSS3A)
       
       !- SO4
       
       ZAERSU1A=YDRIP%YREAERC_MACC%RMAESU1(INLO1,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESU1(INLO1,INLA2)-YDRIP%YREAERC_MACC%RMAESU1(INLO1,INLA1))    
       ZAERSU1B=YDRIP%YREAERC_MACC%RMAESU1(INLO2,INLA1)&
            & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESU1(INLO2,INLA2)-YDRIP%YREAERC_MACC%RMAESU1(INLO2,INLA1))    
       ZAERSUA(IL)=ZAERSU1A+ZLON(IL)*(ZAERSU1B-ZAERSU1A)
       
       
    ELSE !LAER3D true
       DO JK=1,KLEV_AER
          
          !- reference pressure (Pa)
          ZREF_AER_PRA=YDRIP%YREAERC_MACC%REF_AER_PRS(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%REF_AER_PRS(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%REF_AER_PRS(INLO1,INLA1,JK))
          ZREF_AER_PRB=YDRIP%YREAERC_MACC%REF_AER_PRS(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%REF_AER_PRS(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%REF_AER_PRS(INLO2,INLA1,JK))
          ZREF_AER_PR(IL,JK)=ZREF_AER_PRA+ZLON(IL)*(ZREF_AER_PRB-ZREF_AER_PRA)
          !- reference delta-pressure (Pa)
          ZREF_AER_DPRA=YDRIP%YREAERC_MACC%REF_AER_DPRS(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%REF_AER_DPRS(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%REF_AER_DPRS(INLO1,INLA1,JK))
          ZREF_AER_DPRB=YDRIP%YREAERC_MACC%REF_AER_DPRS(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%REF_AER_DPRS(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%REF_AER_DPRS(INLO2,INLA1,JK))
          ZREF_AER_DPR(IL,JK)=ZREF_AER_DPRA+ZLON(IL)*(ZREF_AER_DPRB-ZREF_AER_DPRA)
          
          !- BC hydrophilic, hydrophobic
          
          
          ZAERBC1A=YDRIP%YREAERC_MACC%RMAEBC13D(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEBC13D(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%RMAEBC13D(INLO1,INLA1,JK))    
          ZAERBC1B=YDRIP%YREAERC_MACC%RMAEBC13D(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEBC13D(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%RMAEBC13D(INLO2,INLA1,JK))    
          ZAERBCA3D(IL,JK)=ZAERBC1A+ZLON(IL)*(ZAERBC1B-ZAERBC1A)
          
          ZAERBC2A=YDRIP%YREAERC_MACC%RMAEBC23D(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEBC23D(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%RMAEBC23D(INLO1,INLA1,JK))    
          ZAERBC2B=YDRIP%YREAERC_MACC%RMAEBC23D(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEBC23D(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%RMAEBC23D(INLO2,INLA1,JK))    
          ZAERBCB3D(IL,JK)=ZAERBC2A+ZLON(IL)*(ZAERBC2B-ZAERBC2A)
          
          !- OC hydrophilic, hydrophobic
          
          ZAEROR1A=YDRIP%YREAERC_MACC%RMAEOR13D(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEOR13D(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%RMAEOR13D(INLO1,INLA1,JK))    
          ZAEROR1B=YDRIP%YREAERC_MACC%RMAEOR13D(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEOR13D(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%RMAEOR13D(INLO2,INLA1,JK))    
          ZAERORA3D(IL,JK)=ZAEROR1A+ZLON(IL)*(ZAEROR1B-ZAEROR1A)
          
          ZAEROR2A=YDRIP%YREAERC_MACC%RMAEOR23D(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEOR23D(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%RMAEOR23D(INLO1,INLA1,JK))    
          ZAEROR2B=YDRIP%YREAERC_MACC%RMAEOR23D(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAEOR23D(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%RMAEOR23D(INLO2,INLA1,JK))    
          ZAERORB3D(IL,JK)=ZAEROR2A+ZLON(IL)*(ZAEROR2B-ZAEROR2A)
          
          !- SD 3 bins
          
          ZAERSD1A=YDRIP%YREAERC_MACC%RMAESD13D(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD13D(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESD13D(INLO1,INLA1,JK))    
          ZAERSD1B=YDRIP%YREAERC_MACC%RMAESD13D(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD13D(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESD13D(INLO2,INLA1,JK))    
          ZAERSDA3D(IL,JK)=ZAERSD1A+ZLON(IL)*(ZAERSD1B-ZAERSD1A)
          
          ZAERSD2A=YDRIP%YREAERC_MACC%RMAESD23D(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD23D(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESD23D(INLO1,INLA1,JK))    
          ZAERSD2B=YDRIP%YREAERC_MACC%RMAESD23D(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD23D(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESD23D(INLO2,INLA1,JK))    
          ZAERSDB3D(IL,JK)=ZAERSD2A+ZLON(IL)*(ZAERSD2B-ZAERSD2A)
          
          ZAERSD3A=YDRIP%YREAERC_MACC%RMAESD33D(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD33D(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESD33D(INLO1,INLA1,JK))    
          ZAERSD3B=YDRIP%YREAERC_MACC%RMAESD33D(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESD33D(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESD33D(INLO2,INLA1,JK))    
          ZAERSDC3D(IL,JK)=ZAERSD3A+ZLON(IL)*(ZAERSD3B-ZAERSD3A)
          
          
          !- SS 3 bins
          
          ZAERSS1A=YDRIP%YREAERC_MACC%RMAESS13D(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS13D(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESS13D(INLO1,INLA1,JK))    
          ZAERSS1B=YDRIP%YREAERC_MACC%RMAESS13D(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS13D(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESS13D(INLO2,INLA1,JK))    
          ZAERSSA3D(IL,JK)=ZAERSS1A+ZLON(IL)*(ZAERSS1B-ZAERSS1A)
          
          ZAERSS2A=YDRIP%YREAERC_MACC%RMAESS23D(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS23D(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESS23D(INLO1,INLA1,JK))    
          ZAERSS2B=YDRIP%YREAERC_MACC%RMAESS23D(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS23D(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESS23D(INLO2,INLA1,JK))    
          ZAERSSB3D(IL,JK)=ZAERSS2A+ZLON(IL)*(ZAERSS2B-ZAERSS2A)
          
          ZAERSS3A=YDRIP%YREAERC_MACC%RMAESS33D(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS33D(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESS33D(INLO1,INLA1,JK))    
          ZAERSS3B=YDRIP%YREAERC_MACC%RMAESS33D(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESS33D(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESS33D(INLO2,INLA1,JK))    
          ZAERSSC3D(IL,JK)=ZAERSS3A+ZLON(IL)*(ZAERSS3B-ZAERSS3A)
          
          !- SO4
          
          ZAERSU1A=YDRIP%YREAERC_MACC%RMAESU13D(INLO1,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESU13D(INLO1,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESU13D(INLO1,INLA1,JK))    
          ZAERSU1B=YDRIP%YREAERC_MACC%RMAESU13D(INLO2,INLA1,JK) &
               & +ZSILAT(IL)*(YDRIP%YREAERC_MACC%RMAESU13D(INLO2,INLA2,JK)-YDRIP%YREAERC_MACC%RMAESU13D(INLO2,INLA1,JK))    
          ZAERSUA3D(IL,JK)=ZAERSU1A+ZLON(IL)*(ZAERSU1B-ZAERSU1A)
          
       ENDDO
    ENDIF !LAER3D
          
 ENDDO
  
ENDIF



!*         1.3    TROPOSPHERIC SULPHATE AEROSOL DISTRIBUTION PARAMETERS
!                 -----------------------------------------------------

IF (LNEWAER .AND. LESO4HIS) THEN

  IL=KSHIFT
  DO JL=KIDIA,KFDIA,KRINT        
    IL=IL+1
    ZSSIN = PSIN(JL)
    CALL INTPOL_REGLATLON(ZAERSU(IL),YDRIP%RAERSO4,PSIN=ZSSIN,PLON=(180_JPRB/RPI)*PGELAM(JL))
  ENDDO       
ENDIF

!     ------------------------------------------------------------------   

!*       2.     OZONE
!               -----

ZSIN=PSIN(KIDIA)

!*       2.1     CALL TO LEGTRI.
!                ---------------
!***
CALL LEGTRI (ZSIN,6,66,ZALP)
!***

!*       2.2     LEGENDRE TRANSFORM FOR OZONE.
!                -----------------------------

DO JMM=1,11
  ZFOZQ(JMM)=0.0_JPRB
  ZFOZH(JMM)=0.0_JPRB
ENDDO
IMM=0
IMNC=0
IMNS=0
DO JMM=1,6
  IMM=IMM+1
  DO JNN=JMM,6
    IMNC=IMNC+1
    ZFOZQ(IMM)=ZFOZQ(IMM)+ZALP(IMNC)*YDRIP%YREOZOC%COZQC(IMNC)
    ZFOZH(IMM)=ZFOZH(IMM)+ZALP(IMNC)*YDRIP%YREOZOC%COZHC(IMNC)
  ENDDO
  IF(JMM /= 1) THEN
    IMM=IMM+1
    DO JNN=JMM,6
      IMNS=IMNS+1
      ZFOZQ(IMM)=ZFOZQ(IMM)+ZALP(IMNS+6)*YDRIP%YREOZOC%COZQS(IMNS)
      ZFOZH(IMM)=ZFOZH(IMM)+ZALP(IMNS+6)*YDRIP%YREOZOC%COZHS(IMNS)
    ENDDO
  ENDIF
ENDDO

!*       2.3     FOURIER TRANSFORM FOR OZONE.
!                ----------------------------

IL=KSHIFT
DO JL=KIDIA,KFDIA,KRINT
  IL=IL+1
  ZCOS1=PCLON(JL)
  ZSIN1=PSLON(JL)
  ZCOS2=ZCOS1*ZCOS1-ZSIN1*ZSIN1
  ZSIN2=ZSIN1*ZCOS1+ZCOS1*ZSIN1
  ZCOS3=ZCOS2*ZCOS1-ZSIN2*ZSIN1
  ZSIN3=ZSIN2*ZCOS1+ZCOS2*ZSIN1
  ZCOS4=ZCOS3*ZCOS1-ZSIN3*ZSIN1
  ZSIN4=ZSIN3*ZCOS1+ZCOS3*ZSIN1
  ZCOS5=ZCOS4*ZCOS1-ZSIN4*ZSIN1
  ZSIN5=ZSIN4*ZCOS1+ZCOS4*ZSIN1
  ZOZQ(IL)=&
   & ZFOZQ(1)+2.0_JPRB*(ZFOZQ(2)*ZCOS1+ZFOZQ(3)*ZSIN1+ZFOZQ(4)*ZCOS2&
   & +ZFOZQ(5)*ZSIN2+ZFOZQ(6)*ZCOS3+ZFOZQ(7)*ZSIN3+ZFOZQ(8)&
   & *ZCOS4+ZFOZQ(9)*ZSIN4+ZFOZQ(10)*ZCOS5+ZFOZQ(11)*ZSIN5)  
  ZOZH(IL)=&
   & ZFOZH(1)+2.0_JPRB*(ZFOZH(2)*ZCOS1+ZFOZH(3)*ZSIN1+ZFOZH(4)*ZCOS2&
   & +ZFOZH(5)*ZSIN2+ZFOZH(6)*ZCOS3+ZFOZH(7)*ZSIN3+ZFOZH(8)&
   & *ZCOS4+ZFOZH(9)*ZSIN4+ZFOZH(10)*ZCOS5+ZFOZH(11)*ZSIN5)  
  ZOZH(IL)=SQRT(ZOZH(IL))**3
ENDDO

!     ------------------------------------------------------------------

!       3.     AEROSOLS
!              --------
!***
!       3.1     CALL TO LEGTRI

!***
CALL LEGTRI (ZSIN,11,66,ZALP)
!***

!       3.2     LEGENDRE TRANSFORM FOR AEROSOLS
!               -------------------------------

DO JMM=1,21
  ZFAES(JMM) = 0.0_JPRB
  ZFAEL(JMM) = 0.0_JPRB
  ZFAEU(JMM) = 0.0_JPRB
  ZFAED(JMM) = 0.0_JPRB
ENDDO
IMM  = 0
IMNC = 0
IMNS = 0
DO JMM=1,11
  IMM  = IMM+1
  DO JNN=JMM,11
    IMNC = IMNC+1
    ZFAES(IMM) = ZFAES(IMM)+ZALP(IMNC)*RAESC(IMNC)
    ZFAEL(IMM) = ZFAEL(IMM)+ZALP(IMNC)*RAELC(IMNC)
    ZFAEU(IMM) = ZFAEU(IMM)+ZALP(IMNC)*RAEUC(IMNC)
    ZFAED(IMM) = ZFAED(IMM)+ZALP(IMNC)*RAEDC(IMNC)
  ENDDO
  IF(JMM /= 1) THEN
    IMM  = IMM+1
    DO JNN=JMM,11
      IMNS = IMNS+1
      ZFAES(IMM) = ZFAES(IMM)+ZALP(IMNS+11)*RAESS(IMNS)
      ZFAEL(IMM) = ZFAEL(IMM)+ZALP(IMNS+11)*RAELS(IMNS)
      ZFAEU(IMM) = ZFAEU(IMM)+ZALP(IMNS+11)*RAEUS(IMNS)
      ZFAED(IMM) = ZFAED(IMM)+ZALP(IMNS+11)*RAEDS(IMNS)
    ENDDO
  ENDIF
ENDDO

!       3.3     FOURIER TRANSFORM FOR AEROSOLS
!               ------------------------------

IL = KSHIFT
DO JL=KIDIA,KFDIA,KRINT
  IL = IL+1
  ZCOS1    = PCLON(JL)
  ZSIN1    = PSLON(JL)
  ZCOS2    = ZCOS1*ZCOS1-ZSIN1*ZSIN1
  ZSIN2    = ZSIN1*ZCOS1+ZCOS1*ZSIN1
  ZCOS3    = ZCOS2*ZCOS1-ZSIN2*ZSIN1
  ZSIN3    = ZSIN2*ZCOS1+ZCOS2*ZSIN1
  ZCOS4    = ZCOS3*ZCOS1-ZSIN3*ZSIN1
  ZSIN4    = ZSIN3*ZCOS1+ZCOS3*ZSIN1
  ZCOS5    = ZCOS4*ZCOS1-ZSIN4*ZSIN1
  ZSIN5    = ZSIN4*ZCOS1+ZCOS4*ZSIN1
  ZCOS6    = ZCOS5*ZCOS1-ZSIN5*ZSIN1
  ZSIN6    = ZSIN5*ZCOS1+ZCOS5*ZSIN1
  ZCOS7    = ZCOS6*ZCOS1-ZSIN6*ZSIN1
  ZSIN7    = ZSIN6*ZCOS1+ZCOS6*ZSIN1
  ZCOS8    = ZCOS7*ZCOS1-ZSIN7*ZSIN1
  ZSIN8    = ZSIN7*ZCOS1+ZCOS7*ZSIN1
  ZCOS9    = ZCOS8*ZCOS1-ZSIN8*ZSIN1
  ZSIN9    = ZSIN8*ZCOS1+ZCOS8*ZSIN1
  ZCOS10   = ZCOS9*ZCOS1-ZSIN9*ZSIN1
  ZSIN10   = ZSIN9*ZCOS1+ZCOS9*ZSIN1
  ZAES(IL) = ZFAES(1) + 2.0_JPRB*&
   & ( ZFAES(2)*ZCOS1  + ZFAES(3)*ZSIN1  + ZFAES(4)*ZCOS2&
   & + ZFAES(5)*ZSIN2  + ZFAES(6)*ZCOS3  + ZFAES(7)*ZSIN3&
   & + ZFAES(8)*ZCOS4  + ZFAES(9)*ZSIN4  + ZFAES(10)*ZCOS5&
   & + ZFAES(11)*ZSIN5 + ZFAES(12)*ZCOS6 + ZFAES(13)*ZSIN6&
   & + ZFAES(14)*ZCOS7 + ZFAES(15)*ZSIN7 + ZFAES(16)*ZCOS8&
   & + ZFAES(17)*ZSIN8 + ZFAES(18)*ZCOS9 + ZFAES(19)*ZSIN9&
   & + ZFAES(20)*ZCOS10+ ZFAES(21)*ZSIN10                 )  
  ZAEL(IL) = ZFAEL(1) + 2.0_JPRB*&
   & ( ZFAEL(2)*ZCOS1  + ZFAEL(3)*ZSIN1  + ZFAEL(4)*ZCOS2&
   & + ZFAEL(5)*ZSIN2  + ZFAEL(6)*ZCOS3  + ZFAEL(7)*ZSIN3&
   & + ZFAEL(8)*ZCOS4  + ZFAEL(9)*ZSIN4  + ZFAEL(10)*ZCOS5&
   & + ZFAEL(11)*ZSIN5 + ZFAEL(12)*ZCOS6 + ZFAEL(13)*ZSIN6&
   & + ZFAEL(14)*ZCOS7 + ZFAEL(15)*ZSIN7 + ZFAEL(16)*ZCOS8&
   & + ZFAEL(17)*ZSIN8 + ZFAEL(18)*ZCOS9 + ZFAEL(19)*ZSIN9&
   & + ZFAEL(20)*ZCOS10+ ZFAEL(21)*ZSIN10                 )  
  ZAEU(IL) = ZFAEU(1) + 2.0_JPRB*&
   & ( ZFAEU(2)*ZCOS1  + ZFAEU(3)*ZSIN1  + ZFAEU(4)*ZCOS2&
   & + ZFAEU(5)*ZSIN2  + ZFAEU(6)*ZCOS3  + ZFAEU(7)*ZSIN3&
   & + ZFAEU(8)*ZCOS4  + ZFAEU(9)*ZSIN4  + ZFAEU(10)*ZCOS5&
   & + ZFAEU(11)*ZSIN5 + ZFAEU(12)*ZCOS6 + ZFAEU(13)*ZSIN6&
   & + ZFAEU(14)*ZCOS7 + ZFAEU(15)*ZSIN7 + ZFAEU(16)*ZCOS8&
   & + ZFAEU(17)*ZSIN8 + ZFAEU(18)*ZCOS9 + ZFAEU(19)*ZSIN9&
   & + ZFAEU(20)*ZCOS10+ ZFAEU(21)*ZSIN10                 )  
  ZAED(IL) = ZFAED(1) + 2.0_JPRB*&
   & ( ZFAED(2)*ZCOS1  + ZFAED(3)*ZSIN1  + ZFAED(4)*ZCOS2&
   & + ZFAED(5)*ZSIN2  + ZFAED(6)*ZCOS3  + ZFAED(7)*ZSIN3&
   & + ZFAED(8)*ZCOS4  + ZFAED(9)*ZSIN4  + ZFAED(10)*ZCOS5&
   & + ZFAED(11)*ZSIN5 + ZFAED(12)*ZCOS6 + ZFAED(13)*ZSIN6&
   & + ZFAED(14)*ZCOS7 + ZFAED(15)*ZSIN7 + ZFAED(16)*ZCOS8&
   & + ZFAED(17)*ZSIN8 + ZFAED(18)*ZCOS9 + ZFAED(19)*ZSIN9&
   & + ZFAED(20)*ZCOS10+ ZFAED(21)*ZSIN10                 )  
ENDDO

!       3.4     PREPARE PERTURBATIONS OF AEROSOL DISTRIBUTION
!               ---------------------------------------------

IF (YDSPP_CONFIG%LSPP) THEN

  IPN = YDSPP_CONFIG%PPTR%ZHS_VDAERO
  LLPERT_ZHS_VDAERO = IPN > 0
  IF (LLPERT_ZHS_VDAERO) THEN
    PN1ZHS_VD = YDSPP_CONFIG%SM%PN(IPN)
    IPZHSVDAERO=PN1ZHS_VD%MP_RADGRID
  ENDIF

  IPN = YDSPP_CONFIG%PPTR%DELTA_AERO
  LLPERT_DELTA_AERO = IPN > 0
  IF (LLPERT_DELTA_AERO) THEN
    PN1DELTA = YDSPP_CONFIG%SM%PN(IPN)
    IPDELTAAERO=PN1DELTA%MP_RADGRID
  ENDIF

ELSE
  LLPERT_ZHS_VDAERO = .FALSE.
  LLPERT_DELTA_AERO = .FALSE.
ENDIF

!     ------------------------------------------------------------------

!*       4.      VERTICAL DISTRIBUTION
!*               ---------------------
!* HH The code around LESO4HIS could be simpler; but it ensures bit-identical
!* HH results with CY36R4 when it is .false. (default)

IL=KSHIFT
DO JL=KIDIA,KFDIA,KRINT
  IL=IL+1
  ZDPO(IL)=PAPRS (JL,1)
  ZCPHO3=PAPRS (JL,1)**3
  ZSDPO3=SQRT  (ZCPHO3)
  IF (LNEWAER) THEN
    ZVDAEL=CVDAEL(1)
    ZVDAES=CVDAES(1)
    ZVDAEU=CVDAEU(1)
    ZVDAED=CVDAED(1)
    IF (NAERMACC == 1) THEN
      ZVDAESU=CVDAESU(1)
      ZVDAESS=CVDAESS(1)
      ZVDAEDU=CVDAEDU(1)
      ZVDAEOM=CVDAEOM(1)
      ZVDAEBC=CVDAEBC(1)
    ENDIF
    !
    !   SPP: perturb vertical length scales if LLPERT_ZHS_VDAERO=T
    !     ZVDAE. is replaced by ZVDAE**(1./r) with 1/r=ZRRVD
    !
    IF (LLPERT_ZHS_VDAERO) THEN
      ! distribution of r^-1
      ! random pattern stored in ZRRVD for later use
      ZRRVD(IL)=EXP(-(PN1ZHS_VD%MU(1)+PN1ZHS_VD%XMAG(1)*PPERT(JL,IPZHSVDAERO)))
      ZVDAEL=ZVDAEL**ZRRVD(IL)
      ZVDAES=ZVDAES**ZRRVD(IL)
      ZVDAEU=ZVDAEU**ZRRVD(IL)
      ZVDAED=ZVDAED**ZRRVD(IL)
      IF (NAERMACC == 1) THEN
        ZVDAESU=ZVDAESU**ZRRVD(IL)
        ZVDAESS=ZVDAESS**ZRRVD(IL)
        ZVDAEDU=ZVDAEDU**ZRRVD(IL)
        ZVDAEOM=ZVDAEOM**ZRRVD(IL)
        ZVDAEBC=ZVDAEBC**ZRRVD(IL)
      ENDIF
    ENDIF

    ZXAERSU(IL)=ZAERSU(IL)
    ZXAERSS(IL)=ZAERSS(IL)
    ZXAEROR(IL)=ZAEROR(IL)
    ZXAERBC(IL)=ZAERBC(IL)
    ZXAERSD(IL)=ZAERSD(IL)
    IF (NAERMACC == 1 .AND. .NOT. LAER3D) THEN
      ZXAERSUA(IL)=ZAERSUA(IL)
      ZXAERSSA(IL)=ZAERSSA(IL)
      ZXAERSSB(IL)=ZAERSSB(IL)
      ZXAERSSC(IL)=ZAERSSC(IL)
      ZXAERSDA(IL)=ZAERSDA(IL)
      ZXAERSDB(IL)=ZAERSDB(IL)
      ZXAERSDC(IL)=ZAERSDC(IL)
      ZXAERORA(IL)=ZAERORA(IL)
      ZXAERORB(IL)=ZAERORB(IL)
      ZXAERBCA(IL)=ZAERBCA(IL)
      ZXAERBCB(IL)=ZAERBCB(IL)
    ENDIF
    !
    !   SPP: perturb 2D horizontal distribution if LLPERT_DELTA_AERO=T
    !
    IF (LLPERT_DELTA_AERO) THEN
      ZRDELTA=EXP(PN1DELTA%MU(1)+PN1DELTA%XMAG(1)*PPERT(JL,IPDELTAAERO))
      ZXAERSU(IL)=ZXAERSU(IL)*ZRDELTA
      ZXAERSS(IL)=ZXAERSS(IL)*ZRDELTA
      ZXAEROR(IL)=ZXAEROR(IL)*ZRDELTA
      ZXAERBC(IL)=ZXAERBC(IL)*ZRDELTA
      ZXAERSD(IL)=ZXAERSD(IL)*ZRDELTA
      IF (NAERMACC == 1 .AND. .NOT. LAER3D) THEN
        ZXAERSUA(IL)=ZXAERSUA(IL)*ZRDELTA
        ZXAERSSA(IL)=ZXAERSSA(IL)*ZRDELTA
        ZXAERSSB(IL)=ZXAERSSB(IL)*ZRDELTA
        ZXAERSSC(IL)=ZXAERSSC(IL)*ZRDELTA
        ZXAERSDA(IL)=ZXAERSDA(IL)*ZRDELTA
        ZXAERSDB(IL)=ZXAERSDB(IL)*ZRDELTA
        ZXAERSDC(IL)=ZXAERSDC(IL)*ZRDELTA
        ZXAERORA(IL)=ZXAERORA(IL)*ZRDELTA
        ZXAERORB(IL)=ZXAERORB(IL)*ZRDELTA
        ZXAERBCA(IL)=ZXAERBCA(IL)*ZRDELTA
        ZXAERBCB(IL)=ZXAERBCB(IL)*ZRDELTA
      ENDIF
    ENDIF
      
    ZSO4SO(IL)= ZXAERSU(IL)*ZVDAEL
    ZAEQSO(IL)= ZXAERSS(IL)*ZVDAES
    IF (LESO4HIS) THEN
       ZAEQLO(IL)= ZXAEROR(IL)*ZVDAEL
    ELSE
       ZAEQLO(IL)= ZXAEROR(IL)*ZVDAEL + ZSO4SO(IL)
    ENDIF
    ZAEQUO(IL)= ZXAERBC(IL)*ZVDAEU
    ZAEQDO(IL)= ZXAERSD(IL)*ZVDAED
    IF (NAERMACC == 1 .AND. .NOT. LAER3D) THEN
      ZAERSUO(IL)= ZXAERSUA(IL)*ZVDAESU   
      ZAERS1O(IL)= ZXAERSSA(IL)*ZVDAESS   
      ZAERS2O(IL)= ZXAERSSB(IL)*ZVDAESS
      ZAERS3O(IL)= ZXAERSSC(IL)*ZVDAESS
      ZAERD1O(IL)= ZXAERSDA(IL)*ZVDAEDU
      ZAERD2O(IL)= ZXAERSDB(IL)*ZVDAEDU
      ZAERD3O(IL)= ZXAERSDC(IL)*ZVDAEDU
      ZAERO1O(IL)= ZXAERORA(IL)*ZVDAEOM
      ZAERO2O(IL)= ZXAERORB(IL)*ZVDAEOM
      ZAERB1O(IL)= ZXAERBCA(IL)*ZVDAEBC
      ZAERB2O(IL)= ZXAERBCB(IL)*ZVDAEBC
    ENDIF
  ELSE
    ZSO4SO(IL)=0.0_JPRB
    ZAEQSO(IL)=RCAEOPS*ZAES(IL)*CVDAES(1)
    ZAEQLO(IL)=RCAEOPL*ZAEL(IL)*CVDAEL(1)
    ZAEQUO(IL)=RCAEOPU*ZAEU(IL)*CVDAEU(1)
    ZAEQDO(IL)=RCAEOPD*ZAED(IL)*CVDAED(1)
  ENDIF  
  ZAETRO(IL)=1.0_JPRB
  ZQOFO(IL)=ZOZQ(IL)*ZSDPO3 / (ZSDPO3 + ZOZH(IL))
ENDDO

DO JK=1,KLEV
  IL=KSHIFT
  IF (KCF == 0) THEN
    DO JL=KIDIA,KFDIA,KRINT
      IL=IL+1
      ZGRTH(IL)= PTH(JL,JK)/PTH(JL,JK+1)
      ZRH(IL)  = PQ (JL,JK)/PQS(JL,JK)
    ENDDO
  ELSEIF (KCF == 1) THEN
    DO JL=KIDIA,KFDIA,KRINT
      IL=IL+1
      ZGRTH(IL)= PTH(IL,JK)/PTH(IL,JK+1)
      ZRH(IL)  = PQ (IL,JK)/PQS(IL,JK)
    ENDDO
  ENDIF

  IF(LESO4HIS) THEN
    IL=KSHIFT
    DO JL=KIDIA,KFDIA,KRINT
      IL=IL+1
      IRH(IL)=1
      DO JTAB=1,12
        IF (ZRH(IL)*100._JPRB > RRHTAB(JTAB)) THEN
          IRH(IL)=JTAB
        ENDIF
      ENDDO
    ENDDO
  ENDIF

  IL=KSHIFT
  DO JL=KIDIA,KFDIA,KRINT
    IL=IL+1
    ZDPN(IL)=PAPRS (JL,JK+1)
    ZCPHN3=PAPRS (JL,JK+1)**3
    ZSDPN3=SQRT  (ZCPHN3)
    IF (LNEWAER) THEN
      ZVDAEL=CVDAEL(JK+1)
      ZVDAES=CVDAES(JK+1)
      ZVDAEU=CVDAEU(JK+1)
      ZVDAED=CVDAED(JK+1)
      IF (NAERMACC == 1) THEN
        ZVDAESU=CVDAESU(JK+1)
        ZVDAESS=CVDAESS(JK+1)
        ZVDAEDU=CVDAEDU(JK+1)
        ZVDAEOM=CVDAEOM(JK+1)
        ZVDAEBC=CVDAEBC(JK+1)
      ENDIF
      !
      !   SPP: perturb vertical length scales if LLPERT_ZHS_VDAERO=T
      !     ZVDAE. is replaced by ZVDAE**(1./r) with 1/r=ZRRVD
      !
      IF (LLPERT_ZHS_VDAERO) THEN
        !
        ! distribution of r^-1:
        !   ZRRVD(IL) is pre-computed in block that deals with CVDAE.(1)
        !
        ZVDAEL=ZVDAEL**ZRRVD(IL)
        ZVDAES=ZVDAES**ZRRVD(IL)
        ZVDAEU=ZVDAEU**ZRRVD(IL)
        ZVDAED=ZVDAED**ZRRVD(IL)
        IF (NAERMACC == 1) THEN
          ZVDAESU=ZVDAESU**ZRRVD(IL)
          ZVDAESS=ZVDAESS**ZRRVD(IL)
          ZVDAEDU=ZVDAEDU**ZRRVD(IL)
          ZVDAEOM=ZVDAEOM**ZRRVD(IL)
          ZVDAEBC=ZVDAEBC**ZRRVD(IL)
        ENDIF
      ENDIF
      !
      !   ZXAER.. are unperturbed if LLPERT_DELTA_AERO=F
      !
      ZSO4SN(IL)= ZXAERSU(IL)*ZVDAEL
      ZAEQSN(IL)= ZXAERSS(IL)*ZVDAES
      IF (LESO4HIS) THEN
         ZAEQLN(IL)= ZXAEROR(IL)*ZVDAEL
      ELSE
         ZAEQLN(IL)= ZXAEROR(IL)*ZVDAEL + ZSO4SN(IL)
      ENDIF
      ZAEQUN(IL)= ZXAERBC(IL)*ZVDAEU
      ZAEQDN(IL)= ZXAERSD(IL)*ZVDAED
      IF (NAERMACC == 1 .AND. .NOT. LAER3D) THEN
        ZAERSUN(IL)= ZXAERSUA(IL)*ZVDAESU
        ZAERS1N(IL)= ZXAERSSA(IL)*ZVDAESS
        ZAERS2N(IL)= ZXAERSSB(IL)*ZVDAESS
        ZAERS3N(IL)= ZXAERSSC(IL)*ZVDAESS
        ZAERD1N(IL)= ZXAERSDA(IL)*ZVDAEDU
        ZAERD2N(IL)= ZXAERSDB(IL)*ZVDAEDU
        ZAERD3N(IL)= ZXAERSDC(IL)*ZVDAEDU
        ZAERO1N(IL)= ZXAERORA(IL)*ZVDAEOM
        ZAERO2N(IL)= ZXAERORB(IL)*ZVDAEOM
        ZAERB1N(IL)= ZXAERBCA(IL)*ZVDAEBC
        ZAERB2N(IL)= ZXAERBCB(IL)*ZVDAEBC
      ENDIF
    ELSE
      ZSO4SN(IL)=0.0_JPRB
      ZAEQSN(IL)=RCAEOPS*ZAES(IL)*CVDAES(JK+1)
      ZAEQLN(IL)=RCAEOPL*ZAEL(IL)*CVDAEL(JK+1)
      ZAEQUN(IL)=RCAEOPU*ZAEU(IL)*CVDAEU(JK+1)
      ZAEQDN(IL)=RCAEOPD*ZAED(IL)*CVDAED(JK+1)
    ENDIF  

    IF (0.5_JPRB*(PAPRS(JL,JK)+PAPRS(JL,JK+1)) < 999._JPRB) THEN
      ZAETRN(IL)=1.0_JPRB
    ELSE
      ZAETRN(IL)=ZAETRO(IL)*(MIN(1.0_JPRB,     ZGRTH(IL)         ))**RCTRPT
    ENDIF
    ZAETR=SQRT  (ZAETRN(IL)*ZAETRO(IL))
    IF(NVOLCVERT==0) THEN
      ZAETRV=ZAETR
    ELSEIF(NVOLCVERT==1) THEN
! Use temperature profile, but no volcanic aerosol above 10hPa
      IF (0.5_JPRB*(PAPRS(JL,JK)+PAPRS(JL,JK+1)) < 999._JPRB) THEN
        ZAETRV=0.0_JPRB
      ELSE
        ZAETRV=ZAETR
      ENDIF
    ELSEIF(NVOLCVERT==2) THEN
! Use prognostic ozone to define lower edge of aerosol distribution
      IF (0.5_JPRB*(PAPRS(JL,JK)+PAPRS(JL,JK+1)) < 999._JPRB) THEN
        ZAETRV=0.0_JPRB
      ELSEIF(0.5_JPRB*(PAPRS(JL,JK)+PAPRS(JL,JK+1)) < 7000._JPRB) THEN
        ZAETRV=1.0_JPRB
      ELSEIF(PAPRS(JL,JK) > 40000._JPRB) THEN
        ZAETRV=0.0_JPRB
      ELSE
        IF(PECPO3(JL,JK) > 0.4E-6_JPRB) THEN
          ZAETRV=1.0_JPRB
        ELSEIF(PECPO3(JL,JK) > 0.2E-6_JPRB) THEN
          ZAETRV=(PECPO3(JL,JK)-0.2E-6_JPRB)/0.2E-6_JPRB
        ELSE
          ZAETRV=0.0_JPRB
        ENDIF
      ENDIF
    ENDIF

    ZQOFN(IL)=ZOZQ(IL)*ZSDPN3/(ZSDPN3+ZOZH(IL))
    ZDPNMO    =ZDPN(IL)-ZDPO(IL)
    IF(LESO4HIS) THEN
       ZDSO4S = (ZSO4SN(IL)-ZSO4SO(IL))*ALF_SU(IRH(IL),9)
       PAER(IL,1,JK)=(1.0_JPRB-ZAETR)*(RCTRBGA*ZDPNMO+ ZAEQLN(IL)-ZAEQLO(IL) + ZDSO4S)
    ELSE
       PAER(IL,1,JK)=(1.0_JPRB-ZAETR)*(RCTRBGA*ZDPNMO+ ZAEQLN(IL)-ZAEQLO(IL))
    ENDIF
!fixed tropospheric background only in case of MACC climatology
    IF (NAERMACC == 1) PAER(IL,1,JK)=(1.0_JPRB-ZAETR)*(RCTRBGA*ZDPNMO)
    PAER(IL,2,JK)=(1.0_JPRB-ZAETR)*(ZAEQSN(IL)-ZAEQSO(IL))
    PAER(IL,3,JK)=(1.0_JPRB-ZAETR)*(ZAEQDN(IL)-ZAEQDO(IL))
    PAER(IL,4,JK)=(1.0_JPRB-ZAETR)*(ZAEQUN(IL)-ZAEQUO(IL))
! volcanic ash at fixed (low) background value
    PAER(IL,5,JK)=   ZAETRV  * RCVOBGA*ZDPNMO
! volcanic sulphate aerosol either fixed or varying according to GISS 
    PAER(IL,6,JK)=   ZAETRV  * ZAERVO(IL) * ZDPNMO
    POZON(IL,JK)=ZQOFN(IL)-ZQOFO(IL)
!**** **************************************************
!**** **************************************************
    IF (NAERMACC == 1) THEN
       IF (.NOT.LAER3D) THEN
!**** input data are in total integrated mass (kg/m2). The vertical profile is mass mixing ratio (kg/kg)
!**** hence the scaling by dp/g

          ZDP = (PAPRS(JL,JK+1)-PAPRS(JL,JK))/RG
          
          PAERO(IL,JK,1) = (1.0_JPRB-ZAETR)*(ZAERS1N(IL)-ZAERS1O(IL)) / ZDP
          PAERO(IL,JK,2) = (1.0_JPRB-ZAETR)*(ZAERS2N(IL)-ZAERS2O(IL)) / ZDP 
          PAERO(IL,JK,3) = (1.0_JPRB-ZAETR)*(ZAERS3N(IL)-ZAERS3O(IL)) / ZDP
          PAERO(IL,JK,4) = (1.0_JPRB-ZAETR)*(ZAERD1N(IL)-ZAERD1O(IL)) / ZDP
          PAERO(IL,JK,5) = (1.0_JPRB-ZAETR)*(ZAERD2N(IL)-ZAERD2O(IL)) / ZDP
          PAERO(IL,JK,6) = (1.0_JPRB-ZAETR)*(ZAERD3N(IL)-ZAERD3O(IL)) / ZDP
          PAERO(IL,JK,7) = (1.0_JPRB-ZAETR)*(ZAERO1N(IL)-ZAERO1O(IL)) / ZDP
          PAERO(IL,JK,8) = (1.0_JPRB-ZAETR)*(ZAERO2N(IL)-ZAERO2O(IL)) / ZDP
          PAERO(IL,JK,9) = (1.0_JPRB-ZAETR)*(ZAERB1N(IL)-ZAERB1O(IL)) / ZDP
          PAERO(IL,JK,10)= (1.0_JPRB-ZAETR)*(ZAERB2N(IL)-ZAERB2O(IL)) / ZDP
          PAERO(IL,JK,11)= (1.0_JPRB-ZAETR)*(ZAERSUN(IL)-ZAERSUO(IL)) / ZDP
          PAERO(IL,JK,12)= 0._JPRB
       ENDIF
    ENDIF
 ENDDO
  IL=KSHIFT
  DO JL=KIDIA,KFDIA,KRINT
    IL=IL+1
    ZDPO(IL)=ZDPN(IL)
    ZQOFO(IL)=ZQOFN(IL)

    ZAEQSO(IL)=ZAEQSN(IL)
    ZAEQLO(IL)=ZAEQLN(IL)
    ZSO4SO(IL)=ZSO4SN(IL)
    ZAEQUO(IL)=ZAEQUN(IL)
    ZAEQDO(IL)=ZAEQDN(IL)
    ZAETRO(IL)=ZAETRN(IL)

    IF (NAERMACC == 1 .AND. .NOT. LAER3D) THEN
      ZAERSUO(IL)= ZAERSUN(IL)
      ZAERS1O(IL)= ZAERS1N(IL)
      ZAERS2O(IL)= ZAERS2N(IL)
      ZAERS3O(IL)= ZAERS3N(IL)
      ZAERD1O(IL)= ZAERD1N(IL)
      ZAERD2O(IL)= ZAERD2N(IL)
      ZAERD3O(IL)= ZAERD3N(IL)
      ZAERO1O(IL)= ZAERO1N(IL)
      ZAERO2O(IL)= ZAERO2N(IL)
      ZAERB1O(IL)= ZAERB1N(IL)
      ZAERB2O(IL)= ZAERB2N(IL)
    ENDIF
  ENDDO
  
!-- diagnostics on Tegen climatology in case of problem  
  DO JAER=1,6
    IL=KSHIFT
    DO JL=KIDIA,KFDIA,KRINT
      IL=IL+1
      PAER(IL,JAER,JK)=MAX(PAER(IL,JAER,JK),YDRIP%YREAERC_TEGEN%REPAER)
    ENDDO
    ITOT=IL
  ENDDO   
!--
   
ENDDO

!-- Initialization of arrays used in the interpolation
!-- of 3D aerosol climatology
ZAERBCA3D_VI_input(KIDIA:KFDIA,0) = 0._JPRB
ZAERBCA3D_VI(KIDIA:KFDIA,0) = 0._JPRB
ZAERBCB3D_VI_input(KIDIA:KFDIA,0) = 0._JPRB
ZAERBCB3D_VI(KIDIA:KFDIA,0) = 0._JPRB

ZAERORA3D_VI_input(KIDIA:KFDIA,0) = 0._JPRB
ZAERORA3D_VI(KIDIA:KFDIA,0) = 0._JPRB
ZAERORB3D_VI_input(KIDIA:KFDIA,0) = 0._JPRB
ZAERORB3D_VI(KIDIA:KFDIA,0) = 0._JPRB

ZAERSDA3D_VI_input(KIDIA:KFDIA,0) = 0._JPRB
ZAERSDA3D_VI(KIDIA:KFDIA,0) = 0._JPRB
ZAERSDB3D_VI_input(KIDIA:KFDIA,0) = 0._JPRB
ZAERSDB3D_VI(KIDIA:KFDIA,0) = 0._JPRB
ZAERSDC3D_VI_input(KIDIA:KFDIA,0) = 0._JPRB
ZAERSDC3D_VI(KIDIA:KFDIA,0) = 0._JPRB

ZAERSSA3D_VI_input(KIDIA:KFDIA,0) = 0._JPRB
ZAERSSA3D_VI(KIDIA:KFDIA,0) = 0._JPRB
ZAERSSB3D_VI_input(KIDIA:KFDIA,0) = 0._JPRB
ZAERSSB3D_VI(KIDIA:KFDIA,0) = 0._JPRB
ZAERSSC3D_VI_input(KIDIA:KFDIA,0) = 0._JPRB
ZAERSSC3D_VI(KIDIA:KFDIA,0) = 0._JPRB

ZAERSUA3D_VI_input(KIDIA:KFDIA,0) = 0._JPRB
ZAERSUA3D_VI(KIDIA:KFDIA,0) = 0._JPRB

ZREF_AER_PR(KIDIA:KFDIA,0) = 0._JPRB !to define!!!!!

!shift needed because otherwise DP is computed as JK+1 - JK
!while aerosol MMR as JK - JK-1
ZPRS(:,0:KLEV)=PAPRS(:,1:KLEV+1)
IF (LAER3D .AND. NAERMACC==1) THEN
!vertical interpolation of the input 3D climatology
!files come in already in layer mass kg/m2 (mmr*dp/g).
!1)compute the cumulative vertical profile on the original grid
   DO JK=1,KLEV_AER
      ZAERBCA3D_VI_input(KIDIA:KFDIA,JK) = ZAERBCA3D_VI_input(KIDIA:KFDIA,JK-1) + ZAERBCA3D(KIDIA:KFDIA,JK)
      ZAERBCB3D_VI_input(KIDIA:KFDIA,JK) = ZAERBCB3D_VI_input(KIDIA:KFDIA,JK-1) + ZAERBCB3D(KIDIA:KFDIA,JK)

      ZAERORA3D_VI_input(KIDIA:KFDIA,JK) = ZAERORA3D_VI_input(KIDIA:KFDIA,JK-1) + ZAERORA3D(KIDIA:KFDIA,JK)
      ZAERORB3D_VI_input(KIDIA:KFDIA,JK) = ZAERORB3D_VI_input(KIDIA:KFDIA,JK-1) + ZAERORB3D(KIDIA:KFDIA,JK)

      ZAERSDA3D_VI_input(KIDIA:KFDIA,JK) = ZAERSDA3D_VI_input(KIDIA:KFDIA,JK-1) + ZAERSDA3D(KIDIA:KFDIA,JK)
      ZAERSDB3D_VI_input(KIDIA:KFDIA,JK) = ZAERSDB3D_VI_input(KIDIA:KFDIA,JK-1) + ZAERSDB3D(KIDIA:KFDIA,JK)
      ZAERSDC3D_VI_input(KIDIA:KFDIA,JK) = ZAERSDC3D_VI_input(KIDIA:KFDIA,JK-1) + ZAERSDC3D(KIDIA:KFDIA,JK)

      ZAERSSA3D_VI_input(KIDIA:KFDIA,JK) = ZAERSSA3D_VI_input(KIDIA:KFDIA,JK-1) + ZAERSSA3D(KIDIA:KFDIA,JK)
      ZAERSSB3D_VI_input(KIDIA:KFDIA,JK) = ZAERSSB3D_VI_input(KIDIA:KFDIA,JK-1) + ZAERSSB3D(KIDIA:KFDIA,JK)
      ZAERSSC3D_VI_input(KIDIA:KFDIA,JK) = ZAERSSC3D_VI_input(KIDIA:KFDIA,JK-1) + ZAERSSC3D(KIDIA:KFDIA,JK)

      ZAERSUA3D_VI_input(KIDIA:KFDIA,JK) = ZAERSUA3D_VI_input(KIDIA:KFDIA,JK-1) + ZAERSUA3D(KIDIA:KFDIA,JK)
   ENDDO
!2)interpolate the cumulative vertical profile on the (vertical) model grid
   DO JK=1,KLEV
      IL=KSHIFT
      DO JL=KIDIA,KFDIA,KRINT
         IL=IL+1
         IC=KLEV_AER-1
         DO JC=0,KLEV_AER-1
            IF( ZPRS(JL,JK) >= ZREF_AER_PR(IL,JC) .AND. ZPRS(JL,JK) < ZREF_AER_PR(IL,JC+1)) THEN
               IC = JC
               EXIT
            ENDIF
         ENDDO
         ZINT=(ZPRS(JL,JK)-ZREF_AER_PR(IL,IC))/(ZREF_AER_PR(IL,IC+1)-ZREF_AER_PR(IL,IC))

         ZAERBCA3D_VI(IL,JK) = ZAERBCA3D_VI_input(IL,IC) + ZINT * (ZAERBCA3D_VI_input(IL,IC+1) -ZAERBCA3D_VI_input(IL,IC))
         ZAERBCB3D_VI(IL,JK) = ZAERBCB3D_VI_input(IL,IC) + ZINT * (ZAERBCB3D_VI_input(IL,IC+1) -ZAERBCB3D_VI_input(IL,IC))

         ZAERORA3D_VI(IL,JK) = ZAERORA3D_VI_input(IL,IC) + ZINT * (ZAERORA3D_VI_input(IL,IC+1) -ZAERORA3D_VI_input(IL,IC))
         ZAERORB3D_VI(IL,JK) = ZAERORB3D_VI_input(IL,IC) + ZINT * (ZAERORB3D_VI_input(IL,IC+1) -ZAERORB3D_VI_input(IL,IC))

         ZAERSDA3D_VI(IL,JK) = ZAERSDA3D_VI_input(IL,IC) + ZINT * (ZAERSDA3D_VI_input(IL,IC+1) -ZAERSDA3D_VI_input(IL,IC))
         ZAERSDB3D_VI(IL,JK) = ZAERSDB3D_VI_input(IL,IC) + ZINT * (ZAERSDB3D_VI_input(IL,IC+1) -ZAERSDB3D_VI_input(IL,IC))
         ZAERSDC3D_VI(IL,JK) = ZAERSDC3D_VI_input(IL,IC) + ZINT * (ZAERSDC3D_VI_input(IL,IC+1) -ZAERSDC3D_VI_input(IL,IC))

         ZAERSSA3D_VI(IL,JK) = ZAERSSA3D_VI_input(IL,IC) + ZINT * (ZAERSSA3D_VI_input(IL,IC+1) -ZAERSSA3D_VI_input(IL,IC))
         ZAERSSB3D_VI(IL,JK) = ZAERSSB3D_VI_input(IL,IC) + ZINT * (ZAERSSB3D_VI_input(IL,IC+1) -ZAERSSB3D_VI_input(IL,IC))
         ZAERSSC3D_VI(IL,JK) = ZAERSSC3D_VI_input(IL,IC) + ZINT * (ZAERSSC3D_VI_input(IL,IC+1) -ZAERSSC3D_VI_input(IL,IC))

         ZAERSUA3D_VI(IL,JK) = ZAERSUA3D_VI_input(IL,IC) + ZINT * (ZAERSUA3D_VI_input(IL,IC+1) -ZAERSUA3D_VI_input(IL,IC))
      ENDDO
   ENDDO
!3)compute the mass mixing ratio from the cumulative vertical profile
   DO JK=1,KLEV
      IL=KSHIFT
      DO JL=KIDIA,KFDIA,KRINT
         IL=IL+1
         ZDP=(ZPRS(JL,JK)-ZPRS(JL,JK-1))/RG !back to kg/kg from kg/m2

         PAERO(IL,JK,1) = (ZAERSSA3D_VI(IL,JK)-ZAERSSA3D_VI(IL,JK-1)) / ZDP
         PAERO(IL,JK,2) = (ZAERSSB3D_VI(IL,JK)-ZAERSSB3D_VI(IL,JK-1)) / ZDP
         PAERO(IL,JK,3) = (ZAERSSC3D_VI(IL,JK)-ZAERSSC3D_VI(IL,JK-1)) / ZDP

         PAERO(IL,JK,4) = (ZAERSDA3D_VI(IL,JK)-ZAERSDA3D_VI(IL,JK-1)) / ZDP
         PAERO(IL,JK,5) = (ZAERSDB3D_VI(IL,JK)-ZAERSDB3D_VI(IL,JK-1)) / ZDP
         PAERO(IL,JK,6) = (ZAERSDC3D_VI(IL,JK)-ZAERSDC3D_VI(IL,JK-1)) / ZDP

         PAERO(IL,JK,7) = (ZAERORA3D_VI(IL,JK)-ZAERORA3D_VI(IL,JK-1)) / ZDP
         PAERO(IL,JK,8) = (ZAERORB3D_VI(IL,JK)-ZAERORB3D_VI(IL,JK-1)) / ZDP

         PAERO(IL,JK,9) = (ZAERBCA3D_VI(IL,JK)-ZAERBCA3D_VI(IL,JK-1)) / ZDP
         PAERO(IL,JK,10) = (ZAERBCB3D_VI(IL,JK)-ZAERBCB3D_VI(IL,JK-1)) / ZDP

         PAERO(IL,JK,11) = (ZAERSUA3D_VI(IL,JK)-ZAERSUA3D_VI(IL,JK-1)) / ZDP
         PAERO(IL,JK,12) = 0._JPRB
      ENDDO
   ENDDO
ENDIF

!     ------------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('RADACT',1,ZHOOK_HANDLE)
END SUBROUTINE RADACT
