! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE RADINA&
 & (YDDIMV, YDMODEL,KIDIA , KFDIA , KLON , KLEV ,&
 & PALBD , PALBP , PAPRS  , PAPRSF,&
 & PCCNL , PCCNO , PCLFR,&
 & PGELAM, PCLON,  PSLON,&
 & PDP ,   PEMIR , PEMIW,&
 & PGEMU,  PMU0 ,  PQ     , PQS,&
 & PQIWP , PQLWP,  PQRWP,   PQSWP,&
 & PSLM  , PT    , PTS,&
 & PEMTD , PTRSO,&
 & PEMIT , PTH   , PCTRSO , PCEMTR , PTRSOD, PFRTED,&
 & PSUDU , PSDUR , PDSRP&
 & )  

!**** *RADINA* - RADIATION INTERFACE TO RADIATION SCHEME USED
!                DURING ASSIMILATION

!     PURPOSE.
!     --------

!**   INTERFACE.
!     ----------

!        EXPLICIT ARGUMENTS :
!        --------------------
!     ==== INPUTS ===
! KLEV   : NUMBER OF LEVELS

! PAER   : (KLON,6,KLEV)        ; OPTICAL THICKNESS OF THE AEROSOLS
! PALBD  : (KLON,NSW)           ; DIFFUSE ALBEDO IN THE NSW SW INTERVALS
! PALBP  : (KLON,NSW)           ; PARALLEL ALBEDO IN THE NSW SW INTERVALS
! PAPRS  : (KLON,KLEV+1)        ; HALF LEVEL PRESSURE
! PAPRSF : (KLON,KLEV )         ; FULL LEVEL PRESSURE
! PCCNL  : (KLON)               ; CCN CONCENTRATION OVER LAND
! PCCNO  : (KLON)               ; CCN CONCENTRATION OVER OCEAN
! PCLFR  : (KLON,KLEV )         ; CLOUD FRACTIONAL COVER
! PGELAM : (KLON)               ; LONGITUDE
! PQO3   : (KLON,KLEV )         ; OZONE MIXING RATIO (MASS)
! PDP    : (KLON,KLEV)          ; LAYER PRESSURE THICKNESS
! PEMIR  : (KLON)               ; SURFACE EMISSIVITY OUTSIDE LW WINDOW
! PEMIW  : (KLON)               ; SURFACE LW WINDOW EMISSIVITY
! PGEMU  : (KLON)               ; SINE OF LATITUDE ON THE REAL EARTH
! PMU0   : (KLON)               ; SOLAR ANGLE
! PQ     : (KLON,KLEV )         ; SPECIFIC HUMIDITY PA/PA
! PQS    : (KLON,KLEV )         ; SATURATION SPECIFIC HUMIDITY PA/PA
! PQIWP  : (KLON,KLEV )         ; ICE    WATER KG/KG
! PQLWP  : (KLON,KLEV )         ; LIQUID WATER KG/KG
! PQRWP  : (KLON,KLEV )         ; RAIN WATER KG/KG
! PQSWP  : (KLON,KLEV )         ; SNOW WATER KG/KG
! PSLM   : (KLON)               ; LAND-SEA MASK
! PT     : (KLON,KLEV)          ; FULL LEVEL TEMPERATURE
! PTS    : (KLON)               ; SURFACE TEMPERATURE
!     ==== OUTPUTS ===
! PEMTD (KLON,KLEV+1)           ; TOTAL DOWNWARD LONGWAVE EMISSIVITY
! PTRSO (KLON,KLEV+1)           ; TOTAL SHORTWAVE TRANSMISSIVITY
! PTH   (KLON,KLEV+1)           ; HALF LEVEL TEMPERATURE
! PCTRSO(KLON,2)                ; CLEAR-SKY SHORTWAVE TRANSMISSIVITY
! PCEMTR(KLON,2)                ; CLEAR-SKY NET LONGWAVE EMISSIVITY
! PTRSOD(KLON)                  ; TOTAL-SKY SURFACE SW TRANSMISSITY
! PFRTED(KLON)                  ; Surface downwelling LW flux
! PEMIT (KLON)                  ; SURFACE TOTAL LONGWAVE EMISSIVITY

!        IMPLICIT ARGUMENTS :   NONE
!        --------------------

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF RESEARCH DEPARTMENT DOCUMENTATION OF THE IFS

!     AUTHOR.
!     -------
!      Original : 96-10-11 JJ MORCRETTE

!     MODIFICATIONS.
!     --------------
!      01-10-10   JJMorcrette  CCNs
!      01-11-08   JJMorcrette  Safety checks
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!        2011-02    A.Alias    Change of call to RADLSW
!      June 2014  R Hogan      Pass surface downwelling LW flux through
!      Y. Bouteloup october 2016 : Add ZFDIF (new output flux from radlswr)
!-----------------------------------------------------------------------

USE TYPE_MODEL , ONLY : MODEL
USE YOMDIMV    , ONLY : TDIMV
USE PARKIND1   , ONLY : JPIM, JPRB
USE YOMHOOK    , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOERDU     , ONLY : NIMP, NOUT

IMPLICIT NONE

TYPE(TDIMV)       ,INTENT(IN)    :: YDDIMV
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PALBD(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PALBP(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRS(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PAPRSF(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCCNL(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCCNO(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLFR(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGELAM(KLON), PCLON(KLON), PSLON(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDP(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PEMIR(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PEMIW(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGEMU(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMU0(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQ(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQS(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQIWP(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQLWP(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQRWP(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQSWP(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSLM(KLON) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PT(KLON,KLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTS(KLON) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PEMTD(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTRSO(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PEMIT(KLON) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTH(KLON,KLEV+1) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PCTRSO(KLON,2) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PCEMTR(KLON,2) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTRSOD(KLON) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSUDU(KLON) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PSDUR(KLON) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PDSRP(KLON) 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFRTED(KLON) 

!-----------------------------------------------------------------------

REAL(KIND=JPRB) :: ZQAER(KLON,6,KLEV) , ZQOZ(KLON,KLEV)

REAL(KIND=JPRB) :: ZFRTHC(KLON,KLEV+1), ZFRSOC(KLON,KLEV+1), ZFRSOD(KLON)
REAL(KIND=JPRB) :: ZFRTH (KLON,KLEV+1), ZFRSO (KLON,KLEV+1)
REAL(KIND=JPRB) :: ZSUDU (KLON)       , ZFRSODC(KLON)      , ZFRTEDC(KLON)
REAL(KIND=JPRB) :: ZNBAS(KLON)        , ZNTOP(KLON)

REAL(KIND=JPRB) :: ZAMU0(KLON)

REAL(KIND=JPRB) :: ZCLFR(KLON,KLEV)
REAL(KIND=JPRB) :: ZQ(KLON,KLEV)    , ZQS(KLON,KLEV)
REAL(KIND=JPRB) :: ZQIWP(KLON,KLEV) , ZQLWP(KLON,KLEV)
REAL(KIND=JPRB) :: ZUVDF(KLON) , ZPARF(KLON), ZPARCF(KLON), ZTINCF(KLON)
REAL(KIND=JPRB) :: ZFSDNN(KLON) , ZFSDNV(KLON)
REAL(KIND=JPRB) :: ZSFSWDIR(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW),ZSFSWDIF(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)
REAL(KIND=JPRB) :: ZDUM(KLON), ZDUMAER(KLON,KLEV,12)
REAL(KIND=JPRB) :: ZDUMMY(KLON,KLEV,YDMODEL%YRML_PHY_RAD%YRERAD%NSW),ZDUMMY2(KLON,KLEV+1)

!-- quantities added for calling 32R1 radiation scheme (RADLSWR)
!-- inputs
REAL(KIND=JPRB) :: ZCO2(KLON,KLEV), ZCH4(KLON,KLEV), ZN2O(KLON,KLEV), ZNO2(KLON,KLEV)
REAL(KIND=JPRB) :: ZC11(KLON,KLEV), ZC12(KLON,KLEV), ZC22(KLON,KLEV), ZCL4(KLON,KLEV)
REAL(KIND=JPRB) :: ZQRWP(KLON,KLEV), ZQSWP(KLON,KLEV)
REAL(KIND=JPRB) :: ZQAERO(KLON,KLEV, YDMODEL%YRML_GCONF%YGFL%NAERO)

! The following is for partial derivative dLwUp_dLwUpSurf that is not
! used when the radiation is called every gridpoint (as in radina);
! the radintg subroutine does use it.
REAL(KIND=JPRB) :: ZDUMMY3(KLON,KLEV+1), ZDUMMY4(KLON,YDMODEL%YRML_PHY_RAD%YRERAD%NSW)

!-- outputs
REAL(KIND=JPRB) :: ZCDIR(KLON), ZFDIR(KLON), ZFDIF(KLON)

INTEGER(KIND=JPIM) :: JAER, JK, JL

REAL(KIND=JPRB) :: Z1S, Z2S, Z3S, ZCRAE, ZRII0
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "radaca.intfb.h"
#include "radlsw.intfb.h"
#include "radlswr.intfb.h"
#include "radozc.intfb.h"

!     ------------------------------------------------------------------

!*       1.    PREPARATORY WORK
!              ----------------

IF (LHOOK) CALL DR_HOOK('RADINA',0,ZHOOK_HANDLE)
ASSOCIATE(YDPHY=>YDMODEL%YRML_PHY_MF%YRPHY,YDEPHLI=>YDMODEL%YRML_PHY_SLIN%YREPHLI,YDERAD=>YDMODEL%YRML_PHY_RAD%YRERAD, &
 & YDPHY3=>YDMODEL%YRML_PHY_MF%YRPHY3, YDRIP=>YDMODEL%YRML_GCONF%YRRIP, &
 & YGFL=>YDMODEL%YRML_GCONF%YGFL,YDERDI=>YDMODEL%YRML_PHY_RAD%YRERDI,YDEAERD=>YDMODEL%YRML_PHY_RAD%YREAERD)
ASSOCIATE(NAERO=>YGFL%NAERO, &
 & RCAEROS=>YDEAERD%RCAEROS, &
 & LPHYLIN=>YDEPHLI%LPHYLIN, &
 & LEPO3RA=>YDERAD%LEPO3RA, LSRTM=>YDERAD%LSRTM, NAER=>YDERAD%NAER, &
 & NMODE=>YDERAD%NMODE, NOZOCL=>YDERAD%NOZOCL, NSW=>YDERAD%NSW, &
 & RCARDI=>YDERDI%RCARDI, RCCL4=>YDERDI%RCCL4, RCFC11=>YDERDI%RCFC11, &
 & RCFC12=>YDERDI%RCFC12, RCFC22=>YDERDI%RCFC22, RCH4=>YDERDI%RCH4, &
 & REPCLC=>YDERDI%REPCLC, REPH2O=>YDERDI%REPH2O, RN2O=>YDERDI%RN2O, &
 & RNO2=>YDERDI%RNO2, RRAE=>YDERDI%RRAE, RSUNDUR=>YDERDI%RSUNDUR, &
 & LRAYFM=>YDPHY%LRAYFM, RII0=>YDPHY3%RII0)
NIMP=0
NOUT=0
ZRII0=RII0

!- various constants      

ZCRAE=RRAE*(RRAE+2.0_JPRB)

!     ------------------------------------------------------------------

!*         2.     HALF-LEVEL QUANTITIES

! 200 CONTINUE

DO JK=2,KLEV
  DO JL=KIDIA,KFDIA
    Z1S = PAPRSF(JL,JK-1)*(PAPRSF(JL,JK)-PAPRS(JL,JK))
    Z2S = PAPRSF(JL,JK)*(PAPRS(JL,JK)-PAPRSF(JL,JK-1))
    Z3S = PAPRS(JL,JK)*(PAPRSF(JL,JK)-PAPRSF(JL,JK-1))
    PTH(JL,JK)=(PT(JL,JK-1)*Z1S+PT(JL,JK)*Z2S)/Z3S
  ENDDO
ENDDO

DO JL=KIDIA,KFDIA
  PTH(JL,1) =&
   & PT(JL,1)-PAPRSF(JL,1)&
   & *(PT(JL,1)-PTH(JL,2))&
   & /(PAPRSF(JL,1)-PAPRS(JL,2))    

  PTH(JL,KLEV+1)= PTS(JL)
  ZNBAS(JL) = 1.0_JPRB
  ZNTOP(JL) = 1.0_JPRB
ENDDO

!     ------------------------------------------------------------------

!*         3.     SOLAR ZENITH ANGLE IS SAMPLED AND EARTH'S CURVATURE
!                                     CORRECTED

! 300 CONTINUE

DO JL=KIDIA,KFDIA
  IF (PMU0(JL) > 1.E-10_JPRB) THEN
    ZAMU0(JL)=RRAE/(SQRT(PMU0(JL)**2+ZCRAE)-PMU0(JL))
  ELSE
    ZAMU0(JL)=RRAE/SQRT(ZCRAE)
  ENDIF  
ENDDO

!*           3.3     SECURITY COMPUTATIONS FOR CRITICAL VARIABLES.

DO JK=1,KLEV
  DO JL=KIDIA,KFDIA
    ZCLFR(JL,JK)=PCLFR(JL,JK)
    IF (PCLFR(JL,JK) < 0.0_JPRB ) THEN
      ZCLFR(JL,JK) = 0.0_JPRB
    ELSEIF (PCLFR(JL,JK) > 1.0_JPRB ) THEN
      ZCLFR(JL,JK) = 1.0_JPRB
    ENDIF
    ZQS(JL,JK)=PQS(JL,JK)
    IF (PQS(JL,JK) <= 2.0_JPRB*REPH2O) THEN
      ZQS(JL,JK) = 2.0_JPRB*REPH2O
    ENDIF
    ZQ(JL,JK)=PQ(JL,JK)
    IF (PQ(JL,JK) <= 2.0_JPRB*REPH2O) THEN
      ZQ(JL,JK) = 2.0_JPRB*REPH2O
    ELSEIF (PQ(JL,JK) > PQS(JL,JK)*(1.0_JPRB-REPH2O)) THEN
      ZQ(JL,JK) = PQS(JL,JK)*(1.0_JPRB-REPH2O)
    ENDIF
    ZQLWP(JL,JK)=PQLWP(JL,JK)
    IF (PQLWP(JL,JK) <= REPH2O) THEN
      ZQLWP(JL,JK) = REPH2O
    ENDIF
    ZQIWP(JL,JK)=PQIWP(JL,JK)
    IF (PQIWP(JL,JK) <= REPH2O) THEN
      ZQIWP(JL,JK) = REPH2O
    ENDIF
    IF (PCLFR(JL,JK) > REPCLC) THEN
      ZQRWP(JL,JK)=PQRWP(JL,JK)/PCLFR(JL,JK)
      ZQSWP(JL,JK)=PQSWP(JL,JK)/PCLFR(JL,JK)
    ELSE
      ZQRWP(JL,JK) = 0.0_JPRB
      ZQSWP(JL,JK) = 0.0_JPRB
    ENDIF
  ENDDO
ENDDO

!     ------------------------------------------------------------------

!*         4.     OZONE AND AEROSOLS

IF(.NOT.LRAYFM) THEN
  CALL  RADACA ( YDEAERD,YDERAD, YDRIP, KIDIA , KFDIA , KLON , KLEV,&
   & PAPRS, PGELAM, PGEMU, PCLON, PSLON, PTH,&
   & ZQAER, ZDUMAER, ZQOZ, ZDUM,&
   & ZDUM, ZDUM, ZDUM, ZDUM, ZDUM, ZDUM )  

  IF (NOZOCL == 1.AND..NOT.LEPO3RA .AND..NOT.LPHYLIN) THEN
    CALL RADOZC ( YDRIP%YREOZOC, KIDIA , KFDIA , KLON, KLEV,&
     & 1     , KLON , 0,&
     & PAPRS , PGEMU,&
     & ZQOZ  )  
  ENDIF

ENDIF

IF (NAER == 0) THEN
  DO JAER = 1 , 6
    DO JK = 1 , KLEV
      DO JL = KIDIA,KFDIA
        ZQAER(JL,JAER,JK) = RCAEROS
      ENDDO
    ENDDO
  ENDDO
ELSE
  DO JK = 1 , KLEV
    DO JL = KIDIA,KFDIA
!            ZQAER(JL,4,JK) = RCAEROS
      ZQAER(JL,5,JK) = RCAEROS
    ENDDO
  ENDDO
ENDIF

!     ------------------------------------------------------------------

!*         5.      CALL TO ACTUAL RADIATION SCHEME 

IF (.NOT.LSRTM) THEN

  CALL RADLSW&
   & (YDDIMV, YDMODEL%YRML_PHY_RAD,YDEPHLI,YDMODEL%YRML_PHY_SLIN%YRPHNC,YDMODEL%YRML_PHY_EC%YRECLD, &
   & KIDIA , KFDIA , KLON  , KLEV  ,  NMODE , NAER,&
   & ZRII0,&
   & ZQAER , PALBD , PALBP , PAPRS , PAPRSF,&
   & PCCNL , PCCNO ,&
   & RCARDI, ZCLFR , PDP   , PEMIR , PEMIW , PSLM  , ZAMU0 , ZQOZ,&
   & ZQ    , ZQIWP , ZQLWP , ZQS ,&
   & PTH   , PT    , PTS   , ZNBAS , ZNTOP,&
   & PEMIT , ZFRTHC , ZFRTH , ZFRSOC , ZFRSO,&
   & ZFRSOD, ZSUDU , ZUVDF  , ZPARF , ZPARCF , ZTINCF,&
   & ZSFSWDIR,ZSFSWDIF,ZFSDNN,ZFSDNV,&
   & .FALSE., ZDUMMY, ZDUMMY, ZDUMMY, ZDUMMY2)

ELSE


  DO JK=1,KLEV
    DO JL=KIDIA,KFDIA
      ZCO2(JL,JK)=RCARDI
      ZCH4(JL,JK)=RCH4
      ZN2O(JL,JK)=RN2O
      ZNO2(JL,JK)=RNO2
      ZC11(JL,JK)=RCFC11
      ZC12(JL,JK)=RCFC12
      ZC22(JL,JK)=RCFC22
      ZCL4(JL,JK)=RCCL4
    ENDDO
  ENDDO
  ZQAERO(KIDIA:KFDIA,1:KLEV,1:NAERO)=RCAEROS
                                          

  CALL RADLSWR&
   &(YDDIMV, YDMODEL, KIDIA , KFDIA , KLON  , KLEV  , NAERO ,&
   &ZRII0 ,&
   &ZQAER , ZQAERO, PALBD , PALBP , PAPRS , PAPRSF,&
   &PCCNL , PCCNO , PGELAM, PGEMU ,&
   &ZCO2  , ZCH4  , ZN2O  , ZNO2  , ZC11  , ZC12  , ZC22  , ZCL4 ,&
   &ZCLFR , PDP   , PEMIR , PEMIW , PSLM  , ZAMU0 , ZQOZ  ,&
   &ZQ    , ZQIWP , ZQSWP , ZQLWP , ZQRWP ,&
   &PTH   , PT    , PTS   ,&
   &PEMIT , ZFRTHC, ZFRTH , ZFRSOC , ZFRSO, ZFRSOD, PFRTED,&
   &ZFRSODC, ZFRTEDC,&
   &ZSUDU , ZUVDF , ZPARF , ZPARCF , ZTINCF,&
   &ZFDIR , ZFDIF , ZCDIR , ZDUMMY3, ZDUMMY4, ZDUMMY4&
   & )

ENDIF


!     ------------------------------------------------------------------

!*         6.     TRANSFORM FLUXES TO MODEL HISTORICAL VARIABLES

! 600 CONTINUE

DO JK=1,KLEV+1
  DO JL=KIDIA,KFDIA
    PTRSO(JL,JK)=ZFRSO(JL,JK)/(ZRII0*ZAMU0(JL))
    PEMTD(JL,JK)=ZFRTH(JL,JK)
  ENDDO
ENDDO

DO JL=KIDIA,KFDIA
  PTRSOD(JL)=ZFRSOD(JL)/(ZRII0*ZAMU0(JL))
!direct beam in Sun's direction. 
!computation of sunshine duration
!(direct beam >120 W/m2) This is
!done in radheatn when radiation is called via radintg
!as in operational code!!!
  PDSRP(JL) =ZSUDU(JL)
  PSUDU(JL) =ZSUDU(JL)
  IF (PDSRP(JL) >= RSUNDUR) THEN
    PSDUR(JL)=1.0_JPRB
  ELSE
    PSDUR(JL)=0.0_JPRB
  ENDIF
ENDDO

DO JL=KIDIA,KFDIA
  PCTRSO(JL,1) =ZFRSOC(JL,1)/(ZRII0*ZAMU0(JL))
  PCTRSO(JL,2) =ZFRSOC(JL,KLEV+1)/(ZRII0*ZAMU0(JL))

  PCEMTR(JL,1)=ZFRTHC(JL,     1)
  PCEMTR(JL,2)=ZFRTHC(JL,KLEV+1)
ENDDO

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('RADINA',1,ZHOOK_HANDLE)
END SUBROUTINE RADINA
