! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE VARFPOS(YDRQDYN,YDFPDATA,YDRQPHY,LDCFU,LDXFU,YDGEOMETRY,YDGMV,YDGFL,YDSURF,YDCFU,YDXFU,YDMODEL, &
 & PWSXI,PWDXI,PCFUBUF,PXFUBUF,KCUFNR,PMCUFGP,P2DFIELDS,PGMVS,P3DFIELDS,P3DGFL,KP3LEVS,KP3FIELDS)

!**** *VARFPOS*  - A complete step of post-processing for a single kind of pp level and arrays instead of files in output 

!     Purpose.
!     --------
!           performs a complete step of post-processing :
!            - physical fields post-processing
!            - dynamical fields post-processing
!            + post event in the case of Arpege/Arome

!**   Interface.
!     ----------
!        *CALL* *VARFPOS

!        Explicit arguments :
!        --------------------
!           LDCFU   : True if post-processing of cumulated fluxes
!           LDXFU   : True if post-processing of instantaneous fluxes
!           YDGEOMETRY : input model geometry
!           YDGMV   : input GMV fields
!           YDGFL   : input GFL fields
!           YDSURF  : input surface fields
!           YDCFU   : input cumulated fluxes metadata
!           YDXFU   : input instantaneous fluxes metadata
!           YDMODEL : input model
!           PWSXI, PWDXI : input max values for soil moisture
!           PCFUBUF : input cumulated fluxes
!           PXFUBUF : input instantaneous fluxes
!           PMCUFGP : monitoring of coupling update frequency
!           P2DFIELDS : alternative 2D output array to PBUF
!           PGMVS   : alternative 2D output array to PBUF
!           P3DFIELDS : alternative 3D output array to PBUF
!           P3DGFL  : alternative 3D output array to PBUF for GFL
!           KP3LEVS : number of levels for each field in P3D*
!           KP3FIELDS : number of fields in P3D*

!        Implicit arguments :
!        --------------------
!        None

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      R. El Khatib *METEO-FRANCE*
!      Original : 31-Jan-2017

!     Modifications.
!     R. El Khatib 15-Jun-2018 option NFPWRITE=-1 to disable norms
!     R. El Khatib : 06-Jun-2019 split stepo_fpos to avoid multiple horizontal interpolation of model fields
!     ------------------------------------------------------------------

USE PARKIND1      , ONLY : JPIM,    JPRB, JPRD
USE YOMHOOK       , ONLY : LHOOK,   DR_HOOK, JPHOOK
USE YOMLUN        , ONLY : NULOUT
USE YOMCT0        , ONLY : LARPEGEF ,LOPDIS
USE GEOMETRY_MOD  , ONLY : GEOMETRY
USE YOMGMV        , ONLY : TGMV
USE YOMGFL        , ONLY : TGFL
USE YOMCFU        , ONLY : TCFU
USE YOMXFU        , ONLY : TXFU
USE TYPE_MODEL    , ONLY : MODEL
USE PARFPOS       , ONLY : JPOSDYN
USE FULLPOS       , ONLY : TFPDATA
USE YOMFPC        , ONLY : LALLOFP, LTRACEFP
USE YOM4FPOS      , ONLY : TRQFPDYN
USE YOMFPGEOMETRY , ONLY : TFPGEOMETRY, LFPOSBUF
USE YOMFP4L       , ONLY : TRQFP, IFPSEARCH
USE YOMTIM        , ONLY : RSTART   ,RVSTART  ,RTIMEF
USE TYPE_FPRQDYNS , ONLY : TYPE_FPRQDYN, ALLOCATE_FPRQDYN, INQUIRE_FPRQDYN
USE YOMAFN        , ONLY : TAFN
USE TYPE_FPOSBUF  , ONLY : FPOSBUF
USE SURFACE_FIELDS_MIX , ONLY : TSURF

IMPLICIT NONE

TYPE(TRQFPDYN)    , INTENT(IN) :: YDRQDYN
TYPE(TFPDATA)     , INTENT(IN) :: YDFPDATA
TYPE(TRQFP)       , INTENT(IN) :: YDRQPHY
LOGICAL           , INTENT(IN) :: LDCFU
LOGICAL           , INTENT(IN) :: LDXFU
TYPE(GEOMETRY)    , INTENT(IN) :: YDGEOMETRY
TYPE(TGMV)        , INTENT(IN) :: YDGMV
TYPE(TGFL)        , INTENT(IN) :: YDGFL
TYPE(TSURF)       , INTENT(IN) :: YDSURF
TYPE(TCFU)        , INTENT(IN) :: YDCFU
TYPE(TXFU)        , INTENT(IN) :: YDXFU
TYPE(MODEL)       , INTENT(IN) :: YDMODEL
REAL(KIND=JPRB)   , INTENT(IN) :: PWSXI
REAL(KIND=JPRB)   , INTENT(IN) :: PWDXI
REAL(KIND=JPRB)   , INTENT(IN), TARGET :: PCFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDCFU%NFDCFU,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   , INTENT(IN), TARGET :: PXFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDXFU%NFDXFU,YDGEOMETRY%YRDIM%NGPBLKS)
INTEGER(KIND=JPIM), INTENT(IN) :: KCUFNR
REAL(KIND=JPRB)   , INTENT(IN) :: PMCUFGP(YDGEOMETRY%YRDIM%NPROMA,KCUFNR,YDGEOMETRY%YRDIM%NGPBLKS)
INTEGER(KIND=JPIM), INTENT(IN) :: KP3LEVS
INTEGER(KIND=JPIM), INTENT(IN) :: KP3FIELDS
REAL(KIND=JPRB)   , INTENT(INOUT), OPTIONAL :: P2DFIELDS(YDFPDATA%YFPOS%YFPGEOMETRY%YFPGEO%NFPROMA,YDRQPHY%NFIELDG,YDFPDATA%YFPOS%YFPGEOMETRY%YFPGEO%NFPBLOCS)
REAL(KIND=JPRB)   , ALLOCATABLE, INTENT(INOUT), OPTIONAL :: PGMVS(:,:,:)
REAL(KIND=JPRB)   , INTENT(INOUT), OPTIONAL :: P3DFIELDS(YDFPDATA%YFPOS%YFPGEOMETRY%YFPGEO%NFPROMA,KP3LEVS,KP3FIELDS,YDFPDATA%YFPOS%YFPGEOMETRY%YFPGEO%NFPBLOCS)
REAL(KIND=JPRB)   , ALLOCATABLE, INTENT(INOUT), OPTIONAL :: P3DGFL(:,:,:,:)

TYPE(TYPE_FPRQDYN) :: YLQTYPE
TYPE(FPOSBUF)     :: YLAUX
TYPE(TRQFP) :: YLRQSP
TYPE(TRQFP) :: YLRQGP

!     CLVER : Configuration for vertical post-processing
!     CLHOR : Configuration for horizontal post-processing
!     CLWFP : Configuration for I/Os

CHARACTER(LEN=1)  :: CLVER,CLHOR,CLWFP
CHARACTER(LEN=9)  :: CLOPDIS ! config displayed for opdis

INTEGER(KIND=JPIM) :: IFPDOM, IPPLEV, ITER, ILMOD(JPOSDYN), IGPX(JPOSDYN)
INTEGER(KIND=JPIM) :: IPTRCFU, IPTRXFU, IXFIS
INTEGER(KIND=JPIM) :: IFLDPTRCFU(YDCFU%NFDCFU), IFLDPTRXFU(YDXFU%NFDXFU)
INTEGER(KIND=JPIM), ALLOCATABLE :: ICOD(:)
LOGICAL :: LLOWPASS, LLPHYS, LLHPOS, LLEZO, LLSURF, LLNHDYN
REAL(KIND=JPRD) :: ZCT, ZVT, ZWT
REAL(KIND=JPRB), POINTER :: ZCFUBUF(:,:,:), ZXFUBUF(:,:,:), ZFPBUF(:,:,:), ZAUXBUF(:,:,:), ZABUF(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZSPEC(:,:), ZPPLEV(:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "user_clock.intfb.h"

#include "sufptr2.intfb.h"
#include "gridfpos.intfb.h"
#include "fpgpnorm.intfb.h"
#include "sufporog.intfb.h"
#include "fpmodcfu.intfb.h"
#include "fpmodxfu.intfb.h"
#include "fpmodprec.intfb.h"
#include "stepo_fpos_vh.intfb.h"
#include "stepo_fpos_hv.intfb.h"
#include "stepo_fpos_hvlag.intfb.h"
#include "lcheck4nhfields.intfb.h"
#include "suvpos.intfb.h"
#include "suvfposl.intfb.h"
#include "cpvpospr.intfb.h"
#include "opdis.intfb.h"

#include "abor1.intfb.h"

!      -----------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('VARFPOS',0,ZHOOK_HANDLE)
ASSOCIATE(YDFPOS=>YDFPDATA%YFPOS)
ASSOCIATE(YDFPGEOMETRY=>YDFPOS%YFPGEOMETRY, YDFPFILTERS=>YDFPOS%YFPFILTERS, YDFPIOH=>YDFPOS%YFPIOH, YDAFN=>YDFPOS%YAFN, &
 & YDFPVAB=>YDFPOS%YFPVAB, YDFPSTRUCT=>YDFPOS%YFPSTRUCT, YDFPWSTD=>YDFPOS%YFPWSTD,YDFPCNT=>YDFPOS%YFPCNT, &
 & YDNAMFPSCI=>YDFPOS%YNAMFPSCI, YDNAMFPINT=>YDFPOS%YNAMFPINT, NFLEVG=>YDGEOMETRY%YRDIMV%NFLEVG)
ASSOCIATE(TFP=>YDAFN%TFP, TFP_DYNDS=>YDAFN%TFP_DYNDS, GFP_PHYDS=>YDAFN%GFP_PHYDS, GFP=>YDAFN%GFP, &
 & NSFXPRE_CNT=>YDAFN%NSFXPRE_CNT, NFPCLI=>YDNAMFPSCI%NFPCLI, YDFPGEO_DEP=>YDFPGEOMETRY%YFPGEO_DEP, &
 & YDFPGEO=>YDFPGEOMETRY%YFPGEO, YDFPGIND=>YDFPGEOMETRY%YFPGIND, YDFPUSERGEO=>YDFPGEOMETRY%YFPUSERGEO, &
 & YDFPOFN=>YDFPIOH%YFPOFN(:), YDFPOPH=>YDFPIOH%YFPOPH(:), YDNAMFPIOS=>YDFPIOH%YNAMFPIOS, NFPCONF=>YDFPCNT%NFPCONF, &
 & NFPINPHY=>YDNAMFPINT%NFPINPHY)
ASSOCIATE(NFPROMA=>YDFPGEO%NFPROMA, NFPBLOCS=>YDFPGEO%NFPBLOCS, NFPRGPL=>YDFPGEO%NFPRGPL, LFPOSHOR=>YDFPGEOMETRY%LFPOSHOR, &
 & LMPHYS=>YDMODEL%YRML_PHY_MF%YRPHY%LMPHYS, LEPHYS=>YDMODEL%YRML_PHY_EC%YREPHY%LEPHYS, NFPRESOL=>YDFPUSERGEO(:)%NFPRESOL, &
 & NFPRGPG=>YDFPGEO%NFPRGPG, NSPEC2=>YDFPUSERGEO(:)%NSPEC2, LFPMODELSPEC=>YDFPUSERGEO(:)%LFPMODELSPEC, &
 & NFPSIZEG=>YDFPUSERGEO(:)%NFPSIZEG,CFPDOM=>YDFPUSERGEO(:)%CFPDOM, YDCLIMO=>YDFPDATA%YFPCLIMO, &
 & NFPWRITE=>YDNAMFPIOS%NFPWRITE, NSPEC2G=>YDFPUSERGEO(:)%NSPEC2G, NFPXFLD=>YDNAMFPIOS%NFPXFLD)


IFPDOM=SIZE(YDFPOS%YFPGEOMETRY%YFPUSERGEO)

! LLHPOS tells if any horizontal post-processing is active(core or E-zone).
! (otherwise model-shaped buffer are used, meaning for LAM the E-zone is included)
! Somehow this is a hack :-(
LLHPOS=LFPOSBUF(YDFPGEOMETRY)
! Unfortunately, for now climatology is supported only through the horizontal
! interpolations mechanizm, so we should extend the activation of LLHPOS :
LLHPOS=LLHPOS.OR.(NFPCLI>0)
! Should only the truncation change, then LLHPOS could remain .false. But this
! mean going to apache via pos which is not yet re-coded. For now therefore we force LLHPOS=true
!(though the mechanism already works for surface-independent post-processing) :
LLHPOS=LLHPOS.OR.((.NOT.(ALL(LFPMODELSPEC(:)))).AND.NFPCONF==2)
! Alas again, if NFPCONF=1 there is no mechanism yet to transfer the output arrays from
! pos (gpp, hfpbuf) directly to the input arrays for fullpos I/Os (hfpbuf)
! so we should extend again the activation of LLHPOS :
! (However it would work exceptionally if no spectral fit => empty gpp array).
! so we do:
LLHPOS=LLHPOS.OR.(NFPCONF==1)

! LLEZO : .TRUE. if an extension zone computation is active
LLEZO = ANY(YDFPUSERGEO(:)%LFPBIPER)

IF(LTRACEFP) THEN
  WRITE(UNIT=NULOUT,FMT='('' LLEZO = '',L2,'' LLHPOS = '',L2)') LLEZO, LLHPOS
ENDIF


! Pre-processing : setup auxilary data post-processing
WRITE(NULOUT,'('' == Full-Pos : setup auxilary data == '')')
LLPHYS=LEPHYS.OR.LMPHYS
CALL SUFPTR2(YDRQPHY,YLAUX%YRQPHY,NFPINPHY,YDNAMFPSCI,YDAFN,LLPHYS,LLHPOS,LFPOSHOR,YDRQDYN)

IPTRCFU=0
IPTRXFU=0
ZCFUBUF=>PCFUBUF(:,:,:)
ZXFUBUF=>PXFUBUF(:,:,:)

IF (YDRQPHY%NFIELDG > 0 .OR. YLAUX%YRQPHY%NFIELDG > 0) THEN

!*  MODIFY PRECIPITATIONS FIELDS (a second copy may be avoided if we know if cfu/xfu are already copies)
!                                (case of packing) => inout allowed)

  IF (LFPOSHOR.AND.(LDCFU.OR.LDXFU)) THEN
    ALLOCATE(ICOD(YLAUX%YRQPHY%NFIELDG+YDRQPHY%NFIELDG))
    ICOD(1:YLAUX%YRQPHY%NFIELDG)=YLAUX%YRQPHY%ICOD(1:YLAUX%YRQPHY%NFIELDG)
    ICOD(YLAUX%YRQPHY%NFIELDG+1:YLAUX%YRQPHY%NFIELDG+YDRQPHY%NFIELDG)=YDRQPHY%ICOD(1:YDRQPHY%NFIELDG)
    IF (LDCFU) THEN
      CALL FPMODCFU(GFP,YDCFU,ICOD,NFLEVG,IPTRCFU,IFLDPTRCFU)
      IF (IPTRCFU > 0) THEN
        NULLIFY(ZCFUBUF)
        ALLOCATE(ZCFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDCFU%NFDCFU,YDGEOMETRY%YRDIM%NGPBLKS))
        ZCFUBUF(:,:,:)=PCFUBUF(:,:,:)
        CALL FPMODPREC(YDFPSTRUCT,YDGEOMETRY,IPTRCFU,ZCFUBUF,IFLDPTRCFU)
      ENDIF
    ENDIF
    IF (LDXFU) THEN
      CALL FPMODXFU(GFP,YDXFU,ICOD,IPTRXFU,IFLDPTRXFU)
      IF (IPTRXFU > 0) THEN
        NULLIFY(ZXFUBUF)
        ALLOCATE(ZXFUBUF(YDGEOMETRY%YRDIM%NPROMA,YDXFU%NFDXFU,YDGEOMETRY%YRDIM%NGPBLKS))
        ZXFUBUF(:,:,:)=PXFUBUF(:,:,:)
        CALL FPMODPREC(YDFPSTRUCT,YDGEOMETRY,IPTRXFU,ZXFUBUF,IFLDPTRXFU)
      ENDIF
    ENDIF
  ENDIF

ENDIF

!*       5. PERFORM POST-PROCESSING ON AUXILARY SURFACE FIELDS
!           --------------------------------------------------

ALLOCATE(YLAUX%FPBUF(NFPROMA,YLAUX%YRQPHY%NFIELDG,NFPBLOCS))

IF (YLAUX%YRQPHY%NFIELDG > 0) THEN

  ! Physical fields post-processing
  CALL GRIDFPOS(YLAUX%YRQPHY,YDNAMFPINT,YDNAMFPSCI,YDAFN,NFPXFLD,YDFPGEOMETRY,YDFPDATA,PWSXI,PWDXI,YDFPWSTD,YDFPSTRUCT,'G',LLEZO, &
   & IFPDOM,YDGEOMETRY,YDSURF,YDCFU,YDXFU,YDMODEL,ZCFUBUF,ZXFUBUF,ZAUXBUF,P2DFIELDS=YLAUX%FPBUF,KP3LEVS=0,KP3FIELDS=0)
  NULLIFY(ZAUXBUF)

!*       5.4 Spectral fit of interpolated orography

  IF (NFPCONF == 2 .AND. NFPCLI == 0) THEN
    IXFIS=IFPSEARCH(YLAUX%YRQPHY,GFP%SFIS%ICOD)
    IF (IXFIS > 0) THEN
      CALL SUFPOROG(YLAUX%YRQPHY%NFIELDG,IXFIS,YDFPGEO,IFPDOM,NFPRESOL,NSPEC2,YLAUX%FPBUF)
    ENDIF
  ENDIF

ENDIF


!*       6. PERFORM POST-PROCESSING ON MAIN SURFACE FIELDS
!           ----------------------------------------------


IF (YDRQPHY%NFIELDG > 0) THEN

  NULLIFY(ZFPBUF)

  CALL GRIDFPOS(YDRQPHY,YDNAMFPINT,YDNAMFPSCI,YDAFN,NFPXFLD,YDFPGEOMETRY,YDFPDATA,PWSXI,PWDXI,YDFPWSTD,YDFPSTRUCT,'P',LLEZO, &
   & IFPDOM,YDGEOMETRY,YDSURF,YDCFU,YDXFU,YDMODEL,ZCFUBUF,ZXFUBUF,ZFPBUF, &
   & YDAUX=YLAUX,P2DFIELDS=P2DFIELDS,P3DFIELDS=P3DFIELDS,KP3LEVS=KP3LEVS,KP3FIELDS=KP3FIELDS)


  IF (NFPWRITE >= 0) THEN
    ! Norms
    IF (LARPEGEF) THEN
      CALL FPGPNORM(NFPXFLD,YDFPGEO,IFPDOM,CFPDOM,NFPRESOL,NFPSIZEG,PGP=ZFPBUF,LDSURF=YDRQPHY%LLSURF,&
       & CDPREF=YDRQPHY%CLPREF,KDOM=YDRQPHY%IDOM,KDOMPTR=YDRQPHY%IDMP,&
       & CDNAME=YDRQPHY%CLNAME)
    ELSE
      CALL FPGPNORM(NFPXFLD,YDFPGEO,IFPDOM,CFPDOM,NFPRESOL,NFPSIZEG,PGP=ZFPBUF,LDSURF=YDRQPHY%LLSURF, &
       & CDPREF=YDRQPHY%CLPREF,KDOM=YDRQPHY%IDOM,KDOMPTR=YDRQPHY%IDMP,&
       & CDNAME=YDRQPHY%CLNAME,KGRIB=YDRQPHY%IGRIB)
    ENDIF
  ENDIF

  IF (ASSOCIATED(ZFPBUF)) THEN
    IF (.NOT.(PRESENT(P3DFIELDS).OR.PRESENT(P2DFIELDS))) THEN
      DEALLOCATE(ZFPBUF)
    ENDIF
    NULLIFY(ZFPBUF)
  ENDIF

ENDIF

IF (IPTRCFU > 0) THEN
  DEALLOCATE(ZCFUBUF)
ELSE
  NULLIFY(ZCFUBUF)
ENDIF
IF (IPTRXFU > 0) THEN
  DEALLOCATE(ZXFUBUF)
ELSE
  NULLIFY(ZXFUBUF)
ENDIF


  !*     2.1 INITIALIZE CONFIGURATION

  ! Eta levels :
  IPPLEV=YDRQDYN%YES%NPXLEV
  ALLOCATE(ZPPLEV(IPPLEV))
  IF (IPPLEV > 0) THEN
    ZPPLEV(1:IPPLEV)=YDRQDYN%YES%ZPXLEV(1:IPPLEV)
  ENDIF
  CLVER='S'
  CALL ALLOCATE_FPRQDYN(YLQTYPE,IFPDOM,IPPLEV)
  IF (LALLOFP) THEN
    CALL INQUIRE_FPRQDYN(YLQTYPE,'YLQTYPE',NULOUT)
  ENDIF
  ! only one scan => LLSURF=.TRUE.
  LLSURF=.TRUE.
  LLOWPASS=.FALSE.
  IF (.NOT.LLHPOS) THEN
    CLHOR='0'
  ELSE
    CLHOR='I'
  ENDIF
  CLWFP='S'
  CALL SUVPOS(YLQTYPE,YDRQDYN%YES,YDRQDYN%Y2D,YDAFN,NFPCONF,CLVER,CLHOR,LLSURF,LLOWPASS,LDSP=.FALSE.,LDSORT=.TRUE.)
  CALL CPVPOSPR(NFPCONF,YDAFN,YLQTYPE)

  IF (YLQTYPE%NFPDYNB > 0) THEN

    !*       2.2 POST-PROCESSING STEP

    ITER=0
    CALL USER_CLOCK(PELAPSED_TIME=ZWT,PTOTAL_CP=ZCT,PVECTOR_CP=ZVT)
    ZCT=ZCT-RSTART
    ZVT=ZVT-RVSTART
    ZWT=ZWT-RTIMEF
    RSTART=RSTART+ZCT
    RVSTART=RVSTART+ZVT
    RTIMEF=RTIMEF+ZWT
    IF (LOPDIS) THEN
      CLOPDIS(1:9)='FULLPOS-'//CLVER
      CALL OPDIS(CLOPDIS,'DYNFPOS   ',ZCT,ZVT,ZWT,RSTART,RTIMEF,ITER,YDMODEL%YRML_DYN%YRDYNA%LNHDYN)
    ENDIF

    NULLIFY(ZFPBUF)

    IF (CLHOR /= 'I') THEN
      IF (PRESENT(P3DGFL)) THEN
        CALL STEPO_FPOS_VH(YLQTYPE,YLAUX,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,NFPXFLD,YDFPOS,IFPDOM,YDGEOMETRY,YDGMV,YDGFL, &
         & YDSURF,YDXFU,KCUFNR,PMCUFGP,YDMODEL,CLVER,CLHOR,IPPLEV,ZPPLEV,LLHPOS,LLEZO,ZFPBUF,ZSPEC, &
         & P2DFIELDS=PGMVS,P3DFIELDS=P3DGFL,KP3FIELDS=0)
      ELSEIF (PRESENT(P3DFIELDS)) THEN
        IF(IPPLEV /= KP3LEVS) CALL ABOR1('VARFPOS : ERROR IN LEVEL NUMBER')
        CALL STEPO_FPOS_VH(YLQTYPE,YLAUX,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,NFPXFLD,YDFPOS,IFPDOM,YDGEOMETRY,YDGMV,YDGFL, &
         & YDSURF,YDXFU,KCUFNR,PMCUFGP,YDMODEL,CLVER,CLHOR,IPPLEV,ZPPLEV,LLHPOS,LLEZO,ZFPBUF,ZSPEC, &
         & P2DFIELDS=PGMVS,P3DPHYS=P3DFIELDS,KP3FIELDS=KP3FIELDS)
      ELSE
        CALL STEPO_FPOS_VH(YLQTYPE,YLAUX,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,NFPXFLD,YDFPOS,IFPDOM,YDGEOMETRY,YDGMV,YDGFL, &
         & YDSURF,YDXFU,KCUFNR,PMCUFGP,YDMODEL,CLVER,CLHOR,IPPLEV,ZPPLEV,LLHPOS,LLEZO,ZFPBUF,ZSPEC, &
         & P2DFIELDS=PGMVS,KP3FIELDS=0)
      ENDIF
    ELSE
      NULLIFY(ZABUF)
      ! A bit awkward : we have to find in NH primitive fields on model levels 
      ! should be preprocessed and horizontally interpolated :
      LLNHDYN=YDMODEL%YRML_DYN%YRDYNA%LNHDYN
      CALL LCHECK4NHFIELDS(LLNHDYN,TFP,YD3=YDRQDYN%YES,YD2=YDRQDYN%Y2D)
      IF(LTRACEFP) THEN
        WRITE(UNIT=NULOUT,FMT='('' LFPNHDYN = '',L2)') LLNHDYN 
      ENDIF

      CALL STEPO_FPOS_HV(LLNHDYN,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,NFPXFLD,YDFPOS,IFPDOM,YDGEOMETRY,YDGMV,YDGFL, &
       & YDSURF,YDXFU,KCUFNR,PMCUFGP,YDMODEL,LLHPOS,IGPX,LLEZO,ZABUF,ILMOD)
      IF (PRESENT(P3DGFL)) THEN
        CALL STEPO_FPOS_HVLAG(ILMOD,YLQTYPE,YLAUX,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,NFPXFLD,YDFPOS,IFPDOM,YDGEOMETRY, &
         & YDSURF,KCUFNR,YDMODEL,CLVER,IPPLEV,ZPPLEV,0,IGPX,ZABUF,ZFPBUF,ZSPEC, &
         & P2DFIELDS=PGMVS,P3DFIELDS=P3DGFL)
      ELSEIF (PRESENT(P3DFIELDS)) THEN
        IF(IPPLEV /= KP3LEVS) CALL ABOR1('VARFPOS : ERROR IN LEVEL NUMBER')
        CALL STEPO_FPOS_HVLAG(ILMOD,YLQTYPE,YLAUX,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,NFPXFLD,YDFPOS,IFPDOM,YDGEOMETRY, &
         & YDSURF,KCUFNR,YDMODEL,CLVER,IPPLEV,ZPPLEV,KP3FIELDS,IGPX,ZABUF,ZFPBUF,ZSPEC, &
         & P2DFIELDS=PGMVS,P3DPHYS=P3DFIELDS)
      ELSE
        CALL STEPO_FPOS_HVLAG(ILMOD,YLQTYPE,YLAUX,YDCLIMO,YDNAMFPINT,YDNAMFPSCI,NFPXFLD,YDFPOS,IFPDOM,YDGEOMETRY, &
         & YDSURF,KCUFNR,YDMODEL,CLVER,IPPLEV,ZPPLEV,0,IGPX,ZABUF,ZFPBUF,ZSPEC, &
         & P2DFIELDS=PGMVS)
      ENDIF

      ! just in case ...
      IF (ASSOCIATED(ZABUF)) THEN
        DEALLOCATE(ZABUF)
        NULLIFY(ZABUF)
      ENDIF
    ENDIF

  !*     2.2 I/Os and computation of norms

    CALL SUVFPOSL(YLQTYPE,YLRQSP,YLRQGP,TFP_DYNDS(:)%IGRIB,TFP_DYNDS(:)%LLSRF,TFP_DYNDS(:)%CLNAME,IFPDOM,IPPLEV, &
     & ZPPLEV,NFPCONF,CLWFP)

    IF (NFPWRITE >= 0) THEN
      ! GRIDPOINT NORMS
      IF (YLRQGP%NFIELDG > 0) THEN
        IF (LARPEGEF) THEN
          CALL FPGPNORM(NFPXFLD,YDFPGEO,IFPDOM,CFPDOM,NFPRESOL,NFPSIZEG,PGP=ZFPBUF,LDSURF=YLRQGP%LLSURF, &
           & CDPREF=YLRQGP%CLPREF,PLEV=YLRQGP%ZLEV,KDOM=YLRQGP%IDOM,KDOMPTR=YLRQGP%IDMP, &
           & CDNAME=YLRQGP%CLNAME,CDCONF=CLWFP)
        ELSE
          CALL FPGPNORM(NFPXFLD,YDFPGEO,IFPDOM,CFPDOM,NFPRESOL,NFPSIZEG,PGP=ZFPBUF,LDSURF=YLRQGP%LLSURF, &
           & CDPREF=YLRQGP%CLPREF,PLEV=YLRQGP%ZLEV,KDOM=YLRQGP%IDOM,KDOMPTR=YLRQGP%IDMP, &
           & CDNAME=YLRQGP%CLNAME,KGRIB=YLRQGP%IGRIB,CDCONF=CLWFP)
        ENDIF
      ENDIF
    ENDIF

  !   Deallocate descriptors
    CALL SUVFPOSL(YLQTYPE,YLRQSP,YLRQGP,TFP_DYNDS(:)%IGRIB,TFP_DYNDS(:)%LLSRF,TFP_DYNDS(:)%CLNAME,IFPDOM,IPPLEV,ZPPLEV)

  !   Deallocate output data arrays

    IF (ASSOCIATED(ZFPBUF)) THEN
      IF (.NOT.(PRESENT(P3DGFL).OR.PRESENT(PGMVS).OR.PRESENT(P3DFIELDS))) THEN
        DEALLOCATE(ZFPBUF)
      ENDIF
      NULLIFY(ZFPBUF)
    ENDIF

  ENDIF ! NFPDYNB >0


END ASSOCIATE
END ASSOCIATE
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('VARFPOS',1,ZHOOK_HANDLE)
!      -----------------------------------------------------------------

END SUBROUTINE VARFPOS
