! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

INTERFACE
SUBROUTINE FPBIPERE(KDLUX,KDGUX,KDLON,KDGL,KNUBI,KD1,PGPBI,KDADD,LDZON,&
& LDBOYD,KDBOYD,PLBOYD,PBIPOUT)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KNUBI
INTEGER(KIND=JPIM),INTENT(IN) :: KD1
INTEGER(KIND=JPIM),INTENT(IN) :: KDLUX
INTEGER(KIND=JPIM),INTENT(IN) :: KDGUX
INTEGER(KIND=JPIM),INTENT(IN) :: KDLON
INTEGER(KIND=JPIM),INTENT(IN) :: KDGL
INTEGER(KIND=JPIM),INTENT(IN) :: KDADD
REAL(KIND=JPRB) ,INTENT(INOUT):: PGPBI(KD1,KNUBI)
LOGICAL, OPTIONAL ,INTENT(IN) :: LDZON
LOGICAL, OPTIONAL ,INTENT(IN) :: LDBOYD
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KDBOYD(6)
REAL(KIND=JPRB)   , INTENT(IN), OPTIONAL :: PLBOYD
REAL(KIND=JPRB)   ,INTENT(OUT), OPTIONAL :: PBIPOUT(:,:)
END SUBROUTINE FPBIPERE
END INTERFACE
