! (C) Copyright 1989- Meteo-France.

SUBROUTINE CPFPFILTER(YDGEOMETRY,CDDILA,CDCONT,KFPDOM,KFPCMAX,PSEL,KFMAX,PBED,PLTF, &
  & LDBED,KCMAX,PSTRET,PMAXDEV,LDFPFIL,PFPFIL,PFPMAT)

!**** *CPFPFILTER*  - COMPUTE MATRIXES FOR POST-PROCESSING SPECTRAL FILTER

!     PURPOSE.
!     --------
!        To initialize the filtering matrixes for the post-processing of
!        derivatives

!**   INTERFACE.
!     ----------
!       *CALL* *CPFPFILTER*

!        EXPLICIT ARGUMENTS
!         --------------------
!          YDGEOMETRY : model geometry
!          CDDILA : filename of dilatation matrix
!          CDCONT : filename of contraction matrix
!          KFPDOM : number of subdomains
!          KFPCMAX: maximum truncation for the post-processing
!          PSEL   : coefficient of selectivity of the low-pass filter
!          KFMAX  : maximum truncation of the output subdomains.
!          PBED : coefficient of the exponential function in the low-pass filter.
!          PLTF : coefficient of the exponential function in the gaussian filter
!          LDBED : .TRUE. to use the low-pass filter on the homogenous resolution
!            space (arpege only); otherwise the gaussian filter is used.
!          KCMAX  : maximum truncation read in matrix files or computed
!          PSTRET : model stretching factor
!          PMAXDEV: maximum deviation from identity for for dilatation/contraction matrixes
!          LDFPFIL : .TRUE. if filter active (for each domain)
!          PFPFIL : filters profile for each domain
!          PFPMAT : matrix filters for each domain

!       IMPLICIT ARGUMENTS
!        --------------------

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 22-May-2013 from fpfilter

!     MODIFICATIONS.
!     --------------
!      LF Meunier 19-Jul-2015 Remove useless array and computations. Move
!                             Open-MP to a lower level (to save memory)
!      R. El Khatib 20-jan-2016 Redo B-level distribution over the vertical levels communicator
!                               + computation of Legendre polynomials on the fly
!      P. Marguinaud 04-Oct-2016 Port to single precision
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB, JPRD
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMLUN   , ONLY : NULOUT   ,NULDILA  ,NULCONT
USE YOMFPC   , ONLY : LALLOFP
USE YOMMP0   , ONLY : NPRTRV, NPRTRW, MYSETW, MYSETV
USE DILATATION_MOD, ONLY : DILAT_CALC, DILAT_DEVIATION, DILAT_MAPPING
USE MPL_MODULE, ONLY : MPL_WAIT, JP_NON_BLOCKING_STANDARD, MPL_BROADCAST, MPL_SEND, MPL_RECV
USE MPL_GROUPS, ONLY : MPL_ALL_LEVS_COMM

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY),     INTENT(IN) :: YDGEOMETRY
CHARACTER(LEN=*), INTENT(IN) :: CDDILA
CHARACTER(LEN=*), INTENT(IN) :: CDCONT
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
INTEGER(KIND=JPIM), INTENT(IN) :: KFPCMAX
REAL(KIND=JPRB), INTENT(IN)    :: PSEL(KFPDOM)
INTEGER(KIND=JPIM), INTENT(IN) :: KFMAX(KFPDOM)
REAL(KIND=JPRB),    INTENT(IN) :: PBED
REAL(KIND=JPRB),    INTENT(IN) :: PLTF
LOGICAL,            INTENT(IN) :: LDBED
INTEGER(KIND=JPIM), INTENT(OUT) :: KCMAX(KFPDOM)
REAL(KIND=JPRB), INTENT(IN) :: PSTRET
REAL(KIND=JPRB), INTENT(IN) :: PMAXDEV
LOGICAL,            INTENT(IN) :: LDFPFIL(KFPDOM)
REAL(KIND=JPRB), ALLOCATABLE, INTENT(OUT) :: PFPFIL(:,:)
REAL(KIND=JPRB), ALLOCATABLE, INTENT(OUT) :: PFPMAT(:,:)

!     ZDILALU : dilat. matrix elements related to a zonal wave number
!     ZCONTLU : contract. matrix elements related to a zonal wave number
!     ZDILA   : same as ZDILALU (dilatation only), overdimensioned up to the nearest odd number
!     ZCONT   : same as ZCONTLU (contraction only), overdimensioned up to the nearest odd number
!     ZSPECT  : vector in the spectral work sphere
!     ZSPECC  : vector in the spectral geographical sphere
!     ZFILTC  : filtered vector in the spectral geographical sphere

CHARACTER (LEN = 16) :: CLWAVE

REAL(KIND=JPRB), ALLOCATABLE :: ZSPECT(:,:), ZSPECC(:,:), ZFILTC(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: ZDILA(:,:,:), ZCONT(:,:,:), ZDILALU(:), ZCONTLU(:)
REAL(KIND=JPRB), ALLOCATABLE :: ZPNMC(:,:), ZW(:), ZPNMS(:,:), ZMAPP(:)
REAL(KIND=JPRD), ALLOCATABLE :: ZMU(:)

INTEGER(KIND=JPIM) :: ICMAX, ILONG, ISMIN_DILA, ISMIN_CONT, ISMAX_DILA, ISMAX_CONT
INTEGER(KIND=JPIM) :: ICMXSUR, ICRANGE, INAR, INARI, IOS, IREP, ITMXSUR, ITAG, IR
INTEGER(KIND=JPIM) :: JC, JDOM, JF, IM, JMLOC, JN, IMM1, JT, II, IND
INTEGER(KIND=JPIM) :: IDIMAT, IVNUMP, INIMES, IFACTD
INTEGER(KIND=JPIM) :: IDGNH, IDGLG, IDGL, IDGLHRAW, IDLON, IRESOLS, IRESOLC
INTEGER(KIND=JPIM) :: ID1, ID2, IROOT, IPROC, IOWN0
INTEGER(KIND=JPIM), ALLOCATABLE :: ISRANGE(:), IOFF(:), IREQ(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: IUMPP(:), IALLMS(:), IPTRMS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: IVSET(:), IVMYMS(:), IWMLOC(:)

REAL(KIND=JPRB) :: ZMAX
LOGICAL :: LLDILA, LLCONT, LLOP, LLOPEN

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "setup_trans.h"
#include "trans_inq.h"
#include "mxmaop.h"
#include "trans_release.h"
#include "trans_pnm.h"

#include "abor1.intfb.h"
#include "fpfilter.intfb.h"
#include "set2pe.intfb.h"
#include "sulfi.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('CPFPFILTER',0,ZHOOK_HANDLE)
ASSOCIATE(MYMS=>YDGEOMETRY%YRLAP%MYMS, NSMAX=>YDGEOMETRY%YRDIM%NSMAX, NCMAX=>YDGEOMETRY%YRDIM%NCMAX, &
 & NUMP=>YDGEOMETRY%YRDIM%NUMP)
!     ------------------------------------------------------------------

!*    1.   Spectral setup

WRITE(NULOUT,*) ' Entering CPFPFILTER'

IREP=0
INARI=0
INAR=NSMAX+1
ILONG=1
INIMES=1
CALL SULFI(NULOUT,NSMAX,NCMAX,PSTRET,IFACTD)
INQUIRE(FILE=TRIM(CDDILA),IOSTAT=IOS,EXIST=LLDILA,OPENED=LLOP)
IF (LLDILA) THEN
  LLOPEN=(IOS == 0 .AND. LLOP)
  IF (.NOT.LLOPEN) THEN
    CALL LFIAFM(IREP,NULDILA,IFACTD)
    CALL LFIOUV(IREP,NULDILA,.TRUE.,TRIM(CDDILA),'OLD',.TRUE.,.FALSE.,INIMES,INAR,&
     & INARI)
  ELSE
    CALL LFIPOS(IREP,NULDILA)
  ENDIF
  CALL LFIINTLEC(IREP,NULDILA,'NSMIN',ISMIN_DILA,ILONG)
  CALL LFIINTLEC(IREP,NULDILA,'NSMAX',ISMAX_DILA,ILONG)
ENDIF
INQUIRE(FILE=TRIM(CDCONT),IOSTAT=IOS,EXIST=LLCONT,OPENED=LLOP)
IF (LLCONT) THEN
  LLOPEN=(IOS == 0 .AND. LLOP)
  IF (.NOT.LLOPEN) THEN
    CALL LFIAFM(IREP,NULCONT,IFACTD)
    CALL LFIOUV(IREP,NULCONT,.TRUE.,TRIM(CDCONT),'OLD',.TRUE.,.FALSE.,INIMES,INAR,&
     & INARI)
  ELSE
    CALL LFIPOS(IREP,NULCONT)
  ENDIF
  CALL LFIINTLEC(IREP,NULCONT,'NSMIN',ISMIN_CONT,ILONG)
  CALL LFIINTLEC(IREP,NULCONT,'NSMAX',ISMAX_CONT,ILONG)
ENDIF
IF (LLDILA .AND. .NOT. LLCONT) THEN
  CALL ABOR1('CPFPFILTER : CONTRACTION MATRIX IS MISSING')
ELSEIF(LLCONT .AND. .NOT. LLDILA) THEN
  CALL ABOR1('CPFPFILTER : DILATATION MATRIX IS MISSING')
ELSEIF (LLDILA .AND. LLCONT) THEN
  IF (ISMIN_DILA==ISMIN_CONT .AND. ISMAX_DILA==ISMAX_CONT) THEN
    IF (ISMIN_DILA /= NSMAX) THEN
      CALL ABOR1('CPFPFILTER : MATRIXES MINIMUM TRUNCATION DO NOT MATCH WITH MODEL')
    ELSEIF (ISMAX_DILA < KFPCMAX) THEN
      CALL ABOR1('CPFPFILTER : MATRIXES MAXIMUM TRUNCATION ARE TOO SMALL')
    ELSE
      ICMAX=ISMAX_DILA
      CALL FPFILTER(ICMAX,KFPDOM,LDFPFIL,KFMAX,PSEL,PBED,PLTF,LDBED,PFPFIL)
    ENDIF
  ELSE
    CALL ABOR1('CPFPFILTER : DILATATION AND CONTRACTION MATRIXES DO NOT MATCH')
  ENDIF
ELSE
  WRITE(NULOUT,*) 'CPFPFILTER : DILATATION AND CONTRACTION MATRIX TO BE COMPUTED'
! The number of latitudes should be a multiple of 4 to fit the spectral transforms package.
  IDGLHRAW=(KFPCMAX+1)/2
  IDGL=4*((IDGLHRAW+1)/2)
  IDLON=2*IDGL
! PSTRET > 1 assumed
  ICMAX=MAX(KFPCMAX,(IDLON-3)/2)
  CALL FPFILTER(ICMAX,KFPDOM,LDFPFIL,KFMAX,PSEL,PBED,PLTF,LDBED,PFPFIL)
  CALL SETUP_TRANS(KRESOL=IRESOLC,KTMAX=ICMAX,KSMAX=NSMAX,KDGL=IDGL, &
   & LDUSEFLT=.FALSE.,LDUSERPNM=.FALSE.,LDKEEPRPNM=.FALSE., &
   & LDPNMONLY=.TRUE.)
  CALL TRANS_INQ(KRESOL=IRESOLC,KLEI3=IDGNH)
  ALLOCATE(ZMU(2*IDGNH),ZW(2*IDGNH))
  CALL TRANS_INQ(KRESOL=IRESOLC,PMU=ZMU,PGW=ZW)
  CALL SETUP_TRANS(KRESOL=IRESOLS,KSMAX=NSMAX,KDGL=IDGL, &
   & LDUSEFLT=.FALSE.,LDUSERPNM=.FALSE.,LDKEEPRPNM=.FALSE.,PSTRET=PSTRET, &
   & LDPNMONLY=.TRUE.)
  CALL TRANS_INQ(KRESOL=IRESOLS,KLEI3=IDGLG)
  ALLOCATE(IUMPP(NPRTRW),IALLMS(NSMAX+1),IPTRMS(NPRTRW))
  CALL TRANS_INQ(KRESOL=IRESOLS,KUMPP=IUMPP, &
   & KALLMS=IALLMS(:),KPTRMS=IPTRMS(:))
  WRITE(NULOUT,'('' IDGLG = '',I6)') IDGLG
  WRITE(NULOUT,'('' IDGNH = '',I6,'' ICMAX = '',I8)') IDGNH,ICMAX
  IF (IDGL /= IDGLG) THEN
    WRITE(NULOUT,*) 'ERROR ON IDGL, PROBABLY BECAUSE IDGNH IS ODD.'
    CALL ABOR1('CPFPFILTER : NUMBER OF LATITUDES HAS BEEN REDEFINED.')
  ENDIF
! Computation of map factor from the non-stretched sines of latitudes
  ALLOCATE(ZMAPP(2*IDGNH))
  CALL DILAT_MAPPING(PSTRET,ZMU(:),ZMAPP(:))
  DEALLOCATE(ZMU)
ENDIF

KCMAX(:)=ICMAX

! Circular distribution of waves over the V-sets in order to balance the computational cost :
ALLOCATE(IVSET(NUMP)) ! V-set for each local wave number
DO JMLOC=1,NUMP
  IVSET(JMLOC)=MOD(JMLOC,NPRTRV)+1
ENDDO
IVNUMP=COUNT(IVSET == MYSETV)
ALLOCATE(IVMYMS(IVNUMP))
ALLOCATE(IWMLOC(IVNUMP)) ! Full W-set local wave number for each V-set local wave number
II=0
DO JMLOC=1,NUMP
  IF (IVSET(JMLOC)==MYSETV) THEN
    II=II+1
    IVMYMS(II)=MYMS(JMLOC)
    IWMLOC(II)=JMLOC
  ENDIF
ENDDO

ALLOCATE(ISRANGE(IVNUMP))
DO JMLOC=1,IVNUMP
  IM=IVMYMS(JMLOC)
  ISRANGE(JMLOC)=NSMAX+1-IM
ENDDO

ALLOCATE(IOFF(NUMP+1))
IOFF(1)=0
DO JMLOC=1,NUMP
  IOFF(JMLOC+1)=IOFF(JMLOC)+(NSMAX+1-MYMS(JMLOC))**2
ENDDO
IDIMAT=2*(IOFF(NUMP+1)/2)+1

!*    2.   Read matrixes files

IF (LLCONT) THEN

  ITMXSUR=2*((NSMAX+1)/2)+1
  ICMXSUR=2*((ICMAX+1)/2)+1
  ALLOCATE(ZDILA(ICMXSUR,ITMXSUR,IVNUMP))
  ALLOCATE(ZCONT(ICMXSUR,ITMXSUR,IVNUMP))
  ALLOCATE(ZDILALU((NSMAX+1)*(ICMAX+1)))
  ALLOCATE(ZCONTLU((NSMAX+1)*(ICMAX+1)))
  DO JMLOC=1,IVNUMP
    IM=IVMYMS(JMLOC)
    ICRANGE=ICMAX+1-IM
    IF (IM == 0) WRITE (CLWAVE,'(A,I5.4)') 'WNUM 0000'
    IF (IM  > 0) WRITE (CLWAVE,'(A,I5.4)') 'WNUM',IM
    CALL RLFILEC (NULDILA, CLWAVE, ZDILALU, ISRANGE(JMLOC)*ICRANGE)
    CALL RLFILEC (NULCONT, CLWAVE, ZCONTLU, ISRANGE(JMLOC)*ICRANGE)
!$OMP PARALLEL DO SCHEDULE(STATIC,1) PRIVATE(JT,JC,IND)
    DO JT=1,ISRANGE(JMLOC)
      IND=(JT-1)*ICRANGE
      DO JC=1,ICRANGE
        ZDILA(JC,JT,JMLOC)=ZDILALU(IND+JC)
        ZCONT(JC,JT,JMLOC)=ZCONTLU(IND+JC)
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
  ENDDO
  DEALLOCATE(ZDILALU)
  DEALLOCATE(ZCONTLU)

  IF (.NOT.LLOPEN) THEN
    CALL LFIFER(IREP,NULDILA,'UNKNOWN')
    CALL LFIFER(IREP,NULCONT,'UNKNOWN')
  ENDIF

ENDIF

!*    3.   Compute filtering matrixes for each zonal wavenumber

ALLOCATE(PFPMAT(IDIMAT,KFPDOM))
IF (LALLOFP) THEN
  WRITE(NULOUT,"(1X,'ARRAY ',A10,' ALLOCATED ',8I12)") 'PFPMAT   ',SIZE(PFPMAT),SHAPE(PFPMAT)
ENDIF
IF (IDIMAT > IOFF(NUMP+1)) THEN
  PFPMAT(IDIMAT,:)=0._JPRB
ENDIF

IF (LLCONT) THEN

!$OMP PARALLEL PRIVATE(JMLOC,IM,IMM1,ICRANGE,ZSPECC,JDOM,JF,JN,ZFILTC,ZSPECT,II)
  ALLOCATE(ZSPECC(ICMXSUR,NSMAX+1))
  ALLOCATE(ZFILTC(ICMXSUR,NSMAX+1))
  ALLOCATE(ZSPECT(ITMXSUR,NSMAX+1))  
!$OMP DO SCHEDULE(DYNAMIC,1)
  DO JMLOC=1,IVNUMP
    IM=IVMYMS(JMLOC)
    IMM1=-IM+1
    ICRANGE=ICMAX+1-IM

!*  3.1   Canonical injection into the geographical sphere

    DO JF=1,ISRANGE(JMLOC)
      DO JN=1,NSMAX+IMM1
        ZSPECT(JN,JF)=0.0_JPRB
      ENDDO
    ENDDO
    DO JF=1,ISRANGE(JMLOC)
      ZSPECT(JF,JF)=1.0_JPRB
    ENDDO

    CALL MXMAOP(ZDILA(:,:,JMLOC),1,ICMXSUR,ZSPECT,1,ITMXSUR,ZSPECC,1,ICMXSUR, &
     & ICRANGE,ISRANGE(JMLOC),ISRANGE(JMLOC))  

!*  3.2   Computation of filtering matrix for each subdomain

    DO JDOM=1,KFPDOM
      IF (LDFPFIL(JDOM)) THEN

        DO JF=1,ISRANGE(JMLOC)
          DO JN=1,ICMAX+IMM1
            ZFILTC(JN,JF)=ZSPECC(JN,JF)*PFPFIL(JN-IMM1,JDOM)
          ENDDO
        ENDDO
        CALL MXMAOP(ZCONT(:,:,JMLOC),ICMXSUR,1,ZFILTC,1,ICMXSUR,ZSPECT,1, &
         & ITMXSUR,ISRANGE(JMLOC),ICRANGE,ISRANGE(JMLOC))

        DO JF=1,ISRANGE(JMLOC)
          II=IOFF(IWMLOC(JMLOC))+ISRANGE(JMLOC)*(JF-1)
          DO JN=1,ISRANGE(JMLOC)
            PFPMAT(II+JN,JDOM)=MIN(1._JPRB,MAX(-1._JPRB,ZSPECT(JN,JF)))
          ENDDO
        ENDDO
      
      ENDIF
    ENDDO

  ENDDO !JMLOC
!$OMP END DO
  DEALLOCATE(ZSPECC)
  DEALLOCATE(ZFILTC)
  DEALLOCATE(ZSPECT)
!$OMP END PARALLEL

  DEALLOCATE(ZDILA)
  DEALLOCATE(ZCONT)

ELSE

  IROOT=1
  CALL SET2PE(IPROC,0,0,MYSETW,MYSETV)
  ITAG=0

  DO JMLOC=1,IVNUMP

    IM=IVMYMS(JMLOC)

    ID1=ICMAX-IM+1
    ID2=NSMAX-IM+1

!*  3.1   Canonical injection into the geographical sphere

    ALLOCATE(ZPNMS(IDGLG,NSMAX-IM+3))
    ALLOCATE(ZPNMC(IDGNH,ICMAX-IM+3))
    CALL TRANS_PNM(KRESOL=IRESOLS,KM=IM,PRPNM=ZPNMS,LDCHEAP=.TRUE.)
    CALL TRANS_PNM(KRESOL=IRESOLC,KM=IM,PRPNM=ZPNMC,LDCHEAP=.TRUE.)

    ALLOCATE(ZCONT(ID1,ID2,1))
    ALLOCATE(ZDILA(ID1,ID2,1))
    CALL DILAT_CALC(IM,ICMAX,NSMAX,IDGNH,ZPNMS(:,2:NSMAX-IM+2),ZW(1:IDGNH),ZMAPP, &
     & ZPNMC(:,2:ICMAX-IM+2),ZCONT(:,:,1),ZDILA(:,:,1))
    DEALLOCATE(ZPNMS)
    DEALLOCATE(ZPNMC)

    IF (IM == 0) THEN 
      CALL DILAT_DEVIATION(ZCONT(:,:,1),ZDILA(:,:,1),ZMAX)
      IF (IPROC /= IROOT) THEN
        CALL MPL_SEND(ZMAX,KDEST=IROOT,KTAG=ITAG,CDSTRING='CPFPFILTER:')
      ENDIF
    ENDIF

    ALLOCATE(ZSPECC(ID1,ID2))
    ALLOCATE(ZSPECT(ID2,ID2))  

!*  3.2   Computation of filtering matrix for each subdomain

    DO JDOM=1,KFPDOM
      IF (LDFPFIL(JDOM)) THEN

        !$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JN)
        DO JF=1,ID2
          DO JN=1,ID1
            ZSPECC(JN,JF)=ZDILA(JN,JF,1)*PFPFIL(JN+IM-1,JDOM)
          ENDDO
        ENDDO
        !$OMP END PARALLEL DO 

        CALL MXMAOP(ZCONT(:,:,1),ID1,1,ZSPECC,1,ID1,ZSPECT,1, &
         & ID2,ID2,ID1,ID2)

        !$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JN, II)
        DO JF=1,ID2
          II=IOFF(IWMLOC(JMLOC))+ID2*(JF-1)
          DO JN=1,ID2
            PFPMAT(II+JN,JDOM)=MIN(1._JPRB,MAX(-1._JPRB,ZSPECT(JN,JF)))
          ENDDO
        ENDDO
        !$OMP END PARALLEL DO 
      
      ENDIF
    ENDDO

    DEALLOCATE(ZSPECC)
    DEALLOCATE(ZSPECT)
    DEALLOCATE(ZDILA)
    DEALLOCATE(ZCONT)

  ENDDO !JMLOC

  IF (IPROC == IROOT) THEN
    IM=0
    DO JMLOC=1,NUMP
      IF (MYMS(JMLOC) == IM) THEN
        CALL SET2PE(IOWN0,0,0,MYSETW,IVSET(JMLOC))
        IF (IOWN0 /= IROOT) THEN
          CALL MPL_RECV(ZMAX,KSOURCE=IOWN0,KTAG=ITAG,CDSTRING='CPFPFILTER:')
        ENDIF
        WRITE(NULOUT,'('' ZONAL WAVE NUMBER '',I4, &
         & '' DEVIATION FROM IDENTITY MATRIX '',E10.3)') IM,ZMAX
        IF (ZMAX > PMAXDEV) THEN
          WRITE(NULOUT,'('' CPFPFILTER : TOO MUCH DEVIATION FROM IDENTITY '')')
          WRITE(NULOUT,'('' INCREASE NFPCMAX IN NAMELIST'')')
          WRITE(NULOUT,'('' OR REDUCE RFPMAXDEV IN NAMELIST'')')
          CALL FLUSH(NULOUT)
          CALL ABOR1('CPFPFILTER : TOO MUCH DEVIATION FROM IDENTITY')
        ENDIF
        EXIT
      ENDIF
    ENDDO
  ENDIF

ENDIF

IF (.NOT.LLDILA .AND. .NOT.LLCONT) THEN
  CALL TRANS_RELEASE(KRESOL=IRESOLC)
  CALL TRANS_RELEASE(KRESOL=IRESOLS)
ENDIF

!*    4.   B-level allgathering of matrixes

! mpl_allgatherv needs data to be unpacked after send.
! alternative : use send/recv to master task then broadcast.
! or (here) : broadcasts along V communicator.

IF (NPRTRV > 1) THEN

  ALLOCATE(IREQ(COUNT(LDFPFIL)*NUMP))
  IR=0

  DO JMLOC=1,NUMP
    DO JDOM=1,KFPDOM
      IF (LDFPFIL(JDOM)) THEN
        IR=IR+1
        ITAG=JMLOC+NUMP*(JDOM-1)
        CALL MPL_BROADCAST(PFPMAT(IOFF(JMLOC)+1:IOFF(JMLOC+1),JDOM),KROOT=IVSET(JMLOC),KTAG=ITAG, &
         & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQ(IR),KCOMM=MPL_ALL_LEVS_COMM, &
         & CDSTRING='CPFPFILTER:')
      ENDIF
    ENDDO
  ENDDO

  IF (IR > 0) THEN
    CALL MPL_WAIT(KREQUEST=IREQ(1:IR),CDSTRING='CPFPFILTER: WAIT FOR SENDS AND RECEIVES')
  ENDIF

  DEALLOCATE(IREQ)

ENDIF
!----------------------------------


DEALLOCATE(IOFF)


DEALLOCATE(IVMYMS)
DEALLOCATE(IWMLOC)
DEALLOCATE(ISRANGE)

DEALLOCATE(IVSET)

!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('CPFPFILTER',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE RLFILEC (KNUMER, CDNOMA, PDONNE, KLONGD)

USE PARKIND1, ONLY : JPRD

INTEGER (KIND=JPIM), INTENT(IN) :: KNUMER
CHARACTER (LEN=*), INTENT(IN)   :: CDNOMA
REAL (KIND=JPRB), INTENT(OUT)   :: PDONNE (:)
INTEGER (KIND=JPIM), INTENT(IN) :: KLONGD

REAL (KIND=JPRD)    :: ZDONNE (SIZE (PDONNE))

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('CPFPFILTER:RLFILEC',0,ZHOOK_HANDLE)

CALL LFILEC (IREP, KNUMER, CDNOMA, ZDONNE, KLONGD)
PDONNE = REAL (ZDONNE, JPRB)

IF (LHOOK) CALL DR_HOOK('CPFPFILTER:RLFILEC',1,ZHOOK_HANDLE)

END SUBROUTINE RLFILEC

END SUBROUTINE CPFPFILTER
