! (C) Copyright 1989- Meteo-France.

SUBROUTINE ENDPOS_PREPGFL(YDQTYPE,YDTFP,KLMOD,KFLEVG,YGFL,KPPGFL,YDIN_GFL,YDPPIC,LD1,LD2,LDPBL,LDICV,&
 & LD_GFL,LDS1_GFL,LDS2_GFL,LDIN_GFL,KGFLCOD,KDIN_GFL)

!**** *ENDPOS_PREPGFL* - post-processing

!     PURPOSE.
!     -------
!           Post-processing calculations: preliminary calculations for GFL

!**   INTERFACE.
!     ---------
!        *CALL* *ENDPOS_PREPGFL(...)

!        EXPLICIT ARGUMENTS :
!        ------------------
!        * INPUT:
!          KLMOD : model/post-processing dynamic primitive variable indicator for each fullpos field :
!                  2 : upper air primitive dynamic variable
!                  1 : surface primitive dynamic variable
!                  0 : not a primitive variable
!        KPPGFL    : dimension (number of GFL variables required for post-processing)
!        YDIN_GFL  : pointers allowing to retrieve individual fields in PGFL (in ENDPOS)
!        YDPPIC    : pointers allowing to retrieve individual fields in ZPPGFL (in ENDPOS)
!        LD1       : additional condition to use Q,L,I.
!        LD2       : additional condition to use S,RR,G,H.
!        LDPBL     : addit. condition to use L,I,S,RR,G,H (activate PBL computation).
!        LDICV     : addit. condition to use L,I,S,RR,G,H (activate CAPE & CIEN comp).
!        * OUTPUT:
!        LD_GFL    : says if pp of GFL is required or not
!        LDS1_GFL  : cf. LD_GFL but for call APACHE with model levels
!        LDS2_GFL  : cf. LD_GFL but for call APACHE with pp. levels
!        LDIN_GFL  : ldin_gfl(jvar_[X])=KLMOD(YDTFP%[X]%ICOD)
!        KGFLCOD   : stores YDTFP%[X]%ICOD
!        KDIN_GFL  : allows to find correspondance between ordering GFL in PGFLT0
!                    and ordering GFL in ZGFLT0, in ENDPOS
!                    zgflt0(jvar)=pgflt0(kdin_gfl(jvar)).

!     EXTERNALS.
!     ---------

! Modifications
! -------------
!   ORIGINAL : August 2009 (K. Yessad)
!      Y. Bouteloup: 11-Jan-2017 Add deep convective variables
! End Modifications
!------------------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
USE YOMAFN   , ONLY : ALL_FULLPOS_TYPES
USE YOM_YGFL , ONLY : TYPE_GFLD
USE TYPE_GFLFLDS, ONLY: TYPE_IGFLFLD
USE PARFPOS  , ONLY : JPOSDYN

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE (TYPE_FPRQDYN),  INTENT(IN) :: YDQTYPE
TYPE(ALL_FULLPOS_TYPES), INTENT(IN) :: YDTFP
INTEGER(KIND=JPIM),INTENT(IN) :: KLMOD(JPOSDYN)
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
TYPE(TYPE_GFLD)   ,INTENT(IN) :: YGFL
INTEGER(KIND=JPIM),INTENT(IN) :: KPPGFL
TYPE(TYPE_IGFLFLD),INTENT(IN) :: YDIN_GFL
TYPE(TYPE_IGFLFLD),INTENT(IN) :: YDPPIC
LOGICAL,INTENT(IN)            :: LD1
LOGICAL,INTENT(IN)            :: LD2
LOGICAL,INTENT(IN)            :: LDPBL
LOGICAL,INTENT(IN)            :: LDICV
LOGICAL,INTENT(OUT)           :: LD_GFL(KPPGFL)
LOGICAL,INTENT(OUT)           :: LDS1_GFL(KPPGFL)
LOGICAL,INTENT(OUT)           :: LDS2_GFL(KPPGFL)
LOGICAL,INTENT(OUT)           :: LDIN_GFL(KPPGFL)
INTEGER(KIND=JPIM),INTENT(OUT) :: KGFLCOD(KPPGFL)
INTEGER(KIND=JPIM),INTENT(OUT) :: KDIN_GFL(KPPGFL)

!     ------------------------------------------------------------------

INTEGER(KIND=JPIM) :: JVAR
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('ENDPOS_PREPGFL',0,ZHOOK_HANDLE)
ASSOCIATE(NAERO=>YGFL%NAERO, NCHEM=>YGFL%NCHEM, NGFL_EXT=>YGFL%NGFL_EXT, NGHG=>YGFL%NGHG)
!     ------------------------------------------------------------------

!     1.     LD_GFL

LD_GFL(YDPPIC%IQ)    = YDQTYPE%LL(YDTFP%Q%ICOD).OR.LD1
LD_GFL(YDPPIC%IL)    = YDQTYPE%LL(YDTFP%L%ICOD).OR.LD1
LD_GFL(YDPPIC%ILRAD) = YDQTYPE%LL(YDTFP%LRAD%ICOD).OR.LD1
LD_GFL(YDPPIC%II)    = YDQTYPE%LL(YDTFP%I%ICOD).OR.LD1
LD_GFL(YDPPIC%IIRAD) = YDQTYPE%LL(YDTFP%IRAD%ICOD).OR.LD1
LD_GFL(YDPPIC%IA)    = YDQTYPE%LL(YDTFP%CLF%ICOD)
LD_GFL(YDPPIC%IO3)   = YDQTYPE%LL(YDTFP%O3MX%ICOD)
LD_GFL(YDPPIC%ICPF)   = YDQTYPE%LL(YDTFP%CPF%ICOD)
LD_GFL(YDPPIC%ISPF)   = YDQTYPE%LL(YDTFP%SPF%ICOD)
LD_GFL(YDPPIC%IS)    = YDQTYPE%LL(YDTFP%SN%ICOD).OR.LD2
LD_GFL(YDPPIC%IRR)   = YDQTYPE%LL(YDTFP%RR%ICOD).OR.LD2
LD_GFL(YDPPIC%IG)    = YDQTYPE%LL(YDTFP%GR%ICOD).OR.LD2
LD_GFL(YDPPIC%IH)    = YDQTYPE%LL(YDTFP%HL%ICOD).OR.LD2
LD_GFL(YDPPIC%ITKE)  = YDQTYPE%LL(YDTFP%TKE%ICOD)
LD_GFL(YDPPIC%ILCONV)= YDQTYPE%LL(YDTFP%LCONV%ICOD)
LD_GFL(YDPPIC%IICONV)= YDQTYPE%LL(YDTFP%ICONV%ICOD)
LD_GFL(YDPPIC%IRCONV)= YDQTYPE%LL(YDTFP%RCONV%ICOD)
LD_GFL(YDPPIC%ISCONV)= YDQTYPE%LL(YDTFP%SCONV%ICOD)
LD_GFL(YDPPIC%IUAL)  = YDQTYPE%LL(YDTFP%UAL%ICOD)
LD_GFL(YDPPIC%IUOM)  = YDQTYPE%LL(YDTFP%UOM%ICOD)
LD_GFL(YDPPIC%IDAL)  = YDQTYPE%LL(YDTFP%DAL%ICOD)
LD_GFL(YDPPIC%IDOM)  = YDQTYPE%LL(YDTFP%DOM%ICOD)

DO JVAR=1,NGHG
  LD_GFL(YDPPIC%IGHG+JVAR-1)=YDQTYPE%LL(YDTFP%GHG(JVAR)%ICOD)
ENDDO
DO JVAR=1,NAERO
  LD_GFL(YDPPIC%IAERO+JVAR-1)=YDQTYPE%LL(YDTFP%AERO(JVAR)%ICOD)
ENDDO
DO JVAR=1,NCHEM
  LD_GFL(YDPPIC%ICHEM+JVAR-1)=YDQTYPE%LL(YDTFP%CHEM(JVAR)%ICOD)
ENDDO
DO JVAR=1,NGFL_EXT
  LD_GFL(YDPPIC%IEXT+JVAR-1)=YDQTYPE%LL(YDTFP%EXT(JVAR)%ICOD)
ENDDO

!     2.     LDS1_GFL

LDS1_GFL(YDPPIC%IQ)     = .TRUE.
LDS1_GFL(YDPPIC%IL)     = LDPBL.OR.LDICV
LDS1_GFL(YDPPIC%ILRAD)  = .FALSE.
LDS1_GFL(YDPPIC%II)     = LDPBL.OR.LDICV
LDS1_GFL(YDPPIC%IIRAD)  = .FALSE.
LDS1_GFL(YDPPIC%IA)     = .FALSE.
LDS1_GFL(YDPPIC%IO3)    = .FALSE.
LDS1_GFL(YDPPIC%ICPF)    = .FALSE.
LDS1_GFL(YDPPIC%ISPF)    = .FALSE.
LDS1_GFL(YDPPIC%IS)     = LDPBL.OR.LDICV
LDS1_GFL(YDPPIC%IRR)    = LDPBL.OR.LDICV
LDS1_GFL(YDPPIC%IG)     = LDPBL.OR.LDICV
LDS1_GFL(YDPPIC%IH)     = LDPBL.OR.LDICV
LDS1_GFL(YDPPIC%ITKE)   = .FALSE.
LDS1_GFL(YDPPIC%ILCONV) = .FALSE.
LDS1_GFL(YDPPIC%IICONV) = .FALSE.
LDS1_GFL(YDPPIC%IRCONV) = .FALSE.
LDS1_GFL(YDPPIC%ISCONV) = .FALSE.
LDS1_GFL(YDPPIC%IUAL)   = .FALSE.
LDS1_GFL(YDPPIC%IUOM)   = .FALSE.
LDS1_GFL(YDPPIC%IDAL)   = .FALSE.
LDS1_GFL(YDPPIC%IDOM)   = .FALSE.
DO JVAR=1,NGHG
  LDS1_GFL(YDPPIC%IGHG+JVAR-1)=.FALSE.
ENDDO
DO JVAR=1,NAERO
  LDS1_GFL(YDPPIC%IAERO+JVAR-1)=.FALSE.
ENDDO
DO JVAR=1,NCHEM
  LDS1_GFL(YDPPIC%ICHEM+JVAR-1)=.FALSE.
ENDDO
DO JVAR=1,NGFL_EXT
  LDS1_GFL(YDPPIC%IEXT+JVAR-1)=.FALSE.
ENDDO

!     3.     LDS2_GFL

LDS2_GFL(YDPPIC%IQ)     = .TRUE.
LDS2_GFL(YDPPIC%IL)   = YDQTYPE%LL(YDTFP%HTPW%ICOD) .OR. YDQTYPE%LL(YDTFP%HTPW1%ICOD) &
        & .OR.YDQTYPE%LL(YDTFP%HTPW2%ICOD).OR.YDQTYPE%LL(YDTFP%TPW%ICOD)
LDS2_GFL(YDPPIC%ILRAD)  = .FALSE.
LDS2_GFL(YDPPIC%II)   = YDQTYPE%LL(YDTFP%HTPW%ICOD) .OR. YDQTYPE%LL(YDTFP%HTPW1%ICOD) &
        & .OR.YDQTYPE%LL(YDTFP%HTPW2%ICOD).OR.YDQTYPE%LL(YDTFP%TPW%ICOD)
LDS2_GFL(YDPPIC%IIRAD)  = .FALSE.
LDS2_GFL(YDPPIC%IA)     = .FALSE.
LDS2_GFL(YDPPIC%IO3)    = .FALSE.
LDS2_GFL(YDPPIC%ICPF)   = .FALSE.
LDS2_GFL(YDPPIC%ISPF)   = .FALSE.
LDS2_GFL(YDPPIC%IS)     = .FALSE.
LDS2_GFL(YDPPIC%IRR)    = .FALSE.
LDS2_GFL(YDPPIC%IG)     = .FALSE.
LDS2_GFL(YDPPIC%IH)     = .FALSE.
LDS2_GFL(YDPPIC%ITKE)   = .FALSE.
LDS2_GFL(YDPPIC%ILCONV) = .FALSE.
LDS2_GFL(YDPPIC%IICONV) = .FALSE.
LDS2_GFL(YDPPIC%IRCONV) = .FALSE.
LDS2_GFL(YDPPIC%ISCONV) = .FALSE.
LDS2_GFL(YDPPIC%IUAL)   = .FALSE.
LDS2_GFL(YDPPIC%IUOM)   = .FALSE.
LDS2_GFL(YDPPIC%IDAL)   = .FALSE.
LDS2_GFL(YDPPIC%IDOM)   = .FALSE.
DO JVAR=1,NGHG
  LDS2_GFL(YDPPIC%IGHG+JVAR-1)=.FALSE.
ENDDO
DO JVAR=1,NAERO
  LDS2_GFL(YDPPIC%IAERO+JVAR-1)=.FALSE.
ENDDO
DO JVAR=1,NCHEM
  LDS2_GFL(YDPPIC%ICHEM+JVAR-1)=.FALSE.
ENDDO
DO JVAR=1,NGFL_EXT
  LDS2_GFL(YDPPIC%IEXT+JVAR-1)=.FALSE.
ENDDO

!     4.     KGFLCOD

KGFLCOD(YDPPIC%IQ)=YDTFP%Q%ICOD
KGFLCOD(YDPPIC%IL)=YDTFP%L%ICOD
KGFLCOD(YDPPIC%ILRAD)=YDTFP%LRAD%ICOD
KGFLCOD(YDPPIC%II)=YDTFP%I%ICOD
KGFLCOD(YDPPIC%IIRAD)=YDTFP%IRAD%ICOD
KGFLCOD(YDPPIC%IA)=YDTFP%CLF%ICOD
KGFLCOD(YDPPIC%IO3)=YDTFP%O3MX%ICOD
KGFLCOD(YDPPIC%ICPF)=YDTFP%CPF%ICOD
KGFLCOD(YDPPIC%ISPF)=YDTFP%SPF%ICOD
KGFLCOD(YDPPIC%IS)=YDTFP%SN%ICOD
KGFLCOD(YDPPIC%IRR)=YDTFP%RR%ICOD
KGFLCOD(YDPPIC%IG)=YDTFP%GR%ICOD
KGFLCOD(YDPPIC%IH)=YDTFP%HL%ICOD
KGFLCOD(YDPPIC%ITKE)=YDTFP%TKE%ICOD
KGFLCOD(YDPPIC%ILCONV)=YDTFP%LCONV%ICOD
KGFLCOD(YDPPIC%IICONV)=YDTFP%ICONV%ICOD
KGFLCOD(YDPPIC%IRCONV)=YDTFP%RCONV%ICOD
KGFLCOD(YDPPIC%ISCONV)=YDTFP%SCONV%ICOD
KGFLCOD(YDPPIC%IUAL)=YDTFP%UAL%ICOD
KGFLCOD(YDPPIC%IUOM)=YDTFP%UOM%ICOD
KGFLCOD(YDPPIC%IDAL)=YDTFP%DAL%ICOD
KGFLCOD(YDPPIC%IDOM)=YDTFP%DOM%ICOD
DO JVAR=1,NGHG
  KGFLCOD(YDPPIC%IGHG+JVAR-1)=YDTFP%GHG(JVAR)%ICOD
ENDDO
DO JVAR=1,NAERO
  KGFLCOD(YDPPIC%IAERO+JVAR-1)=YDTFP%AERO(JVAR)%ICOD
ENDDO
DO JVAR=1,NCHEM
  KGFLCOD(YDPPIC%ICHEM+JVAR-1)=YDTFP%CHEM(JVAR)%ICOD
ENDDO
DO JVAR=1,NGFL_EXT
  KGFLCOD(YDPPIC%IEXT+JVAR-1)=YDTFP%EXT(JVAR)%ICOD
ENDDO

!     5.     KDIN_GFL

KDIN_GFL(YDPPIC%IQ)=YDIN_GFL%IQ
KDIN_GFL(YDPPIC%IL)=YDIN_GFL%IL
KDIN_GFL(YDPPIC%ILRAD)=YDIN_GFL%ILRAD
KDIN_GFL(YDPPIC%II)=YDIN_GFL%II
KDIN_GFL(YDPPIC%IIRAD)=YDIN_GFL%IIRAD
KDIN_GFL(YDPPIC%IA)=YDIN_GFL%IA
KDIN_GFL(YDPPIC%IO3)=YDIN_GFL%IO3
KDIN_GFL(YDPPIC%ICPF)=YDIN_GFL%ICPF
KDIN_GFL(YDPPIC%ISPF)=YDIN_GFL%ISPF
KDIN_GFL(YDPPIC%IS)=YDIN_GFL%IS
KDIN_GFL(YDPPIC%IRR)=YDIN_GFL%IRR
KDIN_GFL(YDPPIC%IG)=YDIN_GFL%IG
KDIN_GFL(YDPPIC%IH)=YDIN_GFL%IH
KDIN_GFL(YDPPIC%ITKE)=YDIN_GFL%ITKE
KDIN_GFL(YDPPIC%ILCONV)=YDIN_GFL%ILCONV
KDIN_GFL(YDPPIC%IICONV)=YDIN_GFL%IICONV
KDIN_GFL(YDPPIC%IRCONV)=YDIN_GFL%IRCONV
KDIN_GFL(YDPPIC%ISCONV)=YDIN_GFL%ISCONV
KDIN_GFL(YDPPIC%IUAL)=YDIN_GFL%IUAL
KDIN_GFL(YDPPIC%IUOM)=YDIN_GFL%IUOM
KDIN_GFL(YDPPIC%IDAL)=YDIN_GFL%IDAL
KDIN_GFL(YDPPIC%IDOM)=YDIN_GFL%IDOM
DO JVAR=1,NGHG
  KDIN_GFL(YDPPIC%IGHG+JVAR-1)=YDIN_GFL%IGHG+(JVAR-1)*KFLEVG
ENDDO
DO JVAR=1,NAERO
  KDIN_GFL(YDPPIC%IAERO+JVAR-1)=YDIN_GFL%IAERO+(JVAR-1)*KFLEVG
ENDDO
DO JVAR=1,NCHEM
  KDIN_GFL(YDPPIC%ICHEM+JVAR-1)=YDIN_GFL%ICHEM+(JVAR-1)*KFLEVG
ENDDO
DO JVAR=1,NGFL_EXT
  KDIN_GFL(YDPPIC%IEXT+JVAR-1)=YDIN_GFL%IEXT+(JVAR-1)*KFLEVG
ENDDO

!     6.     LDIN_GFL

LDIN_GFL(YDPPIC%IQ)=(KLMOD(YDTFP%Q%ICOD) >= 1)
LDIN_GFL(YDPPIC%IL)=(KLMOD(YDTFP%L%ICOD) >= 1)
LDIN_GFL(YDPPIC%ILRAD)=(KLMOD(YDTFP%LRAD%ICOD) >= 1)
LDIN_GFL(YDPPIC%II)=(KLMOD(YDTFP%I%ICOD) >= 1)
LDIN_GFL(YDPPIC%IIRAD)=(KLMOD(YDTFP%IRAD%ICOD) >= 1)
LDIN_GFL(YDPPIC%IA)=(KLMOD(YDTFP%CLF%ICOD) >= 1)
LDIN_GFL(YDPPIC%IO3)=(KLMOD(YDTFP%O3MX%ICOD) >= 1)
LDIN_GFL(YDPPIC%ICPF)=(KLMOD(YDTFP%CPF%ICOD) >= 1)
LDIN_GFL(YDPPIC%ISPF)=(KLMOD(YDTFP%SPF%ICOD) >= 1)
LDIN_GFL(YDPPIC%IS)=(KLMOD(YDTFP%SN%ICOD) >= 1)
LDIN_GFL(YDPPIC%IRR)=(KLMOD(YDTFP%RR%ICOD) >= 1)
LDIN_GFL(YDPPIC%IG)=(KLMOD(YDTFP%GR%ICOD) >= 1)
LDIN_GFL(YDPPIC%IH)=(KLMOD(YDTFP%HL%ICOD) >= 1)
LDIN_GFL(YDPPIC%ITKE)=(KLMOD(YDTFP%TKE%ICOD) >= 1)
LDIN_GFL(YDPPIC%ILCONV)=(KLMOD(YDTFP%LCONV%ICOD) >= 1)
LDIN_GFL(YDPPIC%IICONV)=(KLMOD(YDTFP%ICONV%ICOD) >= 1)
LDIN_GFL(YDPPIC%IRCONV)=(KLMOD(YDTFP%RCONV%ICOD) >= 1)
LDIN_GFL(YDPPIC%ISCONV)=(KLMOD(YDTFP%SCONV%ICOD) >= 1)
LDIN_GFL(YDPPIC%IUAL)=(KLMOD(YDTFP%UAL%ICOD) >= 1)
LDIN_GFL(YDPPIC%IUOM)=(KLMOD(YDTFP%UOM%ICOD) >= 1)
LDIN_GFL(YDPPIC%IDAL)=(KLMOD(YDTFP%DAL%ICOD) >= 1)
LDIN_GFL(YDPPIC%IDOM)=(KLMOD(YDTFP%DOM%ICOD) >= 1)
DO JVAR=1,NGHG
  LDIN_GFL(YDPPIC%IGHG+JVAR-1)=.TRUE.
ENDDO
DO JVAR=1,NAERO
  LDIN_GFL(YDPPIC%IAERO+JVAR-1)=.TRUE.
ENDDO
DO JVAR=1,NCHEM
  LDIN_GFL(YDPPIC%ICHEM+JVAR-1)=.TRUE.
ENDDO
DO JVAR=1,NGFL_EXT
  LDIN_GFL(YDPPIC%IEXT+JVAR-1)=.TRUE.
ENDDO

!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('ENDPOS_PREPGFL',1,ZHOOK_HANDLE)
END SUBROUTINE ENDPOS_PREPGFL
