! (C) Copyright 1989- Meteo-France.

SUBROUTINE FPSELEZO (YDFPUSERGEO, KPTR, KGP, KFXLAT, KFXLON, PWI, PNO)

!**** *FPSELEZO*  - 

!         KPTR   : pointer to the subdomain

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 11-09-2012
!      R. El Khatib 27-Sep-2013 LFPBOYD => NFPBOYD
!      R. El Khatib 04-Aug-2014 Pruning of the conf. 927/928

USE PARKIND1, ONLY : JPRB, JPIM
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO

IMPLICIT NONE

TYPE (TFPUSERGEO),   INTENT (IN)    :: YDFPUSERGEO
INTEGER (KIND=JPIM), INTENT (IN)    :: KPTR
INTEGER (KIND=JPIM), INTENT (IN)    :: KGP 
INTEGER (KIND=JPIM), INTENT (IN)    :: KFXLAT
INTEGER (KIND=JPIM), INTENT (IN)    :: KFXLON
REAL (KIND=JPRB),    INTENT (IN)    :: PWI (:)         ! 
REAL (KIND=JPRB),    INTENT (INOUT)   :: PNO (:)         ! 

#include "abor1.intfb.h"

INTEGER (KIND=JPIM) :: ISTCI, ISTAE, ILENZ
INTEGER (KIND=JPIM) :: JFPGL

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('FPSELEZO',0,ZHOOK_HANDLE)
ASSOCIATE(NFPSIZEG=>YDFPUSERGEO%NFPSIZEG, NFPLUX=>YDFPUSERGEO%NFPLUX, NFPGUX=>YDFPUSERGEO%NFPGUX)

ILENZ=KFXLAT*KFXLON

IF (ILENZ == NFPSIZEG) THEN
  ! Both file and model have C+I or C+I+E => straight copy :
  PNO(KPTR:KPTR+NFPSIZEG-1)=PWI(1:NFPSIZEG)
ELSEIF (ILENZ > NFPSIZEG) THEN
  ! Drop E-zone from climatology :
  ISTCI=KPTR
  ISTAE=1
  DO JFPGL=1,NFPGUX
    PNO(ISTCI:ISTCI+NFPLUX-1)=PWI(ISTAE:ISTAE+NFPLUX-1)
    ISTAE=ISTAE+KFXLON
    ISTCI=ISTCI+NFPLUX
  ENDDO
ELSE
  CALL ABOR1('FPSELEZO : E-ZONE IS MISSING FROM THE CLIMATOLOGY')
ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK ('FPSELEZO',1,ZHOOK_HANDLE)

END SUBROUTINE FPSELEZO
