! (C) Copyright 1989- Meteo-France.

SUBROUTINE FPSPECFITG(YDAFN,YDFPGEO,KFPDOM,KFPRESOL,KSPEC2,YDGEOMETRY,KAPTR,PABUF)

!**** *FPSPECFITG*  - Processing previously done in SPECFITG

!     PURPOSE.
!     --------
!        Cap humidity to saturation and 
!        spectrally fit dynamic fields.

!**   INTERFACE.
!     ----------
!       *CALL* *FPSPECFITG*

!        EXPLICIT ARGUMENTS
!        --------------------
!     PABUF    : post-processed fields 

!        IMPLICIT ARGUMENTS
!        --------------------

!     METHOD.
!     -------

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!      Tomas Wilhelmsson *ECMWF*
!      ORIGINAL : 2014-06-10

!     MODIFICATIONS.
!     --------------
!     ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1  ,ONLY : JPIM, JPRB
USE YOMHOOK   ,ONLY : LHOOK, DR_HOOK, JPHOOK
USE PARFPOS   , ONLY : JPOSDYN
USE YOMFPGEO, ONLY : TFPGEO
USE YOMAFN, ONLY : TAFN

!     ------------------------------------------------------------------
IMPLICIT NONE

TYPE (TAFN),  INTENT(IN) :: YDAFN
TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
INTEGER(KIND=JPIM), INTENT(IN) :: KFPRESOL(KFPDOM)
INTEGER(KIND=JPIM), INTENT(IN) :: KSPEC2(KFPDOM)
TYPE(GEOMETRY),     INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN) :: KAPTR(JPOSDYN)
REAL(KIND=JPRB),INTENT(INOUT) :: PABUF(:,:,:)

INTEGER(KIND=JPIM) :: JBLOC, JL, IST, IEND, JF

INTEGER(KIND=JPIM) :: IVSETSC(YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB), ALLOCATABLE :: ZGP(:,:,:), ZSPSCA(:,:), ZSPVOR(:,:), ZSPDIV(:,:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "dir_trans.h"
#include "inv_trans.h"

!      -----------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('FPSPECFITG',0,ZHOOK_HANDLE)
ASSOCIATE(TFP=>YDAFN%TFP, YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, &
 & YDMP=>YDGEOMETRY%YRMP, YDVAB=>YDGEOMETRY%YRVAB, YDVETA=>YDGEOMETRY%YRVETA, YDVFE=>YDGEOMETRY%YRVFE)
ASSOCIATE(NFPBLOCS=>YDFPGEO%NFPBLOCS, NFPROMA=>YDFPGEO%NFPROMA, NFPEND=>YDFPGEO%NFPEND, &
 & NFLEVG=>YDDIMV%NFLEVG, NFLEVL=>YDDIMV%NFLEVL, NBSETLEV=>YDMP%NBSETLEV)

!      -----------------------------------------------------------

ALLOCATE(ZGP(NFPROMA,3*NFLEVG+1,NFPBLOCS))
ALLOCATE(ZSPVOR(NFLEVL,KSPEC2(1)))
ALLOCATE(ZSPDIV(NFLEVL,KSPEC2(1)))
ALLOCATE(ZSPSCA(NFLEVL+1,KSPEC2(1)))
DO JBLOC=1,NFPBLOCS
  JF=0
  IST =1
  IEND=NFPEND(JBLOC)
    
  DO JL=1,NFLEVG
    JF=JF+1
    ZGP(IST:IEND,JF,JBLOC)=PABUF(IST:IEND,KAPTR(TFP%U%ICOD)+JL-1,JBLOC)
  ENDDO
  
  DO JL=1,NFLEVG
    JF=JF+1
    ZGP(IST:IEND,JF,JBLOC)=PABUF(IST:IEND,KAPTR(TFP%V%ICOD)+JL-1,JBLOC)
  ENDDO
    
  DO JL=1,NFLEVG
    JF=JF+1
    ZGP(IST:IEND,JF,JBLOC)=PABUF(IST:IEND,KAPTR(TFP%T%ICOD)+JL-1,JBLOC)
    IVSETSC(JL)=NBSETLEV(JL)
  ENDDO

  JF=JF+1
  ZGP(IST:IEND,JF,JBLOC)=PABUF(IST:IEND,KAPTR(TFP%LNSP%ICOD),JBLOC)
  IVSETSC(NFLEVG+1)=NBSETLEV(1)
ENDDO

CALL DIR_TRANS(PSPVOR=ZSPVOR,PSPDIV=ZSPDIV,PSPSCALAR=ZSPSCA,PGP=ZGP,&
  & KVSETUV=NBSETLEV,KVSETSC=IVSETSC,KPROMA=NFPROMA,KRESOL=KFPRESOL(1))

CALL INV_TRANS(PSPVOR=ZSPVOR,PSPDIV=ZSPDIV,PSPSCALAR=ZSPSCA,PGP=ZGP,&
  & KVSETUV=NBSETLEV,KVSETSC=IVSETSC,KPROMA=NFPROMA,KRESOL=KFPRESOL(1))

DO JBLOC=1,NFPBLOCS
  JF=0
  IST =1
  IEND=NFPEND(JBLOC)
  
  DO JL=1,NFLEVG
    JF=JF+1
    PABUF(IST:IEND,KAPTR(TFP%U%ICOD)+JL-1,JBLOC)=ZGP(IST:IEND,JF,JBLOC)
  ENDDO
  
  DO JL=1,NFLEVG
    JF=JF+1
    PABUF(IST:IEND,KAPTR(TFP%V%ICOD)+JL-1,JBLOC)=ZGP(IST:IEND,JF,JBLOC)
  ENDDO
  
  DO JL=1,NFLEVG
    JF=JF+1
    PABUF(IST:IEND,KAPTR(TFP%T%ICOD)+JL-1,JBLOC)=ZGP(IST:IEND,JF,JBLOC)
  ENDDO
  
  JF=JF+1
  PABUF(IST:IEND,KAPTR(TFP%LNSP%ICOD),JBLOC)=ZGP(IST:IEND,JF,JBLOC)
ENDDO

DEALLOCATE(ZSPSCA)
DEALLOCATE(ZSPDIV)
DEALLOCATE(ZSPVOR)
DEALLOCATE(ZGP)

!      -----------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('FPSPECFITG',1,ZHOOK_HANDLE)
!      -----------------------------------------------------------

END SUBROUTINE FPSPECFITG

