! (C) Copyright 1989- Meteo-France.

SUBROUTINE HPOS_CFU(YDAFN,LDFPOSHOR,YDCFU,KPROMA,KFLEVG,KEND,KC,KFPCLI,PCFU,PFPBUF1)

!**** *HPOS_CFU*  - HORIZONTAL POST-PROCESSING

!     PURPOSE.
!     --------
!        FILL THE "SEMI-LAGRANGIAN" BUFFERS WITH THE FIELDS TO TRANSFER
!        OR INTERPOLATE

!**   INTERFACE.
!     ----------
!       *CALL* *HPOS_CFU*

!        EXPLICIT ARGUMENTS
!        --------------------
!         INPUT:
!          LDFPOSHOR  : .true. if actual horizontal interpolations
!          KPROMA     : horizontal dimension
!          KFLEVG     : number of vertical levels
!          KEND       : last  adress in post-processing buffers to read
!          KC         : field code
!          KFPCLI     : climatology usage
!          PCFU       : cumulated fluxes

!         INPUT/OUTPUT:
!          PFPBUF1    : interpolation buffer containing the fields to interpolate

!        IMPLICIT ARGUMENTS
!        --------------------
!        se #include below.

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS
!        See documentation about FULL-POS.

!     AUTHOR.
!     -------
!        RYAD EL KHATIB *METEO-FRANCE*
!        ORIGINAL : 19-Sep-2016 from HPOS

!     MODIFICATIONS.
!     --------------
!     09-2018, R. Brozkova: Added global normal irradiance.
!     ------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM     ,JPRB
USE YOMHOOK  , ONLY : LHOOK    ,DR_HOOK, JPHOOK
USE YOMCFU   , ONLY : TCFU
USE YOMAFN, ONLY : TAFN

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE (TAFN),  INTENT(IN) :: YDAFN
LOGICAL           ,INTENT(IN)    :: LDFPOSHOR
TYPE(TCFU)        ,INTENT(IN)    :: YDCFU
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN)    :: KEND 
INTEGER(KIND=JPIM),INTENT(IN)    :: KC
INTEGER(KIND=JPIM),INTENT(IN)    :: KFPCLI
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCFU(KPROMA,YDCFU%NFDCFU)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPBUF1(KPROMA) 


INTEGER(KIND=JPIM) :: IST, INFLEV, INFLEVD, INFLEVT, IANO

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('HPOS_CFU',0,ZHOOK_HANDLE)
ASSOCIATE(GFP_PHYDS=>YDAFN%GFP_PHYDS, GFP=>YDAFN%GFP, NFDCFU=>YDCFU%NFDCFU, &
 & LTFPLC=>YDCFU%LTFPLC, LTFPLS=>YDCFU%LTFPLS, LTFR=>YDCFU%LTFR, &
 & LTSTRC=>YDCFU%LTSTRC, LTSTRD=>YDCFU%LTSTRD, LTSTRT=>YDCFU%LTSTRT)
!     ------------------------------------------------------------------

!*       1. PRELIMINARY INITIALISATIONS.
!           ----------------------------

IST=1

!*       5.2 Fill buffer.

IF (LDFPOSHOR.OR.KFPCLI > 0) THEN
  IANO=GFP_PHYDS(KC)%IANO
ELSE
  ! No interpolation nor change of physiography <=> only buffers transfers
  IANO=0
ENDIF

IF (KC == GFP%CLSP%ICOD) THEN
  ! Stratiform precipitations
  IF(LTFPLS)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFPLSL)
ELSEIF (KC == GFP%CCP%ICOD ) THEN
  ! Convective precipitations
  IF(LTFPLC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFPLCL)
ELSEIF (KC == GFP%CLSS%ICOD.AND.YDCFU%YCFUPT%MFPLSN>0) THEN
  ! Stratiform snow
  IF(LTFPLS)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFPLSN)
ELSEIF (KC == GFP%CCSF%ICOD.AND.YDCFU%YCFUPT%MFPLCN>0) THEN
  ! Convective snow
  IF(LTFPLC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFPLCN)
ELSEIF (KC == GFP%CLSG%ICOD.AND.YDCFU%YCFUPT%MFPLSG>0) THEN
  ! Stratiform graupel
  IF(LTFPLS)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFPLSG)
ELSEIF (KC == GFP%CCSG%ICOD.AND.YDCFU%YCFUPT%MFPLCG>0) THEN
  ! Convective graupel
  IF(LTFPLC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFPLCG)
ELSEIF (KC == GFP%CLSH%ICOD.AND.YDCFU%YCFUPT%MFPLSH>0) THEN
  ! Stratiform hail
  IF(LTFPLS)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFPLSH)
ELSEIF (KC == GFP%CCSH%ICOD.AND.YDCFU%YCFUPT%MFPLCH>0) THEN
  ! Convective hail
  IF(LTFPLC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFPLCH)
ELSEIF (KC == GFP%CUSS%ICOD) THEN
  ! Turbulence on U
  IF(LTSTRT)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MSTRTU)
ELSEIF (KC == GFP%CVSS%ICOD) THEN
  ! Turbulence on V
  IF(LTSTRT)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MSTRTV)
ELSEIF (KC == GFP%CSSH%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFCS)
ELSEIF (KC == GFP%CSMR%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRSOLU)
ELSEIF (KC == GFP%CSLH%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFCL)
ELSEIF (KC == GFP%CTSP%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MSPRES)
ELSEIF (KC == GFP%CTCC%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFNEBT)
ELSEIF (KC == GFP%CBLD%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFDISH)
ELSEIF (KC == GFP%CSSR%ICOD) THEN
  ! Surface solar radiative flux
  IF(LTFR)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=1
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFRSO)
ELSEIF (KC == GFP%CSTR%ICOD) THEN
  ! Surface thermic radiative flux
  IF(LTFR)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=1
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFRTH)
ELSEIF (KC == GFP%CTSR%ICOD) THEN
  ! Top solar radiative flux
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRSO)
ELSEIF (KC == GFP%CTTR%ICOD) THEN
  ! Top thermic radiative flux
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRTH)
ELSEIF (KC == GFP%CCCC%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MNEBCON)
ELSEIF (KC == GFP%CHCC%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MNEBHAU)
ELSEIF (KC == GFP%CMCC%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MNEBMOY)
ELSEIF (KC == GFP%CLCC%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MNEBBAS)
ELSEIF (KC == GFP%CUGW%ICOD) THEN
  ! Gravity wave drag on U
  IF(LTSTRD)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MSTRDU)
ELSEIF (KC == GFP%CVGW%ICOD) THEN
  ! Gravity wave drag on V
  IF(LTSTRD)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MSTRDV)
ELSEIF (KC == GFP%CUTO%ICOD) THEN
  ! Total drag on U
  IF(LTSTRD)THEN
    INFLEVD=KFLEVG
  ELSE
    INFLEVD=0
  ENDIF
  IF(LTSTRT)THEN
    INFLEVT=KFLEVG
  ELSE
    INFLEVT=0
  ENDIF
  IF (YDCFU%YCFUPT%MSTRDU > 0) THEN
     PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEVD+YDCFU%YCFUPT%MSTRDU)+PCFU(IST:KEND,INFLEVT+YDCFU%YCFUPT%MSTRTU)
  ELSE
     PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEVT+YDCFU%YCFUPT%MSTRTU)
  END IF
ELSEIF (KC == GFP%CVTO%ICOD) THEN
  ! Total drag on V
  IF(LTSTRD)THEN
    INFLEVD=KFLEVG
  ELSE
    INFLEVD=0
  ENDIF
  IF(LTSTRT)THEN
    INFLEVT=KFLEVG
  ELSE
    INFLEVT=0
  ENDIF
  IF (YDCFU%YCFUPT%MSTRDV>0) THEN
    PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEVD+YDCFU%YCFUPT%MSTRDV)+PCFU(IST:KEND,INFLEVT+YDCFU%YCFUPT%MSTRTV)
  ELSE
    PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEVT+YDCFU%YCFUPT%MSTRTV)
  END IF
ELSEIF (KC == GFP%CE%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFEVL)
ELSEIF (KC == GFP%CS%ICOD  ) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFEVN)
ELSEIF (KC == GFP%CT%ICOD  ) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFEVN)+PCFU(IST:KEND,YDCFU%YCFUPT%MFEVL)
ELSEIF (KC == GFP%CLHE%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFCLL)
ELSEIF (KC == GFP%CLHS%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFCLN)
ELSEIF (KC == GFP%CLHT%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFCLN)+PCFU(IST:KEND,YDCFU%YCFUPT%MFCLL)
ELSEIF (KC == GFP%CWS%ICOD ) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MWS)
ELSEIF (KC == GFP%CSNS%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MSNS)
ELSEIF (KC == GFP%CQTO%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MQTOT)
ELSEIF (KC == GFP%CTO3%ICOD .AND. YDCFU%YCFUPT%MOZONT > 0) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MOZONT)
ELSEIF (KC == GFP%CTME%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFTOPH)
ELSEIF (KC == GFP%CICE%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MQICE)
ELSEIF (KC == GFP%CLI%ICOD ) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MQLI)
ELSEIF (KC == GFP%CCVU%ICOD) THEN
  ! Convection on U
  IF(LTSTRC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MSTRCU)
ELSEIF (KC == GFP%CCVV%ICOD) THEN
  ! Convection on V
  IF(LTSTRC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MSTRCV)
ELSEIF (KC == GFP%CCVQ%ICOD) THEN
  ! Convection on Q
  IF(LTSTRC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFDICQ)
ELSEIF (KC == GFP%CCVS%ICOD) THEN
  ! Convection on Cp.T
  IF(LTSTRC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFDICS)
ELSEIF (KC == GFP%CTUQ%ICOD) THEN
  ! Turbulence on Q
  IF(LTSTRT)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFDITQ)
ELSEIF (KC == GFP%CTUS%ICOD) THEN
  ! Turbulence on Cp.T
  IF(LTSTRT)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,INFLEV+YDCFU%YCFUPT%MFDITS)
ELSEIF (KC == GFP%CTSOC%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRSOC0)
ELSEIF (KC == GFP%CSOC%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRSOC1)
ELSEIF (KC == GFP%CTTHC%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRTHC0)
ELSEIF (KC == GFP%CTHC%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRTHC1)
ELSEIF (KC == GFP%CDNI%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRSDNI)
ELSEIF (KC == GFP%CGNI%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRSGNI)
ELSEIF (KC == GFP%CSOP%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRSOPS)
ELSEIF (KC == GFP%CTOP%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRSOPT)
ELSEIF (KC == GFP%CSOD%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRSODS)
ELSEIF (KC == GFP%CTHD%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFRTHDS)
ELSEIF (KC == GFP%CFON%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFONTE)
ELSEIF (KC == GFP%CCHS%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFCHSP)
ELSEIF (KC == GFP%CEAS%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFLWSP)
ELSEIF (KC == GFP%CSRU%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MRUISS)
ELSEIF (KC == GFP%CDRU%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MRUISP)
ELSEIF (KC == GFP%CIRU%ICOD .AND. YDCFU%YCFUPT%MRUISL > 0) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MRUISL)
ELSEIF (KC == GFP%CETP%ICOD .AND. YDCFU%YCFUPT%MFEVV  > 0) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFEVV)
ELSEIF (KC == GFP%CTP%ICOD  .AND. YDCFU%YCFUPT%MFTR   > 0) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFTR)
ELSEIF (KC == GFP%CDUTP%ICOD) THEN
  PFPBUF1(IST:KEND)=PCFU(IST:KEND,YDCFU%YCFUPT%MFDUTP)
ENDIF

!     ------------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('HPOS_CFU',1,ZHOOK_HANDLE)
END SUBROUTINE HPOS_CFU
