! (C) Copyright 1989- Meteo-France.

SUBROUTINE HPOS_XFU(YDAFN,LDFPOSHOR,YDXFU,YDPHY,YDPHY1,KPROMA,KFLEVG,YDSURF,KEND,KC,KFPCLI,PGM,PWSXI,PSP_RR,PSD_VX,PSD_VF,PSD_VV, &
 & PXFU,PFPBUF1)

!**** *HPOS_XFU*  - HORIZONTAL POST-PROCESSING

!     PURPOSE.
!     --------
!        FILL THE "SEMI-LAGRANGIAN" BUFFERS WITH THE FIELDS TO TRANSFER
!        OR INTERPOLATE

!**   INTERFACE.
!     ----------
!       *CALL* *HPOS_XFU*

!        EXPLICIT ARGUMENTS
!        --------------------
!         INPUT:
!          LDFPOSHOR  : .true. if actual horizontal interpolations
!          KPROMA     : horizontal dimension
!          KFLEVG     : number of vertical levels
!          KEND       : last  adress in post-processing buffers to read
!          KC         : field code
!          KFPCLI     : climatology usage
!          PGM        : map factor
!          PWSXI      : maximum surface soil moisture
!          PSP_RR     : surface prognostic quantities 
!          PSD_VX     : auxilary climatological diagnostic fields
!          PSD_VV     : vegetation diagnostic fields
!          PSD_VF     : climatological/geographical diagnostic fields
!          PXFU       : instantaneous fluxes

!         INPUT/OUTPUT:
!          PFPBUF1    : interpolation buffer containing the fields to interpolate

!        IMPLICIT ARGUMENTS
!        --------------------
!        se #include below.

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS
!        See documentation about FULL-POS.

!     AUTHOR.
!     -------
!        RYAD EL KHATIB *METEO-FRANCE*
!        ORIGINAL : 19-Sep-2016 from HPOS

!     MODIFICATIONS.
!     --------------
!     09-2018, R. Brozkova: Added mean radiant temperature.
!     ------------------------------------------------------------------

USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM     ,JPRB
USE YOMHOOK  , ONLY : LHOOK    ,DR_HOOK, JPHOOK
USE YOMPHY   , ONLY : TPHY
USE YOMXFU   , ONLY : TXFU
USE YOMAFN, ONLY : TAFN


USE YOMCST   , ONLY : RPI
USE YOMPHY1  , ONLY : TPHY1

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE (TAFN),  INTENT(IN) :: YDAFN
LOGICAL           ,INTENT(IN)    :: LDFPOSHOR
TYPE(TPHY)        ,INTENT(IN)    :: YDPHY
TYPE(TPHY1)       ,INTENT(IN)    :: YDPHY1
TYPE(TXFU)        ,INTENT(IN)    :: YDXFU
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEVG
TYPE(TSURF)       ,INTENT(IN)    :: YDSURF
INTEGER(KIND=JPIM),INTENT(IN)    :: KEND 
INTEGER(KIND=JPIM),INTENT(IN)    :: KC
INTEGER(KIND=JPIM),INTENT(IN)    :: KFPCLI
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGM(KPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWSXI
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSP_RR(:,:)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSD_VX(:,:)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSD_VF(:,:)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSD_VV(:,:)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXFU(KPROMA,YDXFU%NFDXFU)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFPBUF1(KPROMA) 

REAL(KIND=JPRB) :: ZWFC(KPROMA),ZWWILT(KPROMA), ZWSAT(KPROMA)
REAL(KIND=JPRB) :: ZWSMX(KPROMA), ZWPMX(KPROMA), ZDUMM(KPROMA)

REAL(KIND=JPRB) :: Z1SWSX

INTEGER(KIND=JPIM) :: IST, INFLEV, JI, IANO

LOGICAL :: LLHMT

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "acsolw.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('HPOS_XFU',0,ZHOOK_HANDLE)
ASSOCIATE(GFP=>YDAFN%GFP, GFP_PHYDS=>YDAFN%GFP_PHYDS, &
 & YSD_VF=>YDSURF%YSD_VF, YSD_VV=>YDSURF%YSD_VV, YSD_VX=>YDSURF%YSD_VX, YSP_RR=>YDSURF%YSP_RR, &
 & LTXR=>YDXFU%LTXR, LTXTRC=>YDXFU%LTXTRC, LTXTRD=>YDXFU%LTXTRD, LTXTRT=>YDXFU%LTXTRT, NFDXFU=>YDXFU%NFDXFU, &
 & LSOLV=>YDPHY%LSOLV, GCONV=>YDPHY1%GCONV, RD1=>YDPHY1%RD1)
!     ------------------------------------------------------------------

!*       1. PRELIMINARY INITIALISATIONS.
!           ----------------------------

IST=1

!*       5.2 Fill buffer.

IF (LDFPOSHOR.OR.KFPCLI > 0) THEN
  IANO=GFP_PHYDS(KC)%IANO
ELSE
  ! No interpolation nor change of physiography <=> only buffers transfers
  IANO=0
ENDIF

IF     (KC == GFP%XTCC%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXNEBT)
ELSEIF (KC == GFP%X10U%ICOD.AND.YDXFU%YXFUPT%MXUCLS > 0) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXUCLS)
ELSEIF (KC == GFP%X10V%ICOD.AND.YDXFU%YXFUPT%MXVCLS > 0) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXVCLS)
ELSEIF (KC == GFP%X10FF%ICOD.AND.YDXFU%YXFUPT%MXUCLS > 0 .AND.YDXFU%YXFUPT%MXVCLS > 0) THEN
  PFPBUF1(IST:KEND)=SQRT(&
   & (PXFU(IST:KEND,YDXFU%YXFUPT%MXUCLS)*PGM(IST:KEND))**2+&
   & (PXFU(IST:KEND,YDXFU%YXFUPT%MXVCLS)*PGM(IST:KEND))**2)
ELSEIF (KC == GFP%X10NU%ICOD.AND.YDXFU%YXFUPT%MXNUCLS > 0) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXNUCLS)
ELSEIF (KC == GFP%X10NV%ICOD.AND.YDXFU%YXFUPT%MXNVCLS > 0) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXNVCLS)  
ELSEIF (KC == GFP%X2T%ICOD.AND.YDXFU%YXFUPT%MXTCLS > 0) THEN
  IF (IANO == 0 .OR..NOT.YSP_RR%YT%LSET) THEN
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXTCLS)
  ELSE
    ! Interpolation of T2m-Ts
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXTCLS)-PSP_RR(IST:KEND,YSP_RR%YT%MP0)
  ENDIF
ELSEIF (KC == GFP%X2SH%ICOD.AND.YDXFU%YXFUPT%MXQCLS > 0) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXQCLS)
ELSEIF (KC == GFP%X2RH%ICOD.AND.YDXFU%YXFUPT%MXRHCLS > 0) THEN
  IF (IANO == 0 .OR..NOT.YSP_RR%YW%LSET) THEN
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXRHCLS)
  ELSEIF(KFPCLI <= 2) THEN
    ! Interpolation of HU2m-HUs
    Z1SWSX=1.0_JPRB/PWSXI
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXRHCLS)&
     & - 0.5_JPRB*(1.0_JPRB-COS(RPI*PSP_RR(IST:KEND,YSP_RR%YW%MP0)*Z1SWSX))  
  ELSE
    ! ISBA option
    IF (YSD_VV%YARG%LSET) THEN
      LLHMT=.TRUE. ! no need for vegetation index, d2, sand
      ZDUMM(:)=HUGE(1.0_JPRB)
      IF (YSD_VX%YLSM%LSET.AND..NOT.YSD_VF%YLSM%LSET) THEN
        ! Use extra land-sea mask (SURFEX case)
        CALL ACSOLW(YDPHY1,IST,KEND,KPROMA,PSD_VV(:,YSD_VV%YARG%MP),ZDUMM,&
         & PSD_VX(:,YSD_VX%YLSM%MP),ZDUMM,ZDUMM,LLHMT,ZWFC,ZWPMX,ZWSAT,ZWSMX,ZWWILT)
!DEC$ IVDEP
        DO JI=IST,KEND
          Z1SWSX=1.0_JPRB/(ZWFC(JI)*GCONV*RD1)
          PFPBUF1(JI)=PXFU(JI,YDXFU%YXFUPT%MXRHCLS)- 0.5_JPRB&
           & *(1.0_JPRB-COS(RPI*MIN(PSP_RR(JI,YSP_RR%YW%MP0)*Z1SWSX,1.0_JPRB)))
        ENDDO
      ELSEIF (YSD_VF%YLSM%LSET) THEN
        ! Current ISBA case
        CALL ACSOLW(YDPHY1,IST,KEND,KPROMA,PSD_VV(:,YSD_VV%YARG%MP),ZDUMM,&
         & PSD_VF(:,YSD_VF%YLSM%MP),ZDUMM,ZDUMM,LLHMT,ZWFC,ZWPMX,ZWSAT,ZWSMX,ZWWILT)
!DEC$ IVDEP
        DO JI=IST,KEND
          Z1SWSX=1.0_JPRB/(ZWFC(JI)*GCONV*RD1)
          PFPBUF1(JI)=PXFU(JI,YDXFU%YXFUPT%MXRHCLS)- 0.5_JPRB&
           & *(1.0_JPRB-COS(RPI*MIN(PSP_RR(JI,YSP_RR%YW%MP0)*Z1SWSX,1.0_JPRB)))
        ENDDO
      ELSE
        Z1SWSX=1.0_JPRB/PWSXI
        PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXRHCLS)&
         & - 0.5_JPRB*(1.0_JPRB-COS(RPI*PSP_RR(IST:KEND,YSP_RR%YW%MP0)*Z1SWSX))  
      ENDIF
    ELSE
      Z1SWSX=1.0_JPRB/PWSXI
      PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXRHCLS)&
       & - 0.5_JPRB*(1.0_JPRB-COS(RPI*PSP_RR(IST:KEND,YSP_RR%YW%MP0)*Z1SWSX))  
    ENDIF
  ENDIF
ELSEIF (KC == GFP%XCCC%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXNBCON)
ELSEIF (KC == GFP%XHCC%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXNBHAU)
ELSEIF (KC == GFP%XMCC%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXNBMOY)
ELSEIF (KC == GFP%XLCC%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXNBBAS)
ELSEIF (KC == GFP%XXDIAGH%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXXDIAGH)
ELSEIF (KC == GFP%VISICLD%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXVISICLD)
ELSEIF (KC == GFP%VISIHYD%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXVISIHYD)
ELSEIF (KC == GFP%MXCLWC%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXCLWC)
ELSEIF (KC == GFP%VISICLD2%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXVISICLD2)
ELSEIF (KC == GFP%VISIHYD2%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXVISIHYD2)
ELSEIF (KC == GFP%MXCLWC2%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXCLWC2)
ELSEIF (KC == GFP%X2TPW%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXTPWCLS)
ELSEIF (KC == GFP%XPTYPE%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPTYPE)
ELSEIF (KC == GFP%XPTYPESEV%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPTYPESEV)
ELSEIF (KC == GFP%XPTYPE2%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPTYPE2)
ELSEIF (KC == GFP%XPTYPESEV2%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPTYPESEV2)  
ELSEIF (KC == GFP%XX2T%ICOD.AND.YDXFU%YXFUPT%MXTX > 0) THEN
  IF (IANO == 0) THEN
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXTX)
  ELSE
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXTX)-PXFU(IST:KEND,YDXFU%YXFUPT%MXTCLS)
  ENDIF 
ELSEIF (KC == GFP%XN2T%ICOD.AND.YDXFU%YXFUPT%MXTN > 0) THEN
  IF (IANO == 0) THEN
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXTN)
  ELSE
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXTN)-PXFU(IST:KEND,YDXFU%YXFUPT%MXTCLS)
  ENDIF
ELSEIF (KC == GFP%XX2HU%ICOD.AND.YDXFU%YXFUPT%MXHUX > 0) THEN
  IF (IANO == 0) THEN
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXHUX)
  ELSE
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXHUX)-PXFU(IST:KEND,YDXFU%YXFUPT%MXRHCLS)
  ENDIF
ELSEIF (KC == GFP%XN2HU%ICOD.AND.YDXFU%YXFUPT%MXHUN > 0) THEN
  IF (IANO == 0) THEN
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXHUN)
  ELSE
    PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXHUN)-PXFU(IST:KEND,YDXFU%YXFUPT%MXRHCLS)
  ENDIF
ELSEIF (KC == GFP%INCTX%ICOD .AND.YDXFU%YXFUPT%MXTX > 0 .AND. YDXFU%YXFUPT%MXTCLS > 0) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXTX)-PXFU(IST:KEND,YDXFU%YXFUPT%MXTCLS)
ELSEIF (KC == GFP%INCTN%ICOD .AND.YDXFU%YXFUPT%MXTN > 0 .AND. YDXFU%YXFUPT%MXTCLS > 0) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXTN)-PXFU(IST:KEND,YDXFU%YXFUPT%MXTCLS)
ELSEIF (KC == GFP%INCHN%ICOD .AND.YDXFU%YXFUPT%MXHUN > 0 .AND. YDXFU%YXFUPT%MXRHCLS > 0) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXHUN)-PXFU(IST:KEND,YDXFU%YXFUPT%MXRHCLS)
ELSEIF (KC == GFP%INCHX%ICOD .AND.YDXFU%YXFUPT%MXHUX > 0 .AND. YDXFU%YXFUPT%MXRHCLS > 0) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXHUX)-PXFU(IST:KEND,YDXFU%YXFUPT%MXRHCLS)
ELSEIF (KC == GFP%XCVU%ICOD) THEN
  ! Convection on U
  IF(LTXTRC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV+YDXFU%YXFUPT%MXTRCU)
ELSEIF (KC == GFP%XCVV%ICOD) THEN
  ! Convection on V
  IF(LTXTRC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV+YDXFU%YXFUPT%MXTRCV)
ELSEIF (KC == GFP%XCVQ%ICOD) THEN
  ! Convection on Q
  IF(LTXTRC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV+YDXFU%YXFUPT%MXDICQ)
ELSEIF (KC == GFP%XCVS%ICOD) THEN
  ! Convection on Cp.T
  IF(LTXTRC)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV+YDXFU%YXFUPT%MXDICS)
ELSEIF (KC == GFP%XTUU%ICOD) THEN
  ! Turbulence on U
  IF(LTXTRT)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV+YDXFU%YXFUPT%MXTRTU)
ELSEIF (KC == GFP%XTUV%ICOD) THEN
  ! Turbulence on V
  IF(LTXTRT)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV+YDXFU%YXFUPT%MXTRTV)
ELSEIF (KC == GFP%XTUQ%ICOD) THEN
  ! Turbulence on Q
  IF(LTXTRT)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV+YDXFU%YXFUPT%MXDITQ)
ELSEIF (KC == GFP%XTUS%ICOD) THEN
  ! Turbulence on Cp.T
  IF(LTXTRT)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV+YDXFU%YXFUPT%MXDITS)
ELSEIF (KC == GFP%XGDU%ICOD) THEN
  ! Gravity wave drag on U
  IF(LTXTRD)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV+YDXFU%YXFUPT%MXTRDU)
ELSEIF (KC == GFP%XGDV%ICOD) THEN
  ! Gravity wave drag on V
  IF(LTXTRD)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=0
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV+YDXFU%YXFUPT%MXTRDV)
ELSEIF (KC == GFP%XLSP%ICOD) THEN
  ! Stratiform precipitations
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPLSL)
ELSEIF (KC == GFP%XCP%ICOD ) THEN
  ! Convective precipitations
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPLCL)
ELSEIF (KC == GFP%XLSS%ICOD.AND.YDXFU%YXFUPT%MXPLSN > 0) THEN
  ! Stratiform snow
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPLSN)
ELSEIF (KC == GFP%XCSF%ICOD.AND.YDXFU%YXFUPT%MXPLCN > 0) THEN
  ! Convective snow
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPLCN)
ELSEIF (KC == GFP%XLSG%ICOD.AND.YDXFU%YXFUPT%MXPLSG > 0) THEN
  ! Stratiform graupel
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPLSG)
ELSEIF (KC == GFP%XCSG%ICOD.AND.YDXFU%YXFUPT%MXPLCG > 0) THEN
  ! Convective graupel
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPLCG)
ELSEIF (KC == GFP%XLSH%ICOD.AND.YDXFU%YXFUPT%MXPLSH > 0) THEN
  ! Stratiform hail
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPLSH)
ELSEIF (KC == GFP%XCSH%ICOD.AND.YDXFU%YXFUPT%MXPLCH > 0) THEN
  ! Convective hail
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXPLCH)
ELSEIF (KC == GFP%XSSR%ICOD) THEN
  !           Surface solar radiative flux
  IF(LTXR)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=1
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV-1+YDXFU%YXFUPT%MXRSO)
ELSEIF (KC == GFP%XSTR%ICOD) THEN
  ! Surface thermic radiative flux
  IF(LTXR)THEN
    INFLEV=KFLEVG
  ELSE
    INFLEV=1
  ENDIF
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,INFLEV-1+YDXFU%YXFUPT%MXRTH)
ELSEIF (KC == GFP%XTSR%ICOD) THEN
  ! Top solar radiative flux
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXRSO)
ELSEIF (KC == GFP%XTTR%ICOD) THEN
  ! Top thermic radiative flux
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXRTH)
ELSEIF (KC == GFP%XCAPE%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXCAPE)
ELSEIF (KC == GFP%XCTOP%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXCTOP)
ELSEIF (KC == GFP%XMOCO%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXMOCON)
ELSEIF (KC == GFP%XCLPH%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXCLPH)
ELSEIF (KC == GFP%XVEIN%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXVEIN)
ELSEIF (KC == GFP%XMRT%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXMRT)
ELSEIF (KC == GFP%XUGST%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXUGST)
ELSEIF (KC == GFP%XVGST%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXVGST)
ELSEIF (KC == GFP%XUGST2%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXUGST2)
ELSEIF (KC == GFP%XVGST2%ICOD) THEN
  PFPBUF1(IST:KEND)=PXFU(IST:KEND,YDXFU%YXFUPT%MXVGST2)
ENDIF

!     ------------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('HPOS_XFU',1,ZHOOK_HANDLE)
END SUBROUTINE HPOS_XFU
