! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPUSERGEO(YDNAMFPSCI,CDFPFMT,CDFPDOM,YDNAMFPD,YDNAMFPG,KFPCONF,YDGEOMETRY,K,YDFPUSERGEO)

!**** *SUFPUSERGEO*  - INITIALIZE THE GEOMETRY OF A POST-PROCESSED GRID FOR FULLPOS FROM THE MODULE YOMFPD

!     PURPOSE.
!     --------
!        ALLOCATE AND FILL THE STRUCTURE DEFINING THE GEOMETRY OF A POST-PROCESSED GRID FROM THE NAMELIST VARIABLES
!        THEN CONTROL ITS CONSISTENCY

!        Notice : angles of Fullpos structure are in degrees (RLON.., RLAT..)

!**   INTERFACE.
!     ----------
!       *CALL* *SUFPUSERGEO*

!        EXPLICIT ARGUMENTS
!        ------------------
!           YDNAMFPD: namelist structure of dimensionning parameters
!           KFPCONF : configuration of the post-processing :
!                     0 : vertical interpolation only (<CFPFMT='MODEL'>)
!                     1 : gridpoint post-processing, possibly with spectral filters (<NFPOS=1>)
!                     2 : gridpoint/spectral post-processing (spectral outputs possible) (<NFPOS=2>)

!        IMPLICIT ARGUMENTS
!        ------------------

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS
!        Documentation about FULL-POS.

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 13-Mar-2017

!     MODIFICATIONS.
!     --------------
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM, JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMCST_IFSAUX, ONLY: XRPI

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMLUN   , ONLY : NULOUT
USE YOMCT0   , ONLY : LELAM
USE YOMMP0   , ONLY : LSPLIT, NPROC
USE YOMFPC        , ONLY : TNAMFPSCI, LTRACEFP
USE YOMFPD, ONLY : TNAMFPD
USE YOMFPG, ONLY : TNAMFPG
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO, ALLOC_FPUSERGEO, PRINT_FPUSERGEO, CHECK_FPUSERGEO

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE (TNAMFPSCI),  INTENT(IN) :: YDNAMFPSCI
CHARACTER(LEN=*),   INTENT(IN)    :: CDFPFMT
CHARACTER(LEN=*),   INTENT(IN)    :: CDFPDOM
TYPE(TNAMFPD),      INTENT(IN)    :: YDNAMFPD
TYPE(TNAMFPG),      INTENT(IN)    :: YDNAMFPG
INTEGER(KIND=JPIM), INTENT(IN)    :: KFPCONF
TYPE(GEOMETRY),     INTENT(IN)    :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN)    :: K
TYPE (TFPUSERGEO),  INTENT(INOUT) :: YDFPUSERGEO

LOGICAL            :: LLMODELGEO ! .TRUE. if the spectral transforms variables are equal to the model ones
LOGICAL            :: LLFPTRANS  ! .TRUE. if output spectral transforms ( /= model) needed
LOGICAL            :: LLGRIDONLY ! .TRUE. if grid only, not spectral
LOGICAL            :: LLETRANS   ! Inquired LAM/Global flag (0 stands for the model tag)
INTEGER(KIND=JPIM) :: ILAT

REAL(KIND=JPRB)    :: ZEXWN, ZEYWN, ZLO0, ZLA0, ZLOC, ZLAC, ZEPS, ZRDTODG
REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE


#include "setup_trans.h"
#include "esetup_trans.h"
#include "trans_inq.h"
#include "etrans_inq.h"

#include "updtrans.intfb.h"

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SUFPUSERGEO',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDGEM=>YDGEOMETRY%YRGEM,YDEGEO=>YDGEOMETRY%YREGEO)
ASSOCIATE(NFPBOYD=>YDNAMFPSCI%NFPBOYD, &
 & NDGLG=>YDDIM%NDGLG, NDLON=>YDDIM%NDLON, NMSMAX=>YDDIM%NMSMAX, NSMAX=>YDDIM%NSMAX, &
 & NDGUXG=>YDDIM%NDGUXG, NDLUXG=>YDDIM%NDLUXG, NRESOL=>YDDIM%NRESOL,NLOENG=>YDGEM%NLOENG, &
 & NHTYP=>YDGEM%NHTYP, NSTTYP=>YDGEM%NSTTYP, &
 & RLOCEN=>YDGEM%RLOCEN, RMUCEN=>YDGEM%RMUCEN, RSTRET=>YDGEM%RSTRET, &
 & EDELX=>YDEGEO%EDELX, EDELY=>YDEGEO%EDELY, ELAT0=>YDEGEO%ELAT0, &
 & ELATC=>YDEGEO%ELATC, ELON0=>YDEGEO%ELON0, ELONC=>YDEGEO%ELONC, &
 & ELX=>YDEGEO%ELX, ELY=>YDEGEO%ELY, LMAP=>YDEGEO%LMAP, LMRT=>YDEGEO%LMRT)

!*       1. ALLOCATE AND FILL STRUCTURE WITH USER PARAMETER
!           -----------------------------------------------

YDFPUSERGEO%CFPGRID  = CDFPFMT
YDFPUSERGEO%CFPDOM   = CDFPDOM
YDFPUSERGEO%NLAT     = YDNAMFPD%NLAT(K)
YDFPUSERGEO%NLON     = YDNAMFPD%NLON(K)
YDFPUSERGEO%NFPMAX   = YDNAMFPG%NFPMAX(K)
YDFPUSERGEO%NMFPMAX  = YDNAMFPG%NMFPMAX
YDFPUSERGEO%NFPHTYP  = YDNAMFPG%NFPHTYP
YDFPUSERGEO%NFPTTYP  = YDNAMFPG%NFPTTYP
YDFPUSERGEO%FPMUCEN  = YDNAMFPG%FPMUCEN
YDFPUSERGEO%FPLOCEN  = YDNAMFPG%FPLOCEN 
YDFPUSERGEO%FPSTRET  = YDNAMFPG%FPSTRET 
YDFPUSERGEO%RDELY    = YDNAMFPD%RDELY(K)
YDFPUSERGEO%RDELX    = YDNAMFPD%RDELX(K)
YDFPUSERGEO%NFPGUX   = YDNAMFPD%NFPGUX
YDFPUSERGEO%NFPLUX   = YDNAMFPD%NFPLUX
IF (NFPBOYD==0) THEN
  YDFPUSERGEO%NFPBWX   = 0
  YDFPUSERGEO%NFPBWY   = 0
ELSE
  YDFPUSERGEO%NFPBWX   = YDNAMFPD%NFPBWX
  YDFPUSERGEO%NFPBWY   = YDNAMFPD%NFPBWY
ENDIF
YDFPUSERGEO%RLATC    = YDNAMFPD%RLATC(K)
YDFPUSERGEO%RLONC    = YDNAMFPD%RLONC(K)
YDFPUSERGEO%FPLON0   = YDNAMFPG%FPLON0
YDFPUSERGEO%FPLAT0   = YDNAMFPG%FPLAT0
YDFPUSERGEO%LFPMRT   = YDNAMFPG%LFPMRT
YDFPUSERGEO%LFPMAP   = YDNAMFPG%LFPMAP
YDFPUSERGEO%NFPBZONL = YDNAMFPD%NFPBZONL
YDFPUSERGEO%NFPBZONG = YDNAMFPD%NFPBZONG
YDFPUSERGEO%NFPNOEXTZL  = YDNAMFPD%NFPNOEXTZL
YDFPUSERGEO%NFPNOEXTZG  = YDNAMFPD%NFPNOEXTZG
IF (YDFPUSERGEO%CFPGRID == 'LELAM') THEN
  IF (KFPCONF /= 1) THEN
    ! supposed to be spectral outputs
    YDFPUSERGEO%NFPEDOM = 1
  ELSEIF (.NOT.(YDFPUSERGEO%NLON == YDFPUSERGEO%NFPLUX .AND. YDFPUSERGEO%NLAT == YDFPUSERGEO%NFPGUX)) THEN  
    ! supposed to be gridpoint with extension zone
    YDFPUSERGEO%NFPEDOM = -1
  ELSE
    ! supposed to be gridpoint without extension zone
    YDFPUSERGEO%NFPEDOM = 0
  ENDIF
ELSE
  YDFPUSERGEO%NFPEDOM = 0
ENDIF
IF (YDFPUSERGEO%CFPGRID /= 'GAUSS') THEN
  YDFPUSERGEO%NFPRLX = YDNAMFPD%NFPRLX
  YDFPUSERGEO%NFPRLY = YDNAMFPD%NFPRLY
  YDFPUSERGEO%NFPRUX = YDNAMFPD%NFPRUX
  YDFPUSERGEO%NFPRUY = YDNAMFPD%NFPRUY
ENDIF
CALL ALLOC_FPUSERGEO(YDFPUSERGEO)

YDFPUSERGEO%NFPRGRI(:)= YDNAMFPG%NFPRGRI(1:YDFPUSERGEO%NLAT)

CALL CHECK_FPUSERGEO(YDFPUSERGEO,NULOUT)

!*       2. FINALIZE STRUCTURE WITH VARIABLES COMPUTED FROM THE SPECTRAL TRANSFORMS PACKAGE
!           -------------------------------------------------------------------------------

! Find if the dimensions needed to setup the spectral transforms are different from the model one
! (if not, the same resolution tag can be used)

YDFPUSERGEO%LFPMODELSPEC = (YDFPUSERGEO%NFPMAX == NSMAX)
IF(YDFPUSERGEO%CFPGRID == 'LELAM' .AND. LELAM) THEN
  IF (YDFPUSERGEO%LFPMODELSPEC) YDFPUSERGEO%LFPMODELSPEC = (YDFPUSERGEO%NMFPMAX == NMSMAX)
ELSEIF (YDFPUSERGEO%CFPGRID == 'LALON') THEN
  YDFPUSERGEO%LFPMODELSPEC=.FALSE.
ENDIF

YDFPUSERGEO%LFPMODELGRID = (YDFPUSERGEO%NLON == NDLON).AND.(YDFPUSERGEO%NLAT == NDGLG)
IF (YDFPUSERGEO%CFPGRID == 'GAUSS' .AND. .NOT.LELAM) THEN
   IF (YDFPUSERGEO%LFPMODELGRID) YDFPUSERGEO%LFPMODELGRID = (ALL(YDFPUSERGEO%NFPRGRI(1:YDFPUSERGEO%NLAT) == NLOENG(1:NDGLG)))
ELSEIF(YDFPUSERGEO%CFPGRID == 'LALON') THEN
  YDFPUSERGEO%LFPMODELGRID=.FALSE.
ENDIF

IF(YDFPUSERGEO%CFPGRID == 'LELAM' .AND. LELAM) THEN
  YDFPUSERGEO%LFPMODELCORE = (YDFPUSERGEO%NFPLUX == NDLUXG).AND.(YDFPUSERGEO%NFPGUX == NDGUXG)
ELSEIF (YDFPUSERGEO%CFPGRID == 'GAUSS' .AND. .NOT.LELAM) THEN
  YDFPUSERGEO%LFPMODELCORE = YDFPUSERGEO%LFPMODELGRID
ELSE
  YDFPUSERGEO%LFPMODELCORE = .FALSE.
ENDIF

ZEPS = EPSILON(1.0_JPRB)*10000._JPRB
IF (YDFPUSERGEO%CFPGRID == 'GAUSS' .AND. .NOT.LELAM) THEN
  YDFPUSERGEO%LFPCOORD = (.NOT.YDFPUSERGEO%LFPMODELCORE) .OR. &
   & (ABS(YDFPUSERGEO%FPSTRET-RSTRET) > ZEPS) .OR. (YDFPUSERGEO%NFPTTYP /= NSTTYP) .OR. &
   & (ABS(YDFPUSERGEO%FPMUCEN-RMUCEN) > ZEPS) .OR. (ABS(YDFPUSERGEO%FPLOCEN-RLOCEN) > ZEPS)
ELSEIF(YDFPUSERGEO%CFPGRID == 'LELAM' .AND. LELAM) THEN
  IF (LMAP) THEN
    ZRDTODG=180._JPRB/XRPI
    ZLO0=ABS(MOD(YDFPUSERGEO%FPLON0-ELON0*ZRDTODG,360._JPRB))
    ZLA0=ABS(MOD(YDFPUSERGEO%FPLAT0-ELAT0*ZRDTODG,360._JPRB))
    ZLOC=ABS(MOD(YDFPUSERGEO%RLONC-ELONC*ZRDTODG,360._JPRB))
    ZLAC=ABS(MOD(YDFPUSERGEO%RLATC-ELATC*ZRDTODG,360._JPRB))
    YDFPUSERGEO%LFPCOORD = (.NOT.YDFPUSERGEO%LFPMODELCORE) .OR. &
     & (ZLO0 > ZEPS.AND.(360._JPRB-ZLO0) > ZEPS) .OR. &
     & (ZLA0 > ZEPS.AND.(360._JPRB-ZLA0) > ZEPS) .OR. &
     & (ZLAC > ZEPS.AND.(360._JPRB-ZLAC) > ZEPS) .OR. &
     & (ZLOC > ZEPS.AND.(360._JPRB-ZLOC) > ZEPS) .OR. ((YDFPUSERGEO%LFPMRT.NEQV.LMRT)) .OR. &
     & (ABS(YDFPUSERGEO%RDELX-EDELX) > ZEPS) .OR. (ABS(YDFPUSERGEO%RDELY-EDELY) > ZEPS)
  ELSE
    YDFPUSERGEO%LFPCOORD = (.NOT.YDFPUSERGEO%LFPMODELCORE) .OR. &
     & (ABS(YDFPUSERGEO%FPLX-ELX) > ZEPS) .OR. (ABS(YDFPUSERGEO%FPLY-ELY) > ZEPS)
  ENDIF
ELSE
  YDFPUSERGEO%LFPCOORD=.TRUE.
ENDIF

! If a non-empty extension zone exists
IF (YDFPUSERGEO%CFPGRID == 'LELAM' .AND. &
 & YDFPUSERGEO%NLAT*YDFPUSERGEO%NLON-YDFPUSERGEO%NFPLUX*YDFPUSERGEO%NFPGUX > 0) THEN
  ! No interpolation and no change of the width of the extension zone <=> no biper
  YDFPUSERGEO%LFPBIPER=.NOT.(LELAM.AND.YDFPUSERGEO%LFPMODELGRID.AND..NOT.YDFPUSERGEO%LFPCOORD)
ELSE
  YDFPUSERGEO%LFPBIPER=.FALSE.
ENDIF

! Extract core (no interpolations and no extension zone)
YDFPUSERGEO%LFPLAMCOREXT = LELAM .AND. &
 & .NOT.(YDFPUSERGEO%LFPCOORD .OR. YDFPUSERGEO%LFPBIPER .OR. YDFPUSERGEO%LFPMODELGRID)

! Map factor aspect : only for projections, real case + expected spectral outputs
YDFPUSERGEO%LFPMAPF = (KFPCONF==2 .AND. YDFPUSERGEO%CFPGRID == 'LELAM' .AND. YDFPUSERGEO%LFPMAP)

YDFPUSERGEO%LFPOSBUFSHAPE = YDFPUSERGEO%LFPCOORD .OR. YDFPUSERGEO%LFPBIPER .OR. YDFPUSERGEO%LFPLAMCOREXT

YDFPUSERGEO%NFPSIZEG=SUM(YDFPUSERGEO%NFPRGRI(1:YDFPUSERGEO%NLAT))
IF (NFPBOYD==0) THEN
  YDFPUSERGEO%NFPSIZEG_DEP=YDFPUSERGEO%NFPSIZEG
ELSE
  YDFPUSERGEO%NFPSIZEG_DEP=(YDFPUSERGEO%NFPLUX+2*YDFPUSERGEO%NFPBWX+2*(YDFPUSERGEO%NLON-YDFPUSERGEO%NFPLUX)) &
                        & *(YDFPUSERGEO%NFPGUX+2*YDFPUSERGEO%NFPBWY+2*(YDFPUSERGEO%NLAT-YDFPUSERGEO%NFPGUX))
ENDIF

! a bit weird ...
IF (NPROC > 1) THEN
  IF (.NOT.YDFPUSERGEO%LFPOSBUFSHAPE) THEN
    ! No fullpos buffer => Distribution is meaningless
    YDFPUSERGEO%NFPDIST=0
  ELSEIF ((YDFPUSERGEO%LFPCOORD.OR.YDFPUSERGEO%LFPBIPER) .AND. KFPCONF==2) THEN
    ! The enhanced distribution is mandatory
    YDFPUSERGEO%NFPDIST=2
  ELSEIF (NFPBOYD /= 0) THEN
    ! Distribution is mandatory because we need 2 grids
    YDFPUSERGEO%NFPDIST=MIN(2,MAX(YDNAMFPG%NFPDISTRIB,1))
  ELSE
    YDFPUSERGEO%NFPDIST=MIN(2,MAX(YDNAMFPG%NFPDISTRIB,0))
  ENDIF
ELSE
  IF (.NOT.YDFPUSERGEO%LFPOSBUFSHAPE) THEN
    ! No fullpos buffer => Distribution is meaningless
    YDFPUSERGEO%NFPDIST=0
  ELSEIF (NFPBOYD == 0) THEN
    ! Distribution is meaningless
    YDFPUSERGEO%NFPDIST=0
  ELSE
    ! Distribution is mandatory because we need 2 grids
    YDFPUSERGEO%NFPDIST=MAX(YDNAMFPG%NFPDISTRIB,1)
  ENDIF
ENDIF


IF (KFPCONF== 2 .OR. YDFPUSERGEO%NFPDIST >=2) THEN 
  ! notice : (KFPCONF==2) => (YDFPUSERGEO%NFPDIST==2)
  ! Needs to setup a spectral transform for each subdomain
  LLFPTRANS=.TRUE.
  LLGRIDONLY=.FALSE.
ELSEIF (YDFPUSERGEO%CFPGRID == 'GAUSS') THEN
  LLFPTRANS=.TRUE.
  LLGRIDONLY=.FALSE. ! cannot be true :-(
  ! at least to get the gaussian latitudes and way numbers anyway (output file heders need that)
ELSE
  LLFPTRANS=.FALSE.
  LLGRIDONLY=.FALSE.
ENDIF

! which consequence later in the code will be NFPRESOL(i) > 0

LLMODELGEO = YDFPUSERGEO%LFPMODELSPEC .AND. YDFPUSERGEO%LFPMODELGRID

IF (LLFPTRANS.OR.LLGRIDONLY) THEN
  ! Notice : weighted distribution not yet supported.
  ILAT=YDFPUSERGEO%NLAT
  IF (YDFPUSERGEO%CFPGRID == 'GAUSS') THEN
    IF (LLMODELGEO) THEN
      YDFPUSERGEO%NFPRESOL=NRESOL
    ELSE
      CALL SETUP_TRANS(KSMAX=YDFPUSERGEO%NFPMAX,KDGL=ILAT,KLOEN=YDFPUSERGEO%NFPRGRI(1:ILAT), &
       & LDSPLIT=LSPLIT,LDGRIDONLY=LLGRIDONLY, &
       & LDUSERPNM=(YDNAMFPG%NFPFLT(K) == 0),LDKEEPRPNM=(YDNAMFPG%NFPFLT(K) == 0), &
       & KRESOL=YDFPUSERGEO%NFPRESOL,LDUSEFFTW=(YDNAMFPG%NFPFFTW(K) /= 0),LDUSEFLT=(YDNAMFPG%NFPFLT(K) /= 0))
    ENDIF
    CALL UPDTRANS(YDFPUSERGEO%NFPRESOL,LLETRANS)
    CALL TRANS_INQ(KRESOL=YDFPUSERGEO%NFPRESOL,KSPEC2=YDFPUSERGEO%NSPEC2,KSPEC2G=YDFPUSERGEO%NSPEC2G, &
     & KNMENG=YDFPUSERGEO%NFPMEN(1:ILAT),PMU=YDFPUSERGEO%FPMU(1:ILAT),KGPTOTG=YDFPUSERGEO%NFPSIZEG)
  ELSE
    IF (LLMODELGEO) THEN
      YDFPUSERGEO%NFPRESOL=NRESOL
    ELSE
      ZEXWN=(2.0_JPRB*XRPI)/YDFPUSERGEO%FPLX
      ZEYWN=(2.0_JPRB*XRPI)/YDFPUSERGEO%FPLY
      IF (YDFPUSERGEO%CFPGRID == 'LELAM') THEN
        CALL ESETUP_TRANS(KSMAX=YDFPUSERGEO%NFPMAX,KDGL=ILAT,KLOEN=YDFPUSERGEO%NFPRGRI(1:ILAT), &
         & KMSMAX=YDFPUSERGEO%NMFPMAX,KDGUX=ILAT,PEXWN=ZEXWN,PEYWN=ZEYWN, &
         & KNOEXTZL=YDFPUSERGEO%NFPNOEXTZL,KNOEXTZG=YDFPUSERGEO%NFPNOEXTZG, &
         & LDSPLIT=LSPLIT,LDUSEFFTW=(YDNAMFPG%NFPFFTW(K) /= 0), &
         & LDGRIDONLY=LLGRIDONLY,KRESOL=YDFPUSERGEO%NFPRESOL)
      ELSE
        CALL ESETUP_TRANS(KSMAX=YDFPUSERGEO%NFPMAX,KDGL=ILAT,KLOEN=YDFPUSERGEO%NFPRGRI(1:ILAT), &
         & KMSMAX=YDFPUSERGEO%NMFPMAX,KDGUX=ILAT,PEXWN=ZEXWN,PEYWN=ZEYWN, &
         & LDGRIDONLY=LLGRIDONLY,KRESOL=YDFPUSERGEO%NFPRESOL)
      ENDIF
    ENDIF
    CALL UPDTRANS(YDFPUSERGEO%NFPRESOL,LLETRANS)
    CALL ETRANS_INQ(KRESOL=YDFPUSERGEO%NFPRESOL,KSPEC2=YDFPUSERGEO%NSPEC2,KSPEC2G=YDFPUSERGEO%NSPEC2G, &
     & KGPTOT=YDFPUSERGEO%NGPTOT)
  ENDIF
  IF(LTRACEFP) THEN
    WRITE(NULOUT,'('' NFPRESOL = '',I3,'' LLETRANS = '',L2,'' LLGRIDONLY = '',L2)')  &
   & YDFPUSERGEO%NFPRESOL,LLETRANS,LLGRIDONLY
  ENDIF
ENDIF


IF (LTRACEFP) THEN
  CALL PRINT_FPUSERGEO(YDFPUSERGEO,NULOUT)
ENDIF

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPUSERGEO',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPUSERGEO
