! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPGEOMETRY(YDNAMFPINT,YDNAMFPSCI,YDFPGEOMETRY,YDGEOMETRY,KFPROMA_DEP,KFPROMA,PCO_EZO)

!**** *SUFPGEOMETRY*  - Construct Fullpos geometry object

!     PURPOSE.
!     --------

!       To initialize the post-processing horizontal distribution in the
!       departure and the arrival geometries.
!       To initialize the array slicing for vector or memory cache optimization.

!**   INTERFACE.
!     ----------
!       *CALL* *SUFPGEOMETRY*

!        EXPLICIT ARGUMENTS
!        -------------------

!        IMPLICIT ARGUMENTS
!        --------------------
!        NONE.

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL :  24-Jul-2012 from SUBFPOS

!     MODIFICATIONS.
!     --------------
!      R. El Khatib 31-Aug-2012 new E-zone management
!      R. El Khatib 27-Sep-2013 Boyd periodization in Fullpos-2
!      R. El Khatib 27-Jul-2016 bugfix for the case NFPBW* > 0
!      R. El Khatib 27-Jul-2016 interpolations over C+I+E ; recode LWIDER_DOM
!     ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1  ,ONLY : JPIM ,   JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMLUN   , ONLY : NULOUT
USE YOMCT0   , ONLY : LELAM
USE YOMFPC       , ONLY : TNAMFPSCI, TNAMFPINT, LTRACEFP, LALLOFP, LWIDER_DOM
USE YOMFPGEOMETRY, ONLY : TFPGEOMETRY, LFPOSBUF
USE YOMMP0   ,ONLY : NPROC, MYPROC

!     ------------------------------------------------------------------

IMPLICIT NONE

#include "sufpg2.intfb.h"
#include "suefpg3.intfb.h"
#include "sumpfpos_dep.intfb.h"
#include "fpbipere.h"
#include "sufpmapf.intfb.h"
#include "sufpdistrib.intfb.h"
#include "suprocfp_dep.intfb.h"
#include "suprocfp.intfb.h"
#include "sumpfpos.intfb.h"

!     ------------------------------------------------------------------

TYPE(TNAMFPINT),   INTENT(IN) :: YDNAMFPINT
TYPE (TNAMFPSCI),  INTENT(IN) :: YDNAMFPSCI
TYPE (TFPGEOMETRY), INTENT(INOUT) :: YDFPGEOMETRY
TYPE(GEOMETRY),     INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM), INTENT(IN) :: KFPROMA_DEP
INTEGER(KIND=JPIM), INTENT(IN) :: KFPROMA
REAL(KIND=JPRB),    INTENT(IN) :: PCO_EZO


REAL(KIND=JPRB), ALLOCATABLE :: ZFPLA_DEP(:), ZFPLO_DEP(:), ZFPMS_DEP(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: INUMD_DEP(:)
REAL(KIND=JPRB), ALLOCATABLE, TARGET :: ZFPNORX_DEP(:), ZFPNORY_DEP(:), ZFPGM_DEP(:)
REAL(KIND=JPRB), POINTER :: ZFPNORX(:), ZFPNORY(:), ZFPGM(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: INUMPROCFP_DEP(:), INUMPROCFP(:)
INTEGER(KIND=JPIM) :: IBOYD(6), IBWXO, IBWYO
INTEGER(KIND=JPIM) :: JLON, ILONF, ILATF, IND, IND1, JGL
INTEGER(KIND=JPIM) :: IPL, JJPG, IDISTRIB
INTEGER(KIND=JPIM) :: IEND, JBLOC, IOFF, JFP
INTEGER(KIND=JPIM) :: IFPROMA_DEP
INTEGER(KIND=JPIM) :: IFPDOM
LOGICAL, ALLOCATABLE :: LLMASKG(:)
LOGICAL :: LLMASK

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE


!-----------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SUFPGEOMETRY',0,ZHOOK_HANDLE)
ASSOCIATE(NFPBOYD=>YDNAMFPSCI%NFPBOYD, RFPBSCAL=>YDNAMFPSCI%RFPBSCAL, &
 & NFPRGPG_DEP=>YDFPGEOMETRY%YFPGEO_DEP%NFPRGPG, NFPRGPG=>YDFPGEOMETRY%YFPGEO%NFPRGPG, &
 & NGLOBALPROC=>YDGEOMETRY%YRMP%NGLOBALPROC, LFPOSHOR=>YDFPGEOMETRY%LFPOSHOR)

!*   Initialize mixed output geometries 
WRITE(NULOUT,'('' == Full-Pos : setup horizontal distribution == '')')

NFPRGPG_DEP=SUM(YDFPGEOMETRY%YFPUSERGEO(:)%NFPSIZEG_DEP)
NFPRGPG=SUM(YDFPGEOMETRY%YFPUSERGEO(:)%NFPSIZEG)

!*       1. GLOBAL COORDINATES, MAP FACTOR, RELATIVE COMPASS & DOMAIN INDEX
!           ---------------------------------------------------------------

ALLOCATE(ZFPLA_DEP(NFPRGPG_DEP))
ALLOCATE(ZFPLO_DEP(NFPRGPG_DEP))
ALLOCATE(ZFPGM_DEP(NFPRGPG_DEP))
ALLOCATE(ZFPNORX_DEP(NFPRGPG_DEP))
ALLOCATE(ZFPNORY_DEP(NFPRGPG_DEP))
ALLOCATE(INUMD_DEP(NFPRGPG_DEP))
ALLOCATE(ZFPMS_DEP(NFPRGPG_DEP))

IFPDOM=SIZE(YDFPGEOMETRY%YFPUSERGEO(:))

CALL SUFPG2(YDNAMFPINT,YDNAMFPSCI,IFPDOM,YDFPGEOMETRY%YFPUSERGEO,YDGEOMETRY,NFPRGPG_DEP,PCO_EZO,LFPOSHOR,ZFPLA_DEP,ZFPLO_DEP, &
 & ZFPGM_DEP,ZFPNORX_DEP,ZFPNORY_DEP,INUMD_DEP,ZFPMS_DEP)

!*       1. MIXED CONTROL PARAMETERS
!           ------------------------

IDISTRIB=YDFPGEOMETRY%YFPUSERGEO(1)%NFPDIST

!*       1.2 Control that the points are inside the model domain or setup a
!            larger halo (partly over the extension zone)

! because ZFPLA_DEP, ZFPLO_DEP are inout of suefpg3
IF (LELAM.AND.LFPOSHOR) THEN
  ALLOCATE(LLMASKG(NFPRGPG))
  CALL SUEFPG3(NFPBOYD,IFPDOM,YDFPGEOMETRY%YFPUSERGEO,YDGEOMETRY,NFPRGPG,NFPRGPG_DEP,LWIDER_DOM,ZFPLA_DEP,ZFPLO_DEP,LLMASKG)
  LLMASK=ALL(LLMASKG(:)) 
  IF (LLMASK) THEN 
    DEALLOCATE(LLMASKG)
  ENDIF
ELSE
  LLMASK=.TRUE.
ENDIF

ALLOCATE(INUMPROCFP(NFPRGPG))

IF (.NOT.LFPOSBUF(YDFPGEOMETRY)) THEN
  INUMPROCFP(:)=NGLOBALPROC(:)
ELSEIF (NPROC == 1) THEN
  INUMPROCFP(:)=1
ELSEIF(IDISTRIB > 0) THEN
  CALL SUPROCFP(IDISTRIB,IFPDOM,NFPRGPG,YDFPGEOMETRY%YFPUSERGEO,INUMPROCFP)
! else, copied from _dep (below)
ENDIF


! INTERPOLATION GRID :
! ==================

IF (LFPOSBUF(YDFPGEOMETRY)) THEN

  ALLOCATE(INUMPROCFP_DEP(NFPRGPG_DEP))

  IF (NPROC == 1) THEN
    INUMPROCFP_DEP(:)=1
  ELSE
    CALL SUPROCFP_DEP(YDGEOMETRY,NFPRGPG_DEP,ZFPLA_DEP,ZFPLO_DEP,INUMPROCFP_DEP)
  ENDIF

  IF (IDISTRIB == 0) THEN
    ! => _ARR == _DEP
    INUMPROCFP(:)=INUMPROCFP_DEP(:)
  ENDIF

  IF (IDISTRIB == 0) THEN
    IFPROMA_DEP=KFPROMA
  ELSE
    IFPROMA_DEP=KFPROMA_DEP
  ENDIF

  CALL SUMPFPOS('_DEP',NFPRGPG_DEP,INUMPROCFP_DEP,IFPROMA_DEP,YDFPGEOMETRY%YFPGEO_DEP%NFPRGPNUM,&
   & YDFPGEOMETRY%YFPGEO_DEP%NFPRGPL,YDFPGEOMETRY%YFPGEO_DEP%NFPRGPLX,YDFPGEOMETRY%YFPGEO_DEP%NFPRGPIND, &
   & YDFPGEOMETRY%YFPGEO_DEP%NFPROMA,YDFPGEOMETRY%YFPGEO_DEP%NFPBLOCS,YDFPGEOMETRY%YFPGEO_DEP%NFPEND)

  ! more statistics
  IF (LTRACEFP) THEN
    CALL SUMPFPOS_DEP(YDFPGEOMETRY%YFPGEO_DEP)
  ENDIF

  ALLOCATE(YDFPGEOMETRY%YFPGEO_DEP%RFPLA(YDFPGEOMETRY%YFPGEO_DEP%NFPRGPL))
  ALLOCATE(YDFPGEOMETRY%YFPGEO_DEP%RFPLO(YDFPGEOMETRY%YFPGEO_DEP%NFPRGPL))
  ALLOCATE(YDFPGEOMETRY%YFPGEO_DEP%RFPGMS(YDFPGEOMETRY%YFPGEO_DEP%NFPRGPL))
  ALLOCATE(YDFPGEOMETRY%YFPGEO_DEP%NFPNUMD(YDFPGEOMETRY%YFPGEO_DEP%NFPRGPL))
  IF (LALLOFP) THEN
    WRITE(NULOUT,9990) 'YDFPGEOMETRY%YFPGEO_DEP%RFPLA  ',SIZE(YDFPGEOMETRY%YFPGEO_DEP%RFPLA),SHAPE(YDFPGEOMETRY%YFPGEO_DEP%RFPLA)
    WRITE(NULOUT,9990) 'YDFPGEOMETRY%YFPGEO_DEP%RFPLO  ',SIZE(YDFPGEOMETRY%YFPGEO_DEP%RFPLO),SHAPE(YDFPGEOMETRY%YFPGEO_DEP%RFPLO)
    WRITE(NULOUT,9990) 'YDFPGEOMETRY%YFPGEO_DEP%RFPGMS ',SIZE(YDFPGEOMETRY%YFPGEO_DEP%RFPGMS),SHAPE(YDFPGEOMETRY%YFPGEO_DEP%RFPGMS)
    WRITE(NULOUT,9990) 'YDFPGEOMETRY%YFPGEO_DEP%NFPNUMD',SIZE(YDFPGEOMETRY%YFPGEO_DEP%NFPNUMD), &
     & SHAPE(YDFPGEOMETRY%YFPGEO_DEP%NFPNUMD)
  ENDIF
  IF (YDFPGEOMETRY%YFPGEO_DEP%NFPRGPL == NFPRGPG_DEP) THEN
    ! All points are treated by the same processor           
      YDFPGEOMETRY%YFPGEO_DEP%RFPLA(:)=ZFPLA_DEP(:)
      YDFPGEOMETRY%YFPGEO_DEP%RFPLO(:)=ZFPLO_DEP(:)
      YDFPGEOMETRY%YFPGEO_DEP%RFPGMS(:)=ZFPMS_DEP(:)
      YDFPGEOMETRY%YFPGEO_DEP%NFPNUMD(:)=INUMD_DEP(:)
  ELSEIF (YDFPGEOMETRY%YFPGEO_DEP%NFPRGPL > 0) THEN
    ! Actual distribution
    IPL=0
    DO JJPG=1,NFPRGPG_DEP
      IF (INUMPROCFP_DEP(JJPG) == MYPROC) THEN
        IPL=IPL+1
        YDFPGEOMETRY%YFPGEO_DEP%RFPLA(IPL)=ZFPLA_DEP(JJPG)
        YDFPGEOMETRY%YFPGEO_DEP%RFPLO(IPL)=ZFPLO_DEP(JJPG)
        YDFPGEOMETRY%YFPGEO_DEP%RFPGMS(IPL)=ZFPMS_DEP(JJPG)
        YDFPGEOMETRY%YFPGEO_DEP%NFPNUMD(IPL)=INUMD_DEP(JJPG)
      ENDIF
    ENDDO
  ENDIF

ENDIF

DEALLOCATE(ZFPMS_DEP)
DEALLOCATE(INUMD_DEP)
DEALLOCATE(ZFPLA_DEP)
DEALLOCATE(ZFPLO_DEP)


! TARGET GRID :
! ===========

CALL SUMPFPOS(' ',NFPRGPG,INUMPROCFP,KFPROMA,YDFPGEOMETRY%YFPGEO%NFPRGPNUM,YDFPGEOMETRY%YFPGEO%NFPRGPL, &
 & YDFPGEOMETRY%YFPGEO%NFPRGPLX,YDFPGEOMETRY%YFPGEO%NFPRGPIND, &
 & YDFPGEOMETRY%YFPGEO%NFPROMA,YDFPGEOMETRY%YFPGEO%NFPBLOCS,YDFPGEOMETRY%YFPGEO%NFPEND)

IF (NFPBOYD == 0) THEN
  ZFPNORX => ZFPNORX_DEP(:)
  ZFPNORY => ZFPNORY_DEP(:)
  ZFPGM   => ZFPGM_DEP(:)
ELSE
! Boyd biperiodicization of the map factor
  IBOYD(3)=YDFPGEOMETRY%YFPUSERGEO(1)%NFPBWX
  IBOYD(6)=YDFPGEOMETRY%YFPUSERGEO(1)%NFPBWY
  CALL FPBIPERE(YDFPGEOMETRY%YFPUSERGEO(1)%NFPLUX,YDFPGEOMETRY%YFPUSERGEO(1)%NFPGUX,YDFPGEOMETRY%YFPUSERGEO(1)%NLON, &
   & YDFPGEOMETRY%YFPUSERGEO(1)%NLAT,1,NFPRGPG_DEP,ZFPGM_DEP,0,LDZON=.TRUE.,LDBOYD=.TRUE.,KDBOYD=IBOYD,PLBOYD=RFPBSCAL)
  ALLOCATE(ZFPNORX(NFPRGPG))
  ALLOCATE(ZFPNORY(NFPRGPG))
  ALLOCATE(ZFPGM(NFPRGPG))
! Fill C+I+E from C+I+W
  IBWXO=YDFPGEOMETRY%YFPUSERGEO(1)%NFPBWX+YDFPGEOMETRY%YFPUSERGEO(1)%NLON-YDFPGEOMETRY%YFPUSERGEO(1)%NFPLUX
  IBWYO=YDFPGEOMETRY%YFPUSERGEO(1)%NFPBWY+YDFPGEOMETRY%YFPUSERGEO(1)%NLAT-YDFPGEOMETRY%YFPUSERGEO(1)%NFPGUX
  DO JLON=1+IBWXO,YDFPGEOMETRY%YFPUSERGEO(1)%NLON+IBWXO
    ILONF=MODULO(JLON-1-YDFPGEOMETRY%YFPUSERGEO(1)%NFPBWX-(YDFPGEOMETRY%YFPUSERGEO(1)%NLON-YDFPGEOMETRY%YFPUSERGEO(1)%NFPLUX), &
         & YDFPGEOMETRY%YFPUSERGEO(1)%NLON)+1
    DO JGL=1+IBWYO,YDFPGEOMETRY%YFPUSERGEO(1)%NLAT+IBWYO
      ILATF=MODULO(JGL-1-YDFPGEOMETRY%YFPUSERGEO(1)%NFPBWY-(YDFPGEOMETRY%YFPUSERGEO(1)%NLAT-YDFPGEOMETRY%YFPUSERGEO(1)%NFPGUX), &
           & YDFPGEOMETRY%YFPUSERGEO(1)%NLAT)+1
      IND1=(YDFPGEOMETRY%YFPUSERGEO(1)%NFPLUX+2*YDFPGEOMETRY%YFPUSERGEO(1)%NFPBWX+ &
           & 2*(YDFPGEOMETRY%YFPUSERGEO(1)%NLON-YDFPGEOMETRY%YFPUSERGEO(1)%NFPLUX))*(JGL-1)+JLON
      IND=YDFPGEOMETRY%YFPUSERGEO(1)%NLON*(ILATF-1)+ILONF
      ZFPNORX(IND)=ZFPNORX_DEP(IND1)
      ZFPNORY(IND)=ZFPNORY_DEP(IND1)
      ZFPGM(IND)=ZFPGM_DEP(IND1)
    ENDDO
  ENDDO
ENDIF

! Spectral outputs need smoothed map factor if plane geometry
IF (ANY(YDFPGEOMETRY%YFPUSERGEO(:)%LFPMAPF)) THEN
  WRITE(NULOUT,'('' == Full-Pos : setup map factor for LAM == '')')
  CALL SUFPMAPF(IFPDOM,YDFPGEOMETRY%YFPUSERGEO,NFPRGPG,ZFPGM)
ENDIF

ALLOCATE(YDFPGEOMETRY%YFPGEO%RFPGM(YDFPGEOMETRY%YFPGEO%NFPROMA,YDFPGEOMETRY%YFPGEO%NFPBLOCS))
IF (LALLOFP) THEN
  WRITE(NULOUT,9990) 'RFPGM     ',SIZE(YDFPGEOMETRY%YFPGEO%RFPGM  ),SHAPE(YDFPGEOMETRY%YFPGEO%RFPGM  )
ENDIF
IF (LFPOSHOR) THEN
  ALLOCATE(YDFPGEOMETRY%YFPGEO%RFPNORX(YDFPGEOMETRY%YFPGEO%NFPROMA,YDFPGEOMETRY%YFPGEO%NFPBLOCS))
  ALLOCATE(YDFPGEOMETRY%YFPGEO%RFPNORY(YDFPGEOMETRY%YFPGEO%NFPROMA,YDFPGEOMETRY%YFPGEO%NFPBLOCS))
  IF (LALLOFP) THEN
    WRITE(NULOUT,9990) 'RFPNORX   ',SIZE(YDFPGEOMETRY%YFPGEO%RFPNORX),SHAPE(YDFPGEOMETRY%YFPGEO%RFPNORX)
    WRITE(NULOUT,9990) 'RFPNORY   ',SIZE(YDFPGEOMETRY%YFPGEO%RFPNORY),SHAPE(YDFPGEOMETRY%YFPGEO%RFPNORY)
  ENDIF
ENDIF
! rfpmask is always allocated because it can be an output field for fullpos
! (as compass or output map factor could be, by the way)
ALLOCATE(YDFPGEOMETRY%YFPGEO%RFPMASK(YDFPGEOMETRY%YFPGEO%NFPROMA,YDFPGEOMETRY%YFPGEO%NFPBLOCS))
IF (LALLOFP) THEN
  WRITE(NULOUT,9990) 'RFPMASK   ',SIZE(YDFPGEOMETRY%YFPGEO%RFPMASK),SHAPE(YDFPGEOMETRY%YFPGEO%RFPMASK)
ENDIF

IF (LLMASK) THEN
  YDFPGEOMETRY%YFPGEO%RFPMASK(:,:)=1._JPRB
ENDIF
IF (YDFPGEOMETRY%YFPGEO%NFPRGPL == NFPRGPG) THEN
  ! All points are treated by the same processor           
  DO JBLOC=1,YDFPGEOMETRY%YFPGEO%NFPBLOCS
    IOFF=(JBLOC-1)*YDFPGEOMETRY%YFPGEO%NFPROMA
    IEND=YDFPGEOMETRY%YFPGEO%NFPEND(JBLOC)
    YDFPGEOMETRY%YFPGEO%RFPGM(1:IEND,JBLOC)=ZFPGM(IOFF+1:IOFF+IEND)
    IF (LFPOSHOR) THEN
      YDFPGEOMETRY%YFPGEO%RFPNORX(1:IEND,JBLOC)=ZFPNORX(IOFF+1:IOFF+IEND)
      YDFPGEOMETRY%YFPGEO%RFPNORY(1:IEND,JBLOC)=ZFPNORY(IOFF+1:IOFF+IEND)
    ENDIF
    IF (.NOT.LLMASK) THEN
      IF (ALL(LLMASKG(1+IOFF:IEND+IOFF))) THEN
        YDFPGEOMETRY%YFPGEO%RFPMASK(1:IEND,JBLOC)=1._JPRB
      ELSEIF (.NOT.ANY(LLMASKG(1+IOFF:IEND+IOFF))) THEN
        YDFPGEOMETRY%YFPGEO%RFPMASK(1:IEND,JBLOC)=0._JPRB
      ELSE
        DO JFP=1,IEND
          IF (LLMASKG(JFP+IOFF)) THEN
            YDFPGEOMETRY%YFPGEO%RFPMASK(JFP,JBLOC)=1._JPRB
          ELSE
            YDFPGEOMETRY%YFPGEO%RFPMASK(JFP,JBLOC)=0._JPRB
          ENDIF
        ENDDO
      ENDIF
    ENDIF
  ENDDO
ELSEIF (YDFPGEOMETRY%YFPGEO%NFPRGPL > 0) THEN
  ! Actual distribution
  IPL=0
  DO JJPG=1,NFPRGPG
    IF (INUMPROCFP(JJPG) == MYPROC) THEN
      IPL=IPL+1
      JBLOC=(IPL-1)/YDFPGEOMETRY%YFPGEO%NFPROMA+1
      JFP=IPL-(JBLOC-1)*YDFPGEOMETRY%YFPGEO%NFPROMA
      YDFPGEOMETRY%YFPGEO%RFPGM(JFP,JBLOC)=ZFPGM(JJPG)
      IF (LFPOSHOR) THEN
        YDFPGEOMETRY%YFPGEO%RFPNORX(JFP,JBLOC)=ZFPNORX(JJPG)
        YDFPGEOMETRY%YFPGEO%RFPNORY(JFP,JBLOC)=ZFPNORY(JJPG)
      ENDIF
      IF (.NOT.LLMASK) THEN
        IF (LLMASKG(JJPG)) THEN
          YDFPGEOMETRY%YFPGEO%RFPMASK(JFP,JBLOC)=1._JPRB
        ELSE
          YDFPGEOMETRY%YFPGEO%RFPMASK(JFP,JBLOC)=0._JPRB
        ENDIF
      ENDIF
    ENDIF
  ENDDO
ENDIF
DO JBLOC=1,YDFPGEOMETRY%YFPGEO%NFPBLOCS
  IEND=YDFPGEOMETRY%YFPGEO%NFPEND(JBLOC)
  IF (IEND < YDFPGEOMETRY%YFPGEO%NFPROMA) THEN
    YDFPGEOMETRY%YFPGEO%RFPGM  (IEND+1:YDFPGEOMETRY%YFPGEO%NFPROMA,JBLOC)=HUGE(1._JPRB)
    IF (LFPOSHOR) THEN
      YDFPGEOMETRY%YFPGEO%RFPNORX(IEND+1:YDFPGEOMETRY%YFPGEO%NFPROMA,JBLOC)=HUGE(1._JPRB)
      YDFPGEOMETRY%YFPGEO%RFPNORY(IEND+1:YDFPGEOMETRY%YFPGEO%NFPROMA,JBLOC)=HUGE(1._JPRB)
    ENDIF
    YDFPGEOMETRY%YFPGEO%RFPMASK(IEND+1:YDFPGEOMETRY%YFPGEO%NFPROMA,JBLOC)=HUGE(1._JPRB)
  ENDIF
ENDDO

IF (NFPBOYD == 0) THEN
  NULLIFY(ZFPNORX)
  NULLIFY(ZFPNORY)
  NULLIFY(ZFPGM)
ELSE
  DEALLOCATE(ZFPNORX)
  DEALLOCATE(ZFPNORY)
  DEALLOCATE(ZFPGM)
ENDIF
IF (.NOT.LLMASK) THEN 
  DEALLOCATE(LLMASKG)
ENDIF

DEALLOCATE(ZFPGM_DEP)
DEALLOCATE(ZFPNORX_DEP)
DEALLOCATE(ZFPNORY_DEP)

! TRANSPOSITION FROM INTERPOLATION GRID TO TARGET GRID :
! ====================================================

IF (IDISTRIB > 0) THEN
  CALL SUFPDISTRIB(YDNAMFPSCI,YDFPGEOMETRY%YFPGEO_DEP,YDFPGEOMETRY%YFPGIND,YDFPGEOMETRY%YFPGEO,YDFPGEOMETRY%YFPUSERGEO, &
   & INUMPROCFP_DEP,INUMPROCFP)
ENDIF

!     ------------------------------------------------------------------

9990 FORMAT(1X,'ARRAY ',A20,' ALLOCATED ',8I8)

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPGEOMETRY',1,ZHOOK_HANDLE)

END SUBROUTINE SUFPGEOMETRY
