! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPWIDE(YDFPGEOMETRY,YDFPSTRUCT,YDGEOMETRY,KFPWIDE,YDFPGEO_DEP)

!**** *SUFPWIDE*  Initialize control of scan2 
!                 related to horizontal post-processing

!     Purpose.
!     -------
!           Initialize. part of the common that controls the
!           multi - tasking and buffer usage in the grid - point
!           calculations under SCAN2MSM/DM.

!     Interface.
!     ---------
!        *CALL*  *SUFPWIDE*

!        Explicit arguments : None
!        ------------------
!        Implicit arguments :
!        ------------------
!        KFPWIDE : user-provided width of the halo
!        see above "USE MODULE"

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!        Several multitasking routines (LOCK... and EV... routines).
!        SUSIZBUF,SLCSET

!     Author.
!     ------
!      Ryad EL KHATIB      * METEO-FRANCE *
!      Original  : 99-08-06 from SUSC2

!     Modifications.
!     -------------
!      G.Mozdzynski: 01-12-18 support radiation grid
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      R. El Khatib    20-May-2005 NFPWIDE moved to YOMWFPDS
!      G.Mozdzynski (Feb 2011): OOPS cleaning, use of derived type TCSGLEG
!      T. Wilhelmsson and K. Yessad (Oct 2013) Geometry and setup refactoring.
!      K. Yessad (July 2014): Move some variables.
!      R. El Khatib 27-Jul-2016 computation of NSLWIDE back here + interpolations over C+I+E
!     ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE PARFPOS  , ONLY : JPROW
USE YOMLUN   , ONLY : NULOUT
USE YOMMP0   , ONLY : MY_REGION_NS, MY_REGION_EW, MYPROC   ,NPROC
USE YOMCT0   , ONLY : LELAM
USE YOMFPC   , ONLY : LTRACEFP
USE EINT_MOD, ONLY : SL_STRUCT
USE YOMFPGEOMETRY, ONLY : TFPGEOMETRY
USE YOMFPGEO, ONLY : TFPGEO
USE MPL_MODULE, ONLY : MPL_BROADCAST

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE (TFPGEOMETRY),  INTENT(IN) :: YDFPGEOMETRY
TYPE(SL_STRUCT),   INTENT(OUT) :: YDFPSTRUCT
TYPE(GEOMETRY)    ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KFPWIDE
TYPE (TFPGEO)     ,INTENT(IN) :: YDFPGEO_DEP

INTEGER(KIND=JPIM) :: IDGSAH, IDGENH, IFPWIDER_DOM, IFPWIDE, JROC
INTEGER(KIND=JPIM) :: IWIDEL(NPROC)
REAL(KIND=JPRB) :: ZLOMAX, ZLOMIN, ZLAMAX, ZLAMIN

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "slcset.intfb.h"

#include "abor1.intfb.h"
!    -------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SUFPWIDE',0,ZHOOK_HANDLE)
ASSOCIATE(LFPOSHOR=>YDFPGEOMETRY%LFPOSHOR, &
 & YDDIM=>YDGEOMETRY%YRDIM, YDEGEO=>YDGEOMETRY%YREGEO, &
 & YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP, YDCSGLEG=>YDGEOMETRY%YRCSGLEG)
ASSOCIATE(NDGENG=>YDDIM%NDGENG, &
 & NDGENL=>YDDIM%NDGENL, NDGLG=>YDDIM%NDGLG, &
 & NDGSAG=>YDDIM%NDGSAG, NDGSAL=>YDDIM%NDGSAL, &
 & NDGSUR=>YDDIM%NDGSUR, NDGUNG=>YDDIM%NDGUNG, NDGUXG=>YDDIM%NDGUXG, &
 & NDGUXL=>YDDIM%NDGUXL, NDLON=>YDDIM%NDLON, NDLSUR=>YDDIM%NDLSUR, &
 & NDLUNG=>YDDIM%NDLUNG, NDLUXG=>YDDIM%NDLUXG, NDSUR1=>YDDIM%NDSUR1, &
 & NGPBLKS=>YDDIM%NGPBLKS, NPROMA=>YDDIM%NPROMA, &
 & NGPTOT=>YDGEM%NGPTOT, NLOENG=>YDGEM%NLOENG, &
 & EDELY=>YDEGEO%EDELY, EDELX=>YDEGEO%EDELX, &
 & RFPLA_DEP=>YDFPGEO_DEP%RFPLA, RFPLO_DEP=>YDFPGEO_DEP%RFPLO, NFPRGPL_DEP=>YDFPGEO_DEP%NFPRGPL, &
 & MYFRSTACTLAT=>YDMP%MYFRSTACTLAT, MYLSTACTLAT=>YDMP%MYLSTACTLAT, &
 & NFRSTLAT=>YDMP%NFRSTLAT, NFRSTLOFF=>YDMP%NFRSTLOFF, NLSTLAT=>YDMP%NLSTLAT, &
 & NONL=>YDMP%NONL, NPTRFLOFF=>YDMP%NPTRFLOFF, NPTRFRSTLAT=>YDMP%NPTRFRSTLAT, &
 & NSTA=>YDMP%NSTA)
!     ------------------------------------------------------------------

!     2. COMPUTE A TAILORED HALO WIDTH
!        -----------------------------
IF (LELAM.AND.LFPOSHOR) THEN
  ! Halos can provide a bit more rows from extension zone for the interpolations :
  IF (NFPRGPL_DEP > 0) THEN
    ZLOMAX=MAXVAL(RFPLO_DEP(:))/EDELX - REAL(NDLUXG-JPROW,KIND=JPRB)
    ZLOMIN=REAL(JPROW,KIND=JPRB) - MINVAL(RFPLO_DEP(:))/EDELX
    ZLAMAX=MAXVAL(RFPLA_DEP(:))/EDELY - REAL(NDGUXG-JPROW,KIND=JPRB)
    ZLAMIN=REAL(JPROW,KIND=JPRB) - MINVAL(RFPLA_DEP(:))/EDELY
    IFPWIDER_DOM=MAX(0,INT(MAX(ZLOMAX,ZLOMIN,ZLAMAX,ZLAMIN))+1)
  ELSE
    IFPWIDER_DOM=0 
  ENDIF
  ! Find maximum value among taks :
  IF (NPROC > 1) THEN
    IWIDEL(MYPROC)=IFPWIDER_DOM
    DO JROC=1,NPROC
      CALL MPL_BROADCAST(IWIDEL(JROC:JROC),KROOT=JROC,KTAG=JROC,CDSTRING='SUFPWIDE')
    ENDDO
    IFPWIDER_DOM=MAXVAL(IWIDEL(:))
  ENDIF
ELSE
  IFPWIDER_DOM=0 
ENDIF

IFPWIDE=MAX(IFPWIDER_DOM,KFPWIDE)

!*     3. INITIALIZE CONTROL ARRAYS FOR HORIZONTAL INTERPOLATIONS
!         -------------------------------------------------------

YDFPSTRUCT%CVER='FP'
YDFPSTRUCT%NSLWIDE=MAX(IFPWIDE,JPROW+1)

IF (LELAM) THEN
  IDGSAH = NDGSAL-YDFPSTRUCT%NSLWIDE
  IDGENH = NDGENL+YDFPSTRUCT%NSLWIDE
ELSE
  IDGSAH = MAX(NDGSAG,NDGSAL+NFRSTLOFF-YDFPSTRUCT%NSLWIDE)-NFRSTLOFF
  IDGENH = MIN(NDGENG,NDGENL+NFRSTLOFF+YDFPSTRUCT%NSLWIDE)-NFRSTLOFF
ENDIF

!*        3.1   ALLOCATIONS AND COMPUTATIONS

CALL SLCSET(YDGEOMETRY,YDFPSTRUCT,MY_REGION_NS,MY_REGION_EW,&
 & NDGLG,NDLON,NDGSAG,NDGENG,NDGSAL,NDGENL,IDGSAH,IDGENH,&
 & NDGUXL,NDLUNG,NDLUXG,NDGUNG,NDGUXG,&
 & NDSUR1,NDLSUR,NDGSUR,NGPTOT,&
 & NPTRFLOFF,NFRSTLOFF,MYFRSTACTLAT,MYLSTACTLAT,&
 & NSTA,NONL,NLOENG,NPTRFRSTLAT,NFRSTLAT,NLSTLAT,&
 & YDCSGLEG%RMU,YDCSGLEG%RSQM2)

!*        3.2   PRINTS ON OUTPUT

IF (LTRACEFP) THEN
  WRITE(NULOUT,'('' SUFPWIDE PRINTS OUT'')')
  WRITE(NULOUT,'('' NFPWIDE ='',I4, '' NFPDGSAH = '',I4,'' NFPDGENH = '',I4)') &
   & YDFPSTRUCT%NSLWIDE, YDFPSTRUCT%NDGSAH, YDFPSTRUCT%NDGENH
ENDIF

IF (YDFPSTRUCT%NSLWIDE /= 0 .AND. YDFPSTRUCT%NSLWIDE  < JPROW+1) THEN
  CALL ABOR1('SUFPWIDE : INTERNAL ERROR ON YDFPSTRUCT%NSLWIDE')
ENDIF

IF (YDFPSTRUCT%NSLWIDE == 0 .AND. YDFPSTRUCT%NASLB1 /= NPROMA*NGPBLKS) THEN
  YDFPSTRUCT%NASLB1=NPROMA*NGPBLKS
  WRITE(NULOUT,'(''*** YDFPSTRUCT%NASLB1 RESET TO NPROMA*NGPBLKS='',I7)') YDFPSTRUCT%NASLB1
ENDIF

! ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPWIDE',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPWIDE
