! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPPHY(YDAFN,LDPHYS,YDFPFIELDS,KFPDOM,CDFPDOM,LDNOFIL,CDYFILE,YGFL,YDEAERATM,LDLAG,LDOCEDELAY,LDOCE,YDRQPHY)

!**** *SUFPPHY*  - INITIALIZE REQUESTS ON PHYSICS

!     PURPOSE.
!     --------
!        INITIALIZE PHYSIC REQUESTS OF POST-PROCESSING AT A GIVEN TIME STEP.

!**   INTERFACE.
!     ----------
!       *CALL* *SUFPPHY*

!        EXPLICIT ARGUMENTS
!        --------------------
!           KFPDOM : number of subdomains
!           CDFPDOM: names of the subdomains
!           LDNOFIL : .TRUE. if no selection namelists
!           CDYFILE : filename containing the selection namelists
!           LDOCEDELAY   : Post-processing physics fields at the end of the step
!           LDOCE   : Post-processing ocean fields if called in ocean mode


!        IMPLICIT ARGUMENTS
!        ------------------
!        NONE.

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 94-04-08

!     MODIFICATIONS.
!     --------------
!      R. El Khatib : 02-21-20 Fullpos B-level distribution + remove IO scheme
!      R. El Khatib : 03-04-17 Fullpos improvments
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      K. Yessad (July 2014): Move some variables.
!      R. El Khatib 27-Nov-2014 Discriminate PHY/CFU/XFU by start/end index
!     ------------------------------------------------------------------

USE PARKIND1     , ONLY : JPIM     ,JPRB
USE YOMHOOK      , ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMLUN       , ONLY : NULNAM   ,NULOUT
USE PARFPOS      , ONLY : JPOSDOM  ,JPOSLEN  ,JPOSCFU  ,JPOSXFU  ,JPOSSGP  
USE YOMCT0       , ONLY : LARPEGEF
USE YOMFPC       , ONLY : LTRACEFP, LALLOFP
USE TYPE_FPFIELDS, ONLY : TFPFIELDS
USE YOMAFN       , ONLY : TAFN
USE YOMMP0       , ONLY : NPRINTLEV
USE YOMFP4L, ONLY : TRQFP
USE TYPE_FPRQPHYS, ONLY : ALLOCATE_FPRQPHY
USE YOM_YGFL     , ONLY : TYPE_GFLD
USE YOEAERATM    , ONLY : TEAERATM
USE IOGRIDE_MOD  , ONLY : LAGGED_PP_PAR, OCEAN_PP_PAR

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE (TAFN),       INTENT(IN) :: YDAFN
LOGICAL,           INTENT(IN) :: LDPHYS
TYPE (TFPFIELDS),  INTENT(IN) :: YDFPFIELDS
INTEGER(KIND=JPIM),INTENT(IN)  :: KFPDOM
CHARACTER(LEN=*),  INTENT(IN)  :: CDFPDOM(KFPDOM)
LOGICAL,           INTENT(IN)  :: LDNOFIL 
CHARACTER(LEN=*),  INTENT(IN)  :: CDYFILE 
TYPE(TYPE_GFLD),   INTENT(IN)  :: YGFL
TYPE(TEAERATM),    INTENT(IN)  :: YDEAERATM
LOGICAL,           INTENT(IN)  :: LDLAG
LOGICAL,           INTENT(IN)  :: LDOCEDELAY
LOGICAL,           INTENT(IN)  :: LDOCE
TYPE(TRQFP),       INTENT(OUT) :: YDRQPHY

!     ------------------------------------------------------------------

INTEGER(KIND=JPIM), PARAMETER :: JPSIZE=JPOSDOM*(JPOSLEN+1)-1

CHARACTER(LEN=1)      :: CLBLANK=' '
CHARACTER(LEN=16)     :: CLPHY(JPOSSGP),  CLCFU(JPOSCFU),  CLXFU(JPOSXFU)
CHARACTER(LEN=JPSIZE) :: CLDPHY(JPOSSGP), CLDCFU(JPOSCFU), CLDXFU(JPOSXFU)

!     IFPOSPHY: number of fields
!     ICPHYFP : Fields codes
!     IAPHYFP : Number of subdomains for each field
!     IIPHYFP : Subdomains pointers for each field

INTEGER(KIND=JPIM),ALLOCATABLE:: ICPHYFP(:), IAPHYFP(:), IIPHYFP(:,:) 

INTEGER(KIND=JPIM) :: IFPOSPHY, IFPDPHY

INTEGER(KIND=JPIM) :: I, ICFU, IERR, IPHY, IXD, IXFU, J, JD, JF, IN
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "abor1.intfb.h"
#include "posnam.intfb.h"
#include "sufpdom.intfb.h"

#include "namfpphy.nam.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUFPPHY',0,ZHOOK_HANDLE)
ASSOCIATE(GFP_PHYDS=>YDAFN%GFP_PHYDS, GFP=>YDAFN%GFP, MSTARTGFP_PHY=>YDAFN%MSTARTGFP_PHY, &
 & MSTARTGFP_CFU=>YDAFN%MSTARTGFP_CFU, MSTARTGFP_XFU=>YDAFN%MSTARTGFP_XFU, &
 & MENDGFP_PHY=>YDAFN%MENDGFP_PHY, MENDGFP_CFU=>YDAFN%MENDGFP_CFU, MENDGFP_XFU=>YDAFN%MENDGFP_XFU, &
 & CFPPHY=>YDFPFIELDS%CFPPHY, CFPCFU=>YDFPFIELDS%CFPCFU, CFPXFU=>YDFPFIELDS%CFPXFU, &
 & NFPPHY=>YDFPFIELDS%NFPPHY, NFPCFU=>YDFPFIELDS%NFPCFU, NFPXFU=>YDFPFIELDS%NFPXFU, &
 & MFPPHY=>YDFPFIELDS%MFPPHY)
!     ------------------------------------------------------------------

IFPDPHY=NFPPHY+NFPCFU+NFPXFU

ALLOCATE(ICPHYFP(IFPDPHY))
ALLOCATE(IAPHYFP(IFPDPHY))
ALLOCATE(IIPHYFP(KFPDOM,IFPDPHY))

IXD=JPOSDOM

IERR=0
I=0

SELECT CASE (LDNOFIL)

CASE (.TRUE.)

!   Physical fields :
  IF (LARPEGEF) THEN
    DO JF=1,NFPPHY
      I=I+1
      DO J=MSTARTGFP_PHY,MENDGFP_PHY
        IF (CFPPHY(JF) == GFP_PHYDS(J)%CLNAME) EXIT
      ENDDO
      IF (J > MENDGFP_PHY) THEN
        WRITE(NULOUT,*) ' UNKNOWN REQUESTED FIELD ',CFPPHY(JF)
        IERR=IERR+1
      ELSE
        ICPHYFP(I)=J
      ENDIF
    ENDDO
  ELSE
    ! ECMWF specific
    DO JF=1,NFPPHY
      IF (LAGGED_PP_PAR(YGFL,YDEAERATM,MFPPHY(JF)) .NEQV. LDLAG) THEN
        IF (LTRACEFP .AND. NPRINTLEV >= 2) THEN
          IF (LDLAG) THEN
            WRITE(NULOUT, '(I8,'' RESERVED FOR NON-LAGGED PP CALL'')') MFPPHY(JF)
          ELSE
            WRITE(NULOUT, '(I8,'' RESERVED FOR LAGGED PP CALL'')') MFPPHY(JF)
          ENDIF
        ENDIF
        CYCLE
      ENDIF
      IF (LDOCEDELAY) THEN
        IF (OCEAN_PP_PAR(MFPPHY(JF)) .NEQV. LDOCE) THEN
          IF (LTRACEFP .AND. NPRINTLEV >= 2) THEN
            IF (LDOCE) THEN
              WRITE(NULOUT, '(I8,'' RESERVED FOR NON-LAGGED OCEAN PP CALL'')') MFPPHY(JF)
            ELSE
              WRITE(NULOUT, '(I8,'' RESERVED FOR LAGGED OCEAN PP CALL'')') MFPPHY(JF)
            ENDIF
          ENDIF
          CYCLE
        ENDIF
      ENDIF
      I=I+1
      DO J=MSTARTGFP_PHY,MENDGFP_PHY
        IF (MFPPHY(JF) == GFP_PHYDS(J)%IGRIB) EXIT
      ENDDO
      IF (J > MENDGFP_PHY) THEN
        WRITE(NULOUT,*) ' UNKNOWN REQUESTED FIELD ',MFPPHY(JF)
        IERR=IERR+1
      ELSE
        ICPHYFP(I)=J
      ENDIF
    ENDDO
  ENDIF
!   Cumulated fluxes :
  DO JF=1,NFPCFU
    I=I+1
    DO J=MSTARTGFP_CFU,MENDGFP_CFU
      IF (CFPCFU(JF) == GFP_PHYDS(J)%CLNAME) EXIT
    ENDDO
    IF (J > MENDGFP_CFU) THEN
      WRITE(NULOUT,*) ' UNKNOWN REQUESTED FIELD ',CFPCFU(JF)
      IERR=IERR+1
    ELSE
      ICPHYFP(I)=J
    ENDIF
  ENDDO
!   Instantaneous fluxes/diagnostics :
  DO JF=1,NFPXFU
    I=I+1
    DO J=MSTARTGFP_XFU,MENDGFP_XFU
      IF (CFPXFU(JF) == GFP_PHYDS(J)%CLNAME) EXIT
    ENDDO
    IF (J > MENDGFP_XFU) THEN
      WRITE(NULOUT,*) ' UNKNOWN REQUESTED FIELD ',CFPXFU(JF)
      IERR=IERR+1
    ELSE
      ICPHYFP(I)=J
    ENDIF
  ENDDO
!   Select all fields
  IFPOSPHY=I
!   Select all domains for all fields :
  IAPHYFP(1:IFPOSPHY)=KFPDOM
  DO JD=1,KFPDOM
    IIPHYFP(JD,1:IFPOSPHY)=JD
  ENDDO

CASE (.FALSE.)

!   Read selection namelists

  CLPHY (:)=CLBLANK
  CLDPHY(:)=CLBLANK
  CLCFU (:)=CLBLANK
  CLDCFU(:)=CLBLANK
  CLXFU (:)=CLBLANK
  CLDXFU(:)=CLBLANK

  CLOSE(NULNAM)
  OPEN(NULNAM,FILE=CDYFILE,ACTION='READ')
  CALL POSNAM(NULNAM,'NAMFPPHY')
  READ(NULNAM,NAMFPPHY)

  IPHY=COUNT(CLPHY /= CLBLANK)
  ICFU=COUNT(CLCFU /= CLBLANK)
  IXFU=COUNT(CLXFU /= CLBLANK)
  IF (.NOT.LDPHYS .AND. IPHY+ICFU+IXFU > 0) THEN
    IPHY=0
    ICFU=0
    IXFU=0
    WRITE(NULOUT,*) 'WARNING : PHYSICAL FIELDS HAVE BEEN IGNORED IN THIS ADIABATIC MODEL'
  ENDIF

!   Count selected fields :
  IF (IPHY > NFPPHY) THEN
    WRITE(NULOUT,*) 'TOO MUCH PHYSICAL FIELDS IN SELECTION NAMELIST'
    CALL ABOR1('SUFPPHY: ABOR1 CALLED')
  ELSEIF (ICFU > NFPCFU) THEN
    WRITE(NULOUT,*) 'TOO MUCH CUMULATED FLUXES IN SELECTION NAMELIST'
    CALL ABOR1('SUFPPHY: ABOR1 CALLED')
  ELSEIF (IXFU > NFPXFU) THEN
    WRITE(NULOUT,*) 'TOO MUCH INSTANTANEOUS FLUXES IN SELECTION NAMELIST'
    CALL ABOR1('SUFPPHY: ABOR1 CALLED')
  ELSE
    IFPOSPHY=IPHY+ICFU+IXFU
  ENDIF
!   Physical fields :
  IN=0
  DO JF=1,IPHY
    IN=IN+1
    DO WHILE (CLPHY(IN) == CLBLANK)
      IN=IN+1
    ENDDO
    I=I+1
    DO J=MSTARTGFP_PHY,MENDGFP_PHY
      IF (CLPHY(IN) == GFP_PHYDS(J)%CLNAME) EXIT
    ENDDO
    IF (J > MENDGFP_PHY) THEN
      WRITE(NULOUT,*) ' UNKNOWN SELECTED FIELD ',CLPHY(IN)
      IERR=IERR+1
    ELSEIF (ANY(CFPPHY(1:NFPPHY)==CLPHY(IN))) THEN
      ICPHYFP(I)=J
      CALL SUFPDOM(CDFPDOM,IXD,KFPDOM,CLDPHY(IN),1,1,IAPHYFP(I),IIPHYFP(1,I))
    ELSE
      WRITE(NULOUT,*) ' MISSING FIELD IN MAIN NAMELIST ', CLPHY(IN)
    ENDIF
  ENDDO
!   Cumulated fluxes :
  IN=0
  DO JF=1,ICFU
    IN=IN+1
    DO WHILE (CLCFU(IN) == CLBLANK)
      IN=IN+1
    ENDDO
    I=I+1
    DO J=MSTARTGFP_CFU,MENDGFP_CFU
      IF (CLCFU(IN) == GFP_PHYDS(J)%CLNAME) EXIT
    ENDDO
    IF (J > MENDGFP_CFU) THEN
      WRITE(NULOUT,*) ' UNKNOWN SELECTED FIELD ',CLCFU(IN)
      IERR=IERR+1
    ELSEIF (ANY(CFPCFU(1:NFPCFU)==CLCFU(IN))) THEN
      ICPHYFP(I)=J
      CALL SUFPDOM(CDFPDOM,IXD,KFPDOM,CLDCFU(IN),1,1,IAPHYFP(I),IIPHYFP(1,I))
    ELSE
      WRITE(NULOUT,*) ' MISSING FIELD IN MAIN NAMELIST ', CLCFU(IN)
    ENDIF
  ENDDO
!   Instantaneous fluxes/diagnostics :
  IN=0
  DO JF=1,IXFU
    IN=IN+1
    DO WHILE (CLXFU(IN) == CLBLANK)
      IN=IN+1
    ENDDO
    I=I+1
    DO J=MSTARTGFP_XFU,MENDGFP_XFU
      IF (CLXFU(IN) == GFP_PHYDS(J)%CLNAME) EXIT
    ENDDO
    IF (J > MENDGFP_XFU) THEN
      WRITE(NULOUT,*) ' UNKNOWN SELECTED FIELD ',CLXFU(IN)
      IERR=IERR+1
    ELSEIF (ANY(CFPXFU(1:NFPXFU)==CLXFU(IN))) THEN
      ICPHYFP(I)=J
      CALL SUFPDOM(CDFPDOM,IXD,KFPDOM,CLDXFU(IN),1,1,IAPHYFP(I),IIPHYFP(1,I))
    ELSE
      WRITE(NULOUT,*) ' MISSING FIELD IN MAIN NAMELIST ', CLXFU(IN)
    ENDIF
  ENDDO

END SELECT

IF (IERR > 0) CALL ABOR1('SUFPPHY: ABOR1 CALLED')

IF (IFPOSPHY > 0) THEN
  CALL ALLOCATE_FPRQPHY(GFP_PHYDS,YDRQPHY,KFPDOM,IFPOSPHY,ICPHYFP,NULOUT,LALLOFP,KFPDOM=IAPHYFP,KDMPTR=IIPHYFP)
  IF (LTRACEFP .AND. NPRINTLEV >= 2) THEN
    WRITE(NULOUT,*) ' THE FOLLOWING PHYSICAL FIELDS WILL BE POST_PROCESSED AT THE CURRENT TIME STEP :'  
    DO JF=1,IFPOSPHY
      WRITE(NULOUT,FMT='(A16,''/'',15(1X,A7))') GFP_PHYDS(ICPHYFP(JF))%CLNAME,&
       & (CDFPDOM(IIPHYFP(JD,JF)), JD=1,IAPHYFP(JF))  
    ENDDO
  ENDIF
ENDIF

!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPPHY',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPPHY
