! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPMODELGEO(LDLAM,YDGEOMETRY,CDFPDOM,YDFPUSERGEO,YDHOSTGEOM,KFPCONF,KFPBOYD)

!**** *SUFPMODELGEO*  - INITIALIZE THE GEOMETRY OF A POST-PROCESSED GRID FOR FULLPOS FROM A MODEL GEOMETRY

!     PURPOSE.
!     --------
!        ALLOCATE AND FILL THE STRUCTURE DEFINING THE GEOMETRY OF A POST-PROCESSED GRID FROM A MODEL GEOMETRY
!        THEN CONTROL ITS CONSISTENCY

!        Notice :
!        - input angles of model geometry are in radians (ELON.., ELAT..)
!        - angles of Fullpos structure are in degrees (RLON.., RLAT..)

!**   INTERFACE.
!     ----------
!       *CALL* *SUFPMODELGEO*

!        EXPLICIT ARGUMENTS
!        ------------------
!           KFPCONF : configuration of the post-processing :
!                     0 : vertical interpolation only (<CFPFMT='MODEL'>)
!                     1 : gridpoint post-processing, possibly with spectral filters (<NFPOS=1>)
!                     2 : gridpoint/spectral post-processing (spectral outputs possible) (<NFPOS=2>)
!           KFPBOYD : /= 0 for Boyd biperiodicization of E-zone


!        IMPLICIT ARGUMENTS
!        ------------------

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS
!        Documentation about FULL-POS.

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 13-Mar-2017

!     MODIFICATIONS.
!     --------------
!    R. El Khatib 14-May-2018 fix uninitialized variable
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM, JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMCST_IFSAUX, ONLY : XRPI, XRA
USE YOMLUN   , ONLY : NULOUT
USE YOMFPC   , ONLY : LTRACEFP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMCT0   , ONLY : LELAM
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO, ALLOC_FPUSERGEO, PRINT_FPUSERGEO, CHECK_FPUSERGEO

!     ------------------------------------------------------------------

IMPLICIT NONE

LOGICAL          ,  INTENT (IN)    :: LDLAM
TYPE (GEOMETRY)  ,  INTENT (IN)    :: YDGEOMETRY
CHARACTER(LEN=*) ,  INTENT (IN)    :: CDFPDOM
TYPE (TFPUSERGEO),  INTENT (INOUT) :: YDFPUSERGEO
TYPE (GEOMETRY)  ,  INTENT (IN)    :: YDHOSTGEOM
INTEGER(KIND=JPIM), INTENT (IN)    :: KFPCONF
INTEGER(KIND=JPIM), INTENT (IN)    :: KFPBOYD


REAL(KIND=JPRB)    :: ZLO0, ZLA0, ZLOC, ZLAC, ZEPS, ZRDTODG

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "trans_inq.h"

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SUFPMODELGEO',0,ZHOOK_HANDLE)

!*       1. ALLOCATE AND FILL STRUCTURE WITH USER PARAMETER
!           -----------------------------------------------

ZRDTODG=180._JPRB/XRPI

YDFPUSERGEO%CFPDOM   = CDFPDOM
YDFPUSERGEO%NLAT     = YDGEOMETRY%YRDIM%NDGLG
YDFPUSERGEO%NLON     = YDGEOMETRY%YRDIM%NDLON
YDFPUSERGEO%NFPMAX   = YDGEOMETRY%YRDIM%NSMAX
YDFPUSERGEO%NMFPMAX  = YDGEOMETRY%YRDIM%NMSMAX
! lam specific
YDFPUSERGEO%NFPGUX   = YDGEOMETRY%YRDIM%NDGUXG
YDFPUSERGEO%NFPLUX   = YDGEOMETRY%YRDIM%NDLUXG
YDFPUSERGEO%NFPBWX   = YDGEOMETRY%YREDIM%NBIPINCIX
YDFPUSERGEO%NFPBWY   = YDGEOMETRY%YREDIM%NBIPINCIY
YDFPUSERGEO%NFPNOEXTZL  = YDGEOMETRY%YREDIM%NNOEXTZL
YDFPUSERGEO%NFPNOEXTZG  = YDGEOMETRY%YREDIM%NNOEXTZG
YDFPUSERGEO%RLATC    = YDGEOMETRY%YREGEO%ELATC*ZRDTODG
YDFPUSERGEO%RLONC    = YDGEOMETRY%YREGEO%ELONC*ZRDTODG
YDFPUSERGEO%FPLON0   = YDGEOMETRY%YREGEO%ELON0*ZRDTODG
YDFPUSERGEO%FPLAT0   = YDGEOMETRY%YREGEO%ELAT0*ZRDTODG
YDFPUSERGEO%LFPMRT   = YDGEOMETRY%YREGEO%LMRT
YDFPUSERGEO%LFPMAP   = YDGEOMETRY%YREGEO%LMAP
IF (LDLAM) THEN
  YDFPUSERGEO%CFPGRID = 'LELAM'
  IF (YDGEOMETRY%YREGEO%LREDEL_IN_METRES) THEN
    YDFPUSERGEO%RDELY    = YDGEOMETRY%YREGEO%EDELY
    YDFPUSERGEO%RDELX    = YDGEOMETRY%YREGEO%EDELX
    YDFPUSERGEO%FPLX     = YDGEOMETRY%YREGEO%ELX
    YDFPUSERGEO%FPLY     = YDGEOMETRY%YREGEO%ELY
  ELSE
    YDFPUSERGEO%RDELY    = YDGEOMETRY%YREGEO%EDELY*ZRDTODG
    YDFPUSERGEO%RDELX    = YDGEOMETRY%YREGEO%EDELX*ZRDTODG
    YDFPUSERGEO%FPLX     = YDGEOMETRY%YREGEO%ELX*XRA
    YDFPUSERGEO%FPLY     = YDGEOMETRY%YREGEO%ELY*XRA
  ENDIF
ELSE
  YDFPUSERGEO%CFPGRID = 'GAUSS'
ENDIF
YDFPUSERGEO%NFPBZONL  = YDGEOMETRY%YREDIM%NBZONL
YDFPUSERGEO%NFPBZONG  = YDGEOMETRY%YREDIM%NBZONG
YDFPUSERGEO%NFPEDOM   = 1
! global specific
YDFPUSERGEO%NFPHTYP  = YDGEOMETRY%YRGEM%NHTYP
YDFPUSERGEO%NFPTTYP  = YDGEOMETRY%YRGEM%NSTTYP
YDFPUSERGEO%FPMUCEN  = YDGEOMETRY%YRGEM%RMUCEN
YDFPUSERGEO%FPLOCEN  = YDGEOMETRY%YRGEM%RLOCEN
YDFPUSERGEO%FPSTRET  = YDGEOMETRY%YRGEM%RSTRET

CALL ALLOC_FPUSERGEO(YDFPUSERGEO)

YDFPUSERGEO%NFPRGRI(:)= YDGEOMETRY%YRGEM%NLOENG(1:YDFPUSERGEO%NLAT)

CALL CHECK_FPUSERGEO(YDFPUSERGEO,NULOUT)

!*       2. FINALIZE STRUCTURE WITH VARIABLES COMPUTED FROM THE SPECTRAL TRANSFORMS PACKAGE
!           -------------------------------------------------------------------------------

YDFPUSERGEO%LFPMODELSPEC = (YDFPUSERGEO%NFPMAX == YDHOSTGEOM%YRDIM%NSMAX)
IF(YDFPUSERGEO%CFPGRID == 'LELAM' .AND. LELAM) THEN
  IF (YDFPUSERGEO%LFPMODELSPEC) YDFPUSERGEO%LFPMODELSPEC = (YDFPUSERGEO%NMFPMAX == YDHOSTGEOM%YRDIM%NMSMAX)
ELSEIF (YDFPUSERGEO%CFPGRID == 'LALON') THEN
  YDFPUSERGEO%LFPMODELSPEC=.FALSE.
ENDIF

YDFPUSERGEO%LFPMODELGRID = (YDFPUSERGEO%NLON == YDHOSTGEOM%YRDIM%NDLON).AND.(YDFPUSERGEO%NLAT == YDHOSTGEOM%YRDIM%NDGLG)
IF (YDFPUSERGEO%CFPGRID == 'GAUSS' .AND. .NOT.LELAM) THEN
   IF (YDFPUSERGEO%LFPMODELGRID) YDFPUSERGEO%LFPMODELGRID = &
    & (ALL(YDFPUSERGEO%NFPRGRI(1:YDFPUSERGEO%NLAT) == YDHOSTGEOM%YRGEM%NLOENG(1:YDHOSTGEOM%YRDIM%NDGLG)))
ELSEIF(YDFPUSERGEO%CFPGRID == 'LALON') THEN
  YDFPUSERGEO%LFPMODELGRID=.FALSE.
ENDIF

IF(YDFPUSERGEO%CFPGRID == 'LELAM' .AND. LELAM) THEN
  YDFPUSERGEO%LFPMODELCORE = (YDFPUSERGEO%NFPLUX == YDHOSTGEOM%YRDIM%NDLUXG).AND.(YDFPUSERGEO%NFPGUX == YDHOSTGEOM%YRDIM%NDGUXG)
ELSEIF (YDFPUSERGEO%CFPGRID == 'GAUSS' .AND. .NOT.LELAM) THEN
  YDFPUSERGEO%LFPMODELCORE = YDFPUSERGEO%LFPMODELGRID
ELSE
  YDFPUSERGEO%LFPMODELCORE = .FALSE.
ENDIF

ZEPS = EPSILON(1.0_JPRB)*10000._JPRB
IF (YDFPUSERGEO%CFPGRID == 'GAUSS' .AND. .NOT.LELAM) THEN
  YDFPUSERGEO%LFPCOORD = (.NOT.YDFPUSERGEO%LFPMODELCORE) .OR. &
   & (ABS(YDFPUSERGEO%FPSTRET-YDHOSTGEOM%YRGEM%RSTRET) > ZEPS) .OR. (YDFPUSERGEO%NFPTTYP /= YDHOSTGEOM%YRGEM%NSTTYP) .OR. &
   & (ABS(YDFPUSERGEO%FPMUCEN-YDHOSTGEOM%YRGEM%RMUCEN) > ZEPS) .OR. (ABS(YDFPUSERGEO%FPLOCEN-YDHOSTGEOM%YRGEM%RLOCEN) > ZEPS)
ELSEIF(YDFPUSERGEO%CFPGRID == 'LELAM' .AND. LELAM) THEN
  IF (YDFPUSERGEO%LFPMAP .AND. YDHOSTGEOM%YREGEO%LMAP) THEN
    ZRDTODG=180._JPRB/XRPI
    ZLO0=ABS(MOD(YDFPUSERGEO%FPLON0-YDHOSTGEOM%YREGEO%ELON0*ZRDTODG,360._JPRB))
    ZLA0=ABS(MOD(YDFPUSERGEO%FPLAT0-YDHOSTGEOM%YREGEO%ELAT0*ZRDTODG,360._JPRB))
    ZLOC=ABS(MOD(YDFPUSERGEO%RLONC-YDHOSTGEOM%YREGEO%ELONC*ZRDTODG,360._JPRB))
    ZLAC=ABS(MOD(YDFPUSERGEO%RLATC-YDHOSTGEOM%YREGEO%ELATC*ZRDTODG,360._JPRB))
    YDFPUSERGEO%LFPCOORD = (.NOT.YDFPUSERGEO%LFPMODELCORE) .OR. &
     & (ZLO0 > ZEPS.AND.(360._JPRB-ZLO0) > ZEPS) .OR. &
     & (ZLA0 > ZEPS.AND.(360._JPRB-ZLA0) > ZEPS) .OR. &
     & (ZLAC > ZEPS.AND.(360._JPRB-ZLAC) > ZEPS) .OR. &
     & (ZLOC > ZEPS.AND.(360._JPRB-ZLOC) > ZEPS) .OR. ((YDFPUSERGEO%LFPMRT.NEQV.YDHOSTGEOM%YREGEO%LMRT)) .OR. &
     & (ABS(YDFPUSERGEO%RDELX-YDHOSTGEOM%YREGEO%EDELX) > ZEPS) .OR. (ABS(YDFPUSERGEO%RDELY-YDHOSTGEOM%YREGEO%EDELY) > ZEPS)
  ELSEIF (.NOT.YDFPUSERGEO%LFPMAP .AND. .NOT.YDHOSTGEOM%YREGEO%LMAP) THEN
    YDFPUSERGEO%LFPCOORD = (.NOT.YDFPUSERGEO%LFPMODELCORE) .OR. &
     & (ABS(YDFPUSERGEO%FPLX-YDHOSTGEOM%YREGEO%ELX) > ZEPS) .OR. (ABS(YDFPUSERGEO%FPLY-YDHOSTGEOM%YREGEO%ELY) > ZEPS)
  ELSE
    YDFPUSERGEO%LFPCOORD=.TRUE.
  ENDIF
ELSE
  YDFPUSERGEO%LFPCOORD=.TRUE.
ENDIF

! If a non-empty extension zone exists
IF (YDFPUSERGEO%CFPGRID == 'LELAM' .AND. &
 & YDFPUSERGEO%NLAT*YDFPUSERGEO%NLON-YDFPUSERGEO%NFPLUX*YDFPUSERGEO%NFPGUX > 0) THEN
  ! No interpolation and no change of the width of the extension zone <=> no biper
  YDFPUSERGEO%LFPBIPER=.NOT.(LELAM.AND.YDFPUSERGEO%LFPMODELGRID.AND..NOT.YDFPUSERGEO%LFPCOORD)
ELSE
  YDFPUSERGEO%LFPBIPER=.FALSE.
ENDIF

! Extract core (no interpolations and no extension zone)
YDFPUSERGEO%LFPLAMCOREXT = LELAM .AND. &
 & .NOT.(YDFPUSERGEO%LFPCOORD .OR. YDFPUSERGEO%LFPBIPER .OR. YDFPUSERGEO%LFPMODELGRID)

! Map factor aspect : only for projections, real case + expected spectral outputs
YDFPUSERGEO%LFPMAPF = (KFPCONF /= 1 .AND. YDFPUSERGEO%CFPGRID == 'LELAM' .AND. YDFPUSERGEO%LFPMAP)

YDFPUSERGEO%LFPOSBUFSHAPE = YDFPUSERGEO%LFPCOORD .OR. YDFPUSERGEO%LFPBIPER .OR. YDFPUSERGEO%LFPLAMCOREXT

! nproma slicing is needed to ensure output data would fit any third-party host array -oops !
YDFPUSERGEO%LFPOSBUFSHAPE = YDFPUSERGEO%LFPOSBUFSHAPE .OR. (YDGEOMETRY%YRDIM%NPROMA /= YDHOSTGEOM%YRDIM%NPROMA)


YDFPUSERGEO%NFPSIZEG=SUM(YDFPUSERGEO%NFPRGRI(1:YDFPUSERGEO%NLAT))
IF (KFPBOYD==0) THEN
  YDFPUSERGEO%NFPSIZEG_DEP=YDFPUSERGEO%NFPSIZEG
ELSE
  YDFPUSERGEO%NFPSIZEG_DEP=(YDFPUSERGEO%NFPLUX+2*YDFPUSERGEO%NFPBWX+2*(YDFPUSERGEO%NLON-YDFPUSERGEO%NFPLUX)) &
                        & *(YDFPUSERGEO%NFPGUX+2*YDFPUSERGEO%NFPBWY+2*(YDFPUSERGEO%NLAT-YDFPUSERGEO%NFPGUX))
ENDIF

! Let us make this parameter simple :
IF (YDFPUSERGEO%LFPOSBUFSHAPE) THEN
  YDFPUSERGEO%NFPDIST=2
ELSE
  YDFPUSERGEO%NFPDIST=0
ENDIF

YDFPUSERGEO%NFPRESOL = YDGEOMETRY%YRDIM%NRESOL
YDFPUSERGEO%NSPEC2G = YDGEOMETRY%YRDIM%NSPEC2G
YDFPUSERGEO%NSPEC2 = YDGEOMETRY%YRDIM%NSPEC2
YDFPUSERGEO%NGPTOT = YDGEOMETRY%YRGEM%NGPTOT
YDFPUSERGEO%NFPMEN(:)= YDGEOMETRY%YRGEM%NMENG(1:YDFPUSERGEO%NLAT)
IF (.NOT.LDLAM) THEN
  ! Call Trans_INQ to set FPMU in double precision
  CALL TRANS_INQ(KRESOL=YDFPUSERGEO%NFPRESOL,PMU=YDFPUSERGEO%FPMU(1:YDFPUSERGEO%NLAT))
ENDIF


IF (LTRACEFP) THEN
  CALL PRINT_FPUSERGEO(YDFPUSERGEO,NULOUT)
ENDIF

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SUFPMODELGEO',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPMODELGEO
