! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPSUW(YDCLIMO,YDNAMFPINT,YDNAMFPSCI,YDAFN,KFPXFLD,YDFPGEOMETRY,YDFPSUW,YDFPWSTD,YDFPSTRUCT, &
 & YDGEOMETRY,YDSURF,YDMODEL)

! Purpose :
! -------
!   *SUFPSUW* Compute weights for horizontal interpolations of surface fields

! Interface :
! ---------

!        KFPXFLD : maximum number of fields to extract at a time

! Externals :
! ---------
!   see below

! Method :
! ------

! Reference :
! ---------

! Author :
! ------
!   03-Aug-2005 R. El Khatib  *METEO-FRANCE*

! Modifications :
! -------------
!   K. Yessad: 28-Feb-2007: optimisation of distributed memory in FULL-POS.
!   K. Yessad (oct 2010): multi-linear interpolations.
!   G.Mozdzynski (Jan 2011): OOPS cleaning, use of derived types SL_STRUCT, TCSGLEG
!   R. El Khatib  24-Jul-2012 LFPDISTRIB replaced by NFPDISTRIB
!   R. El Khatib 13-Dec-2012 Fullpos buffers reshaping
!   T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!      R. El Khatib 27-Sep-2013 move fptratod inside cpclimi
!   P.Marguinaud    01-Oct-2014 Compute weights for PREP fields interpolations
!   R. El Khatib 27-Jul-2016 interpolations over C+I+E
! End Modifications
!-----------------------------------------------------------------------------

USE TYPE_MODEL         , ONLY : MODEL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1           , ONLY : JPIM     ,JPRB
USE YOMHOOK            , ONLY : LHOOK,   DR_HOOK, JPHOOK
USE YOMLUN             , ONLY : NULOUT
USE YOMCT0             , ONLY : LELAM
USE YOMAFN             , ONLY : TAFN
USE YOMFPC             , ONLY : TNAMFPINT, TNAMFPSCI, LALLOFP, LTRACEFP
USE YOMWFPB            , ONLY : TFPWSTD, TFPSUW
USE EINT_MOD           , ONLY : SL_STRUCT
USE YOMCST             , ONLY : RPI
USE YOMFPGEOMETRY      , ONLY : TFPGEOMETRY
USE TYPE_FPOSBUF       , ONLY : FPOSBUF
USE MPL_MODULE         , ONLY : MPL_BARRIER

!-----------------------------------------------------------------------------

IMPLICIT NONE

TYPE(FPOSBUF)      , INTENT(IN) :: YDCLIMO
TYPE(TNAMFPINT)    , INTENT(IN) :: YDNAMFPINT
TYPE(TNAMFPSCI)    , INTENT(IN) :: YDNAMFPSCI
TYPE(TAFN)         , INTENT(IN) :: YDAFN
INTEGER(KIND=JPIM) , INTENT(IN) :: KFPXFLD
TYPE(TFPGEOMETRY)  , INTENT(IN) :: YDFPGEOMETRY
TYPE(TFPSUW)       , INTENT(INOUT) :: YDFPSUW
TYPE(TFPWSTD)      , INTENT(IN) :: YDFPWSTD
TYPE(SL_STRUCT)    , INTENT(IN) :: YDFPSTRUCT
TYPE(GEOMETRY)     , INTENT(IN) :: YDGEOMETRY
TYPE(TSURF)        , INTENT(IN) :: YDSURF
TYPE(MODEL)        , INTENT(IN) :: YDMODEL

REAL(KIND=JPRB) :: ZDLAT(4,YDFPGEOMETRY%YFPGEO_DEP%NFPROMA), ZDLO(0:3,4,YDFPGEOMETRY%YFPGEO_DEP%NFPROMA)
REAL(KIND=JPRB) :: ZTSIN(YDFPSTRUCT%NASLB1), ZTSOUT(YDFPGEOMETRY%YFPGEO_DEP%NFPROMA)
REAL(KIND=JPRB) :: ZMASKIN(YDFPSTRUCT%NASLB1,2)
! ZMASKOUT_DEP(:,1,:) = land-sea mask or land mask
! ZMASKOUT_DEP(:,2,:) = sea mask
REAL(KIND=JPRB) :: ZMASKOUT_DEP(YDFPGEOMETRY%YFPGEO_DEP%NFPROMA,YDNAMFPSCI%NFPMASK,YDFPGEOMETRY%YFPGEO_DEP%NFPBLOCS)

REAL(KIND=JPRB) :: ZFPCR_SFX(2,4)

INTEGER(KIND=JPIM) :: IEND,ILSIM,IST,J,IBINL,IOFF
INTEGER(KIND=JPIM) :: ICOD(YDNAMFPSCI%NFPMASK), IORDER(YDNAMFPSCI%NFPMASK)

INTEGER(KIND=JPIM) :: ILAT(YDFPGEOMETRY%YFPGEO_DEP%NFPROMA), ILON(YDFPGEOMETRY%YFPGEO_DEP%NFPROMA)
INTEGER(KIND=JPIM) :: ILOS(YDFPGEOMETRY%YFPGEO_DEP%NFPROMA)
INTEGER(KIND=JPIM) :: ILONN(YDFPGEOMETRY%YFPGEO_DEP%NFPROMA), ILOSS(YDFPGEOMETRY%YFPGEO_DEP%NFPROMA)

LOGICAL :: LLML, LLSURF, LLLAN00, LLSEA00
INTEGER(KIND=JPIM) :: IPSL, I1, I2, I3, I4, JBLOC, JI

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-----------------------------------------------------------------------------

#include "cpclimi.intfb.h"
#include "suhow1.intfb.h"
#include "suehow1.intfb.h"
#include "suehowlsm.intfb.h"
#include "sufpcip.intfb.h"
#include "suhowlsm.intfb.h"

!-----------------------------------------------------------------------------


IF (LHOOK) CALL DR_HOOK('SUFPSUW',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM, YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP,  &
 & YDCSGLEG=>YDGEOMETRY%YRCSGLEG, YDEGEO=>YDGEOMETRY%YREGEO, YDPHY1=>YDMODEL%YRML_PHY_MF%YRPHY1, &
 & YDFPGEO_DEP=>YDFPGEOMETRY%YFPGEO_DEP, YDFPGEO=>YDFPGEOMETRY%YFPGEO,GFP=>YDAFN%GFP)
ASSOCIATE(LFPML_LAN=>YDNAMFPINT%LFPML_LAN, LFPML_SEA=>YDNAMFPINT%LFPML_SEA, NFPINPHY=>YDNAMFPINT%NFPINPHY, &
 & RFPCR_LAN=>YDNAMFPINT%RFPCR_LAN, RFPCR_SEA=>YDNAMFPINT%RFPCR_SEA, &
 & NFPLAKE=>YDNAMFPSCI%NFPLAKE, NFPSURFEX=>YDNAMFPSCI%NFPSURFEX, NFPMASK=>YDNAMFPSCI%NFPMASK, &
 & NFPROMA_DEP=>YDFPGEO_DEP%NFPROMA, NFPRGPL_DEP=>YDFPGEO_DEP%NFPRGPL,NDGENH=>YDFPSTRUCT%NDGENH, NDGLG=>YDDIM%NDGLG, &
 & NFPROMA=>YDFPGEO%NFPROMA, NFPBLOCS=>YDFPGEO%NFPBLOCS, &
 & NDGSAH=>YDFPSTRUCT%NDGSAH, NDLON=>YDDIM%NDLON, NAFPB1=>YDFPSTRUCT%NASLB1, &
 & RFPLA_DEP=>YDFPGEO_DEP%RFPLA, RFPLO_DEP=>YDFPGEO_DEP%RFPLO, NFPBLOCS_DEP=>YDFPGEO_DEP%NFPBLOCS, NFPEND_DEP=>YDFPGEO_DEP%NFPEND, &
 & RFPGMS_DEP=>YDFPGEO_DEP%RFPGMS, RINVGMS=>YDFPWSTD%RINVGMS, ML0=>YDFPWSTD%ML0, &
 & EDELX=>YDEGEO%EDELX, EDELY=>YDEGEO%EDELY, &
 & NLOENG=>YDGEM%NLOENG, R4JP=>YDGEM%R4JP, RC2M1=>YDGEM%RC2M1, &
 & RC2P1=>YDGEM%RC2P1, RSTRET=>YDGEM%RSTRET, &
 & NFRSTLOFF=>YDMP%NFRSTLOFF, &
 & TMERGL=>YDPHY1%TMERGL)
!-----------------------------------------------------------------------------

! 1. Setup general switches for the choice of surface-dependent weights computation
!    ------------------------------------------------------------------------------

! Surface-dependent fields expected
!LLSURF = (NFP3H+NFP3S+NFP3F+NFP2DF+NFPPHY+NFPCFU+NFPXFU > 0)
LLSURF = .TRUE. ! temporary (?) simplification

! Land(-sea) mask weights
         LLLAN00 =  (NFPMASK >= 1) .AND. (NFPINPHY ==  0) .AND. LLSURF
! Lake option uses quadratic weights, to minimize the number of isolated point
YDFPSUW%LWLAN12 = ((NFPMASK >= 1) .AND. (NFPINPHY == 12) .AND. LLSURF) .OR. (NFPLAKE /= 0)
! linear weight if no quadratic interpolations but nearest point
YDFPSUW%LWLAN04 = ((NFPMASK >= 1) .AND. (NFPINPHY ==  4) .AND. LLSURF) .OR. (LLLAN00 .AND. .NOT.YDFPSUW%LWLAN12)

! Sea mask weights
         LLSEA00 =  (NFPMASK >= 2) .AND. (NFPINPHY ==  0) .AND. LLSURF
! Lake option uses quadratic weights, to minimize the number of isolated point
YDFPSUW%LWSEA12 = ((NFPMASK >= 2) .AND. (NFPINPHY == 12) .AND. LLSURF) .OR. ((NFPLAKE /= 0) .AND. NFPMASK >= 2)
! linear weight if no quadratic interpolations but nearest point
YDFPSUW%LWSEA04 = ((NFPMASK >= 2) .AND. (NFPINPHY ==  4) .AND. LLSURF) .OR. (LLSEA00 .AND. .NOT.YDFPSUW%LWSEA12)

IF(LTRACEFP) THEN
  WRITE(UNIT=NULOUT,FMT='('' YDFPSUW%LWLAN04 = '',L2,'' YDFPSUW%LWSEA04 = '',L2)') YDFPSUW%LWLAN04, YDFPSUW%LWSEA04
  WRITE(UNIT=NULOUT,FMT='('' YDFPSUW%LWLAN12 = '',L2,'' YDFPSUW%LWSEA12 = '',L2)') YDFPSUW%LWLAN12, YDFPSUW%LWSEA12
ENDIF


! 2. Interpolate input surface masks
!    --------------------------------

IF (NFPMASK >= 1) THEN

  ! Interpolate ISBA masks :
  ! Land-Sea mask :
  ICOD(1)=GFP%LSM%ICOD
  IORDER(1)=ABS(GFP%LSM%IORDR)
  IF (NFPMASK >= 2) THEN
    ! Land proportion :
    ICOD(2)=GFP%LAN%ICOD
    IORDER(2)=ABS(GFP%LAN%IORDR)
  ENDIF
  CALL CPCLIMI(YDCLIMO,YDNAMFPINT,YDNAMFPSCI,YDAFN,KFPXFLD,YDFPGEOMETRY,YDFPWSTD,YDFPSTRUCT,YDGEOMETRY,YDSURF,YDMODEL, &
   & NFPMASK,ICOD,IORDER,ZMASKIN,ZMASKOUT_DEP)

  ! No use of sea/ice aspect => provisional initialization of Ts/SST:
  ZTSIN(:)=TMERGL
  ZTSOUT(:)=TMERGL

  ALLOCATE(YDFPSUW%WLANML(NFPROMA_DEP,5:16,NFPBLOCS_DEP))
  IF (LALLOFP) THEN
    WRITE(NULOUT,9990) 'YDFPSUW%WLANML   ',SIZE(YDFPSUW%WLANML),SHAPE(YDFPSUW%WLANML)
  ENDIF
  IF (YDFPSUW%LWLAN12) THEN
    WRITE (NULOUT,*) ' SUFPSUW: weights LAN12 computed'
    IBINL=12
    ALLOCATE(YDFPSUW%WLAN12(NFPROMA_DEP,IBINL,NFPBLOCS_DEP))
    IF (LALLOFP) THEN
      WRITE(NULOUT,9990) 'YDFPSUW%WLAN12   ',SIZE(YDFPSUW%WLAN12),SHAPE(YDFPSUW%WLAN12)
    ENDIF
  ENDIF
  IF (YDFPSUW%LWLAN04) THEN
    WRITE (NULOUT,*) ' SUFPSUW: weights LAN04 computed'
    IBINL=4
    ALLOCATE(YDFPSUW%WLAN04(NFPROMA_DEP,IBINL,NFPBLOCS_DEP))
    IF (LALLOFP) THEN
      WRITE(NULOUT,9990) 'YDFPSUW%WLAN04   ',SIZE(YDFPSUW%WLAN04),SHAPE(YDFPSUW%WLAN04)
    ENDIF
  ENDIF
  IF (NFPLAKE /= 0) THEN
    ALLOCATE(YDFPSUW%MWIC(NFPROMA,NFPBLOCS))
    IF (LALLOFP) THEN
      WRITE(NULOUT,'(1X,''ARRAY '',A10,'' ALLOCATED '',8I8)') 'YDFPSUW%MWIC     ',SIZE(YDFPSUW%MWIC),SHAPE(YDFPSUW%MWIC)
    ENDIF
  ENDIF

  IF (NFPMASK >= 2) THEN
    ALLOCATE(YDFPSUW%WSEAML(NFPROMA_DEP,5:16,NFPBLOCS_DEP))
    IF (LALLOFP) THEN
      WRITE(NULOUT,9990) 'YDFPSUW%WSEAML   ',SIZE(YDFPSUW%WSEAML),SHAPE(YDFPSUW%WSEAML)
    ENDIF
    IF (YDFPSUW%LWSEA12) THEN
      WRITE (NULOUT,*) ' SUFPSUW: weights SEA12 computed'
      IBINL=12
      ALLOCATE(YDFPSUW%WSEA12(NFPROMA_DEP,IBINL,NFPBLOCS_DEP))
      IF (LALLOFP) THEN
        WRITE(NULOUT,9990) 'YDFPSUW%WSEA12   ',SIZE(YDFPSUW%WSEA12),SHAPE(YDFPSUW%WSEA12)
      ENDIF
    ENDIF
    IF (YDFPSUW%LWSEA04) THEN
      WRITE (NULOUT,*) ' SUFPSUW: weights SEA04 computed'
      IBINL=4
      ALLOCATE(YDFPSUW%WSEA04(NFPROMA_DEP,IBINL,NFPBLOCS_DEP))
      IF (LALLOFP) THEN
        WRITE(NULOUT,9990) 'YDFPSUW%WSEA04   ',SIZE(YDFPSUW%WSEA04),SHAPE(YDFPSUW%WSEA04)
      ENDIF
    ENDIF
  ENDIF

ENDIF

IF (NFPSURFEX == 2) THEN

  IBINL=4
  ALLOCATE(YDFPSUW%NPSLSFX(0:1,0:1,0:1,0:1))
  ALLOCATE(YDFPSUW%LPSLSFX(IBINL,SIZE(YDFPSUW%NPSLSFX)))
  ALLOCATE(YDFPSUW%WSFXPS(NFPROMA_DEP,IBINL,SIZE(YDFPSUW%NPSLSFX),NFPBLOCS_DEP))
  IF (LALLOFP) THEN
    WRITE(NULOUT,9990) 'YDFPSUW%NPSLSFX   ',SIZE(YDFPSUW%NPSLSFX),SHAPE(YDFPSUW%NPSLSFX)
    WRITE(NULOUT,9990) 'YDFPSUW%LPSLSFX   ',SIZE(YDFPSUW%LPSLSFX),SHAPE(YDFPSUW%LPSLSFX)
    WRITE(NULOUT,9990) 'YDFPSUW%WSFXPS   ',SIZE(YDFPSUW%WSFXPS),SHAPE(YDFPSUW%WSFXPS)
  ENDIF
  IPSL = 1
  DO I1 = 0, 1
    DO I2 = 0, 1
      DO I3 = 0, 1
        DO I4 = 0, 1
          YDFPSUW%NPSLSFX(I1, I2, I3, I4) = IPSL
          YDFPSUW%LPSLSFX(1, IPSL) = I1 > 0
          YDFPSUW%LPSLSFX(2, IPSL) = I2 > 0
          YDFPSUW%LPSLSFX(3, IPSL) = I3 > 0
          YDFPSUW%LPSLSFX(4, IPSL) = I4 > 0
          IPSL = IPSL + 1
        ENDDO
      ENDDO
    ENDDO
  ENDDO
  DO JI=1,SIZE(ZFPCR_SFX,DIM=2)
    ZFPCR_SFX(1,JI)=1.0_JPRB
    ZFPCR_SFX(2,JI)=0.0_JPRB
  ENDDO

ENDIF


! 2. Compute weights with masks
!    --------------------------

LLML=(NFPSURFEX == 2).OR.LFPML_LAN.OR.LFPML_SEA

!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(JBLOC,IST,IEND,IOFF,J,ILSIM,IBINL,ZDLAT,ZDLO,ILAT,ILON,ILONN,ILOS,ILOSS)
DO JBLOC=1,NFPBLOCS_DEP

! 2.1  Adressing

  IST =1
  IEND=NFPEND_DEP(JBLOC)
  IOFF=(JBLOC-1)*NFPROMA_DEP

  IBINL=0 ! cheap (?)
  IF (LELAM) THEN
    CALL SUEHOW1(NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,IBINL,LLML,RFPLA_DEP(IOFF+1),RFPLO_DEP(IOFF+1),&
     & EDELX,EDELY,NDLON,NDGLG,ILAT,ILON,ILONN,ILOS,ILOSS,ZDLAT,ZDLO(0,1,1))
  ELSE
    CALL SUHOW1(NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,R4JP,RPI,NLOENG(NDGSAH+NFRSTLOFF:),YDCSGLEG%RLATIG(NDGSAH+NFRSTLOFF:),&
     & IBINL,LLML,RFPLA_DEP(IOFF+1),RFPLO_DEP(IOFF+1),ILAT,ILON,ILONN,ILOS,ILOSS,ZDLAT,ZDLO(0,1,1))
  ENDIF

! 2.2 Weights with Land mask or land-sea mask

IF (NFPMASK >= 1) THEN

  IF (NFPSURFEX == 0) THEN
    IF (NFPMASK == 2) THEN
      DO J=1,IEND
        ZMASKOUT_DEP(J,1,JBLOC)=REAL(CEILING(ZMASKOUT_DEP(J,2,JBLOC)))
        ZMASKOUT_DEP(J,2,JBLOC)=REAL(CEILING(1._JPRB-ZMASKOUT_DEP(J,2,JBLOC)))
      ENDDO
    ENDIF
  ELSEIF (NFPSURFEX == 1) THEN
    ! Conversion ISBA -> SURFEX. Force land everywhere because we don't have land prop. from surfex
    ZMASKOUT_DEP(:,1,JBLOC)=1._JPRB
    IF (NFPMASK == 2) THEN
      ! Conversion ISBA -> SURFEX. Force sea everywhere because we don't have land prop. from surfex
      ZMASKOUT_DEP(:,2,JBLOC)=0._JPRB
    ENDIF
  ENDIF
  
  ILSIM=1

  IF (YDFPSUW%LWLAN12) THEN
    IBINL=12
    IF (LELAM) THEN
      CALL SUEHOWLSM(NFPROMA_DEP,IEND,NAFPB1,RFPCR_LAN,RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),ILSIM,IBINL,LFPML_LAN,ML0(:,:,JBLOC), &
       & ZDLAT,ZDLO(0,1,1),EDELY,YDFPSUW%WLAN12(:,:,JBLOC),YDFPSUW%WLANML(:,5:16,JBLOC),TMERGL,ZTSIN, &
       & ZMASKIN(1,1),ZTSOUT,ZMASKOUT_DEP(:,1,JBLOC))
    ELSE
      CALL SUHOWLSM(NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,NAFPB1,RFPCR_LAN,YDCSGLEG%RLATIG(NDGSAH+NFRSTLOFF:), &
       & RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),ILSIM,IBINL,LFPML_LAN,ILAT,ML0(:,:,JBLOC),ZDLAT,ZDLO(0,1,1), &
       & YDFPSUW%WLAN12(:,:,JBLOC),YDFPSUW%WLANML(:,5:16,JBLOC),TMERGL,ZTSIN,ZMASKIN(1,1),ZTSOUT,ZMASKOUT_DEP(:,1,JBLOC))
    ENDIF
  ENDIF

  IF (YDFPSUW%LWLAN04) THEN
    IBINL=4
    IF (LELAM) THEN
      CALL SUEHOWLSM(NFPROMA_DEP,IEND,NAFPB1,RFPCR_LAN,RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),ILSIM,IBINL,LFPML_LAN,ML0(:,:,JBLOC), &
       & ZDLAT,ZDLO(0,1,1),EDELY,YDFPSUW%WLAN04(:,:,JBLOC),YDFPSUW%WLANML(:,5:16,JBLOC),TMERGL,ZTSIN, &
       & ZMASKIN(1,1),ZTSOUT,ZMASKOUT_DEP(:,1,JBLOC))
    ELSE
      CALL SUHOWLSM(NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,NAFPB1,RFPCR_LAN,YDCSGLEG%RLATIG(NDGSAH+NFRSTLOFF:), &
       & RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),ILSIM,IBINL,LFPML_LAN,ILAT,ML0(:,:,JBLOC),ZDLAT,ZDLO(0,1,1), &
       & YDFPSUW%WLAN04(:,:,JBLOC),YDFPSUW%WLANML(:,5:16,JBLOC),TMERGL,ZTSIN,ZMASKIN(1,1),ZTSOUT,ZMASKOUT_DEP(:,1,JBLOC))
    ENDIF
  ENDIF

ENDIF

! 2.3 Weights with Sea mask

IF (NFPMASK >= 2) THEN

  IF (YDFPSUW%LWSEA12) THEN
    IBINL=12
    IF (LELAM) THEN
      CALL SUEHOWLSM(NFPROMA_DEP,IEND,NAFPB1,RFPCR_SEA,RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),ILSIM,IBINL,LFPML_SEA,ML0(:,:,JBLOC), &
       & ZDLAT,ZDLO(0,1,1),EDELY,YDFPSUW%WSEA12(:,:,JBLOC),YDFPSUW%WSEAML(:,5:16,JBLOC),TMERGL,ZTSIN, &
       & ZMASKIN(1,1),ZTSOUT,ZMASKOUT_DEP(:,2,JBLOC))
    ELSE
      CALL SUHOWLSM(NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,NAFPB1,RFPCR_SEA,YDCSGLEG%RLATIG(NDGSAH+NFRSTLOFF:), &
       & RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),ILSIM,IBINL,LFPML_SEA,ILAT,ML0(:,:,JBLOC),ZDLAT,ZDLO(0,1,1), &
       & YDFPSUW%WSEA12(:,:,JBLOC),YDFPSUW%WSEAML(:,5:16,JBLOC),TMERGL,ZTSIN,ZMASKIN(1,1),ZTSOUT,ZMASKOUT_DEP(:,2,JBLOC))
    ENDIF
  ENDIF

  IF (YDFPSUW%LWSEA04) THEN
    IBINL=4
    IF (LELAM) THEN
      CALL SUEHOWLSM(NFPROMA_DEP,IEND,NAFPB1,RFPCR_SEA,RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),ILSIM,IBINL,LFPML_SEA,ML0(:,:,JBLOC), &
       & ZDLAT,ZDLO(0,1,1),EDELY,YDFPSUW%WSEA04(:,:,JBLOC),YDFPSUW%WSEAML(:,5:16,JBLOC),TMERGL,ZTSIN, &
       & ZMASKIN(1,1),ZTSOUT,ZMASKOUT_DEP(:,2,JBLOC))
    ELSE
      CALL SUHOWLSM(NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,NAFPB1,RFPCR_SEA,YDCSGLEG%RLATIG(NDGSAH+NFRSTLOFF:), &
       & RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),ILSIM,IBINL,LFPML_SEA,ILAT,ML0(:,:,JBLOC),ZDLAT,ZDLO(0,1,1), &
       & YDFPSUW%WSEA04(:,:,JBLOC),YDFPSUW%WSEAML(:,5:16,JBLOC),TMERGL,ZTSIN,ZMASKIN(1,1),ZTSOUT,ZMASKOUT_DEP(:,2,JBLOC))
    ENDIF
  ENDIF

ENDIF

! 2.4 Weights with SURFEX masks

IF (NFPSURFEX == 2) THEN

  IBINL=4
  ILSIM=3
  DO JI = 1, SIZE(YDFPSUW%NPSLSFX)
    IF (LELAM) THEN
      CALL SUEHOWLSM(NFPROMA_DEP,IEND,NAFPB1,ZFPCR_SFX,RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),ILSIM,IBINL,&
       & LLML,ML0(:,:,JBLOC),ZDLAT,ZDLO(0,1,1),EDELY,YDFPSUW%WSFXPS (:,:,JI,JBLOC),LDPSL=YDFPSUW%LPSLSFX (:,JI))
    ELSE
      CALL SUHOWLSM(NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,NAFPB1,ZFPCR_SFX,YDCSGLEG%RLATIG(NDGSAH+NFRSTLOFF:), &
       & RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),ILSIM,IBINL,LLML,ILAT,ML0(:,:,JBLOC),ZDLAT,ZDLO(0,1,1), &
       & YDFPSUW%WSFXPS (:,:,JI,JBLOC),LDPSL=YDFPSUW%LPSLSFX (:,JI))
    ENDIF
  ENDDO

ENDIF

ENDDO
!$OMP END PARALLEL DO

! fair load imbalance absorber
CALL MPL_BARRIER(CDSTRING='SUFPSUW:')


IF (NFPMASK >= 1) THEN
  IF (NFPLAKE /= 0) THEN
    CALL SUFPCIP(YDCLIMO,GFP,KFPXFLD,YDFPGEOMETRY,YDFPWSTD,YDFPSTRUCT,ZMASKIN(1,1),NFPMASK,ZMASKOUT_DEP,YDFPSUW%MWIC)
  ENDIF
ENDIF

!-----------------------------------------------------------------------------
9990 FORMAT(1X,'ARRAY ',A10,' ALLOCATED ',8I8)

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPSUW',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPSUW
