! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPRFPBUF_CLIM(YDCLIMO,YDAFN,KFPXFLD,YDFPGEO,KFPDOM,KMONTH,YDFPUSERGEO,CDFILE,YDNAMFPSCI,LDPHY)

!**** *SUFPRFPBUF_CLIM*  - INITIALIZE STRUCTURE YDCLIMO, WHICH CONTAINS THE OUTPUT CLIMATOLOGY DATA

!     PURPOSE.
!     --------
!       READ OUTPUT CLIMATOLOGY, COPY GEOMETRY THEN FILL BUFFER
!       DM-environment is the one of arrival geometry.

!**   INTERFACE.
!     ----------
!       *CALL* *SUFPRFPBUF_CLIM*

!        EXPLICIT ARGUMENTS
!        --------------------
!          KFPXFLD : maximum number of fields to extract at a time
!          KMONTH : month
!          KFPDOM : number of subdomains
!          CDFILE : climatology filenames (without possible month extension)

!        IMPLICIT ARGUMENTS
!        --------------------
!        See lower #include.

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS
!        Documentation about FULL-POS.

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 94-04-08

!     MODIFICATIONS.
!     --------------
!      R. El Khatib : 02-21-20 Fullpos B-level distribution + remove IO scheme
!      R. El Khatib : 03-01-29 Remove SM aspects.
!      R. El Khatib : 03-04-17 Fullpos improvments
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      M.Hamrud      10-Jan-2004 CY28R1 Cleaning
!      K. Yessad    : 31-01-2007 Cleanings + use DISGRIDFP.
!      R. El Khatib 31-Aug-2012 new E-zone management
!      R. El Khatib 13-Dec-2012 Fullpos buffers reshaping
!      R. El Khatib 01-Aug-2013 Optimization
!      R. El Khatib 06-07-2015 Move allocation of rfpbuf to _geom
!      R. El Khatib 08-Dec-2015 Interoperability GRIB2 vs FA
!      R. El Khatib 04-Aug-2016 use incfpf
!      R. El Khatib 16-Aug-2016 use output format for output climatology
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMLUN   , ONLY : NULOUT
USE PARFPOS  , ONLY : JPOSPHY
USE YOMFPGEO , ONLY : TFPGEO
USE TYPE_FPOSBUF, ONLY : FPOSBUF
USE YOMCT0   , ONLY : LARPEGEF
USE YOMMP0   , ONLY : MYPROC   ,NSTRIN, NPROC
USE YOMOPH0  , ONLY : CCLIMINC
USE YOMFPC   , ONLY : LALLOFP, LTRACEFP, TNAMFPSCI
USE YOMAFN   , ONLY : TAFN
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
USE TYPE_FPRQPHYS      , ONLY : ALLOCATE_FPRQPHY

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(FPOSBUF)     , INTENT(OUT) :: YDCLIMO
TYPE(TAFN)        , INTENT(IN) :: YDAFN
INTEGER(KIND=JPIM), INTENT(IN) :: KFPXFLD
TYPE(TFPGEO)      , INTENT(IN) :: YDFPGEO
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
INTEGER(KIND=JPIM), INTENT(IN) :: KMONTH
TYPE(TFPUSERGEO)  , INTENT(IN) :: YDFPUSERGEO(KFPDOM)
CHARACTER(LEN=*)  , INTENT(IN) :: CDFILE(KFPDOM)
TYPE(TNAMFPSCI)   , INTENT(IN) :: YDNAMFPSCI
LOGICAL           , INTENT(IN) :: LDPHY

INTEGER(KIND=JPIM) :: ISTRIN, IST, JDOM, IPTR, ICOD, JFLD, ICHUNKS, IFLDSCH, JCH, IBFA, IEFA, IBFABUF, INFG, INFL, IFLDS
INTEGER(KIND=JPIM) :: INFD(NPROC), IFLDOFF(NPROC)
INTEGER(KIND=JPIM) :: IFPCOD(JPOSPHY) ! temporary list of climatology fields

REAL(KIND=JPRB), ALLOCATABLE :: ZFIELDG(:,:)

CHARACTER(LEN=LEN(CDFILE(1))+LEN(CCLIMINC)+2) :: CLFILE(KFPDOM)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
!     ------------------------------------------------------------------

#include "sumpioh.intfb.h"
#include "incfpf.intfb.h"
#include "rdclimo.intfb.h"
#include "rdecclimo.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUFPRFPBUF_CLIM',0,ZHOOK_HANDLE)
ASSOCIATE(GFP_PHYDS=>YDAFN%GFP_PHYDS,NFPBLOCS=>YDFPGEO%NFPBLOCS, NFPROMA=>YDFPGEO%NFPROMA, NFPEND=>YDFPGEO%NFPEND, &
 & NFPRGPG=>YDFPGEO%NFPRGPG, NFPRGPIND=>YDFPGEO%NFPRGPIND, NFPRGPNUM=>YDFPGEO%NFPRGPNUM, &
 & NFPSIZEG=>YDFPUSERGEO%NFPSIZEG, GFP=>YDAFN%GFP, NFPMASK=>YDNAMFPSCI%NFPMASK, NFPCLI=>YDNAMFPSCI%NFPCLI, &
 & LCLIMALBEDOS=>YDNAMFPSCI%LCLIMALBEDOS, LCLIMAEROSOL=>YDNAMFPSCI%LCLIMAEROSOL, LCLIMOZONE=>YDNAMFPSCI%LCLIMOZONE)
!     ------------------------------------------------------------------

!*       1. SETUP LIST OF  CLIMATOLOGICAL OUTPUT FIELDS
!           -------------------------------------------

IPTR=0

IF (NFPCLI > 0) THEN

  CALL SET_NEXT(GFP%GFIS%ICOD)

  IF (LDPHY) THEN

    IF (NFPMASK >= 1) THEN
      CALL SET_NEXT(GFP%LSM%ICOD)
      IF (NFPMASK >= 2) THEN
        CALL SET_NEXT(GFP%LAN%ICOD)
      ENDIF
    ENDIF

    IF (NFPCLI > 1) THEN

      CALL SET_NEXT(GFP%ST%ICOD)
      CALL SET_NEXT(GFP%DST%ICOD)
      CALL SET_NEXT(GFP%CSSW%ICOD)
      CALL SET_NEXT(GFP%SD%ICOD)
      CALL SET_NEXT(GFP%CDSW%ICOD)
      CALL SET_NEXT(GFP%AL%ICOD)
      CALL SET_NEXT(GFP%EMIS%ICOD)
      CALL SET_NEXT(GFP%SDOG%ICOD)
      CALL SET_NEXT(GFP%VEG%ICOD)
      CALL SET_NEXT(GFP%SR%ICOD)
      CALL SET_NEXT(GFP%ACOT%ICOD)
      CALL SET_NEXT(GFP%DPAT%ICOD)

      CALL SET_NEXT(GFP%ARG%ICOD)
      CALL SET_NEXT(GFP%SAB%ICOD)
      CALL SET_NEXT(GFP%D2%ICOD)
      CALL SET_NEXT(GFP%IVEG%ICOD)
      CALL SET_NEXT(GFP%RSMIN%ICOD)
      CALL SET_NEXT(GFP%LAI%ICOD)
      CALL SET_NEXT(GFP%Z0H%ICOD)
      CALL SET_NEXT(GFP%BSR%ICOD)
      CALL SET_NEXT(GFP%BAAL%ICOD)

      IF (LCLIMALBEDOS) THEN
        CALL SET_NEXT(GFP%ALS%ICOD)
        CALL SET_NEXT(GFP%ALV%ICOD)
      ENDIF
      IF (LCLIMAEROSOL) THEN
        CALL SET_NEXT(GFP%ASEA%ICOD)
        CALL SET_NEXT(GFP%ALAN%ICOD)
        CALL SET_NEXT(GFP%ASOO%ICOD)
        CALL SET_NEXT(GFP%ADES%ICOD)
      ENDIF
      IF (LCLIMOZONE) THEN
        CALL SET_NEXT(GFP%O3A%ICOD)
        CALL SET_NEXT(GFP%O3B%ICOD)
        CALL SET_NEXT(GFP%O3C%ICOD)
      ENDIF

    ENDIF

  ENDIF

ENDIF

IFLDS=IPTR


!*       2. ALLOCATE STRUCTURE AND DESCRIBE IT
!           ----------------------------------

CALL ALLOCATE_FPRQPHY(GFP_PHYDS,YDCLIMO%YRQPHY,KFPDOM,IFLDS,IFPCOD(1:IFLDS),NULOUT,LALLOFP)
ALLOCATE(YDCLIMO%FPBUF(NFPROMA,0:IFLDS,NFPBLOCS)) ! always allocated
IF (LALLOFP) THEN
  WRITE(NULOUT,'(1X,''ARRAY '',A10,'' ALLOCATED '',8I8)') 'YDCLIMO%FPBUF  ',SIZE(YDCLIMO%FPBUF  ),SHAPE(YDCLIMO%FPBUF  )
ENDIF
IF(LTRACEFP) THEN
  WRITE(UNIT=NULOUT,FMT='('' MODULE YOMRFPB'')')
  WRITE(UNIT=NULOUT,FMT='('' NFPVSO = '',I2)') IFLDS
  IF (IFLDS > 0) THEN
    IF (LARPEGEF) THEN
      WRITE(NULOUT,FMT='(''(JFLD GFP_PHYDS%CLNAME)'')')
      WRITE(UNIT=NULOUT,FMT='(6('' ('',I2,1X,A16,'')''))')(JFLD,GFP_PHYDS(IFPCOD(JFLD))%CLNAME, JFLD=1,IFLDS)
    ELSE
      WRITE(NULOUT,FMT='(''(JFLD GFP_PHYDS%IGRIB)'')')
      WRITE(UNIT=NULOUT,FMT='(6('' ('',I2,1X,I5,'')''))') (JFLD,GFP_PHYDS(IFPCOD(JFLD))%IGRIB, JFLD=1,IFLDS)  
    ENDIF
  ENDIF
ENDIF

!*       4. READ OUTPUT CLIMATOLOGY
!           -----------------------

IF (IFLDS > 0) THEN

  IF (KFPXFLD <= 0) THEN
    IFLDSCH=IFLDS
  ELSE
    IFLDSCH=KFPXFLD
  ENDIF
  ICHUNKS=(IFLDS-1)/IFLDSCH+1

  IF (CCLIMINC==' ') THEN
    CLFILE(:)=CDFILE(:)
  ELSE
    DO JDOM=1,KFPDOM
      WRITE(UNIT=CLFILE(JDOM),FMT='(A,I2.2)') TRIM(CDFILE(JDOM))//TRIM(CCLIMINC),KMONTH
    ENDDO
  ENDIF

  DO JCH=1,ICHUNKS
    IBFA=(JCH-1)*IFLDSCH+1
    IEFA=MIN(JCH*IFLDSCH,IFLDS)
    INFG=IEFA-IBFA+1
    ISTRIN=MAX(1,MIN(NSTRIN,NPROC))
    CALL SUMPIOH(KPROC=NPROC,KPRIO=ISTRIN,KFLG=INFG,KFLD=INFD,KFLDOFF=IFLDOFF)
    INFL=INFD(MYPROC)
    ALLOCATE(ZFIELDG(NFPRGPG,INFL))
    IF (INFL > 0) THEN
      IST=IFLDOFF(MYPROC)+IBFA
      IF (LARPEGEF) THEN
        IPTR=1
        DO JDOM=1,KFPDOM
          CALL RDCLIMO(GFP_PHYDS,JDOM,CLFILE(JDOM),KMONTH,YDFPUSERGEO(JDOM),ZFIELDG,NFPRGPG,INFL,IPTR,IFPCOD(IST:IST-1+INFL),NFPCLI)
          IPTR=IPTR+NFPSIZEG(JDOM)
        ENDDO
      ELSE
        DO JDOM=1,KFPDOM
          CALL RDECCLIMO(YDAFN,CLFILE(JDOM),KMONTH,YDFPUSERGEO(JDOM),ZFIELDG,NFPRGPG,INFL,IFPCOD(IST:IST-1+INFL))
        ENDDO
      ENDIF
    ENDIF
  ! Shift field addresses by 1 because YDCLIMO%FPBUF is sized 0:IFLDS
    IBFABUF=IBFA+1
    CALL INCFPF(INFG,INFD,IFLDOFF,IBFABUF,NFPROMA,IFLDS+1,NFPBLOCS,NFPEND,NFPRGPG,NFPRGPNUM,NFPRGPIND,ZFIELDG,YDCLIMO%FPBUF)
    DEALLOCATE(ZFIELDG)
  ENDDO

ENDIF

! ---------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPRFPBUF_CLIM',1,ZHOOK_HANDLE)

!------------------------------------------------------------------------------

CONTAINS

SUBROUTINE SET_NEXT(KCOD)

INTEGER(KIND=JPIM), INTENT(IN)    :: KCOD
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SUFPRFPBUF_CLIM:SET_NEXT',0,ZHOOK_HANDLE)

IPTR=IPTR+1
IFPCOD(IPTR)=KCOD

IF (LHOOK) CALL DR_HOOK('SUFPRFPBUF_CLIM:SET_NEXT',1,ZHOOK_HANDLE)

END SUBROUTINE SET_NEXT

END SUBROUTINE SUFPRFPBUF_CLIM
