! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPWFPBUF(YDNAMFPINT,YDFPGEO_DEP,YDFPWSTD,YDFPSTRUCT,YDGEOMETRY)

!**** *SUFPWFPBUF*  - INITIALIZE BUFFER WFPBUF, WHICH CONTAINS THE WORKING FIELDS
!                   FOR HORIZONTAL INTERPOLATIONS : SIZE OF THE BOX, INDEXES
!                   AND WEIGHTS

!     PURPOSE.
!     --------
!        READ OR COMPUTE INPUT/OUTPUT LAND-SEA MASK, COMPUTE WEIGHTS AND INDEX,
!        (computes ILAT,ILON,ILOS,ILONN,ILOSS,WSTD04,WSTD12,WSTDML(:,5:16,JBLOC)).

!       Numbering of the points (I is the interpolation point):
!                     13       5       6      14

!                      7       1       2       8
!                                 (I)
!                      9       3       4      10

!                     15      11      12      16
!       Points number 1 to 12 are used if 12 points interpolations.
!       Points number 1 to 4 are used if bilinear interpolations.
!       All points are used for multi-linear interpolations.

!       DM-environment is the one of departure geometry.


!        IMPLICIT ARGUMENTS
!        --------------------
!        See lower #include.

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------
!      see below.

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS
!        Documentation about FULL-POS.

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 94-04-08

!     MODIFICATIONS.
!     --------------
!      R. El Khatib : 01-08-07 Pruning options
!      R. El Khatib : 02-21-20 Fullpos B-level distribution + remove IO scheme
!      R. El Khatib : 03-01-29 Remove SM aspects.
!      R. El Khatib : 03-04-17 Fullpos improvments
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      M.Hamrud      10-Jan-2004 CY28R1 Cleaning
!      K.Yessad : 27-02-2007  Optimisations of distributed memory in FULL-POS.
!      K. Yessad (oct 2010): multi-linear interpolations.
!      G.Mozdzynski (Feb 2011): OOPS cleaning, use of derived type TMWFPB and TCSGLEG
!      T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!      P.Marguinaud (Oct 2014) Initializations for PREP fields interpolations
!      R. El Khatib 27-Jul-2016 interpolations over C+I+E except for Surfex
!     ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMLUN   , ONLY : NULOUT
USE YOMCT0   , ONLY : LELAM
USE PARFPOS  , ONLY : JPROW
USE YOMFPC   , ONLY : TNAMFPINT, LTRACEFP, LALLOFP
USE YOMWFPB  , ONLY : TFPWSTD
USE YOMCST   , ONLY : RPI, RA
USE EINT_MOD , ONLY : SL_STRUCT
USE YOMFPGEO , ONLY : TFPGEO

!-----------------------------------------------------------------------------

IMPLICIT NONE

TYPE (TNAMFPINT),  INTENT(IN) :: YDNAMFPINT
TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO_DEP
TYPE (TFPWSTD), INTENT(INOUT) :: YDFPWSTD
TYPE(SL_STRUCT),   INTENT(IN) :: YDFPSTRUCT
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY

REAL(KIND=JPRB) :: ZDLAT(4,YDFPGEO_DEP%NFPROMA),ZDLO(0:3,4,YDFPGEO_DEP%NFPROMA)
REAL(KIND=JPRB) :: ZMSD

INTEGER(KIND=JPIM) :: ILAT(YDFPGEO_DEP%NFPROMA), ILON(YDFPGEO_DEP%NFPROMA)
INTEGER(KIND=JPIM) :: ILATA(YDFPGEO_DEP%NFPROMA), ILONA(YDFPGEO_DEP%NFPROMA)
INTEGER(KIND=JPIM) :: ILOS(YDFPGEO_DEP%NFPROMA)
INTEGER(KIND=JPIM) :: ILONN(YDFPGEO_DEP%NFPROMA), ILOSS(YDFPGEO_DEP%NFPROMA)
INTEGER(KIND=JPIM) :: IBINL, J, IEND, IOFF, JBLOC, IST, IFPROW

LOGICAL :: LLML, LLSTD00

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
#ifdef __INTEL_COMPILER
INTRINSIC :: SHAPE ! Fails with Intel compiler as it thinks we use ATLAS shape function
#endif


!-----------------------------------------------------------------------------

#include "suhow1.intfb.h"
#include "suhox1.intfb.h"
#include "fpscaw.intfb.h"
#include "fpscax.intfb.h"
#include "suhow2.intfb.h"
#include "suehow1.intfb.h"
#include "suehox1.intfb.h"
#include "suehow2.intfb.h"

!-----------------------------------------------------------------------------


IF (LHOOK) CALL DR_HOOK('SUFPWFPBUF',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM, &
 & YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP, YDCSGLEG=>YDGEOMETRY%YRCSGLEG, &
 & YDEGEO=>YDGEOMETRY%YREGEO)
ASSOCIATE(LFPML_STD=>YDNAMFPINT%LFPML_STD, RFPCR_STD=>YDNAMFPINT%RFPCR_STD, &
 & NFPSFXINT=>YDNAMFPINT%NFPSFXINT, NFPINDYN=>YDNAMFPINT%NFPINDYN, NFPINPHY=>YDNAMFPINT%NFPINPHY, &
 & LFPML_LAN=>YDNAMFPINT%LFPML_LAN, LFPML_SEA=>YDNAMFPINT%LFPML_SEA, &
 & NSLWIDE=>YDFPSTRUCT%NSLWIDE, NDGENH=>YDFPSTRUCT%NDGENH, NDGLG=>YDDIM%NDGLG, NDLON=>YDDIM%NDLON, &
 & NDGSAH=>YDFPSTRUCT%NDGSAH, NDGUXG=>YDDIM%NDGUXG, NDLUXG=>YDDIM%NDLUXG, &
 & EDELX=>YDEGEO%EDELX, EDELY=>YDEGEO%EDELY, RC2M1=>YDGEM%RC2M1, RC2P1=>YDGEM%RC2P1, RSTRET=>YDGEM%RSTRET, &
 & NLOENG=>YDGEM%NLOENG, R4JP=>YDGEM%R4JP, &
 & RFPLA_DEP=>YDFPGEO_DEP%RFPLA, RFPLO_DEP=>YDFPGEO_DEP%RFPLO, RFPGMS_DEP=>YDFPGEO_DEP%RFPGMS, NFPEND_DEP=>YDFPGEO_DEP%NFPEND, &
 & NFPRGPL_DEP=>YDFPGEO_DEP%NFPRGPL, NFPROMA_DEP=>YDFPGEO_DEP%NFPROMA, NFPBLOCS_DEP=>YDFPGEO_DEP%NFPBLOCS, &
 & NFRSTLOFF=>YDMP%NFRSTLOFF)
!-----------------------------------------------------------------------------

! 2. Compute adresses
!    ----------------

ALLOCATE(YDFPWSTD%ML0(NFPROMA_DEP,2*JPROW,NFPBLOCS_DEP))
IF (LALLOFP) THEN
  WRITE(NULOUT,9990) 'ML0      ',SIZE(YDFPWSTD%ML0),SHAPE(YDFPWSTD%ML0)
ENDIF
IF (NFPSFXINT > 0) THEN
  ALLOCATE(YDFPWSTD%MS1(NFPROMA_DEP,2*NSLWIDE,NFPBLOCS_DEP))
  IF (LALLOFP) THEN
    WRITE(NULOUT,9990) 'YDFPWSTD%MS1    ',SIZE(YDFPWSTD%MS1),SHAPE(YDFPWSTD%MS1)
  ENDIF
ENDIF

LLML=LFPML_STD .OR. LFPML_LAN .OR. LFPML_SEA


! 3. Setup general switches for the choice of weights computation
!    ------------------------------------------------------------

! Standard weights
         LLSTD00 = (NFPINPHY ==  0 .OR. NFPINDYN ==  0)
YDFPWSTD%LWSTD12 = (NFPINPHY == 12 .OR. NFPINDYN == 12)
! linear weight if no quadratic interpolations but nearest point
YDFPWSTD%LWSTD04 = (NFPINPHY ==  4 .OR. NFPINDYN ==  4) .OR. (LLSTD00 .AND. .NOT.YDFPWSTD%LWSTD12)

IF(LTRACEFP) THEN
  WRITE(UNIT=NULOUT,FMT='('' YDFPWSTD%LWSTD04 = '',L2)') YDFPWSTD%LWSTD04
  WRITE(UNIT=NULOUT,FMT='('' YDFPWSTD%LWSTD12 = '',L2)') YDFPWSTD%LWSTD12
ENDIF


! 4. Compute standard weights
!    ------------------------

ALLOCATE(YDFPWSTD%WSTDML(NFPROMA_DEP,5:16,NFPBLOCS_DEP))
IF (LALLOFP) THEN
  WRITE(NULOUT,9990) 'YDFPWSTD%WSTDML   ',SIZE(YDFPWSTD%WSTDML(:,5:16,JBLOC)),SHAPE(YDFPWSTD%WSTDML(:,5:16,JBLOC))
ENDIF
IF (YDFPWSTD%LWSTD12) THEN
  WRITE (NULOUT,*) ' SUFPWFPBUF: weights STD12 computed'
  IBINL=12
  ALLOCATE(YDFPWSTD%WSTD12(NFPROMA_DEP,IBINL,NFPBLOCS_DEP))
  IF (LALLOFP) THEN
    WRITE(NULOUT,9990) 'YDFPWSTD%WSTD12   ',SIZE(YDFPWSTD%WSTD12),SHAPE(YDFPWSTD%WSTD12)
  ENDIF
ENDIF
IF (YDFPWSTD%LWSTD04) THEN
  WRITE (NULOUT,*) ' SUFPWFPBUF: weights STD04 computed'
  IBINL=4
  ALLOCATE(YDFPWSTD%WSTD04(NFPROMA_DEP,IBINL,NFPBLOCS_DEP))
  IF (LALLOFP) THEN
    WRITE(NULOUT,9990) 'YDFPWSTD%WSTD04   ',SIZE(YDFPWSTD%WSTD04),SHAPE(YDFPWSTD%WSTD04)
  ENDIF
ENDIF


ALLOCATE(YDFPWSTD%RINVGMS(NFPRGPL_DEP))
IF (LALLOFP) THEN
  WRITE(NULOUT,9990) 'YDFPWSTD%RINVGMS   ',SIZE(YDFPWSTD%RINVGMS),SHAPE(YDFPWSTD%RINVGMS)
ENDIF

! 4.1 For quadratic interpolations + possibly multilinear interpolations

IF (LLML) THEN
  IF (LELAM) THEN
    ZMSD=SQRT(0.5_JPRB*(EDELX*EDELX+EDELY*EDELY))
  ELSE
    ZMSD=RPI*RA/REAL(NDGLG,JPRB)
  ENDIF
ENDIF

IFPROW=SIZE(YDFPWSTD%ML0,DIM=2)

!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(JBLOC,IEND,IOFF,IBINL,J,ZDLAT,ZDLO,ILAT,ILONN,ILON,ILOS,ILOSS,ILATA,ILONA)
DO JBLOC=1,NFPBLOCS_DEP

! 2.1  Adressing

  IST=1
  IEND=NFPEND_DEP(JBLOC)
  IOFF=(JBLOC-1)*NFPROMA_DEP

  IBINL=0 ! cheap (?)
  IF (LELAM) THEN
    CALL SUEHOW1(NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,IBINL,LLML,RFPLA_DEP(IOFF+1),RFPLO_DEP(IOFF+1),EDELX,EDELY,NDLON,NDGLG, &
     & ILAT,ILON,ILONN,ILOS,ILOSS,ZDLAT,ZDLO(0,1,1))
    IF (NFPSFXINT > 0) THEN
      CALL SUEHOX1(NSLWIDE,NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,RFPLA_DEP(IOFF+1),RFPLO_DEP(IOFF+1),&
       & EDELX,EDELY,1,NDLUXG,1,NDGUXG,ILATA,ILONA)
    ENDIF 
  ELSE
    CALL SUHOW1(NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,R4JP,RPI,NLOENG(NDGSAH+NFRSTLOFF:),YDCSGLEG%RLATIG(NDGSAH+NFRSTLOFF:), &
     & IBINL,LLML,RFPLA_DEP(IOFF+1),RFPLO_DEP(IOFF+1),ILAT,ILON,ILONN,ILOS,ILOSS,ZDLAT,ZDLO(0,1,1))
    IF (NFPSFXINT > 0) THEN
      CALL SUHOX1(NSLWIDE,NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,R4JP,RPI,NLOENG(NDGSAH+NFRSTLOFF), &
       & YDCSGLEG%RLATIG(NDGSAH+NFRSTLOFF:),RFPLA_DEP(IOFF+1),RFPLO_DEP(IOFF+1),ILATA,ILONA)
    ENDIF
  ENDIF

  CALL FPSCAW(YDFPSTRUCT,NFPROMA_DEP,IST,IEND,IFPROW,ILAT,ILONN,ILON,ILOS,ILOSS,YDFPWSTD%ML0(:,:,JBLOC))
  IF (NFPSFXINT > 0) THEN
    CALL FPSCAX(YDFPSTRUCT,NFPROMA_DEP,IST,IEND,ILATA,ILONA,YDFPWSTD%MS1(:,:,JBLOC))  
  ENDIF

IF (LLML) THEN
  ! * departure grid: 1/(local geographic mesh-size).
  IF (LELAM) THEN
    YDFPWSTD%RINVGMS(IOFF+1:IOFF+IEND)=1._JPRB/ZMSD
  ELSE
    DO J=IOFF+1,IOFF+IEND
      YDFPWSTD%RINVGMS(J)=(RC2P1+RC2M1*SIN(YDFPGEO_DEP%RFPLA(J)))/(2._JPRB*RSTRET*ZMSD)
    ENDDO
  ENDIF
ENDIF

IF (YDFPWSTD%LWSTD12) THEN
  IBINL=12
  IF (LELAM) THEN
    CALL SUEHOW2(NFPROMA_DEP,IEND,RFPCR_STD,YDFPWSTD%RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),IBINL,LFPML_STD,&
     & ZDLAT,ZDLO(0,1,1),EDELY,YDFPWSTD%WSTD12(:,:,JBLOC),YDFPWSTD%WSTDML(:,5:16,JBLOC))   
  ELSE
    CALL SUHOW2(NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,RFPCR_STD,&
     & YDCSGLEG%RLATIG(NDGSAH+NFRSTLOFF:),YDFPWSTD%RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),IBINL,LFPML_STD,ILAT,&
     & ZDLAT,ZDLO(0,1,1),YDFPWSTD%WSTD12(:,:,JBLOC),YDFPWSTD%WSTDML(:,5:16,JBLOC))
  ENDIF
ENDIF

! 4.2 For bilinear interpolations or possibly multilinear interpolations

IF (YDFPWSTD%LWSTD04) THEN
  IBINL=4
  IF (LELAM) THEN
    CALL SUEHOW2(NFPROMA_DEP,IEND,RFPCR_STD,YDFPWSTD%RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),IBINL,LFPML_STD,&
     & ZDLAT,ZDLO(0,1,1),EDELY,YDFPWSTD%WSTD04(:,:,JBLOC),YDFPWSTD%WSTDML(:,5:16,JBLOC))  
  ELSE
    CALL SUHOW2(NDGSAH,NDGENH,NFRSTLOFF,NFPROMA_DEP,IEND,RFPCR_STD,&
     & YDCSGLEG%RLATIG(NDGSAH+NFRSTLOFF:),YDFPWSTD%RINVGMS(IOFF+1),RFPGMS_DEP(IOFF+1),IBINL,LFPML_STD,ILAT,&
     & ZDLAT,ZDLO(0,1,1),YDFPWSTD%WSTD04(:,:,JBLOC),YDFPWSTD%WSTDML(:,5:16,JBLOC))
  ENDIF
ENDIF

ENDDO
!$OMP END PARALLEL DO

IF (LLML) THEN
  WRITE (NULOUT,*) ' SUFPWFPBUF: max ratio DX_arr/DX_dep:',MAXVAL(YDFPWSTD%RINVGMS*YDFPGEO_DEP%RFPGMS)
  WRITE (NULOUT,*) ' SUFPWFPBUF: min ratio DX_arr/DX_dep:',MINVAL(YDFPWSTD%RINVGMS*YDFPGEO_DEP%RFPGMS)
ENDIF

9990 FORMAT(1X,'ARRAY ',A10,' ALLOCATED ',8I8)

!-----------------------------------------------------------------------------


END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPWFPBUF',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPWFPBUF
