! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPOPH(KFPSURFEX,CDFPFN,CDFPCLIFNAME,CDFPSFXFNAME,YDFPUSERGEO,YDVAB,YDFPOPH,YDFPOFN)

!**** *SUFPOPH*  - INITIALIZE POST-PROCESSING FILE-HANDLING PARAMETERS

!     PURPOSE.
!     --------
!        INITIALIZE COMMON YOMFPOP WHICH CONTAINS POST-PROCESSING
!            FA FILE-HANDLING PARAMETERS

!**   INTERFACE.
!     ----------
!       *CALL* *SUFPOPH*

!        EXPLICIT ARGUMENTS
!        --------------------

!          CDFPFN       : partial output filenames (filenames without extensions)
!          CDFPCLIFNAME : filename of climatology file on target geometry
!          CDFPSFXFNAME : filename of surfex climatology file on target geometries
!          YDFPOFN      : partial output filename (filename without time stamp)

!        IMPLICIT ARGUMENTS
!        --------------------
!        YOMFPOP
!        YOMFPC

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 94-04-08

!     MODIFICATIONS.
!     --------------
!      M. Janousek : 01-04-14 : New domain and projection parameters
!      R. El Khatib : 01-08-07 Pruning options
!      R. El Khatib : 02-09-03 Fix for aladin 2D model
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      JD. GRIL 10-02-2005 Add flag for Mercator Rotated/Tilted
!      Daan Degrauwe: Feb 2012 Boyd biperiodization         
!      R. El Khatib : YDFPUSERGEO%NFPMEN computation moved here
!      R. El Khatib : 05-Sep-2012 New E-zone management
!      R. El Khatib 27-Sep-2013 Boyd window in frame
!      R. El Khatib 04-Aug-2014 Pruning of the conf. 927/928 + remove sunmen
!      R. El Khatib 13-Oct-2017 make ZRPK local (only its sign is tested, anyway) 
!      R. El Khatib 03-Sep-2018 Support for multi-object against FA software
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMLUN   , ONLY : NULOUT
USE YOMFPC        , ONLY : LTRACEFP
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
USE TYPE_FAOPH, ONLY : TFAOPH
USE TYPE_FPOFN, ONLY : TFPOFN
USE YOMCST   , ONLY : RPI      ,RA
USE YOMVERT  , ONLY : VP00     ,TVAB
USE FA_MOD,    ONLY : JPPRCM

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN) :: KFPSURFEX
CHARACTER(LEN=*),  INTENT(IN) :: CDFPFN
CHARACTER(LEN=*),  INTENT(IN) :: CDFPCLIFNAME
CHARACTER(LEN=*),  INTENT(IN) :: CDFPSFXFNAME
TYPE (TFPUSERGEO), INTENT(IN) :: YDFPUSERGEO
TYPE (TVAB)      , INTENT(IN) :: YDVAB
TYPE (TFAOPH),     INTENT(INOUT) :: YDFPOPH
TYPE (TFPOFN),     INTENT(INOUT) :: YDFPOFN


INTEGER(KIND=JPIM) :: ISTRON, ITRONC, ILEV, IULOUT
INTEGER(KIND=JPIM) :: IBWX, IBWY, IREP
INTEGER(KIND=JPIM) :: ILON, ILAT, ILUX, IGUX, JJ, IGIVO, ISOTRP, IST1

LOGICAL, PARAMETER :: LLPGARD=.TRUE.
LOGICAL :: LLFPMRT

REAL(KIND=JPRB) :: ZLAT0, ZLATN, ZLATC, ZLATS, ZLON0, ZLONE, ZLONC, ZLONW, ZXWN, ZYWN
REAL(KIND=JPRB) :: ZDELX, ZDELY, ZRPK, ZBETA, Z180SPI, ZLATR, ZLONR
REAL(KIND=JPRB) :: ZDUM(YDFPUSERGEO%NFPLUX*YDFPUSERGEO%NFPGUX)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "sueframe.intfb.h"
#include "suframe.intfb.h"
#include "eggx_n.h"

IF (LHOOK) CALL DR_HOOK('SUFPOPH',0,ZHOOK_HANDLE)
ASSOCIATE(VALH=>YDVAB%VALH,VBH=>YDVAB%VBH,&
 & NFPSIZEG=>YDFPUSERGEO%NFPSIZEG, NSPEC2G=>YDFPUSERGEO%NSPEC2G, &
 & NFPMAX=>YDFPUSERGEO%NFPMAX, NMFPMAX=>YDFPUSERGEO%NMFPMAX, &
 & NLAT=>YDFPUSERGEO%NLAT, NLON=>YDFPUSERGEO%NLON, NFPLUX=>YDFPUSERGEO%NFPLUX, &
 & NFPTTYP=>YDFPUSERGEO%NFPTTYP, FPMUCEN=>YDFPUSERGEO%FPMUCEN, &
 & FPLOCEN=>YDFPUSERGEO%FPLOCEN, FPSTRET=>YDFPUSERGEO%FPSTRET, FPLX=>YDFPUSERGEO%FPLX, &
 & FPLY=>YDFPUSERGEO%FPLY, FPLON0=>YDFPUSERGEO%FPLON0, FPLAT0=>YDFPUSERGEO%FPLAT0, &
 & LFPMAP=>YDFPUSERGEO%LFPMAP, LFPMRT=>YDFPUSERGEO%LFPMRT, &
 & NFPGUX=>YDFPUSERGEO%NFPGUX, RLATC=>YDFPUSERGEO%RLATC, RLONC=>YDFPUSERGEO%RLONC, &
 & RDELX=>YDFPUSERGEO%RDELX, RDELY=>YDFPUSERGEO%RDELY, NFPBWX=>YDFPUSERGEO%NFPBWX, &
 & NFPBZONL=>YDFPUSERGEO%NFPBZONL, NFPBZONG=>YDFPUSERGEO%NFPBZONG, NFPEDOM=>YDFPUSERGEO%NFPEDOM, &
 & NFPBWY=>YDFPUSERGEO%NFPBWY, CFPGRID=>YDFPUSERGEO%CFPGRID, CFPDOM=>YDFPUSERGEO%CFPDOM)


ILEV=UBOUND(YDVAB%VBH,DIM=1)

! memory adress in hexadecimal to enable any 64 bits adressing of any frame object
WRITE(UNIT=YDFPOPH%CFPCA,FMT='(Z16)') LOC(YDFPOPH%CFPCA)

!       INITIALISE OUTPUT FRAME OF FILE *ARPEGE*

IF (CFPGRID == 'GAUSS') THEN
  CALL SUFRAME(YDFPOPH%CFPCA,FPMUCEN,FPLOCEN,FPSTRET,NFPTTYP,NFPMAX,NLAT,NLON,YDFPUSERGEO%NFPRGRI, &
   & YDFPUSERGEO%NFPMEN,REAL(YDFPUSERGEO%FPMU,JPRB),LLPGARD,ILEV,VP00,VALH,VBH)  

!       INITIALISE OUTPUT FRAME OF FILE *ALADIN*

ELSEIF (CFPGRID == 'LELAM') THEN
  ZLONC=RLONC*RPI/180._JPRB
  ZLATC=RLATC*RPI/180._JPRB
  ZLON0=FPLON0*RPI/180._JPRB
  ZLAT0=FPLAT0*RPI/180._JPRB
  LLFPMRT=LFPMRT
  JJ=-1
  IF (LFPMRT) THEN
    JJ=JJ-1
  ENDIF
  IF (LFPMAP) THEN
    ZRPK=HUGE(1._JPRB)
    ! will be recomputed by eggx
  ELSE
    ZRPK=-9._JPRB
  ENDIF
  ZBETA=0._JPRB
  IGIVO=0_JPIM
  ISOTRP=0_JPIM
  IST1=1
  ZDELX=RDELX
  ZDELY=RDELY
  IULOUT=-NULOUT ! to disable verbosity
  CALL EGGX_N(RPI,RA,JJ,ZLONR,ZLATR,ZBETA,ZLONW,ZLATS,ZLONE,ZLATN,ZLON0,ZLAT0,&
   & ZRPK,IULOUT,ISOTRP,IGIVO,ZDUM,ZDUM,ZDUM,ZDUM,ZDUM,IST1,NFPLUX,IST1,NFPGUX,&
   & IST1,NFPLUX,IST1,NFPGUX,ZDELX,ZDELY,ZLONC,ZLATC)
  Z180SPI=180._JPRB/RPI
  ZLATN = ZLATN * Z180SPI
  ZLATS = ZLATS * Z180SPI
  ZLONE = ZLONE * Z180SPI
  ZLONW = ZLONW * Z180SPI
  IF (ZLONE < ZLONW) THEN
    ZLONW=ZLONW-360._JPRB
  ENDIF
  IF(LTRACEFP) THEN
    WRITE(UNIT=NULOUT,FMT='('' RLATN(deg) = '',F8.2,'' RLATS(deg) = '',F8.2, &
     & '' RLONW(deg) = '',F8.2,'' RLONE(deg) = '',F8.2)') ZLATN,ZLATS,ZLONW,ZLONE
  ENDIF
  ZLATN=ZLATN*RPI/180._JPRB
  ZLATS=ZLATS*RPI/180._JPRB
  ZLONE=ZLONE*RPI/180._JPRB
  ZLONW=ZLONW*RPI/180._JPRB
  ZXWN=2.0_JPRB*RPI/FPLX
  ZYWN=2.0_JPRB*RPI/FPLY
  ISTRON=MAX(0,MIN(11,NMFPMAX,NFPMAX)-1)
  ILON=NLON
  ILAT=NLAT
  ILUX=NFPLUX
  IGUX=NFPGUX
  IBWX=NFPBWX
  IBWY=NFPBWY
  CALL SUEFRAME(YDFPOPH%CFPCA,LFPMAP,NMFPMAX,NFPMAX,ILAT,ILON,LLPGARD,LLFPMRT,ZLON0,ZLAT0, &
   & ZLONC,ZLATC,RDELX,RDELY,ZLONW,ZLATS,ZLONE,ZLATN,ZRPK,FPLX,FPLY,ZXWN,ZYWN,1, &
   & ILUX,1,IGUX,NFPBZONL,NFPBZONG,ILEV,VP00,VALH,VBH,NFPEDOM,ISTRON,IBWX,IBWY)

!       INITIALISE OUTPUT FRAMES OF FILE *LATLON*

ELSE
  ZLONC=RLONC*RPI/180._JPRB
  ZLATC=RLATC*RPI/180._JPRB
  ZDELX=RDELX*RPI/180._JPRB
  ZDELY=RDELY*RPI/180._JPRB
  ZLATS=RLATC-RDELY*0.5_JPRB*REAL(NLAT-1,JPRB)
  ZLATN=RLATC+RDELY*0.5_JPRB*REAL(NLAT-1,JPRB)
  ZLONW=MOD(RLONC-RDELX*0.5_JPRB*REAL(NLON-1,JPRB),360._JPRB)
  IF (ZLONW >= 360._JPRB) ZLONW=ZLONW-360._JPRB
  ZLONE=MOD(RLONC+RDELX*0.5_JPRB*REAL(NLON-1,JPRB),360._JPRB)
  IF (ZLONE >= 360._JPRB) ZLONE=ZLONE-360._JPRB
  IF(LTRACEFP) THEN
    WRITE(UNIT=NULOUT,FMT='('' RLATN(deg) = '',F8.2,'' RLATS(deg) = '',F8.2, &
     & '' RLONW(deg) = '',F8.2,'' RLONE(deg) = '',F8.2)') ZLATN,ZLATS,ZLONW,ZLONE
  ENDIF
  ZLATN=ZLATN*RPI/180._JPRB
  ZLATS=ZLATS*RPI/180._JPRB
  ZLONE=ZLONE*RPI/180._JPRB
  ZLONW=ZLONW*RPI/180._JPRB
  ZLON0=FPLON0*RPI/180._JPRB
  ZLAT0=FPLAT0*RPI/180._JPRB
  LLFPMRT=.FALSE.
  ZXWN=0._JPRB
  ZYWN=0._JPRB
  ITRONC=11 ! arbitrary values since there are no spectral fields in
  ISTRON=10 ! such files
  IBWX=NFPBWX
  IBWY=NFPBWY
  ZRPK=-9._JPRB
  CALL SUEFRAME(YDFPOPH%CFPCA,LFPMAP,ITRONC,ITRONC,NLAT,NLON,LLPGARD,LLFPMRT,ZLON0,ZLAT0, &
   & ZLONC,ZLATC,ZDELX,ZDELY,ZLONW,ZLATS,ZLONE,ZLATN,ZRPK,FPLX,FPLY,ZXWN,ZYWN, &
   & 1,NLON,1,NLAT,NFPBZONL,NFPBZONG,ILEV,VP00,VALH,VBH,NFPEDOM,ISTRON,IBWX,IBWY)
ENDIF

CALL FASGRA (IREP, YDFPOPH%CFPCA , YDFPOPH%NHEADMAX)
YDFPOPH%NHEADMAX = JPPRCM*YDFPOPH%NHEADMAX
YDFPOPH%NGPSIZPK = NFPSIZEG + YDFPOPH%NHEADMAX ! See FACOND for justification
YDFPOPH%NSPSIZPK = NSPEC2G  + YDFPOPH%NHEADMAX ! See FACOND for justification

YDFPOFN%CSH=CDFPFN
YDFPOFN%CGG=CDFPFN
YDFPOFN%CUA=CDFPFN
YDFPOFN%CSX=CDFPFN

! traditional clim filename in output geometry
YDFPOFN%CLI=CDFPCLIFNAME
! input Surfex clim filename in output geometry
YDFPOFN%CSU=CDFPSFXFNAME

WRITE(NULOUT,FMT='('' OUTPUT FILENAME ROOT = '',A)') TRIM(CDFPFN)
WRITE(NULOUT,FMT='('' CLIMATOLOGY FILENAME ON TARGET GEOMETRY : '',A)') TRIM(CDFPCLIFNAME)
IF (KFPSURFEX > 0) THEN
  WRITE(NULOUT,FMT='('' SURFEX CLIMATOLOGY FILENAME ON TARGET GEOMETRY : '',A)') TRIM(CDFPSFXFNAME)
ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPOPH',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPOPH
