! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPFIELDS(YDNAMFPL,KFLEVG,KLEVSNOW,YDFPFIELDS,YDFPVAB,LDPRINT)

!**** *SUFPFIELDS*  - INITIALIZE POST-PROCESSED FIELDS LIST FOR FULLPOS

!     PURPOSE.
!     --------
!        ALLOCATE AND FILL THE STRUCTURE OF POST-PROCESSED FIELDS FROM THE NAMELIST VARIABLES

!**   INTERFACE.
!     ----------
!       *CALL* *SUFPFIELDS

!        EXPLICIT ARGUMENTS
!        ------------------
!           YDFPFIELDS : post-precessed fields structure
!           LDPRINT    : .TRUE. to printout the structure content
!           CDPATH - PATH NAME OF NAMELIST FILE
!                    IF CDPATH IS ABSENT, FILE NULNAM IS READ


!        IMPLICIT ARGUMENTS
!        ------------------

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 07-Mar-2017

!     MODIFICATIONS.
!     --------------
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMLUN   , ONLY : NULOUT
USE YOMCT0   , ONLY : LARPEGEF
USE YOM_GRIB_CODES  , ONLY : NGRBCLBT, NGRBCSBT, &
                           & NGRBSD, NGRBRSN, NGRBTSN, NGRBWSN
USE TYPE_FPFIELDS, ONLY : TFPFIELDS, ALLOC_FPFIELDS, PRINT_FPFIELDS
USE YOMFPC  , ONLY : TNAMFPL
USE YOMVERT , ONLY : TVAB
USE YOMSATSIM, ONLY : NSATSIM

IMPLICIT NONE

TYPE(TNAMFPL)     ,INTENT(IN) :: YDNAMFPL
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEVG
INTEGER(KIND=JPIM),INTENT(IN) :: KLEVSNOW
TYPE(TFPFIELDS)  ,INTENT(OUT) :: YDFPFIELDS
TYPE(TVAB)        ,INTENT(IN), OPTIONAL :: YDFPVAB
LOGICAL           ,INTENT(IN), OPTIONAL :: LDPRINT


INTEGER(KIND=JPIM) :: J, IERR
LOGICAL :: LLPRINT

INTEGER(KIND=JPIM) :: IFLD, JFLD, JSAT, JSNOW
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUFPFIELDS',0,ZHOOK_HANDLE)
ASSOCIATE(RFP3P=>YDNAMFPL%RFP3P, RFP3H=>YDNAMFPL%RFP3H, RFP3TH=>YDNAMFPL%RFP3TH, &
 & RFP3PV=>YDNAMFPL%RFP3PV, RFP3I=>YDNAMFPL%RFP3I, RFP3F=>YDNAMFPL%RFP3F, &
 & NRFP3S=>YDNAMFPL%NRFP3S, NFP3DFP=>YDNAMFPL%NFP3DFP, NFP3DFH=>YDNAMFPL%NFP3DFH, &
 & NFP3DFT=>YDNAMFPL%NFP3DFT, NFP3DFV=>YDNAMFPL%NFP3DFV, NFP3DFI=>YDNAMFPL%NFP3DFI, &
 & NFP3DFF=>YDNAMFPL%NFP3DFF, NFP3DFS=>YDNAMFPL%NFP3DFS, MFP3DFP=>YDNAMFPL%MFP3DFP, &
 & MFP3DFH=>YDNAMFPL%MFP3DFH, MFP3DFT=>YDNAMFPL%MFP3DFT, MFP3DFV=>YDNAMFPL%MFP3DFV, &
 & MFP3DFI=>YDNAMFPL%MFP3DFI, MFP3DFF=>YDNAMFPL%MFP3DFF, MFP3DFS=>YDNAMFPL%MFP3DFS, &
 & CFP3DF=>YDNAMFPL%CFP3DF, CFP2DF=>YDNAMFPL%CFP2DF, MFP2DF=>YDNAMFPL%MFP2DF, &
 & NFP2DF=>YDNAMFPL%NFP2DF, CFPCFU=>YDNAMFPL%CFPCFU, CFPXFU=>YDNAMFPL%CFPXFU, &
 & CFPPHY=>YDNAMFPL%CFPPHY, MFPPHY=>YDNAMFPL%MFPPHY, NFPPHY=>YDNAMFPL%NFPPHY)

IF (LARPEGEF) THEN
  DO J=1,SIZE(CFP2DF)
    IF (CFP2DF(J) == ' ') EXIT
  ENDDO
  YDFPFIELDS%NFP2DF=J-1
  DO J=1,SIZE(CFP3DF)
    IF (CFP3DF(J) == ' ') EXIT
  ENDDO
  YDFPFIELDS%NFP3DF=J-1
  DO J=1,SIZE(CFPCFU)
    IF (CFPCFU(J) == ' ') EXIT
  ENDDO
  YDFPFIELDS%NFPCFU=J-1
  DO J=1,SIZE(CFPXFU)
    IF (CFPXFU(J) == ' ') EXIT
  ENDDO
  YDFPFIELDS%NFPXFU=J-1
  DO J=1,SIZE(CFPPHY)
    IF (CFPPHY(J) == ' ') EXIT
  ENDDO
  YDFPFIELDS%NFPPHY=J-1
! needed by sualfpos etc
  YDFPFIELDS%NFP3DFS = YDFPFIELDS%NFP3DF
  YDFPFIELDS%NFP3DFP = YDFPFIELDS%NFP3DF
  YDFPFIELDS%NFP3DFH = YDFPFIELDS%NFP3DF
  YDFPFIELDS%NFP3DFT = YDFPFIELDS%NFP3DF
  YDFPFIELDS%NFP3DFV = YDFPFIELDS%NFP3DF
  YDFPFIELDS%NFP3DFI = YDFPFIELDS%NFP3DF
  YDFPFIELDS%NFP3DFF = YDFPFIELDS%NFP3DF
ELSE
  YDFPFIELDS%NFP2DF  = NFP2DF
  YDFPFIELDS%NFP3DF  = 0
  YDFPFIELDS%NFPCFU  = 0
  YDFPFIELDS%NFPXFU  = 0
  YDFPFIELDS%NFPPHY  = NFPPHY
  YDFPFIELDS%NFP3DFS = NFP3DFS
  YDFPFIELDS%NFP3DFP = NFP3DFP
  YDFPFIELDS%NFP3DFH = NFP3DFH
  YDFPFIELDS%NFP3DFT = NFP3DFT
  YDFPFIELDS%NFP3DFV = NFP3DFV
  YDFPFIELDS%NFP3DFI = NFP3DFI
  YDFPFIELDS%NFP3DFF = NFP3DFF
  YDFPFIELDS%NFPCFU  = 0
  YDFPFIELDS%NFPXFU  = 0
  IF (NSATSIM > 0) THEN
    ! Repeat grib codes for each satellite/channel of simulated satellite images
    DO JFLD = 1, NFPPHY
      IF (MFPPHY(JFLD) == NGRBCLBT .OR. MFPPHY(JFLD) == NGRBCSBT) &
       & YDFPFIELDS%NFPPHY = YDFPFIELDS%NFPPHY + (NSATSIM - 1)
    ENDDO
  ENDIF
! Snow multi-layer
  IF (KLEVSNOW > 0) THEN
    ! Repeat grib codes for each snow field for KLEVSN times
    DO JFLD = 1, NFPPHY
      IF (MFPPHY(JFLD) == NGRBSD .OR. MFPPHY(JFLD) == NGRBWSN) THEN
           YDFPFIELDS%NFPPHY = YDFPFIELDS%NFPPHY + (KLEVSNOW - 1)
      ENDIF
    ! Repeat grib codes for each snow field for KLEVSN+1 times (+1 for
    ! single-layer diagnostic output
      IF (MFPPHY(JFLD) == NGRBRSN .OR. MFPPHY(JFLD) == NGRBTSN) THEN
           YDFPFIELDS%NFPPHY = YDFPFIELDS%NFPPHY + (KLEVSNOW)
      ENDIF
    ENDDO
  ENDIF
ENDIF

DO J=1,SIZE(RFP3P)
  IF (RFP3P(J) < 0.0_JPRB) EXIT
ENDDO
YDFPFIELDS%NFP3P=(J-1)*MIN(1,YDFPFIELDS%NFP3DFP)
DO J=1,SIZE(RFP3H)
  IF (RFP3H(J) < 0.0_JPRB) EXIT
ENDDO
YDFPFIELDS%NFP3H=(J-1)*MIN(1,YDFPFIELDS%NFP3DFH)
DO J=1,SIZE(RFP3TH)
  IF (RFP3TH(J) < 0.0_JPRB) EXIT
ENDDO
YDFPFIELDS%NFP3TH=(J-1)*MIN(1,YDFPFIELDS%NFP3DFT)
DO J=1,SIZE(RFP3PV)
  IF (RFP3PV(J) >= 100000._JPRB) EXIT
ENDDO
YDFPFIELDS%NFP3PV=(J-1)*MIN(1,YDFPFIELDS%NFP3DFV)
DO J=1,SIZE(RFP3I)
  IF (RFP3I(J) < -999_JPRB) EXIT
ENDDO
YDFPFIELDS%NFP3I=(J-1)*MIN(1,YDFPFIELDS%NFP3DFI)

! a trick : first value flagged -99 means: generate all model levels
IF (NRFP3S(1) == -99 ) THEN
  YDFPFIELDS%NFP3S=KFLEVG*MIN(1,YDFPFIELDS%NFP3DFS)
ELSE
  DO J=1,SIZE(NRFP3S)
    IF (NRFP3S(J) < 0) EXIT
  ENDDO
  YDFPFIELDS%NFP3S=(J-1)*MIN(1,YDFPFIELDS%NFP3DFS)
ENDIF

DO J=1,SIZE(RFP3F)
  IF (RFP3F(J) < 0.0_JPRB) EXIT
ENDDO
YDFPFIELDS%NFP3F=(J-1)*MIN(1,YDFPFIELDS%NFP3DFF)

CALL ALLOC_FPFIELDS(YDFPFIELDS)

YDFPFIELDS%RFP3P (:)=RFP3P (1:YDFPFIELDS%NFP3P)
YDFPFIELDS%RFP3H (:)=RFP3H (1:YDFPFIELDS%NFP3H)
YDFPFIELDS%RFP3TH(:)=RFP3TH(1:YDFPFIELDS%NFP3TH)
YDFPFIELDS%RFP3PV(:)=RFP3PV(1:YDFPFIELDS%NFP3PV)
YDFPFIELDS%RFP3I (:)=RFP3I (1:YDFPFIELDS%NFP3I)
YDFPFIELDS%RFP3F (:)=RFP3F (1:YDFPFIELDS%NFP3F)
! a trick : first value flagged -99 means: generate all model levels
IF (NRFP3S(1) == -99 ) THEN
  DO J=1,KFLEVG
    YDFPFIELDS%NRFP3S(J)=J
  ENDDO
ELSE
  YDFPFIELDS%NRFP3S(:)=NRFP3S(1:YDFPFIELDS%NFP3S)
ENDIF

IF (LARPEGEF) THEN

  YDFPFIELDS%CFP3DF(:)=CFP3DF(1:YDFPFIELDS%NFP3DF)
  YDFPFIELDS%CFP2DF(:)=CFP2DF(1:YDFPFIELDS%NFP2DF)
  YDFPFIELDS%CFPPHY(:)=CFPPHY(1:YDFPFIELDS%NFPPHY)
  YDFPFIELDS%CFPCFU(:)=CFPCFU(1:YDFPFIELDS%NFPCFU)
  YDFPFIELDS%CFPXFU(:)=CFPXFU(1:YDFPFIELDS%NFPXFU)

ELSE

  YDFPFIELDS%MFP3DFS(:)=MFP3DFS(1:YDFPFIELDS%NFP3DFS)
  YDFPFIELDS%MFP3DFP(:)=MFP3DFP(1:YDFPFIELDS%NFP3DFP)
  YDFPFIELDS%MFP3DFH(:)=MFP3DFH(1:YDFPFIELDS%NFP3DFH)
  YDFPFIELDS%MFP3DFT(:)=MFP3DFT(1:YDFPFIELDS%NFP3DFT)
  YDFPFIELDS%MFP3DFV(:)=MFP3DFV(1:YDFPFIELDS%NFP3DFV)
  YDFPFIELDS%MFP3DFI(:)=MFP3DFI(1:YDFPFIELDS%NFP3DFI)
  YDFPFIELDS%MFP3DFF(:)=MFP3DFF(1:YDFPFIELDS%NFP3DFF)
  YDFPFIELDS%MFP2DF (:)=MFP2DF (1:YDFPFIELDS%NFP2DF)
  ! Repeat grib codes for each satellite/channel of simulated satellite images
  IFLD = 0
  DO JFLD = 1, NFPPHY
    IFLD = IFLD + 1
    YDFPFIELDS%MFPPHY(IFLD)=MFPPHY(JFLD)
    IF (MFPPHY(JFLD) == NGRBCLBT .OR. MFPPHY(JFLD) == NGRBCSBT) THEN
      DO JSAT = 1, NSATSIM-1
        IFLD = IFLD + 1
        YDFPFIELDS%MFPPHY(IFLD)=MFPPHY(JFLD)
      ENDDO
    ENDIF
!!ENDDO
!!  IFLD = 0
! Fill the grib codes for each layer of snow with same grib code..
!!  DO JFLD = 1, NFPPHY
!!  IFLD = IFLD + 1
!!  YDFPFIELDS%MFPPHY(IFLD)=MFPPHY(JFLD)
    IF (MFPPHY(JFLD) == NGRBSD .OR. MFPPHY(JFLD) == NGRBWSN) THEN
      DO JSNOW = 1, KLEVSNOW-1
        IFLD = IFLD + 1
        YDFPFIELDS%MFPPHY(IFLD)=MFPPHY(JFLD)
      ENDDO
    ENDIF
    ! add one extra field to output single-layer values
    IF (MFPPHY(JFLD) == NGRBRSN .OR. MFPPHY(JFLD) == NGRBTSN) THEN
      DO JSNOW = 1, KLEVSNOW
        IFLD = IFLD + 1
        YDFPFIELDS%MFPPHY(IFLD)=MFPPHY(JFLD)
      ENDDO
    ENDIF
  ENDDO
ENDIF

IF (PRESENT(LDPRINT)) THEN
  LLPRINT=LDPRINT
ELSE
  LLPRINT=.TRUE.
ENDIF
IF (LLPRINT) THEN
  WRITE(UNIT=NULOUT,FMT='('' STRUCTURE YDFPFIELDS'')')
  CALL PRINT_FPFIELDS(YDFPFIELDS,LARPEGEF,NULOUT)
  WRITE(UNIT=NULOUT,FMT='('' '')')
ENDIF

IF (PRESENT(YDFPVAB)) THEN
  ! Cross-check YDFPVAB and YDFPFIELDS
  IERR = 0
  IF (SIZE(YDFPFIELDS%NRFP3S) > UBOUND(YDFPVAB%VBH,DIM=1)) THEN
    IERR = IERR+1
    WRITE(NULOUT,*) 'SIZE(YDFPFIELDS%NRFP3S) CANNOT BE GREATER THAN UBOUND(YDFPVAB%VBH,DIM=1)'
  ENDIF
  DO J = 1, SIZE(YDFPFIELDS%NRFP3S)
    IF (YDFPFIELDS%NRFP3S(J) < 1 .OR. YDFPFIELDS%NRFP3S(J) > UBOUND(YDFPVAB%VBH,DIM=1)) THEN
      IERR = IERR+1
      WRITE(NULOUT,*) 'ERROR YDFPFIELDS%NRFP3S(',J,') = ',YDFPFIELDS%NRFP3S(J), &
       & ' OUT OF [1,',UBOUND(YDFPVAB%VBH,DIM=1),']'
    ENDIF
  ENDDO
  IF (IERR > 0) CALL ABOR1('SUFPFIELDS: MISMATCH YDFPVAB AND YDFPFIELDS')
ENDIF

!     ------------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPFIELDS',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPFIELDS
