! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUFPDYN(YDNAMFPSCI,YDFPFIELDS,KFPDOM,CDFPDOM,KGRIB,LDSURF,CDNAME,LDNOFIL,CDYFILE,YDRQDYN)

!**** *SUFPDYN*  - INITIALIZE REQUESTS ON DYNAMICS

!     PURPOSE.
!     --------
!        INITIALIZE DYNAMIC REQUESTS OF POST-PROCESSING AT A GIVEN TIME STEP.
!        IN THIS ROUTINE, WE CONSIDER THAT FOR A GIVEN LEVEL TYPE, ALL THE
!        FIELDS ARE POST-PROCESSED AT ALL LEVELS AND FOR ALL SUBDOMAINS.
!
!        NB: THIS DEFAULT BEHAVIOUR HAS NOW CHANGED IN THE CASE OF USE OF A
!            CONTROL FILE. IF A BLOCK NAMFPDY* IS EMPTY IN CONTROL FILE, NOTHING
!            WILL BE PRODUCED.

!**   INTERFACE.
!     ----------
!       *CALL* *SUFPDYN*

!        EXPLICIT ARGUMENTS
!        --------------------
!           KFPDOM : number of subdomains
!           CDFPDOM: names of the subdomains
!           KGRIB  : GRIB code for all fullpos fields
!           LDSURF : Surface/upper-air indicator for all fullpos fields
!           CDNAME : FA field name for all fullpos fields

!           LDNOFIL : .TRUE. if no control file
!           CDYFILE : control file name

!        IMPLICIT ARGUMENTS
!        --------------------
!        NONE.

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 94-04-08

!     MODIFICATIONS.
!     --------------
!      R. El Khatib : 01-08-07 Pruning options
!      R. El Khatib : 02-21-20 Fullpos B-level distribution + remove IO scheme
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      A.Bogatchev : 26-Oct-2007 removing of severe breaks of coding rools
!      S.Martinez  : 11-Aug-2010 do not produce anything if block NAMFP* is empty
!                                in "select" namelist
!        S.Martinez  : 11-Aug-2010 do not produce anything if block NAMFP* is empty
!                                  in "select" namelist
!      R. El Khatib 17-Jul-2013 FABEC post-processing
!      R. El Khatib 17-Aug-2016 Better interoperability GRIB2 vs FA
!      R. El Khatib 03 May 2018 Use allocatable array to prevent breaking the stack limit
!     ------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM     ,JPRB
USE YOMHOOK  , ONLY : LHOOK    ,DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULNAM   ,NULERR, NULOUT
USE PARFPOS  , ONLY : JPOSDOM  ,JPOSLEN  ,JPOSLE   ,JPOSDYN  ,JPOS2DF  ,JPOS3DF
USE YOMFPC   , ONLY : TNAMFPSCI, LTRACEFP, LALLOFP
USE TYPE_FPFIELDS, ONLY : TFPFIELDS
USE YOMCT0   , ONLY : LARPEGEF
USE YOMMP0   , ONLY :  NPRINTLEV
USE YOM4FPOS , ONLY : TRQFPDYN, ALLOCATE_TRQ3FP, ALLOCATE_TRQ2FP


IMPLICIT NONE

TYPE (TNAMFPSCI),  INTENT(IN)    :: YDNAMFPSCI
TYPE (TFPFIELDS),  INTENT(IN)    :: YDFPFIELDS
INTEGER(KIND=JPIM),INTENT(IN)    :: KFPDOM
CHARACTER(LEN=*),  INTENT(IN)    :: CDFPDOM(KFPDOM)
INTEGER(KIND=JPIM),INTENT(IN)    :: KGRIB(:)
LOGICAL,           INTENT(IN)    :: LDSURF(:)
CHARACTER(LEN=*),  INTENT(IN)    :: CDNAME(:)
LOGICAL           ,INTENT(IN)    :: LDNOFIL
CHARACTER(LEN=120),INTENT(IN)    :: CDYFILE
TYPE(TRQFPDYN),    INTENT(OUT) :: YDRQDYN

INTEGER(KIND=JPIM), EXTERNAL :: ISRCHEQ

CHARACTER (LEN = 39) ::  CLNOTE
CHARACTER (LEN = 16) ::  CL2DF(JPOS2DF)
CHARACTER (LEN=(JPOSDOM*(JPOSLEN+1))-1) :: CLD2DF(JPOS2DF)
NAMELIST/NAMFPDY2/CL2DF,CLD2DF
CHARACTER (LEN = 12) ::  CL3DF(JPOS3DF)
INTEGER(KIND=JPIM) :: IL3DF(JPOSLE,JPOS3DF), ILEV3(JPOS3DF)

! local arrays CL3DF[PHTVSI]/CLD3DF[PHTVSI]/IL3DF[PHTVSI]: initialized with content
! of given post-processing "select" namelist
CHARACTER (LEN = 12) :: CL3DFP(JPOS3DF), CL3DFH(JPOS3DF), &
 & CL3DFT(JPOS3DF), CL3DFV(JPOS3DF), CL3DFS(JPOS3DF), CL3DFI(JPOS3DF),&
 & CL3DFF(JPOS3DF)
INTEGER(KIND=JPIM) :: IL3DFP(JPOSLE,JPOS3DF), IL3DFH(JPOSLE,JPOS3DF), &
 & IL3DFT(JPOSLE,JPOS3DF), IL3DFV(JPOSLE,JPOS3DF), &
 & IL3DFS(JPOSLE,JPOS3DF), IL3DFI(JPOSLE,JPOS3DF), IL3DFF(JPOSLE,JPOS3DF)
CHARACTER (LEN=(JPOSDOM*(JPOSLEN+1))-1), ALLOCATABLE :: CLD3DF(:,:)
CHARACTER (LEN=(JPOSDOM*(JPOSLEN+1))-1), ALLOCATABLE :: CLD3DFP(:,:), CLD3DFH(:,:), CLD3DFT(:,:)
CHARACTER (LEN=(JPOSDOM*(JPOSLEN+1))-1), ALLOCATABLE :: CLD3DFV(:,:), CLD3DFS(:,:), CLD3DFI(:,:), CLD3DFF(:,:)

INTEGER(KIND=JPIM) :: I2DF, I3DF(7), II3DF, IDIM, IERR, IXD, J, &
 & JF, JFLD, JL, JLEV, JSCAN, JD, ILEV, ITOTAL
 
! LL2DF = .TRUE. if block NAMFPDY2 is not empty
! LL3DF(1/2/3/4/5/6) = .TRUE. if block NAMFPDYP/H/T/V/S/I is not empty
LOGICAL :: LL2DF, LL3DF(7)

CHARACTER(LEN=16)  :: CL

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"
#include "posnam.intfb.h"
#include "sufpdom.intfb.h"

#include "namfpdyp.nam.h"
#include "namfpdyh.nam.h"
#include "namfpdyt.nam.h"
#include "namfpdyv.nam.h"
#include "namfpdys.nam.h"
#include "namfpdyi.nam.h"
#include "namfpdyf.nam.h"

IF (LHOOK) CALL DR_HOOK('SUFPDYN',0,ZHOOK_HANDLE)
ASSOCIATE(NFP3DF=>YDFPFIELDS%NFP3DF, CFP2DF=>YDFPFIELDS%CFP2DF, CFP3DF=>YDFPFIELDS%CFP3DF, NRFP3S=>YDFPFIELDS%NRFP3S, &
 & RFP3F=>YDFPFIELDS%RFP3F, RFP3H=>YDFPFIELDS%RFP3H, RFP3I=>YDFPFIELDS%RFP3I, RFP3P=>YDFPFIELDS%RFP3P, &
 & RFP3PV=>YDFPFIELDS%RFP3PV, RFP3TH=>YDFPFIELDS%RFP3TH, MFP2DF=>YDFPFIELDS%MFP2DF, MFP3DFS=>YDFPFIELDS%MFP3DFS, &
 & MFP3DFP=>YDFPFIELDS%MFP3DFP, MFP3DFH=>YDFPFIELDS%MFP3DFH, MFP3DFT=>YDFPFIELDS%MFP3DFT, MFP3DFV=>YDFPFIELDS%MFP3DFV, &
 & MFP3DFI=>YDFPFIELDS%MFP3DFI, MFP3DFF=>YDFPFIELDS%MFP3DFF, NFP3DFS=>YDFPFIELDS%NFP3DFS, NFP3DFP=>YDFPFIELDS%NFP3DFP, &
 & NFP3DFH=>YDFPFIELDS%NFP3DFH, NFP3DFT=>YDFPFIELDS%NFP3DFT, NFP3DFV=>YDFPFIELDS%NFP3DFV, NFP3DFI=>YDFPFIELDS%NFP3DFI, &
 & NFP3DFF=>YDFPFIELDS%NFP3DFF, NFP2DF=>YDFPFIELDS%NFP2DF, NFP3P=>YDFPFIELDS%NFP3P, NFP3H=>YDFPFIELDS%NFP3H, &
 & NFP3TH=>YDFPFIELDS%NFP3TH, NFP3PV=>YDFPFIELDS%NFP3PV, NFP3F=>YDFPFIELDS%NFP3F, NFP3S=>YDFPFIELDS%NFP3S, &
 & NFP3I=>YDFPFIELDS%NFP3I)

IXD=JPOSDOM

ALLOCATE(CLD3DF(JPOSLE,JPOS3DF))

!*       1. READ REQUESTS IF CONTROL FILE EXISTS
!           ------------------------------------

! initialize LL2DF/LL3DF to .FALSE.
LL2DF=.FALSE.
LL3DF(:)=.FALSE.

IF (.NOT.LDNOFIL) THEN

  CLOSE(NULNAM)
  OPEN(NULNAM,FILE=CDYFILE,ACTION='READ')

!        Post-processing on 2D fields :

  CL2DF(:)=' '
  CLD2DF(:)=' '

  CALL POSNAM(NULNAM,'NAMFPDY2')
  READ(NULNAM,NAMFPDY2)

  DO J=1, JPOS2DF
    IF (CL2DF(J) == ' ') EXIT
  ENDDO
  I2DF=J-1
  LL2DF=( I2DF > 0 )

!        Post-processing on 3D fields :

  DO JSCAN=1,7

    CL3DF(:)=' '
    IL3DF(:,:)=0
    CLD3DF(:,:)=' '

    IF (JSCAN == 1) THEN
      CALL POSNAM(NULNAM,'NAMFPDYP')
      READ(NULNAM,NAMFPDYP)
      CL3DFP=CL3DF
      IL3DFP=IL3DF
      ALLOCATE(CLD3DFP(JPOSLE,JPOS3DF))
      CLD3DFP(:,:)=CLD3DF(:,:)
    ELSEIF (JSCAN == 2) THEN
      CALL POSNAM(NULNAM,'NAMFPDYH')
      READ(NULNAM,NAMFPDYH)
      CL3DFH=CL3DF
      IL3DFH=IL3DF
      ALLOCATE(CLD3DFH(JPOSLE,JPOS3DF))
      CLD3DFH(:,:)=CLD3DF(:,:)
    ELSEIF (JSCAN == 3) THEN
      CALL POSNAM(NULNAM,'NAMFPDYT')
      READ(NULNAM,NAMFPDYT)
      CL3DFT=CL3DF
      IL3DFT=IL3DF
      ALLOCATE(CLD3DFT(JPOSLE,JPOS3DF))
      CLD3DFT(:,:)=CLD3DF(:,:)
    ELSEIF (JSCAN == 4) THEN
      CALL POSNAM(NULNAM,'NAMFPDYV')
      READ(NULNAM,NAMFPDYV)
      CL3DFV=CL3DF
      IL3DFV=IL3DF
      ALLOCATE(CLD3DFV(JPOSLE,JPOS3DF))
      CLD3DFV(:,:)=CLD3DF(:,:)
    ELSEIF (JSCAN == 5) THEN
      CALL POSNAM(NULNAM,'NAMFPDYS')
      READ(NULNAM,NAMFPDYS)
      CL3DFS=CL3DF
      IL3DFS=IL3DF
      ALLOCATE(CLD3DFS(JPOSLE,JPOS3DF))
      CLD3DFS(:,:)=CLD3DF(:,:)
    ELSEIF (JSCAN == 6) THEN
      CALL POSNAM(NULNAM,'NAMFPDYI')
      READ(NULNAM,NAMFPDYI)
      CL3DFI=CL3DF
      IL3DFI=IL3DF
      ALLOCATE(CLD3DFI(JPOSLE,JPOS3DF))
      CLD3DFI(:,:)=CLD3DF(:,:)
    ELSEIF (JSCAN == 7) THEN
      CALL POSNAM(NULNAM,'NAMFPDYF')
      READ(NULNAM,NAMFPDYF)
      CL3DFF=CL3DF
      IL3DFF=IL3DF
      ALLOCATE(CLD3DFF(JPOSLE,JPOS3DF))
      CLD3DFF(:,:)=CLD3DF(:,:)
    ENDIF

    DO J=1, JPOS3DF
      IF (CL3DF(J) == ' ') EXIT
    ENDDO
    II3DF=J-1
    LL3DF(JSCAN)=( II3DF > 0 )
    I3DF(JSCAN)=II3DF

  ENDDO

  CLOSE(NULNAM)

ENDIF

!*       2. INITIALIZE REQUESTS IF NO POST-PROCESSING CONTROL FILE
!           ------------------------------------------------------

IERR=0

IF (LARPEGEF) THEN
  DO JFLD=1,NFP3DF
    IF (.NOT.ANY(CDNAME(:)(1:12) == CFP3DF(JFLD))) THEN
      WRITE(NULOUT,'(''UNKNOWN FIELD '',A12)') CFP3DF(JFLD)
      IERR=IERR+1
    ENDIF
  ENDDO
  DO JFLD=1,NFP2DF
    IF (.NOT.ANY(CDNAME(:)(1:16) == CFP2DF(JFLD))) THEN
      WRITE(NULOUT,'(''UNKNOWN FIELD '',A16)') CFP2DF(JFLD)
      IERR=IERR+1
    ENDIF
  ENDDO
ENDIF


! Pressure levels
CALL ALLOCATE_TRQ3FP(YDFPFIELDS%NFP3DFP,YDFPFIELDS%NFP3P,KFPDOM,LALLOFP,NULOUT,YDRQDYN%YPR)
YDRQDYN%YPR%NSPFIL=YDNAMFPSCI%NSPFILP
YDRQDYN%YPR%NFIT  =YDNAMFPSCI%NFITP
YDRQDYN%YPR%ZPXLEV(1:YDRQDYN%YPR%NPXLEV)=YDFPFIELDS%RFP3P(1:YDRQDYN%YPR%NPXLEV)

DO JFLD=1,YDRQDYN%YPR%NPPFIELDG
  IF (.NOT.LARPEGEF) THEN
    YDRQDYN%YPR%ICOD(JFLD)=ISRCHEQ(JPOSDYN,KGRIB(:),1,MFP3DFP(JFLD))
    IF (YDRQDYN%YPR%ICOD(JFLD) > JPOSDYN) THEN
      WRITE(NULOUT,'(''UNKNOWN GRIBCODE '',I8)') MFP3DFP(JFLD)
      IERR=IERR+1
    ENDIF
  ELSE
    DO J=1,JPOSDYN
      IF (CFP3DF(JFLD) == CDNAME(J)(1:12)) THEN
        YDRQDYN%YPR%ICOD(JFLD)=J
        EXIT
      ENDIF
    ENDDO
  ENDIF
ENDDO

! Height (above orography) levels
CALL ALLOCATE_TRQ3FP(YDFPFIELDS%NFP3DFH,YDFPFIELDS%NFP3H,KFPDOM,LALLOFP,NULOUT,YDRQDYN%YHO)
YDRQDYN%YHO%NSPFIL=YDNAMFPSCI%NSPFILH
YDRQDYN%YHO%NFIT  =YDNAMFPSCI%NFITH
YDRQDYN%YHO%ZPXLEV(1:YDRQDYN%YHO%NPXLEV)=YDFPFIELDS%RFP3H(1:YDRQDYN%YHO%NPXLEV)

DO JFLD=1,YDRQDYN%YHO%NPPFIELDG
  IF (.NOT.LARPEGEF) THEN
    YDRQDYN%YHO%ICOD(JFLD)=ISRCHEQ(JPOSDYN,KGRIB(:),1,MFP3DFH(JFLD))
    IF (YDRQDYN%YHO%ICOD(JFLD) > JPOSDYN) THEN
      WRITE(NULOUT,'(''UNKNOWN GRIBCODE '',I8)') MFP3DFH(JFLD)
      IERR=IERR+1
    ENDIF
  ELSE
    DO J=1,JPOSDYN
      IF (CFP3DF(JFLD) == CDNAME(J)(1:12)) EXIT
    ENDDO
    IF (J > JPOSDYN) THEN
    ELSE
      YDRQDYN%YHO%ICOD(JFLD)=J
    ENDIF
  ENDIF
ENDDO

! isentropic (Theta) levels
CALL ALLOCATE_TRQ3FP(YDFPFIELDS%NFP3DFT,YDFPFIELDS%NFP3TH,KFPDOM,LALLOFP,NULOUT,YDRQDYN%YTH)
YDRQDYN%YTH%NSPFIL=YDNAMFPSCI%NSPFILT
YDRQDYN%YTH%NFIT  =YDNAMFPSCI%NFITT
YDRQDYN%YTH%ZPXLEV(1:YDRQDYN%YTH%NPXLEV)=YDFPFIELDS%RFP3TH(1:YDRQDYN%YTH%NPXLEV)

DO JFLD=1,YDRQDYN%YTH%NPPFIELDG
  IF (.NOT.LARPEGEF) THEN
    YDRQDYN%YTH%ICOD(JFLD)=ISRCHEQ(JPOSDYN,KGRIB(:),1,MFP3DFT(JFLD))
    IF (YDRQDYN%YTH%ICOD(JFLD) > JPOSDYN) THEN
      WRITE(NULOUT,'(''UNKNOWN GRIBCODE '',I8)') MFP3DFT(JFLD)
      IERR=IERR+1
    ENDIF
  ELSE
    DO J=1,JPOSDYN
      IF (CFP3DF(JFLD) == CDNAME(J)(1:12)) EXIT
    ENDDO
    IF (J > JPOSDYN) THEN
    ELSE
      YDRQDYN%YTH%ICOD(JFLD)=J
    ENDIF
  ENDIF
ENDDO

! Potential Vorticity levels
CALL ALLOCATE_TRQ3FP(YDFPFIELDS%NFP3DFV,YDFPFIELDS%NFP3PV,KFPDOM,LALLOFP,NULOUT,YDRQDYN%YPV)
YDRQDYN%YPV%NSPFIL=YDNAMFPSCI%NSPFILV
YDRQDYN%YPV%NFIT  =YDNAMFPSCI%NFITV
YDRQDYN%YPV%ZPXLEV(1:YDRQDYN%YPV%NPXLEV)=YDFPFIELDS%RFP3PV(1:YDRQDYN%YPV%NPXLEV)

DO JFLD=1,YDRQDYN%YPV%NPPFIELDG
  IF (.NOT.LARPEGEF) THEN
    YDRQDYN%YPV%ICOD(JFLD)=ISRCHEQ(JPOSDYN,KGRIB(:),1,MFP3DFV(JFLD))
    IF (YDRQDYN%YPV%ICOD(JFLD) > JPOSDYN) THEN
      WRITE(NULOUT,'(''UNKNOWN GRIBCODE '',I8)') MFP3DFV(JFLD)
      IERR=IERR+1
    ENDIF
  ELSE
    DO J=1,JPOSDYN
      IF (CFP3DF(JFLD) == CDNAME(J)(1:12)) EXIT
    ENDDO
    IF (J > JPOSDYN) THEN
    ELSE
      YDRQDYN%YPV%ICOD(JFLD)=J
    ENDIF
  ENDIF
ENDDO

! Eta (s) levels
CALL ALLOCATE_TRQ3FP(YDFPFIELDS%NFP3DFS,YDFPFIELDS%NFP3S,KFPDOM,LALLOFP,NULOUT,YDRQDYN%YES)
YDRQDYN%YES%NSPFIL=YDNAMFPSCI%NSPFILS
YDRQDYN%YES%NFIT  =YDNAMFPSCI%NFITS
DO JLEV=1,YDRQDYN%YES%NPXLEV
  YDRQDYN%YES%ZPXLEV(JLEV)=REAL(YDFPFIELDS%NRFP3S(JLEV),JPRB)
ENDDO

DO JFLD=1,YDRQDYN%YES%NPPFIELDG
  IF (.NOT.LARPEGEF) THEN
    YDRQDYN%YES%ICOD(JFLD)=ISRCHEQ(JPOSDYN,KGRIB(:),1,MFP3DFS(JFLD))
    IF (YDRQDYN%YES%ICOD(JFLD) > JPOSDYN) THEN
      WRITE(NULOUT,'(''UNKNOWN GRIBCODE '',I8)') MFP3DFS(JFLD)
      IERR=IERR+1
    ENDIF
  ELSE
    DO J=1,JPOSDYN
      IF (CFP3DF(JFLD) == CDNAME(J)(1:12)) EXIT
    ENDDO
    IF (J > JPOSDYN) THEN
    ELSE
      YDRQDYN%YES%ICOD(JFLD)=J
    ENDIF
  ENDIF
ENDDO

! isothermic (T) levels
CALL ALLOCATE_TRQ3FP(YDFPFIELDS%NFP3DFI,YDFPFIELDS%NFP3I,KFPDOM,LALLOFP,NULOUT,YDRQDYN%YIT)
YDRQDYN%YIT%NSPFIL=YDNAMFPSCI%NSPFILI
YDRQDYN%YIT%NFIT  =YDNAMFPSCI%NFITI
YDRQDYN%YIT%ZPXLEV(1:YDRQDYN%YIT%NPXLEV)=YDFPFIELDS%RFP3I(1:YDRQDYN%YIT%NPXLEV)

DO JFLD=1,YDRQDYN%YIT%NPPFIELDG
  IF (.NOT.LARPEGEF) THEN
    YDRQDYN%YIT%ICOD(JFLD)=ISRCHEQ(JPOSDYN,KGRIB(:),1,MFP3DFI(JFLD))
    IF (YDRQDYN%YIT%ICOD(JFLD) > JPOSDYN) THEN
      WRITE(NULOUT,'(''UNKNOWN GRIBCODE '',I8)') MFP3DFI(JFLD)
      IERR=IERR+1
    ENDIF
  ELSE
    DO J=1,JPOSDYN
      IF (CFP3DF(JFLD) == CDNAME(J)(1:12)) EXIT
    ENDDO
    IF (J > JPOSDYN) THEN
    ELSE
      YDRQDYN%YIT%ICOD(JFLD)=J
    ENDIF
  ENDIF
ENDDO

! Flight (altitude in feet) levels
CALL ALLOCATE_TRQ3FP(YDFPFIELDS%NFP3DFF,YDFPFIELDS%NFP3F,KFPDOM,LALLOFP,NULOUT,YDRQDYN%YFL)
YDRQDYN%YFL%NSPFIL=YDNAMFPSCI%NSPFILF
YDRQDYN%YFL%NFIT  =YDNAMFPSCI%NFITF
YDRQDYN%YFL%ZPXLEV(1:YDRQDYN%YFL%NPXLEV)=YDFPFIELDS%RFP3F(1:YDRQDYN%YFL%NPXLEV)

DO JFLD=1,YDRQDYN%YFL%NPPFIELDG
  IF (.NOT.LARPEGEF) THEN
    YDRQDYN%YFL%ICOD(JFLD)=ISRCHEQ(JPOSDYN,KGRIB(:),1,MFP3DFF(JFLD))
    IF (YDRQDYN%YFL%ICOD(JFLD) > JPOSDYN) THEN
      WRITE(NULOUT,'(''UNKNOWN GRIBCODE '',I8)') MFP3DFF(JFLD)
      IERR=IERR+1
    ENDIF
  ELSE
    DO J=1,JPOSDYN
      IF (CFP3DF(JFLD) == CDNAME(J)(1:12)) EXIT
    ENDDO
    IF (J > JPOSDYN) THEN
    ELSE
      YDRQDYN%YFL%ICOD(JFLD)=J
    ENDIF
  ENDIF
ENDDO


! 2D fields
CALL ALLOCATE_TRQ2FP(YDFPFIELDS%NFP2DF,KFPDOM,LALLOFP,NULOUT,YDRQDYN%Y2D)
DO JFLD=1,YDRQDYN%Y2D%NPPFIELDG
  IF (.NOT.LARPEGEF) THEN
    DO J=1,JPOSDYN
      IF (LDSURF(J).AND.KGRIB(J)==MFP2DF(JFLD)) EXIT
    ENDDO
    YDRQDYN%Y2D%ICOD(JFLD)=J
    IF (YDRQDYN%Y2D%ICOD(JFLD) > JPOSDYN) THEN
      WRITE(NULOUT,'(''UNKNOWN GRIBCODE '',I8)') MFP2DF(JFLD)
      IERR=IERR+1
    ENDIF
  ELSE
    DO J=1,JPOSDYN
      IF (CFP2DF(JFLD) == CDNAME(J)(1:16)) EXIT
    ENDDO
    IF (J > JPOSDYN) THEN
    ELSE
      YDRQDYN%Y2D%ICOD(JFLD)=J
    ENDIF
  ENDIF
ENDDO

IF (IERR > 0) CALL ABOR1('SUFPDYN : UNKNOWN FIELD(S) ')

!*       3. MODIFIY REQUESTS IF CONTROL FILE EXISTS
!           ---------------------------------------

IF (.NOT.LDNOFIL) THEN

!        Post-processing on 2D fields :

  IERR=0
  DO J=1, I2DF
    IF (.NOT.ANY(CFP2DF(:)==CL2DF(J))) THEN
      WRITE(UNIT=CLNOTE,FMT='('' UNKNOWN FIELD '',A16)') CL2DF(J)
      WRITE(NULOUT,*) CLNOTE
      WRITE(NULERR,*) CLNOTE
      IERR=IERR+1
    ENDIF
  ENDDO
  IF (IERR > 0) CALL ABOR1('SUFPDYN: ABOR1 CALLED')

  YDRQDYN%Y2D%NPPFIELDG=I2DF
  DO JFLD=1,I2DF
    DO J=1,JPOSDYN
      IF (CL2DF(JFLD) == CDNAME(J)(1:16)) EXIT
    ENDDO
    IF (J > JPOSDYN) THEN
      CALL ABOR1('SUFPDYN : UNKNOWN FIELD ')
    ELSE
      YDRQDYN%Y2D%ICOD(JFLD)=J
    ENDIF
  ENDDO
  IDIM=JPOSDYN

  IF (.NOT.LL2DF) CLD2DF(:)=' '
  CALL SUFPDOM(CDFPDOM,IXD,KFPDOM,CLD2DF,IDIM,I2DF,YDRQDYN%Y2D%IDOM,YDRQDYN%Y2D%IDMP)

!        Post-processing on 3D fields :


  DO JSCAN=1,7

    II3DF=I3DF(JSCAN)

    IF (JSCAN == 1) THEN
      CL3DF=CL3DFP
      IL3DF=IL3DFP
      CLD3DF(:,:)=CLD3DFP(:,:)
      DEALLOCATE(CLD3DFP)
    ELSEIF (JSCAN == 2) THEN
      CL3DF=CL3DFH
      IL3DF=IL3DFH
      CLD3DF(:,:)=CLD3DFH(:,:)
      DEALLOCATE(CLD3DFH)
    ELSEIF (JSCAN == 3) THEN
      CL3DF=CL3DFT
      IL3DF=IL3DFT
      CLD3DF(:,:)=CLD3DFT(:,:)
      DEALLOCATE(CLD3DFT)
    ELSEIF (JSCAN == 4) THEN
      CL3DF=CL3DFV
      IL3DF=IL3DFV
      CLD3DF(:,:)=CLD3DFV(:,:)
      DEALLOCATE(CLD3DFV)
    ELSEIF (JSCAN == 5) THEN
      CL3DF=CL3DFS
      IL3DF=IL3DFS
      CLD3DF(:,:)=CLD3DFS(:,:)
      DEALLOCATE(CLD3DFS)
    ELSEIF (JSCAN == 6) THEN
      CL3DF=CL3DFI
      IL3DF=IL3DFI
      CLD3DF(:,:)=CLD3DFI(:,:)
      DEALLOCATE(CLD3DFI)
    ELSEIF (JSCAN == 7) THEN
      CL3DF=CL3DFF
      IL3DF=IL3DFF
      CLD3DF(:,:)=CLD3DFF(:,:)
      DEALLOCATE(CLD3DFF)
    ENDIF

    IF (.NOT.LL3DF(JSCAN)) CLD3DF(:,:)=' '

    DO JF=1, II3DF
      DO JL=1, JPOSLE
        IF (IL3DF(JL,JF) <= 0) EXIT
      ENDDO
      ILEV3(JF)=JL-1
    ENDDO

    IERR=0

    DO J=1, II3DF

      IF (.NOT.ANY(CFP3DF(:)==CL3DF(J))) THEN
        WRITE(UNIT=CLNOTE,FMT='('' UNKNOWN FIELD '',A12)') CL3DF(J)
        WRITE(NULOUT,*) CLNOTE
        WRITE(NULERR,*) CLNOTE
        IERR=IERR+1
      ENDIF
      IF (JSCAN == 1) THEN
        IF (ILEV3(J) > NFP3P) THEN
          WRITE(UNIT=CLNOTE,FMT='('' TOO MUCH PRESSURE LEVELS '')')
          WRITE(NULOUT,*) CLNOTE
          WRITE(NULERR,*) CLNOTE
          IERR=IERR+1
        ENDIF
        DO JL=1,ILEV3(J)
          IF (IL3DF(JL,J) > NFP3P) THEN
            WRITE(UNIT=CLNOTE,FMT='(''PRESSURE INDEX RANGE ERROR'')')
            WRITE(NULOUT,*) CLNOTE
            WRITE(NULERR,*) CLNOTE
            IERR=IERR+1
          ENDIF
        ENDDO
      ELSEIF (JSCAN == 2) THEN
        IF (ILEV3(J) > NFP3H) THEN
          WRITE(UNIT=CLNOTE,FMT='('' TOO MUCH HEIGHT LEVELS '')')
          WRITE(NULOUT,*) CLNOTE
          WRITE(NULERR,*) CLNOTE
          IERR=IERR+1
        ENDIF
        DO JL=1,ILEV3(J)
          IF (IL3DF(JL,J) > NFP3H) THEN
            WRITE(UNIT=CLNOTE,FMT='('' HEIGHT INDEX RANGE ERROR '')')
            WRITE(NULOUT,*) CLNOTE
            WRITE(NULERR,*) CLNOTE
            IERR=IERR+1
          ENDIF
        ENDDO
      ELSEIF (JSCAN == 3) THEN
        IF (ILEV3(J) > NFP3TH) THEN
          WRITE(UNIT=CLNOTE,FMT='('' TOO MUCH THETA LEVELS '')')
          WRITE(NULOUT,*) CLNOTE
          WRITE(NULERR,*) CLNOTE
          IERR=IERR+1
        ENDIF
        DO JL=1,ILEV3(J)
          IF (IL3DF(JL,J) > NFP3TH) THEN
            WRITE(UNIT=CLNOTE,FMT='('' THETA INDEX RANGE ERROR '')')
            WRITE(NULOUT,*) CLNOTE
            WRITE(NULERR,*) CLNOTE
            IERR=IERR+1
          ENDIF
        ENDDO
      ELSEIF (JSCAN == 4) THEN
        IF (ILEV3(J) > NFP3PV) THEN
          WRITE(UNIT=CLNOTE,FMT='('' TOO MUCH PV LEVELS '')')
          WRITE(NULOUT,*) CLNOTE
          WRITE(NULERR,*) CLNOTE
          IERR=IERR+1
        ENDIF
        DO JL=1,ILEV3(J)
          IF (IL3DF(JL,J) > NFP3PV) THEN
            WRITE(UNIT=CLNOTE,FMT='('' PV INDEX RANGE ERROR '')')
            WRITE(NULOUT,*) CLNOTE
            WRITE(NULERR,*) CLNOTE
            IERR=IERR+1
          ENDIF
        ENDDO
      ELSEIF (JSCAN == 5) THEN
        IF (ILEV3(J) > NFP3S) THEN
          WRITE(UNIT=CLNOTE,FMT='('' TOO MUCH ETA LEVELS '')')
          WRITE(NULOUT,*) CLNOTE
          WRITE(NULERR,*) CLNOTE
          IERR=IERR+1
        ENDIF
        DO JL=1,ILEV3(J)
          IF (IL3DF(JL,J) > NFP3S) THEN
            WRITE(UNIT=CLNOTE,FMT='('' ETA INDEX RANGE ERROR '')')
            WRITE(NULOUT,*) CLNOTE
            WRITE(NULERR,*) CLNOTE
            IERR=IERR+1
          ENDIF
        ENDDO
      ELSEIF (JSCAN == 6) THEN
        IF (ILEV3(J) > NFP3I) THEN
          WRITE(UNIT=CLNOTE,FMT='('' TOO MUCH TEMPERATURE LEVELS '')')
          WRITE(NULOUT,*) CLNOTE
          WRITE(NULERR,*) CLNOTE
          IERR=IERR+1
        ENDIF
        DO JL=1,ILEV3(J)
          IF (IL3DF(JL,J) > NFP3I) THEN
            WRITE(UNIT=CLNOTE,FMT='('' TEMPERATURE INDEX RANGE ERROR '')')
            WRITE(NULOUT,*) CLNOTE
            WRITE(NULERR,*) CLNOTE
            IERR=IERR+1
          ENDIF
        ENDDO
      ELSEIF (JSCAN == 7) THEN
        IF (ILEV3(J) > NFP3F) THEN
          WRITE(UNIT=CLNOTE,FMT='('' TOO MUCH FLIGHT LEVELS '')')
          WRITE(NULOUT,*) CLNOTE
          WRITE(NULERR,*) CLNOTE
          IERR=IERR+1
        ENDIF
        DO JL=1,ILEV3(J)
          IF (IL3DF(JL,J) > NFP3F) THEN
            WRITE(UNIT=CLNOTE,FMT='('' FLIGHT INDEX RANGE ERROR '')')
            WRITE(NULOUT,*) CLNOTE
            WRITE(NULERR,*) CLNOTE
            IERR=IERR+1
          ENDIF
        ENDDO
      ENDIF

    ENDDO

    IF (IERR > 0) CALL ABOR1('SUFPDYN: ABOR1 CALLED')

    IDIM=JPOSLE
    IF (JSCAN == 1) THEN
      YDRQDYN%YPR%NPPFIELDG=II3DF
      DO JFLD=1,II3DF
        DO J=1,JPOSDYN
          IF (CL3DF(JFLD) == CDNAME(J)(1:12)) EXIT
        ENDDO
        IF (J > JPOSDYN) THEN
          CALL ABOR1('SUFPDYN : UNKNOWN FIELD ')
        ELSE
          YDRQDYN%YPR%ICOD(JFLD)=J
        ENDIF
        YDRQDYN%YPR%NPPLEVG(JFLD)=ILEV3(JFLD)
        IF (YDRQDYN%YPR%NPPLEVG(JFLD) > 0) THEN
          CALL SUFPDOM(CDFPDOM,IXD,KFPDOM,CLD3DF(1,JFLD),IDIM,&
           & YDRQDYN%YPR%NPPLEVG(JFLD),YDRQDYN%YPR%IDOM(1,JFLD),YDRQDYN%YPR%IDMP(1,1,JFLD))
        ENDIF
        DO JLEV=1,YDRQDYN%YPR%NPPLEVG(JFLD)
          YDRQDYN%YPR%ILEV(JLEV,JFLD)=IL3DF(JLEV,JFLD)
        ENDDO
      ENDDO
    ELSEIF (JSCAN == 2) THEN
      YDRQDYN%YHO%NPPFIELDG=II3DF
      DO JFLD=1,II3DF
        DO J=1,JPOSDYN
          IF (CL3DF(JFLD) == CDNAME(J)(1:12)) EXIT
        ENDDO
        IF (J > JPOSDYN) THEN
          CALL ABOR1('SUFPDYN : UNKNOWN FIELD ')
        ELSE
          YDRQDYN%YHO%ICOD(JFLD)=J
        ENDIF
        YDRQDYN%YHO%NPPLEVG(JFLD)=ILEV3(JFLD)
        IF (YDRQDYN%YHO%NPPLEVG(JFLD) > 0) THEN
          CALL SUFPDOM(CDFPDOM,IXD,KFPDOM,CLD3DF(1,JFLD),IDIM,&
           & YDRQDYN%YHO%NPPLEVG(JFLD),YDRQDYN%YHO%IDOM(1,JFLD),YDRQDYN%YHO%IDMP(1,1,JFLD))
        ENDIF
        DO JLEV=1,YDRQDYN%YHO%NPPLEVG(JFLD)
          YDRQDYN%YHO%ILEV(JLEV,JFLD)=IL3DF(JLEV,JFLD)
        ENDDO
      ENDDO
    ELSEIF (JSCAN == 3) THEN
      YDRQDYN%YTH%NPPFIELDG=II3DF
      DO JFLD=1,II3DF
        DO J=1,JPOSDYN
          IF (CL3DF(JFLD) == CDNAME(J)(1:12)) EXIT
        ENDDO
        IF (J > JPOSDYN) THEN
          CALL ABOR1('SUFPDYN : UNKNOWN FIELD ')
        ELSE
          YDRQDYN%YTH%ICOD(JFLD)=J
        ENDIF
        YDRQDYN%YTH%NPPLEVG(JFLD)=ILEV3(JFLD)
        IF (YDRQDYN%YTH%NPPLEVG(JFLD) > 0) THEN
          CALL SUFPDOM(CDFPDOM,IXD,KFPDOM,CLD3DF(1,JFLD),IDIM,&
           & YDRQDYN%YTH%NPPLEVG(JFLD),YDRQDYN%YTH%IDOM(1,JFLD),YDRQDYN%YTH%IDMP(1,1,JFLD))
        ENDIF
        DO JLEV=1,YDRQDYN%YTH%NPPLEVG(JFLD)
          YDRQDYN%YTH%ILEV(JLEV,JFLD)=IL3DF(JLEV,JFLD)
        ENDDO
      ENDDO
    ELSEIF (JSCAN == 4) THEN
      YDRQDYN%YPV%NPPFIELDG=II3DF
      DO JFLD=1,II3DF
        DO J=1,JPOSDYN
          IF (CL3DF(JFLD) == CDNAME(J)(1:12)) EXIT
        ENDDO
        IF (J > JPOSDYN) THEN
          CALL ABOR1('SUFPDYN : UNKNOWN FIELD ')
        ELSE
          YDRQDYN%YPV%ICOD(JFLD)=J
        ENDIF
        YDRQDYN%YPV%NPPLEVG(JFLD)=ILEV3(JFLD)
        IF (YDRQDYN%YPV%NPPLEVG(JFLD) > 0) THEN
          CALL SUFPDOM(CDFPDOM,IXD,KFPDOM,CLD3DF(1,JFLD),IDIM,&
           & YDRQDYN%YPV%NPPLEVG(JFLD),YDRQDYN%YPV%IDOM(1,JFLD),YDRQDYN%YPV%IDMP(1,1,JFLD))
        ENDIF
        DO JLEV=1,YDRQDYN%YPV%NPPLEVG(JFLD)
          YDRQDYN%YPV%ILEV(JLEV,JFLD)=IL3DF(JLEV,JFLD)
        ENDDO
      ENDDO
    ELSEIF (JSCAN == 5) THEN
      YDRQDYN%YES%NPPFIELDG=II3DF
      DO JFLD=1,II3DF
        DO J=1,JPOSDYN
          IF (CL3DF(JFLD) == CDNAME(J)(1:12)) EXIT
        ENDDO
        IF (J > JPOSDYN) THEN
          CALL ABOR1('SUFPDYN : UNKNOWN FIELD ')
        ELSE
          YDRQDYN%YES%ICOD(JFLD)=J
        ENDIF
        YDRQDYN%YES%NPPLEVG(JFLD)=ILEV3(JFLD)
        IF (YDRQDYN%YES%NPPLEVG(JFLD) > 0) THEN
          CALL SUFPDOM(CDFPDOM,IXD,KFPDOM,CLD3DF(1,JFLD),IDIM,&
           & YDRQDYN%YES%NPPLEVG(JFLD),YDRQDYN%YES%IDOM(1,JFLD),YDRQDYN%YES%IDMP(1,1,JFLD))
        ENDIF
        DO JLEV=1,YDRQDYN%YES%NPPLEVG(JFLD)
          YDRQDYN%YES%ILEV(JLEV,JFLD)=IL3DF(JLEV,JFLD)
        ENDDO
      ENDDO
    ELSEIF (JSCAN == 6) THEN
      YDRQDYN%YIT%NPPFIELDG=II3DF
      DO JFLD=1,II3DF
        DO J=1,JPOSDYN
          IF (CL3DF(JFLD) == CDNAME(J)(1:12)) EXIT
        ENDDO
        IF (J > JPOSDYN) THEN
          CALL ABOR1('SUFPDYN : UNKNOWN FIELD ')
        ELSE
          YDRQDYN%YIT%ICOD(JFLD)=J
        ENDIF
        YDRQDYN%YIT%NPPLEVG(JFLD)=ILEV3(JFLD)
        IF (YDRQDYN%YIT%NPPLEVG(JFLD) > 0) THEN
          CALL SUFPDOM(CDFPDOM,IXD,KFPDOM,CLD3DF(1,JFLD),IDIM,&
           & YDRQDYN%YIT%NPPLEVG(JFLD),YDRQDYN%YIT%IDOM(1,JFLD),YDRQDYN%YIT%IDMP(1,1,JFLD))
        ENDIF
        DO JLEV=1,YDRQDYN%YIT%NPPLEVG(JFLD)
          YDRQDYN%YIT%ILEV(JLEV,JFLD)=IL3DF(JLEV,JFLD)
        ENDDO
      ENDDO
    ELSEIF (JSCAN == 7) THEN
      YDRQDYN%YFL%NPPFIELDG=II3DF
      DO JFLD=1,II3DF
        DO J=1,JPOSDYN
          IF (CL3DF(JFLD) == CDNAME(J)(1:12)) EXIT
        ENDDO
        IF (J > JPOSDYN) THEN
          CALL ABOR1('SUFPDYN : UNKNOWN FIELD ')
        ELSE
          YDRQDYN%YFL%ICOD(JFLD)=J
        ENDIF
        YDRQDYN%YFL%NPPLEVG(JFLD)=ILEV3(JFLD)
        IF (YDRQDYN%YFL%NPPLEVG(JFLD) > 0) THEN
          CALL SUFPDOM(CDFPDOM,IXD,KFPDOM,CLD3DF(1,JFLD),IDIM,&
           & YDRQDYN%YFL%NPPLEVG(JFLD),YDRQDYN%YFL%IDOM(1,JFLD),YDRQDYN%YFL%IDMP(1,1,JFLD))
        ENDIF
        DO JLEV=1,YDRQDYN%YFL%NPPLEVG(JFLD)
          YDRQDYN%YFL%ILEV(JLEV,JFLD)=IL3DF(JLEV,JFLD)
        ENDDO
      ENDDO
    ENDIF
  ENDDO

ENDIF

!*       3. PRINT OUT REQUESTS
!           ------------------

ITOTAL=YDRQDYN%YPR%NPPFIELDG+YDRQDYN%YHO%NPPFIELDG+YDRQDYN%YTH%NPPFIELDG+YDRQDYN%YPV%NPPFIELDG+YDRQDYN%YES%NPPFIELDG &
 &    +YDRQDYN%YIT%NPPFIELDG+YDRQDYN%YFL%NPPFIELDG+YDRQDYN%Y2D%NPPFIELDG

IF (LTRACEFP .AND. NPRINTLEV >= 2 .AND. ITOTAL > 0) THEN

  WRITE(NULOUT,*) ' THE FOLLOWING DYNAMIC FIELDS WILL BE POST_PROCESSED AT THE CURRENT TIME STEP :'

!        Post-processing on P levels :
  DO JFLD=1,YDRQDYN%YPR%NPPFIELDG
    DO JLEV=1,YDRQDYN%YPR%NPPLEVG(JFLD)
      IF (RFP3P(YDRQDYN%YPR%ILEV(JLEV,JFLD)) < 100000._JPRB) THEN
        ILEV=NINT(RFP3P(YDRQDYN%YPR%ILEV(JLEV,JFLD))/100._JPRB)
      ELSE
        ILEV=NINT(RFP3P(YDRQDYN%YPR%ILEV(JLEV,JFLD))-100000._JPRB)
      ENDIF
      WRITE(NULOUT,FMT='(''P'',I3.3,A12,''/'',10(1X,A7))')&
       & ILEV,CDNAME(YDRQDYN%YPR%ICOD(JFLD))(1:12),&
       & (CDFPDOM(YDRQDYN%YPR%IDMP(JD,JLEV,JFLD)),JD=1,YDRQDYN%YPR%IDOM(JLEV,JFLD))
    ENDDO
  ENDDO

!        Post-processing on H levels :
  CL(1:1)='H'
  DO JFLD=1,YDRQDYN%YHO%NPPFIELDG
    CL(5:)=CDNAME(YDRQDYN%YHO%ICOD(JFLD))(1:12)
    DO JLEV=1,YDRQDYN%YHO%NPPLEVG(JFLD)
      WRITE(UNIT=CL(2:4),FMT='(I3.3)') NINT(RFP3H(YDRQDYN%YHO%ILEV(JLEV,JFLD)))
      WRITE(NULOUT,FMT='(A16,''/'',10(1X,A7))')&
       & CL,(CDFPDOM(YDRQDYN%YHO%IDMP(JD,JLEV,JFLD)),JD=1,YDRQDYN%YHO%IDOM(JLEV,JFLD))
    ENDDO
  ENDDO

  CL(1:1)='T'
  DO JFLD=1,YDRQDYN%YTH%NPPFIELDG
    CL(5:)=CDNAME(YDRQDYN%YTH%ICOD(JFLD))(1:12)
    DO JLEV=1,YDRQDYN%YTH%NPPLEVG(JFLD)
      WRITE(UNIT=CL(2:4),FMT='(I3.3)') NINT(RFP3TH(YDRQDYN%YTH%ILEV(JLEV,JFLD)))
      WRITE(NULOUT,FMT='(A16,''/'',10(1X,A7))')&
       & CL,(CDFPDOM(YDRQDYN%YTH%IDMP(JD,JLEV,JFLD)),JD=1,YDRQDYN%YTH%IDOM(JLEV,JFLD))
    ENDDO
  ENDDO

!        Post-processing on PV levels :
  CL(1:1)='V'
  DO JFLD=1,YDRQDYN%YPV%NPPFIELDG
    CL(6:)=CDNAME(YDRQDYN%YPV%ICOD(JFLD))(1:12)
    DO JLEV=1,YDRQDYN%YPV%NPPLEVG(JFLD)
      ILEV=NINT(RFP3PV(YDRQDYN%YPV%ILEV(JLEV,JFLD))*1.E+09_JPRB)
      WRITE(UNIT=CL(2:5),FMT='(I4.4)') ILEV
      WRITE(NULOUT,FMT='(A16,''/'',10(1X,A7))')&
       & CL,(CDFPDOM(YDRQDYN%YPV%IDMP(JD,JLEV,JFLD)),JD=1,YDRQDYN%YPV%IDOM(JLEV,JFLD))
    ENDDO
  ENDDO

!        Post-processing on S levels :
  DO JFLD=1,YDRQDYN%YES%NPPFIELDG
    DO JLEV=1,YDRQDYN%YES%NPPLEVG(JFLD)
      WRITE(NULOUT,FMT='(''S'',I3.3,A12,''/'',10(1X,A7))')&
       & NRFP3S(YDRQDYN%YES%ILEV(JLEV,JFLD)),CDNAME(YDRQDYN%YES%ICOD(JFLD))(1:12),&
       & (CDFPDOM(YDRQDYN%YES%IDMP(JD,JLEV,JFLD)),JD=1,YDRQDYN%YES%IDOM(JLEV,JFLD))
    ENDDO
  ENDDO

!        Post-processing on T levels :
  CL(1:1)='K'
  DO JFLD=1,YDRQDYN%YIT%NPPFIELDG
    CL(5:)=CDNAME(YDRQDYN%YIT%ICOD(JFLD))(1:12)
    DO JLEV=1,YDRQDYN%YIT%NPPLEVG(JFLD)
      WRITE(UNIT=CL(2:4),FMT='(I3.3)') NINT(RFP3I(YDRQDYN%YIT%ILEV(JLEV,JFLD)))
      WRITE(NULOUT,FMT='(A16,''/'',10(1X,A7))')&
       & CL,(CDFPDOM(YDRQDYN%YIT%IDMP(JD,JLEV,JFLD)),JD=1,YDRQDYN%YIT%IDOM(JLEV,JFLD))
    ENDDO
  ENDDO

  !        Post-processing on Flight levels :
  CL(1:1)='F'
  DO JFLD=1,YDRQDYN%YFL%NPPFIELDG
    CL(5:)=CDNAME(YDRQDYN%YFL%ICOD(JFLD))(1:12)
    DO JLEV=1,YDRQDYN%YFL%NPPLEVG(JFLD)
      WRITE(UNIT=CL(2:4),FMT='(I3.3)') NINT(RFP3F(YDRQDYN%YFL%ILEV(JLEV,JFLD)))
      WRITE(NULOUT,FMT='(A16,''/'',10(1X,A7))')&
       & CL,(CDFPDOM(YDRQDYN%YFL%IDMP(JD,JLEV,JFLD)),JD=1,YDRQDYN%YFL%IDOM(JLEV,JFLD))
    ENDDO
  ENDDO

!        Post-processing on 2D fields :
  DO JFLD=1,YDRQDYN%Y2D%NPPFIELDG
    WRITE(NULOUT,FMT='(A16,''/'',10(1X,A7))')&
     & CDNAME(YDRQDYN%Y2D%ICOD(JFLD)),(CDFPDOM(YDRQDYN%Y2D%IDMP(JD,JFLD)),&
     & JD=1,YDRQDYN%Y2D%IDOM(JFLD))
  ENDDO

ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUFPDYN',1,ZHOOK_HANDLE)
END SUBROUTINE SUFPDYN

