! (C) Copyright 1989- Meteo-France.

SUBROUTINE SUVFPOSL(YDQTYPE,YDRQSP,YDRQGP,KGRIB,LDSURF,CDNAME,KFPDOM,KPXLEV,PXLEV,KFPCONF,CDCONF)

!**** *SUVFPOSL*  - SETUP VERTICAL POST-PROCESSING / LAGGED PART

!     PURPOSE.
!     --------
!        TO INITIALIZE THE MODULE YOMFP4L WHICH CONTAINS THE VARIABLES AND ARRAYS
!        NEEDED TO WRITE OUT POST-PROCESSED FIELDS
!        (originally "LAGGED" BECAUSE THE WRITING OUT WAS PERFORMED IN A NEXT STEPO SEQUENCE)

!**   INTERFACE.
!     ----------
!       *CALL* *SUVFPOSL*

!        EXPLICIT ARGUMENTS
!        ------------------
!           KGRIB  : GRIB code for all fullpos fields
!           LDSURF : Surface/upper-air indicator for all fullpos fields
!           CDNAME : FA field name for all fullpos fields
!           KFPDOM  : number of subdomains
!           KFPCONF : configuration of the post-processing :
!                     0 : vertical interpolation only (<CFPFMT='MODEL'>)
!                     1 : gridpoint post-processing, possibly with spectral filters (<NFPOS=1>)
!                     2 : gridpoint/spectral post-processing (spectral outputs possible) (<NFPOS=2>)
!              CDCONF  : Configuration of IOs
!                        if present then allocate and compute ; else deallocate.

!        IMPLICIT ARGUMENTS
!        ------------------

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!      RYAD EL KHATIB *METEO-FRANCE*
!      ORIGINAL : 94-04-08

!     MODIFICATIONS.
!     --------------
!      R. El Khatib : 02-21-20 Fullpos B-level distribution + remove IO scheme
!      R. El Khatib : 03-04-17 Fullpos improvments
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      R. El Khatib : 08-Aug-2012 Cleanings + replace cfpfmt by nfpos
!      R. El Khatib 04-Aug-2014 Pruning of the conf. 927/928
!      R. El Khatib 20-Nov-2015 more descriptors
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMLUN   , ONLY : NULOUT
USE YOMFPC   , ONLY : LTRACEFP ,LALLOFP
USE TYPE_FPRQDYNS, ONLY : TYPE_FPRQDYN
USE YOMFP4L  , ONLY : TRQFP

IMPLICIT NONE

TYPE (TYPE_FPRQDYN),  INTENT(IN) :: YDQTYPE
TYPE (TRQFP),  INTENT(INOUT) :: YDRQSP
TYPE (TRQFP),  INTENT(INOUT) :: YDRQGP
INTEGER(KIND=JPIM),INTENT(IN)  :: KGRIB(:)
LOGICAL,           INTENT(IN)  :: LDSURF(:)
CHARACTER(LEN=*),  INTENT(IN)  :: CDNAME(:)
INTEGER(KIND=JPIM), INTENT(IN) :: KFPDOM
INTEGER(KIND=JPIM), INTENT(IN) :: KPXLEV
REAL(KIND=JPRB),    INTENT(IN) :: PXLEV(KPXLEV)
INTEGER(KIND=JPIM), INTENT(IN),OPTIONAL :: KFPCONF
CHARACTER(LEN=1),INTENT(IN),OPTIONAL :: CDCONF

LOGICAL :: LLIOSPEC, LLSURF
INTEGER(KIND=JPIM) :: J, INC, IGP, ISPA, JL, JD, IJ

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('SUVFPOSL',0,ZHOOK_HANDLE)

IF (PRESENT(CDCONF)) THEN

!*       1. SETUP
!           -----

  LLIOSPEC=(KFPCONF /= 1) ! says the output data is spectral

  IF (LLIOSPEC) THEN
!   Spectral outputs :
    YDRQSP%NFIELDL=YDQTYPE%NFPSPB
    YDRQSP%NFIELDG=YDQTYPE%NFPDYNB-YDQTYPE%NFPAUXB
    YDRQGP%NFIELDG=YDQTYPE%NFPAUXB
  ELSE
    YDRQSP%NFIELDL=0
    YDRQSP%NFIELDG=0
    YDRQGP%NFIELDG=YDQTYPE%NFPDYNB
  ENDIF

  IF (LTRACEFP) THEN
    WRITE(NULOUT,'('' YDRQSP%NFIELDL = '',I5,'' YDRQGP%NFIELDG = '',I5,'' YDRQSP%NFIELDG = '',I5)') &
     & YDRQSP%NFIELDL,YDRQGP%NFIELDG,YDRQSP%NFIELDG  
  ENDIF

!*       2. ALLOCATIONS
!           -----------

  ALLOCATE(YDRQGP%ICOD(YDRQGP%NFIELDG),YDRQGP%LLSURF(YDRQGP%NFIELDG),YDRQGP%ZLEV(YDRQGP%NFIELDG))
  ALLOCATE(YDRQGP%IDOM(YDRQGP%NFIELDG),YDRQGP%IDMP(KFPDOM,YDRQGP%NFIELDG))
  ALLOCATE(YDRQSP%ICOD(YDRQSP%NFIELDG),YDRQSP%LLSURF(YDRQSP%NFIELDG),YDRQSP%ZLEV(YDRQSP%NFIELDG))
  ALLOCATE(YDRQSP%IVSETG(YDRQSP%NFIELDG),YDRQSP%IVLOCG(YDRQSP%NFIELDG))
  ALLOCATE(YDRQSP%CLPREF(YDRQSP%NFIELDG),YDRQSP%CLNAME(YDRQSP%NFIELDG),YDRQSP%IGRIB(YDRQSP%NFIELDG))
  ALLOCATE(YDRQGP%CLPREF(YDRQGP%NFIELDG),YDRQGP%CLNAME(YDRQGP%NFIELDG),YDRQGP%IGRIB(YDRQGP%NFIELDG))
  IF (LALLOFP) THEN
    WRITE(NULOUT,9) 'ICOD  ',SIZE(YDRQGP%ICOD),SHAPE(YDRQGP%ICOD) 
    WRITE(NULOUT,9) 'LLSURF  ',SIZE(YDRQGP%LLSURF),SHAPE(YDRQGP%LLSURF)
    WRITE(NULOUT,9) 'ZLEV  ',SIZE(YDRQGP%ZLEV),SHAPE(YDRQGP%ZLEV)
    WRITE(NULOUT,9) 'IDOM  ',SIZE(YDRQGP%IDOM),SHAPE(YDRQGP%IDOM)
    WRITE(NULOUT,9) 'IDMP  ',SIZE(YDRQGP%IDMP),SHAPE(YDRQGP%IDMP)
    WRITE(NULOUT,9) 'ICOD ',SIZE(YDRQSP%ICOD),SHAPE(YDRQSP%ICOD)
    WRITE(NULOUT,9) 'LLSURF ',SIZE(YDRQSP%LLSURF),SHAPE(YDRQSP%LLSURF)
    WRITE(NULOUT,9) 'ZLEV ',SIZE(YDRQSP%ZLEV),SHAPE(YDRQSP%ZLEV)
    WRITE(NULOUT,9) 'IVSETG ',SIZE(YDRQSP%IVSETG),SHAPE(YDRQSP%IVSETG)
    WRITE(NULOUT,9) 'IVLOCG ',SIZE(YDRQSP%IVLOCG),SHAPE(YDRQSP%IVLOCG)
    WRITE(NULOUT,9) 'CLPREF ',SIZE(YDRQSP%CLPREF),SHAPE(YDRQSP%CLPREF)
    WRITE(NULOUT,9) 'CLNAME ',SIZE(YDRQSP%CLNAME),SHAPE(YDRQSP%CLNAME)
    WRITE(NULOUT,9) 'IGRIB ',SIZE(YDRQSP%IGRIB),SHAPE(YDRQSP%IGRIB)
    WRITE(NULOUT,9) 'CLPREF ',SIZE(YDRQGP%CLPREF),SHAPE(YDRQGP%CLPREF)
    WRITE(NULOUT,9) 'CLNAME ',SIZE(YDRQGP%CLNAME),SHAPE(YDRQGP%CLNAME)
    WRITE(NULOUT,9) 'IGRIB ',SIZE(YDRQGP%IGRIB),SHAPE(YDRQGP%IGRIB)
  ENDIF

!*       4. INITIALIZE
!           ----------

  IGP=1
  ISPA=0
  DO J=1, YDQTYPE%NFPOSDYN
    IJ=YDQTYPE%NFPTRDYN(J)
    INC=YDQTYPE%ILEV(IJ)
    LLSURF=LDSURF(IJ)
    IF ((YDQTYPE%ISF(IJ)>=1).AND.LLIOSPEC) THEN
!     Spectral array
      DO JL=1,INC
        ISPA=ISPA+1
        YDRQSP%ICOD(ISPA)=IJ
        YDRQSP%LLSURF(ISPA)=LLSURF
        YDRQSP%IVSETG(ISPA)=YDQTYPE%ISET(JL,IJ)      
        YDRQSP%IVLOCG(ISPA)=YDQTYPE%ILOC(JL,IJ) 
        YDRQSP%CLPREF(ISPA)(2:)=' '
        YDRQSP%IGRIB(ISPA)=KGRIB(IJ)
        IF (LLSURF) THEN
!         Surface fields
          YDRQSP%CLPREF(ISPA)=CDNAME(IJ)(1:4)
          YDRQSP%ZLEV(ISPA)=0.0_JPRB
          YDRQSP%CLNAME(ISPA)=CDNAME(IJ)(5:16)
        ELSE
!         Upper air fields
          YDRQSP%CLPREF(ISPA)(1:1)=CDCONF
          YDRQSP%ZLEV(ISPA)=PXLEV(YDQTYPE%ILVP(JL,IJ))
          SELECT CASE (CDCONF)
          CASE ('K')
!           Iso- surface can be compute either from the bottom (B) or from the top (T)
            IF (NINT(YDRQSP%ZLEV(ISPA)) < 0) THEN
              YDRQSP%CLPREF(ISPA)(2:)='T'
            ELSE
              YDRQSP%CLPREF(ISPA)(2:)='B'
            ENDIF
          END SELECT
          YDRQSP%CLNAME(ISPA)=CDNAME(IJ)(1:12)
        ENDIF
      ENDDO
    ELSE
!     Gridpoint arrays
      DO JL=1,INC
        YDRQGP%ICOD(IGP+JL-1)=IJ
        YDRQGP%LLSURF(IGP+JL-1)=LLSURF
        YDRQGP%CLPREF(IGP+JL-1)(2:)=' '
        YDRQGP%IGRIB(IGP+JL-1)=KGRIB(IJ)
        IF (LLSURF) THEN
!         Surface fields
          YDRQGP%CLPREF(IGP+JL-1)=CDNAME(IJ)(1:4)
          YDRQGP%ZLEV(IGP+JL-1)=0.0_JPRB
          YDRQGP%CLNAME(IGP+JL-1)=CDNAME(IJ)(5:16)
        ELSE
!         Upper air fields
          YDRQGP%CLPREF(IGP+JL-1)(1:1)=CDCONF
          YDRQGP%ZLEV(IGP+JL-1)=PXLEV(YDQTYPE%ILVP(JL,IJ))
          SELECT CASE (CDCONF)
          CASE ('K')
!           Iso- surface can be compute either from the bottom (B) or from the top (T)
            IF (NINT(YDRQGP%ZLEV(IGP+JL-1)) < 0) THEN
              YDRQGP%CLPREF(IGP+JL-1)(2:)='T'
            ELSE
              YDRQGP%CLPREF(IGP+JL-1)(2:)='B'
            ENDIF
          END SELECT
          YDRQGP%CLNAME(IGP+JL-1)=CDNAME(IJ)(1:12)
        ENDIF
        YDRQGP%IDOM(IGP+JL-1)=YDQTYPE%IDOM(JL,IJ)
        DO JD=1,YDQTYPE%IDOM(JL,IJ)
          YDRQGP%IDMP(JD,IGP+JL-1)=YDQTYPE%IDMP(JD,JL,IJ)
        ENDDO
        DO JD=YDQTYPE%IDOM(JL,IJ)+1,KFPDOM
          YDRQGP%IDMP(JD,IGP+JL-1)=0
        ENDDO
      ENDDO
      IGP=IGP+INC
    ENDIF 
  ENDDO

  IF (ISPA /= YDRQSP%NFIELDG) THEN
    WRITE(NULOUT,*) 'ISPA=', ISPA, 'NFIELDG=',YDRQSP%NFIELDG
    CALL ABOR1('SUVFPOSL : INTERNAL ERROR ISPA/NFIELDG')
  ELSEIF (IGP-1 /= YDRQGP%NFIELDG) THEN
    WRITE(NULOUT,*) 'IGP=', IGP, 'NFIELDG=',YDRQGP%NFIELDG
    CALL ABOR1('SUVFPOSL : INTERNAL ERROR IGP/NFIELDG')
  ENDIF

ELSE

!*       5. DEALLOCATIONS
!           -------------

  DEALLOCATE(YDRQGP%ICOD,YDRQGP%LLSURF,YDRQGP%ZLEV,YDRQGP%IDOM,YDRQGP%IDMP)
  DEALLOCATE(YDRQSP%ICOD,YDRQSP%LLSURF,YDRQSP%ZLEV)
  DEALLOCATE(YDRQSP%IVSETG,YDRQSP%IVLOCG)
  DEALLOCATE(YDRQSP%CLPREF,YDRQSP%CLNAME,YDRQSP%IGRIB)
  DEALLOCATE(YDRQGP%CLPREF,YDRQGP%CLNAME,YDRQGP%IGRIB)

ENDIF

! ---------------------------------------------------------------------
9 FORMAT(1X,'ARRAY ',A10,' ALLOCATED ',3I8)

IF (LHOOK) CALL DR_HOOK('SUVFPOSL',1,ZHOOK_HANDLE)
END SUBROUTINE SUVFPOSL
