! (C) Copyright 1989- Meteo-France.

SUBROUTINE WRGP2FAFP (YDFPGEO,KFPDOM, YDFPOPH, YDVAB,YDFPUSERGEO, PGPBUFL, YDFLDSC, YDFACTX, YDFACTXS,&
                    & KSIZPK, KSIZEG, KSIZEGS, KTAG, LDNORM, CDFPFN, KFPCHKDAT)

!**** *WRGP2FAFP*  - Compress and write a set of post-processed grid-point fields 

!            KFPDOM : number of subdomains
!            LDNORM : TRUE if norms to be computed here
!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 11-09-2012

!     Modifications :

!     Modifications.
!     --------------
!      R. El Khatib 27-Sep-2013 LFPBOYD => NFPBOYD
!      P. Marguinaud : 10-10-2013 : Use FACTX
!      T. Wilhelmsson and K. Yessad (Oct 2013) Geometry and setup refactoring.
!      R. El Khatib 04-Aug-2014 Pruning of the conf. 927/928
!      R. El Khatib 20-Nov-2015 Optional argument LDNORM, CDFPFN
!-------------------------------------------------------------------------------

USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
USE TYPE_FAOPH, ONLY : TFAOPH
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMVERT  , ONLY : TVAB
USE PARKIND1, ONLY : JPRB, JPIM
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE YOMTAG, ONLY : MTAGDISTGP
USE YOMFPGEO, ONLY : TFPGEO
USE YOMMP0, ONLY : MYPROC, NSTROUT, NPROC

USE FPGPNORM_MOD, ONLY : FPGPNORMX

USE MFIOOPTS_MOD, ONLY : MFIOOPTS

USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE IOCPTDESC_MOD, ONLY : IOCPTDESC

USE FACTX_MOD, ONLY : FACTX

IMPLICIT NONE

TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO
INTEGER(KIND=JPIM), INTENT(IN)                :: KFPDOM
TYPE (TFAOPH)     ,  INTENT (IN)              :: YDFPOPH(KFPDOM)
TYPE(TVAB)        ,  INTENT (IN)              :: YDVAB
TYPE (TFPUSERGEO) ,  INTENT (IN)              :: YDFPUSERGEO(KFPDOM)
REAL (KIND=JPRB),    INTENT (IN)              :: PGPBUFL (:,:)
TYPE (IOFLDDESC),    INTENT (IN)              :: YDFLDSC(:)
TYPE (FACTX),        INTENT (INOUT), OPTIONAL :: YDFACTX
TYPE (FACTX),        INTENT (INOUT), OPTIONAL :: YDFACTXS (KFPDOM)
INTEGER (KIND=JPIM), INTENT (IN),    OPTIONAL :: KSIZPK
INTEGER (KIND=JPIM), INTENT (IN),    OPTIONAL :: KSIZEG
INTEGER (KIND=JPIM), INTENT (IN),    OPTIONAL :: KSIZEGS (KFPDOM)
INTEGER (KIND=JPIM), INTENT (IN),    OPTIONAL :: KTAG
LOGICAL,             INTENT (IN),    OPTIONAL :: LDNORM
CHARACTER(LEN=*)    ,INTENT (IN),    OPTIONAL :: CDFPFN(KFPDOM)
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPCHKDAT

#include "sumpioh.intfb.h"
#include "prepacka.intfb.h"
#include "wrgathflnm.intfb.h"
#include "abor1.intfb.h"
#include "diwrgrfp.intfb.h"


!     ZGPBUFG: extracted and sorted fields for the local set of fields
!     ZAVEL  : mean    values per domain for the local set of fields
!     ZMINL  : minimum values per domain for the local set of fields
!     ZMAXL  : maximum values per domain for the local set of fields
!     CLNMAL : fields names for the local set of fields
!     ILOGAL : actual length of fields for the local set of fields
!     INOMAL : actual length of a field name for the local set of fields
!     IZVAL: number of points in the global output array to be written
!               out on file(s), overdimensionned by 2 for safety 
!               while packing. 
!     INFD   : number of fields in the current chunk for each processor
!     IFLDOFF: fields offset after distribution among NSTROUT procs.
!     INFL   : local number of fields


REAL (KIND=JPRB),     ALLOCATABLE :: ZGPBUFG (:,:)
REAL (KIND=JPRB),     ALLOCATABLE :: ZVALCO (:,:)
TYPE (IOCPTDESC),     ALLOCATABLE :: YLCPDSC (:,:)

INTEGER (KIND=JPIM) :: INFD (NPROC), IFLDOFF (NPROC)
INTEGER (KIND=JPIM) :: INFL, INFG
INTEGER (KIND=JPIM) :: IZVAL
INTEGER (KIND=JPIM) :: JDOM, JF
INTEGER (KIND=JPIM) :: JFLDG1, JFLDG2
TYPE (MFIOOPTS)     :: YLOPTS
INTEGER (KIND=JPIM) :: IPTR (KFPDOM)
INTEGER (KIND=JPIM) :: ISIZEGS (KFPDOM)
TYPE (FACTX)        :: YLFACTXS (KFPDOM)
LOGICAL :: LLNORM

INTEGER (KIND=JPIM) :: IMASK(SIZE(YDFLDSC),KFPDOM)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRGP2FAFP',0,ZHOOK_HANDLE)
ASSOCIATE(NFPRGPLX=>YDFPGEO%NFPRGPLX, NFPRGPL=>YDFPGEO%NFPRGPL, NFPRGPNUM=>YDFPGEO%NFPRGPNUM, &
 & NFPRGPIND=>YDFPGEO%NFPRGPIND)

IF ((.NOT. (PRESENT (YDFACTXS) .AND. PRESENT (KSIZEGS))) .AND. (KFPDOM > 1)) THEN

  CALL ABOR1 ('WRGP2FAFP: KFPDOM > 1 DEMANDS ALL ARGUMENTS')

ENDIF

IF (PRESENT (YDFACTXS)) THEN
  YLFACTXS = YDFACTXS
ELSEIF (PRESENT (YDFACTX)) THEN
  YLFACTXS = YDFACTX
ELSE
  CALL ABOR1 ('WRGP2FAFP: YDFACTX IS REQUIRED')
ENDIF

IF (PRESENT (KSIZEGS)) THEN
  ISIZEGS = KSIZEGS
ELSEIF (PRESENT (KSIZEG)) THEN
  ISIZEGS = KSIZEG
ELSE
  CALL ABOR1 ('WRGP2FAFP: KSIZEG IS REQUIRED')
ENDIF

INFG = SIZE (PGPBUFL, 2)

IF (INFG == 0) THEN
  IF (LHOOK) CALL DR_HOOK ('WRGP2FAFP',1,ZHOOK_HANDLE)
  RETURN
ENDIF

IZVAL = MAXVAL (YDFLDSC%NSIZPK)

YLOPTS = YLFACTXS (1)%YIOOPTS

CALL SUMPIOH (NPROC,NSTROUT,INFG,INFD,IFLDOFF)

INFL = INFD (MYPROC)

ALLOCATE (ZGPBUFG (IZVAL, INFL))

CALL DIWRGRFP (MTAGDISTGP, INFG, IZVAL, NFPRGPL, NFPRGPLX, INFL,&
 & NFPRGPIND, NFPRGPNUM, INFD, IFLDOFF, PGPBUFL, ZGPBUFG)

! "I/O" PROCESSORS ARE PRECONDITIONNING DATA 

ALLOCATE (YLCPDSC (INFL, KFPDOM))


JFLDG1 = IFLDOFF(MYPROC)+1
JFLDG2 = IFLDOFF(MYPROC)+INFL

IPTR(1)=1
DO JDOM = 2, KFPDOM
  IPTR(JDOM)=IPTR(JDOM-1)+ISIZEGS(JDOM-1)
ENDDO

IMASK(:,:)=0
DO JDOM=1,KFPDOM
  DO JF=1,SIZE(YDFLDSC)
    IMASK(JF,JDOM)=IBITS(YDFLDSC(JF)%IFPMASK, JDOM-1, 1)
  ENDDO
ENDDO

IF (PRESENT(LDNORM)) THEN
  LLNORM=LDNORM
ELSE
  LLNORM=.FALSE.
ENDIF

IF (LLNORM) THEN
  DO JDOM = 1, KFPDOM
    CALL FPGPNORMX (ZGPBUFG(IPTR(JDOM):IPTR(JDOM)+ISIZEGS(JDOM)-1,:),&
                  & YLCPDSC (:,JDOM)%ZAVE, YLCPDSC (:,JDOM)%ZMIN, YLCPDSC (:,JDOM)%ZMAX,&
                  & LDUNDF=YDFLDSC (JFLDG1:JFLDG2)%LUNDF,&
                  & PUNDEF=YDFLDSC (JFLDG1:JFLDG2)%XUNDF,&
                  & KMASK=IMASK(JFLDG1:JFLDG2,JDOM), PEPSILON=EPSILON(1._JPRB))
  ENDDO
ENDIF

ALLOCATE (ZVALCO (IZVAL, INFL))

JFLDG1 = IFLDOFF(MYPROC)+1
JFLDG2 = IFLDOFF(MYPROC)+INFL

CALL PREPACKA (YLFACTXS, KFPDOM, YDFLDSC(JFLDG1:JFLDG2), INFL, IMASK(JFLDG1:JFLDG2,1:KFPDOM),&
             & YLCPDSC, IPTR, ISIZEGS, YDFPOPH,PFIELD=ZGPBUFG, PVALCO=ZVALCO)

CALL WRGATHFLNM(YDVAB,KFPDOM, INFL, IZVAL, INFD, IFLDOFF, ZVALCO, YLCPDSC, YDFPOPH, CDFPFN, &
               & KPTR=IPTR, KMASK=IMASK(JFLDG1:JFLDG2,1:KFPDOM), LDNORM=LLNORM,&
               & YDFACTXS=YLFACTXS, CDNORMTITLE='FULL-POS GPNORMS', KTAG=KTAG, &
               & CDDOMNAMES=YDFPUSERGEO%CFPDOM,YDFPUSERGEO=YDFPUSERGEO,KFPCHKDAT=KFPCHKDAT)

DEALLOCATE (ZVALCO)

DEALLOCATE (YLCPDSC)

DEALLOCATE (ZGPBUFG)

IF (PRESENT (YDFACTXS)) THEN
  YDFACTXS = YLFACTXS
ELSEIF (PRESENT (YDFACTX)) THEN
  YDFACTX = YLFACTXS (1)
ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK ('WRGP2FAFP',1,ZHOOK_HANDLE)

END SUBROUTINE WRGP2FAFP
