! (C) Copyright 1989- Meteo-France.

SUBROUTINE WRMLFP_IO_SERV(YDRQSP,YDRQGP,YDGEOMETRY,YDSURF,YDECLDP,YDEPHY,YDRQPHY,KFPRGPL,KFPRGPG, &
 & KFPROMA,KSPEC2,KSPEC2G,CDCONF, &
 & LDLAG,LDOCE,PFPBUF,PTSTEP,PSPEC)

!**** *WRMLFP_IO_SERV*  - writes out the model level and sfc fields in GRIB

!     Purpose.
!     --------
!     Write out the model level and sfc fields in GRIB

!**   Interface.
!     ----------
!        *CALL* *WRMLFP_IO_SERV(...)

!        Explicit arguments :     CDCONF - configuration of call
!        --------------------     LDLAG - TRUE if called in "lagged" mode

USE YOECLDP      , ONLY : TECLDP
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMMP0   , ONLY : NPROC, MYSETV
USE YOMCT0   , ONLY : NCONF    ,LOBSC1
USE YOEPHY   , ONLY : TEPHY
USE YOMVAR   , ONLY : LTWBGV   ,LTWCGL  
USE YOMFP4L            , ONLY : TRQFP
USE MPL_MODULE, ONLY : MPL_BARRIER
USE IOSPECE_MOD,  ONLY : IOSPECE_ML_SELECTF,  IOSPECE_ML_SELECTD,  IOSPECE_ML_COUNT
USE IOGRIDE_MOD,  ONLY : IOGRIDE_SELECTF,     IOGRIDE_SELECTD,     IOGRIDE_COUNT
USE IOGRIDUE_MOD, ONLY : IOGRIDUE_ML_SELECTF, IOGRIDUE_ML_SELECTD, IOGRIDUE_ML_COUNT
USE IOGRIDOE_MOD, ONLY : IOGRIDOE_SELECTF,    IOGRIDOE_SELECTD,    IOGRIDOE_COUNT
USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE YOMIO_SERV_MAP_PLAN, ONLY : IO_SERV_SEND_PLAN
USE YOMIO_SERV, ONLY : IO_SERV_C001
USE YOMCT3,     ONLY : NSTEP
IMPLICIT NONE

TYPE (TRQFP),  INTENT(IN) :: YDRQSP
TYPE (TRQFP),  INTENT(IN) :: YDRQGP
TYPE(GEOMETRY)  ,INTENT(IN)    :: YDGEOMETRY
TYPE(TSURF)     ,INTENT(IN)    :: YDSURF
TYPE(TECLDP)    ,INTENT(IN) :: YDECLDP
TYPE(TEPHY)     ,INTENT(IN) :: YDEPHY
TYPE (TRQFP),  INTENT(IN) :: YDRQPHY
INTEGER (KIND=JPIM),INTENT(IN) :: KFPRGPL
INTEGER (KIND=JPIM),INTENT(IN) :: KFPRGPG
INTEGER (KIND=JPIM),INTENT(IN) :: KFPROMA
INTEGER (KIND=JPIM),INTENT(IN) :: KSPEC2
INTEGER (KIND=JPIM),INTENT(IN) :: KSPEC2G
CHARACTER(LEN=1),INTENT(IN)    :: CDCONF 
LOGICAL         ,INTENT(IN)    :: LDLAG
LOGICAL         ,INTENT(IN)    :: LDOCE
REAL(KIND=JPRB) ,INTENT(IN)    :: PFPBUF(:,:,:)
REAL(KIND=JPRB) ,INTENT(IN), OPTIONAL :: PTSTEP
REAL(KIND=JPRB) ,INTENT(IN), OPTIONAL :: PSPEC(:,:)

#include "io_serv_map_send_part1.intfb.h"
#include "io_serv_map_send_part2.intfb.h"
#include "io_serv_log.intfb.h"

! Spectral

INTEGER (KIND=JPIM), PARAMETER :: ITAG_ECIO_WRSPECE_ML = 100000

TYPE (IO_SERV_SEND_PLAN) :: YLIOSMPP_SP
TYPE (IOFLDDESC), ALLOCATABLE :: YLFLDSC_SP_L (:), YLFLDSC_SP_G (:)

INTEGER (KIND=JPIM) :: IFNUM_SP_L, IFNUM_SP_G, IFNUM_SP_O

! Grid-point

INTEGER (KIND=JPIM), PARAMETER :: ITAG_ECIO_WRGRIDE_ML = 100001

TYPE (IO_SERV_SEND_PLAN) :: YLIOSMPP_GP
TYPE (IOFLDDESC), ALLOCATABLE :: YLFLDSC_GP (:)
INTEGER (KIND=JPIM) :: IFNUM_GRE, IFNUM_GRUE, IFNUM_GROE, IFNUM_GP, IFCUR, ITAG

REAL (KIND=JPRB) :: ZIOPROC1, ZIOPROC2

LOGICAL :: LLDYN, LLPHY
CHARACTER(LEN=128)               :: CLMESS
  
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('WRMLFP_IO_SERV',0,ZHOOK_HANDLE)

LLDYN=CDCONF /= 'I'
LLPHY=CDCONF == 'I'

IF (YDRQSP%NFIELDG > 0.AND.LLDYN .AND. .NOT. LDLAG) THEN

! Reckon the total number of spectral fields

  IFNUM_SP_G = 0
  CALL IOSPECE_ML_COUNT (YDRQSP%NFIELDG,IFNUM_SP_G)

  IF (IFNUM_SP_G > 0) THEN

! Retrieve global descriptors list

    ALLOCATE (YLFLDSC_SP_G (IFNUM_SP_G))
    CALL IOSPECE_ML_SELECTD (YDRQSP,KSPEC2G,YLFLDSC_SP_G)

! Number of fields and field offset for current vset

    IFNUM_SP_L = COUNT (YLFLDSC_SP_G%IVSET == MYSETV)
    IFNUM_SP_O = COUNT (YLFLDSC_SP_G%IVSET < MYSETV)
    
    IF (IFNUM_SP_L > 0) THEN

! Get descriptors list of fields on current vset

      ALLOCATE (YLFLDSC_SP_L (IFNUM_SP_L))
      YLFLDSC_SP_L = PACK (YLFLDSC_SP_G, YLFLDSC_SP_G%IVSET == MYSETV)

! Range of IO tasks to address

      ZIOPROC1 = REAL (IFNUM_SP_O, JPRB) / REAL (IFNUM_SP_G, JPRB)
      ZIOPROC2 = REAL (IFNUM_SP_O + IFNUM_SP_L, JPRB) / REAL (IFNUM_SP_G, JPRB)

! Allocate buffers & encode descriptors

      CALL IO_SERV_MAP_SEND_PART1(IO_SERV_C001,KSPEC2,KSPEC2G,YLFLDSC_SP_L,ITAG_ECIO_WRSPECE_ML,YLIOSMPP_SP, &
 &                                PIOPROC1=ZIOPROC1,PIOPROC2=ZIOPROC2,PTSTEP=PTSTEP)

! Fill field buffers

      CALL IOSPECE_ML_SELECTF (PSPEC,YLIOSMPP_SP%YLBUFD, YLFLDSC_SP_L)

! Send to IO server

      CALL IO_SERV_MAP_SEND_PART2 (IO_SERV_C001, YLIOSMPP_SP)

      DEALLOCATE (YLFLDSC_SP_L)

    ENDIF

  ENDIF

  DEALLOCATE (YLFLDSC_SP_G)

ENDIF

! Reckon number of grid-point fields

IFNUM_GRE = 0

IF ( LLPHY.AND.(.NOT.(LTWBGV.OR.LTWCGL).AND.((&
   & YDEPHY%LEPHYS).OR.LOBSC1.OR.NCONF == 131)) ) THEN  
  CALL IOGRIDE_COUNT(YDGEOMETRY%YRGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,IFNUM_GRE)
ENDIF

IFNUM_GRUE = 0

IF (LLDYN.AND.YDRQGP%NFIELDG > 0 .AND. .NOT. LDLAG) THEN
  CALL IOGRIDUE_ML_COUNT(YDRQGP,YDGEOMETRY%YRGEM,YDECLDP,KFPRGPL,KFPROMA,IFNUM_GRUE)
ENDIF

IFNUM_GP = IFNUM_GRE+IFNUM_GRUE

IF (IFNUM_GP > 0) THEN

! Allocate & retrieve field descriptors

  ALLOCATE (YLFLDSC_GP (IFNUM_GP))

  IFCUR = 0

  IF (IFNUM_GRE  > 0) CALL IOGRIDE_SELECTD(YDGEOMETRY%YRGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,YLFLDSC_GP,KFCUR=IFCUR)
  IF (IFNUM_GRUE > 0) CALL IOGRIDUE_ML_SELECTD(YDRQGP,YDGEOMETRY%YRGEM,YDECLDP,KFPRGPL,KFPROMA,YLFLDSC_GP,KFCUR=IFCUR)

! Allocate buffers & encode field descriptors

  ITAG = ITAG_ECIO_WRGRIDE_ML
  IF(LDLAG) ITAG = ITAG_ECIO_WRGRIDE_ML+10
  IF(LDOCE) ITAG = ITAG_ECIO_WRGRIDE_ML+20
  IF(IFNUM_GRUE > 0) ITAG = ITAG+100
  WRITE (CLMESS, '("WRMLFP IFNUM_GRE ",I4," IFNUM_GRUE ",I4," ITAG ",I8," NSTEP",i4)')&
   & IFNUM_GRE,IFNUM_GRUE,ITAG,NSTEP
  CALL IO_SERV_LOG (IO_SERV_C001, 'message text="'//CLMESS//'"')

  CALL IO_SERV_MAP_SEND_PART1(IO_SERV_C001,KFPRGPL,KFPRGPG,YLFLDSC_GP,ITAG,YLIOSMPP_GP,PTSTEP=PTSTEP)

! Fill grid-point buffers

  IFCUR = 0

  IF (IFNUM_GRE  > 0) THEN
    CALL IOGRIDE_SELECTF(YDGEOMETRY%YRGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,YLIOSMPP_GP%YLBUFD,PFPBUF,YLFLDSC_GP,&
   & KFCUR=IFCUR)
  ENDIF
  IF (IFNUM_GRUE > 0) THEN
    CALL IOGRIDUE_ML_SELECTF(YDRQGP,YDGEOMETRY%YRGEM,YDECLDP,KFPRGPL,KFPROMA,YLIOSMPP_GP%YLBUFD,PFPBUF, YLFLDSC_GP, KFCUR=IFCUR)
  ENDIF

! Send to IO server

  CALL IO_SERV_MAP_SEND_PART2 (IO_SERV_C001, YLIOSMPP_GP)

  DEALLOCATE (YLFLDSC_GP)

ENDIF

! Reckon number of grid-point fields from the ocean

IFNUM_GROE = 0
IF (LDLAG.OR.LDOCE) THEN
  CALL IOGRIDOE_COUNT(YDGEOMETRY,YDSURF,IFNUM_GROE)
ENDIF

IFNUM_GP = IFNUM_GROE

IF (IFNUM_GP > 0) THEN

! Allocate & retrieve field descriptors

  ALLOCATE (YLFLDSC_GP (IFNUM_GP))

  IFCUR = 0

  IF (IFNUM_GROE > 0) CALL IOGRIDOE_SELECTD(YDGEOMETRY,YDSURF,YLFLDSC_GP, KFCUR=IFCUR)

! Allocate buffers & encode field descriptors

  ITAG = ITAG_ECIO_WRGRIDE_ML
  IF(LDLAG) ITAG = ITAG_ECIO_WRGRIDE_ML+10
  IF(LDOCE) ITAG = ITAG_ECIO_WRGRIDE_ML+20
  IF(IFNUM_GROE > 0) ITAG = ITAG+1000
  WRITE (CLMESS, '("WRMLFP IFNUM_GROE ",I4," ITAG ",I8," NSTEP",i4)')&
   & IFNUM_GROE,ITAG,NSTEP
  CALL IO_SERV_LOG (IO_SERV_C001, CLMESS)

  CALL IO_SERV_MAP_SEND_PART1(IO_SERV_C001,KFPRGPL,KFPRGPG,YLFLDSC_GP,ITAG,YLIOSMPP_GP,PTSTEP=PTSTEP)

! Fill grid-point buffers

  IFCUR = 0

  IF (IFNUM_GROE > 0) CALL IOGRIDOE_SELECTF(YDGEOMETRY,YDSURF,YLIOSMPP_GP%YLBUFD, YLFLDSC_GP, KFCUR=IFCUR)

! Send to IO server

  CALL IO_SERV_MAP_SEND_PART2 (IO_SERV_C001, YLIOSMPP_GP)

  DEALLOCATE (YLFLDSC_GP)

ENDIF

IF( NPROC > 1 )THEN
  CALL GSTATS(792,0)
  CALL MPL_BARRIER(CDSTRING='WRMLFP_IO_SERV:')
  CALL GSTATS(792,1)
ENDIF

IF (LHOOK) CALL DR_HOOK('WRMLFP_IO_SERV',1,ZHOOK_HANDLE)

END SUBROUTINE WRMLFP_IO_SERV

