! (C) Copyright 1989- Meteo-France.

!OPTIONS XOPT(NOEVAL)
SUBROUTINE SUPHY1(YDPHY1,YDVDOZ,KULOUT)

!**** *SUPHY1*   - Initialize common YOMPHY1 physics land surface
!                  constants

!     Purpose.
!     --------
!           Initialize YOMPHY1, the common that contains the parameters
!           for the land surface part of the physics of the model.

!**   Interface.
!     ----------
!        *CALL* *SUPHY1(...)

!        Explicit arguments :
!        --------------------
!        KULOUT : Logical unit for the output

!        Implicit arguments :
!        --------------------
!        COMMON YOMPHY1

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------

!     Reference.
!     ----------
!        Documentation ARPEGE

!     Author.
!     -------
!      J.-F. Geleyn .
!      Original : 90-9-1

!     Modifications.
!     --------------
!      Modified by E. Bazile   : 02-10-29 Defaults for the snow scheme LVGSN.
!      Modified by E. Bazile   : 04-02-24 Introduce NCHSP.
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      K. Yessad (Jan 2010): remove useless variables.
!      A. Alias  (Oct 2010): Introduction of LALBMERCLIM.
!      M. Dian   (May 2016): Introduction of LCLS_HS, ACLS_HS.
!     ------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM     ,JPRB
USE YOMHOOK  , ONLY : LHOOK    ,DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULNAM
USE YOMCST   , ONLY : RPI      ,RDAY     ,RG       ,RCS
!YT USE SURFACE_FIELDS_MIX , ONLY : YRSURF
USE YOMCT0   , ONLY : LECMWF
USE YOMPHY1  , ONLY : TPHY1
USE YOMVDOZ  , ONLY : TVDOZ

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(TPHY1)       ,INTENT(INOUT),TARGET :: YDPHY1
TYPE(TVDOZ)       ,INTENT(INOUT),TARGET :: YDVDOZ
INTEGER(KIND=JPIM),INTENT(IN)           :: KULOUT 

!     ------------------------------------------------------------------

INTEGER(KIND=JPIM) :: IVEG, J
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "abor1.intfb.h"
#include "posnam.intfb.h"

REAL(KIND=JPRB) , POINTER ::  ALB1
REAL(KIND=JPRB) , POINTER ::  RZ0GLA
REAL(KIND=JPRB) , POINTER ::  GC1
REAL(KIND=JPRB) , POINTER ::  HSOL
REAL(KIND=JPRB) , POINTER ::  GVEGMX
REAL(KIND=JPRB) , POINTER ::  RZHZ0G
REAL(KIND=JPRB) , POINTER ::  RHOMIN
REAL(KIND=JPRB) , POINTER ::  GC1Y1
REAL(KIND=JPRB) , POINTER ::  XCRINR
REAL(KIND=JPRB) , POINTER ::  G1CGSAT
REAL(KIND=JPRB) , POINTER ::  GC3
REAL(KIND=JPRB) , POINTER ::  RTINER
REAL(KIND=JPRB) , POINTER ::  TOEXP
REAL(KIND=JPRB) , POINTER ::  GWFC
REAL(KIND=JPRB) , POINTER ::  G2CGSAT
REAL(KIND=JPRB) , POINTER ::  GCGEL
REAL(KIND=JPRB) , POINTER ::  GC31
REAL(KIND=JPRB) , POINTER ::  ALBGLA
REAL(KIND=JPRB) , POINTER ::  GWLMX
REAL(KIND=JPRB) , POINTER ::  RLAI
REAL(KIND=JPRB) , POINTER ::  G1P
REAL(KIND=JPRB) , POINTER ::  RHOMAX
REAL(KIND=JPRB) , POINTER ::  HSOLIT0
REAL(KIND=JPRB) , POINTER ::  RD2GLA
REAL(KIND=JPRB) , POINTER ::  GC1S4
REAL(KIND=JPRB) , POINTER ::  G2C1SAT
REAL(KIND=JPRB) , POINTER ::  ALBMAX
REAL(KIND=JPRB) , POINTER ::  RCGMAX
REAL(KIND=JPRB) , POINTER ::  G1C1SAT
REAL(KIND=JPRB) , POINTER ::  EMCRIN
REAL(KIND=JPRB) , POINTER ::  GC32
REAL(KIND=JPRB) , POINTER ::  G2P
REAL(KIND=JPRB) , POINTER ::  GA
REAL(KIND=JPRB) , POINTER ::  GLAIMX
REAL(KIND=JPRB) , POINTER ::  SODELX(:)
REAL(KIND=JPRB) , POINTER ::  RCTGLA
LOGICAL, POINTER ::  LCLS_HS
REAL(KIND=JPRB) , POINTER ::  ACLS_HS
REAL(KIND=JPRB) , POINTER ::  TOLIN
REAL(KIND=JPRB) , POINTER ::  RLAIMX
REAL(KIND=JPRB) , POINTER ::  WCRINC
REAL(KIND=JPRB) , POINTER ::  EMMGLA
INTEGER(KIND=JPIM) , POINTER ::  NCHSP
REAL(KIND=JPRB) , POINTER ::  GC1S3
LOGICAL , POINTER ::  LIMW
REAL(KIND=JPRB) , POINTER ::  HSOLIWR
REAL(KIND=JPRB) , POINTER ::  GNEIMXS
REAL(KIND=JPRB) , POINTER ::  GCGELS
REAL(KIND=JPRB) , POINTER ::  GVEGMXS
REAL(KIND=JPRB) , POINTER ::  GLAIMXS
REAL(KIND=JPRB) , POINTER ::  GSNC1
LOGICAL , POINTER ::  LC1VAP
REAL(KIND=JPRB) , POINTER ::  EWFC
REAL(KIND=JPRB) , POINTER ::  GWWILT
REAL(KIND=JPRB) , POINTER ::  OMTPRO
REAL(KIND=JPRB) , POINTER ::  GC1S2
REAL(KIND=JPRB) , POINTER ::  RZ0MER
REAL(KIND=JPRB) , POINTER ::  ALRCN2
REAL(KIND=JPRB) , POINTER ::  RD1
REAL(KIND=JPRB) , POINTER ::  RD2MER
REAL(KIND=JPRB) , POINTER ::  RC1MAX
REAL(KIND=JPRB) , POINTER ::  RCTVEG(:)
INTEGER(KIND=JPIM) , POINTER ::  NTVGLA
REAL(KIND=JPRB) , POINTER ::  GSNC2
REAL(KIND=JPRB) , POINTER ::  GF3(:)
REAL(KIND=JPRB) , POINTER ::  GF4(:)
REAL(KIND=JPRB) , POINTER ::  ALBMER
REAL(KIND=JPRB) , POINTER ::  XCRINV
REAL(KIND=JPRB) , POINTER ::  EMMMER
INTEGER(KIND=JPIM) , POINTER ::  NTVMER
REAL(KIND=JPRB) , POINTER ::  GC1S1
REAL(KIND=JPRB) , POINTER ::  GTSVAP
REAL(KIND=JPRB) , POINTER ::  G3CGSAT
REAL(KIND=JPRB) , POINTER ::  EA
REAL(KIND=JPRB) , POINTER ::  ALRCN1
REAL(KIND=JPRB) , POINTER ::  ALBMIN
REAL(KIND=JPRB) , POINTER ::  TREF4(:)
REAL(KIND=JPRB) , POINTER ::  G2B
REAL(KIND=JPRB) , POINTER ::  G1B
REAL(KIND=JPRB) , POINTER ::  WSMX
REAL(KIND=JPRB) , POINTER ::  EC2REF
REAL(KIND=JPRB) , POINTER ::  GNEIMX
REAL(KIND=JPRB) , POINTER ::  GWPIMX
REAL(KIND=JPRB) , POINTER ::  GCZ0H(:,:)
REAL(KIND=JPRB) , POINTER ::  WPMX
REAL(KIND=JPRB) , POINTER ::  WNEW
REAL(KIND=JPRB) , POINTER ::  RSMAX
REAL(KIND=JPRB) , POINTER ::  TMERGL
REAL(KIND=JPRB) , POINTER ::  RGL(:)
REAL(KIND=JPRB) , POINTER ::  ALCRIN
REAL(KIND=JPRB) , POINTER ::  OMWPRO
REAL(KIND=JPRB) , POINTER ::  G2WSAT
REAL(KIND=JPRB) , POINTER ::  GWLEX
REAL(KIND=JPRB) , POINTER ::  ALB2
LOGICAL , POINTER ::  LALBMERCLIM
REAL(KIND=JPRB) , POINTER ::  WCRIN
REAL(KIND=JPRB) , POINTER ::  GC2REF
REAL(KIND=JPRB) , POINTER ::  G1WSAT
REAL(KIND=JPRB) , POINTER ::  EWWILT
REAL(KIND=JPRB) , POINTER ::  RZHZ0M
LOGICAL , POINTER ::  LIMC
REAL(KIND=JPRB) , POINTER ::  GF1
REAL(KIND=JPRB) , POINTER ::  WCRING
REAL(KIND=JPRB) , POINTER ::  GC2
#include "namphy1.nam.h"

REAL(KIND=JPRB) , POINTER ::  VDPJS(:)
REAL(KIND=JPRB) , POINTER ::  VDHNS(:)
REAL(KIND=JPRB) , POINTER ::  VDEJS(:)
REAL(KIND=JPRB) , POINTER ::  VDHNH(:)
REAL(KIND=JPRB) , POINTER ::  VOZNJ
REAL(KIND=JPRB) , POINTER ::  VDPJH(:)
REAL(KIND=JPRB) , POINTER ::  VDENS(:)
REAL(KIND=JPRB) , POINTER ::  VDPNS(:)
REAL(KIND=JPRB) , POINTER ::  VDPNH(:)
LOGICAL , POINTER ::  LRDIFOZ
REAL(KIND=JPRB) , POINTER ::  VOZHS
REAL(KIND=JPRB) , POINTER ::  VDAJH(:)
LOGICAL , POINTER ::  LRDEPOZ
REAL(KIND=JPRB) , POINTER ::  VDANH(:)
REAL(KIND=JPRB) , POINTER ::  VDHJH(:)
REAL(KIND=JPRB) , POINTER ::  VDAJS(:)
REAL(KIND=JPRB) , POINTER ::  VDANS(:)
REAL(KIND=JPRB) , POINTER ::  VDNJS(:)
REAL(KIND=JPRB) , POINTER ::  VDEJH(:)
REAL(KIND=JPRB) , POINTER ::  VDNNH(:)
REAL(KIND=JPRB) , POINTER ::  VDENH(:)
REAL(KIND=JPRB) , POINTER ::  VDHJS(:)
REAL(KIND=JPRB) , POINTER ::  VDNJH(:)
REAL(KIND=JPRB) , POINTER ::  VDNNS(:)
#include "namvdoz.nam.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SUPHY1',0,ZHOOK_HANDLE)
ASSOCIATE(GCONV=>YDPHY1%GCONV,  ALBMED=>YDPHY1%ALBMED &
! & , YSD_VVD=>YRSURF%YSD_VVD, YSP_SBD=>YRSURF%YSP_SBD, &
 & )
EWWILT => YDPHY1%EWWILT
GWLEX => YDPHY1%GWLEX
RD2GLA => YDPHY1%RD2GLA
GNEIMX => YDPHY1%GNEIMX
GC1S2 => YDPHY1%GC1S2
GC1S1 => YDPHY1%GC1S1
GC1S4 => YDPHY1%GC1S4
TREF4 => YDPHY1%TREF4
WSMX => YDPHY1%WSMX
ALB1 => YDPHY1%ALB1
WCRINC => YDPHY1%WCRINC
ALB2 => YDPHY1%ALB2
WCRING => YDPHY1%WCRING
RLAI => YDPHY1%RLAI
HSOL => YDPHY1%HSOL
WPMX => YDPHY1%WPMX
RZ0GLA => YDPHY1%RZ0GLA
GA => YDPHY1%GA
G1C1SAT => YDPHY1%G1C1SAT
GNEIMXS => YDPHY1%GNEIMXS
GCZ0H => YDPHY1%GCZ0H
G1CGSAT => YDPHY1%G1CGSAT
GWLMX => YDPHY1%GWLMX
RD2MER => YDPHY1%RD2MER
G2P => YDPHY1%G2P
RTINER => YDPHY1%RTINER
G2B => YDPHY1%G2B
NCHSP => YDPHY1%NCHSP
G2CGSAT => YDPHY1%G2CGSAT
NTVMER => YDPHY1%NTVMER
ALBMER => YDPHY1%ALBMER
RGL => YDPHY1%RGL
RLAIMX => YDPHY1%RLAIMX
EC2REF => YDPHY1%EC2REF
RSMAX => YDPHY1%RSMAX
OMTPRO => YDPHY1%OMTPRO
GC1 => YDPHY1%GC1
LALBMERCLIM => YDPHY1%LALBMERCLIM
GC3 => YDPHY1%GC3
GC2 => YDPHY1%GC2
G3CGSAT => YDPHY1%G3CGSAT
WNEW => YDPHY1%WNEW
EA => YDPHY1%EA
LIMW => YDPHY1%LIMW
RZHZ0M => YDPHY1%RZHZ0M
LIMC => YDPHY1%LIMC
RZHZ0G => YDPHY1%RZHZ0G
RC1MAX => YDPHY1%RC1MAX
SODELX => YDPHY1%SODELX
TOLIN => YDPHY1%TOLIN
G2C1SAT => YDPHY1%G2C1SAT
GC1S3 => YDPHY1%GC1S3
EMMGLA => YDPHY1%EMMGLA
HSOLIWR => YDPHY1%HSOLIWR
GVEGMXS => YDPHY1%GVEGMXS
GTSVAP => YDPHY1%GTSVAP
WCRIN => YDPHY1%WCRIN
RCTVEG => YDPHY1%RCTVEG
RD1 => YDPHY1%RD1
ALRCN2 => YDPHY1%ALRCN2
ALRCN1 => YDPHY1%ALRCN1
G1B => YDPHY1%G1B
GSNC1 => YDPHY1%GSNC1
GSNC2 => YDPHY1%GSNC2
GF3 => YDPHY1%GF3
HSOLIT0 => YDPHY1%HSOLIT0
G1P => YDPHY1%G1P
GF1 => YDPHY1%GF1
GLAIMX => YDPHY1%GLAIMX
GWFC => YDPHY1%GWFC
GCGELS => YDPHY1%GCGELS
XCRINV => YDPHY1%XCRINV
XCRINR => YDPHY1%XCRINR
GVEGMX => YDPHY1%GVEGMX
RCGMAX => YDPHY1%RCGMAX
NTVGLA => YDPHY1%NTVGLA
GC2REF => YDPHY1%GC2REF
ALCRIN => YDPHY1%ALCRIN
GF4 => YDPHY1%GF4
GC32 => YDPHY1%GC32
ALBMIN => YDPHY1%ALBMIN
GLAIMXS => YDPHY1%GLAIMXS
GCGEL => YDPHY1%GCGEL
ALBMAX => YDPHY1%ALBMAX
GC31 => YDPHY1%GC31
ALBGLA => YDPHY1%ALBGLA
EWFC => YDPHY1%EWFC
GC1Y1 => YDPHY1%GC1Y1
RHOMIN => YDPHY1%RHOMIN
RZ0MER => YDPHY1%RZ0MER
RHOMAX => YDPHY1%RHOMAX
G2WSAT => YDPHY1%G2WSAT
EMCRIN => YDPHY1%EMCRIN
EMMMER => YDPHY1%EMMMER
GWPIMX => YDPHY1%GWPIMX
G1WSAT => YDPHY1%G1WSAT
OMWPRO => YDPHY1%OMWPRO
TMERGL => YDPHY1%TMERGL
TOEXP => YDPHY1%TOEXP
GWWILT => YDPHY1%GWWILT
LC1VAP => YDPHY1%LC1VAP
RCTGLA => YDPHY1%RCTGLA
LCLS_HS => YDPHY1%LCLS_HS
ACLS_HS => YDPHY1%ACLS_HS

VDNNH => YDVDOZ%VDNNH
VDNJS => YDVDOZ%VDNJS
VDPNS => YDVDOZ%VDPNS
VDAJS => YDVDOZ%VDAJS
VDAJH => YDVDOZ%VDAJH
VDPNH => YDVDOZ%VDPNH
VDNJH => YDVDOZ%VDNJH
VDNNS => YDVDOZ%VDNNS
VDANH => YDVDOZ%VDANH
VDPJH => YDVDOZ%VDPJH
LRDEPOZ => YDVDOZ%LRDEPOZ
VDPJS => YDVDOZ%VDPJS
VDANS => YDVDOZ%VDANS
VDHJH => YDVDOZ%VDHJH
VDHNH => YDVDOZ%VDHNH
VDHNS => YDVDOZ%VDHNS
VDHJS => YDVDOZ%VDHJS
VDEJH => YDVDOZ%VDEJH
LRDIFOZ => YDVDOZ%LRDIFOZ
VOZNJ => YDVDOZ%VOZNJ
VOZHS => YDVDOZ%VOZHS
VDENH => YDVDOZ%VDENH
VDENS => YDVDOZ%VDENS
VDEJS => YDVDOZ%VDEJS
!     ------------------------------------------------------------------

!*       1.    Set default values.
!              -------------------

!        1.1 Set implicit default values

!  Snow , Sea-Ice
ALCRIN=0.7_JPRB
ALRCN1=1.E-03_JPRB
ALRCN2=2.5E-03_JPRB
EMCRIN=0.98_JPRB
WCRIN=10._JPRB
TMERGL=271.23_JPRB
NCHSP=0
!  Characteristics of ice and sea
NTVGLA=2
NTVMER=1
RD2GLA=8._JPRB
RD2MER=8._JPRB
ALBGLA=.65_JPRB
ALBMER=.07_JPRB
ALBMED=.06_JPRB
EMMGLA=.97_JPRB
EMMMER=.96_JPRB
RZ0GLA=.001_JPRB
RZ0MER=.001_JPRB
RZHZ0G=1.0_JPRB
RZHZ0M=1.0_JPRB
!  Usual - soil
HSOL=1.0E-05_JPRB
HSOLIT0=0.35_JPRB
HSOLIWR=6._JPRB
RTINER=5._JPRB
WPMX=100._JPRB
WSMX=20._JPRB
SODELX(0)=1.0_JPRB/SQRT(1.0_JPRB+2.0_JPRB*RPI)
DO J=1,9
  SODELX(J)=SODELX(J-1)*2.0_JPRB*RPI
ENDDO
!  Relaxation
OMTPRO=0._JPRB
OMWPRO=0._JPRB
!  ISBA - soil
EA=-0.54_JPRB
GA=732.42E-3_JPRB
G1B=0.137_JPRB
G2B=3.5_JPRB
G1P=0.134_JPRB
G2P=3.4_JPRB
GC1=0.5_JPRB
GC2=10._JPRB
GC3=8._JPRB
GCONV=1.E3_JPRB

G1WSAT=-1.08E-3_JPRB
G2WSAT=494.31E-3_JPRB
EWFC=0.35_JPRB
GWFC=89.0467E-3_JPRB
EWWILT=0.5_JPRB
GWWILT=37.1342E-3_JPRB
EC2REF=-0.95_JPRB
GC2REF=13.82_JPRB
G1CGSAT=-1.5571E-8_JPRB
G2CGSAT=-1.441E-8_JPRB
G3CGSAT=4.70217E-6_JPRB
G1C1SAT=5.58E-3_JPRB
G2C1SAT=84.88E-3_JPRB
GC31=5.3275_JPRB
GC32=-1.043_JPRB

RD1=1.E-2_JPRB
RC1MAX=500._JPRB
RCTGLA=5.5E-6_JPRB
RCGMAX=0.8E-5_JPRB
LIMC=.TRUE.
LIMW=.TRUE.
!  ISBA - vegetation
GF1=0.55_JPRB
GWLEX=2.0_JPRB/3._JPRB
GWLMX=0.2_JPRB
RSMAX=5000._JPRB
GF3(1:18)=0.0_JPRB
GF4(1:18)=0.0016_JPRB
RCTVEG(1:18)=0.8E-5_JPRB
RGL(1:18)=100._JPRB
TREF4(1:18)=298._JPRB
GF3(4)=40._JPRB
RGL(4)=30._JPRB
!  ISBA - roughness length
GCZ0H(0,1)=7.5_JPRB
GCZ0H(1,1)=2.39037_JPRB
GCZ0H(2,1)=-.28583_JPRB
GCZ0H(3,1)=.01074_JPRB
GCZ0H(0,2)=0.5_JPRB
GCZ0H(1,2)=-.07028_JPRB
GCZ0H(2,2)=.01023_JPRB
GCZ0H(3,2)=-.00067_JPRB
GCZ0H(0,3)=5.0_JPRB
GCZ0H(1,3)=4.51268_JPRB
GCZ0H(2,3)=.34012_JPRB
GCZ0H(3,3)=-.05330_JPRB
GCZ0H(0,4)=0.5_JPRB
GCZ0H(1,4)=-.09421_JPRB
GCZ0H(2,4)=.01463_JPRB
GCZ0H(3,4)=-.00099_JPRB
!  ISBA - snow
ALBMAX=0.85_JPRB
ALBMIN=0.50_JPRB
RHOMAX=0.3_JPRB
RHOMIN=0.1_JPRB
TOEXP=0.24_JPRB/86400._JPRB
TOLIN=0.008_JPRB/86400._JPRB
WCRINC=70._JPRB
WCRING=10._JPRB
WNEW=10._JPRB
XCRINR=1.0_JPRB/RG
XCRINV=10000._JPRB
GSNC1=RPI/(2.22_JPRB*RCS*RDAY*1000._JPRB)
GSNC2=2.885_JPRB
!   ISBA - C1 vapour phase
LC1VAP=.TRUE.
GTSVAP=0._JPRB
GC1S1= 1.19_JPRB
GC1S2=-5.09_JPRB
GC1S3=-1.464E+2_JPRB
GC1S4= 17.86E+2_JPRB
GC1Y1=10._JPRB
! Deep Soil freezing
GVEGMX=5._JPRB
GLAIMX=30._JPRB
GNEIMX=1.8_JPRB
GWPIMX=150._JPRB
GCGEL=3.E-5_JPRB
! Surface soil freezing
GCGELS=5.E-5_JPRB
GVEGMXS=5._JPRB
GLAIMXS=30._JPRB
GNEIMXS=1.8_JPRB
!  OZONE DIFFUSION AND DEPOSITION
LRDIFOZ=.FALSE.
LRDEPOZ=.FALSE.
VOZNJ=1._JPRB
VOZHS=1.0_JPRB/86400._JPRB
DO J=1,99
  VDHJS(J)=-999._JPRB
  VDHJH(J)=-999._JPRB
  VDHNS(J)=-999._JPRB
  VDHNH(J)=-999._JPRB
  VDPJS(J)=-999._JPRB
  VDPJH(J)=-999._JPRB
  VDPNS(J)=-999._JPRB
  VDPNH(J)=-999._JPRB
  VDEJS(J)=-999._JPRB
  VDEJH(J)=-999._JPRB
  VDENS(J)=-999._JPRB
  VDENH(J)=-999._JPRB
  VDAJS(J)=-999._JPRB
  VDAJH(J)=-999._JPRB
  VDANS(J)=-999._JPRB
  VDANH(J)=-999._JPRB
  VDNJS(J)=-999._JPRB
  VDNJH(J)=-999._JPRB
  VDNNS(J)=-999._JPRB
  VDNNH(J)=-999._JPRB
ENDDO
! New snow scheme (LVGSN)
ALB1=0.87_JPRB
ALB2=0.84_JPRB
RLAIMX=7._JPRB
RLAI=3._JPRB
! To compute ALBMER for CLIMAT when LRRTM=.T.
LALBMERCLIM=.FALSE.

! 2m interpolation (TOUCANS)
LCLS_HS=.FALSE.
ACLS_HS=1._JPRB

!        1.2 Modify default values according to LECMWF

IF (LECMWF) THEN
ELSE
ENDIF

!     ------------------------------------------------------------------

!*       2.    Modify default values.
!              ----------------------

CALL POSNAM(NULNAM,'NAMPHY1')
READ(NULNAM,NAMPHY1)
CALL POSNAM(NULNAM,'NAMVDOZ')
READ(NULNAM,NAMVDOZ)

!        2.5   Check consistency
!              -----------------
IF (GC1Y1 > 60._JPRB) THEN
  CALL ABOR1 ('GC1Y1 FOR C1-VAPOUR PHASE IS BIGGER THAN 60.')
ENDIF

!YT Dependency on surface fields should go somewhere else!
!YT
!YT IF ((YSD_VVD%NUMFLDS < 8).AND.(RZHZ0M /= 1.0_JPRB)) THEN
!YT   CALL ABOR1('YSD_VVD%NUMFLDS<8 IMPLIES RZHZ0M=1.0_JPRB !...')
!YT ENDIF

!     ------------------------------------------------------------------

!*       3.    Print final values.
!              -------------------

WRITE(UNIT=KULOUT,FMT='('' COMMON YOMPHY1 '')')

WRITE(UNIT=KULOUT,FMT='(&
 & '' ALCRIN ='',E10.4,'' ALRCN1 ='',E10.4,'' ALRCN2 ='',E10.4&
 & ,'' EMCRIN ='',E10.4,'' WCRIN ='',E10.4,'' TMERGL ='',E10.4)')&
 & ALCRIN,ALRCN1,ALRCN2,EMCRIN,WCRIN,TMERGL  

WRITE(UNIT=KULOUT,FMT='(&
 & '' NCHSP ='',I3,&
 & '' NTVMER ='',I3,'' NTVGLA ='',I3&
 & ,'' RD2MER ='',E10.4,'' ALBMER='',E10.4,'' EMMMER ='',E10.4,/&
 & ,'' RD2GLA ='',E10.4,'' ALBGLA='',E10.4,'' EMMGLA ='',E10.4,/&
 & ,'' RZ0MER ='',E10.4,'' RZ0GLA ='',E10.4,'' LALBMERCLIM ='',L2)')&
 & NCHSP,NTVMER,NTVGLA,RD2MER,ALBMER,EMMMER&
 & ,RD2GLA,ALBGLA,EMMGLA,RZ0MER,RZ0GLA,LALBMERCLIM
WRITE(UNIT=KULOUT,FMT='(&
 & '' RTINER ='',E10.4,'' HSOL ='',E10.4,'' HSOLIT0 ='',E10.4&
 & ,'' HSOLIWR ='',E10.4,'' WPMX ='',E10.4&
 & ,'' WSMX ='',E10.4,'' OMTPRO ='',E10.4,'' OMWPRO ='',E10.4)')&
 & RTINER,HSOL,HSOLIT0,HSOLIWR,WPMX,WSMX,OMTPRO,OMWPRO  

WRITE(UNIT=KULOUT,FMT='(&
 & '' EA ='',E10.4,'' GA ='',E10.4,'' G1B ='',E10.4&
 & ,'' G2B ='',E10.4,'' G1P ='',E10.4,'' G2P = '',E10.4,/&
 & ,'' GC1 ='',E10.4,'' GC2 ='',E10.4,'' GC3 ='',E10.4&
 & ,'' GCONV ='',E10.4)')&
 & EA,GA,G1B,G2B,G1P,G2P,GC1,GC2,GC3,GCONV  

WRITE(UNIT=KULOUT,FMT='(&
 & '' G1WSAT ='',E10.4,'' G2WSAT ='',E10.4,'' EWFC ='',E10.4&
 & ,'' GWFC ='',E10.4,/,'' EWWILT ='',E10.4,'' GWWILT ='',E10.4&
 & ,'' EC2REF ='',E10.4,'' GC2REF ='',E10.4,/&
 & ,'' G1CGSAT ='',E10.4,'' G2CGSAT ='',E10.4,'' G3CGSAT =''&
 & ,E10.4,'' G1C1SAT ='',E10.4,'' G2C1SAT ='',E10.4)')&
 & G1WSAT,G2WSAT,EWFC,GWFC,EWWILT,GWWILT,EC2REF,GC2REF,&
 & G1CGSAT,G2CGSAT,G3CGSAT,G1C1SAT,G2C1SAT  

WRITE(UNIT=KULOUT,FMT='(&
 & '' RD1 ='',E10.4,'' RC1MAX ='',E10.4,'' RCTGLA ='',E10.4&
 & ,'' RCGMAX ='',E10.4,''  LIMC ='',L2,'' LIMW ='',L2)')&
 & RD1,RC1MAX,RCTGLA,RCGMAX,LIMC,LIMW  

WRITE(UNIT=KULOUT,FMT='(&
 & '' GC1S1 ='',E10.4,'' GC1S2 ='',E10.4,'' GC1S3 ='',E10.4&
 & ,'' GC1S4 ='',E10.4,''  GC1Y1 ='',E10.4,'' LC1VAP ='',L2&
 & ,'' GTSVAP ='',E10.4)')&
 & GC1S1,GC1S2,GC1S3,GC1S4,GC1Y1,LC1VAP,GTSVAP  

WRITE(UNIT=KULOUT,FMT='(&
 & '' GCGEL ='',E10.4,'' GVEGMX ='',E10.4,'' GLAIMX ='',E10.4&
 & ,'' GWPIMX ='',E10.4,'' GNEIMX  ='',E10.4)')&
 & GCGEL,GVEGMX,GLAIMX,GWPIMX,GNEIMX  

WRITE(UNIT=KULOUT,FMT='(&
 & '' GCGELS  ='',E10.4,'' GVEGMXS ='',E10.4&
 & ,'' GLAIMXS ='',E10.4,'' GNEIMXS ='',E10.4)')&
 & GCGELS,GVEGMXS,GLAIMXS,GNEIMXS  

WRITE(UNIT=KULOUT,FMT='(&
 & '' ALB1  ='',E10.4,'' ALB2 ='',E10.4&
 & ,'' RLAIMX ='',E10.4,'' RLAI ='',E10.4)')&
 & ALB1,ALB2,RLAIMX,RLAI  

WRITE(UNIT=KULOUT,FMT='('' GCZ0H ='',/,4(1X,4E11.4,/))')GCZ0H

WRITE(UNIT=KULOUT,FMT='(&
 & '' GF1 ='',E10.4,'' GWLEX ='',E10.4,'' GWLMX ='',E10.4&
 & ,'' RSMAX ='',E10.4,/&
 & ,'' GF3 ='',/,2(1X,9E11.4,/),'' GF4 ='',/,2(1X,9E11.4,/)&
 & ,'' RCTVEG ='',/,2(1X,9E11.4,/),'' RGL ='',/,2(1X,9E11.4,/)&
 & ,'' TREF4 ='',/,2(1X,9E11.4,/))')&
 & GF1,GWLEX,GWLMX,RSMAX,GF3,GF4,RCTVEG,RGL,TREF4  

WRITE(UNIT=KULOUT,FMT='(&
 & '' ALBMAX = '',E10.4,'' ALBMIN = '',E10.4&
 & ,'' RHOMAX = '',E10.4,'' RHOMIN = '',E10.4,/&
 & ,'' TOEXP = '',E10.4,'' TOLIN = '',E10.4&
 & ,'' WCRINC = '',E10.4,'' WCRING = '',E10.4,/&
 & ,'' WNEW = '',E10.4&
 & ,'' XCRINR = '',E10.4,'' XCRINV = '',E10.4)')&
 & ALBMAX,ALBMIN,RHOMAX,RHOMIN,TOEXP,TOLIN,WCRINC,WCRING,WNEW,&
 & XCRINR,XCRINV  

WRITE(KULOUT,'(A,L1,A,ES11.4)') ' LCLS_HS = ',LCLS_HS,' ACLS_HS = ',ACLS_HS

WRITE(UNIT=KULOUT,FMT='('' SODELX = ''/5E11.4/5E11.4)') SODELX
!YT Dependency on surface fields should go somewhere else!
!YT
!YT IF(YSP_SBD%NLEVS > 9)  CALL ABOR1(' TOO MANY SOIL LAYERS !')

WRITE(UNIT=KULOUT,FMT='('' COMMON YOMVDOZ '')')

WRITE(UNIT=KULOUT,FMT='('' LRDIFOZ ='',L2,'' LRDEPOZ ='',L2)')LRDIFOZ,LRDEPOZ

IF (LRDIFOZ.AND.LRDEPOZ) THEN
  WRITE(UNIT=KULOUT,FMT='('' VOZNJ ='',F10.5,'' VOZHS ='',F10.5)')VOZNJ,VOZHS
  DO IVEG=1,99
    IF((VDHJS(IVEG) /= -999._JPRB).OR.(VDHJH(IVEG) /= -999._JPRB).OR.&
       & (VDHNS(IVEG) /= -999._JPRB).OR.(VDHNH(IVEG) /= -999._JPRB).OR.&
       & (VDPJS(IVEG) /= -999._JPRB).OR.(VDPJH(IVEG) /= -999._JPRB).OR.&
       & (VDPNS(IVEG) /= -999._JPRB).OR.(VDPNH(IVEG) /= -999._JPRB).OR.&
       & (VDEJS(IVEG) /= -999._JPRB).OR.(VDEJH(IVEG) /= -999._JPRB).OR.&
       & (VDENS(IVEG) /= -999._JPRB).OR.(VDENH(IVEG) /= -999._JPRB).OR.&
       & (VDAJS(IVEG) /= -999._JPRB).OR.(VDAJH(IVEG) /= -999._JPRB).OR.&
       & (VDANS(IVEG) /= -999._JPRB).OR.(VDANH(IVEG) /= -999._JPRB).OR.&
       & (VDNJS(IVEG) /= -999._JPRB).OR.(VDNJH(IVEG) /= -999._JPRB).OR.&
       & (VDNNS(IVEG) /= -999._JPRB).OR.(VDNNH(IVEG) /= -999._JPRB))THEN  
      WRITE(UNIT=KULOUT,FMT='('' IVEJ ='',I2&
       & ,'' VDHJS ='',E9.3,'' VDHJH ='',E9.3,'' VDHNS ='',E9.3&
       & ,'' VDHNH ='',E9.3)')&
       & IVEG,VDHJS(IVEG),VDHJH(IVEG),VDHNS(IVEG),VDHNH(IVEG)  
      WRITE(UNIT=KULOUT,FMT='('' IVEJ ='',I2&
       & ,'' VDPJS ='',E9.3,'' VDPJH ='',E9.3,'' VDPNS ='',E9.3&
       & ,'' VDPNH ='',E9.3)')&
       & IVEG,VDPJS(IVEG),VDPJH(IVEG),VDPNS(IVEG),VDPNH(IVEG)  
      WRITE(UNIT=KULOUT,FMT='('' IVEJ ='',I2&
       & ,'' VDEJS ='',E9.3,'' VDEJH ='',E9.3,'' VDENS ='',E9.3&
       & ,'' VDENH ='',E9.3)')&
       & IVEG,VDEJS(IVEG),VDEJH(IVEG),VDENS(IVEG),VDENH(IVEG)  
      WRITE(UNIT=KULOUT,FMT='('' IVEJ ='',I2&
       & ,'' VDAJS ='',E9.3,'' VDAJH ='',E9.3,'' VDANS ='',E9.3&
       & ,'' VDANH ='',E9.3)')&
       & IVEG,VDAJS(IVEG),VDAJH(IVEG),VDANS(IVEG),VDANH(IVEG)  
      WRITE(UNIT=KULOUT,FMT='('' IVEJ ='',I2&
       & ,'' VDNJS ='',E9.3,'' VDNJH ='',E9.3,'' VDNNS ='',E9.3&
       & ,'' VDNNH ='',E9.3)')&
       & IVEG,VDNJS(IVEG),VDNJH(IVEG),VDNNS(IVEG),VDNNH(IVEG)  
    ENDIF
  ENDDO
ENDIF
!*
!     ------------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUPHY1',1,ZHOOK_HANDLE)
END SUBROUTINE SUPHY1
