! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE WRCOE(YDGEOMETRY,YDML_AOC,YDRIP)

!**** * WRCOE  * - ROUTINE TO WRITE THE COUPLED FIELDS

!     PURPOSE.
!     --------
!        WRITES YOMGCO ON DISK (distributed memory version)

!**   INTERFACE.
!     ----------
!        *CALL* *WRCOE*

!     EXPLICIT ARGUMENTS :  NONE
!     --------------------

!     IMPLICIT ARGUMENTS :
!     --------------------
!        COMMON  YOMGCO

!     METHOD.
!     -------
!        Depends on NOACOMM

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF RESEARCH DEPARTMENT DOCUMENTATION OF THE IFS

!     AUTHOR.
!     -------
!      CHRISTINE DREVETON
!      ORIGINAL : 92-05-25 (D'APRES WRFU)

!     MODIFICATIONS.
!     --------------
!      09-10-13 K. Yessad (use DIWRGRID)
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      R. El Khatib : 23-Apr-2010 use diwgrid_mod instead of diwgrid
!      K. Yessad (July 2014): Move some variables.
!-----------------------------------------------------------------------

USE MODEL_ATMOS_OCEAN_COUPLING_MOD , ONLY : MODEL_ATMOS_OCEAN_COUPLING_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULCO, NULOUT
USE YOMMSC   , ONLY : NINTLEN, NREALEN
USE YOMGCO   , ONLY : STRSU, STRSV, FCHAS, FRSOS, FHUMS
USE YOMCT0   , ONLY : NFRCO
USE YOMCT3   , ONLY : NSTEP
USE YOMMP0   , ONLY : MYPROC
USE DIWRGRID_MOD, ONLY : DIWRGRID_SEND, DIWRGRID_RECV
USE YOMRIP   , ONLY : TRIP

!-----------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY), INTENT(IN)   :: YDGEOMETRY
TYPE(MODEL_ATMOS_OCEAN_COUPLING_TYPE),INTENT(INOUT):: YDML_AOC
TYPE(TRIP)     ,INTENT(INOUT):: YDRIP
INTEGER(KIND=JPIM) :: JPNCHP

PARAMETER(JPNCHP=6)
REAL(KIND=JPRB) :: ZHEAT (YDGEOMETRY%YRGEM%NGPTOTG)
REAL(KIND=JPRB) :: ZFCHAS(YDGEOMETRY%YRGEM%NGPTOTG)
REAL(KIND=JPRB) :: ZFRSOS(YDGEOMETRY%YRGEM%NGPTOTG)
REAL(KIND=JPRB) :: ZSTRSU(YDGEOMETRY%YRGEM%NGPTOTG)
REAL(KIND=JPRB) :: ZSTRSV(YDGEOMETRY%YRGEM%NGPTOTG)
REAL(KIND=JPRB) :: ZFHUMS(YDGEOMETRY%YRGEM%NGPTOTG)
REAL(KIND=JPRB) :: ZREAL(YDGEOMETRY%YRDIM%NDLON*YDGEOMETRY%YRDIM%NDGLG)
REAL(KIND=JPRB) :: ZWORK(YDGEOMETRY%YRGEM%NGPTOTMX)
REAL(KIND=JPRB) :: ZFACT
INTEGER(KIND=JPIM) :: ICSTEP

INTEGER(KIND=JPIM) :: IA, IRET, ISND, ISST1,&
 & ISST2, ISTEP, JL ,J  

LOGICAL :: LLDONE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-----------------------------------------------------------------------

#include "abor1.intfb.h"
#include "sugco0.intfb.h"

!-----------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('WRCOE',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM, &
 & YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP, YDMCC=>YDML_AOC%YRMCC, &
 & YDCOU=>YDML_AOC%YRCOU)
ASSOCIATE(NDGLG=>YDDIM%NDGLG, NDLON=>YDDIM%NDLON, &
 & NGPTOT=>YDGEM%NGPTOT, NGPTOTG=>YDGEM%NGPTOTG, NGPTOTMX=>YDGEM%NGPTOTMX, &
 & NOACOMM=>YDMCC%NOACOMM, &
 & TSTEP=>YDRIP%TSTEP)
!-----------------------------------------------------------------------

!*       1.    PREPARATIONS.
!              --------------
!   WRCOE is called from end of CNT4, so different timekeeping

ISTEP=NSTEP
IF(ISTEP <= 0) THEN
  WRITE(NULOUT,*) 'ERROR: WRCOE CALLED AT WRONG TIMESTEP'
  WRITE(NULOUT,*) 'NSTEP IS ',NSTEP
  IF (LHOOK) CALL DR_HOOK('WRCOE',1,ZHOOK_HANDLE)
  RETURN
ENDIF

!*       1.2   OPEN FILES

ISND=1

DO J=1,NGPTOT
  ZWORK(J)=FCHAS(J,1)
ENDDO
IF( MYPROC /= ISND )THEN
  CALL DIWRGRID_SEND(YDGEOMETRY%YRGEM,ISND,1,ZWORK,1)
ELSE
  CALL DIWRGRID_RECV(YDGEOMETRY,1,ZWORK,1,ZFCHAS)
ENDIF

DO J=1,NGPTOT
  ZWORK(J)=FRSOS(J,1)
ENDDO
IF( MYPROC /= ISND )THEN
  CALL DIWRGRID_SEND(YDGEOMETRY%YRGEM,ISND,1,ZWORK,1)
ELSE
  CALL DIWRGRID_RECV(YDGEOMETRY,1,ZWORK,1,ZFRSOS)
ENDIF

DO J=1,NGPTOT
  ZWORK(J)=STRSU(J)
ENDDO
IF( MYPROC /= ISND )THEN
  CALL DIWRGRID_SEND(YDGEOMETRY%YRGEM,ISND,1,ZWORK,1)
ELSE
  CALL DIWRGRID_RECV(YDGEOMETRY,1,ZWORK,1,ZSTRSU)
ENDIF

DO J=1,NGPTOT
  ZWORK(J)=STRSV(J)
ENDDO
IF( MYPROC /= ISND )THEN
  CALL DIWRGRID_SEND(YDGEOMETRY%YRGEM,ISND,1,ZWORK,1)
ELSE
  CALL DIWRGRID_RECV(YDGEOMETRY,1,ZWORK,1,ZSTRSV)
ENDIF

DO J=1,NGPTOT
  ZWORK(J)=FHUMS(J,1)
ENDDO
IF( MYPROC /= ISND )THEN
  CALL DIWRGRID_SEND(YDGEOMETRY%YRGEM,ISND,1,ZWORK,1)
ELSE
  CALL DIWRGRID_RECV(YDGEOMETRY,1,ZWORK,1,ZFHUMS)
ENDIF

IF( MYPROC == ISND )THEN

  ZFACT=1.0_JPRB/(NFRCO*TSTEP)
  DO JL=1,NGPTOTG
    ZHEAT(JL) =(ZFCHAS(JL)+ZFRSOS(JL))*ZFACT
    ZFRSOS(JL)=ZFRSOS(JL)*ZFACT
    ZSTRSU(JL)=ZSTRSU(JL)*ZFACT
    ZSTRSV(JL)=ZSTRSV(JL)*ZFACT
    ZFHUMS(JL)=ZFHUMS(JL)*ZFACT
  ENDDO

!     ------------------------------------------------------------------

!*       2.   WRITE OUT SURFACE FLUXES
!             ------------------------

  ZREAL(:)=0.0_JPRB

  IF((NOACOMM <= 2).OR.(NOACOMM == 4)) THEN
    OPEN(UNIT=NULCO,FILE='flxatmos',FORM='UNFORMATTED',POSITION='REWIND')
  ENDIF

  DO JL=1,NGPTOTG
    ZREAL(JL)=ZHEAT(JL)
  ENDDO
  IF((NOACOMM <= 2).OR.(NOACOMM == 4)) THEN
    WRITE(NULCO) 'QNET_ATM'
    WRITE(NULCO) ZREAL
  ELSEIF(NOACOMM == 3) THEN
    CALL SVIPC_WRITE(YDCOU%NCULF(3),ZREAL,NDLON*NDGLG*NREALEN,IRET)
  ENDIF

  DO JL=1,NGPTOTG
    ZREAL(JL)=ZFRSOS(JL)
  ENDDO
  IF((NOACOMM <= 2).OR.(NOACOMM == 4)) THEN
    WRITE(NULCO) 'QSOL_ATM'
    WRITE(NULCO) ZREAL
  ELSEIF(NOACOMM == 3) THEN
    CALL SVIPC_WRITE(YDCOU%NCULF(4),ZREAL,NDLON*NDGLG*NREALEN,IRET)
  ENDIF

  DO JL=1,NGPTOTG
    ZREAL(JL)=ZSTRSU(JL)
  ENDDO
  IF((NOACOMM <= 2).OR.(NOACOMM == 4)) THEN
    WRITE(NULCO) 'TAUX_ATM'
    WRITE(NULCO) ZREAL
  ELSEIF(NOACOMM == 3) THEN
    CALL SVIPC_WRITE(YDCOU%NCULF(5),ZREAL,NDLON*NDGLG*NREALEN,IRET)
  ENDIF

  DO JL=1,NGPTOTG
    ZREAL(JL)=ZSTRSV(JL)
  ENDDO
  IF((NOACOMM <= 2).OR.(NOACOMM == 4)) THEN
    WRITE(NULCO) 'TAUY_ATM'
    WRITE(NULCO) ZREAL
  ELSEIF(NOACOMM == 3) THEN
    CALL SVIPC_WRITE(YDCOU%NCULF(6),ZREAL,NDLON*NDGLG*NREALEN,IRET)
  ENDIF

  DO JL=1,NGPTOTG
    ZREAL(JL)=ZFHUMS(JL)
  ENDDO
  IF((NOACOMM <= 2).OR.(NOACOMM == 4)) THEN
    WRITE(NULCO) 'PMEV_ATM'
    WRITE(NULCO) ZREAL
  ELSEIF(NOACOMM == 3) THEN
    CALL SVIPC_WRITE(YDCOU%NCULF(7),ZREAL,NDLON*NDGLG*NREALEN,IRET)
  ENDIF

  IF((NOACOMM <= 2).OR.(NOACOMM == 4)) THEN
    CLOSE(NULCO)
  ENDIF

  WRITE(NULOUT,*) 'SURFACE FLUXES WRITTEN TO COUPLING FILES'

  IF(NOACOMM == 1) THEN
    WRITE (NULOUT,'(''ERROR: NOACOMM==1 IS NO LONGER SUPPORTED'')')
    CALL ABOR1 ('NOACOMM==1 IS NO LONGER SUPPORTED')
!!    WRITE(NCMAFL(5),*) ISTEP
!!    CALL FLUSH(NCMAFL(5))
!!    WRITE(NCMAFL(6),*) ISTEP
!!    CALL FLUSH(NCMAFL(6))
!!    WRITE(NCMAFL(7),*) ISTEP
!!    CALL FLUSH(NCMAFL(7))
!!    WRITE(NCMAFL(8),*) ISTEP
!!    CALL FLUSH(NCMAFL(8))
!!    WRITE(NCMAFL(9),*) ISTEP
!!    CALL FLUSH(NCMAFL(9))
!!    WRITE(NULOUT,*) 'OASIS SIGNALLED VIA PIPES'
  ELSEIF((NOACOMM == 2).OR.(NOACOMM == 4)) THEN
    CALL PBWRITE(YDCOU%NCULF(3),ISTEP,NINTLEN,IRET)
    CALL PBFLUSH(YDCOU%NCULF(3))
    CALL PBWRITE(YDCOU%NCULF(4),ISTEP,NINTLEN,IRET)
    CALL PBFLUSH(YDCOU%NCULF(4))
    CALL PBWRITE(YDCOU%NCULF(5),ISTEP,NINTLEN,IRET)
    CALL PBFLUSH(YDCOU%NCULF(5))
    CALL PBWRITE(YDCOU%NCULF(6),ISTEP,NINTLEN,IRET)
    CALL PBFLUSH(YDCOU%NCULF(6))
    CALL PBWRITE(YDCOU%NCULF(7),ISTEP,NINTLEN,IRET)
    CALL PBFLUSH(YDCOU%NCULF(7))
    WRITE(NULOUT,*) 'OASIS SIGNALLED VIA PIPES'
  ENDIF

!     ------------------------------------------------------------------

!*       3.    WAIT UNTIL SST FIELDS READY 
!              ---------------------------
!  (Needs modifiying for last timestep of serial runs)

  IF(NOACOMM == 1) THEN
    WRITE (NULOUT,'(''ERROR: NOACOMM==1 IS NO LONGER SUPPORTED'')')
    CALL ABOR1 ('NOACOMM==1 IS NO LONGER SUPPORTED')
!!    CALL FLUSH(NULOUT)
!!    READ(NCMAFL(3),*) ICSTEP
!!    READ(NCMAFL(4),*) ICSTEP
  ELSEIF(NOACOMM == 2) THEN
    CALL FLUSH(NULOUT)
    CALL PBREAD(YDCOU%NCULF(1),ICSTEP,NINTLEN,IRET)
    CALL PBREAD(YDCOU%NCULF(2),ICSTEP,NINTLEN,IRET)
  ELSEIF(NOACOMM == 3) THEN
!   Nothing to do - continue execution
  ELSEIF(NOACOMM == 4) THEN
    IA=0
    ISST1=0
    ISST2=0
    LLDONE=.FALSE.
    DO WHILE (.NOT.LLDONE)
      IF(ISST1 == 0) CALL PBREAD(YDCOU%NCULF(1),ICSTEP,NINTLEN,IRET)
      IF(IRET > 0) ISST1=1
      IF(ISST2 == 0) CALL PBREAD(YDCOU%NCULF(2),ICSTEP,NINTLEN,IRET)
      IF(IRET > 0) ISST2=1
      IF(ISST1*ISST2 == 0) THEN
        IA=IA+1
        IF(IA == 1) THEN
          WRITE(NULOUT,*) 'Sleeping ...'
          CALL FLUSH(NULOUT)
        ENDIF
        CALL SLEEP(1)
        IF(IA > 300) THEN
          WRITE(NULOUT,*) 'Timed out waiting for coupler'
          CALL ABOR1('ABORT in INICOU')
        ENDIF
      ELSE
        IF(IA /= 0) THEN
          WRITE(NULOUT,*) 'Slept for ',IA,' seconds'
        ENDIF
        LLDONE=.TRUE.
      ENDIF
    ENDDO
  ENDIF

  IF(NOACOMM /= 3) THEN
    WRITE(NULOUT,*) 'OASIS REPLIED THAT NEW SST FIELD IS READY'
    WRITE(NULOUT,*) 'OASIS ITERATION NUMBER ',ICSTEP
  ENDIF

ENDIF

!     ------------------------------------------------------------------

!*       4.    RESET TO ZERO
!              -------------

!  At the next joint cycle, we should create a single SUGCO0
CALL SUGCO0(YDMCC)

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('WRCOE',1,ZHOOK_HANDLE)
END SUBROUTINE WRCOE
