! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE CHECK_SL_STRUCT(YDSL,CDSTR)

!**** *CHECK_SL_STRUC * - Routine to check use of SL halo

!     Explicit arguments :
!      --------------------
!        YDSL        - SL_STRUCT definition
!        CDSTR       - string indicating where this call is from
!
!     Author.
!     -------
!        G. Mozdzynski (ECMWF)
!
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
USE MPL_MODULE, ONLY : MPL_ALLREDUCE
USE YOMLUN_IFSAUX , ONLY : NULOUT
USE EINT_MOD, ONLY : SL_STRUCT

IMPLICIT NONE
SAVE

TYPE(SL_STRUCT),INTENT(INOUT) :: YDSL
CHARACTER(LEN=*),INTENT(IN) :: CDSTR
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('CHECK_SL_STRUCT',0,ZHOOK_HANDLE)

CALL CHECK_SL_STRUCT1(YDSL%MASK_SL1, 'MASK_SL1 ')
CALL CHECK_SL_STRUCT1(YDSL%MASK_SL2, 'MASK_SL2 ')

IF (LHOOK) CALL DR_HOOK('CHECK_SL_STRUCT',1,ZHOOK_HANDLE)


CONTAINS


SUBROUTINE CHECK_SL_STRUCT1(KMASK,CDMASK)
INTEGER(KIND=JPIM),INTENT(IN) :: KMASK(:)
CHARACTER(LEN=*),INTENT(IN) :: CDMASK
INTEGER(KIND=JPIM) :: IIMIN
REAL(KIND=JPRB) :: ZMIN
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('CHECK_SL_STRUCT:CHECK_SL_STRUCT1',0,ZHOOK_HANDLE)
 
CALL CHECK_SL_STRUCT2(YDSL,IIMIN,ZMIN,KMASK)
WRITE(NULOUT,'("CHECK_SL_STRUCT: ",A," :",2X,A,2X,A," MINIMUM UNUSED HALO GRID POINTS=",I3,&
  &" DISTANCE IN KM=",F8.1)') CDMASK,CDSTR,YDSL%CVER,IIMIN,ZMIN
YDSL%NUNUSEDHALO=MIN(YDSL%NUNUSEDHALO,IIMIN)
YDSL%DISTUNUSEDHALO=MIN(YDSL%DISTUNUSEDHALO,ZMIN)

IF (LHOOK) CALL DR_HOOK('CHECK_SL_STRUCT:CHECK_SL_STRUCT1',1,ZHOOK_HANDLE)
END SUBROUTINE CHECK_SL_STRUCT1


SUBROUTINE CHECK_SL_STRUCT2(YDSL,KMIN,PMIN,KMASK)
TYPE(SL_STRUCT),INTENT(IN) :: YDSL
INTEGER(KIND=JPIM),INTENT(OUT) :: KMIN
REAL(KIND=JPRB),INTENT(OUT) :: PMIN
INTEGER(KIND=JPIM),INTENT(IN) :: KMASK(:)
INTEGER(KIND=JPIM) :: JGLLOC,I,J,IB,IE,III
REAL(KIND=JPRB),ALLOCATABLE :: ZDISTW(:)
REAL(KIND=JPRB),ALLOCATABLE :: ZDISTE(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('CHECK_SL_STRUCT:CHECK_SL_STRUCT2',0,ZHOOK_HANDLE)

KMIN=999999
PMIN=999999.0_JPRB
III=0

IB=LBOUND(YDSL%NSLSTA,1)
IE=UBOUND(YDSL%NSLSTA,1)

ALLOCATE(ZDISTW(IB:IE))
ALLOCATE(ZDISTE(IB:IE))

ZDISTW(:)=PMIN
ZDISTE(:)=PMIN

DO JGLLOC=IB,IE
  IF( YDSL%NSLOFF(JGLLOC) > 0 .AND. .NOT.YDSL%LCOMPLAT(JGLLOC) )THEN
    I=0
    DO J=YDSL%NSLOFF(JGLLOC)+1,YDSL%NSLOFF(JGLLOC)+YDSL%NSLONL(JGLLOC)
      IF( KMASK(J) > 0 .OR. YDSL%LSLCORE(J) )THEN
        EXIT
      ELSE
        I=I+1
      ENDIF
    ENDDO
    ZDISTW(JGLLOC)=YDSL%DIST1GP(JGLLOC)*REAL(I,JPRB)
    IF( I == 0 .AND. (YDSL%CVER=='OA' .OR. YDSL%CVER=='AD') )THEN
! place to set a breakpoint
      III=III+1
!     WRITE(NULERR,'(" CHECK_SL_STRUCT: CVER=",A2," MIN UNUSED WEST POINTS =",I1," LAT=",I5,&
!      & " MYPROC=",I5," DIST1GP=",F8.2," NSLPTSWEST=",I3)') &
!      & YDSL%CVER,I,YDSL%NLATGLO(JGLLOC),MYPROC,YDSL%DIST1GP(JGLLOC),YDSL%NSLPTSWEST(JGLLOC)
    ENDIF
    PMIN=MIN(PMIN,ZDISTW(JGLLOC))
    KMIN=MIN(KMIN,I)
    I=0
    DO J=YDSL%NSLOFF(JGLLOC)+YDSL%NSLONL(JGLLOC),YDSL%NSLOFF(JGLLOC)+1,-1
      IF( KMASK(J) > 0 .OR. YDSL%LSLCORE(J) )THEN
        EXIT
      ELSE
        I=I+1
      ENDIF
    ENDDO
    ZDISTE(JGLLOC)=YDSL%DIST1GP(JGLLOC)*REAL(I,JPRB)
    IF( I == 0 .AND. (YDSL%CVER=='OA' .OR. YDSL%CVER=='AD') )THEN
! place to set a breakpoint
      III=III+1
!     WRITE(NULERR,'(" CHECK_SL_STRUCT: CVER=",A2," MIN UNUSED EAST POINTS =",I1," LAT=",I5,&
!      & " MYPROC=",I5," DIST1GP=",F8.2," NSLPTSEAST=",I3)') &
!      & YDSL%CVER,I,YDSL%NLATGLO(JGLLOC),MYPROC,YDSL%DIST1GP(JGLLOC),YDSL%NSLPTSEAST(JGLLOC)
    ENDIF
    PMIN=MIN(PMIN,ZDISTE(JGLLOC))
    KMIN=MIN(KMIN,I)
  ENDIF
ENDDO

CALL  MPL_ALLREDUCE(KSENDBUF=KMIN,CDOPER='MIN',CDSTRING='CHECK_SL_STRUCT:CHECK_SL_STRUCT2')
CALL  MPL_ALLREDUCE(PSENDBUF=PMIN,CDOPER='MIN',CDSTRING='CHECK_SL_STRUCT:CHECK_SL_STRUCT2')

DEALLOCATE(ZDISTW)
DEALLOCATE(ZDISTE)

IF (LHOOK) CALL DR_HOOK('CHECK_SL_STRUCT:CHECK_SL_STRUCT2',1,ZHOOK_HANDLE)
END SUBROUTINE CHECK_SL_STRUCT2

END SUBROUTINE CHECK_SL_STRUCT

