! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SLCOMM2(YDDIM,YDSL,KFIXFLD,KMASK1,KMASK2,KFLDSLB,LDINC,PB1A,LDSLCOMM,LDSWITCH,LDTLEVOL)
!****-------------------------------------------------------------------
!**** *SLCOMM2* - Interpolation buffer communication
!****-------------------------------------------------------------------
!     Purpose.
!     --------
!           This routine is called to perform the inter-processor 
!     communication required for schemes needing horizontal interpolations.

!**   Interface.
!     ----------
!        *CALL* *SLCOMM2

!        Explicit arguments :
!        --------------------
!        INPUT:
!          YDSL           - SL_STRUCT definition
!          KFLDSLB        - number of fields in interpolation buffer.
!          KFIXFLD        - description of 'fixed' fields. (fields not sent/
!                           received)
!          KMASK1         - Mask1 for on demand-comms
!          KMASK2         - Mask2 for on demand-comms
!          LDINC          - increment flag for interpolation buffer
!          LDSLCOMM       - Optional: flag indicating whether this processor needs to
!                           communicate with a specific processor.
!          LDSWITCH       - Optional: flag switching send with recv, default=false
!        INPUT/OUTPUT:
!          PB1A           - interpolation buffer.

!        Implicit arguments :  None.
!        --------------------

!     Method.
!     -------
!       Copy of SLCOMM for 'on demand' Semi-Lagrangian Communications

!     Externals.
!     ----------
!        MPL_BARRIER,  MPL_SEND, MPL_RECV, MPL_WAIT
!                                   - Communication Interface

!        Is called by SCAN2M, SCAN2MTL, CPCLIMO, CPCLIMI, FPMODPREC

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!      Deborah Salmond

!     Modifications
!     -------------
!      01-11-23  Deborah Salmond  LIMP_NOOLAP Option for non-overlapping 
!                                  message passing and buffer packing
!      26-05-02  Deborah Salmond  Memory save for LIMP_NOOLAP
!      02-10-01  G.Mozdzynski     support for radiation on-demand comms
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      03-01-07  Deborah Salmond  Tidy up
!      G.Mozdzynski  10-Nov-2005 Optimised OpenMP parallelisation
!      G.Mozdzynski  01-Jan-2008 Cleanup
!      G.Mozdzynski  02-Jan-2009 use non-blocking recv and send
!      G.Mozdzynski  27-Jul-2009 Optimise SL communications (LDSLCOMM)
!      G. Mozdzynski (Jan 2011): OOPS cleaning, use of derived type SL_STRUCT
!      G. Mozdzynski (Aug 2011): support higher order interpolation
!     ------------------------------------------------------------------

USE YOMDIM       , ONLY : TDIM
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN_IFSAUX, ONLY : NULOUT
USE MPL_MODULE
! arp/ifs dependencies to be solved later.
USE YOMMP0       , ONLY : NPRCIDS, LSLDEBUG
USE YOMTAG       , ONLY : MTAGSLAG
USE YOMVAR       , ONLY : LSLADREP
USE ALGORITHM_STATE_MOD  , ONLY : GET_NSIM4D
USE EINT_MOD     , ONLY : SL_STRUCT

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(TDIM)        ,INTENT(IN)    :: YDDIM
TYPE(SL_STRUCT)   ,INTENT(INOUT) :: YDSL
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLDSLB 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFIXFLD(2) 
INTEGER(KIND=JPIM),INTENT(IN)    :: KMASK1(YDSL%NASLB1+YDDIM%NSTENCILWIDE*2) 
INTEGER(KIND=JPIM),INTENT(INOUT) :: KMASK2(YDSL%NASLB1+YDDIM%NSTENCILWIDE*2) 
LOGICAL           ,INTENT(IN)    :: LDINC 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PB1A(YDSL%NASLB1,KFLDSLB) 
LOGICAL,OPTIONAL  ,INTENT(IN)    :: LDSLCOMM(YDSL%NSLPROCS)
LOGICAL,OPTIONAL  ,INTENT(IN)    :: LDSWITCH
LOGICAL,OPTIONAL  ,INTENT(IN)    :: LDTLEVOL

!     ------------------------------------------------------------------

LOGICAL :: LLSWITCH
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "check_sl_struct.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SLCOMM2',0,ZHOOK_HANDLE)
ASSOCIATE(NSTENCILWIDE=>YDDIM%NSTENCILWIDE )
!     ------------------------------------------------------------------

LLSWITCH=.FALSE.
IF(PRESENT(LDSWITCH)) LLSWITCH=LDSWITCH

IF( .NOT.LLSWITCH )THEN
  CALL SLCOMM2_INT(YDSL,YDSL%NSLRPT,YDSL%NSLSPT,YDSL%NSLRECVPOS,YDSL%NSLSENDPOS,&
                 & YDSL%NSLRECVPTR,YDSL%NSLSENDPTR,&
                 & KFIXFLD,KMASK1,KMASK2,KFLDSLB,LDINC,PB1A,LDSLCOMM,LDTLEVOL)  
ELSE
  CALL SLCOMM2_INT(YDSL,YDSL%NSLSPT,YDSL%NSLRPT,YDSL%NSLSENDPOS,YDSL%NSLRECVPOS,&
                 & YDSL%NSLSENDPTR,YDSL%NSLRECVPTR,&
                 & KFIXFLD,KMASK1,KMASK2,KFLDSLB,LDINC,PB1A,LDSLCOMM,LDTLEVOL)  
ENDIF

IF (LSLDEBUG) CALL CHECK_SL_STRUCT(YDSL,'SLCOMM2')

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SLCOMM2',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE SLCOMM2_INT(YDSL,KSLRPT,KSLSPT,KSLRECVPOS,KSLSENDPOS,&
                     & KSLRECVPTR,KSLSENDPTR,&
                     & KFIXFLD,KMASK1,KMASK2,KFLDSLB,LDINC,PB1A,LDSLCOMM,LDTLEVOL)  

USE PARKIND1 , ONLY : JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
TYPE(SL_STRUCT),   INTENT(IN)    :: YDSL
INTEGER(KIND=JPIM),INTENT(IN)    :: KSLRPT
INTEGER(KIND=JPIM),INTENT(IN)    :: KSLSPT
INTEGER(KIND=JPIM),INTENT(IN)    :: KSLRECVPOS(KSLRPT)
INTEGER(KIND=JPIM),INTENT(IN)    :: KSLSENDPOS(KSLSPT)
INTEGER(KIND=JPIM),INTENT(IN)    :: KSLRECVPTR(YDSL%NSLPROCS+1)
INTEGER(KIND=JPIM),INTENT(IN)    :: KSLSENDPTR(YDSL%NSLPROCS+1)
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLDSLB 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFIXFLD(2) 
INTEGER(KIND=JPIM),INTENT(IN)    :: KMASK1(YDSL%NASLB1+YDDIM%NSTENCILWIDE*2) 
INTEGER(KIND=JPIM),INTENT(INOUT) :: KMASK2(YDSL%NASLB1+YDDIM%NSTENCILWIDE*2) 
LOGICAL           ,INTENT(IN)    :: LDINC 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PB1A(YDSL%NASLB1,KFLDSLB) 
LOGICAL,OPTIONAL  ,INTENT(IN)    :: LDSLCOMM(YDSL%NSLPROCS)
LOGICAL,OPTIONAL  ,INTENT(IN)    :: LDTLEVOL

REAL(KIND=JPRB),ALLOCATABLE :: ZSENDBUF(:),ZRECVBUF(:)

INTEGER(KIND=JPIM) :: IRECVMAP(0:KSLRPT,YDSL%NSLPROCS)
INTEGER(KIND=JPIM) :: ISENDMAP(0:KSLSPT,YDSL%NSLPROCS)

INTEGER(KIND=JPIM) :: ISENDTOT (YDSL%NSLPROCS)
INTEGER(KIND=JPIM) :: IRECVTOT (YDSL%NSLPROCS)
INTEGER(KIND=JPIM) :: IREQ     (YDSL%NSLPROCS*2)
INTEGER(KIND=JPIM) :: JPOS     (YDSL%NSLPROCS)
INTEGER(KIND=JPIM) :: JSEND    (YDSL%NSLPROCS)
INTEGER(KIND=JPIM) :: ISEND_POS(YDSL%NSLPROCS)
INTEGER(KIND=JPIM) :: IRECV_POS(YDSL%NSLPROCS)
INTEGER(KIND=JPIM) :: ILENB    (YDSL%NSLPROCS)
LOGICAL            :: LLSLCOMM (YDSL%NSLPROCS)
INTEGER(KIND=JPIM) :: IFIXFLD(2)

INTEGER(KIND=JPIM) :: IBEG, IEND, ILEN,&
 & IPT, IRECVPROC, ISENDPROC,&
 & ITAG, J, JFLD, JNUM, ITOT,  INUMFIELDS,&
 & JR, JS, INUMSENT, JJ,JM, I_KPOS, IR

INTEGER(KIND=JPIM) :: ISENDCOUNT,IRECVCOUNT
INTEGER(KIND=JPIM),ALLOCATABLE :: IPTA(:,:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
LOGICAL :: LLCOMMDBGL
INTEGER(KIND=JPIM) :: I_MAPSENDTOT, I_MAPRECVTOT

IF (LHOOK) CALL DR_HOOK('SLCOMM2_INT',0,ZHOOK_HANDLE)
IFIXFLD(1)=KFIXFLD(1)
IFIXFLD(2)=KFIXFLD(2)

JR=0
JS=0
INUMSENT=0
ISENDCOUNT=0
IRECVCOUNT=0
INUMFIELDS=KFLDSLB-IFIXFLD(2)+IFIXFLD(1)-1

DO J=1,YDSL%NSLPROCS
  ISENDTOT(J)=KSLSENDPTR(J+1)-KSLSENDPTR(J)
  IRECVTOT(J)=KSLRECVPTR(J+1)-KSLRECVPTR(J)
  IF(ISENDTOT(J) > 0 ) THEN
    JS=JS+1
  ENDIF
  IF(IRECVTOT(J) > 0 ) THEN
    JR=JR+1
  ENDIF
  ISENDCOUNT=MAX(ISENDCOUNT,ISENDTOT(J))
  IRECVCOUNT=MAX(IRECVCOUNT,IRECVTOT(J))
ENDDO

ITAG=MTAGSLAG

LLCOMMDBGL=.FALSE.

IF( LLCOMMDBGL )THEN
  DO J=1,YDSL%NSLPROCS
    WRITE(NULOUT,'("SLCOMM2: J,YDSL%NSLCOMM(J),ISENDTOT(J),",&
     & "IRECVTOT(J)=",4I6)')J,YDSL%NSLCOMM(J),ISENDTOT(J),IRECVTOT(J)  
    CALL FLUSH(NULOUT)
  ENDDO
ENDIF

DO J=1,YDSL%NSLPROCS
  IF(PRESENT(LDSLCOMM))THEN
    IF (.NOT. PRESENT(LDTLEVOL)) THEN
      CALL ABOR1('Cannot call SLCOMM2 with LDSLCOMM but no LDTLEVOL')
    ENDIF
    IF((GET_NSIM4D() > 0).AND.(.NOT.LDTLEVOL)) THEN
      LLSLCOMM(J)=LDSLCOMM(J)
    ELSE
      LLSLCOMM(J)=.TRUE.
    ENDIF
    IF( LSLADREP ) LLSLCOMM(J)=.TRUE.
  ELSE
    LLSLCOMM(J)=.TRUE.
  ENDIF
ENDDO

CALL GSTATS_BARRIER(759)
CALL GSTATS(501,0)
IF(LDINC)THEN
  DO J=1,YDSL%NSLPROCS
    ITOT=0
    IBEG=KSLSENDPTR(J)
    IEND=KSLSENDPTR(J+1)-1
    DO JNUM=IBEG,IEND
      IPT=KSLSENDPOS(JNUM)
      ISENDMAP(JNUM-IBEG+1,J)= KMASK1(IPT)
      IF(KMASK1(IPT) == 1)ITOT=ITOT+1
    ENDDO
    ISENDMAP(0,J)=ITOT
    IF(ISENDMAP(0,J) == 0) ISENDTOT(J)=0
  ENDDO
  IR=0
  DO J=1,YDSL%NSLPROCS
    IRECVMAP(0,J)=0
    IF( LLSLCOMM(J) )THEN
      IR=IR+1
      IRECVPROC=YDSL%NSLCOMM(J)
      ILEN=(KSLRECVPTR(J+1)-KSLRECVPTR(J))
      CALL MPL_RECV(IRECVMAP(0:ILEN,J),KSOURCE=NPRCIDS(IRECVPROC),KTAG=ITAG,&
       & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQ(IR),&
       & CDSTRING='SLCOMM2:SLCOMM2_INT RECV MAP ' )  
    ENDIF
  ENDDO
  DO J=1,YDSL%NSLPROCS
    IF( LLSLCOMM(J) )THEN
      IR=IR+1
      ISENDPROC=YDSL%NSLCOMM(J)
      ILEN=(KSLSENDPTR(J+1)-KSLSENDPTR(J))
      CALL MPL_SEND(ISENDMAP(0:ILEN,J),KDEST=NPRCIDS(ISENDPROC),KTAG=ITAG,&
       & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQ(IR),&
       & CDSTRING='SLCOMM2:SLCOMM2_INT SEND MAP ' )  
    ENDIF
  ENDDO
  IF( IR > 0 )THEN
    CALL MPL_WAIT(KREQUEST=IREQ(1:IR),CDSTRING='SLCOMM2:SLCOMM2_INT WAIT FOR MAP SENDS AND RECEIVES')  
  ENDIF
  DO J=1,YDSL%NSLPROCS
    IF(IRECVMAP(0,J) == 0) IRECVTOT(J)=0
  ENDDO
  
ELSE ! LDINC
  
  DO J=1,YDSL%NSLPROCS
    ITOT=0
    ISENDPROC=YDSL%NSLCOMM(J)
    IBEG=KSLRECVPTR(J)
    IEND=KSLRECVPTR(J+1)-1
    DO JNUM=IBEG,IEND
      IPT=KSLRECVPOS(JNUM)
      IRECVMAP(JNUM-IBEG+1,J)= KMASK2(IPT)
      IF(KMASK2(IPT) == 1)ITOT=ITOT+1
    ENDDO
    IRECVMAP(0,J)=ITOT
    IF(IRECVMAP(0,J) == 0) IRECVTOT(J)=0 
  ENDDO
  IR=0
  DO J=1,YDSL%NSLPROCS
    ISENDMAP(0,J)=0
    IF( LLSLCOMM(J) )THEN
      IR=IR+1
      IRECVPROC=YDSL%NSLCOMM(J)
      ILEN=(KSLSENDPTR(J+1)-KSLSENDPTR(J))
      CALL MPL_RECV(ISENDMAP(0:ILEN,J),KSOURCE=NPRCIDS(IRECVPROC),KTAG=ITAG,&
       & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQ(IR),&
       & CDSTRING='SLCOMM2:SLCOMM2_INT RECV MAP ' )  
    ENDIF
  ENDDO
  DO J=1,YDSL%NSLPROCS
    IF( LLSLCOMM(J) )THEN
      IR=IR+1
      ISENDPROC=YDSL%NSLCOMM(J)
      ILEN=(KSLRECVPTR(J+1)-KSLRECVPTR(J))
      CALL MPL_SEND(IRECVMAP(0:ILEN,J),KDEST=NPRCIDS(ISENDPROC),KTAG=ITAG,&
       & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQ(IR),&
       & CDSTRING='SLCOMM2:SLCOMM2_INT SEND MAP ' )  
    ENDIF
  ENDDO
  IF( IR > 0 )THEN
    CALL MPL_WAIT(KREQUEST=IREQ(1:IR),CDSTRING='SLCOMM2:SLCOMM2_INT ERROR IN MPL_WAIT FOR MAP')  
   ENDIF
  DO J=1,YDSL%NSLPROCS
    IF(ISENDMAP(0,J) == 0) ISENDTOT(J)=0 
  ENDDO

ENDIF ! LDINC
CALL GSTATS(501,1)
CALL GSTATS_BARRIER2(759)

ISEND_POS(1)=0
IRECV_POS(1)=0

DO J=2,YDSL%NSLPROCS
  ISEND_POS(J)=ISEND_POS(J-1)+ISENDMAP(0,J-1)*INUMFIELDS+1
  IRECV_POS(J)=IRECV_POS(J-1)+IRECVMAP(0,J-1)*INUMFIELDS+1
ENDDO

I_MAPSENDTOT=ISEND_POS(YDSL%NSLPROCS)+ISENDMAP(0,YDSL%NSLPROCS)*INUMFIELDS
I_MAPRECVTOT=IRECV_POS(YDSL%NSLPROCS)+IRECVMAP(0,YDSL%NSLPROCS)*INUMFIELDS

!     Determine the maximum number of grid columns that can be communicated

IF (I_MAPSENDTOT > 0 ) ALLOCATE (ZSENDBUF(0:I_MAPSENDTOT))
IF (I_MAPRECVTOT > 0 ) ALLOCATE (ZRECVBUF(0:I_MAPRECVTOT))



!     Loop over the number of processors we need to communicate with

ITAG=ITAG+1

!       Pack loop.............................................................

CALL GSTATS(1220,0)

ALLOCATE(IPTA(MAX(ISENDCOUNT,IRECVCOUNT),YDSL%NSLPROCS))
!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(J,IRECVPROC,IBEG,IEND,JM,JNUM)
DO J=1,YDSL%NSLPROCS
  IF( ISENDTOT(J) > 0 .AND. LLSLCOMM(J) )THEN
    IRECVPROC=YDSL%NSLCOMM(J)
    IBEG=KSLSENDPTR(J)
    IEND=KSLSENDPTR(J+1)-1
    JM=0
    DO JNUM=IBEG,IEND
      IF(ISENDMAP((JNUM-KSLSENDPTR(J)+1),J) == 1)THEN
        JM=JM+1
        IPTA(JM,J)=KSLSENDPOS(JNUM)
      ENDIF
    ENDDO
    ILENB(J)=JM
    JPOS(J)=(KFLDSLB-(IFIXFLD(2)-IFIXFLD(1)+1))*JM
    JSEND(J)=NPRCIDS(IRECVPROC)
    ZSENDBUF(ISEND_POS(J))=ISENDTOT(J)
    IF( LLCOMMDBGL )THEN
      WRITE(NULOUT,'("SLCOMM2: SENDING ",I6," TO ",I6,&
       & " ITAG=",I9)')ISENDTOT(J),IRECVPROC,ITAG
      CALL FLUSH(NULOUT)
    ENDIF
  ENDIF
ENDDO
!$OMP END PARALLEL DO

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JFLD,J,ILEN,I_KPOS,JJ)
DO JFLD=1,IFIXFLD(1)-1
  DO J=1,YDSL%NSLPROCS
    IF( ISENDTOT(J) > 0 .AND. LLSLCOMM(J) )THEN
      ILEN=ILENB(J)
      I_KPOS=ISEND_POS(J)+(JFLD-1)*ILEN
      DO JJ=1,ILEN
        ZSENDBUF(I_KPOS+JJ)=PB1A(IPTA(JJ,J),JFLD)
      ENDDO
    ENDIF
  ENDDO
ENDDO
!$OMP END PARALLEL DO

!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JFLD,J,ILEN,I_KPOS,JJ)
DO JFLD=IFIXFLD(2)+1,KFLDSLB
  DO J=1,YDSL%NSLPROCS
    IF( ISENDTOT(J) > 0 .AND. LLSLCOMM(J) )THEN
      ILEN=ILENB(J)
      I_KPOS=ISEND_POS(J)+(IFIXFLD(1)-IFIXFLD(2)+JFLD-2)*ILEN
      DO JJ=1,ILEN
        ZSENDBUF(I_KPOS+JJ)=PB1A(IPTA(JJ,J),JFLD)
      ENDDO
    ENDIF
  ENDDO
ENDDO
!$OMP END PARALLEL DO
  DEALLOCATE(IPTA)

CALL GSTATS(1220,1)


IR=0
CALL GSTATS_BARRIER(748)
CALL GSTATS(511,0)

!       Receive loop.........................................................
DO J=1,YDSL%NSLPROCS
  IF( IRECVTOT(J) > 0 .AND. LLSLCOMM(J) )THEN
    IR=IR+1
    ISENDPROC=YDSL%NSLCOMM(J)
    IF( LLCOMMDBGL )THEN
      WRITE(NULOUT,'("SLCOMM2: RECEIVING ",I6," FROM ",I6,&
       & " ITAG=",I9)')ISENDPROC,ITAG  
      CALL FLUSH(NULOUT)
    ENDIF
    ILEN=IRECVMAP(0,J)*INUMFIELDS
    CALL MPL_RECV(ZRECVBUF(IRECV_POS(J):IRECV_POS(J)+ILEN),&
     & KSOURCE=NPRCIDS(ISENDPROC),&
     & KTAG=ITAG,&
     & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQ(IR),&
     & CDSTRING='SLCOMM2:SLCOMM2_INT RECV' )  
  ENDIF
ENDDO

!       Send loop.............................................................
DO J=1,YDSL%NSLPROCS
  IF( ISENDTOT(J) > 0 .AND. LLSLCOMM(J) )THEN
    IR=IR+1
    CALL MPL_SEND(ZSENDBUF(ISEND_POS(J):ISEND_POS(J)+JPOS(J)),&
     & KDEST=JSEND(J),KTAG=ITAG,&
     & KMP_TYPE=JP_NON_BLOCKING_STANDARD,KREQUEST=IREQ(IR),&
     & CDSTRING='SLCOMM2:SLCOMM2_INT SEND ' )  
  ENDIF
ENDDO

!       Wait for all outstanding sends

IF(IR > 0) THEN
  CALL MPL_WAIT(KREQUEST=IREQ(1:IR),CDSTRING='SLCOMM2:SLCOMM2_INT WAIT FOR SENDS AND RECEIVES')
ENDIF

CALL GSTATS(511,1)
CALL GSTATS_BARRIER2(748)

!     Unpack loop.............................................................
CALL GSTATS(1221,0)

ALLOCATE(IPTA(MAX(ISENDCOUNT,IRECVCOUNT),YDSL%NSLPROCS))
!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) PRIVATE(J,ISENDPROC,IBEG,IEND,JM,JNUM)
DO J=1,YDSL%NSLPROCS
  IF( IRECVTOT(J) > 0 .AND. LLSLCOMM(J) )THEN
    ISENDPROC=YDSL%NSLCOMM(J)
    IBEG=KSLRECVPTR(J)
    IEND=KSLRECVPTR(J)+ZRECVBUF(IRECV_POS(J))-1
    JM=0
    DO JNUM=IBEG,IEND
      IF(IRECVMAP((JNUM-KSLRECVPTR(J)+1),J) == 1)THEN
        JM=JM+1
        IPTA(JM,J)=KSLRECVPOS(JNUM)
      ENDIF
    ENDDO
    ILENB(J)=JM
    IF( LLCOMMDBGL )THEN
      WRITE(NULOUT,'("SLCOMM2: SENDING ",I6," TO ",I6,&
       & " ITAG=",I9)')ISENDTOT(J),IRECVPROC,ITAG
      CALL FLUSH(NULOUT)
    ENDIF
  ENDIF
ENDDO
!$OMP END PARALLEL DO

IF( LDINC )THEN
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JFLD,J,ILEN,I_KPOS,JJ)
  DO JFLD=1,IFIXFLD(1)-1
    DO J=1,YDSL%NSLPROCS
      IF( IRECVTOT(J) > 0 )THEN
        ILEN=ILENB(J)
        I_KPOS=IRECV_POS(J)+(JFLD-1)*ILEN
        DO JJ=1,ILEN
          PB1A(IPTA(JJ,J),JFLD)=PB1A(IPTA(JJ,J),JFLD)+ZRECVBUF(I_KPOS+JJ)
        ENDDO
      ENDIF
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JFLD,J,ILEN,I_KPOS,JJ)
  DO JFLD=IFIXFLD(2)+1,KFLDSLB
    DO J=1,YDSL%NSLPROCS
      IF( IRECVTOT(J) > 0 )THEN
        ILEN=ILENB(J)
        I_KPOS=IRECV_POS(J)+(IFIXFLD(1)-IFIXFLD(2)+JFLD-2)*ILEN
        DO JJ=1,ILEN
          PB1A(IPTA(JJ,J),JFLD)=PB1A(IPTA(JJ,J),JFLD)+ZRECVBUF(I_KPOS+JJ)
        ENDDO
      ENDIF
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
ELSE
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JFLD,J,ILEN,I_KPOS,JJ)
  DO JFLD=1,IFIXFLD(1)-1
    DO J=1,YDSL%NSLPROCS
      IF( IRECVTOT(J) > 0 .AND. LLSLCOMM(J) )THEN
        ILEN=ILENB(J)
        I_KPOS=IRECV_POS(J)+(JFLD-1)*ILEN
        DO JJ=1,ILEN
          PB1A(IPTA(JJ,J),JFLD)=ZRECVBUF(I_KPOS+JJ)
        ENDDO
      ENDIF
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JFLD,J,ILEN,I_KPOS,JJ)
  DO JFLD=IFIXFLD(2)+1,KFLDSLB
    DO J=1,YDSL%NSLPROCS
      IF( IRECVTOT(J) > 0 .AND. LLSLCOMM(J) )THEN
        ILEN=ILENB(J)
        I_KPOS=IRECV_POS(J)+(IFIXFLD(1)-IFIXFLD(2)+JFLD-2)*ILEN
        DO JJ=1,ILEN
          PB1A(IPTA(JJ,J),JFLD)=ZRECVBUF(I_KPOS+JJ)
        ENDDO
      ENDIF
    ENDDO
  ENDDO
!$OMP END PARALLEL DO
ENDIF

DEALLOCATE(IPTA)

CALL GSTATS(1221,1)
IF (ALLOCATED(ZSENDBUF)) DEALLOCATE (ZSENDBUF)
IF (ALLOCATED(ZRECVBUF)) DEALLOCATE (ZRECVBUF)
IF (LHOOK) CALL DR_HOOK('SLCOMM2_INT',1,ZHOOK_HANDLE)
END SUBROUTINE SLCOMM2_INT

END SUBROUTINE SLCOMM2

