! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE FDBSUBS_MOD
!
!== fdbsubs_mod.F90 ==
!
! A module to encapsulate FDB-calls in order to call Dr.Hook
!
! Author: Sami Saarinen, 22-Mar-2004
!

USE PARKIND1,   ONLY : JPIM, JPRB
USE YOMHOOK,    ONLY : LHOOK, DR_HOOK, JPHOOK
USE MPL_MODULE, ONLY : MPL_ABORT

IMPLICIT NONE

PUBLIC
SAVE

CONTAINS

SUBROUTINE IFLUSHFDBSUBS(KRET)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT)   :: KRET

INTEGER(KIND=JPIM), EXTERNAL :: IMULTIO_FLUSH

INTEGER(KIND=JPIM) :: IRET
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IFLUSHFDBSUBS',0,ZHOOK_HANDLE)

IRET = IMULTIO_FLUSH()
IF(PRESENT(KRET)) THEN
  KRET = IRET
ELSEIF(IRET /= 0) THEN
  WRITE(0,*) 'IMULTIO_FLUSH FAILED ',IRET
  CALL MPL_ABORT('IMULTIO_FLUSH FAILED')
ENDIF

IF (LHOOK) CALL DR_HOOK('IFLUSHFDBSUBS',1,ZHOOK_HANDLE)
END SUBROUTINE IFLUSHFDBSUBS

SUBROUTINE IWRITEFDBSUBS(KGRIB,KLEN,KRET)
INTEGER(KIND=JPIM),           INTENT(IN)    :: KLEN, KGRIB(:)
INTEGER(KIND=JPIM), OPTIONAL, INTENT(OUT)   :: KRET

INTEGER(KIND=JPIM), EXTERNAL :: IMULTIO_WRITE

INTEGER(KIND=JPIM) :: IRET
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IWRITEFDBSUBS',0,ZHOOK_HANDLE)

IF (SIZE(KGRIB) > 0) THEN
  IRET = IMULTIO_WRITE(KGRIB(1), KLEN)
ELSE
  IRET = IMULTIO_WRITE(KGRIB, KLEN)
ENDIF
IF(PRESENT(KRET)) THEN
  KRET = IRET
ELSEIF(IRET /= 0) THEN
  WRITE(0,*) 'IMULTIO_WRITE KLEN ', KLEN,' FAILED ',IRET
  CALL MPL_ABORT('IMULTIO_WRITE FAILED')
ENDIF

IF (LHOOK) CALL DR_HOOK('IWRITEFDBSUBS',1,ZHOOK_HANDLE)
END SUBROUTINE IWRITEFDBSUBS

END MODULE FDBSUBS_MOD
