! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE AER_NO3NH4 &
  &( YDEAERSNK,YDEAERATM,YDCOMPO, KIDIA, KFDIA, KLON, KLEV, KLEVTROP,  PRSF1,&
  &  PSO4 , PNO3_1, PNO3_2, PNH4OK, PNH3,PHNO3, PDUST1, PDUST2, PDUST3, PTDUST1, PTDUST2, PTDUST3, &
  &  PSS1, PSS2, PSS3, PTSS1, PTSS2, PTSS3, PRHO, PRHCL, PT, PDP, PTSPHY, PFRAC_CA1, PFRAC_CA2, PTNO3_1, PTNO3_2, PTNH4, &
  &  PTHNO3, PTNH3, PFNO3_1, PFNO3_2, PFNH4)

!*** * AER_NO3NH4* - GAS-TO-PARTICLE (NITRATE and AMMONIUM)

!**   INTERFACE.
!     ----------
!          *AER_NO3NH4* IS CALLED FROM *AER_PHY3*.

!     AUTHOR.
!     -------
!        SAMUEL REMY (LMD)  
!        FROM D.HAUGLUSTAINE's nitrates.F90
!        cf Hauglustaine et al., Atmos. Chem. Phys., 14, 11031–11063, 2014
!        doi:10.5194/acp-14-11031-2014 

!     SOURCE.
!     -------

!     MODIFICATIONS.
!     --------------
!        ORIGINAL : 20160914
!        20170425 SRemy simplified gas partitioning, add RH size dependence for
!                       het uptake, reactions up to tropopause +10
!        20170613 SRemy added the RH80 switch
!-----------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMCST    ,ONLY : RG, RPI, RMD
USE YOEAERSNK , ONLY : TEAERSNK
USE YOEAERATM , ONLY : TEAERATM
USE YOMCOMPO  , ONLY : TCOMPO

IMPLICIT NONE

!-----------------------------------------------------------------------

!*       0.1   ARGUMENTS
!              ---------

TYPE(TEAERSNK)    ,INTENT(INOUT) :: YDEAERSNK
TYPE(TEAERATM)    ,INTENT(INOUT) :: YDEAERATM
TYPE(TCOMPO)      ,INTENT(INOUT) :: YDCOMPO
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON 
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVTROP(KLON)

REAL(KIND=JPRB)   ,INTENT(IN)    :: PRSF1(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSO4(KLON,KLEV), PDP(KLON, KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDUST1(KLON,KLEV), PDUST2(KLON,KLEV), PDUST3(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT)    :: PTDUST1(KLON,KLEV), PTDUST2(KLON,KLEV), PTDUST3(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSS1(KLON,KLEV), PSS2(KLON,KLEV), PSS3(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(INOUT)    :: PTSS1(KLON,KLEV), PTSS2(KLON,KLEV), PTSS3(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNO3_1(KLON,KLEV),PNO3_2(KLON,KLEV),PNH4OK(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNH3(KLON,KLEV), PHNO3 (KLON, KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PT(KLON,KLEV),PRHO(KLON,KLEV),PRHCL(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSPHY 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRAC_CA1(KLON),PFRAC_CA2(KLON)

REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTNO3_1(KLON,KLEV), PTNO3_2(KLON,KLEV), PTNH4(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTNH3(KLON,KLEV),PTHNO3(KLON,KLEV)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PFNO3_1(KLON), PFNO3_2(KLON), PFNH4(KLON)


!*       0.5   LOCAL VARIABLES
!              ---------------
! molar masses
REAL(KIND=JPRB), PARAMETER :: ZMWNH3  = 17.E-3_JPRB !Kg/mol
REAL(KIND=JPRB), PARAMETER :: ZMWHNO3 = 63.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWNH4  = 18.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWNO3  = 62.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWCACO3  = 100.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWCA  = 40.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWNACL  = 58.44E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWNA  = 22.9E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZRATIOHNO3  = (63.E-3_JPRB+29E-3_JPRB) / 63.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZMWSO4  = 96.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZGHNO315_DD = 1.E-5_JPRB
REAL(KIND=JPRB), PARAMETER :: ZGHNO330_DD = 1.E-4_JPRB
REAL(KIND=JPRB), PARAMETER :: ZGHNO370_DD = 6.E-4_JPRB
REAL(KIND=JPRB), PARAMETER :: ZGHNO380_DD = 1.05E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZGHNO315_SS = 1.E-3_JPRB
REAL(KIND=JPRB), PARAMETER :: ZGHNO330_SS = 1.E-2_JPRB
REAL(KIND=JPRB), PARAMETER :: ZGHNO370_SS = 6.E-2_JPRB
REAL(KIND=JPRB), PARAMETER :: ZGHNO380_SS = 1.05E-1_JPRB
REAL(KIND=JPRB)            :: ZGHNO3_DD, ZGHNO3_SS
REAL(KIND=JPRB)            :: ZTINV(KLON,KLEV),ZDG0(KLON,KLEV)
REAL(KIND=JPRB)            :: ZTA(KLON,KLEV),ZTN(KLON,KLEV),ZTADISP(KLON,KLEV)
REAL(KIND=JPRB)            :: ZTNTA(KLON,KLEV),ZTS(KLON,KLEV)
REAL(KIND=JPRB)            :: ZAIRDM(KLON,KLEV),ZTDU(KLON,KLEV),ZTSS(KLON,KLEV)
REAL(KIND=JPRB)            :: ZKHNO30(KLON,KLEV)
REAL(KIND=JPRB)            :: ZKHNO3(KLON,KLEV)
REAL(KIND=JPRB)            :: ZRHLOC(KLON,KLEV),ZRHINV(KLON,KLEV),ZRH1580
REAL(KIND=JPRB)            :: ZNH4PINI(KLON,KLEV),ZDGHNO3(KLON,KLEV)
REAL(KIND=JPRB)            :: ZCAMMR(KLON,KLEV),ZCAVMR(KLON,KLEV),ZCINO3(KLON,KLEV)
REAL(KIND=JPRB)            :: ZNAMMR(KLON,KLEV),ZNAVMR(KLON,KLEV)
REAL(KIND=JPRB)            :: ZNTOTDUST1(KLON,KLEV),ZNTOTDUST2(KLON,KLEV),ZNTOTDUST3(KLON,KLEV)
REAL(KIND=JPRB)            :: ZNTOTSS1(KLON,KLEV),ZNTOTSS2(KLON,KLEV),ZNTOTSS3(KLON,KLEV)
REAL(KIND=JPRB)            :: ZWRK1,ZWRK2,ZKPL,ZKPL1,ZKPL2,ZKPL3,ZDRH,ZSO4
REAL(KIND=JPRB)            :: ZHNO3EQ,ZNH3EQ
REAL(KIND=JPRB)            :: ZKHNO3_DD1,ZKHNO3_DD2,ZKHNO3_DD3
REAL(KIND=JPRB)            :: ZKHNO3_SS1,ZKHNO3_SS2,ZKHNO3_SS3
REAL(KIND=JPRB)            :: ZMFP,ZKN_DD1,ZKN_DD2,ZKN_DD3
REAL(KIND=JPRB)            :: ZKN_SS1,ZKN_SS2,ZKN_SS3
REAL(KIND=JPRB)            :: ZNO3MOL,ZNH4MOL,ZDRAD, ZAVG, ZR0,ZSIG0
REAL(KIND=JPRB)            :: ZTENDHNO3
REAL(KIND=JPRB)            :: ZHNO3_TEST, ZTHNO3_TMP, ZNH3_TEST, ZTNH3_TMP
REAL(KIND=JPRB)            :: ZTDUST1, ZTSS1
REAL(KIND=JPRB)            :: ZTDUST2, ZTSS2
REAL(KIND=JPRB)            :: ZTDUST3, ZTSS3, ZCOEF, ZT0T
INTEGER(KIND=JPIM)         :: JL, JK, IRH(KLON,KLEV), IIRH, JTAB
INTEGER(KIND=JPIM), PARAMETER :: JTOT=30
REAL(KIND=JPRB), DIMENSION(JTOT) :: ZRAD,ZLRAD
REAL(KIND=JPRB), PARAMETER :: ZRGAS = 8.314_JPRB           !J/mol/K
REAL(KIND=JPRB), PARAMETER :: ZMGAS = 29._JPRB /1000._JPRB !Molecular weight in Kg
REAL(KIND=JPRB), PARAMETER :: ZDMOLEC = 4.5E-10_JPRB       !molec diameter in m
REAL(KIND=JPRB), PARAMETER :: ZRATIO_CA_CACO3  = 40._JPRB/100._JPRB           ! ratio molar mass ca/caco3
REAL(KIND=JPRB),DIMENSION(2) :: ZRHDZ ! RHD / MRHD arrays for different aerosol types
! salt solutes:
!   1 = NH4NO3, 2 = 2H-SO4
REAL(KIND=JPRB),DIMENSION(2),PARAMETER :: ZRHDA = (/0.67500, 0.4000  /)
REAL(KIND=JPRB),DIMENSION(2),PARAMETER :: ZRHDE = (/ 262.000, 384.00 /)
REAL(KIND=JPRB),PARAMETER    :: ZT0=298.15,ZR=82.0567E-6 ! in cu.m*atm/deg/mole
! EQSAM4Clim
REAL(KIND=JPRB)            :: ZXTT,ZXAW,ZXWH2O,ZXYPA(5),ZXYMA(4)
REAL(KIND=JPRB)            :: ZXSPM,ZXAPM,ZXPMS,ZXPMT,ZXRHO,ZXVOL,ZXPH,ZXHp,ZXGF,ZXYPS(5),ZXYMS(4),ZXYG(4)
REAL(KIND=JPRB), PARAMETER :: ZDD = 1.e-6_JPRB ! dry droplet diameter for the Kelvin effect (not used)
INTEGER(KIND=JPIM)         :: LMASK
LOGICAL                    :: LEQSKIP





REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "aer_eqsam4clim.intfb.h"

!-----------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('AER_NO3NH4',0,ZHOOK_HANDLE)
ASSOCIATE(LAEREQSAM4CLIM => YDCOMPO%LAEREQSAM4CLIM, &
         & RMMD_DD=>YDEAERSNK%RMMD_DD, RRHO_DD=>YDEAERSNK%RRHO_DD, &
         & RMMD_SS=>YDEAERSNK%RMMD_SS, RRHO_SS=>YDEAERSNK%RRHO_SS, &
         & RRHTAB=>YDEAERSNK%RRHTAB, &
         & LSEASALT_RH80=> YDEAERATM%LSEASALT_RH80, &
         & RSS_DRY_MASSFAC=>YDEAERATM%RSS_DRY_MASSFAC,&
         & RSS_DRY_DIAFAC=>YDEAERATM%RSS_DRY_DIAFAC,&
         & RSSGROWTH_RHTAB=>YDEAERSNK%RSSGROWTH_RHTAB, &
         & RSSDENS_RHTAB=>YDEAERSNK%RSSDENS_RHTAB)

IRH(:,:)=1
  
DO JL=KIDIA,KFDIA
  DO JK=1,KLEV
   PTNO3_1(JL,JK)=0.0_JPRB
   PTNO3_2(JL,JK)=0.0_JPRB
   PTNH4(JL,JK)=0.0_JPRB
   ZNTOTDUST1(JL,JK)=0.0_JPRB
   ZNTOTDUST2(JL,JK)=0.0_JPRB
   ZNTOTDUST3(JL,JK)=0.0_JPRB
   ZNTOTSS1(JL,JK)=0.0_JPRB
   ZNTOTSS2(JL,JK)=0.0_JPRB
   ZNTOTSS3(JL,JK)=0.0_JPRB
   DO JTAB=1,12
        IF (PRHCL(JL,JK)*100._JPRB > RRHTAB(JTAB)) THEN
          IRH(JL,JK)=JTAB
        ENDIF
      ENDDO
   ENDDO
ENDDO

! Init radius
ZDRAD = 1.0E-5_JPRB ! cm
ZAVG = 6.02217E+23_JPRB ! Avogadro number [mol-1]
ZRAD(1) = ZDRAD
DO JK   = 2, JTOT
  ZRAD(JK) = ZRAD(JK-1) + ZDRAD
ENDDO
ZLRAD   = LOG(ZRAD)
ZR0=0.29E-4_JPRB   ! cm
ZSIG0=2.0_JPRB

PTHNO3(:,:)=0._JPRB
PTNH3(:,:)=0._JPRB

DO JL=KIDIA,KFDIA
  DO JK=KLEVTROP(JL)+10,KLEV

    IIRH=IRH(JL,JK)
    ZTINV(JL,JK)    = 1._JPRB / PT(JL,JK)
    ZRHLOC(JL,JK) = PRHCL(JL,JK)
    ZRHDZ(:)=ZRHDA(:)*EXP(ZRHDE(:)*(1._JPRB/PT(JL,JK)-1._JPRB/ZT0))
    IF (ZRHLOC(JL,JK) < 1.E-15_JPRB ) ZRHLOC(JL,JK) = 1.E-15_JPRB
    IF (ZRHLOC(JL,JK) > 0.98_JPRB ) ZRHLOC(JL,JK) = 0.98_JPRB
    ZRHINV(JL,JK) = 1._JPRB - ZRHLOC(JL,JK)

    ! needed for HNO3 update on dust and ss
    ZDG0(JL,JK)= 3._JPRB/(8._JPRB*ZAVG*PRHO(JL,JK)*(ZDMOLEC**2._JPRB))
    ZDGHNO3(JL,JK) = ZDG0(JL,JK) * (ZRGAS*ZMGAS/2._JPRB/RPI*PT(JL,JK)*ZRATIOHNO3)**0.5_JPRB

    ! Number of dust particles: mass/size
    ZNTOTDUST1(JL,JK)=MAX(PDUST1(JL,JK),0._JPRB)*PRHO(JL,JK) &
        & /(RRHO_DD(1)*4._JPRB*RPI*(RMMD_DD(1)*0.5_JPRB*1E-6_JPRB)**3_JPRB/3._JPRB)
    ZNTOTDUST2(JL,JK)=MAX(PDUST2(JL,JK),0._JPRB)*PRHO(JL,JK) &
        & /(RRHO_DD(2)*4._JPRB*RPI*(RMMD_DD(2)*0.5_JPRB*1E-6_JPRB)**3_JPRB/3._JPRB)
    ZNTOTDUST3(JL,JK)=MAX(PDUST3(JL,JK),0._JPRB)*PRHO(JL,JK) &
        & /(RRHO_DD(3)*4._JPRB*RPI*(RMMD_DD(3)*0.5_JPRB*1E-6_JPRB)**3_JPRB/3._JPRB)

    ! Number of SS particles
    ! Use dry values for mass and size

    ZNTOTSS1(JL,JK)=MAX(PSS1(JL,JK),0._JPRB)*PRHO(JL,JK) &
    &                /(RSSDENS_RHTAB(IIRH)*4._JPRB*RPI*(RMMD_SS(1)*RSSGROWTH_RHTAB(IIRH)*0.5_JPRB*1E-6_JPRB)**3_JPRB/3._JPRB)
    ZNTOTSS2(JL,JK)=MAX(PSS2(JL,JK),0._JPRB)*PRHO(JL,JK) &
    &               /(RSSDENS_RHTAB(IIRH)*4._JPRB*RPI*(RMMD_SS(2)*RSSGROWTH_RHTAB(IIRH)*0.5_JPRB*1E-6_JPRB)**3_JPRB/3._JPRB)
    ZNTOTSS3(JL,JK)=MAX(PSS3(JL,JK),0._JPRB)*PRHO(JL,JK) &
    &               /(RSSDENS_RHTAB(IIRH)*4._JPRB*RPI*(RMMD_SS(3)*RSSGROWTH_RHTAB(IIRH)*0.5_JPRB*1E-6_JPRB)**3_JPRB/3._JPRB)

    ZNTOTSS1(JL,JK)=ZNTOTSS1(JL,JK)*ZMWNA/ZMWNACL
    ZNTOTSS2(JL,JK)=ZNTOTSS2(JL,JK)*ZMWNA/ZMWNACL
    ZNTOTSS3(JL,JK)=ZNTOTSS3(JL,JK)*ZMWNA/ZMWNACL

    ZNTOTSS1(JL,JK)=ZNTOTSS1(JL,JK)*ZMWNA/ZMWNACL
    ZNTOTSS2(JL,JK)=ZNTOTSS2(JL,JK)*ZMWNA/ZMWNACL
    ZNTOTSS3(JL,JK)=ZNTOTSS3(JL,JK)*ZMWNA/ZMWNACL

    !RH dependent HNO3 uptake coefficient based on Fairlie et al. 2010 and scale for SS
    ZRH1580 = MAX(MIN(ZRHLOC(JL,JK),0.80_JPRB),0.15_JPRB)
    IF( ZRH1580 <= 0.30_JPRB ) THEN
      ZGHNO3_DD = ZGHNO315_DD + (ZGHNO330_DD-ZGHNO315_DD)/0.15_JPRB*(ZRH1580-0.15_JPRB)
      ZGHNO3_SS = ZGHNO315_SS + (ZGHNO330_SS-ZGHNO315_SS)/0.15_JPRB*(ZRH1580-0.15_JPRB)
    ELSEIF (ZRH1580 > 0.30_JPRB .AND. ZRH1580 <= 0.70_JPRB) THEN
      ZGHNO3_DD = ZGHNO330_DD + (ZGHNO370_DD-ZGHNO330_DD)/0.40_JPRB*(ZRH1580-0.30_JPRB)
      ZGHNO3_SS = ZGHNO330_SS + (ZGHNO370_SS-ZGHNO330_SS)/0.40_JPRB*(ZRH1580-0.30_JPRB)
    ELSEIF (ZRH1580 > 0.70_JPRB ) THEN
      ZGHNO3_DD = ZGHNO370_DD + (ZGHNO380_DD-ZGHNO370_DD)/0.10_JPRB*(ZRH1580-0.70_JPRB)
      ZGHNO3_SS = ZGHNO370_SS + (ZGHNO380_SS-ZGHNO370_SS)/0.10_JPRB*(ZRH1580-0.70_JPRB)
    ENDIF

    ZAIRDM(JL,JK) = (7.24291E16_JPRB*PRSF1(JL,JK)/PT(JL,JK)) * RMD /6.02E23_JPRB * 1E6_JPRB
    LEQSKIP=.FALSE.
    IF (LAEREQSAM4CLIM) THEN
      ZXWH2O=0.0_JPRB
      ZXPMT=0.0_JPRB
      ZXPMS=0.0_JPRB
      ZXSPM=0.0_JPRB
      ZXAPM=0.0_JPRB
      ZXHP=0.0_JPRB
      ZXRHO=0.0_JPRB
      ZXVOL=0.0_JPRB
   ! gases (mol/m^3 air)
      ZXYG(1)= 0._JPRB
      ZXYG(2)= 0._JPRB                    ! HCL
      ZXYG(3)= 0._JPRB
      ZXYG(4)= 0._JPRB                    ! H2SO4
   ! Anions (mol/m^3 air)
      ZXYMA(1)=  PSO4(JL,JK)*ZAIRDM(JL,JK)/ZMWSO4
      IF (ZXYMA(1) < 1.E-15_JPRB) ZXYMA(1)=0._JPRB
      ZXYMA(2)=  0._JPRB                    ! HSO4-
      ZXYMA(3)=  (PNO3_1(JL,JK))*ZAIRDM(JL,JK)/ZMWNO3 + PHNO3(JL,JK)*ZAIRDM(JL,JK)/ZMWHNO3
      IF (ZXYMA(3) < 1.E-15_JPRB) ZXYMA(3)=0._JPRB
      ZXYMA(4)=  0._JPRB                     ! Cl-
      ! cations (mol/m^3 air)
      ZXYPA(1)= PNH4OK(JL,JK)*ZAIRDM(JL,JK)/ZMWNH4+PNH3(JL,JK)*ZAIRDM(JL,JK)/ZMWNH3
      IF (ZXYPA(1) < 1.E-15_JPRB) ZXYPA(1)=0._JPRB
      ZXYPA(2)= 0._JPRB                      ! Na+
      ZXYPA(3)= 0._JPRB                      ! Kµ
      ZXYPA(4)= 0._JPRB                      ! Ca++
      ZXYPA(5)= 0._JPRB                      ! Ng++
      ZTENDHNO3=0._JPRB

      CALL AER_EQSAM4CLIM(PRSF1(JL,JK),PT(JL,JK),ZRHLOC(JL,JK),ZXSPM,ZXAPM,ZXPMS,ZXPMT,ZXRHO,ZXVOL,ZXPH,ZXHP,&
      &                  ZXGF,ZXWH2O,ZXYPA,ZXYPS,ZXYMA,ZXYMS,ZXYG, &
      &                  LMASK,ZDD,LEQSKIP)

      IF (.NOT. LEQSKIP) THEN
        PTHNO3(JL,JK)=(ZXYG(1)*ZMWHNO3/ZAIRDM(JL,JK)-PHNO3(JL,JK))/PTSPHY
        PTNO3_1(JL,JK)=-1._JPRB*PTHNO3(JL,JK)*ZMWNO3/ZMWHNO3
        !PTNO3_1(JL,JK)=((ZXYMA(3)-ZXYG(1))*ZMWNO3/ZAIRDM - PNO3_1(JL,JK))/PTSPHY
        ZTENDHNO3=PTHNO3(JL,JK)
        PTNH3(JL,JK)=(ZXYG(3)*ZMWNH3/ZAIRDM(JL,JK) - PNH3(JL,JK))/PTSPHY
        PTNH4(JL,JK)=-1._JPRB*PTNH3(JL,JK)*ZMWNH3/ZMWNH4
      ENDIF
    ENDIF
    IF (.NOT. LAEREQSAM4CLIM .OR. LEQSKIP) THEN
      !Equilibrium constant based on Mozurkewich, 1993
      ZDRH  = EXP(723.7_JPRB*ZTINV(JL,JK)+1.6954_JPRB) * 1.E-2_JPRB
      ZKPL1 = EXP(-135.94_JPRB+8763._JPRB*ZTINV(JL,JK)+19.12_JPRB*LOG(PT(JL,JK)))
      ZKPL2 = EXP(-122.65_JPRB+9969._JPRB*ZTINV(JL,JK)+16.22_JPRB*LOG(PT(JL,JK)))
      ZKPL3 = EXP(-182.61_JPRB+13875._JPRB*ZTINV(JL,JK)+24.46_JPRB*LOG(PT(JL,JK)))
      ZT0T=ZT0/PT(JL,JK)
      ZCOEF=1.0+LOG(ZT0T)-ZT0T

      ! EQUILIBRIUM CONSTANT NH4NO3(s) <==> NH3(g) + HNO3(g) [atm^2] (ISORROPIA)

      ZKPL= 5.746E-17_JPRB * EXP(-74.38*(ZT0T-1.0_JPRB) + 6.120_JPRB*ZCOEF)


      IF (ZRHLOC(JL,JK) >= ZDRH ) THEN
        ZKPL =&
        & (ZKPL1-ZKPL2*ZRHINV(JL,JK)+ZKPL3*ZRHINV(JL,JK)**2._JPRB)&
        & * ZRHINV(JL,JK)**1.75_JPRB*ZKPL
      ENDIF 

      !Total in moles
      ZAIRDM(JL,JK) = (7.24291E16_JPRB*PRSF1(JL,JK)/PT(JL,JK)) * RMD /6.02E23_JPRB * 1E6_JPRB
      ZTN(JL,JK)    = PHNO3(JL,JK)*ZAIRDM(JL,JK)/ZMWHNO3 + PNO3_1(JL,JK)*ZAIRDM(JL,JK)/ZMWNO3
      ZTA(JL,JK)    = PNH3(JL,JK)*ZAIRDM(JL,JK)/ZMWNH3  + PNH4OK(JL,JK)*ZAIRDM(JL,JK)/ZMWNH4
      ZTDU(JL,JK)   = (PDUST1(JL,JK)*PFRAC_CA1(JL)+PDUST2(JL,JK)*PFRAC_CA1(JL)+PDUST3(JL,JK)*PFRAC_CA2(JL))*ZAIRDM(JL,JK)/ZMWCA
      ZTDU(JL,JK)   = ZTDU(JL,JK)+0.05_JPRB*(PDUST1(JL,JK)+PDUST2(JL,JK)+PDUST3(JL,JK))*ZAIRDM(JL,JK)/ZMWCA
      ZTSS(JL,JK)   = (PSS1(JL,JK)+PSS2(JL,JK)+PSS3(JL,JK))*ZAIRDM(JL,JK)/ZMWNACL
      ZTS(JL,JK)    = PSO4(JL,JK)*ZAIRDM(JL,JK)/ZMWSO4


      ! Step 0 : Sulfate state. Metzger et al. 2002

      ZSO4 = 2.0
      IF (ZTS(JL,JK)> 0.5_JPRB*ZTA(JL,JK)) THEN
        IF(PRHCL(JL,JK) <= ZRHDZ(2_JPIM)) THEN  ! ACCOUNT FOR MIXTURE OF (NH4)2SO4(s) & NH4HSO4(s) & (NH4)3H(SO4)2(s)
          ZSO4=1.677_JPRB    !    (Na)2SO4 &  NaHSO4
          ! ZGG=1.5
        ELSEIF(PRHCL(JL,JK) > ZRHDZ(2_JPIM).AND.PRHCL(JL,JK) <= ZRHDZ(1)) THEN ! MAINLY (Na)2SO4 / (NH4)2SO4(s) & (NH4)3H(SO4)2(s)
          ZSO4=1.75_JPRB
          ! GG=1.5
        ELSEIF(PRHCL(JL,JK) > ZRHDZ(1_JPIM)) THEN   ! (NH4)2SO4(S) & NH4HSO4(S) & SO4-- & HSO4-
          ZSO4=1.5_JPRB   !  (Na)2SO4 &  NaHSO4
        ENDIF
        !ZSO4=1.5_JPRB   !  (Na)2SO4 &  NaHSO4
      ENDIF
      IF (ZTS(JL,JK)> ZTA(JL,JK)) THEN
        ZSO4 = 1.0_JPRB
      ENDIF

      ZTADISP(JL,JK)  = MAX((ZTA(JL,JK)-ZSO4*ZTS(JL,JK)),0._JPRB)
      ZTADISP(JL,JK)  = MAX((ZTADISP(JL,JK)-ZTDU(JL,JK)),0._JPRB)
      ZTADISP(JL,JK)  = MAX((ZTADISP(JL,JK)-0.1_JPRB*ZTSS(JL,JK)),0._JPRB)
      ZTNTA(JL,JK)    = ZTN(JL,JK)*ZTADISP(JL,JK)
      ZNH4PINI(JL,JK) = ZSO4*ZTS(JL,JK)

      ! Step 1: Equilibrium concentrations

      IF ( ZTNTA(JL,JK) > ZKPL ) THEN

        ZWRK1 = (ZTADISP(JL,JK)+ZTN(JL,JK))**2._JPRB-4._JPRB*(ZTNTA(JL,JK)-ZKPL)
        ZWRK1    = MAX(ZWRK1,0._JPRB)
        ZWRK2    = 0.5_JPRB*(ZTADISP(JL,JK)+ZTN(JL,JK)-SQRT(ZWRK1))
        ZWRK2    = MAX(ZWRK2,0._JPRB)
        ZWRK2    = MIN(ZWRK2,ZTN(JL,JK))
        ZWRK2    = MIN(ZWRK2,ZTADISP(JL,JK))

        ZHNO3EQ  = MAX(ZTN(JL,JK)-ZWRK2,0._JPRB)
        ZNH3EQ   = MAX(ZTADISP(JL,JK)- ZWRK2,0._JPRB)

        !Step 3: Update aerosol phase

        ZNO3MOL = MAX((ZTN(JL,JK)-ZHNO3EQ),0._JPRB)
        ZNH4MOL = MAX((ZTADISP(JL,JK)-ZNH3EQ),0._JPRB)
        ZNH4MOL = ZNH4MOL + ZNH4PINI(JL,JK)

        PTNO3_1(JL,JK)=(ZNO3MOL/ZAIRDM(JL,JK)*ZMWNO3-PNO3_1(JL,JK))/PTSPHY
        PTNH4(JL,JK)=(ZNH4MOL/ZAIRDM(JL,JK)*ZMWNH4-PNH4OK(JL,JK))/PTSPHY
    
      ELSE
        PTNO3_1(JL,JK)=-PNO3_1(JL,JK)/PTSPHY
        ZNH4MOL = ZNH4PINI(JL,JK)
        PTNH4(JL,JK)=(ZNH4MOL/ZAIRDM(JL,JK)*ZMWNH4-PNH4OK(JL,JK))/PTSPHY
      ENDIF


      ZNH4PINI(JL,JK)=ZNH4PINI(JL,JK)-PNH4OK(JL,JK)*ZAIRDM(JL,JK)/ZMWNH4
      ! PTNH4(JL,JK)=PTNH4(JL,JK)+(ZNH4PINI(JL,JK)/ZAIRDM(JL,JK)*ZMWNH4)/PTSPHY
      PTHNO3(JL,JK)=-1._JPRB*PTNO3_1(JL,JK)*ZMWHNO3/ZMWNO3
      PTNH3(JL,JK)=-1._JPRB*PTNH4(JL,JK)*ZMWNH3/ZMWNH4
    ENDIF ! NOT LAEREQSAM4CLIM or LEQSKIP

    ! Check negatives..

    ZHNO3_TEST=PHNO3(JL,JK)-(PTNO3_1(JL,JK)*ZMWHNO3/ZMWNO3)*PTSPHY
    IF (ZHNO3_TEST < 0_JPRB) THEN
      ! Maximum is to remove all HNO3
      ZTHNO3_TMP=PTHNO3(JL,JK)
      PTHNO3(JL,JK)=-PHNO3(JL,JK)/PTSPHY
      ! total change in HNO3 tendency= New tendency-old tendency  > 0.
      ZTHNO3_TMP=PTHNO3(JL,JK)-ZTHNO3_TMP

      ! Remove this change in tendency from nitrate_1 production tendency,
      ! resulting in smaller NO3_1 tendency
      PTNO3_1(JL,JK)=PTNO3_1(JL,JK)-ZTHNO3_TMP*ZMWNO3/ZMWHNO3
    ENDIF
    ZNH3_TEST=PNH3(JL,JK)+PTNH3(JL,JK)*PTSPHY
    IF (ZNH3_TEST < 0_JPRB) THEN
      ! Maximum is to remove all HNO3
      ZTNH3_TMP=PTNH3(JL,JK)
      PTNH3(JL,JK)=-PNH3(JL,JK)/PTSPHY
      ! total change in HNO3 tendency= New tendency-old tendency  > 0.
      ZTNH3_TMP=PTNH3(JL,JK)-ZTNH3_TMP

      ! Remove this change in tendency from nitrate_1 production tendency,
      ! resulting in smaller NO3_1 tendency
      PTNH4(JL,JK)=PTNH4(JL,JK)-ZTNH3_TMP*ZMWNH4/ZMWNH3
    ENDIF

    ! Uptake of HNO3 on dust, integrated
    ZMFP=3._JPRB * ZDGHNO3(JL,JK) / SQRT(8._JPRB*ZRGAS*PT(JL,JK)/RPI/ZMWHNO3)
    ZKN_DD1=2._JPRB * ZMFP / RMMD_DD(1)
    ZKN_DD2=2._JPRB * ZMFP / RMMD_DD(2)
    ZKN_DD3=2._JPRB * ZMFP / RMMD_DD(3)
    ! For SS, use dry RMMD here to be multiplied by growth factor
    ZKN_SS1=2._JPRB * ZMFP / (RMMD_SS(1) * RSSGROWTH_RHTAB(IIRH)) 
    ZKN_SS2=2._JPRB * ZMFP / (RMMD_SS(2) * RSSGROWTH_RHTAB(IIRH)) 
    ZKN_SS3=2._JPRB* ZMFP / (RMMD_SS(3) * RSSGROWTH_RHTAB(IIRH)) 

    ZKHNO3_DD1 = (2._JPRB*RPI*RMMD_DD(1)*1E-6*ZDGHNO3(JL,JK)) /&
                &(1._JPRB + ZKN_DD1 * (4._JPRB/(3._JPRB*ZGHNO3_DD)))
    ZKHNO3_DD2 = (2._JPRB*RPI*RMMD_DD(2)*1E-6*ZDGHNO3(JL,JK)) /&
                &(1._JPRB + ZKN_DD2 * (4._JPRB/(3._JPRB*ZGHNO3_DD)))
    ZKHNO3_DD3 = (2._JPRB*RPI*RMMD_DD(3)*1E-6*ZDGHNO3(JL,JK)) /&
                &(1._JPRB + ZKN_DD3 * (4._JPRB/(3._JPRB*ZGHNO3_DD)))

    ZKHNO3_SS1 =(2._JPRB*RPI*RMMD_SS(1)*RSSGROWTH_RHTAB(IIRH))*1E-6*ZDGHNO3(JL,JK)/&
                &(1._JPRB + ZKN_SS1 * (4._JPRB/(3._JPRB*ZGHNO3_SS)))
    ZKHNO3_SS2 =(2._JPRB*RPI*RMMD_SS(2)*RSSGROWTH_RHTAB(IIRH))*1E-6*ZDGHNO3(JL,JK)/&
                &(1._JPRB + ZKN_SS2 * (4._JPRB/(3._JPRB*ZGHNO3_SS)))
    ZKHNO3_SS3 =(2._JPRB*RPI*RMMD_SS(3)*RSSGROWTH_RHTAB(IIRH))*1E-6*ZDGHNO3(JL,JK)/&
                &(1._JPRB + ZKN_SS3 * (4._JPRB/(3._JPRB*ZGHNO3_SS)))


    ZKHNO30(JL,JK)= MAX(0._JPRB,ZKHNO3_DD1*ZNTOTDUST1(JL,JK)*PFRAC_CA1(JL)*ZRATIO_CA_CACO3+&
                    &ZKHNO3_DD2*ZNTOTDUST2(JL,JK)*PFRAC_CA1(JL)*ZRATIO_CA_CACO3+&
                    &ZKHNO3_DD3*ZNTOTDUST3(JL,JK)*PFRAC_CA2(JL)*ZRATIO_CA_CACO3)
    ZKHNO3(JL,JK)=ZKHNO30(JL,JK)  + MAX(0._JPRB,ZKHNO3_SS1*ZNTOTSS1(JL,JK) +&
                 &ZKHNO3_SS2*ZNTOTSS2(JL,JK) + ZKHNO3_SS3*ZNTOTSS3(JL,JK))
    !Calcium limitation
    ZCAMMR(JL,JK)    =(PDUST1(JL,JK)+PDUST2(JL,JK))*PFRAC_CA1(JL)*ZRATIO_CA_CACO3
    ZCAMMR(JL,JK)    = ZCAMMR(JL,JK)+PDUST3(JL,JK)*PFRAC_CA2(JL)*ZRATIO_CA_CACO3
    ZCAVMR(JL,JK)    = ZCAMMR(JL,JK)/40._JPRB*29._JPRB*0.5_JPRB !Moles of Ca available for Ca(NO3)2 formation
    ZCINO3(JL,JK) = PNO3_2(JL,JK)/62._JPRB*29._JPRB
    ZNAMMR(JL,JK)    =PSS1(JL,JK)+PSS2(JL,JK)+PSS3(JL,JK)
    ZNAVMR(JL,JK)    = ZNAMMR(JL,JK)/58._JPRB*29._JPRB*ZMWNA/ZMWNACL
    IF (ZCINO3(JL,JK) > ZCAVMR(JL,JK)) ZKHNO3(JL,JK)= ZKHNO3(JL,JK)-ZKHNO30(JL,JK)
    IF (ZCINO3(JL,JK) > ZNAVMR(JL,JK)) ZKHNO3(JL,JK)= ZKHNO30(JL,JK)

    PTNO3_2(JL,JK)=MAX(0._JPRB,ZKHNO30(JL,JK))*(PHNO3(JL,JK)+PTHNO3(JL,JK)*PTSPHY)*ZMWNO3/ZMWHNO3
    PTNO3_2(JL,JK)=PTNO3_2(JL,JK)+MAX(0._JPRB,(ZKHNO3(JL,JK)-ZKHNO30(JL,JK)))*(PHNO3(JL,JK)+PTHNO3(JL,JK)*PTSPHY)*ZMWNO3/ZMWHNO3

    ! Update dust tendencies
  
    ZTDUST1=MAX(0._JPRB,ZKHNO3_DD1*ZNTOTDUST1(JL,JK)*PFRAC_CA1(JL)*ZRATIO_CA_CACO3)*PHNO3(JL,JK)*ZMWCACO3*0.5_JPRB
    ZTDUST2=MAX(0._JPRB,ZKHNO3_DD2*ZNTOTDUST2(JL,JK)*PFRAC_CA1(JL)*ZRATIO_CA_CACO3)*PHNO3(JL,JK)*ZMWCACO3*0.5_JPRB
    ZTDUST3=MAX(0._JPRB,ZKHNO3_DD3*ZNTOTDUST3(JL,JK)*PFRAC_CA2(JL)*ZRATIO_CA_CACO3)*PHNO3(JL,JK)*ZMWCACO3*0.5_JPRB
    PTDUST1(JL,JK)=PTDUST1(JL,JK) -ZTDUST1
    PTDUST2(JL,JK)=PTDUST2(JL,JK) -ZTDUST2
    PTDUST3(JL,JK)=PTDUST3(JL,JK) -ZTDUST3

    ! Update sea-salt tendencies
    ZTSS1=MAX(0._JPRB,ZKHNO3_SS1*ZNTOTSS1(JL,JK))*PHNO3(JL,JK)*ZMWNACL
    ZTSS2=MAX(0._JPRB,ZKHNO3_SS2*ZNTOTSS2(JL,JK))*PHNO3(JL,JK)*ZMWNACL
    ZTSS3=MAX(0._JPRB,ZKHNO3_SS3*ZNTOTSS3(JL,JK))*PHNO3(JL,JK)*ZMWNACL

    PTSS1(JL,JK)=PTSS1(JL,JK) -ZTSS1
    PTSS2(JL,JK)=PTSS2(JL,JK) -ZTSS2
    PTSS3(JL,JK)=PTSS3(JL,JK) -ZTSS3

    PTHNO3(JL,JK)=PTHNO3(JL,JK) - PTNO3_2(JL,JK)*ZMWHNO3/ZMWNO3
    ! Check negatives..

    ZHNO3_TEST=PHNO3(JL,JK)+PTHNO3(JL,JK)*PTSPHY
    IF (ZHNO3_TEST < 0_JPRB) THEN
      ! Maximum is to remove all HNO3
      ZTHNO3_TMP=PTHNO3(JL,JK)
      PTHNO3(JL,JK)=-PHNO3(JL,JK)/PTSPHY
      ! total change in HNO3 tendency= New tendency-old tendency  > 0.
      ZTHNO3_TMP=PTHNO3(JL,JK)-ZTHNO3_TMP

      ! Remove this change in tendency from nitrate_1 production tendency,
      ! resulting in smaller NO3_1 tendency
      PTNO3_2(JL,JK)=PTNO3_2(JL,JK)-ZTHNO3_TMP*ZMWNO3/ZMWHNO3
    ENDIF

!   IF (JK==KLEV) THEN
!     WRITE(*,*) 'NITRATE2 HNO3 PROD=',JL,PTNO3_2(JL,JK),ZKHNO3(JL,JK),ZKHNO30(JL,JK), &
!       & PTHNO3(JL,JK),PHNO3(JL,JK),ZTDUST1,ZTDUST2,ZTDUST3,PFRAC_CA1(JL),PFRAC_CA2(JL)
!    ENDIF
   ENDDO
ENDDO

DO JL=KIDIA,KFDIA
  PFNO3_1(JL)=0.0_JPRB
  PFNO3_2(JL)=0.0_JPRB
  PFNH4(JL)=0.0_JPRB
ENDDO

DO JK=1,KLEV
  DO JL=KIDIA,KFDIA
    PFNO3_1(JL) = PFNO3_1(JL) + PTNO3_1(JL,JK)*(PDP(JL,JK))/RG
    PFNO3_2(JL) = PFNO3_2(JL) + PTNO3_2(JL,JK)*(PDP(JL,JK))/RG
    PFNH4(JL) = PFNH4(JL) + PTNH4(JL,JK)*(PDP(JL,JK))/RG
  ENDDO
ENDDO

!-----------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('AER_NO3NH4',1,ZHOOK_HANDLE)
END SUBROUTINE AER_NO3NH4
