! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE CPSPE(&
 & KPROMA ,KSTART ,KPROF  ,KLEVS  ,KLEVXP , KLEVO,KLEVSN, &
 & KFLDXP ,KFLDXP2,PDT,&
 & PTSAE1 ,PTLE1  ,PWSAE1,&
 & PISAE1,&
 & PWLE1  ,PSNSE1,PWSNE1,&
 & PASNE1 ,PRSNE1 ,PTSNE1,&
 & PTLICEE1, PTLMNWE1,&
 & PTLWMLE1, PTLBOTE1,&
 & PTLSFE1 ,&
 & PHLICEE1, PHLMLE1,&
 & PEXTRE1,PXTR2E1,&
 & PUOE1  ,PVOE1  ,PTOE1  ,PSOE1, & !KPP
 & PTSA1  ,PTL1   ,PWSA1,&
 & PISA1,&
 & PWL1   ,PSNS1,PWSN1,&
 & PASN1  ,PRSN1  ,PTSN1,&
 & PTLIC1, PTLMN1,&
 & PTLML1, PTLBT1,&
 & PTLSF1,&
 & PHLIC1, PHLM1,&
 & PEXTRP1,PXTRP21,&
 & PUO1  ,PVO1  ,PTO1  ,PSO1 &     !KPP or ocean TKE
 & )  

!**** *CPSPE* - COMPUTE NEW T+DT VALUES FOR SURFACE FIELDS

!     PURPOSE.                                                                  
!     --------                                                        

!     COMPUTE THE NEW T+DT VALUES FOR THE SURFACE FIELDS
!     FROM T-DT VALUES AND TENDENCIES FOR ECMWF PHYSICS

!**   INTERFACE. CALL CPSPE(...)
!     ----------
!                CPSPE IS CALLED FROM POSTPHY

!     INPUT PARAMETERS :

!     KPROMA   : HORISONTAL DIMENSION
!     KSTART   : START POINT
!     KPROF    : END POINT
!     KLEVS   : NUMBER OF SOIL LAYERS
!     KLEVSN  : NUMBER OF SNOW LAYERS
!     KFLEVO   : NUMBER OF OCEAN MIXED LAYERS  !KPP
!     PDT      : TIME STEP FOR PHYSICS                                                  
!     PSNSE1   : TENDENCY OF MULTI-LAYER SNOW MASS PER UNIT SURFACE
!     PWLE1    : TENDENCY OF SKIN RESERVOIR WATER CONTENT
!     PTLE1    : TENDENCY OF SKIN TEMPERATURE
!     PTSAE1   : TENDENCY OF MULTI-LAYER SOIL TEMPERATURE
!     PWSAE1   : TENDENCY OF MULTI-LAYER SOIL WETNESS
!     PTLICEE1 : TENDENCY OF LAKE ICE TEMPERATURE
!     PTLMNWE1 : TENDENCY OF LAKE MEAN WATER COLUMN TEMPERATURE
!     PTLWMLE1 : TENDENCY OF LAKE MIXED-LAYER TEMPERATURE
!     PTLBOTE1 : TENDENCY OF LAKE BOTTOM TEMPERATURE
!     PTLSFE1  : TENDENCY OF LAKE SHAPE FACTOR (thermocline)
!     PHLICEE1 : TENDENCY OF LAKE ICE THICKNESS
!     PHLMLE1  : TENDENCY OF LAKE MIXED-LAYER THICKNESS
!     PEXTRE1  : TENDENCY OF MULTI-LAYER EXTRA FIELDS
!     PXTR2E1  : TENDENCY OF SINGLE-LAYER EXTRA FIELDS
!     PUOE1    : TENDENCY OF OCEAN VELOCITY (U)  
!     PVOE1    : TENDENCY OF OCEAN VELOCITY (V)  
!     PTOE1    : TENDENCY OF OCEAN TEMPERATURE   
!     PSOE1    : TENDENCY OF OCEAN SALINITY      

!     OUTPUT PARAMETERS: (T+DT VALUES)

!     PSNS1    : SNOW MASS PER UNIT SURFACE
!     PWL1     : SKIN RESERVOIR WATER CONTENT
!     PTL1     : SKIN TEMPERATURE
!     PTSA1    : MULTI-LAYER SOIL TEMPERATURE
!     PWSA1    : MULTI-LAYER SOIL WETNESS
!     PTLIC1   : LAKE ICE TEMPERATURE
!     PTLMN1   : LAKE MEAN WATER COLUMN TEMPERATURE
!     PTLML1   : LAKE MIXED-LAYER TEMPERATURE
!     PTLBT1   : LAKE BOTTOM TEMPERATURE
!     PTLSF1   : LAKE SHAPE FACTOR (thermocline)
!     PHLIC1   : LAKE ICE THICKNESS
!     PHLM1    : LAKE MIXED-LAYER THICKNESS
!     PEXTRP1  : MULTI-LAYER EXTRA FIELDS   
!     PXTRP21  : SINGLE-LAYER EXTRA FIELDS   
!     PUO1     : OCEAN VELOCITY (U)  
!     PVO1     : OCEAN VELOCITY (V) 
!     PTO1     : OCEAN TEMPERATURE 
!     PSO1     : OCEAN SALINITY    

!     AUTHOR.
!     -------
!      ORIGINAL     J.-J. Morcrette

!     MODIFICATION
!     ------------
!      Modified     D.Salmond 15-10-01 FULLIMP mods
!      Modified     Y.Takaya  02-02-09 Ocean mixed layer model
!      Modified     G.Balsamo 24-10-12 lake model
!      Modified     E.Dutra/G.Arduini : Jan 2018 Snow multi-layer 
!     ------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

IMPLICIT NONE

INTEGER(KIND=JPIM),INTENT(IN)    :: KPROMA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVS 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVSN 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVXP
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEVO  !KPP 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLDXP 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLDXP2 
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTART 
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROF 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDT 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSAE1(KPROMA,KLEVS) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTLE1(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWSAE1(KPROMA,KLEVS) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PISAE1(KPROMA,KLEVS) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWLE1(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSNSE1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PASNE1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRSNE1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSNE1(KPROMA,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWSNE1(KPROMA,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTLICEE1(KPROMA)       !FLAKE
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTLMNWE1(KPROMA)       !FLAKE
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTLWMLE1(KPROMA)       !FLAKE
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTLBOTE1(KPROMA)       !FLAKE
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTLSFE1(KPROMA)        !FLAKE
REAL(KIND=JPRB)   ,INTENT(IN)    :: PHLICEE1(KPROMA)       !FLAKE
REAL(KIND=JPRB)   ,INTENT(IN)    :: PHLMLE1(KPROMA)        !FLAKE
REAL(KIND=JPRB)   ,INTENT(IN)    :: PEXTRE1(KPROMA,KLEVXP,KFLDXP) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXTR2E1(KPROMA,KFLDXP2) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PUOE1(KPROMA,KLEVO)  !KPP
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVOE1(KPROMA,KLEVO)  !KPP
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTOE1(KPROMA,KLEVO)  !KPP
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSOE1(KPROMA,KLEVO)  !KPP
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTSA1(KPROMA,KLEVS) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTL1(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PWSA1(KPROMA,KLEVS) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PISA1(KPROMA,KLEVS) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PWL1(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSNS1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PASN1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PRSN1(KPROMA,KLEVSN) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTSN1(KPROMA,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PWSN1(KPROMA,KLEVSN)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTLIC1(KPROMA)       !FLAKE
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTLMN1(KPROMA)       !FLAKE
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTLML1(KPROMA)       !FLAKE
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTLBT1(KPROMA)       !FLAKE
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTLSF1(KPROMA)       !FLAKE
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PHLIC1(KPROMA)       !FLAKE
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PHLM1(KPROMA)        !FLAKE
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PEXTRP1(KPROMA,KLEVXP,KFLDXP) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PXTRP21(KPROMA,KFLDXP2) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PUO1(KPROMA,KLEVO)   !KPP 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PVO1(KPROMA,KLEVO)   !KPP 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PTO1(KPROMA,KLEVO)   !KPP 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PSO1(KPROMA,KLEVO)   !KPP 
INTEGER(KIND=JPIM) :: JLEV, JROF, JVAR
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

!*        1.   COMPUTE T+DT VALUES
!              -------------------
IF (LHOOK) CALL DR_HOOK('CPSPE',0,ZHOOK_HANDLE)
DO JLEV=1,KLEVS
  DO JROF = KSTART, KPROF
    PTSA1(JROF,JLEV) = PTSA1(JROF,JLEV) + PDT*PTSAE1(JROF,JLEV)
    PWSA1(JROF,JLEV) = PWSA1(JROF,JLEV) + PDT*PWSAE1(JROF,JLEV)
    PISA1(JROF,JLEV) = PISA1(JROF,JLEV) + PDT*PISAE1(JROF,JLEV)
  ENDDO
ENDDO
DO JLEV=1,KLEVSN
  DO JROF = KSTART, KPROF
    PSNS1(JROF,JLEV)= PSNS1(JROF,JLEV) + PDT*PSNSE1(JROF,JLEV)
    PRSN1(JROF,JLEV)= PRSN1(JROF,JLEV) + PDT*PRSNE1(JROF,JLEV)
    PTSN1(JROF,JLEV)= PTSN1(JROF,JLEV) + PDT*PTSNE1(JROF,JLEV)
    PWSN1(JROF,JLEV)= PWSN1(JROF,JLEV) + PDT*PWSNE1(JROF,JLEV)
    PASN1(JROF,JLEV)= PASN1(JROF,JLEV) + PDT*PASNE1(JROF,JLEV) ! not necessary, but all fields of SNOWG have the level dimension
  ENDDO
ENDDO

DO JROF=KSTART,KPROF
  PWL1(JROF) = PWL1(JROF)  + PDT*PWLE1(JROF)
  PTL1(JROF) = PTL1(JROF)  + PDT*PTLE1(JROF)

!FLAKE
  PTLIC1(JROF)= PTLIC1(JROF) + PDT*PTLICEE1(JROF) 
  PTLMN1(JROF)= PTLMN1(JROF) + PDT*PTLMNWE1(JROF)
  PTLML1(JROF)= PTLML1(JROF) + PDT*PTLWMLE1(JROF)
  PTLBT1(JROF)= PTLBT1(JROF) + PDT*PTLBOTE1(JROF)
  PTLSF1(JROF)= PTLSF1(JROF) + PDT*PTLSFE1(JROF)
  PHLIC1(JROF)= PHLIC1(JROF) + PDT*PHLICEE1(JROF)
  PHLM1(JROF) = PHLM1(JROF)  + PDT*PHLMLE1(JROF)
ENDDO
DO JVAR=1,KFLDXP
  DO JLEV=1,KLEVXP
    DO JROF=KSTART,KPROF
      PEXTRP1(JROF,JLEV,JVAR)=PEXTRP1(JROF,JLEV,JVAR)&
       & + PDT*PEXTRE1(JROF,JLEV,JVAR)  
    ENDDO
  ENDDO
ENDDO
DO JVAR=1,KFLDXP2
  DO JROF=KSTART,KPROF
    PXTRP21(JROF,JVAR)=PXTRP21(JROF,JVAR)+PDT*PXTR2E1(JROF,JVAR)
  ENDDO
ENDDO

!-- KPP or Ocean TKE
DO JLEV=1,KLEVO
  DO JROF = KSTART, KPROF
    PUO1(JROF,JLEV) = PUO1(JROF,JLEV) + PDT*PUOE1(JROF,JLEV)   
    PVO1(JROF,JLEV) = PVO1(JROF,JLEV) + PDT*PVOE1(JROF,JLEV)   
    PTO1(JROF,JLEV) = PTO1(JROF,JLEV) + PDT*PTOE1(JROF,JLEV)   
    PSO1(JROF,JLEV) = PSO1(JROF,JLEV) + PDT*PSOE1(JROF,JLEV)   
  ENDDO
ENDDO

!     ------------------------------------------------------------------

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('CPSPE',1,ZHOOK_HANDLE)
END SUBROUTINE CPSPE

