! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE STATE_UPDATE(YDPHY2,KDIM,PISTATE,PTEND,POSTATE)
! Update state by cumulated tendency
  !     PISTATE  - input state
  !     PTEND    - updating tendency
  !     POSTATE  - updated state (output)
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMPHY2  , ONLY : TPHY2
USE YOMPHYDER, ONLY : STATE_TYPE, MASK_GFL_TYPE, DIMENSION_TYPE
USE YOECLDP  , ONLY : NCLDQL, NCLDQR, NCLDQI, NCLDQS

IMPLICIT NONE

TYPE(TPHY2)         , INTENT(INOUT):: YDPHY2
TYPE (DIMENSION_TYPE),INTENT(IN)   :: KDIM 
TYPE (STATE_TYPE),    INTENT(IN)   :: PISTATE
TYPE (STATE_TYPE),    INTENT(IN)   :: PTEND
TYPE (STATE_TYPE),    INTENT(INOUT):: POSTATE

INTEGER (KIND=JPIM)  :: JJLEV
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
  
IF (LHOOK) CALL DR_HOOK('STATE_UPDATE',0,ZHOOK_HANDLE)
ASSOCIATE(TSPHY=>YDPHY2%TSPHY)

DO JJLEV=1,KDIM%KLEV
  POSTATE%U(KDIM%KIDIA:KDIM%KFDIA,JJLEV)=PISTATE%U(KDIM%KIDIA:KDIM%KFDIA,JJLEV) &
    &  + TSPHY*PTEND%U(KDIM%KIDIA:KDIM%KFDIA,JJLEV)
  POSTATE%V(KDIM%KIDIA:KDIM%KFDIA,JJLEV)=PISTATE%V(KDIM%KIDIA:KDIM%KFDIA,JJLEV) &
    &  + TSPHY*PTEND%V(KDIM%KIDIA:KDIM%KFDIA,JJLEV)
  POSTATE%T(KDIM%KIDIA:KDIM%KFDIA,JJLEV)=PISTATE%T(KDIM%KIDIA:KDIM%KFDIA,JJLEV) &
    &  + TSPHY*PTEND%T(KDIM%KIDIA:KDIM%KFDIA,JJLEV)
  IF (POSTATE%KEYMASK%Q) POSTATE%Q(KDIM%KIDIA:KDIM%KFDIA,JJLEV)  =PISTATE%Q(KDIM%KIDIA:KDIM%KFDIA,JJLEV) &
    &  + TSPHY*PTEND%Q(KDIM%KIDIA:KDIM%KFDIA,JJLEV)
  IF (POSTATE%KEYMASK%O3) POSTATE%O3(KDIM%KIDIA:KDIM%KFDIA,JJLEV)=PISTATE%O3(KDIM%KIDIA:KDIM%KFDIA,JJLEV) &
    &  + TSPHY*PTEND%O3(KDIM%KIDIA:KDIM%KFDIA,JJLEV)
  IF (POSTATE%KEYMASK%A) POSTATE%A(KDIM%KIDIA:KDIM%KFDIA,JJLEV)  =PISTATE%A(KDIM%KIDIA:KDIM%KFDIA,JJLEV) &
    &  + TSPHY*PTEND%A(KDIM%KIDIA:KDIM%KFDIA,JJLEV)
  IF (POSTATE%KEYMASK%QL) POSTATE%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQL)= &
    & PISTATE%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQL)+TSPHY*PTEND%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQL)
  IF (POSTATE%KEYMASK%QI) POSTATE%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQI)= &
    & PISTATE%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQI)+TSPHY*PTEND%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQI)
  IF (POSTATE%KEYMASK%QR) POSTATE%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQR)= &
    & PISTATE%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQR)+TSPHY*PTEND%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQR)
  IF (POSTATE%KEYMASK%QS) POSTATE%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQS)= &
    & PISTATE%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQS)+TSPHY*PTEND%CLD(KDIM%KIDIA:KDIM%KFDIA,JJLEV,NCLDQS)
  IF (POSTATE%KEYMASK%TKE) POSTATE%TKE(KDIM%KIDIA:KDIM%KFDIA,JJLEV)  =PISTATE%TKE(KDIM%KIDIA:KDIM%KFDIA,JJLEV) &
    &  + TSPHY*PTEND%TKE(KDIM%KIDIA:KDIM%KFDIA,JJLEV)
ENDDO

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('STATE_UPDATE',1,ZHOOK_HANDLE)

END SUBROUTINE STATE_UPDATE
