! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE SURFTSTP_LAYER(YDSURF, &
  & YDEPHY,YDRIP,YDPHY2,KDIM,STATE,PAUX,PSURF,SURFL,LLKEYS,FLUX,PDDHS)

!**** *SURFTSTP_LAYER* - Layer routine calling time stepping of surface scheme

!     PURPOSE.
!     --------

!**   INTERFACE.
!     ----------

!        EXPLICIT ARGUMENTS :
!        --------------------
!     ==== INPUTS ===
! KDIM     : Derived variable for dimensions
! state    : Derived variable for model state 
! PAUX     : Derived variables for general auxiliary quantities

!     ==== Input/output ====
! PSURF    : Derived variables for general surface quantities
! SURFL    : Derived variables for local surface quantities
! LLKEYS   : Derived variable with keys
! FLUX     : Derived variable for fluxes
! PDDHS    : Derived variable for DDH files

!        IMPLICIT ARGUMENTS :   NONE
!        --------------------

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF RESEARCH DEPARTMENT DOCUMENTATION OF THE IFS

!     AUTHOR.
!     -------
!      Original : 2012-11-23  F. VANA (c) ECMWF

!     MODIFICATIONS.
!     --------------
!      K. Yessad (July 2014): Move some variables.
!      E. Dutra : 10/10/2014  add net longwave tiled
!-----------------------------------------------------------------------

USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1     , ONLY : JPIM ,   JPRB
USE YOMHOOK      , ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMPHYDER    , ONLY : DIMENSION_TYPE, STATE_TYPE, AUX_TYPE, &
   &                      SURF_AND_MORE_TYPE, SURF_AND_MORE_LOCAL_TYPE, KEYS_LOCAL_TYPE, &
   &                      FLUX_TYPE, DDH_SURF_TYPE
USE YOMRIP       , ONLY : TRIP
USE YOMCT3       , ONLY : NSTEP
USE YOMPHY2      , ONLY : TPHY2
USE YOMCTESSELDIM, ONLY: IKVTYPES,IKDHVBIOS,IKDHFBIOS,IKDHVVEGS,IKDHFVEGS
USE YOEPHY       , ONLY : TEPHY

!-----------------------------------------------------------------------

IMPLICIT NONE

TYPE(TSURF), INTENT(INOUT) :: YDSURF
TYPE(TEPHY) ,INTENT(INOUT) :: YDEPHY
TYPE(TPHY2) ,INTENT(INOUT) :: YDPHY2
TYPE(TRIP)  ,INTENT(INOUT) :: YDRIP
TYPE (DIMENSION_TYPE)          , INTENT (IN)   :: KDIM
TYPE (STATE_TYPE)              , INTENT (IN)   :: STATE
TYPE (AUX_TYPE)                , INTENT (IN)   :: PAUX
TYPE (SURF_AND_MORE_TYPE)      , INTENT(INOUT) :: PSURF
TYPE (SURF_AND_MORE_LOCAL_TYPE), INTENT(INOUT) :: SURFL
TYPE (KEYS_LOCAL_TYPE)         , INTENT(INOUT) :: LLKEYS
TYPE (FLUX_TYPE)               , INTENT(INOUT) :: FLUX
TYPE (DDH_SURF_TYPE)           , INTENT(INOUT) :: PDDHS
!-----------------------------------------------------------------------
INTEGER(KIND=JPIM) :: IVEG(KDIM%KLON,IKVTYPES)                       !CTESSEL

REAL(KIND=JPRB) :: ZLAIVT(KDIM%KLON,IKVTYPES)                        !CTESSEL
REAL(KIND=JPRB) :: ZCVT(KDIM%KLON,IKVTYPES)                          !CTESSEL
REAL(KIND=JPRB) :: ZRESPBSTR(KDIM%KLON,IKVTYPES)                     !CTESSEL
REAL(KIND=JPRB) :: ZRESPBSTR2(KDIM%KLON,IKVTYPES)                    !CTESSEL
REAL(KIND=JPRB) :: ZBIOMASS_LAST(KDIM%KLON,IKVTYPES)                 !CTESSEL
REAL(KIND=JPRB) :: ZBIOMASSTR_LAST(KDIM%KLON,IKVTYPES)               !CTESSEL
REAL(KIND=JPRB) :: ZBIOMASSTR2_LAST(KDIM%KLON,IKVTYPES)              !CTESSEL 
REAL(KIND=JPRB) :: ZBLOSSVT(KDIM%KLON,IKVTYPES)                      !CTESSEL
REAL(KIND=JPRB) :: ZBGAINVT(KDIM%KLON,IKVTYPES)                      !CTESSEL
REAL(KIND=JPRB) :: ZLAI(KDIM%KLON)                                   !CTESSEL
REAL(KIND=JPRB) :: ZBIOM(KDIM%KLON)                                  !CTESSEL
REAL(KIND=JPRB) :: ZBLOSS(KDIM%KLON)                                 !CTESSEL
REAL(KIND=JPRB) :: ZBGAIN(KDIM%KLON)                                 !CTESSEL
REAL(KIND=JPRB) :: ZBIOMSTR(KDIM%KLON)                               !CTESSEL
REAL(KIND=JPRB) :: ZBIOMSTR2(KDIM%KLON)                              !CTESSEL
REAL(KIND=JPRB) :: ZLAIE1(KDIM%KLON,IKVTYPES)                        !CTESSEL
REAL(KIND=JPRB) :: ZBSTRE1(KDIM%KLON,KDIM%KLEVS)                     !CTESSEL
REAL(KIND=JPRB) :: ZBSTR2E1(KDIM%KLON,IKVTYPES)                      !CTESSEL
REAL(KIND=JPRB) :: ZDHBIOS(KDIM%KLON,IKVTYPES,IKDHVBIOS+IKDHFBIOS)   !CTESSEL

INTEGER(KIND=JPIM) :: JL

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-----------------------------------------------------------------------

#include "surftstp.h"

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER',0,ZHOOK_HANDLE)
ASSOCIATE(LESICE=>YDEPHY%LESICE, YSURF=>YDEPHY%YSURF, &
 & NSTART=>YDRIP%NSTART, &
 & YSD_V2=>YDSURF%YSD_V2, YSD_V3=>YDSURF%YSD_V3, YSD_VF=>YDSURF%YSD_VF, &
 & YSD_WS=>YDSURF%YSD_WS, YSP_OM=>YDSURF%YSP_OM, YSP_RR=>YDSURF%YSP_RR, &
 & YSP_SB=>YDSURF%YSP_SB, YSP_SG=>YDSURF%YSP_SG, YSP_SL=>YDSURF%YSP_SL, &
 & TSPHY=>YDPHY2%TSPHY)
!     ------------------------------------------------------------------

!*         0.     INITIALIZATION FOR CTESSEL DYNAMICS

ZRESPBSTR(:,:)=0._JPRB
ZRESPBSTR2(:,:)=0._JPRB
ZBIOMASS_LAST(:,:)=0._JPRB
ZBIOMASSTR_LAST(:,:)=0._JPRB
ZBIOMASSTR2_LAST(:,:)=0._JPRB 
ZBLOSSVT(:,:)=0._JPRB
ZBGAINVT(:,:)=0._JPRB
ZLAIE1(:,:)=0._JPRB
ZBSTRE1(:,:)=0._JPRB
ZBSTR2E1(:,:)=0._JPRB

!*         1.     UNROLL THE DERIVED STRUCTURES AND CALL SURFTSTP

CALL SURFTSTP  (YDSURF=YSURF, KIDIA=KDIM%KIDIA, KFDIA=KDIM%KFDIA,&
  &  KLON=KDIM%KLON, KLEVS=KDIM%KLEVS, KTILES=KDIM%KTILES,&
  &  KLEVSN=KDIM%KLEVSN, KLEVO=KDIM%KLEVO ,KLEVI=KDIM%KLEVI, KSTART=NSTART, KSTEP=NSTEP,&!KPP
  &  KDHVTSS=KDIM%KDHVTSS, KDHFTSS=KDIM%KDHFTSS,&
  &  KDHVTTS=KDIM%KDHVTTS, KDHFTTS=KDIM%KDHFTTS,&
  &  KDHVTIS=KDIM%KDHVTIS, KDHFTIS=KDIM%KDHFTIS,&
  &  KDHVSSS=KDIM%KDHVSSS, KDHFSSS=KDIM%KDHFSSS,&
  &  KDHVIIS=KDIM%KDHVIIS, KDHFIIS=KDIM%KDHFIIS,&
  &  KDHVWLS=KDIM%KDHVWLS, KDHFWLS=KDIM%KDHFWLS,&
  &  KDHVBIOS=IKDHVBIOS, KDHFBIOS=IKDHFBIOS,&!CTESSEL
  &  KDHVVEGS=IKDHVVEGS, KDHFVEGS=IKDHFVEGS,&!CTESSEL
  &  KTVL=PSURF%ITVL ,KTVH=PSURF%ITVH, KVEG=IVEG,KSOTY=PSURF%ISOTY,&
  &  PTSPHY=TSPHY,PSDOR=PSURF%PHSTD, PFRTI=SURFL%ZFRTI,&
  &  PSST=PSURF%PSD_VF(:,YSD_VF%YSST%MP), PUSTRTI=PSURF%PUSTRTI, PVSTRTI=PSURF%PVSTRTI,&
  &  PAHFSTI=PSURF%PAHFSTI, PEVAPTI=PSURF%PEVAPTI, PSSRFLTI=SURFL%ZFRSOTI,PSLRFLTI=SURFL%ZAHFTRTI,&
  &  PLAT=PAUX%PGELAT,PANFMVT=SURFL%ZANFMVT, PANDAYVT=SURFL%ZANDAYVT, PMU0=PAUX%PMU0,&!CTESSEL    
  &  PCVT=ZCVT, PLAIVT=ZLAIVT, PLAIL=PSURF%PLAIL, PLAIH=PSURF%PLAIH,&!CTESSEL
  &  PLAILC=PSURF%PSD_VF(:,YSD_VF%YLAIL%MP), PLAIHC=PSURF%PSD_VF(:,YSD_VF%YLAIH%MP),&
  &  LDLAND=LLKEYS%LLLAND, LDSICE=LLKEYS%LLSICE, LDSI=LESICE, LDNH=LLKEYS%LLNH, LDOCN_KPP=LLKEYS%LLOCN_KPP,&
  &  PSNM1M=SURFL%ZSNM1M ,PTSNM1M=PSURF%PSP_SG(:,:,YSP_SG%YT%MP9), PASNM1M=PSURF%PSP_SG(:,1,YSP_SG%YA%MP9), &
  &  PRSNM1M=PSURF%PSP_SG(:,:,YSP_SG%YR%MP9), PWSNM1M=PSURF%PSP_SG(:,:,YSP_SG%YW%MP9),PAPRS=PAUX%PAPRS(:,KDIM%KLEV), &
  &  PTSKM1M=PSURF%PSP_RR(:,YSP_RR%YT%MP9),&
  &  PTSAM1M=PSURF%PSP_SB(:,:,YSP_SB%YT%MP9), PTIAM1M=PSURF%PSP_SB(:,:,YSP_SB%YTL%MP9),&
  &  PWLM1M=SURFL%ZWLM1M, PWSAM1M=PSURF%PSP_SB(:,:,YSP_SB%YQ%MP9),&
  &  PTLICEM1M=PSURF%PSP_SL(:,YSP_SL%YLICT%MP9),PTLMNWM1M=PSURF%PSP_SL(:,YSP_SL%YLTLT%MP9),&!LAKE
  &  PTLWMLM1M=PSURF%PSP_SL(:,YSP_SL%YLMLT%MP9),PTLBOTM1M=PSURF%PSP_SL(:,YSP_SL%YLBLT%MP9),&!LAKE
  &  PTLSFM1M=PSURF%PSP_SL(:,YSP_SL%YLSHF%MP9),&!LAKE
  &  PHLICEM1M=PSURF%PSP_SL(:,YSP_SL%YLICD%MP9),PHLMLM1M=PSURF%PSP_SL(:,YSP_SL%YLMLD%MP9),&!LAKE
  &  PGEMU=PAUX%PGEMU,&
  &  PLDEPTH=PSURF%PSD_VF(:,YSD_VF%YDL%MP),LDLAKE=LLKEYS%LLLAKE, PCLAKE=PSURF%PSD_VF(:,YSD_VF%YCLK%MP),&!LAKE
  &  PRSFC=FLUX%PFPLCL(:,KDIM%KLEV),PRSFL=FLUX%PFPLSL(:,KDIM%KLEV),&
  &  PSLRFL=FLUX%PFRTH(:,KDIM%KLEV), PSSFC=FLUX%PFPLCN(:,KDIM%KLEV), PSSFL=FLUX%PFPLSN(:,KDIM%KLEV),&
  &  PCVL=PSURF%PCVL, PCVH=PSURF%PCVH, PCUR=PSURF%PCUR, PWLMX=SURFL%ZWLMX , PEVAPSNW=SURFL%ZEVAPSNW,&
  &  PUSRF=STATE%U(:,KDIM%KLEV),PVSRF=STATE%V(:,KDIM%KLEV),PTSRF=STATE%T(:,KDIM%KLEV),&
  &  PZO=PSURF%PSD_V3(:,:,YSD_V3%YZO%MP),PHO=PSURF%PSD_V3(:,:,YSD_V3%YHO%MP),&
  &  PHO_INV=PSURF%PSD_V3(:,:,YSD_V3%YHO_INV%MP),PDO=PSURF%PSD_V3(:,:,YSD_V3%YDO%MP),&
  &  POCDEPTH=PSURF%PSD_V2(:,YSD_V2%YOCDEP%MP),&
  &  PUO0=PSURF%PSP_OM(:,:,YSP_OM%YUO%MP9),PVO0=PSURF%PSP_OM(:,:,YSP_OM%YVO%MP9),&
  &  PUOC=PSURF%PSD_V3(:,:,YSD_V3%YUOC%MP),PVOC=PSURF%PSD_V3(:,:,YSD_V3%YVOC%MP),&
  &  PTO0=PSURF%PSP_OM(:,:,YSP_OM%YTO%MP9),&
  &  PSO0=PSURF%PSP_OM(:,:,YSP_OM%YSO%MP9),PADVT=PSURF%PSD_V3(:,:,YSD_V3%YADVT%MP),&
  &  PADVS=PSURF%PSD_V3(:,:,YSD_V3%YADVS%MP),PTRI0=PSURF%PSD_V3(:,:,YSD_V3%YTRI0%MP),&
  &  PTRI1=PSURF%PSD_V3(:,:,YSD_V3%YTRI1%MP),&
  &  PSWDK_SAVE=PSURF%PSD_V3(:,:,YSD_V3%YSWDK%MP),PUSTRC=PSURF%PSD_V2(:,YSD_V2%YUSTRC%MP),&
  &  PVSTRC=PSURF%PSD_V2(:,YSD_V2%YVSTRC%MP),&
  &  PUSTOKES=PSURF%PSD_WS(:,YSD_WS%YUSTOKES%MP),PVSTOKES=PSURF%PSD_WS(:,YSD_WS%YVSTOKES%MP),&
  &  PTAUOCX=PSURF%PSD_WS(:,YSD_WS%YTAUOCX%MP), PTAUOCY=PSURF%PSD_WS(:,YSD_WS%YTAUOCY%MP),&
  &  PPHIOC=PSURF%PSD_WS(:,YSD_WS%YPHIOC%MP),&
  &  PWSEMEAN=PSURF%PSD_WS(:,YSD_WS%YWSEMEAN%MP), PWSFMEAN=PSURF%PSD_WS(:,YSD_WS%YWSFMEAN%MP),&
   !-DIAGNOSTICS OUTPUT
  & PTSDFL=FLUX%PFTG12, PROFD=FLUX%PFWROD, PROFS=FLUX%PFWRO1,&
  & PWFSD=FLUX%PFWG12, PMELT=FLUX%PFWMLT, PFWEV=FLUX%PFWEV , PENES=FLUX%PENES,&
  & PDIFM=PSURF%PSD_V3(:,:,YSD_V3%YDIFM%MP), PDIFT=PSURF%PSD_V3(:,:,YSD_V3%YDIFT%MP), &
  & PDIFS=PSURF%PSD_V3(:,:,YSD_V3%YDIFS%MP),POTKE=PSURF%PSD_V3(:,:,YSD_V3%YOTKE%MP),& 
  & PRESPBSTR=ZRESPBSTR,PRESPBSTR2=ZRESPBSTR2,PBIOMASS_LAST=ZBIOMASS_LAST,& !CTESSEL
  & PBIOMASSTR_LAST=ZBIOMASSTR_LAST,PBIOMASSTR2_LAST=ZBIOMASSTR2_LAST, &    !CTESSEL
  & PBLOSSVT=ZBLOSSVT, PBGAINVT=ZBGAINVT,&                                  !CTESSEL
  & PLAI=ZLAI, PBIOM=ZBIOM, PBLOSS=ZBLOSS,PBGAIN=ZBGAIN,&                   !CTESSEL
  & PBIOMSTR=ZBIOMSTR,PBIOMSTR2=ZBIOMSTR2,&                                 !CTESSEL                        
   !-TENDENCIES OUTPUT
  &  PSNE1=PSURF%PSNSE1, PTSNE1=PSURF%PTSNE1, PASNE1=PSURF%PASNE1(:,1),&
  &  PRSNE1=PSURF%PRSNE1, PWSNE1=PSURF%PWSNE1, PTSAE1=PSURF%PTSAE1, PTIAE1=PSURF%PTIAE1,&
  & PWLE1=PSURF%PWLE1,PWSAE1=PSURF%PWSAE1,&
  & PTLICEE1=PSURF%PTLICEE1,PTLMNWE1=PSURF%PTLMNWE1,PTLWMLE1=PSURF%PTLWMLE1,& !LAKE
  & PTLBOTE1=PSURF%PTLBOTE1,PTLSFE1=PSURF%PTLSFE1,&                           !LAKE
  & PHLICEE1=PSURF%PHLICEE1,PHLMLE1=PSURF%PHLMLE1,&                           !LAKE
  & PUOE1=PSURF%PUOE1,PVOE1=PSURF%PVOE1,PTOE1=PSURF%PTOE1,PSOE1=PSURF%PSOE1,&     
  & PLAIE1=ZLAIE1,PBSTRE1=ZBSTRE1,PBSTR2E1=ZBSTR2E1, &                      !CTESSEL         
   !-DDH OUTPUTS
  & PDHTSS=PDDHS%PDHTSS, PDHTTS=PDDHS%PDHTTS, PDHTIS=PDDHS%PDHTIS,&
  & PDHSSS=PDDHS%PDHSSS, PDHIIS=PDDHS%PDHIIS, PDHWLS=PDDHS%PDHWLS,&
  & PDHBIOS=ZDHBIOS,PDHVEGS=SURFL%ZDHVEGS)                                        !CTESSEL 


!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SURFTSTP_LAYER',1,ZHOOK_HANDLE)
END SUBROUTINE SURFTSTP_LAYER
