! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE UPDATE_FIELDS (YDPHY2,KONFIG, KIDIA, KFDIA, KLON, KLEV, &
! optional input
                      & PI1, PI2, PI3, PI4, PI5, PI6, PI7, PI8, PI9, PI10, &
                      & PI11,PI12,PI13, &
                      & PS1, PS2, PS3, PS4, PS5, PS6, PS7, PS8, PS9, PS10, &
                      & PS11,PS12,PS13, &
                      & PA1, PA2, PA3, PA4, PA5, PA6, PA7, PA8, PA9, PA10, &
                      & PA11,PA12,PA13, &
                      & LDV1, LDV2, LDV3, LDV4, LDV5, LDV6, LDV7, LDV8, LDV9, LDV10, &
                      & LDV11,LDV12,LDV13, &
                      & PTA1, PTA2, PTA3, PTA4, PTA5, PTA6, PTA7, PTA8, PTA9, PTA10, &
                      & PTA11,PTA12,PTA13, &
                      & PTS1, PTS2, PTS3, PTS4, PTS5, PTS6, PTS7, PTS8, PTS9, PTS10, &
                      & PTS11,PTS12,PTS13, &
! output
                      & PO1, PO2, PO3, PO4, PO5, PO6, PO7, PO8, PO9, PO10, &
                      & PO11,PO12,PO13)

!===============================================================================
!**** *UPDATE_FIELDS* -  Routine for transfer or update of fields used in physics
! 
!     PIxx  - input field
!     PSxx  - field to subtract from input field
!     PAxx  - field to add to input field
!     PTAxx - positive tendency to update input field (if KONFIG=1)
!     PTSxx - negative tendency to update input field (if KONFIG=1)
!     LDVxx - key activating the computation for variable xx
!     POxx  - output field
!
!
!     F. Vana (ECMWF)
!
!     MODIFICATIONS.
!     -------------
!     Original 18-May-2012
!     F. Vana  25-Jul-2012  optimized and secured for NaN initialization arrays
!     F. Vana  14-Sep-2012  better handling of incrementing arrays
!
! ---------------------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM     ,JPRB
USE YOMHOOK  , ONLY : LHOOK,   DR_HOOK, JPHOOK

USE YOMPHY2  , ONLY : TPHY2

! ---------------------------------------------------------------------------------

IMPLICIT NONE

TYPE(TPHY2)       ,INTENT(INOUT) :: YDPHY2
INTEGER(KIND=JPIM),INTENT(IN)    :: KONFIG
INTEGER(KIND=JPIM),INTENT(IN)    :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN)    :: KLON
INTEGER(KIND=JPIM),INTENT(IN)    :: KLEV
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PI13(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PS13(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN) :: PA13(KLON,KLEV)
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV1
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV2
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV3
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV4
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV5
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV6
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV7
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV8
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV9
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV10
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV11
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV12
LOGICAL, OPTIONAL, INTENT(IN)   :: LDV13
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTA13(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL ,INTENT(IN)  :: PTS13(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO1(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO2(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO3(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO4(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO5(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO6(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO7(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO8(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO9(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO10(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO11(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO12(KLON,KLEV)
REAL(KIND=JPRB),OPTIONAL   ,INTENT(INOUT)   :: PO13(KLON,KLEV)

! ---------------------------------------------------------------------------------

LOGICAL :: LLTRG1, LLTRG2, LLTRG3, LLTRG4, LLTRG5, LLTRG6, &
  &   LLTRG7, LLTRG8, LLTRG9, LLTRG10, LLTRG11, LLTRG12, LLTRG13 

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

! ---------------------------------------------------------------------------------

#include "abor1.intfb.h"

! ---------------------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('UPDATE_FIELDS',0,ZHOOK_HANDLE)
ASSOCIATE(TSPHY=>YDPHY2%TSPHY)
!     ------------------------------------------------------------------


! Initial check activating the computation

LLTRG1= PRESENT(PO1)
IF (LLTRG1.AND.PRESENT(LDV1)) LLTRG1=LDV1
LLTRG2= PRESENT(PO2)
IF (LLTRG2.AND.PRESENT(LDV2)) LLTRG2=LDV2
LLTRG3= PRESENT(PO3)
IF (LLTRG3.AND.PRESENT(LDV3)) LLTRG3=LDV3
LLTRG4= PRESENT(PO4)
IF (LLTRG4.AND.PRESENT(LDV4)) LLTRG4=LDV4
LLTRG5= PRESENT(PO5)
IF (LLTRG5.AND.PRESENT(LDV5)) LLTRG5=LDV5
LLTRG6= PRESENT(PO6)
IF (LLTRG6.AND.PRESENT(LDV6)) LLTRG6=LDV6
LLTRG7= PRESENT(PO7)
IF (LLTRG7.AND.PRESENT(LDV7)) LLTRG7=LDV7
LLTRG8= PRESENT(PO8)
IF (LLTRG8.AND.PRESENT(LDV8)) LLTRG8=LDV8
LLTRG9= PRESENT(PO9)
IF (LLTRG9.AND.PRESENT(LDV9)) LLTRG9=LDV9
LLTRG10= PRESENT(PO10)
IF (LLTRG10.AND.PRESENT(LDV10)) LLTRG10=LDV10
LLTRG11= PRESENT(PO11)
IF (LLTRG11.AND.PRESENT(LDV11)) LLTRG11=LDV11
LLTRG12= PRESENT(PO12)
IF (LLTRG12.AND.PRESENT(LDV12)) LLTRG12=LDV12
LLTRG13= PRESENT(PO13)
IF (LLTRG13.AND.PRESENT(LDV13)) LLTRG13=LDV13


! ---------------------------------------------------------------------------------

SELECT CASE (KONFIG)

! ---------------------------------------------------------------------------------

CASE (1)
  
  ! Do regular update by a tendency

  IF (LLTRG1) THEN
    IF (PRESENT(PI1)) PO1(KIDIA:KFDIA,1:KLEV)=PI1(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS1)) THEN
      PO1(KIDIA:KFDIA,1:KLEV)=PO1(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA1(KIDIA:KFDIA,1:KLEV)-PTS1(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO1(KIDIA:KFDIA,1:KLEV)=PO1(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA1(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG2) THEN
    IF (PRESENT(PI2)) PO2(KIDIA:KFDIA,1:KLEV)=PI2(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS2)) THEN
      PO2(KIDIA:KFDIA,1:KLEV)=PO2(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA2(KIDIA:KFDIA,1:KLEV)-PTS2(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO2(KIDIA:KFDIA,1:KLEV)=PO2(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA2(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG3) THEN
    IF (PRESENT(PI3)) PO3(KIDIA:KFDIA,1:KLEV)=PI3(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS3)) THEN
      PO3(KIDIA:KFDIA,1:KLEV)=PO3(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA3(KIDIA:KFDIA,1:KLEV)-PTS3(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO3(KIDIA:KFDIA,1:KLEV)=PO3(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA3(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG4) THEN
    IF (PRESENT(PI4)) PO4(KIDIA:KFDIA,1:KLEV)=PI4(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS4)) THEN
      PO4(KIDIA:KFDIA,1:KLEV)=PO4(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA4(KIDIA:KFDIA,1:KLEV)-PTS4(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO4(KIDIA:KFDIA,1:KLEV)=PO4(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA4(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG5) THEN
    IF (PRESENT(PI5)) PO5(KIDIA:KFDIA,1:KLEV)=PI5(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS5)) THEN
      PO5(KIDIA:KFDIA,1:KLEV)=PO5(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA5(KIDIA:KFDIA,1:KLEV)-PTS5(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO5(KIDIA:KFDIA,1:KLEV)=PO5(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA5(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG6) THEN
    IF (PRESENT(PI6)) PO6(KIDIA:KFDIA,1:KLEV)=PI6(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS6)) THEN
      PO6(KIDIA:KFDIA,1:KLEV)=PO6(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA6(KIDIA:KFDIA,1:KLEV)-PTS6(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO6(KIDIA:KFDIA,1:KLEV)=PO6(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA6(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG7) THEN
    IF (PRESENT(PI7)) PO7(KIDIA:KFDIA,1:KLEV)=PI7(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS7)) THEN
      PO7(KIDIA:KFDIA,1:KLEV)=PO7(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA7(KIDIA:KFDIA,1:KLEV)-PTS7(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO7(KIDIA:KFDIA,1:KLEV)=PO7(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA7(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG8) THEN
    IF (PRESENT(PI8)) PO8(KIDIA:KFDIA,1:KLEV)=PI8(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS8)) THEN
      PO8(KIDIA:KFDIA,1:KLEV)=PO8(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA8(KIDIA:KFDIA,1:KLEV)-PTS8(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO8(KIDIA:KFDIA,1:KLEV)=PO8(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA8(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG9) THEN
    IF (PRESENT(PI9)) PO9(KIDIA:KFDIA,1:KLEV)=PI9(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS9)) THEN
      PO9(KIDIA:KFDIA,1:KLEV)=PO9(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA9(KIDIA:KFDIA,1:KLEV)-PTS9(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO9(KIDIA:KFDIA,1:KLEV)=PO9(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA9(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG10) THEN
    IF (PRESENT(PI10)) PO10(KIDIA:KFDIA,1:KLEV)=PI10(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS10)) THEN
      PO10(KIDIA:KFDIA,1:KLEV)=PO10(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA10(KIDIA:KFDIA,1:KLEV)-PTS10(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO10(KIDIA:KFDIA,1:KLEV)=PO10(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA10(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG11) THEN
    IF (PRESENT(PI11)) PO11(KIDIA:KFDIA,1:KLEV)=PI11(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS11)) THEN
      PO11(KIDIA:KFDIA,1:KLEV)=PO11(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA11(KIDIA:KFDIA,1:KLEV)-PTS11(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO11(KIDIA:KFDIA,1:KLEV)=PO11(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA11(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG12) THEN
    IF (PRESENT(PI12)) PO12(KIDIA:KFDIA,1:KLEV)=PI12(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS12)) THEN
      PO12(KIDIA:KFDIA,1:KLEV)=PO12(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA12(KIDIA:KFDIA,1:KLEV)-PTS12(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO12(KIDIA:KFDIA,1:KLEV)=PO12(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA12(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF
  IF (LLTRG13) THEN
    IF (PRESENT(PI13)) PO13(KIDIA:KFDIA,1:KLEV)=PI13(KIDIA:KFDIA,1:KLEV)
    IF (PRESENT(PTS13)) THEN
      PO13(KIDIA:KFDIA,1:KLEV)=PO13(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*(PTA13(KIDIA:KFDIA,1:KLEV)-PTS13(KIDIA:KFDIA,1:KLEV))
    ELSE
      PO13(KIDIA:KFDIA,1:KLEV)=PO13(KIDIA:KFDIA,1:KLEV) &
       &  + TSPHY*PTA13(KIDIA:KFDIA,1:KLEV)
    ENDIF
  ENDIF

! -----------------------------------------------------------------------------

CASE (2)

  ! Simple copy of arrays

  IF (LLTRG1.AND.PRESENT(PI1)) PO1(KIDIA:KFDIA,1:KLEV)=PI1(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG2.AND.PRESENT(PI2)) PO2(KIDIA:KFDIA,1:KLEV)=PI2(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG3.AND.PRESENT(PI3)) PO3(KIDIA:KFDIA,1:KLEV)=PI3(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG4.AND.PRESENT(PI4)) PO4(KIDIA:KFDIA,1:KLEV)=PI4(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG5.AND.PRESENT(PI5)) PO5(KIDIA:KFDIA,1:KLEV)=PI5(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG6.AND.PRESENT(PI6)) PO6(KIDIA:KFDIA,1:KLEV)=PI6(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG7.AND.PRESENT(PI7)) PO7(KIDIA:KFDIA,1:KLEV)=PI7(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG8.AND.PRESENT(PI8)) PO8(KIDIA:KFDIA,1:KLEV)=PI8(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG9.AND.PRESENT(PI9)) PO9(KIDIA:KFDIA,1:KLEV)=PI9(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG10.AND.PRESENT(PI10)) PO10(KIDIA:KFDIA,1:KLEV)=PI10(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG11.AND.PRESENT(PI11)) PO11(KIDIA:KFDIA,1:KLEV)=PI11(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG12.AND.PRESENT(PI12)) PO12(KIDIA:KFDIA,1:KLEV)=PI12(KIDIA:KFDIA,1:KLEV)
  IF (LLTRG13.AND.PRESENT(PI13)) PO13(KIDIA:KFDIA,1:KLEV)=PI13(KIDIA:KFDIA,1:KLEV)
   

! -----------------------------------------------------------------------------
CASE DEFAULT
  CALL ABOR1('UPDATE_FIELDS: Unknown configuration KONFIG')
END SELECT

! -----------------------------------------------------------------------------

! Add or subtract fields when required

IF (PRESENT(PA1).AND.LLTRG1)  PO1(KIDIA:KFDIA,1:KLEV)= PO1(KIDIA:KFDIA,1:KLEV) +PA1(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA2).AND.LLTRG2)  PO2(KIDIA:KFDIA,1:KLEV)= PO2(KIDIA:KFDIA,1:KLEV) +PA2(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA3).AND.LLTRG3)  PO3(KIDIA:KFDIA,1:KLEV)= PO3(KIDIA:KFDIA,1:KLEV) +PA3(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA4).AND.LLTRG4)  PO4(KIDIA:KFDIA,1:KLEV)= PO4(KIDIA:KFDIA,1:KLEV) +PA4(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA5).AND.LLTRG5)  PO5(KIDIA:KFDIA,1:KLEV)= PO5(KIDIA:KFDIA,1:KLEV) +PA5(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA6).AND.LLTRG6)  PO6(KIDIA:KFDIA,1:KLEV)= PO6(KIDIA:KFDIA,1:KLEV) +PA6(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA7).AND.LLTRG7)  PO7(KIDIA:KFDIA,1:KLEV)= PO7(KIDIA:KFDIA,1:KLEV) +PA7(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA8).AND.LLTRG8)  PO8(KIDIA:KFDIA,1:KLEV)= PO8(KIDIA:KFDIA,1:KLEV) +PA8(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA9).AND.LLTRG9)  PO9(KIDIA:KFDIA,1:KLEV)= PO9(KIDIA:KFDIA,1:KLEV) +PA9(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA10).AND.LLTRG10) PO10(KIDIA:KFDIA,1:KLEV)=PO10(KIDIA:KFDIA,1:KLEV)+PA10(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA11).AND.LLTRG11) PO11(KIDIA:KFDIA,1:KLEV)=PO11(KIDIA:KFDIA,1:KLEV)+PA11(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA12).AND.LLTRG12) PO12(KIDIA:KFDIA,1:KLEV)=PO12(KIDIA:KFDIA,1:KLEV)+PA12(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PA13).AND.LLTRG13) PO13(KIDIA:KFDIA,1:KLEV)=PO13(KIDIA:KFDIA,1:KLEV)+PA13(KIDIA:KFDIA,1:KLEV)

IF (PRESENT(PS1).AND.LLTRG1)  PO1(KIDIA:KFDIA,1:KLEV)= PO1(KIDIA:KFDIA,1:KLEV) -PS1(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS2).AND.LLTRG2)  PO2(KIDIA:KFDIA,1:KLEV)= PO2(KIDIA:KFDIA,1:KLEV) -PS2(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS3).AND.LLTRG3)  PO3(KIDIA:KFDIA,1:KLEV)= PO3(KIDIA:KFDIA,1:KLEV) -PS3(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS4).AND.LLTRG4)  PO4(KIDIA:KFDIA,1:KLEV)= PO4(KIDIA:KFDIA,1:KLEV) -PS4(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS5).AND.LLTRG5)  PO5(KIDIA:KFDIA,1:KLEV)= PO5(KIDIA:KFDIA,1:KLEV) -PS5(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS6).AND.LLTRG6)  PO6(KIDIA:KFDIA,1:KLEV)= PO6(KIDIA:KFDIA,1:KLEV) -PS6(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS7).AND.LLTRG7)  PO7(KIDIA:KFDIA,1:KLEV)= PO7(KIDIA:KFDIA,1:KLEV) -PS7(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS8).AND.LLTRG8)  PO8(KIDIA:KFDIA,1:KLEV)= PO8(KIDIA:KFDIA,1:KLEV) -PS8(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS9).AND.LLTRG9)  PO9(KIDIA:KFDIA,1:KLEV)= PO9(KIDIA:KFDIA,1:KLEV) -PS9(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS10).AND.LLTRG10) PO10(KIDIA:KFDIA,1:KLEV)=PO10(KIDIA:KFDIA,1:KLEV)-PS10(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS11).AND.LLTRG11) PO11(KIDIA:KFDIA,1:KLEV)=PO11(KIDIA:KFDIA,1:KLEV)-PS11(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS12).AND.LLTRG12) PO12(KIDIA:KFDIA,1:KLEV)=PO12(KIDIA:KFDIA,1:KLEV)-PS12(KIDIA:KFDIA,1:KLEV)
IF (PRESENT(PS13).AND.LLTRG13) PO13(KIDIA:KFDIA,1:KLEV)=PO13(KIDIA:KFDIA,1:KLEV)-PS13(KIDIA:KFDIA,1:KLEV)

!     ------------------------------------------------------------------
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('UPDATE_FIELDS',1,ZHOOK_HANDLE)
END SUBROUTINE UPDATE_FIELDS
