! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE WVCOUPLE(YDGEOMETRY,YDSURF,YDEPHY,YDEWCOU,PTSTEP,KSTOP,KSTPW,LDSTOP,LDWRRE)
#ifdef WITH_WAVE

!**** *WCOUPLE* - CALLS THE WAVE MODEL

!     PURPOSE.
!     --------

!           THIS ROUTINE CALLS THE WAVE MODEL

!     INTERFACE.
!     ----------

!           *CALL* *WVCOUPLE(...)*.

!           *WVCOUPLE* IS CALLED FROM *CNT4*.

!           *WVCOUPLE* HAS FOUR INPUT PARAMETERS.

!          PTSTEP*  - LENGTH OF THE IFS TIMESTEP IN SECONDS.
!          KSTOP*  - NUMBER OF TIME STEPS NEEDED TO REACH THE END OF THE RUN.
!          KSTPW*  - FREQUENCY OF CALL TO THE WAVE MODEL.
!          LDSTOP* - SET .TRUE. IF STOP SIGNAL RECEIVED.
!          LDWRRE* - SET .TRUE. IF RESTART FILE SIGNAL RECEIVED.

!    METHOD.
!     -------

!           FIRST THE CHARNOCK FIELD IS OBTAINED IN A IRREGULAR LAT/LON
!     GRID, WITH THE LATITUDE POINTS BETWEEN *PPSOUTW AND *PPNORTW. THE
!     ARRAY IS THEN EXTENDED TO COVER THE WHOLE GLOBE AND A CONVERSION
!     TO GAUSSIAN GRID IS MADE. THE FINAL CHARNOCK FIELD IS KEPT
!     CONSTANT UNTIL THE NEXT TIME THE POSTPROCESSING IS CALLED.

!        BRIEFLY, THE LOWEST MODEL LEVEL WINDS AS GLOBAL ARRAYS HAVE
!      BEEN CREATED IN *CALLPAR*
!        THE WAVEMODEL IS CALLED IN THIS ROUTINE, AND THIS WINDS ARE
!     USED AS FORCING CONDITIONS FOR OBTAINING THE WAVE STATE, FROM
!     WHICH THE LONGWAVE CONTRIBUTION TO THE STRESSES IS DERIVED IN THE
!     FORM OF A MODIFIED CHARNOCK CONSTANT AND PASSED TO THE ATMOSPHERIC
!     MODEL AS AN ARRAY IN THE WAVEMODEL GRID (SCANNED SOUTH TO NORTH)
!                   *ZBETAWN*      (NLONW,NLATW).
!     AN INTERPOLATION IS PERFORMED AND THE CORRESPONDING VALUES IN THE
!     ATMOSPHERIC GRID ARE OBTAINED AS AN ATM GRID ARRAY
!     UNTIL THE NEXT TIME THE WAVEMODEL IS CALLED, *VDIFF*
!     WILL CALCULATE THE ROUGHNESS LENGTH OVER THE OCEANS BY USING
!     THIS MODIFIED CHARNOCK CONSTANT IN THE CHARNOCK EQUATION AND
!     *VDFUPDZ0* WILL USE THIS ROUGHNESS LENGTH.

!     EXTERNALS.
!     ----------

!          *WVCOUPLE* CALLS:

!             *WAVEMDL*  - TO RUN THE WAVE MODEL PRODUCING THE STRESSES.
!             *WVWG2RG*  - TO CONVERT FIELDS COMING FROM THE WAVE MODEL
!                          FROM REGULAR GRID TO GAUSSIAN GRID.

!     REFERENCES.
!     -----------

!           NONE.

!  ADD EXTRA FIELDS CODE TO COMMON BLOCK, CHANGE CALLPAR AND THIS
!  ROUTINE

!  3 FLAVOURS FOR ZBETA, LABELLED ZBETAXX, WHERE XX STANDS FOR

!          WN  - NON-EXTENDED WAVE MODEL GRID
!          WX  - POLE-EXTENDED WAVE MODEL GRID
!          RG  - ATM REDUCED GAUSSIAN GRID

!     AUTHOR.
!     -------
!      P. VITERBO               E.C.M.W.F.      06/09/88

!     MODIFICATIONS.
!     --------------
!      S. Abdalla (ECMWF) 27/11/01: Generalized ATM-WAVE interface
!      J. Bidlot  (ECMWF) 20/11/03: limit interpolation to local grid points
!      G. Mozdzynski      14/01/05: Optimise coupling communications
!      P. Bechtold        26/03/12: Add RPLRADI RPLRG for small planet
!      J. Hague           16/10/12: Parallelised loop
!      J. Hawkes          27/11/17: Extract initialization to separate routine
!      O. Marsden         16/02/18: Restructured first call handling
!      I. Hadade          24/05/21: Removed Z_WVFLDWN in order to prevent expensive
!                                   memory copy into Z_WVFLDWX
!     ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1  , ONLY : JPIM, JPRB
USE YOMHOOK   , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCT3    , ONLY : NSTEP
USE YOMLUN    , ONLY : NULOUT
USE YOMVAR    , ONLY : LREPRO4DVAR
USE YOEWCOU   , ONLY : TEWCOU
USE YOEPHY    , ONLY : TEPHY
USE YOMDYNCORE, ONLY : RPLRG, RPLRADI
USE YOMVAR    , ONLY : NDATE_TIME_WINDOW_END
USE YOMIO_SERV, ONLY : IO_SERV_C001
USE YOWCOUP   , ONLY : IFSNUPTRA, IFSMUPTRA, IFSCONTEXT, IFSTOWAM_HANDLER
USE ALGORITHM_STATE_MOD, ONLY : GET_MUPTRA, GET_NUPTRA, GET_ALGOR_TYPE

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TSURF)       ,INTENT(INOUT) :: YDSURF
TYPE(TEPHY)       ,INTENT(INOUT) :: YDEPHY
TYPE(TEWCOU)      ,INTENT(INOUT) :: YDEWCOU
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTSTEP
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTOP
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTPW
LOGICAL           ,INTENT(INOUT) :: LDSTOP
LOGICAL           ,INTENT(INOUT) :: LDWRRE
!     ------------------------------------------------------------------
INTEGER(KIND=JPIM) :: I_NWVFIELDS ! NUMBER OF FIELDS RETURNED FROM WAM
!                                   set with IVWV in SU_SURF_FLDS
INTEGER(KIND=JPIM) :: I_NFIELDS   ! NUMBER OF FIELDS PASSED TO WAM
!                                   set with IVWW in SU_SURF_FLDS
INTEGER(KIND=JPIM) :: I_NC, I_NR, JSN
INTEGER(KIND=JPIM) :: IGPTOTG,IGPTOT,IPROMA,IDGLG
INTEGER(KIND=JPIM) :: I_WVFLDRG  ! FIRST DIMENSION OF Z_WVFLDRG
REAL(KIND=JPRB), ALLOCATABLE :: Z_FIELDS(:,:)

REAL(KIND=JPRB) :: ZRCHAR, ZRNU, ZRNUM
REAL(KIND=JPRB), ALLOCATABLE :: ZDELLO(:)
REAL(KIND=JPRB), ALLOCATABLE :: ZDXNS(:)
REAL(KIND=JPRB), ALLOCATABLE :: Z_WVFLDRG(:,:)
REAL(KIND=JPRB), ALLOCATABLE, SAVE :: Z_WVFLDWX(:,:,:)

INTEGER(KIND=JPIM) :: JLA, JLO, IFLD
INTEGER(KIND=JPIM) :: IWVCL, ILEN, JLAW, JLOW

!!LOGICAL :: LLFRST, LLRESTARTED
LOGICAL :: LLRESTARTED
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

LOGICAL :: LLFREE_WAM_MEMORY
INTEGER(KIND=JPIM) :: INADV

!     ------------------------------------------------------------------

#include "surf_inq.h"




#include "wavemdl.intfb.h"
#include "wvrg2xf.intfb.h"
#include "wvwg2rg.intfb.h"
#include "wvxf2gb.intfb.h"
#include "wvcouple_init_early.intfb.h"
#include "wvalloc.intfb.h"
#include "wvdealloc.intfb.h"
#include "ifstowam.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('WVCOUPLE',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP)
ASSOCIATE(NDGLG=>YDDIM%NDGLG, NPROMA=>YDDIM%NPROMA, &
 & YSURF=>YDEPHY%YSURF, &
 & NATMFLX=>YDEWCOU%NATMFLX, &
 & CBEGDAT=>YDEWCOU%CBEGDAT, LWCOU=>YDEWCOU%LWCOU, LWCOU2W=>YDEWCOU%LWCOU2W, &
 & LWCOUNORMS=>YDEWCOU%LWCOUNORMS, LWCUR=>YDEWCOU%LWCUR, LWFLUX=>YDEWCOU%LWFLUX, &
 & LWFRSTIME=>YDEWCOU%LWFRSTIME, LWSTOKES=>YDEWCOU%LWSTOKES, &
 & LWINIT=>YDEWCOU%LWINIT, &
 & LWVIN_MASK_NOT_SET=>YDEWCOU%LWVIN_MASK_NOT_SET, &
 & LWVIN_UNINITIALISED=>YDEWCOU%LWVIN_UNINITIALISED, &
 & LWVOUT_MASK_NOT_SET=>YDEWCOU%LWVOUT_MASK_NOT_SET, &
 & NADV_WAVE=>YDEWCOU%NADV_WAVE, &
 & NGRIB_HANDLE_FOR_WAM=>YDEWCOU%NGRIB_HANDLE_FOR_WAM, NLAT1W=>YDEWCOU%NLAT1W, &
 & NGAUSSW=>YDEWCOU%NGAUSSW, &
 & NLATW=>YDEWCOU%NLATW, NLON1W=>YDEWCOU%NLON1W, NLONW=>YDEWCOU%NLONW, &
 & NWV_W2IWGHT=>YDEWCOU%NWV_W2IWGHT, &
 & RDEGREW=>YDEWCOU%RDEGREW, RMISSW=>YDEWCOU%RMISSW, RNORTW=>YDEWCOU%RNORTW, &
 & RSOUTW=>YDEWCOU%RSOUTW, &
 & NGPTOT=>YDGEM%NGPTOT, NGPTOTG=>YDGEM%NGPTOTG, &
 & YSD_WSD=>YDSURF%YSD_WSD, YSD_WWD=>YDSURF%YSD_WWD)

!     ------------------------------------------------------------------

IGPTOTG=NGPTOTG
IGPTOT=NGPTOT
IPROMA=NPROMA
IDGLG=NDGLG

LLFREE_WAM_MEMORY=.FALSE.

IF (NSTEP > 0 .AND. LWCOU) THEN
  WRITE(NULOUT,*) '------------------------------------',&
   & '----------------------------------- '
  IF (LWCOU2W) THEN
    WRITE(NULOUT,*) 'THE WAVE MODEL IS CALLED FOR TWO-WAY INTERACTION BETWEEN WIND AND WAVES '
  ELSE
    WRITE(NULOUT,*) 'THE WAVE MODEL IS CALLED FOR ONE-WAY INTERACTION BETWEEN WIND AND WAVES '
  ENDIF
  WRITE(NULOUT,*) ' '
ENDIF

IF (NSTEP == 0 .OR. .NOT.LWCOU) THEN
  IF (LHOOK) CALL DR_HOOK('WVCOUPLE',1,ZHOOK_HANDLE)
  RETURN
ENDIF

!*    ------------------------------------------------------------------
!*       0.     WAVE MODEL SETUP
!               ----------------

  ! Setup the wam for data assimilation. This is required to break a cyclic
  ! dependency between WAM and IFS




  CALL WVCOUPLE_INIT_EARLY(YDEWCOU, YDGEOMETRY, PTSTEP)
  IFSCONTEXT = GET_ALGOR_TYPE()
  IFSMUPTRA  = GET_MUPTRA()
  IFSNUPTRA  = GET_NUPTRA()
  IFSTOWAM_HANDLER => IFSTOWAM

!*       1.    Fetching ATM fields (U10, V10, ... etc.) and their grid:
!              --------------------------------------------------------

I_NFIELDS=YSD_WWD%NDIM
I_NWVFIELDS=YSD_WSD%NDIM

IF (ALLOCATED (Z_FIELDS)) DEALLOCATE (Z_FIELDS)
ALLOCATE (Z_FIELDS(IGPTOTG,I_NFIELDS))


CALL WVXF2GB(YDGEOMETRY, YDSURF, LWFRSTIME,PTSTEP, YDEWCOU, I_NFIELDS, I_NC, I_NR,&
 & KSTPW,&
 & LWCOUNORMS, Z_FIELDS, IGPTOT, IGPTOTG, IPROMA, IDGLG)


INADV = NADV_WAVE


!*       2.    ALLOCATE WAVE RELATED ARRAYS.
!              -------- ---- ------- -------
CALL WVALLOC


IF ( NGAUSSW == 1 ) THEN
  NLAT1W=NLATW
  NLON1W=NLONW
ELSE
  NLAT1W=NINT(180._JPRB/RDEGREW)+1
  NLON1W=NLONW
ENDIF
! THIS IS A GLOBAL ARRAY, WE SHOULD REALLY ONLY ALLOCATE IT ONCE
! BEST SOLUTION IS TO REMOVE IT COMPLETELY AS SOON AS POSSIBLE
! I HADADE 24/05/2021
IF (.NOT. ALLOCATED(Z_WVFLDWX)) THEN
  ALLOCATE (Z_WVFLDWX(NLON1W,NLAT1W,I_NWVFIELDS))
ELSE IF ((UBOUND(Z_WVFLDWX,1) /= NLON1W) .OR. &
       & (UBOUND(Z_WVFLDWX,2) /= NLAT1W) .OR. &
       & (UBOUND(Z_WVFLDWX,3) /= I_NWVFIELDS)) THEN
  DEALLOCATE (Z_WVFLDWX)
  ALLOCATE (Z_WVFLDWX(NLON1W,NLAT1W,I_NWVFIELDS))
ENDIF

IF(NWV_W2IWGHT >  0) THEN
  I_WVFLDRG=NWV_W2IWGHT
ELSE
  I_WVFLDRG=IGPTOT
ENDIF
ALLOCATE (Z_WVFLDRG(I_WVFLDRG,I_NWVFIELDS))
ALLOCATE(ZDELLO(NLATW))

!     ------------------------------------------------------------------

!*       3.    CALLS THE WAVE MODEL.
!              ----- --- ---- ------

CALL SURF_INQ(YSURF,PRNU=ZRNU)
CALL SURF_INQ(YSURF,PRNUM=ZRNUM)
CALL SURF_INQ(YSURF,PRCHAR=ZRCHAR)
! WARNING: PASSING Z_WVFLDWX OF SIZE NLON1W, NLAT1W, I_NWVFIELDS (includes South Pole latitudes)
! WHEREAS WAVEMDL WILL ONLY MANIPULATE Z_WVFLDWX USING NLONW, NLATW, I_NWVFIELDS (without South Pole latitudes)
! WE CAN DO THIS BECAUSE WAM STORES LATITUDES IN A NORTH-SOUTH ORIENTATION
! THIS IS A QUICK FIX TO REMOVE THE VERY COSTLY MEMORY COPY FROM WHAT USED TO BE THE REDUCED WAM GRID
! Z_WVFLDWN INTO Z_WVFLDWX, BOTH OF WHICH ARE GLOBAL ARRAYS
! A COMPLETE SOLUTION SHOULD SEE THE REMOVAL OF Z_WVFLDWX AS WELL AND ANY SIMILAR GLOBAL ARRAYS
CALL WAVEMDL (CBEGDAT, PTSTEP, KSTOP, KSTPW, &
 & I_NFIELDS,IGPTOTG, I_NC, I_NR, NGRIB_HANDLE_FOR_WAM , RMISSW, ZRCHAR, Z_FIELDS,&
 & NATMFLX, &
 & LWCUR ,LWSTOKES,&
 & I_NWVFIELDS, Z_WVFLDWX, NLONW, NLATW, LDSTOP, LDWRRE,&
 & LLRESTARTED, ZDELLO, LWCOUNORMS, LREPRO4DVAR, &
 & YDEWCOU%MASK_WAVE_IN, YDEWCOU%MASK_WAVE_OUT,&
 & LWFRSTIME, INADV, RPLRADI, RPLRG,&
 & ZRNU, ZRNUM,&
 & NDATE_TIME_WINDOW_END, NSTEP,&
 & IO_SERV_C001%NPROC_IO > 0 )

!!LWFRSTIME = LLFRSTIME !! WAVEMDL doesn't change the FIRSTIME argument any more
NADV_WAVE = INADV

DEALLOCATE (Z_FIELDS)

ALLOCATE (ZDXNS(NLAT1W))

IF (LWFRSTIME) THEN
  LWFRSTIME = .FALSE.
  IF (LLRESTARTED) THEN
    WRITE (NULOUT,*)'WVCOUPLE: WAM RESTARTED FOR DATE = ', CBEGDAT
  ENDIF
ENDIF
IF ( LDSTOP.OR. LDWRRE) THEN
  WRITE (NULOUT,*)'WVCOUPLE: WAM CREATED RESTART FILES '
ENDIF

!     ------------------------------------------------------------------
!*        4.   DEALLOCATE UNUSED ARRAYS
!              ---------- ------ ------

!  Consider not deallocating to save serial time on large numbers of processors
!  See LLFREE_WAM_MEMORY
   IF(LLFREE_WAM_MEMORY) CALL WVDEALLOC

!     ------------------------------------------------------------------

!*        5.    OBTAINS THE WAVE FIELDS IN THE REDUCED GRID.
!               ------- --- ---- ------ -- --- ------- -----

IF (LWCOU2W) THEN

!         5.1   EXTENDS THE LAT/LON FIELDS TO THE POLAR AREAS.

  CALL GSTATS(1994,0)
  DO JLA=NLATW+1,NLAT1W
    DO JLO=1,NLON1W
      Z_WVFLDWX(JLO,JLA,1)=ZRCHAR   ! Charnock field
      IF (I_NWVFIELDS >= 2) THEN
        Z_WVFLDWX(JLO,JLA,2:I_NWVFIELDS)=0.0_JPRB  ! other fields
      ENDIF
    ENDDO
  ENDDO
  CALL GSTATS(1994,1)

  DO JLA=1,NLATW
    JSN=NLATW-JLA+1
    ZDXNS(JLA)=ZDELLO(JSN)
  ENDDO
  DO JLA=NLATW+1,NLAT1W
    ZDXNS(JLA)=ZDELLO(1)
  ENDDO

!        5.2   CONVERTS FROM REGULAR/IRREGULAR LAT/LON USED BY THE WAVE MODEL
!              INTO THE REDUCED GRID OF THE ATMOSPHERIC MODEL.

  CALL WVWG2RG(YDGEOMETRY,YDEWCOU,Z_WVFLDWX,I_NWVFIELDS,NLON1W,NLAT1W,ZDXNS,NGAUSSW,&
   & Z_WVFLDRG,IDGLG,I_WVFLDRG,IPROMA)


!        5.3  DETERMINES THE MASK THAT WILL BE USED BY WAM TO SET
!             WHICH TASKS IN IFS ARE RECEIVING INFORMATION FROM
!             THE CURRENT TASK.

  IF(LWVOUT_MASK_NOT_SET) THEN
    DO IWVCL=1,4
      DO ILEN=1,NWV_W2IWGHT
        JLOW=YDEWCOU%IWV_LON(ILEN,IWVCL)
        JLAW=YDEWCOU%IWV_LAT(ILEN,IWVCL)
        IF(JLAW >= 1 .AND. JLAW <= NLATW) THEN
          YDEWCOU%MASK_WAVE_OUT(JLOW,JLAW)=1
        ENDIF
      ENDDO
    ENDDO
    LWVOUT_MASK_NOT_SET=.FALSE.
  ENDIF

!     ------------------------------------------------------------------

!*       6.    PUT THE FIELD IN THE SURFACE WORK FILE
!              --- --- ----- -- --- ------- ---- ----

  CALL WVRG2XF(YDSURF,Z_WVFLDRG,I_NWVFIELDS,I_WVFLDRG,IPROMA)

ENDIF


IF (ALLOCATED(Z_WVFLDRG)) DEALLOCATE(Z_WVFLDRG)
IF (ALLOCATED(ZDELLO)) DEALLOCATE (ZDELLO)
IF (ALLOCATED(ZDXNS)) DEALLOCATE (ZDXNS)

IF (NSTEP > 0 .AND. LWCOU) THEN
  WRITE(NULOUT,*) ' '
  WRITE(NULOUT,*) 'END OF WAVE MODEL CALL '
  WRITE(NULOUT,*) '------------------------------------',&
   & '----------------------------------- '
ENDIF

!     ------------------------------------------------------------------
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('WVCOUPLE',1,ZHOOK_HANDLE)
#else
#include "abor1.intfb.h"
CALL ABOR1('wvcouple should never be called')
#endif
END SUBROUTINE WVCOUPLE
