! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE WVWG2RG(YDGEOMETRY,YDEWCOU,PIN,K_NWVFIELDS,KLORG,KLARG,PDXNS,K_IQGAUSS,&
&                  POUT,KLAGG,KBIG,KPROMA)

!*** *WVWG2RG* - INTERPOLATES A FIELD FROM REGULAR TO GAUSSIAN GRID

!     PURPOSE.
!     --------

!     *RGW2GG* IS CALLED TO CONVERT A FIELD FROM A LAT/LON (REGULAR OR
!     IRREGULAR) GRID TO GAUSSIAN GRID (REDUCED OR FULL).
!     THERE IS NO INTENTION OF
!     GENERALITY. IT IS DESIGNED PRIMARILY FOR USE WITH THE WAVE COUPLING
!     (NOTE IN PARTICULAR THE SCANNING OF THE LATITUDE LINES.
!     NO DISTINCTION IS MADE BETWEEN LAND AND SEA POINTS.
!     !!! IT IS ONLY VALID FOR GLOBAL MODEL GRID !!!

!**   INTERFACE.
!     ----------

!           *CALL* *WVWG2RG(...)
!           *RGW2GG* IS CALLED FROM *WCOUPLE*.
!           PARAMETERS - *PIN* - INPUT FIELD IN LAT/LON GRID
!                                    (LATITUDES SCANNED NORTH TO SOUTH)
!                                FOR IRREGULAR GRID, THIS MIGHT MEAN THAT
!                                THE GRID WAS EXTENDED TO THE POLES BY ADDING
!                                GRID POINTS WHICH ARE SPACED REGULARLY FROM
!                                THE LAST LATITUDE OF THE WAVE GRID TO THE POLES
!                        *NWVFIELDS* - Number of fields to pass from WAVE to ATM
!                        *KLORG* - FIRST DIEMENSION OF PIN
!                        *KLARG* - SECOND DIEMESION OF PIN
!                        *PDXNS* - GRID SPACING FOR EACH LATITUDE FROM
!                                  NORTH TO SOUTH (CANNOT BE ZERO !!!)
!                        *IQGAUSS  =1 IF WAM IS USING A QUASI GAUSSIAN GRID
!                        *POUT* - OUTPUT FIELD IN GAUSSIAN REDUCED OR FULL GRID
!                                 (LATITUDES SCANNED NORTH TO SOUTH)
!                        *KLAGG* - NUMBER OF GAUSSIAN GRID LATITUDES
!                        *KBIG* - MAXIMUN DIMENSION OF POUT
!                                 ONLY FOR LOCAL GRID POINTS.

!     METHOD.
!     -------

!           FIRST THE VALUES FOR THE REDUCED GAUSSIAN GRID ARE OBTAINED
!     FROM THE INPUT ARRAY *PIN(KLORG,KLARG)* USING BILINEAR INTERPOLATION.
!     THE FINAL REDUCED GRID ARRAY IS RIGHT-PADDED WITH ZERO VALUES.

!     EXTERNAL.
!     ---------

!     REFERENCE.
!     ----------

!        NONE SO FAR.

!     AUTHOR.
!     -------
!      P. VITERBO      E.C.M.W.F.        6/04/89

!     MODIFICATIONS.
!     --------------
!      S. ABDALLA   ECMWF, 27/11/01: GENERALISE WAVE-ATM INTERFACE.
!      J. BIDLOT    ECMWF, 20/11/03: ONLY PERFORM THE INTERPOLATION FOR THE GRID
!                          POINTS THAT ARE LOCAL. 
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      D.Salmond     22-Nov-2005 Mods for coarser/finer physics
!      G.Mozdzynski (Feb 2011): OOPS cleaning, use of derived type TCSGLEG
!      T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!     ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST       , ONLY : RPI
USE YOEWCOU      , ONLY : TEWCOU
USE YOMMP0       , ONLY : MY_REGION_NS, MY_REGION_EW

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TEWCOU)      ,INTENT(INOUT) :: YDEWCOU
INTEGER(KIND=JPIM),INTENT(IN)    :: K_NWVFIELDS 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLORG 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLARG 
INTEGER(KIND=JPIM),INTENT(IN)    :: KBIG 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PIN(KLORG,KLARG,K_NWVFIELDS) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDXNS(KLARG) 
INTEGER(KIND=JPIM),INTENT(IN)    :: K_IQGAUSS 
REAL(KIND=JPRB)   ,INTENT(OUT)   :: POUT(KBIG,K_NWVFIELDS) 
INTEGER(KIND=JPIM),INTENT(IN)    :: KLAGG 
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROMA

!     ------------------------------------------------------------------

REAL(KIND=JPRB) :: ZLATNS(KLAGG), ZCONDX(KLARG)
INTEGER(KIND=JPIM) :: INLON(KLARG)
INTEGER(KIND=JPIM),ALLOCATABLE :: ILOENG(:)
REAL(KIND=JPRB),ALLOCATABLE :: ZRLATIG(:)

INTEGER(KIND=JPIM) :: IILO, ILAT, ILATM, ILATP, ILON, ILONMM, ILONMP,&
 & ILONPM, ILONPP, JLAT, JLON1, JLON2, IFLD  
INTEGER(KIND=JPIM) :: IA, IB, IGL1, IGL2, IGLOFF, ILEN, JGL, JLON
INTEGER(KIND=JPIM) :: IC, ICC, IDUM, JDUM 
INTEGER(KIND=JPIM) :: JSTGLO, IST, IEND

REAL(KIND=JPRB) :: ZCONS1, ZCONS2, ZCONS4, ZDXMM, ZDXMP, ZDXPM,&
 & ZDXPP, ZDY, ZDYM, ZDYP, ZLATG, ZLONG, ZMONORTH  
REAL(KIND=JPRB) :: ZMAX, ZDUM
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('WVWG2RG',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM, &
  & YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP, YDCSGLEG=>YDGEOMETRY%YRCSGLEG)
ASSOCIATE(NDGENG=>YDDIM%NDGENG, NDGSAG=>YDDIM%NDGSAG, &
 & LWVOUT_MASK_NOT_SET=>YDEWCOU%LWVOUT_MASK_NOT_SET, &
 & NWV_W2IWGHT=>YDEWCOU%NWV_W2IWGHT, RNORTW=>YDEWCOU%RNORTW, &
 & RSOUTW=>YDEWCOU%RSOUTW, &
 & NLOENG=>YDGEM%NLOENG, &
 & NFRSTLAT=>YDMP%NFRSTLAT, NLSTLAT=>YDMP%NLSTLAT, NONL=>YDMP%NONL, &
 & NPTRFRSTLAT=>YDMP%NPTRFRSTLAT, NSTA=>YDMP%NSTA)
!     ------------------------------------------------------------------

IF(KBIG < NWV_W2IWGHT ) THEN
  CALL ABOR1("WVWG2RG: PROBLEM: KBIG < NWV_W2IWGHT  !!! ")
ENDIF 

CALL GSTATS(1993,0)

! 1. COMPUTE INTEROLATION WEIGHTS AND INDICES 
!    ----------------------------------------

IF(.NOT.ALLOCATED(YDEWCOU%WV_W2IWGHT) .OR. LWVOUT_MASK_NOT_SET) THEN

! DEFINE INFORMATION ON WAM EXTENDED IRREGULAR GRID
  IF ( K_IQGAUSS == 1 ) THEN
    ZMONORTH=RNORTW
!!! this is crude approaximation for the spacing between Gaussian latitude
!!! It will work to find the closest grid point, but it should be replaced
!!! with something better to insure that grids are mathced.
    ZCONS1=REAL(KLARG-1,JPRB)/(RNORTW-RSOUTW)
  ELSE
    ZMONORTH=90._JPRB
    ZCONS1=REAL(KLARG-1,JPRB)/180._JPRB
  ENDIF
  ZDY=1.0_JPRB/ZCONS1
  DO ILAT = 1,KLARG
    INLON(ILAT) = NINT(360._JPRB/PDXNS(ILAT))
    ZCONDX(ILAT) = 1.0_JPRB/PDXNS(ILAT)
  ENDDO


  ALLOCATE(ILOENG(NDGSAG:NDGENG))
  ALLOCATE(ZRLATIG(NDGSAG:NDGENG))
  ILOENG=NLOENG
  ZRLATIG=YDCSGLEG%RLATIG

! COMPUTE THE GAUSSIAN LATITUDES.
  ZCONS4=180._JPRB/RPI
  DO JLAT=1,KLAGG
    ZLATNS(JLAT)=ZRLATIG(JLAT)*ZCONS4
  ENDDO

! FIND THE FIRST DIMENSION OF WV_W2IWGHT
  IA=MY_REGION_NS
  IB=MY_REGION_EW
  IGLOFF=NPTRFRSTLAT(IA)
  IGL1 = NFRSTLAT(IA)
  IGL2 = NLSTLAT(IA)
  ILEN = 0
  DO JGL=IGL1,IGL2
    JLON1=NSTA(IGLOFF+JGL-IGL1,IB)
    JLON2=JLON1+NONL(IGLOFF+JGL-IGL1,IB)-1
    ILEN=ILEN+(JLON2-JLON1)+1
  ENDDO

  NWV_W2IWGHT=ILEN
  IF(ALLOCATED(YDEWCOU%WV_W2IWGHT)) DEALLOCATE(YDEWCOU%WV_W2IWGHT)
  ALLOCATE(YDEWCOU%WV_W2IWGHT(NWV_W2IWGHT,4))
  IF(ALLOCATED(YDEWCOU%IWV_LON)) DEALLOCATE(YDEWCOU%IWV_LON)
  ALLOCATE(YDEWCOU%IWV_LON(NWV_W2IWGHT,4))
  IF(ALLOCATED(YDEWCOU%IWV_LAT)) DEALLOCATE(YDEWCOU%IWV_LAT)
  ALLOCATE(YDEWCOU%IWV_LAT(NWV_W2IWGHT,4))

! COMPUTE WV_W2IWGHT
  IA=MY_REGION_NS
  IB=MY_REGION_EW
  IGLOFF=NPTRFRSTLAT(IA)
  IGL1 = NFRSTLAT(IA)
  IGL2 = NLSTLAT(IA)

  ILEN = 0
  DO JGL=IGL1,IGL2
    ZLATG=ZMONORTH-ZLATNS(JGL)
    ILAT=ZLATG*ZCONS1
    ILAT=MIN(MAX(ILAT,0),KLARG-1)
    ILATM=ILAT+1
    ILATP=MIN(ILATM+1,KLARG)
    ZDYM=ZLATG-ILAT*ZDY
    ZDYP=ZDY-ZDYM
    ZDYM=ZDYM*ZCONS1
    ZDYP=ZDYP*ZCONS1

    IILO=ILOENG(JGL)
    ZCONS2=360._JPRB/REAL(IILO,JPRB)

    JLON1=NSTA(IGLOFF+JGL-IGL1,IB)
    JLON2=JLON1+NONL(IGLOFF+JGL-IGL1,IB)-1

    DO JLON=JLON1,JLON2
      ZLONG=REAL(JLON-1,JPRB)*ZCONS2

      ILON=INT(ZLONG/PDXNS(ILATM))
      ILONMM=ILON+1
      ILONPM=ILONMM+1
      IF (ILONPM > INLON(ILATM)) ILONPM=1

      ZDXMM=ZLONG-ILON*PDXNS(ILATM)
      ZDXPM=PDXNS(ILATM)-ZDXMM
      ZDXMM=ZDXMM*ZCONDX(ILATM)
      ZDXPM=ZDXPM*ZCONDX(ILATM)

      ILON=INT(ZLONG/PDXNS(ILATP))
      ILONMP=ILON+1
      ILONPP=ILONMP+1
      IF (ILONPP > INLON(ILATP)) ILONPP=1

      ZDXMP=ZLONG-ILON*PDXNS(ILATP)
      ZDXPP=PDXNS(ILATP)-ZDXMP
      ZDXMP=ZDXMP*ZCONDX(ILATP)
      ZDXPP=ZDXPP*ZCONDX(ILATP)

      ILEN=ILEN+1
      IF(ILEN > KBIG ) THEN
         CALL ABOR1("WVWG2RG: PROBLEM ILEN > KBIG !!! ")
      ENDIF 
      YDEWCOU%IWV_LON(ILEN,1)=ILONMM
      YDEWCOU%IWV_LAT(ILEN,1)=ILATM
      YDEWCOU%WV_W2IWGHT(ILEN,1)=ZDXPM*ZDYP

      YDEWCOU%IWV_LON(ILEN,2)=ILONPM
      YDEWCOU%IWV_LAT(ILEN,2)=ILATM
      YDEWCOU%WV_W2IWGHT(ILEN,2)=ZDXMM*ZDYP

      YDEWCOU%IWV_LON(ILEN,3)=ILONMP
      YDEWCOU%IWV_LAT(ILEN,3)=ILATP
      YDEWCOU%WV_W2IWGHT(ILEN,3)=ZDXPP*ZDYM

      YDEWCOU%IWV_LON(ILEN,4)=ILONPP
      YDEWCOU%IWV_LAT(ILEN,4)=ILATP
      YDEWCOU%WV_W2IWGHT(ILEN,4)=ZDXMP*ZDYM


    ENDDO
  ENDDO

  DEALLOCATE(ILOENG)
  DEALLOCATE(ZRLATIG)

  IF ( K_IQGAUSS == 1 ) THEN
    ! Insure that index 1 points to the closest grid point

    !$OMP PARALLEL DO SCHEDULE(STATIC)&
    !$OMP&PRIVATE(JSTGLO,IST,IEND,ILEN,IC,ZMAX,ICC,ZDUM,IDUM,JDUM)
    DO JSTGLO=1,NWV_W2IWGHT,KPROMA
      IST    = JSTGLO 
      IEND   = MIN(JSTGLO+KPROMA-1,NWV_W2IWGHT)

        DO ILEN=IST, IEND

          IC = 1
          ZMAX = YDEWCOU%WV_W2IWGHT(ILEN,IC)
          DO ICC = 2,4
            IF ( ZMAX < YDEWCOU%WV_W2IWGHT(ILEN,ICC) ) THEN
              IC = ICC
              ZMAX = YDEWCOU%WV_W2IWGHT(ILEN,IC)
            ENDIF
          ENDDO 

          IF ( IC /= 1 ) THEN
            ZDUM = YDEWCOU%WV_W2IWGHT(ILEN,1)
            IDUM = YDEWCOU%IWV_LON(ILEN,1) 
            JDUM = YDEWCOU%IWV_LAT(ILEN,1)

            YDEWCOU%WV_W2IWGHT(ILEN,1) = YDEWCOU%WV_W2IWGHT(ILEN,IC)
            YDEWCOU%IWV_LON(ILEN,1) = YDEWCOU%IWV_LON(ILEN,IC)
            YDEWCOU%IWV_LAT(ILEN,1) = YDEWCOU%IWV_LAT(ILEN,IC)

            YDEWCOU%WV_W2IWGHT(ILEN,IC) = ZDUM
            YDEWCOU%IWV_LON(ILEN,IC) = IDUM
            YDEWCOU%IWV_LAT(ILEN,IC) = JDUM
          ENDIF

        ENDDO

    ENDDO
    !$OMP END PARALLEL DO
  ENDIF

ENDIF


! 2. INTERPOLATE TO IFS GRID
!    -----------------------

IF ( K_IQGAUSS == 1 ) THEN
  ! SAME GAUSSIAN GRID (this should be re-written to avoid the copy...)
  !$OMP PARALLEL DO SCHEDULE(STATIC)&
  !$OMP&PRIVATE(JSTGLO,IST,IEND,IFLD,ILEN)
  DO JSTGLO=1,NWV_W2IWGHT,KPROMA
    IST    = JSTGLO 
    IEND   = MIN(JSTGLO+KPROMA-1,NWV_W2IWGHT)

    DO IFLD=1,K_NWVFIELDS
      DO ILEN=IST, IEND
        POUT(ILEN,IFLD) = PIN(YDEWCOU%IWV_LON(ILEN,1),YDEWCOU%IWV_LAT(ILEN,1),IFLD)
      ENDDO
    ENDDO
  ENDDO
!$OMP END PARALLEL DO


ELSE
  !$OMP PARALLEL DO SCHEDULE(STATIC)&
  !$OMP&PRIVATE(JSTGLO,IST,IEND,IFLD,ILEN)
  DO JSTGLO=1,NWV_W2IWGHT,KPROMA
    IST    = JSTGLO 
    IEND   = MIN(JSTGLO+KPROMA-1,NWV_W2IWGHT)

    DO IFLD=1,K_NWVFIELDS
      DO ILEN=IST, IEND
        POUT(ILEN,IFLD)=&
        &(YDEWCOU%WV_W2IWGHT(ILEN,1)*PIN(YDEWCOU%IWV_LON(ILEN,1),YDEWCOU%IWV_LAT(ILEN,1),IFLD)+&
        & YDEWCOU%WV_W2IWGHT(ILEN,2)*PIN(YDEWCOU%IWV_LON(ILEN,2),YDEWCOU%IWV_LAT(ILEN,2),IFLD)+&
        & YDEWCOU%WV_W2IWGHT(ILEN,3)*PIN(YDEWCOU%IWV_LON(ILEN,3),YDEWCOU%IWV_LAT(ILEN,3),IFLD)+&
        & YDEWCOU%WV_W2IWGHT(ILEN,4)*PIN(YDEWCOU%IWV_LON(ILEN,4),YDEWCOU%IWV_LAT(ILEN,4),IFLD))
      ENDDO
    ENDDO
  ENDDO
!$OMP END PARALLEL DO

ENDIF


CALL GSTATS(1993,1)

!     ------------------------------------------------------------------
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('WVWG2RG',1,ZHOOK_HANDLE)
END SUBROUTINE WVWG2RG
