! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE CHECK_PHTRAJT(YDGEOMETRY,YDMODEL,&
 & KSTA,KEND,KTRAC,KSTEP,KIBL,PTRAJ_PHYS_TLAD,&
 & PTENTVD5,PTENQVD5,PTENUVD5,PTENVVD5,&
 & PTENTGW5,PTENUGW5,PTENVGW5,&
 & PTENTCO5,PTENQCO5,PTENUCO5,PTENVCO5,&
 & PTENTCL5,PTENUWM5,PTENVWM5,&
 & PTENTSL5,PTENQSL5,&
 & PDIFTQ5 ,PDIFTS5 ,PEMTED5 ,PTRSOL5,&
 & PA5 ,PL5 ,PI5,&
 & PLUDE5  ,PLU5    , PMFU5  , PMFD5 , &
 & PFPLCL5 ,PFPLCN5 ,PUCFL5  ,PVCFL5 ,PTCFL5 ,PQCFL5,&
 & PFRSOTI5,PAHFSTI5,PEVAPTI5,&
 & PEVAPSNW5,PFPLSL5,PFPLSN5 ,PFRTH5 ,PSLPHY95,&
 & PTENC55D)

!**** *CHECK_PHTRAJT* - Check the trajectory of phys.tendencies does not change
!                   to work file

!     Purpose.  Write out the trajectory of phys.tendencies
!               to work file

!**   Interface.
!     ----------
!        *CALL* *CHECK_PHTRAJT(...)*

!        Explicit arguments :
!        --------------------  KSTA    - start adress         (input)
!                              KEND    - end adress           (input)
!                              PTRAJ_PHYS_TLAD - structure traj. (output)
!                              PTENTVD5 to PTRSOL5: trajectory of
!                                        phys.tendencies to be written (input)

!        Implicit arguments :  None
!        --------------------

!     Method.
!     -------

!     Externals.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!        Marta Janiskova  *ECMWF*

!     Modifications.
!     --------------
!        Original : 2000-01-20
!        Modified :
!           P. Lopez   ECMWF  2003-12:   Added arguments PLUDE5 and PLU5.
!           M.Hamrud      01-Oct-2003 CY28 Cleaning
!           M.Hamrud      10-Jan-2004 CY28R1 Cleaning
!           M. Janiskova  18-Sep-2009: added tendencies needed for non-orog.gwd
!           M. Janiskova  18-May-2010: Cleaning & saving fields for LEMWAVE
!           F. Vana  28-Nov-2013 : Redesigned trajectory handling
!           M. Janiskova  03-May-2012: Saving fields for surface scheme
!           F. Vana       11-Sep-2020: SLAVEPP and LEPCLD2
!           F. Vana       22-Sep-2021: CAMS with LETRAJPT
!        ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL   , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMTRAJ  , ONLY : TRAJ_PHYS_TLAD_TYPE, LPRTTRAJ
USE YOMLUN   , ONLY : NULOUT,NULERR
USE YOMPHYDER, ONLY : MODEL_STATE_TYPE

!        ------------------------------------------------------------------

IMPLICIT NONE

! * INPUT:
TYPE(GEOMETRY)            ,INTENT(IN)    :: YDGEOMETRY
TYPE(MODEL)               ,INTENT(IN)    :: YDMODEL
INTEGER(KIND=JPIM)        ,INTENT(IN)    :: KSTA
INTEGER(KIND=JPIM)        ,INTENT(IN)    :: KEND
INTEGER(KIND=JPIM)        ,INTENT(IN)    :: KTRAC
INTEGER(KIND=JPIM)        ,INTENT(IN)    :: KSTEP
INTEGER(KIND=JPIM)        ,INTENT(IN)    :: KIBL
TYPE (TRAJ_PHYS_TLAD_TYPE),INTENT(IN)    :: PTRAJ_PHYS_TLAD
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENTVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENQVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENUVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENVVD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENTGW5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENUGW5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENVGW5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENTCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENQCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENUCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENVCO5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENTCL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENUWM5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENVWM5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENTSL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENQSL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PDIFTQ5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PDIFTS5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PEMTED5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTRSOL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PA5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PI5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PLUDE5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PLU5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PMFU5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PMFD5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PFPLCL5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PFPLCN5(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PUCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PVCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PQCFL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PFRSOTI5(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_PHY_G%YRDPHY%NTILES)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PAHFSTI5(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_PHY_G%YRDPHY%NTILES)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PEVAPTI5(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_PHY_G%YRDPHY%NTILES)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PEVAPSNW5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PFPLSL5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PFPLSN5(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)           ,INTENT(IN)    :: PFRTH5(YDGEOMETRY%YRDIM%NPROMA)
TYPE (MODEL_STATE_TYPE)   ,INTENT(IN)    :: PSLPHY95
REAL(KIND=JPRB)           ,INTENT(IN)    :: PTENC55D(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,KTRAC)


!!$INTEGER(KIND=JPIM) :: INOTSAME(1000)=0
LOGICAL :: LLSTR
LOGICAL,SAVE :: LL_OOPS_DEBUG = .FALSE.
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

IF(.NOT.LL_OOPS_DEBUG) RETURN

IF (LHOOK) CALL DR_HOOK('CHECK_PHTRAJT',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, &
 & YDMP=>YDGEOMETRY%YRMP,YGFL=>YDMODEL%YRML_GCONF%YGFL,YDEPHY=>YDMODEL%YRML_PHY_EC%YREPHY,&
 & YDDPHY=>YDMODEL%YRML_PHY_G%YRDPHY,YDPHNC=>YDMODEL%YRML_PHY_SLIN%YRPHNC)
ASSOCIATE(NPROMA=>YDDIM%NPROMA, &
 & NFLEVG=>YDDIMV%NFLEVG, YQ=>YGFL%YQ, &
 & NTILES=>YDDPHY%NTILES, &
 & LEMWAVE=>YDEPHY%LEMWAVE, LSLPHY=>YDEPHY%LSLPHY, &
 & LEGWWMS2=>YDPHNC%LEGWWMS2, LENCLD2=>YDPHNC%LENCLD2, &
 & LERADLW2=>YDPHNC%LERADLW2, LERADN2=>YDPHNC%LERADN2, &
 & LERADSW2=>YDPHNC%LERADSW2, LESURF2=>YDPHNC%LESURF2, &
 & LEPCLD2=>YDPHNC%LEPCLD2, LETRAJPT=>YDPHNC%LETRAJPT)
!*       0.    CHECK IF ANY ACCTION IS DONE HERE

LLSTR= (LERADN2.OR.LERADSW2.OR.LERADLW2).OR. LEGWWMS2 .OR. LENCLD2 .OR. LETRAJPT

!*       1.    WRITE OUT GRIDPOINT ARRAY.
!              --------------------------

IF (LERADN2.OR.LERADSW2.OR.LERADLW2) THEN
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PEMTED5(KSTA:KEND,1:NFLEVG+1),PEMTED5(KSTA:KEND,1:NFLEVG+1),'PEMTED5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTRSOL5(KSTA:KEND,1:NFLEVG+1),PTRSOL5(KSTA:KEND,1:NFLEVG+1),'PTRSOL5')
ENDIF

IF (LEGWWMS2) THEN
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENUWM5(KSTA:KEND,1:NFLEVG),PTENUWM5(KSTA:KEND,1:NFLEVG),'PTENUWM5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENVWM5(KSTA:KEND,1:NFLEVG),PTENVWM5(KSTA:KEND,1:NFLEVG),'PTENVWM5')
ENDIF

IF (LENCLD2 .AND. .NOT.LEPCLD2) THEN
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PA5(KSTA:KEND,1:NFLEVG),PA5(KSTA:KEND,1:NFLEVG),'PA5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PL5(KSTA:KEND,1:NFLEVG),PL5(KSTA:KEND,1:NFLEVG),'PL5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PI5(KSTA:KEND,1:NFLEVG),PI5(KSTA:KEND,1:NFLEVG),'PI5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PLUDE5(KSTA:KEND,1:NFLEVG),PLUDE5(KSTA:KEND,1:NFLEVG),'PLUDE5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PLU5(KSTA:KEND,1:NFLEVG)  ,PLU5(KSTA:KEND,1:NFLEVG),'PLU5')
ELSEIF(LEPCLD2) THEN
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PA5(KSTA:KEND,1:NFLEVG),PA5(KSTA:KEND,1:NFLEVG),'PA5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PLUDE5(KSTA:KEND,1:NFLEVG),PLUDE5(KSTA:KEND,1:NFLEVG),'PLUDE5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PLU5(KSTA:KEND,1:NFLEVG)  ,PLU5(KSTA:KEND,1:NFLEVG),'PLU5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PMFU5(KSTA:KEND,1:NFLEVG) ,PMFU5(KSTA:KEND,1:NFLEVG),'PMFU5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PMFD5(KSTA:KEND,1:NFLEVG) ,PMFD5(KSTA:KEND,1:NFLEVG),'PMFD5')
ENDIF

IF (LETRAJPT) THEN
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENTVD5(KSTA:KEND,1:NFLEVG),PTENTVD5(KSTA:KEND,1:NFLEVG),'PTENTVD5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENQVD5(KSTA:KEND,1:NFLEVG),PTENQVD5(KSTA:KEND,1:NFLEVG),'PTENQVD5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENUVD5(KSTA:KEND,1:NFLEVG),PTENUVD5(KSTA:KEND,1:NFLEVG),'PTENUVD5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENVVD5(KSTA:KEND,1:NFLEVG),PTENVVD5(KSTA:KEND,1:NFLEVG),'PTENVVD5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENTGW5(KSTA:KEND,1:NFLEVG),PTENTGW5(KSTA:KEND,1:NFLEVG),'PTENTGW5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENUGW5(KSTA:KEND,1:NFLEVG),PTENUGW5(KSTA:KEND,1:NFLEVG),'PTENUGW5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENVGW5(KSTA:KEND,1:NFLEVG),PTENVGW5(KSTA:KEND,1:NFLEVG),'PTENVGW5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENTCO5(KSTA:KEND,1:NFLEVG),PTENTCO5(KSTA:KEND,1:NFLEVG),'PTENTCO5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENQCO5(KSTA:KEND,1:NFLEVG),PTENQCO5(KSTA:KEND,1:NFLEVG),'PTENQCO5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENUCO5(KSTA:KEND,1:NFLEVG),PTENUCO5(KSTA:KEND,1:NFLEVG),'PTENUCO5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENVCO5(KSTA:KEND,1:NFLEVG),PTENVCO5(KSTA:KEND,1:NFLEVG),'PTENVCO5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PDIFTQ5(KSTA:KEND,1:NFLEVG+1),PDIFTQ5(KSTA:KEND,1:NFLEVG+1),'PDIFTQ5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PDIFTS5(KSTA:KEND,1:NFLEVG+1),PDIFTS5(KSTA:KEND,1:NFLEVG+1),'PDIFTS5')


 IF (LSLPHY) THEN
    CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENTSL5(KSTA:KEND,1:NFLEVG),PTENTSL5(KSTA:KEND,1:NFLEVG),'PTENTSL5')
    CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENQSL5(KSTA:KEND,1:NFLEVG),PTENQSL5(KSTA:KEND,1:NFLEVG),'PTENQSL5')
  ENDIF

  IF (.NOT. LEMWAVE) THEN
    CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PTENTCL5(KSTA:KEND,1:NFLEVG),PTENTCL5(KSTA:KEND,1:NFLEVG),'PTENTCL5')
  ENDIF

  IF ((LENCLD2.OR.LEPCLD2) .AND. LEMWAVE) THEN
    CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PFPLCL5(KSTA:KEND,1:NFLEVG+1),PFPLCL5(KSTA:KEND,1:NFLEVG+1),'PFPLCL5')
    CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PFPLCN5(KSTA:KEND,1:NFLEVG+1),PFPLCN5(KSTA:KEND,1:NFLEVG+1),'PFPLCN5')
    CALL CHECK_ARRAY1(PTRAJ_PHYS_TLAD%PUCFL5(KSTA:KEND),PUCFL5(KSTA:KEND),'PUCFL5')
    CALL CHECK_ARRAY1(PTRAJ_PHYS_TLAD%PVCFL5(KSTA:KEND),PVCFL5(KSTA:KEND),'PVCFL5')
    CALL CHECK_ARRAY1(PTRAJ_PHYS_TLAD%PTCFL5(KSTA:KEND),PTCFL5(KSTA:KEND),'PTCFL5')
    CALL CHECK_ARRAY1(PTRAJ_PHYS_TLAD%PQCFL5(KSTA:KEND),PQCFL5(KSTA:KEND),'PQCFL5')
  ENDIF

  IF (LESURF2) THEN
    CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PFRSOTI5(KSTA:KEND,1:NTILES),PFRSOTI5(KSTA:KEND,1:NTILES),'PFRSOTI5')
    CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PAHFSTI5(KSTA:KEND,1:NTILES),PAHFSTI5(KSTA:KEND,1:NTILES),'PAHFSTI5')
    CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PEVAPTI5(KSTA:KEND,1:NTILES),PEVAPTI5(KSTA:KEND,1:NTILES),'PEVAPTI5')
    IF (.NOT. ((LENCLD2.OR.LEPCLD2) .AND. LEMWAVE)) THEN
      CALL CHECK_ARRAY1(PTRAJ_PHYS_TLAD%PFPLCL5(KSTA:KEND,NFLEVG+1),PFPLCL5(KSTA:KEND,NFLEVG+1),'PFPLCL5')
      CALL CHECK_ARRAY1(PTRAJ_PHYS_TLAD%PFPLCN5(KSTA:KEND,NFLEVG+1),PFPLCN5(KSTA:KEND,NFLEVG+1),'PFPLCN5')
    ENDIF
    CALL CHECK_ARRAY1(PTRAJ_PHYS_TLAD%PEVAPSNW5(KSTA:KEND),PEVAPSNW5(KSTA:KEND),'PEVAPSNW5')
    CALL CHECK_ARRAY1(PTRAJ_PHYS_TLAD%PFPLSL5(KSTA:KEND),PFPLSL5(KSTA:KEND),'PFPLSL5')
    CALL CHECK_ARRAY1(PTRAJ_PHYS_TLAD%PFPLSN5(KSTA:KEND),PFPLSN5(KSTA:KEND),'PFPLSN5')
    CALL CHECK_ARRAY1(PTRAJ_PHYS_TLAD%PFRTH5(KSTA:KEND),PFRTH5(KSTA:KEND),'PFRTH5')
  ENDIF

  IF (KTRAC>0) CALL CHECK_ARRAY3(PTRAJ_PHYS_TLAD%TENDC55D(KSTA:KEND,1:NFLEVG,1:KTRAC), &
    &  PTENC55D(KSTA:KEND,1:NFLEVG,1:KTRAC),'PTENC55D')
ENDIF

IF (LSLPHY) THEN
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PHTENU5(KSTA:KEND,1:NFLEVG),PSLPHY95%U(KSTA:KEND,1:NFLEVG),'PHTENU5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PHTENV5(KSTA:KEND,1:NFLEVG),PSLPHY95%V(KSTA:KEND,1:NFLEVG),'PHTENV5')
  CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PHTENT5(KSTA:KEND,1:NFLEVG),PSLPHY95%T(KSTA:KEND,1:NFLEVG),'PHTENT5')
  IF (YQ%LPHY) CALL CHECK_ARRAY2(PTRAJ_PHYS_TLAD%PHTENQ5(KSTA:KEND,1:NFLEVG), &
   &                            PSLPHY95%GFL(KSTA:KEND,1:NFLEVG,YQ%MPSLP),'PHTENQ5')
ENDIF

IF (LPRTTRAJ.AND.LLSTR.AND.PTRAJ_PHYS_TLAD%LASTCHUNK)&
  &  WRITE(NULOUT,*)'GREPTRAJ WRITE TRAJ_PHYS_TLAD in CHECK_PHTRAJT'

!     ------------------------------------------------------------------
END ASSOCIATE
END ASSOCIATE

IF (LHOOK) CALL DR_HOOK('CHECK_PHTRAJT',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE CHECK_ARRAY1(PA,PB,CDLABEL)
REAL(KIND=JPRB),  INTENT(IN) :: PA(:)
REAL(KIND=JPRB),  INTENT(IN) :: PB(:)
CHARACTER(LEN=*), INTENT(IN) :: CDLABEL
LOGICAL :: LL

LL = (SUM(ABS(PA-PB)) == 0.0)
!$OMP CRITICAL
IF(.NOT.LL) THEN
  WRITE(NULERR,*) 'CHECK_PHTRAJT NOT SAME ',TRIM(CDLABEL), KSTEP,KIBL,SUM(ABS(PA-PB))
  CALL ABOR1('CHECK_PHTRAJT NOT SAME ')
!!$  IF(KIBL < 1000) THEN
!!$    INOTSAME(KIBL) = INOTSAME(KIBL)+1
!!$    IF(INOTSAME(KIBL) <= 10) THEN
!!$      WRITE(NULERR,*) 'CHECK_PHTRAJT NOT SAME ',TRIM(CDLABEL), KSTEP,KIBL,SUM(ABS(PA-PB))
!!$    ELSE
!!$      CALL ABOR1('CHECK_PHTRAJT NOT SAME ')
!!$    ENDIF
!!$  ELSE
!!$    CALL ABOR1('CHECK_PHTRAJT NOT SAME ')
!!$  ENDIF
ENDIF
!$OMP END CRITICAL
END SUBROUTINE CHECK_ARRAY1

SUBROUTINE CHECK_ARRAY2(PA,PB,CDLABEL)
REAL(KIND=JPRB),  INTENT(IN) :: PA(:,:)
REAL(KIND=JPRB),  INTENT(IN) :: PB(:,:)
CHARACTER(LEN=*), INTENT(IN) :: CDLABEL
LOGICAL :: LL

IF (LHOOK) CALL DR_HOOK('CHECK_PHTRAJT:CHECK_ARRAY',0,ZHOOK_HANDLE)
LL = (SUM(ABS(PA-PB)) == 0.0)
!$OMP CRITICAL
IF(.NOT.LL) THEN
  WRITE(NULERR,*) 'CHECK_PHTRAJT NOT SAME ',TRIM(CDLABEL), KSTEP,KIBL,SUM(ABS(PA-PB))
  CALL ABOR1('CHECK_PHTRAJT NOT SAME ')
!!$  IF(KIBL < 1000) THEN
!!$    INOTSAME(KIBL) = INOTSAME(KIBL)+1
!!$    IF(INOTSAME(KIBL) <= 10) THEN
!!$      WRITE(NULERR,*) 'CHECK_PHTRAJT NOT SAME ',TRIM(CDLABEL), KSTEP,KIBL,SUM(ABS(PA-PB))
!!$    ELSE
!!$      CALL ABOR1('CHECK_PHTRAJT NOT SAME ')
!!$    ENDIF
!!$  ELSE
!!$    CALL ABOR1('CHECK_PHTRAJT NOT SAME ')
!!$  ENDIF
ENDIF
IF (LHOOK) CALL DR_HOOK('CHECK_PHTRAJT:CHECK_ARRAY',1,ZHOOK_HANDLE)
!$OMP END CRITICAL
END SUBROUTINE CHECK_ARRAY2

SUBROUTINE CHECK_ARRAY3(PA,PB,CDLABEL)
REAL(KIND=JPRB),  INTENT(IN) :: PA(:,:,:)
REAL(KIND=JPRB),  INTENT(IN) :: PB(:,:,:)
CHARACTER(LEN=*), INTENT(IN) :: CDLABEL
LOGICAL :: LL

IF (LHOOK) CALL DR_HOOK('CHECK_PHTRAJT:CHECK_ARRAY1',0,ZHOOK_HANDLE)
LL = (SUM(ABS(PA-PB)) == 0.0)
!$OMP CRITICAL
IF(.NOT.LL) THEN
  WRITE(NULERR,*) 'CHECK_PHTRAJT NOT SAME ',TRIM(CDLABEL), KSTEP,KIBL,SUM(ABS(PA-PB))
  CALL ABOR1('CHECK_PHTRAJT NOT SAME ')
!!$  IF(KIBL < 1000) THEN
!!$    INOTSAME(KIBL) = INOTSAME(KIBL)+1
!!$    IF(INOTSAME(KIBL) <= 10) THEN
!!$      WRITE(NULERR,*) 'CHECK_PHTRAJT NOT SAME ',TRIM(CDLABEL), KSTEP,KIBL,SUM(ABS(PA-PB))
!!$    ELSE
!!$      CALL ABOR1('CHECK_PHTRAJT NOT SAME ')
!!$    ENDIF
!!$  ELSE
!!$    CALL ABOR1('CHECK_PHTRAJT NOT SAME ')
!!$  ENDIF
ENDIF
IF (LHOOK) CALL DR_HOOK('CHECK_PHTRAJT:CHECK_ARRAY1',1,ZHOOK_HANDLE)
!$OMP END CRITICAL
END SUBROUTINE CHECK_ARRAY3

END SUBROUTINE CHECK_PHTRAJT

