! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE CPCFU(YDGEOMETRY,YDCFU,YDRIP,KST,KND,KSTC,KENDC,KSTGLO,LDFSTEP,&
 & PDIFCQ, PDIFCS, PDIFTQ, PDIFTS, PFCCQL, PFCCQN, PFCSQL, PFCSQN, PFPLCL,&
 & PFPLCN, PFPLCG, PFPLCH, PFPLSL, PFPLSN, PFPLSG, PFPLSH, PFRMH,  PFRSO ,&
 & PFRSOC, PFRTH , PFRTHC, PFDIS , PSTRCU, PSTRCV, PSTRDU, PSTRDV, PSTRTU,&
 & PSTRTV, PDELP , PNEB  , PQICE , PQLI  , PRES  , PSNS  , PO3   , PQ    ,&
 & PWS   , PFEVL , PFEVN , PCLCT , PCLCH , PCLCM , PCLCL , PCLCC , PFCLL ,&
 & PFCLN , PFCS  , PFONTE, PFCHSP, PFLWSP, PRUISS, PRUISP, PFEVV , PFTR  ,&
 & PRUISL, PFGEL , PFGELS, PFRSODS,PFRSOPS,PFRSOPT,PFRSOLU,PFRTHDS,PFRSDNI,&
 & PFRSGNI,PFLASH)

!**** *CPCFU* - CUMUL OF FLUX DIAGNOSTICS.

!     Purpose.
!     --------
!           DIAGNOSTICS OF PHYSICAL FLUXES.

!**   Interface.
!     ----------
!        *CALL* *CPCFU*

!        Explicit arguments :
!        --------------------

!       KPROMA                 - HORIZONTAL DIMENSION                 (INPUT)
!       KGL1,KGL2              - KGL1 TO KGL2 LATITUDES OF WORK.      (INPUT)
!       KSTABUF                - KSTABUF(JGL) FOR LATITUDE JGL        (INPUT)
!       FLUXES COMING FROM THE PHYSICAL PARAMETERIZATIONS             (INPUT)

!        --------------------

!     Method.
!     -------

!     Externals.
!     ----------

!     Reference.
!     ----------

!     Author.
!     -------
!      O. CLARY
!      Original : 06/92 D'APRES CUMCO

!     Modifications.
!     --------------
!      Modified : 01-08-07 R. El Khatib - pruning options
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      M.Hamrud      10-Jan-2004 CY28R1 Cleaning
!      Y.Seity       15-Jan-2007 add graupel and hail 
!      K. Yessad (July 2014): Move some variables.
!      R. Brozkova (Sep 2018): Added global normal irradiance.
!     ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMRIP       , ONLY : TRIP
USE YOMCFU       , ONLY : TCFU
USE YOMCST       , ONLY : RG
USE YOMCT3       , ONLY : NSTEP
USE YOMCT0,ONLY: LCORWAT

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TCFU)        ,INTENT(INOUT) :: YDCFU
TYPE(TRIP)        ,INTENT(IN)    :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN)    :: KST 
INTEGER(KIND=JPIM),INTENT(IN)    :: KND 
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTC 
INTEGER(KIND=JPIM),INTENT(IN)    :: KENDC 
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTGLO 
LOGICAL           ,INTENT(IN)    :: LDFSTEP 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFCQ(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFCS(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFTQ(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFTS(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCCQL(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCCQN(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCSQL(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCSQN(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLCL(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLCN(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLCG(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLCH(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLSL(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLSN(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLSG(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLSH(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRMH(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRSO(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRSOC(YDGEOMETRY%YRDIM%NPROMA,0:1) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRTH(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRTHC(YDGEOMETRY%YRDIM%NPROMA,0:1) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFDIS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRCU(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRCV(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRDU(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRDV(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRTU(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRTV(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDELP(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNEB(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQICE(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQLI(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRES(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSNS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PO3(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQ(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFEVL(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFEVN(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLCT(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLCH(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLCM(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLCL(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLCC(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCLL(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCLN(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFONTE(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCHSP(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFLWSP(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRUISS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRUISP(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFEVV(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFTR(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRUISL(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFGEL(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFGELS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRSODS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRSOPS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRSOPT(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRSOLU(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRTHDS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRSDNI(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRSGNI(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFLASH(YDGEOMETRY%YRDIM%NPROMA) 

!     ------------------------------------------------------------------

REAL(KIND=JPRB) :: ZGFU(YDGEOMETRY%YRDIM%NPROMA,YDCFU%NFDCFU)
REAL(KIND=JPRB) :: ZFPREC9(YDGEOMETRY%YRDIM%NPROMA) ! past cumulated flux of total precipitations
REAL(KIND=JPRB) :: ZFPREC0(YDGEOMETRY%YRDIM%NPROMA) ! instantaneous flux of total precipitations
REAL(KIND=JPRB) :: ZSQPRE(YDGEOMETRY%YRDIM%NPROMA)  ! instantaneous flux of total squared precipitations

REAL(KIND=JPRB) :: ZEPS

INTEGER(KIND=JPIM) :: IJLEV, JLEV, JNIV, JF, IFLD, IOFF, ILEVB, JI, IADD
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "abor1.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('CPCFU',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP)
ASSOCIATE(LREACFU=>YDCFU%LREACFU, NFDCFU=>YDCFU%NFDCFU, NFRRC=>YDCFU%NFRRC, GFUBUF=>YDCFU%GFUBUF, &
 & NTYPCFU=>YDCFU%NTYPCFU, TYPE_CFU=>YDCFU%TYPE_CFU, &
 & NPROMA=>YDDIM%NPROMA, &
 & NFLEVG=>YDDIMV%NFLEVG, &
 & TSTEP=>YDRIP%TSTEP)
!     ------------------------------------------------------------------

!*    1.    PREPARATIONS

!*    1.1   READ IN FIELDS

IF (.NOT.LDFSTEP .OR. LREACFU) THEN
  ZGFU = GFUBUF (:, :, 1+(KSTGLO-1)/YDGEOMETRY%YRDIM%NPROMA)

ELSE
  ZGFU=0.0_JPRB
ENDIF

!*    1.2  SAVE TOTAL PRECIPITATIONS CUMULATED FLUX

IF (YDCFU%YCFUPT%MFDUTP > 0) THEN
  ZEPS=EPSILON(1.0_JPRB)*100._JPRB
  ZFPREC9(KST:KND)=0.0_JPRB
  ZFPREC0(KST:KND)=0.0_JPRB
  ZSQPRE(KST:KND)=0.0_JPRB
  IOFF=0
  DO JF=1,NTYPCFU

    IADD=1+IOFF
!   Last level only, in order to get the total precipitations :
    ILEVB=TYPE_CFU(JF)%ILEV
    IFLD=ILEVB+IOFF
    IJLEV=TYPE_CFU(JF)%INUMLEV(ILEVB)

    IF (IADD == YDCFU%YCFUPT%MFPLCL) THEN
      ZFPREC9(KST:KND)=ZFPREC9(KST:KND)+ZGFU(KST:KND,IFLD)
      ZFPREC0(KST:KND)=ZFPREC0(KST:KND)+PFPLCL(KST:KND,IJLEV)
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLCN) THEN
      ZFPREC9(KST:KND)=ZFPREC9(KST:KND)+ZGFU(KST:KND,IFLD)
      ZFPREC0(KST:KND)=ZFPREC0(KST:KND)+PFPLCN(KST:KND,IJLEV)
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLCG) THEN
      ZFPREC9(KST:KND)=ZFPREC9(KST:KND)+ZGFU(KST:KND,IFLD)
      ZFPREC0(KST:KND)=ZFPREC0(KST:KND)+PFPLCG(KST:KND,IJLEV)
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLCH) THEN
      ZFPREC9(KST:KND)=ZFPREC9(KST:KND)+ZGFU(KST:KND,IFLD)
      ZFPREC0(KST:KND)=ZFPREC0(KST:KND)+PFPLCH(KST:KND,IJLEV)
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLSL) THEN
      ZFPREC9(KST:KND)=ZFPREC9(KST:KND)+ZGFU(KST:KND,IFLD)
      ZFPREC0(KST:KND)=ZFPREC0(KST:KND)+PFPLSL(KST:KND,IJLEV)
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLSN) THEN
      ZFPREC9(KST:KND)=ZFPREC9(KST:KND)+ZGFU(KST:KND,IFLD)
      ZFPREC0(KST:KND)=ZFPREC0(KST:KND)+PFPLSN(KST:KND,IJLEV)
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLSG) THEN
      ZFPREC9(KST:KND)=ZFPREC9(KST:KND)+ZGFU(KST:KND,IFLD)
      ZFPREC0(KST:KND)=ZFPREC0(KST:KND)+PFPLSG(KST:KND,IJLEV)
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLSH) THEN
      ZFPREC9(KST:KND)=ZFPREC9(KST:KND)+ZGFU(KST:KND,IFLD)
      ZFPREC0(KST:KND)=ZFPREC0(KST:KND)+PFPLSH(KST:KND,IJLEV)
    ENDIF

    IOFF=IOFF+TYPE_CFU(JF)%ILEV
  ENDDO
  ZSQPRE(KST:KND)=(ZFPREC0(KST:KND)**2)*TSTEP
  ZFPREC0(KST:KND)=ZFPREC0(KST:KND)*TSTEP
ENDIF

!     ------------------------------------------------------------------

!*    2.    ACCUMULATE FLUXES.
!           ------------------

IOFF=0
DO JF=1,NTYPCFU
  IADD=1+IOFF
  DO JLEV=1,TYPE_CFU(JF)%ILEV

    IFLD=JLEV+IOFF
    IJLEV=TYPE_CFU(JF)%INUMLEV(JLEV)

    IF (IADD == YDCFU%YCFUPT%MSTRDU) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PSTRDU(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MSTRDV) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PSTRDV(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MSTRCU) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PSTRCU(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MSTRCV) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PSTRCV(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFDICQ) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PDIFCQ(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFDICS) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PDIFCS(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MSTRTU) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PSTRTU(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MSTRTV) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PSTRTV(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFDITQ) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PDIFTQ(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFDITS) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PDIFTS(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLCL) THEN
      IF (.NOT.LCORWAT)&
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFPLCL(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFCCQL) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFCCQL(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLCN) THEN
      IF (.NOT.LCORWAT)&
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFPLCN(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLCG) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFPLCG(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLCH) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFPLCH(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFCCQN) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFCCQN(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLSL) THEN
      IF (.NOT.LCORWAT)&
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFPLSL(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFCSQL) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFCSQL(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLSN) THEN
      IF (.NOT.LCORWAT)&
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFPLSN(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLSG) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFPLSG(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFPLSH) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFPLSH(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFCSQN) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFCSQN(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFRSO) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRSO(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFRTH) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRTH(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFNEB) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PNEB(KST:KND,IJLEV)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFNEBT) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PCLCT(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFCLL) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFCLL(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFCLN) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFCLN(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFEVL) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFEVL(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFEVN) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFEVN(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFONTE) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFONTE(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFCHSP) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFCHSP(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFLWSP) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFLWSP(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MRUISS) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PRUISS(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MRUISP) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PRUISP(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFEVV) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFEVV(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFTR) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFTR(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MRUISL) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PRUISL(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFGEL) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFGEL(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFGELS) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFGELS(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFCS) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFCS(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MWS) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PWS(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MSNS) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PSNS(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MSPRES) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PRES(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFCL) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+&
       & (PFCLL(KST:KND)+PFCLN(KST:KND))*TSTEP  
    ELSEIF (IADD == YDCFU%YCFUPT%MFDISH) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFDIS(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFTOPH) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRMH(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MQTOT) THEN
      DO JNIV=1,NFLEVG
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PQ(KST:KND,JNIV)&
         & *PDELP(KST:KND,JNIV)/RG*TSTEP  
      ENDDO
    ELSEIF (IADD == YDCFU%YCFUPT%MQICE) THEN
      DO JNIV=1,NFLEVG
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PQICE(KST:KND,JNIV)&
         & *PDELP(KST:KND,JNIV)/RG*TSTEP  
      ENDDO
    ELSEIF (IADD == YDCFU%YCFUPT%MQLI) THEN
      DO JNIV=1,NFLEVG
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PQLI(KST:KND,JNIV)&
         & *PDELP(KST:KND,JNIV)/RG*TSTEP  
      ENDDO
    ELSEIF (IADD == YDCFU%YCFUPT%MOZONT) THEN
      DO JNIV=1,NFLEVG
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PO3(KST:KND,JNIV)&
         & *PDELP(KST:KND,JNIV)/RG*TSTEP  
      ENDDO
    ELSEIF (IADD == YDCFU%YCFUPT%MFRSODS) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRSODS(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFRSDNI) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRSDNI(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFRSGNI) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRSGNI(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFRSOPS) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRSOPS(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFRSOPT) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRSOPT(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFRTHDS) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRTHDS(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFRSOLU) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRSOLU(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MNEBCON) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PCLCC(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MNEBHAU) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PCLCH(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MNEBMOY) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PCLCM(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MNEBBAS) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PCLCL(KST:KND)*TSTEP
    ELSEIF (IADD == YDCFU%YCFUPT%MFRSOC0) THEN
      IF (MOD(NSTEP,NFRRC) == 0) THEN
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRSOC(KST:KND,0)*TSTEP*NFRRC
      ENDIF
    ELSEIF (IADD == YDCFU%YCFUPT%MFRSOC1) THEN
      IF (MOD(NSTEP,NFRRC) == 0) THEN
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRSOC(KST:KND,1)*TSTEP*NFRRC
      ENDIF
    ELSEIF (IADD == YDCFU%YCFUPT%MFRTHC0) THEN
      IF (MOD(NSTEP,NFRRC) == 0) THEN
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRTHC(KST:KND,0)*TSTEP*NFRRC
      ENDIF
    ELSEIF (IADD == YDCFU%YCFUPT%MFRTHC1) THEN
      IF (MOD(NSTEP,NFRRC) == 0) THEN
        ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFRTHC(KST:KND,1)*TSTEP*NFRRC
      ENDIF
    ELSEIF (IADD == YDCFU%YCFUPT%MFLASH) THEN
      ZGFU(KST:KND,IFLD)=ZGFU(KST:KND,IFLD)+PFLASH(KST:KND)*TSTEP    
    ELSEIF (IADD == YDCFU%YCFUPT%MFDUTP) THEN
      DO JI=KST,KND
        IF (ZFPREC9(JI) > ZEPS) THEN
          ZGFU(JI,IFLD)=ZGFU(JI,IFLD)*((ZFPREC9(JI)+ZFPREC0(JI))**2)&
           & /((ZFPREC9(JI)**2)+(ZGFU(JI,IFLD)*ZSQPRE(JI)))  
        ELSEIF (ZFPREC0(JI) > ZEPS) THEN
          ZGFU(JI,IFLD)=TSTEP
        ELSE
          ZGFU(JI,IFLD)=0.0_JPRB
        ENDIF
      ENDDO
    ELSE
      CALL ABOR1('CPCFU : ERROR IN POINTERS') 
    ENDIF

  ENDDO
  IOFF=IOFF+TYPE_CFU(JF)%ILEV
ENDDO

!     ------------------------------------------------------------------

!*       3.    WRITE OUT ACC. FIELDS .
!              -----------------------

!*    3.1   WRITE OUT FIELDS

GFUBUF (:, :, 1+(KSTGLO-1)/YDGEOMETRY%YRDIM%NPROMA) = ZGFU


!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('CPCFU',1,ZHOOK_HANDLE)
END SUBROUTINE CPCFU
