! (C) Copyright 1989- Meteo-France.

SUBROUTINE CPCUDDH_OMP(YDMDDH,YDTDDH,KPROMA,KSTART,KPROF,KFLEVG,KDDHI,YDDDH,LDDYN)
!****
!     ------------------------------------------------------------------

!     MOYENNES HORIZONTALES ET CUMULS SUR DOMAINES INTERNES
!     DIAGNOSTICS PAR DOMAINES HORIZONTAUX
!     ------------------------------------

USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMMP0   , ONLY : MYPROC
USE YOMLUN   , ONLY : NULOUT
USE YOMCT3   , ONLY : NSTEP
USE YOMMDDH  , ONLY : TMDDH
USE YOMTDDH  , ONLY : TTDDH
USE OML_MOD  , ONLY : OML_MY_THREAD
USE DDH_MIX  , ONLY : TYP_DDH

IMPLICIT NONE

TYPE(TMDDH)       ,INTENT(INOUT) :: YDMDDH
TYPE(TTDDH)       ,INTENT(INOUT) :: YDTDDH
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROMA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTART 
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROF 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEVG 
INTEGER(KIND=JPIM),INTENT(IN)    :: KDDHI(KPROMA) 
TYPE(TYP_DDH)     ,INTENT(INOUT) :: YDDDH 
LOGICAL           ,INTENT(IN)    :: LDDYN  
!     ------------------------------------------------------------------

INTEGER(KIND=JPIM) :: JFLD, JROF ,ITHREAD, IPLEND, IPLST, IFIELD, JDOM
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
LOGICAL :: LLSAME

!*    SECURITES DIMENSIONS

ASSOCIATE(HDCS0=>YDTDDH%HDCS0, HDCS1=>YDTDDH%HDCS1, HDCVB0=>YDTDDH%HDCVB0, &
 & HDCVB1=>YDTDDH%HDCVB1,NFIELDSMAX=>YDMDDH%NFIELDSMAX,NDHIDH=>YDMDDH%NDHIDH)
IF (LHOOK) CALL DR_HOOK('CPCUDDH_OMP',0,ZHOOK_HANDLE)

ITHREAD=OML_MY_THREAD()

IF ( NSTEP == 1 ) THEN
  !variables at initial time
  DO JFLD = 1, YDDDH%NFIELDS3D
    IF ( YDDDH%YFIELD3D(JFLD)%CTYPE=='V' ) THEN
      IPLST =(1+KFLEVG)*(YDDDH%NFIELDS3D_OFFSET+JFLD-1)+1
      IPLEND=(1+KFLEVG)*(YDDDH%NFIELDS3D_OFFSET+JFLD)
      DO JDOM = 1,NDHIDH
        HDCVB0(IPLST:IPLEND,JDOM,ITHREAD) = HDCVB0(IPLST:IPLEND,JDOM,ITHREAD)&
         & + YDDDH%YFIELD3D(JFLD)%RVAL(:,JDOM)
      ENDDO
    ENDIF
  ENDDO
ENDIF

! var/flux/tendencies at time t
DO JFLD = 1,YDDDH%NFIELDS3D
  IPLST =(1+KFLEVG)*(YDDDH%NFIELDS3D_OFFSET+JFLD-1)+1
  IPLEND=(1+KFLEVG)*(YDDDH%NFIELDS3D_OFFSET+JFLD)
  DO JDOM = 1,NDHIDH
    HDCVB1(IPLST:IPLEND,JDOM,ITHREAD) = HDCVB1(IPLST:IPLEND,JDOM,ITHREAD)&
     & + YDDDH%YFIELD3D(JFLD)%RVAL(:,JDOM)
  ENDDO
ENDDO

!     ------------------------------------------------------------------

! surface fields

IF ( NSTEP == 1 ) THEN
  !variables at initial time
  DO JFLD = 1, YDDDH%NFIELDS2D
    IF ( YDDDH%YFIELD2D(JFLD)%CTYPE=='V' ) THEN
      DO JDOM = 1,NDHIDH
        HDCS0(YDDDH%NFIELDS2D_OFFSET+JFLD,JDOM,ITHREAD) = HDCS0(YDDDH%NFIELDS2D_OFFSET+JFLD,JDOM,ITHREAD)&
         & + YDDDH%YFIELD2D(JFLD)%RVAL(JDOM)
      ENDDO
    ENDIF
  ENDDO
ENDIF

! var/flux/tendencies at time t
DO JFLD = 1,YDDDH%NFIELDS2D
  DO JDOM = 1,NDHIDH
    HDCS1(YDDDH%NFIELDS2D_OFFSET+JFLD,JDOM,ITHREAD) = HDCS1(YDDDH%NFIELDS2D_OFFSET+JFLD,JDOM,ITHREAD)&
     & + YDDDH%YFIELD2D(JFLD)%RVAL(JDOM)
  ENDDO
ENDDO


IF (LHOOK) CALL DR_HOOK('CPCUDDH_OMP',1,ZHOOK_HANDLE)
END ASSOCIATE
END SUBROUTINE CPCUDDH_OMP
