! (C) Copyright 1989- Meteo-France.

#ifdef RS6K
@PROCESS NOCHECK
#endif
SUBROUTINE CPDYDDHLAG(&
 ! --- INPUT ----------------------------------------------------------
 & YDGEOMETRY, YDML_DIAG,YDML_GCONF,LDNHDYN,KST,KEND,KSTGLO, KITER, &
 ! --- INOUT ----------------------------------------------------------
 & PGMVTNDSL,PGFLTNDSL,YDDDH)

!**** *CPDYDDHLAG    -  DDH calculations for some adiabatic terms: lagged part.

!     Purpose.
!     --------

!**   Interface.
!     ----------
!        *CALL* *CPDYDDHLAG(......)

!        Explicit arguments :
!        --------------------

!        INPUT:
!          KST         - first element where computations are performed.
!          KEND        - depth of work.
!          KSTGLO      - 

!        INOUT:
!          PGMVTNDSL   - cf. GMVTNDSL_DDH in YOMGPDDH
!          PGFLTNDSL   - cf. GFLTNDSL_DDH in YOMGPDDH

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------

!     Reference.
!     ----------

!     Author.
!     -------
!      F. VOITUS,
!     ------------------------------------------------------------------

USE MODEL_DIAGNOSTICS_MOD  , ONLY : MODEL_DIAGNOSTICS_TYPE
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD           , ONLY : GEOMETRY
USE PARKIND1               , ONLY : JPIM, JPRB
USE YOMHOOK                , ONLY : LHOOK, DR_HOOK, JPHOOK
USE DDH_MIX                , ONLY : ADD_FIELD_3D, NTOTFIELD, RDDH_FIELD,&
 &                                  RDDHSURF_FIELD, NTOTFSL, RDDH_DESCR, NEW_ADD_FIELD_3D, CLEANDDH, SETDDH, &
 &                                  TYP_DDH

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)               ,INTENT(IN)    :: YDGEOMETRY
TYPE(MODEL_DIAGNOSTICS_TYPE) ,INTENT(INOUT) :: YDML_DIAG
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN)    :: YDML_GCONF
LOGICAL           ,INTENT(IN)    :: LDNHDYN
INTEGER(KIND=JPIM),INTENT(IN)    :: KST
INTEGER(KIND=JPIM),INTENT(IN)    :: KEND
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTGLO
INTEGER(KIND=JPIM),INTENT(IN)    :: KITER
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGMVTNDSL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,2+YDML_GCONF%YRDIMF%NFTHER)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGFLTNDSL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDML_GCONF%YGFL%NUMFLDS)
TYPE(TYP_DDH)     ,INTENT(INOUT) :: YDDDH

!     ------------------------------------------------------------------

INTEGER(KIND=JPIM) :: IPLEND, IFLD, JROF
INTEGER(KIND=JPIM) :: IDDHI(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZDHSF(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZTMPAF(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG),&
 & ZTMPFF(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG+1)
REAL(KIND=JPRB), TARGET :: ZAUX3D(0:YDGEOMETRY%YRDIMV%NFLEVG,YDML_DIAG%YRMDDH%NDHIDH,YDDDH%NFIELDS3D_AUTO)
REAL(KIND=JPRB), TARGET :: ZAUX2D(YDML_DIAG%YRMDDH%NDHIDH,YDDDH%NFIELDS2D_AUTO)
REAL(KIND=JPRB), TARGET :: ZAUXSM(YDGEOMETRY%YRDIM%NPROMA,1,YDGEOMETRY%YRDIMV%NFLEVG,13)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "cpcuddh.intfb.h"
#include "cpcuddh_omp.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('CPDYDDHLAG',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP, &
  & YDMDDH=>YDML_DIAG%YRMDDH,YDLDDH=>YDML_DIAG%YRLDDH,YGFL=>YDML_GCONF%YGFL,YDDIMF=>YDML_GCONF%YRDIMF)
ASSOCIATE(NUMFLDS=>YGFL%NUMFLDS, &
 & NPROMA=>YDDIM%NPROMA, &
 & NFTHER=>YDDIMF%NFTHER, &
 & NFLEVG=>YDDIMV%NFLEVG, &
 & LFLEXDIA=>YDLDDH%LFLEXDIA, LDDH_OMP=>YDLDDH%LDDH_OMP,&
 & HDSF=>YDMDDH%HDSF, MSLDDH_PD=>YDMDDH%MSLDDH_PD, MSLDDH_T=>YDMDDH%MSLDDH_T, &
 & MSLDDH_U=>YDMDDH%MSLDDH_U, MSLDDH_V=>YDMDDH%MSLDDH_V, &
 & MSLDDH_VD=>YDMDDH%MSLDDH_VD, NDDHI=>YDMDDH%NDDHI)
!     ------------------------------------------------------------------

DO JROF=KST,KEND
  IDDHI(JROF)=NDDHI(JROF+KSTGLO-1)
  ZDHSF(JROF)=HDSF(JROF+KSTGLO-1)
ENDDO

ZTMPAF(:,:)=0.0
ZTMPFF(:,:)=0.0
ZAUXSM(:,:,:,:)=0.0

!     ------------------------------------------------------------------


IF (LFLEXDIA) THEN
  IF (LDDH_OMP) THEN

    CALL SETDDH(YDMDDH,YDDDH,KST,KEND,NPROMA,NFLEVG,KITER,ZDHSF,IDDHI,ZAUX3D,ZAUX2D,ZAUXSM)
 
    IF (KITER == 0) THEN
      ZTMPAF(KST:KEND,1:NFLEVG)=PGMVTNDSL(KST:KEND,1:NFLEVG,MSLDDH_U)
      CALL NEW_ADD_FIELD_3D(YDMDDH,ZTMPAF,'TSLUADV',YDDDH)
      ZTMPAF(KST:KEND,1:NFLEVG)=PGMVTNDSL(KST:KEND,1:NFLEVG,MSLDDH_V)
      CALL NEW_ADD_FIELD_3D(YDMDDH,ZTMPAF,'TSLVADV',YDDDH)
      IF (NFTHER > 0) THEN
        ZTMPAF(KST:KEND,1:NFLEVG)=PGMVTNDSL(KST:KEND,1:NFLEVG,MSLDDH_T)
        CALL NEW_ADD_FIELD_3D(YDMDDH,ZTMPAF,'TSLTADV',YDDDH)
      ENDIF
      IF (LDNHDYN) THEN
        ZTMPAF(KST:KEND,1:NFLEVG)=PGMVTNDSL(KST:KEND,1:NFLEVG,MSLDDH_PD)
        CALL NEW_ADD_FIELD_3D(YDMDDH,ZTMPAF,'TSLPDADV',YDDDH)
        ZTMPAF(KST:KEND,1:NFLEVG)=PGMVTNDSL(KST:KEND,1:NFLEVG,MSLDDH_VD)
        CALL NEW_ADD_FIELD_3D(YDMDDH,ZTMPAF,'TSLVDADV',YDDDH)
      ENDIF
    ENDIF 
  ELSE
    IF (KITER == 0) THEN
      IPLEND=NTOTFIELD-NTOTFSL
      DO IFLD=1,IPLEND
        CALL ADD_FIELD_3D(YDLDDH,ZTMPFF,RDDH_DESCR(IFLD)%CNAME,RDDH_DESCR(IFLD)%CFLUX,&
         & RDDH_DESCR(IFLD)%CMOD,.TRUE.,RDDH_DESCR(IFLD)%LKDDH)
      ENDDO
      ZTMPAF(KST:KEND,1:NFLEVG)=PGMVTNDSL(KST:KEND,1:NFLEVG,MSLDDH_U)
      CALL ADD_FIELD_3D(YDLDDH,ZTMPAF,'TSLUADV','T','ARP',.TRUE.,.TRUE.)
      ZTMPAF(KST:KEND,1:NFLEVG)=PGMVTNDSL(KST:KEND,1:NFLEVG,MSLDDH_V)
      CALL ADD_FIELD_3D(YDLDDH,ZTMPAF,'TSLVADV','T','ARP',.TRUE.,.TRUE.)
      IF (NFTHER > 0) THEN
        ZTMPAF(KST:KEND,1:NFLEVG)=PGMVTNDSL(KST:KEND,1:NFLEVG,MSLDDH_T)
        CALL ADD_FIELD_3D(YDLDDH,ZTMPAF,'TSLTADV','T','ARP',.TRUE.,.TRUE.)
      ENDIF
      IF (LDNHDYN) THEN
        ZTMPAF(KST:KEND,1:NFLEVG)=PGMVTNDSL(KST:KEND,1:NFLEVG,MSLDDH_PD)
        CALL ADD_FIELD_3D(YDLDDH,ZTMPAF,'TSLPDADV','T','ARP',.TRUE.,.TRUE.)
        ZTMPAF(KST:KEND,1:NFLEVG)=PGMVTNDSL(KST:KEND,1:NFLEVG,MSLDDH_VD)
        CALL ADD_FIELD_3D(YDLDDH,ZTMPAF,'TSLVDADV','T','ARP',.TRUE.,.TRUE.)
      ENDIF
    ENDIF
  ENDIF
ENDIF

IF (LFLEXDIA) THEN
 IF (LDDH_OMP) THEN
    IF (KITER == 0) CALL CPCUDDH_OMP(YDMDDH,YDML_DIAG%YRTDDH,NPROMA,KST,KEND,NFLEVG,IDDHI,YDDDH,.TRUE.)
    CALL CLEANDDH(YDML_DIAG%YRTDDH,YDDDH,KSTGLO,KITER)
  ELSE 
   IF (KITER == 0) CALL CPCUDDH(YDML_DIAG,YDML_GCONF%YRRIP,NPROMA,KST,KEND,NFLEVG,IDDHI,ZDHSF,RDDH_FIELD,RDDHSURF_FIELD,.TRUE.,.FALSE.,NTOTFIELD)
 ENDIF  
ENDIF


!     ------------------------------------------------------------------
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('CPDYDDHLAG',1,ZHOOK_HANDLE)
END SUBROUTINE CPDYDDHLAG

