! (C) Copyright 1989- Meteo-France.

SUBROUTINE CPPHDDH( &
 !     INPUT.
 & YDML_DIAG,YDEPHY,YDRIP,YDML_PHY_MF,KPROMA,KSTART,KPROF,KFLEV,LDDYN,&
 & YDGSGEOM,PUZGEO,PVMGEO,&
 & PSNS,PTP,PTS,&
 & PWP,PWS,PT0,PLSM,&
 & PDIFCQ, PDIFCS, PDIFTQ, PDIFTS, PFCQNG,&
 & PFPLCL, PFPLCN, PFPLSL, PFPLSN, PFRSO, PFRTH,&
 & PFRTHDS,PFHPCL, PFHPCN, PFHPSL, PFHPSN,&
 & PSTRCU, PSTRCV, PSTRDU, PSTRDV, PSTRTU, PSTRTV,&
 & PCT,&
 & PFCHSP, PFCLL, PFCLN, PFCS, PFEVL, PFEVN, PFLWSP,&
 & PFONTE, PRUISP, PRUISS,&
 & PENTRA, PENTRV,&
 & PDIFTQL,PDIFTQN,PDIFCQL,PDIFCQN,PFCQLNG,PFCQNNG,&
 & PFHSCL,PFHSCN,PFHSSL,PFHSSN, PFEPFP, PFCMPCQ, PFCMPSN, PFCMPSL,&
 & PFCQLF,PFCQIF,PFSQLF,PFSQIF,&
 & PFPFPL,PFPFPN,PFPFPCL,PFPFPCN,&
 & PFPEVPL,PFPEVPN,PFPEVPCL,PFPEVPCN,&
 & PFCQRNG, PFCQSNG,&
 & PHI0,PUCLS,PVCLS,PTCLS,PQCLS,PCLPH,PALB,PGZ0,PGZ0H,&
 !     OUTPUT.
 & PDHCV,PDHCS,PFTCNS)

!---------------------------------------------------------------------------
!**** *CPPHDDH*  - CALCUL DES FLUX/TENDANCES DYNAMIQUES
!                  DIAGNOSTICS PAR DOMAINES HORIZONTAUX
!---------------------------------------------------------------------------
!     BUT
!     ---
!      CALCULS PHYSIQUES POUR LES DIAGNOSTICS DDH
!      AINSI QUE DES VARIABLES AU SOL A L'INSTANT COURANT

!   ** SURVEILLER LE POSITIONNEMENT DES CHAMPS AU MOYEN DE L'INDICATEUR
!                           IDHCV

!     ARGUMENTS D ENTREE (INPUT)
!     --------------------------

! - DIMENSIONS
!     KPROMA : DIMENSION HORIZONTALE.
!     KSTART : DEBUT DE LA BOUCLE HORIZONTALE.
!     KPROF  : FIN DE LA BOUCLE HORIZONTALE.
!     KFLEV  : DIMENSION VERTICALE ET NB DE NIVEAUX

! - LOGIQUES DE CONTROLE
!     LDDYN  : activation des DDH pour la dynamique.

! - TABLEAUX DE DONNEES
!     YDGSGEOM       : structure for geographical sphere horizontal geometry.
!     PUZGEO, PVMGEO : VENT ZONAL ET MERIDIEN VRAIS GEOGRAPHIQUES
!                      (UNIQUEMENT SI LHDHKS OU LHDMCI OU LHDENT VRAIS)
!     PSNS       : MASSE PAR UNITE DE SURFACE DE LA COUCHE NEIGEUSE.
!     PTP        : TEMPERATURE EN PROFONDEUR.
!     PTS        : TEMPERATURE DE SURFACE.
!     PWP        : CONTENU EN EAU DU RESERVOIR EN PROFONDEUR.
!     PWS        : CONTENU EN EAU DU RESERVOIR DE SURFACE.
!     PT0        : TEMPERATURE A INSTANT 0 / TEMPERATURE AT TIME LEVEL 0
!     PHI0       : OROGRAPHIE (HAUTEUR GEOPOTENTIELLE "gz" A L'INSTANT t SUR LES INTERCOUCHES).
!     PLSM       : INDICE TERRE/MER.
!     PUCLS      : COMPOSANTE U DU VENT A 10 METRES (DIAGNOSTIQUE).
!     PVCLS      : COMPOSANTE V DU VENT A 10 METRES (DIAGNOSTIQUE).
!     PTCLS      : TEMPERATURE A 2 METRES (DIAGNOSTIQUE).
!     PQCLS      : HUMIDITE SPECIFIQUE A 2 METRES (DIAGNOSTIQUE).
!     PCLPH      : HAUTEUR (EN METRES) DE LA COUCHE LIMITE PLANETAIRE.
!     PALB       : ALBEDO DE SURFACE COURANT.
!     PGZ0       : G*LONGUEUR DE RUGOSITE DYNAMIQUE.
!     PGZ0H      : G*LONGUEUR DE RUGOSITE THERMIQUE.
!     PDIFCQ     : FLUX CONVECTIF D'HUMIDITE SPECIFIQUE (HORS PLUIE/NEIGE).
!     PDIFCS     : FLUX CONVECTIF D'ENTHALPIE (HORS PLUIE/NEIGE).
!     PDIFTQ     : FLUX TURBULENT (ET Q NEGATIF) D'HUMIDITE SPECIFIQUE.
!     PDIFTS     : FLUX TURBULENT D'ENTHALPIE (OU D'ENERGIE STATIQUE SECHE).
!     PFCQNG     : FLUX FICTIF D'EAU POUR CORRIGER LES Q<0.
!     PFPLCL     : PRECIPITATIONS CONVECTIVES SOUS FORME LIQUIDE.
!     PFPLCN     : PRECIPITATIONS CONVECTIVES SOUS FORME NEIGE.
!     PFPLSL     : PRECIPITATIONS STRATIFORMES SOUS FORME LIQUIDE.
!     PFPLSN     : PRECIPITATIONS STRATIFORMES SOUS FORME NEIGE.
!     PFRSO      : FLUX DE RAYONNEMENT SOLAIRE.
!     PFRTH      : FLUX DE RAYONNEMENT THERMIQUE.
!     PFRTHDS    : FLUX DE RAYONNEMENT THERMIQUE DESCENDANT A LA SURFACE.
!     PFHPCL     : FLUX ENTHALPIE CONVECTIVES SOUS FORME LIQUIDE.
!     PFHPCN     : FLUX ENTHALPIE CONVECTIVES SOUS FORME NEIGE.
!     PFHPSL     : FLUX ENTHALPIE STRATIFORMES SOUS FORME LIQUIDE.
!     PFHPSN     : FLUX ENTHALPIE STRATIFORMES SOUS FORME NEIGE.
!     PSTRCU     : FLUX CONVECTIF DE QUANTITE DE MOUVEMENT "U".
!     PSTRCV     : FLUX CONVECTIF DE QUANTITE DE MOUVEMENT "V".
!     PSTRDU     : FLUX "GRAVITY WAVE DRAG" "U".
!     PSTRDV     : FLUX "GRAVITY WAVE DRAG" "V".
!     PSTRTU     : FLUX TURBULENT DE QUANTITE DE MOUVEMENT "U".
!     PSTRTV     : FLUX TURBULENT DE QUANTITE DE MOUVEMENT "V".
!     PCT        : ???
!     PFCHSP     : FLUX DE CHALEUR DE LA SURFACE VERS LE SOL PROFOND.
!     PFCLL      : FLUX DE CHALEUR LATENTE SUR EAU LIQUIDE (OU SOL HUMIDE).
!     PFCLN      : FLUX DE CHALEUR LATENTE SUR NEIGE (OU GLACE).
!     PFCS       : FLUX DE CHALEUR SENSIBLE EN SURFACE.
!     PFEVL      : FLUX DE VAPEUR D'EAU SUR EAU LIQUIDE (OU SOL HUMIDE).
!     PFEVN      : FLUX DE VAPEUR D'EAU SUR NEIGE (OU GLACE).
!     PFLWSP     : FLUX D'EAU LIQUIDE DE LA SURFACE VERS LE SOL PROFOND.
!     PFONTE     : FLUX D'EAU CORRESPONDANT A LA FONTE DE NEIGE EN SURFACE.
!     PRUISP     : FLUX DE RUISSELLEMENT EN PROFONDEUR.
!     PRUISS     : FLUX DE RUISSELLEMENT EN SURFACE.
!     PENTRA     : ENTROPIE AIR SEC / SPECIFIC ENTROPY OF DRY AIR
!     PENTRV     : ENTROPIE VAPEUR D'EAU / SPECIFIC ENTROPY OF WATER VAPOUR
!     PDIFTQL    : FLUX D'EAU LIQUIDE TURBULENT.
!     PDIFTQN    : FLUX D'EAU NEIGEUSE TURBULENT.
!     PDIFCQL    : FLUX D'EAU LIQUIDE TURBULENT CONVECTIF.
!     PDIFCQN    : FLUX D'EAU NEIGEUSE TURBULENT CONVECTIF.
!     PFCQLNG    : FLUX D'EAU LIQUIDE DE CORR. DES VALEURS < 0.
!     PFCQNNG    : FLUX D'EAU NEIGEUSE DE CORR. DES VALEURS < 0.
!     PFHSCL     : FLUX DE CHALEUR SENSIBLE LIE AUX PRECIPITATIONS CONV. LIQ.
!     PFHSCN     : FLUX DE CHALEUR SENSIBLE LIE AUX PRECIPITATIONS CONV. NEI.
!     PFHSSL     : FLUX DE CHALEUR SENSIBLE LIE AUX PRECIPITATIONS STRA. LIQ.
!     PFHSSN     : FLUX DE CHALEUR SENSIBLE LIE AUX PRECIPITATIONS STRA. NEI.
!     PFEPFP     : PSEUDO FLUX D'ENTHALPIE LIE A L'ENERGIE PRECIPITATIONS.
!     PFCQLF     : FLUX DE CONDENSATION CONV. LIQ.
!     PFCQIF     : FLUX DE CONDENSATION CONV. NEI.
!     PFSQLF     : FLUX DE CONDENSATION STRA. LIQ.
!     PFSQIF     : FLUX DE CONDENSATION STRA. NEI.

!     ENTREES IMPLICITES
!     ------------------
!       UNITE NULOUT (/YOMLUN/)
!       CONSTANTES UNIVERSELLES, COMMON /YOMCST/
!       FONCTIONS THERMODYNAMIQUES, COMDECK *FCTTRM*

!       CONTROLE PHYSIQUE DE BASE : YOMPHY : NDPSFI
!       CONSTANTES PHYSIQUES (NORMALEMENT INUTILES)
!       YOMPHY0, YOMPHY1, YOMPHY2, YOMPHY3

!       ELEMENTS DE CONTROLE DDH
!       INDICATEURS LOGIQUES, COMMON /YOMLDDH/
!        DANS LE COMDECK * YOMMDDH * POUR LES MASQUES
!       DIMENSIONS PROPRES AUX MASQUES DIAGNOSTIQUES DDH, COMMON /DDHDIM/
!       ET DIMENSIONS POUR LES TABLEAUX DE CUMULS
!       INDICATEURS DE POSITIONS DANS LES TABLEAUX DE CUMUL

!     ARGUMENTS DE SORTIES (OUTPUT)
!     -----------------------------
!      DANS PDHCV, FLUX/TENDANCES PHYSIQUES INSTANTANEES
!      DANS PDHCS  VARIABLES ET FLUX AU SOL

!     REMARQUES SUPPLEMENTAIRES
!     -------------------------

!     ORIGINAL
!     --------
!     91-03-04, Alain Joly.

!     MODIFICATIONS
!   N. Wedi and K. Yessad (Jan 2008): different dev for NH model and PC scheme
!   08-12-18 O.Riviere Add new dataflow for DDH under key LFLEXDIA
!   K. Yessad (Dec 2008): remove dummy CDLOCK + cleanings
!   K. Yessad (Jan 2011): introduce INTDYN_MOD structures.
!   K. Yessad (Dec 2011): use YDGSGEOM.
!   T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!   K. Yessad (July 2014): Move some variables.
!   R. El Khatib 02-May-2016 Optimizations (make use of memcpy)
!   K. Yessad (Feb 2018): remove deep-layer formulations.
!   R. El Khatib 05-Feb-2018 Fix uninitialized variables
!   R. Brozkova (Sep 2018): fix of swapped convective and resolved
!                           precipitation enthalpy
!   M. Hrastinski (Sep-2019): TKE and TTE phys. fluxes for ALARO DDH (PFTCNS)
!-------------------------------------------------------------------------------

USE MODEL_DIAGNOSTICS_MOD , ONLY : MODEL_DIAGNOSTICS_TYPE
USE MODEL_PHYSICS_MF_MOD  , ONLY : MODEL_PHYSICS_MF_TYPE
USE PARKIND1              , ONLY : JPIM, JPRB
USE YOMHOOK               , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMRIP0               , ONLY : NSSSSS
USE YOMRIP                , ONLY : TRIP
USE YOMCST                , ONLY : ROMEGA, RA, RG, RCW, RCS, RCPD, RCPV, RLMLT
USE YOEPHY                , ONLY : TEPHY
USE YOMGSGEOM             , ONLY : TGSGEOM

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(TEPHY)       ,INTENT(IN)    :: YDEPHY
TYPE(MODEL_DIAGNOSTICS_TYPE),INTENT(INOUT) :: YDML_DIAG
TYPE(MODEL_PHYSICS_MF_TYPE) ,INTENT(IN)    :: YDML_PHY_MF
TYPE(TRIP)        ,INTENT(IN)    :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROMA 
INTEGER(KIND=JPIM),INTENT(IN)    :: KFLEV 
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTART 
INTEGER(KIND=JPIM),INTENT(IN)    :: KPROF 
LOGICAL           ,INTENT(IN)    :: LDDYN 
TYPE(TGSGEOM)     ,INTENT(IN)    :: YDGSGEOM
REAL(KIND=JPRB)   ,INTENT(IN)    :: PUZGEO(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVMGEO(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSNS(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTP(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTS(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWP(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWS(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PT0(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PLSM(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFCQ(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFCS(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFTQ(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFTS(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCQNG(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLCL(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLCN(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLSL(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLSN(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRSO(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRTH(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRTHDS(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFHPCL(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFHPCN(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFHPSL(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFHPSN(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRCU(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRCV(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRDU(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRDV(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRTU(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRTV(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCT(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCHSP(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCLL(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCLN(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCS(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFEVL(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFEVN(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFLWSP(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFONTE(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRUISP(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRUISS(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PENTRA(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PENTRV(KPROMA,KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFTQL(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFTQN(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFCQL(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFCQN(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCQLNG(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCQNNG(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFHSCL(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFHSCN(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFHSSL(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFHSSN(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFEPFP(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCMPCQ(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCMPSN(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCMPSL(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCQLF(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCQIF(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFSQLF(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFSQIF(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPFPL(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPFPN(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPFPCL(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPFPCN(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPEVPL(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPEVPN(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPEVPCL(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPEVPCN(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCQRNG(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCQSNG(KPROMA,0:KFLEV)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PHI0(KPROMA,0:KFLEV) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PUCLS(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVCLS(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PTCLS(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQCLS(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLPH(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PALB(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGZ0(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PGZ0H(KPROMA) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PDHCV(KPROMA,0:KFLEV,YDML_DIAG%YRMDDH%NDHCVSU) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PDHCS(KPROMA,YDML_DIAG%YRMDDH%NDHCSSU) 
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PFTCNS(KPROMA,0:KFLEV,6)

!     ------------------------------------------------------------------
REAL(KIND=JPRB) :: ZCLON(KPROMA), ZSLON(KPROMA)
REAL(KIND=JPRB) :: ZFPLL ! ZFPLL : FLUX DE PRECIPITATIONS LIQUIDES
REAL(KIND=JPRB) :: ZFPLN ! ZFPLN : FLUX DE PRECIPITATIONS SOLIDES
!   FLUX DE QTE DE MVT TURBULENTS DANS LE REPERE LOCAL GEOGRAPHIQUE
REAL(KIND=JPRB) :: ZSTTUG(KPROMA,0:KFLEV), ZSTTVG(KPROMA,0:KFLEV)
!   FLUX DE QTE DE MVT CONVECTIFS DANS LE REPERE LOCAL GEOGRAPHIQUE
REAL(KIND=JPRB) :: ZSTCUG(KPROMA,0:KFLEV), ZSTCVG(KPROMA,0:KFLEV)
!   FLUX DE QTE DE MVT ONDES OROG.DANS LE REPERE LOCAL GEOGRAPHIQUE
REAL(KIND=JPRB) :: ZSTDUG(KPROMA,0:KFLEV), ZSTDVG(KPROMA,0:KFLEV)
!   PSEUDO-RAYON "rs" SUR LES INTERCOUCHES:
REAL(KIND=JPRB) :: ZRS
!   INDICE TERRE-MER * (rs/a)**2
REAL(KIND=JPRB) :: ZLSM, ZNORDM(KPROMA), ZNORDL(KPROMA)

INTEGER(KIND=JPIM) :: IDHCV, IDH, JLEV, JROF

REAL(KIND=JPRB) :: ZDISKC, ZDISKD, ZDISKT, ZDPSFI, ZUSRG, &
 & ZEPS, ZFHSSL, ZFHSSN, ZFHSCL, ZFHSCN
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('CPPHDDH',0,ZHOOK_HANDLE)
ASSOCIATE(LEPHYS=>YDEPHY%LEPHYS, &
 & LHDENT=>YDML_DIAG%YRLDDH%LHDENT, LHDHKS=>YDML_DIAG%YRLDDH%LHDHKS, LHDLIST=>YDML_DIAG%YRLDDH%LHDLIST, &
 & LHDMCI=>YDML_DIAG%YRLDDH%LHDMCI, &
 & NDHAHKP=>YDML_DIAG%YRMDDH%NDHAHKP, NDHAVP=>YDML_DIAG%YRMDDH%NDHAVP, NDHBHKP=>YDML_DIAG%YRMDDH%NDHBHKP, &
 & NDHBMCP=>YDML_DIAG%YRMDDH%NDHBMCP, NDHCSSU=>YDML_DIAG%YRMDDH%NDHCSSU, NDHCVSU=>YDML_DIAG%YRMDDH%NDHCVSU, &
 & NDHFSD=>YDML_DIAG%YRMDDH%NDHFSD, NDHFSP=>YDML_DIAG%YRMDDH%NDHFSP, NDHFVD=>YDML_DIAG%YRMDDH%NDHFVD, &
 & NDHVFS=>YDML_DIAG%YRMDDH%NDHVFS, NDHVS=>YDML_DIAG%YRMDDH%NDHVS, NDHVV=>YDML_DIAG%YRMDDH%NDHVV, &
 & RSTATI=>YDRIP%RSTATI, &
 & LHDQLN=>YDML_DIAG%YRSDDH%LHDQLN, &
 & LMSE=>YDML_PHY_MF%YRARPHY%LMSE, L3MT=>YDML_PHY_MF%YRPHY%L3MT, LCONDWT=>YDML_PHY_MF%YRPHY%LCONDWT, &
 & LGPCMT=>YDML_PHY_MF%YRPHY%LGPCMT, LPROCLD=>YDML_PHY_MF%YRPHY%LPROCLD, LSTRAPRO=>YDML_PHY_MF%YRPHY%LSTRAPRO, &
 & NDPSFI=>YDML_PHY_MF%YRPHY%NDPSFI, RTINER=>YDML_PHY_MF%YRPHY1%RTINER, &
 & LPTKE=>YDML_PHY_MF%YRPHY%LPTKE, LCOEFK_PTTE=>YDML_PHY_MF%YRPHY%LCOEFK_PTTE)
!     ------------------------------------------------------------------
!**   1.- INITIALISATIONS DIVERSES

ZUSRG = 1.0_JPRB/RG
ZDPSFI = REAL(NDPSFI,JPRB)
ZEPS = 1.E-4_JPRB
IDHCV=0

ZNORDM(KSTART:KPROF)=YDGSGEOM%GNORDM(KSTART:KPROF)
ZNORDL(KSTART:KPROF)=YDGSGEOM%GNORDL(KSTART:KPROF)
DO JLEV = 0, KFLEV
  DO JROF=KSTART,KPROF
    ZSTTUG(JROF,JLEV) = ZNORDM(JROF)*PSTRTU(JROF,JLEV)-ZNORDL(JROF)*PSTRTV(JROF,JLEV)  
    ZSTTVG(JROF,JLEV) = ZNORDL(JROF)*PSTRTU(JROF,JLEV)+ZNORDM(JROF)*PSTRTV(JROF,JLEV)  
    ZSTCUG(JROF,JLEV) = ZNORDM(JROF)*PSTRCU(JROF,JLEV)-ZNORDL(JROF)*PSTRCV(JROF,JLEV)  
    ZSTCVG(JROF,JLEV) = ZNORDL(JROF)*PSTRCU(JROF,JLEV)+ZNORDM(JROF)*PSTRCV(JROF,JLEV)  
    ZSTDUG(JROF,JLEV) = ZNORDM(JROF)*PSTRDU(JROF,JLEV)-ZNORDL(JROF)*PSTRDV(JROF,JLEV)  
    ZSTDVG(JROF,JLEV) = ZNORDL(JROF)*PSTRDU(JROF,JLEV)+ZNORDM(JROF)*PSTRDV(JROF,JLEV)  
  ENDDO
ENDDO

!     ------------------------------------------------------------------
!**   2.- CALCUL DES FLUX PHYSIQUES

IF ( LHDHKS ) THEN
  IF(LDDYN) THEN
    IDHCV=NDHVV+NDHFVD
  ELSE
    IDHCV=0
  ENDIF
  IDH=IDHCV
  
  DO JLEV = 0, KFLEV
    DO JROF=KSTART,KPROF
!     FPPSUMFPL
      ZFPLL = PFPLCL(JROF,JLEV) + PFPLSL(JROF,JLEV)
      ZFPLN = PFPLCN(JROF,JLEV) + PFPLSN(JROF,JLEV)
      PDHCV(JROF,JLEV,IDH+1) = ZDPSFI*(ZFPLL+ZFPLN)
    ENDDO  
!   FQVTUR
    PDHCV(KSTART:KPROF,JLEV,IDH+2) = PDIFTQ(KSTART:KPROF,JLEV)
!   FQVTURCONV
    PDHCV(KSTART:KPROF,JLEV,IDH+3) = PDIFCQ(KSTART:KPROF,JLEV)
!   FQVPRECISTL
    PDHCV(KSTART:KPROF,JLEV,IDH+4) = PFPLSL(KSTART:KPROF,JLEV)
!   FQVPRECISTN
    PDHCV(KSTART:KPROF,JLEV,IDH+5) = PFPLSN(KSTART:KPROF,JLEV)
!   FQVPRECICOL
    PDHCV(KSTART:KPROF,JLEV,IDH+6) = PFPLCL(KSTART:KPROF,JLEV)
!   FQVPRECICON
    PDHCV(KSTART:KPROF,JLEV,IDH+7) = PFPLCN(KSTART:KPROF,JLEV)
!   FQVTURQNEGAT
    PDHCV(KSTART:KPROF,JLEV,IDH+8) = PFCQNG(KSTART:KPROF,JLEV)
!   FUUTUR
!   FVVTUR
    PDHCV(KSTART:KPROF,JLEV,IDH+9) = ZSTTUG(KSTART:KPROF,JLEV)
    PDHCV(KSTART:KPROF,JLEV,IDH+10) = ZSTTVG(KSTART:KPROF,JLEV)
!   FUUTURCONV
!   FVVTURCONV
    PDHCV(KSTART:KPROF,JLEV,IDH+11) = ZSTCUG(KSTART:KPROF,JLEV)
    PDHCV(KSTART:KPROF,JLEV,IDH+12) = ZSTCVG(KSTART:KPROF,JLEV)
!   FUUONDEGREL
!   FVVONDEGREL
    PDHCV(KSTART:KPROF,JLEV,IDH+13) = ZSTDUG(KSTART:KPROF,JLEV)
    PDHCV(KSTART:KPROF,JLEV,IDH+14) = ZSTDVG(KSTART:KPROF,JLEV)
!   FCTTUR
    PDHCV(KSTART:KPROF,JLEV,IDH+15) = PDIFTS(KSTART:KPROF,JLEV)
!   FCTTURCONV
    PDHCV(KSTART:KPROF,JLEV,IDH+16) = PDIFCS(KSTART:KPROF,JLEV)
!   FCTRAYSOL1
    PDHCV(KSTART:KPROF,JLEV,IDH+17) = PFRSO(KSTART:KPROF,JLEV)
!   FCTRAYTER1
    PDHCV(KSTART:KPROF,JLEV,IDH+18) = PFRTH(KSTART:KPROF,JLEV)
  ENDDO

  IF  ( L3MT.OR.LSTRAPRO )  THEN
!   This is ALARO!      
    IF (NDPSFI==1) THEN
      DO JLEV = 0, KFLEV
        DO JROF=KSTART,KPROF
          ZFHSSL = (RCPD/RCW)*PFHSSL(JROF,JLEV)
          ZFHSSN = (RCPD/RCS)*PFHSSN(JROF,JLEV)
          ZFHSCL = (RCPD/RCW)*PFHSCL(JROF,JLEV)
          ZFHSCN = (RCPD/RCS)*PFHSCN(JROF,JLEV)
!         FCTPRECISTL
          PDHCV(JROF,JLEV,IDH+19) = PFHSSL(JROF,JLEV)-ZFHSSL
!         FCTPRECISTN
          PDHCV(JROF,JLEV,IDH+20) = PFHSSN(JROF,JLEV)-ZFHSSN
!         FCTPRECICOL
          PDHCV(JROF,JLEV,IDH+21) = PFHSCL(JROF,JLEV)-ZFHSCL
!         FCTPRECICON
          PDHCV(JROF,JLEV,IDH+22) = PFHSCN(JROF,JLEV)-ZFHSCN
!         FCTCMP 
          IDH=IDH+1
          PDHCV(JROF,JLEV,IDH+22)=ZFHSSL+ZFHSSN+ZFHSCL+ZFHSCN+PFEPFP(JROF,JLEV)
!         FQVCMPC
          IDH=IDH+1
          PDHCV(JROF,JLEV,IDH+22) = PFCMPCQ(JROF,JLEV)
        ENDDO  
      ENDDO
    ELSE
      DO JLEV = 0, KFLEV
!       FCTPRECISTL
        PDHCV(KSTART:KPROF,JLEV,IDH+19) = PFHSSL(KSTART:KPROF,JLEV)
!       FCTPRECISTN
        PDHCV(KSTART:KPROF,JLEV,IDH+20) = PFHSSN(KSTART:KPROF,JLEV)
!       FCTPRECICOL
        PDHCV(KSTART:KPROF,JLEV,IDH+21) = PFHSCL(KSTART:KPROF,JLEV)
!       FCTPRECICON
        PDHCV(KSTART:KPROF,JLEV,IDH+22) = PFHSCN(KSTART:KPROF,JLEV)
      ENDDO
    ENDIF
    DO JLEV = 0, KFLEV
!     FCTPRECCSSTL
      PDHCV(KSTART:KPROF,JLEV,IDH+23) = PFHPSL(KSTART:KPROF,JLEV)
!     FCTPRECCSSTN
      PDHCV(KSTART:KPROF,JLEV,IDH+24) = PFHPSN(KSTART:KPROF,JLEV)
!     FCTPRECCSCOL
      PDHCV(KSTART:KPROF,JLEV,IDH+25) = PFHPCL(KSTART:KPROF,JLEV)
!     FCTPRECCSCON
      PDHCV(KSTART:KPROF,JLEV,IDH+26) = PFHPCN(KSTART:KPROF,JLEV)
    ENDDO
  ELSE
    DO JLEV = 0, KFLEV
!     FCTPRECISTL
      PDHCV(KSTART:KPROF,JLEV,IDH+19) = PFHPSL(KSTART:KPROF,JLEV)
!     FCTPRECISTN
      PDHCV(KSTART:KPROF,JLEV,IDH+20) = PFHPSN(KSTART:KPROF,JLEV)
!     FCTPRECICOL
      PDHCV(KSTART:KPROF,JLEV,IDH+21) = PFHPCL(KSTART:KPROF,JLEV)
!     FCTPRECICON
      PDHCV(KSTART:KPROF,JLEV,IDH+22) = PFHPCN(KSTART:KPROF,JLEV)
!     FCTPRECCSCOL
      PDHCV(KSTART:KPROF,JLEV,IDH+23) = PFHSCL(KSTART:KPROF,JLEV)
!     FCTPRECCSCON
      PDHCV(KSTART:KPROF,JLEV,IDH+24) = PFHSCN(KSTART:KPROF,JLEV)
!     FCTPRECCSSTL
      PDHCV(KSTART:KPROF,JLEV,IDH+25) = PFHSSL(KSTART:KPROF,JLEV)
!     FCTPRECCSSTN
      PDHCV(KSTART:KPROF,JLEV,IDH+26) = PFHSSN(KSTART:KPROF,JLEV)
    ENDDO
  ENDIF
  IF(LHDQLN) THEN
    DO JLEV = 0, KFLEV
!     FQLTUR
      PDHCV(KSTART:KPROF,JLEV,IDH+27) = PDIFTQL(KSTART:KPROF,JLEV)
!     FQNTUR
      PDHCV(KSTART:KPROF,JLEV,IDH+28) = PDIFTQN(KSTART:KPROF,JLEV)
!     FQLTURCONV
      PDHCV(KSTART:KPROF,JLEV,IDH+29) = PDIFCQL(KSTART:KPROF,JLEV)
!     FQNTURCONV
      PDHCV(KSTART:KPROF,JLEV,IDH+30) = PDIFCQN(KSTART:KPROF,JLEV)
!     FQLTURQNEGAT
      PDHCV(KSTART:KPROF,JLEV,IDH+31) = PFCQLNG(KSTART:KPROF,JLEV)
!     FQNTURQNEGAT
      PDHCV(KSTART:KPROF,JLEV,IDH+32) = PFCQNNG(KSTART:KPROF,JLEV)
      IF(LGPCMT) THEN
        !
        !-------------------------------------------------
        ! In the case of PCMT convection scheme, the present "non flexible" DDH should
        ! diagnose FQTCONDECOL as containing both condensation and precipitation evaporation.
        !-------------------------------------------------
        !
        DO JROF=KSTART,KPROF
!         FQTCONDECOL
          PDHCV(JROF,JLEV,IDH+33) = PFCQLF(JROF,JLEV)-PFPEVPCL(JROF,JLEV)
!         FQTCONDECON
          PDHCV(JROF,JLEV,IDH+34) = PFCQIF(JROF,JLEV)-PFPEVPCN(JROF,JLEV)
        ENDDO
      ELSE
!       FQTCONDECOL
        PDHCV(KSTART:KPROF,JLEV,IDH+33) = PFCQLF(KSTART:KPROF,JLEV)
!       FQTCONDECON
        PDHCV(KSTART:KPROF,JLEV,IDH+34) = PFCQIF(KSTART:KPROF,JLEV)
      ENDIF
!     FQTCONDESTL
      PDHCV(KSTART:KPROF,JLEV,IDH+35) = PFSQLF(KSTART:KPROF,JLEV)
!     FQTCONDESTN
      PDHCV(KSTART:KPROF,JLEV,IDH+36) = PFSQIF(KSTART:KPROF,JLEV)
    ENDDO

    IF ( (LCONDWT.AND.LPROCLD).OR. ( L3MT.OR.LSTRAPRO ) ) THEN
      DO JLEV = 0, KFLEV
!       FPEVPL
        PDHCV(KSTART:KPROF,JLEV,IDH+37) = PFPEVPL(KSTART:KPROF,JLEV)
!       FPEVPN
        PDHCV(KSTART:KPROF,JLEV,IDH+38) = PFPEVPN(KSTART:KPROF,JLEV)
!       FPFPL
        PDHCV(KSTART:KPROF,JLEV,IDH+39) = PFPFPL(KSTART:KPROF,JLEV)
!       FPFPN
        PDHCV(KSTART:KPROF,JLEV,IDH+40) = PFPFPN(KSTART:KPROF,JLEV)
      ENDDO
      IF ( L3MT.OR.LSTRAPRO ) THEN
        DO JLEV = 0, KFLEV
!         ... , FQRPEVC
          PDHCV(KSTART:KPROF,JLEV,IDH+41) = PFPEVPCL (KSTART:KPROF,JLEV)
!         ... , FQSPEVC
          PDHCV(KSTART:KPROF,JLEV,IDH+42) = PFPEVPCN (KSTART:KPROF,JLEV)
!         ... , FQLPFPC
          PDHCV(KSTART:KPROF,JLEV,IDH+43) = PFPFPCL (KSTART:KPROF,JLEV)
!         ... , FQNPFPC
          PDHCV(KSTART:KPROF,JLEV,IDH+44) = PFPFPCN (KSTART:KPROF,JLEV)
!         ... , FQRNG
          PDHCV(KSTART:KPROF,JLEV,IDH+45) = PFCQRNG (KSTART:KPROF,JLEV)
!         ... , FQSNG
          PDHCV(KSTART:KPROF,JLEV,IDH+46) = PFCQSNG (KSTART:KPROF,JLEV)
        ENDDO
        IF (NDPSFI==1) THEN
          DO JLEV = 0, KFLEV
!           FQLCMP
            IDH=IDH+1
            PDHCV(KSTART:KPROF,JLEV,IDH+46) = PFCMPSL(KSTART:KPROF,JLEV)
!           FQNCMP
            IDH=IDH+1
            PDHCV(KSTART:KPROF,JLEV,IDH+46) = PFCMPSN(KSTART:KPROF,JLEV)
          ENDDO
        ENDIF
      ENDIF
    ENDIF
  ENDIF
  IF (LPTKE) THEN
    DO JLEV = 0, KFLEV
!     FTKES_TCNS
      PDHCV(KSTART:KPROF,JLEV,IDH+47) = PFTCNS(KSTART:KPROF,JLEV,1)
!     FTKEB_TCNS
      PDHCV(KSTART:KPROF,JLEV,IDH+48) = PFTCNS(KSTART:KPROF,JLEV,2)
!     FTKEDISS_TCNS
      PDHCV(KSTART:KPROF,JLEV,IDH+49) = PFTCNS(KSTART:KPROF,JLEV,3)
!     FTKETUR_TCNS
      PDHCV(KSTART:KPROF,JLEV,IDH+50) = PFTCNS(KSTART:KPROF,JLEV,4)
      IF(LCOEFK_PTTE) THEN
!       FTTEDISS_TCNS
        PDHCV(KSTART:KPROF,JLEV,IDH+51) = PFTCNS(KSTART:KPROF,JLEV,5)
!       FTTETUR_TCNS
        PDHCV(KSTART:KPROF,JLEV,IDH+52) = PFTCNS(KSTART:KPROF,JLEV,6)
      ENDIF
    ENDDO
  ENDIF
ENDIF

IF ( LHDMCI ) THEN
  IDHCV=NDHVV+NDHFVD+NDHAHKP
  DO JROF=KSTART,KPROF
    ZCLON(JROF) = COS(YDGSGEOM%GELAM(JROF)+ROMEGA*(RSTATI-NSSSSS))
    ZSLON(JROF) = SIN(YDGSGEOM%GELAM(JROF)+ROMEGA*(RSTATI-NSSSSS))
  ENDDO
  ZRS=RA
  DO JLEV = 0, KFLEV
    DO JROF=KSTART,KPROF
      ZRS=RA
!     FA1TUR
!     FA2TUR
!     FA3TUR
      PDHCV(JROF,JLEV,IDHCV+1) = ZRS*( ZSTTVG(JROF,JLEV)*&
       & ZSLON(JROF)-&
       & ZSTTUG(JROF,JLEV)*ZCLON(JROF)*YDGSGEOM%GEMU(JROF))  
      PDHCV(JROF,JLEV,IDHCV+2) = ZRS*(-ZSTTVG(JROF,JLEV)*&
       & ZCLON(JROF)-&
       & ZSTTUG(JROF,JLEV)*ZSLON(JROF)*YDGSGEOM%GEMU(JROF))  
      PDHCV(JROF,JLEV,IDHCV+3) = ZRS*ZSTTUG(JROF,JLEV)*YDGSGEOM%GSQM2(JROF)
!     FA1TURCONV
!     FA2TURCONV
!     FA3TURCONV
      PDHCV(JROF,JLEV,IDHCV+4) = ZRS*( ZSTCVG(JROF,JLEV)*&
       & ZSLON(JROF)-&
       & ZSTCUG(JROF,JLEV)*ZCLON(JROF)*YDGSGEOM%GEMU(JROF))  
      PDHCV(JROF,JLEV,IDHCV+5) = ZRS*(-ZSTCVG(JROF,JLEV)*&
       & ZCLON(JROF)-&
       & ZSTCUG(JROF,JLEV)*ZSLON(JROF)*YDGSGEOM%GEMU(JROF))  
      PDHCV(JROF,JLEV,IDHCV+6) = ZRS*ZSTCUG(JROF,JLEV)*YDGSGEOM%GSQM2(JROF)
!     FA1ONDEGREL
!     FA2ONDEGREL
!     FA3ONDEGREL
      PDHCV(JROF,JLEV,IDHCV+7) = ZRS*( ZSTDVG(JROF,JLEV)*&
       & ZSLON(JROF)-&
       & ZSTDUG(JROF,JLEV)*ZCLON(JROF)*YDGSGEOM%GEMU(JROF))  
      PDHCV(JROF,JLEV,IDHCV+8) = ZRS*(-ZSTDVG(JROF,JLEV)*&
       & ZCLON(JROF)-&
       & ZSTDUG(JROF,JLEV)*ZSLON(JROF)*YDGSGEOM%GEMU(JROF))  
      PDHCV(JROF,JLEV,IDHCV+9) = ZRS*ZSTDUG(JROF,JLEV)*YDGSGEOM%GSQM2(JROF)
    ENDDO
  ENDDO
ENDIF
!     ------------------------------------------------------------------
!**   3.- CALCUL DES TENDANCES PHYSIQUES

!*         - DISSIPATION D'ENERGIE CINETIQUE.

IF ( LHDHKS ) THEN
  IF(LDDYN) THEN
    IDHCV=NDHVV+NDHFVD+NDHAVP
  ELSE
    IDHCV=NDHAVP
  ENDIF
  DO JLEV = 1, KFLEV
    DO JROF=KSTART,KPROF
!     TKKDISSIPTUR
      ZDISKT = -( PUZGEO(JROF,JLEV)*&
       & (ZSTTUG(JROF,JLEV)-ZSTTUG(JROF,JLEV-1)) + PVMGEO(JROF,JLEV)&
       & *(ZSTTVG(JROF,JLEV)-ZSTTVG(JROF,JLEV-1)) )  
      PDHCV(JROF,JLEV,IDHCV+1) = ZDISKT
    ENDDO
    DO JROF=KSTART,KPROF
!     TKKDISSIPCONV
      ZDISKC = -( PUZGEO(JROF,JLEV)*&
       & (ZSTCUG(JROF,JLEV)-ZSTCUG(JROF,JLEV-1)) + PVMGEO(JROF,JLEV)&
       & *(ZSTCVG(JROF,JLEV)-ZSTCVG(JROF,JLEV-1)) )  
      PDHCV(JROF,JLEV,IDHCV+2) = ZDISKC
    ENDDO
    DO JROF=KSTART,KPROF
!     TKKDISSIPGREL
      ZDISKD = -( PUZGEO(JROF,JLEV)*&
       & (ZSTDUG(JROF,JLEV)-ZSTDUG(JROF,JLEV-1)) + PVMGEO(JROF,JLEV)&
       & *(ZSTDVG(JROF,JLEV)-ZSTDVG(JROF,JLEV-1)) )  
      PDHCV(JROF,JLEV,IDHCV+3) = ZDISKD
    ENDDO
  ENDDO
ENDIF

IF ( LHDENT ) THEN
  IDHCV=NDHVV+NDHFVD+NDHAVP+NDHBHKP+NDHBMCP
  DO JLEV = 1, KFLEV
    DO JROF=KSTART,KPROF
!     TSSDISSIPTUR
      PDHCV(JROF,JLEV,IDHCV+1) = ( PUZGEO(JROF,JLEV)*&
       & (ZSTTUG(JROF,JLEV)-ZSTTUG(JROF,JLEV-1)) + PVMGEO(JROF,JLEV)&
       & *(ZSTTVG(JROF,JLEV)-ZSTTVG(JROF,JLEV-1)) ) / PT0(JROF,JLEV)  
    ENDDO
    DO JROF=KSTART,KPROF
!     TSSDISSIPCONV
      PDHCV(JROF,JLEV,IDHCV+2) = ( PUZGEO(JROF,JLEV)*&
       & (ZSTCUG(JROF,JLEV)-ZSTCUG(JROF,JLEV-1)) + PVMGEO(JROF,JLEV)&
       & *(ZSTCVG(JROF,JLEV)-ZSTCVG(JROF,JLEV-1)) ) / PT0(JROF,JLEV)  
    ENDDO
    DO JROF=KSTART,KPROF
!     TSSDISSIPGREL
      PDHCV(JROF,JLEV,IDHCV+3) = ( PUZGEO(JROF,JLEV)*&
       & (ZSTDUG(JROF,JLEV)-ZSTDUG(JROF,JLEV-1)) + PVMGEO(JROF,JLEV)&
       & *(ZSTDVG(JROF,JLEV)-ZSTDVG(JROF,JLEV-1)) ) / PT0(JROF,JLEV)  
    ENDDO
    DO JROF=KSTART,KPROF
!     TSSTURQVTOT
      PDHCV(JROF,JLEV,IDHCV+4) =&
       & (PENTRA(JROF,JLEV)-PENTRV(JROF,JLEV) + RCPV-RCPD)*&
       & ( PDIFTQ(JROF,JLEV)-PDIFTQ(JROF,JLEV-1) +&
       & PDIFCQ(JROF,JLEV)-PDIFCQ(JROF,JLEV-1) )  
    ENDDO
    DO JROF=KSTART,KPROF
!     TSSRAY1
      PDHCV(JROF,JLEV,IDHCV+5) =&
       & - ( PFRSO(JROF,JLEV)-PFRSO(JROF,JLEV-1) +&
       & PFRTH(JROF,JLEV)-PFRTH(JROF,JLEV-1) ) / PT0(JROF,JLEV)  
    ENDDO
    DO JROF=KSTART,KPROF
!     TSSTURCTTOT
      PDHCV(JROF,JLEV,IDHCV+6) =&
       & - ( PDIFTS(JROF,JLEV)-PDIFTS(JROF,JLEV-1) +&
       & PDIFCS(JROF,JLEV)-PDIFCS(JROF,JLEV-1) ) / PT0(JROF,JLEV)  
    ENDDO
  ENDDO
ENDIF

!     ------------------------------------------------------------------
!**   4.- CHAMPS AU SOL


IF ( LHDHKS ) THEN

!DEC$ IVDEP
  DO JROF=KSTART,KPROF

    ZLSM=PLSM(JROF)

!     VARIABLES
!     ---------

    PDHCS(JROF,1) = ZLSM

    IF(LEPHYS.OR.LMSE) THEN
      PDHCS(JROF,2) = ZLSM*PTS(JROF)
      PDHCS(JROF,3) = ZLSM*PTP(JROF)
    ELSE
      PDHCS(JROF,2) = ZLSM/PCT(JROF)*PTS(JROF)
      PDHCS(JROF,3) = ZLSM/PCT(JROF)*RTINER*PTP(JROF)
    ENDIF

!    FREE_STYLE VARIABLES
!    --------------------


    PDHCS(JROF,4) = ZLSM*PWS(JROF)
    PDHCS(JROF,5) = ZLSM*PWP(JROF)
    PDHCS(JROF,6) = ZLSM*PSNS(JROF)

!       FREE_STYLE FLUXES
!       -----------------

    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+1) = ZLSM*PFRSO(JROF,KFLEV)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+2) = ZLSM*PFRTH(JROF,KFLEV)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+3) = ZLSM*PFCLL (JROF)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+4) = ZLSM*PFCLN (JROF)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+5) = ZLSM*PFCS  (JROF)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+6) = ZLSM*PFCHSP(JROF)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+7) = -ZLSM*PFONTE(JROF)*RLMLT
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+8) = ZLSM*PFPLSL(JROF,KFLEV)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+9) = ZLSM*PFPLSN(JROF,KFLEV)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+10) = ZLSM*PFPLCL(JROF,KFLEV)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+11) = ZLSM*PFPLCN(JROF,KFLEV)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+12) = ZLSM*PFEVL (JROF)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+13) = ZLSM*PFEVN (JROF)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+14) = ZLSM*PFLWSP(JROF)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+15) = ZLSM*PFONTE(JROF)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+16) = ZLSM*PRUISS(JROF)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+17) = ZLSM*PRUISP(JROF)
    PDHCS(JROF,NDHVS+NDHVFS+NDHFSD+NDHFSP+1) = PFRSO(JROF,KFLEV)/MAX(1.0_JPRB-PALB(JROF),ZEPS)

  ENDDO

!     FLUX - straight copies
!     ----------------------

  PDHCS(KSTART:KPROF,NDHVS+1) = PTCLS(KSTART:KPROF)
  PDHCS(KSTART:KPROF,NDHVS+2) = PQCLS(KSTART:KPROF)
  PDHCS(KSTART:KPROF,NDHVS+3) = PUCLS(KSTART:KPROF)
  PDHCS(KSTART:KPROF,NDHVS+4) = PVCLS(KSTART:KPROF)
  PDHCS(KSTART:KPROF,NDHVS+5) = PHI0(KSTART:KPROF,KFLEV)
  PDHCS(KSTART:KPROF,NDHVS+6) = PGZ0(KSTART:KPROF)
  PDHCS(KSTART:KPROF,NDHVS+7) = PGZ0H(KSTART:KPROF)
  PDHCS(KSTART:KPROF,NDHVS+8) = PALB(KSTART:KPROF)
  PDHCS(KSTART:KPROF,NDHVS+9) = PCLPH(KSTART:KPROF)
  IF (NDHVFS > 9) THEN
    PDHCS(KSTART:KPROF,NDHVS+10:NDHVS+NDHVFS) = 0._JPRB
  ENDIF
  PDHCS(KSTART:KPROF,NDHVS+NDHVFS+NDHFSD+NDHFSP+2) = PFRTHDS(KSTART:KPROF)


ENDIF

!     ------------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('CPPHDDH',1,ZHOOK_HANDLE)
END SUBROUTINE CPPHDDH
