! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE CPXFU(YDGEOMETRY,YDXFU,YDPRECIPS,KST,KND,KSTC,KENDC,KSTGLO,&
 & PDIFCQ, PDIFCS, PDIFTQ, PDIFTS, PFPLCL, PFPLCN,  PFPLCG, PFPLCH,&
 & PFPLSL, PFPLSN, PFPLSG, PFPLSH, PFRSO,&
 & PFRTH  ,PCLCT,  PSTRCU, PSTRCV, PSTRDU, PSTRDV, PSTRTU, PSTRTV, PNEB,&
 & PQICE  ,PQLI,   PXUCLS, PXVCLS, PXNUCLS, PXNVCLS,&
 & PXTCLS, PXQCLS, PXRHCLS,PCLCH,  PCLCM,  PCLCL,  PCLCC,PFTHW,&
 & PFONTE, PFCHSP, PFLWSP, PFEVL,  PRUISP, PRUISS, PCCAPE, PCCTOP, PCMOCON,PXCLPH,&
 & PXVEIN, PXUGST ,PXVGST, PFEVV,  PFTR,   PRUISL, PDIAGH, PMRT,&
 & PVISICLD,PVISIHYDRO, PMXCLWC, PXTPWCLS, PDPRECIPS, PDPRECIPS2)

!**** *CPXFU* - INTERFACE FOR INSTANTANEOUS FLUXES.

!     Purpose.
!     --------
!           DIAGNOSTICS OF PHYSICAL FLUXES.

!**   Interface.
!     ----------
!        *CALL* *CPXFU*

!        Explicit arguments :
!        --------------------

!       NPROMA                 - HORIZONTAL DIMENSION                 (INPUT)
!       KGL1,KGL2              - KGL1 TO KGL2 LATITUDES OF WORK.      (INPUT)
!       KSTABUF                - KSTABUF(JGL) FOR LATITUDE JGL        (INPUT)
!       FLUXES COMING FROM THE PHYSICAL PARAMETERIZATIONS             (INPUT)

!        --------------------

!     Method.
!     -------

!     Externals.
!     ----------

!     Reference.
!     ----------

!     Author.
!     -------
!      O. CLARY
!      Original : 06/92 D'APRES CUMCO

!     Modifications.
!     --------------
!      Modified : 01-08-07 by R. El Khatib - Pruning options
!      M.Hamrud      01-Oct-2003 CY28 Cleaning
!      M.Hamrud      10-Jan-2004 CY28R1 Cleaning
!      Y.Bouteloup   26-Mars-2004 introduction of MTS radiance
!      F.Bouyssel    10-Nov-2005 introduction of PQLI,PQICE
!      Y.Seity       15-Jan-2007 introduction of Graupel and Hail
!      Y.Seity       30-Jan-2008 introduction of Theta'w' flux
!      S. Riette    : 05-may-2009 extreme gusts and mean cls wind added
!      S. Riette     24-Feb-2010 max gusts over NXGSTPERIOD seconds
!      Y. Seity     04-Jan-2011 Hail diagnostic for AROME
!      Y. Seity     04-Sept-2017 gust calculation over 2 different periods
!      R. El Khatib 05-Jun-2018 computation of periods moved from cnt4 (OOPS refactoring)
!      R. Brozkova  Sep-2018 added mean radiant temperature
!     ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMXFU       , ONLY : TXFU
USE YOMDPRECIPS  , ONLY : TDPRECIPS

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TXFU)        ,INTENT(INOUT) :: YDXFU
TYPE(TDPRECIPS)   ,INTENT(IN)    :: YDPRECIPS
INTEGER(KIND=JPIM),INTENT(IN)    :: KST 
INTEGER(KIND=JPIM),INTENT(IN)    :: KND 
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTC 
INTEGER(KIND=JPIM),INTENT(IN)    :: KENDC 
INTEGER(KIND=JPIM),INTENT(IN)    :: KSTGLO 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFCQ(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFCS(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFTQ(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIFTS(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLCL(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLCN(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLCG(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLCH(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLSL(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLSN(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLSG(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFPLSH(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRSO(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFRTH(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLCT(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRCU(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRCV(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRDU(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRDV(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRTU(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PSTRTV(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PNEB(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQICE(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PQLI(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXUCLS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXVCLS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXNUCLS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXNVCLS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXTCLS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXQCLS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXRHCLS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLCH(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLCM(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLCL(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCLCC(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFONTE(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFTHW(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDIAGH(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMRT(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFCHSP(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFLWSP(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFEVL(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRUISP(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRUISS(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCCAPE(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCCTOP(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PCMOCON(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXCLPH(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXVEIN(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXUGST(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXVGST(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFEVV(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PFTR(YDGEOMETRY%YRDIM%NPROMA) 
REAL(KIND=JPRB)   ,INTENT(IN)    :: PRUISL(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVISICLD(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PVISIHYDRO(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PMXCLWC(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDPRECIPS(YDGEOMETRY%YRDIM%NPROMA,YDPRECIPS%NDTPREC)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PDPRECIPS2(YDGEOMETRY%YRDIM%NPROMA,YDPRECIPS%NDTPREC2)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PXTPWCLS(YDGEOMETRY%YRDIM%NPROMA)

!     ------------------------------------------------------------------

REAL(KIND=JPRB) :: ZGFU(YDGEOMETRY%YRDIM%NPROMA,YDXFU%NFDXFU)
REAL(KIND=JPRB) :: ZGST(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZGST2(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZXPTYPE(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZXPTYPESEV(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZXPTYPE2(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZXPTYPESEV2(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZUMEAN(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZVMEAN(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZNUMEAN(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZNVMEAN(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: ZEPS

INTEGER(KIND=JPIM) :: IJLEV, JLEV, JF, IFLD, IOFF, IADD, ISTATS,J

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "abor1.intfb.h"
#include "dprecips_xfu.intfb.h"

!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('CPXFU',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP)
ASSOCIATE(NPROMA=>YDDIM%NPROMA, NFLEVG=>YDDIMV%NFLEVG, &
 & LRESET=>YDXFU%LRESET, LRESET_GST=>YDXFU%LRESET_GST,LRESET_GST2=>YDXFU%LRESET_GST2, &
 & LXMWINDCLS=>YDXFU%LXMWINDCLS, LXCLS=>YDXFU%LXCLS, LXNUVCLS=>YDXFU%LXNUVCLS,&
 & LXXGST=>YDXFU%LXXGST, LXXGST2=>YDXFU%LXXGST2, NMEANSTEPS=>YDXFU%NMEANSTEPS, &
 & NTYPXFU=>YDXFU%NTYPXFU, RMWINDCALC=>YDXFU%RMWINDCALC, RMNWINDCALC=>YDXFU%RMNWINDCALC, &
 & LRESET_VISI=>YDXFU%LRESET_VISI, LRESET_VISI2=>YDXFU%LRESET_VISI2,&
 & LRESET_PRECIP=>YDXFU%LRESET_PRECIP,LRESET_PRECIP2=>YDXFU%LRESET_PRECIP2,&
 & TYPE_XFU=>YDXFU%TYPE_XFU)
!     ------------------------------------------------------------------

!*    1.    READ IN INST. FIELDS

IF (.NOT.LRESET) THEN
  ZGFU = YDXFU%XFUBUF (:, :, 1+(KSTGLO-1)/YDGEOMETRY%YRDIM%NPROMA)
ELSE
  ZGFU=0.0_JPRB
ENDIF

!     ------------------------------------------------------------------

!*    2.    COPY FLUXES
!           -----------

!*    2.1   Extreme gusts
IF (LXXGST) THEN
  IF (LRESET_GST) THEN
    ZGST(KST:KND)=-1.0_JPRB
  ELSE
    DO J=KST,KND
      ZGST(J)=ZGFU(J,YDXFU%YXFUPT%MXUGST)**2+ZGFU(J,YDXFU%YXFUPT%MXVGST)**2
    ENDDO
  ENDIF
ENDIF

IF (LXXGST2) THEN
  IF (LRESET_GST2) THEN
    ZGST2(KST:KND)=-1.0_JPRB
  ELSE
    DO J=KST,KND
      ZGST2(J)=ZGFU(J,YDXFU%YXFUPT%MXUGST2)**2+ZGFU(J,YDXFU%YXFUPT%MXVGST2)**2
    ENDDO
  ENDIF
ENDIF


!*    2.2   Mean cls real/neutral wind
IF (LXMWINDCLS .AND. NMEANSTEPS/=0) THEN

  ! MEANWIND subroutine contained here (in CPXFU)
  IF (LXCLS) CALL MEANWIND &
   & (NMEANSTEPS,YDXFU%YXFUPT%MXUCLS,YDXFU%YXFUPT%MXVCLS,PXUCLS(KST:KND),PXVCLS(KST:KND) &
   & ,RMWINDCALC(KST+KSTGLO-KST:KND+KSTGLO-KST),ZUMEAN(KST:KND),ZVMEAN(KST:KND))
  IF (LXNUVCLS) CALL MEANWIND &
   & (NMEANSTEPS,YDXFU%YXFUPT%MXNUCLS,YDXFU%YXFUPT%MXNVCLS,PXNUCLS(KST:KND),PXNVCLS(KST:KND) &
   & ,RMNWINDCALC(KST+KSTGLO-KST:KND+KSTGLO-KST),ZNUMEAN(KST:KND),ZNVMEAN(KST:KND))
ENDIF

!*    2.3   All fields

IOFF=0
DO JF=1,NTYPXFU
  IADD=1+IOFF
  DO JLEV=1,TYPE_XFU(JF)%ILEV

    IFLD=JLEV+IOFF
    IJLEV=TYPE_XFU(JF)%INUMLEV(JLEV)

    IF (IADD == YDXFU%YXFUPT%MXTRDU) THEN
      ZGFU(KST:KND,IFLD)=PSTRDU(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXTRDV) THEN
      ZGFU(KST:KND,IFLD)=PSTRDV(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXTRCU) THEN
      ZGFU(KST:KND,IFLD)=PSTRCU(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXTRCV) THEN
      ZGFU(KST:KND,IFLD)=PSTRCV(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXDICQ) THEN
      ZGFU(KST:KND,IFLD)=PDIFCQ(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXDICS) THEN
      ZGFU(KST:KND,IFLD)=PDIFCS(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXTRTU) THEN
      ZGFU(KST:KND,IFLD)=PSTRTU(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXTRTV) THEN
      ZGFU(KST:KND,IFLD)=PSTRTV(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXDITQ) THEN
      ZGFU(KST:KND,IFLD)=PDIFTQ(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXDITS) THEN
      ZGFU(KST:KND,IFLD)=PDIFTS(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXPLCL) THEN
      ZGFU(KST:KND,IFLD)=PFPLCL(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXPLCN) THEN
      ZGFU(KST:KND,IFLD)=PFPLCN(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXPLCG) THEN
      ZGFU(KST:KND,IFLD)=PFPLCG(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXPLCH) THEN
      ZGFU(KST:KND,IFLD)=PFPLCH(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXPLSL) THEN
      ZGFU(KST:KND,IFLD)=PFPLSL(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXPLSN) THEN
      ZGFU(KST:KND,IFLD)=PFPLSN(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXPLSG) THEN
      ZGFU(KST:KND,IFLD)=PFPLSG(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXPLSH) THEN
      ZGFU(KST:KND,IFLD)=PFPLSH(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXRSO) THEN
      ZGFU(KST:KND,IFLD)=PFRSO(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXRTH) THEN
      ZGFU(KST:KND,IFLD)=PFRTH(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXNEB) THEN
      ZGFU(KST:KND,IFLD)=PNEB(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXQICE) THEN
      ZGFU(KST:KND,IFLD)=PQICE(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXQLI) THEN
      ZGFU(KST:KND,IFLD)=PQLI(KST:KND,IJLEV) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXNEBT) THEN
      ZGFU(KST:KND,IFLD)=PCLCT(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXFEVL) THEN
      ZGFU(KST:KND,IFLD)=PFEVL(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXFONTE) THEN
      ZGFU(KST:KND,IFLD)=PFONTE(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXFCHSP) THEN
      ZGFU(KST:KND,IFLD)=PFCHSP(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXFLWSP) THEN
      ZGFU(KST:KND,IFLD)=PFLWSP(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXRUISS) THEN
      ZGFU(KST:KND,IFLD)=PRUISS(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXRUISP) THEN
      ZGFU(KST:KND,IFLD)=PRUISP(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXFEVV) THEN
      ZGFU(KST:KND,IFLD)=PFEVV(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXFTR) THEN
      ZGFU(KST:KND,IFLD)=PFTR(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXRUISL) THEN
      ZGFU(KST:KND,IFLD)=PRUISL(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXNBCON) THEN
      ZGFU(KST:KND,IFLD)=PCLCC(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXNBHAU) THEN
      ZGFU(KST:KND,IFLD)=PCLCH(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXNBMOY) THEN
      ZGFU(KST:KND,IFLD)=PCLCM(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXNBBAS) THEN
      ZGFU(KST:KND,IFLD)=PCLCL(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXCAPE) THEN
      ZGFU(KST:KND,IFLD)=PCCAPE(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXCTOP) THEN
      ZGFU(KST:KND,IFLD)=PCCTOP(KST:KND)
    ELSEIF (IADD == YDXFU%YXFUPT%MXMOCON) THEN
      ZGFU(KST:KND,IFLD)=PCMOCON(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXCLPH) THEN
      ZGFU(KST:KND,IFLD)=PXCLPH(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXVEIN) THEN
      ZGFU(KST:KND,IFLD)=PXVEIN(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXMRT) THEN
      ZGFU(KST:KND,IFLD)=PMRT(KST:KND)
    ELSEIF (IADD == YDXFU%YXFUPT%MXUGST) THEN
      !case raf max
      IF (LXXGST) THEN
        DO J=KST,KND
          IF (PXUGST(J)**2+PXVGST(J)**2>ZGST(J)) THEN
            ZGFU(J,IFLD)=PXUGST(J)
          ENDIF
        ENDDO
      ELSE 
      !case raf inst
        ZGFU(KST:KND,IFLD)=PXUGST(KST:KND) 
      ENDIF
    ELSEIF (IADD == YDXFU%YXFUPT%MXVGST) THEN
      !case raf max
      IF (LXXGST) THEN
        DO J=KST,KND
          IF (PXUGST(J)**2+PXVGST(J)**2>ZGST(J)) THEN
            ZGFU(J,IFLD)=PXVGST(J)
          ENDIF
        ENDDO
      ELSE
        !case raf inst
        ZGFU(KST:KND,IFLD)=PXVGST(KST:KND) 
      ENDIF
    ELSEIF (IADD == YDXFU%YXFUPT%MXUGST2) THEN
      IF (LXXGST2) THEN
        !case raf max
        DO J=KST,KND
          IF (PXUGST(J)**2+PXVGST(J)**2>ZGST2(J)) THEN
            ZGFU(J,IFLD)=PXUGST(J)
          ENDIF
        ENDDO
      ENDIF
    ELSEIF (IADD == YDXFU%YXFUPT%MXVGST2) THEN
      !case raf max
      IF (LXXGST2) THEN
        DO J=KST,KND
          IF (PXUGST(J)**2+PXVGST(J)**2>ZGST2(J)) THEN
            ZGFU(J,IFLD)=PXVGST(J)
          ENDIF
        ENDDO
      ENDIF

    ELSEIF (IADD == YDXFU%YXFUPT%MXUCLS) THEN
      IF (LXMWINDCLS) THEN
        ! case mean wind
        ZGFU(KST:KND,IFLD)=ZUMEAN(KST:KND)
      ELSE
        ! case inst wind
        ZGFU(KST:KND,IFLD)=PXUCLS(KST:KND) 
      ENDIF
    ELSEIF (IADD == YDXFU%YXFUPT%MXVCLS) THEN
      IF (LXMWINDCLS) THEN
        ! case mean wind
        ZGFU(KST:KND,IFLD)=ZVMEAN(KST:KND)
      ELSE
        ! case inst wind
        ZGFU(KST:KND,IFLD)=PXVCLS(KST:KND) 
      ENDIF
    ELSEIF (IADD == YDXFU%YXFUPT%MXNUCLS) THEN
      IF (LXMWINDCLS) THEN
        ! case mean wind
        ZGFU(KST:KND,IFLD)=ZNUMEAN(KST:KND)
      ELSE
        ! case inst wind
        ZGFU(KST:KND,IFLD)=PXNUCLS(KST:KND) 
      ENDIF
    ELSEIF (IADD == YDXFU%YXFUPT%MXNVCLS) THEN
      IF (LXMWINDCLS) THEN
        ! case mean wind
        ZGFU(KST:KND,IFLD)=ZNVMEAN(KST:KND)
      ELSE
        ! case inst wind
        ZGFU(KST:KND,IFLD)=PXNVCLS(KST:KND) 
      ENDIF
    ELSEIF (IADD == YDXFU%YXFUPT%MXTCLS) THEN
      ZGFU(KST:KND,IFLD)=PXTCLS(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXQCLS) THEN
      ZGFU(KST:KND,IFLD)=PXQCLS(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXRHCLS) THEN
      ZGFU(KST:KND,IFLD)=MAX(0.0_JPRB,MIN(1.0_JPRB,PXRHCLS(KST:KND)))
    ELSEIF (IADD == YDXFU%YXFUPT%MXTN) THEN
      IF (LRESET) THEN
        ZGFU(KST:KND,IFLD)=100000._JPRB
      ENDIF
      ZGFU(KST:KND,IFLD)=MIN(ZGFU(KST:KND,IFLD),PXTCLS(KST:KND))
    ELSEIF (IADD == YDXFU%YXFUPT%MXTX) THEN
      IF (LRESET) THEN
        ZGFU(KST:KND,IFLD)=0.0_JPRB
      ENDIF
      ZGFU(KST:KND,IFLD)=MAX(ZGFU(KST:KND,IFLD),PXTCLS(KST:KND)) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXHUN) THEN
      IF (LRESET) THEN
        ZGFU(KST:KND,IFLD)=1.0_JPRB
      ENDIF
      ZGFU(KST:KND,IFLD)=MIN(ZGFU(KST:KND,IFLD),PXRHCLS(KST:KND))
      ZGFU(KST:KND,IFLD)=MAX(0.0_JPRB,MIN(1.0_JPRB,ZGFU(KST:KND,IFLD)))
    ELSEIF (IADD == YDXFU%YXFUPT%MXHUX) THEN
      IF (LRESET) THEN
        ZGFU(KST:KND,IFLD)=0.0_JPRB
      ENDIF
      ZGFU(KST:KND,IFLD)=MAX(ZGFU(KST:KND,IFLD),PXRHCLS(KST:KND))
      ZGFU(KST:KND,IFLD)=MAX(0.0_JPRB,MIN(1.0_JPRB,ZGFU(KST:KND,IFLD)))
    ELSEIF (IADD == YDXFU%YXFUPT%MXTHW) THEN  
      ZGFU(KST:KND,IFLD)=PFTHW(KST:KND) 
    ELSEIF (IADD == YDXFU%YXFUPT%MXXDIAGH) THEN
! YS: it would be better to define a new specific LRESET_DIAGH 
      IF (LRESET_GST) THEN
        ZGFU(KST:KND,IFLD)=0.0_JPRB
      ENDIF
      ZGFU(KST:KND,IFLD)=MAX(ZGFU(KST:KND,IFLD),PDIAGH(KST:KND))
    ELSEIF (IADD == YDXFU%YXFUPT%MXVISICLD) THEN
       IF (LRESET_VISI) THEN
         ZGFU(KST:KND,IFLD)=20000.0_JPRB
       ENDIF
       ZGFU(KST:KND,IFLD)=MIN(ZGFU(KST:KND,IFLD),PVISICLD(KST:KND))
       ZGFU(KST:KND,IFLD)=MAX(ZGFU(KST:KND,IFLD),0.0_JPRB)
     ELSEIF (IADD == YDXFU%YXFUPT%MXVISIHYD) THEN
       IF (LRESET_VISI) THEN
         ZGFU(KST:KND,IFLD)=20000.0_JPRB
       ENDIF
       ZGFU(KST:KND,IFLD)=MIN(ZGFU(KST:KND,IFLD),PVISIHYDRO(KST:KND))
       ZGFU(KST:KND,IFLD)=MAX(ZGFU(KST:KND,IFLD),0.0_JPRB)
     ELSEIF (IADD == YDXFU%YXFUPT%MXCLWC) THEN
       IF (LRESET_VISI) THEN
         ZGFU(KST:KND,IFLD)=0.0_JPRB
       ENDIF
       ZGFU(KST:KND,IFLD)=MAX(ZGFU(KST:KND,IFLD),PMXCLWC(KST:KND))
       ZGFU(KST:KND,IFLD)=MAX(ZGFU(KST:KND,IFLD),0.0_JPRB)
     ELSEIF (IADD == YDXFU%YXFUPT%MXVISICLD2) THEN
       IF (LRESET_VISI2) THEN
         ZGFU(KST:KND,IFLD)=20000.0_JPRB
       ENDIF
       ZGFU(KST:KND,IFLD)=MIN(ZGFU(KST:KND,IFLD),PVISICLD(KST:KND))
       ZGFU(KST:KND,IFLD)=MAX(ZGFU(KST:KND,IFLD),0.0_JPRB)
     ELSEIF (IADD == YDXFU%YXFUPT%MXVISIHYD2) THEN
       IF (LRESET_VISI2) THEN
         ZGFU(KST:KND,IFLD)=20000.0_JPRB
       ENDIF
       ZGFU(KST:KND,IFLD)=MIN(ZGFU(KST:KND,IFLD),PVISIHYDRO(KST:KND))
       ZGFU(KST:KND,IFLD)=MAX(ZGFU(KST:KND,IFLD),0.0_JPRB)
     ELSEIF (IADD == YDXFU%YXFUPT%MXCLWC2) THEN
       IF (LRESET_VISI2) THEN
         ZGFU(KST:KND,IFLD)=0.0_JPRB
       ENDIF
       ZGFU(KST:KND,IFLD)=MAX(ZGFU(KST:KND,IFLD),PMXCLWC(KST:KND))
       ZGFU(KST:KND,IFLD)=MAX(ZGFU(KST:KND,IFLD),0.0_JPRB)
     ELSEIF (IADD == YDXFU%YXFUPT%MXTPWCLS) THEN
       ZGFU(KST:KND,IFLD)=PXTPWCLS(KST:KND)
     ELSEIF (IADD == YDXFU%YXFUPT%MXPTYPE) THEN
       IF (LRESET_PRECIP) THEN
         ZGFU(KST:KND,IFLD)=0.0_JPRB
       ENDIF
       ISTATS=0
       CALL DPRECIPS_XFU(KST,KND,YDGEOMETRY%YRDIM%NPROMA,YDPRECIPS%NDTPREC,&
                      & ISTATS,PDPRECIPS(:,:),ZXPTYPE(:))
       ZGFU(KST:KND,IFLD)=ZXPTYPE(KST:KND)
     ELSEIF (IADD == YDXFU%YXFUPT%MXPTYPESEV) THEN
       IF (LRESET_PRECIP) THEN
          ZGFU(KST:KND,IFLD)=0.0_JPRB
       ENDIF
       ISTATS=2
       CALL DPRECIPS_XFU(KST,KND,YDGEOMETRY%YRDIM%NPROMA,YDPRECIPS%NDTPREC,&
                     & ISTATS,PDPRECIPS(:,:),ZXPTYPESEV(:))
       ZGFU(KST:KND,IFLD)=ZXPTYPESEV(KST:KND)  
     ELSEIF (IADD == YDXFU%YXFUPT%MXPTYPE2) THEN
       IF (LRESET_PRECIP2) THEN
         ZGFU(KST:KND,IFLD)=0.0_JPRB
       ENDIF
       ISTATS=0
       CALL DPRECIPS_XFU(KST,KND,YDGEOMETRY%YRDIM%NPROMA,YDPRECIPS%NDTPREC2,&
                      & ISTATS,PDPRECIPS2(:,:),ZXPTYPE2(:))
       ZGFU(KST:KND,IFLD)=ZXPTYPE2(KST:KND)
      ELSEIF (IADD == YDXFU%YXFUPT%MXPTYPESEV2) THEN
       IF (LRESET_PRECIP2) THEN
          ZGFU(KST:KND,IFLD)=0.0_JPRB
       ENDIF
       ISTATS=2
       CALL DPRECIPS_XFU(KST,KND,YDGEOMETRY%YRDIM%NPROMA,YDPRECIPS%NDTPREC2,&
                     & ISTATS,PDPRECIPS2(:,:),ZXPTYPESEV2(:))
       ZGFU(KST:KND,IFLD)=ZXPTYPESEV2(KST:KND)  
    ELSE
      CALL ABOR1('CPXFU : ERROR IN POINTERS') 
    ENDIF

  ENDDO
  IOFF=IOFF+TYPE_XFU(JF)%ILEV
ENDDO

!     ------------------------------------------------------------------

!*       3.    WRITE OUT FIELDS .
!              -----------------

!*    3.1   WRITE OUT FIELDS

YDXFU%XFUBUF (:, :, 1+(KSTGLO-1)/YDGEOMETRY%YRDIM%NPROMA) = ZGFU


!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('CPXFU',1,ZHOOK_HANDLE)

!     ------------------------------------------------------------------

CONTAINS

SUBROUTINE MEANWIND(KMEANSTEPS,KXU,KXV,PXU,PXV,PMWINDCALC,ZUM,ZVM)
! The algorithm is the same as the one used to compute observed mean wind

INTEGER(KIND=JPIM) ,INTENT(IN) :: KMEANSTEPS
INTEGER(KIND=JPIM) ,INTENT(IN) :: KXU ,KXV
REAL(KIND=JPRB) ,INTENT(IN) ,DIMENSION(KST:KND) :: PXU ,PXV
REAL(KIND=JPRB) ,INTENT(INOUT) :: PMWINDCALC(KST+KSTGLO-KST:KND+KSTGLO-KST)
REAL(KIND=JPRB) ,INTENT(OUT) ,DIMENSION(KST:KND) :: ZUM ,ZVM

REAL(KIND=JPRB) :: ZMEANMODULE(KST:KND)
REAL(KIND=JPRB) :: ZMEANANGLE
REAL(KIND=JPRB) :: ZANGLE
REAL(KIND=JPRB) :: ZMEANCANGLE
REAL(KIND=JPRB) :: ZMEANSANGLE
REAL(KIND=JPRB) :: ZEPS

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('CPXFU:MEANWIND',0,ZHOOK_HANDLE)

ZEPS=1.E-12
IF (KMEANSTEPS==1) THEN
  ZUM(KST:KND)=PXU(KST:KND)
  ZVM(KST:KND)=PXV(KST:KND)
  PMWINDCALC(KST+KSTGLO-KST:KND+KSTGLO-KST)=1.0_JPRB
ELSE
  DO J=KST,KND
    ! Module of mean wind is the mean of the modules
    ZMEANMODULE(J)=SQRT(ZGFU(J,KXU)**2+ZGFU(J,KXV)**2)
  ENDDO
  DO J=KST,KND
    ! Module of mean wind is the mean of the modules
    ZMEANMODULE(J)= ZMEANMODULE(J)*REAL(KMEANSTEPS-1,JPRB) + SQRT(PXU(J)**2+PXV(J)**2)
  ENDDO
  DO J=KST,KND
    ! We compute mean of COS and mean of SIN
    ! Direction of mean wind is the direction of vector [mean COS, mean SIN]
    IF (ABS(ZGFU(J,KXV))<ZEPS.AND.ABS(ZGFU(J,KXU))<ZEPS) THEN
      ZMEANANGLE=0.0_JPRB
    ELSE
      ZMEANANGLE=ATAN2(ZGFU(J,KXV),ZGFU(J,KXU))
    ENDIF
    IF (ABS(PXV(J))<ZEPS.AND.ABS(PXU(J))<ZEPS) THEN
      ZANGLE=0.0_JPRB
    ELSE
      ZANGLE=ATAN2(PXV(J),PXU(J))
    ENDIF
    ZMEANCANGLE=( COS(ZMEANANGLE)*REAL(KMEANSTEPS-1,JPRB) * &
     & PMWINDCALC(J+KSTGLO-KST)+ &
     & COS(ZANGLE) ) / REAL(KMEANSTEPS,JPRB)
    ZMEANSANGLE=( SIN(ZMEANANGLE)*REAL(KMEANSTEPS-1,JPRB) * &
     & PMWINDCALC(J+KSTGLO-KST)+ &
     & SIN(ZANGLE) ) / REAL(KMEANSTEPS,JPRB)
    PMWINDCALC(J+KSTGLO-KST)=SQRT(ZMEANCANGLE**2+ZMEANSANGLE**2)
    IF (ABS(ZMEANSANGLE)<ZEPS.AND.ABS(ZMEANCANGLE)<ZEPS) THEN
      ZMEANANGLE=0.0_JPRB
    ELSE
      ZMEANANGLE=ATAN2(ZMEANSANGLE,ZMEANCANGLE)
    ENDIF
    ZUM(J)=ZMEANMODULE(J)*COS(ZMEANANGLE)/ REAL(KMEANSTEPS,JPRB)
    ZVM(J)=ZMEANMODULE(J)*SIN(ZMEANANGLE)/ REAL(KMEANSTEPS,JPRB)
  ENDDO
ENDIF

IF (LHOOK) CALL DR_HOOK('CPXFU:MEANWIND',1,ZHOOK_HANDLE)

END SUBROUTINE MEANWIND 

!     ------------------------------------------------------------------

END SUBROUTINE CPXFU
