! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE WRFLD_FP(YDFPS,YDGEOMETRY,PTSTEP,KTAG,KMVSET,YDFLDPTR,YDIOS_CL,YD_DISTR)

!**** *WRFLD_FP*  - Send fields to FP server 

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 15-04-2016


USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK

USE YOMFP_SERV,   ONLY : FP_SERV, FP_SERV_DISTR
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE YOMIO_SERV,   ONLY : IO_SERV

USE YOMIO_SERV_HDR,      ONLY : NIO_SERV_HDR_IDOM_MDP
USE YOMIO_SERV_MAP_PLAN, ONLY : IO_SERV_SEND_PLAN

USE IOFLDPTR_MOD, ONLY : IOFLDPTR

USE IOSPEC_MOD, ONLY : IOSPEC_SELECTF, NIOSPECCT_WRITE
USE IOGRID_MOD, ONLY : IOGRID_SELECTF, NIOGRIDCT_WRITE

IMPLICIT NONE

TYPE (FP_SERV),      INTENT (INOUT) :: YDFPS
TYPE (GEOMETRY),     INTENT (IN)    :: YDGEOMETRY
REAL(KIND=JPRB),     INTENT(IN)     :: PTSTEP
INTEGER (KIND=JPIM), INTENT (IN)    :: KTAG
INTEGER (KIND=JPIM), INTENT (IN)    :: KMVSET
TYPE (IOFLDPTR),     INTENT (IN)    :: YDFLDPTR (:)
TYPE (IO_SERV),      INTENT (INOUT) :: YDIOS_CL (:,:)
TYPE (FP_SERV_DISTR),INTENT (IN)    :: YD_DISTR

#include "io_serv_map_send_part1.intfb.h"
#include "io_serv_map_send_part2.intfb.h"
#include "abor1.intfb.h"

INTEGER(KIND=JPIM) :: INFLDG, INFLDL

TYPE (IOFLDPTR), ALLOCATABLE :: YLFLDPTR (:)
TYPE (IO_SERV_SEND_PLAN), ALLOCATABLE :: YLIOSMPP (:,:)
INTEGER (KIND=JPIM) :: ISIZEG, ISIZEL
INTEGER (KIND=JPIM) :: ISIZEG_DUMMY, ISIZEL_DUMMY
INTEGER (KIND=JPIM) :: IISETH, IISETV, INSETH, INSETV
INTEGER (KIND=JPIM) :: IVSETR, JFLDG, JFLDR, ILEVG
INTEGER (KIND=JPIM), POINTER :: IINDSEL (:)
LOGICAL             :: LLSPEC

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('WRFLD_FP',0,ZHOOK_HANDLE)

LLSPEC = ALL (YDFLDPTR%YFLDDSC%LSPEC)

IF ((.NOT. LLSPEC) .AND. (ANY (YDFLDPTR%YFLDDSC%LSPEC))) THEN
  CALL ABOR1 ('WRFLD_FP: MIXED SPECTRAL AND GRID POINT FIELDS')
ENDIF

INFLDG = SIZE (YDFLDPTR)

INSETH = SIZE (YDIOS_CL, 1)
INSETV = SIZE (YDIOS_CL, 2)

ALLOCATE (YLIOSMPP (INSETH, INSETV))

ISIZEL_DUMMY=HUGE(1)
ISIZEG_DUMMY=HUGE(1)

DO IISETH = 1, INSETH
  DO IISETV = 1, INSETV

! NSPEC2 of remote task

    ISIZEG  = YD_DISTR%YFSDINF (IISETH)%NSIZEG

! V-set of remote task

    IVSETR  = YD_DISTR%ISETV_R (IISETV)

! Find common levels between current local task and remote task

    INFLDL = 0
    DO JFLDG = 1, INFLDG
      ILEVG = YDFLDPTR (JFLDG)%YFLDDSC%ILEVG
      IF ((YD_DISTR%ISETLEV_L (ILEVG) == KMVSET)&
  & .AND. (YD_DISTR%ISETLEV_R (ILEVG) == IVSETR)) THEN
        INFLDL = INFLDL + 1
      ENDIF
    ENDDO

    ALLOCATE (YLFLDPTR (INFLDL))

    JFLDR = 0
    DO JFLDG = 1, INFLDG
      ILEVG = YDFLDPTR (JFLDG)%YFLDDSC%ILEVG
      IF ((YD_DISTR%ISETLEV_L (ILEVG) == KMVSET)&
  & .AND. (YD_DISTR%ISETLEV_R (ILEVG) == IVSETR)) THEN
        JFLDR = JFLDR + 1
        YLFLDPTR (JFLDR) = YDFLDPTR (JFLDG)
      ENDIF
    ENDDO

    YLFLDPTR%YFLDDSC%NFLSZ = ISIZEG
 
    CALL IO_SERV_MAP_SEND_PART1(YDIOS_CL(IISETH,IISETV),ISIZEL_DUMMY, ISIZEG_DUMMY,YLFLDPTR%YFLDDSC,KTAG,YLIOSMPP(IISETH,IISETV), &
 &                              KDOM_TYPE=NIO_SERV_HDR_IDOM_MDP,PTSTEP=PTSTEP)
 
    ISIZEL  = YD_DISTR%ISORTCNT (IISETH)
    IINDSEL => YD_DISTR%ISORTR2L (1:ISIZEL, IISETH)
 
    IF (LLSPEC) THEN
      CALL IOSPEC_SELECTF (YDGEOMETRY, NIOSPECCT_WRITE, YLIOSMPP (IISETH, IISETV)%YLBUFD,&
                         & YLFLDPTR, KINDSEL=IINDSEL)
    ELSE
      CALL IOGRID_SELECTF (YDGEOMETRY, NIOGRIDCT_WRITE, YLIOSMPP (IISETH, IISETV)%YLBUFD,&
                         & YLFLDPTR, KINDSEL=IINDSEL)
    ENDIF
 
    CALL IO_SERV_MAP_SEND_PART2 (YDIOS_CL (IISETH, IISETV), YLIOSMPP (IISETH, IISETV))

    DEALLOCATE (YLFLDPTR)
 
  ENDDO
ENDDO

YDFPS%LSENTFLD = .TRUE.

IF (LHOOK) CALL DR_HOOK('WRFLD_FP',1,ZHOOK_HANDLE)

END SUBROUTINE WRFLD_FP

