! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE WRGATHFLNM (YDVAB, KDOM, KNFL, KDIMGVAL, KNFD, KFLDOFF, PVALCO, YDCPDSC, YDFPOPH, CDFPFN, &
                     & KPTR, KMASK, LDNORM, YDFACTX, YDFACTXS, CDNORMTITLE, KTAG, CDDOMNAMES, &
                     & YDGEOMETRY,YDFPUSERGEO,KFPCHKDAT)

!**** *WRGATHFLNM*  - Write compressed data

!        CDFPFN : output filenames

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 11-09-2012

!     Modifications:
!     --------------
!     P. Marguinaud : 10-10-2013 : Use FACTX, multi-root option, do not use GATHFLNM
!      T. Wilhelmsson and K. Yessad (Oct 2013) Geometry and setup refactoring.
!      R. El Khatib 10-Dec-2015 CDFPFN
!     P. Marguinaud : 04-10-2016 : Port to single precision
!-----------------------------------------------------------------------------

USE TYPE_FAOPH, ONLY : TFAOPH
USE TYPE_FPUSERGEO, ONLY : TFPUSERGEO
USE GEOMETRY_MOD  , ONLY : GEOMETRY
USE YOMVERT  , ONLY : TVAB
USE PARKIND1      , ONLY : JPRB, JPIM
USE YOMHOOK       , ONLY : LHOOK, DR_HOOK, JPHOOK

USE WRFLDCW_MOD   , ONLY : WRFLDCW_OPEN,    &
                         & WRFLDCW_START,   &
                         & WRFLDCW_WRITE,   &
                         & WRFLDCW_CLOSE,   &
                         & WRFLDCW_FINISH,  &
                         & WRFLDCW_CTX
USE MFIOOPTS_MOD  , ONLY : MFIOOPTS
USE IOCPTDESC_MOD , ONLY : IOCPTDESC,     &
                         & NIOCPTDESC_SIZE

USE MPL_MODULE    , ONLY : MPL_SEND, MPL_RECV, JP_BLOCKING_STANDARD

USE YOMMP0        , ONLY : MYPROC, NPROC
USE YOMLUN        , ONLY : NULOUT
USE FACTX_MOD, ONLY : FACTX, OPENWRFACTX, WRITEFLD
USE FA_MOD        , ONLY : JPPRCM

IMPLICIT NONE

TYPE(TVAB),            INTENT (IN)    :: YDVAB
INTEGER (KIND=JPIM)   ,INTENT (IN)    :: KDOM
INTEGER (KIND=JPIM)   ,INTENT (IN)    :: KNFL
INTEGER (KIND=JPIM)   ,INTENT (IN)    :: KDIMGVAL
INTEGER (KIND=JPIM)   ,INTENT (IN)    :: KNFD (NPROC)
INTEGER (KIND=JPIM)   ,INTENT (IN)    :: KFLDOFF (NPROC)
REAL (KIND=JPRB)      ,INTENT (INOUT) :: PVALCO (KDIMGVAL,KNFL)            ! should be intent in 
TYPE (IOCPTDESC)      ,INTENT (IN)    :: YDCPDSC (KNFL,KDOM)               ! compressed field descriptors
TYPE (TFAOPH)     ,    INTENT (IN)    :: YDFPOPH(:)
CHARACTER (LEN=*),     INTENT (IN)    :: CDFPFN(:)
INTEGER (KIND=JPIM)   ,INTENT (INOUT), OPTIONAL :: KPTR (KDOM)             ! pointers required when KDOM > 1
INTEGER (KIND=JPIM)   ,INTENT (IN),    OPTIONAL :: KMASK (KNFL,KDOM)
LOGICAL               ,INTENT (IN)   , OPTIONAL :: LDNORM                  ! gather norms on MPI #1 and print
TYPE (FACTX)          ,INTENT (INOUT), OPTIONAL :: YDFACTX
TYPE (FACTX)          ,INTENT (INOUT), OPTIONAL :: YDFACTXS (KDOM)
CHARACTER (LEN=*)     ,INTENT (IN),    OPTIONAL :: CDNORMTITLE
INTEGER (KIND=JPIM),   INTENT (IN),    OPTIONAL :: KTAG
TYPE (GEOMETRY),       INTENT (IN),    OPTIONAL :: YDGEOMETRY
TYPE (TFPUSERGEO)     ,INTENT (IN),    OPTIONAL :: YDFPUSERGEO(:)
CHARACTER (LEN=*)     ,INTENT (IN),    OPTIONAL :: CDDOMNAMES (KDOM)       ! Domain names
INTEGER (KIND=JPIM)   ,INTENT (IN),    OPTIONAL :: KFPCHKDAT               ! check date (fpos only, though ...)

! if KTAG is present then it is possible for MPI #1 to receive compressed data in random order

#include "abor1.intfb.h"

INTEGER (KIND=JPIM) :: IIOROOT     ! IO root for current proc
INTEGER (KIND=JPIM) :: IIOLAST     ! Last processor covered by IO root
LOGICAL             :: LLISIOROOT  ! Current proc is IO root
TYPE (MFIOOPTS)     :: YLIOOPTS    ! IO options
INTEGER (KIND=JPIM) :: IPFAOVSZ (KDOM) ! Extra size for packed fields

INTEGER (KIND=JPIM) :: JROC
INTEGER (KIND=JPIM) :: INFL, INFG, JDOM

TYPE (IOCPTDESC)   , ALLOCATABLE :: YLCPDSCG (:,:)
INTEGER (KIND=JPIM), ALLOCATABLE :: IMASKG (:,:)

INTEGER (KIND=JPIM) :: IPTR (KDOM)
INTEGER (KIND=JPIM) :: IMASK (KNFL,KDOM)
TYPE (FACTX)        :: YLFACTXS (KDOM)
TYPE (WRFLDCW_CTX)  :: YLWCTX1F
LOGICAL :: LLNORM

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM',0,ZHOOK_HANDLE)

LLNORM = .FALSE.
IF (PRESENT (LDNORM)) LLNORM = LDNORM

IF (.NOT. PRESENT (KPTR)) THEN
  IF (KDOM == 1) THEN
    IPTR (1) = 1
  ELSE
    CALL ABOR1 ('WRGATHFLNM: KPTR IS MANDATORY WHEN KDOM > 1')
  ENDIF
ELSE
  IPTR = KPTR
ENDIF

IF (PRESENT (KMASK)) THEN
  IMASK = KMASK
ELSE
  IMASK = 1
ENDIF

IF (PRESENT (YDFACTXS)) THEN
  YLFACTXS = YDFACTXS
ELSEIF (PRESENT (YDFACTX)) THEN
  IF (KDOM > 1) CALL ABOR1 ('WRGATHFLNM: YDFACTXS IS MANDATORY WHEN KDOM > 1')
  YLFACTXS = YDFACTX
ELSE
  CALL ABOR1 ('WRGATHFLNM: EXPECTED ARGUMENT : YDFACTXS OR YDFACTX')
ENDIF

DO JDOM = 1, KDOM
  IPFAOVSZ(JDOM)= YDFPOPH(JDOM)%NHEADMAX
ENDDO

YLIOOPTS = YLFACTXS (1)%YIOOPTS
INFG = SUM (KNFD)
INFL = KNFL

IF (YLIOOPTS%LDOCW) CALL WRFLDCW_START (YLWCTX1F, LDISIO=INFL > 0, LDMPI=.TRUE.)

IF (INFL == 0) THEN
  IF (YLIOOPTS%LDOCW) CALL WRFLDCW_FINISH (YLWCTX1F)
  IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM',1,ZHOOK_HANDLE)
  RETURN
ENDIF

DO JROC = 1, YLIOOPTS%NIOROOT
  IIOROOT = 1 + ((JROC-1) * NPROC) / YLIOOPTS%NIOROOT
  IIOLAST = (JROC * NPROC) / YLIOOPTS%NIOROOT
  IF ((IIOROOT <= MYPROC) .AND. (MYPROC <= IIOLAST)) EXIT
ENDDO

DO WHILE (KNFD (IIOROOT) == 0)
  IIOROOT = IIOROOT + 1
ENDDO

LLISIOROOT = IIOROOT == MYPROC

IF (LLISIOROOT) THEN
  ALLOCATE (YLCPDSCG (INFG,KDOM), IMASKG (INFG,KDOM))
  YLCPDSCG%CNOMA = 'XXXXXXXXXXXXXXXX'
  YLCPDSCG%ILNOMA = 0
  YLCPDSCG%ILONGD = 0
  YLCPDSCG%ZMIN   = -999._JPRB
  YLCPDSCG%ZMAX   = -999._JPRB
  YLCPDSCG%ZAVE   = -999._JPRB
  IMASKG = 0_JPIM
ENDIF

IF (YLIOOPTS%LDOW1) THEN

! MPI #1 writes

  IF (YLIOOPTS%LDOGF) THEN

    IF (LLISIOROOT) THEN
      CALL DOWRMYFLDS
      CALL DOWROTHERFLDS
    ELSE
      CALL DOSENDMYFLDS
    ENDIF

  ENDIF

ELSEIF (YLIOOPTS%LDOWN) THEN

! Each MPI writes

  IF (YLIOOPTS%LDOWR) THEN

! To different files

    CALL DOWRMYFLDS

  ELSEIF (YLIOOPTS%LDOCW) THEN

! To the same file

    CALL DOWRMYFLDS1F

  ENDIF

ENDIF

IF (LLNORM) CALL DUMPNORMS

IF (LLISIOROOT) THEN
  DEALLOCATE (YLCPDSCG)
ENDIF

IF (PRESENT (YDFACTXS)) THEN
  YDFACTXS = YLFACTXS
ELSEIF (PRESENT (YDFACTX)) THEN
  YDFACTX = YLFACTXS (1)
ENDIF

IF (YLIOOPTS%LDOCW) CALL WRFLDCW_FINISH (YLWCTX1F)

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE DUMPNORMS

USE IOCPTDESC_MOD, ONLY : IOCPTDESC_FREEZE, IOCPTDESC_THAW

REAL (KIND=JPRB), ALLOCATABLE :: ZBUF (:)

INTEGER (KIND=JPIM) :: JROC, ITAG
INTEGER (KIND=JPIM) :: JFLDG, JFLDL, JFLDG1, JFLDG2
INTEGER (KIND=JPIM) :: JDOM, IHDRSPK, IBUF
TYPE (IOCPTDESC)    :: YLCPDSC1
CHARACTER(LEN=16)   :: CLPRINT

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DUMPNORMS',0,ZHOOK_HANDLE)

!          GATHER NORMS FROM NSTROUT PROCS
!          -------------------------------

IHDRSPK = NIOCPTDESC_SIZE

IF (.NOT. YLIOOPTS%LDOW1) THEN

  IOMASTER_DISTIO : IF (INFL > 0 .AND. MYPROC /= 1) THEN

    ITAG = MYPROC

    ALLOCATE (ZBUF (IHDRSPK*INFL*KDOM))
    
    IBUF = 0
    DO JDOM = 1, KDOM
      DO JFLDL = 1, INFL
        YLCPDSC1 = YDCPDSC (JFLDL,JDOM)
        IF (IMASK (JFLDL,JDOM) == 0) YLCPDSC1%CNOMA = ''
        ZBUF (IBUF+1:IBUF+IHDRSPK) = IOCPTDESC_FREEZE (YLCPDSC1)
        IBUF = IBUF + IHDRSPK
      ENDDO
    ENDDO

    CALL MPL_SEND (ZBUF, KDEST=1, KTAG=ITAG, CDSTRING='WRGATHFLNM:DUMPNORMS')

    DEALLOCATE (ZBUF)

  ELSEIF (MYPROC == 1) THEN IOMASTER_DISTIO

    DO JROC = 2, NPROC

      IF (KNFD (JROC) == 0) CYCLE

      ITAG = JROC

      JFLDG1 = KFLDOFF(JROC) + 1
      JFLDG2 = KFLDOFF(JROC) + KNFD (JROC)

      ALLOCATE (ZBUF (IHDRSPK*KNFD (JROC)*KDOM))
      CALL MPL_RECV (ZBUF, KTAG=ITAG, KSOURCE=JROC, CDSTRING='WRGATHFLNM:DUMPNORMS')

      IBUF = 0
      DO JDOM = 1, KDOM
        DO JFLDG = JFLDG1, JFLDG2
          YLCPDSCG (JFLDG,JDOM) = IOCPTDESC_THAW (ZBUF (IBUF+1:IBUF+IHDRSPK))
          IF (YLCPDSCG (JFLDG,JDOM)%CNOMA == '') THEN
            IMASKG (JFLDG,JDOM) = 0
          ELSE
            IMASKG (JFLDG,JDOM) = 1
          ENDIF
        ENDDO
      ENDDO

      DEALLOCATE (ZBUF)

    ENDDO

  ENDIF IOMASTER_DISTIO

ENDIF

! IOMASTER DUMPS OUT NORMS

IF (MYPROC == 1) THEN

  DO JDOM = 1, KDOM

    DO JFLDL = 1, KNFD (MYPROC)

      JFLDG = KFLDOFF (MYPROC) + JFLDL
      YLCPDSCG (JFLDG,JDOM) = YDCPDSC (JFLDL,JDOM)
      IMASKG (JFLDG,JDOM)  = IMASK (JFLDL,JDOM)

    ENDDO

  ENDDO

  IF (PRESENT (CDNORMTITLE)) WRITE (NULOUT, *) CDNORMTITLE

  DO JDOM = 1, KDOM

    WRITE (NULOUT, FMT='(29X,3(6X,A7,9X))') 'AVERAGE','MINIMUM','MAXIMUM'

    DO JFLDG = 1, INFG

      IF (IMASKG (JFLDG,JDOM) == 0) CYCLE

      CLPRINT = YLCPDSCG (JFLDG,JDOM)%CNOMA (1:YLCPDSCG (JFLDG,JDOM)%ILNOMA)//' '

      IF (PRESENT (CDDOMNAMES)) THEN

        WRITE(NULOUT,FMT='(1X, A16,''/'',A7,'' : '',3(E21.15,1X))') CLPRINT, CDDOMNAMES (JDOM),&
         & YLCPDSCG (JFLDG,JDOM)%ZAVE, YLCPDSCG (JFLDG,JDOM)%ZMIN, YLCPDSCG (JFLDG,JDOM)%ZMAX

      ELSE

        WRITE(NULOUT,FMT='(1X, A16,'' : '',3(E21.15,1X))') CLPRINT,&
        & YLCPDSCG (JFLDG,JDOM)%ZAVE, YLCPDSCG (JFLDG,JDOM)%ZMIN, YLCPDSCG (JFLDG,JDOM)%ZMAX

      ENDIF


    ENDDO

  ENDDO

ENDIF

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DUMPNORMS',1,ZHOOK_HANDLE)

END SUBROUTINE DUMPNORMS

SUBROUTINE DOWRMYFLDS

INTEGER (KIND=JPIM) :: JDOM
INTEGER (KIND=JPIM) :: IMIN, IMAX

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOWRMYFLDS',0,ZHOOK_HANDLE)

IF (YLIOOPTS%LDOWR) THEN

! task writes its own fields

  DO JDOM = 1, KDOM
    IMIN = IPTR (JDOM)+SUM (IPFAOVSZ (1:JDOM-1))
    IF (JDOM == KDOM) THEN
      IMAX = KDIMGVAL
    ELSE
      IMAX = IPTR (JDOM+1)+SUM (IPFAOVSZ (1:JDOM))-1
    ENDIF
    IF (KNFL > 0 .AND. ANY(IMASK(:,JDOM) /= 0)) THEN
      IF (PRESENT(YDFPUSERGEO)) THEN
        CALL OPENWRFACTX(YDVAB,YLFACTXS(JDOM),CDFPFN(JDOM),YDFPOPH(JDOM)%CFPCA,YDFPUSERGEO=YDFPUSERGEO(JDOM),KFPCHKDAT=KFPCHKDAT)
      ELSE
        CALL OPENWRFACTX(YDVAB,YLFACTXS(JDOM),CDFPFN(JDOM),YDFPOPH(JDOM)%CFPCA,YDGEOMETRY=YDGEOMETRY)
      ENDIF
    ENDIF
    CALL WRITEFLD(YLFACTXS (JDOM), YDCPDSC (:,JDOM), IMASK (:,JDOM), PVALCO (IMIN:IMAX,:))
  ENDDO

ENDIF

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOWRMYFLDS',1,ZHOOK_HANDLE)

END SUBROUTINE DOWRMYFLDS

SUBROUTINE DOWROTHERFLDS

USE IOCPTDESC_MOD, ONLY : IOCPTDESC_THAW

INTEGER (KIND=JPIM) :: IROC, JROC, JDOM, JFLDL, JFLDG
REAL (KIND=JPRB), ALLOCATABLE :: ZBUF (:,:)
INTEGER (KIND=JPIM) :: IBUF, IHDRSPK

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE_RECV
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOWROTHERFLDS',0,ZHOOK_HANDLE)


! MPI #1 receives fields from other procs
  
IHDRSPK = NIOCPTDESC_SIZE

ALLOCATE (ZBUF (((IHDRSPK*KDOM+KDIMGVAL) * MAXVAL (KNFD (IIOROOT:IIOLAST))),1))

DO IROC = IIOROOT, IIOLAST

  IF (IROC == IIOROOT) CYCLE
  IF (KNFD(IROC) == 0) CYCLE

  IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOWROTHERFLDS:RECV',0,ZHOOK_HANDLE_RECV)
  IF (PRESENT (KTAG) .AND. YLIOOPTS%LRECV_NOORDER) THEN
    CALL MPL_RECV (ZBUF, KTAG=KTAG, KFROM=JROC, CDSTRING='WRGATHFLNM:DOWROTHERFLDS')
  ELSE
    CALL MPL_RECV (ZBUF, KTAG=1, KSOURCE=IROC, CDSTRING='WRGATHFLNM:DOWROTHERFLDS')
    JROC = IROC
  ENDIF
  IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOWROTHERFLDS:RECV',1,ZHOOK_HANDLE_RECV)

  IBUF = 0

  DO JFLDL = 1, KNFD (JROC)

    JFLDG = KFLDOFF(JROC)+JFLDL

    DO JDOM = 1, KDOM

      YLCPDSCG (JFLDG, JDOM) = IOCPTDESC_THAW (ZBUF (IBUF+1:IBUF+IHDRSPK,1))
      IBUF = IBUF + IHDRSPK

      IF (YLCPDSCG (JFLDG, JDOM)%CNOMA == '') THEN
        IMASKG  (JFLDG, JDOM) = 0
      ELSE
        IMASKG  (JFLDG, JDOM) = 1
      ENDIF

      IF (KNFL > 0 .AND. IMASKG(JFLDG,JDOM) /= 0) THEN
        IF (PRESENT(YDFPUSERGEO)) THEN
          CALL OPENWRFACTX(YDVAB,YLFACTXS(JDOM),CDFPFN(JDOM),YDFPOPH(JDOM)%CFPCA,YDFPUSERGEO=YDFPUSERGEO(JDOM),KFPCHKDAT=KFPCHKDAT)
        ELSE
          CALL OPENWRFACTX(YDVAB,YLFACTXS(JDOM),CDFPFN(JDOM),YDFPOPH(JDOM)%CFPCA,YDGEOMETRY=YDGEOMETRY)
        ENDIF
        CALL WRITEFLD (YLFACTXS (JDOM), YLCPDSCG (JFLDG:JFLDG,JDOM),IMASKG (JFLDG:JFLDG,JDOM), ZBUF (IBUF+1:,1:1))
      ENDIF

      IBUF = IBUF + YLCPDSCG (JFLDG,JDOM)%ILONGD * JPPRCM
 
    ENDDO

  ENDDO

ENDDO

DEALLOCATE (ZBUF)

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOWROTHERFLDS',1,ZHOOK_HANDLE)

END SUBROUTINE DOWROTHERFLDS

SUBROUTINE DOSENDMYFLDS

USE IOCPTDESC_MOD, ONLY : IOCPTDESC_FREEZE

INTEGER (KIND=JPIM) :: JFLDL, JDOM, ITAG, IMIN, IMAX
TYPE (IOCPTDESC)    :: YLCPDSC1
REAL (KIND=JPRB), ALLOCATABLE :: ZBUF (:)
INTEGER (KIND=JPIM) :: IBUF, IHDRSPK

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE_COPY
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE_SEND
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOSENDMYFLDS',0,ZHOOK_HANDLE)

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOSENDMYFLDS:COPY',0,ZHOOK_HANDLE_COPY)

IHDRSPK = NIOCPTDESC_SIZE
ALLOCATE (ZBUF (IHDRSPK * INFL * KDOM + SUM (YDCPDSC%ILONGD) * JPPRCM))

IBUF = 0

! Pack data in ZBUF
DO JFLDL = 1, INFL
  DO JDOM = 1, KDOM
    YLCPDSC1 = YDCPDSC (JFLDL,JDOM)

    IF (IMASK (JFLDL,JDOM) == 0) YLCPDSC1%CNOMA = ''
    ZBUF (IBUF+1:IBUF+IHDRSPK) = IOCPTDESC_FREEZE (YLCPDSC1)
    IBUF = IBUF + IHDRSPK


    IMIN = IPTR (JDOM) + SUM (IPFAOVSZ (1:JDOM-1))
    IMAX = IPTR (JDOM) + SUM (IPFAOVSZ (1:JDOM-1)) + YLCPDSC1%ILONGD * JPPRCM - 1

    IF (IMAX > UBOUND (PVALCO, 1)) CALL ABOR1 ('WRGATHFLNM:DOSENDMYFLDS: SIZE MISMATCH')

    ZBUF (IBUF+1:IBUF+YLCPDSC1%ILONGD*JPPRCM) = PVALCO (IMIN:IMAX,JFLDL)

    IBUF = IBUF + YLCPDSC1%ILONGD * JPPRCM
  ENDDO
ENDDO

IF (IBUF /= SIZE (ZBUF)) CALL ABOR1 ('WRGATHFLNM:DOSENDMYFLDS: SIZE MISMATCH')

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOSENDMYFLDS:COPY',1,ZHOOK_HANDLE_COPY)

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOSENDMYFLDS:SEND',0,ZHOOK_HANDLE_SEND)

ITAG = 1
IF (PRESENT (KTAG) .AND. YLIOOPTS%LRECV_NOORDER) ITAG = KTAG

CALL MPL_SEND (ZBUF, KDEST=IIOROOT, KTAG=ITAG, KMP_TYPE=JP_BLOCKING_STANDARD,&
             & CDSTRING='WRGATHFLNM:DOSENDMYFLDS')

DEALLOCATE (ZBUF)

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOSENDMYFLDS:SEND',1,ZHOOK_HANDLE_SEND)

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOSENDMYFLDS',1,ZHOOK_HANDLE)

END SUBROUTINE DOSENDMYFLDS

SUBROUTINE DOWRMYFLDS1F

INTEGER (KIND=JPIM) :: JDOM, IMIN, IMAX

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOWRMYFLDS1F',0,ZHOOK_HANDLE)

DO JDOM = 1, KDOM

  IF (LLISIOROOT) THEN
    IF (PRESENT(YDFPUSERGEO)) THEN
      CALL OPENWRFACTX(YDVAB,YLFACTXS (JDOM),CDFPFN(JDOM),YDFPOPH(JDOM)%CFPCA,YDFPUSERGEO=YDFPUSERGEO(JDOM),KFPCHKDAT=KFPCHKDAT)
    ELSE
      CALL OPENWRFACTX(YDVAB,YLFACTXS (JDOM),CDFPFN(JDOM),YDFPOPH(JDOM)%CFPCA,YDGEOMETRY=YDGEOMETRY)
    ENDIF
  ENDIF

  IMIN = IPTR (JDOM)+SUM (IPFAOVSZ (1:JDOM-1))
  IF (JDOM == KDOM) THEN
    IMAX = KDIMGVAL
  ELSE
    IMAX = IPTR (JDOM+1)+SUM (IPFAOVSZ (1:JDOM))-1
  ENDIF

  CALL WRFLDCW_OPEN (YLWCTX1F, YLFACTXS (JDOM)%IUNITWR)

  CALL WRFLDCW_WRITE (YLWCTX1F, YDCPDSC (1:INFL,JDOM)%CNOMA, YDCPDSC (1:INFL,JDOM)%ILNOMA,&
                    & PVALCO (IMIN:IMAX,:),  YDCPDSC (1:INFL,JDOM)%ILONGD, IMASK (1:INFL,JDOM))

  CALL WRFLDCW_CLOSE (YLWCTX1F)

ENDDO

IF (LHOOK) CALL DR_HOOK ('WRGATHFLNM:DOWRMYFLDS1F',1,ZHOOK_HANDLE)

END SUBROUTINE DOWRMYFLDS1F

END SUBROUTINE WRGATHFLNM
