! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE WRGRIDALL_FP(YDFPS,YDGEOMETRY,YDGFL,YDSURF,YDCFU,YDXFU,YDMODEL,YDFLAG)

!**** *WRGRIDALL_FP*  - Send grid-point fields to FP server

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 15-04-2016

USE TYPE_MODEL         , ONLY : MODEL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGFL             , ONLY : TGFL
USE YOMCFU             , ONLY : TCFU
USE YOMXFU             , ONLY : TXFU
USE PARKIND1           , ONLY : JPRB, JPIM
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE IOFU_MOD           , ONLY : IOFU_COUNT,     IOFU_SELECTD,     NIOFUACT_WRITE
USE IOGRIDA_MOD        , ONLY : IOGRIDA_COUNT,  IOGRIDA_SELECTD,  NIOGRIDACT_WRITE
USE IOGRIDUA_MOD       , ONLY : IOGRIDUA_COUNT, IOGRIDUA_SELECTD, NIOGRIDUACT_WRITE
USE IOXFU_MOD          , ONLY : IOXFU_COUNT,    IOXFU_SELECTD,    NIOXFUACT_WRITE
USE YOMTAG             , ONLY : MTAG_MFIO_WRGRIDALL
USE IOFLDPTR_MOD       , ONLY : IOFLDPTR
USE YOMFP_SERV         , ONLY : FP_SERV
USE MFIOOPTS_MOD       , ONLY : MFIOFLAG

IMPLICIT NONE

TYPE (FP_SERV)      ,INTENT (INOUT) :: YDFPS
TYPE (GEOMETRY)     ,INTENT (IN)    :: YDGEOMETRY
TYPE (TGFL)         ,INTENT (INOUT) :: YDGFL
TYPE (TSURF)        ,INTENT (INOUT) :: YDSURF
TYPE (TCFU)         ,INTENT (INOUT) :: YDCFU
TYPE (TXFU)         ,INTENT (INOUT) :: YDXFU
TYPE (MODEL)        ,INTENT (INOUT) :: YDMODEL
TYPE (MFIOFLAG)     ,INTENT (IN)    :: YDFLAG

#include "wrfld_fp.intfb.h"

INTEGER (KIND=JPIM) :: IFNUM, IFCUR
TYPE (IOFLDPTR), ALLOCATABLE :: YLFLDSD (:)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRGRIDALL_FP',0,ZHOOK_HANDLE)

IFNUM = 0
IF (YDFLAG%LLWRFU)     CALL IOFU_COUNT(YDGEOMETRY,YDCFU,NIOFUACT_WRITE,IFNUM)
IF (YDFLAG%LLWRGRIDA)  CALL IOGRIDA_COUNT(YDGEOMETRY,YDSURF,YDMODEL%YRML_AOC%YRMCC,YDMODEL%YRML_PHY_G%YRDPHY, &
 & YDMODEL%YRML_PHY_MF%YRPHY,YDMODEL%YRML_PHY_MF%YRPHYDS,NIOGRIDACT_WRITE,IFNUM)
IF (YDFLAG%LLWRGRIDUA) CALL IOGRIDUA_COUNT(YDGEOMETRY,YDGFL,YDMODEL%YRML_GCONF%YGFL,NIOGRIDUACT_WRITE,IFNUM)
IF (YDFLAG%LLWRXFU)    CALL IOXFU_COUNT(YDGEOMETRY,YDXFU,NIOXFUACT_WRITE,IFNUM)

IF (IFNUM > 0) THEN

  ALLOCATE (YLFLDSD (IFNUM))

  IFCUR = 0
  IF (YDFLAG%LLWRFU)     CALL IOFU_SELECTD(YDGEOMETRY,  YDCFU,  NIOFUACT_WRITE,    YLFLDSD, IFCUR)
  IF (YDFLAG%LLWRGRIDA)  CALL IOGRIDA_SELECTD(YDGEOMETRY, YDSURF, YDMODEL%YRML_AOC%YRMCC, YDMODEL%YRML_PHY_G%YRDPHY, & 
 & YDMODEL%YRML_PHY_MF%YRPHY, YDMODEL%YRML_PHY_MF%YRPHYDS, NIOGRIDACT_WRITE,  YLFLDSD, IFCUR)
  IF (YDFLAG%LLWRGRIDUA) CALL IOGRIDUA_SELECTD(YDGEOMETRY, YDGFL, YDMODEL%YRML_GCONF%YGFL, NIOGRIDUACT_WRITE, YLFLDSD, IFCUR)
  IF (YDFLAG%LLWRXFU)    CALL IOXFU_SELECTD(YDGEOMETRY, YDXFU, NIOXFUACT_WRITE,   YLFLDSD, IFCUR)

  CALL WRFLD_FP(YDFPS,YDGEOMETRY,YDMODEL%YRML_GCONF%YRRIP%TSTEP,MTAG_MFIO_WRGRIDALL,1_JPIM,YLFLDSD,YDFPS%YIOS_GP_CL,YDFPS%YGP_DISTR)

  DEALLOCATE (YLFLDSD)

ENDIF


IF (LHOOK) CALL DR_HOOK ('WRGRIDALL_FP',1,ZHOOK_HANDLE)

END SUBROUTINE WRGRIDALL_FP

