! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE WRGRIDALL_MAP(YDGEOMETRY,YDGFL,YDSURF,YDCFU,YDXFU,YDMODEL,LDWRFU,LDWRGRIDA,LDWRGRIDUA,LDWRXFU,PIOPROC1A,PIOPROC2A)

!**** *WRGRIDALL_MAP*  - IO of all grid-point data

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 30-09-2013

!      Modifications :
!      O. Marsden: June 2015 CY42 YRGMV, YRGFL, YRSURF, YRGMV5, and YRGFL5 are now passed by argument


USE TYPE_MODEL         , ONLY : MODEL
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE YOMGFL             , ONLY : TGFL
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMCFU             , ONLY : TCFU
USE YOMXFU             , ONLY : TXFU
USE PARKIND1           , ONLY : JPRB, JPIM
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE IOFU_MOD           , ONLY : IOFU_COUNT,     IOFU_SELECTD,     NIOFUACT_WRITE
USE IOGRIDA_MOD        , ONLY : IOGRIDA_COUNT,  IOGRIDA_SELECTD,  NIOGRIDACT_WRITE
USE IOGRIDUA_MOD       , ONLY : IOGRIDUA_COUNT, IOGRIDUA_SELECTD, NIOGRIDUACT_WRITE
USE IOXFU_MOD          , ONLY : IOXFU_COUNT,    IOXFU_SELECTD,    NIOXFUACT_WRITE
USE IOGRID_MOD         , ONLY :                 IOGRID_SELECTF,   NIOGRIDCT_WRITE
USE YOMTAG             , ONLY : MTAG_MFIO_WRGRIDALL

USE YOMIO_SERV_MAP_PLAN, ONLY : IO_SERV_SEND_PLAN

USE IOFLDPTR_MOD, ONLY : IOFLDPTR

USE YOMIO_SERV, ONLY : IO_SERV_C001

IMPLICIT NONE

TYPE (GEOMETRY),   INTENT (IN)    :: YDGEOMETRY
TYPE (TGFL),       INTENT (INOUT) :: YDGFL
TYPE (TSURF),      INTENT (INOUT) :: YDSURF
TYPE (TCFU),       INTENT (INOUT) :: YDCFU
TYPE (TXFU),       INTENT (INOUT) :: YDXFU
TYPE (MODEL),      INTENT (INOUT) :: YDMODEL
LOGICAL,           INTENT (IN)    :: LDWRFU 
LOGICAL,           INTENT (IN)    :: LDWRGRIDA 
LOGICAL,           INTENT (IN)    :: LDWRGRIDUA 
LOGICAL,           INTENT (IN)    :: LDWRXFU
REAL (KIND=JPRB),  INTENT (IN)    :: PIOPROC1A
REAL (KIND=JPRB),  INTENT (IN)    :: PIOPROC2A

#include "io_serv_map_send_part1.intfb.h"
#include "io_serv_map_send_part2.intfb.h"

TYPE (IOFLDPTR),  ALLOCATABLE :: YLFLDGT (:) 
TYPE (IO_SERV_SEND_PLAN)      :: YLIOSMPP
INTEGER (KIND=JPIM)           :: IFNUM
INTEGER (KIND=JPIM)           :: IFCUR

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRGRIDALL_MAP',0,ZHOOK_HANDLE)

IFNUM = 0

IF (LDWRFU)     CALL IOFU_COUNT(YDGEOMETRY,YDCFU,NIOFUACT_WRITE,IFNUM)
IF (LDWRGRIDA)  CALL IOGRIDA_COUNT(YDGEOMETRY,YDSURF,YDMODEL%YRML_AOC%YRMCC,YDMODEL%YRML_PHY_G%YRDPHY,YDMODEL%YRML_PHY_MF%YRPHY, &
 &                                 YDMODEL%YRML_PHY_MF%YRPHYDS,NIOGRIDACT_WRITE,IFNUM)
IF (LDWRGRIDUA) CALL IOGRIDUA_COUNT(YDGEOMETRY,YDGFL,YDMODEL%YRML_GCONF%YGFL,NIOGRIDUACT_WRITE,IFNUM)
IF (LDWRXFU)    CALL IOXFU_COUNT(YDGEOMETRY,YDXFU,NIOXFUACT_WRITE,IFNUM)

IF (IFNUM > 0) THEN

  ALLOCATE (YLFLDGT (IFNUM))

  IFCUR = 0
  IF (LDWRFU)     CALL IOFU_SELECTD(YDGEOMETRY, YDCFU,  NIOFUACT_WRITE,    YLFLDGT, IFCUR)
  IF (LDWRGRIDA)  CALL IOGRIDA_SELECTD(YDGEOMETRY, YDSURF, YDMODEL%YRML_AOC%YRMCC, YDMODEL%YRML_PHY_G%YRDPHY, &
 &                                     YDMODEL%YRML_PHY_MF%YRPHY, YDMODEL%YRML_PHY_MF%YRPHYDS,  NIOGRIDACT_WRITE,  YLFLDGT, IFCUR)
  IF (LDWRGRIDUA) CALL IOGRIDUA_SELECTD(YDGEOMETRY, YDGFL, YDMODEL%YRML_GCONF%YGFL, NIOGRIDUACT_WRITE, YLFLDGT, IFCUR)
  IF (LDWRXFU)    CALL IOXFU_SELECTD(YDGEOMETRY, YDXFU,   NIOXFUACT_WRITE,   YLFLDGT, IFCUR)

  CALL IO_SERV_MAP_SEND_PART1(IO_SERV_C001,YDGEOMETRY%YRGEM%NGPTOT, YDGEOMETRY%YRGEM%NGPTOTG,YLFLDGT%YFLDDSC,MTAG_MFIO_WRGRIDALL,YLIOSMPP, &
 &                            PIOPROC1=PIOPROC1A,PIOPROC2=PIOPROC2A,PTSTEP=YDMODEL%YRML_GCONF%YRRIP%TSTEP)

  CALL IOGRID_SELECTF (YDGEOMETRY, NIOGRIDCT_WRITE, YLIOSMPP%YLBUFD, YLFLDGT)

  CALL IO_SERV_MAP_SEND_PART2 (IO_SERV_C001, YLIOSMPP)

  DEALLOCATE (YLFLDGT)

ENDIF

IF (LHOOK) CALL DR_HOOK ('WRGRIDALL_MAP',1,ZHOOK_HANDLE)

END SUBROUTINE WRGRIDALL_MAP

