! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE WRMLPPA_IO_SERV(YDGEOMETRY,YDGFL,YDSURF,YDCFU,YDXFU,YDSPEC,YDMODEL,LDWRGRIDA,LDWRGRIDUA,LDWRXFU,LDWRFU,LDWRSPECA,YDMCUF)

!**** *WRMLPPA_IO_SERV*  - Field selection for the IO server

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 10-10-2013

!      Modifications :

USE PARKIND1           , ONLY : JPRB, JPIM
USE YOMHOOK            , ONLY : LHOOK, DR_HOOK, JPHOOK
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMGFL             , ONLY : TGFL
USE YOMCFU             , ONLY : TCFU
USE YOMXFU             , ONLY : TXFU
USE TYPE_MODEL         , ONLY : MODEL
USE IOFU_MOD           , ONLY : IOFU_COUNT,     NIOFUACT_WRITE
USE IOGRIDA_MOD        , ONLY : IOGRIDA_COUNT,  NIOGRIDACT_WRITE
USE IOGRIDUA_MOD       , ONLY : IOGRIDUA_COUNT, NIOGRIDUACT_WRITE
USE IOXFU_MOD          , ONLY : IOXFU_COUNT,    NIOXFUACT_WRITE
USE IOSPECA_MOD        , ONLY : IOSPECA_COUNT,  NSPECACT_WRITE
USE YOMIO_SERV         , ONLY : IO_SERV_C001
USE YOMMCUF            , ONLY : TMCUF
USE SPECTRAL_FIELDS_MOD
IMPLICIT NONE

TYPE (GEOMETRY),       INTENT (IN)    :: YDGEOMETRY
TYPE (TGFL),           INTENT (INOUT) :: YDGFL
TYPE (TSURF),          INTENT (INOUT) :: YDSURF
TYPE (TCFU),           INTENT (INOUT) :: YDCFU
TYPE (TXFU),           INTENT (INOUT) :: YDXFU
TYPE (SPECTRAL_FIELD), INTENT (INOUT) :: YDSPEC
TYPE(MODEL),           INTENT (INOUT) :: YDMODEL
LOGICAL,               INTENT (IN)    :: LDWRFU 
LOGICAL,               INTENT (IN)    :: LDWRGRIDA 
LOGICAL,               INTENT (IN)    :: LDWRGRIDUA 
LOGICAL,               INTENT (IN)    :: LDWRXFU
LOGICAL,               INTENT (IN)    :: LDWRSPECA
TYPE(TMCUF),           INTENT(INOUT), OPTIONAL :: YDMCUF

#include "wrspeca_map.intfb.h"
#include "wrgridall_map.intfb.h"

! Spectral fields
INTEGER (KIND=JPIM)           :: IFNUM_SP
REAL (KIND=JPRB)              :: ZIOPROC1_SP, ZIOPROC2_SP
! Grid-point fields
INTEGER (KIND=JPIM)           :: IFNUM_GP
REAL (KIND=JPRB)              :: ZIOPROC1_GP, ZIOPROC2_GP
!
REAL (KIND=JPRB)              :: ZIOPROC

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRMLPPA_IO_SERV',0,ZHOOK_HANDLE)

IFNUM_SP = 0
IF (LDWRSPECA)  CALL IOSPECA_COUNT(YDGEOMETRY,YDMODEL%YRML_GCONF,YDMODEL%YRML_DYN%YRDYNA,NSPECACT_WRITE,IFNUM_SP,YDMCUF=YDMCUF)
IFNUM_GP = 0
IF (LDWRFU)     CALL IOFU_COUNT(YDGEOMETRY,YDCFU,NIOFUACT_WRITE,IFNUM_GP)
IF (LDWRGRIDA)  CALL IOGRIDA_COUNT(YDGEOMETRY,YDSURF,YDMODEL%YRML_AOC%YRMCC,YDMODEL%YRML_PHY_G%YRDPHY,YDMODEL%YRML_PHY_MF%YRPHY, &
 & YDMODEL%YRML_PHY_MF%YRPHYDS,NIOGRIDACT_WRITE,IFNUM_GP)
IF (LDWRGRIDUA) CALL IOGRIDUA_COUNT(YDGEOMETRY,YDGFL,YDMODEL%YRML_GCONF%YGFL,NIOGRIDUACT_WRITE,IFNUM_GP)
IF (LDWRXFU)    CALL IOXFU_COUNT(YDGEOMETRY,YDXFU,NIOXFUACT_WRITE,IFNUM_GP)

IF (IFNUM_SP + IFNUM_GP > 0) THEN

  ZIOPROC = REAL (IFNUM_GP, JPRB) / REAL (IFNUM_SP + IFNUM_GP, JPRB)
  ZIOPROC = IO_SERV_C001%PIOPROC1_MDL + ZIOPROC * (IO_SERV_C001%PIOPROC2_MDL - IO_SERV_C001%PIOPROC1_MDL)

  ZIOPROC1_GP = IO_SERV_C001%PIOPROC1_MDL
  ZIOPROC2_GP = ZIOPROC
  ZIOPROC1_SP = ZIOPROC
  ZIOPROC2_SP = IO_SERV_C001%PIOPROC2_MDL

  IF (IFNUM_GP > 0) THEN
    CALL WRGRIDALL_MAP(YDGEOMETRY, YDGFL, YDSURF, YDCFU, YDXFU, YDMODEL, LDWRFU, LDWRGRIDA, LDWRGRIDUA, LDWRXFU,&
 &                     PIOPROC1A=ZIOPROC1_GP,PIOPROC2A=ZIOPROC2_GP)
  ENDIF

  IF (IFNUM_SP > 0) THEN
    CALL WRSPECA_MAP(YDGEOMETRY,YDGFL,YDMODEL%YRML_GCONF,YDMODEL%YRML_DYN%YRDYN,YDMODEL%YRML_DYN%YRDYNA,&
     & YDSPEC,PIOPROC1A=ZIOPROC1_SP,PIOPROC2A=ZIOPROC2_SP,YDMCUF=YDMCUF)
  ENDIF

ENDIF

IF (LHOOK) CALL DR_HOOK ('WRMLPPA_IO_SERV',1,ZHOOK_HANDLE)

END SUBROUTINE WRMLPPA_IO_SERV

