! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE WRSPECA_MAP(YDGEOMETRY,YDGFL,YDML_GCONF,YDDYN,YDDYNA,YDSPEC,PIOPROC1A,PIOPROC2A,YDMCUF)

!**** *WRSPECA_MAP*  - IO of spectral fields with IO server

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 10-10-2013

!      Modifications :
!      P. Marguinaud : 10-10-2013 : Use only a fraction of IO tasks
!      O. Marsden: June 2015 CY42 YRGMV, YRGFL, and YRSURF are now passed by argument


USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE YOMDYN       , ONLY : TDYN
USE YOMDYNA      , ONLY : TDYNA
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL  , ONLY : TGFL
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK,  ONLY : LHOOK, DR_HOOK, JPHOOK

USE YOMMP0,  ONLY : MYSETV, NPRTRV
USE YOMCT0,  ONLY : LWRSPECA_GP

USE YOMTAG, ONLY : MTAG_MFIO_WRSPECA

USE IOSPECA_MOD, ONLY :&
                      & IOSPECA_SELECTD,&
                      & IOSPECA_SELECTF,&
                      & IOSPECA_START,&
                      & IOSPECA_COUNT,&
                      & IOSPECA_CTX,&
                      & IOSPECA_FINISH,&
                      & IOSPECA_VSETOFF,&
                      & NSPECACT_WRITE,&
                      & IOSPECA_FLDDESC_SP2GP

USE YOMIO_SERV,     ONLY : IO_SERV_C001

USE IOFLDDESC_MOD, ONLY : IOFLDDESC

USE YOMIO_SERV_MAP_PLAN, ONLY : IO_SERV_SEND_PLAN
USE SPECTRAL_FIELDS_MOD
USE YOMMCUF                , ONLY : TMCUF

IMPLICIT NONE

TYPE (GEOMETRY),       INTENT (IN)    :: YDGEOMETRY
TYPE (TGFL),           INTENT (INOUT) :: YDGFL
TYPE(TDYN)            ,INTENT(INOUT)  :: YDDYN
TYPE(TDYNA)           ,INTENT(INOUT)  :: YDDYNA
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
TYPE (SPECTRAL_FIELD), INTENT (INOUT) :: YDSPEC
REAL (KIND=JPRB),      INTENT (IN)    :: PIOPROC1A
REAL (KIND=JPRB),      INTENT (IN)    :: PIOPROC2A
TYPE(TMCUF)         , INTENT(INOUT), OPTIONAL :: YDMCUF

#include "io_serv_map_send_part1.intfb.h"
#include "io_serv_map_send_part2.intfb.h"

TYPE (IOFLDDESC), ALLOCATABLE :: YLFLDSCL (:)  ! List of field descriptors on this V-set
TYPE (IOFLDDESC), ALLOCATABLE :: YLFLDSCS (:)  ! List of field descriptors on this V-set, to be send to the IO server
TYPE (IOFLDDESC), ALLOCATABLE :: YLFLDSCG (:)  ! Global list of field descriptors
TYPE (IO_SERV_SEND_PLAN)      :: YLIOSMPP
INTEGER (KIND=JPIM)           :: IFNUMG        ! Global number of fields
INTEGER (KIND=JPIM)           :: IFNUML        ! Number of fields on this V-set
INTEGER (KIND=JPIM)           :: IFOFFL        ! Offset of fields of this V-set in global list
INTEGER (KIND=JPIM)           :: IVSETOFF (NPRTRV)
REAL (KIND=JPRB)              :: ZIOPROC1, ZIOPROC2
TYPE (IOSPECA_CTX)            :: YLIOSP

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!      -----------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('WRSPECA_MAP',0,ZHOOK_HANDLE)

CALL IOSPECA_START(YDGEOMETRY,YDGFL,YDML_GCONF,YDDYNA,NSPECACT_WRITE,YLIOSP,YDSPEC)

CALL IOSPECA_COUNT(YDGEOMETRY,YDML_GCONF,YDDYNA,NSPECACT_WRITE,IFNUMG,YDMCUF=YDMCUF)

IF (IFNUMG > 0) THEN

  ALLOCATE (YLFLDSCG (IFNUMG))

  CALL IOSPECA_SELECTD(YDGEOMETRY,YDML_GCONF,YDDYNA,NSPECACT_WRITE,YLFLDSCG,YDMCUF=YDMCUF)

  CALL IOSPECA_VSETOFF (YLFLDSCG%IVSET, KVSETOFF=IVSETOFF)

  IFNUML = COUNT (YLFLDSCG%IVSET == MYSETV)
  IFOFFL = IVSETOFF (MYSETV)

  ZIOPROC1 = REAL (IFOFFL, JPRB) / REAL (IFNUMG, JPRB)
  ZIOPROC2 = REAL (IFOFFL+IFNUML, JPRB) / REAL (IFNUMG, JPRB)

  ZIOPROC1 = PIOPROC1A + ZIOPROC1 * (PIOPROC2A - PIOPROC1A)
  ZIOPROC2 = PIOPROC1A + ZIOPROC2 * (PIOPROC2A - PIOPROC1A)

  IF (IFNUML > 0) THEN

    ALLOCATE (YLFLDSCL (IFNUML), YLFLDSCS (IFNUML))
    YLFLDSCL = PACK (YLFLDSCG, YLFLDSCG%IVSET == MYSETV)

    IF (LWRSPECA_GP) THEN
      CALL IOSPECA_FLDDESC_SP2GP (YDGEOMETRY, YLFLDSCL, YLFLDSCS, LDRNONLY=.TRUE.)
    ELSE
      YLFLDSCS = YLFLDSCL
    ENDIF

    CALL IO_SERV_MAP_SEND_PART1 (IO_SERV_C001, YDGEOMETRY%YRDIM%NSPEC2, YDGEOMETRY%YRDIM%NSPEC2G, YLFLDSCS, &
                               & MTAG_MFIO_WRSPECA, YLIOSMPP, PIOPROC1=ZIOPROC1, PIOPROC2=ZIOPROC2, PTSTEP=YDML_GCONF%YRRIP%TSTEP)

    CALL IOSPECA_SELECTF(YDGEOMETRY, YDML_GCONF%YGFL,YDDYN,NSPECACT_WRITE, YLIOSP, IFNUML, 0_JPIM,&
                        & 0_JPIM, YLFLDSCL, YLIOSMPP%YLBUFD, YDSPEC=YDSPEC,YDMCUF=YDMCUF)

    CALL IO_SERV_MAP_SEND_PART2 (IO_SERV_C001, YLIOSMPP)

    DEALLOCATE (YLFLDSCL, YLFLDSCS)

  ENDIF

  IO_SERV_C001%LSENTFLD = .TRUE.

  DEALLOCATE (YLFLDSCG)

ENDIF 

CALL IOSPECA_FINISH (YDGEOMETRY, YDDYNA,NSPECACT_WRITE, YLIOSP, YDSPEC=YDSPEC)

IF (LHOOK) CALL DR_HOOK('WRSPECA_MAP',1,ZHOOK_HANDLE)

END SUBROUTINE WRSPECA_MAP

