! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE CALL_SL_HEAP2(YDGEOMETRY,YDGMV,&
 & YDMODEL,PGFL,&
 & YDSL,KVSEPC,KVSEPL,PB1,PB2,PWRL9,PGMVT1,PGMVT1S,PGFLT1,PGFLPC,&
 & KL0,PLSCAW,PUP9,PVP9,PTP9,PGFLP9)

!****-------------------------------------------------------------------
!**** *CALL_SL_HEAP2* - Semi-lagrangian driver preferring memory on heap
!****-------------------------------------------------------------------
!     Purpose.   call_sl driver using memory on heap for large arrays
!     --------   allocates memory (if possible) only once

!**   Interface.
!     ----------
!        *CALL* *CALL_SL_HEAP2 (..) -- NOPT_MEMORY=2

!        Explicit arguments :  CDCONF - configuration of work (see doc.)
!        --------------------

!        Implicit arguments :  None.
!        --------------------

!     Method.
!     -------

!     Externals.   See includes below.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     Author.
!     -------
!        S. Saarinen, ECMWF, 30-Oct-2017

! Modifications
! -------------
! End Modifications
!-------------------------------------------------------------------------------

USE TYPE_MODEL   , ONLY : MODEL
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV       , ONLY : TGMV
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK

USE EINT_MOD     , ONLY : SL_STRUCT

!     ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)    ,INTENT(IN)    :: YDGEOMETRY
TYPE(TGMV)        ,INTENT(INOUT) :: YDGMV
TYPE(MODEL)       ,INTENT(INOUT) :: YDMODEL
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM, &
 &                                       YDGEOMETRY%YRDIM%NGPBLKS)
TYPE(SL_STRUCT)   ,INTENT(INOUT) :: YDSL
INTEGER(KIND=JPIM),INTENT(INOUT) :: KVSEPC(YDGEOMETRY%YRDIM%NGPBLKS)
INTEGER(KIND=JPIM),INTENT(INOUT) :: KVSEPL(YDGEOMETRY%YRDIM%NGPBLKS)
INTEGER(KIND=JPIM),INTENT(OUT)   :: KL0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,0:3,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PB1(YDSL%NASLB1,YDMODEL%YRML_DYN%YRPTRSLB1%NFLDSLB1)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PB2(YDGEOMETRY%YRDIM%NPROMA,YDMODEL%YRML_DYN%YRPTRSLB2%NFLDSLB2,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(IN)    :: PWRL9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMVT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGMV%YT1%NDIM,&
 &                                         YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMVT1S(YDGEOMETRY%YRDIM%NPROMA,YDGMV%YT1%NDIMS,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGFLT1(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM1, &
 &                                         YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGFLPC(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIMPC,&
 &                                         YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PUP9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PVP9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PTP9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PGFLP9(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NUMFLDS,&
 &                                         YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(OUT)   :: PLSCAW(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DYN%YYTLSCAW%NDIM,&
 &                                         YDGEOMETRY%YRDIM%NGPBLKS)
!     ------------------------------------------------------------------
LOGICAL, SAVE :: LLINITALLOC = .FALSE.
LOGICAL :: LLREALLOC
INTEGER(KIND=JPIM), SAVE :: IDX_ILH0(3) = (/0,0,0/)
INTEGER(KIND=JPIM), SAVE :: IDX_ZRSCAW(4) = (/0,0,0,0/)
INTEGER(KIND=JPIM), SAVE :: IDX_ZSCO(4) = (/0,0,0,0/)
INTEGER(KIND=JPIM), ALLOCATABLE, SAVE :: ILH0 (:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE, SAVE :: ZRSCAW(:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE, SAVE :: ZSCO(:,:,:,:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

#include "call_sl.intfb.h"

IF (LHOOK) CALL DR_HOOK('CALL_SL_HEAP2',0,ZHOOK_HANDLE)

LLREALLOC = .FALSE.
IF (LLINITALLOC) THEN
  IF (.NOT. ALL(IDX_ILH0 == &
    & (/YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG, &
    & YDGEOMETRY%YRDIM%NGPBLKS/))) LLREALLOC = .TRUE.
  IF (.NOT. ALL(IDX_ZRSCAW == &
    & (/YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG, &
    & YDMODEL%YRML_DYN%YYTRSCAW%NDIM,YDGEOMETRY%YRDIM%NGPBLKS/))) LLREALLOC = .TRUE.
  IF (.NOT. ALL(IDX_ZSCO == &
    & (/YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG, &
    & YDMODEL%YRML_DYN%YYTSCO%NDIM,YDGEOMETRY%YRDIM%NGPBLKS/))) LLREALLOC = .TRUE.
  IF (LLREALLOC) THEN
    DEALLOCATE(ZSCO)
    DEALLOCATE(ZRSCAW)
    DEALLOCATE(ILH0)
  ENDIF
ELSE ! (.not.LLINITALLOC) -- occurs only once
   LLINITALLOC = .TRUE.
   LLREALLOC = .TRUE.
ENDIF

IF (LLREALLOC) THEN
   IDX_ILH0 = (/YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDGEOMETRY%YRDIM%NGPBLKS/)
   IDX_ZRSCAW = (/YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DYN%YYTRSCAW%NDIM,YDGEOMETRY%YRDIM%NGPBLKS/)
   IDX_ZSCO = (/YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DYN%YYTSCO%NDIM,YDGEOMETRY%YRDIM%NGPBLKS/)

   ALLOCATE(ILH0 (YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,0:3,YDGEOMETRY%YRDIM%NGPBLKS))
   ALLOCATE(ZRSCAW(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DYN%YYTRSCAW%NDIM,YDGEOMETRY%YRDIM%NGPBLKS))
   ALLOCATE(ZSCO(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_DYN%YYTSCO%NDIM,YDGEOMETRY%YRDIM%NGPBLKS))
ENDIF

CALL CALL_SL(YDGEOMETRY,YDGMV,&
 & YDMODEL,PGFL,&
 & YDSL,KVSEPC,KVSEPL,PB1,PB2,PWRL9,PGMVT1,PGMVT1S,PGFLT1,PGFLPC,&
 & KL0,PLSCAW,PUP9,PVP9,PTP9,PGFLP9,ILH0,ZRSCAW,ZSCO)

IF (LHOOK) CALL DR_HOOK('CALL_SL_HEAP2',1,ZHOOK_HANDLE)

END SUBROUTINE CALL_SL_HEAP2
