! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE FV_GRADIENT(YDGEOMETRY,PVAR,PGRAD)

!**** *FV_GRADIENT* - COMPUTES GRID-POINT DERIVATIVES using FINITE VOLUME

!     PURPOSE.  

!**   INTERFACE.
!     ----------
!        *CALL* FV_GRADIENT*(..)*

!        EXPLICIT ARGUMENTS
!        --------------------
!         PVAR - grid-pointfield
!         PGRAD - gradient

!        IMPLICIT ARGUMENTS :   
!        --------------------   

!     METHOD.
!     -------
!        SEE DOCUMENTATION

!     EXTERNALS.     NONE.
!     ----------

!     REFERENCE.
!     ----------
!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!      Mats Hamrud AND Willem Deconinck  *ECMWF*
!      ORIGINAL : Nov 2015

!     MODIFICATIONS.
!     --------------
!     ------------------------------------------------------------------

USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST   , ONLY : RPI, RA
#ifdef WITH_ATLAS
USE ATLAS_MODULE, ONLY : ATLAS_FIELD, ATLAS_MESH_NODES, ATLAS_MESH_EDGES, &
                       & ATLAS_CONNECTIVITY
#endif
USE TYPE_GEOMETRY , ONLY : GEOMETRY

IMPLICIT NONE

TYPE(GEOMETRY), INTENT(IN)  :: YDGEOMETRY
REAL(KIND=JPRB),INTENT(IN)  :: PVAR(:,:)
REAL(KIND=JPRB),INTENT(OUT) :: PGRAD(:,:,:)

#ifdef WITH_ATLAS
TYPE(ATLAS_FIELD) :: LONLAT
TYPE(ATLAS_FIELD) :: DUAL_VOLUMES
TYPE(ATLAS_FIELD) :: DUAL_NORMALS
TYPE(ATLAS_FIELD) :: IS_POLE_EDGE
TYPE(ATLAS_FIELD) :: NODE2EDGE_SIGN
TYPE(ATLAS_MESH_NODES) :: NODES
TYPE(ATLAS_MESH_EDGES) :: EDGES
TYPE(ATLAS_CONNECTIVITY) :: NODE2EDGE
TYPE(ATLAS_CONNECTIVITY) :: EDGE2NODE
LOGICAL,            POINTER :: LLIS_POLE_EDGE(:)
REAL(KIND=JPRB),    POINTER :: ZLONLAT(:,:)
REAL(KIND=JPRB),    POINTER :: ZDUAL_VOLUMES(:)
REAL(KIND=JPRB),    POINTER :: ZDUAL_NORMALS(:,:)
REAL(KIND=JPRB),    POINTER :: ZNODE2EDGE_SIGN(:,:)
INTEGER(KIND=JPIM), POINTER :: IEDGE2NODE(:,:)
INTEGER(KIND=JPIM), POINTER :: INODE2EDGE(:)
INTEGER(KIND=JPIM)          :: INODE2EDGE_SIZE
INTEGER(KIND=JPIM) :: JNODE,JEDGE,JLEV,INEDGES,IP1,IP2,IEDGE,INODES,ILEVS
REAL(KIND=JPRB), ALLOCATABLE :: ZAVG_S(:,:,:)
REAL(KIND=JPRB) :: ZAVG,ZSIGN,ZMETRIC_X,ZMETRIC_Y,ZSCALE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('FV_GRADIENT',0,ZHOOK_HANDLE)

NODES          = YDGEOMETRY%YRATLAS%MESH%NODES()
EDGES          = YDGEOMETRY%YRATLAS%MESH%EDGES()
LONLAT         = NODES%LONLAT()
EDGE2NODE      = EDGES%NODE_CONNECTIVITY()
NODE2EDGE      = NODES%EDGE_CONNECTIVITY()
DUAL_VOLUMES   = NODES%FIELD('dual_volumes')
DUAL_NORMALS   = EDGES%FIELD('dual_normals')
IS_POLE_EDGE   = EDGES%FIELD('is_pole_edge')
NODE2EDGE_SIGN = NODES%FIELD('node2edge_sign')

ILEVS = SIZE(PVAR(:,1))
ZSCALE = RPI/180.0_JPRB * RPI/180.0_JPRB * RA

CALL LONLAT%DATA(ZLONLAT)
CALL EDGE2NODE%DATA(IEDGE2NODE)
CALL DUAL_VOLUMES%DATA(ZDUAL_VOLUMES)
CALL DUAL_NORMALS%DATA(ZDUAL_NORMALS)
CALL IS_POLE_EDGE%DATA(LLIS_POLE_EDGE)
CALL NODE2EDGE_SIGN%DATA(ZNODE2EDGE_SIGN)

INEDGES = SIZE(ZDUAL_NORMALS)/2
ALLOCATE(ZAVG_S(2,ILEVS,INEDGES))
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JEDGE,IP1,IP2,JLEV,ZAVG)
DO JEDGE=1,INEDGES
  IP1 = IEDGE2NODE(1,JEDGE)
  IP2 = IEDGE2NODE(2,JEDGE)
  DO JLEV=1,ILEVS
    ZAVG = (PVAR(JLEV,IP1)+PVAR(JLEV,IP2)) * 0.5_JPRB
    ZAVG_S(1,JLEV,JEDGE) = ZDUAL_NORMALS(1,JEDGE)*RPI/180.0_JPRB * ZAVG
    ZAVG_S(2,JLEV,JEDGE) = ZDUAL_NORMALS(2,JEDGE)*RPI/180.0_JPRB * ZAVG
  ENDDO
ENDDO
!$OMP END PARALLEL DO

INODES = SIZE(ZLONLAT)/2
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JNODE,JLEV,INODE2EDGE,INODE2EDGE_SIZE,JEDGE,IEDGE,ZSIGN,ZMETRIC_X,ZMETRIC_Y)
DO JNODE=1,INODES
  DO JLEV=1,ILEVS
    PGRAD(1,JLEV,JNODE) = 0.0_JPRB
    PGRAD(2,JLEV,JNODE) = 0.0_JPRB
  ENDDO
  CALL NODE2EDGE%ROW(JNODE,INODE2EDGE,INODE2EDGE_SIZE)
  DO JEDGE=1,INODE2EDGE_SIZE
    IEDGE = INODE2EDGE(JEDGE)
    ZSIGN = ZNODE2EDGE_SIGN(JEDGE,JNODE)
    DO JLEV=1,ILEVS
      PGRAD(1,JLEV,JNODE) =  PGRAD(1,JLEV,JNODE)+ZSIGN*ZAVG_S(1,JLEV,IEDGE)
      PGRAD(2,JLEV,JNODE) =  PGRAD(2,JLEV,JNODE)+ZSIGN*ZAVG_S(2,JLEV,IEDGE)
    ENDDO
  ENDDO
  ZMETRIC_Y = 1._JPRB/(ZDUAL_VOLUMES(JNODE)*ZSCALE)
  ZMETRIC_X = ZMETRIC_Y/COS(ZLONLAT(2,JNODE)*RPI/180.0_JPRB)
  DO JLEV=1,ILEVS
    PGRAD(1,JLEV,JNODE) = PGRAD(1,JLEV,JNODE)*ZMETRIC_X
    PGRAD(2,JLEV,JNODE) = PGRAD(2,JLEV,JNODE)*ZMETRIC_Y
  ENDDO
ENDDO
!$OMP END PARALLEL DO

CALL LONLAT%FINAL()
CALL DUAL_VOLUMES%FINAL()
CALL DUAL_NORMALS%FINAL()
CALL IS_POLE_EDGE%FINAL()
CALL NODE2EDGE_SIGN%FINAL()
CALL NODES%FINAL()
CALL EDGES%FINAL()
CALL NODE2EDGE%FINAL()
CALL EDGE2NODE%FINAL()

IF (LHOOK) CALL DR_HOOK('FV_GRADIENT',1,ZHOOK_HANDLE)
#endif
END SUBROUTINE FV_GRADIENT

