! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE GPTOSPTOGP(YDGEOMETRY,YDGMV,YDML_GCONF,YDML_DYN,PGMV,PGMVS,PGFL,PPGTERM)

! GPTOSPTOGP
!
! Externals
! ---------
! Method
! ------
!
!    Calculate pressure gradient term in the momentum equation in grid-point space 
!    in an identical way as done in CPG_GP_HYD.
!    Then transform it to sepctral space and back to remove grid point aliasing.

!   OUTPUT: 
!   PPGTERM   - de-aliased pressure gradient term 
!   eventually other quantities to be re-used:
!     - full level: gz, grad gz E-W&N-S, RT, grad RT E-W&N-S  
!     - half level: gz, grad gz E-W&N-S
!
! Reference
! ---------

! Author
! ------
!   I. Polichtchouk (2020)

!   Modifications
!   -------------
!   F. Vana  21-Sep-2020: More flexibility to memory use & cleaning

!------------------------------------------------------------------

USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE MODEL_DYNAMICS_MOD , ONLY : MODEL_DYNAMICS_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV       , ONLY : TGMV
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST       , ONLY : RD, RV
USE YOMMP0       , ONLY : MYSETV ,NPRTRV
USE INTDYN_MOD   , ONLY : YYTXYB0, YYTXYBDER0, TPG_TYPE

! -----------------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY)               ,INTENT(IN)    :: YDGEOMETRY
TYPE(TGMV)                   ,INTENT(INOUT) :: YDGMV
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN)    :: YDML_GCONF
TYPE(MODEL_DYNAMICS_TYPE)    ,INTENT(IN)    :: YDML_DYN
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMV(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,&
 & YDGMV%NDIMGMV,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGMVS(YDGEOMETRY%YRDIM%NPROMA,YDGMV%NDIMGMVS,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB)   ,INTENT(INOUT) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG, &
 & YDML_GCONF%YGFL%NDIM,YDGEOMETRY%YRDIM%NGPBLKS)
TYPE(TPG_TYPE)    ,INTENT(INOUT) :: PPGTERM(YDGEOMETRY%YRDIM%NGPBLKS)


! -----------------------------------------------------------------------------

INTEGER(KIND=JPIM), PARAMETER :: JFIELDS = 2
LOGICAL            :: LLSTR
INTEGER(KIND=JPIM) :: JROF, JKGLO, IBL, IOFF, IST, ICEND, JL, JB, IFLDSIN, IFLD, IFLAG
REAL(KIND=JPRB)    :: ZEPS

REAL(KIND=JPRB)            :: ZRTLNSPL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)            :: ZRTLNSPM(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)            :: ZXYB0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYB0%NDIM)
REAL(KIND=JPRB)            :: ZXYBDER0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYBDER0%NDIM)
REAL(KIND=JPRB)            :: ZPRCP0(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB)            :: ZOROGL(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB)            :: ZOROGM(YDGEOMETRY%YRDIM%NPROMA) 

REAL(KIND=JPRB) :: ZPRESH(YDGEOMETRY%YRDIM%NPROMA,0:YDGEOMETRY%YRDIMV%NFLEVG),&
 &                 ZPRESF(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZSP0L(YDGEOMETRY%YRDIM%NPROMA),ZSP0M(YDGEOMETRY%YRDIM%NPROMA)

REAL(KIND=JPRB)            :: ZPHIF0FORTR(YDGEOMETRY%YRGEM%NGPTOT,JFIELDS*YDGEOMETRY%YRDIMV%NFLEVG,1)
REAL(KIND=JPRB)            :: ZPHI0DERS(YDGEOMETRY%YRGEM%NGPTOT,2*YDGEOMETRY%YRDIMV%NFLEVG,1)
INTEGER(KIND=JPIM)         :: INUMFLD(NPRTRV)
INTEGER(KIND=JPIM), ALLOCATABLE :: IVSETSC(:)
REAL(KIND=JPRB), ALLOCATABLE    :: ZSPSCAL(:,:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

! -----------------------------------------------------------------------------

#include "dir_trans.h"
#include "inv_trans.h"
#include "gpmpfc.intfb.h"
#include "gpgeo.intfb.h"
#include "gphpre.intfb.h"
#include "gpgrxyb.intfb.h"
#include "gprcp.intfb.h"
#include "gpgrp.intfb.h"
#include "gprt.intfb.h"
#include "gpgrgeo.intfb.h"
! -----------------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('GPTOSPTOGP',0,ZHOOK_HANDLE)

ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, &
 & YDOROG=>YDGEOMETRY%YROROG, YDGSGEOM=>YDGEOMETRY%YRGSGEOM, &
 & YDVAB=>YDGEOMETRY%YRVAB, YDCVER=>YDGEOMETRY%YRCVER, YQ=>YDML_GCONF%YGFL%YQ, &
 & YDDYN=>YDML_DYN%YRDYN, YDDYNA=>YDML_DYN%YRDYNA)
ASSOCIATE(NGPBLKS=>YDDIM%NGPBLKS, NPROMA=>YDDIM%NPROMA, NRESOL=>YDDIM%NRESOL, &
 & NSPEC2=>YDDIM%NSPEC2, NFLEVG=>YDDIMV%NFLEVG, NGPTOT=>YDGEM%NGPTOT, &
 & RSTRET=>YDGEM%RSTRET, YT0=>YDGMV%YT0)
! -----------------------------------------------------------------------------


!*       0.    PRELIMINARY INITIALISATIONS.
! 

ZEPS=100.0_JPRB*TINY(1.0_JPRB)
LLSTR=(ABS(RSTRET-1.0_JPRB)>ZEPS)


! =============================================
! compute 3D geop. height in grid point space 
! =============================================

!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) &
!$OMP& PRIVATE (JKGLO,IOFF,IST,IBL,ICEND) &
!$OMP& PRIVATE (ZPRESH,ZSP0L,ZSP0M,ZPRESF,ZXYB0,ZXYBDER0,ZPRCP0) &
!$OMP& PRIVATE (JROF,JL,ZRTLNSPL,ZRTLNSPM,ZOROGL,ZOROGM)
DO JKGLO=1,NGPTOT,NPROMA
  IBL=(JKGLO-1)/NPROMA+1
  IOFF=JKGLO
  IST=1
  ICEND=MIN(NPROMA,NGPTOT-JKGLO+1)

  IF (.NOT.YDDYNA%LPGREUSE) THEN
    !ALLOCATE(PPGTERM(IBL)%PHI0F(NPROMA,NFLEVG)) ! already allocated
    ALLOCATE(PPGTERM(IBL)%PHI0FL(NPROMA,NFLEVG))
    ALLOCATE(PPGTERM(IBL)%PHI0FM(NPROMA,NFLEVG))
    ALLOCATE(PPGTERM(IBL)%RT0(NPROMA,NFLEVG))
    ALLOCATE(PPGTERM(IBL)%RT0L(NPROMA,NFLEVG))
    ALLOCATE(PPGTERM(IBL)%RT0M(NPROMA,NFLEVG))
    ALLOCATE(PPGTERM(IBL)%PHI0H(NPROMA,0:NFLEVG))
    ALLOCATE(PPGTERM(IBL)%PHI0HL(NPROMA,0:NFLEVG))
    ALLOCATE(PPGTERM(IBL)%PHI0HM(NPROMA,0:NFLEVG))
  ENDIF

  IF(LLSTR) THEN
    IFLAG=0
    CALL GPMPFC(YDGMV,YDML_GCONF,YDDYN,YDDYNA,NPROMA,NFLEVG,IST,ICEND,IFLAG,&
     &   YDGSGEOM(IBL)%GM,PGMV,PGMVS,PGFL)
  ENDIF

  ! ZPRESH, ZPRESF, ZXYB0:
  DO JROF=IST,ICEND
    ZPRESH(JROF,NFLEVG)=EXP(PGMVS(JROF,YT0%MSP,IBL))
    ZSP0L(JROF)=ZPRESH(JROF,NFLEVG)*PGMVS(JROF,YT0%MSPL,IBL)
    ZSP0M(JROF)=ZPRESH(JROF,NFLEVG)*PGMVS(JROF,YT0%MSPM,IBL)
  ENDDO
  !*     COMPUTE ZPRESH,ZXYB0,ZPRESF
  CALL GPHPRE(NPROMA,NFLEVG,IST,ICEND,YDVAB,YDCVER,ZPRESH,PXYB=ZXYB0,PRESF=ZPRESF)

  !*     COMPUTE ZXYBDER0
  CALL GPGRXYB(NPROMA,IST,ICEND,NFLEVG,.FALSE.,YDVAB,YDCVER,ZSP0L,ZSP0M,ZXYB0,ZXYBDER0)

  !*     COMPUTE "R"
  CALL GPRCP(NPROMA,IST,ICEND,NFLEVG,PGFL=PGFL(:,:,:,IBL),PR=ZPRCP0)

  !*     COMPUTE SURFACE GEOPOTENTIAL HEIGHT AND ITS GRADIENT
  PPGTERM(IBL)%PHI0H(IST:ICEND,NFLEVG)=YDOROG(IBL)%OROG(IST:ICEND)
  ZOROGL(IST:ICEND)=YDOROG(IBL)%OROGL(IST:ICEND)*YDGSGEOM(IBL)%GM(IST:ICEND)
  ZOROGM(IST:ICEND)=YDOROG(IBL)%OROGM(IST:ICEND)*YDGSGEOM(IBL)%GM(IST:ICEND)

  !* computes RT and its gradient
  CALL GPRT(YDDYNA%LSPRT,NPROMA,IST,ICEND,NFLEVG,RD,RV,&
   & ZPRCP0,PGMV(:,:,YT0%MT,IBL),PGMV(:,:,YT0%MTL,IBL),PGMV(:,:,YT0%MTM,IBL),&
   & PGFL(:,:,YQ%MPL,IBL),PGFL(:,:,YQ%MPM,IBL),&
   & PPGTERM(IBL)%RT0,PPGTERM(IBL)%RT0L,PPGTERM(IBL)%RT0M)

  !*     COMPUTES THE GEOPOTENTIAL HEIGHT "gz" AND ITS GRADIENT.

  !* "gz" at full levels and half levels.
  CALL GPGEO(NPROMA,IST,ICEND,NFLEVG,&
   & PPGTERM(IBL)%PHI0H,PPGTERM(IBL)%PHI0F,PGMV(:,:,YT0%MT,IBL),&
   & ZPRCP0,ZXYB0(:,:,YYTXYB0%M_LNPR),ZXYB0(:,:,YYTXYB0%M_ALPH),&
   & YDGEOMETRY%YRVERT_GEOM)

  ! * "grad gz" at full levels and half levels.
  CALL GPGRGEO(YDGEOMETRY,NPROMA,IST,ICEND,NFLEVG,&
   & PPGTERM(IBL)%RT0,PPGTERM(IBL)%RT0L,PPGTERM(IBL)%RT0M,&
   & ZXYB0(:,:,YYTXYB0%M_LNPR),ZXYB0(:,:,YYTXYB0%M_ALPH),ZXYBDER0,&
   & ZOROGL,ZOROGM,&
   & PPGTERM(IBL)%PHI0FL,PPGTERM(IBL)%PHI0FM,PPGTERM(IBL)%PHI0HL,PPGTERM(IBL)%PHI0HM)

  !* COMPUTES THE PRESSURE FORCE FOR THE RHS OF MOMENTUM EQN.
  CALL GPGRP(YDGEOMETRY,IST,ICEND,&
   & PPGTERM(IBL)%RT0,PPGTERM(IBL)%RT0L,PPGTERM(IBL)%RT0M,ZSP0L,ZSP0M,ZXYB0,ZXYBDER0,&
   & PPGTERM(IBL)%PHI0HL,PPGTERM(IBL)%PHI0HM,PPGTERM(IBL)%PHI0FL,PPGTERM(IBL)%PHI0FM,&
   & ZRTLNSPL,ZRTLNSPM)

  ! fill array ready for direct transform
  DO JL=1,NFLEVG
    DO JROF=IST,ICEND
      ZPHIF0FORTR(IOFF+JROF-1,JL,1)=ZRTLNSPL(JROF,JL)
      ZPHIF0FORTR(IOFF+JROF-1,1*NFLEVG+JL,1)=ZRTLNSPM(JROF,JL)
    ENDDO
  ENDDO

  ! Release memory
  IF (.NOT.YDDYNA%LPGREUSE) THEN
    !DEALLOCATE(PPGTERM(IBL)%PHI0F)
    DEALLOCATE(PPGTERM(IBL)%PHI0FL, PPGTERM(IBL)%PHI0FM, &
     & PPGTERM(IBL)%RT0, PPGTERM(IBL)%RT0L, PPGTERM(IBL)%RT0M, &
     & PPGTERM(IBL)%PHI0H, PPGTERM(IBL)%PHI0HL, PPGTERM(IBL)%PHI0HM)
  ENDIF

ENDDO
!$OMP END PARALLEL DO

! setup trans
IFLDSIN=JFIELDS*NFLEVG
INUMFLD(:)=IFLDSIN/NPRTRV
DO JL=1,MOD(IFLDSIN,NPRTRV)
  INUMFLD(JL)=INUMFLD(JL)+1
ENDDO

ALLOCATE(IVSETSC(IFLDSIN))
IFLD=0
DO JB=1,NPRTRV
  DO JL=1,INUMFLD(JB)
    IFLD=IFLD+1
    IVSETSC(IFLD)=JB
  ENDDO
ENDDO

! =========================================================
! transfrom the pressure force to spectral space and then 
! back to de-alias in grid-point space
! =========================================================


ALLOCATE(ZSPSCAL(INUMFLD(MYSETV),NSPEC2))
CALL DIR_TRANS(PSPSCALAR=ZSPSCAL(:,:),KVSETSC=IVSETSC(:),KRESOL=NRESOL,KPROMA=NGPTOT,PGP=ZPHIF0FORTR)
CALL INV_TRANS(PSPSCALAR=ZSPSCAL,LDSCDERS=.FALSE.,KVSETSC=IVSETSC(:),KRESOL=NRESOL,KPROMA=NGPTOT,PGP=ZPHI0DERS)
DEALLOCATE(ZSPSCAL)

!$OMP PARALLEL DO SCHEDULE(DYNAMIC,1) &
!$OMP& PRIVATE (JKGLO,IOFF,IST,IBL,ICEND) &
!$OMP& PRIVATE (JROF,JL)
DO JKGLO=1,NGPTOT,NPROMA
  IBL=(JKGLO-1)/NPROMA+1
  IOFF=JKGLO
  IST=1
  ICEND=MIN(NPROMA,NGPTOT-JKGLO+1)

  DO JL=1,NFLEVG
    DO JROF=IST,ICEND
      PPGTERM(IBL)%PSGRTL(JROF,JL)=ZPHI0DERS(IOFF+JROF-1,JL,1)
      PPGTERM(IBL)%PSGRTM(JROF,JL)=ZPHI0DERS(IOFF+JROF-1,1*NFLEVG+JL,1)
    ENDDO
  ENDDO
ENDDO
!$OMP END PARALLEL DO


! -----------------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('GPTOSPTOGP',1,ZHOOK_HANDLE)
END SUBROUTINE GPTOSPTOGP
