! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE FINAL_STATS(CDLABEL,KSTEP,LDNHDYN)

USE PARKIND1   , ONLY : JPIM, JPIB, JPRB, JPRD
USE YOMHOOK    , ONLY : LHOOK,   DR_HOOK, JPHOOK
USE YOMCT0     , ONLY : LOPDIS
USE YOMLUN     , ONLY : NULOUT
USE YOMTIM     , ONLY : RSTART, RVSTART, RTIMEF

IMPLICIT NONE

CHARACTER(LEN=*), INTENT(IN) :: CDLABEL
INTEGER(KIND=JPIM), INTENT(IN) :: KSTEP
LOGICAL,          INTENT(IN) :: LDNHDYN

CHARACTER(LEN=32) :: CLENV
CHARACTER(LEN=9)  :: CLCONF='000000000'

INTEGER(KIND=JPIB) :: IHWM, IRSS, ICURHEAP, ISTK, IMAXSTK
INTEGER(KIND=JPIB), EXTERNAL :: GETHWM, GETRSS, GETCURHEAP, GETSTK, GETMAXSTK

REAL(KIND=JPRD) :: ZCT, ZVT, ZWT, ZRATIO, ZNULLTIME

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "user_clock.intfb.h"

#include "opdis.intfb.h"

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('FINAL_STATS',0,ZHOOK_HANDLE)

!*       3.6 STATISTICS

CALL USER_CLOCK(PELAPSED_TIME=ZWT,PVECTOR_CP=ZVT,PTOTAL_CP=ZCT)
ZCT=ZCT-RSTART
ZVT=ZVT-RVSTART
ZWT=ZWT-RTIMEF
!  avoid divide by zero
IF(ABS(ZWT) <= EPSILON(ZWT)) THEN
  ZRATIO=1.0_JPRD
ELSE
  ZRATIO=ZCT/ZWT
ENDIF

CALL GET_ENVIRONMENT_VARIABLE("EC_PROFILE_MEM", CLENV)
IF (CLENV=='0') THEN
  IHWM=0
  IRSS=0
  ICURHEAP=0
  ISTK=0
  IMAXSTK=0
ELSE
  IHWM=GETHWM()
  IRSS=GETRSS()
  ICURHEAP=GETCURHEAP()
  ISTK=GETSTK()
  IMAXSTK=GETMAXSTK()
ENDIF
CALL GET_ENVIRONMENT_VARIABLE('EC_DATE_AND_TIME', CLENV)
! EC_DATE_AND_TIME =  0 : no time
! EC_DATE_AND_TIME =  any other value : time
IF (CLENV /= '0') THEN
  WRITE(NULOUT,'('' NSTEP ='',I6,'' '',A,''   '',A9,4F8.3,5(1x,I15))')&
   & KSTEP,TRIM(CDLABEL),CLCONF,ZVT,ZCT,ZWT,ZRATIO,IHWM,IRSS,ICURHEAP,ISTK,IMAXSTK
ELSE
  ZNULLTIME=0._JPRD
  WRITE(NULOUT,'('' NSTEP ='',I6,'' '',A,''   '',A9,4F8.3,5(1x,I15))')&
   & KSTEP,TRIM(CDLABEL),CLCONF,ZNULLTIME,ZNULLTIME,ZNULLTIME,ZNULLTIME&
   & ,IHWM,IRSS,ICURHEAP,ISTK,IMAXSTK
ENDIF
IF (LOPDIS) THEN
  RSTART=RSTART+ZCT
  RVSTART=RVSTART+ZVT
  RTIMEF=RTIMEF+ZWT
  CALL OPDIS(CLCONF,TRIM(CDLABEL),ZCT,ZVT,ZWT,RSTART,RTIMEF,KSTEP,LDNHDYN)
ENDIF

IF (LHOOK) CALL DR_HOOK('FINAL_STATS',1,ZHOOK_HANDLE)

END SUBROUTINE FINAL_STATS
