! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE GPNORM_GMV(YDGEOMETRY,YDGMV)

!**** *GPNORM_GMV*  - ROUTINE FOR CALCULATING GRID POINT NORM OF
!                     GMV VARIABLES

!     PURPOSE.
!     --------

!**   INTERFACE.
!     ----------

!        *CALL* *GPNORM_GMV*

!     METHOD.
!     -------

!     EXTERNALS.
!     ----------

!     REFERENCE.
!     ----------

!        ECMWF Research Department documentation of the IFS

!     AUTHOR.
!     -------
!       T. Wilhelmsson *ECMWF*  (based on gpnorm_gfl)
!       Original : 11 May 2011

!     MODIFICATIONS.
!     --------------
!      T. Wilhelmsson and K. Yessad (Oct 2013) Geometry and setup refactoring.
!     -----------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV       , ONLY : TGMV
USE PARKIND1     , ONLY : JPIM, JPRB
USE YOMHOOK      , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMMP0       , ONLY : NPROC, MYPROC
USE YOMCT0       , ONLY : NSPPR, LELAM
USE YOMLUN       , ONLY : NULOUT

IMPLICIT NONE

TYPE(GEOMETRY) , INTENT(IN)   :: YDGEOMETRY
TYPE(TGMV)     , INTENT(IN)   :: YDGMV
REAL(KIND=JPRB), ALLOCATABLE  :: ZGP(:,:,:)
REAL(KIND=JPRB), ALLOCATABLE  :: ZAVE(:), ZMAX(:), ZMIN(:)
REAL(KIND=JPRB), ALLOCATABLE  :: ZMAXBLK(:,:), ZMINBLK(:,:)

INTEGER(KIND=JPIM), PARAMETER :: JPNFLDS = 3
INTEGER(KIND=JPIM) :: IMPT(JPNFLDS)
CHARACTER(LEN=16)  :: CLNAME(JPNFLDS)

INTEGER(KIND=JPIM) :: IEND, IST, JF, JL, JKGLO, IBL, JFLD
LOGICAL            :: LLEVELS, LLAVE_ONLY
REAL(KIND=JPHOOK)    :: ZHOOK_HANDLE

#include "gpnorm_trans.h"
#include "egpnorm_trans.h"

#include "gpnorm1.intfb.h"

!     -----------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('GPNORM_GMV',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP)
ASSOCIATE(NGPBLKS=>YDDIM%NGPBLKS, NPROMA=>YDDIM%NPROMA, NRESOL=>YDDIM%NRESOL, &
 & NFLEVG=>YDDIMV%NFLEVG, &
 & NGPTOT=>YDGEM%NGPTOT, &
 & GMV=>YDGMV%GMV, GMVS=>YDGMV%GMVS, YT0=>YDGMV%YT0)

ALLOCATE(ZGP(NPROMA,1,NGPBLKS))

CALL GSTATS(1223,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO,IST,IEND,IBL,JF,JL)
DO JKGLO=1,NGPTOT,NPROMA
  IST=1
  IEND=MIN(NPROMA,NGPTOT-JKGLO+1)
  IBL=(JKGLO-1)/NPROMA+1
  DO JL=IST,IEND
    ZGP(JL,1,IBL) = GMVS(JL,YT0%MSP,IBL)
  ENDDO
ENDDO
!$OMP END PARALLEL DO
CALL GSTATS(1223,1)
      
LLEVELS=.FALSE.
CALL GPNORM1(YDGEOMETRY,ZGP,1,LLEVELS,'SURFACE PRESSURE')

DEALLOCATE(ZGP)

IMPT(1)  = YT0%MU
IMPT(2)  = YT0%MV
IMPT(3)  = YT0%MT

CLNAME(1) = 'U VELOCITY'
CLNAME(2) = 'V VELOCITY'
CLNAME(3) = 'TEMPERATURE'

LLEVELS = NSPPR>0

IF( LLEVELS )THEN

  ALLOCATE(ZGP(NPROMA,NFLEVG,NGPBLKS))

  DO JFLD=1,JPNFLDS
    CALL GSTATS(1223,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO,IST,IEND,IBL,JF,JL)
    DO JKGLO=1,NGPTOT,NPROMA
      IST=1
      IEND=MIN(NPROMA,NGPTOT-JKGLO+1)
      IBL=(JKGLO-1)/NPROMA+1
      DO JF=1,NFLEVG
        DO JL=IST,IEND
          ZGP(JL,JF,IBL) = GMV(JL,JF,IMPT(JFLD),IBL)
        ENDDO
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1223,1)
      
    CALL GPNORM1(YDGEOMETRY,ZGP,NFLEVG,LLEVELS,CLNAME(JFLD))
  ENDDO

  DEALLOCATE(ZGP)

ELSE

  ALLOCATE(ZGP(NPROMA,JPNFLDS,NGPBLKS))

  ALLOCATE(ZAVE(JPNFLDS))
  ALLOCATE(ZMIN(JPNFLDS))
  ALLOCATE(ZMAX(JPNFLDS))
  ALLOCATE(ZMINBLK(JPNFLDS,NGPBLKS))
  ALLOCATE(ZMAXBLK(JPNFLDS,NGPBLKS))

  DO JFLD=1, JPNFLDS
    ZMINBLK(JFLD,:)=GMV(1,1,IMPT(JFLD),1)
    ZMAXBLK(JFLD,:)=GMV(1,1,IMPT(JFLD),1)

    CALL GSTATS(1427,0)
!$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JKGLO,IST,IEND,IBL,JF,JL)
    DO JKGLO=1,NGPTOT,NPROMA
      IST=1
      IEND=MIN(NPROMA,NGPTOT-JKGLO+1)
      IBL=(JKGLO-1)/NPROMA+1
      DO JL=IST,IEND
        ZGP(JL,JFLD,IBL) = 0.0_JPRB
      ENDDO
      DO JF=1,NFLEVG
        DO JL=IST,IEND
          ZGP(JL,JFLD,IBL) = ZGP(JL,JFLD,IBL)+GMV(JL,JF,IMPT(JFLD),IBL)
          ZMINBLK(JFLD,IBL) = MIN(ZMINBLK(JFLD,IBL),GMV(JL,JF,IMPT(JFLD),IBL))
          ZMAXBLK(JFLD,IBL) = MAX(ZMAXBLK(JFLD,IBL),GMV(JL,JF,IMPT(JFLD),IBL))
        ENDDO
      ENDDO
    ENDDO
!$OMP END PARALLEL DO
    CALL GSTATS(1427,1)
    ZMIN(JFLD)=MINVAL(ZMINBLK(JFLD,1:NGPBLKS))
    ZMAX(JFLD)=MAXVAL(ZMAXBLK(JFLD,1:NGPBLKS))
  ENDDO

  LLAVE_ONLY=.TRUE. 
  IF ( .NOT. LELAM ) THEN
   CALL GPNORM_TRANS(ZGP,JPNFLDS,NPROMA,ZAVE,ZMIN,ZMAX,LLAVE_ONLY,NRESOL)
  ELSE
   CALL EGPNORM_TRANS(ZGP,JPNFLDS,NPROMA,ZAVE,ZMIN,ZMAX,LLAVE_ONLY,NRESOL)
  ENDIF
  IF (MYPROC == 1.OR.NPROC == 1) THEN
    DO JFLD=1,JPNFLDS
      WRITE(NULOUT,'(5(1X,A))') 'GPNORM',CLNAME(JFLD),'    AVERAGE         ',&
        & '     MINIMUM        ','      MAXIMUM        '
      WRITE(NULOUT,'(9X,A5,3(1X,E21.15))') 'AVE  ',ZAVE(JFLD)/NFLEVG,ZMIN(JFLD),ZMAX(JFLD)
    ENDDO
  ENDIF

  DEALLOCATE(ZGP)
  DEALLOCATE(ZAVE)
  DEALLOCATE(ZMIN)
  DEALLOCATE(ZMAX)
  DEALLOCATE(ZMINBLK)
  DEALLOCATE(ZMAXBLK)

ENDIF

!     -----------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('GPNORM_GMV',1,ZHOOK_HANDLE)
END SUBROUTINE GPNORM_GMV
