! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBROUTINE SAVE_TEST4DINC(YDGEOMETRY,YDGFL,YDGMV,YDGMV5,YDML_GCONF,KSTEP)

!     Purpose.
!     --------
!       Saves field for test of TL approximation.

!     Author.
!     -------
!       Y. Tremolet
!       Original    06-08-01

!     Modifications.
!     --------------
!       Y.Tremolet  20-11-03 Moved out of TESTVAR_MIX module
!        M.Hamrud      01-Oct-2003 CY28 Cleaning
!        Y.Tremolet    07-Jun-2004 Re-wrote for GMV/GFL
!        Y.Tremolet    17-Feb-2005 Conserving interp., change file names
!       M.Drusch      18-Jan-2007 introduce nconf 302
!       M.Fisher 15-Feb-2013 CVA_DATA
!       K. Yessad (July 2014): Move some variables.
! ------------------------------------------------------------------

USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL   , ONLY : TGFL
USE YOMGMV   , ONLY : TGMV
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULOUT
USE YOMCT0   , ONLY : NCONF, LOBSC1
USE ALGORITHM_STATE_MOD  , ONLY : GET_NUPTRA
USE YOMCVA   , ONLY : CVA_DATA
USE YOM_GRIB_CODES , ONLY : NGRBVO, NGRBD, NGRBU, NGRBV, NGRBT, NGRBLNSP, NGRBSP
USE TESTVAR_MIX,ONLY: LSTEP_TESTINC, INTERP_TEST, NGRB_TESTINC, LTESTSPPA
USE GRIDPOINT_FIELDS_MIX, ONLY : ASSIGNMENT(=), GRIDPOINT_FIELD, DEALLOCATE_GRID, ALLOCATE_GRID, HUGIFY_ENDGRID

! ------------------------------------------------------------------

IMPLICIT NONE

TYPE(GEOMETRY),     INTENT(IN)    :: YDGEOMETRY
TYPE(TGFL),         INTENT(INOUT) :: YDGFL
TYPE(TGMV),         INTENT(INOUT) :: YDGMV
TYPE(TGMV),         INTENT(INOUT) :: YDGMV5
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(INOUT):: YDML_GCONF
INTEGER(KIND=JPIM), INTENT(IN)    :: KSTEP 
! ------------------------------------------------------------------
TYPE(GRIDPOINT_FIELD) :: YLGRID
REAL(KIND=JPRB), ALLOCATABLE :: ZLNSPREF(:,:)
CHARACTER(LEN=26) :: CLFILE
INTEGER(KIND=JPIM) :: JL,JB,IH,IM,IS,ILEN,JG,II,JF
INTEGER(KIND=JPIM), ALLOCATABLE :: IGRIB(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

! ------------------------------------------------------------------

#include "abor1.intfb.h"
#include "write_grid_grib.intfb.h"
#include "prtime.intfb.h"

! ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('SAVE_TEST4DINC',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV, &
  & YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP, YGFL=>YDML_GCONF%YGFL,YDRIP=>YDML_GCONF%YRRIP)
ASSOCIATE(NUMFLDS=>YGFL%NUMFLDS, YCOMP=>YGFL%YCOMP, &
 & GFL=>YDGFL%GFL, &
 & GMV=>YDGMV%GMV, GMVS=>YDGMV%GMVS, YT0=>YDGMV%YT0, &
 & GMV5S=>YDGMV5%GMV5S, YT5=>YDGMV5%YT5, &
 & TSTEP=>YDRIP%TSTEP)
! ------------------------------------------------------------------

IF (LSTEP_TESTINC(KSTEP)) THEN
  IF (NCONF==131) THEN
    CLFILE(1:26)='TEST4DINC/minXXggXXXXhXXXX'
    WRITE(CLFILE(14:15),'(I2.2)')GET_NUPTRA()
  ELSEIF (NCONF==1.OR.NCONF==302) THEN
    IF (LOBSC1) THEN
    CLFILE(1:26)='TEST4DINC/traXXggXXXXhXXXX'
      WRITE(CLFILE(14:15),'(I2.2)')GET_NUPTRA()
    ELSE
      CLFILE(1:26)='TEST4DINC/fcastggXXXXhXXXX'
    ENDIF
  ELSE
    CALL ABOR1('SAVE_TEST4DINC: NCONF neither 1 nor 131')
  ENDIF
  IS=KSTEP*NINT(TSTEP)
  IH=IS/3600
  IS=IS-3600*IH
  IM=IS/60
  IS=IS-60*IM
  WRITE(CLFILE(18:21),'(I4.4)')IH
  WRITE(CLFILE(23:24),'(I2.2)')IM
  WRITE(CLFILE(25:26),'(I2.2)')IS

  ALLOCATE(IGRIB(CVA_DATA%NVA3D+CVA_DATA%NVA2D))
  IGRIB(:)=CVA_DATA%NGRBVAR(:)
  WHERE (IGRIB(:)==NGRBVO) IGRIB(:)=NGRBU
  WHERE (IGRIB(:)==NGRBD ) IGRIB(:)=NGRBV
  IF (LTESTSPPA) WHERE (IGRIB(:)==NGRBLNSP) IGRIB(:)=NGRBSP
  WRITE(NULOUT,*)'SAVE_TEST4DINC: igrib=',IGRIB

  CALL ALLOCATE_GRID(YDGEOMETRY,YLGRID,CVA_DATA%NVA3D,CVA_DATA%NVA2D,IGRIB)
  DEALLOCATE(IGRIB)

  DO JF=1,YLGRID%NG3D
    IF (YLGRID%NGRIB3(JF)==NGRBU.OR.YLGRID%NGRIB3(JF)==NGRBV.OR.&
      & YLGRID%NGRIB3(JF)==NGRBT) THEN
      IF (YLGRID%NGRIB3(JF)==NGRBU) THEN
        JG=YT0%MU
      ELSEIF (YLGRID%NGRIB3(JF)==NGRBV) THEN
        JG=YT0%MV
      ELSEIF (YLGRID%NGRIB3(JF)==NGRBT) THEN
        JG=YT0%MT
      ELSE
        CALL ABOR1('SAVE_TEST4DINC: Error GMV')
      ENDIF
      WRITE(NULOUT,*)'SAVE_TEST4DINC: GMV jf,jg=',JF,JG
      DO JB=1,YLGRID%NGPBLKS
        ILEN=MIN(YLGRID%NPROMA, YLGRID%NGPTOT-(JB-1)*YLGRID%NPROMA)
        DO JL=1,YLGRID%NFLEVG
          YLGRID%GP3D(1:ILEN,JL,JF,JB)=GMV(1:ILEN,JL,JG,JB)
        ENDDO
      ENDDO
    ELSE
      JG=-999
      II=0
      DO WHILE (II<NUMFLDS .AND. JG<0)
        II=II+1
        IF (YLGRID%NGRIB3(JF)==YCOMP(II)%IGRBCODE) JG=YCOMP(II)%MP
      ENDDO
      WRITE(NULOUT,*)'SAVE_TEST4DINC: GFL jf,jg=',JF,JG
      IF (JG<1.OR.JG>NUMFLDS) CALL ABOR1('SAVE_TEST4DINC: Error GFL')
      DO JB=1,YLGRID%NGPBLKS
        ILEN=MIN(YLGRID%NPROMA, YLGRID%NGPTOT-(JB-1)*YLGRID%NPROMA)
        DO JL=1,YLGRID%NFLEVG
          YLGRID%GP3D(1:ILEN,JL,JF,JB)=GFL(1:ILEN,JL,JG,JB)
        ENDDO
      ENDDO
    ENDIF
  ENDDO
  DO JF=1,YLGRID%NG2D
    IF (YLGRID%NGRIB2(JF)==NGRBSP.OR.YLGRID%NGRIB2(JF)==NGRBLNSP) THEN
      JG=YT0%MSP
      WRITE(NULOUT,*)'SAVE_TEST4DINC: GMVS jf,jg=',JF,JG
      DO JB=1,YLGRID%NGPBLKS
        ILEN=MIN(YLGRID%NPROMA, YLGRID%NGPTOT-(JB-1)*YLGRID%NPROMA)
        YLGRID%GP2D(1:ILEN,JF,JB)=GMVS(1:ILEN,JG,JB)
      ENDDO
    ELSE
      CALL ABOR1('SAVE_TEST4DINC: 2D field not found.')
    ENDIF
  ENDDO
  CALL HUGIFY_ENDGRID(YLGRID)

  ALLOCATE(ZLNSPREF(YLGRID%NPROMA,YLGRID%NGPBLKS))
  IF (NCONF==131) THEN
    ZLNSPREF(:,:)=GMV5S(:,YT5%MSP,:)
  ELSE
    ZLNSPREF(:,:)=GMVS(:,YT0%MSP,:)
  ENDIF

  IF (LTESTSPPA) THEN
    IF (NCONF==131) THEN
      DO JB=1,YLGRID%NGPBLKS
        ILEN=MIN(YLGRID%NPROMA, YLGRID%NGPTOT-(JB-1)*YLGRID%NPROMA)
        DO JL=1,ILEN
          YLGRID%GP2D(JL,1,JB)=YLGRID%GP2D(JL,1,JB)*EXP(ZLNSPREF(JL,JB))
        ENDDO
      ENDDO
    ELSE
      DO JB=1,YLGRID%NGPBLKS
        ILEN=MIN(YLGRID%NPROMA, YLGRID%NGPTOT-(JB-1)*YLGRID%NPROMA)
        DO JL=1,ILEN
          YLGRID%GP2D(JL,1,JB)=EXP(YLGRID%GP2D(JL,1,JB))
        ENDDO
      ENDDO
    ENDIF
  ENDIF

  CALL PRTIME(YDRIP,'SAVE_TEST4DINC')
  WRITE(NULOUT,*)'SAVE_TEST4DINC: writing to file ',CLFILE
  CALL WRITE_GRID_GRIB(YDGEOMETRY,YDRIP,CLFILE,YLGRID,NGRB_TESTINC,INTERP_TEST,&
                     & PGPSP=ZLNSPREF)
  CALL DEALLOCATE_GRID(YLGRID)

  IF (ALLOCATED(ZLNSPREF)) DEALLOCATE(ZLNSPREF)
ENDIF

! ------------------------------------------------------------------
END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SAVE_TEST4DINC',1,ZHOOK_HANDLE)
END SUBROUTINE SAVE_TEST4DINC
