! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

! ------------------------------------------------------------------
TYPE(FULLPOS_TYPE), POINTER :: TFP_Z
TYPE(FULLPOS_TYPE), POINTER :: TFP_T
TYPE(FULLPOS_TYPE), POINTER :: TFP_U
TYPE(FULLPOS_TYPE), POINTER :: TFP_V
TYPE(FULLPOS_TYPE), POINTER :: TFP_Q
TYPE(FULLPOS_TYPE), POINTER :: TFP_HU
TYPE(FULLPOS_TYPE), POINTER :: TFP_VV
TYPE(FULLPOS_TYPE), POINTER :: TFP_VOR
TYPE(FULLPOS_TYPE), POINTER :: TFP_DIV
TYPE(FULLPOS_TYPE), POINTER :: TFP_PSI
TYPE(FULLPOS_TYPE), POINTER :: TFP_KHI
TYPE(FULLPOS_TYPE), POINTER :: TFP_L
TYPE(FULLPOS_TYPE), POINTER :: TFP_I
TYPE(FULLPOS_TYPE), POINTER :: TFP_LRAD
TYPE(FULLPOS_TYPE), POINTER :: TFP_IRAD
TYPE(FULLPOS_TYPE), POINTER :: TFP_SN
TYPE(FULLPOS_TYPE), POINTER :: TFP_RR
TYPE(FULLPOS_TYPE), POINTER :: TFP_GR
TYPE(FULLPOS_TYPE), POINTER :: TFP_HL
TYPE(FULLPOS_TYPE), POINTER :: TFP_TKE
TYPE(FULLPOS_TYPE), POINTER :: TFP_PHYCTY
TYPE(FULLPOS_TYPE), POINTER :: TFP_EFB1
TYPE(FULLPOS_TYPE), POINTER :: TFP_EFB2
TYPE(FULLPOS_TYPE), POINTER :: TFP_EFB3
TYPE(FULLPOS_TYPE), POINTER :: TFP_TH
TYPE(FULLPOS_TYPE), POINTER :: TFP_THPW
TYPE(FULLPOS_TYPE), POINTER :: TFP_TPW
TYPE(FULLPOS_TYPE), POINTER :: TFP_CLF
TYPE(FULLPOS_TYPE), POINTER :: TFP_O3MX
TYPE(FULLPOS_TYPE), POINTER :: TFP_CPF
TYPE(FULLPOS_TYPE), POINTER :: TFP_SPF
TYPE(FULLPOS_TYPE), POINTER :: TFP_WND
TYPE(FULLPOS_TYPE), POINTER :: TFP_ETH
TYPE(FULLPOS_TYPE), POINTER :: TFP_ABS
TYPE(FULLPOS_TYPE), POINTER :: TFP_STD
TYPE(FULLPOS_TYPE), POINTER :: TFP_PV
TYPE(FULLPOS_TYPE), POINTER :: TFP_SHD
TYPE(FULLPOS_TYPE), POINTER :: TFP_P
TYPE(FULLPOS_TYPE), POINTER :: TFP_MG
TYPE(FULLPOS_TYPE), POINTER :: TFP_PD
TYPE(FULLPOS_TYPE), POINTER :: TFP_VD
TYPE(FULLPOS_TYPE), POINTER :: TFP_VW
TYPE(FULLPOS_TYPE), POINTER :: TFP_SRE
TYPE(FULLPOS_TYPE), POINTER :: TFP_SREDB
TYPE(FULLPOS_TYPE), POINTER :: TFP_THV
TYPE(FULLPOS_TYPE), POINTER :: TFP_ETAD
TYPE(FULLPOS_TYPE), POINTER :: TFP_RKTH
TYPE(FULLPOS_TYPE), POINTER :: TFP_RKTQV
TYPE(FULLPOS_TYPE), POINTER :: TFP_RKTQC
TYPE(FULLPOS_TYPE), POINTER :: TFP_TCVS
TYPE(FULLPOS_TYPE), POINTER :: TFP_DAL
TYPE(FULLPOS_TYPE), POINTER :: TFP_DOM
TYPE(FULLPOS_TYPE), POINTER :: TFP_UAL
TYPE(FULLPOS_TYPE), POINTER :: TFP_UOM
TYPE(FULLPOS_TYPE), POINTER :: TFP_UEN
TYPE(FULLPOS_TYPE), POINTER :: TFP_UNEBH
TYPE(FULLPOS_TYPE), POINTER :: TFP_LCONV
TYPE(FULLPOS_TYPE), POINTER :: TFP_ICONV
TYPE(FULLPOS_TYPE), POINTER :: TFP_RCONV
TYPE(FULLPOS_TYPE), POINTER :: TFP_SCONV
TYPE(FULLPOS_TYPE), POINTER :: TFP_TTE
TYPE(FULLPOS_TYPE), POINTER :: TFP_MXL
TYPE(FULLPOS_TYPE), POINTER :: TFP_SHTUR
TYPE(FULLPOS_TYPE), POINTER :: TFP_FQTUR
TYPE(FULLPOS_TYPE), POINTER :: TFP_FSTUR
TYPE(FULLPOS_TYPE), POINTER :: TFP_EDR
TYPE(FULLPOS_TYPE), POINTER :: TFP_EDRP(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_FUA(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_EXT(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_EZDIAG(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_EMIS3D(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_GHG(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_CHEM(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_AERO(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_LRCH4
TYPE(FULLPOS_TYPE), POINTER :: TFP_PTB
TYPE(FULLPOS_TYPE), POINTER :: TFP_HTB
TYPE(FULLPOS_TYPE), POINTER :: TFP_RHO
TYPE(FULLPOS_TYPE), POINTER :: TFP_SP
TYPE(FULLPOS_TYPE), POINTER :: TFP_SPNH
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSL
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSLNH
TYPE(FULLPOS_TYPE), POINTER :: TFP_CUF1
TYPE(FULLPOS_TYPE), POINTER :: TFP_CUF2
TYPE(FULLPOS_TYPE), POINTER :: TFP_CUF3
TYPE(FULLPOS_TYPE), POINTER :: TFP_CUF4
TYPE(FULLPOS_TYPE), POINTER :: TFP_CUF5
TYPE(FULLPOS_TYPE), POINTER :: TFP_VEIN
TYPE(FULLPOS_TYPE), POINTER :: TFP_QNH
TYPE(FULLPOS_TYPE), POINTER :: TFP_FIS
TYPE(FULLPOS_TYPE), POINTER :: TFP_GM
TYPE(FULLPOS_TYPE), POINTER :: TFP_FOL
TYPE(FULLPOS_TYPE), POINTER :: TFP_WWS
TYPE(FULLPOS_TYPE), POINTER :: TFP_LNSP
TYPE(FULLPOS_TYPE), POINTER :: TFP_UCLS
TYPE(FULLPOS_TYPE), POINTER :: TFP_VCLS
TYPE(FULLPOS_TYPE), POINTER :: TFP_TCLS
TYPE(FULLPOS_TYPE), POINTER :: TFP_QCLS
TYPE(FULLPOS_TYPE), POINTER :: TFP_RCLS
TYPE(FULLPOS_TYPE), POINTER :: TFP_FCLS
TYPE(FULLPOS_TYPE), POINTER :: TFP_TX
TYPE(FULLPOS_TYPE), POINTER :: TFP_TN
TYPE(FULLPOS_TYPE), POINTER :: TFP_CAPE
TYPE(FULLPOS_TYPE), POINTER :: TFP_CIEN
TYPE(FULLPOS_TYPE), POINTER :: TFP_MOCO
TYPE(FULLPOS_TYPE), POINTER :: TFP_TWV
TYPE(FULLPOS_TYPE), POINTER :: TFP_UGST
TYPE(FULLPOS_TYPE), POINTER :: TFP_VGST
TYPE(FULLPOS_TYPE), POINTER :: TFP_FGST
TYPE(FULLPOS_TYPE), POINTER :: TFP_HCLP
TYPE(FULLPOS_TYPE), POINTER :: TFP_UJET
TYPE(FULLPOS_TYPE), POINTER :: TFP_VJET
TYPE(FULLPOS_TYPE), POINTER :: TFP_PJET
TYPE(FULLPOS_TYPE), POINTER :: TFP_TCAO
TYPE(FULLPOS_TYPE), POINTER :: TFP_PCAO
TYPE(FULLPOS_TYPE), POINTER :: TFP_HTPW
TYPE(FULLPOS_TYPE), POINTER :: TFP_HTPW1
TYPE(FULLPOS_TYPE), POINTER :: TFP_HTPW2
TYPE(FULLPOS_TYPE), POINTER :: TFP_HUX
TYPE(FULLPOS_TYPE), POINTER :: TFP_HUN
TYPE(FULLPOS_TYPE), POINTER :: TFP_SREX
TYPE(FULLPOS_TYPE), POINTER :: TFP_SREDBX
TYPE(FULLPOS_TYPE), POINTER :: TFP_TOPR
TYPE(FULLPOS_TYPE), POINTER :: TFP_IET
TYPE(FULLPOS_TYPE), POINTER :: TFP_SMC
TYPE(FULLPOS_TYPE), POINTER :: TFP_ASMC
TYPE(FULLPOS_TYPE), POINTER :: TFP_VSMC
TYPE(FULLPOS_TYPE), POINTER :: TFP_FSU(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT7C1
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT7C2
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT8C1
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT8C2
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT8C3
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT8C4
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT8C5
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT8C6
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT8C7
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT8C8
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT9C1
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT9C2
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT9C3
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT9C4
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT9C5
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT9C6
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT9C7
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSAT9C8
TYPE(FULLPOS_TYPE), POINTER :: TFP_GOES11C1
TYPE(FULLPOS_TYPE), POINTER :: TFP_GOES11C2
TYPE(FULLPOS_TYPE), POINTER :: TFP_GOES11C3
TYPE(FULLPOS_TYPE), POINTER :: TFP_GOES11C4
TYPE(FULLPOS_TYPE), POINTER :: TFP_GOES12C1
TYPE(FULLPOS_TYPE), POINTER :: TFP_GOES12C2
TYPE(FULLPOS_TYPE), POINTER :: TFP_GOES12C3
TYPE(FULLPOS_TYPE), POINTER :: TFP_GOES12C4
TYPE(FULLPOS_TYPE), POINTER :: TFP_MTSAT1C1
TYPE(FULLPOS_TYPE), POINTER :: TFP_MTSAT1C2
TYPE(FULLPOS_TYPE), POINTER :: TFP_MTSAT1C3
TYPE(FULLPOS_TYPE), POINTER :: TFP_MTSAT1C4
TYPE(FULLPOS_TYPE), POINTER :: TFP_LCL
TYPE(FULLPOS_TYPE), POINTER :: TFP_FCL
TYPE(FULLPOS_TYPE), POINTER :: TFP_EL

TYPE(FULLPOS_TYPE), POINTER :: TFP_SRH
TYPE(FULLPOS_TYPE), POINTER :: TFP_STRMMU
TYPE(FULLPOS_TYPE), POINTER :: TFP_STRMMV

TYPE(FULLPOS_TYPE), POINTER :: TFP_NOGW(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_AEROUT(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_UVP(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_MSK
TYPE(FULLPOS_TYPE), POINTER :: TFP_ERA40(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_AERAOT(:)
TYPE(FULLPOS_TYPE), POINTER :: TFP_AERLISI(:)

TYPE(FPDSPHY), POINTER :: GFP_ALUVP
TYPE(FPDSPHY), POINTER :: GFP_ALUVD
TYPE(FPDSPHY), POINTER :: GFP_ALNIP
TYPE(FPDSPHY), POINTER :: GFP_ALNID
TYPE(FPDSPHY), POINTER :: GFP_ALUVI
TYPE(FPDSPHY), POINTER :: GFP_ALNII
TYPE(FPDSPHY), POINTER :: GFP_ALUVV
TYPE(FPDSPHY), POINTER :: GFP_ALNIV
TYPE(FPDSPHY), POINTER :: GFP_ALUVG
TYPE(FPDSPHY), POINTER :: GFP_ALNIG
TYPE(FPDSPHY), POINTER :: GFP_SDFOR
TYPE(FPDSPHY), POINTER :: GFP_CGPP
TYPE(FPDSPHY), POINTER :: GFP_CREC
TYPE(FPDSPHY), POINTER :: GFP_LSM
TYPE(FPDSPHY), POINTER :: GFP_GFIS
TYPE(FPDSPHY), POINTER :: GFP_SFIS
TYPE(FPDSPHY), POINTER :: GFP_ST
TYPE(FPDSPHY), POINTER :: GFP_DST
TYPE(FPDSPHY), POINTER :: GFP_RDST
TYPE(FPDSPHY), POINTER :: GFP_SSW
TYPE(FPDSPHY), POINTER :: GFP_DSW
TYPE(FPDSPHY), POINTER :: GFP_FSSW
TYPE(FPDSPHY), POINTER :: GFP_FDSW
TYPE(FPDSPHY), POINTER :: GFP_RDSW
TYPE(FPDSPHY), POINTER :: GFP_CSSW
TYPE(FPDSPHY), POINTER :: GFP_CDSW
TYPE(FPDSPHY), POINTER :: GFP_SD
TYPE(FPDSPHY), POINTER :: GFP_SDSL
TYPE(FPDSPHY), POINTER :: GFP_WSN
TYPE(FPDSPHY), POINTER :: GFP_SR
TYPE(FPDSPHY), POINTER :: GFP_BSR
TYPE(FPDSPHY), POINTER :: GFP_AL
TYPE(FPDSPHY), POINTER :: GFP_EMIS
TYPE(FPDSPHY), POINTER :: GFP_SDOG
TYPE(FPDSPHY), POINTER :: GFP_VEG
TYPE(FPDSPHY), POINTER :: GFP_SOTY
TYPE(FPDSPHY), POINTER :: GFP_LAN
TYPE(FPDSPHY), POINTER :: GFP_CLK
TYPE(FPDSPHY), POINTER :: GFP_DL
TYPE(FPDSPHY), POINTER :: GFP_LMLT
TYPE(FPDSPHY), POINTER :: GFP_LMLD
TYPE(FPDSPHY), POINTER :: GFP_LBLT
TYPE(FPDSPHY), POINTER :: GFP_LTLT
TYPE(FPDSPHY), POINTER :: GFP_LSHF
TYPE(FPDSPHY), POINTER :: GFP_LICT
TYPE(FPDSPHY), POINTER :: GFP_LICD
TYPE(FPDSPHY), POINTER :: GFP_ACOT
TYPE(FPDSPHY), POINTER :: GFP_DPAT
TYPE(FPDSPHY), POINTER :: GFP_IVEG
TYPE(FPDSPHY), POINTER :: GFP_RSMIN
TYPE(FPDSPHY), POINTER :: GFP_ARG
TYPE(FPDSPHY), POINTER :: GFP_SAB
TYPE(FPDSPHY), POINTER :: GFP_D2
TYPE(FPDSPHY), POINTER :: GFP_LAI
TYPE(FPDSPHY), POINTER :: GFP_HV
TYPE(FPDSPHY), POINTER :: GFP_Z0H
TYPE(FPDSPHY), POINTER :: GFP_IC
TYPE(FPDSPHY), POINTER :: GFP_ALSN
TYPE(FPDSPHY), POINTER :: GFP_SNDE
TYPE(FPDSPHY), POINTER :: GFP_BAAL
TYPE(FPDSPHY), POINTER :: GFP_ALBHIS
TYPE(FPDSPHY), POINTER :: GFP_ALS
TYPE(FPDSPHY), POINTER :: GFP_ALV
TYPE(FPDSPHY), POINTER :: GFP_PSRHU
TYPE(FPDSPHY), POINTER :: GFP_PADOU
TYPE(FPDSPHY), POINTER :: GFP_PADOV
TYPE(FPDSPHY), POINTER :: GFP_PCAAG
TYPE(FPDSPHY), POINTER :: GFP_PCAPG
TYPE(FPDSPHY), POINTER :: GFP_IDZ0
TYPE(FPDSPHY), POINTER :: GFP_ITZ0
TYPE(FPDSPHY), POINTER :: GFP_PVGMX
TYPE(FPDSPHY), POINTER :: GFP_Z0V
TYPE(FPDSPHY), POINTER :: GFP_PURB
TYPE(FPDSPHY), POINTER :: GFP_D2MX
TYPE(FPDSPHY), POINTER :: GFP_STL1
TYPE(FPDSPHY), POINTER :: GFP_STL2
TYPE(FPDSPHY), POINTER :: GFP_STL3
TYPE(FPDSPHY), POINTER :: GFP_STL4
TYPE(FPDSPHY), POINTER :: GFP_SWL1
TYPE(FPDSPHY), POINTER :: GFP_SWL2
TYPE(FPDSPHY), POINTER :: GFP_SWL3
TYPE(FPDSPHY), POINTER :: GFP_SWL4
TYPE(FPDSPHY), POINTER :: GFP_TSN
TYPE(FPDSPHY), POINTER :: GFP_ISOR
TYPE(FPDSPHY), POINTER :: GFP_ANOR
TYPE(FPDSPHY), POINTER :: GFP_SLOR
TYPE(FPDSPHY), POINTER :: GFP_LSRH
TYPE(FPDSPHY), POINTER :: GFP_SRC
TYPE(FPDSPHY), POINTER :: GFP_SKT
TYPE(FPDSPHY), POINTER :: GFP_LSP
TYPE(FPDSPHY), POINTER :: GFP_CP
TYPE(FPDSPHY), POINTER :: GFP_TP
TYPE(FPDSPHY), POINTER :: GFP_SF
TYPE(FPDSPHY), POINTER :: GFP_FZRA
TYPE(FPDSPHY), POINTER :: GFP_BLD
TYPE(FPDSPHY), POINTER :: GFP_SSHF
TYPE(FPDSPHY), POINTER :: GFP_SLHF
TYPE(FPDSPHY), POINTER :: GFP_NEE
TYPE(FPDSPHY), POINTER :: GFP_GPP
TYPE(FPDSPHY), POINTER :: GFP_REC
TYPE(FPDSPHY), POINTER :: GFP_MSLD
TYPE(FPDSPHY), POINTER :: GFP_SP
TYPE(FPDSPHY), POINTER :: GFP_TCC
TYPE(FPDSPHY), POINTER :: GFP_10U
TYPE(FPDSPHY), POINTER :: GFP_10V
TYPE(FPDSPHY), POINTER :: GFP_10SI
TYPE(FPDSPHY), POINTER :: GFP_2T
TYPE(FPDSPHY), POINTER :: GFP_2D
TYPE(FPDSPHY), POINTER :: GFP_2SH
TYPE(FPDSPHY), POINTER :: GFP_SSR
TYPE(FPDSPHY), POINTER :: GFP_STR
TYPE(FPDSPHY), POINTER :: GFP_TSR
TYPE(FPDSPHY), POINTER :: GFP_TTR
TYPE(FPDSPHY), POINTER :: GFP_EWSS
TYPE(FPDSPHY), POINTER :: GFP_NSSS
TYPE(FPDSPHY), POINTER :: GFP_E
TYPE(FPDSPHY), POINTER :: GFP_PEV
TYPE(FPDSPHY), POINTER :: GFP_CCC
TYPE(FPDSPHY), POINTER :: GFP_LCC
TYPE(FPDSPHY), POINTER :: GFP_MCC
TYPE(FPDSPHY), POINTER :: GFP_HCC
TYPE(FPDSPHY), POINTER :: GFP_LGWS
TYPE(FPDSPHY), POINTER :: GFP_MGWS
TYPE(FPDSPHY), POINTER :: GFP_GWD
TYPE(FPDSPHY), POINTER :: GFP_MX2T
TYPE(FPDSPHY), POINTER :: GFP_MN2T
TYPE(FPDSPHY), POINTER :: GFP_MX2T3
TYPE(FPDSPHY), POINTER :: GFP_MN2T3
TYPE(FPDSPHY), POINTER :: GFP_MX2T6
TYPE(FPDSPHY), POINTER :: GFP_MN2T6
TYPE(FPDSPHY), POINTER :: GFP_MXTPR
TYPE(FPDSPHY), POINTER :: GFP_MNTPR
TYPE(FPDSPHY), POINTER :: GFP_MXTPR3
TYPE(FPDSPHY), POINTER :: GFP_MNTPR3
TYPE(FPDSPHY), POINTER :: GFP_MXTPR6
TYPE(FPDSPHY), POINTER :: GFP_MNTPR6
TYPE(FPDSPHY), POINTER :: GFP_LSRR
TYPE(FPDSPHY), POINTER :: GFP_CRR
TYPE(FPDSPHY), POINTER :: GFP_LSSFR
TYPE(FPDSPHY), POINTER :: GFP_CSFR
TYPE(FPDSPHY), POINTER :: GFP_PTYPE
TYPE(FPDSPHY), POINTER :: GFP_ILSPF
TYPE(FPDSPHY), POINTER :: GFP_RO
TYPE(FPDSPHY), POINTER :: GFP_SRO
TYPE(FPDSPHY), POINTER :: GFP_SSRO
TYPE(FPDSPHY), POINTER :: GFP_ALB
TYPE(FPDSPHY), POINTER :: GFP_IEWSS
TYPE(FPDSPHY), POINTER :: GFP_INSSS
TYPE(FPDSPHY), POINTER :: GFP_ISSHF
TYPE(FPDSPHY), POINTER :: GFP_IE
TYPE(FPDSPHY), POINTER :: GFP_INEE
TYPE(FPDSPHY), POINTER :: GFP_IGPP
TYPE(FPDSPHY), POINTER :: GFP_IREC
TYPE(FPDSPHY), POINTER :: GFP_ICH4
TYPE(FPDSPHY), POINTER :: GFP_CSF
TYPE(FPDSPHY), POINTER :: GFP_LSF
TYPE(FPDSPHY), POINTER :: GFP_Z0F
TYPE(FPDSPHY), POINTER :: GFP_LZ0H
TYPE(FPDSPHY), POINTER :: GFP_TCW
TYPE(FPDSPHY), POINTER :: GFP_TCWV
TYPE(FPDSPHY), POINTER :: GFP_SSRD
TYPE(FPDSPHY), POINTER :: GFP_STRD
TYPE(FPDSPHY), POINTER :: GFP_SSRDC
TYPE(FPDSPHY), POINTER :: GFP_STRDC
TYPE(FPDSPHY), POINTER :: GFP_TCO3
TYPE(FPDSPHY), POINTER :: GFP_TCGHG(:)
TYPE(FPDSPHY), POINTER :: GFP_TCCHEM(:)
TYPE(FPDSPHY), POINTER :: GFP_EMIS2D(:)
TYPE(FPDSPHY), POINTER :: GFP_EMIS2DAUX(:)
TYPE(FPDSPHY), POINTER :: GFP_CHEMFLXO(:)
TYPE(FPDSPHY), POINTER :: GFP_CHEMWDFLX(:)
TYPE(FPDSPHY), POINTER :: GFP_CHEMDDFLX(:)
TYPE(FPDSPHY), POINTER :: GFP_AERODIAG(:,:)
TYPE(FPDSPHY), POINTER :: GFP_AERO_WVL_DIAG(:,:)
TYPE(FPDSPHY), POINTER :: GFP_MXCAP6
TYPE(FPDSPHY), POINTER :: GFP_MXCAPS6
TYPE(FPDSPHY), POINTER :: GFP_TPR
TYPE(FPDSPHY), POINTER :: GFP_VIWVN
TYPE(FPDSPHY), POINTER :: GFP_VIWVE
TYPE(FPDSPHY), POINTER :: GFP_EC20D
TYPE(FPDSPHY), POINTER :: GFP_FCA1
TYPE(FPDSPHY), POINTER :: GFP_FCA2
TYPE(FPDSPHY), POINTER :: GFP_ICTH
TYPE(FPDSPHY), POINTER :: GFP_MLD
TYPE(FPDSPHY), POINTER :: GFP_SSH
TYPE(FPDSPHY), POINTER :: GFP_SSS
TYPE(FPDSPHY), POINTER :: GFP_TEM3
TYPE(FPDSPHY), POINTER :: GFP_SAL3

TYPE(FPDSPHY), POINTER :: GFP_SUND
TYPE(FPDSPHY), POINTER :: GFP_CHAR
TYPE(FPDSPHY), POINTER :: GFP_BLH
TYPE(FPDSPHY), POINTER :: GFP_BV
TYPE(FPDSPHY), POINTER :: GFP_TCLW
TYPE(FPDSPHY), POINTER :: GFP_TCIW
TYPE(FPDSPHY), POINTER :: GFP_TCRW
TYPE(FPDSPHY), POINTER :: GFP_TCSW
TYPE(FPDSPHY), POINTER :: GFP_TCSLW
TYPE(FPDSPHY), POINTER :: GFP_VX2(:)
TYPE(FPDSPHY), POINTER :: GFP_FSU(:)
TYPE(FPDSPHY), POINTER :: GFP_CVL
TYPE(FPDSPHY), POINTER :: GFP_CO2TYP
TYPE(FPDSPHY), POINTER :: GFP_CVH
TYPE(FPDSPHY), POINTER :: GFP_FWET
TYPE(FPDSPHY), POINTER :: GFP_CUR
TYPE(FPDSPHY), POINTER :: GFP_TVL
TYPE(FPDSPHY), POINTER :: GFP_TVH
TYPE(FPDSPHY), POINTER :: GFP_LAIL
TYPE(FPDSPHY), POINTER :: GFP_LAIH
TYPE(FPDSPHY), POINTER :: GFP_CI
TYPE(FPDSPHY), POINTER :: GFP_ASN
TYPE(FPDSPHY), POINTER :: GFP_RSN
TYPE(FPDSPHY), POINTER :: GFP_SST
TYPE(FPDSPHY), POINTER :: GFP_ISTL1
TYPE(FPDSPHY), POINTER :: GFP_ISTL2
TYPE(FPDSPHY), POINTER :: GFP_ISTL3
TYPE(FPDSPHY), POINTER :: GFP_ISTL4
TYPE(FPDSPHY), POINTER :: GFP_TSRC
TYPE(FPDSPHY), POINTER :: GFP_TTRC
TYPE(FPDSPHY), POINTER :: GFP_SSRC
TYPE(FPDSPHY), POINTER :: GFP_STRC
TYPE(FPDSPHY), POINTER :: GFP_ES
TYPE(FPDSPHY), POINTER :: GFP_SMLT
TYPE(FPDSPHY), POINTER :: GFP_LSPF
TYPE(FPDSPHY), POINTER :: GFP_10FG
TYPE(FPDSPHY), POINTER :: GFP_10FG3
TYPE(FPDSPHY), POINTER :: GFP_10FG6
TYPE(FPDSPHY), POINTER :: GFP_I10FG
TYPE(FPDSPHY), POINTER :: GFP_ASEA
TYPE(FPDSPHY), POINTER :: GFP_ALAN
TYPE(FPDSPHY), POINTER :: GFP_ASOO
TYPE(FPDSPHY), POINTER :: GFP_ADES
TYPE(FPDSPHY), POINTER :: GFP_ASUL
TYPE(FPDSPHY), POINTER :: GFP_AVOL
TYPE(FPDSPHY), POINTER :: GFP_O3A
TYPE(FPDSPHY), POINTER :: GFP_O3B
TYPE(FPDSPHY), POINTER :: GFP_O3C
TYPE(FPDSPHY), POINTER :: GFP_SPAR
TYPE(FPDSPHY), POINTER :: GFP_SUVB
TYPE(FPDSPHY), POINTER :: GFP_CAPE
TYPE(FPDSPHY), POINTER :: GFP_MUCAPE
TYPE(FPDSPHY), POINTER :: GFP_MLCAPE50
TYPE(FPDSPHY), POINTER :: GFP_MLCAPE100
TYPE(FPDSPHY), POINTER :: GFP_PDEPL
TYPE(FPDSPHY), POINTER :: GFP_CAPES
TYPE(FPDSPHY), POINTER :: GFP_TROPOTP
TYPE(FPDSPHY), POINTER :: GFP_SPARC
TYPE(FPDSPHY), POINTER :: GFP_STINC
TYPE(FPDSPHY), POINTER :: GFP_SFDIR
TYPE(FPDSPHY), POINTER :: GFP_SCDIR
TYPE(FPDSPHY), POINTER :: GFP_SDSRP
TYPE(FPDSPHY), POINTER :: GFP_VIMD
TYPE(FPDSPHY), POINTER :: GFP_CBASE
TYPE(FPDSPHY), POINTER :: GFP_0DEGL
TYPE(FPDSPHY), POINTER :: GFP_M10DEGL
TYPE(FPDSPHY), POINTER :: GFP_VISIH
TYPE(FPDSPHY), POINTER :: GFP_CIN
TYPE(FPDSPHY), POINTER :: GFP_MLCIN50
TYPE(FPDSPHY), POINTER :: GFP_MLCIN100
TYPE(FPDSPHY), POINTER :: GFP_KINDEX
TYPE(FPDSPHY), POINTER :: GFP_TTINDEX
TYPE(FPDSPHY), POINTER :: GFP_CBASEA
TYPE(FPDSPHY), POINTER :: GFP_CTOPC
TYPE(FPDSPHY), POINTER :: GFP_ZTWETB0
TYPE(FPDSPHY), POINTER :: GFP_ZTWETB1
TYPE(FPDSPHY), POINTER :: GFP_SO2DD
TYPE(FPDSPHY), POINTER :: GFP_URBF
TYPE(FPDSPHY), POINTER :: GFP_ODSS
TYPE(FPDSPHY), POINTER :: GFP_ODDU
TYPE(FPDSPHY), POINTER :: GFP_ODOM
TYPE(FPDSPHY), POINTER :: GFP_ODBC
TYPE(FPDSPHY), POINTER :: GFP_ODSU
TYPE(FPDSPHY), POINTER :: GFP_ODNI
TYPE(FPDSPHY), POINTER :: GFP_ODAM
TYPE(FPDSPHY), POINTER :: GFP_ODSOA
TYPE(FPDSPHY), POINTER :: GFP_ODVFA
TYPE(FPDSPHY), POINTER :: GFP_ODVSU
TYPE(FPDSPHY), POINTER :: GFP_ODTOACC
TYPE(FPDSPHY), POINTER :: GFP_AEPM1
TYPE(FPDSPHY), POINTER :: GFP_AEPM25
TYPE(FPDSPHY), POINTER :: GFP_AEPM10
TYPE(FPDSPHY), POINTER :: GFP_UVBED
TYPE(FPDSPHY), POINTER :: GFP_UVBEDCS
TYPE(FPDSPHY), POINTER :: GFP_DMSO
TYPE(FPDSPHY), POINTER :: GFP_AERDEP
TYPE(FPDSPHY), POINTER :: GFP_AERLTS
TYPE(FPDSPHY), POINTER :: GFP_AERSCC
TYPE(FPDSPHY), POINTER :: GFP_DSF
TYPE(FPDSPHY), POINTER :: GFP_DSZ
TYPE(FPDSPHY), POINTER :: GFP_UCUR
TYPE(FPDSPHY), POINTER :: GFP_VCUR
TYPE(FPDSPHY), POINTER :: GFP_100U
TYPE(FPDSPHY), POINTER :: GFP_100V
TYPE(FPDSPHY), POINTER :: GFP_100SI
TYPE(FPDSPHY), POINTER :: GFP_200U
TYPE(FPDSPHY), POINTER :: GFP_200V
TYPE(FPDSPHY), POINTER :: GFP_200SI
TYPE(FPDSPHY), POINTER :: GFP_ZUST
TYPE(FPDSPHY), POINTER :: GFP_10NU
TYPE(FPDSPHY), POINTER :: GFP_10NV
TYPE(FPDSPHY), POINTER :: GFP_DNDZN
TYPE(FPDSPHY), POINTER :: GFP_DNDZA
TYPE(FPDSPHY), POINTER :: GFP_DCTB
TYPE(FPDSPHY), POINTER :: GFP_TPLB
TYPE(FPDSPHY), POINTER :: GFP_TPLT
TYPE(FPDSPHY), POINTER :: GFP_LITOTI
TYPE(FPDSPHY), POINTER :: GFP_LITOTA1
TYPE(FPDSPHY), POINTER :: GFP_LITOTA3
TYPE(FPDSPHY), POINTER :: GFP_LITOTA6
TYPE(FPDSPHY), POINTER :: GFP_LICGI
TYPE(FPDSPHY), POINTER :: GFP_LICGA1
TYPE(FPDSPHY), POINTER :: GFP_LICGA3
TYPE(FPDSPHY), POINTER :: GFP_LICGA6
TYPE(FPDSPHY), POINTER :: GFP_PTYPEMODE1
TYPE(FPDSPHY), POINTER :: GFP_PTYPEMODE3
TYPE(FPDSPHY), POINTER :: GFP_PTYPEMODE6
TYPE(FPDSPHY), POINTER :: GFP_PTYPESEVR1
TYPE(FPDSPHY), POINTER :: GFP_PTYPESEVR3
TYPE(FPDSPHY), POINTER :: GFP_PTYPESEVR6
TYPE(FPDSPHY), POINTER :: GFP_CLBT
TYPE(FPDSPHY), POINTER :: GFP_CSBT
TYPE(FPDSPHY), POINTER :: GFP_CLSP
TYPE(FPDSPHY), POINTER :: GFP_CCP
TYPE(FPDSPHY), POINTER :: GFP_CLSS
TYPE(FPDSPHY), POINTER :: GFP_CCSF
TYPE(FPDSPHY), POINTER :: GFP_CLSG
TYPE(FPDSPHY), POINTER :: GFP_CCSG
TYPE(FPDSPHY), POINTER :: GFP_CLSH
TYPE(FPDSPHY), POINTER :: GFP_CCSH
TYPE(FPDSPHY), POINTER :: GFP_CUSS
TYPE(FPDSPHY), POINTER :: GFP_CVSS
TYPE(FPDSPHY), POINTER :: GFP_CSSH
TYPE(FPDSPHY), POINTER :: GFP_CSLH
TYPE(FPDSPHY), POINTER :: GFP_CTSP
TYPE(FPDSPHY), POINTER :: GFP_CTCC
TYPE(FPDSPHY), POINTER :: GFP_CBLD
TYPE(FPDSPHY), POINTER :: GFP_CSMR
TYPE(FPDSPHY), POINTER :: GFP_CSSR
TYPE(FPDSPHY), POINTER :: GFP_CSTR
TYPE(FPDSPHY), POINTER :: GFP_CTSR
TYPE(FPDSPHY), POINTER :: GFP_CTTR
TYPE(FPDSPHY), POINTER :: GFP_CCCC
TYPE(FPDSPHY), POINTER :: GFP_CHCC
TYPE(FPDSPHY), POINTER :: GFP_CMCC
TYPE(FPDSPHY), POINTER :: GFP_CLCC
TYPE(FPDSPHY), POINTER :: GFP_CUGW
TYPE(FPDSPHY), POINTER :: GFP_CVGW
TYPE(FPDSPHY), POINTER :: GFP_CUTO
TYPE(FPDSPHY), POINTER :: GFP_CVTO
TYPE(FPDSPHY), POINTER :: GFP_CE
TYPE(FPDSPHY), POINTER :: GFP_CS
TYPE(FPDSPHY), POINTER :: GFP_CT
TYPE(FPDSPHY), POINTER :: GFP_CLHE
TYPE(FPDSPHY), POINTER :: GFP_CLHS
TYPE(FPDSPHY), POINTER :: GFP_CLHT
TYPE(FPDSPHY), POINTER :: GFP_CWS
TYPE(FPDSPHY), POINTER :: GFP_CSNS
TYPE(FPDSPHY), POINTER :: GFP_CQTO
TYPE(FPDSPHY), POINTER :: GFP_CTO3
TYPE(FPDSPHY), POINTER :: GFP_CTME
TYPE(FPDSPHY), POINTER :: GFP_CICE
TYPE(FPDSPHY), POINTER :: GFP_CLI
TYPE(FPDSPHY), POINTER :: GFP_CCVU
TYPE(FPDSPHY), POINTER :: GFP_CCVV
TYPE(FPDSPHY), POINTER :: GFP_CCVQ
TYPE(FPDSPHY), POINTER :: GFP_CCVS
TYPE(FPDSPHY), POINTER :: GFP_CTUQ
TYPE(FPDSPHY), POINTER :: GFP_CTUS
TYPE(FPDSPHY), POINTER :: GFP_CSOC
TYPE(FPDSPHY), POINTER :: GFP_CTSOC
TYPE(FPDSPHY), POINTER :: GFP_CTHC
TYPE(FPDSPHY), POINTER :: GFP_CTTHC
TYPE(FPDSPHY), POINTER :: GFP_CSOP
TYPE(FPDSPHY), POINTER :: GFP_CTOP
TYPE(FPDSPHY), POINTER :: GFP_CSOD
TYPE(FPDSPHY), POINTER :: GFP_CTHD
TYPE(FPDSPHY), POINTER :: GFP_CDNI
TYPE(FPDSPHY), POINTER :: GFP_CGNI
TYPE(FPDSPHY), POINTER :: GFP_CFON
TYPE(FPDSPHY), POINTER :: GFP_CCHS
TYPE(FPDSPHY), POINTER :: GFP_CEAS
TYPE(FPDSPHY), POINTER :: GFP_CSRU
TYPE(FPDSPHY), POINTER :: GFP_CDRU
TYPE(FPDSPHY), POINTER :: GFP_CIRU
TYPE(FPDSPHY), POINTER :: GFP_CETP
TYPE(FPDSPHY), POINTER :: GFP_CTP
TYPE(FPDSPHY), POINTER :: GFP_CDUTP
TYPE(FPDSPHY), POINTER :: GFP_XTCC
TYPE(FPDSPHY), POINTER :: GFP_X10U
TYPE(FPDSPHY), POINTER :: GFP_X10V
TYPE(FPDSPHY), POINTER :: GFP_X10FF
TYPE(FPDSPHY), POINTER :: GFP_X2T
TYPE(FPDSPHY), POINTER :: GFP_X2TPW
TYPE(FPDSPHY), POINTER :: GFP_X2SH
TYPE(FPDSPHY), POINTER :: GFP_X2RH
TYPE(FPDSPHY), POINTER :: GFP_XCCC
TYPE(FPDSPHY), POINTER :: GFP_XHCC
TYPE(FPDSPHY), POINTER :: GFP_XMCC
TYPE(FPDSPHY), POINTER :: GFP_XLCC
TYPE(FPDSPHY), POINTER :: GFP_XX2T
TYPE(FPDSPHY), POINTER :: GFP_XN2T
TYPE(FPDSPHY), POINTER :: GFP_XCVU
TYPE(FPDSPHY), POINTER :: GFP_XCVV
TYPE(FPDSPHY), POINTER :: GFP_XCVQ
TYPE(FPDSPHY), POINTER :: GFP_XCVS
TYPE(FPDSPHY), POINTER :: GFP_XTUU
TYPE(FPDSPHY), POINTER :: GFP_XTUV
TYPE(FPDSPHY), POINTER :: GFP_XTUQ
TYPE(FPDSPHY), POINTER :: GFP_XTUS
TYPE(FPDSPHY), POINTER :: GFP_XGDU
TYPE(FPDSPHY), POINTER :: GFP_XGDV
TYPE(FPDSPHY), POINTER :: GFP_XLSP
TYPE(FPDSPHY), POINTER :: GFP_XCP
TYPE(FPDSPHY), POINTER :: GFP_XLSS
TYPE(FPDSPHY), POINTER :: GFP_XCSF
TYPE(FPDSPHY), POINTER :: GFP_XLSG
TYPE(FPDSPHY), POINTER :: GFP_XCSG
TYPE(FPDSPHY), POINTER :: GFP_XLSH
TYPE(FPDSPHY), POINTER :: GFP_XCSH
TYPE(FPDSPHY), POINTER :: GFP_XSSR
TYPE(FPDSPHY), POINTER :: GFP_XSTR
TYPE(FPDSPHY), POINTER :: GFP_XTSR
TYPE(FPDSPHY), POINTER :: GFP_XTTR
TYPE(FPDSPHY), POINTER :: GFP_XCAPE
TYPE(FPDSPHY), POINTER :: GFP_XCTOP
TYPE(FPDSPHY), POINTER :: GFP_XMOCO
TYPE(FPDSPHY), POINTER :: GFP_XCLPH
TYPE(FPDSPHY), POINTER :: GFP_XVEIN
TYPE(FPDSPHY), POINTER :: GFP_XMRT
TYPE(FPDSPHY), POINTER :: GFP_XGUST
TYPE(FPDSPHY), POINTER :: GFP_XUGST
TYPE(FPDSPHY), POINTER :: GFP_XVGST
TYPE(FPDSPHY), POINTER :: GFP_XX2HU
TYPE(FPDSPHY), POINTER :: GFP_XN2HU
TYPE(FPDSPHY), POINTER :: GFP_INCTX
TYPE(FPDSPHY), POINTER :: GFP_INCTN
TYPE(FPDSPHY), POINTER :: GFP_INCHX
TYPE(FPDSPHY), POINTER :: GFP_INCHN
TYPE(FPDSPHY), POINTER :: GFP_XTHW
TYPE(FPDSPHY), POINTER :: GFP_XXDIAGH
TYPE(FPDSPHY), POINTER :: GFP_ACCGREL
TYPE(FPDSPHY), POINTER :: GFP_X10NU
TYPE(FPDSPHY), POINTER :: GFP_X10NV
TYPE(FPDSPHY), POINTER :: GFP_XUGST2
TYPE(FPDSPHY), POINTER :: GFP_XVGST2
TYPE(FPDSPHY), POINTER :: GFP_VISICLD
TYPE(FPDSPHY), POINTER :: GFP_CFLASH
TYPE(FPDSPHY), POINTER :: GFP_VISIHYD
TYPE(FPDSPHY), POINTER :: GFP_MXCLWC
TYPE(FPDSPHY), POINTER :: GFP_VISICLD2
TYPE(FPDSPHY), POINTER :: GFP_VISIHYD2
TYPE(FPDSPHY), POINTER :: GFP_MXCLWC2
TYPE(FPDSPHY), POINTER :: GFP_XPTYPE
TYPE(FPDSPHY), POINTER :: GFP_XPTYPESEV
TYPE(FPDSPHY), POINTER :: GFP_XPTYPE2
TYPE(FPDSPHY), POINTER :: GFP_XPTYPESEV2
! ------------------------------------------------------------------

NAMELIST/NAMAFN/ &
& GFP_VX2   ,GFP_FSU   ,GFP_10U   ,GFP_10V   ,GFP_2D    ,GFP_2T    , &
& GFP_SUND  ,GFP_BLH   ,GFP_ACOT  ,GFP_AL    ,GFP_ALB   ,GFP_ALSN  , &
& GFP_ALUVP ,GFP_ALUVD ,GFP_ALNIP ,GFP_ALNID , &
& GFP_ALUVI ,GFP_ALNII ,GFP_ALUVV ,GFP_ALNIV, GFP_ALUVG ,GFP_ALNIG , &
& GFP_AERDEP,GFP_AERLTS,GFP_AERSCC,GFP_DSF   ,GFP_DSZ   ,GFP_UCUR  ,GFP_VCUR  , &
& GFP_ODVFA ,GFP_ODVSU ,GFP_AEPM1 ,GFP_AEPM25,GFP_AEPM10,GFP_DMSO  , &
& GFP_UVBED ,GFP_UVBEDCS , GFP_EC20D, &
& GFP_SO2DD ,GFP_URBF  ,GFP_ALBHIS,&
& GFP_ANOR  ,GFP_ARG   ,GFP_BAAL  ,GFP_BLD   ,GFP_BSR   ,GFP_CBLD  , &
& GFP_CCC   ,GFP_CCCC  ,GFP_CCHS  ,GFP_CCP   ,GFP_CCSF  ,GFP_CCSG  , &
& GFP_CCSH  ,GFP_CCVQ  ,GFP_CCVS  ,GFP_CCVU  , &
& GFP_CCVV  ,GFP_CDRU  ,GFP_CDSW  ,GFP_CE    ,GFP_CEAS  ,GFP_CETP  , &
& GFP_CFON  ,GFP_CHAR  ,GFP_CHCC  ,GFP_CICE  ,GFP_CIRU  ,GFP_CLCC  , &
& GFP_CLHE  ,GFP_CLHS  ,GFP_CLI   ,GFP_CLSG  ,GFP_CLSH  ,GFP_CLSP  , &
& GFP_CLSS  ,GFP_CMCC  ,GFP_CP    ,GFP_CQTO  ,GFP_CS    ,GFP_CSF   , &
& GFP_CSLH  ,GFP_CSNS  ,GFP_CSOC  ,GFP_CSOD  ,GFP_CSOP  ,GFP_CSRU  , &
& GFP_CSSH  ,GFP_CSSR  ,GFP_CSSW  ,GFP_CSTR  ,GFP_CTCC  ,GFP_CTHC  , &
& GFP_CTHD  ,GFP_CDNI  ,GFP_CGNI  , &
& GFP_CTME  ,GFP_CTO3  ,GFP_CTOP  ,GFP_CTP   ,GFP_CTSP  , &
& GFP_CTSR  ,GFP_CTTR  ,GFP_CTUQ  ,GFP_CTUS  ,GFP_CUGW  ,GFP_CUSS  , &
& GFP_CVGW  ,GFP_CVSS  ,GFP_CTSOC ,GFP_CTTHC ,GFP_CWS   ,GFP_D2    , &
& GFP_DPAT  ,GFP_XX2HU ,GFP_XN2HU ,GFP_DST   ,GFP_DSW   ,GFP_E     ,GFP_PEV ,&
& GFP_EMIS  ,GFP_EWSS  ,GFP_FDSW  ,GFP_FZRA  ,GFP_GFIS  ,GFP_GWD   ,GFP_HCC ,&
& GFP_HV    ,GFP_IC    ,GFP_IE    ,GFP_IEWSS ,GFP_INSSS ,GFP_ISOR  , &
& GFP_ISTL1 ,GFP_ISTL2 ,GFP_ISTL3 ,GFP_ISTL4 , &
& GFP_ISSHF ,GFP_IVEG  ,GFP_LAI   ,GFP_LAN   ,GFP_LCC   ,GFP_LGWS  , &
& GFP_LSF   ,GFP_LSM   ,GFP_LSP   ,GFP_LSRH  ,GFP_LZ0H  ,GFP_MCC   , &
& GFP_MGWS  ,GFP_MN2T  ,GFP_MSLD  ,GFP_MX2T  ,GFP_NSSS  ,GFP_RDST  , &
& GFP_RDSW  ,GFP_RO    ,GFP_RSMIN ,GFP_SAB   ,GFP_SD    ,GFP_SDOG  , &
& GFP_SF    ,GFP_SKT   ,GFP_SLHF  ,GFP_SLOR  ,GFP_SNDE  ,GFP_SR    , &
& GFP_SRC   ,GFP_SSHF  ,GFP_SSR   ,GFP_SSRD  ,GFP_SSRDC ,GFP_SSW   ,GFP_ST    , &
& GFP_STL1  ,GFP_STL2  ,GFP_STL3  ,GFP_STL4  ,GFP_STR   ,GFP_STRD  ,GFP_STRDC , &
& GFP_SWL1  ,GFP_SWL2  ,GFP_SWL3  ,GFP_SWL4  ,GFP_TCC   ,GFP_TCO3  , &
& GFP_ITZ0  ,GFP_IDZ0  ,GFP_TCCHEM,GFP_CHEMFLXO, GFP_CHEMWDFLX, GFP_CHEMDDFLX,  GFP_XXDIAGH,&
& GFP_CLK   ,GFP_DL    ,GFP_LMLT  ,GFP_LMLD  ,GFP_LBLT  ,GFP_LTLT  , &
& GFP_LSHF  ,GFP_LICT  ,GFP_LICD  ,&
& GFP_NEE   ,GFP_GPP   ,GFP_REC   ,GFP_INEE  ,GFP_IGPP  ,GFP_IREC  , GFP_ICH4 , &
& GFP_TCW   ,GFP_TCWV  ,GFP_TSN   ,GFP_TSR   ,GFP_TTR   ,GFP_PSRHU , &
& GFP_PADOU ,GFP_PADOV ,GFP_PCAAG ,GFP_VEG   ,GFP_X10U  ,GFP_X10V  , &
& GFP_X10NU ,GFP_X10NV ,GFP_X2TPW , &
& GFP_X2RH  ,GFP_X2SH  ,GFP_X2T   ,GFP_XCCC  ,GFP_XCSG  ,GFP_XCSH  , &
& GFP_XGDU  ,GFP_XGDV  ,GFP_XHCC  ,GFP_XLCC  ,GFP_XLSG  ,GFP_XLSH  , &
& GFP_XLSP  ,GFP_XLSS  ,GFP_XMCC  ,GFP_PCAPG , &
& GFP_XCP   ,GFP_XCSF  ,GFP_XCVQ  ,GFP_XCVS  ,GFP_XCVU  ,GFP_XCVV  , &
& GFP_XN2T  ,GFP_XSSR  ,GFP_XSTR  ,GFP_XTCC  ,GFP_XTSR  ,GFP_XTTR  , &
& GFP_XTUQ  ,GFP_XTUS  ,GFP_XTUU  ,GFP_XTUV  ,GFP_XX2T  ,GFP_Z0F   , &
& GFP_Z0H   ,GFP_X10FF ,GFP_XCAPE ,GFP_XCTOP ,GFP_XMOCO ,GFP_XCLPH , &
& GFP_XGUST ,GFP_XUGST ,GFP_XVGST ,GFP_XUGST2,GFP_XVGST2,GFP_CSMR  , & 
& GFP_FSSW  ,GFP_CDUTP ,GFP_ALS   , &
& GFP_ALV   ,GFP_SFIS  ,GFP_PVGMX ,GFP_Z0V   ,GFP_PURB  ,GFP_D2MX  , &
& GFP_SPAR  ,GFP_SUVB  ,GFP_CAPE  ,GFP_CAPES ,GFP_MXCAP6,GFP_MXCAPS6,&
& GFP_MLCAPE50         ,GFP_MLCAPE100        ,GFP_MUCAPE,GFP_PDEPL , &
& GFP_MLCIN50          ,GFP_MLCIN100         ,GFP_TROPOTP          , &
& GFP_TCLW  ,GFP_TCIW  ,GFP_RSN   , &
& GFP_TCRW  ,GFP_TCSW  ,GFP_TCSLW ,GFP_VIWVE ,GFP_VIWVN ,GFP_SST   , &
& GFP_CI    ,GFP_ASN   ,GFP_MXTPR ,GFP_MNTPR ,GFP_MXTPR6,GFP_MNTPR6, &
& GFP_TPR   ,GFP_LSRR  ,GFP_CRR   ,GFP_LSSFR ,GFP_CSFR  ,GFP_XVEIN , &
& GFP_XMRT  ,GFP_PTYPE ,GFP_ILSPF ,GFP_I10FG , &
& GFP_ASEA  ,GFP_ALAN  ,GFP_ASOO  ,GFP_ADES  ,GFP_ASUL  ,GFP_AVOL  , &
& GFP_O3A   ,GFP_O3B   ,GFP_O3C   ,GFP_SFDIR ,GFP_SDSRP, GFP_SCDIR , &
& GFP_CGPP,  GFP_CREC                                              , &
& GFP_CBASE ,GFP_0DEGL ,GFP_M10DEGL,GFP_VISIH                      , &
& GFP_CIN   ,GFP_KINDEX,GFP_TTINDEX                                , &
& GFP_CBASEA,GFP_CTOPC ,GFP_ZTWETB0,GFP_ZTWETB1                    , &
& GFP_SDFOR ,GFP_SOTY   , &
& GFP_CUTO  ,GFP_CVTO  ,GFP_CT    ,GFP_CLHT  ,                       &
& GFP_VISICLD ,GFP_VISIHYD, GFP_MXCLWC ,GFP_XPTYPE ,GFP_XPTYPESEV  , &
& GFP_CFLASH, &
& GFP_VISICLD2,GFP_VISIHYD2, GFP_MXCLWC2,GFP_XPTYPE2,GFP_XPTYPESEV2, &
& TFP_Z     ,TFP_T     ,TFP_U     ,TFP_V     ,TFP_Q     ,TFP_HU    , &
& TFP_VV    ,TFP_VOR   ,TFP_DIV   ,TFP_PSI   ,TFP_KHI   ,TFP_L     , &
& TFP_I     ,TFP_SN    ,TFP_RR    ,TFP_GR    ,TFP_HL    ,TFP_TKE   , &
& TFP_TH    ,TFP_THPW  ,TFP_CLF   ,TFP_O3MX  ,TFP_THV   ,TFP_TPW   , &
& TFP_WND   ,TFP_ETH   ,TFP_ABS   ,TFP_STD   ,TFP_PV    ,TFP_TWV   , &
& TFP_SHD   ,TFP_P     ,TFP_PD    ,TFP_VD    ,TFP_VW    ,TFP_FUA   , &
& TFP_EXT   ,TFP_MG    ,TFP_HUX   ,TFP_SP    ,TFP_MSL   ,TFP_FIS   , &
& TFP_GM    ,TFP_FOL   ,TFP_WWS   ,TFP_LNSP  ,TFP_UCLS  ,TFP_VCLS  , &
& TFP_TCLS  ,TFP_QCLS  ,TFP_RCLS  ,TFP_FCLS  ,TFP_CAPE  ,TFP_CIEN  , &
& TFP_MOCO  ,TFP_UGST  ,TFP_VGST  ,TFP_FGST  ,TFP_HCLP  ,TFP_UJET  , &
& TFP_VJET  ,TFP_PJET  ,TFP_TCAO  ,TFP_PCAO  ,TFP_FSU   ,TFP_TX    , &
& TFP_TN    ,TFP_PTB   ,TFP_HTB   ,TFP_HTPW  ,TFP_HUN   ,TFP_IET   , &
& TFP_SMC   ,TFP_ASMC  ,TFP_RHO   ,TFP_QNH   ,TFP_HTPW1 ,TFP_HTPW2 , &
& TFP_CUF1  ,TFP_CUF2  ,TFP_CUF3  ,TFP_CUF4  ,TFP_CUF5  ,TFP_VEIN  , &
& TFP_GHG   ,TFP_AERO  ,TFP_RKTH  ,TFP_RKTQV ,TFP_RKTQC ,TFP_TCVS  , &
& TFP_LRAD  ,TFP_IRAD  ,TFP_TTE   ,TFP_MXL   ,TFP_SHTUR ,TFP_FQTUR , &
& TFP_FSTUR ,TFP_VSMC  ,TFP_CPF   ,TFP_SPF   , &
& TFP_DAL   ,TFP_DOM   ,TFP_UAL   ,TFP_UOM   ,TFP_UEN   ,TFP_UNEBH , &
& TFP_LCL   ,TFP_FCL   ,TFP_EL    ,&
& TFP_SRE   ,TFP_SREX  ,TFP_SREDB ,TFP_SREDBX, TFP_TOPR, &
& TFP_MSAT7C1  ,TFP_MSAT7C2  ,&
& TFP_MSAT8C1  ,TFP_MSAT8C2  ,TFP_MSAT8C3  ,TFP_MSAT8C4 ,&
& TFP_MSAT8C5  ,TFP_MSAT8C6  ,TFP_MSAT8C7  ,TFP_MSAT8C8 ,&
& TFP_MSAT9C1  ,TFP_MSAT9C2  ,TFP_MSAT9C3  ,TFP_MSAT9C4 ,&
& TFP_MSAT9C5  ,TFP_MSAT9C6  ,TFP_MSAT9C7  ,TFP_MSAT9C8 ,&
& TFP_GOES11C1 ,TFP_GOES11C2 ,TFP_GOES11C3 ,TFP_GOES11C4,&
& TFP_GOES12C1 ,TFP_GOES12C2 ,TFP_GOES12C3 ,TFP_GOES12C4,&
& TFP_MTSAT1C1 ,TFP_MTSAT1C2 ,TFP_MTSAT1C3 ,TFP_MTSAT1C4,&
& TFP_EDR      ,TFP_EDRP     ,TFP_MSLNH    ,TFP_SPNH
!    -----------------------------------------------------------------
