! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

!     ------------------------------------------------------------------
NAMELIST/NAMDYN/REPS1 ,REPS2 ,REPSP1,REPSM1,REPSM2 &
      &,HDIRVOR,HDIRDIV,HDIRT,HDIRQ,HDIRO3,HDIRPD,HDIRVD,HDIRSP &
      &,BETADT,XIDT,REFGEO,NVLAG,NITMP &
      &,NWLAG,NTLAG,NSPDLAG,NSVDLAG,NSPLTHOI,NQMHOISLT &
      &,LADVF,LIMPF,NEDER,RALPHA,RALPHA_TOP,NLEV_ZALPHA,LWENOBC &
      &,LRHS_CURV,LSLDP_RK,LSLDP_CURV &
      &,LSLDP_XYZ,LSLDP_SAVE,RW2TLFF,SIPR,SITR,SITRA,NOPT_SITRA,NSITER &
      &,SITRUB,SIPRUB &
      &,LNEWHD,RRDXTAU &
      &,RDAMPVOR,RDAMPDIV,RDAMPT,RDAMPQ,RDAMPO3,RDAMPPD,RDAMPVD,RDAMPSP &
      &,REXPDH,FRANDH,SLEVDH,SLEVDH1,SLEVDH2,SLEVDH3,NSREFDH,RATIO_HDI_TOP &
      &,VNORM, RINTOPT &
      &,VMAX1,VMAX2,VESL &
      &,LBOUND_D3,RMAX_D3 &
      &,LQMW, LQMHW, LQMT, LQMHT, LQMP, LQMHP &
      &,LQMPD,LQMHPD,LQMVD,LQMHVD &
      &,LVWENO_W, LVWENO_T, LVWENO_SP, LVWENO_SPD, LVWENO_SVD &
      &,WENO_ALPHA_W, WENO_ALPHA_T, WENO_ALPHA_SP, WENO_ALPHA_SPD, WENO_ALPHA_SVD &
      &,RCMSLP0,RTEMRB &
      &,VETAON,VETAOX &
      &,NVSEPC,NVSEPL &
      &,SLHDA0,SLHDA0T,SLHDB,SLHDBT,SLHDD00,SLHDD00T,SLHDDIV,SLHDRATDDIV,SLHDHOR &
      &,ZSLHDP1,ZSLHDP3,LSLHDHEAT,LSLHDSPONGE,SLHD_P_LOW,SLHD_P_HIGH &
      &,REXPDHS,SLEVDHS,SLEVDHS1,SLEVDHS2,RDAMPDIVS,SDRED &
      &,RDAMPVORS,RDAMPVDS,RRFZ1,RRFPLM,RRFTAU  &
      &,NCOMP_CVGQ,LRHDI_LASTITERPC,NITERHELM &
      &,LMASDRY,LMASCOR,LGPMASCOR,NGPMASCOR &
      &,LSVTSM,RPRES_SVTSM,LSETTLSVF,LSETTLSVF_DIFF,LSETFSTAT,RPRES_SETTLSVF,RSCALE,RSCALEOFF &
      &,LHDIFFM,NDIFFACT,LGPSTRESS,RCLSTRESS,RCLPOLE,LSPECVIS &
      &,NPROFILEHD,RPROFHDBT,RPROFHDTP,RPROFHDMX,RPROFHDEX,LRDISPE_EC &
      &,NFLEVSF &
      &,LTOP_VOR, NTOP_VOR_TRUNC, NTOP_VOR_BOT, LRFRICISOTR,LRFRIC &
      &,LNODRYFLX, KLSPONGE, RBEGSPONGE, LM0DAMP

!     ------------------------------------------------------------------

