! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

!     ------------------------------------------------------------------
NAMELIST/NAMPHY/&
! * GROUPE DES CLES GENERALES.
  &LMPHYS,LSLC,LREASUR &
! * GROUPE DES CLES NE COMMANDANT PAS L'APPEL AUX ROUTINES AM-----.
  &,LCAPE,LCVSHCU,LCVGQ,LCVGQD,LCVGQM,LCONDWT,LCVCAS,LCVDD,LCVLIS,LCVPP,LNEIGE &
  &,LPEC,LRNUMX,LUDEVOL,LCLSATUR,LRRGUST,LO3ABC,LO3FL,LECSHAL,LECDEEP,LNEBNXR &
  &,LRNUEXP,LRTRUEBBC,LRTRUEDIR,LCLSATUR &
  &,LACPANMX, LFPCOR,LNOIAS,LGLT,LNEWD,LHUCN,LQXRTGH &
  &,LPROCLD,LEVAPP,LCOLLEC,LRELAXT,LRELAXW &
  &,LAEROSEA,LAEROLAN,LAEROSOO,LAERODES,LAEROVOL,LAEROSUL &
  &,LSSD,LPHCDPI,LBLVAR &
  &,LZ0HSREL,LCVPRO,LGRAPRO,LCDDCSD,LCDDPRO,LENTCH,LCDDEVPRO &
  &,LMLH,LNODIFQC,LNCVPGY,LDIFCEXP,LSQRML &
  &,NDPRECPERIOD,LDPRECIPS,NDPRECPERIOD2,LDPRECIPS2 &
! * GROUPE DES CLES COMMANDANT L'APPEL AUX ROUTINES AM-----.
  &,CGMIXLEN,CGTRG,LPRGML,LCVCSD,LCVRA,LGWD,LGWDC,LNORGWD,LNEBCO,LNEBN,LNEBR &
  &,LPTOPC,LNSDO,LOZONE,LRAY,LRAYLU,LREWS &
  &,LRPROX,LRMIX,LRSTAB,LRSTAER,LVOIGT,LVFULL,LRTPP,LRTDL,LRAYPL &
  &,LRAYFM,LRAYFM15,LRMU0M,LRRMES,LSFHYD,LSNV,LSOLV,LFGEL,LSTRA,LSTRAS &
  &,LUSL,LVDIF,L3MT,LGPCMT,LSCMF,LFLUSO,LAJUCV,LCAMOD,LCOMOD &
! * GROUPE DES INDICES DE CALCUL.
  &,NBITER,NCLOMIX,NFSIG,NOIR,NDPSFI,NPHYREP &
  &,LVGSN,LDIFCONS,LDIFQL,LDISTUR,LECT,LEFB,LECTQ1,NLEND,LECTREP &
  &,LPTKE,LCVPGY,LPBLE, NCALLRAD &
  &,LADJCLD,LCVPPKF,LEDKF,LEDMFI,LEDMFS,LECTFL,LECTFL0,LNEBGR,LNEBGY,LCVRAV3 &
  &,LSTRAPRO, LNEWSTAT, LPHSPSH, LSMNIMBT, LSMTPS, LSMGCDEV, LXRCDEV, LRKCDEV &
  &,LSMITH_CDEV,LRCVOTT, LNEBCV, NDIFFNEB, NSMTBOT, NSMDNEB, NPRAC, NPRRI &
  &,NITERFL,NIMELIT,NRAY,NSORAYFR,NTHRAYFR,NRAUTOEV &
  &,LNEB_FP, LNEBECT, LCVGQKF, LACDIFUS, L2MICRO, LNEBINS &
  &,LSEDSTA,LSEDLAG,LSEDCL,LFSVAR,LFSFIX,LA0MPS,LARPMPS,LAB12 &
  &,LAFGD_A, LCVGQP, LSMOOTHMELT, LGLACIERS &
  &,LCOEFKTKE,LCOEFKSURF,LCOEFK_MSC, LCOEFK_THS1,LCOEFK_TOMS,LCOEFK_RIS &
  &,LCOEFK_PL, LCOEFK_RIH,LCOEFK_PTTE,LCOEFK_FLX &
  &,LCOEFK_SCQ,LCOEFK_ML,LCOEFK_F1,CGTURS, LDAYD,LEDR &
  &,LHLRADUPD&
  &,LCVTURB, LNEBRIC

!     ------------------------------------------------------------------
