! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE GENERIC_CTLVEC_MOD
!> Generic control vector for parallel I/O
USE PARKIND1,     ONLY : JPIM, JPRB
USE IOSTREAM_MIX, ONLY : SETUP_IOSTREAM, SETUP_IOREQUEST, IO_PUT,IO_GET, &
 &                       CLOSE_IOSTREAM, TYPE_IOSTREAM, TYPE_IOREQUEST, &
 &                       CLOSE_IOREQUEST
USE MPL_MODULE,   ONLY : MPL_GATHERV, MPL_ALLGATHERV, MPL_SCATTERV,  &
 &                       MPL_ALLGATHERV, MPL_ALLTOALLV
USE YOMHOOK,      ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMMP0,       ONLY : MYPROC, NPROC
IMPLICIT NONE
PRIVATE

TYPE,PUBLIC :: GENERIC_CTLVEC
  INTEGER(KIND=JPIM)       :: NSIZEL  = 0_JPIM
  REAL(KIND=JPRB), POINTER :: DATA(:) => NULL()
CONTAINS
  PROCEDURE :: SET   => SET_GENERIC_CTLVEC
  PROCEDURE :: RESET => RESET_GENERIC_CTLVEC
END TYPE GENERIC_CTLVEC

TYPE,PUBLIC :: MULTI_IO
  LOGICAL                         :: LSETUP
  CHARACTER(LEN=1)                :: CLREQTYPE
  INTEGER(KIND=JPIM)              :: NSIZEL
  INTEGER(KIND=JPIM)              :: NIOPROCS
  INTEGER(KIND=JPIM)              :: NBUFSIZE
  INTEGER(KIND=JPIM), ALLOCATABLE :: NIOPROC(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: ISENDCOUNTS(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: IRECVCOUNTS(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: ILENSR(:)
  INTEGER(KIND=JPIM), ALLOCATABLE :: ILENG(:)
  REAL(KIND=JPRB),    ALLOCATABLE :: ZBUF(:)
CONTAINS  
  PROCEDURE :: SETUP   => SETUP_MULTI_IO
  PROCEDURE :: GATHER  => GATHER_MULTI_IO
  PROCEDURE :: SCATTER => SCATTER_MULTI_IO
  PROCEDURE :: RESET   => RESET_MULTI_IO
END TYPE MULTI_IO

PUBLIC :: GATHER_GENERIC_CTLVEC, &
 &        SCATTER_GENERIC_CTLVEC, &
 &        MULTIGATHER_GENERIC_CTLVEC, &
 &        MULTISCATTER_GENERIC_CTLVEC, &
 &        GET_SIZE_GENERIC_CTLVEC

CONTAINS
! ------------------------------------------------------------------------------

SUBROUTINE SET_GENERIC_CTLVEC(SELF,PBUF)
CLASS(GENERIC_CTLVEC),   INTENT(INOUT) :: SELF
REAL(KIND=JPRB), TARGET, INTENT(IN)    :: PBUF(:)

SELF%NSIZEL = SIZE(PBUF)
SELF%DATA => PBUF(:)

END SUBROUTINE SET_GENERIC_CTLVEC

! ------------------------------------------------------------------------------

SUBROUTINE RESET_GENERIC_CTLVEC(SELF)
CLASS(GENERIC_CTLVEC), INTENT(INOUT) :: SELF

SELF%NSIZEL = 0_JPIM
SELF%DATA => NULL()

END SUBROUTINE RESET_GENERIC_CTLVEC

! ------------------------------------------------------------------------------

SUBROUTINE GATHER_GENERIC_CTLVEC(PARRIN,KIOPROC,PARR)
REAL(KIND=JPRB),            INTENT(IN)  :: PARRIN(:)
INTEGER(KIND=JPIM),         INTENT(IN)  :: KIOPROC
REAL(KIND=JPRB),ALLOCATABLE,INTENT(OUT) :: PARR(:)

INTEGER(KIND=JPIM) :: ILENR(NPROC),ILEN,ILENG
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('GATHER_GENERIC_CTLVEC',0,ZHOOK_HANDLE)

ILEN = SIZE(PARRIN(:))
CALL MPL_ALLGATHERV(ILEN,ILENR)
IF (MYPROC==KIOPROC) THEN
  ILENG = SUM(ILENR)
  ALLOCATE(PARR(ILENG))
ENDIF

CALL MPL_GATHERV(PSENDBUF=PARRIN,KROOT=KIOPROC,PRECVBUF=PARR,&
 & KRECVCOUNTS=ILENR,CDSTRING='GATHER_GENERIC_CTLVEC')

IF (LHOOK) CALL DR_HOOK('GATHER_GENERIC_CTLVEC',1,ZHOOK_HANDLE)

END SUBROUTINE GATHER_GENERIC_CTLVEC

!------------------------------------------------------------------------------

SUBROUTINE SCATTER_GENERIC_CTLVEC(PARROUT,KIOPROC,PARR)
REAL(KIND=JPRB),    INTENT(INOUT) :: PARROUT(:)
INTEGER(KIND=JPIM), INTENT(IN)    :: KIOPROC
REAL(KIND=JPRB),    INTENT(IN)    :: PARR(:)

INTEGER(KIND=JPIM) :: ILENS(NPROC),ILEN,ILENG
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SCATTER_GENERIC_CTLVEC',0,ZHOOK_HANDLE)

ILEN = SIZE(PARROUT)
CALL MPL_ALLGATHERV(ILEN,ILENS)
IF (MYPROC==KIOPROC) THEN
  ILENG = SUM(ILENS)
  IF (SIZE(PARR)/=ILENG) &
   & CALL ABOR1('SCATTER_GENERIC_CTLVEC: PARR WRONG SIZE')
ENDIF

CALL MPL_SCATTERV(PRECVBUF=PARROUT,KROOT=KIOPROC,PSENDBUF=PARR,&
 & KSENDCOUNTS=ILENS,CDSTRING='SCATTER_GENERIC_CTLVEC')

IF (LHOOK) CALL DR_HOOK('SCATTER_GENERIC_CTLVEC',1,ZHOOK_HANDLE)

END SUBROUTINE SCATTER_GENERIC_CTLVEC

!------------------------------------------------------------------------------

SUBROUTINE MULTIGATHER_GENERIC_CTLVEC(YDVECS,KIOPROC,PBUF,KSTART,KEND)

!     Purpose.
!     --------
!       Gather multiple control vectors on multiple PEs.
!       (Based on CONTROL_VECTORS_COMM_MOD:MULTIGATHER_CTLVEC)

! ----------------------------------------------

TYPE(GENERIC_CTLVEC),          INTENT(IN)  :: YDVECS(KSTART:KEND)
INTEGER(KIND=JPIM),            INTENT(IN)  :: KIOPROC(KSTART:KEND)
REAL(KIND=JPRB), ALLOCATABLE,  INTENT(OUT) :: PBUF(:)
INTEGER(KIND=JPIM),            INTENT(IN)  :: KSTART
INTEGER(KIND=JPIM),            INTENT(IN)  :: KEND

INTEGER(KIND=JPIM) :: ISENDCOUNTS(NPROC), IRECVCOUNTS(NPROC)
INTEGER(KIND=JPIM) :: ILENR(NPROC,KSTART:KEND)
INTEGER(KIND=JPIM) :: ILENG(KSTART:KEND),JP,JJ,J,ICNT
REAL(KIND=JPRB), ALLOCATABLE :: ZSENDBUF(:),ZRECVBUF(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MULTIGATHER_GENERIC_CTLVEC',0,ZHOOK_HANDLE)

IRECVCOUNTS(1:NPROC) = 0
DO JJ = KSTART, KEND
  ! Allocate receive buffer
  ! -----------------------
  CALL MPL_ALLGATHERV(KSENDBUF=YDVECS(JJ)%NSIZEL,KRECVBUF=ILENR(:,JJ), &
    &                 CDSTRING='MULTIGATHER_GENERIC_CTLVEC')

  ILENG(JJ)=SUM(ILENR(:,JJ))

  IF (MYPROC==KIOPROC(JJ)) THEN
    ALLOCATE(PBUF(ILENG(JJ)))
    DO JP = 1, NPROC
       IRECVCOUNTS(JP) = ILENR(JP,JJ)
    ENDDO
  ENDIF
ENDDO

! Allocate and fill send buffer
! -----------------------------
ALLOCATE(ZSENDBUF(SUM(ILENR(MYPROC,:))))

ISENDCOUNTS(1:NPROC) = 0
ICNT = 0
DO JJ = KSTART, KEND
  DO J=1, YDVECS(JJ)%NSIZEL
    ICNT = ICNT + 1
    ZSENDBUF(ICNT) = YDVECS(JJ)%DATA(J)
  ENDDO
  ISENDCOUNTS(KIOPROC(JJ)) = YDVECS(JJ)%NSIZEL
ENDDO

IF (SUM(ILENR(MYPROC,:))/=ICNT) &
  & CALL ABOR1('MULTIGATHER_GENERIC_CTLVEC: sendbuf wrong size')

! Exchange data
! -------------
CALL MPL_ALLTOALLV(ZSENDBUF, ISENDCOUNTS, PBUF, IRECVCOUNTS,&
                 & CDSTRING='MULTIGATHER_GENERIC_CTLVEC')

DEALLOCATE(ZSENDBUF)

IF (LHOOK) CALL DR_HOOK('MULTIGATHER_GENERIC_CTLVEC',1,ZHOOK_HANDLE)
END SUBROUTINE MULTIGATHER_GENERIC_CTLVEC

!------------------------------------------------------------------------------

SUBROUTINE MULTISCATTER_GENERIC_CTLVEC(YDVECS,KIOPROC,PBUF,KSTART,KEND)

!     Purpose.
!     --------
!       Scatter multiple control vectors on multiple PEs.
!       (Based on CONTROL_VECTORS_COMM_MOD:MULTISCATTER_CTLVEC)

! ----------------------------------------------

TYPE(GENERIC_CTLVEC), INTENT(INOUT) :: YDVECS(KSTART:KEND)
INTEGER(KIND=JPIM),   INTENT(IN)    :: KIOPROC(KSTART:KEND)
REAL(KIND=JPRB),      INTENT(IN)    :: PBUF(:)
INTEGER(KIND=JPIM),   INTENT(IN)    :: KSTART
INTEGER(KIND=JPIM),   INTENT(IN)    :: KEND

INTEGER(KIND=JPIM) :: ISENDCOUNTS(NPROC), IRECVCOUNTS(NPROC)
INTEGER(KIND=JPIM) :: ILENS(NPROC,KSTART:KEND)
INTEGER(KIND=JPIM) :: ILENG(KSTART:KEND),JP,JJ,J,ICNT
REAL(KIND=JPRB), ALLOCATABLE :: ZSENDBUF(:),ZRECVBUF(:)
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MULTISCATTER_GENERIC_CTLVEC',0,ZHOOK_HANDLE)

ISENDCOUNTS(1:NPROC) = 0
DO JJ = KSTART, KEND
  ! Allocate receive buffer
  ! -----------------------
  CALL MPL_ALLGATHERV(KSENDBUF=YDVECS(JJ)%NSIZEL,KRECVBUF=ILENS(:,JJ), &
    &                 CDSTRING='MULTISCATTER_GENERIC_CTLVEC')

  ILENG(JJ)=SUM(ILENS(:,JJ))

  IF (MYPROC==KIOPROC(JJ)) THEN
    IF (ILENG(JJ)/=SIZE(PBUF)) &
      &  CALL ABOR1('MULTISCATTER_GENERIC_CTLVEC: pcv wrong size')
    DO JP = 1, NPROC
       ISENDCOUNTS(JP) = ILENS(JP,JJ)
    ENDDO
  ENDIF
ENDDO

! Allocate receive buffer
! -----------------------
ALLOCATE(ZRECVBUF(SUM(ILENS(MYPROC,:))))

IRECVCOUNTS(1:NPROC) = 0
DO JJ = KSTART, KEND
  IRECVCOUNTS(KIOPROC(JJ)) = YDVECS(JJ)%NSIZEL
ENDDO

CALL MPL_ALLTOALLV(PBUF, ISENDCOUNTS, ZRECVBUF, IRECVCOUNTS,&
  &                CDSTRING='MULTISCATTER_GENERIC_CTLVEC')

ICNT = 0
DO JJ = KSTART, KEND
  DO J=1, YDVECS(JJ)%NSIZEL
    ICNT = ICNT + 1
    YDVECS(JJ)%DATA(J) = ZRECVBUF(ICNT)
  ENDDO
ENDDO

IF (SUM(ILENS(MYPROC,:))/=ICNT) &
  & CALL ABOR1('MULTISCATTER_GENERIC_CTLVEC: recvbuf wrong size')

DEALLOCATE(ZRECVBUF)

IF (LHOOK) CALL DR_HOOK('MULTISCATTER_GENERIC_CTLVEC',1,ZHOOK_HANDLE)
END SUBROUTINE MULTISCATTER_GENERIC_CTLVEC

!------------------------------------------------------------------------------

SUBROUTINE GET_SIZE_GENERIC_CTLVEC(ZBUF,KLENG,KLENS,KDISPS)
REAL(KIND=JPRB), INTENT(IN) :: ZBUF(:)
INTEGER(KIND=JPIM), INTENT(OUT) :: KLENG
INTEGER(KIND=JPIM), INTENT(OUT) :: KLENS(NPROC)
INTEGER(KIND=JPIM), INTENT(OUT) :: KDISPS(NPROC)
INTEGER(KIND=JPIM) :: JP, ILEN

ILEN = SIZE(ZBUF(:))
CALL MPL_ALLGATHERV(ILEN,KLENS)
KLENG = SUM(KLENS(:))
KDISPS(1)=0
DO JP=2,NPROC
  KDISPS(JP)=KDISPS(JP-1)+KLENS(JP-1)
ENDDO

END SUBROUTINE GET_SIZE_GENERIC_CTLVEC

!------------------------------------------------------------------------------

SUBROUTINE SETUP_MULTI_IO(SELF,CDREQTYPE,KSIZEL,KIOPROC,KIOPROCS)
CLASS(MULTI_IO),    INTENT(INOUT) :: SELF  
CHARACTER(LEN=1),   INTENT(IN)    :: CDREQTYPE  
INTEGER(KIND=JPIM), INTENT(IN)    :: KSIZEL
INTEGER(KIND=JPIM), INTENT(IN)    :: KIOPROC(KIOPROCS)
INTEGER(KIND=JPIM), INTENT(IN)    :: KIOPROCS

INTEGER(KIND=JPIM) :: JP,JJ,J,ICNT,JK,IL,IU
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SETUP_MULTI_IO',0,ZHOOK_HANDLE)

IF (SELF%LSETUP) CALL SELF%RESET()

SELF%CLREQTYPE = CDREQTYPE
SELF%NSIZEL = KSIZEL
SELF%NIOPROCS = KIOPROCS
SELF%NIOPROC = KIOPROC
ALLOCATE(SELF%ILENG(KIOPROCS))
ALLOCATE(SELF%ISENDCOUNTS(NPROC))
ALLOCATE(SELF%IRECVCOUNTS(NPROC))
ALLOCATE(SELF%ILENSR(NPROC))

! Communicate local size to each processor
CALL MPL_ALLGATHERV(KSENDBUF=SELF%NSIZEL,KRECVBUF=SELF%ILENSR(:), &
  &                 CDSTRING='SETUP_MULTI_IO')

IF (CDREQTYPE=="G") THEN
  SELF%ILENG(:)=0
  SELF%IRECVCOUNTS(:) = 0
  IL = 1
  DO JK = 1, SELF%NIOPROCS
    IU = SELF%NIOPROC(JK)
    SELF%ILENG(JK) = SUM(SELF%ILENSR(IL:IU))
    IF (MYPROC==SELF%NIOPROC(JK)) THEN
      DO JP = IL, IU
        SELF%IRECVCOUNTS(JP) = SELF%IRECVCOUNTS(JP) + SELF%ILENSR(JP)
      ENDDO
    ENDIF
    IL = IU + 1
  ENDDO
  
  SELF%ISENDCOUNTS(1:NPROC) = 0
  IL = 1
  DO JK = 1, SELF%NIOPROCS
    IU = SELF%NIOPROC(JK)
    IF (MYPROC >= IL .AND. MYPROC <= IU) THEN
      SELF%ISENDCOUNTS(KIOPROC(JK)) = KSIZEL
    ENDIF  
    IL = IU + 1
  ENDDO
    
  IF (SELF%ILENSR(MYPROC)/=SELF%NSIZEL) &
    & CALL ABOR1('SETUP_MULTI_IO: sendbuf wrong size')

  ALLOCATE(SELF%ZBUF(1))
  DO JK = 1, SELF%NIOPROCS
    IF (MYPROC==SELF%NIOPROC(JK)) THEN
      IF (ALLOCATED(SELF%ZBUF)) DEALLOCATE(SELF%ZBUF)
      ALLOCATE(SELF%ZBUF(SELF%ILENG(JK)))
    ENDIF
  ENDDO

ELSEIF (CDREQTYPE=="S") THEN  

  SELF%ILENG(:)=0
  SELF%ISENDCOUNTS(:) = 0
  IL = 1
  DO JK = 1, SELF%NIOPROCS
    IU = SELF%NIOPROC(JK)
    SELF%ILENG(JK) = SUM(SELF%ILENSR(IL:IU))
    IF (MYPROC==SELF%NIOPROC(JK)) THEN
      DO JP = IL, IU
         SELF%ISENDCOUNTS(JP) = SELF%ISENDCOUNTS(JP) + SELF%ILENSR(JP)
      ENDDO
    ENDIF
    IL = IU + 1
  ENDDO
  
  SELF%IRECVCOUNTS(1:NPROC) = 0
  IL = 1
  DO JK = 1, SELF%NIOPROCS
    IU = SELF%NIOPROC(JK)
    IF (MYPROC >= IL .AND. MYPROC <= IU) THEN
      SELF%IRECVCOUNTS(SELF%NIOPROC(JK)) = KSIZEL
    ENDIF  
    IL = IU + 1
  ENDDO
ELSE  

  CALL ABOR1("SETUP_MULTI_IO: incorrect request")

ENDIF  

SELF%LSETUP=.TRUE.

IF (LHOOK) CALL DR_HOOK('SETUP_MULTI_IO',1,ZHOOK_HANDLE)

END SUBROUTINE SETUP_MULTI_IO

!------------------------------------------------------------------------------

SUBROUTINE GATHER_MULTI_IO(SELF,PDATA)

!     Purpose.
!     --------

! ----------------------------------------------

CLASS(MULTI_IO),    INTENT(INOUT) :: SELF  
REAL(KIND=JPRB),    INTENT(IN)    :: PDATA(SELF%NSIZEL)
INTEGER(KIND=JPIM) :: JK
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('GATHER_MULTI_IO',0,ZHOOK_HANDLE)

! Check if the request is setup correctly
! ---------------------------------------
IF(SELF%LSETUP.EQV..FALSE..OR.SELF%CLREQTYPE/='G') &
  & CALL ABOR1('GATHER_MULTI_IO: incompatible request type/request not setup')

! Exchange data
! -------------
CALL MPL_ALLTOALLV(PDATA, SELF%ISENDCOUNTS, SELF%ZBUF, SELF%IRECVCOUNTS,&
                 & CDSTRING='GATHER_MULTI_IO')

IF (LHOOK) CALL DR_HOOK('GATHER_MULTI_IO',1,ZHOOK_HANDLE)
END SUBROUTINE GATHER_MULTI_IO

!------------------------------------------------------------------------------

SUBROUTINE SCATTER_MULTI_IO(SELF,PDATA,PBUF,KBUFSIZE)

!     Purpose.
!     --------

! ----------------------------------------------

CLASS(MULTI_IO),    INTENT(INOUT)  :: SELF  
REAL(KIND=JPRB),    INTENT(INOUT)  :: PDATA(SELF%NSIZEL)
REAL(KIND=JPRB),    INTENT(IN)     :: PBUF(KBUFSIZE)
INTEGER(KIND=JPIM), INTENT(IN)     :: KBUFSIZE

INTEGER(KIND=JPIM) :: JK
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('SCATTER_MULTI_IO',0,ZHOOK_HANDLE)

! Check if the request is setup correctly
! ---------------------------------------
IF(SELF%LSETUP.EQV..FALSE..OR.SELF%CLREQTYPE/='S') &
  & CALL ABOR1('SCATTER_MULTI_IO: incompatible request type/request not setup')

! Exchange data
! -------------
CALL MPL_ALLTOALLV(PBUF, SELF%ISENDCOUNTS, PDATA, SELF%IRECVCOUNTS,&
                 & CDSTRING='SCATTER_MULTI_IO')

IF (LHOOK) CALL DR_HOOK('SCATTER_MULTI_IO',1,ZHOOK_HANDLE)
END SUBROUTINE SCATTER_MULTI_IO

!------------------------------------------------------------------------------

SUBROUTINE RESET_MULTI_IO(SELF)

!     Purpose.
!     --------

! ----------------------------------------------

CLASS(MULTI_IO),    INTENT(INOUT)  :: SELF  
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('RESET_MULTI_IO',0,ZHOOK_HANDLE)

IF(ALLOCATED(SELF%NIOPROC )) DEALLOCATE(SELF%NIOPROC )
IF(ALLOCATED(SELF%ILENG   )) DEALLOCATE(SELF%ILENG   )
IF(ALLOCATED(SELF%ILENG   )) DEALLOCATE(SELF%ILENG   )
IF(ALLOCATED(SELF%ISENDCOUNTS)) DEALLOCATE(SELF%ISENDCOUNTS)
IF(ALLOCATED(SELF%IRECVCOUNTS)) DEALLOCATE(SELF%IRECVCOUNTS)
IF(ALLOCATED(SELF%ILENSR))      DEALLOCATE(SELF%ILENSR)
IF(ALLOCATED(SELF%ZBUF    )) DEALLOCATE(SELF%ZBUF    )

SELF%LSETUP=.FALSE.

IF (LHOOK) CALL DR_HOOK('RESET_MULTI_IO',1,ZHOOK_HANDLE)

END SUBROUTINE RESET_MULTI_IO

!------------------------------------------------------------------------------

END MODULE GENERIC_CTLVEC_MOD
