! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE ACCLPH ( YDPHY0,YDPHY2,KIDIA,KFDIA,KLON,KTDIA,KLEV,&
 & PTHETAV,PAPHI,PAPHIF,PU,PV,&
 & PTHETAVS,&
 & KCLPH,PCLPH,PVEIN,PUGST,PVGST)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE YOMPHY0 , ONLY : TPHY0
USE YOMPHY2 , ONLY : TPHY2
TYPE(TPHY0) ,INTENT(IN) :: YDPHY0
TYPE(TPHY2) ,INTENT(IN) :: YDPHY2
INTEGER(KIND=JPIM),INTENT(IN) :: KLON
INTEGER(KIND=JPIM),INTENT(IN) :: KLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KIDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KFDIA
INTEGER(KIND=JPIM),INTENT(IN) :: KTDIA
REAL(KIND=JPRB) ,INTENT(IN) :: PTHETAV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHI(KLON,0:KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PAPHIF(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON,KLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PTHETAVS(KLON)
INTEGER(KIND=JPIM),INTENT(OUT) :: KCLPH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PCLPH(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVEIN(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PUGST(KLON)
REAL(KIND=JPRB) ,INTENT(OUT) :: PVGST(KLON)
call abor1("acclph.F90 should never be called with OpenIFS - EXITING")
END SUBROUTINE ACCLPH
