! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE ETRANSINV_MDL(YDGEOMETRY,YDGMV,YDMDDH,YDML_GCONF,PSPVOR,PSPDIV,PSPMEANU,PSPMEANV,PSPSP,PSPHV,PSPGFL,&
 & PGMV,PGMVS,PGFL,LDERR,&
 & PSPTNDSI_VOR,PSPTNDSI_DIV,PSPTNDSI_T,&
 & PSPTNDSI_SPD,PSPTNDSI_SVD,&
 & PSPTNDHD_VOR,PSPTNDHD_DIV,PSPTNDHD_T,&
 & PSPTNDHD_SPD,PSPTNDHD_SVD,PSPTNDHD_SNHX,PSPTNDHD_GFL,&
 & PGMVTNDSI,PGMVTNDHD,PGFLTNDHD,&
 & LDSIDDH,LDHDDDH,PSPVOR_FLT,PSPDIV_FLT,PSPUB_FLT,PSPVB_FLT)
USE MODEL_GENERAL_CONF_MOD , ONLY : MODEL_GENERAL_CONF_TYPE
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV , ONLY : TGMV
use parkind1 , only:&
 & jprb
USE YOMMDDH , ONLY : TMDDH
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
TYPE(TGMV) , INTENT(INOUT) :: YDGMV
TYPE(TMDDH) ,INTENT(IN) :: YDMDDH
TYPE(MODEL_GENERAL_CONF_TYPE),INTENT(IN) :: YDML_GCONF
REAL(KIND=JPRB),INTENT(IN) :: PSPVOR(:,:)
REAL(KIND=JPRB),INTENT(IN) :: PSPDIV(:,:)
REAL(KIND=JPRB),INTENT(IN) :: PSPMEANU(:)
REAL(KIND=JPRB),INTENT(IN) :: PSPMEANV(:)
REAL(KIND=JPRB),INTENT(IN) :: PSPSP(:)
REAL(KIND=JPRB),INTENT(IN) :: PSPHV(:,:,:)
REAL(KIND=JPRB),INTENT(IN) :: PSPGFL(:,:,:)
REAL(KIND=JPRB),INTENT(OUT) :: PGMV(:,:,:,:)
REAL(KIND=JPRB),INTENT(OUT) :: PGMVS(:,:,:)
REAL(KIND=JPRB),INTENT(OUT) :: PGFL(:,:,:,:)
LOGICAL ,INTENT(IN) :: LDERR
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDSI_VOR(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDSI_DIV(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDSI_T(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDSI_SPD(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDSI_SVD(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDHD_VOR(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDHD_DIV(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDHD_T(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDHD_SPD(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDHD_SVD(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDHD_SNHX(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPTNDHD_GFL(:,:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(INOUT) :: PGMVTNDSI(:,:,:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(INOUT) :: PGMVTNDHD(:,:,:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(INOUT) :: PGFLTNDHD(:,:,:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPVOR_FLT(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPDIV_FLT(:,:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPUB_FLT(:)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PSPVB_FLT(:)
LOGICAL ,OPTIONAL ,INTENT(IN) :: LDSIDDH
LOGICAL ,OPTIONAL ,INTENT(IN) :: LDHDDDH
call abor1("etransinv_mdl.F90 should never be called with OpenIFS - EXITING")
END SUBROUTINE ETRANSINV_MDL
