! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE GNHGRPRE(&
 & YDGEOMETRY, KPDVAR,KPROMA,KFLEV,KSTART,KEND,PRTGR,PREL,PREM,PNHPREF,PSPDL,PSPDM,&
 & PNHPREFL,PNHPREFM,PLNNHPREFL,PLNNHPREFM,PQCHAL,PQCHAM)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KPDVAR
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: PRTGR(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PREL(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PREM(KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PNHPREF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPDL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSPDM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNHPREFL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PNHPREFM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLNNHPREFL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PLNNHPREFM(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQCHAL(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(OUT) :: PQCHAM(KPROMA,KFLEV)
call abor1("gnhgrpre.F90 should never be called with OpenIFS - EXITING")
END SUBROUTINE GNHGRPRE
