! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE GNHPRE(&
 & YDGEOMETRY, KPDVAR,KPROMA,KFLEV,KSTART,KEND,PSPD,PREF,&
 & PKAP,&
 & PNHPREF,PNHPPI,PRNHPPI,PDEP,PEQCHAF,PEIQCHAF)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KPDVAR
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
INTEGER(KIND=JPIM),INTENT(IN) :: KSTART
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB) ,INTENT(IN) :: PSPD(KPROMA,KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PREF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(IN) :: PKAP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PNHPREF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PNHPPI(KPROMA,KFLEV)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PRNHPPI(KPROMA,KFLEV)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PDEP(KPROMA,KFLEV)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PEQCHAF(KPROMA,KFLEV)
REAL(KIND=JPRB) ,OPTIONAL,INTENT(OUT) :: PEIQCHAF(KPROMA,KFLEV)
call abor1("gnhpre.F90 should never be called with OpenIFS - EXITING")
END SUBROUTINE GNHPRE
