! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE GNHQE_CONV_TEMPE(&
 & YDGEOMETRY,KPDVAR,LD_TT_TO_T,KDIM_GFL,KST,KEND,PQCHA,PSP, &
 & PT, &
 & KGFLTYP,PGFL,KDDER,PQCHAL,PQCHAM, &
 & PTL,PTM)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
INTEGER(KIND=JPIM),INTENT(IN) :: KPDVAR
LOGICAL ,INTENT(IN) :: LD_TT_TO_T
INTEGER(KIND=JPIM),INTENT(IN) :: KDIM_GFL
INTEGER(KIND=JPIM),INTENT(IN) :: KST
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
REAL(KIND=JPRB),INTENT(IN) :: PQCHA(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB),INTENT(IN) :: PSP(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB),INTENT(INOUT) :: PT(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KGFLTYP
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PGFL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG,KDIM_GFL)
INTEGER(KIND=JPIM),OPTIONAL,INTENT(IN) :: KDDER
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQCHAL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB),OPTIONAL,INTENT(IN) :: PQCHAM(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PTL(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB),OPTIONAL,INTENT(INOUT) :: PTM(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIMV%NFLEVG)
call abor1("gnhqe_conv_tempe.F90 should never be called with OpenIFS - EXITING")
END SUBROUTINE GNHQE_CONV_TEMPE
