! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE MTS_PHYS(YDDIMV,YDRIP,KIDIA,KFDIA,KLON,KLEV,PGEMU,PGELAM,POROG,PAPRS,PAPRSF,&
 & PLNPR,PALPH,PU,PV,PT,PQ,PQO3,PQLI,PQICE,PNEB,PTS,PITM,&
 & PUCLS,PVCLS,PTCLS,PQCLS,&
 & PTBMSAT7,PTBMSAT8,PTBMSAT9,PTBGOES11,PTBGOES12,PTBMTSAT1)
USE YOMDIMV , ONLY : TDIMV
 USE PARKIND1 ,ONLY : JPIM ,JPRB
 USE YOMRIP , ONLY : TRIP
 TYPE(TDIMV) , INTENT(IN) :: YDDIMV
 TYPE(TRIP) , INTENT(IN) :: YDRIP
 INTEGER(KIND=JPIM), INTENT(IN) :: KIDIA
 INTEGER(KIND=JPIM), INTENT(IN) :: KFDIA
 INTEGER(KIND=JPIM), INTENT(IN) :: KLON
 INTEGER(KIND=JPIM), INTENT(IN) :: KLEV
 REAL(KIND=JPRB) ,INTENT(IN) :: PGEMU(KLON)
 REAL(KIND=JPRB) ,INTENT(IN) :: PGELAM(KLON)
 REAL(KIND=JPRB) ,INTENT(IN) :: POROG(KLON)
 REAL(KIND=JPRB) ,INTENT(IN) :: PTS(KLON)
 REAL(KIND=JPRB) ,INTENT(IN) :: PITM(KLON)
 REAL(KIND=JPRB) ,INTENT(IN) :: PTCLS(KLON)
 REAL(KIND=JPRB) ,INTENT(IN) :: PQCLS(KLON)
 REAL(KIND=JPRB) ,INTENT(IN) :: PUCLS(KLON)
 REAL(KIND=JPRB) ,INTENT(IN) :: PVCLS(KLON)
 REAL(KIND=JPRB) ,INTENT(IN) :: PAPRS(KLON,0:YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(IN) :: PQO3(KLON,0:YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(IN) :: PAPRSF(KLON,YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(IN) :: PLNPR(KLON,YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(IN) :: PALPH(KLON,YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(IN) :: PU(KLON,YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(IN) :: PV(KLON,YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(IN) :: PT(KLON,YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(IN) :: PQ(KLON,YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(IN) :: PQLI(KLON,YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(IN) :: PQICE(KLON,YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(IN) :: PNEB(KLON,YDDIMV%NFLEVG)
 REAL(KIND=JPRB) ,INTENT(OUT), TARGET :: PTBMSAT7(KLON,2), PTBMSAT8(KLON,8)
 REAL(KIND=JPRB) ,INTENT(OUT), TARGET :: PTBMSAT9(KLON,8)
 REAL(KIND=JPRB) ,INTENT(OUT), TARGET :: PTBGOES11(KLON,4), PTBGOES12(KLON,4)
 REAL(KIND=JPRB) ,INTENT(OUT), TARGET :: PTBMTSAT1(KLON,4)
call abor1("mts_phys.F90 should never be called with OpenIFS - EXITING")
END SUBROUTINE MTS_PHYS
