! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE SPNHSI(&
 & YDGEOMETRY,YDLDDH,YDRIP,YDDYN,KM,KMLOC,KSTA,KEND,LDONEM,&
 & PSPVORG,PSPDIVG,PSPTG,PSPSPG,PSPSPDG,PSPSVDG,&
 & PSPTNDSI_VORG,PSPTNDSI_DIVG,PSPTNDSI_TG,PSPTNDSI_SPDG,PSPTNDSI_SVDG)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMDYN , ONLY : TDYN
USE YOMLDDH , ONLY : TLDDH
USE YOMRIP , ONLY : TRIP
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(IN) :: YDDYN
TYPE(TLDDH) ,INTENT(IN) :: YDLDDH
TYPE(TRIP) ,INTENT(IN) :: YDRIP
INTEGER(KIND=JPIM),INTENT(IN) :: KM
INTEGER(KIND=JPIM),INTENT(IN) :: KMLOC
INTEGER(KIND=JPIM),INTENT(IN) :: KSTA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
LOGICAL ,INTENT(IN) :: LDONEM
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPVORG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPDIVG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSPG(:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSPDG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPSVDG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDSI_VORG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDSI_DIVG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDSI_TG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDSI_SPDG(:,:)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PSPTNDSI_SVDG(:,:)
call abor1("spnhsi.F90 should never be called with OpenIFS - EXITING")
END SUBROUTINE SPNHSI
