! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE SUEGEM_NAML(YDGEOMETRY,PGM,PGNORX,PGNORY,PGELAM,PGELAT,KSUPERSEDE)
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE PARKIND1 , ONLY : JPIM, JPRB
TYPE(GEOMETRY), INTENT(INOUT),TARGET :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(OUT) :: PGM(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGNORX(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGNORY(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGELAM(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(OUT) :: PGELAT(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
INTEGER(KIND=JPIM), INTENT(IN), OPTIONAL :: KSUPERSEDE
call abor1("suegem_naml.F90 should never be called with OpenIFS - EXITING")
END SUBROUTINE SUEGEM_NAML
