! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE SUEGEM2(YDGEOMETRY,PGM,PGNORX,PGNORY,PGELAM,PGELAT)
USE GEOMETRY_MOD , ONLY : GEOMETRY
use parkind1 , only:&
 & jprb
TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
REAL(KIND=JPRB) ,INTENT(IN) :: PGM(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGNORX(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGNORY(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGELAM(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
REAL(KIND=JPRB) ,INTENT(INOUT) :: PGELAT(0:YDGEOMETRY%YRDIM%NDLSUR,YDGEOMETRY%YRDIM%NDGSAG:YDGEOMETRY%YRDIM%NDGENG)
call abor1("suegem2.F90 should never be called with OpenIFS - EXITING")
END SUBROUTINE SUEGEM2
