! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE SUEHOWLSM(KPROMA,KEND,KAFPB,PCR,PRGMSD,PGMSF,&
 & KLSIM,KBINL,LDML,KL0,PDLAT,PDLO,PDELY,PWXX,PWXY,&
 & PTMERGL,PTSIN,PLSMIN,PTSOUT,PLSMOUT,LDPSL)
USE PARKIND1 ,ONLY : JPIM ,JPRB
USE PARFPOS , ONLY : JPROW
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KAFPB
REAL(KIND=JPRB) ,INTENT(IN) :: PCR(2)
REAL(KIND=JPRB) ,INTENT(IN) :: PRGMSD(KEND)
REAL(KIND=JPRB) ,INTENT(IN) :: PGMSF(KEND)
INTEGER(KIND=JPIM),INTENT(IN) :: KLSIM
INTEGER(KIND=JPIM),INTENT(IN) :: KBINL
LOGICAL ,INTENT(IN) :: LDML
INTEGER(KIND=JPIM),INTENT(IN) :: KL0(KPROMA,2*JPROW)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLAT(4,KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PDLO(0:3,4,KPROMA)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELY
REAL(KIND=JPRB) ,INTENT(OUT) :: PWXX(KPROMA,KBINL)
REAL(KIND=JPRB), OPTIONAL ,INTENT(OUT) :: PWXY(KPROMA,5:16)
REAL(KIND=JPRB), OPTIONAL ,INTENT(IN) :: PTMERGL
REAL(KIND=JPRB), OPTIONAL ,INTENT(IN) :: PTSIN(KAFPB)
REAL(KIND=JPRB), OPTIONAL ,INTENT(IN) :: PLSMIN(KAFPB)
REAL(KIND=JPRB), OPTIONAL ,INTENT(IN) :: PTSOUT(KPROMA)
REAL(KIND=JPRB), OPTIONAL ,INTENT(IN) :: PLSMOUT(KPROMA)
LOGICAL, OPTIONAL ,INTENT(IN) :: LDPSL (4)
call abor1("suehowlsm.F90 should never be called with OpenIFS - EXITING")
END SUBROUTINE SUEHOWLSM
