! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE SUEHOW1(KDGSA,KDGEN,KFRSTLOFF,KPROMA,KEND,&
 & KBINL,LDML,PLAT,PLON,&
 & PDELX,PDELY,KDLON,KDGLG,&
 & KLA,KLON,KLONN,KLOS,KLOSS,PDLAT,PDLO)
USE PARKIND1 ,ONLY : JPIM ,JPRB
INTEGER(KIND=JPIM),INTENT(IN) :: KDGSA
INTEGER(KIND=JPIM),INTENT(IN) :: KDGEN
INTEGER(KIND=JPIM),INTENT(IN) :: KFRSTLOFF
INTEGER(KIND=JPIM),INTENT(IN) :: KPROMA
INTEGER(KIND=JPIM),INTENT(IN) :: KEND
INTEGER(KIND=JPIM),INTENT(IN) :: KBINL
LOGICAL ,INTENT(IN) :: LDML
REAL(KIND=JPRB) ,INTENT(IN) :: PLAT(KEND)
REAL(KIND=JPRB) ,INTENT(IN) :: PLON(KEND)
REAL(KIND=JPRB) ,INTENT(IN) :: PDELX
REAL(KIND=JPRB) ,INTENT(IN) :: PDELY
INTEGER(KIND=JPIM),INTENT(IN) :: KDLON
INTEGER(KIND=JPIM),INTENT(IN) :: KDGLG
INTEGER(KIND=JPIM),INTENT(OUT) :: KLA(KPROMA)
INTEGER(KIND=JPIM),INTENT(OUT) :: KLON(KPROMA)
INTEGER(KIND=JPIM),INTENT(OUT) :: KLONN(KPROMA)
INTEGER(KIND=JPIM),INTENT(OUT) :: KLOS(KPROMA)
INTEGER(KIND=JPIM),INTENT(OUT) :: KLOSS(KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDLAT(4,KPROMA)
REAL(KIND=JPRB) ,INTENT(OUT) :: PDLO(0:3,4,KPROMA)
call abor1("suehow1.F90 should never be called with OpenIFS - EXITING")
END SUBROUTINE SUEHOW1
