! (C) Copyright 2011- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE SUNHSI(YDGEOMETRY,YDRIP,YDDYN,YDEDYN,LDNESC,KULOUT,LDEB)
USE GEOMETRY_MOD , ONLY : GEOMETRY
use parkind1 , only:&
 & jpim
USE YOMDYN , ONLY : TDYN
USE YEMDYN , ONLY : TEDYN
USE YOMRIP , ONLY : TRIP
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT):: YDDYN
TYPE(TEDYN) ,INTENT(INOUT):: YDEDYN
TYPE(TRIP) ,INTENT(INOUT):: YDRIP
LOGICAL ,INTENT(IN) :: LDNESC
INTEGER(KIND=JPIM),INTENT(IN) :: KULOUT
LOGICAL ,INTENT(IN) :: LDEB
END SUBROUTINE SUNHSI
SUBROUTINE NH_MATRIX(YDGEOMETRY,YDDYN,LVERB,KFLEV,PKWAVE, &
 &PSITR,PSITRAM,PSIPR,MDIM,MM)
USE PARKIND1 , ONLY : JPRB, JPIM
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMDYN , ONLY : TDYN
TYPE(GEOMETRY) ,INTENT(IN) :: YDGEOMETRY
TYPE(TDYN) ,INTENT(INOUT) :: YDDYN
LOGICAL ,INTENT(IN) :: LVERB
INTEGER(KIND=JPIM),INTENT(IN) :: KFLEV
REAL(KIND=JPRB) ,INTENT(IN) :: PKWAVE
REAL(KIND=JPRB) ,INTENT(IN) :: PSITR
REAL(KIND=JPRB) ,INTENT(IN) :: PSITRAM(KFLEV)
REAL(KIND=JPRB) ,INTENT(IN) :: PSIPR
INTEGER(KIND=JPIM),INTENT(IN) :: MDIM
REAL(KIND=JPRB) ,INTENT(OUT) :: MM(MDIM,MDIM)
call abor1("sunhsi.F90 should never be called with OpenIFS - EXITING")
END
