! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!     Variable naming changed to ECMWF conventions by V. Huijnen
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


MODULE bascoe_kpp_Parameters

!  USE cifs_kpp_Precision
  USE PARKIND1  ,ONLY : JPIM  
  IMPLICIT NONE

  PUBLIC
  SAVE
 
! NSPEC - Number of chemical species
  INTEGER(KIND=JPIM), PARAMETER :: NSPEC = 66 
! NVAR - Number of Variable species
  INTEGER(KIND=JPIM), PARAMETER :: NVAR = 64 
! NVARACT - Number of Active species
  INTEGER(KIND=JPIM), PARAMETER :: NVARACT = 63 
! NFIX - Number of Fixed species
  INTEGER(KIND=JPIM), PARAMETER :: NFIX = 2 
! NREACT - Number of reactions
  INTEGER(KIND=JPIM), PARAMETER :: NREACT = 219 
! NVARST - Starting of variables in conc. vect.
  INTEGER(KIND=JPIM), PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER(KIND=JPIM), PARAMETER :: NFIXST = 65 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER(KIND=JPIM), PARAMETER :: NONZERO = 551 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER(KIND=JPIM), PARAMETER :: LU_NONZERO = 666 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER(KIND=JPIM), PARAMETER :: CNVAR = 65 
! NHESS - Length of Sparse Hessian
  INTEGER(KIND=JPIM), PARAMETER :: NHESS = 468 
! NLOOKAT - Number of species to look at
  INTEGER(KIND=JPIM), PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER(KIND=JPIM), PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER(KIND=JPIM), PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER(KIND=JPIM), PARAMETER :: ind_HF = 1 
  INTEGER(KIND=JPIM), PARAMETER :: ind_N2O = 2 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CCl4 = 3 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CFC11 = 4 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CFC12 = 5 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CFC113 = 6 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CFC114 = 7 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CFC115 = 8 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HA1301 = 9 
  INTEGER(KIND=JPIM), PARAMETER :: ind_N = 10 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HCN = 11 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3CN = 12 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HA1211 = 13 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3CCl3 = 14 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CHBr3 = 15 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH2Br2 = 16 
  INTEGER(KIND=JPIM), PARAMETER :: ind_H2SO4 = 17 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3 = 18 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CO2 = 19 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ClNO2 = 20 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HCFC22 = 21 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3O = 22 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HCO = 23 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3Cl = 24 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3Br = 25 
  INTEGER(KIND=JPIM), PARAMETER :: ind_OCS = 26 
  INTEGER(KIND=JPIM), PARAMETER :: ind_Br2 = 27 
  INTEGER(KIND=JPIM), PARAMETER :: ind_SO3 = 28 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HO2NO2 = 29 
  INTEGER(KIND=JPIM), PARAMETER :: ind_N2O5 = 30 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3OOH = 31 
  INTEGER(KIND=JPIM), PARAMETER :: ind_BrCl = 32 
  INTEGER(KIND=JPIM), PARAMETER :: ind_SO2 = 33 
  INTEGER(KIND=JPIM), PARAMETER :: ind_BrONO2 = 34 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CO = 35 
  INTEGER(KIND=JPIM), PARAMETER :: ind_H2O2 = 36 
  INTEGER(KIND=JPIM), PARAMETER :: ind_Cl2O2 = 37 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH4 = 38 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3O2 = 39 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ClOO = 40 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HNO3 = 41 
  INTEGER(KIND=JPIM), PARAMETER :: ind_H2 = 42 
  INTEGER(KIND=JPIM), PARAMETER :: ind_Cl2 = 43 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HOBr = 44 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ClONO2 = 45 
  INTEGER(KIND=JPIM), PARAMETER :: ind_OClO = 46 
  INTEGER(KIND=JPIM), PARAMETER :: ind_H = 47 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HBr = 48 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH2O = 49 
  INTEGER(KIND=JPIM), PARAMETER :: ind_H2O = 50 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HOCl = 51 
  INTEGER(KIND=JPIM), PARAMETER :: ind_NO = 52 
  INTEGER(KIND=JPIM), PARAMETER :: ind_Br = 53 
  INTEGER(KIND=JPIM), PARAMETER :: ind_Cl = 54 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HCl = 55 
  INTEGER(KIND=JPIM), PARAMETER :: ind_O = 56 
  INTEGER(KIND=JPIM), PARAMETER :: ind_NO3 = 57 
  INTEGER(KIND=JPIM), PARAMETER :: ind_OH = 58 
  INTEGER(KIND=JPIM), PARAMETER :: ind_BrO = 59 
  INTEGER(KIND=JPIM), PARAMETER :: ind_O1D = 60 
  INTEGER(KIND=JPIM), PARAMETER :: ind_NO2 = 61 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ClO = 62 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HO2 = 63 
  INTEGER(KIND=JPIM), PARAMETER :: ind_O3 = 64 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER(KIND=JPIM), PARAMETER :: ind_O2 = 65 
  INTEGER(KIND=JPIM), PARAMETER :: ind_N2 = 66 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER(KIND=JPIM), PARAMETER :: indf_O2 = 1 
  INTEGER(KIND=JPIM), PARAMETER :: indf_N2 = 2 


 

!~~~>  Statistics on the work performed by the Rosenbrock method
  INTEGER(KIND=JPIM), PARAMETER :: Nfun=1, Njac=2, Nstp=3, Nacc=4, &
                  &     Nrej=5, Ndec=6, Nsol=7, Nsng=8, &
                  &     Ntexit=1, Nhexit=2, Nhnew = 3



END MODULE bascoe_kpp_Parameters

