! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE ECPHYS_DIMENSION_TYPE_MOD

USE PARKIND1, ONLY : JPIM, JPRB
USE GEOMETRY_MOD, ONLY : GEOMETRY
USE TYPE_MODEL, ONLY : MODEL
USE SURFACE_FIELDS_MIX, ONLY : TSURF
IMPLICIT NONE

TYPE DIMENSION_TYPE
  INTEGER(KIND=JPIM) :: KIDIA,KFDIA,KBL,KLON,KSMAX,KLEVS,KTILES,KSTGLO,&
   & KLEVX,KFLDX,KFLDX2,KTDIA,KLEV,KVCLIS,KLEVI,KLEVO,KLEVSN,&
   & KDHVTLS,KDHFTLS,KDHVTSS,KDHFTSS,KDHVTTS,KDHFTTS,KDHVTIS,&
   & KDHFTIS,KDHVSSS,KDHFSSS,KDHVIIS,KDHFIIS,KDHVWLS,KDHFWLS,K2DSDT
  INTEGER(KIND=JPIM), DIMENSION(:), POINTER, CONTIGUOUS  :: KGPLAT  ! DM-global number of the latitude of point jrof=KSTART

CONTAINS
  PROCEDURE :: INIT => DIMENSION_TYPE_INIT
  PROCEDURE :: UPDATE => DIMENSION_TYPE_UPDATE
END TYPE DIMENSION_TYPE

CONTAINS

  SUBROUTINE DIMENSION_TYPE_INIT(SELF, YDGEOMETRY, YDMODEL, YDSURF)
    ! Setup global (not block-specific) dimension information
    CLASS(DIMENSION_TYPE) :: SELF
    TYPE(GEOMETRY), INTENT(IN) :: YDGEOMETRY
    TYPE(MODEL),    INTENT(IN) :: YDMODEL
    TYPE(TSURF),    INTENT(IN) :: YDSURF

    SELF%KLON   = YDGEOMETRY%YRDIM%NPROMA
    SELF%KSMAX  = YDGEOMETRY%YRDIM%NSMAX
    SELF%KIDIA  = 1
    SELF%KLEVS  = YDSURF%YSP_SBD%NLEVS
    SELF%KTILES = YDMODEL%YRML_PHY_G%YRDPHY%NTILES
    SELF%KLEVX  = YDSURF%YSD_XAD%NLEVS
    SELF%KFLDX  = YDSURF%YSD_XAD%NUMFLDS
    SELF%KFLDX2 = YDSURF%YSD_X2D%NUMFLDS
    SELF%KTDIA  = 1
    SELF%KLEV   = YDGEOMETRY%YRDIMV%NFLEVG
    SELF%KVCLIS = YDMODEL%YRML_PHY_G%YRDPHY%NVCLIS
    SELF%KLEVI  = YDMODEL%YRML_PHY_G%YRDPHY%NCSI
    SELF%KLEVO  = YDMODEL%YRML_PHY_G%YRDPHY%NCOM-1
    SELF%KLEVSN = YDMODEL%YRML_PHY_G%YRDPHY%NCSNEC
    SELF%KDHVTLS= YDMODEL%YRML_DIAG%YRMDDH%NDHVTLS
    SELF%KDHFTLS= YDMODEL%YRML_DIAG%YRMDDH%NDHFTLS
    SELF%KDHVTSS= YDMODEL%YRML_DIAG%YRMDDH%NDHVTSS
    SELF%KDHFTSS= YDMODEL%YRML_DIAG%YRMDDH%NDHFTSS
    SELF%KDHVTTS= YDMODEL%YRML_DIAG%YRMDDH%NDHVTTS
    SELF%KDHFTTS= YDMODEL%YRML_DIAG%YRMDDH%NDHFTTS
    SELF%KDHVTIS= YDMODEL%YRML_DIAG%YRMDDH%NDHVTIS
    SELF%KDHFTIS= YDMODEL%YRML_DIAG%YRMDDH%NDHFTIS
    SELF%KDHVSSS= YDMODEL%YRML_DIAG%YRMDDH%NDHVSSS
    SELF%KDHFSSS= YDMODEL%YRML_DIAG%YRMDDH%NDHFSSS
    SELF%KDHVIIS= YDMODEL%YRML_DIAG%YRMDDH%NDHVIIS
    SELF%KDHFIIS= YDMODEL%YRML_DIAG%YRMDDH%NDHFIIS
    SELF%KDHVWLS= YDMODEL%YRML_DIAG%YRMDDH%NDHVWLS
    SELF%KDHFWLS= YDMODEL%YRML_DIAG%YRMDDH%NDHFWLS
    IF (YDMODEL%YRML_GCONF%YRSPPT_CONFIG%LSPSDT) THEN
      SELF%K2DSDT = YDMODEL%YRML_SPPT%N2D
    ELSE
      SELF%K2DSDT = 0
    ENDIF
  END SUBROUTINE DIMENSION_TYPE_INIT

  SUBROUTINE DIMENSION_TYPE_UPDATE(SELF, IBL, ICEND, JKGLO, KGPLAT)
    ! Setup global (not block-specific) dimension information
    CLASS(DIMENSION_TYPE) :: SELF
    INTEGER(KIND=JPIM), INTENT(IN) :: IBL, ICEND, JKGLO
    INTEGER(KIND=JPIM), DIMENSION(:), POINTER, INTENT(IN) :: KGPLAT

    SELF%KBL    = IBL
    SELF%KFDIA  = ICEND
    SELF%KSTGLO = JKGLO
    SELF%KGPLAT => KGPLAT
  END SUBROUTINE DIMENSION_TYPE_UPDATE

END MODULE ECPHYS_DIMENSION_TYPE_MOD
