! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE EXTFPSELECT_MOD

!**** *EXTFPSELECT_MOD*  - Change Fullpos fields from NPROMA to NGPTOT layout

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE* 
!      Original : 01-10-2014
!      R. El Khatib recode LWIDER_DOM


USE PARKIND1, ONLY : JPRB, JPIM
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE YOMFPGEO, ONLY : TFPGEO
USE IOFLDDESC_MOD, ONLY : IOFLDDESC

USE IOMULTIBUF_MOD, ONLY : IOMULTIBUF,          &
                         & IOMULTIBUF_SIZE_IDX, &
                         & IOMULTIBUF_COMP_IDX

IMPLICIT NONE

INTERFACE EXTFPSELECT
  MODULE PROCEDURE EXTFPSELECTX, EXTFPSELECTY, EXTFPSELECTX1
END INTERFACE EXTFPSELECT

CONTAINS

SUBROUTINE EXTFPSELECTX1 (YDFPGEO,PGPL, PGPBUF, KFLDGIND)


TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO
REAL (KIND=JPRB),   INTENT (OUT), TARGET   :: PGPL (:)
REAL (KIND=JPRB),   INTENT (IN)            :: PGPBUF (:,:,:)
INTEGER (KIND=JPIM),INTENT (IN)            :: KFLDGIND

INTEGER (KIND=JPIM) :: JBLOC, ISTA, IEND, JFP, IOFF

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('EXTFPSELECT_MOD:EXTFPSELECTX1',0,ZHOOK_HANDLE)
ASSOCIATE(NFPBLOCS=>YDFPGEO%NFPBLOCS, NFPEND=>YDFPGEO%NFPEND, NFPROMA=>YDFPGEO%NFPROMA)

DO JBLOC = 1, NFPBLOCS
  
  ISTA = 1
  IEND = NFPEND(JBLOC)
  IOFF = (JBLOC-1)*NFPROMA

  PGPL (ISTA+IOFF:IEND+IOFF) = PGPBUF(ISTA:IEND,KFLDGIND,JBLOC)

ENDDO

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('EXTFPSELECT_MOD:EXTFPSELECTX1',1,ZHOOK_HANDLE)

END SUBROUTINE EXTFPSELECTX1

SUBROUTINE EXTFPSELECTX (YDFPGEO,LDPADDING, YDFLDSC, PGPL, PGPBUF, KFLDGOFF)

TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO
LOGICAL,            INTENT (IN)            :: LDPADDING
TYPE (IOFLDDESC),   INTENT (IN)            :: YDFLDSC(:)
REAL (KIND=JPRB),   INTENT (OUT), TARGET   :: PGPL (:,:)
REAL (KIND=JPRB),   INTENT (IN)            :: PGPBUF (:,:,:)
INTEGER (KIND=JPIM),INTENT (IN),  OPTIONAL :: KFLDGOFF

TYPE (IOMULTIBUF) :: YLFPBUFL (1)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('EXTFPSELECT_MOD:EXTFPSELECTX',0,ZHOOK_HANDLE)

YLFPBUFL (1)%P => PGPL
CALL EXTFPSELECTY (YDFPGEO,LDPADDING, YDFLDSC, YLFPBUFL, PGPBUF, KFLDGOFF)

IF (LHOOK) CALL DR_HOOK('EXTFPSELECT_MOD:EXTFPSELECTX',1,ZHOOK_HANDLE)

END SUBROUTINE EXTFPSELECTX

SUBROUTINE EXTFPSELECTY (YDFPGEO,LDPADDING, YDFLDSC, YDFPBUFL, PGPBUF, KFLDGOFF)

!**** *EXTFPSELECTY*  - 

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 11-09-2012

TYPE (TFPGEO),  INTENT(IN) :: YDFPGEO
LOGICAL,            INTENT (IN)            :: LDPADDING
TYPE (IOFLDDESC),   INTENT (IN)            :: YDFLDSC(:)
TYPE (IOMULTIBUF),  INTENT (INOUT)         :: YDFPBUFL (:)
REAL (KIND=JPRB),   INTENT (IN)            :: PGPBUF (:,:,:)
INTEGER (KIND=JPIM),INTENT (IN),  OPTIONAL :: KFLDGOFF

#include "abor1.intfb.h"

INTEGER (KIND=JPIM)              :: ISTA, IEND, JFLDG, JBLOC, INFG, JFP, IOFF
INTEGER (KIND=JPIM)              :: IFLDGOFF
INTEGER (KIND=JPIM), ALLOCATABLE :: ISPBUFY (:), JSPBUFY (:)
REAL (KIND=JPRB),    ALLOCATABLE :: ZGPBUF (:,:)            

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('EXTFPSELECT_MOD:EXTFPSELECTY',0,ZHOOK_HANDLE)
ASSOCIATE(NFPBLOCS=>YDFPGEO%NFPBLOCS, NFPEND=>YDFPGEO%NFPEND, NFPROMA=>YDFPGEO%NFPROMA,RFPMASK=>YDFPGEO%RFPMASK)

IFLDGOFF = 0
IF (PRESENT (KFLDGOFF)) IFLDGOFF = KFLDGOFF

CALL IOMULTIBUF_SIZE_IDX (YDFPBUFL, INFG)

IF ((INFG + IFLDGOFF) > UBOUND (PGPBUF, 2)) &
  & CALL ABOR1 ('EXTFPSELECT_MOD:EXTFPSELECTY: OUT OF BOUNDS REQUEST')

ALLOCATE (ISPBUFY (INFG), JSPBUFY (INFG))

CALL IOMULTIBUF_COMP_IDX (YDFPBUFL, ISPBUFY, JSPBUFY)

ALLOCATE (ZGPBUF (SIZE (PGPBUF, 1), INFG))

DO JBLOC = 1, NFPBLOCS
  
  ISTA = 1
  IEND = NFPEND(JBLOC)
  IOFF = (JBLOC-1)*NFPROMA

  ZGPBUF (ISTA:IEND, :) = PGPBUF (ISTA:IEND, IFLDGOFF+1:IFLDGOFF+INFG, JBLOC) 

  IF (LDPADDING) THEN
    DO JFLDG = 1, INFG
      ZGPBUF (ISTA:IEND, JFLDG) = YDFLDSC(JFLDG)%XUNDF * (1._JPRB - RFPMASK (ISTA:IEND, JBLOC)) + &
                                & ZGPBUF (ISTA:IEND, JFLDG) * RFPMASK (ISTA:IEND, JBLOC)
    ENDDO
  ENDIF

  DO JFLDG = 1, INFG
    YDFPBUFL (ISPBUFY (JFLDG))%P (ISTA+IOFF:IEND+IOFF, JSPBUFY (JFLDG)) = ZGPBUF (ISTA:IEND, JFLDG)
  ENDDO

ENDDO

DEALLOCATE (ISPBUFY, JSPBUFY)

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('EXTFPSELECT_MOD:EXTFPSELECTY',1,ZHOOK_HANDLE)

END SUBROUTINE EXTFPSELECTY

END MODULE EXTFPSELECT_MOD
