! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE GFL_SUBS_MOD

!     Purpose.
!     --------

!      GFL_SUBS_MOD contains routines to do basic manipulatutions of GFL descriptors 

!     Author.
!     -------
!     Mats Hamrud(ECMWF)

!     Modifications.
!     --------------
!        Original : 2003-03-01
!        Modifications:
!        03/07/09 C. Fischer - add Arome/Aladin attributes
!        M.Hamrud      01-Oct-2003 CY28 Cleaning
!        M. Tudor      31-Oct-2003 physics tendencies
!        Y.Tremolet    03-Mar-2004 Protect *EACT_CLOUD_GFL for multiple calls
!        Y.Tremolet    12-Mar-2004 Save/falsify GFLC
!        J.Haseler     10-Oct-2005 Switch for I/O to trajectory  structure
!        Y. Bouteloup  28-Jan-2005 Add YR (rain !) in DEACT_CLOUD_GFL
!        20-Feb-2005 J. Vivoda  3TL PC Eulerian scheme, GWADV scheme for PC_FULL 
!        Y. Bouteloup  25-Dec-2005 Add YS (snow !) in DEACT_CLOUD_GFL
!        A. Trojakova  29-June-2006 Add YCPF in DEACT_CLOUD_GFL
!        J. Flemming   12-April-2008 GFL attribute extention for GEMS 
!        Y. Seity 18-Dec-2007 add YG and YH (Graupel and Hail)in DEACT_CLOUD_GFL
!        Y. Bouteloup  12-Jun-2008 Add YTKE (tke !) in DEACT_CLOUD_GFL
!        O. Riviere  Feb. 2011 If LPROCLDTL switch off desactivation of QL/QI
!        A. Geer       13-Jan-2012 LDIAG atttribute for GP model diagnostics 
!        A. Inness     19-Feb-2013 Add CHEM fields with LASSIM=false
!        2011-09-07 J.M. Piriou: add Y*CONV variables for PCMT convection scheme.
!        T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!        2013-11, D. Degrauwe: INTFLEX attributes.
!        F. Vana       20-Feb-2019 New attribute for quintic vertical interpolation
!        F. Vana       11-Sep-2020 SLAVEPP and (semi) prognostic cloud
!-------------------------------------------------------------------------
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULOUT,NULERR
USE YOM_YGFL , ONLY : TYPE_GFLD,TYPE_GFL_COMP, JPGFL, JPCHEM, JPLIMA
USE YOMDIMV  , ONLY : TDIMV
USE YOMCT0   , ONLY : NUNDEFLD, L_OOPS
USE YOMMP0   , ONLY : NPRINTLEV

IMPLICIT NONE
SAVE

PRIVATE
PUBLIC DEFINE_GFL_COMP,FALSIFY_GFL_COMP,PRINT_GFL,SET_GFL_ATTR,DEACT_CLOUD_GFL,REACT_CLOUD_GFL

! For internal use
TYPE(TYPE_GFL_COMP)  :: YL_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YLCONV_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YICONV_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YRCONV_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YSCONV_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YI_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YA_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YR_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YS_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YG_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YH_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YCPF_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YLRCH4_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YCHEM_SAVE(JPCHEM) ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YTKE_SAVE ! For saving status of cloud fields
TYPE(TYPE_GFL_COMP)  :: YCVGQ_SAVE ! For saving status of cloud fields
LOGICAL :: L_CLD_DEACT=.FALSE.


TYPE(TYPE_GFL_COMP)  :: YLIMA_SAVE(JPLIMA) ! For saving status of cloud fields

#include "abor1.intfb.h"

!-------------------------------------------------------------------------
CONTAINS
!-------------------------------------------------------------------------

SUBROUTINE DEFINE_GFL_COMP(YGFL,YDCOMP,CDNAME,KGRIB,LDGP,KREQIN,PREFVALI,KFID,&
 & LDREQOUT,LDERS,LD5,LDT1,LDGPINGP,LDMGRID,LDTRAJIO,LDTHERMACT,PR,PRCP,&
 & KCOUPLO4,LDASSIM,LDDIFF,LDCONV,PMOLMASS,PEFOLD,PHENRYA,PHENRYB,&
 & KGRIBTC,KGRBFLXO,KGRBWDFLX,KGRBDDFLX,KGRIBDV,PBETAMFBC,LDMASSFIX,LDNEGFIX,LDCOMAD,LDIAG,&
 & LDWATER, LDPRECIP, PLZER, PWENO_ALPHA)  
!**** *DEFINE_GFL_COMP*  - Setup indivual GFL field
 
!     Purpose.
!     --------
!     Basic allocation of GFL descriptor structure (on first call)
!     Setup basic attributes of individual GFL component

!        Explicit arguments :
!        --------------------

!        YDCOMP  - field handle
!        CDNAME  - field ARPEGE name
!        KGRIB   - GRIB code
!        LDGP    - if TRUE gridpoint field
!        KREQIN  - 1 if required in input, 0 if not, -1 if initialised with refernence value
!        PREFVALI - reference value for initialisation in case NREQIN==-1
!        LDREQOUT- TRUE if requiered in output
!        LDERS   - TRUE if derivatives required (only possible for spectral field)
!        LD5     - TRUE if field needs to be present in trajectory (T5)
!        LD1     - TRUE if field needs to be present in t+dt array (GFLT1) 
!        LDTRAJIO- TRUE if field written to/from trajectory structure files
!        LDIAG   - TRUE if field is diagnostic at t (e.g. cloud fraction)
!         KCOUPLO4  - 1 / 2 if coupled to CTM by OASIS4 input/in&out , 0 false (obsolete)
!         LDASSIM    - TRUE if  used as Control Variable (CHEM, either monitored or assimilated)
!         KGRIBTC   - GRIB code of Total Column (CHEM)
!         KGRBFLXO  - GRIB code of Surface Flux (CHEM, output) 
!         KGRBWDFLX  - GRIB code of Wet Deposition Flux (CHEM, output) 
!         KGRBDDFLX  - GRIB code of Dry Deposition Flux (CHEM, output) 
!         KGRIBDV   - GRIB code of Deposition velocity (CHEM)
!         LDDIFF     - TRUE if diffusion  on (CHEM)
!         LDCONV     - TRUE if convection on (CHEM)
!         PMOLMASS  - Molar Mass (CHEM)
!         PEFOLD     -  Efolding decay time (CHEM)
!         PHENRYA   - Henry Constant a (CHEM)
!         PHENRYB   - Henry Constant b (CHEM)
!         LDCOMAD   - COMAD interpolation for GFL component
!         LDMASSFIX - Correct total mass after advection
!         PWENO_ALPHA - Alpha parameter (called p in literature) controlling WENO interpolation
!         PBETAMFBC - parameter for BC mass fixer
!         LDNEGFIX  - Correct negative values 
!         LDWATER   - Water species
!         LDPRECIP  - Precipitating water species
!         PLZER     - Latent heat change at 0K
!
!     Author.
!     -------
!      Mats Hamrud  *ECMWF*

!     Modifications.
!     --------------
!      Original : 2003-03-01
!      Modifications:
!      03/07/09 C. Fischer - add Arome/Aladin attributes
!      16/06/10 J Flemming, GFL attribute list extention 
!      R. El Khatib 24-May-2018 Bugfix YLASTCOMP for OOPS
!-------------------------------------------------------------------------

TYPE(TYPE_GFLD)           ,INTENT(INOUT) :: YGFL
TYPE(TYPE_GFL_COMP),TARGET,INTENT(INOUT) :: YDCOMP
CHARACTER(LEN=16),INTENT(IN) :: CDNAME
INTEGER(KIND=JPIM),INTENT(IN) :: KGRIB
INTEGER(KIND=JPIM),INTENT(IN) :: KREQIN
LOGICAL,INTENT(IN)::   LDREQOUT
LOGICAL,INTENT(IN) ::   LDGP
LOGICAL,INTENT(IN) ::   LDERS 
LOGICAL,INTENT(IN) ::   LD5 
LOGICAL,INTENT(IN) ::   LDT1
REAL(KIND=JPRB)           ,INTENT(IN),OPTIONAL :: PREFVALI
LOGICAL,INTENT(IN),OPTIONAL ::   LDGPINGP
LOGICAL,INTENT(IN),OPTIONAL ::   LDMGRID
LOGICAL,INTENT(IN),OPTIONAL ::   LDTRAJIO
LOGICAL,INTENT(IN),OPTIONAL ::   LDIAG
LOGICAL,INTENT(IN),OPTIONAL ::   LDTHERMACT
REAL(KIND=JPRB),INTENT(IN),OPTIONAL :: PR
REAL(KIND=JPRB),INTENT(IN),OPTIONAL :: PRCP
 
INTEGER(KIND=JPIM) ,INTENT(IN),OPTIONAL :: KFID        
INTEGER(KIND=JPIM) ,INTENT(IN),OPTIONAL :: KCOUPLO4        
LOGICAL ,INTENT(IN),OPTIONAL           :: LDASSIM          
INTEGER(KIND=JPIM),INTENT(IN),OPTIONAL :: KGRIBTC         
INTEGER(KIND=JPIM),INTENT(IN),OPTIONAL :: KGRBFLXO         
INTEGER(KIND=JPIM),INTENT(IN),OPTIONAL :: KGRBWDFLX         
INTEGER(KIND=JPIM),INTENT(IN),OPTIONAL :: KGRBDDFLX         
INTEGER(KIND=JPIM),INTENT(IN),OPTIONAL :: KGRIBDV         
LOGICAL  ,INTENT(IN),OPTIONAL          :: LDDIFF           
LOGICAL  ,INTENT(IN),OPTIONAL          :: LDCONV           
REAL(KIND=JPRB),INTENT(IN),OPTIONAL    :: PMOLMASS        
REAL(KIND=JPRB),INTENT(IN),OPTIONAL    :: PEFOLD        
REAL(KIND=JPRB),INTENT(IN),OPTIONAL    :: PHENRYA
REAL(KIND=JPRB),INTENT(IN),OPTIONAL    :: PHENRYB
LOGICAL, INTENT(IN),OPTIONAL           :: LDCOMAD
REAL(KIND=JPRB),INTENT(IN),OPTIONAL    :: PBETAMFBC
LOGICAL, INTENT(IN),OPTIONAL           :: LDNEGFIX
LOGICAL, INTENT(IN),OPTIONAL           :: LDMASSFIX
REAL(KIND=JPRB), INTENT(IN),OPTIONAL   :: PWENO_ALPHA
LOGICAL, INTENT(IN), OPTIONAL          :: LDWATER
LOGICAL, INTENT(IN), OPTIONAL          :: LDPRECIP
REAL(KIND=JPRB),INTENT(IN),OPTIONAL    :: PLZER

TYPE(TYPE_GFL_COMP),POINTER :: YPTRC     ! Temporary field pointer

LOGICAL :: LLP
INTEGER(KIND=JPIM) :: JGFL, ICURFLDPT, ICURFLDPC
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-------------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:DEFINE_GFL_COMP',0,ZHOOK_HANDLE)

LLP = NPRINTLEV >= 1 
!-------------------------------------------------------------------------

!      1. Define GFL component
!         --------------------

!      1.1 Some checks
IF(LDGP) THEN
  DO JGFL=1,YGFL%NUMFLDS
    IF(.NOT. YGFL%YCOMP(JGFL)%LGP) THEN
      !        Grid-point fields should be defined before any spectral field 
      CALL ABOR1('YOMMFL:DEFINE_GFL_COMP:GRIDPOINT BEFORE SPECTRAL')
    ENDIF
  ENDDO
ENDIF
IF(LDGP) THEN
!!$  IF(LDERS) THEN
!!$    !      Derivatives can only be defined for spectral fields
!!$    CALL ABOR1('YOMMFL:DEFINE_GFL_COMP:DERIVATIVES ONLY WITH SPECTRAL')
!!$  ENDIF
ENDIF
IF(YGFL%NUMFLDS == JPGFL) THEN
  WRITE(NULOUT,*) ' MAXIMUM NUMBER OF FIELDS ALREADY DEFINED'
  CALL ABOR1('YOMMFL: EXCEED NUMBER OF FIELDS')
ENDIF

!      1.2 Define field attributes

ICURFLDPT = YGFL%NUMFLDS+1
ICURFLDPC = YGFL%NUMFLDS+1

YDCOMP%LACTIVE = .TRUE.
YDCOMP%CNAME = CDNAME
YDCOMP%IGRBCODE = KGRIB
YDCOMP%NREQIN = KREQIN
IF (PRESENT(PREFVALI)) THEN
  YDCOMP%REFVALI = PREFVALI
ENDIF 
IF(PRESENT(KFID)) YDCOMP%IFID = KFID
YDCOMP%LREQOUT = LDREQOUT
YDCOMP%LGP = LDGP
YDCOMP%LSP= .NOT. YDCOMP%LGP
YDCOMP%LT5 = LD5
YDCOMP%LT1 = LDT1
YDCOMP%LCDERS  = LDERS
IF(PRESENT(LDGPINGP)) YDCOMP%LGPINGP=LDGPINGP
YDCOMP%LMGRID = .FALSE.
IF(PRESENT(LDMGRID)) YDCOMP%LMGRID=LDMGRID
IF(PRESENT(LDTRAJIO)) YDCOMP%LTRAJIO=LDTRAJIO
IF(PRESENT(LDIAG)) YDCOMP%LDIAG=LDIAG
IF(PRESENT(LDTHERMACT)) YDCOMP%LTHERMACT=LDTHERMACT
IF(YDCOMP%LTHERMACT) THEN
  IF(.NOT.PRESENT(PR))&
   &CALL ABOR1('GFL_SUBS_MOD:DEFINE_GFL_COMPONENT - PR MISSING')
  IF(.NOT.PRESENT(PRCP))&
   &CALL ABOR1('GFL_SUBS_MOD:DEFINE_GFL_COMPONENT - PRCP MISSING')
  YDCOMP%R = PR
  YDCOMP%RCP = PRCP
ENDIF


! GFL nanmel list extension  
YDCOMP%NCOUPLO4 = -1 
YDCOMP%LASSIM = .FALSE.
YDCOMP%LDIFF = .TRUE. 
YDCOMP%LCONV = .TRUE. 
YDCOMP%IGRIBTC = -9999 
YDCOMP%IGRBFLXO = -9999
YDCOMP%IGRBWDFLX = -9999
YDCOMP%IGRBDDFLX = -9999
YDCOMP%IGRIBDV = -9999
YDCOMP%RMOLMASS = -99999.9_JPRB
YDCOMP%REFOLD = -99999.9_JPRB
YDCOMP%HENRYA = -99999.9_JPRB
YDCOMP%HENRYB = -99999.9_JPRB
! end gems nl extension

YDCOMP%LCOMAD = .FALSE.
YDCOMP%LMASSFIX = .FALSE.
YDCOMP%WENO_ALPHA = 0.0_JPRB
YDCOMP%LNEGFIX = .FALSE.
YDCOMP%BETAMFBC = 1.0_JPRB

IF (PRESENT(KCOUPLO4)) YDCOMP%NCOUPLO4 = KCOUPLO4
IF (PRESENT(LDASSIM)) YDCOMP%LASSIM = LDASSIM
IF (PRESENT(LDDIFF)) YDCOMP%LDIFF = LDDIFF
IF (PRESENT(LDCONV)) YDCOMP%LCONV = LDCONV
IF (PRESENT(KGRIBTC)) YDCOMP%IGRIBTC = KGRIBTC
IF (PRESENT(KGRBFLXO)) YDCOMP%IGRBFLXO = KGRBFLXO
IF (PRESENT(KGRBWDFLX)) YDCOMP%IGRBWDFLX = KGRBWDFLX
IF (PRESENT(KGRBDDFLX)) YDCOMP%IGRBDDFLX = KGRBDDFLX
IF (PRESENT(KGRIBDV)) YDCOMP%IGRIBDV = KGRIBDV
IF (PRESENT(PMOLMASS)) YDCOMP%RMOLMASS = PMOLMASS
IF (PRESENT(PEFOLD)) YDCOMP%REFOLD = PEFOLD
IF (PRESENT(PHENRYA))  YDCOMP%HENRYA = PHENRYA
IF (PRESENT(PHENRYB))  YDCOMP%HENRYB = PHENRYB

IF (PRESENT(PBETAMFBC)) YDCOMP%BETAMFBC = PBETAMFBC
IF (PRESENT(LDMASSFIX)) YDCOMP%LMASSFIX = LDMASSFIX
IF (PRESENT(PWENO_ALPHA)) YDCOMP%WENO_ALPHA = PWENO_ALPHA
IF (PRESENT(LDCOMAD)) YDCOMP%LCOMAD = LDCOMAD
IF (PRESENT(LDNEGFIX)) YDCOMP%LNEGFIX = LDNEGFIX

IF (PRESENT(LDWATER)) YDCOMP%LWATER = LDWATER
IF (YDCOMP%LWATER) THEN
  IF (.NOT.PRESENT(LDPRECIP))&
   & CALL ABOR1('GFL_SUBS_MOD:DEFINE_GFL_COMPONENT - LDPRECIP MISSING')
  IF (.NOT.PRESENT(PLZER))&
   & CALL ABOR1('GFL_SUBS_MOD:DEFINE_GFL_COMPONENT - PLZER MISSING')
  IF (.NOT.PRESENT(PRCP))&
   & CALL ABOR1('GFL_SUBS_MOD:DEFINE_GFL_COMPONENT - PRCP MISSING')
  YDCOMP%LPRECIP = LDPRECIP
  YDCOMP%RLZER = PLZER
  YDCOMP%RCP = PRCP
ENDIF

!    1.3  Numbers of fields and dimensions
YGFL%NUMFLDS = YGFL%NUMFLDS+1
IF (YDCOMP%LT5) YGFL%NUMFLDS5 = YGFL%NUMFLDS5+1

IF(YDCOMP%LCDERS) THEN
  YGFL%NDIM = YGFL%NDIM+3
  YGFL%NDIM0 = YGFL%NDIM0+3
  YGFL%NDERS = YGFL%NDERS+1
  IF (YDCOMP%LT5) YGFL%NDIM5 = YGFL%NDIM5+3
ELSE
  YGFL%NDIM = YGFL%NDIM+1
  YGFL%NDIM0 = YGFL%NDIM0+1
  IF (YDCOMP%LT5) YGFL%NDIM5 = YGFL%NDIM5+1
ENDIF

IF(YDCOMP%LSP) THEN
  YGFL%NUMSPFLDS =YGFL%NUMSPFLDS+1
ELSE
  YGFL%NUMGPFLDS =YGFL%NUMGPFLDS+1
ENDIF

IF (YDCOMP%LT1)  THEN
  YGFL%NUMFLDS1 = YGFL%NUMFLDS1+1
  YGFL%NDIM1 = YGFL%NDIM1+1
  IF (YDCOMP%LSP) YGFL%NUMSPFLDS1 =YGFL%NUMSPFLDS1+1
ENDIF  

!    1.4  Define field "pointers"
YDCOMP%MP5 = NUNDEFLD
IF (YDCOMP%LGP) THEN
!  YDCOMP%MP = YGFL%NDIM0
  YDCOMP%MP = YGFL%NUMFLDS
  IF (YDCOMP%LT5) YDCOMP%MP5 = YGFL%NDIM5
ELSE
  YDCOMP%MP = YGFL%NUMFLDS
  IF (YDCOMP%LT5) YDCOMP%MP5 = YGFL%NUMFLDS5
ENDIF
IF (YDCOMP%LCDERS) THEN
  YDCOMP%MPM = YDCOMP%MP+YGFL%NDERS
  YDCOMP%MPL = YDCOMP%MP+2*YGFL%NDERS
  IF(YDCOMP%LT5) THEN
    YDCOMP%MP5M = YDCOMP%MP5+YGFL%NDERS
    YDCOMP%MP5L = YDCOMP%MP5+2*YGFL%NDERS
  ENDIF
ELSE
  YDCOMP%MPL = NUNDEFLD
  YDCOMP%MPM = NUNDEFLD
  YDCOMP%MP5L = NUNDEFLD
  YDCOMP%MP5M = NUNDEFLD
ENDIF

IF(YDCOMP%LSP) THEN
  YDCOMP%MPSP = YGFL%NUMSPFLDS
ELSE
  YDCOMP%MPSP = NUNDEFLD
ENDIF

IF (YDCOMP%LT1)  THEN
  YDCOMP%MP1 = YGFL%NUMFLDS1
ELSE
  YDCOMP%MP1 = NUNDEFLD
ENDIF  
  
!      1.6  Possibly reassign pointers (needed for multiple fields with derivatives)

IF(ASSOCIATED(YGFL%YLASTCOMP)) THEN
  YPTRC=>YGFL%YLASTCOMP
  DO
!    IF(.NOT.LDGP) THEN
      IF(LLP) WRITE(NULOUT,*)' DEFINE_GFL_COMP:CHECKING ',YPTRC%CNAME
      IF(YPTRC%LCDERS) THEN
        YPTRC%MPM = YPTRC%MPM+1
        IF(LDERS)THEN
          YPTRC%MPL = YPTRC%MPL+2
        ELSE
          YPTRC%MPL = YPTRC%MPL+1
        ENDIF
        IF(LLP) WRITE(NULOUT,*)' REASSIGNED MPL=',YPTRC%MPL,' MPM=',YPTRC%MPM
      ENDIF
      IF (YDCOMP%LT5) THEN
        IF(YPTRC%LT5) THEN
          IF(YPTRC%LCDERS) THEN
            YPTRC%MP5M = YPTRC%MP5M+1
            IF(LDERS)THEN
              YPTRC%MP5L = YPTRC%MP5L+2
            ELSE
              YPTRC%MP5L = YPTRC%MP5L+1
            ENDIF
          ENDIF
          IF(LLP) WRITE(NULOUT,*)' REASSIGNED MP5L=',YPTRC%MP5L,' MP5M=',YPTRC%MP5M
        ENDIF
      ENDIF

!    ENDIF
    IF(.NOT.ASSOCIATED(YPTRC%PREVIOUS)) EXIT
    YPTRC=>YPTRC%PREVIOUS
  ENDDO
ENDIF

!    1.7  Point to last defined field
YDCOMP%PREVIOUS=>YGFL%YLASTCOMP
YGFL%YLASTCOMP => YDCOMP

IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:DEFINE_GFL_COMP',1,ZHOOK_HANDLE)

!     ------------------------------------------------------------------
END SUBROUTINE DEFINE_GFL_COMP

!=========================================================================

SUBROUTINE SET_GFL_ATTR(YDDIMV,YGFL,YDCOMP,LDADV,LDMGRID,LDADV5,LDTDIABLIN,&
 & LDHORTURB,LDT9,LDPHY,LDPT,LDPC,&
 & LDADJUST0,LDADJUST1,KCOUPLING,PREFVALC,LDBIPER,CDSLINT)

!**** *SET_GFL_ATTR* Add attributes to previously setup GFL components

!     Purpose.
!     --------
!     Add further attributes to previously setup, by call to DEFINE_GFL_COMP, GFL components

!        Explicit arguments :
!        --------------------
!        LDADV   - TRUE if field to be advected
!        LDADV5  - TRUE if field to be advected by background wind only
!        LDTDIABLIN- TRUE if physics tendencies interpolated by lin. int.
!        LDHORTURB-TRUE if field is subject of 3D turbulence.
!        LDT9    - TRUE if field present in t-dt
!        LDPHY   - TRUE if field updated by physics
!        LDPT    - TRUE if field present in phy. tend.
!        LDPC    - TRUE if field in predictor/corrector time stepping treatment (3TL)
!        LDADJUST0  - TRUE if field to be adjusted at t
!        LDADJUST1  - TRUE if field to be adjusted at t+dt
!        KCOUPLING - 1 if field to be coupled, 0 if not, -1 if coupled with REFVALC
!        REVALC     - refernce value for coupling, used only in case NCOUPLING==-1
!        LDBIPER    - TRUE if field to be biperiodised
!        CDSLINT - S.L. interpolator

!     Author.
!     -------
!      Mats Hamrud  *ECMWF*

!     Modifications.
!     --------------
!      Original : 2003-03-01
!      Modifications:
!      03/07/09 C. Fischer - add Arome/Aladin attributes
!      2004-Nov F. Vana - update of CDSLINT
!      07/07/27 E. Holm - add LDADV5, i. e. advection by background in TL/AD
!      22-Feb-2011 F. Vana - LDPHYLIN, LDHORTURB attributes
!      09-Aug-2012 F. Vana - renaming LDPHYLIN to LDTDIABLIN
!      F. Vana    Oct-2018: SLPHYS cleaning
!-------------------------------------------------------------------------

USE YOM_YGFL , ONLY : TYPE_GFLD

TYPE(TDIMV)        ,INTENT(IN)           :: YDDIMV
TYPE(TYPE_GFLD)    ,INTENT(INOUT)        :: YGFL
TYPE(TYPE_GFL_COMP),INTENT(INOUT),TARGET :: YDCOMP
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDADV
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDMGRID
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDADV5
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDTDIABLIN
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDHORTURB
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDT9 
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDPHY
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDPT
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDPC
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDADJUST0
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDADJUST1
INTEGER(KIND=JPIM) ,INTENT(IN),OPTIONAL  :: KCOUPLING
REAL(KIND=JPRB)    ,INTENT(IN),OPTIONAL  :: PREFVALC
LOGICAL            ,INTENT(IN),OPTIONAL  :: LDBIPER
CHARACTER(LEN=12)  ,INTENT(IN),OPTIONAL  :: CDSLINT


INTEGER(KIND=JPIM) :: IGFLPTR
INTEGER(KIND=JPIM) :: INODEFLD=-99
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!-------------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:SET_GFL_ATTR',0,ZHOOK_HANDLE)
ASSOCIATE(NFLEVG=>YDDIMV%NFLEVG, NFLSUL=>YDDIMV%NFLSUL)

IF(YDCOMP%MP < 1 .OR. YDCOMP%MP > YGFL%NUMFLDS) THEN
  WRITE(NULERR,*)' SET_GFL_ATTR: ',YDCOMP%MP,YDCOMP%CNAME
  CALL ABOR1('SET_GFL_ATTR: GFL COMPONENT NOT SET UP')
ELSE
  IGFLPTR=YDCOMP%MP
ENDIF

IF(PRESENT(LDADV)) THEN
  YDCOMP%LADV = LDADV
ENDIF
IF(YDCOMP%LADV) THEN
  IF(.NOT.YDCOMP%LT1) THEN
    CALL ABOR1(' GFL field to be advected but LT1=false')
  ENDIF
  YGFL%NUMFLDS_SL1 = YGFL%NUMFLDS_SL1+1
  YDCOMP%MP_SL1 = YGFL%NUMFLDS_SL1
  YDCOMP%MP_SLX = (YGFL%NUMFLDS_SL1-1)*(NFLEVG+2*NFLSUL)
ENDIF
  
IF(PRESENT(LDMGRID)) THEN
  YDCOMP%LMGRID = LDMGRID
ENDIF
  
IF(PRESENT(LDADV5)) THEN
  YDCOMP%LADV5 = LDADV5
ENDIF

IF(PRESENT(LDTDIABLIN)) THEN
  YDCOMP%LTDIABLIN = LDTDIABLIN
ELSE
  YDCOMP%LTDIABLIN = .FALSE.
ENDIF

IF(PRESENT(LDHORTURB)) THEN
  YDCOMP%LHORTURB = LDHORTURB
ELSE
  YDCOMP%LHORTURB = .FALSE.
ENDIF

! Other timelevels etc.

IF(PRESENT(LDT9)) THEN
  YDCOMP%LT9 = LDT9
ENDIF
IF(YDCOMP%LT9 .AND. YDCOMP%MP9 == NUNDEFLD ) THEN
  YGFL%NUMFLDS9 = YGFL%NUMFLDS9+1
  YGFL%NDIM  = YGFL%NDIM+1
  YGFL%NDIM9 = YGFL%NDIM9+1
  YDCOMP%MP9 = YGFL%NDIM0+YGFL%NUMFLDS9
  YDCOMP%MP9_PH = YDCOMP%MP9
ELSE
  YDCOMP%MP9 = YDCOMP%MP
  YDCOMP%MP9_PH = YDCOMP%MP9
!!$  WRITE(NULOUT,*) 'WARNING YDCOMP%MP9 = YDCOMP%MP',YDCOMP%MP9,YDCOMP%MP
ENDIF

IF(PRESENT(LDPHY)) THEN
  YDCOMP%LPHY = LDPHY
ENDIF
IF(YDCOMP%MPSLP == INODEFLD) THEN ! Can't be NUNDEFLD it equals to 1 when boundchecking
  IF(YDCOMP%LPHY) THEN
    IF(.NOT.YDCOMP%LT1) THEN
      CALL ABOR1(' GFL field to be modified by physics but LT1=false')
    ENDIF
    YGFL%NUMFLDSPHY = YGFL%NUMFLDSPHY+1
    YGFL%NDIMSLP = YGFL%NDIMSLP+1
    YDCOMP%MPSLP = YGFL%NUMFLDSPHY
  ELSE
    YDCOMP%MPSLP = NUNDEFLD
  ENDIF
ENDIF

IF(PRESENT(LDPT)) THEN
  YDCOMP%LPT = LDPT
ENDIF
IF(YDCOMP%MPPT == NUNDEFLD) THEN
  IF(YDCOMP%LPT) THEN
    YGFL%NUMFLDSPT = YGFL%NUMFLDSPT+1
    YGFL%NDIMPT = YGFL%NDIMPT+1
    YDCOMP%MPPT = YGFL%NUMFLDSPT
  ENDIF
ENDIF
IF(PRESENT(LDPC)) THEN
  YDCOMP%LPC = LDPC
ENDIF
IF(YDCOMP%MPPC == NUNDEFLD) THEN
  IF(YDCOMP%LPC) THEN
    YGFL%NUMFLDSPC = YGFL%NUMFLDSPC+1
    YGFL%NDIMPC = YGFL%NDIMPC+1
    YDCOMP%MPPC = YGFL%NUMFLDSPC
  ENDIF
ENDIF


! LAM attributes (do not involve extra dimensioning or pointers)

IF(PRESENT(LDADJUST0)) THEN
  YDCOMP%LADJUST0 = LDADJUST0
ENDIF
IF(PRESENT(LDADJUST1)) THEN
  YDCOMP%LADJUST1 = LDADJUST1
ENDIF
IF(PRESENT(KCOUPLING)) THEN
  YDCOMP%NCOUPLING = KCOUPLING
ENDIF
IF(PRESENT(PREFVALC)) THEN
  YDCOMP%REFVALC = PREFVALC
ENDIF
IF(PRESENT(LDBIPER)) THEN
  YDCOMP%LBIPER = LDBIPER
ENDIF

IF(PRESENT(CDSLINT)) THEN
  YDCOMP%CSLINT=CDSLINT
  IF(YDCOMP%MP_SPL == NUNDEFLD) THEN
    IF(CDSLINT == 'LAITVSPCQM  ') THEN
      YGFL%NUMFLDS_SPL = YGFL%NUMFLDS_SPL+1
      YGFL%NDIM_SPL = YGFL%NDIM_SPL+1
      YDCOMP%MP_SPL = YGFL%NUMFLDS_SPL
    ENDIF
  ENDIF
ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:SET_GFL_ATTR',1,ZHOOK_HANDLE)

!     -------------------------------------------------------------------
END SUBROUTINE SET_GFL_ATTR

!=========================================================================

SUBROUTINE PRINT_GFL(YGFL)

!**** *PRINT_GFL*  - Print GFL attributes

!     -------------------------------------------------------------------

USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD),INTENT(INOUT):: YGFL

TYPE(TYPE_GFL_COMP),POINTER :: YPTRC     ! Temporary field pointer

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:PRINT_GFL',0,ZHOOK_HANDLE)

WRITE(NULOUT,*) ' ---- GFL COMPONENT ATTRIBUTES ----'
IF(ASSOCIATED(YGFL%YLASTCOMP)) THEN
  YPTRC=>YGFL%YLASTCOMP
  DO
    WRITE(NULOUT,*) 'GFL COMPONENT DEFINED - NAME=',&
     & YPTRC%CNAME,' GRIBCODE=', YPTRC%IGRBCODE, ' IFID=', YPTRC%IFID 
    WRITE(NULOUT,*)' LGP=',YPTRC%LGP,' NREQIN=',YPTRC%NREQIN,&
     & ' LREQOUT=',YPTRC%LREQOUT,' REFVALI=',YPTRC%REFVALI,&
     & ' LCDERS=', YPTRC%LCDERS,' LADV=',YPTRC%LADV,&
     & ' LTDIABLIN=',YPTRC%LTDIABLIN,' LHORTURB=',YPTRC%LHORTURB,&
     & ' LPHY=',YPTRC%LPHY,' LPT=',YPTRC%LPT,' LPC=',YPTRC%LPC
    WRITE(NULOUT,*)' LADJUST0=',YPTRC%LADJUST0,' LADJUST1=',YPTRC%LADJUST1,&
     & ' NCOUPLING=',YPTRC%NCOUPLING,' REFVALC=',YPTRC%REFVALC,&
     & ' LBIPER=',YPTRC%LBIPER  
    WRITE(NULOUT,*)' LTRAJIO=',YPTRC%LTRAJIO,' LDIAG=',YPTRC%LDIAG,' LGPINGP=',YPTRC%LGPINGP
    WRITE(NULOUT,*)' CSLINT=',YPTRC%CSLINT,' WENO_ALPHA=',YPTRC%WENO_ALPHA,&
     & ' LTHERMACT=',YPTRC%LTHERMACT,' R=',YPTRC%R,' RCP=',YPTRC%RCP
    WRITE(NULOUT,*)' LWATER=',YPTRC%LWATER,&
     & ' LPRECIP=',YPTRC%LPRECIP,' RLZER=',YPTRC%RLZER
    WRITE(NULOUT,*)' MP=',YPTRC%MP,' MPL=',YPTRC%MPL,&
     & ' MPM=',YPTRC%MPM,' MP9=',YPTRC%MP9,' MP1=',YPTRC%MP1,&
     & ' MP5=',YPTRC%MP5,' MP5L=',YPTRC%MP5L,' MP5M=',YPTRC%MP5M,&
     & ' MPSLP=',YPTRC%MPSLP,' MPSP=',YPTRC%MPSP,&
     & ' MPPT=',YPTRC%MPPT, ' MPPC=',YPTRC%MPPC
    IF(.NOT.ASSOCIATED(YPTRC%PREVIOUS)) EXIT
    YPTRC=>YPTRC%PREVIOUS
  ENDDO
ENDIF

WRITE(NULOUT,*) ' ---- YGFL ATTRIBUTES ----'
WRITE(NULOUT,*) ' YGFL%NUMFLDS=',YGFL%NUMFLDS,&
 & ' YGFL%NUMSPFLDS=',YGFL%NUMSPFLDS,' YGFL%NUMGPFLDS=',YGFL%NUMGPFLDS,&
 & ' YGFL%NDERS=',YGFL%NDERS,' YGFL%NUMFLDSPT=',YGFL%NUMFLDSPT,&
 & ' YGFL%NUMFLDSPC=',YGFL%NUMFLDSPC 
WRITE(NULOUT,*) ' YGFL%NUMFLDS_SL1=',YGFL%NUMFLDS_SL1 
WRITE(NULOUT,*) ' YGFL%NDIM=',YGFL%NDIM,' YGFL%NDIM0=',YGFL%NDIM0,&
 & ' YGFL%NDIM9=',YGFL%NDIM9,' YGFL%NDIM1=',YGFL%NDIM1,&
 & ' YGFL%NDIM5=',YGFL%NDIM5,' YGFL%NDIMSLP=',YGFL%NDIMSLP,&
 & ' YGFL%NDIMPT=',YGFL%NDIMPT,' YGFL%NDIMPC=',YGFL%NDIMPC
!!$WRITE(NULOUT,*) ' YGFL%CNAMES=',YGFL%CNAMES(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%IGRBCODE=',YGFL%IGRBCODE(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%NREQIN=',YGFL%NREQIN(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%REFVALI=',YGFL%REFVALI(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LREQOUT=',YGFL%LREQOUT(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LADV=',YGFL%LADV(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LTDIABLIN=',YGFL%LTDIABLIN(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LHORTURB=',YGFL%LHORTURB(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%CSLINT=',YGFL%CSLINT(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MP=',YGFL%MP(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LSP=',YGFL%LSP(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MPSP=',YGFL%MPSP(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LCDERS=',YGFL%LCDERS(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LTRAJIO=',YGFL%LTRAJIO(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MPL=',YGFL%MPL(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MPM=',YGFL%MPM(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LT9=',YGFL%LT9(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MP9=',YGFL%MP9(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LT1=',YGFL%LT1(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MP1=',YGFL%MP1(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LT5=',YGFL%LT5(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MP5=',YGFL%MP5(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MP5L=',YGFL%MP5L(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MP5M=',YGFL%MP5M(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LPHY=',YGFL%LPHY(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MPSLP=',YGFL%MPSLP(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LPT=',YGFL%LPT(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MPPT=',YGFL%MPPT(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LPC=',YGFL%LPC(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%MPPC=',YGFL%MPPC(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LADJUST0=',YGFL%LADJUST0(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LADJUST1=',YGFL%LADJUST1(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%NCOUPLING=',YGFL%NCOUPLING(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%REFVALC=',YGFL%REFVALC(1:YGFL%NUMFLDS)
!!$WRITE(NULOUT,*) ' YGFL%LBIPER=',YGFL%LBIPER(1:YGFL%NUMFLDS)
WRITE(NULOUT,*) ' --------------------------------------------'
IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:PRINT_GFL',1,ZHOOK_HANDLE)
END SUBROUTINE PRINT_GFL

!=========================================================================

SUBROUTINE DEACT_CLOUD_GFL(YDDIMV,YDCVER,YDMODEL)

!**** *DEACT_CLOUD_GFL* Deactivate prognostic cloud variables

!     ------------------------------------------------------------------

USE TYPE_MODEL , ONLY : MODEL
USE YOMCVER    , ONLY : TCVER
TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(TCVER), INTENT(IN) :: YDCVER
TYPE(MODEL) ,INTENT(INOUT):: YDMODEL


INTEGER(KIND=JPIM) :: JGFL,JCHEM,JLIMA
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "suslb.intfb.h"

IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:DEACT_CLOUD_GFL',0,ZHOOK_HANDLE)
ASSOCIATE(YGFL=>YDMODEL%YRML_GCONF%YGFL,YDSIMPHL=>YDMODEL%YRML_PHY_MF%YRSIMPHL, &
 & YDPHNC=>YDMODEL%YRML_PHY_SLIN%YRPHNC)

ASSOCIATE(NFLEVG=>YDDIMV%NFLEVG, NFLSUL=>YDDIMV%NFLSUL, &
 & YCOMP=>YGFL%YCOMP, YL=>YGFL%YL, YLCONV=>YGFL%YLCONV, YICONV=>YGFL%YICONV, &
 & YRCONV=>YGFL%YRCONV, YSCONV=>YGFL%YSCONV, YI=>YGFL%YI, YA=>YGFL%YA, &
 & YR=>YGFL%YR, YS=>YGFL%YS, YG=>YGFL%YG, YH=>YGFL%YH, YCPF=>YGFL%YCPF, &
 & YLRCH4=>YGFL%YLRCH4, YTKE=>YGFL%YTKE, YCVGQ=>YGFL%YCVGQ, &
 & YCHEM=>YGFL%YCHEM, NCHEM=>YGFL%NCHEM, LENCLD2=>YDPHNC%LENCLD2, &
 & LEPCLD2=>YDPHNC%LEPCLD2, &
 & LPROCLDTL=>YDSIMPHL%LPROCLDTL,YLIMA=>YGFL%YLIMA, NLIMA=>YGFL%NLIMA)
IF ((.NOT.L_CLD_DEACT .OR.L_OOPS) .AND.&
 & (YL%LACTIVE .OR. YI%LACTIVE .OR.YR%LACTIVE .OR. YS%LACTIVE .OR.&
 & YLCONV%LACTIVE .OR. YICONV%LACTIVE .OR. YRCONV%LACTIVE .OR. YSCONV%LACTIVE .OR.&
 &  YG%LACTIVE .OR. YH%LACTIVE .OR. YA%LACTIVE .OR. YCPF%LACTIVE .OR. YTKE%LACTIVE .OR. YCVGQ%LACTIVE) ) THEN
  IF(.NOT.L_OOPS) THEN
  IF (.NOT. (LENCLD2.OR.LEPCLD2)) CALL COPY_GFL_COMP(YGFL,YL_SAVE,YL)
  CALL COPY_GFL_COMP(YGFL,YLCONV_SAVE,YLCONV)
  CALL COPY_GFL_COMP(YGFL,YICONV_SAVE,YICONV)
  CALL COPY_GFL_COMP(YGFL,YRCONV_SAVE,YRCONV)
  CALL COPY_GFL_COMP(YGFL,YSCONV_SAVE,YSCONV)
  IF (.NOT. (LENCLD2.OR.LEPCLD2)) CALL COPY_GFL_COMP(YGFL,YI_SAVE,YI)
  CALL COPY_GFL_COMP(YGFL,YR_SAVE,YR)
  CALL COPY_GFL_COMP(YGFL,YS_SAVE,YS)
  CALL COPY_GFL_COMP(YGFL,YG_SAVE,YG)
  CALL COPY_GFL_COMP(YGFL,YH_SAVE,YH)
  IF (.NOT. (LENCLD2.OR.LEPCLD2)) CALL COPY_GFL_COMP(YGFL,YA_SAVE,YA)
  CALL COPY_GFL_COMP(YGFL,YCPF_SAVE,YCPF)
  CALL COPY_GFL_COMP(YGFL,YLRCH4_SAVE,YLRCH4)
  DO JCHEM=1,NCHEM
    IF(.NOT.YCHEM(JCHEM)%LASSIM) CALL COPY_GFL_COMP(YGFL,YCHEM_SAVE(JCHEM),YCHEM(JCHEM))
  ENDDO

  DO JLIMA=1,NLIMA
    IF(.NOT.YLIMA(JLIMA)%LASSIM) CALL COPY_GFL_COMP(YGFL,YLIMA_SAVE(JLIMA),YLIMA(JLIMA))
  ENDDO
  CALL COPY_GFL_COMP(YGFL,YTKE_SAVE,YTKE)
  CALL COPY_GFL_COMP(YGFL,YCVGQ_SAVE,YTKE)
  ENDIF
  IF( .NOT. (LENCLD2.OR.LEPCLD2)) THEN
    IF (YL%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YLCONV%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YICONV%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YRCONV%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YSCONV%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YI%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YR%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YS%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YG%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YH%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YA%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YCPF%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YLRCH4%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    DO JCHEM=1,NCHEM
      IF(YCHEM(JCHEM)%LGP.AND..NOT.YCHEM(JCHEM)%LASSIM) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    ENDDO

    DO JLIMA=1,NLIMA
      IF(YLIMA(JLIMA)%LGP.AND..NOT.YLIMA(JLIMA)%LASSIM) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    ENDDO
    IF (YTKE%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1
    IF (YCVGQ%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS-1

    IF (YL%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YLCONV%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YICONV%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YRCONV%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YSCONV%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YI%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YR%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YS%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YG%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YH%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YA%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YCPF%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YLRCH4%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    DO JCHEM=1,NCHEM
      IF (YCHEM(JCHEM)%LT5.AND..NOT.YCHEM(JCHEM)%LASSIM) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    ENDDO

    DO JLIMA=1,NLIMA
      IF (YLIMA(JLIMA)%LT5.AND..NOT.YLIMA(JLIMA)%LASSIM) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    ENDDO
    IF (YTKE%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1
    IF (YCVGQ%LT5) YGFL%NUMFLDS5=YGFL%NUMFLDS5-1

    IF (.NOT. LPROCLDTL) THEN
      CALL FALSIFY_GFL_COMP(YGFL,YL)
      CALL FALSIFY_GFL_COMP(YGFL,YI)
    ENDIF
    CALL FALSIFY_GFL_COMP(YGFL,YLCONV)
    CALL FALSIFY_GFL_COMP(YGFL,YICONV)
    CALL FALSIFY_GFL_COMP(YGFL,YRCONV)
    CALL FALSIFY_GFL_COMP(YGFL,YSCONV)
    CALL FALSIFY_GFL_COMP(YGFL,YR)
    CALL FALSIFY_GFL_COMP(YGFL,YS)
    CALL FALSIFY_GFL_COMP(YGFL,YG)
    CALL FALSIFY_GFL_COMP(YGFL,YH)
    CALL FALSIFY_GFL_COMP(YGFL,YA)
    CALL FALSIFY_GFL_COMP(YGFL,YCPF)
    CALL FALSIFY_GFL_COMP(YGFL,YLRCH4)
    DO JCHEM=1,NCHEM
      IF (.NOT.YCHEM(JCHEM)%LASSIM) CALL FALSIFY_GFL_COMP(YGFL,YCHEM(JCHEM))
    ENDDO

    DO JLIMA=1,NLIMA
      IF (.NOT.YLIMA(JLIMA)%LASSIM) CALL FALSIFY_GFL_COMP(YGFL,YLIMA(JLIMA))
    ENDDO
    CALL FALSIFY_GFL_COMP(YGFL,YTKE)
    CALL FALSIFY_GFL_COMP(YGFL,YCVGQ)
  ELSE
    !CALL NOADVECT_COMP(YGFL,YLCONV)
    !CALL NOADVECT_COMP(YGFL,YICONV)
    CALL NOADVECT_COMP(YGFL,YRCONV)
    CALL NOADVECT_COMP(YGFL,YSCONV)
    CALL NOADVECT_COMP(YGFL,YR)
    CALL NOADVECT_COMP(YGFL,YS)
    CALL NOADVECT_COMP(YGFL,YG)
    CALL NOADVECT_COMP(YGFL,YH)
    CALL NOADVECT_COMP(YGFL,YCPF)
    CALL NOADVECT_COMP(YGFL,YLRCH4)
    DO JCHEM=1,NCHEM
      IF (.NOT.YCHEM(JCHEM)%LASSIM) CALL NOADVECT_COMP(YGFL,YCHEM(JCHEM))
    ENDDO

    DO JLIMA=1,NLIMA
      IF (.NOT.YLIMA(JLIMA)%LASSIM) CALL NOADVECT_COMP(YGFL,YLIMA(JLIMA))
    ENDDO
    CALL NOADVECT_COMP(YGFL,YTKE)
    CALL NOADVECT_COMP(YGFL,YCVGQ)
  ENDIF
  YGFL%NUMFLDS_SL1 = 0
  DO JGFL=1,YGFL%NUMFLDS
    YCOMP(JGFL)%MP_SL1 = NUNDEFLD
    IF(YCOMP(JGFL)%LADV) THEN
      YGFL%NUMFLDS_SL1 = YGFL%NUMFLDS_SL1+1
      YCOMP(JGFL)%MP_SL1 = YGFL%NUMFLDS_SL1
      YCOMP(JGFL)%MP_SLX = (YCOMP(JGFL)%MP_SL1-1)*(NFLEVG+2*NFLSUL)
    ENDIF
  ENDDO
  CALL SUSLB(YDDIMV,YDCVER,YDMODEL)

  L_CLD_DEACT=.TRUE.
  WRITE(NULOUT,*)' CLOUD FIELDS DE-ACTIVATED, YGFL%NUMGPFLDS=',&
  & YGFL%NUMGPFLDS,' YGFL%NUMFLDS_SL1=', YGFL%NUMFLDS_SL1
ENDIF

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:DEACT_CLOUD_GFL',1,ZHOOK_HANDLE)

END SUBROUTINE DEACT_CLOUD_GFL

!=========================================================================

SUBROUTINE REACT_CLOUD_GFL(YDDIMV,YDCVER,YDMODEL)
!**** *REACT_CLOUD_GFL* Reactivate prognostic cloud variables

USE TYPE_MODEL , ONLY : MODEL
USE YOMCVER  , ONLY : TCVER
TYPE(TDIMV), INTENT(IN) :: YDDIMV
TYPE(TCVER), INTENT(IN) :: YDCVER
TYPE(MODEL) ,INTENT(INOUT):: YDMODEL

INTEGER(KIND=JPIM) :: JGFL,JCHEM, JLIMA
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

LOGICAL :: LLGPI,LLGPL,LLGPLCONV,LLGPICONV,LLGPRCONV,LLGPSCONV,LLGPA,LLGPLRCH4,LLGPR,LLGPS,LLGPCHEM(JPCHEM),LLGPLIMA(JPLIMA)
#include "suslb.intfb.h"
!     ------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:REACT_CLOUD_GFL',0,ZHOOK_HANDLE)
ASSOCIATE(YGFL=>YDMODEL%YRML_GCONF%YGFL,YDPHNC=>YDMODEL%YRML_PHY_SLIN%YRPHNC)

ASSOCIATE(NFLEVG=>YDDIMV%NFLEVG, NFLSUL=>YDDIMV%NFLSUL, &
 & YI=>YGFL%YI, YL=>YGFL%YL, YA=>YGFL%YA, NCHEM=>YGFL%NCHEM, &
 & YLCONV=>YGFL%YLCONV, YLRCH4=>YGFL%YLRCH4, YCOMP=>YGFL%YCOMP, & 
 & YRCONV=>YGFL%YRCONV, YCHEM=>YGFL%YCHEM, YICONV=>YGFL%YICONV, YR=>YGFL%YR, &
 & YSCONV=>YGFL%YSCONV, YS=>YGFL%YS, YLIMA=>YGFL%YLIMA, NLIMA=>YGFL%NLIMA, &
 & LENCLD2=>YDPHNC%LENCLD2,LEPCLD2=>YDPHNC%LEPCLD2)
IF(L_OOPS) CALL ABOR1('GFL_SUBS_MOD: REACT_CLOUD_GFL - SHOULD NEVER BE CALLED BY OOPS')
IF (L_CLD_DEACT) THEN
  LLGPL = YL%LGP
  LLGPLCONV = YLCONV%LGP
  LLGPICONV = YICONV%LGP
  LLGPRCONV = YRCONV%LGP
  LLGPSCONV = YSCONV%LGP
  LLGPI = YI%LGP
  LLGPA = YA%LGP
  LLGPR = YR%LGP
  LLGPS = YS%LGP
  LLGPLRCH4 = YLRCH4%LGP
  DO JCHEM=1,NCHEM
   IF(.NOT.YCHEM(JCHEM)%LASSIM) LLGPCHEM(JCHEM)=YCHEM(JCHEM)%LGP
  ENDDO

  DO JLIMA=1,NLIMA
   IF(.NOT.YLIMA(JLIMA)%LASSIM) LLGPLIMA(JLIMA)=YLIMA(JLIMA)%LGP
  ENDDO
  
  IF (.NOT.(LENCLD2.OR.LEPCLD2)) CALL COPY_GFL_COMP(YGFL,YL,YL_SAVE)
  CALL COPY_GFL_COMP(YGFL,YLCONV,YLCONV_SAVE)
  CALL COPY_GFL_COMP(YGFL,YICONV,YICONV_SAVE)
  CALL COPY_GFL_COMP(YGFL,YRCONV,YRCONV_SAVE)
  CALL COPY_GFL_COMP(YGFL,YSCONV,YSCONV_SAVE)
  IF (.NOT.(LENCLD2.OR.LEPCLD2)) CALL COPY_GFL_COMP(YGFL,YI,YI_SAVE)
  IF (.NOT.(LENCLD2.OR.LEPCLD2)) CALL COPY_GFL_COMP(YGFL,YA,YA_SAVE)
  CALL COPY_GFL_COMP(YGFL,YR,YR_SAVE)
  CALL COPY_GFL_COMP(YGFL,YS,YS_SAVE)
  CALL COPY_GFL_COMP(YGFL,YLRCH4,YLRCH4_SAVE)
  DO JCHEM=1,NCHEM
    IF(.NOT.YCHEM(JCHEM)%LASSIM) CALL COPY_GFL_COMP(YGFL,YCHEM(JCHEM),YCHEM_SAVE(JCHEM))
  ENDDO

  DO JLIMA=1,NLIMA
    IF(.NOT.YLIMA(JLIMA)%LASSIM) CALL COPY_GFL_COMP(YGFL,YLIMA(JLIMA),YLIMA_SAVE(JLIMA))
  ENDDO

  ! Following looks like a nonsense:
  ! As LLGPxx==Yxx%LGP, there is no way (.NOT. LX .AND. LX) becomes ever .true.
  IF (.NOT. LLGPL .AND. YL%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  IF (.NOT. LLGPLCONV .AND. YLCONV%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  IF (.NOT. LLGPICONV .AND. YICONV%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  IF (.NOT. LLGPRCONV .AND. YRCONV%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  IF (.NOT. LLGPSCONV .AND. YSCONV%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  IF (.NOT. LLGPI .AND. YI%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  IF (.NOT. LLGPA .AND. YA%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  IF (.NOT. LLGPR .AND. YR%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  IF (.NOT. LLGPS .AND. YS%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  IF (.NOT. LLGPLRCH4 .AND. YLRCH4%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  DO JCHEM=1,NCHEM
    IF(.NOT.YCHEM(JCHEM)%LASSIM.AND..NOT.LLGPCHEM(JCHEM).AND.YCHEM(JCHEM)%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  ENDDO

  DO JLIMA=1,NLIMA
    IF(.NOT.YLIMA(JLIMA)%LASSIM.AND..NOT.LLGPLIMA(JLIMA).AND.YLIMA(JLIMA)%LGP) YGFL%NUMGPFLDS=YGFL%NUMGPFLDS+1
  ENDDO

  YGFL%NUMFLDS_SL1 = 0
  DO JGFL=1,YGFL%NUMFLDS
    YCOMP(JGFL)%MP_SL1 = NUNDEFLD
    IF(YCOMP(JGFL)%LADV) THEN
      YGFL%NUMFLDS_SL1 = YGFL%NUMFLDS_SL1+1
      YCOMP(JGFL)%MP_SL1 = YGFL%NUMFLDS_SL1
      YCOMP(JGFL)%MP_SLX = (YCOMP(JGFL)%MP_SL1-1)*(NFLEVG+2*NFLSUL)
    ENDIF
  ENDDO
  CALL SUSLB(YDDIMV,YDCVER,YDMODEL)

  L_CLD_DEACT=.FALSE.
  WRITE(NULOUT,*)' CLOUD FIELDS RE-ACTIVATAD, YGFL%NUMGPFLDS=',&
  & YGFL%NUMGPFLDS,' YGFL%NUMFLDS_SL1=', YGFL%NUMFLDS_SL1
ENDIF

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:REACT_CLOUD_GFL',1,ZHOOK_HANDLE)

!     ------------------------------------------------------------------
END SUBROUTINE REACT_CLOUD_GFL

!=========================================================================

SUBROUTINE FALSIFY_GFL_COMP(YGFL,YDCOMP)

!     Purpose.
!     --------
!       Set field descriptors to false.

!     Author.
!     -------
!      Y. Tremolet

!     Modifications.
!     --------------
!      Original : 2004-03-12
!-------------------------------------------------------------------------

USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD)    ,INTENT(INOUT) :: YGFL
TYPE(TYPE_GFL_COMP),INTENT(INOUT) :: YDCOMP

INTEGER(KIND=JPIM) :: INODEFLD=-99
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:FALSIFY_GFL_COMP',0,ZHOOK_HANDLE)

YDCOMP%CNAME     = ''
YDCOMP%IGRBCODE  = -999
YDCOMP%LADV      = .FALSE.
YDCOMP%LADV5     = .FALSE.
YDCOMP%LTDIABLIN = .FALSE.
YDCOMP%LHORTURB  = .FALSE.
YDCOMP%NREQIN    = 0
YDCOMP%REFVALI   = 0.0_JPRB
YDCOMP%LREQOUT   = .FALSE.
YDCOMP%LGPINGP   = .TRUE.
YDCOMP%LTRAJIO   = .FALSE.
YDCOMP%LDIAG     = .FALSE.
YDCOMP%LGP       = .FALSE.
YDCOMP%LSP       = .FALSE.
YDCOMP%LCDERS    = .FALSE.
YDCOMP%LACTIVE   = .FALSE.
YDCOMP%LTHERMACT = .FALSE.
YDCOMP%LT9       = .FALSE.
YDCOMP%LT1       = .FALSE.
YDCOMP%LT5       = .FALSE.
YDCOMP%LPHY      = .FALSE.
YDCOMP%LPT       = .FALSE.
YDCOMP%LPC       = .FALSE.
YDCOMP%LADJUST0  = .FALSE.
YDCOMP%LADJUST1  = .FALSE.
YDCOMP%NCOUPLING = 0
YDCOMP%REFVALC   = 0.0_JPRB
YDCOMP%LBIPER    = .FALSE.
YDCOMP%CSLINT    = ''
YDCOMP%R         = 0.0_JPRB
YDCOMP%RCP       = 0.0_JPRB
YDCOMP%LWATER    = .FALSE.
YDCOMP%LPRECIP   = .FALSE.
YDCOMP%RLZER     = 0.0_JPRB
YDCOMP%MP        = NUNDEFLD
YDCOMP%MPL       = NUNDEFLD
YDCOMP%MPM       = NUNDEFLD
YDCOMP%MP9       = NUNDEFLD
YDCOMP%MP9_PH    = NUNDEFLD
YDCOMP%MP1       = NUNDEFLD
YDCOMP%MP5       = NUNDEFLD
YDCOMP%MP5L      = NUNDEFLD
YDCOMP%MP5M      = NUNDEFLD
YDCOMP%MPSLP     = INODEFLD
YDCOMP%MPSP      = NUNDEFLD
YDCOMP%MP_SPL    = NUNDEFLD
YDCOMP%MP_SL1    = NUNDEFLD
YDCOMP%MP_SLX    = NUNDEFLD
YDCOMP%MPPT      = NUNDEFLD
YDCOMP%MPPC      = NUNDEFLD
NULLIFY(YDCOMP%PREVIOUS)

IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:FALSIFY_GFL_COMP',1,ZHOOK_HANDLE)

END SUBROUTINE FALSIFY_GFL_COMP
!=========================================================================

SUBROUTINE NOADVECT_COMP(YGFL,YDCOMP)

!     Purpose.
!     --------
!       Switch off advection ect.

!     Author.
!     -------
!      Y. Tremolet

!     Modifications.
!     --------------
!      Original : 2004-03-12
!-------------------------------------------------------------------------

USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD)    ,INTENT(INOUT) :: YGFL
TYPE(TYPE_GFL_COMP),INTENT(INOUT) :: YDCOMP
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:NOADVECT_COMP',0,ZHOOK_HANDLE)

YDCOMP%LADV      = .FALSE.
YDCOMP%LADV5     = .FALSE.
YDCOMP%LTDIABLIN = .FALSE.
YDCOMP%LHORTURB  = .FALSE.
YDCOMP%LCDERS    = .FALSE.
YDCOMP%LT1       = .FALSE.
YDCOMP%LT5       = .FALSE.
YDCOMP%LPHY      = .FALSE.
YDCOMP%LPT       = .FALSE.
YDCOMP%LADJUST0  = .FALSE.
YDCOMP%LADJUST1  = .FALSE.
YDCOMP%LBIPER    = .FALSE.
YDCOMP%CSLINT    = ''

IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:NOADVECT_COMP',1,ZHOOK_HANDLE)

END SUBROUTINE NOADVECT_COMP

!=========================================================================

SUBROUTINE COPY_GFL_COMP(YGFL,YDCOMP1,YDCOMP2)

!     Purpose.
!     --------
!       Copy field descriptors.

!     Author.
!     -------
!      Y. Tremolet

!     Modifications.
!     --------------
!      Original : 2004-03-12
!-------------------------------------------------------------------------

USE YOM_YGFL , ONLY : TYPE_GFLD
TYPE(TYPE_GFLD)      ,INTENT(INOUT) :: YGFL
TYPE (TYPE_GFL_COMP), INTENT(INOUT) :: YDCOMP1
TYPE (TYPE_GFL_COMP), INTENT(IN)    :: YDCOMP2
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:COPY_GFL_COMP',0,ZHOOK_HANDLE)

YDCOMP1%CNAME     = YDCOMP2%CNAME
YDCOMP1%IGRBCODE  = YDCOMP2%IGRBCODE
YDCOMP1%LADV      = YDCOMP2%LADV
YDCOMP1%LADV5     = YDCOMP2%LADV5
YDCOMP1%LTDIABLIN = YDCOMP2%LTDIABLIN
YDCOMP1%LHORTURB  = YDCOMP2%LHORTURB
YDCOMP1%NREQIN    = YDCOMP2%NREQIN
YDCOMP1%REFVALI   = YDCOMP2%REFVALI
YDCOMP1%LREQOUT   = YDCOMP2%LREQOUT
YDCOMP1%LGPINGP   = YDCOMP2%LGPINGP
YDCOMP1%LTRAJIO   = YDCOMP2%LTRAJIO
YDCOMP1%LDIAG     = YDCOMP2%LDIAG
YDCOMP1%LGP       = YDCOMP2%LGP
YDCOMP1%LSP       = YDCOMP2%LSP
YDCOMP1%LPT       = YDCOMP2%LPT
YDCOMP1%LPC       = YDCOMP2%LPC
YDCOMP1%LCDERS    = YDCOMP2%LCDERS
YDCOMP1%LACTIVE   = YDCOMP2%LACTIVE
YDCOMP1%LTHERMACT = YDCOMP2%LTHERMACT
YDCOMP1%LT9       = YDCOMP2%LT9
YDCOMP1%LT1       = YDCOMP2%LT1
YDCOMP1%LT5       = YDCOMP2%LT5
YDCOMP1%LPHY      = YDCOMP2%LPHY
YDCOMP1%LADJUST0  = YDCOMP2%LADJUST0
YDCOMP1%LADJUST1  = YDCOMP2%LADJUST1
YDCOMP1%NCOUPLING = YDCOMP2%NCOUPLING
YDCOMP1%REFVALC   = YDCOMP2%REFVALC
YDCOMP1%LBIPER    = YDCOMP2%LBIPER
YDCOMP1%CSLINT    = YDCOMP2%CSLINT
YDCOMP1%R         = YDCOMP2%R
YDCOMP1%RCP       = YDCOMP2%RCP
YDCOMP1%LWATER    = YDCOMP2%LWATER
YDCOMP1%LPRECIP   = YDCOMP2%LPRECIP
YDCOMP1%RLZER     = YDCOMP2%RLZER
YDCOMP1%MP        = YDCOMP2%MP
YDCOMP1%MPL       = YDCOMP2%MPL
YDCOMP1%MPM       = YDCOMP2%MPM
YDCOMP1%MP9       = YDCOMP2%MP9
YDCOMP1%MP1       = YDCOMP2%MP1
YDCOMP1%MP5       = YDCOMP2%MP5
YDCOMP1%MP5L      = YDCOMP2%MP5L
YDCOMP1%MP5M      = YDCOMP2%MP5M
YDCOMP1%MPSLP     = YDCOMP2%MPSLP
YDCOMP1%MP_SPL    = YDCOMP2%MP_SPL
YDCOMP1%MP_SL1    = YDCOMP2%MP_SL1
YDCOMP1%MPSP      = YDCOMP2%MPSP
YDCOMP1%MPPT      = YDCOMP2%MPPT
YDCOMP1%MPPC      = YDCOMP2%MPPC
!yt YDCOMP1%PREVIOUS => YDCOMP2%PREVIOUS

IF (LHOOK) CALL DR_HOOK('GFL_SUBS_MOD:COPY_GFL_COMP',1,ZHOOK_HANDLE)

END SUBROUTINE COPY_GFL_COMP

!=========================================================================

END MODULE GFL_SUBS_MOD
