! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

module ifs_dbase_view_mod

   ! DO NOT EDIT THIS FILE MANUALLY
   ! THIS SHOULD BE AUTOMATICALLY GENERATED BY THE PYTHON SCRIPT:
   !   odb/scripts/generate_ifs_dbase_view_mod.py
   !
   ! e.g. on your workstation in your branch directory:
   !    cd odb/scripts
   !    python3 generate_ifs_dbase_view_mod.py
   use ifsobs_schema_mod


    type, abstract                          :: abstract_dbase_view
        real(kind=jprl), allocatable        :: data(:,:)                    !! Data cast as floating point values [rows,columns]
    end type


   type,extends(abstract_dbase_view)        :: ifs_dbase_view
        type(aeolus_hdr_table) :: aeolus_hdr
        type(aeolus_auxmet_table) :: aeolus_auxmet
        type(aeolus_l2c_table) :: aeolus_l2c
        type(aeolus_l2b_table) :: aeolus_l2b
        type(allsky_table) :: allsky
        type(allsky_body_table) :: allsky_body
        type(auxiliary_table) :: auxiliary
        type(auxiliary_body_table) :: auxiliary_body
        type(body_table) :: body
        type(claerlid_table) :: claerlid
        type(claerlid_body_table) :: claerlid_body
        type(cloud_sink_table) :: cloud_sink
        type(clrad_table) :: clrad
        type(clrad_body_table) :: clrad_body
        type(desc_table) :: desc
        type(poolmask_table) :: poolmask
        type(timeslot_index_table) :: timeslot_index
        type(index_table) :: index
        type(collocated_imager_information_table) :: collocated_imager_information
        type(conv_table) :: conv
        type(conv_body_table) :: conv_body
        type(ensemble_table) :: ensemble
        type(errstat_table) :: errstat
        type(fcdiagnostic_table) :: fcdiagnostic
        type(gbrad_table) :: gbrad
        type(gbrad_body_table) :: gbrad_body
        type(gnssro_table) :: gnssro
        type(gnssro_body_table) :: gnssro_body
        type(hdr_table) :: hdr
        type(limb_table) :: limb
        type(modsurf_table) :: modsurf
        type(radar_table) :: radar
        type(radar_body_table) :: radar_body
        type(radar_station_table) :: radar_station
        type(radiance_table) :: radiance
        type(radiance_body_table) :: radiance_body
        type(raingg_table) :: raingg
        type(raingg_body_table) :: raingg_body
        type(resat_table) :: resat
        type(resat_averaging_kernel_table) :: resat_averaging_kernel
        type(sat_table) :: sat
        type(satob_table) :: satob
        type(scatt_table) :: scatt
        type(scatt_body_table) :: scatt_body
        type(smos_table) :: smos
        type(ssmi_table) :: ssmi
        type(ssmi_body_table) :: ssmi_body
        type(superob_table) :: superob
        type(surfbody_feedback_table) :: surfbody_feedback
   contains
        procedure, public                   :: setup_col_pointers
   end type ifs_dbase_view

contains


    subroutine setup_col_pointers(this)

        class(ifs_dbase_view), target,intent(inout) :: this
        call abor1("Call to ifs_dbase_view%setup_col_pointers.")
    end subroutine setup_col_pointers
end module ifs_dbase_view_mod
