! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

! PLEASE DO NOT EDIT THIS FILE; IT SHOULD BE AUTOMTATICALLY GENERATED USING odb/scripts/generate_ifs_dbase_view_mod.py
module ifsobs_schema_mod





implicit none

integer, parameter :: jprl = selected_real_kind(13,300)


type aeolus_hdr_table
   real(kind=jprl), pointer :: aeolus_hdrflag(:) => null()
   real(kind=jprl), pointer :: aeolus_auxmet(:) => null()
   real(kind=jprl), pointer :: aeolus_l2c(:) => null()
   real(kind=jprl), pointer :: aeolus_l2b(:) => null()
end type aeolus_hdr_table

type aeolus_auxmet_table
   real(kind=jprl), pointer :: lev(:) => null()
   real(kind=jprl), pointer :: ptop(:) => null()
   real(kind=jprl), pointer :: pnom(:) => null()
   real(kind=jprl), pointer :: ztop(:) => null()
   real(kind=jprl), pointer :: znom(:) => null()
   real(kind=jprl), pointer :: u(:) => null()
   real(kind=jprl), pointer :: v(:) => null()
   real(kind=jprl), pointer :: t(:) => null()
   real(kind=jprl), pointer :: rh(:) => null()
   real(kind=jprl), pointer :: q(:) => null()
   real(kind=jprl), pointer :: cc(:) => null()
   real(kind=jprl), pointer :: clwc(:) => null()
   real(kind=jprl), pointer :: ciwc(:) => null()
   real(kind=jprl), pointer :: error_t(:) => null()
   real(kind=jprl), pointer :: error_rh(:) => null()
   real(kind=jprl), pointer :: error_p(:) => null()
end type aeolus_auxmet_table

type aeolus_l2c_table
   real(kind=jprl), pointer :: hlos_ob_err(:) => null()
   real(kind=jprl), pointer :: hlos_fg(:) => null()
   real(kind=jprl), pointer :: u_fg(:) => null()
   real(kind=jprl), pointer :: u_fg_err(:) => null()
   real(kind=jprl), pointer :: v_fg(:) => null()
   real(kind=jprl), pointer :: v_fg_err(:) => null()
   real(kind=jprl), pointer :: hlos_fg_err(:) => null()
   real(kind=jprl), pointer :: hlos_an(:) => null()
   real(kind=jprl), pointer :: hlos_an_err(:) => null()
   real(kind=jprl), pointer :: u_an(:) => null()
   real(kind=jprl), pointer :: v_an(:) => null()
end type aeolus_l2c_table

type aeolus_l2b_table
   real(kind=jprl), pointer :: t_ref(:) => null()
   real(kind=jprl), pointer :: p_ref(:) => null()
   real(kind=jprl), pointer :: beta(:) => null()
   real(kind=jprl), pointer :: dhlos_dt(:) => null()
   real(kind=jprl), pointer :: dhlos_dp(:) => null()
   real(kind=jprl), pointer :: dhlos_dbeta(:) => null()
   real(kind=jprl), pointer :: horiz_length(:) => null()
   real(kind=jprl), pointer :: vert_length(:) => null()
   real(kind=jprl), pointer :: conf_flag(:) => null()
end type aeolus_l2b_table

type allsky_table
   real(kind=jprl), pointer :: fg_rain_rate(:) => null()
   real(kind=jprl), pointer :: fg_snow_rate(:) => null()
   real(kind=jprl), pointer :: fg_tcwv(:) => null()
   real(kind=jprl), pointer :: fg_cwp(:) => null()
   real(kind=jprl), pointer :: fg_iwp(:) => null()
   real(kind=jprl), pointer :: fg_rwp(:) => null()
   real(kind=jprl), pointer :: fg_swp(:) => null()
   real(kind=jprl), pointer :: fg_rttov_cld_fraction(:) => null()
   real(kind=jprl), pointer :: fg_theta700(:) => null()
   real(kind=jprl), pointer :: fg_thetasfc(:) => null()
   real(kind=jprl), pointer :: fg_uth(:) => null()
   real(kind=jprl), pointer :: fg_conv(:) => null()
   real(kind=jprl), pointer :: fg_pbl(:) => null()
   real(kind=jprl), pointer :: an_rain_rate(:) => null()
   real(kind=jprl), pointer :: an_snow_rate(:) => null()
   real(kind=jprl), pointer :: an_tcwv(:) => null()
   real(kind=jprl), pointer :: an_cwp(:) => null()
   real(kind=jprl), pointer :: an_iwp(:) => null()
   real(kind=jprl), pointer :: an_rwp(:) => null()
   real(kind=jprl), pointer :: an_swp(:) => null()
   real(kind=jprl), pointer :: an_rttov_cld_fraction(:) => null()
   real(kind=jprl), pointer :: an_theta700(:) => null()
   real(kind=jprl), pointer :: an_thetasfc(:) => null()
   real(kind=jprl), pointer :: an_uth(:) => null()
   real(kind=jprl), pointer :: an_conv(:) => null()
   real(kind=jprl), pointer :: an_pbl(:) => null()
   real(kind=jprl), pointer :: gnorm_10mwind(:) => null()
   real(kind=jprl), pointer :: gnorm_skintemp(:) => null()
   real(kind=jprl), pointer :: gnorm_temp(:) => null()
   real(kind=jprl), pointer :: gnorm_q(:) => null()
   real(kind=jprl), pointer :: gnorm_rainflux(:) => null()
   real(kind=jprl), pointer :: gnorm_snowflux(:) => null()
   real(kind=jprl), pointer :: gnorm_clw(:) => null()
   real(kind=jprl), pointer :: gnorm_ciw(:) => null()
   real(kind=jprl), pointer :: gnorm_cc(:) => null()
   real(kind=jprl), pointer :: seaice_estimate(:) => null()
   real(kind=jprl), pointer :: report_tbcloud(:) => null()
   real(kind=jprl), pointer :: allsky_body(:) => null()
end type allsky_table

type allsky_body_table
   real(kind=jprl), pointer :: tbvalue(:) => null()
   real(kind=jprl), pointer :: tbvaluetl(:) => null()
   real(kind=jprl), pointer :: tbvaluead(:) => null()
   real(kind=jprl), pointer :: datum_tbflag(:) => null()
   real(kind=jprl), pointer :: ob_cloudprox(:) => null()
   real(kind=jprl), pointer :: fg_cloudprox(:) => null()
   real(kind=jprl), pointer :: an_cloudprox(:) => null()
   real(kind=jprl), pointer :: cloudprox_type(:) => null()
end type allsky_body_table

type auxiliary_table
   real(kind=jprl), pointer :: auxiliary_body(:) => null()
end type auxiliary_table

type auxiliary_body_table
end type auxiliary_body_table

type body_table
   real(kind=jprl), pointer :: entryno(:) => null()
   real(kind=jprl), pointer :: obsvalue(:) => null()
   real(kind=jprl), pointer :: varno(:) => null()
   real(kind=jprl), pointer :: vertco_type(:) => null()
   real(kind=jprl), pointer :: vertco_reference_1(:) => null()
   real(kind=jprl), pointer :: vertco_reference_2(:) => null()
   real(kind=jprl), pointer :: datum_anflag(:) => null()
   real(kind=jprl), pointer :: datum_status(:) => null()
   real(kind=jprl), pointer :: datum_event1(:) => null()
   real(kind=jprl), pointer :: datum_rdbflag(:) => null()
   real(kind=jprl), pointer :: datum_blacklist(:) => null()
   real(kind=jprl), pointer :: datum_event2(:) => null()
   real(kind=jprl), pointer :: varbc_ix(:) => null()
   real(kind=jprl), pointer :: biascorr(:) => null()
   real(kind=jprl), pointer :: biascorr_fg(:) => null()
   real(kind=jprl), pointer :: tbcorr(:) => null()
   real(kind=jprl), pointer :: bias_volatility(:) => null()
   real(kind=jprl), pointer :: wdeff_bcorr(:) => null()
   real(kind=jprl), pointer :: an_depar(:) => null()
   real(kind=jprl), pointer :: fg_depar(:) => null()
   real(kind=jprl), pointer :: actual_depar(:) => null()
   real(kind=jprl), pointer :: actual_ndbiascorr(:) => null()
   real(kind=jprl), pointer :: qc_a(:) => null()
   real(kind=jprl), pointer :: qc_l(:) => null()
   real(kind=jprl), pointer :: qc_pge(:) => null()
   real(kind=jprl), pointer :: fc_sens_obs(:) => null()
   real(kind=jprl), pointer :: an_sens_obs(:) => null()
   real(kind=jprl), pointer :: jacobian_peak(:) => null()
   real(kind=jprl), pointer :: jacobian_peakl(:) => null()
   real(kind=jprl), pointer :: jacobian_hpeak(:) => null()
   real(kind=jprl), pointer :: jacobian_hpeakl(:) => null()
   real(kind=jprl), pointer :: mf_vertco_type(:) => null()
   real(kind=jprl), pointer :: mf_log_p(:) => null()
   real(kind=jprl), pointer :: mf_stddev(:) => null()
   real(kind=jprl), pointer :: nlayer(:) => null()
end type body_table

type claerlid_table
   real(kind=jprl), pointer :: report_clbscflag(:) => null()
   real(kind=jprl), pointer :: claerlid_body(:) => null()
end type claerlid_table

type claerlid_body_table
   real(kind=jprl), pointer :: clbscvalue(:) => null()
   real(kind=jprl), pointer :: clbscvaluetl(:) => null()
   real(kind=jprl), pointer :: clbscvaluead(:) => null()
   real(kind=jprl), pointer :: clbscvaluefg(:) => null()
   real(kind=jprl), pointer :: datum_clbsc_stflag(:) => null()
   real(kind=jprl), pointer :: fg_presf(:) => null()
   real(kind=jprl), pointer :: fg_z(:) => null()
   real(kind=jprl), pointer :: fg_temp(:) => null()
   real(kind=jprl), pointer :: fg_spech(:) => null()
   real(kind=jprl), pointer :: fg_cwc(:) => null()
   real(kind=jprl), pointer :: fg_iwc(:) => null()
   real(kind=jprl), pointer :: fg_cc(:) => null()
   real(kind=jprl), pointer :: fg_rwc(:) => null()
   real(kind=jprl), pointer :: fg_swc(:) => null()
   real(kind=jprl), pointer :: fg_pfra(:) => null()
   real(kind=jprl), pointer :: fg_crwc(:) => null()
   real(kind=jprl), pointer :: fg_cswc(:) => null()
   real(kind=jprl), pointer :: an_presf(:) => null()
   real(kind=jprl), pointer :: an_temp(:) => null()
   real(kind=jprl), pointer :: an_spech(:) => null()
   real(kind=jprl), pointer :: an_cwc(:) => null()
   real(kind=jprl), pointer :: an_iwc(:) => null()
   real(kind=jprl), pointer :: an_cc(:) => null()
   real(kind=jprl), pointer :: an_rwc(:) => null()
   real(kind=jprl), pointer :: an_swc(:) => null()
   real(kind=jprl), pointer :: an_pfra(:) => null()
   real(kind=jprl), pointer :: an_crwc(:) => null()
   real(kind=jprl), pointer :: an_cswc(:) => null()
end type claerlid_body_table

type cloud_sink_table
   real(kind=jprl), pointer :: ctopbg(:) => null()
   real(kind=jprl), pointer :: ctoper(:) => null()
   real(kind=jprl), pointer :: ctopinc(:) => null()
   real(kind=jprl), pointer :: camtbg(:) => null()
   real(kind=jprl), pointer :: camter(:) => null()
   real(kind=jprl), pointer :: camtinc(:) => null()
end type cloud_sink_table

type clrad_table
   real(kind=jprl), pointer :: report_clreflflag(:) => null()
   real(kind=jprl), pointer :: clrad_body(:) => null()
end type clrad_table

type clrad_body_table
   real(kind=jprl), pointer :: clreflvalue(:) => null()
   real(kind=jprl), pointer :: clreflvaluetl(:) => null()
   real(kind=jprl), pointer :: clreflvaluead(:) => null()
   real(kind=jprl), pointer :: clreflvaluefg(:) => null()
   real(kind=jprl), pointer :: datum_clrefl_stflag(:) => null()
   real(kind=jprl), pointer :: fg_presf(:) => null()
   real(kind=jprl), pointer :: fg_z(:) => null()
   real(kind=jprl), pointer :: fg_temp(:) => null()
   real(kind=jprl), pointer :: fg_spech(:) => null()
   real(kind=jprl), pointer :: fg_cwc(:) => null()
   real(kind=jprl), pointer :: fg_iwc(:) => null()
   real(kind=jprl), pointer :: fg_cc(:) => null()
   real(kind=jprl), pointer :: fg_rwc(:) => null()
   real(kind=jprl), pointer :: fg_swc(:) => null()
   real(kind=jprl), pointer :: fg_pfra(:) => null()
   real(kind=jprl), pointer :: fg_crwc(:) => null()
   real(kind=jprl), pointer :: fg_cswc(:) => null()
   real(kind=jprl), pointer :: an_presf(:) => null()
   real(kind=jprl), pointer :: an_temp(:) => null()
   real(kind=jprl), pointer :: an_spech(:) => null()
   real(kind=jprl), pointer :: an_cwc(:) => null()
   real(kind=jprl), pointer :: an_iwc(:) => null()
   real(kind=jprl), pointer :: an_cc(:) => null()
   real(kind=jprl), pointer :: an_rwc(:) => null()
   real(kind=jprl), pointer :: an_swc(:) => null()
   real(kind=jprl), pointer :: an_pfra(:) => null()
   real(kind=jprl), pointer :: an_crwc(:) => null()
   real(kind=jprl), pointer :: an_cswc(:) => null()
end type clrad_body_table

type desc_table
   real(kind=jprl), pointer :: expver(:) => null()
   real(kind=jprl), pointer :: class(:) => null()
   real(kind=jprl), pointer :: stream(:) => null()
   real(kind=jprl), pointer :: type(:) => null()
   real(kind=jprl), pointer :: andate(:) => null()
   real(kind=jprl), pointer :: antime(:) => null()
   real(kind=jprl), pointer :: inidate(:) => null()
   real(kind=jprl), pointer :: initime(:) => null()
   real(kind=jprl), pointer :: creadate(:) => null()
   real(kind=jprl), pointer :: creatime(:) => null()
   real(kind=jprl), pointer :: creaby(:) => null()
   real(kind=jprl), pointer :: moddate(:) => null()
   real(kind=jprl), pointer :: modtime(:) => null()
   real(kind=jprl), pointer :: modby(:) => null()
   real(kind=jprl), pointer :: mxup_traj(:) => null()
   real(kind=jprl), pointer :: numtsl(:) => null()
   real(kind=jprl), pointer :: poolmask(:) => null()
   real(kind=jprl), pointer :: timeslot_index(:) => null()
   real(kind=jprl), pointer :: fcdiagnostic(:) => null()
   real(kind=jprl), pointer :: latlon_rad(:) => null()
   real(kind=jprl), pointer :: enda_member(:) => null()
end type desc_table

type poolmask_table
   real(kind=jprl), pointer :: timeslot(:) => null()
   real(kind=jprl), pointer :: obstype(:) => null()
   real(kind=jprl), pointer :: codetype(:) => null()
   real(kind=jprl), pointer :: sensor(:) => null()
   real(kind=jprl), pointer :: bufrtype(:) => null()
   real(kind=jprl), pointer :: subtype(:) => null()
   real(kind=jprl), pointer :: poolno(:) => null()
   real(kind=jprl), pointer :: hdr_count(:) => null()
   real(kind=jprl), pointer :: body_count(:) => null()
   real(kind=jprl), pointer :: max_bodylen(:) => null()
end type poolmask_table

type timeslot_index_table
   real(kind=jprl), pointer :: timeslot(:) => null()
   real(kind=jprl), pointer :: model_timestep(:) => null()
   real(kind=jprl), pointer :: enddate(:) => null()
   real(kind=jprl), pointer :: endtime(:) => null()
   real(kind=jprl), pointer :: index(:) => null()
end type timeslot_index_table

type index_table
   real(kind=jprl), pointer :: target(:) => null()
   real(kind=jprl), pointer :: procid(:) => null()
   real(kind=jprl), pointer :: timeslot(:) => null()
   real(kind=jprl), pointer :: kset(:) => null()
   real(kind=jprl), pointer :: abnob(:) => null()
   real(kind=jprl), pointer :: mapomm(:) => null()
   real(kind=jprl), pointer :: maptovscv(:) => null()
   real(kind=jprl), pointer :: hdr(:) => null()
end type index_table

type collocated_imager_information_table
   real(kind=jprl), pointer :: avhrr_mean_ir(:) => null()
   real(kind=jprl), pointer :: avhrr_stddev_ir(:) => null()
   real(kind=jprl), pointer :: avhrr_stddev_ir2(:) => null()
   real(kind=jprl), pointer :: avhrr_num_clusters(:) => null()
   real(kind=jprl), pointer :: avhrr_mean_vis(:) => null()
   real(kind=jprl), pointer :: avhrr_stddev_vis(:) => null()
   real(kind=jprl), pointer :: avhrr_max_cluster(:) => null()
   real(kind=jprl), pointer :: avhrr_coldest_cluster_ir(:) => null()
   real(kind=jprl), pointer :: avhrr_warmest_cluster_ir(:) => null()
   real(kind=jprl), pointer :: avhrr_largest_cluster_ir(:) => null()
   real(kind=jprl), pointer :: provider_qc(:) => null()
   real(kind=jprl), pointer :: avhrr_frac_cl1(:) => null()
   real(kind=jprl), pointer :: avhrr_frac_cl2(:) => null()
   real(kind=jprl), pointer :: avhrr_frac_cl3(:) => null()
   real(kind=jprl), pointer :: avhrr_frac_cl4(:) => null()
   real(kind=jprl), pointer :: avhrr_frac_cl5(:) => null()
   real(kind=jprl), pointer :: avhrr_frac_cl6(:) => null()
   real(kind=jprl), pointer :: avhrr_frac_cl7(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir1_cl1(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir1_cl2(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir1_cl3(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir1_cl4(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir1_cl5(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir1_cl6(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir1_cl7(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir2_cl1(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir2_cl2(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir2_cl3(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir2_cl4(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir2_cl5(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir2_cl6(:) => null()
   real(kind=jprl), pointer :: avhrr_m_ir2_cl7(:) => null()
   real(kind=jprl), pointer :: avhrr_fg_ir1(:) => null()
   real(kind=jprl), pointer :: avhrr_fg_ir2(:) => null()
   real(kind=jprl), pointer :: avhrr_cloud_flag(:) => null()
end type collocated_imager_information_table

type conv_table
   real(kind=jprl), pointer :: flight_phase(:) => null()
   real(kind=jprl), pointer :: flight_dp_o_dt(:) => null()
   real(kind=jprl), pointer :: anemoht(:) => null()
   real(kind=jprl), pointer :: baroht(:) => null()
   real(kind=jprl), pointer :: station_type(:) => null()
   real(kind=jprl), pointer :: sonde_type(:) => null()
   real(kind=jprl), pointer :: collection_identifier(:) => null()
   real(kind=jprl), pointer :: country(:) => null()
   real(kind=jprl), pointer :: unique_identifier(:) => null()
   real(kind=jprl), pointer :: timeseries_index(:) => null()
   real(kind=jprl), pointer :: heading(:) => null()
   real(kind=jprl), pointer :: aircraft_type(:) => null()
   real(kind=jprl), pointer :: conv_body(:) => null()
end type conv_table

type conv_body_table
   real(kind=jprl), pointer :: ppcode(:) => null()
   real(kind=jprl), pointer :: level(:) => null()
   real(kind=jprl), pointer :: datum_qcflag(:) => null()
end type conv_body_table

type ensemble_table
   real(kind=jprl), pointer :: nensemble(:) => null()
end type ensemble_table

type errstat_table
   real(kind=jprl), pointer :: final_obs_error(:) => null()
   real(kind=jprl), pointer :: obs_error(:) => null()
   real(kind=jprl), pointer :: repres_error(:) => null()
   real(kind=jprl), pointer :: pers_error(:) => null()
   real(kind=jprl), pointer :: fg_error(:) => null()
   real(kind=jprl), pointer :: eda_spread(:) => null()
   real(kind=jprl), pointer :: obs_ak_error(:) => null()
   real(kind=jprl), pointer :: obs_corr_mask(:) => null()
end type errstat_table

type fcdiagnostic_table
   real(kind=jprl), pointer :: max_fcdiag(:) => null()
end type fcdiagnostic_table

type gbrad_table
   real(kind=jprl), pointer :: report_rrflag(:) => null()
   real(kind=jprl), pointer :: gbrad_body(:) => null()
end type gbrad_table

type gbrad_body_table
   real(kind=jprl), pointer :: rrvalue(:) => null()
   real(kind=jprl), pointer :: rrvaluetl(:) => null()
   real(kind=jprl), pointer :: rrvaluead(:) => null()
end type gbrad_body_table

type gnssro_table
   real(kind=jprl), pointer :: gnss_type(:) => null()
   real(kind=jprl), pointer :: radcurv(:) => null()
   real(kind=jprl), pointer :: undulation(:) => null()
   real(kind=jprl), pointer :: gnssro_body(:) => null()
end type gnssro_table

type gnssro_body_table
   real(kind=jprl), pointer :: obs_dndz(:) => null()
   real(kind=jprl), pointer :: obs_refractivity(:) => null()
   real(kind=jprl), pointer :: bg_dndz(:) => null()
   real(kind=jprl), pointer :: bg_refractivity(:) => null()
   real(kind=jprl), pointer :: bg_layerno(:) => null()
   real(kind=jprl), pointer :: obs_tvalue(:) => null()
   real(kind=jprl), pointer :: obs_zvalue(:) => null()
   real(kind=jprl), pointer :: bg_tvalue(:) => null()
end type gnssro_body_table

type hdr_table
   real(kind=jprl), pointer :: seqno(:) => null()
   real(kind=jprl), pointer :: subseqno(:) => null()
   real(kind=jprl), pointer :: reportno(:) => null()
   real(kind=jprl), pointer :: bufrtype(:) => null()
   real(kind=jprl), pointer :: subtype(:) => null()
   real(kind=jprl), pointer :: subsetno(:) => null()
   real(kind=jprl), pointer :: groupid(:) => null()
   real(kind=jprl), pointer :: reportype(:) => null()
   real(kind=jprl), pointer :: obstype(:) => null()
   real(kind=jprl), pointer :: codetype(:) => null()
   real(kind=jprl), pointer :: sensor(:) => null()
   real(kind=jprl), pointer :: retrtype(:) => null()
   real(kind=jprl), pointer :: instrument_type(:) => null()
   real(kind=jprl), pointer :: stalt(:) => null()
   real(kind=jprl), pointer :: date(:) => null()
   real(kind=jprl), pointer :: time(:) => null()
   real(kind=jprl), pointer :: rdbdate(:) => null()
   real(kind=jprl), pointer :: rdbtime(:) => null()
   real(kind=jprl), pointer :: distribtype(:) => null()
   real(kind=jprl), pointer :: distribid(:) => null()
   real(kind=jprl), pointer :: gp_dist(:) => null()
   real(kind=jprl), pointer :: gp_number(:) => null()
   real(kind=jprl), pointer :: numlev(:) => null()
   real(kind=jprl), pointer :: numactiveb(:) => null()
   real(kind=jprl), pointer :: checksum(:) => null()
   real(kind=jprl), pointer :: sortbox(:) => null()
   real(kind=jprl), pointer :: areatype(:) => null()
   real(kind=jprl), pointer :: report_status(:) => null()
   real(kind=jprl), pointer :: report_event1(:) => null()
   real(kind=jprl), pointer :: report_rdbflag(:) => null()
   real(kind=jprl), pointer :: report_blacklist(:) => null()
   real(kind=jprl), pointer :: report_event2(:) => null()
   real(kind=jprl), pointer :: thinningtimekey(:) => null()
   real(kind=jprl), pointer :: sitedep(:) => null()
   real(kind=jprl), pointer :: source(:) => null()
   real(kind=jprl), pointer :: lat(:) => null()
   real(kind=jprl), pointer :: lon(:) => null()
   real(kind=jprl), pointer :: trlat(:) => null()
   real(kind=jprl), pointer :: trlon(:) => null()
   real(kind=jprl), pointer :: restricted(:) => null()
   real(kind=jprl), pointer :: modsurf(:) => null()
   real(kind=jprl), pointer :: statid(:) => null()
   real(kind=jprl), pointer :: conv(:) => null()
   real(kind=jprl), pointer :: sat(:) => null()
   real(kind=jprl), pointer :: body(:) => null()
   real(kind=jprl), pointer :: errstat(:) => null()
   real(kind=jprl), pointer :: auxiliary(:) => null()
   real(kind=jprl), pointer :: ensemble(:) => null()
   real(kind=jprl), pointer :: gbrad(:) => null()
   real(kind=jprl), pointer :: raingg(:) => null()
   real(kind=jprl), pointer :: clrad(:) => null()
   real(kind=jprl), pointer :: claerlid(:) => null()
   real(kind=jprl), pointer :: surfbody_feedback(:) => null()
   real(kind=jprl), pointer :: superob(:) => null()
   real(kind=jprl), pointer :: window_offset(:) => null()
end type hdr_table

type limb_table
   real(kind=jprl), pointer :: ntan(:) => null()
end type limb_table

type modsurf_table
   real(kind=jprl), pointer :: lsm(:) => null()
   real(kind=jprl), pointer :: seaice(:) => null()
   real(kind=jprl), pointer :: orography(:) => null()
   real(kind=jprl), pointer :: snow_depth(:) => null()
   real(kind=jprl), pointer :: snow_density(:) => null()
   real(kind=jprl), pointer :: soil_moisture(:) => null()
   real(kind=jprl), pointer :: soil_temp(:) => null()
   real(kind=jprl), pointer :: lai(:) => null()
   real(kind=jprl), pointer :: t2m(:) => null()
   real(kind=jprl), pointer :: albedo(:) => null()
   real(kind=jprl), pointer :: windspeed10m(:) => null()
   real(kind=jprl), pointer :: u10m(:) => null()
   real(kind=jprl), pointer :: v10m(:) => null()
   real(kind=jprl), pointer :: surface_class(:) => null()
   real(kind=jprl), pointer :: tsfc(:) => null()
end type modsurf_table

type radar_table
   real(kind=jprl), pointer :: iternoconv_1dv(:) => null()
   real(kind=jprl), pointer :: failure_1dv(:) => null()
   real(kind=jprl), pointer :: radar_body(:) => null()
end type radar_table

type radar_body_table
   real(kind=jprl), pointer :: flgdyn(:) => null()
   real(kind=jprl), pointer :: time(:) => null()
   real(kind=jprl), pointer :: distance(:) => null()
   real(kind=jprl), pointer :: elevation(:) => null()
   real(kind=jprl), pointer :: polarisation(:) => null()
   real(kind=jprl), pointer :: anaprop(:) => null()
   real(kind=jprl), pointer :: reflcost(:) => null()
   real(kind=jprl), pointer :: azimuth(:) => null()
   real(kind=jprl), pointer :: press(:) => null()
   real(kind=jprl), pointer :: temp_1dv(:) => null()
   real(kind=jprl), pointer :: q_1dv(:) => null()
end type radar_body_table

type radar_station_table
   real(kind=jprl), pointer :: ident(:) => null()
   real(kind=jprl), pointer :: type(:) => null()
   real(kind=jprl), pointer :: lat(:) => null()
   real(kind=jprl), pointer :: lon(:) => null()
   real(kind=jprl), pointer :: stalt(:) => null()
   real(kind=jprl), pointer :: antenht(:) => null()
   real(kind=jprl), pointer :: beamwidth(:) => null()
   real(kind=jprl), pointer :: frequency(:) => null()
end type radar_station_table

type radiance_table
   real(kind=jprl), pointer :: scanline(:) => null()
   real(kind=jprl), pointer :: scanpos(:) => null()
   real(kind=jprl), pointer :: orbit(:) => null()
   real(kind=jprl), pointer :: typesurf(:) => null()
   real(kind=jprl), pointer :: corr_version(:) => null()
   real(kind=jprl), pointer :: cldcover(:) => null()
   real(kind=jprl), pointer :: skintemper(:) => null()
   real(kind=jprl), pointer :: scatterindex_89_157(:) => null()
   real(kind=jprl), pointer :: scatterindex_23_89(:) => null()
   real(kind=jprl), pointer :: scatterindex_23_165(:) => null()
   real(kind=jprl), pointer :: lwp_obs(:) => null()
   real(kind=jprl), pointer :: asr_pclear(:) => null()
   real(kind=jprl), pointer :: asr_pcloudy(:) => null()
   real(kind=jprl), pointer :: asr_pcloudy_low(:) => null()
   real(kind=jprl), pointer :: asr_pcloudy_middle(:) => null()
   real(kind=jprl), pointer :: asr_pcloudy_high(:) => null()
   real(kind=jprl), pointer :: allsky(:) => null()
   real(kind=jprl), pointer :: cloud_sink(:) => null()
   real(kind=jprl), pointer :: collocated_imager_information(:) => null()
   real(kind=jprl), pointer :: radiance_body(:) => null()
end type radiance_table

type radiance_body_table
   real(kind=jprl), pointer :: csr_pclear(:) => null()
   real(kind=jprl), pointer :: cld_fg_depar(:) => null()
   real(kind=jprl), pointer :: rank_cld(:) => null()
   real(kind=jprl), pointer :: tausfc(:) => null()
   real(kind=jprl), pointer :: skintemp_retr(:) => null()
   real(kind=jprl), pointer :: tbclear(:) => null()
   real(kind=jprl), pointer :: emis_rtin(:) => null()
   real(kind=jprl), pointer :: emis_atlas(:) => null()
   real(kind=jprl), pointer :: emis_atlas_error(:) => null()
   real(kind=jprl), pointer :: emis_retr(:) => null()
   real(kind=jprl), pointer :: emis_fg(:) => null()
   real(kind=jprl), pointer :: specularity(:) => null()
   real(kind=jprl), pointer :: cold_nedt(:) => null()
   real(kind=jprl), pointer :: warm_nedt(:) => null()
   real(kind=jprl), pointer :: channel_qc(:) => null()
   real(kind=jprl), pointer :: nobs_averaged(:) => null()
   real(kind=jprl), pointer :: stdev_averaged(:) => null()
   real(kind=jprl), pointer :: zenith_by_channel(:) => null()
   real(kind=jprl), pointer :: dust_aod_ir(:) => null()
end type radiance_body_table

type raingg_table
   real(kind=jprl), pointer :: report_rrflag(:) => null()
   real(kind=jprl), pointer :: raingg_body(:) => null()
end type raingg_table

type raingg_body_table
   real(kind=jprl), pointer :: rrvalue(:) => null()
   real(kind=jprl), pointer :: rrvaluetl(:) => null()
   real(kind=jprl), pointer :: rrvaluead(:) => null()
end type raingg_body_table

type resat_table
   real(kind=jprl), pointer :: instrument_type(:) => null()
   real(kind=jprl), pointer :: product_type(:) => null()
   real(kind=jprl), pointer :: solar_elevation(:) => null()
   real(kind=jprl), pointer :: scanpos(:) => null()
   real(kind=jprl), pointer :: cloud_cover(:) => null()
   real(kind=jprl), pointer :: cloud_top_press(:) => null()
   real(kind=jprl), pointer :: quality_retrieval(:) => null()
   real(kind=jprl), pointer :: number_layers(:) => null()
   real(kind=jprl), pointer :: resat_averaging_kernel(:) => null()
   real(kind=jprl), pointer :: snow_ice_indicator(:) => null()
   real(kind=jprl), pointer :: surface_type_indicator(:) => null()
   real(kind=jprl), pointer :: methane_correction(:) => null()
   real(kind=jprl), pointer :: surface_height(:) => null()
   real(kind=jprl), pointer :: retrsource(:) => null()
end type resat_table

type resat_averaging_kernel_table
   real(kind=jprl), pointer :: nak(:) => null()
end type resat_averaging_kernel_table

type sat_table
   real(kind=jprl), pointer :: satellite_identifier(:) => null()
   real(kind=jprl), pointer :: satellite_instrument(:) => null()
   real(kind=jprl), pointer :: zenith(:) => null()
   real(kind=jprl), pointer :: azimuth(:) => null()
   real(kind=jprl), pointer :: solar_zenith(:) => null()
   real(kind=jprl), pointer :: solar_azimuth(:) => null()
   real(kind=jprl), pointer :: range(:) => null()
   real(kind=jprl), pointer :: arg_lat(:) => null()
   real(kind=jprl), pointer :: lsm_fov(:) => null()
   real(kind=jprl), pointer :: gen_centre(:) => null()
   real(kind=jprl), pointer :: gen_subcentre(:) => null()
   real(kind=jprl), pointer :: datastream(:) => null()
   real(kind=jprl), pointer :: channel(:) => null()
   real(kind=jprl), pointer :: radiance(:) => null()
   real(kind=jprl), pointer :: resat(:) => null()
   real(kind=jprl), pointer :: gnssro(:) => null()
   real(kind=jprl), pointer :: satob(:) => null()
   real(kind=jprl), pointer :: limb(:) => null()
   real(kind=jprl), pointer :: ssmi(:) => null()
   real(kind=jprl), pointer :: smos(:) => null()
   real(kind=jprl), pointer :: scatt(:) => null()
   real(kind=jprl), pointer :: aeolus_hdr(:) => null()
   real(kind=jprl), pointer :: radar_station(:) => null()
   real(kind=jprl), pointer :: radar(:) => null()
end type sat_table

type satob_table
   real(kind=jprl), pointer :: comp_method(:) => null()
   real(kind=jprl), pointer :: instdata(:) => null()
   real(kind=jprl), pointer :: dataproc(:) => null()
   real(kind=jprl), pointer :: qi_fc(:) => null()
   real(kind=jprl), pointer :: qi_nofc(:) => null()
   real(kind=jprl), pointer :: rff(:) => null()
   real(kind=jprl), pointer :: ee(:) => null()
   real(kind=jprl), pointer :: segment_size_x(:) => null()
   real(kind=jprl), pointer :: segment_size_y(:) => null()
   real(kind=jprl), pointer :: chan_freq(:) => null()
   real(kind=jprl), pointer :: tb(:) => null()
   real(kind=jprl), pointer :: t(:) => null()
   real(kind=jprl), pointer :: shear(:) => null()
   real(kind=jprl), pointer :: t200(:) => null()
   real(kind=jprl), pointer :: t500(:) => null()
   real(kind=jprl), pointer :: top_mean_t(:) => null()
   real(kind=jprl), pointer :: top_wv(:) => null()
   real(kind=jprl), pointer :: dt_by_dp(:) => null()
   real(kind=jprl), pointer :: p_best(:) => null()
   real(kind=jprl), pointer :: u_best(:) => null()
   real(kind=jprl), pointer :: v_best(:) => null()
   real(kind=jprl), pointer :: dd_best(:) => null()
   real(kind=jprl), pointer :: ff_best(:) => null()
   real(kind=jprl), pointer :: p_old(:) => null()
   real(kind=jprl), pointer :: u_old(:) => null()
   real(kind=jprl), pointer :: v_old(:) => null()
   real(kind=jprl), pointer :: height_assignment_method(:) => null()
   real(kind=jprl), pointer :: tracer_correlation_method(:) => null()
   real(kind=jprl), pointer :: land_sea(:) => null()
   real(kind=jprl), pointer :: tracking_error_u(:) => null()
   real(kind=jprl), pointer :: tracking_error_v(:) => null()
   real(kind=jprl), pointer :: h_assignment_error_u(:) => null()
   real(kind=jprl), pointer :: h_assignment_error_v(:) => null()
   real(kind=jprl), pointer :: error_in_h_assignment(:) => null()
   real(kind=jprl), pointer :: ct_p(:) => null()
   real(kind=jprl), pointer :: cb_p(:) => null()
   real(kind=jprl), pointer :: umod_old(:) => null()
   real(kind=jprl), pointer :: vmod_old(:) => null()
end type satob_table

type scatt_table
   real(kind=jprl), pointer :: cellno(:) => null()
   real(kind=jprl), pointer :: nretr_amb(:) => null()
   real(kind=jprl), pointer :: prodflag(:) => null()
   real(kind=jprl), pointer :: wvc_qf(:) => null()
   real(kind=jprl), pointer :: scatt_body(:) => null()
end type scatt_table

type scatt_body_table
   real(kind=jprl), pointer :: azimuth(:) => null()
   real(kind=jprl), pointer :: incidence(:) => null()
   real(kind=jprl), pointer :: kp(:) => null()
   real(kind=jprl), pointer :: invresid(:) => null()
   real(kind=jprl), pointer :: dirskill(:) => null()
   real(kind=jprl), pointer :: mpc(:) => null()
   real(kind=jprl), pointer :: kp_qf(:) => null()
   real(kind=jprl), pointer :: ambig_select(:) => null()
   real(kind=jprl), pointer :: sigma0_qf(:) => null()
   real(kind=jprl), pointer :: sigma0_sm(:) => null()
   real(kind=jprl), pointer :: soilmoist_sd(:) => null()
   real(kind=jprl), pointer :: soilmoist_cf(:) => null()
   real(kind=jprl), pointer :: soilmoist_pf(:) => null()
   real(kind=jprl), pointer :: land_fraction(:) => null()
   real(kind=jprl), pointer :: wetland_fraction(:) => null()
   real(kind=jprl), pointer :: topo_complex(:) => null()
   real(kind=jprl), pointer :: likelihood(:) => null()
end type scatt_body_table

type smos_table
   real(kind=jprl), pointer :: snapshot_id(:) => null()
   real(kind=jprl), pointer :: grid_point_id(:) => null()
   real(kind=jprl), pointer :: electron_count(:) => null()
   real(kind=jprl), pointer :: sun_bt(:) => null()
   real(kind=jprl), pointer :: snapshot_acc(:) => null()
   real(kind=jprl), pointer :: rad_acc_pure(:) => null()
   real(kind=jprl), pointer :: rad_acc_cross(:) => null()
   real(kind=jprl), pointer :: polarisation(:) => null()
   real(kind=jprl), pointer :: water_fraction(:) => null()
   real(kind=jprl), pointer :: incidence_angle(:) => null()
   real(kind=jprl), pointer :: faradey_rot_angle(:) => null()
   real(kind=jprl), pointer :: pixel_rot_angle(:) => null()
   real(kind=jprl), pointer :: info(:) => null()
   real(kind=jprl), pointer :: snapshot_quality(:) => null()
   real(kind=jprl), pointer :: report_tbflag(:) => null()
   real(kind=jprl), pointer :: tbvalue(:) => null()
   real(kind=jprl), pointer :: nobs_averaged(:) => null()
   real(kind=jprl), pointer :: stdev_averaged(:) => null()
end type smos_table

type ssmi_table
   real(kind=jprl), pointer :: iterno_conv_1dvar(:) => null()
   real(kind=jprl), pointer :: simno_conv_1dvar(:) => null()
   real(kind=jprl), pointer :: failure_1dvar(:) => null()
   real(kind=jprl), pointer :: epsg_1dvar(:) => null()
   real(kind=jprl), pointer :: minim_status_1dvar(:) => null()
   real(kind=jprl), pointer :: cost(:) => null()
   real(kind=jprl), pointer :: sfc_rain_3d_fg(:) => null()
   real(kind=jprl), pointer :: sfc_snow_3d_fg(:) => null()
   real(kind=jprl), pointer :: sfc_rain_3d_an(:) => null()
   real(kind=jprl), pointer :: sfc_snow_3d_an(:) => null()
   real(kind=jprl), pointer :: ssmi_body(:) => null()
end type ssmi_table

type ssmi_body_table
   real(kind=jprl), pointer :: tcwv_fg(:) => null()
   real(kind=jprl), pointer :: tcwv_fg_err(:) => null()
   real(kind=jprl), pointer :: radcost(:) => null()
   real(kind=jprl), pointer :: rad_obs(:) => null()
   real(kind=jprl), pointer :: rad_fg_depar(:) => null()
   real(kind=jprl), pointer :: rad_an_depar(:) => null()
   real(kind=jprl), pointer :: rad_obs_err(:) => null()
   real(kind=jprl), pointer :: rad_bias(:) => null()
   real(kind=jprl), pointer :: rad_fg_3d(:) => null()
   real(kind=jprl), pointer :: rad_4dan(:) => null()
   real(kind=jprl), pointer :: frequency(:) => null()
   real(kind=jprl), pointer :: bandwidth(:) => null()
   real(kind=jprl), pointer :: polarisation(:) => null()
   real(kind=jprl), pointer :: press(:) => null()
end type ssmi_body_table

type superob_table
   real(kind=jprl), pointer :: standard_deviation(:) => null()
   real(kind=jprl), pointer :: n_obs(:) => null()
   real(kind=jprl), pointer :: cloud_fraction(:) => null()
   real(kind=jprl), pointer :: sf_max(:) => null()
end type superob_table

type surfbody_feedback_table
   real(kind=jprl), pointer :: datum_status(:) => null()
   real(kind=jprl), pointer :: datum_sfc_event(:) => null()
   real(kind=jprl), pointer :: an_depar(:) => null()
   real(kind=jprl), pointer :: fg_depar(:) => null()
   real(kind=jprl), pointer :: snow_depth(:) => null()
   real(kind=jprl), pointer :: snow_density(:) => null()
   real(kind=jprl), pointer :: lsm(:) => null()
end type surfbody_feedback_table

end module ifsobs_schema_mod
