! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOCPTDESC_MOD

!**** *IOCPTDESC_MOD*  - Structures used for field IO

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 11-09-2012

!     Modifications.
!     --------------
!      P. Marguinaud : 04-10-2016 : Port to single precision

USE PARKIND1, ONLY : JPIM, JPRB, JPIB
USE YOMHOOK, ONLY : DR_HOOK, JPHOOK, LHOOK

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NNAMELEN = 16_JPIM

INTEGER (KIND=JPIM) :: NIOCPTDESC_SIZE = -1

! Compressed field descriptor

CHARACTER (LEN=8), PARAMETER :: CIOCPTDESC_MAGIC = "IOCPTDES"

TYPE IOCPTDESC
  SEQUENCE
  CHARACTER (LEN=8)        :: CMAGIC = CIOCPTDESC_MAGIC
  CHARACTER (LEN=NNAMELEN) :: CNOMA  = ''
  INTEGER (KIND=JPIM)      :: ILNOMA = 0
  INTEGER (KIND=JPIM)      :: ILONGD = 0
  REAL (KIND=JPRB)         :: ZMIN   = + HUGE (1._JPRB)
  REAL (KIND=JPRB)         :: ZMAX   = - HUGE (1._JPRB)
  REAL (KIND=JPRB)         :: ZAVE   = 0._JPRB
END TYPE IOCPTDESC

SAVE

CONTAINS

SUBROUTINE IOCPTDESC_GROK_SIZE 

#include "abor1.intfb.h"

TYPE (IOCPTDESC) :: YLCPDSC (2)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

#define LHOOK .FALSE.
IF (LHOOK) CALL DR_HOOK('IOCPTDESC_MOD:IOCPTDESC_GROK_SIZE',0,ZHOOK_HANDLE)

CALL GROKSIZE (NIOCPTDESC_SIZE, YLCPDSC (2), YLCPDSC (1))

IF (MODULO (NIOCPTDESC_SIZE, JPRB) /= 0) &
  & CALL ABOR1 ('NIOCPTDESC_SIZE SIZE SHOULD BE A MULTIPLE OF JPRB')
NIOCPTDESC_SIZE = NIOCPTDESC_SIZE / JPRB

IF (LHOOK) CALL DR_HOOK('IOCPTDESC_MOD:IOCPTDESC_GROK_SIZE',1,ZHOOK_HANDLE)
#undef LHOOK

END SUBROUTINE IOCPTDESC_GROK_SIZE

REAL (KIND=JPRB) FUNCTION IOCPTDESC_FREEZE (YDCPTSC)
DIMENSION :: IOCPTDESC_FREEZE (NIOCPTDESC_SIZE)
TYPE (IOCPTDESC), INTENT (IN) :: YDCPTSC
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

#define LHOOK .FALSE.
IF (LHOOK) CALL DR_HOOK('IOCPTDESC_MOD:IOCPTDESC_FREEZE',0,ZHOOK_HANDLE)
IOCPTDESC_FREEZE = TRANSFER (YDCPTSC, IOCPTDESC_FREEZE)
IF (LHOOK) CALL DR_HOOK('IOCPTDESC_MOD:IOCPTDESC_FREEZE',1,ZHOOK_HANDLE)
#undef LHOOK

END FUNCTION IOCPTDESC_FREEZE

TYPE (IOCPTDESC) FUNCTION IOCPTDESC_THAW (P)
REAL (KIND=JPRB), INTENT (IN) :: P (NIOCPTDESC_SIZE)
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

#define LHOOK .FALSE.
IF (LHOOK) CALL DR_HOOK('IOCPTDESC_MOD:IOCPTDESC_THAW',0,ZHOOK_HANDLE)
IOCPTDESC_THAW = TRANSFER (P, IOCPTDESC_THAW)
IF (LHOOK) CALL DR_HOOK('IOCPTDESC_MOD:IOCPTDESC_THAW',1,ZHOOK_HANDLE)
#undef LHOOK

END FUNCTION IOCPTDESC_THAW

END MODULE IOCPTDESC_MOD
