! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOFLDDESC_MOD

!**** *IOFLDDESC_MOD*  - Structures used for field IO

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 11-09-2012

!     Modifications :
!     P. Marguinaud : 10-10-2013 : Move IOCPTDESC to IOCPTDESC_MOD, 
!                                  add freeze & thaw routines
!     P. Marguinaud : 04-10-2016 : Port to single precision

USE PARKIND1, ONLY : JPIM, JPRB, JPIB
USE YOMHOOK, ONLY : DR_HOOK, JPHOOK, LHOOK

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NPREFLEN =  8_JPIM
INTEGER (KIND=JPIM), PARAMETER :: NSUFFLEN = 16_JPIM

INTEGER (KIND=JPIM) :: NIOFLDDESC_SIZE = -1

CHARACTER (LEN=8), PARAMETER :: CIOFLDDESC_MAGIC = "IOFLDDES"

! Field descriptor for IO

TYPE IOFLDDESC_WAVEMODEL
  SEQUENCE
  INTEGER (KIND=JPIM)      :: IANGLE = -1_JPIM
  INTEGER (KIND=JPIM)      :: IFREQ  = -1_JPIM
  INTEGER (KIND=JPIM)      :: NDATE_TIME_WINDOW_END
  INTEGER (KIND=JPIM)      :: KCOUSTEP
  LOGICAL                  :: LRSTST0
  INTEGER (KIND=JPIM)      :: ITABLE
  INTEGER (KIND=JPIM)      :: IPARAM
  INTEGER (KIND=JPIM)      :: KLEV
  INTEGER (KIND=JPIM)      :: IFCST
  CHARACTER(LEN=2)         :: MARSTYPE
  CHARACTER(LEN=14)        :: CDATE
  INTEGER(KIND=JPIM)       :: NSTEP
END TYPE IOFLDDESC_WAVEMODEL
  
TYPE IOFLDDESC
  SEQUENCE 
  CHARACTER (LEN=8)        :: CMAGIC = CIOFLDDESC_MAGIC
  CHARACTER (LEN=NPREFLEN) :: CPREF  = ''       ! Field prefix
  INTEGER (KIND=JPIM)      :: ILEVG  = 0_JPIM   ! Field level
  CHARACTER (LEN=NSUFFLEN) :: CSUFF  = ''       ! Field suffix
  LOGICAL                  :: LREQD  = .TRUE.   ! If field is not in input file, program will abort
  LOGICAL                  :: LSPEC  = .FALSE.  ! Spectral field
  INTEGER(KIND=JPIM)       :: NFLSZ  = -1_JPIM  ! Field size (global)
  INTEGER(KIND=JPIM)       :: NSIZPK = -1_JPIM  ! Packed field size
  INTEGER(KIND=JPIM)       :: NGRIBL = -1_JPIM  ! Grib level
  INTEGER(KIND=JPIB)       :: IFPMASK = 0       ! Fullpos mask
! Grid point field only
  INTEGER (KIND=JPIM)      :: JBITS  = -1_JPIM  ! Number of bits for packing
  LOGICAL                  :: LUNDF  = .FALSE.  ! Field contains UNDEF values
  REAL (KIND=JPRB)         :: XUNDF  = 0._JPRB  ! UNDEF value
! Grid point hollow fields
  INTEGER (KIND=JPIM)      :: ICPLB  = 0_JPIM   ! Number of bits for packing mantissa
  INTEGER (KIND=JPIM)      :: ICPLS  = 0_JPIM   ! Size of the frame extension
! Spectral fields only 
  INTEGER (KIND=JPIM)      :: ILEVL  = 0_JPIM   ! Local level
  INTEGER (KIND=JPIM)      :: IVSET  = 0_JPIM   ! V-set
! Upper air fields
  INTEGER (KIND=JPIM)      :: IOLEV  = 0_JPIM  
  LOGICAL                  :: LIOLV  = .FALSE.  ! use IO levels
! Other
  REAL (KIND=JPRB)         :: XAUX1  = 0._JPRB
! Grib codes
  INTEGER (KIND=JPIM)      :: IGRIB  = 0_JPIM   ! GRIB code  
  INTEGER (KIND=JPIM)      :: IPREVPP  = -1_JPIM   ! Prev PP step for field
! Wave model
  TYPE(IOFLDDESC_WAVEMODEL) :: YWAM

END TYPE IOFLDDESC

SAVE

PRIVATE :: IOFLDDESC_EQ, IOFLDDESC_NEQ

INTERFACE OPERATOR (==)
  MODULE PROCEDURE IOFLDDESC_EQ
END INTERFACE

INTERFACE OPERATOR (/=)
  MODULE PROCEDURE IOFLDDESC_NEQ
END INTERFACE

CONTAINS

SUBROUTINE IOFLDDESC_GROK_SIZE 

#include "abor1.intfb.h"

TYPE (IOFLDDESC) :: YLFLDSC (2)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

#define LHOOK .FALSE.
IF (LHOOK) CALL DR_HOOK('IOFLDDESC_MOD:IOFLDDESC_GROK_SIZE',0,ZHOOK_HANDLE)

CALL GROKSIZE (NIOFLDDESC_SIZE, YLFLDSC (2), YLFLDSC (1))

IF (MODULO (NIOFLDDESC_SIZE, JPRB) /= 0) &
  & CALL ABOR1 ('NIOFLDDESC_SIZE SIZE SHOULD BE A MULTIPLE OF JPRB')
NIOFLDDESC_SIZE = NIOFLDDESC_SIZE / JPRB

IF (LHOOK) CALL DR_HOOK('IOFLDDESC_MOD:IOFLDDESC_GROK_SIZE',1,ZHOOK_HANDLE)
#undef LHOOK

END SUBROUTINE IOFLDDESC_GROK_SIZE

LOGICAL FUNCTION IOFLDDESC_EQ (YDFLDSC1, YDFLDSC2)

TYPE (IOFLDDESC), INTENT (IN) :: YDFLDSC1, YDFLDSC2

INTEGER (KIND=JPIB), ALLOCATABLE :: I1 (:), I2 (:)
INTEGER (KIND=JPIM)          :: ISIZE
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

#define LHOOK .FALSE.
IF (LHOOK) CALL DR_HOOK('IOFLDDESC_MOD:IOFLDDESC_EQ',0,ZHOOK_HANDLE)

ALLOCATE (I1 (ISIZE), I2 (ISIZE))

I1 = TRANSFER (YDFLDSC1, I1)
I2 = TRANSFER (YDFLDSC2, I2)

IOFLDDESC_EQ = ALL (I1 == I2)

DEALLOCATE (I1, I2)
IF (LHOOK) CALL DR_HOOK('IOFLDDESC_MOD:IOFLDDESC_EQ',1,ZHOOK_HANDLE)
#undef LHOOK

END FUNCTION IOFLDDESC_EQ

LOGICAL FUNCTION IOFLDDESC_NEQ (YDFLDSC1, YDFLDSC2)

TYPE (IOFLDDESC), INTENT (IN) :: YDFLDSC1, YDFLDSC2
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

#define LHOOK .FALSE.
IF (LHOOK) CALL DR_HOOK('IOFLDDESC_MOD:IOFLDDESC_NEQ',0,ZHOOK_HANDLE)

IOFLDDESC_NEQ = .NOT. IOFLDDESC_EQ (YDFLDSC1, YDFLDSC2)

IF (LHOOK) CALL DR_HOOK('IOFLDDESC_MOD:IOFLDDESC_NEQ',1,ZHOOK_HANDLE)
#undef LHOOK

END FUNCTION IOFLDDESC_NEQ

REAL (KIND=JPRB) FUNCTION IOFLDDESC_FREEZE (YDFLDSC)
DIMENSION :: IOFLDDESC_FREEZE (NIOFLDDESC_SIZE)
TYPE (IOFLDDESC), INTENT (IN) :: YDFLDSC
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

#define LHOOK .FALSE.
IF (LHOOK) CALL DR_HOOK('IOFLDDESC_MOD:IOFLDDESC_FREEZE',0,ZHOOK_HANDLE)
IOFLDDESC_FREEZE = TRANSFER (YDFLDSC, IOFLDDESC_FREEZE)
IF (LHOOK) CALL DR_HOOK('IOFLDDESC_MOD:IOFLDDESC_FREEZE',1,ZHOOK_HANDLE)
#undef LHOOK

END FUNCTION IOFLDDESC_FREEZE

TYPE (IOFLDDESC) FUNCTION IOFLDDESC_THAW (P)
REAL (KIND=JPRB), INTENT (IN) :: P (NIOFLDDESC_SIZE)
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

#include "abor1.intfb.h"

#define LHOOK .FALSE.
IF (LHOOK) CALL DR_HOOK('IOFLDDESC_MOD:IOFLDDESC_THAW',0,ZHOOK_HANDLE)
IOFLDDESC_THAW = TRANSFER (P, IOFLDDESC_THAW)
IF (IOFLDDESC_THAW%CMAGIC /= CIOFLDDESC_MAGIC) &
  & CALL ABOR1 ('IOFLDDESC_MOD:IOFLDDESC_THAW: DETECTED CORRUPTED IOFLDDESC')
IF (LHOOK) CALL DR_HOOK('IOFLDDESC_MOD:IOFLDDESC_THAW',1,ZHOOK_HANDLE)
#undef LHOOK

END FUNCTION IOFLDDESC_THAW

END MODULE IOFLDDESC_MOD

