! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOFU_MOD

!**** *IOFU_MOD*  Module for cumulated fluxes. 

! Author.
! -------
!  14/01/2011 : P.Marguinaud

! Modifications
!  P.Marguinaud : 11/09/2012 : Use IOFLDDESC_MOD
!  T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!  P.Marguinaud : 10/10/2013 : Cleaning
!  P.Marguinaud : 10/10/2014 : Add read capability
!  P.Marguinaud : 04-10-2016 : Port to single precision
! End Modifications
! ---------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
USE FA_MOD, ONLY : JPPRCM

USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE IOFLDPTR_MOD, ONLY : IOFLDPTR

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NIOFUACT_READ = 0, NIOFUACT_WRITE = 1

INTERFACE IOFU_SELECTD
  MODULE PROCEDURE IOFU_SELECTDD, IOFU_SELECTDP
END INTERFACE IOFU_SELECTD

PRIVATE :: IOFU_SELECTDD, IOFU_SELECTDP, IOFU_SELECT_WH

SAVE

CONTAINS

SUBROUTINE IOFU_COUNT(YDGEOMETRY,YDCFU,KACTION,KFNUM)

USE YOMCFU       , ONLY : TCFU
USE GEOMETRY_MOD , ONLY : GEOMETRY

IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)    :: YDGEOMETRY
TYPE(TCFU)          ,INTENT(INOUT)  :: YDCFU
INTEGER (KIND=JPIM), INTENT (IN)    :: KACTION
INTEGER (KIND=JPIM), INTENT (INOUT) :: KFNUM

INTEGER (KIND=JPIM) :: IFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOFU_MOD:IOFU_COUNT',0,ZHOOK_HANDLE)

IFCUR = 0
CALL IOFU_SELECT_WH(YDGEOMETRY,YDCFU,KACTION,KFCUR=IFCUR)
KFNUM = KFNUM + IFCUR

IF (LHOOK) CALL DR_HOOK('IOFU_MOD:IOFU_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOFU_COUNT

SUBROUTINE IOFU_SELECTDD(YDGEOMETRY,YDCFU,KACTION,YDFLDSC,KFCUR)

USE YOMCFU       , ONLY : TCFU
USE GEOMETRY_MOD , ONLY : GEOMETRY
IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)              :: YDGEOMETRY
TYPE(TCFU)          ,INTENT(INOUT)            :: YDCFU
INTEGER (KIND=JPIM), INTENT (IN)              :: KACTION
TYPE (IOFLDDESC),    INTENT (INOUT)           :: YDFLDSC (:)
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOFU_MOD:IOFU_SELECTDD',0,ZHOOK_HANDLE)

CALL IOFU_SELECT_WH(YDGEOMETRY,YDCFU,KACTION,YDFLDSC=YDFLDSC,KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOFU_MOD:IOFU_SELECTDD',1,ZHOOK_HANDLE)

END SUBROUTINE IOFU_SELECTDD

SUBROUTINE IOFU_SELECTDP(YDGEOMETRY,YDCFU,KACTION,YDFLDGT,KFCUR)

USE YOMCFU       , ONLY : TCFU
USE GEOMETRY_MOD , ONLY : GEOMETRY
IMPLICIT NONE

TYPE (GEOMETRY),      INTENT (IN)              :: YDGEOMETRY
TYPE(TCFU)           ,INTENT(INOUT)            :: YDCFU
INTEGER (KIND=JPIM),  INTENT (IN)              :: KACTION
TYPE (IOFLDPTR),      INTENT (INOUT)           :: YDFLDGT (:)
INTEGER (KIND=JPIM),  INTENT (INOUT), OPTIONAL :: KFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOFU_MOD:IOFU_SELECTDP',0,ZHOOK_HANDLE)

CALL IOFU_SELECT_WH(YDGEOMETRY,YDCFU,KACTION,YDFLDGT=YDFLDGT,KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOFU_MOD:IOFU_SELECTDP',1,ZHOOK_HANDLE)

END SUBROUTINE IOFU_SELECTDP

SUBROUTINE IOFU_SELECT_WH(YDGEOMETRY,YDCFU,KACTION,YDFLDSC,YDFLDGT,KFCUR)

!**** * IOFU_SELECT  * - ROUTINE TO SELECT CUMULATED FLUXES
!        14/01/2011 : Creation from wrfu.F90 ; P.Marguinaud
!        -----------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMCFU   , ONLY : TCFU
USE YOMCT0   , ONLY : LRPLANE
USE YOMOPH0  , ONLY : CNMCA
USE YOMFA    , ONLY : NVGRIB, NBITPG
USE FA_MOD   , ONLY : JPPRCM

IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)                      :: YDGEOMETRY
TYPE(TCFU), TARGET  ,INTENT(INOUT)                    :: YDCFU
INTEGER (KIND=JPIM), INTENT (IN)                      :: KACTION
TYPE (IOFLDPTR),     INTENT (INOUT), TARGET, OPTIONAL :: YDFLDGT (:)
TYPE (IOFLDDESC),    INTENT (INOUT), TARGET, OPTIONAL :: YDFLDSC (:)
INTEGER (KIND=JPIM), INTENT (INOUT),         OPTIONAL :: KFCUR

TYPE (IOFLDDESC), POINTER :: YLFLDSC (:)

INTEGER (KIND=JPIM) :: JF, JL, IFLD
INTEGER (KIND=JPIM) :: IFCUR
INTEGER (KIND=JPIM) :: IREP, IPFAOVSZ

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOFU_MOD:IOFU_SELECT_WH',0,ZHOOK_HANDLE)

IFCUR = 0
IF (PRESENT (KFCUR)) IFCUR = KFCUR

IF (PRESENT (YDFLDSC)) THEN
  YLFLDSC => YDFLDSC
ELSEIF (PRESENT (YDFLDGT)) THEN
  YLFLDSC => YDFLDGT%YFLDDSC
ELSE
  YLFLDSC => NULL ()
ENDIF

CALL FASGRA (IREP, CNMCA, IPFAOVSZ)

IFLD = 0
DO JF=1,YDCFU%NTYPCFU
  DO JL=1,YDCFU%TYPE_CFU(JF)%ILEV
    IFCUR = IFCUR + 1
    IFLD = IFLD + 1
    IF (ASSOCIATED (YLFLDSC)) THEN
      YLFLDSC(IFCUR)%NFLSZ  = YDGEOMETRY%YRGEM%NGPTOTG
      YLFLDSC(IFCUR)%NSIZPK = YDGEOMETRY%YRGEM%NGPTOTG + JPPRCM * IPFAOVSZ
      YLFLDSC(IFCUR)%CPREF  = YDCFU%TYPE_CFU(JF)%CLPREF(JL)
      YLFLDSC(IFCUR)%ILEVG  = YDCFU%TYPE_CFU(JF)%INUMLEV(JL)
      YLFLDSC(IFCUR)%CSUFF  = YDCFU%TYPE_CFU(JF)%CLSUFF
      YLFLDSC(IFCUR)%NGRIBL = NVGRIB
      YLFLDSC(IFCUR)%JBITS  = NBITPG
    ENDIF
    IF (PRESENT (YDFLDGT)) THEN
      YDFLDGT(IFCUR)%ZFLDGP => YDCFU%GFUBUF (:,IFLD,:) 
! De-reduce vector fields
      YDFLDGT(IFCUR)%LDRDGP = LRPLANE .AND. (YDCFU%TYPE_CFU(JF)%IPARITY == 1)
    ENDIF
  ENDDO
ENDDO

IF (PRESENT (KFCUR)) KFCUR = IFCUR

IF (LHOOK) CALL DR_HOOK('IOFU_MOD:IOFU_SELECT_WH',1,ZHOOK_HANDLE)

END SUBROUTINE IOFU_SELECT_WH

END MODULE IOFU_MOD

