! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOGRIDA_MOD

!**** *IOGRIDA_MOD*  Module for ARPEGE file writing.

! Author.
! -------
!  14/01/2011 : P.Marguinaud

! Modifications
!  P.Marguinaud : 11/09/2012 : Use IOFLDDESC_MOD
!  T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
! P.Marguinaud : 10/10/2013 : Use JPFAOVSZ_
! P.Marguinaud : 04-10-2016 : Port to single precision
! E.Dutra/G.Arduini : Jan 2018 : SNOWG is 3D, changed calls using only 1st level
! End Modifications
! ---------------------------------------------------------------------

USE PARKIND1     , ONLY : JPIM     ,JPRB
USE YOMHOOK      , ONLY : LHOOK,   DR_HOOK, JPHOOK

USE IOFLDPTR_MOD , ONLY : IOFLDPTR
USE IOFLDDESC_MOD, ONLY : IOFLDDESC

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NIOGRIDACT_READ = 0, NIOGRIDACT_WRITE = 1

PRIVATE

PUBLIC :: NIOGRIDACT_READ, NIOGRIDACT_WRITE, IOGRIDA_COUNT, &
        & IOGRIDA_SELECTD

INTERFACE IOGRIDA_SELECTD
  MODULE PROCEDURE IOGRIDA_SELECTDD, IOGRIDA_SELECTDP
END INTERFACE IOGRIDA_SELECTD

SAVE

CONTAINS

SUBROUTINE IOGRIDA_COUNT(YDGEOMETRY,YDSURF,YDMCC,YDDPHY,YDPHY,YDPHYDS,KACTION,KFNUM)
!     O. Marsden: June 2015 CY42 YRGMV, YRGFL, YRSURF, YRGMV5, and YRGFL5 are now passed by argument

USE YOMDPHY            , ONLY : TDPHY
USE YOMMCC             , ONLY : TMCC
USE YOMPHY             , ONLY : TPHY
USE YOMPHYDS           , ONLY : TPHYDS
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
IMPLICIT NONE


TYPE (GEOMETRY),     INTENT (IN)    :: YDGEOMETRY
TYPE (TSURF),        INTENT (INOUT) :: YDSURF
TYPE (TDPHY),        INTENT (IN)    :: YDDPHY
TYPE (TMCC),         INTENT (IN)    :: YDMCC
TYPE (TPHY),         INTENT (IN)    :: YDPHY
TYPE (TPHYDS),       INTENT (IN)    :: YDPHYDS
INTEGER (KIND=JPIM), INTENT (IN)    :: KACTION
INTEGER (KIND=JPIM), INTENT (INOUT) :: KFNUM

INTEGER (KIND=JPIM) :: IFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDA_MOD:IOGRIDA_COUNT',0,ZHOOK_HANDLE)

IFCUR = 0
CALL IOGRIDA_SELECT_WH(YDGEOMETRY,YDSURF,YDMCC,YDDPHY,YDPHY,YDPHYDS,KACTION,KFCUR=IFCUR)
KFNUM = KFNUM + IFCUR

IF (LHOOK) CALL DR_HOOK('IOGRIDA_MOD:IOGRIDA_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDA_COUNT

SUBROUTINE IOGRIDA_SELECTDD(YDGEOMETRY,YDSURF,YDMCC,YDDPHY,YDPHY,YDPHYDS,KACTION,YDFLDSC,KFCUR)

!     Purpose.
!     --------
!        Select out the model surface fields to ARPEGE file
!     History
!        14/01/2011 : Creation from wrgrida.F90 (P.Marguinaud)
!        O. Marsden: June 2015 CY42 YRGMV, YRGFL, YRSURF, YRGMV5, and YRGFL5 are now passed by argument
!     -------------------------------------------------------------------------

USE YOMDPHY            , ONLY : TDPHY
USE YOMMCC             , ONLY : TMCC
USE YOMPHY             , ONLY : TPHY
USE YOMPHYDS           , ONLY : TPHYDS
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)              :: YDGEOMETRY
TYPE (TSURF),        INTENT (INOUT)           :: YDSURF
TYPE (TDPHY),        INTENT (IN)              :: YDDPHY
TYPE (TMCC),         INTENT (IN)              :: YDMCC
TYPE (TPHY),         INTENT (IN)              :: YDPHY
TYPE (TPHYDS),       INTENT (IN)              :: YDPHYDS
INTEGER (KIND=JPIM), INTENT (IN)              :: KACTION
TYPE (IOFLDDESC),    INTENT (INOUT)           :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDA_MOD:IOGRIDA_SELECTDD',0,ZHOOK_HANDLE)

CALL IOGRIDA_SELECT_WH(YDGEOMETRY,YDSURF,YDMCC,YDDPHY,YDPHY,YDPHYDS,KACTION,YDFLDSC=YDFLDSC,KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOGRIDA_MOD:IOGRIDA_SELECTDD',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDA_SELECTDD

SUBROUTINE IOGRIDA_SELECTDP(YDGEOMETRY,YDSURF,YDMCC,YDDPHY,YDPHY,YDPHYDS,KACTION,YDFLDGT,KFCUR)

!     Purpose.
!     --------
!        Select out the model surface fields to ARPEGE file
!     History
!        14/01/2011 : Creation from wrgrida.F90 (P.Marguinaud)
!        O. Marsden: June 2015 CY42 YRGMV, YRGFL, YRSURF, YRGMV5, and YRGFL5 are now passed by argument
!     -------------------------------------------------------------------------

USE YOMDPHY            , ONLY : TDPHY
USE YOMMCC             , ONLY : TMCC
USE YOMPHY             , ONLY : TPHY
USE YOMPHYDS           , ONLY : TPHYDS
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
IMPLICIT NONE

TYPE (GEOMETRY),         INTENT (IN)              :: YDGEOMETRY
TYPE (TSURF),            INTENT (INOUT)           :: YDSURF
TYPE (TDPHY),            INTENT (IN)              :: YDDPHY
TYPE (TMCC),             INTENT (IN)              :: YDMCC
TYPE (TPHY),             INTENT (IN)              :: YDPHY
TYPE (TPHYDS),           INTENT (IN)              :: YDPHYDS
INTEGER (KIND=JPIM),     INTENT (IN)              :: KACTION
TYPE (IOFLDPTR),         INTENT (INOUT)           :: YDFLDGT (:) 
INTEGER (KIND=JPIM),     INTENT (INOUT), OPTIONAL :: KFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDA_MOD:IOGRIDA_SELECTDP',0,ZHOOK_HANDLE)

CALL IOGRIDA_SELECT_WH(YDGEOMETRY,YDSURF,YDMCC,YDDPHY,YDPHY,YDPHYDS,KACTION,YDFLDGT=YDFLDGT,KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOGRIDA_MOD:IOGRIDA_SELECTDP',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDA_SELECTDP

SUBROUTINE IOGRIDA_SELECT_WH(YDGEOMETRY,YDSURF,YDMCC,YDDPHY,YDPHY,YDPHYDS,KACTION,YDFLDSC,YDFLDGT,KFCUR)
!     O. Marsden: June 2015 CY42 YRGMV, YRGFL, YRSURF, YRGMV5, and YRGFL5 are now passed by argument

USE YOMDPHY            , ONLY : TDPHY
USE GEOMETRY_MOD       , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMCT0             , ONLY : LCANARI, LRPLANE, LSFXLSM, NCONF
USE YOMMCC             , ONLY : TMCC
USE YOMPHY             , ONLY : TPHY
USE YOMPHYDS           , ONLY : TPHYDS


IMPLICIT NONE

TYPE (GEOMETRY),               INTENT (IN)            :: YDGEOMETRY
TYPE (TSURF),                  INTENT (INOUT)         :: YDSURF
TYPE (TDPHY),                  INTENT (IN)            :: YDDPHY
TYPE (TMCC),                   INTENT (IN)            :: YDMCC
TYPE (TPHY),                   INTENT (IN)            :: YDPHY
TYPE (TPHYDS),                 INTENT (IN)            :: YDPHYDS
INTEGER (KIND=JPIM),           INTENT (IN)            :: KACTION
TYPE (IOFLDDESC),    OPTIONAL, INTENT (INOUT), TARGET :: YDFLDSC (:) 
TYPE (IOFLDPTR),     OPTIONAL, INTENT (INOUT), TARGET :: YDFLDGT (:) 
INTEGER (KIND=JPIM), OPTIONAL, INTENT (INOUT)         :: KFCUR
#include "abor1.intfb.h"

INTEGER (KIND=JPIM) :: IFCAN, IFISBA, JC, JV, IFCUR
LOGICAL             :: LLR

TYPE (IOFLDDESC), POINTER :: YLFLDSC (:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDA_MOD:IOGRIDA_SELECT_WH',0,ZHOOK_HANDLE)

IF (PRESENT (YDFLDSC)) THEN
  YLFLDSC => YDFLDSC
ELSEIF (PRESENT (YDFLDGT)) THEN
  YLFLDSC => YDFLDGT%YFLDDSC
ELSE
  YLFLDSC => NULL ()
ENDIF

IFCUR = 0
IF (PRESENT (KFCUR)) IFCUR = KFCUR


! Prognostic fields

! SOILB

DO JC = 1, YDSURF%YSP_SBD%NLEVS
  DO JV = 1, YDSURF%YSP_SBD%NUMFLDS
    CALL ACPY (YDSURF%YSP_SB%YSB(JV)%CNAME(JC), PFLD=YDSURF%SP_SB (:,JC,JV,:),&
       LDREQ=YDSURF%YSP_SB%YSB(JV)%NREQIN(JC)==1)
  ENDDO
ENDDO

! SNOWG

DO JV = 1, YDSURF%YSP_SGD%NUMFLDS
  CALL ACPY (YDSURF%YSP_SG%YSG(JV)%CNAME(1), PFLD=YDSURF%SP_SG (:,1,JV,:),LDREQ=.FALSE.)
ENDDO

! RESVR

DO JV = 1, YDSURF%YSP_RRD%NUMFLDS
  CALL ACPY (YDSURF%YSP_RR%YRR(JV)%CNAME, PFLD=YDSURF%SP_RR (:,JV,:),LDREQ=.FALSE.)
ENDDO

! CLS

SELECT CASE (KACTION)
  
  CASE (NIOGRIDACT_WRITE)
  
  CASE (NIOGRIDACT_READ)

    DO JV = 1, YDSURF%YSP_CLD%NUMFLDS
      CALL ACPY (YDSURF%YSP_CL%YCL(JV)%CNAME, PFLD=YDSURF%SP_CL (:,JV,:),LDREQ=.FALSE.)
    ENDDO

END SELECT 

! EXTRP

DO JC = 1, YDSURF%YSP_EPD%NLEVS
  DO JV = 1, YDSURF%YSP_EPD%NUMFLDS
    CALL ACPY (YDSURF%YSP_EP%YEP(JV)%CNAME(JC), PFLD=YDSURF%SP_EP (:,JC,JV,:),&
      LDREQ=YDSURF%YSP_EP%YEP(JV)%NREQIN(JC)==1)
  ENDDO
ENDDO

! XTRP2

DO JV=1,YDSURF%YSP_X2D%NUMFLDS
  CALL ACPY (YDSURF%YSP_X2%YX2(JV)%CNAME, PFLD=YDSURF%SP_X2 (:,JV,:), LDREQ=(NCONF/=701))
ENDDO

! CANRI

SELECT CASE (KACTION)

  CASE (NIOGRIDACT_WRITE)

    IF (LCANARI.AND.YDPHY%LSOLV) THEN
      IFISBA=5
    ELSE
      IFISBA=0
    ENDIF
    IFCAN = YDSURF%YSP_CID%NUMFLDS-IFISBA

    DO JV = 1, IFCAN
      IF (LRPLANE .AND.                                          (&
         & YDSURF%YSP_CI%YCI(JV)%CNAME == 'CLSVENT.ZONAL   '.OR.&
         & YDSURF%YSP_CI%YCI(JV)%CNAME == 'CLSVENT.MERIDIEN')) THEN

        CALL ACPY (YDSURF%YSP_CI%YCI(JV)%CNAME, PFLD=YDSURF%SP_CI (:,JV,:), LDRDGP=.TRUE., LDREQ=.FALSE.) 
      ELSEIF (YDSURF%YSP_CI%YCI(JV)%CNAME /= 'SURFANALYSISMASK' .AND.&
            & YDSURF%YSP_CI%YCI(JV)%CNAME /= 'SURFSST.CLIM.   ') THEN  
        CALL ACPY (YDSURF%YSP_CI%YCI(JV)%CNAME, PFLD=YDSURF%SP_CI (:,JV,:), LDREQ=.FALSE.) 
      ENDIF
    ENDDO

  CASE (NIOGRIDACT_READ)

    DO JV = 1, YDSURF%YSP_CID%NUMFLDS
      CALL ACPY (YDSURF%YSP_CI%YCI(JV)%CNAME, PFLD=YDSURF%SP_CI (:,JV,:), LDREQ=.FALSE.)
    ENDDO

END SELECT


! Climatological fields

! VARSF

DO JV = 1, YDSURF%YSD_VFD%NUMFLDS

  LLR=.FALSE.
  SELECT CASE (KACTION)
    CASE (NIOGRIDACT_WRITE)
      LLR = .TRUE.
    CASE (NIOGRIDACT_READ)
      LLR = .NOT.((YDSURF%YSD_VF%YVF(JV)%CNAME == 'SURFIND.TERREMER') .AND. LSFXLSM)
    CASE DEFAULT
      CALL ABOR1 ('IOGRIDA_MOD: UNEXPECTED KACTION')
  END SELECT

  
  IF (LLR .AND. .NOT.YDMCC%LMCC01) THEN

    IF (YDSURF%YSD_VF%YVF(JV)%CNAME (5:) == YDSURF%YSD_VF%YZ0F%CNAME(5:)) THEN
      CALL ACPY (YDSURF%YSD_VF%YVF(JV)%CNAME, PFLD=YDSURF%SD_VF (:,JV,:),&
        LDREQ=YDSURF%YSD_VF%YVF(JV)%NREQIN==1,KBPDG=64)
    ELSEIF (YDSURF%YSD_VF%YVF(JV)%CNAME (5:) == YDSURF%YSD_VF%YZ0RLF%CNAME(5:)) THEN
      CALL ACPY (YDSURF%YSD_VF%YVF(JV)%CNAME, PFLD=YDSURF%SD_VF (:,JV,:),&
        LDREQ=YDSURF%YSD_VF%YVF(JV)%NREQIN==1,KBPDG=64)
    ELSE
      CALL ACPY (YDSURF%YSD_VF%YVF(JV)%CNAME, PFLD=YDSURF%SD_VF (:,JV,:),&
        LDREQ=YDSURF%YSD_VF%YVF(JV)%NREQIN==1)
    ENDIF


  ENDIF

ENDDO

! VCLIP

DO JV = 1, YDSURF%YSD_VPD%NUMFLDS
  IF (.NOT.YDMCC%LMCC01) THEN
    CALL ACPY (YDSURF%YSD_VP%YVP(JV)%CNAME, PFLD=YDSURF%SD_VP (:,JV,:),&
      LDREQ=YDSURF%YSD_VP%YVP(JV)%NREQIN==1)
  ENDIF
ENDDO

! VCLIV

DO JV = 1, YDSURF%YSD_VVD%NUMFLDS
  IF (.NOT.YDMCC%LMCC01) THEN

    IF (YDSURF%YSD_VV%YVV(JV)%CNAME (5:) == YDSURF%YSD_VV%YZ0H%CNAME(5:)) THEN
      CALL ACPY (YDSURF%YSD_VV%YVV(JV)%CNAME, PFLD=YDSURF%SD_VV (:,JV,:),&
        LDREQ=YDSURF%YSD_VV%YVV(JV)%NREQIN==1,KBPDG=64)
    ELSE
      CALL ACPY (YDSURF%YSD_VV%YVV(JV)%CNAME, PFLD=YDSURF%SD_VV (:,JV,:),&
        LDREQ=YDSURF%YSD_VV%YVV(JV)%NREQIN==1)
    ENDIF


  ENDIF
ENDDO

! VCLIA

DO JV = 1, YDSURF%YSD_VAD%NUMFLDS
  IF (.NOT.YDMCC%LMCC01) THEN
    CALL ACPY (YDSURF%YSD_VA%YVA(JV)%CNAME, PFLD=YDSURF%SD_VA (:,JV,:),&
      LDREQ=YDSURF%YSD_VA%YVA(JV)%NREQIN==1)
  ENDIF
ENDDO

! VO3ABC

DO JV = 1, YDSURF%YSD_VCD%NUMFLDS
  IF (.NOT.YDMCC%LMCC01) THEN
    CALL ACPY (YDSURF%YSD_VC%YVC(JV)%CNAME, PFLD=YDSURF%SD_VC (:,JV,:), LDREQ=.FALSE.)
  ENDIF
ENDDO


SELECT CASE (KACTION)

  CASE (NIOGRIDACT_WRITE)

    DO JV = 1, YDSURF%YSD_VDD%NUMFLDS
      CALL ACPY (YDSURF%YSD_VD%YVD(JV)%CNAME, PFLD=YDSURF%SD_VD (:,JV,:))
    ENDDO

  CASE (NIOGRIDACT_READ)

! fields not read

END SELECT

! WAVES

DO JV=1,YDSURF%YSD_WSD%NUMFLDS
  CALL ACPY (YDSURF%YSD_WS%YWS(JV)%CNAME, PFLD=YDSURF%SD_WS (:,JV,:),&
    LDREQ=YDSURF%YSD_WS%YWS(JV)%NREQIN==1)
ENDDO

DO JV=1,YDSURF%YSD_WWD%NUMFLDS
  CALL ACPY (YDSURF%YSD_WW%YWW(JV)%CNAME, PFLD=YDSURF%SD_WW (:,JV,:),&
    LDREQ=YDSURF%YSD_WW%YWW(JV)%NREQIN==1)
ENDDO

! SFORC & SFLUX

SELECT CASE (KACTION)

  CASE (NIOGRIDACT_WRITE)

! fields not written

  CASE (NIOGRIDACT_READ)

    DO JV = 1, YDSURF%YSD_SFOD%NUMFLDS
      CALL ACPY (YDSURF%YSD_SFO%YSFO(JV)%CNAME, PFLD=YDSURF%SD_SFO (:,JV,:), LDREQ=.FALSE.)
    ENDDO

    DO JV = 1, YDSURF%YSD_SFLD%NUMFLDS
      CALL ACPY (YDSURF%YSD_SFL%YSFL(JV)%CNAME, PFLD=YDSURF%SD_SFL (:,JV,:), LDREQ=.FALSE.)
    ENDDO

END SELECT


SELECT CASE (KACTION)

  CASE (NIOGRIDACT_WRITE)

  CASE (NIOGRIDACT_READ)

    CALL ROZO
 
END SELECT

! VEXTRDI

SELECT CASE (KACTION)

  CASE (NIOGRIDACT_WRITE)

    IF (YDPHYDS%LREQOUT_VEXTRDI) THEN
      DO JC = 1, YDSURF%YSD_DID%NLEVS
        DO JV = 1, YDSURF%YSD_DID%NUMFLDS
          CALL ACPY (YDSURF%YSD_DI%YXA(JV)%CNAME(JC), PFLD=YDSURF%SD_DI (:,JC,JV,:))
        ENDDO
      ENDDO
    ENDIF

  CASE (NIOGRIDACT_READ)

    DO JC = 1, YDSURF%YSD_DID%NLEVS
      DO JV = 1, YDSURF%YSD_DID%NUMFLDS
        CALL ACPY (YDSURF%YSD_DI%YXA(JV)%CNAME(JC), PFLD=YDSURF%SD_DI (:,JC,JV,:),LDREQ=YDPHYDS%LREQIN_VEXTRDI)
      ENDDO
    ENDDO

END SELECT

IF (PRESENT (KFCUR)) KFCUR = IFCUR 

IF (LHOOK) CALL DR_HOOK('IOGRIDA_MOD:IOGRIDA_SELECT_WH',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE ROZO

! To be moved in iogridua_mod.F90 ?


INTEGER (KIND=JPIM) :: JV, JFLEV
CHARACTER(LEN=20) :: CLSUO3

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDA_MOD:ROZO',0,ZHOOK_HANDLE)


IF ((YDPHY%LOZONE .OR. (YDDPHY%NVCLIS == 1)) .AND. (.NOT.YDMCC%LMCC01)) THEN

  DO JFLEV = 1, YDGEOMETRY%YRDIMV%NFLEVG

    DO JV = 1, YDDPHY%NVCLIS
      WRITE (UNIT=CLSUO3, FMT='(''S   OZONE.A'',I1)') JV
      CALL ACPY (CLSUO3, KLEV=JFLEV)
    ENDDO 

  ENDDO 

ENDIF

IF (LHOOK) CALL DR_HOOK ('IOGRIDA_MOD:ROZO',1,ZHOOK_HANDLE)

END SUBROUTINE ROZO

SUBROUTINE ACPY (CDNAME, KLEV, PFLD, LDRDGP, LDREQ, KBPDG)

USE YOMOPH0, ONLY : CNMCA
USE YOMFA,  ONLY : NVGRIB, NBITPG
USE FA_MOD, ONLY : JPPRCM

CHARACTER (LEN=*),   INTENT (IN)                       :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN),    OPTIONAL          :: KLEV
REAL (KIND=JPRB),    INTENT (INOUT), OPTIONAL, TARGET  :: PFLD (:,:)  ! with YRDIM%NPROMA blocks
LOGICAL,             INTENT (IN),    OPTIONAL          :: LDRDGP
LOGICAL,             INTENT (IN),    OPTIONAL          :: LDREQ       ! field required
INTEGER (KIND=JPIM), INTENT (IN),    OPTIONAL          :: KBPDG

CHARACTER (LEN=*), PARAMETER :: CLBLANK = '                '
LOGICAL                      :: LLRDGP
REAL (KIND=JPRB),    POINTER :: ZFLD (:,:)
INTEGER (KIND=JPIM)          :: IREP, IPFAOVSZ

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDA_MOD:ACPY',0,ZHOOK_HANDLE)

CALL FASGRA (IREP, CNMCA, IPFAOVSZ)

LLRDGP = .FALSE.
IF (PRESENT (LDRDGP)) LLRDGP=LDRDGP

ZFLD => NULL ()
IF (PRESENT (PFLD)) ZFLD => PFLD

IF (CDNAME /= CLBLANK) THEN

  IFCUR = IFCUR + 1

  IF (ASSOCIATED (YLFLDSC)) THEN

    IF (IFCUR > UBOUND (YLFLDSC,1)) CALL ABOR1 ('INPUT BUFFER TOO SMALL')

    YLFLDSC(IFCUR)%ILEVG  = 0
    YLFLDSC(IFCUR)%LREQD  = .TRUE.
    YLFLDSC(IFCUR)%NFLSZ  = YDGEOMETRY%YRGEM%NGPTOTG
    YLFLDSC(IFCUR)%NSIZPK = YDGEOMETRY%YRGEM%NGPTOTG + JPPRCM * IPFAOVSZ
    YLFLDSC(IFCUR)%CPREF  = CDNAME(1:4)
    YLFLDSC(IFCUR)%CSUFF  = CDNAME(5:)
    YLFLDSC(IFCUR)%NGRIBL = NVGRIB
    YLFLDSC(IFCUR)%JBITS  = NBITPG

    IF (PRESENT (KLEV)) YLFLDSC(IFCUR)%ILEVG = KLEV

    IF (PRESENT (LDREQ)) YLFLDSC(IFCUR)%LREQD  = LDREQ

    IF (PRESENT (KBPDG)) THEN
      YLFLDSC(IFCUR)%JBITS = KBPDG
    ENDIF

  ENDIF

  IF (PRESENT (YDFLDGT)) THEN
    YDFLDGT(IFCUR)%ZFLDGP   => ZFLD
    YDFLDGT(IFCUR)%LDRDGP   = LLRDGP
  ENDIF

ENDIF

IF (LHOOK) CALL DR_HOOK ('IOGRIDA_MOD:ACPY',1,ZHOOK_HANDLE)

END SUBROUTINE ACPY

END SUBROUTINE IOGRIDA_SELECT_WH

END MODULE IOGRIDA_MOD

