! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOGRIDOE_MOD

!**** *IOGRIDOE_MOD*  Module for ECMWF Fullpos output selection, model levels.

! Author.
! -------
!  01/12/2014 : P.Marguinaud - From IOGRIDOA_MOD

! Modifications
! M.Hamrud : Jan 2015 : Added lagged p.p. etc.
! End Modifications

USE PARKIND1, ONLY : JPIM, JPRB, JPRD
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE IOFLDDESC_MOD, ONLY : IOFLDDESC

USE IOMULTIBUF_MOD, ONLY : IOMULTIBUF,&
                         & IOMULTIBUF_SIZE_IDX,&
                         & IOMULTIBUF_COMP_IDX

IMPLICIT NONE

INTERFACE IOGRIDOE_SELECTF
  MODULE PROCEDURE IOGRIDOE_SELECTFX, IOGRIDOE_SELECTFY
END INTERFACE IOGRIDOE_SELECTF

PRIVATE :: IOGRIDOE_SELECTFX, IOGRIDOE_SELECTFY

CONTAINS

SUBROUTINE IOGRIDOE_COUNT(YDGEOMETRY,YDSURF,KFNUM)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
TYPE(GEOMETRY)     ,INTENT(IN)    :: YDGEOMETRY
TYPE(TSURF)        ,INTENT(IN)    :: YDSURF
INTEGER (KIND=JPIM),INTENT (INOUT):: KFNUM
INTEGER (KIND=JPIM) :: IFCUR

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDOE_MOD:IOGRIDOE_COUNT',0,ZHOOK_HANDLE)

IFCUR = 0
CALL IOGRIDOE_SELECT_WH(YDGEOMETRY,YDSURF,KFCUR=IFCUR)
KFNUM = KFNUM + IFCUR

IF (LHOOK) CALL DR_HOOK ('IOGRIDOE_MOD:IOGRIDOE_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDOE_COUNT

SUBROUTINE IOGRIDOE_SELECTD(YDGEOMETRY,YDSURF,YDFLDSC, KFCUR)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
TYPE(GEOMETRY)     , INTENT(IN)    :: YDGEOMETRY
TYPE(TSURF)        , INTENT(IN)    :: YDSURF
TYPE (IOFLDDESC)   , INTENT(INOUT):: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT(INOUT), OPTIONAL :: KFCUR
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE


IF (LHOOK) CALL DR_HOOK ('IOGRIDOE_MOD:IOGRIDOE_SELECTD',0,ZHOOK_HANDLE)

CALL IOGRIDOE_SELECT_WH(YDGEOMETRY,YDSURF,YDFLDSC=YDFLDSC, KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK ('IOGRIDOE_MOD:IOGRIDOE_SELECTD',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDOE_SELECTD

SUBROUTINE IOGRIDOE_SELECTFX(YDGEOMETRY,YDSURF,PREAL, YDFLDSC, KFCUR)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
TYPE(GEOMETRY)     , INTENT (IN)    :: YDGEOMETRY
TYPE(TSURF)        , INTENT (IN)    :: YDSURF
REAL (KIND=JPRB)   , INTENT (INOUT), TARGET   :: PREAL (:,:)
TYPE (IOFLDDESC)   , INTENT (INOUT)           :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
TYPE (IOMULTIBUF) :: YLGPBUF (1)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDOE_MOD:IOGRIDOE_SELECTFX',0,ZHOOK_HANDLE)

YLGPBUF (1)%P => PREAL

CALL IOGRIDOE_SELECT_WH(YDGEOMETRY,YDSURF,YDGPBUF=YLGPBUF, YDFLDSC=YDFLDSC,&
                       & KFCUR=KFCUR, LDCHECKCD=.TRUE.)

IF (LHOOK) CALL DR_HOOK ('IOGRIDOE_MOD:IOGRIDOE_SELECTFX',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDOE_SELECTFX

SUBROUTINE IOGRIDOE_SELECTFY(YDGEOMETRY,YDSURF,YDGPBUF, YDFLDSC, KFCUR)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
TYPE(GEOMETRY)     , INTENT(IN)     :: YDGEOMETRY
TYPE(TSURF)        , INTENT(IN)     :: YDSURF
TYPE (IOMULTIBUF)  , INTENT (INOUT) :: YDGPBUF (:)
TYPE (IOFLDDESC)   , INTENT (INOUT) :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDOE_MOD:IOGRIDOE_SELECTFY',0,ZHOOK_HANDLE)

CALL IOGRIDOE_SELECT_WH(YDGEOMETRY,YDSURF,YDGPBUF=YDGPBUF, YDFLDSC=YDFLDSC,&
                       & KFCUR=KFCUR, LDCHECKCD=.TRUE.)

IF (LHOOK) CALL DR_HOOK ('IOGRIDOE_MOD:IOGRIDOE_SELECTFY',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDOE_SELECTFY

SUBROUTINE IOGRIDOE_SELECT_WH(YDGEOMETRY,YDSURF,YDGPBUF, YDFLDSC, KFCUR, LDCHECKCD)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULOUT
USE YOMCT3   , ONLY : NSTEP    !KPP
USE YOM_GRIB_CODES  , ONLY :&
 & NGRBOCLDP,NGRBOCLZ ,&!KPP
 & NGRBOCUC  ,NGRBOCVC

IMPLICIT NONE

TYPE(GEOMETRY)    , INTENT(IN)    :: YDGEOMETRY
TYPE(TSURF)       , INTENT(IN)    :: YDSURF
TYPE (IOMULTIBUF) , INTENT(INOUT), OPTIONAL :: YDGPBUF (:)
TYPE (IOFLDDESC)  , INTENT(INOUT), OPTIONAL, TARGET :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
LOGICAL,             INTENT (IN),    OPTIONAL :: LDCHECKCD
#include "fcttim.func.h"
#include "abor1.intfb.h"

REAL(KIND=JPRB), POINTER :: ZREAL(:)

LOGICAL :: LLCOPYF, LLCOPYD, LLCHECKCD
INTEGER (KIND=JPIM) :: IGPBUFY, JGPBUFY
INTEGER (KIND=JPIM), ALLOCATABLE :: IGPBUFY_IDX (:), JGPBUFY_IDX (:)
INTEGER (KIND=JPIM) :: INFLD, IFCUR
TYPE (IOFLDDESC), POINTER :: YLFLDSC (:)

INTEGER(KIND=JPIM) :: IEND, IGGMAX, IGRIBCD,&
 & J, JF, JLEV, JSTGLO, IBL 

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDOE_MOD:IOGRIDOE_SELECT_WH',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, YDMP=>YDGEOMETRY%YRMP)
ASSOCIATE( &
 & SP_OM=>YDSURF%SP_OM,YSP_OM=>YDSURF%YSP_OM,YSP_OMD=>YDSURF%YSP_OMD,& 
 & SD_V2=>YDSURF%SD_V2,YSD_V2=>YDSURF%YSD_V2,YSD_V2D=>YDSURF%YSD_V2D,&
 & YSD_V3=>YDSURF%YSD_V3,SD_V3=>YDSURF%SD_V3,YSD_V3D=>YDSURF%YSD_V3D )

LLCOPYF = PRESENT (YDGPBUF)
LLCOPYD = PRESENT (YDFLDSC)

IFCUR = 0
IF (PRESENT (KFCUR)) IFCUR = KFCUR

IF (LLCOPYF) THEN
  CALL IOMULTIBUF_SIZE_IDX (YDGPBUF, INFLD)
  ALLOCATE (IGPBUFY_IDX (INFLD), JGPBUFY_IDX (INFLD))
  CALL IOMULTIBUF_COMP_IDX (YDGPBUF, IGPBUFY_IDX, JGPBUFY_IDX)
ENDIF

YLFLDSC => NULL ()
IF (LLCOPYD) THEN
  YLFLDSC => YDFLDSC (IFCUR+1:)
ENDIF

LLCHECKCD = .FALSE.
IF (PRESENT (LDCHECKCD)) LLCHECKCD = LDCHECKCD

ZREAL => NULL ()
IF (LLCOPYD .AND. (.NOT. LLCHECKCD)) THEN
  YLFLDSC%CPREF  = 'm'
  YLFLDSC%ILEVG  = 0
  YLFLDSC%NFLSZ  = YDGEM%NGPTOTG
ENDIF


IGGMAX=0

IF (LLCOPYF) THEN

  WRITE(NULOUT,*) '-------- KPP OUTPUT KPP OUTPUT ',YSP_OMD%NUMFLDS 
  
  IF (YSP_OMD%NUMFLDS>0) THEN
    DO JF=1,YSP_OMD%NUMFLDS
      WRITE(NULOUT,'(A,I4,I6)') ' OML PROGNOSTIC FIELDS :',JF, YSP_OM%YOM(JF)%IGRBCODE(1)
    ENDDO
  ENDIF

ENDIF

IF( YSP_OMD%NUMFLDS > 0 ) THEN
  DO JF=1,YSP_OMD%NUMFLDS
    DO JLEV =1, YSP_OMD%NLEVS
      IGGMAX = IGGMAX+1

      IF (LLCOPYD) THEN
        IGRIBCD = YSP_OM%YOM(JF)%IGRBCODE(1)
        IF (LLCHECKCD) THEN
          IF ((YDFLDSC (IGGMAX)%IGRIB /= IGRIBCD) .OR. (YDFLDSC (IGGMAX)%ILEVG /= JLEV))&
            & CALL ABOR1 ('IOGRIDUE_MOD:IOGRIDUE_SELECT_WH: FIELD MISMATCH')
        ELSE
          YDFLDSC (IGGMAX)%IGRIB = IGRIBCD
          YDFLDSC (IGGMAX)%ILEVG = JLEV
        ENDIF
      ENDIF

      IF (LLCOPYF) THEN
        
        IGPBUFY = IGPBUFY_IDX (IFCUR+IGGMAX)
        JGPBUFY = JGPBUFY_IDX (IFCUR+IGGMAX)

        ZREAL => YDGPBUF (IGPBUFY)%P (:,JGPBUFY)    

        DO JSTGLO=1,YDGEM%NGPTOT,YDDIM%NPROMA
          IEND = MIN(YDDIM%NPROMA,YDGEM%NGPTOT-JSTGLO+1)
          IBL   = (JSTGLO-1)/YDDIM%NPROMA+1
          DO J=1,IEND
            ZREAL(JSTGLO+J-1) = SP_OM(J,JLEV,YSP_OM%YOM(JF)%MP,IBL)
          ENDDO
        ENDDO

      ENDIF

    ENDDO
  ENDDO
ENDIF

IF( NSTEP == 0 ) THEN  

  IF (LLCOPYF) THEN
    IF (YSD_V2D%NUMFLDS>0) THEN
      WRITE(NULOUT,'(A)') ' OML 2D DIAG FIELDS '
    ENDIF
  ENDIF

  IF( YSD_V2D%NUMFLDS > 0 ) THEN
    DO JF=1,YSD_V2D%NUMFLDS
      IGGMAX = IGGMAX+1

      IF (LLCOPYD) THEN
        IGRIBCD = YSD_V2%YV2(JF)%IGRBCODE
        IF (LLCHECKCD) THEN
          IF ((YDFLDSC (IGGMAX)%IGRIB /= IGRIBCD) .OR. (YDFLDSC (IGGMAX)%ILEVG /= 1))&
            & CALL ABOR1 ('IOGRIDUE_MOD:IOGRIDUE_SELECT_WH: FIELD MISMATCH')
        ELSE
          YDFLDSC (IGGMAX)%IGRIB = IGRIBCD
          YDFLDSC (IGGMAX)%ILEVG = 1
        ENDIF
      ENDIF

      IF (LLCOPYF) THEN
        WRITE(NULOUT,'(A,I4,I6)') ' OML 2D DIAGNOSTIC FIELDS :',JF, YSD_V2%YV2(JF)%IGRBCODE

        IGPBUFY = IGPBUFY_IDX (IFCUR+IGGMAX)
        JGPBUFY = JGPBUFY_IDX (IFCUR+IGGMAX)

        ZREAL => YDGPBUF (IGPBUFY)%P (:,JGPBUFY)    

        DO JSTGLO=1,YDGEM%NGPTOT,YDDIM%NPROMA
          IEND = MIN(YDDIM%NPROMA,YDGEM%NGPTOT-JSTGLO+1)
          IBL   = (JSTGLO-1)/YDDIM%NPROMA+1
          DO J=1,IEND
            ZREAL(JSTGLO+J-1) = SD_V2(J,YSD_V2%YV2(JF)%MP,IBL)
          ENDDO
        ENDDO

      ENDIF

    ENDDO
  ENDIF

  IF( YSD_V3D%NUMFLDS > 0 ) THEN
    DO JF=1,YSD_V3D%NUMFLDS
      IF(YSD_V3%YV3(JF)%IGRBCODE(1) == NGRBOCLZ  .OR.&!layer depth       
       & YSD_V3%YV3(JF)%IGRBCODE(1) == NGRBOCLDP .OR.&!layer thickness
       & YSD_V3%YV3(JF)%IGRBCODE(1) == NGRBOCUC  .OR.&
       & YSD_V3%YV3(JF)%IGRBCODE(1) == NGRBOCVC ) THEN  
        DO JLEV =1, YSD_V3D%NLEVS
          IGGMAX = IGGMAX+1

          IF (LLCOPYD) THEN
            IGRIBCD = YSD_V3%YV3(JF)%IGRBCODE(1)
            IF (LLCHECKCD) THEN
              IF ((YDFLDSC (IGGMAX)%IGRIB /= IGRIBCD) .OR. (YDFLDSC (IGGMAX)%ILEVG /= JLEV))&
                & CALL ABOR1 ('IOGRIDUE_MOD:IOGRIDUE_SELECT_WH: FIELD MISMATCH')
            ELSE
              YDFLDSC (IGGMAX)%IGRIB = IGRIBCD
              YDFLDSC (IGGMAX)%ILEVG = JLEV
            ENDIF
          ENDIF

          IF (LLCOPYF) THEN

            WRITE(NULOUT,'(A,I4,I6)') ' OML 3D DIAGNOSTIC FIELDS :',JF, YSD_V3%YV3(JF)%IGRBCODE(1)

            IGPBUFY = IGPBUFY_IDX (IFCUR+IGGMAX)
            JGPBUFY = JGPBUFY_IDX (IFCUR+IGGMAX)

            ZREAL => YDGPBUF (IGPBUFY)%P (:,JGPBUFY)    

            DO JSTGLO=1,YDGEM%NGPTOT,YDDIM%NPROMA
              IEND = MIN(YDDIM%NPROMA,YDGEM%NGPTOT-JSTGLO+1)
              IBL   = (JSTGLO-1)/YDDIM%NPROMA+1
              DO J=1,IEND
                ZREAL(JSTGLO+J-1) = SD_V3(J,JLEV,YSD_V3%YV3(JF)%MP,IBL)
              ENDDO
            ENDDO
          ENDIF

        ENDDO
      ENDIF
    ENDDO
  ENDIF

ENDIF

IF (PRESENT (KFCUR)) KFCUR = KFCUR + IGGMAX

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('IOGRIDOE_MOD:IOGRIDOE_SELECT_WH',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDOE_SELECT_WH 

END MODULE IOGRIDOE_MOD

