! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOGRCLIA_MOD

!**** *IOGRCLIA_MOD*  - Prepare buffer for climatological fields IO

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 11-09-2012


USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE IOFLDDESC_MOD, ONLY : IOFLDDESC, NSUFFLEN, NPREFLEN 

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NIOGRCLIACT_READ = 0, NIOGRCLIACT_WRITE = 1

PRIVATE

PUBLIC :: NIOGRCLIACT_READ, NIOGRCLIACT_WRITE, IOGRCLIA_COUNT,&
        & IOGRCLIA_SELECTD, IOGRCLIA_SELECTF

SAVE

CONTAINS

SUBROUTINE IOGRCLIA_COUNT(YDGEOMETRY,YDSURF,YDMCC,KACTION,KFNUM)

USE YOMMCC       , ONLY : TMCC
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
IMPLICIT NONE


TYPE(GEOMETRY)     ,INTENT(IN)    :: YDGEOMETRY
TYPE(TSURF)        ,INTENT(INOUT) :: YDSURF
TYPE(TMCC)         ,INTENT(INOUT) :: YDMCC
INTEGER (KIND=JPIM),INTENT (IN)   :: KACTION
INTEGER (KIND=JPIM),INTENT (INOUT):: KFNUM
#include "abor1.intfb.h"

INTEGER (KIND=JPIM) :: IFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRCLIA_MOD:IOGRCLIA_COUNT',0,ZHOOK_HANDLE)

IF (KACTION /= NIOGRCLIACT_READ) CALL ABOR1 ('ONLY NIOGRCLIACT_READ IS IMPLEMENTED')

IFCUR = 0
CALL IOGRCLIA_SELECT_WH(YDGEOMETRY,YDSURF,YDMCC,KACTION,KFCUR=IFCUR)
KFNUM = KFNUM + IFCUR

IF (LHOOK) CALL DR_HOOK('IOGRCLIA_MOD:IOGRCLIA_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRCLIA_COUNT

SUBROUTINE IOGRCLIA_SELECTF(YDGEOMETRY,YDSURF,YDMCC,KACTION,PREAL,YDFLDSC,KFCUR)

USE YOMMCC       , ONLY : TMCC
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
IMPLICIT NONE

TYPE(GEOMETRY)     ,INTENT(IN)    :: YDGEOMETRY
TYPE(TSURF)        ,INTENT(INOUT) :: YDSURF
TYPE(TMCC)         ,INTENT(INOUT) :: YDMCC
INTEGER (KIND=JPIM),INTENT (IN)   :: KACTION
REAL (KIND=JPRB)   ,INTENT (INOUT):: PREAL (:,:)
TYPE (IOFLDDESC)   ,INTENT (INOUT):: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
#include "abor1.intfb.h"

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRCLIA_MOD:IOGRCLIA_SELECTF',0,ZHOOK_HANDLE)

IF (KACTION /= NIOGRCLIACT_READ) CALL ABOR1 ('ONLY NIOGRCLIACT_READ IS IMPLEMENTED')

CALL IOGRCLIA_SELECT_WH(YDGEOMETRY,YDSURF,YDMCC,KACTION,PREAL,YDFLDSC=YDFLDSC,KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOGRCLIA_MOD:IOGRCLIA_SELECTF',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRCLIA_SELECTF

SUBROUTINE IOGRCLIA_SELECTD(YDGEOMETRY,YDSURF,YDMCC,KACTION,YDFLDSC,KFCUR)

USE YOMMCC       , ONLY : TMCC
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)    :: YDGEOMETRY
TYPE (TSURF),        INTENT (INOUT) :: YDSURF
TYPE(TMCC)          ,INTENT(INOUT)  :: YDMCC
INTEGER (KIND=JPIM), INTENT (IN)    :: KACTION
TYPE (IOFLDDESC)   , INTENT (INOUT) :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
#include "abor1.intfb.h"

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRCLIA_MOD:IOGRCLIA_SELECTD',0,ZHOOK_HANDLE)

IF (KACTION /= NIOGRCLIACT_READ) CALL ABOR1 ('ONLY NIOGRCLIACT_READ IS IMPLEMENTED')

CALL IOGRCLIA_SELECT_WH(YDGEOMETRY,YDSURF,YDMCC,KACTION,YDFLDSC=YDFLDSC,KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOGRCLIA_MOD:IOGRCLIA_SELECTD',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRCLIA_SELECTD

SUBROUTINE IOGRCLIA_SELECT_WH(YDGEOMETRY,YDSURF,YDMCC,KACTION,PREAL,YDFLDSC,KFCUR)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMMCC, ONLY : TMCC

IMPLICIT NONE

TYPE(GEOMETRY)     , INTENT(IN)    :: YDGEOMETRY
TYPE(TSURF)        , INTENT(INOUT) :: YDSURF
TYPE(TMCC)          ,INTENT(INOUT) :: YDMCC
INTEGER (KIND=JPIM), INTENT (IN)   :: KACTION
REAL (KIND=JPRB),    OPTIONAL, INTENT (INOUT), TARGET :: PREAL (:,:)
TYPE (IOFLDDESC),    OPTIONAL, INTENT (INOUT), TARGET :: YDFLDSC (:) 
INTEGER (KIND=JPIM), OPTIONAL, INTENT (INOUT)         :: KFCUR
#include "abor1.intfb.h"

REAL (KIND=JPRB),         POINTER :: ZREAL (:,:)
CHARACTER (LEN=NPREFLEN), POINTER :: CLPREF (:)
CHARACTER (LEN=NSUFFLEN), POINTER :: CLSUFF (:)
INTEGER (KIND=JPIM),      POINTER :: ILEV (:)
LOGICAL,                  POINTER :: LLREQRD (:)

INTEGER(KIND=JPIM) :: IFLD, JV, IFCUR
LOGICAL :: LLCOPYD
LOGICAL :: LLCOPYF

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRCLIA_MOD:IOGRCLIA_SELECT_WH',0,ZHOOK_HANDLE)

LLCOPYD = PRESENT (YDFLDSC)
LLCOPYF = PRESENT (PREAL)

IFCUR = 0
IF (PRESENT (KFCUR)) IFCUR = KFCUR

ZREAL => NULL ()
IF (LLCOPYF) THEN
  ZREAL => PREAL (:,IFCUR+1:)
ENDIF

CLPREF  => NULL ()
CLSUFF  => NULL ()
ILEV    => NULL ()
LLREQRD => NULL ()
IF (LLCOPYD) THEN
  CLPREF  => YDFLDSC (IFCUR+1:)%CPREF 
  CLSUFF  => YDFLDSC (IFCUR+1:)%CSUFF 
  ILEV    => YDFLDSC (IFCUR+1:)%ILEVG
  LLREQRD => YDFLDSC (IFCUR+1:)%LREQD
ENDIF

IF (LLCOPYD) THEN
  IF (ASSOCIATED (ILEV))    ILEV (:)    = 0
  IF (ASSOCIATED (LLREQRD)) LLREQRD (:) = .TRUE.
ENDIF

IFLD=0

DO JV = 1, YDSURF%YSD_VXD%NUMFLDS
  CALL ACPY(YDGEOMETRY,YDSURF%YSD_VX%YVX(JV)%CNAME, PBUF2=YDSURF%SD_VX(:,JV,:), LDREQ=.NOT.YDMCC%LMCC01)
ENDDO

IF (PRESENT (KFCUR)) KFCUR = KFCUR + IFLD

IF (LHOOK) CALL DR_HOOK('IOGRCLIA_MOD:IOGRCLIA_SELECT_WH',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE ACPY(YDGEOMETRY,CDNAME, PBUF2, LDREQ)


USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY)   , INTENT (IN)              :: YDGEOMETRY
CHARACTER (LEN=*), INTENT (IN)              :: CDNAME
REAL (KIND=JPRB) , INTENT (INOUT), OPTIONAL :: PBUF2 (:,:) ! with NPROMA blocks
LOGICAL,             INTENT (IN),    OPTIONAL :: LDREQ       ! field required

CHARACTER (LEN=*), PARAMETER :: CLBLANK = '                '
INTEGER (KIND=JPIM) :: JSTGLO, IEND, IBL, JL

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRCLIA_MOD:ACPY',0,ZHOOK_HANDLE)

IF (CDNAME /= CLBLANK) THEN

  IFLD = IFLD + 1

  IF (LLCOPYF) THEN

    IF (IFLD > UBOUND (ZREAL,2)) CALL ABOR1 ('INPUT BUFFER TOO SMALL')

    IF (PRESENT (PBUF2)) THEN

      DO JSTGLO = 1, YDGEOMETRY%YRGEM%NGPTOT, YDGEOMETRY%YRDIM%NPROMA

        IEND = MIN (YDGEOMETRY%YRDIM%NPROMA, YDGEOMETRY%YRGEM%NGPTOT-JSTGLO+1)
        IBL  = (JSTGLO-1) / YDGEOMETRY%YRDIM%NPROMA+1

        DO JL = 1, IEND

          SELECT CASE (KACTION)

            CASE (NIOGRCLIACT_WRITE)

              ZREAL (JSTGLO+JL-1,IFLD) = PBUF2 (JL,IBL)

            CASE (NIOGRCLIACT_READ)

              PBUF2 (JL,IBL) = ZREAL (JSTGLO+JL-1,IFLD)

          END SELECT

        ENDDO

      ENDDO

    ENDIF


  ENDIF

  IF (LLCOPYD) THEN

    IF (IFLD > UBOUND (CLPREF,1)) CALL ABOR1 ('INPUT BUFFER TOO SMALL')

    CLPREF(IFLD) = CDNAME(1:4)
    CLSUFF(IFLD) = CDNAME(5:)

    IF (PRESENT (LDREQ)) THEN
      IF (ASSOCIATED (LLREQRD)) LLREQRD (IFLD) = LDREQ
    ENDIF

  ENDIF

ENDIF

IF (LHOOK) CALL DR_HOOK ('IOGRCLIA_MOD:ACPY',1,ZHOOK_HANDLE)

END SUBROUTINE ACPY

END SUBROUTINE IOGRCLIA_SELECT_WH

END MODULE IOGRCLIA_MOD

