! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOGRIDUA_MOD

!**** *IOGRIDUA_MOD*  - Upper air field IO

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE* 

!     Modifications.
!      P. Marguinaud : 10-10-2014 : Read coupling files from the IO server + cleaning
!      P. Marguinaud : 04-10-2016 : Port to single precision

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE IOFLDPTR_MOD, ONLY : IOFLDPTR

USE YOMIO_SERV_MAP_PLAN, ONLY : IO_SERV_RECV_PLAN

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NIOGRIDUACT_READ = 0, NIOGRIDUACT_WRITE = 1

PRIVATE :: IOGRIDUA_SELECT_WH, IOGRIDUA_SELECTDD, IOGRIDUA_SELECTDP

INTERFACE IOGRIDUA_SELECTD
  MODULE PROCEDURE IOGRIDUA_SELECTDD, IOGRIDUA_SELECTDP
END INTERFACE IOGRIDUA_SELECTD

TYPE SUGRIDUA_MAP_CTX
  TYPE (IOFLDDESC), POINTER :: YFLDSC   (:) => NULL ()
  TYPE (IO_SERV_RECV_PLAN) :: YIOSMPP
END TYPE SUGRIDUA_MAP_CTX

SAVE

CONTAINS

SUBROUTINE IOGRIDUA_COUNT(YDGEOMETRY,YDGFL,YGFL,KACTION,KFNUM,KFILE)
!     O. Marsden: June 2015 CY42 YRGMV, YRGFL, YRSURF, YRGMV5, and YRGFL5 are now passed by argument

USE YOM_YGFL     , ONLY : TYPE_GFLD
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)              :: YDGEOMETRY
TYPE (TGFL),         INTENT (INOUT), TARGET   :: YDGFL
TYPE(TYPE_GFLD)     ,INTENT(INOUT)            :: YGFL
INTEGER (KIND=JPIM), INTENT (IN)              :: KACTION
INTEGER (KIND=JPIM), INTENT (INOUT)           :: KFNUM
INTEGER (KIND=JPIM), INTENT (IN),    OPTIONAL :: KFILE
INTEGER (KIND=JPIM) :: IFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDUA_MOD:IOGRIDUA_COUNT',0,ZHOOK_HANDLE)

IFCUR = 0
CALL IOGRIDUA_SELECT_WH(YDGEOMETRY,YDGFL,YGFL,KACTION,KFCUR=IFCUR,KFILE=KFILE)
KFNUM = KFNUM + IFCUR

IF (LHOOK) CALL DR_HOOK('IOGRIDUA_MOD:IOGRIDUA_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUA_COUNT

SUBROUTINE IOGRIDUA_SELECTDD(YDGEOMETRY,YDGFL,YGFL,KACTION,YDFLDSC,KFCUR,KFILE)

!**** *IOGRIDUA_SELECTD*  - 
!     Modifications.
!     --------------
!        14/01/2011 : Creation from wrgridua.F90 (P.Marguinaud)
!        O. Marsden: June 2015 CY42 YRGMV, YRGFL, YRSURF, YRGMV5, and YRGFL5 are now passed by argument
!------------------------------------------------------------------------------

USE YOM_YGFL     , ONLY : TYPE_GFLD
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
IMPLICIT NONE

TYPE (GEOMETRY),     INTENT(IN)               :: YDGEOMETRY
TYPE (TGFL),         INTENT (INOUT), TARGET   :: YDGFL
TYPE(TYPE_GFLD)     ,INTENT(INOUT)            :: YGFL
INTEGER (KIND=JPIM), INTENT (IN)              :: KACTION
TYPE (IOFLDDESC),    INTENT (INOUT)           :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
INTEGER (KIND=JPIM), INTENT (IN),    OPTIONAL :: KFILE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDUA_MOD:IOGRIDUA_SELECTDD',0,ZHOOK_HANDLE)

CALL IOGRIDUA_SELECT_WH(YDGEOMETRY,YDGFL,YGFL,KACTION,YDFLDSC=YDFLDSC,KFCUR=KFCUR,KFILE=KFILE)

IF (LHOOK) CALL DR_HOOK('IOGRIDUA_MOD:IOGRIDUA_SELECTDD',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUA_SELECTDD

SUBROUTINE IOGRIDUA_SELECTDP(YDGEOMETRY,YDGFL,YGFL,KACTION,YDFLDGT,KFCUR,KFILE)

!**** *IOGRIDUA_SELECTD*  - 
!     Modifications.
!     --------------
!        14/01/2011 : Creation from wrgridua.F90 (P.Marguinaud)
!        O. Marsden: June 2015 CY42 YRGMV, YRGFL, YRSURF, YRGMV5, and YRGFL5 are now passed by argument
!------------------------------------------------------------------------------

USE YOM_YGFL     , ONLY : TYPE_GFLD
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL , ONLY : TGFL
IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)                :: YDGEOMETRY
TYPE (TGFL),         INTENT (INOUT), TARGET    :: YDGFL
TYPE(TYPE_GFLD)     ,INTENT(INOUT)              :: YGFL
INTEGER (KIND=JPIM), INTENT (IN)              :: KACTION
TYPE (IOFLDPTR),     INTENT (INOUT)           :: YDFLDGT (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
INTEGER (KIND=JPIM), INTENT (IN),    OPTIONAL :: KFILE
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDUA_MOD:IOGRIDUA_SELECTDP',0,ZHOOK_HANDLE)

CALL IOGRIDUA_SELECT_WH(YDGEOMETRY,YDGFL,YGFL,KACTION,YDFLDGT=YDFLDGT,KFCUR=KFCUR,KFILE=KFILE)

IF (LHOOK) CALL DR_HOOK('IOGRIDUA_MOD:IOGRIDUA_SELECTDP',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUA_SELECTDP

SUBROUTINE IOGRIDUA_SELECT_WH(YDGEOMETRY,YDGFL,YGFL,KACTION,YDFLDSC,YDFLDGT,KFCUR,KFILE)
!     O. Marsden: June 2015 CY42 YRGMV, YRGFL, YRSURF, YRGMV5, and YRGFL5 are now passed by argument

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGFL   , ONLY : TGFL
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOMFA    , ONLY : YFAL, YFAI, YFAR, YFAS, YFALRAD, YFAIRAD, YFACLF, &
 & YFATKE, YFAG, YFAH, YFAO3, YFACPF, YFASPF, NVGRIB, NBITPG
USE YOMOPH0  , ONLY : CNMCA
USE FA_MOD   , ONLY : JPPRCM

!**** *IOGRIDUA_SELECT*  - Select out grid-point fields (GFL) to FA file
!     Modifications.
!     --------------
!        14/01/2011 : Creation from wrgridua.F90 (P.Marguinaud)
!   R. El Khatib 10-Aug-2011 NIOLEVG management
!   P.Marguinaud 10-Oct-2013 Use JPFAOVSZ_
!------------------------------------------------------------------------------

IMPLICIT NONE

TYPE (GEOMETRY),               INTENT (IN)             :: YDGEOMETRY
TYPE (TGFL),                   INTENT (INOUT), TARGET :: YDGFL
TYPE(TYPE_GFLD)               ,INTENT(INOUT)           :: YGFL
INTEGER (KIND=JPIM),           INTENT (IN)            :: KACTION
TYPE (IOFLDDESC),    OPTIONAL, INTENT (INOUT), TARGET :: YDFLDSC (:) 
TYPE (IOFLDPTR),     OPTIONAL, INTENT (INOUT), TARGET :: YDFLDGT (:)
INTEGER (KIND=JPIM), OPTIONAL, INTENT (INOUT)         :: KFCUR
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN)            :: KFILE

#include "abor1.intfb.h"

INTEGER (KIND=JPIM) :: JGFL, JLEV

LOGICAL                   :: LLDF
INTEGER (KIND=JPIM)       :: IFCUR
INTEGER (KIND=JPIM)       :: IFILE
TYPE (IOFLDDESC), POINTER :: YLFLDSC (:)
INTEGER (KIND=JPIM)       :: IREP, IPFAOVSZ

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE


!------------------------------------------------------------------------------

!        1.    SETUP DESCRIPTORS ARRAYS
!              ------------------------

IF (LHOOK) CALL DR_HOOK('IOGRIDUA_MOD:IOGRIDUA_SELECT_WH',0,ZHOOK_HANDLE)

IF (PRESENT (YDFLDSC)) THEN
  YLFLDSC => YDFLDSC
ELSEIF (PRESENT (YDFLDGT)) THEN
  YLFLDSC => YDFLDGT%YFLDDSC
ELSE
  YLFLDSC => NULL ()
ENDIF

IFCUR = 0
IF (PRESENT (KFCUR)) IFCUR = KFCUR

IFILE = -1
IF (PRESENT (KFILE)) IFILE = KFILE

CALL FASGRA (IREP, CNMCA, IPFAOVSZ)

DO JGFL = 1, YGFL%NUMFLDS

  SELECT CASE (KACTION)
    CASE (NIOGRIDUACT_WRITE)
      LLDF = YGFL%YCOMP(JGFL)%LGP .AND. YGFL%YCOMP(JGFL)%LREQOUT
    CASE (NIOGRIDUACT_READ)
      LLDF = YGFL%YCOMP(JGFL)%LGP .AND. (YGFL%YCOMP(JGFL)%NREQIN==1) .AND. ((&
          & YGFL%YCOMP(JGFL)%NCOUPLING==1) .OR. (IFILE/=9))
    CASE DEFAULT
      CALL ABOR1 ('IOGRIDUA_MOD: UNEXPECTED KACTION')
  END SELECT

  IF (LLDF) THEN

    DO JLEV = 1, YDGEOMETRY%YRDIMV%NFLEVG

      IFCUR = IFCUR + 1

      IF (ASSOCIATED (YLFLDSC)) THEN

        IF (IFCUR > UBOUND (YLFLDSC,1)) CALL ABOR1 ('INPUT BUFFER TOO SMALL')
   
        YLFLDSC(IFCUR)%NFLSZ  = YDGEOMETRY%YRGEM%NGPTOTG
        YLFLDSC(IFCUR)%NSIZPK = YDGEOMETRY%YRGEM%NGPTOTG + JPPRCM * IPFAOVSZ
        YLFLDSC(IFCUR)%NGRIBL = NVGRIB
        YLFLDSC(IFCUR)%JBITS  = NBITPG
   
        YLFLDSC(IFCUR)%CPREF = 'S   '
        YLFLDSC(IFCUR)%ILEVG = JLEV 
        YLFLDSC(IFCUR)%IOLEV = JLEV + YDGEOMETRY%YRDIMV%NIOLEVG - YDGEOMETRY%YRDIMV%NFLEVG
        YLFLDSC(IFCUR)%LIOLV = .TRUE.
        YLFLDSC(IFCUR)%CSUFF = YGFL%YCOMP(JGFL)%CNAME(1:12)
        YLFLDSC(IFCUR)%LREQD = .TRUE.
        
        IF (YLFLDSC(IFCUR)%CSUFF == YFAL%CLNAME(1:12) .AND. YFAL%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFAL%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFAI%CLNAME(1:12) .AND. YFAI%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFAI%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFALRAD%CLNAME(1:12) .AND. YFALRAD%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFALRAD%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFAIRAD%CLNAME(1:12) .AND. YFAIRAD%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFAIRAD%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFACLF%CLNAME(1:12) .AND. YFACLF%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFACLF%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFAR%CLNAME(1:12) .AND. YFAR%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFAR%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFAS%CLNAME(1:12) .AND. YFAS%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFAS%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFAG%CLNAME(1:12) .AND. YFAG%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFAG%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFAH%CLNAME(1:12) .AND. YFAH%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFAH%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFATKE%CLNAME(1:12) .AND. YFATKE%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFATKE%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFAO3%CLNAME(1:12) .AND. YFAO3%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFAO3%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFACPF%CLNAME(1:12) .AND. YFACPF%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFACPF%NBITS
        ELSEIF (YLFLDSC(IFCUR)%CSUFF == YFASPF%CLNAME(1:12) .AND. YFASPF%NBITS > 0) THEN
          YLFLDSC(IFCUR)%JBITS = YFASPF%NBITS
        ENDIF

      ENDIF

      IF (PRESENT (YDFLDGT)) THEN
        YDFLDGT(IFCUR)%ZFLDGP => YDGFL%GFL (:,JLEV,YGFL%YCOMP(JGFL)%MP,:)
        YDFLDGT(IFCUR)%LDRDGP = .FALSE.
      ENDIF
   

    ENDDO

  ENDIF

ENDDO

IF (PRESENT (KFCUR)) KFCUR = IFCUR

IF (LHOOK) CALL DR_HOOK('IOGRIDUA_MOD:IOGRIDUA_SELECT_WH',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUA_SELECT_WH

END MODULE IOGRIDUA_MOD

