! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOGRIDVA_MOD

!**** *IOGRIDVA_MOD*  Module for ARPEGE file writing.

! Author.
! -------
!  14/01/2011 : P.Marguinaud

! Modifications
! -------------
! P.Marguinaud : 11/09/2012 : Use IOFLDDESC_MOD
! End Modifications
! ---------------------------------------------------------------------

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK

USE IOFLDDESC_MOD, ONLY : IOFLDDESC, NSUFFLEN, NPREFLEN 

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NIOGRIDVACT_READ = 0, NIOGRIDVACT_WRITE = 1

PRIVATE

PUBLIC :: NIOGRIDVACT_READ, NIOGRIDVACT_WRITE, IOGRIDVA_COUNT, IOGRIDVA_SELECT,&
        & IOGRIDVA_SELECTD, IOGRIDVA_SELECTF

SAVE

CONTAINS

SUBROUTINE IOGRIDVA_COUNT(YDGEOMETRY,YDSURF,KACTION, KFNUM)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
IMPLICIT NONE


TYPE(GEOMETRY)     ,INTENT(IN)    :: YDGEOMETRY
TYPE(TSURF)        ,INTENT(INOUT) :: YDSURF
INTEGER (KIND=JPIM),INTENT (IN)   :: KACTION
INTEGER (KIND=JPIM),INTENT (INOUT):: KFNUM
INTEGER (KIND=JPIM) :: IFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDVA_MOD:IOGRIDVA_COUNT',0,ZHOOK_HANDLE)

IFCUR = 0
CALL IOGRIDVA_SELECT_WH(YDGEOMETRY,YDSURF,KACTION, KFCUR = IFCUR)
KFNUM = KFNUM + IFCUR

IF (LHOOK) CALL DR_HOOK('IOGRIDVA_MOD:IOGRIDVA_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDVA_COUNT

SUBROUTINE IOGRIDVA_SELECT(YDGEOMETRY,YDSURF,KACTION, PREAL, YDFLDSC, KFCUR)

!     Purpose.
!     --------
!        Select out the model surface fields to ARPEGE file
!     History
!        14/01/2011 : Creation from wrgrida.F90 (P.Marguinaud)
!     -------------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
IMPLICIT NONE

TYPE(GEOMETRY)     ,INTENT(IN)    :: YDGEOMETRY
TYPE(TSURF)        ,INTENT(INOUT) :: YDSURF
INTEGER (KIND=JPIM),INTENT (IN)   :: KACTION
REAL (KIND=JPRB)   ,INTENT (INOUT):: PREAL(:,:)
TYPE (IOFLDDESC)   ,INTENT (INOUT):: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDVA_MOD:IOGRIDVA_SELECT',0,ZHOOK_HANDLE)

CALL IOGRIDVA_SELECT_WH(YDGEOMETRY,YDSURF,KACTION, PREAL=PREAL, YDFLDSC=YDFLDSC, KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOGRIDVA_MOD:IOGRIDVA_SELECT',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDVA_SELECT

SUBROUTINE IOGRIDVA_SELECTD(YDGEOMETRY,YDSURF,KACTION, YDFLDSC, KFCUR)

!     Purpose.
!     --------
!        Select out the model surface fields to ARPEGE file
!     History
!        14/01/2011 : Creation from wrgrida.F90 (P.Marguinaud)
!     -------------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
IMPLICIT NONE

TYPE(GEOMETRY)     , INTENT (IN)    :: YDGEOMETRY
TYPE(TSURF)        , INTENT (INOUT) :: YDSURF
INTEGER (KIND=JPIM), INTENT (IN)    :: KACTION
TYPE (IOFLDDESC)   , INTENT (INOUT) :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDVA_MOD:IOGRIDVA_SELECTD',0,ZHOOK_HANDLE)

CALL IOGRIDVA_SELECT_WH(YDGEOMETRY,YDSURF,KACTION, YDFLDSC=YDFLDSC, KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOGRIDVA_MOD:IOGRIDVA_SELECTD',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDVA_SELECTD

SUBROUTINE IOGRIDVA_SELECTF(YDGEOMETRY,YDSURF,KACTION, PREAL, YDFLDSC, KFCUR)

!     Purpose.
!     --------
!        Select out the model surface fields to ARPEGE file
!     History
!        14/01/2011 : Creation from wrgrida.F90 (P.Marguinaud)
!     -------------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
IMPLICIT NONE

TYPE(GEOMETRY)     , INTENT (IN)    :: YDGEOMETRY
TYPE(TSURF)        , INTENT (INOUT) :: YDSURF
INTEGER (KIND=JPIM), INTENT (IN)    :: KACTION
REAL (KIND=JPRB)   , INTENT (INOUT) :: PREAL (:,:)
TYPE (IOFLDDESC)   , INTENT (INOUT) :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDVA_MOD:IOGRIDVA_SELECTF',0,ZHOOK_HANDLE)

CALL IOGRIDVA_SELECT_WH(YDGEOMETRY,YDSURF,KACTION, PREAL=PREAL, YDFLDSC=YDFLDSC,&
                      & KFCUR=KFCUR, LDCHECKCD=.TRUE.)

IF (LHOOK) CALL DR_HOOK('IOGRIDVA_MOD:IOGRIDVA_SELECTF',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDVA_SELECTF

SUBROUTINE IOGRIDVA_SELECT_WH(YDGEOMETRY,YDSURF,KACTION, PREAL, YDFLDSC, KFCUR, LDCHECKCD)


USE GEOMETRY_MOD , ONLY : GEOMETRY
USE SURFACE_FIELDS_MIX , ONLY : TSURF
IMPLICIT NONE

TYPE(GEOMETRY)     , INTENT(IN)    :: YDGEOMETRY
TYPE(TSURF)        , INTENT(INOUT) :: YDSURF
INTEGER (KIND=JPIM), INTENT(IN)    :: KACTION
REAL (KIND=JPRB),    OPTIONAL, INTENT (INOUT), TARGET :: PREAL(:,:)
TYPE (IOFLDDESC),    OPTIONAL, INTENT (INOUT), TARGET :: YDFLDSC (:) 
INTEGER (KIND=JPIM), OPTIONAL, INTENT (INOUT)         :: KFCUR
LOGICAL,             OPTIONAL, INTENT (IN)            :: LDCHECKCD
#include "abor1.intfb.h"

REAL (KIND=JPRB),         POINTER :: ZREAL (:,:)
CHARACTER (LEN=NPREFLEN), POINTER :: CLPREF (:)
CHARACTER (LEN=NSUFFLEN), POINTER :: CLSUFF (:)
INTEGER (KIND=JPIM),      POINTER :: ILEV (:)
LOGICAL,                  POINTER :: LLREQRD (:)

INTEGER(KIND=JPIM):: IFLD, JV, IFCUR
LOGICAL :: LLCOPYD
LOGICAL :: LLCOPYF
LOGICAL :: LLCHECKCD

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDVA_MOD:IOGRIDVA_SELECT_WH',0,ZHOOK_HANDLE)

LLCOPYF = PRESENT (PREAL)
LLCOPYD = PRESENT (YDFLDSC)

IFCUR = 0
IF (PRESENT (KFCUR)) IFCUR = KFCUR

IF (LLCOPYF) THEN
  ZREAL  => PREAL (:,IFCUR+1:)
ELSE
  ZREAL  => NULL ()
ENDIF

CLPREF  => NULL ()
CLSUFF  => NULL ()
ILEV    => NULL ()
LLREQRD => NULL ()
IF (LLCOPYD) THEN
  CLPREF  => YDFLDSC (IFCUR+1:)%CPREF  
  CLSUFF  => YDFLDSC (IFCUR+1:)%CSUFF  
  ILEV    => YDFLDSC (IFCUR+1:)%ILEVG
  LLREQRD => YDFLDSC (IFCUR+1:)%LREQD 
ENDIF

LLCHECKCD = .FALSE.
IF (PRESENT (LDCHECKCD)) LLCHECKCD = LDCHECKCD

IF (LLCOPYD .AND. (.NOT. LLCHECKCD)) THEN
  IF (ASSOCIATED (ILEV))    ILEV (:)    = 0
  IF (ASSOCIATED (LLREQRD)) LLREQRD (:) = .TRUE.
ENDIF

IFLD=0

! Climatological fields

! VARSF

DO JV = 1, YDSURF%YSD_VFD%NUMFLDS
  CALL ACPY(YDGEOMETRY,YDSURF%YSD_VF%YVF(JV)%CNAME, PBUF2=YDSURF%SD_VF (:,JV,:), LDREQ=.FALSE.)
ENDDO

! VCLIP

DO JV = 1, YDSURF%YSD_VPD%NUMFLDS
  CALL ACPY(YDGEOMETRY,YDSURF%YSD_VP%YVP(JV)%CNAME, PBUF2=YDSURF%SD_VP (:,JV,:), LDREQ=.FALSE.)
ENDDO

! VCLIV

DO JV = 1, YDSURF%YSD_VVD%NUMFLDS
  CALL ACPY(YDGEOMETRY,YDSURF%YSD_VV%YVV(JV)%CNAME, PBUF2=YDSURF%SD_VV (:,JV,:), LDREQ=.FALSE.)
ENDDO

! VCLIA

DO JV = 1, YDSURF%YSD_VAD%NUMFLDS
  CALL ACPY(YDGEOMETRY,YDSURF%YSD_VA%YVA(JV)%CNAME, PBUF2=YDSURF%SD_VA (:,JV,:), LDREQ=.FALSE.)
ENDDO

! VO3ABC

DO JV = 1, YDSURF%YSD_VCD%NUMFLDS
  CALL ACPY(YDGEOMETRY,YDSURF%YSD_VC%YVC(JV)%CNAME, PBUF2=YDSURF%SD_VC (:,JV,:), LDREQ=.FALSE.)
ENDDO

IF (PRESENT (KFCUR)) KFCUR = KFCUR + IFLD

IF (LHOOK) CALL DR_HOOK('IOGRIDVA_MOD:IOGRIDVA_SELECT_WH',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE ACPY(YDGEOMETRY,CDNAME, KLEV, PBUF2, LDREQ)


USE GEOMETRY_MOD , ONLY : GEOMETRY
TYPE(GEOMETRY)     , INTENT (IN)              :: YDGEOMETRY
CHARACTER (LEN=*)  , INTENT (IN)              :: CDNAME
INTEGER (KIND=JPIM), INTENT (IN)   , OPTIONAL :: KLEV
REAL (KIND=JPRB)   , INTENT (INOUT), OPTIONAL :: PBUF2 (:,:) ! with NPROMA blocks
LOGICAL            , INTENT (IN)   , OPTIONAL :: LDREQ       ! field required

CHARACTER (LEN=*), PARAMETER :: CLBLANK = '                '
INTEGER (KIND=JPIM) :: JSTGLO, IEND, IBL, JL

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDVA_MOD:ACPY',0,ZHOOK_HANDLE)
ASSOCIATE(NGPTOT=>YDGEOMETRY%YRGEM%NGPTOT, &
 & NPROMA=>YDGEOMETRY%YRDIM%NPROMA)

IF (CDNAME /= CLBLANK) THEN

  IFLD = IFLD + 1

  IF (LLCOPYF) THEN

    IF (IFLD > UBOUND (ZREAL,2)) CALL ABOR1 ('INPUT BUFFER TOO SMALL')

    IF (PRESENT (PBUF2)) THEN
  
      DO JSTGLO = 1, NGPTOT, NPROMA
      
        IEND = MIN (NPROMA, NGPTOT-JSTGLO+1)
        IBL  = (JSTGLO-1) / NPROMA+1
      
        DO JL = 1, IEND
      
          SELECT CASE (KACTION)
      
            CASE (NIOGRIDVACT_WRITE)
      
              ZREAL (JSTGLO+JL-1,IFLD) = PBUF2 (JL,IBL)
      
            CASE (NIOGRIDVACT_READ)
      
              PBUF2 (JL,IBL) = ZREAL (JSTGLO+JL-1,IFLD)
      
          END SELECT
      
        ENDDO
      
      ENDDO

    ENDIF
  
  ENDIF
  
  IF (LLCOPYD) THEN

    IF (IFLD > UBOUND (CLPREF,1)) CALL ABOR1 ('INPUT BUFFER TOO SMALL')

    IF (LLCHECKCD) THEN
      IF ((CLPREF(IFLD) /= CDNAME(1:4)) .OR. (CLSUFF(IFLD) /= CDNAME(5:)))&
      & CALL ABOR1 ('FIELD NAME MISMATCH')
    ELSE
      CLPREF(IFLD) = CDNAME(1:4)
      CLSUFF(IFLD) = CDNAME(5:)
      IF (PRESENT (KLEV)) THEN
        IF (ASSOCIATED (ILEV)) ILEV (IFLD) = KLEV
      ENDIF
      IF (PRESENT (LDREQ)) THEN
        IF (ASSOCIATED (LLREQRD)) LLREQRD (IFLD) = LDREQ
      ENDIF
    ENDIF
  ENDIF

ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK ('IOGRIDVA_MOD:ACPY',1,ZHOOK_HANDLE)

END SUBROUTINE ACPY

END SUBROUTINE IOGRIDVA_SELECT_WH

END MODULE IOGRIDVA_MOD
