! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOGRID_MOD

!**** *IOGRID_MOD*  - General handling ot grid-point fields

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 15-04-2016


USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NIOGRIDCT_READ = 0, NIOGRIDCT_WRITE = 1

PRIVATE
PUBLIC :: IOGRID_SELECTF, NIOGRIDCT_READ, NIOGRIDCT_WRITE

INTERFACE IOGRID_SELECTF
  MODULE PROCEDURE IOGRID_SELECTFX, IOGRID_SELECTFY
END INTERFACE IOGRID_SELECTF

SAVE

CONTAINS

SUBROUTINE INI_INDSEL (YDGEOMETRY, KINDSEL, KBLO, KROF, KINDSEL0)

USE GEOMETRY_MOD , ONLY : GEOMETRY

TYPE (GEOMETRY),     INTENT (IN)                   :: YDGEOMETRY
INTEGER (KIND=JPIM), POINTER                       :: KINDSEL  (:)
INTEGER (KIND=JPIM), INTENT (OUT)                  :: KBLO     (:)
INTEGER (KIND=JPIM), INTENT (OUT)                  :: KROF     (:)
INTEGER (KIND=JPIM), INTENT (IN), TARGET, OPTIONAL :: KINDSEL0 (:)

INTEGER (KIND=JPIM) :: II, IGLG, JKGLO

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRID_MOD:INI_INDSEL',0,ZHOOK_HANDLE)

IF (PRESENT (KINDSEL0)) THEN
  KINDSEL => KINDSEL0
ELSE
  ALLOCATE (KINDSEL (YDGEOMETRY%YRGEM%NGPTOT))
  KINDSEL = (/ (II, II = 1, YDGEOMETRY%YRGEM%NGPTOT) /)
ENDIF

DO II = 1, SIZE (KINDSEL)
  IGLG = KINDSEL (II)
  KBLO (IGLG) = 1 + (IGLG-1) / YDGEOMETRY%YRDIM%NPROMA
  JKGLO = 1 + YDGEOMETRY%YRDIM%NPROMA * (KBLO (IGLG)-1)
  KROF (IGLG) = IGLG-JKGLO+1
ENDDO

IF (LHOOK) CALL DR_HOOK ('IOGRID_MOD:INI_INDSEL',1,ZHOOK_HANDLE)

END SUBROUTINE INI_INDSEL

SUBROUTINE DEL_INDSEL (KINDSEL, KINDSEL0)

INTEGER (KIND=JPIM), POINTER                       :: KINDSEL  (:)
INTEGER (KIND=JPIM), INTENT (IN), TARGET, OPTIONAL :: KINDSEL0 (:)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRID_MOD:DEL_INDSEL',0,ZHOOK_HANDLE)

IF (PRESENT (KINDSEL0)) THEN
  NULLIFY (KINDSEL)
ELSE
  DEALLOCATE (KINDSEL)
  NULLIFY (KINDSEL)
ENDIF

IF (LHOOK) CALL DR_HOOK ('IOGRID_MOD:DEL_INDSEL',1,ZHOOK_HANDLE)

END SUBROUTINE DEL_INDSEL

SUBROUTINE IOGRID_SELECTFX (YDGEOMETRY, KACTION, PREAL, YDFLDGP, KINDSEL, LDFTL)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE IOFLDPTR_MOD,  ONLY : IOFLDPTR
USE IOMULTIBUF_MOD, ONLY : IOMULTIBUF

IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)              :: YDGEOMETRY
INTEGER (KIND=JPIM), INTENT (IN)              :: KACTION
REAL (KIND=JPRB),    INTENT (INOUT), TARGET   :: PREAL (:,:)
TYPE (IOFLDPTR),     INTENT (INOUT), OPTIONAL :: YDFLDGP (:)
INTEGER (KIND=JPIM), INTENT (IN),    OPTIONAL :: KINDSEL (:)
LOGICAL,             INTENT (IN),    OPTIONAL :: LDFTL

TYPE (IOMULTIBUF) :: YLGPBUF (1)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRID_MOD:IOGRID_SELECTFX',0,ZHOOK_HANDLE)

YLGPBUF (1)%P => PREAL

CALL IOGRID_SELECTFY (YDGEOMETRY, KACTION, YLGPBUF, YDFLDGP, KINDSEL, LDFTL)

IF (LHOOK) CALL DR_HOOK('IOGRID_MOD:IOGRID_SELECTFX',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRID_SELECTFX

SUBROUTINE IOGRID_SELECTFY (YDGEOMETRY, KACTION, YDGPBUF, YDFLDGP, KINDSEL, LDFTL)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMLUN   , ONLY : NULOUT
USE IOFLDPTR_MOD,  ONLY : IOFLDPTR
USE IOMULTIBUF_MOD, ONLY : IOMULTIBUF,          &
                         & IOMULTIBUF_SIZE_IDX, &
                         & IOMULTIBUF_COMP_IDX


IMPLICIT NONE

TYPE (GEOMETRY),               INTENT (IN)            :: YDGEOMETRY
INTEGER (KIND=JPIM),           INTENT (IN)            :: KACTION
TYPE (IOMULTIBUF),             INTENT (INOUT)         :: YDGPBUF (:)
TYPE (IOFLDPTR),               INTENT (INOUT), TARGET :: YDFLDGP (:) 
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN),    TARGET :: KINDSEL (:)
LOGICAL,             OPTIONAL, INTENT (IN)            :: LDFTL

#include "abor1.intfb.h"

INTEGER(KIND=JPIM) :: INFLD, JFLD, JROF, IBLO, II, IGLG
INTEGER(KIND=JPIM) :: IGPBUFY, JGPBUFY
INTEGER(KIND=JPIM), ALLOCATABLE :: IGPBUFY_IDX (:), JGPBUFY_IDX (:) 
INTEGER(KIND=JPIM), POINTER :: IINDSEL (:)
INTEGER(KIND=JPIM) :: IBLO_G (YDGEOMETRY%YRGEM%NGPTOT), JROF_G (YDGEOMETRY%YRGEM%NGPTOT) 
LOGICAL            :: LLFTL

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRID_MOD:IOGRID_SELECTFY',0,ZHOOK_HANDLE)

LLFTL = .TRUE.
IF (PRESENT (LDFTL)) LLFTL = LDFTL

CALL IOMULTIBUF_SIZE_IDX (YDGPBUF, INFLD)
ALLOCATE (IGPBUFY_IDX (INFLD), JGPBUFY_IDX (INFLD))
CALL IOMULTIBUF_COMP_IDX (YDGPBUF, IGPBUFY_IDX, JGPBUFY_IDX)

CALL INI_INDSEL (YDGEOMETRY, IINDSEL, IBLO_G, JROF_G, KINDSEL)


DO JFLD = 1, SIZE (YDFLDGP)

  IF (JFLD > UBOUND (IGPBUFY_IDX,1)) &
   & CALL ABOR1 ('IOGRID_MOD:IOGRID_SELECTFY: INPUT BUFFER TOO SMALL')

  IGPBUFY = IGPBUFY_IDX (JFLD)
  JGPBUFY = JGPBUFY_IDX (JFLD)

  IF (YDFLDGP (JFLD)%LSKIPF) CYCLE

  IF (.NOT. ASSOCIATED (YDFLDGP (JFLD)%ZFLDGP)) THEN
    IF (LLFTL) THEN
      WRITE (NULOUT, *) YDFLDGP (JFLD)%YFLDDSC%CPREF, YDFLDGP (JFLD)%YFLDDSC%ILEVG, YDFLDGP (JFLD)%YFLDDSC%CSUFF
      CALL ABOR1 ('IOGRID_MOD:IOGRID_SELECTFY: ZFLDGP IS NOT ASSOCIATED')
    ELSE
      CYCLE
    ENDIF
  ENDIF

  SELECT CASE (KACTION) 

    CASE (NIOGRIDCT_WRITE)

      IF (YDFLDGP (JFLD)%LDRDGP) THEN
        DO II = 1, SIZE (IINDSEL)
          IGLG = IINDSEL (II); IBLO = IBLO_G (IGLG); JROF = JROF_G (IGLG)
          YDGPBUF (IGPBUFY)%P (II,JGPBUFY) =   &
          & YDFLDGP (JFLD)%ZFLDGP (JROF, IBLO) &
          & * YDGEOMETRY%YRGSGEOM_NB%GM (IGLG)
        ENDDO
      ELSE
        DO II = 1, SIZE (IINDSEL)
          IGLG = IINDSEL (II); IBLO = IBLO_G (IGLG); JROF = JROF_G (IGLG)
          YDGPBUF (IGPBUFY)%P (II,JGPBUFY) =   &
          & YDFLDGP (JFLD)%ZFLDGP (JROF, IBLO)
        ENDDO
      ENDIF

    CASE (NIOGRIDCT_READ)

      IF (YDFLDGP (JFLD)%LDRDGP) THEN
        DO II = 1, SIZE (IINDSEL)
          IGLG = IINDSEL (II); IBLO = IBLO_G (IGLG); JROF = JROF_G (IGLG)
          YDFLDGP (JFLD)%ZFLDGP (JROF, IBLO) = &
          & YDGPBUF (IGPBUFY)%P (II,JGPBUFY)   &
          & / YDGEOMETRY%YRGSGEOM_NB%GM (IGLG)
        ENDDO
      ELSE
        DO II = 1, SIZE (IINDSEL)
          IGLG = IINDSEL (II); IBLO = IBLO_G (IGLG); JROF = JROF_G (IGLG)
          YDFLDGP (JFLD)%ZFLDGP (JROF, IBLO) = &
          & YDGPBUF (IGPBUFY)%P (II,JGPBUFY)
        ENDDO
      ENDIF

    CASE DEFAULT

      CALL ABOR1 ('IOGRID_MOD:IOGRID_SELECTFY: UNEXPECTED KACTION')

  END SELECT


ENDDO

CALL DEL_INDSEL (IINDSEL, KINDSEL)

IF (LHOOK) CALL DR_HOOK ('IOGRID_MOD:IOGRID_SELECTFY',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRID_SELECTFY

END MODULE IOGRID_MOD

