! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOGRIDUE_MOD

USE PARKIND1, ONLY : JPIM, JPRB, JPRD
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE IOFLDDESC_MOD, ONLY : IOFLDDESC

USE IOMULTIBUF_MOD, ONLY : IOMULTIBUF,&
                         & IOMULTIBUF_SIZE_IDX,&
                         & IOMULTIBUF_COMP_IDX

USE YOECLDP , ONLY : TECLDP
USE YOMGEM   , ONLY : TGEM
USE YOMFP4L  , ONLY : TRQFP

IMPLICIT NONE

INTERFACE IOGRIDUE_ML_SELECTF
  MODULE PROCEDURE IOGRIDUE_ML_SELECTFX, IOGRIDUE_ML_SELECTFY
END INTERFACE IOGRIDUE_ML_SELECTF

PRIVATE :: IOGRIDUE_ML_SELECTFX, IOGRIDUE_ML_SELECTFY

INTERFACE IOGRIDUE_PL_SELECTF
  MODULE PROCEDURE IOGRIDUE_PL_SELECTFX, IOGRIDUE_PL_SELECTFY
END INTERFACE IOGRIDUE_PL_SELECTF

PRIVATE :: IOGRIDUE_PL_SELECTFX, IOGRIDUE_PL_SELECTFY

CONTAINS

SUBROUTINE IOGRIDUE_ML_COUNT(YDRQGP,YDGEM,YDECLDP,KFPRGPL,KFPROMA,KFNUM)

TYPE (TRQFP)       , INTENT (IN)              :: YDRQGP
TYPE(TGEM) , INTENT(IN) :: YDGEM
TYPE(TECLDP),INTENT(IN):: YDECLDP
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPROMA
INTEGER (KIND=JPIM), INTENT (INOUT) :: KFNUM

INTEGER (KIND=JPIM) :: IFCUR

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_ML_COUNT',0,ZHOOK_HANDLE)

IFCUR = 0
CALL IOGRIDUE_ML_SELECT_WH(YDRQGP,YDGEM,YDECLDP,KFPRGPL,KFPROMA,KFCUR=IFCUR)
KFNUM = KFNUM + IFCUR

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_ML_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUE_ML_COUNT

SUBROUTINE IOGRIDUE_ML_SELECTD(YDRQGP,YDGEM,YDECLDP,KFPRGPL,KFPROMA,YDFLDSC,KFCUR)

TYPE (TRQFP)       , INTENT (IN)              :: YDRQGP
TYPE(TGEM) , INTENT(IN) :: YDGEM
TYPE(TECLDP),INTENT(IN):: YDECLDP
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPROMA
TYPE (IOFLDDESC),    INTENT (INOUT)           :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_ML_SELECTD',0,ZHOOK_HANDLE)

CALL IOGRIDUE_ML_SELECT_WH(YDRQGP,YDGEM,YDECLDP,KFPRGPL,KFPROMA,YDFLDSC=YDFLDSC,KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_ML_SELECTD',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUE_ML_SELECTD

SUBROUTINE IOGRIDUE_ML_SELECTFX(YDRQGP,YDGEM,YDECLDP,KFPRGPL,KFPROMA,PREAL,PFPBUF,YDFLDSC,KFCUR)

TYPE (TRQFP)       , INTENT (IN)              :: YDRQGP
TYPE(TGEM)         , INTENT (IN)              :: YDGEM
TYPE(TECLDP)        ,INTENT(IN)            :: YDECLDP
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPROMA
REAL (KIND=JPRB)   , INTENT (INOUT), TARGET   :: PREAL (:,:)
REAL (KIND=JPRB)   , INTENT (IN)              :: PFPBUF(:,:,:)
TYPE (IOFLDDESC)   , INTENT (INOUT)           :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR

TYPE (IOMULTIBUF) :: YLGPBUF (1)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_ML_SELECTFX',0,ZHOOK_HANDLE)

YLGPBUF (1)%P => PREAL

CALL IOGRIDUE_ML_SELECT_WH(YDRQGP,YDGEM,YDECLDP,KFPRGPL,KFPROMA,YDGPBUF=YLGPBUF,YDFLDSC=YDFLDSC,KFCUR=KFCUR,LDCHECKCD=.TRUE., &
 & PFPBUF=PFPBUF)

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_ML_SELECTFX',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUE_ML_SELECTFX

SUBROUTINE IOGRIDUE_ML_SELECTFY(YDRQGP,YDGEM,YDECLDP,KFPRGPL,KFPROMA,YDGPBUF,PFPBUF,YDFLDSC,KFCUR)

TYPE (TRQFP)       , INTENT (IN)              :: YDRQGP
TYPE(TGEM)         , INTENT (IN)              :: YDGEM
TYPE(TECLDP)        ,INTENT(IN)            :: YDECLDP
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPROMA
TYPE (IOMULTIBUF)  , INTENT (INOUT)           :: YDGPBUF (:)
REAL (KIND=JPRB)   , INTENT (IN)              :: PFPBUF(:,:,:)
TYPE (IOFLDDESC)   , INTENT (INOUT)           :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_ML_SELECTFY',0,ZHOOK_HANDLE)

CALL IOGRIDUE_ML_SELECT_WH(YDRQGP,YDGEM,YDECLDP,KFPRGPL,KFPROMA,YDGPBUF=YDGPBUF,YDFLDSC=YDFLDSC,KFCUR=KFCUR,LDCHECKCD=.TRUE., &
 & PFPBUF=PFPBUF)

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_ML_SELECTFY',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUE_ML_SELECTFY

SUBROUTINE IOGRIDUE_ML_SELECT_WH(YDRQGP,YDGEM,YDECLDP,KFPRGPL,KFPROMA,YDGPBUF,YDFLDSC,KFCUR,LDCHECKCD,PFPBUF)

USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULOUT
USE YOM_GRIB_CODES  , ONLY : NGRBCC, NGRBCLWC, NGRBCIWC

IMPLICIT NONE

TYPE (TRQFP)       , INTENT (IN)                      :: YDRQGP
TYPE(TGEM)         , INTENT (IN)                      :: YDGEM
TYPE(TECLDP)       , INTENT (IN)                      :: YDECLDP
INTEGER (KIND=JPIM), INTENT (IN)                      :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)                      :: KFPROMA
TYPE (IOMULTIBUF)  , INTENT (INOUT), OPTIONAL         :: YDGPBUF (:)
TYPE (IOFLDDESC)   , INTENT (INOUT), OPTIONAL, TARGET :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL         :: KFCUR
LOGICAL,             INTENT (IN),    OPTIONAL         :: LDCHECKCD
REAL(KIND=JPRB)    , INTENT (IN),    OPTIONAL         :: PFPBUF(:,:,:)

INTEGER(KIND=JPIM), EXTERNAL :: ISRCHEQ
#include "fcttim.func.h"
#include "abor1.intfb.h"


REAL(KIND=JPRB), POINTER :: ZREAL(:)

INTEGER(KIND=JPIM) :: IFLDPTU (YDRQGP%NFIELDG), IGRIBU (YDRQGP%NFIELDG), ILEVELU (YDRQGP%NFIELDG), ISKIPU (YDRQGP%NFIELDG)

INTEGER(KIND=JPIM) :: IEND, IFLD, IGRIBCD, II,&
 & ILEVEL, JKGLO, IST, IFF, IZZ, J, JF, JFLD

LOGICAL :: LLUPPER

REAL(KIND=JPRB) :: ZSCALE, ZZSCALE
LOGICAL :: LLCOPYF, LLCOPYD, LLCHECKCD
INTEGER (KIND=JPIM) :: IGPBUFY, JGPBUFY
INTEGER (KIND=JPIM), ALLOCATABLE :: IGPBUFY_IDX (:), JGPBUFY_IDX (:)
INTEGER (KIND=JPIM) :: INFLD, IFCUR
TYPE (IOFLDDESC), POINTER :: YLFLDSC (:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDUE_MOD:IOGRIDUE_ML_SELECT_WH',0,ZHOOK_HANDLE)
ASSOCIATE(NFIELDG=>YDRQGP%NFIELDG, ICOD=>YDRQGP%ICOD, LLSURF=>YDRQGP%LLSURF, IGRIB=>YDRQGP%IGRIB, &
 & ZLEV=>YDRQGP%ZLEV)
! & ZLEV=>YDRQGP%ZLEV, MFP3DFS=>YDFPFIELDS%MFP3DFS, NFP3DFS=>YDFPFIELDS%NFP3DFS)
LLCOPYF = PRESENT (YDGPBUF) .AND. PRESENT(PFPBUF)
LLCOPYD = PRESENT (YDFLDSC)

IFCUR = 0
IF (PRESENT (KFCUR)) IFCUR = KFCUR

IF (LLCOPYF) THEN
  CALL IOMULTIBUF_SIZE_IDX (YDGPBUF, INFLD)
  ALLOCATE (IGPBUFY_IDX (INFLD), JGPBUFY_IDX (INFLD))
  CALL IOMULTIBUF_COMP_IDX (YDGPBUF, IGPBUFY_IDX, JGPBUFY_IDX)
ENDIF

YLFLDSC => NULL ()
IF (LLCOPYD) THEN
  YLFLDSC => YDFLDSC (IFCUR+1:)
ENDIF

LLCHECKCD = .FALSE.
IF (PRESENT (LDCHECKCD)) LLCHECKCD = LDCHECKCD

ZREAL => NULL ()
IF (LLCOPYD .AND. (.NOT. LLCHECKCD)) THEN
  YLFLDSC%CPREF  = 'm'
  YLFLDSC%ILEVG  = 0
  YLFLDSC%NFLSZ  = YDGEM%NGPTOTG
ENDIF

IFF = 0

  IFF = 0

  DO JFLD = 1, NFIELDG

    IFLD=ICOD(JFLD)
    LLUPPER=.NOT.LLSURF(JFLD)
    ILEVELU(JFLD)=NINT(ZLEV(JFLD))
    IGRIBU (JFLD) = IGRIB(JFLD)
    IFLDPTU(JFLD) = JFLD

    IGRIBCD=IGRIBU(JFLD)

    IF( LLUPPER ) THEN
      IF(.FALSE.) THEN
      !IF((NFP3DFS /= 0 .AND. ISRCHEQ(NFP3DFS,MFP3DFS,1,IGRIBCD) > NFP3DFS)) THEN
        IF (LLCOPYF)&
         & WRITE(NULOUT,'(A,I3.3)') ' FIELD IN BUFFER BUT PP NOT REQUESTED ...',IGRIBCD  
        ISKIPU(JFLD) = 1
      ELSE
        IFF = IFF+1
        ISKIPU (JFLD) = 0
      ENDIF
    ELSE
      IF(.FALSE.) THEN
      !IF(QFPTYPE%ISF(IFLD)>=1) THEN
        IF (LLCOPYF)&
         & WRITE(NULOUT,'(A,I3.3)') ' FIELD CONSIDERED SPECTRAL ONLY ... SKIPPED PAR=',IGRIBCD  
        ISKIPU(JFLD) = 1
      ELSE
        IFF = IFF+1
        ISKIPU(JFLD) = 0
      ENDIF
    ENDIF

  ENDDO

  IFF = 0

  DO JF=1, NFIELDG

    IGRIBCD = IGRIBU(JF)
    ILEVEL  = ILEVELU(JF)

    IF (ISKIPU(JF) /= 1) THEN

      IFF = IFF + 1
 
      IF (LLCOPYD) THEN
        IF (LLCHECKCD) THEN
          IF ((YDFLDSC (IFF)%IGRIB /= IGRIBCD) .OR. (YDFLDSC (IFF)%ILEVG /= ILEVEL))&
            & CALL ABOR1 ('IOGRIDUE_MOD:IOGRIDUE_ML_SELECT_WH: FIELD MISMATCH')
        ELSE
          YDFLDSC (IFF)%IGRIB = IGRIBCD
          YDFLDSC (IFF)%ILEVG = ILEVEL
        ENDIF
      ENDIF

      IF (LLCOPYF) THEN

        IGPBUFY = IGPBUFY_IDX (IFCUR+IFF)
        JGPBUFY = JGPBUFY_IDX (IFCUR+IFF)

        ZREAL => YDGPBUF (IGPBUFY)%P (:,JGPBUFY)    

        DO JKGLO=1,KFPRGPL,KFPROMA
          II=(JKGLO-1)/KFPROMA+1
          IST=1
          IEND=MIN(KFPROMA,KFPRGPL-JKGLO+1)
          DO J=IST,IEND
            ZREAL(J+JKGLO-1) = PFPBUF(J,IFLDPTU(JF),II)
          ENDDO
        ENDDO
 
        IF(IGRIBCD == NGRBCC) THEN
          ZSCALE = YDECLDP%RAMIN
        ELSEIF(IGRIBCD == NGRBCLWC) THEN
          ZSCALE = YDECLDP%RLMIN
        ELSEIF(IGRIBCD == NGRBCIWC) THEN
          ZSCALE = YDECLDP%RLMIN
        ELSE
          ZSCALE = 1.0_JPRB
        ENDIF
        IF(ZSCALE /= 1.0_JPRB) THEN
          ZZSCALE = 1.0_JPRB/ZSCALE
          DO J=1,KFPRGPL
            IZZ = ZREAL(J)*ZZSCALE
            ZREAL(J) = IZZ*ZSCALE
          ENDDO
        ENDIF

      ENDIF

    ENDIF
  ENDDO

IF (PRESENT (KFCUR)) KFCUR = KFCUR + IFF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('IOGRIDUE_MOD:IOGRIDUE_ML_SELECT_WH',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUE_ML_SELECT_WH

SUBROUTINE IOGRIDUE_PL_COUNT(YDRQGP,YDGEM,KFPRGPL,KFPROMA,KFNUM,CDPREF)

TYPE (TRQFP)       , INTENT (IN)            :: YDRQGP
TYPE(TGEM)         , INTENT (IN)            :: YDGEM
INTEGER (KIND=JPIM), INTENT (IN)            :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)            :: KFPROMA
INTEGER (KIND=JPIM), INTENT (INOUT)         :: KFNUM
CHARACTER(LEN=1)   , INTENT (IN),  OPTIONAL :: CDPREF

INTEGER (KIND=JPIM) :: IFCUR

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_PL_COUNT',0,ZHOOK_HANDLE)

IFCUR = 0
CALL IOGRIDUE_PL_SELECT_WH(YDRQGP,YDGEM,KFPRGPL,KFPROMA,KFCUR=IFCUR,CDPREF=CDPREF)
KFNUM = KFNUM + IFCUR

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_PL_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUE_PL_COUNT

SUBROUTINE IOGRIDUE_PL_SELECTD(YDRQGP,YDGEM,KFPRGPL,KFPROMA,YDFLDSC, KFCUR,CDPREF)

TYPE (TRQFP)       , INTENT (IN)              :: YDRQGP
TYPE(TGEM)         , INTENT (IN)              :: YDGEM
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPROMA
TYPE (IOFLDDESC)   , INTENT (INOUT)           :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
CHARACTER(LEN=1)   , INTENT (IN),    OPTIONAL :: CDPREF

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_PL_SELECTD',0,ZHOOK_HANDLE)

CALL IOGRIDUE_PL_SELECT_WH(YDRQGP,YDGEM,KFPRGPL,KFPROMA,YDFLDSC=YDFLDSC, KFCUR=KFCUR,CDPREF=CDPREF)

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_PL_SELECTD',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUE_PL_SELECTD

SUBROUTINE IOGRIDUE_PL_SELECTFX(YDRQGP, YDGEM, KFPRGPL,KFPROMA, PREAL, YDFLDSC, PFPBUF, KFCUR,CDPREF)

TYPE (TRQFP)       , INTENT (IN)              :: YDRQGP
TYPE(TGEM)         , INTENT (IN)              :: YDGEM
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPROMA
REAL (KIND=JPRB)   , INTENT (INOUT), TARGET   :: PREAL (:,:)
TYPE (IOFLDDESC)   , INTENT (INOUT)           :: YDFLDSC (:) 
REAL (KIND=JPRB)   , INTENT (IN)              :: PFPBUF(:,:,:)
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
CHARACTER(LEN=1)   , INTENT (IN),    OPTIONAL :: CDPREF

TYPE (IOMULTIBUF) :: YLGPBUF (1)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_PL_SELECTFX',0,ZHOOK_HANDLE)

YLGPBUF (1)%P => PREAL

CALL IOGRIDUE_PL_SELECT_WH(YDRQGP,YDGEM,KFPRGPL,KFPROMA,YDGPBUF=YLGPBUF, YDFLDSC=YDFLDSC,&
                          & KFCUR=KFCUR, LDCHECKCD=.TRUE.,CDPREF=CDPREF,PFPBUF=PFPBUF)

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_PL_SELECTFX',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUE_PL_SELECTFX

SUBROUTINE IOGRIDUE_PL_SELECTFY(YDRQGP,YDGEM,KFPRGPL,KFPROMA,YDGPBUF, YDFLDSC, PFPBUF, KFCUR,CDPREF)

TYPE (TRQFP)       , INTENT (IN)              :: YDRQGP
TYPE(TGEM)         , INTENT (IN)              :: YDGEM
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)              :: KFPROMA
TYPE (IOMULTIBUF)  , INTENT (INOUT)           :: YDGPBUF (:)
TYPE (IOFLDDESC)   , INTENT (INOUT)           :: YDFLDSC (:) 
REAL (KIND=JPRB)   , INTENT (IN)              :: PFPBUF(:,:,:)
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR
CHARACTER(LEN=1)   , INTENT (IN),    OPTIONAL :: CDPREF

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_PL_SELECTFY',0,ZHOOK_HANDLE)

CALL IOGRIDUE_PL_SELECT_WH(YDRQGP,YDGEM,KFPRGPL,KFPROMA,YDGPBUF=YDGPBUF, YDFLDSC=YDFLDSC,&
                          & KFCUR=KFCUR, LDCHECKCD=.TRUE.,CDPREF=CDPREF,PFPBUF=PFPBUF)

IF (LHOOK) CALL DR_HOOK ('IOGRIDUE_MOD:IOGRIDUE_PL_SELECTFY',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUE_PL_SELECTFY

SUBROUTINE IOGRIDUE_PL_SELECT_WH(YDRQGP,YDGEM, KFPRGPL, KFPROMA, YDGPBUF, YDFLDSC, KFCUR, LDCHECKCD,CDPREF,PFPBUF)

USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMLUN   , ONLY : NULOUT
USE YOM_GRIB_CODES, ONLY : NGRBZ, NGRBSP, NGRBMSL, NGRBLNSP   

IMPLICIT NONE

TYPE (TRQFP)       , INTENT (IN)                      :: YDRQGP
TYPE(TGEM)         , INTENT (IN)                      :: YDGEM
INTEGER (KIND=JPIM), INTENT (IN)                      :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)                      :: KFPROMA
TYPE (IOMULTIBUF)  , INTENT (INOUT), OPTIONAL         :: YDGPBUF (:)
TYPE (IOFLDDESC)   , INTENT (INOUT), OPTIONAL, TARGET :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL         :: KFCUR
LOGICAL            , INTENT (IN),    OPTIONAL         :: LDCHECKCD
CHARACTER(LEN=1)   , INTENT (IN),    OPTIONAL         :: CDPREF
REAL(KIND=JPRB)    , INTENT (IN),    OPTIONAL         :: PFPBUF(:,:,:)

INTEGER(KIND=JPIM), EXTERNAL :: ISRCHEQ
#include "fcttim.func.h"
#include "abor1.intfb.h"


REAL(KIND=JPRB), POINTER :: ZREAL(:)

INTEGER(KIND=JPIM) :: IFLDPTU (YDRQGP%NFIELDG), IGRIBU (YDRQGP%NFIELDG), ILEVELU (YDRQGP%NFIELDG), ISKIPU (YDRQGP%NFIELDG)

INTEGER(KIND=JPIM) :: IEND, IFLD, IGRIBCD, II,&
 & ILEVEL, JKGLO, IST, IFF, IZZ, J, JF, JFLD

LOGICAL :: LLUPPER

LOGICAL :: LLCOPYF, LLCOPYD, LLCHECKCD
INTEGER (KIND=JPIM) :: IGPBUFY, JGPBUFY
INTEGER (KIND=JPIM), ALLOCATABLE :: IGPBUFY_IDX (:), JGPBUFY_IDX (:)
INTEGER (KIND=JPIM) :: INFLD, IFCUR
TYPE (IOFLDDESC), POINTER :: YLFLDSC (:)
CHARACTER(LEN=1) :: CLPREF

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOGRIDUE_MOD:IOGRIDUE_PL_SELECT_WH',0,ZHOOK_HANDLE)
ASSOCIATE(NFIELDG=>YDRQGP%NFIELDG, ICOD=>YDRQGP%ICOD, LLSURF=>YDRQGP%LLSURF, IGRIB=>YDRQGP%IGRIB, &
 & ZLEV=>YDRQGP%ZLEV)

LLCOPYF = PRESENT (YDGPBUF) .AND. PRESENT(PFPBUF)
LLCOPYD = PRESENT (YDFLDSC)

IFCUR = 0
IF (PRESENT (KFCUR)) IFCUR = KFCUR
CLPREF = 'p'
IF(PRESENT(CDPREF)) CLPREF = CDPREF

IF (LLCOPYF) THEN
  CALL IOMULTIBUF_SIZE_IDX (YDGPBUF, INFLD)
  ALLOCATE (IGPBUFY_IDX (INFLD), JGPBUFY_IDX (INFLD))
  CALL IOMULTIBUF_COMP_IDX (YDGPBUF, IGPBUFY_IDX, JGPBUFY_IDX)
ENDIF

YLFLDSC => NULL ()
IF (LLCOPYD) THEN
  YLFLDSC => YDFLDSC (IFCUR+1:)
ENDIF

LLCHECKCD = .FALSE.
IF (PRESENT (LDCHECKCD)) LLCHECKCD = LDCHECKCD

ZREAL => NULL ()
IF (LLCOPYD .AND. (.NOT. LLCHECKCD)) THEN
  YLFLDSC%CPREF  = CLPREF
  YLFLDSC%ILEVG  = 0
  YLFLDSC%NFLSZ  = YDGEM%NGPTOTG
ENDIF


  IFF = 0

  DO JFLD = 1, NFIELDG

    IFLD=ICOD(JFLD)
    LLUPPER=.NOT.LLSURF(JFLD)
    IF(CLPREF == 'v') THEN
      ILEVELU(JFLD)=NINT(ZLEV(JFLD)*1.E+09_JPRB)
    ELSE
      ILEVELU(JFLD)=NINT(ZLEV(JFLD))
    ENDIF
    IGRIBU (JFLD) = IGRIB(JFLD)
    IFLDPTU(JFLD) = JFLD

    IGRIBCD=IGRIBU(JFLD)

    IF( LLUPPER ) THEN
        IFF = IFF+1
        ISKIPU (JFLD) = 0
    ELSE
      IF( (IGRIBCD == NGRBLNSP).OR.(IGRIBCD == NGRBSP).OR.&
         & (IGRIBCD == NGRBZ).OR.(IGRIBCD == NGRBMSL) ) THEN  
        IF (LLCOPYF)&
         & WRITE(NULOUT,'(A,I3.3)') ' FIELD CONSIDERED SPECTRAL ONLY ... SKIPPED PAR=',IGRIBCD  
        ISKIPU(JFLD) = 1
      ELSE
        IFF = IFF+1
        ISKIPU(JFLD) = 0
      ENDIF
    ENDIF

  ENDDO

  IFF = 0

  DO JF=1, NFIELDG

    IGRIBCD = IGRIBU(JF)
    ILEVEL  = ILEVELU(JF)

    IF (ISKIPU(JF) /= 1) THEN

      IFF = IFF + 1
 
      IF (LLCOPYD) THEN
        IF (LLCHECKCD) THEN
          IF ((YDFLDSC (IFF)%IGRIB /= IGRIBCD) .OR. (YDFLDSC (IFF)%ILEVG /= ILEVEL))&
            & CALL ABOR1 ('IOGRIDUE_MOD:IOGRIDUE_PL_SELECT_WH: FIELD MISMATCH')
        ELSE
          YDFLDSC (IFF)%IGRIB = IGRIBCD
          YDFLDSC (IFF)%ILEVG = ILEVEL
        ENDIF
      ENDIF

      IF (LLCOPYF) THEN

        IGPBUFY = IGPBUFY_IDX (IFCUR+IFF)
        JGPBUFY = JGPBUFY_IDX (IFCUR+IFF)

        ZREAL => YDGPBUF (IGPBUFY)%P (:,JGPBUFY)    

        DO JKGLO=1,KFPRGPL,KFPROMA
          II=(JKGLO-1)/KFPROMA+1
          IST=1
          IEND=MIN(KFPROMA,KFPRGPL-JKGLO+1)
          DO J=IST,IEND
            ZREAL(J+JKGLO-1) = PFPBUF(J,IFLDPTU(JF),II)
          ENDDO
        ENDDO
 
      ENDIF

    ENDIF
  ENDDO

IF (PRESENT (KFCUR)) KFCUR = KFCUR + IFF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('IOGRIDUE_MOD:IOGRIDUE_PL_SELECT_WH',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDUE_PL_SELECT_WH

END MODULE IOGRIDUE_MOD

