! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOGRIDE_MOD

!**** *IOGRIDE_MOD*  Module for ECMWF Fullpos output selection.

! Author.
! -------
!  01/12/2014 : P.Marguinaud - From IOGRIDA_MOD

! Modifications
! M.Hamrud : Jan 2015 : Added lagged p.p. etc.
! End Modifications
! ---------------------------------------------------------------------

USE PARKIND1, ONLY : JPRB, JPIM, JPRD
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE IOMULTIBUF_MOD, ONLY : IOMULTIBUF,&
                         & IOMULTIBUF_SIZE_IDX,&
                         & IOMULTIBUF_COMP_IDX

USE IOFLDDESC_MOD, ONLY : IOFLDDESC

USE YOMFP4L, ONLY : TRQFP

IMPLICIT NONE

INTERFACE IOGRIDE_SELECTF
  MODULE PROCEDURE IOGRIDE_SELECTFX, IOGRIDE_SELECTFY
END INTERFACE IOGRIDE_SELECTF

PRIVATE :: IOGRIDE_SELECTFX, IOGRIDE_SELECTFY

CONTAINS
!=======================================================================================
SUBROUTINE IOGRIDE_SELECTFY(YDGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,YDGPBUF,PFPBUF,YDFLDSC,KFCUR)

USE YOEPHY , ONLY : TEPHY
USE YOMGEM , ONLY : TGEM
TYPE(TGEM) , INTENT(IN) :: YDGEM
TYPE(TEPHY) ,INTENT(IN):: YDEPHY
TYPE (TRQFP), INTENT(IN) :: YDRQPHY
INTEGER (KIND=JPIM), INTENT (IN)                   :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)                   :: KFPROMA
TYPE (IOMULTIBUF),   INTENT (INOUT)           :: YDGPBUF (:)
REAL (KIND=JPRB),    INTENT (IN)                   :: PFPBUF(:,:,:)
TYPE (IOFLDDESC),    INTENT (INOUT), OPTIONAL :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:IOGRIDE_SELECTFY',0,ZHOOK_HANDLE)

CALL IOGRIDE_SELECT_WH(YDGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,YDGPBUF=YDGPBUF,YDFLDSC=YDFLDSC,KFCUR=KFCUR,LDCHECKCD=.TRUE.,&
 & PFPBUF=PFPBUF)

IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:IOGRIDE_SELECTFY',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDE_SELECTFY
!=======================================================================================
SUBROUTINE IOGRIDE_SELECTFX(YDGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,PREAL,PFPBUF,YDFLDSC,KFCUR)

USE YOEPHY , ONLY : TEPHY
USE YOMGEM , ONLY : TGEM
TYPE(TGEM) , INTENT(IN) :: YDGEM
TYPE(TEPHY) ,INTENT(IN):: YDEPHY
TYPE (TRQFP), INTENT(IN) :: YDRQPHY
INTEGER (KIND=JPIM), INTENT (IN)                   :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)                   :: KFPROMA
REAL (KIND=JPRB),    INTENT (INOUT), TARGET   :: PREAL (:,:)
REAL (KIND=JPRB),    INTENT (IN)                   :: PFPBUF(:,:,:)
TYPE (IOFLDDESC),    INTENT (INOUT), OPTIONAL :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR

TYPE (IOMULTIBUF) :: YLGPBUF (1)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:IOGRIDE_SELECTFX',0,ZHOOK_HANDLE)

YLGPBUF (1)%P => PREAL

CALL IOGRIDE_SELECT_WH(YDGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,YDGPBUF=YLGPBUF,YDFLDSC=YDFLDSC,KFCUR=KFCUR, &
 & LDCHECKCD=.TRUE.,PFPBUF=PFPBUF)

IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:IOGRIDE_SELECTFX',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDE_SELECTFX
!=======================================================================================

SUBROUTINE IOGRIDE_COUNT(YDGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,KFNUM)

USE YOEPHY , ONLY : TEPHY
USE YOMGEM , ONLY : TGEM
TYPE(TGEM) , INTENT(IN) :: YDGEM
TYPE(TEPHY) ,INTENT(IN):: YDEPHY
TYPE (TRQFP), INTENT(IN) :: YDRQPHY
INTEGER (KIND=JPIM), INTENT (IN)                   :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)                   :: KFPROMA
INTEGER (KIND=JPIM), INTENT (INOUT) :: KFNUM

INTEGER (KIND=JPIM) :: IFCUR

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:IOGRIDE_COUNT',0,ZHOOK_HANDLE)

IFCUR = 0
CALL IOGRIDE_SELECT_WH(YDGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,KFCUR=IFCUR)
KFNUM = KFNUM + IFCUR

IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:IOGRIDE_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDE_COUNT
!=======================================================================================

SUBROUTINE IOGRIDE_SELECTD(YDGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,YDFLDSC,KFCUR)

USE YOEPHY , ONLY : TEPHY
USE YOMGEM , ONLY : TGEM
TYPE(TGEM)         , INTENT (IN)              :: YDGEM
TYPE(TEPHY)         ,INTENT(IN)            :: YDEPHY
TYPE (TRQFP), INTENT(IN) :: YDRQPHY
INTEGER (KIND=JPIM), INTENT (IN)                   :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)                   :: KFPROMA
TYPE (IOFLDDESC)   , INTENT (INOUT)           :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:IOGRIDE_SELECTD',0,ZHOOK_HANDLE)

CALL IOGRIDE_SELECT_WH(YDGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,YDFLDSC=YDFLDSC,KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:IOGRIDE_SELECTD',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDE_SELECTD
!=======================================================================================

SUBROUTINE IOGRIDE_SELECT_WH(YDGEM,YDEPHY,YDRQPHY,KFPRGPL,KFPROMA,YDGPBUF,YDFLDSC,KFCUR,LDCHECKCD,PFPBUF)

USE YOMGEM   , ONLY : TGEM
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCT0   , ONLY : NCONF    ,LOBSC1 
USE YOEPHY   , ONLY : TEPHY
USE YOMVAR   , ONLY : LTWBGV   ,LTWCGL  
USE YOM_GRIB_CODES , ONLY :&
 & NGRBSD   ,NGRBSDSL ,NGRBWSN, NGRBRSN, NGRBTSN, NGRBLSP  ,NGRBCP   ,NGRBTP   ,&
  & NGRBSF   ,NGRBFZRA ,NGRBSP   ,NGRBSDOR ,&
 & NGRBLSM  ,NGRBSR   ,NGRBE    ,NGRBPEV  ,&
 & NGRBSRC  ,NGRBRO   ,NGRBSSRO ,NGRBSRO  ,&
 & NGRBCSF  ,NGRBLSF  ,NGRBFSR  ,&
 & NGRBCLBT, NGRBCSBT
USE YOMGRIB,ONLY : JPNUMLPP,NSTEPLPP
USE YOMCST   , ONLY : RG
USE YOETHF   , ONLY : RHOH2O

IMPLICIT NONE

TYPE(TGEM)        ,  INTENT (IN)                      :: YDGEM
TYPE(TEPHY)         ,INTENT(IN)                    :: YDEPHY
INTEGER (KIND=JPIM), INTENT (IN)                   :: KFPRGPL
INTEGER (KIND=JPIM), INTENT (IN)                   :: KFPROMA
TYPE (TRQFP)  ,  INTENT (IN)                      :: YDRQPHY
TYPE (IOMULTIBUF) ,  INTENT (INOUT), OPTIONAL         :: YDGPBUF (:)
TYPE (IOFLDDESC)  ,  INTENT (INOUT), OPTIONAL, TARGET :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL         :: KFCUR
LOGICAL,             INTENT (IN),    OPTIONAL         :: LDCHECKCD
REAL (KIND=JPRB),    INTENT (IN),    OPTIONAL         :: PFPBUF(:,:,:)


INTEGER(KIND=JPIM), EXTERNAL :: ISRCHEQ
INTEGER(KIND=JPIM) :: IFLDGB(YDRQPHY%NFIELDG),IFLDPT(YDRQPHY%NFIELDG)
TYPE (IOFLDDESC), POINTER :: YLFLDSC (:)
REAL (KIND=JPRB), POINTER :: ZREAL (:)

INTEGER(KIND=JPIM) :: IEND, IFLD, IGRIBCD, II,&
 & JKGLO, IST, J, JF, JFLD, ILST,ICLBT, ICSBT, ISDML, IRSNML,ITSNML,IWSNML

REAL(KIND=JPRB) :: ZSCALE
LOGICAL :: LLCOPYF, LLCOPYD, LLCHECKCD
INTEGER (KIND=JPIM) :: INFLD, IFCUR
INTEGER (KIND=JPIM) :: IGPBUFY, JGPBUFY
INTEGER (KIND=JPIM), ALLOCATABLE :: IGPBUFY_IDX (:), JGPBUFY_IDX (:)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

#include "fcttim.func.h"
#include "abor1.intfb.h"

IF (LHOOK) CALL DR_HOOK('IOGRIDE_MOD:IOGRIDE_SELECT_WH',0,ZHOOK_HANDLE)
ASSOCIATE(IGRIB=>YDRQPHY%IGRIB, NFIELDG=>YDRQPHY%NFIELDG)
LLCOPYF = PRESENT (YDGPBUF) .AND. PRESENT(PFPBUF)
LLCOPYD = PRESENT (YDFLDSC)

IFCUR = 0
IF (PRESENT (KFCUR)) IFCUR = KFCUR

IF (LLCOPYF) THEN
  CALL IOMULTIBUF_SIZE_IDX (YDGPBUF, INFLD)
  ALLOCATE (IGPBUFY_IDX (INFLD), JGPBUFY_IDX (INFLD))
  CALL IOMULTIBUF_COMP_IDX (YDGPBUF, IGPBUFY_IDX, JGPBUFY_IDX)
ENDIF

YLFLDSC => NULL ()
IF (LLCOPYD) THEN
  YLFLDSC => YDFLDSC (IFCUR+1:)
ENDIF

LLCHECKCD = .FALSE.
IF (PRESENT (LDCHECKCD)) LLCHECKCD = LDCHECKCD

ZREAL => NULL ()
IF (LLCOPYD .AND. (.NOT. LLCHECKCD)) THEN
  YLFLDSC%CPREF  = 's'
  YLFLDSC%ILEVG  = 0
  YLFLDSC%NFLSZ  = YDGEM%NGPTOTG
ENDIF

IF ( (.NOT.(LTWBGV.OR.LTWCGL).AND.&
   & ((YDEPHY%LEPHYS).OR.LOBSC1.OR.NCONF == 131)) ) THEN  

!*       4.1   COPY FROM NPROMA FORMAT TO FIELD FORMAT

  IFLD = 0

! Assign ILEV information to multi layer surface fields
  ICLBT = 0  
  ICSBT = 0  
  ISDML = 0
  IRSNML = 0
  ITSNML = 0
  IWSNML = 0

  DO JFLD = 1, NFIELDG

    IGRIBCD = IGRIB(JFLD)

    ! lagged/non-lagged selection moved up to sufpphy.F90. REK

      IFLD = IFLD + 1

      IF (LLCOPYD) THEN
        IF (LLCHECKCD) THEN
          IF ((YDFLDSC (IFLD)%IGRIB /= IGRIBCD) .OR.&
            & (IGRIBCD /= NGRBCLBT .AND. IGRIBCD /= NGRBCSBT  .AND. &
            & IGRIBCD /= NGRBSD  .AND. IGRIBCD /= NGRBRSN .AND. IGRIBCD /= NGRBTSN .AND. &
            & IGRIBCD /= NGRBWSN .AND. YDFLDSC (IFLD)%ILEVG /= 0)  ) &
            & CALL ABOR1 ('IOGRIDE_MOD:IOGRIDE_SELECT_WH: FIELD MISMATCH')
        ELSE
          YDFLDSC (IFLD)%IGRIB = IGRIBCD
          ILST = ISRCHEQ(JPNUMLPP,NSTEPLPP(:,1),1,IGRIBCD)
          IF(ILST <= JPNUMLPP) THEN
            YDFLDSC (IFLD)%IPREVPP = NSTEPLPP(ILST,2)
          ELSE
            YDFLDSC (IFLD)%IPREVPP = -1
          ENDIF
          IF (IGRIBCD == NGRBCLBT) THEN
            ICLBT = ICLBT + 1
            YDFLDSC (IFLD)%ILEVG = ICLBT
          ENDIF
          IF (IGRIBCD == NGRBCSBT) THEN
            ICSBT = ICSBT + 1
            YDFLDSC (IFLD)%ILEVG = ICSBT
          ENDIF
          IF (IGRIBCD == NGRBSD) THEN
            ISDML = ISDML + 1
            YDFLDSC (IFLD)%ILEVG = ISDML
          ENDIF
          IF (IGRIBCD == NGRBWSN) THEN
            IWSNML = IWSNML + 1
            YDFLDSC (IFLD)%ILEVG = IWSNML
          ENDIF
          IF (IGRIBCD == NGRBRSN) THEN
            YDFLDSC (IFLD)%ILEVG = IRSNML
            IRSNML = IRSNML + 1
          ENDIF
          IF (IGRIBCD == NGRBTSN) THEN
            YDFLDSC (IFLD)%ILEVG = ITSNML
            ITSNML = ITSNML + 1
          ENDIF
        ENDIF
      ENDIF

      IFLDPT(IFLD) = JFLD
      IFLDGB(IFLD) = IGRIBCD

  ENDDO

  IF (LLCOPYF) THEN

    DO JF = 1, IFLD
      IGRIBCD = YDFLDSC (JF)%IGRIB
    
      IGPBUFY = IGPBUFY_IDX (IFCUR+JF)
      JGPBUFY = JGPBUFY_IDX (IFCUR+JF)

      ZREAL => YDGPBUF (IGPBUFY)%P (:,JGPBUFY)    

      DO JKGLO=1,KFPRGPL,KFPROMA
        II=(JKGLO-1)/KFPROMA+1
        IST=1
        IEND=MIN(KFPROMA,KFPRGPL-JKGLO+1)
        DO J=IST,IEND
          ZREAL(J+JKGLO-1) = PFPBUF(J,IFLDPT(JF),II)
        ENDDO
      ENDDO

      IF    (IFLDGB(JF) == NGRBSD  ) THEN
        ZSCALE = 1.0_JPRB !/RHOH2O multi-layer in kg m-2
      ELSEIF    (IFLDGB(JF) == NGRBSDSL  ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBLSP ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBCP  ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBTP  ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBSF  ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBFZRA  ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBSR  ) THEN
        ZSCALE = 1.0_JPRB/RG
      ELSEIF(IFLDGB(JF) == NGRBE   ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBPEV ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBSRC ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBRO  ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBSSRO  ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBSRO  ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBCSF ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBLSF ) THEN
        ZSCALE = 1.0_JPRB/RHOH2O
      ELSEIF(IFLDGB(JF) == NGRBFSR ) THEN
        ZSCALE = 1.0_JPRB/RG
      ELSEIF(IFLDGB(JF) == NGRBSDOR) THEN
        ZSCALE = 1.0_JPRB/RG
      ELSE
        ZSCALE = 1.0_JPRB
      ENDIF
      IF(ZSCALE /= 1.0_JPRB) THEN
        DO J=1,KFPRGPL
          ZREAL(J) = ZREAL(J)*ZSCALE
        ENDDO
      ENDIF
    ENDDO

  ENDIF

ENDIF

IF (PRESENT (KFCUR)) KFCUR = KFCUR + IFLD

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('IOGRIDE_MOD:IOGRIDE_SELECT_WH',1,ZHOOK_HANDLE)

END SUBROUTINE IOGRIDE_SELECT_WH
!=======================================================================================

LOGICAL FUNCTION LAGGED_PP_PAR(YGFL,YDEAERATM,KGRIBCD)
! Purpose : Returns TRUE if KGRIBCD is in "lagged" p.p.
USE YOM_GRIB_CODES , ONLY :&
 & NGRBBV   ,NGRBVIWVE,NGRBVIWVN,&
 & NGRBTCW  ,NGRBTCWV ,NGRBTCLW  ,NGRBTCIW,&
 & NGRBTCRW ,NGRBTCSW ,NGRBTCSLW,&
 & NGRBSD   ,NGRBLSP  ,NGRBCP   ,NGRBTP   ,&
 & NGRBSF   ,NGRBMSL  ,NGRBSP   ,NGRBSLT ,&
 & NGRBSDOR ,NGRBISOR ,NGRBANOR ,NGRBSLOR ,NGRBTCC  ,&
 & NGRB10U  ,NGRB10V  ,NGRB10SI ,NGRB2T   ,NGRB2D   ,NGRB2SH  ,&
 & NGRBLSM  ,NGRBSR   ,NGRBAL   ,NGRBE    ,NGRBPEV  ,&
 & NGRBCCC  ,NGRBLCC  ,NGRBMCC  ,NGRBHCC  ,NGRBSRC  ,&
 & NGRBRO   ,NGRBSSRO   ,NGRBSRO   ,NGRBTCO3 ,&
 & NGRBTCGHG,&
 & NGRBIEWS ,NGRBINSS ,NGRBISHF ,NGRBIE   ,NGRBLSRH ,&
 & NGRBTPR  ,NGRBLSRR ,NGRBCRR  ,NGRBLSSFR,NGRBCSFR,&
 & NGRBPTYPE,NGRBILSPF,NGRBI10FG,&
 & NGRBCSF  ,NGRBLSF  ,NGRBFAL  ,NGRBFSR  ,&
 & NGRBFLSR ,NGRBBLH  ,NGRBCAPE ,NGRBCAPES,NGRBMXCAP6,NGRBMXCAPS6,&
 & NGRBCBASE,NGRB0DEGL,NGRBM10DEGL,NGRBVISIH,NGRBCIN  ,NGRBKINDEX,NGRBTTINDEX,&
 & NGRBCBASEA,NGRBCTOPC,NGRBTROPOTP,NGRBZTWETB0,NGRBZTWETB1,&
 & NGRBCVL  ,NGRBCVH  ,NGRBFWET ,NGRBCUR, NGRBTVL  ,NGRBTVH  ,NGRBSDFOR,&
 & NGRBALUVP,NGRBALUVD,NGRBALNIP,NGRBALNID,&
 & NGRBALUVI,NGRBALUVV,NGRBALUVG,&
 & NGRBALNII,NGRBALNIV,NGRBALNIG,&
 & NGRBAERDEP, NGRBAERLTS, NGRBAERSCC  ,&
 & NGRBAERLS01,NGRBAERLS02,NGRBAERLS03,NGRBAERLS04,NGRBAERLS05,NGRBAERLS06,&
 & NGRBAERLS07,NGRBAERLS08,NGRBAERLS09,NGRBAERLS10,NGRBAERLS11,NGRBAERLS12,&
 & NGRBAERLS13,&
 & NGRBDNDZN, NGRBDNDZA, NGRBDCTB, NGRBTPLB, NGRBTPLT,&
 & NGRBCLBT, NGRBCSBT,&
 & NGRB100U, NGRB100V, NGRB100SI, NGRB200U, NGRB200V,NGRB200SI,&
 & NGRB10NU,NGRB10NV,NGRBZUST,&
 & NGRBINEE ,NGRBIGPP ,NGRBIREC, NGRBCH4WET,&
 & NGRBLITOTI, NGRBLICGI,&
 & NGRBAODPR, NGRBAODSM, NGRBAODLG,&
 & NGRBAEODSS, NGRBAEODDU, NGRBAEODOM, NGRBAEODBC, NGRBAEODSU,&
 & NGRBAEODNI, NGRBAEODAM, NGRBAEODSOA, &
 & NGRBAEODVFA, NGRBAEODVSU,&
 & NGRBAEPM1, NGRBAEPM25, NGRBAEPM10,&
 & NGRBUVBED, NGRBUVBEDCS,&
 & NGRBMUCAPE, NGRBMLCAPE50, NGRBMLCAPE100, NGRBMLCIN50, NGRBMLCIN100, NGRBMUDEPL
USE YOM_YGFL , ONLY : TYPE_GFLD
USE YOEAERATM, ONLY : TEAERATM
USE YOE_AERODIAG, ONLY : NPAERODIAG
IMPLICIT NONE
TYPE(TYPE_GFLD),   INTENT(IN) :: YGFL
TYPE(TEAERATM),    INTENT(IN) :: YDEAERATM
INTEGER(KIND=JPIM),INTENT(IN) :: KGRIBCD
INTEGER(KIND=JPIM) :: JDIAG
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE
!-------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:LAGGED_PP_PAR',0,ZHOOK_HANDLE)

LAGGED_PP_PAR= (KGRIBCD == NGRBTCC  ).OR.(KGRIBCD == NGRB10U  ).OR.&
 & (KGRIBCD == NGRB10V  ).OR.(KGRIBCD == NGRB2T   ).OR.&
 & (KGRIBCD == NGRB2D   ).OR.(KGRIBCD == NGRB2SH  ).OR.&
 & (KGRIBCD == NGRBCCC  ).OR.&
 & (KGRIBCD == NGRBLCC  ).OR.(KGRIBCD == NGRBMCC  ).OR.&
 & (KGRIBCD == NGRBHCC  ).OR.(KGRIBCD == NGRBBLH  ).OR.&
 & (KGRIBCD == NGRBIEWS ).OR.(KGRIBCD == NGRBINSS ).OR.&
 & (KGRIBCD == NGRBISHF ).OR.(KGRIBCD == NGRBIE   ).OR.&
 & (KGRIBCD == NGRBINEE ).OR.(KGRIBCD == NGRBIGPP ).OR.&
 & (KGRIBCD == NGRBIREC ).OR.(KGRIBCD == NGRBCH4WET ).OR.&
 & (KGRIBCD == NGRBBV   ).OR.(KGRIBCD == NGRBFAL  ).OR.&
 & (KGRIBCD == NGRBMSL  ).OR.(KGRIBCD == NGRBSP   ).OR.&
 & (KGRIBCD == NGRBFSR  ).OR.(KGRIBCD == NGRBFLSR ).OR.&
 & (KGRIBCD == NGRBVIWVE).OR.(KGRIBCD == NGRBVIWVN).OR.&
 & (KGRIBCD == NGRBTCW  ).OR.(KGRIBCD == NGRBTCWV ).OR.&
 & (KGRIBCD == NGRBTCLW ).OR.(KGRIBCD == NGRBTCIW ).OR.&
 & (KGRIBCD == NGRBCAPE ).OR.(KGRIBCD == NGRBTCO3 ).OR.&
 & (KGRIBCD == NGRBTCRW ).OR.(KGRIBCD == NGRBTCSW ).OR.&
 & (KGRIBCD == NGRB100U ).OR.(KGRIBCD == NGRB100V ).OR.&
 & (KGRIBCD == NGRB200U ).OR.(KGRIBCD == NGRB200V ).OR.&
 & (KGRIBCD == NGRBTPR  ).OR.&
 & (KGRIBCD == NGRBLSRR ).OR.(KGRIBCD == NGRBCRR  ).OR.&
 & (KGRIBCD == NGRBLSSFR).OR.(KGRIBCD == NGRBCSFR ).OR.&
 & (KGRIBCD == NGRBPTYPE  ).OR.(KGRIBCD == NGRBILSPF   ).OR.&
 & (KGRIBCD == NGRBI10FG  ).OR.(KGRIBCD == NGRBTCSLW   ).OR.&
 & (KGRIBCD == NGRBZUST ).OR.(KGRIBCD == NGRBCBASE).OR.&
 & (KGRIBCD == NGRB0DEGL).OR.(KGRIBCD == NGRBVISIH).OR.&
 & (KGRIBCD == NGRBM10DEGL).OR.&
 & (KGRIBCD == NGRBCIN ).OR. (KGRIBCD == NGRBCAPES).OR.&
 & (KGRIBCD == NGRBMXCAP6 ).OR. (KGRIBCD == NGRBMXCAPS6).OR.&
 & (KGRIBCD == NGRBMUCAPE).OR. (KGRIBCD == NGRBMUDEPL).OR.&
 & (KGRIBCD == NGRBMLCAPE50).OR. (KGRIBCD == NGRBMLCAPE100).OR.&
 & (KGRIBCD == NGRBMLCIN50).OR. (KGRIBCD == NGRBMLCIN100).OR.&
 & (KGRIBCD == NGRBKINDEX).OR.(KGRIBCD== NGRBTTINDEX).OR.&
 & (KGRIBCD == NGRBCBASEA).OR.(KGRIBCD== NGRBCTOPC).OR.&
 & (KGRIBCD == NGRBZTWETB0).OR.(KGRIBCD== NGRBZTWETB1).OR.&
 & (KGRIBCD == NGRB10NU ).OR.(KGRIBCD == NGRB10NV ).OR.&
 & (KGRIBCD == NGRBDNDZN).OR.(KGRIBCD == NGRBDNDZA).OR.&
 & (KGRIBCD == NGRBDCTB ).OR.&
 & (KGRIBCD == NGRBTPLB ).OR.(KGRIBCD == NGRBTPLT ).OR.&
 & (KGRIBCD == NGRBCLBT ).OR.(KGRIBCD == NGRBCSBT ).OR.&
 & (KGRIBCD == NGRB10SI ).OR.(KGRIBCD == NGRB100SI).OR.&
 & (KGRIBCD == NGRB200SI).OR.&
 & ANY(KGRIBCD == NGRBTCGHG(1:YGFL%NGHG)).OR.&
 & ANY(KGRIBCD == YGFL%YCHEM(1:YGFL%NCHEM)%IGRIBTC) .OR.&
 & ANY(KGRIBCD == YGFL%YCHEM(1:YGFL%NCHEM)%IGRBFLXO) .OR.&
 & ANY(KGRIBCD == YGFL%YCHEM(1:YGFL%NCHEM)%IGRBWDFLX) .OR.&
 & ANY(KGRIBCD == YGFL%YCHEM(1:YGFL%NCHEM)%IGRBDDFLX) .OR.&
 & (KGRIBCD == NGRBLITOTI ).OR.(KGRIBCD == NGRBLICGI ) .OR.&
 & (KGRIBCD == NGRBAODPR     ).OR.(KGRIBCD == NGRBAODSM      ) .OR.&
 & (KGRIBCD == NGRBAODLG     ).OR.&
 & (KGRIBCD == NGRBAEODSS    ) .OR.&
 & (KGRIBCD == NGRBAEODDU    ).OR.(KGRIBCD == NGRBAEODOM     ) .OR.&
 & (KGRIBCD == NGRBAEODBC    ).OR.(KGRIBCD == NGRBAEODSU     ) .OR.&
 & (KGRIBCD == NGRBAEODNI    ).OR.(KGRIBCD == NGRBAEODAM     ) .OR.&
 & (KGRIBCD == NGRBAEODSOA   ) .OR.&
 & (KGRIBCD == NGRBAEODVFA   ).OR.(KGRIBCD == NGRBAEODVSU    ) .OR.&
 & (KGRIBCD == NGRBAEPM1     ).OR.(KGRIBCD == NGRBAEPM25     ) .OR.&
 & (KGRIBCD == NGRBAEPM10    ).OR.&
 & (KGRIBCD == NGRBUVBED     ).OR.(KGRIBCD == NGRBUVBEDCS    )

IF (YGFL%NACTAERO > 0) THEN
  DO JDIAG = 1, NPAERODIAG
    LAGGED_PP_PAR = LAGGED_PP_PAR .OR. ANY(KGRIBCD == YDEAERATM%YAERO_DESC(1:YGFL%NACTAERO)%IGRIBDIAG(JDIAG))
  ENDDO
ENDIF

DO JDIAG = 1, YGFL%NAERO_WVL_DIAG_TYPES
  LAGGED_PP_PAR = LAGGED_PP_PAR .OR. ANY(KGRIBCD == YGFL%YAERO_WVL_DIAG_NL(1:YGFL%NAERO_WVL_DIAG)%IGRIBDIAG(JDIAG))
ENDDO

IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:LAGGED_PP_PAR',1,ZHOOK_HANDLE)
END FUNCTION LAGGED_PP_PAR

LOGICAL FUNCTION OCEAN_PP_PAR(KGRIBCD)
! Purpose : Returns TRUE if KGRIBCD is in "ocean" p.p.
USE YOM_GRIB_CODES , ONLY :&
 & NGRBSSTK, NGRBCI, NGRBSSSO, NGRBUCUR, NGRBVCUR,&
 & NGRBICETK,NGRBMLD,NGRBSL,   NGRB20D,  NGRBCHNK,&
 & NGRBTEM300,NGRBSAL300
IMPLICIT NONE
INTEGER(KIND=JPIM),INTENT(IN) :: KGRIBCD
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE
!-------------------------------------------------------------------------
IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:OCEAN_PP_PAR',0,ZHOOK_HANDLE)

OCEAN_PP_PAR= (KGRIBCD == NGRBSSTK ).OR.(KGRIBCD == NGRBCI   ).OR.&
 & (KGRIBCD == NGRBSSSO ).OR.(KGRIBCD == NGRBUCUR ).OR.&
 & (KGRIBCD == NGRBVCUR ).OR.(KGRIBCD == NGRBICETK).OR.&
 & (KGRIBCD == NGRBMLD  ).OR.(KGRIBCD == NGRBSL   ).OR.&
 & (KGRIBCD == NGRB20D  ).OR.(KGRIBCD == NGRBCHNK ).OR.&
 & (KGRIBCD == NGRBTEM300).OR.(KGRIBCD == NGRBSAL300)

IF (LHOOK) CALL DR_HOOK ('IOGRIDE_MOD:OCEAN_PP_PAR',1,ZHOOK_HANDLE)
END FUNCTION OCEAN_PP_PAR

!=======================================================================================

END MODULE IOGRIDE_MOD

