! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOMULTIBUF_MOD

!**** *IOMULTIBUF_MOD*  - Store a list of fields in a list of arrays

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 11-09-2012

!     Modifications :
!     P. Marguinaud : 10-10-2013 : Remove unused variable

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK, ONLY : DR_HOOK, JPHOOK, LHOOK

IMPLICIT NONE

TYPE IOMULTIBUF
! First dimension is field dimension
! Second dimension is field rank
  REAL (KIND=JPRB), POINTER :: P (:,:) => NULL ()
END TYPE

SAVE

CONTAINS

SUBROUTINE IOMULTIBUF_SIZE_IDX (YDPLIST, KFLD)

! Reckon the number of fields

TYPE (IOMULTIBUF),    INTENT (IN)  :: YDPLIST (:)
INTEGER (KIND=JPIM),  INTENT (OUT) :: KFLD

INTEGER (KIND=JPIM) :: I

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOMULTIBUF_MOD:IOMULTIBUF_SIZE_IDX',0,ZHOOK_HANDLE)

KFLD = 0
DO I = 1, SIZE (YDPLIST)
  KFLD = KFLD + SIZE (YDPLIST(I)%P, 2)
ENDDO

IF (LHOOK) CALL DR_HOOK ('IOMULTIBUF_MOD:IOMULTIBUF_SIZE_IDX',1,ZHOOK_HANDLE)

END SUBROUTINE IOMULTIBUF_SIZE_IDX

SUBROUTINE IOMULTIBUF_INIT_IDX (YDPLIST, KISPBUFY, KJSPBUFY)

! Init index

TYPE (IOMULTIBUF),    INTENT (IN)    :: YDPLIST (:)
INTEGER (KIND=JPIM),  INTENT (INOUT) :: KISPBUFY
INTEGER (KIND=JPIM),  INTENT (INOUT) :: KJSPBUFY

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOMULTIBUF_MOD:IOMULTIBUF_INIT_IDX',0,ZHOOK_HANDLE)

KISPBUFY = 0
KJSPBUFY = 0

IF (LHOOK) CALL DR_HOOK ('IOMULTIBUF_MOD:IOMULTIBUF_INIT_IDX',1,ZHOOK_HANDLE)

END SUBROUTINE IOMULTIBUF_INIT_IDX

SUBROUTINE IOMULTIBUF_INCR_IDX (YDPLIST, KISPBUFY, KJSPBUFY)

! Increment index

TYPE (IOMULTIBUF),    INTENT (IN)    :: YDPLIST (:)
INTEGER (KIND=JPIM),  INTENT (INOUT) :: KISPBUFY
INTEGER (KIND=JPIM),  INTENT (INOUT) :: KJSPBUFY

#include "abor1.intfb.h"

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOMULTIBUF_MOD:IOMULTIBUF_INCR_IDX',0,ZHOOK_HANDLE)

IF (KISPBUFY > SIZE (YDPLIST)) &
  & CALL ABOR1 ('IOMULTIBUF_INCR_IDX: INDEX IS OUT OF BOUNDS')

IF (KISPBUFY == 0) THEN
  KISPBUFY = 1
  KJSPBUFY = 1
ELSEIF (KJSPBUFY == SIZE (YDPLIST(KISPBUFY)%P, 2)) THEN
  KISPBUFY = KISPBUFY + 1 
  KJSPBUFY = 1 
ELSE
  KJSPBUFY = KJSPBUFY + 1 
ENDIF

IF (KISPBUFY > SIZE (YDPLIST)) &
  & CALL ABOR1 ('IOMULTIBUF_INCR_IDX: INDEX IS OUT OF BOUNDS')

IF (KJSPBUFY > SIZE (YDPLIST(KISPBUFY)%P, 2)) &
  & CALL ABOR1 ('IOMULTIBUF_INCR_IDX: INDEX IS OUT OF BOUNDS')

IF (LHOOK) CALL DR_HOOK ('IOMULTIBUF_MOD:IOMULTIBUF_INCR_IDX',1,ZHOOK_HANDLE)

END SUBROUTINE IOMULTIBUF_INCR_IDX

SUBROUTINE IOMULTIBUF_COMP_IDX (YDPLIST, KISPBUFY, KJSPBUFY)

! Pre-compute all indexes

TYPE (IOMULTIBUF),   INTENT (IN)  :: YDPLIST (:) 
INTEGER (KIND=JPIM), INTENT (OUT) :: KISPBUFY (:)
INTEGER (KIND=JPIM), INTENT (OUT) :: KJSPBUFY (:)

INTEGER (KIND=JPIM) :: IS, I, IY, JY

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOMULTIBUF_MOD:IOMULTIBUF_COMP_IDX',0,ZHOOK_HANDLE)

CALL IOMULTIBUF_SIZE_IDX (YDPLIST, IS)

CALL IOMULTIBUF_INIT_IDX (YDPLIST, IY, JY)

DO I = 1, IS

  CALL IOMULTIBUF_INCR_IDX (YDPLIST, IY, JY)

  KISPBUFY (I) = IY
  KJSPBUFY (I) = JY
  
ENDDO

IF (LHOOK) CALL DR_HOOK ('IOMULTIBUF_MOD:IOMULTIBUF_COMP_IDX',1,ZHOOK_HANDLE)

END SUBROUTINE IOMULTIBUF_COMP_IDX

END MODULE IOMULTIBUF_MOD
