! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOSPEC_MOD

!**** *IOSPEC_MOD*  - General handling of spectral fields for IO

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 15-04-2016


USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NIOSPECCT_READ = 0, NIOSPECCT_WRITE = 1

PRIVATE
PUBLIC :: IOSPEC_SELECTF, NIOSPECCT_READ, NIOSPECCT_WRITE

INTERFACE IOSPEC_SELECTF
  MODULE PROCEDURE IOSPEC_SELECTFX, IOSPEC_SELECTFY
END INTERFACE IOSPEC_SELECTF

SAVE

CONTAINS

SUBROUTINE IOSPEC_SELECTFX (YDGEOMETRY, KACTION, PREAL, YDFLDSP, KINDSEL)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE IOFLDPTR_MOD,  ONLY : IOFLDPTR
USE IOMULTIBUF_MOD, ONLY : IOMULTIBUF

IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)              :: YDGEOMETRY
INTEGER (KIND=JPIM), INTENT (IN)              :: KACTION
REAL (KIND=JPRB),    INTENT (INOUT), TARGET   :: PREAL (:,:)
TYPE (IOFLDPTR),     INTENT (INOUT), OPTIONAL :: YDFLDSP (:)
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KINDSEL (:)

TYPE (IOMULTIBUF) :: YLGPBUF (1)

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOSPEC_MOD:IOSPEC_SELECTFX',0,ZHOOK_HANDLE)

YLGPBUF (1)%P => PREAL

CALL IOSPEC_SELECTFY (YDGEOMETRY, KACTION, YLGPBUF, YDFLDSP, KINDSEL)

IF (LHOOK) CALL DR_HOOK('IOSPEC_MOD:IOSPEC_SELECTFX',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPEC_SELECTFX

SUBROUTINE IOSPEC_SELECTFY (YDGEOMETRY, KACTION, YDGPBUF, YDFLDSP, KINDSEL)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMLUN   , ONLY : NULOUT
USE IOFLDPTR_MOD,  ONLY : IOFLDPTR
USE IOMULTIBUF_MOD, ONLY : IOMULTIBUF,          &
                         & IOMULTIBUF_SIZE_IDX, &
                         & IOMULTIBUF_COMP_IDX


IMPLICIT NONE

TYPE (GEOMETRY),               INTENT (IN)            :: YDGEOMETRY
INTEGER (KIND=JPIM),           INTENT (IN)            :: KACTION
TYPE (IOMULTIBUF),             INTENT (INOUT)         :: YDGPBUF (:)
TYPE (IOFLDPTR),               INTENT (INOUT)         :: YDFLDSP (:) 
INTEGER (KIND=JPIM), OPTIONAL, INTENT (IN),    TARGET :: KINDSEL (:)

#include "abor1.intfb.h"

INTEGER(KIND=JPIM) :: INFLD, JFLD, JW, II
INTEGER(KIND=JPIM) :: IGPBUFY, JGPBUFY
INTEGER(KIND=JPIM), ALLOCATABLE :: IGPBUFY_IDX (:), JGPBUFY_IDX (:) 
INTEGER(KIND=JPIM), POINTER     :: IINDSEL (:)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOSPEC_MOD:IOSPEC_SELECTFY',0,ZHOOK_HANDLE)

IF (PRESENT (KINDSEL)) THEN
  IINDSEL => KINDSEL
ELSE
  ALLOCATE (IINDSEL (YDGEOMETRY%YRDIM%NSPEC2))
  IINDSEL = (/ (JW, JW = 1, YDGEOMETRY%YRDIM%NSPEC2) /)
ENDIF

CALL IOMULTIBUF_SIZE_IDX (YDGPBUF, INFLD)
ALLOCATE (IGPBUFY_IDX (INFLD), JGPBUFY_IDX (INFLD))
CALL IOMULTIBUF_COMP_IDX (YDGPBUF, IGPBUFY_IDX, JGPBUFY_IDX)

DO JFLD = 1, SIZE (YDFLDSP)

  IF (JFLD > UBOUND (IGPBUFY_IDX,1)) &
   & CALL ABOR1 ('IOSPEC_MOD:IOSPEC_SELECTFY: INPUT BUFFER TOO SMALL')

  IGPBUFY = IGPBUFY_IDX (JFLD)
  JGPBUFY = JGPBUFY_IDX (JFLD)

  IF (YDFLDSP (JFLD)%LSKIPF) CYCLE

  IF (.NOT. ASSOCIATED (YDFLDSP (JFLD)%ZFLDSP)) THEN
    WRITE (NULOUT, *) YDFLDSP (JFLD)%YFLDDSC%CPREF, YDFLDSP (JFLD)%YFLDDSC%ILEVG, YDFLDSP (JFLD)%YFLDDSC%CSUFF
    CALL ABOR1 ('IOSPEC_MOD:IOSPEC_SELECTFY: ZFLD IS NOT ASSOCIATED')
  ENDIF

  DO II = 1, SIZE (IINDSEL)

    JW = IINDSEL (II)

    SELECT CASE (KACTION) 

      CASE (NIOSPECCT_WRITE)

        YDGPBUF (IGPBUFY)%P (II,JGPBUFY) = &
        & YDFLDSP (JFLD)%ZFLDSP (JW)

      CASE (NIOSPECCT_READ)

        YDFLDSP (JFLD)%ZFLDSP (JW) = &
        & YDGPBUF (IGPBUFY)%P (II,JGPBUFY)

      CASE DEFAULT

        CALL ABOR1 ('IOSPEC_MOD:IOSPEC_SELECTFY: UNEXPECTED KACTION')

    END SELECT

  ENDDO

ENDDO

IF (PRESENT (KINDSEL)) THEN
ELSE
  DEALLOCATE (IINDSEL)
  NULLIFY (IINDSEL)
ENDIF

IF (LHOOK) CALL DR_HOOK ('IOSPEC_MOD:IOSPEC_SELECTFY',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPEC_SELECTFY

END MODULE IOSPEC_MOD

