! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOSPECE_MOD

USE PARKIND1, ONLY : JPRB, JPIM
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE IOMULTIBUF_MOD, ONLY : IOMULTIBUF,          &
                         & IOMULTIBUF_INIT_IDX, & 
                         & IOMULTIBUF_INCR_IDX

USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE YOMFP4L, ONLY : TRQFP

IMPLICIT NONE

INTERFACE IOSPECE_ML_SELECTF
  MODULE PROCEDURE IOSPECE_ML_SELECTFX, IOSPECE_ML_SELECTFY
END INTERFACE IOSPECE_ML_SELECTF

INTERFACE IOSPECE_PL_SELECTF
  MODULE PROCEDURE IOSPECE_PL_SELECTFX, IOSPECE_PL_SELECTFY
END INTERFACE IOSPECE_PL_SELECTF

CONTAINS

SUBROUTINE IOSPECE_ML_COUNT (KFPSPBG,KFNUM)

! Number of fields to be written

INTEGER (KIND=JPIM), INTENT (IN) :: KFPSPBG
INTEGER (KIND=JPIM), INTENT (INOUT) :: KFNUM

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_ML_COUNT',0,ZHOOK_HANDLE)

KFNUM = KFNUM + KFPSPBG

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_ML_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECE_ML_COUNT

SUBROUTINE IOSPECE_ML_SELECTD (YDRQSP,KSPEC2G,YDFLDSC)

! Get field descriptors

TYPE (TRQFP),  INTENT(IN) :: YDRQSP
INTEGER(KIND=JPIM), INTENT(IN)  :: KSPEC2G
TYPE (IOFLDDESC),    INTENT (OUT) :: YDFLDSC (:)

INTEGER(KIND=JPIM)  :: JF

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_ML_SELECTD',0,ZHOOK_HANDLE)
ASSOCIATE(NFIELDG=>YDRQSP%NFIELDG, LLSURF=>YDRQSP%LLSURF, ZLEV=>YDRQSP%ZLEV, IVSETG=>YDRQSP%IVSETG,  &
 & IVLOCG=>YDRQSP%IVLOCG, IGRIB=>YDRQSP%IGRIB)

  DO JF = 1, NFIELDG

    YDFLDSC (JF)%CPREF = 'm'
    YDFLDSC (JF)%LSPEC = .TRUE.
    YDFLDSC (JF)%NFLSZ = KSPEC2G
    YDFLDSC (JF)%ILEVL = IVLOCG (JF)                  ! IGRIBIOSH(4,JF)
    YDFLDSC (JF)%IGRIB = IGRIB (JF)  ! IGRIBIOSH(1,JF)

    IF (LLSURF(JF)) THEN
      YDFLDSC (JF)%ILEVG = 1                            ! IGRIBIOSH(2,JF)
    ELSE
      YDFLDSC (JF)%ILEVG = NINT (ZLEV (JF))         ! IGRIBIOSH(2,JF)
    ENDIF
    YDFLDSC (JF)%IVSET = IVSETG (JF)                  ! IGRIBIOSH(3,JF)

  ENDDO

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_ML_SELECTD',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECE_ML_SELECTD

SUBROUTINE IOSPECE_ML_SELECTFY (PSPEC, YDSPBUF, YDFLDSC)

REAL (KIND=JPRB),    INTENT (IN)    :: PSPEC(:,:)
TYPE (IOMULTIBUF),   INTENT (INOUT) :: YDSPBUF (:)
TYPE (IOFLDDESC),    INTENT (IN)    :: YDFLDSC (:)

INTEGER (KIND=JPIM) :: JFLD, ILOCLV, JNM
INTEGER (KIND=JPIM) :: ISPBUFY, JSPBUFY

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_ML_SELECTFY',0,ZHOOK_HANDLE)

  CALL IOMULTIBUF_INIT_IDX (YDSPBUF, ISPBUFY, JSPBUFY)

  DO JFLD = 1, SIZE (YDFLDSC)
    CALL IOMULTIBUF_INCR_IDX (YDSPBUF, ISPBUFY, JSPBUFY)
    ILOCLV = YDFLDSC (JFLD)%ILEVL
    DO JNM = 1, SIZE(PSPEC,DIM=2)
      YDSPBUF(ISPBUFY)%P(JNM,JSPBUFY) = PSPEC (ILOCLV, JNM)
    ENDDO
  ENDDO

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_ML_SELECTFY',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECE_ML_SELECTFY

SUBROUTINE IOSPECE_ML_SELECTFX (PSPEC, PSPBUF, YDFLDSC)

REAL (KIND=JPRB), INTENT (IN)            :: PSPEC (:,:)
REAL (KIND=JPRB), INTENT (INOUT), TARGET :: PSPBUF (:,:)
TYPE (IOFLDDESC), INTENT (IN)            :: YDFLDSC (:)

TYPE (IOMULTIBUF) :: YLSPBUF (1)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_ML_SELECTFX',0,ZHOOK_HANDLE)

YLSPBUF(1)%P => PSPBUF

CALL IOSPECE_ML_SELECTFY (PSPEC, YLSPBUF, YDFLDSC)

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_ML_SELECTFX',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECE_ML_SELECTFX

SUBROUTINE IOSPECE_PL_COUNT (YDRQSP,KFNUM,CDPREF)

! Number of fields to be written

USE YOM_GRIB_CODES, ONLY : NGRBZ 

TYPE (TRQFP),  INTENT(IN) :: YDRQSP
INTEGER (KIND=JPIM), INTENT (INOUT) :: KFNUM
CHARACTER(LEN=1),    INTENT (IN),    OPTIONAL :: CDPREF

INTEGER (KIND=JPIM) :: JF
CHARACTER(LEN=1) :: CLPREF
CHARACTER(LEN=128) :: CLERR


REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_PL_COUNT',0,ZHOOK_HANDLE)
ASSOCIATE(NFIELDG=>YDRQSP%NFIELDG, LLSURF=>YDRQSP%LLSURF, IGRIB=>YDRQSP%IGRIB)

CLPREF = 'p'
IF(PRESENT(CDPREF)) CLPREF = CDPREF

IF (NFIELDG > 0) THEN
  DO JF = 1, NFIELDG
    IF(CLPREF == 'p') THEN
      IF (IGRIB(JF) == NGRBZ .AND. LLSURF (JF)) CYCLE
    ENDIF
    KFNUM = KFNUM + 1
  ENDDO
ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_PL_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECE_PL_COUNT

SUBROUTINE IOSPECE_PL_SELECTD (YDRQSP,KSPEC2G,YDFLDSC,CDPREF)

! Get field descriptors

USE YOM_GRIB_CODES, ONLY : NGRBZ 

TYPE (TRQFP),  INTENT(IN) :: YDRQSP
INTEGER(KIND=JPIM), INTENT(IN)  :: KSPEC2G
TYPE (IOFLDDESC),    INTENT (OUT) :: YDFLDSC (:)
CHARACTER(LEN=1),    INTENT (IN),    OPTIONAL :: CDPREF

INTEGER(KIND=JPIM)  :: JF, JFLD

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE
CHARACTER(LEN=1) :: CLPREF
CHARACTER(LEN=128) :: CLERR

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_PL_SELECTD',0,ZHOOK_HANDLE)
ASSOCIATE(NFIELDG=>YDRQSP%NFIELDG, LLSURF=>YDRQSP%LLSURF, ZLEV=>YDRQSP%ZLEV, IVSETG=>YDRQSP%IVSETG, &
 & IVLOCG=>YDRQSP%IVLOCG, IGRIB=>YDRQSP%IGRIB)

CLPREF = 'p'
IF(PRESENT(CDPREF)) CLPREF = CDPREF

IF (NFIELDG > 0) THEN

  JF = 0

  DO JFLD = 1, NFIELDG

    IF(CLPREF == 'p') THEN
      IF (IGRIB(JFLD) == NGRBZ .AND. LLSURF (JFLD)) CYCLE
    ENDIF
    JF = JF + 1

    YDFLDSC (JF)%CPREF = CLPREF
    YDFLDSC (JF)%LSPEC = .TRUE.
    YDFLDSC (JF)%NFLSZ = KSPEC2G
    YDFLDSC (JF)%ILEVL = IVLOCG (JFLD)                  ! IGRIBIOSH(4,JF)
    YDFLDSC (JF)%IGRIB = IGRIB (JFLD)  ! IGRIBIOSH(1,JF)

    IF(CLPREF == 'p') THEN
      IF (LLSURF(JF)) THEN
        YDFLDSC (JF)%ILEVG = 100000                         ! IGRIBIOSH(2,JF)
      ELSE
        YDFLDSC (JF)%ILEVG = NINT (ZLEV (JFLD))         ! IGRIBIOSH(2,JF)
      ENDIF
    ELSEIF(CLPREF == 'v') THEN
      YDFLDSC (JF)%ILEVG = NINT(ZLEV(JF)*1.E+09_JPRB)
    ELSE
      YDFLDSC (JF)%ILEVG = NINT(ZLEV(JF))
    ENDIF

      
    YDFLDSC (JF)%IVSET = IVSETG (JFLD)                  ! IGRIBIOSH(3,JF)

  ENDDO

ENDIF

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_PL_SELECTD',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECE_PL_SELECTD

SUBROUTINE IOSPECE_PL_SELECTFY (PSPEC, YDSPBUF, YDFLDSC,CDPREF)

REAL (KIND=JPRB),    INTENT (IN)    :: PSPEC (:,:)
TYPE (IOMULTIBUF),   INTENT (INOUT) :: YDSPBUF (:)
TYPE (IOFLDDESC),    INTENT (IN)    :: YDFLDSC (:)
CHARACTER(LEN=1),    INTENT (IN),    OPTIONAL :: CDPREF

INTEGER (KIND=JPIM) :: JF, ILOCLV, JNM
INTEGER (KIND=JPIM) :: ISPBUFY, JSPBUFY

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE
CHARACTER(LEN=1) :: CLPREF
CHARACTER(LEN=128) :: CLERR

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_PL_SELECTFY',0,ZHOOK_HANDLE)

CLPREF = 'p'
IF(PRESENT(CDPREF)) CLPREF = CDPREF

  CALL IOMULTIBUF_INIT_IDX (YDSPBUF, ISPBUFY, JSPBUFY)

  DO JF = 1, SIZE (YDFLDSC)
    CALL IOMULTIBUF_INCR_IDX (YDSPBUF, ISPBUFY, JSPBUFY)
    ILOCLV = YDFLDSC (JF)%ILEVL
    DO JNM = 1, SIZE(PSPEC,DIM=2)
      YDSPBUF(ISPBUFY)%P(JNM,JSPBUFY) = PSPEC (ILOCLV, JNM)
    ENDDO
  ENDDO

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_PL_SELECTFY',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECE_PL_SELECTFY

SUBROUTINE IOSPECE_PL_SELECTFX (PSPEC, PSPBUF, YDFLDSC,CDPREF)


REAL (KIND=JPRB), INTENT (IN)            :: PSPEC (:,:)
REAL (KIND=JPRB), INTENT (INOUT), TARGET :: PSPBUF (:,:)
TYPE (IOFLDDESC), INTENT (IN)            :: YDFLDSC (:)
CHARACTER(LEN=1), INTENT (IN),    OPTIONAL :: CDPREF

TYPE (IOMULTIBUF) :: YLSPBUF (1)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_PL_SELECTFX',0,ZHOOK_HANDLE)

YLSPBUF(1)%P => PSPBUF

CALL IOSPECE_PL_SELECTFY (PSPEC, YLSPBUF, YDFLDSC,CDPREF)

IF (LHOOK) CALL DR_HOOK ('IOSPECE_MOD:IOSPECE_PL_SELECTFX',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECE_PL_SELECTFX

END MODULE IOSPECE_MOD

