! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOSPECSPA_MOD

!**** *IOSPECSPA_MOD*  - Handling of spectral model state fields for IO

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO-FRANCE*
!      Original : 15-04-2016

!     Modifications.
!     --------------
!      P. Marguinaud : 04-10-2016 : Port to single precision


USE PARKIND1, ONLY : JPRB, JPIM
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD, ASSIGNMENT(=)
USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE IOFLDPTR_MOD, ONLY : IOFLDPTR

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NIOSPECSPACT_READ = 0, NIOSPECSPACT_WRITE = 1

PRIVATE :: IOSPECSPA_SELECT_WH, IOSPECSPA_SELECTDD, IOSPECSPA_SELECTDP

INTERFACE IOSPECSPA_SELECTD
  MODULE PROCEDURE IOSPECSPA_SELECTDD, IOSPECSPA_SELECTDP
END INTERFACE IOSPECSPA_SELECTD

SAVE

CONTAINS

SUBROUTINE IOSPECSPA_COUNT (YDGEOMETRY, KACTION, KFNUM)

USE GEOMETRY_MOD , ONLY : GEOMETRY

IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)    :: YDGEOMETRY
INTEGER (KIND=JPIM), INTENT (IN)    :: KACTION
INTEGER (KIND=JPIM), INTENT (INOUT) :: KFNUM

INTEGER (KIND=JPIM) :: IFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_COUNT',0,ZHOOK_HANDLE)

IFCUR = 0
CALL IOSPECSPA_SELECT_WH (YDGEOMETRY, KACTION, KFCUR=IFCUR)
KFNUM = KFNUM + IFCUR

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECSPA_COUNT

SUBROUTINE IOSPECSPA_SELECTDD (YDGEOMETRY, KACTION, YDFLDSC, KFCUR)

USE GEOMETRY_MOD , ONLY : GEOMETRY
IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)              :: YDGEOMETRY
INTEGER (KIND=JPIM), INTENT (IN)              :: KACTION
TYPE (IOFLDDESC),    INTENT (INOUT)           :: YDFLDSC (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_SELECTDD',0,ZHOOK_HANDLE)

CALL IOSPECSPA_SELECT_WH (YDGEOMETRY, KACTION, YDFLDSC=YDFLDSC, KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_SELECTDD',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECSPA_SELECTDD

SUBROUTINE IOSPECSPA_SELECTDP (YDGEOMETRY, KACTION, YDFLDST, KFCUR)

USE GEOMETRY_MOD , ONLY : GEOMETRY

IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)              :: YDGEOMETRY
INTEGER (KIND=JPIM), INTENT (IN)              :: KACTION
TYPE (IOFLDPTR),     INTENT (INOUT)           :: YDFLDST (:) 
INTEGER (KIND=JPIM), INTENT (INOUT), OPTIONAL :: KFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_SELECTDP',0,ZHOOK_HANDLE)

CALL IOSPECSPA_SELECT_WH (YDGEOMETRY, KACTION, YDFLDST=YDFLDST, KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_SELECTDP',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECSPA_SELECTDP

SUBROUTINE IOSPECSPA_SELECT_WH (YDGEOMETRY, KACTION, YDFLDSC, YDFLDST, KFCUR, YDSPEC)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMMP0   , ONLY : MYSETV
USE YOMOPH0  , ONLY : CNMCA
USE FA_MOD   , ONLY : JPPRCM

IMPLICIT NONE

TYPE (GEOMETRY),               INTENT (IN)            :: YDGEOMETRY
INTEGER (KIND=JPIM),           INTENT (IN)            :: KACTION
TYPE (IOFLDDESC),    OPTIONAL, INTENT (INOUT), TARGET :: YDFLDSC (:) 
TYPE (IOFLDPTR),     OPTIONAL, INTENT (INOUT), TARGET :: YDFLDST (:)
INTEGER (KIND=JPIM), OPTIONAL, INTENT (INOUT)         :: KFCUR
TYPE(SPECTRAL_FIELD), INTENT(INOUT), OPTIONAL         :: YDSPEC

INTEGER (KIND=JPIM)       :: IFCUR, ILEVG
TYPE (IOFLDDESC), POINTER :: YLFLDSC (:)
INTEGER (KIND=JPIM)       :: IREP, IPFAOVSZ

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_SELECT_WH',0,ZHOOK_HANDLE)

CALL FASGRA (IREP, CNMCA, IPFAOVSZ)

IF (PRESENT (YDFLDSC)) THEN
  YLFLDSC => YDFLDSC
ELSEIF (PRESENT (YDFLDST)) THEN
  YLFLDSC => YDFLDST%YFLDDSC
ELSE
  YLFLDSC => NULL ()
ENDIF

IFCUR = 0
IF (PRESENT (KFCUR)) IFCUR = KFCUR

DO ILEVG = 1, YDGEOMETRY%YRDIMV%NFLEVG
  CALL ACPY ('S', ILEVG, 'VORTICITY   ', PSPEC3=YDSPEC%VOR)
  CALL ACPY ('S', ILEVG, 'DIVERGENCE  ', PSPEC3=YDSPEC%DIV)
  CALL ACPY ('S', ILEVG, 'TEMPERATURE ', PSPEC3=YDSPEC%T  )
  CALL ACPY ('S', ILEVG, 'HUMIDITY    ', PSPEC3=YDSPEC%Q  )
  CALL ACPY ('S', ILEVG, 'PRESS.DEPART', PSPEC3=YDSPEC%SPD)
  CALL ACPY ('S', ILEVG, 'VERTIC.DIVER', PSPEC3=YDSPEC%SVD)
  CALL ACPY ('S', ILEVG, 'NHX         ', PSPEC3=YDSPEC%NHX)
ENDDO

CALL ACPY ('SURF', 0_JPIM, 'PRESSURE',    PSPEC2=YDSPEC%SP)
CALL ACPY ('SURF', 0_JPIM, 'OROGRAPHY',   PSPEC2=YDSPEC%OROG)

IF (ASSOCIATED (YLFLDSC)) &
  & CALL IOSPECSPA_FIXUVMEAN (YDGEOMETRY, KACTION, YLFLDSC)

IF (PRESENT (KFCUR)) KFCUR = IFCUR

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_SELECT_WH',1,ZHOOK_HANDLE)

CONTAINS

SUBROUTINE ACPY (CDPREF, KLEVG, CDSUFF, PSPEC2, PSPEC3)

USE SPECTRAL_FIELDS_MOD, ONLY : SP_DUM2D => SPECTRAL_DUMMY2D, &
                              & SP_DUM3D => SPECTRAL_DUMMY3D
USE YOMFA, ONLY : NVGRIB

CHARACTER (LEN=*),   INTENT (IN)         :: CDPREF
INTEGER (KIND=JPIM), INTENT (IN)         :: KLEVG
CHARACTER (LEN=*),   INTENT (IN)         :: CDSUFF
REAL (KIND=JPRB),    POINTER,   OPTIONAL :: PSPEC2 (:)
REAL (KIND=JPRB),    POINTER,   OPTIONAL :: PSPEC3 (:,:)

#include "abor1.intfb.h"

INTEGER (KIND=JPIM) :: ILEVL, IVSET, IOLEV

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_SELECT_WH:ACPY',0,ZHOOK_HANDLE)

IF (PRESENT (PSPEC2)) THEN
  IF (ASSOCIATED (PSPEC2, SP_DUM2D)) GOTO 999
ELSEIF (PRESENT (PSPEC3)) THEN
  IF (ASSOCIATED (PSPEC3, SP_DUM3D)) GOTO 999
ELSE
  CALL ABOR1 ('IOSPECSPA_MOD:IOSPECSPA_SELECT_WH:ACPY: EXPECTED PSPEC2 OR PSPEC3')
ENDIF

IFCUR = IFCUR + 1

IF (KLEVG > 0) THEN
  IVSET = YDGEOMETRY%YRMP%NBSETLEV(KLEVG)
  ILEVL = KLEVG-YDGEOMETRY%YRMP%NPTRLL(IVSET)+1
  IOLEV = KLEVG + YDGEOMETRY%YRDIMV%NIOLEVG - YDGEOMETRY%YRDIMV%NFLEVG
ELSE
  IVSET = YDGEOMETRY%YRMP%NBSETSP
  ILEVL = 0
  IOLEV = 0
ENDIF

IF (PRESENT (YDFLDST)) THEN
  IF (PRESENT (PSPEC2) .AND. (MYSETV == IVSET)) THEN
    YDFLDST (IFCUR)%ZFLDSP => PSPEC2 (:)
  ELSEIF (PRESENT (PSPEC3) .AND. (MYSETV == IVSET)) THEN
    YDFLDST (IFCUR)%ZFLDSP => PSPEC3 (ILEVL,:)
  ENDIF
ENDIF

IF (ASSOCIATED (YLFLDSC)) THEN

  YLFLDSC(IFCUR)%NFLSZ  = YDGEOMETRY%YRDIM%NSPEC2G
  YLFLDSC(IFCUR)%NSIZPK = YDGEOMETRY%YRDIM%NSPEC2G + JPPRCM * IPFAOVSZ
  YLFLDSC(IFCUR)%LSPEC  = .TRUE.
  YLFLDSC(IFCUR)%NGRIBL = NVGRIB
  
  YLFLDSC(IFCUR)%CPREF = CDPREF
  YLFLDSC(IFCUR)%ILEVG = KLEVG
  YLFLDSC(IFCUR)%IOLEV = IOLEV
  YLFLDSC(IFCUR)%IVSET = IVSET
  YLFLDSC(IFCUR)%ILEVL = ILEVL

  YLFLDSC(IFCUR)%LIOLV = .TRUE.
  YLFLDSC(IFCUR)%CSUFF = CDSUFF
  YLFLDSC(IFCUR)%LREQD = .TRUE.

ENDIF

999 CONTINUE

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_SELECT_WH:ACPY',1,ZHOOK_HANDLE)

END SUBROUTINE ACPY

END SUBROUTINE IOSPECSPA_SELECT_WH

SUBROUTINE IOSPECSPA_FIXUVMEAN (YDGEOMETRY, KACTION, YDFLDSC, YDSPEC)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMMP0   , ONLY : MYSETV
USE YOMCT0   , ONLY : LELAM

IMPLICIT NONE

TYPE (GEOMETRY),               INTENT (IN)    :: YDGEOMETRY
INTEGER (KIND=JPIM),           INTENT (IN)    :: KACTION
TYPE (IOFLDDESC),              INTENT (INOUT) :: YDFLDSC (:) 
TYPE(SPECTRAL_FIELD), INTENT(INOUT), OPTIONAL :: YDSPEC

INTEGER (KIND=JPIM) :: JFLD, IVSET, ILEVG, ILEVL

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_FIXUVMEAN',0,ZHOOK_HANDLE)


IF (LELAM) THEN

  DO JFLD = 1, SIZE (YDFLDSC)
  
    ILEVG = YDFLDSC(JFLD)%ILEVG
  
    IF (ILEVG > 0) THEN
  
      IVSET = YDGEOMETRY%YRMP%NBSETLEV(ILEVG)
  
      IF (MYSETV == IVSET) THEN
  
        ILEVL = ILEVG-YDGEOMETRY%YRMP%NPTRLL(IVSET)+1
  
        IF (TRIM (YDFLDSC (JFLD)%CSUFF) == 'VORTICITY' ) THEN
          SELECT CASE (KACTION)
            CASE (NIOSPECSPACT_WRITE)
              YDFLDSC(JFLD)%XAUX1 = YDSPEC%UB (ILEVL)
            CASE (NIOSPECSPACT_READ)
              YDSPEC%UB (ILEVL) = YDFLDSC(JFLD)%XAUX1
          END SELECT
        ENDIF
  
        IF (TRIM (YDFLDSC (JFLD)%CSUFF) == 'DIVERGENCE' ) THEN
          SELECT CASE (KACTION)
            CASE (NIOSPECSPACT_WRITE)
              YDFLDSC(JFLD)%XAUX1 = YDSPEC%VB (ILEVL)
            CASE (NIOSPECSPACT_READ)
              YDSPEC%VB (ILEVL) = YDFLDSC(JFLD)%XAUX1
          END SELECT
        ENDIF
  
      ENDIF
  
    ENDIF
  
  ENDDO

ENDIF

IF (LHOOK) CALL DR_HOOK('IOSPECSPA_MOD:IOSPECSPA_FIXUVMEAN',1,ZHOOK_HANDLE)

END SUBROUTINE IOSPECSPA_FIXUVMEAN

END MODULE IOSPECSPA_MOD

