! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE IOXFU_MOD

!**** *IOXFU_MOD*  Module for instantaneous fluxes.

! Author.
! -------
!  14/01/2011 : P.Marguinaud

! Modifications

! -------------
!  P.Marguinaud : 11-09-2012 : Use IOFLDDESC_MOD
!  T. Wilhelmsson (Sept 2013) Geometry and setup refactoring.
!  P.Marguinaud : 10-10-2013 : Cleaning
!  P.Marguinaud : 10-10-2014 : Add read capability
!  P.marguinaud : 04-10-2016 : Port to single precision
! End Modifications
! ---------------------------------------------------------------------

USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

USE IOFLDDESC_MOD, ONLY : IOFLDDESC
USE IOFLDPTR_MOD, ONLY : IOFLDPTR

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: NIOXFUACT_READ = 0, NIOXFUACT_WRITE = 1

INTERFACE IOXFU_SELECTD
  MODULE PROCEDURE IOXFU_SELECTDD, IOXFU_SELECTDP
END INTERFACE IOXFU_SELECTD

PRIVATE :: IOXFU_SELECTDD, IOXFU_SELECTDP, IOXFU_SELECT_WH

SAVE

CONTAINS

SUBROUTINE IOXFU_COUNT(YDGEOMETRY,YDXFU,KACTION,KFNUM)

USE YOMXFU      , ONLY : TXFU
USE GEOMETRY_MOD, ONLY : GEOMETRY
IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)    :: YDGEOMETRY
TYPE(TXFU)          ,INTENT(INOUT)  :: YDXFU
INTEGER (KIND=JPIM), INTENT (IN)    :: KACTION
INTEGER (KIND=JPIM), INTENT (INOUT) :: KFNUM

INTEGER (KIND=JPIM) :: IFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOXFU_MOD:IOXFU_COUNT',0,ZHOOK_HANDLE)

IFCUR = 0
CALL IOXFU_SELECT_WH(YDGEOMETRY,YDXFU,KACTION,KFCUR=IFCUR)
KFNUM = KFNUM + IFCUR

IF (LHOOK) CALL DR_HOOK('IOXFU_MOD:IOXFU_COUNT',1,ZHOOK_HANDLE)

END SUBROUTINE IOXFU_COUNT

SUBROUTINE IOXFU_SELECTDD(YDGEOMETRY,YDXFU,KACTION,YDFLDSC,KFCUR)

USE YOMXFU       , ONLY : TXFU
USE GEOMETRY_MOD , ONLY : GEOMETRY

IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)              :: YDGEOMETRY
TYPE(TXFU)          ,INTENT(INOUT)            :: YDXFU
INTEGER (KIND=JPIM), INTENT (IN)              :: KACTION
TYPE (IOFLDDESC),    INTENT (INOUT)           :: YDFLDSC (:)
INTEGER(KIND=JPIM),  INTENT (INOUT), OPTIONAL :: KFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOXFU_MOD:IOXFU_SELECTDD',0,ZHOOK_HANDLE)

CALL IOXFU_SELECT_WH(YDGEOMETRY,YDXFU,KACTION,YDFLDSC=YDFLDSC,KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOXFU_MOD:IOXFU_SELECTDD',1,ZHOOK_HANDLE)

END SUBROUTINE IOXFU_SELECTDD

SUBROUTINE IOXFU_SELECTDP(YDGEOMETRY,YDXFU,KACTION,YDFLDGT,KFCUR)

USE YOMXFU       , ONLY : TXFU
USE GEOMETRY_MOD , ONLY : GEOMETRY
IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)              :: YDGEOMETRY
TYPE(TXFU)          ,INTENT(INOUT)            :: YDXFU
INTEGER (KIND=JPIM), INTENT (IN)              :: KACTION
TYPE (IOFLDPTR),     INTENT (INOUT)           :: YDFLDGT (:)
INTEGER(KIND=JPIM),  INTENT (INOUT), OPTIONAL :: KFCUR

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOXFU_MOD:IOXFU_SELECTDP',0,ZHOOK_HANDLE)

CALL IOXFU_SELECT_WH(YDGEOMETRY,YDXFU,KACTION,YDFLDGT=YDFLDGT,KFCUR=KFCUR)

IF (LHOOK) CALL DR_HOOK('IOXFU_MOD:IOXFU_SELECTDP',1,ZHOOK_HANDLE)

END SUBROUTINE IOXFU_SELECTDP

SUBROUTINE IOXFU_SELECT_WH(YDGEOMETRY,YDXFU,KACTION,YDFLDSC,YDFLDGT,KFCUR)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMXFU   , ONLY : TXFU
USE YOMCT0   , ONLY : LRPLANE
USE YOMOPH0  , ONLY : CNMCA
USE YOMFA    , ONLY : NVGRIB, NBITPG
USE FA_MOD   , ONLY : JPPRCM

!**** * IOXFU  * - ROUTINE TO EXTRAXCT AND WRITE INSTANTANEOUS FLUXES
!       History :
!       14/01/2011 : Creation from wrxfu.F90 (P.Marguinaud)
!        -----------------------------------------------------------

IMPLICIT NONE

TYPE (GEOMETRY),     INTENT (IN)                      :: YDGEOMETRY
TYPE(TXFU), TARGET  ,INTENT(INOUT)                    :: YDXFU
INTEGER (KIND=JPIM), INTENT (IN)                      :: KACTION
TYPE (IOFLDDESC),    INTENT (INOUT), OPTIONAL, TARGET :: YDFLDSC (:)
TYPE (IOFLDPTR),     INTENT (INOUT), OPTIONAL, TARGET :: YDFLDGT (:)
INTEGER(KIND=JPIM),  INTENT (INOUT), OPTIONAL         :: KFCUR

INTEGER (KIND=JPIM)       :: JF, IFLD, JL
INTEGER (KIND=JPIM)       :: IFCUR
TYPE (IOFLDDESC), POINTER :: YLFLDSC (:)
INTEGER (KIND=JPIM)       :: IREP, IPFAOVSZ

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('IOXFU_MOD:IOXFU_SELECT_WH',0,ZHOOK_HANDLE)

IF (PRESENT (YDFLDSC)) THEN
  YLFLDSC => YDFLDSC
ELSEIF (PRESENT (YDFLDGT)) THEN
  YLFLDSC => YDFLDGT%YFLDDSC
ELSE
  YLFLDSC => NULL ()
ENDIF

IFCUR = 0
IF (PRESENT (KFCUR)) IFCUR = KFCUR

CALL FASGRA (IREP, CNMCA, IPFAOVSZ)

IFLD = 0
DO JF = 1, YDXFU%NTYPXFU

  DO JL = 1, YDXFU%TYPE_XFU(JF)%ILEV
    IFLD = IFLD + 1
    IFCUR = IFCUR + 1

    IF (ASSOCIATED (YLFLDSC)) THEN

      YLFLDSC(IFCUR)%NFLSZ  = YDGEOMETRY%YRGEM%NGPTOTG
      YLFLDSC(IFCUR)%NSIZPK = YDGEOMETRY%YRGEM%NGPTOTG + JPPRCM * IPFAOVSZ
      YLFLDSC(IFCUR)%CPREF  = YDXFU%TYPE_XFU(JF)%CLPREF(JL)
      YLFLDSC(IFCUR)%ILEVG  = YDXFU%TYPE_XFU(JF)%INUMLEV(JL)
      YLFLDSC(IFCUR)%CSUFF  = YDXFU%TYPE_XFU(JF)%CLSUFF
      YLFLDSC(IFCUR)%NGRIBL = NVGRIB
      YLFLDSC(IFCUR)%JBITS  = NBITPG

      IF (YLFLDSC(IFCUR)%CSUFF == 'NEBULOSI.TOT') THEN
        YLFLDSC(IFCUR)%JBITS = 4
      ELSEIF (YLFLDSC(IFCUR)%CSUFF == 'HUMILIQU.TOT') THEN
        YLFLDSC(IFCUR)%JBITS = 10
      ELSEIF (YLFLDSC(IFCUR)%CSUFF == 'HUMISOLI.TOT') THEN
        YLFLDSC(IFCUR)%JBITS = 10
      ENDIF

    ENDIF
   
    IF (PRESENT (YDFLDGT)) THEN
      YDFLDGT(IFCUR)%ZFLDGP => YDXFU%XFUBUF (:,IFLD,:) 
! De-reduce vector fields
      YDFLDGT(IFCUR)%LDRDGP = LRPLANE .AND. (YDXFU%TYPE_XFU(JF)%IPARITY == 1)
    ENDIF

  ENDDO

ENDDO

IF (PRESENT (KFCUR)) KFCUR = IFCUR

IF (LHOOK) CALL DR_HOOK('IOXFU_MOD:IOXFU_SELECT_WH',1,ZHOOK_HANDLE)

END SUBROUTINE IOXFU_SELECT_WH

END MODULE IOXFU_MOD

