! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBMODULE (MODEL_MOD) MODEL_MOD_MODEL_FINALIZE
IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE MODEL_FINALIZE(SELF, YDFIELDS)

USE PARKIND1        , ONLY : JPRB, JPIM
USE YOMHOOK         , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCT0          , ONLY : NCONF
USE YOMCT3          , ONLY : NSTEP
USE FIELDS_MOD      , ONLY : FIELDS
USE MTRAJ_MOD       , ONLY : MTRAJ
USE GMV_SUBS_MOD    , ONLY : SETUP_GMV5
USE YOMTRAJ_OOPS    , ONLY : TRAJ_TYPE_oops
USE YOMLUN          , ONLY : NULOUT
USE GEOMETRY_MOD    , ONLY : GEOMETRY_SAME
USE DATETIME_TMP_MOD, ONLY : DATETIME_TMP, SETRIPSTEP, GETRIPSTEP

IMPLICIT NONE

#include "abor1.intfb.h"
#include "spnorm.intfb.h"
#include "chem_massdia.intfb.h"

TYPE(MODEL)       , INTENT(INOUT) :: SELF
TYPE(FIELDS)      , INTENT(INOUT) :: YDFIELDS

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_FINALIZE',0,ZHOOK_HANDLE)

CALL MODEL_SET(SELF)
IF(.NOT.GEOMETRY_SAME(SELF%YRML_GCONF%GEOM,YDFIELDS%GEOM)) CALL ABOR1('MODEL_MOD:MODEL_FINALIZE - GEOMETRIES DIFFERENT')

#ifdef WITH_NEMO
IF (SELF%YRML_AOC%YRMCC%LMCC04.AND.SELF%YRML_AOC%YRMCC%LNEMOCOUP) CALL NEMOGCMCOUP_FINAL
#endif

IF (SELF%YRML_CHEM%YRCOMPO%LCHEM_DIA ) THEN
  CALL CHEM_MASSDIA(SELF%YRML_GCONF%GEOM,YDFIELDS%YRGFL,YDFIELDS%YRSURF,SELF%YRML_GCONF,SELF%YRML_CHEM%YRCOMPO, &
    & SELF%YRML_CHEM%YRCHEM,SELF%YRML_PHY_G%YRDPHY, YDFIELDS%YRSPEC)
ENDIF

CALL MODEL_UNSET(SELF)

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_FINALIZE',1,ZHOOK_HANDLE)

END SUBROUTINE MODEL_FINALIZE


END SUBMODULE
