! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

SUBMODULE (MODEL_MOD) MODEL_MOD_MODEL_SET
IMPLICIT NONE

CONTAINS

MODULE SUBROUTINE MODEL_SET(SELF)

USE PARKIND1    , ONLY : JPRB, JPIM
USE YOMHOOK     , ONLY : LHOOK, DR_HOOK, JPHOOK
!!USE YOMDIMF     , ONLY : YRDIMF
USE YOMDPHY     , ONLY : YRDPHY
!!USE YOMSLPHY    , ONLY : YRSLPHY
USE YOM_YGFL    , ONLY : YGFL
!!USE YOMDYN      , ONLY : YRDYN
!!USE YOMRIP      , ONLY : YRRIP
!!USE YOERIP      , ONLY : YRERIP
!!USE YOMOZO      , ONLY : YROZO
!!USE INTDYNSL_MOD, ONLY : YYTLSCAW, YYTLSCAWH, YYTRSCAW, YYTRSCAWH, YYTSCO, YYTCCO
!!USE YOMCHEM     , ONLY : YRCHEM
!!USE YOMCOMPO    , ONLY : YRCOMPO
!!USE YOECLD      , ONLY : YRECLD
!!USE YOECND      , ONLY : YRECND
!!USE YOECUMF     , ONLY : YRECUMF
!!USE YOECUMF2    , ONLY : YRECUMF2
!!USE YOMCUMFS    , ONLY : YRCUMFS
!!USE YOEGWD      , ONLY : YREGWD
!!USE YOEGWWMS    , ONLY : YREGWWMS
!!USE YOMRADF     , ONLY : YRRADF
USE YOERAD      , ONLY : YRERAD ! used in obs operator
!!USE RADIATION_SETUP, ONLY : YRADIATION
!!USE YOEOVLP     , ONLY : YREOVLP
!!USE YOENEUR     , ONLY : YRENEUR
!!USE YOELWRAD    , ONLY : YRELWRAD
!!USE YOEAERD     , ONLY : YREAERD
!!USE YOMAERD15   , ONLY : YRAERD15
USE YOEAERATM   , ONLY : YREAERATM ! used in obs operator
!!USE YOE_UVRAD   , ONLY : YREUVRAD
!!USE YOECLDP     , ONLY : YRECLDP
!!USE YOEWCOU     , ONLY : YREWCOU
USE YOEPHLI     , ONLY : YREPHLI !! still used in obs stuff at CY45
!!USE YOPHNC      , ONLY : YRPHNC
!!USE YOPHLC      , ONLY : YRPHLC
USE YOEAERLID   , ONLY : YREAERLID
!!USE YOEAERMAP   , ONLY : YREAERMAP
USE YOEAERSNK   , ONLY : YREAERSNK
USE YOEAERSRC   , ONLY : YREAERSRC
USE YOEAERVOL   , ONLY : YREAERVOL
!!USE YOEDBUG     , ONLY : YREDBUG
USE YOEPHY      , ONLY : YREPHY
!!USE YOMMCC      , ONLY : YRMCC
!!USE YOMCOM      , ONLY : YRCOM
!!USE YOMCOU      , ONLY : YRCOU
!!USE YOMSLREP    , ONLY : YRSLREP
!!USE YOMNCL      , ONLY : YRNCL
!!USE YOEGWDWMS   , ONLY : YREGWDWMS
!!USE YOMSRFTLAD  , ONLY : YRSRFTLAD
!!USE YOMRCOEF    , ONLY : YRRCOEF
!!USE YOMTNH      , ONLY : YRTNH
!!USE YOMCDDH     , ONLY : YRCDDH
!!USE YOMLDDH     , ONLY : YRLDDH
!!USE YOMMDDH     , ONLY : YRMDDH
!!USE YOMSDDH     , ONLY : YRSDDH
!!USE YOMTDDH     , ONLY : YRTDDH
!!USE YOMGPDDH    , ONLY : YRGPDDH
!!USE YOMPADDH    , ONLY : YRPADDH
!!USE YOMSPDDH    , ONLY : YRSPDDH
!!USE PTRGPPC     , ONLY : YRPTRGPPC
!!USE PTRSLB1     , ONLY : YRPTRSLB1
!!USE PTRSLB2     , ONLY : YRPTRSLB2
!!USE PTRSLB15    , ONLY : YRPTRSLB15
!!USE YOMPRAD     , ONLY : RADGRID, YRAD_GSGEOM
!!USE YOERDI      , ONLY : YRERDI
!!USE YOMCFU      , ONLY : YRCFU
!!USE YOMXFU      , ONLY : YRXFU
!!USE STOPH_MIX   , ONLY : YRSTOPH
!!USE YOE_CUCONVCA, ONLY : YRECUCONVCA
!!USE YOMGFUB     , ONLY : GFUBUF
!!USE YOMXFUB     , ONLY : XFUBUF
!!USE YOMGPPCB    , ONLY : GPPCBUF
!!USE YOMRANDOM_STREAMS, ONLY : YR_RANDOM_STREAMS
!!USE YOE_MCICA   , ONLY : YREMCICA
!!USE YOMTRC      , ONLY : YRTRC
!!USE YOMSPHYHIST , ONLY : GPHIST
!!USE SPNG_MOD    , ONLY : YRSPNG
! ALADIN modules and structures
!USE YEMDYN      , ONLY : YREDYN
!USE YEMGEO      , ONLY : YREGEO
!USE YEMGSL      , ONLY : YREGSL
!USE YEMMP       , ONLY : YREMP
! Physic modules and structures
!!USE YOMCVMNH    , ONLY : YRCVMNH
USE YOMPHY      , ONLY : YRPHY
USE YOMPHY0     , ONLY : YRPHY0
USE YOMPHY1     , ONLY : YRPHY1
USE YOMPHY2     , ONLY : YRPHY2
!!USE YOMPHY3     , ONLY : YRPHY3
!!USE YOMPHYDS    , ONLY : YRPHYDS
!!USE YOMTOPH     , ONLY : YRTOPH
!!USE YOMVDOZ     , ONLY : YRVDOZ
!!USE YOMSIMPHL   , ONLY : YRSIMPHL
!!USE YOMARPHY    , ONLY : YRARPHY
!!USE YOMPARAR    , ONLY : YRPARAR
!!USE YOMMSE      , ONLY : YRMSE
USE YOMLOUIS    , ONLY : YRLOUIS
IMPLICIT NONE

TYPE(MODEL), TARGET, INTENT(IN) :: SELF

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_SET',0,ZHOOK_HANDLE)

!!YRDIMF            => SELF%YRML_GCONF%YRDIMF
YRDPHY            => SELF%YRML_PHY_G%YRDPHY
!!YRSLPHY           => SELF%YRML_PHY_G%YRSLPHY
YGFL              => SELF%YRML_GCONF%YGFL     !! remove after cleaning up calls to GPRCPTL in op_obs
!!YRDYN             => SELF%YRML_DYN%YRDYN
!!YREDYN            => SELF%YRML_DYN%YREDYN
!!YRRIP             => SELF%YRML_GCONF%YRRIP
!!YRERIP            => SELF%YRML_PHY_RAD%YRERIP
!!YROZO             => SELF%YRML_CHEM%YROZO
!!YYTLSCAW          => SELF%YRML_DYN%YYTLSCAW
!!YYTLSCAWH         => SELF%YRML_DYN%YYTLSCAWH
!!YYTRSCAW          => SELF%YRML_DYN%YYTRSCAW
!!YYTRSCAWH         => SELF%YRML_DYN%YYTRSCAWH
!!YYTSCO            => SELF%YRML_DYN%YYTSCO
!!YYTCCO            => SELF%YRML_DYN%YYTCCO
!!YRCHEM            => SELF%YRML_CHEM%YRCHEM
!!!YRCOMPO           => SELF%YRCOMPO
!!YRECLD            => SELF%YRML_PHY_EC%YRECLD
!!YRECND            => SELF%YRML_PHY_EC%YRECND
!!YRECUMF           => SELF%YRML_PHY_EC%YRECUMF
!!YRECUMF2          => SELF%YRML_PHY_SLIN%YRECUMF2
!!YRCUMFS           => SELF%YRML_PHY_SLIN%YRCUMFS
!!YREGWD            => SELF%YRML_PHY_EC%YREGWD
!!YREGWWMS          => SELF%YRML_PHY_EC%YREGWWMS
!!YRRADF            => SELF%YRML_PHY_RAD%YRRADF
YRERAD            => SELF%YRML_PHY_RAD%YRERAD
!!YRADIATION        => SELF%YRML_PHY_RAD%YRADIATION
!!YREOVLP           => SELF%YRML_PHY_RAD%YREOVLP
!!YRENEUR           => SELF%YRML_PHY_RAD%YRENEUR
!!YRELWRAD          => SELF%YRML_PHY_RAD%YRELWRAD
!!YREAERD           => SELF%YRML_PHY_RAD%YREAERD
!!YRAERD15          => SELF%YRML_PHY_RAD%YRAERD15
YREAERATM         => SELF%YRML_PHY_RAD%YREAERATM
!!YREUVRAD          => SELF%YRML_PHY_RAD%YREUVRAD
!!YRTILEPROP        => SELF%YRTILEPROP
!!YRECLDP           => SELF%YRML_PHY_EC%YRECLDP
!!YREWCOU           => SELF%YREWCOU
YREPHLI           => SELF%YRML_PHY_SLIN%YREPHLI
!!YRPHNC            => SELF%YRML_PHY_SLIN%YRPHNC
!!YRPHLC            => SELF%YRML_PHY_SLIN%YRPHLC
YREAERLID         => SELF%YRML_PHY_AER%YREAERLID
!!YREAERMAP         => SELF%YRML_PHY_AER%YREAERMAP
YREAERSNK         => SELF%YRML_PHY_AER%YREAERSNK
YREAERSRC         => SELF%YRML_PHY_AER%YREAERSRC
YREAERVOL         => SELF%YRML_PHY_AER%YREAERVOL
!!YREDBUG           => SELF%YRML_PHY_AER%YREDBUG
YREPHY            => SELF%YRML_PHY_EC%YREPHY
!!YRMCC             => SELF%YRML_AOC%YRMCC
!!YRCOM             => SELF%YRML_AOC%YRCOM
!!YRCOU             => SELF%YRML_AOC%YRCOU
!!YRSLREP           => SELF%YRML_DYN%YRSLREP
!!YRNCL             => SELF%YRML_PHY_SLIN%YRNCL
!!YREGWDWMS         => SELF%YRML_PHY_SLIN%YREGWDWMS
!!YRSRFTLAD         => SELF%YRML_PHY_SLIN%YRSRFTLAD
!!YRRCOEF           => SELF%YRML_PHY_RAD%YRRCOEF
!!YRTNH             => SELF%YRML_DYN%YRTNH
!!YRCDDH            => SELF%YRML_DIAG%YRCDDH
!!YRLDDH            => SELF%YRML_DIAG%YRLDDH
!!YRMDDH            => SELF%YRML_DIAG%YRMDDH
!!YRSDDH            => SELF%YRML_DIAG%YRSDDH
!!YRTDDH            => SELF%YRML_DIAG%YRTDDH
!!YRGPDDH           => SELF%YRML_DIAG%YRGPDDH
!!YRPADDH           => SELF%YRML_DIAG%YRPADDH
!!YRSPDDH           => SELF%YRML_DIAG%YRSPDDH
!!YRPTRGPPC         => SELF%YRML_DYN%YRPTRGPPC
!!YRPTRSLB1         => SELF%YRML_DYN%YRPTRSLB1
!!YRPTRSLB2         => SELF%YRML_DYN%YRPTRSLB2
!!YRPTRSLB15        => SELF%YRML_DYN%YRPTRSLB15
!!RADGRID           => SELF%YRML_PHY_RAD%RADGRID
!!YRAD_GSGEOM       => SELF%YRML_PHY_RAD%YRAD_GSGEOM
!!YRERDI            => SELF%YRML_PHY_RAD%YRERDI
!!YRCFU             => SELF%YRML_DIAG%YRCFU
!!YRXFU             => SELF%YRML_DIAG%YRXFU
!!YR_RANDOM_STREAMS => SELF%YRML_PHY_STOCH%YR_RANDOM_STREAMS
!!YRSTOPH           => SELF%YRML_PHY_STOCH%YRSTOPH
!!YRECUCONVCA       => SELF%YRML_PHY_EC%YRECUCONVCA
!!GFUBUF            => SELF%GFUBUF
!!XFUBUF            => SELF%XFUBUF
!!GPPCBUF           => SELF%GPPCBUF
!!YRCSGEOMAD        => SELF%YRCSGEOMAD     !! moved to GEOMETRY
!!YRCSGEOMAD_NB     => SELF%YRCSGEOMAD_NB
!!YRGSGEOMAD        => SELF%YRGSGEOMAD
!!YRGSGEOMAD_NB     => SELF%YRGSGEOMAD_NB
!!YREMCICA          => SELF%YRML_PHY_RAD%YREMCICA
!!YRTRC             => SELF%YRML_PHY_RAD%YRTRC
!!GPHIST            => SELF%YRML_PHY_SLIN%GPHIST
!!YRSPNG            => SELF%YRML_DYN%YRSPNG
! ALADIN modules and structures
!YREGEO            => SELF%YREGEO
!YREGSL            => SELF%YREGSL
!YREMP             => SELF%YREMP
! Physic modules and structures
!!YRCVMNH           => SELF%YRML_PHY_MF%YRCVMNH
YRPHY             => SELF%YRML_PHY_MF%YRPHY
YRPHY0            => SELF%YRML_PHY_MF%YRPHY0
YRPHY1            => SELF%YRML_PHY_MF%YRPHY1
YRPHY2            => SELF%YRML_PHY_MF%YRPHY2
!!YRPHY3            => SELF%YRML_PHY_MF%YRPHY3
!!YRPHYDS           => SELF%YRML_PHY_MF%YRPHYDS
!!YRTOPH            => SELF%YRML_PHY_MF%YRTOPH
!!YRVDOZ            => SELF%YRML_PHY_MF%YRVDOZ
!!YRSIMPHL          => SELF%YRML_PHY_MF%YRSIMPHL
!!YRARPHY           => SELF%YRML_PHY_MF%YRARPHY
!!YRPARAR           => SELF%YRML_PHY_MF%YRPARAR
!!YRMSE             => SELF%YRML_PHY_MF%YRMSE
YRLOUIS           => SELF%YRML_PHY_MF%YRLOUIS
!YRSL              => SELF%YRML_DYN%YRSL
!YRAD              => SELF%YRAD   !! decide where to put them
!YRRI              => SELF%YRRI
!YRRO              => SELF%YRRO

IF (LHOOK) CALL DR_HOOK('MODEL_MOD:MODEL_SET',1,ZHOOK_HANDLE)

END SUBROUTINE MODEL_SET
END SUBMODULE
