! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE PARCMA
!ODB LEVEL 22R1
!ODB SET $MDI = 2147483647
!==ODB ALIAS tovs IS rtovs
USE PARKIND1 , ONLY : JPIM 
USE PARDIMO  , ONLY : JPXTIM, JPNOTP

IMPLICIT NONE

SAVE

!*    PARCMA - CMA VARIOUS PARAMETERS

!        D. VASILJEVIC    ECMWF    19/09/94

!-----------------------------------------------------------------------

!     CMA EVENTS, FLAGS, CODES ETC. PARAMETERS:
!     -----------------------------------------

!     JPMXPCD     MAX. NO. OF PRESSURE CODES
!     JPMXRE1     MAX. NO. REPORT (PART 1) EVENTS
!     JPMXRE2     MAX. NO. REPORT (PART 2) EVENTS
!     JPMXDE1     MAX. NO. DATUM (PART 1) EVENTS
!     JPMXDE2     MAX. NO. DATUM (PART 2) EVENTS
!     JPMXRBLE    MAX. NO. REPORT BLACKLIST EVENTS
!     JPMXDBLE    MAX. NO. DATUM BLACKLIST EVENTS
!     JPMXSBI1    MAX. NO. OF SATOB I1 CODES
!     JPMXSBI2    MAX. NO. OF SATOB I2I2 CODES


INTEGER(KIND=JPIM) :: JPMXPCD
INTEGER(KIND=JPIM) :: JPMXRE1
INTEGER(KIND=JPIM) :: JPMXRE2
INTEGER(KIND=JPIM) :: JPMXDE1
INTEGER(KIND=JPIM) :: JPMXDE2
INTEGER(KIND=JPIM) :: JPMXRBLE
INTEGER(KIND=JPIM) :: JPMXDBLE
INTEGER(KIND=JPIM) :: JPMXSBI2
INTEGER(KIND=JPIM) :: JPMXSBI1
PARAMETER (JPMXPCD=13)
PARAMETER (JPMXRE1=30)
PARAMETER (JPMXRE2=30)
PARAMETER (JPMXDE1=31)
PARAMETER (JPMXDE2=30)
PARAMETER (JPMXRBLE=32)
PARAMETER (JPMXDBLE=32)
PARAMETER (JPMXSBI2=5)
PARAMETER (JPMXSBI1=5)

!-----------------------------------------------------------------------

!     CMA NO. OF OBS./CODE TYPES, UPDATES, ADD. DEP. ETC. PARAMETERS:
!     --------------------------------------------------------------

!     JPMXOTP     MAX. NO. OF OBS. TYPES
!     JPMXOCT     MAX. NO. OF OBS. CODE TYPES
!     JPMXUP      MAX. NO. UPDATES
!     JPMXENDA    MAX. NO. ensembles
!     JPMXAD      MAX. NO. OF ADDITIONAL DEPARTURES
!     JPMXVAR     MAX. NO. OF CMA VARIABLES
!     JPMXTOCH    MAX. NO. RAD1C CHANNELS (was TOVS CHANNELS)
!     JPXSFPTS    MAX. NO. OF SIM. OBS. FILES PER 6HR TIME SLOT
!     JPXTSL      MAX. NO. OF OUTPUT/INPUT TIME SLOTS
!     JPXSATS     MAX. NO. OF SATELLITES
!     JPMX_LIMB_TAN      MAX. NO. OF TANS IN LIMB TABLE
!     JPMX_AK      MAX. elements of averaging kernels for reo3 data
!     JPMX_RADAR_NIV     MAX. NO. OF LEVELS IN RADAR TABLE
!     JP_NUMEV      MAX. NO. OF RETAINED EIGENVECTORS OF OBS ERR CORR MATRIX
!     JPMXFCDIAG   MAX. NO. OF FORECAST DIAGNOSTICS check forecast_diagnostic.h
INTEGER(KIND=JPIM) :: JPMXOTP
INTEGER(KIND=JPIM) :: JPMXOCT
INTEGER(KIND=JPIM) :: JPMXUP
INTEGER(KIND=JPIM) :: JPMXENKF
INTEGER(KIND=JPIM) :: JPMXENDA
INTEGER(KIND=JPIM) :: JPMXFCDIAG
INTEGER(KIND=JPIM) :: JPMXAD
INTEGER(KIND=JPIM) :: JPMXVAR
INTEGER(KIND=JPIM) :: JPMXTOCH
INTEGER(KIND=JPIM) :: JPXTSL
INTEGER(KIND=JPIM) :: JPXSATS
INTEGER(KIND=JPIM) :: JPMX_LIMB_TAN
INTEGER(KIND=JPIM) :: JPMX_AK
INTEGER(KIND=JPIM) :: JPMX_RADAR_NIV
INTEGER(KIND=JPIM) :: JP_NUMEV
PARAMETER (JPMXOTP=JPNOTP)
PARAMETER (JPMXOCT=14)
PARAMETER (JPMXUP=10)
PARAMETER (JPMXENKF=120)
PARAMETER (JPMXENDA=100)
PARAMETER (JPMXFCDIAG=20)
PARAMETER (JPMXAD=20)
PARAMETER (JPMXVAR=112) ! AJGDB should be obselete but is used in MF setcomcm.F90 and affects o2e_initlong.F90
PARAMETER (JPMXTOCH=8461)
PARAMETER (JPXTSL=JPXTIM)
PARAMETER (JPXSATS=6)
PARAMETER (JPMX_LIMB_TAN=17)
PARAMETER (JPMX_AK=50)
PARAMETER (JPMX_RADAR_NIV=15)
PARAMETER (JP_NUMEV=1)
!-----------------------------------------------------------------------

END MODULE PARCMA
