! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE TM5_CHEM_MODULE

USE PARKIND1  ,ONLY : JPIM     ,JPRB

IMPLICIT NONE

SAVE

  INTEGER(KIND=JPIM), PARAMETER  :: NTRACE = 74  ! All tracers for chemistry

  !
  ! components numbers
  !
  INTEGER(KIND=JPIM), PARAMETER :: IO3=1
  INTEGER(KIND=JPIM), PARAMETER :: INOX=2
  INTEGER(KIND=JPIM), PARAMETER :: IH2O2=3 
  INTEGER(KIND=JPIM), PARAMETER :: ICH4=4 
  INTEGER(KIND=JPIM), PARAMETER :: ICO=5
  INTEGER(KIND=JPIM), PARAMETER :: IHNO3=6
  INTEGER(KIND=JPIM), PARAMETER :: ICH3O2H=7 
  INTEGER(KIND=JPIM), PARAMETER :: ICH2O=8 
  INTEGER(KIND=JPIM), PARAMETER :: IPAR=9
  INTEGER(KIND=JPIM), PARAMETER :: IETH=10 
  INTEGER(KIND=JPIM), PARAMETER :: IOLE=11
  INTEGER(KIND=JPIM), PARAMETER :: IALD2=12
  INTEGER(KIND=JPIM), PARAMETER :: IPAN=13 
  INTEGER(KIND=JPIM), PARAMETER :: IROOH=14
  INTEGER(KIND=JPIM), PARAMETER :: IORGNTR=15
  INTEGER(KIND=JPIM), PARAMETER :: IISOP=16
  INTEGER(KIND=JPIM), PARAMETER :: ISO2=17
  INTEGER(KIND=JPIM), PARAMETER :: IDMS=18 
  INTEGER(KIND=JPIM), PARAMETER :: INH3=19 
  INTEGER(KIND=JPIM), PARAMETER :: ISO4=20 
  INTEGER(KIND=JPIM), PARAMETER :: INH4=21 
  INTEGER(KIND=JPIM), PARAMETER :: IMSA=22
  INTEGER(KIND=JPIM), PARAMETER :: IMGLY=23
  ! marked tracers
  INTEGER(KIND=JPIM), PARAMETER :: IO3S=24   ! stratospheric o3 tracer   

  INTEGER(KIND=JPIM), PARAMETER :: IRN222=25
  INTEGER(KIND=JPIM), PARAMETER :: IPB210=26

  INTEGER(KIND=JPIM), PARAMETER :: INO=27  !in C-IFS also transport NOx - components ! ~ dummy naming...
  INTEGER(KIND=JPIM), PARAMETER :: IHO2=28 
  INTEGER(KIND=JPIM), PARAMETER :: ICH3O2=29 
  INTEGER(KIND=JPIM), PARAMETER :: IOH=30
  INTEGER(KIND=JPIM), PARAMETER :: INO2=31 !in C-IFS also transport NOx - components ! ~ dummy naming...
  INTEGER(KIND=JPIM), PARAMETER :: INO3=32 !in C-IFS also transport NOx - components ! ~ dummy naming...
  INTEGER(KIND=JPIM), PARAMETER :: IN2O5=33 !in C-IFS also transport NOx - components ! ~ dummy naming...
  INTEGER(KIND=JPIM), PARAMETER :: IHNO4=34  !in C-IFS also transport NOx - components ! ~ dummy naming...
  INTEGER(KIND=JPIM), PARAMETER :: IC2O3=35 
  INTEGER(KIND=JPIM), PARAMETER :: IROR=36
  INTEGER(KIND=JPIM), PARAMETER :: IRXPAR=37 
  INTEGER(KIND=JPIM), PARAMETER :: IXO2=38
  INTEGER(KIND=JPIM), PARAMETER :: IXO2N=39
  INTEGER(KIND=JPIM), PARAMETER :: INH2=40
  INTEGER(KIND=JPIM), PARAMETER :: IPSC=41
  INTEGER(KIND=JPIM), PARAMETER :: ICH3OH=42
  INTEGER(KIND=JPIM), PARAMETER :: IHCOOH=43
  INTEGER(KIND=JPIM), PARAMETER :: IMCOOH=44
  INTEGER(KIND=JPIM), PARAMETER :: IC2H6=45
  INTEGER(KIND=JPIM), PARAMETER :: IETHOH=46
  INTEGER(KIND=JPIM), PARAMETER :: IC3H8=47
  INTEGER(KIND=JPIM), PARAMETER :: IC3H6=48
  INTEGER(KIND=JPIM), PARAMETER :: ITERP=49
  INTEGER(KIND=JPIM), PARAMETER :: IISPD=50
  INTEGER(KIND=JPIM), PARAMETER :: INO3_A=51
  INTEGER(KIND=JPIM), PARAMETER :: IACET=52
  INTEGER(KIND=JPIM), PARAMETER :: IACO2=53
  INTEGER(KIND=JPIM), PARAMETER :: IIC3H7O2=54
  INTEGER(KIND=JPIM), PARAMETER :: IHYPROPO2=55
  !VH INTEGER(KIND=JPIM), PARAMETER :: IOCS=xxx ! Exclude OCS from tropospheric chemistry. Filled with zero
  INTEGER(KIND=JPIM), PARAMETER :: ISO3=56
  INTEGER(KIND=JPIM), PARAMETER :: ICH3O2NO2=57 
  INTEGER(KIND=JPIM), PARAMETER :: IHONO=58 
  !
  INTEGER(KIND=JPIM), PARAMETER :: IHCN=59
  INTEGER(KIND=JPIM), PARAMETER :: ICH3CN=60
  !
  INTEGER(KIND=JPIM), PARAMETER :: IXYL=61
  INTEGER(KIND=JPIM), PARAMETER :: ITOL=62 
  INTEGER(KIND=JPIM), PARAMETER :: IAROO2=63 
  ! Isoprene degredation products 
  INTEGER(KIND=JPIM), PARAMETER :: IHPALD1=64
  INTEGER(KIND=JPIM), PARAMETER :: IHPALD2=65 
  INTEGER(KIND=JPIM), PARAMETER :: IISOPOOH=66
  INTEGER(KIND=JPIM), PARAMETER :: IGLY=67         
  INTEGER(KIND=JPIM), PARAMETER :: IGLYALD=68
  INTEGER(KIND=JPIM), PARAMETER :: IHYAC=69
  ! Isoprene peroxy from LIM0    
  INTEGER(KIND=JPIM), PARAMETER :: IISOPBO2=70
  INTEGER(KIND=JPIM), PARAMETER :: IISOPDO2=71  
  !
  INTEGER(KIND=JPIM), PARAMETER :: ISOG1=72
  INTEGER(KIND=JPIM), PARAMETER :: ISOG2A=73
  INTEGER(KIND=JPIM), PARAMETER :: ISOG2B=74
  INTEGER(KIND=JPIM), PARAMETER :: IVSO2=59

  ! Dummy index to track jo2 budget (but it doesn't work). Keep io2 < NCHEM+3
  INTEGER(KIND=JPIM), PARAMETER :: IO2 = NTRACE + 2

  !
  ! molar weights of components
  ! 
  REAL(KIND=JPRB),    PARAMETER :: XMAIR=28.9644_JPRB 
  REAL(KIND=JPRB),    PARAMETER :: XMH2O=18.0152_JPRB
  REAL(KIND=JPRB),    PARAMETER :: XMNH3=17.0_JPRB
  REAL(KIND=JPRB),    PARAMETER :: XMN2O5=108.0_JPRB
  !
  ! number of chemistry to aerosol variables
  !
  INTEGER(KIND=JPIM), PARAMETER :: NCHEM2AER=6
  !
  ! number of chemistry to GHG variables
  !
  INTEGER(KIND=JPIM), PARAMETER :: NCHEM2GHG=2
  !
  ! Reaction data:
  !
  INTEGER(KIND=JPIM), PARAMETER :: NREAC=140      !number of thermal reactions
  INTEGER(KIND=JPIM), PARAMETER :: NREACW=4       !number of aqueous phase reactions
  INTEGER(KIND=JPIM), PARAMETER :: NTHIGH=320
  INTEGER(KIND=JPIM), PARAMETER :: NTLOW=165
  INTEGER(KIND=JPIM), PARAMETER :: NTEMP=155  ! = nthigh-ntlow
  INTEGER(KIND=JPIM), PARAMETER :: NRAT=NREAC+50
  CHARACTER(LEN=12), DIMENSION(NREAC),PARAMETER :: RATNAM=(/&
    &   'RNOO3       ','RHO2NO      ','RMO2NO      ','RNO2OH      ','ROHHNO3     ',&
    &   'RNO2O3      ','RNONO3      ','RNO2NO3     ','RN2O5       ','ROHHONO     ',&
    &   'RHONO       ','RHNO4OH     ','RNO2HO2     ','RHNO4M      ','RMENO2      ',&
    &   'RMENO2M     ','RODM        ','RH2OOD      ','RO3HO2      ','RCOOH       ',&
    &   'RO3OH       ','RHPOH       ','RFRMOH      ','RCH4OH      ','ROHMPER     ',&
    &   'ROHROOH     ','RMO2HO2A    ','RMO2HO2B    ','RMO2MO2     ','RHO2OH      ',&
    &   'RHO2HO2     ','RN2O5AQ     ','RN2O5L      ','RH2OH       ','RC41        ',&
    &   'RC43        ','RC44        ','RC46        ','RC47        ','RC48        ',&
    &   'RC49        ','RC50A       ','KC50B       ','RC52        ','RC53        ',&
    &   'RC54        ','RC57        ','RC58        ','RC59        ','RC61        ',&
    &   'RC62        ','RC73        ','RC76        ','RC77        ','RC78        ',&
    &   'RC79        ','RC80        ','RC81        ','RC82        ','RC83        ',&
    &   'RC84        ','RC85        ','RCDMSOHa    ','RCDMSOHb    ','RCDMSNO3    ',&
    &   'RCSO2OH     ','RCNH3SO4    ','RCNH3OH     ','RCNH2OH     ','RCNH2NO     ',&
    &   'RCNH2NO2    ','RCNH2HO2    ','RCNH2O2     ','ROHCH3OH    ','ROHHCOOH    ',&
    &   'RNO3HO2     ','RNO3MO2     ','RNO3C2O3    ','RNO3XO2     ','RMCOOH      ',&
    &   'ROHC2H6     ','ROHETHOH    ','ROHC3H8     ','ROHC3H6     ','RO3C3H6     ',&
    &   'RNO3C3H6    ','ROHTERP     ','RO3TERP     ','RNO3TERP    ','ROHISPD     ',&
    &   'RO3ISPD     ','RNO3ISPD    ','DRN222      ','RCO3PO3     ','RCO3PO2     ',&
    &   'ROHACET     ','RACO2HO2    ','RACO2MO2    ','RACO2NO     ','RACO2XO2    ',&
    &   'RXO2XO2N    ','RXO2N       ','RN205AER    ','RHO2AER     ','RNO3AER     ',&
    &   'RHO2L       ','RNOHYPRO    ','RHO2HYPR    ','RNOC3H7     ','RHO2C3H7    ',&
    &   'RSO2O3      ','RSO3H2O     ','ROCSOH      ','ROHHCN      ','ROHCH3CN    ',&
    &   'ROHXYL      ','RO3XYL      ','RNO3XYL     ','ROHTOL      ','RO3TOL      ',&
    &   'RNO3XYL     ','RAROO2NO    ','R2AROO2     ','RAR002HO2   ','RAROO2XO2   ',&
    &   'RISOPBO2A   ','RISOPBO2B   ','RISOPDO2A   ','RISOPDO2B   ','RISOPBO2HO2 ',&
    &   'RISOPBO2NO  ','RISOPDO2HO2 ','RISOPDO2NO  ','RISOPOOHOH  ','RHPALD1OH   ',&
    &   'RHPALD2OH   ','RGLYOH      ','RGLYALDOH   ','RHYACOH     ','RSOA_AG     '/)

  CHARACTER(LEN=8), DIMENSION(NREACW),PARAMETER :: RWNAM = &
    &   (/'kso2o3  ','kso2hp  ','knh3so4 ','void    '/)
  !
  ! reaction rates
  !
  INTEGER(KIND=JPIM), PARAMETER :: KNOO3=1
  INTEGER(KIND=JPIM), PARAMETER :: KHO2NO=2
  INTEGER(KIND=JPIM), PARAMETER :: KMO2NO=3
  INTEGER(KIND=JPIM), PARAMETER :: KNO2OH=4
  INTEGER(KIND=JPIM), PARAMETER :: KOHHNO3=5 
  INTEGER(KIND=JPIM), PARAMETER :: KNO2O3=6
  INTEGER(KIND=JPIM), PARAMETER :: KNONO3=7
  INTEGER(KIND=JPIM), PARAMETER :: KNO2NO3=8
  INTEGER(KIND=JPIM), PARAMETER :: KN2O5=9
  INTEGER(KIND=JPIM), PARAMETER :: KOHHONO=10  
  INTEGER(KIND=JPIM), PARAMETER :: KHONO=11  
  INTEGER(KIND=JPIM), PARAMETER :: KHNO4OH=12 
  INTEGER(KIND=JPIM), PARAMETER :: KNO2HO2=13
  INTEGER(KIND=JPIM), PARAMETER :: KHNO4M=14
  INTEGER(KIND=JPIM), PARAMETER :: KMENO2=15
  INTEGER(KIND=JPIM), PARAMETER :: KMENO2M=16    
  INTEGER(KIND=JPIM), PARAMETER :: KODM=17
  INTEGER(KIND=JPIM), PARAMETER :: KH2OOD=18
  INTEGER(KIND=JPIM), PARAMETER :: KO3HO2=19 
  INTEGER(KIND=JPIM), PARAMETER :: KCOOH=20
  INTEGER(KIND=JPIM), PARAMETER :: KO3OH=21
  INTEGER(KIND=JPIM), PARAMETER :: KHPOH=22
  INTEGER(KIND=JPIM), PARAMETER :: KFRMOH=23
  INTEGER(KIND=JPIM), PARAMETER :: KCH4OH=24 
  INTEGER(KIND=JPIM), PARAMETER :: KOHMPER=25
  INTEGER(KIND=JPIM), PARAMETER :: KOHROOH=26
  INTEGER(KIND=JPIM), PARAMETER :: KMO2HO2A=27
  INTEGER(KIND=JPIM), PARAMETER :: KMO2HO2B=28
  INTEGER(KIND=JPIM), PARAMETER :: KMO2MO2=29 
  INTEGER(KIND=JPIM), PARAMETER :: KHO2OH=30
  INTEGER(KIND=JPIM), PARAMETER :: KHO2HO2=31
  INTEGER(KIND=JPIM), PARAMETER :: KN2O5AQ=32
  INTEGER(KIND=JPIM), PARAMETER :: KN2O5L=33
  INTEGER(KIND=JPIM), PARAMETER :: KH2OH=34
  INTEGER(KIND=JPIM), PARAMETER :: KC41=35
  INTEGER(KIND=JPIM), PARAMETER :: KC43=36
  INTEGER(KIND=JPIM), PARAMETER :: KC44=37
  INTEGER(KIND=JPIM), PARAMETER :: KC46=38
  INTEGER(KIND=JPIM), PARAMETER :: KC47=39 
  INTEGER(KIND=JPIM), PARAMETER :: KC48=40 
  INTEGER(KIND=JPIM), PARAMETER :: KC49=41
  INTEGER(KIND=JPIM), PARAMETER :: KC50A=42
  INTEGER(KIND=JPIM), PARAMETER :: KC50B=43
  INTEGER(KIND=JPIM), PARAMETER :: KC52=44
  INTEGER(KIND=JPIM), PARAMETER :: KC53=45
  INTEGER(KIND=JPIM), PARAMETER :: KC54=46
  INTEGER(KIND=JPIM), PARAMETER :: KC57=47 
  INTEGER(KIND=JPIM), PARAMETER :: KC58=48
  INTEGER(KIND=JPIM), PARAMETER :: KC59=49
  INTEGER(KIND=JPIM), PARAMETER :: KC61=50
  INTEGER(KIND=JPIM), PARAMETER :: KC62=51
  INTEGER(KIND=JPIM), PARAMETER :: KC73=52
  INTEGER(KIND=JPIM), PARAMETER :: KC76=53 
  INTEGER(KIND=JPIM), PARAMETER :: KC77=54
  INTEGER(KIND=JPIM), PARAMETER :: KC78=55
  INTEGER(KIND=JPIM), PARAMETER :: KC79=56
  INTEGER(KIND=JPIM), PARAMETER :: KC80=57
  INTEGER(KIND=JPIM), PARAMETER :: KC81=58
  INTEGER(KIND=JPIM), PARAMETER :: KC82=59 
  INTEGER(KIND=JPIM), PARAMETER :: KC83=60
  INTEGER(KIND=JPIM), PARAMETER :: KC84=61
  INTEGER(KIND=JPIM), PARAMETER :: KC85=62
  INTEGER(KIND=JPIM), PARAMETER :: KDMSOHA=63
  INTEGER(KIND=JPIM), PARAMETER :: KDMSOHB=64
  INTEGER(KIND=JPIM), PARAMETER :: KDMSNO3=65
  INTEGER(KIND=JPIM), PARAMETER :: KSO2OH=66
  INTEGER(KIND=JPIM), PARAMETER :: KNH3SO4=67
  INTEGER(KIND=JPIM), PARAMETER :: KNH3OH=68
  INTEGER(KIND=JPIM), PARAMETER :: KNH2OH=69  
  INTEGER(KIND=JPIM), PARAMETER :: KNH2NO=70
  INTEGER(KIND=JPIM), PARAMETER :: KNH2NO2=71
  INTEGER(KIND=JPIM), PARAMETER :: KNH2HO2=72
  INTEGER(KIND=JPIM), PARAMETER :: KNH2O2=73
  !
  ! additional oxidation of BVOC
  !
  INTEGER(KIND=JPIM), PARAMETER :: KOHCH3OH=74
  INTEGER(KIND=JPIM), PARAMETER :: KOHHCOOH=75
  !
  ! additional NO3 reactions
  !
  INTEGER(KIND=JPIM), PARAMETER :: KNO3HO2=76
  INTEGER(KIND=JPIM), PARAMETER :: KNO3MO2=77
  INTEGER(KIND=JPIM), PARAMETER :: KNO3C2O3=78
  INTEGER(KIND=JPIM), PARAMETER :: KNO3XO2=79
  !
  !
  INTEGER(KIND=JPIM), PARAMETER  :: KOHMCOOH=80
  INTEGER(KIND=JPIM), PARAMETER  :: KOHC2H6=81
  INTEGER(KIND=JPIM), PARAMETER  :: KOHETHOH=82
  !
  ! C3 
  !
  INTEGER(KIND=JPIM), PARAMETER  :: KOHC3H8=83
  INTEGER(KIND=JPIM), PARAMETER  :: KOHC3H6=84
  INTEGER(KIND=JPIM), PARAMETER  :: KO3C3H6=85
  INTEGER(KIND=JPIM), PARAMETER  :: KNO3C3H6=86 
  !
  ! TERP
  !
  INTEGER(KIND=JPIM), PARAMETER  :: KOHTERP=87
  INTEGER(KIND=JPIM), PARAMETER  :: KO3TERP=88
  INTEGER(KIND=JPIM), PARAMETER  :: KNO3TERP=89
  !
  INTEGER(KIND=JPIM), PARAMETER  :: KOHISPD=90
  INTEGER(KIND=JPIM), PARAMETER  :: KO3ISPD=91
  INTEGER(KIND=JPIM), PARAMETER  :: KNO3ISPD=92
  !
  INTEGER(KIND=JPIM), PARAMETER  :: KRN222=93
  ! for JO2
  INTEGER(KIND=JPIM), PARAMETER  :: KO3PO3=94
  INTEGER(KIND=JPIM), PARAMETER  :: KO3PO2=95
  ! Acetone
  INTEGER(KIND=JPIM), PARAMETER  :: KOHACET=96
  INTEGER(KIND=JPIM), PARAMETER  :: KACO2HO2=97
  INTEGER(KIND=JPIM), PARAMETER  :: KACO2MO2=98
  INTEGER(KIND=JPIM), PARAMETER  :: KACO2NO=99
  INTEGER(KIND=JPIM), PARAMETER  :: KACO2XO2=100 ! JEW : ACO2 + XO2 ->   (same as for XO2N)
  !
  ! From CB05
  !
  INTEGER(KIND=JPIM), PARAMETER  :: KXO2XO2N=101
  INTEGER(KIND=JPIM), PARAMETER  :: KXO2N=102
  !
  ! Heterogeneous reaction on aerosol - coupling to aerosol fields
  !
  INTEGER(KIND=JPIM), PARAMETER  :: KN2O5_AER=103
  INTEGER(KIND=JPIM), PARAMETER  :: KHO2_AER=104
  INTEGER(KIND=JPIM), PARAMETER  :: KNO3_AER=105
  INTEGER(KIND=JPIM), PARAMETER  :: KHO2L=106
  !
  ! Reactions for C3H6 and C3H8 oxidation
  !
  INTEGER(KIND=JPIM), PARAMETER  :: KNOIC3H7O2=107
  INTEGER(KIND=JPIM), PARAMETER  :: KHO2IC3H7O2=108
  INTEGER(KIND=JPIM), PARAMETER  :: KNOHYPROPO2=109
  INTEGER(KIND=JPIM), PARAMETER  :: KHO2HYPROPO2=110
  !
  ! Extended S-reactions
  !
  INTEGER(KIND=JPIM), PARAMETER  :: KSO2O3G=111
  INTEGER(KIND=JPIM), PARAMETER  :: KSO3H2O=112
  INTEGER(KIND=JPIM), PARAMETER  :: KOCSOH=113
  !
  ! BB tracers HCN/CH3CN
  !
  INTEGER(KIND=JPIM), PARAMETER  :: KOHHCN=114
  INTEGER(KIND=JPIM), PARAMETER  :: KOHCH3CN=115
  !
  ! TOL/XYL aromatics from Karl et al, ACP, 2009
  ! 
  INTEGER(KIND=JPIM), PARAMETER  :: KOHTOL=116
  INTEGER(KIND=JPIM), PARAMETER  :: KO3TOL=117
  INTEGER(KIND=JPIM), PARAMETER  :: KNO3TOL=118
  INTEGER(KIND=JPIM), PARAMETER  :: KOHXYL=119
  INTEGER(KIND=JPIM), PARAMETER  :: KO3XYL=120
  INTEGER(KIND=JPIM), PARAMETER  :: KNO3XYL=121
  INTEGER(KIND=JPIM), PARAMETER  :: KAROO2NO=122
  INTEGER(KIND=JPIM), PARAMETER  :: K2AROO2=123
  INTEGER(KIND=JPIM), PARAMETER  :: KAROO2HO2=124
  INTEGER(KIND=JPIM), PARAMETER  :: KAROO2XO2=125 
  !
  !  Isoprene oxidation scheme of Stavrakou/LIM0
  !
  INTEGER(KIND=JPIM), PARAMETER  :: KISOPBO2A=126
  INTEGER(KIND=JPIM), PARAMETER  :: KISOPBO2B=127
  INTEGER(KIND=JPIM), PARAMETER  :: KISOPDO2A=128
  INTEGER(KIND=JPIM), PARAMETER  :: KISOPDO2B=129
  INTEGER(KIND=JPIM), PARAMETER  :: KISOPBO2HO2=130
  INTEGER(KIND=JPIM), PARAMETER  :: KISOPBO2NO=131
  INTEGER(KIND=JPIM), PARAMETER  :: KISOPDO2HO2=132
  INTEGER(KIND=JPIM), PARAMETER  :: KISOPDO2NO=133
  INTEGER(KIND=JPIM), PARAMETER  :: KISOPOOHOH=134
  INTEGER(KIND=JPIM), PARAMETER  :: KHPALD1OH=135
  INTEGER(KIND=JPIM), PARAMETER  :: KHPALD2OH=136
  INTEGER(KIND=JPIM), PARAMETER  :: KGLYOH=137
  INTEGER(KIND=JPIM), PARAMETER  :: KGLYALDOH=138
  INTEGER(KIND=JPIM), PARAMETER  :: KHYACOH=139   
  INTEGER(KIND=JPIM), PARAMETER  :: KSOA_AG=140  
 
  !
  ! additional PARAMETERs needed for 3-body and other reactions
  !
  INTEGER(KIND=JPIM), PARAMETER :: KNO2OHA=NREAC+1
  INTEGER(KIND=JPIM), PARAMETER :: KNO2OHB=NREAC+2
  INTEGER(KIND=JPIM), PARAMETER :: KOHHNO3A=NREAC+3
  INTEGER(KIND=JPIM), PARAMETER :: KOHHNO3B=NREAC+4
  INTEGER(KIND=JPIM), PARAMETER :: KOHHNO3C=NREAC+5
  INTEGER(KIND=JPIM), PARAMETER :: KNO2NO3A=NREAC+6   
  INTEGER(KIND=JPIM), PARAMETER :: KNO2NO3B=NREAC+7
  INTEGER(KIND=JPIM), PARAMETER :: KHONOA=NREAC+8   
  INTEGER(KIND=JPIM), PARAMETER :: KHONOB=NREAC+9  
  INTEGER(KIND=JPIM), PARAMETER :: KNO2HO2A=NREAC+10
  INTEGER(KIND=JPIM), PARAMETER :: KNO2HO2B=NREAC+11
  INTEGER(KIND=JPIM), PARAMETER :: KMENO2A=NREAC+12
  INTEGER(KIND=JPIM), PARAMETER :: KMENO2B=NREAC+13      
  INTEGER(KIND=JPIM), PARAMETER :: KHO2HO2A=NREAC+14
  INTEGER(KIND=JPIM), PARAMETER :: KHO2HO2B=NREAC+15
  INTEGER(KIND=JPIM), PARAMETER :: KHO2HO2C=NREAC+16
  INTEGER(KIND=JPIM), PARAMETER :: KC47A=NREAC+17
  INTEGER(KIND=JPIM), PARAMETER :: KC47B=NREAC+18 
  INTEGER(KIND=JPIM), PARAMETER :: KC61A=NREAC+19
  INTEGER(KIND=JPIM), PARAMETER :: KC61B=NREAC+20 
  INTEGER(KIND=JPIM), PARAMETER :: KSO2OHA=NREAC+21
  INTEGER(KIND=JPIM), PARAMETER :: KSO2OHB=NREAC+22
  INTEGER(KIND=JPIM), PARAMETER :: KDMSOHC=NREAC+23
  INTEGER(KIND=JPIM), PARAMETER :: KCOOHA=NREAC+24
  INTEGER(KIND=JPIM), PARAMETER :: KCOOHB=NREAC+25
  INTEGER(KIND=JPIM), PARAMETER :: KCOOHC=NREAC+26
  INTEGER(KIND=JPIM), PARAMETER :: KCOOHD=NREAC+27  
  INTEGER(KIND=JPIM), PARAMETER :: KOHMCHO=NREAC+28 
  INTEGER(KIND=JPIM), PARAMETER :: KOHMCH2CHO=NREAC+29  
  INTEGER(KIND=JPIM), PARAMETER :: KNO3MCHO=NREAC+30
  INTEGER(KIND=JPIM), PARAMETER :: KNO3MCH2CHO=NREAC+31
! JEW ; OLE reactions now calcuated using MVK and MACR rates to
!       account for link of OLE to ISOP oxidation . For NO3
  INTEGER(KIND=JPIM), PARAMETER :: KOHOLE=NREAC+32
  
  INTEGER(KIND=JPIM), PARAMETER :: KO3OLE=NREAC+33 
  
  INTEGER(KIND=JPIM), PARAMETER :: KNO3OLE=NREAC+34
  
  INTEGER(KIND=JPIM), PARAMETER :: KOHACETA=NREAC+35
  INTEGER(KIND=JPIM), PARAMETER :: KOHACETB=NREAC+36         

  INTEGER(KIND=JPIM), PARAMETER :: KOHC3H6A=NREAC+37
  INTEGER(KIND=JPIM), PARAMETER :: KOHC3H6B=NREAC+38
  
  INTEGER(KIND=JPIM), PARAMETER :: KO3MVK=NREAC+39
  INTEGER(KIND=JPIM), PARAMETER :: KO3MACR=NREAC+40
  
  INTEGER(KIND=JPIM), PARAMETER :: KOHMVK=NREAC+41
  INTEGER(KIND=JPIM), PARAMETER :: KOHMACR=NREAC+42      
!
!   these are fed directly into to rr in tm5_chem_rates.F90
!     
  INTEGER(KIND=JPIM), PARAMETER :: KC48A=NREAC+43
  INTEGER(KIND=JPIM), PARAMETER :: KC48B=NREAC+44
!   
! parameterization for XYL + O3   
!
  INTEGER(KIND=JPIM), PARAMETER :: KCXYLO3A=NREAC+45
  INTEGER(KIND=JPIM), PARAMETER :: KCXYLO3B=NREAC+46 
!
! Revision of NOx chemistry (Williams et al.)
!
  INTEGER(KIND=JPIM), PARAMETER :: KHNO4A=NREAC+47
  INTEGER(KIND=JPIM), PARAMETER :: KHNO4B=NREAC+48 
  INTEGER(KIND=JPIM), PARAMETER :: KN2O5A=NREAC+49
  INTEGER(KIND=JPIM), PARAMETER :: KN2O5B=NREAC+50 
!
  INTEGER(KIND=JPIM), PARAMETER :: KSO2HP=1
  INTEGER(KIND=JPIM), PARAMETER :: KSO2O3=2

!
! corresponding nrr used for reaction budget calculations
! This table contains the information about which species 
! are involved in each reaction.
!

  INTEGER(KIND=JPIM)         :: IACID, IAIR, IH2O

  INTEGER(KIND=JPIM), DIMENSION(NREAC,2) :: NRR 

  INTEGER(KIND=JPIM), DIMENSION(30) :: NRJ 

  ! nrj and nrr used for reaction budget calculations
  ! INTEGER(KIND=JPIM),DIMENSION(20),PARAMETER    ::  NRJ=(/ &
  ! &         IO3,INO2,IH2O2,IHNO3,IHNO4,IN2O5,ICH2O,ICH2O, &
  ! &         ICH3O2H,INO3,INO3,IPAN,IORGNTR,IALD2,IMGLY,IROOH, & 
  ! &         IO2,IISPD, IACET,IACET, IISOPOOH/) 

  !
  ! heterogeneous chemistry
  !
  
   
  REAL(KIND=JPRB),DIMENSION(NTRACE,NTEMP) :: HENRY   ! heterogeneous removal rates

  ! rates_lut : for reaction rate look up table 
  REAL(KIND=JPRB),DIMENSION(NRAT,NTEMP) :: RATES_LUT

  ! some additional information containing O3 production / loss budget terms
  ! these are stored in the entry 'IEXTR_CHEMX'
  INTEGER(KIND=JPIM),PARAMETER :: NBUD_EXTRA_CHEM = 21
  ! Keep track of photolysis loss budgets for 2 SOA tracers
  INTEGER(KIND=JPIM),PARAMETER :: NSOA_BUDG = 2 
  INTEGER(KIND=JPIM),DIMENSION(NBUD_EXTRA_CHEM), PARAMETER :: CHEM_BUDG   = (/ &
  & KHO2NO, KMO2NO      , KC79        , KO3HO2    , KC58    , &
  & KC62  , KC77        , KO3C3H6     , KO3TERP   , KO3ISPD , &
  & KN2O5L, KSOA_AG    , KN2O5_AER   , KHO2_AER  , KNO3_AER, &
  & KHO2L , KNOHYPROPO2 , KNOIC3H7O2  , KISOPBO2NO, KISOPDO2NO, &
  & KC46 /)
  INTEGER(KIND=JPIM),PARAMETER :: NBUD_EXTRA = NBUD_EXTRA_CHEM+2

  ! uars climatology for HNO3: hno3/o3 ratio at 10 hPa 
  REAL(KIND=JPRB)            :: UARS_HNO3_O3(12,180)

  
  ! HALOE climatology for CH4:  concentrations [ppmv] at 90 and 45 hPa 
  REAL(KIND=JPRB)            :: HALOE_CH4(12,180,2)

  ! SOG yields from precursor reactions. 
  ! Note: BETA1+BETA2 should be < 1 ; likewise for GAMMA1+GAMMA2
  REAL(KIND=JPRB),PARAMETER :: ZALPHA = 0.05  ! C5H8 + O3-> SOG1
  REAL(KIND=JPRB),PARAMETER :: ZBETA1 = 0.6  ! TOL + OH ->SOG2A
  REAL(KIND=JPRB),PARAMETER :: ZBETA2 = 0.3  ! TOL + OH ->SOG2B
  REAL(KIND=JPRB),PARAMETER :: ZGAMMA1= 0.3  ! XYL + OH -> SOG2A
  REAL(KIND=JPRB),PARAMETER :: ZGAMMA2= 0.3  ! XYL + OH -> SOG2B

  REAL(KIND=JPRB),PARAMETER :: ZDELTA = 0.05  ! C5H8+OH -> SOG1
  REAL(KIND=JPRB),PARAMETER :: ZEPSILON1 = 0.15 ! C10H6+OH -> SOG1
  REAL(KIND=JPRB),PARAMETER :: ZEPSILON2 = 0.15 ! C10H16+O3 -> SOG1

  REAL(KIND=JPRB),PARAMETER :: ZPHI1 = 0.3 ! TOL+O3 -> SOG2A
  REAL(KIND=JPRB),PARAMETER :: ZPHI2 = 0.3 ! TOL+O3 -> SOG2B
  REAL(KIND=JPRB),PARAMETER :: ZCHI1 = 0.3 ! XYL+O3 -> SOG2A
  REAL(KIND=JPRB),PARAMETER :: ZCHI2 = 0.3 ! XYL+O3 -> SOG2B

  ! Flexible tracer number for additional chemistry schemes
  INTEGER(KIND=JPIM)   :: IFLRN222
  INTEGER(KIND=JPIM)   :: IFLPB210
  INTEGER(KIND=JPIM)   :: IFLO3
  INTEGER(KIND=JPIM)   :: IFLCO

END MODULE TM5_CHEM_MODULE
