! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Global Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE tm5_kpp_Global

  USE tm5_kpp_Parameters , ONLY:   NVAR, NFIX
  USE PARKIND1           , ONLY:   JPIM     ,JPRB, JPRD
  
  IMPLICIT NONE
  PUBLIC
  SAVE


! Declaration of global variables

! C - Concentration of all species
!  REAL(KIND=JPRB) :: C(NSPEC)
! VAR - Concentrations of variable species (global)
!  REAL(KIND=JPRB) :: VAR(NVAR)
! FIX - Concentrations of fixed species (global)
  REAL(KIND=JPRD) :: FIX(NFIX)
! VAR, FIX are chunks of array C
!      EQUIVALENCE( C(1),VAR(1) )
! RCONST - Rate constants (global)
!  REAL(KIND=JPRB) :: RCONST(NREACT)
! TIME - Current integration time
  REAL(KIND=JPRB) :: TIME
! SUN - Sunlight intensity between [0,1]
  REAL(KIND=JPRB) :: SUN
! TEMP - Temperature
  REAL(KIND=JPRB) :: TEMP
! RTOLS - (scalar) Relative tolerance
  REAL(KIND=JPRD) :: RTOLS
! TSTART - Integration start time
  REAL(KIND=JPRB) :: TSTART
! TEND - Integration end time
  REAL(KIND=JPRB) :: TEND
! DT - Integration step
  REAL(KIND=JPRB) :: DT
! ATOL - Absolute tolerance
  REAL(KIND=JPRD) :: ATOL(NVAR)
! RTOL - Relative tolerance
  REAL(KIND=JPRD) :: RTOL(NVAR)
! STEPMIN - Lower bound for integration step
  REAL(KIND=JPRB) :: STEPMIN
! STEPMAX - Upper bound for integration step
  REAL(KIND=JPRB) :: STEPMAX
! CFACTOR - Conversion factor for concentration units
  REAL(KIND=JPRB) :: CFACTOR
! DDMTYPE - DDM sensitivity w.r.t.: 0=init.val., 1=params
  INTEGER(KIND=JPIM) :: DDMTYPE
  REAL(KIND=JPRD) :: ROUNDOFF_STORE

! INLINED global variable declarations



! INLINED global variable declarations


END MODULE tm5_kpp_Global

