! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
!     Variable naming changed to ECMWF conventions by V. Huijnen
!
!~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE tm5_kpp_Parameters

!  USE tm5_kpp_Precision
  USE PARKIND1 , ONLY :JPIM
  IMPLICIT NONE
  PUBLIC
  SAVE



! NSPEC - Number of chemical species
  INTEGER(KIND=JPIM), PARAMETER :: NSPEC = 71 
! NVAR - Number of Variable species
  INTEGER(KIND=JPIM), PARAMETER :: NVAR = 71 
! NVARACT - Number of Active species
  INTEGER(KIND=JPIM), PARAMETER :: NVARACT = 65 
! NFIX - Number of Fixed species
  INTEGER(KIND=JPIM), PARAMETER :: NFIX = 1 
! NREACT - Number of reactions
  INTEGER(KIND=JPIM), PARAMETER :: NREACT = 160 
! NVARST - Starting of variables in conc. vect.
  INTEGER(KIND=JPIM), PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER(KIND=JPIM), PARAMETER :: NFIXST = 72 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER(KIND=JPIM), PARAMETER :: NONZERO = 614 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER(KIND=JPIM), PARAMETER :: LU_NONZERO = 700
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER(KIND=JPIM), PARAMETER :: CNVAR = 72 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER(KIND=JPIM), PARAMETER :: CNEQN = 161 
! NHESS - Length of Sparse Hessian
  INTEGER(KIND=JPIM), PARAMETER :: NHESS = 524 
! NLOOKAT - Number of species to look at
  INTEGER(KIND=JPIM), PARAMETER :: NLOOKAT = 71 
! NMONITOR - Number of species to monitor
  INTEGER(KIND=JPIM), PARAMETER :: NMONITOR = 1 
! NMASS - Number of atoms to check mass balance
  INTEGER(KIND=JPIM), PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)


  INTEGER(KIND=JPIM), PARAMETER :: ind_Rn = 1 
  INTEGER(KIND=JPIM), PARAMETER :: ind_Pb = 2 
  INTEGER(KIND=JPIM), PARAMETER :: ind_SO4 = 3 
  INTEGER(KIND=JPIM), PARAMETER :: ind_SO3 = 4 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3SO3H = 5 
  INTEGER(KIND=JPIM), PARAMETER :: ind_SOG1 = 6 
  INTEGER(KIND=JPIM), PARAMETER :: ind_SOG2B = 7 
  INTEGER(KIND=JPIM), PARAMETER :: ind_DUMMY = 8 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH4 = 9 
  INTEGER(KIND=JPIM), PARAMETER :: ind_C3H8 = 10 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HCN = 11 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3CN = 12 
  INTEGER(KIND=JPIM), PARAMETER :: ind_OCS = 13 
  INTEGER(KIND=JPIM), PARAMETER :: ind_H2O2 = 14 
  INTEGER(KIND=JPIM), PARAMETER :: ind_SOG2A = 15 
  INTEGER(KIND=JPIM), PARAMETER :: ind_C2H6 = 16 
  INTEGER(KIND=JPIM), PARAMETER :: ind_C2H5OH = 17 
  INTEGER(KIND=JPIM), PARAMETER :: ind_NH3 = 18 
  INTEGER(KIND=JPIM), PARAMETER :: ind_N2O5 = 19 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HONO = 20 
  INTEGER(KIND=JPIM), PARAMETER :: ind_PAN = 21 
  INTEGER(KIND=JPIM), PARAMETER :: ind_DMS = 22 
  INTEGER(KIND=JPIM), PARAMETER :: ind_MCOOH = 23 
  INTEGER(KIND=JPIM), PARAMETER :: ind_RXPAR = 24 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3OH = 25 
  INTEGER(KIND=JPIM), PARAMETER :: ind_SO2 = 26 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HNO4 = 27 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ROR = 28 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3O2NO2 = 29 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3OOH = 30 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HCOOH = 31 
  INTEGER(KIND=JPIM), PARAMETER :: ind_C2H4 = 32 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3COCH3 = 33 
  INTEGER(KIND=JPIM), PARAMETER :: ind_GLYALD = 34 
  INTEGER(KIND=JPIM), PARAMETER :: ind_NH2 = 35 
  INTEGER(KIND=JPIM), PARAMETER :: ind_TOL = 36 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HYAC = 37 
  INTEGER(KIND=JPIM), PARAMETER :: ind_XYL = 38 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HYPROPO2 = 39 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HNO3 = 40 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HPALD1 = 41 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HPALD2 = 42 
  INTEGER(KIND=JPIM), PARAMETER :: ind_IC3H7O2 = 43 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CO = 44 
  INTEGER(KIND=JPIM), PARAMETER :: ind_GLY = 45 
  INTEGER(KIND=JPIM), PARAMETER :: ind_OLE = 46 
  INTEGER(KIND=JPIM), PARAMETER :: ind_C3H6 = 47 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ISOPOOH = 48 
  INTEGER(KIND=JPIM), PARAMETER :: ind_C10H16 = 49 
  INTEGER(KIND=JPIM), PARAMETER :: ind_XO2N = 50 
  INTEGER(KIND=JPIM), PARAMETER :: ind_C5H8 = 51 
  INTEGER(KIND=JPIM), PARAMETER :: ind_MGLYOX = 52 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HCHO = 53 
  INTEGER(KIND=JPIM), PARAMETER :: ind_AROO2 = 54 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ACO2 = 55 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ROOH = 56 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ALD2 = 57 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ISOPDO2 = 58 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ISOPBO2 = 59 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ISPD = 60 
  INTEGER(KIND=JPIM), PARAMETER :: ind_ORGNTR = 61 
  INTEGER(KIND=JPIM), PARAMETER :: ind_O3 = 62 
  INTEGER(KIND=JPIM), PARAMETER :: ind_OH = 63 
  INTEGER(KIND=JPIM), PARAMETER :: ind_HO2 = 64 
  INTEGER(KIND=JPIM), PARAMETER :: ind_CH3O2 = 65 
  INTEGER(KIND=JPIM), PARAMETER :: ind_NO = 66 
  INTEGER(KIND=JPIM), PARAMETER :: ind_NO2 = 67 
  INTEGER(KIND=JPIM), PARAMETER :: ind_NO3 = 68 
  INTEGER(KIND=JPIM), PARAMETER :: ind_C2O3 = 69 
  INTEGER(KIND=JPIM), PARAMETER :: ind_PAR = 70 
  INTEGER(KIND=JPIM), PARAMETER :: ind_XO2 = 71 

! Index declaration for fixed species in C
!   C(ind_spc)


! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)


! NJVRP - Length of sparse Jacobian JVRP
  INTEGER(KIND=JPIM), PARAMETER :: NJVRP = 269 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER(KIND=JPIM), PARAMETER :: NSTOICM = 693 


!~~~>  Statistics on the work performed by the Rosenbrock method
  INTEGER(KIND=JPIM), PARAMETER :: Nfun=1, Njac=2, Nstp=3, Nacc=4, &
                  &     Nrej=5, Ndec=6, Nsol=7, Nsng=8, &
                  &     Ntexit=1, Nhexit=2, Nhnew = 3



END MODULE tm5_kpp_Parameters

