! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE TOVSCV_BASE_MOD
USE PARKIND1, ONLY : JPIM, JPRB
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK
IMPLICIT NONE
PRIVATE :: JPIM, JPRB
TYPE TOVSCV_BASE
INTEGER(KIND=JPIM) :: NVATOVLEN=0
INTEGER(KIND=JPIM) :: NVATOVLENG=0
INTEGER(KIND=JPIM) :: NVATOVV=0
INTEGER(KIND=JPIM),ALLOCATABLE :: NVATOVLENP(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: NVATOVOFF(:)
END TYPE TOVSCV_BASE

CONTAINS
! ------------------------------------------------------------------------------
SUBROUTINE CREATE_TOVSCV_BASE(SELF)
USE YOMMP0   , ONLY : MYPROC,NPROC
USE YOMDIMO  , ONLY : NOBTOVG, NOBTOVBP
USE YOMVAR   , ONLY : LTOVSCV, LCLDSINK
USE DEALLOCATE_IF_ALLOCATED_MOD, ONLY : DEALLOCATE_IF_ALLOCATED

CLASS(TOVSCV_BASE), INTENT(INOUT)  :: SELF
INTEGER(KIND=JPIM) :: J
REAL(KIND=JPHOOK)  :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('TOVSCV_BASE_MOD:CREATE_TOVSCV_BASE',0,ZHOOK_HANDLE)
IF(LTOVSCV) THEN
  CALL DEALLOCATE_IF_ALLOCATED(SELF%NVATOVLENP)
  CALL DEALLOCATE_IF_ALLOCATED(SELF%NVATOVOFF)
  ALLOCATE(SELF%NVATOVLENP(NPROC))  
  ALLOCATE(SELF%NVATOVOFF(NPROC))  
  IF(LCLDSINK) THEN
    SELF%NVATOVV=3
  ELSE
    SELF%NVATOVV = 1
  ENDIF
  SELF%NVATOVLENP(:) = NOBTOVBP(:)
  SELF%NVATOVOFF(1) = 0
  DO J=2,NPROC
    SELF%NVATOVOFF(J)=SELF%NVATOVOFF(J-1)+NOBTOVBP(J-1)
  ENDDO
  SELF%NVATOVLEN = NOBTOVBP(MYPROC)
  SELF%NVATOVLENG = NOBTOVG
ELSE
  SELF%NVATOVV = 0
  SELF%NVATOVLEN = 0
  SELF%NVATOVLENG = 0
ENDIF
IF (LHOOK) CALL DR_HOOK('TOVSCV_BASE_MOD:CREATE_TOVSCV_BASE',1,ZHOOK_HANDLE)

END SUBROUTINE CREATE_TOVSCV_BASE
! ------------------------------------------------------------------------------
SUBROUTINE CHECK_DIMS(CDLABEL,YD1,YD2) 
USE YOMLUN   , ONLY : NULOUT, NULERR
CHARACTER(LEN=*),INTENT(IN)   :: CDLABEL
CLASS(TOVSCV_BASE),INTENT(IN) :: YD1
CLASS(TOVSCV_BASE),INTENT(IN) :: YD2
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('TOVSCV_BASE_MOD:CHECK_DIMS',0,ZHOOK_HANDLE)
IF(YD1%NVATOVLEN /= YD2%NVATOVLEN .OR. YD1%NVATOVV /= YD2%NVATOVV) THEN
  WRITE(NULERR,*) CDLABEL," YD1 ",YD1%NVATOVLEN,YD1%NVATOVV," YD2 ",YD2%NVATOVLEN,YD2%NVATOVV
  WRITE(NULOUT,*) CDLABEL," YD1 ",YD1%NVATOVLEN,YD1%NVATOVV," YD2 ",YD2%NVATOVLEN,YD2%NVATOVV
  CALL ABOR1('TOVSCV_BASE_MOD:CHECK_DIMS - SIZE MISMATCH')
ENDIF
IF (LHOOK) CALL DR_HOOK('TOVSCV_BASE_MOD:CHECK_DIMS',1,ZHOOK_HANDLE)

END SUBROUTINE CHECK_DIMS
! ------------------------------------------------------------------------------
LOGICAL FUNCTION ODB_CHANGED(SELF)
USE YOMDIMO  , ONLY : NOBTOVG, NOBTOVBP
CLASS(TOVSCV_BASE), INTENT(IN)  :: SELF
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

ODB_CHANGED = .NOT. (SELF%NVATOVLENG == NOBTOVG)

END FUNCTION ODB_CHANGED

! ------------------------------------------------------------------------------
SUBROUTINE DEALLOCATE_TOVSCV_BASE(SELF)
USE YOMVAR   , ONLY : LTOVSCV
CLASS(TOVSCV_BASE), INTENT(INOUT)  :: SELF
IF(LTOVSCV) THEN
  DEALLOCATE(SELF%NVATOVLENP)
  DEALLOCATE(SELF%NVATOVOFF)
ENDIF
END SUBROUTINE DEALLOCATE_TOVSCV_BASE
! ------------------------------------------------------------------------------

END MODULE TOVSCV_BASE_MOD
