! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE TYPE_FPFIELDS

USE PARKIND1  ,ONLY : JPIM     ,JPRB
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
USE DEALLOCATE_IF_ALLOCATED_MOD, ONLY : DEALLOCATE_IF_ALLOCATED

IMPLICIT NONE

SAVE

PRIVATE
PUBLIC TFPFIELDS, ALLOC_FPFIELDS, DEALLOC_FPFIELDS, PRINT_FPFIELDS
!     ------------------------------------------------------------------

! === POST-PROCESSED FIELDS === 

! Driven by name (Meteo-France)
!     CFP3DF : names 3D dynamics fields to compute
!     CFP2DF : names 2D dynamics fields to compute
!     CFPPHY : names of physical fields to be post-processed
!     CFPCFU : names of cumulated fluxes fields to be post-processed
!     CFPXFU : names of instantaneous fluxes fields to be post-proc

! Driven by GRIB code (ECMWF)
!     MFP3DFS: Gribcodes of  3D dynamics fields to compute on model levels
!     MFP3DFH: Gribcodes of  3D dynamics fields to compute on H levels
!     MFP3DFT: Gribcodes of  3D dynamics fields to compute on THETA levels
!     MFP3DFV: Gribcodes of  3D dynamics fields to compute on PV levels
!     MFP3DFP: Gribcodes of  3D dynamics fields to compute on P levels
!     MFP3DFI: Gribcodes of  3D dynamics fields to compute on T levels
!     MFP3DFF: Gribcodes of  3D dynamics fields to compute on Flight levels
!     MFP2DF : Gribcodes of  2D dynamics fields to compute
!     MFPPHY : Gribcodes of  physical fields to processed

! Vertical levels
!     RFP3P  : post-processing pressure levels
!     RFP3H  : post-processing height (above orography) levels
!     RFP3TH : post-processing potential temperature levels
!     RFP3PV : post-processing potential vorticity levels
!     RFP3I  : post-processing temperature levels
!     RFP3F  : post-processing height (above sea) levels
!     NRFP3S : post-processing eta levels (CONF. 927 only)

! Number of fields
!     NFP3DF : useful dimension of CFP3DF
!     NFP3DFS: useful dimension of MFP3DFS
!     NFP3DFH: useful dimension of MFP3DFH
!     NFP3DFT: useful dimension of MFP3DFT
!     NFP3DFV: useful dimension of MFP3DFV
!     NFP3DFP: useful dimension of MFP3DFP
!     NFP3DFI: useful dimension of MFP3DFI
!     NFP3DFF: useful dimension of MFP3DFF
!     NFP2DF : useful dimension of CFP2DF
!     NFPPHY : useful dimension of CFPPHY
!     NFPCFU : useful dimension of CFPCFU
!     NFPXFU : useful dimension of CFPXFU
!     NFP3P  : useful dimension of RFP3P
!     NFP3H  : useful dimension of RFP3H
!     NFP3I  : useful dimension of RFP3I
!     NFP3F  : useful dimension of RFP3F
!     NFP3TH : useful dimension of RFP3TH
!     NFP3PV : useful dimension of RFP3PV
!     NFP3S  : useful dimension of NRFP3S

TYPE TFPFIELDS

CHARACTER(LEN = 12), ALLOCATABLE :: CFP3DF(:)
CHARACTER(LEN = 16), ALLOCATABLE :: CFP2DF(:)
CHARACTER(LEN = 16), ALLOCATABLE :: CFPPHY(:)
CHARACTER(LEN = 16), ALLOCATABLE :: CFPCFU(:)
CHARACTER(LEN = 16), ALLOCATABLE :: CFPXFU(:)

INTEGER(KIND=JPIM), ALLOCATABLE :: MFP3DFS(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: MFP3DFP(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: MFP3DFH(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: MFP3DFT(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: MFP3DFV(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: MFP3DFI(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: MFP3DFF(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: MFP2DF(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: MFPPHY(:)

REAL(KIND=JPRB), ALLOCATABLE :: RFP3P(:)
REAL(KIND=JPRB), ALLOCATABLE :: RFP3H(:)
REAL(KIND=JPRB), ALLOCATABLE :: RFP3TH(:)
REAL(KIND=JPRB), ALLOCATABLE :: RFP3PV(:)
REAL(KIND=JPRB), ALLOCATABLE :: RFP3I(:)
REAL(KIND=JPRB), ALLOCATABLE :: RFP3F(:)
INTEGER(KIND=JPIM), ALLOCATABLE :: NRFP3S(:)

INTEGER(KIND=JPIM) :: NFP3P   = 0
INTEGER(KIND=JPIM) :: NFP3H   = 0
INTEGER(KIND=JPIM) :: NFP3TH  = 0
INTEGER(KIND=JPIM) :: NFP3PV  = 0
INTEGER(KIND=JPIM) :: NFP3I   = 0
INTEGER(KIND=JPIM) :: NFP3S   = 0
INTEGER(KIND=JPIM) :: NFP3F   = 0
INTEGER(KIND=JPIM) :: NFP3DFS = 0
INTEGER(KIND=JPIM) :: NFP3DFP = 0
INTEGER(KIND=JPIM) :: NFP3DFH = 0
INTEGER(KIND=JPIM) :: NFP3DFT = 0
INTEGER(KIND=JPIM) :: NFP3DFV = 0
INTEGER(KIND=JPIM) :: NFP3DFI = 0
INTEGER(KIND=JPIM) :: NFP3DFF = 0
INTEGER(KIND=JPIM) :: NFP3DF  = 0
INTEGER(KIND=JPIM) :: NFP2DF  = 0
INTEGER(KIND=JPIM) :: NFPPHY  = 0
INTEGER(KIND=JPIM) :: NFPCFU  = 0
INTEGER(KIND=JPIM) :: NFPXFU  = 0

END TYPE TFPFIELDS

CONTAINS

!-----------------------------------------------------------------------------

SUBROUTINE ALLOC_FPFIELDS(YD)

TYPE(TFPFIELDS), INTENT(INOUT) :: YD

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('TYPE_FPFIELDS:ALLOC_FPFIELDS',0,ZHOOK_HANDLE)

ALLOCATE(YD%CFP3DF(YD%NFP3DF))
YD%CFP3DF(:)=' '
ALLOCATE(YD%CFP2DF(YD%NFP2DF))
YD%CFP2DF(:)=' '
ALLOCATE(YD%CFPPHY(YD%NFPPHY))
YD%CFPPHY(:)=' '
ALLOCATE(YD%CFPCFU(YD%NFPCFU))
YD%CFPCFU(:)=' '
ALLOCATE(YD%CFPXFU(YD%NFPXFU))
YD%CFPXFU(:)=' '

ALLOCATE(YD%MFP3DFS(YD%NFP3DFS))
YD%MFP3DFS(:)=HUGE(1)
ALLOCATE(YD%MFP3DFP(YD%NFP3DFP))
YD%MFP3DFP(:)=HUGE(1)
ALLOCATE(YD%MFP3DFH(YD%NFP3DFH))
YD%MFP3DFH(:)=HUGE(1)
ALLOCATE(YD%MFP3DFT(YD%NFP3DFT))
YD%MFP3DFT(:)=HUGE(1)
ALLOCATE(YD%MFP3DFV(YD%NFP3DFV))
YD%MFP3DFV(:)=HUGE(1)
ALLOCATE(YD%MFP3DFI(YD%NFP3DFI))
YD%MFP3DFI(:)=HUGE(1)
ALLOCATE(YD%MFP3DFF(YD%NFP3DFF))
YD%MFP3DFF(:)=HUGE(1)
ALLOCATE(YD%MFP2DF(YD%NFP2DF))
YD%MFP2DF(:)=HUGE(1)
ALLOCATE(YD%MFPPHY(YD%NFPPHY))
YD%MFPPHY(:)=HUGE(1)

ALLOCATE(YD%RFP3P(YD%NFP3P))
YD%RFP3P(:)=HUGE(1._JPRB)
ALLOCATE(YD%RFP3H(YD%NFP3H))
YD%RFP3H(:)=HUGE(1._JPRB)
ALLOCATE(YD%RFP3TH(YD%NFP3TH))
YD%RFP3TH(:)=HUGE(1._JPRB)
ALLOCATE(YD%RFP3PV(YD%NFP3PV))
YD%RFP3PV(:)=HUGE(1._JPRB)
ALLOCATE(YD%RFP3I(YD%NFP3I))
YD%RFP3I(:)=HUGE(1._JPRB)
ALLOCATE(YD%RFP3F(YD%NFP3F))
YD%RFP3F(:)=HUGE(1._JPRB)
ALLOCATE(YD%NRFP3S(YD%NFP3S))
YD%NRFP3S(:)=HUGE(1_JPIM)

IF (LHOOK) CALL DR_HOOK('TYPE_FPFIELDS:ALLOC_FPFIELDS',1,ZHOOK_HANDLE)

END SUBROUTINE ALLOC_FPFIELDS

SUBROUTINE DEALLOC_FPFIELDS(YD)

TYPE(TFPFIELDS), INTENT(INOUT) :: YD

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('TYPE_FPFIELDS:DEALLOC_FPFIELDS',0,ZHOOK_HANDLE)

CALL DEALLOCATE_IF_ALLOCATED(YD%CFP3DF)
CALL DEALLOCATE_IF_ALLOCATED(YD%CFP2DF)
CALL DEALLOCATE_IF_ALLOCATED(YD%CFPPHY)
CALL DEALLOCATE_IF_ALLOCATED(YD%CFPCFU)
CALL DEALLOCATE_IF_ALLOCATED(YD%CFPXFU)

CALL DEALLOCATE_IF_ALLOCATED(YD%MFP3DFS)
CALL DEALLOCATE_IF_ALLOCATED(YD%MFP3DFP)
CALL DEALLOCATE_IF_ALLOCATED(YD%MFP3DFH)
CALL DEALLOCATE_IF_ALLOCATED(YD%MFP3DFT)
CALL DEALLOCATE_IF_ALLOCATED(YD%MFP3DFV)
CALL DEALLOCATE_IF_ALLOCATED(YD%MFP3DFI)
CALL DEALLOCATE_IF_ALLOCATED(YD%MFP3DFF)
CALL DEALLOCATE_IF_ALLOCATED(YD%MFP2DF)
CALL DEALLOCATE_IF_ALLOCATED(YD%MFPPHY)

CALL DEALLOCATE_IF_ALLOCATED(YD%RFP3P)
CALL DEALLOCATE_IF_ALLOCATED(YD%RFP3H)
CALL DEALLOCATE_IF_ALLOCATED(YD%RFP3TH)
CALL DEALLOCATE_IF_ALLOCATED(YD%RFP3PV)
CALL DEALLOCATE_IF_ALLOCATED(YD%RFP3I)
CALL DEALLOCATE_IF_ALLOCATED(YD%RFP3F)
CALL DEALLOCATE_IF_ALLOCATED(YD%NRFP3S)

IF (LHOOK) CALL DR_HOOK('TYPE_FPFIELDS:DEALLOC_FPFIELDS',1,ZHOOK_HANDLE)

END SUBROUTINE DEALLOC_FPFIELDS

SUBROUTINE PRINT_FPFIELDS(YD,LDARPEGE,KULOUT)

TYPE(TFPFIELDS), INTENT(IN) :: YD
LOGICAL, INTENT(IN) :: LDARPEGE
INTEGER(KIND=JPIM), INTENT(IN) :: KULOUT

INTEGER(KIND=JPIM) :: J
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('TYPE_FPFIELDS:PRINT_FPFIELDS',0,ZHOOK_HANDLE)

WRITE(UNIT=KULOUT,FMT='('' NFP3DF = '',I2 ,'' NFP2DF = '',I2,'' NFPPHY = '',I2, &
 & '' NFPCFU = '',I2 ,'' NFPXFU = '',I2)') &
 & YD%NFP3DF, YD%NFP2DF, YD%NFPPHY, YD%NFPCFU, YD%NFPXFU
WRITE(UNIT=KULOUT,FMT='('' NFP3P = '',I2,'' NFP3H = '',I2,'' NFP3TH = '',I2, &
 & '' NFP3PV = '',I2,'' NFP3S = '',I3,'' NFP3I = '',I3,'' NFP3F = '',I3)') &
 & YD%NFP3P,YD%NFP3H,YD%NFP3TH,YD%NFP3PV,YD%NFP3S,YD%NFP3I,YD%NFP3F

IF (YD%NFP3P > 0) THEN
  WRITE(UNIT=KULOUT,FMT='('' (JL RFP3P)'')')
  WRITE(UNIT=KULOUT,FMT='(10('' ('',I2,1X,F7.0,'')''))') (J,YD%RFP3P(J), J=1,YD%NFP3P)
ENDIF
IF (YD%NFP3H > 0) THEN
  WRITE(UNIT=KULOUT,FMT='('' (JL RFP3H)'')')
  WRITE(UNIT=KULOUT,FMT='(10('' ('',I2,1X,F7.0,'')''))') (J,YD%RFP3H(J), J=1,YD%NFP3H)
ENDIF
IF (YD%NFP3TH > 0) THEN
  WRITE(UNIT=KULOUT,FMT='('' (JL RFP3TH)'')')
  WRITE(UNIT=KULOUT,FMT='(10('' ('',I2,1X,F7.0,'')''))') (J,YD%RFP3TH(J), J=1,YD%NFP3TH)
ENDIF
IF (YD%NFP3PV > 0) THEN
  WRITE(UNIT=KULOUT,FMT='('' (JL RFP3PV)'')')
  WRITE(UNIT=KULOUT,FMT='(7('' ('',I2,1X,E13.6,'')''))') (J,YD%RFP3PV(J), J=1,YD%NFP3PV)
ENDIF
IF (YD%NFP3I > 0) THEN
  WRITE(UNIT=KULOUT,FMT='('' (JL RFP3I)'')')
  WRITE(UNIT=KULOUT,FMT='(7('' ('',I2,1X,E13.6,'')''))') (J,YD%RFP3I(J), J=1,YD%NFP3I)
ENDIF
IF (YD%NFP3F > 0) THEN
  WRITE(UNIT=KULOUT,FMT='('' (JL RFP3F)'')')
  WRITE(UNIT=KULOUT,FMT='(10('' ('',I2,1X,F7.0,'')''))') (J,YD%RFP3F(J), J=1,YD%NFP3F)
ENDIF
IF (YD%NFP3S > 0) THEN
  WRITE(UNIT=KULOUT,FMT='('' (JL NRFP3S)'')')
  WRITE(UNIT=KULOUT,FMT='(13('' ('',I3,1X,I3,'')''))') (J,YD%NRFP3S(J), J=1,YD%NFP3S)
ENDIF

IF (LDARPEGE) THEN

  IF (YD%NFP3DF > 0) THEN
    WRITE(UNIT=KULOUT,FMT='('' (JF CFP3DF )'')')
    WRITE(UNIT=KULOUT,FMT='(7('' ('',I2,1X,A12,'')''))') (J,YD%CFP3DF(J), J=1,YD%NFP3DF)
  ENDIF
  IF (YD%NFP2DF > 0) THEN
    WRITE(UNIT=KULOUT,FMT='('' (JF CFP2DF )'')')
    WRITE(UNIT=KULOUT,FMT='(6('' ('',I2,1X,A16,'')''))') (J,YD%CFP2DF(J), J=1,YD%NFP2DF)
  ENDIF
  IF (YD%NFPPHY > 0) THEN
    WRITE(UNIT=KULOUT,FMT='('' (JF CFPPHY )'')')
    WRITE(UNIT=KULOUT,FMT='(6('' ('',I3,1X,A16,'')''))') (J,YD%CFPPHY(J), J=1,YD%NFPPHY)
  ENDIF
  IF (YD%NFPCFU > 0) THEN
    WRITE(UNIT=KULOUT,FMT='('' (JF CFPCFU )'')')
    WRITE(UNIT=KULOUT,FMT='(6('' ('',I2,1X,A16,'')''))') (J,YD%CFPCFU(J), J=1,YD%NFPCFU)
  ENDIF
  IF (YD%NFPXFU > 0) THEN
    WRITE(UNIT=KULOUT,FMT='('' (JF CFPXFU )'')')
    WRITE(UNIT=KULOUT,FMT='(6('' ('',I2,1X,A16,'')''))') (J,YD%CFPXFU(J), J=1,YD%NFPXFU)
  ENDIF

ELSE

  IF (YD%NFP3DFS > 0) THEN
    WRITE(KULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON MODEL LEVELS'')') YD%NFP3DFS
    WRITE(KULOUT,'(20(1X,I6))') (YD%MFP3DFS(J),J=1,YD%NFP3DFS)
  ENDIF
  IF (YD%NFP3DFH > 0) THEN
    WRITE(KULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON H LEVELS'')') YD%NFP3DFH
    WRITE(KULOUT,'(20(1X,I3))') (YD%MFP3DFH(J),J=1,YD%NFP3DFH)
  ENDIF
  IF (YD%NFP3DFP > 0) THEN
    WRITE(KULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON PRESSURE LEVELS'')') YD%NFP3DFP
    WRITE(KULOUT,'(20(1X,I6))') (YD%MFP3DFP(J),J=1,YD%NFP3DFP)
  ENDIF
  IF (YD%NFP3DFT > 0) THEN
    WRITE(KULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON THETA LEVELS'')') YD%NFP3DFT
    WRITE(KULOUT,'(20(1X,I3))') (YD%MFP3DFT(J),J=1,YD%NFP3DFT)
  ENDIF
  IF (YD%NFP3DFV > 0) THEN
    WRITE(KULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON PV LEVELS'')') YD%NFP3DFV
    WRITE(KULOUT,'(20(1X,I3))') (YD%MFP3DFV(J),J=1,YD%NFP3DFV)
  ENDIF
  IF (YD%NFP3DFI > 0) THEN
    WRITE(KULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON TEMPERATURE LEVELS'')') YD%NFP3DFI
    WRITE(KULOUT,'(20(1X,I3))') (YD%MFP3DFI(J),J=1,YD%NFP3DFI)
  ENDIF
  IF (YD%NFP3DFF > 0) THEN
    WRITE(KULOUT,'('' THE FOLLOWING '',I6,'' 3DYN. FIELDS'','' WILL BE WRITTEN OUT ON FLIGHT LEVELS'')') YD%NFP3DFF
    WRITE(KULOUT,'(20(1X,I3))') (YD%MFP3DFF(J),J=1,YD%NFP3DFF)
  ENDIF
  IF (YD%NFP2DF > 0) THEN
    WRITE(KULOUT,'('' THE FOLLOWING '',I3,'' DYN.SURFACE FIELDS'','' WILL BE WRITTEN OUT '')') YD%NFP2DF
    WRITE(KULOUT,'(20(1X,I3))') (YD%MFP2DF(J),J=1,YD%NFP2DF)
  ENDIF
  IF (YD%NFPPHY > 0) THEN
    WRITE(KULOUT,'('' THE FOLLOWING '',I6,'' PHY.SURFACE FIELDS'','' WILL BE WRITTEN OUT '')') YD%NFPPHY
    WRITE(KULOUT,'(20(1X,I6))') (YD%MFPPHY(J),J=1,YD%NFPPHY)
  ENDIF
ENDIF

IF (LHOOK) CALL DR_HOOK('TYPE_FPFIELDS:PRINT_FPFIELDS',1,ZHOOK_HANDLE)

END SUBROUTINE PRINT_FPFIELDS
!     ------------------------------------------------------------------
END MODULE TYPE_FPFIELDS
