! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE WRFLDCW_MOD

!**** *WRFLDCW_MOD*  - All NSTROUT processors write to the same file (experimental)

!     Author. 
!     ------- 
!      Philippe Marguinaud *METEO FRANCE*
!      Original : 11-09-2012

!     Modifications :
!     P. Marguinaud : 10-10-2013 : Re-organize using LFI_F and WRFLDCW_CTX,
!                                  remove WRFLDCW_WRITE_OVER

USE PARKIND1, ONLY : JPRB, JPIM, JPIA, JPIB
USE YOMHOOK, ONLY : LHOOK, DR_HOOK, JPHOOK

IMPLICIT NONE

INTEGER (KIND=JPIM), PARAMETER :: JPI8 = JPIB
CHARACTER (LEN=16), PARAMETER :: CLFINDINDEX = "**FIN D'INDEX** "

PRIVATE
PUBLIC :: WRFLDCW_WRITE, WRFLDCW_START, WRFLDCW_FINISH, &
        & WRFLDCW_CTX,   WRFLDCW_OPEN,  WRFLDCW_CLOSE,  &
        & LFI_H, LFI_F

TYPE LFI_H
  INTEGER (KIND=JPI8) :: I_AS = -1_JPI8                   ! Physical article size in bytes
  INTEGER (KIND=JPI8), POINTER :: I_S1 (:)    => NULL ()  ! First section
  CHARACTER (LEN=16),  POINTER :: C_S2 (:)    => NULL ()  ! Second section (logical article names)
  INTEGER (KIND=JPI8), POINTER :: I_S3 (:, :) => NULL ()  ! Third section (length/offset)
END TYPE LFI_H

TYPE LFI_F
  INTEGER (KIND=JPIA) :: IFP   = 0_JPIA
  LOGICAL             :: LSWAP = .FALSE.
END TYPE LFI_F

TYPE WRFLDCW_CTX
  INTEGER (KIND=JPIM) :: NCOMMWR
  INTEGER (KIND=JPIM) :: NCOMMWR_SIZE = 1
  INTEGER (KIND=JPIM) :: NCOMMWR_RANK = 0
  LOGICAL             :: LMPI         = .FALSE.
  LOGICAL             :: LROOT        = .TRUE.
  LOGICAL             :: LOPEN        = .FALSE.
  TYPE (LFI_F)        :: YLLFI_F
  TYPE (LFI_H)        :: YLLFI_H
  INTEGER (KIND=JPI8) :: ISIZF
  LOGICAL             :: LLNOMM
  LOGICAL             :: LLERFA
  LOGICAL             :: LLIMST
  CHARACTER (LEN=8)   :: CLSTTU
  CHARACTER (LEN=32)  :: CLNOMC
  CHARACTER (LEN=256) :: CLNOMF
  INTEGER (KIND=JPIM) :: INIMES
  INTEGER (KIND=JPIM) :: IUNIT
END TYPE WRFLDCW_CTX

SAVE

CONTAINS

SUBROUTINE WRFLDCW_START (YDWCTX, LDISIO, LDMPI)

! Create a new communicator with all procs involved in IO

USE MPL_MODULE, ONLY : MPL_COMM, MPL_COMM_SPLIT
USE YOMMP0, ONLY : MYPROC

TYPE (WRFLDCW_CTX), INTENT (INOUT) :: YDWCTX
LOGICAL,            INTENT (IN)    :: LDISIO
LOGICAL,            INTENT (IN)    :: LDMPI

INTEGER (KIND=JPIM) :: ICOLOR, IREP

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_START',0,ZHOOK_HANDLE)

YDWCTX%LMPI = LDMPI

IF (YDWCTX%LMPI) THEN

  IF (LDISIO) THEN
    ICOLOR = 1
  ELSE
    ICOLOR = 0
  ENDIF

  CALL MPL_COMM_SPLIT (MPL_COMM, ICOLOR, MYPROC, YDWCTX%NCOMMWR, IREP, &
                     & CDSTRING='WRFLDCW_MOD:WRFLDCW_START:')

  CALL MPI_COMM_RANK (YDWCTX%NCOMMWR, YDWCTX%NCOMMWR_RANK, IREP)
  CALL MPI_COMM_SIZE (YDWCTX%NCOMMWR, YDWCTX%NCOMMWR_SIZE, IREP)

  YDWCTX%LROOT = YDWCTX%NCOMMWR_RANK == 0

ELSE
  YDWCTX%NCOMMWR_RANK = 0
  YDWCTX%NCOMMWR_SIZE = 1
  YDWCTX%LROOT        = .TRUE.
ENDIF

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_START',1,ZHOOK_HANDLE)

END SUBROUTINE WRFLDCW_START

SUBROUTINE WRFLDCW_FINISH (YDWCTX)

! Delete IO communicator

USE MPL_MODULE, ONLY : MPL_COMM_FREE

TYPE (WRFLDCW_CTX), INTENT (INOUT) :: YDWCTX

INTEGER (KIND=JPIM) :: IREP

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_FINISH',0,ZHOOK_HANDLE)

IF (YDWCTX%LMPI) THEN
  CALL MPL_COMM_FREE (YDWCTX%NCOMMWR, IREP, CDSTRING='WRFLDCW_MOD:WRFLDCW_FINISH:')
ENDIF

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_FINISH',1,ZHOOK_HANDLE)

END SUBROUTINE WRFLDCW_FINISH

SUBROUTINE WRFLDCW_TABLE (YDWCTX, KLONGDL, CDNOMAL, KMASKL, KLONGDG, KPOSEXG, CDNOMAG, KFLDOFF)

! Exchange names and length among all processors

USE MPL_MODULE, ONLY : MPL_ALLGATHERV

TYPE (WRFLDCW_CTX),     INTENT (INOUT) :: YDWCTX
INTEGER (KIND=JPIM),    INTENT (IN)    :: KLONGDL (:)
CHARACTER (LEN=*),      INTENT (IN)    :: CDNOMAL (:)
INTEGER (KIND=JPIM),    INTENT (IN)    :: KMASKL  (:)
INTEGER (KIND=JPI8),    POINTER        :: KLONGDG (:)
INTEGER (KIND=JPI8),    POINTER        :: KPOSEXG (:)
CHARACTER (LEN=16),     POINTER        :: CDNOMAG (:)
INTEGER (KIND=JPIM),    INTENT (OUT)   :: KFLDOFF

INTEGER (KIND=JPIM) :: IFLDL, JFLDL, JFLDG
INTEGER (KIND=JPIM) :: IMULT
INTEGER (KIND=JPIM) :: IFNUML
INTEGER (KIND=JPIM) :: IFNUMG
INTEGER (KIND=JPIM), ALLOCATABLE :: ILFNUMG (:)
INTEGER (KIND=JPIM), ALLOCATABLE :: IBUFG (:), IBUFL (:)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_TABLE',0,ZHOOK_HANDLE)

IFNUML = COUNT (KMASKL > 0)

ALLOCATE (ILFNUMG (YDWCTX%NCOMMWR_SIZE))

IF (YDWCTX%LMPI) THEN
  CALL MPL_ALLGATHERV (IFNUML, ILFNUMG, KCOMM=YDWCTX%NCOMMWR, CDSTRING='WRFLDCW_MOD:WRFLDCW_TABLE:')
ELSE
  ILFNUMG (1) = IFNUML
ENDIF

IFNUMG = SUM (ILFNUMG)

ALLOCATE (KLONGDG (IFNUMG), KPOSEXG (IFNUMG), CDNOMAG (IFNUMG))

IF (YDWCTX%LMPI) THEN

  IMULT = 5 ! = 1+16/4
  
  ALLOCATE (IBUFG (IFNUMG*IMULT)) 
  ALLOCATE (IBUFL (IFNUML*IMULT)) 
  
  IFLDL = 1
  DO JFLDL = 1, SIZE (KMASKL)
    IF (KMASKL (JFLDL) > 0) THEN
      IBUFL ((IFLDL-1)*IMULT+1) = KLONGDL (JFLDL)
      IBUFL ((IFLDL-1)*IMULT+2:IFLDL*IMULT) = TRANSFER (CDNOMAL (JFLDL), IBUFL ((IFLDL-1)*IMULT+2:IFLDL*IMULT))
      IFLDL = IFLDL + 1
    ENDIF
  ENDDO
  
  CALL MPL_ALLGATHERV (IBUFL, IBUFG, KRECVCOUNTS=ILFNUMG*IMULT, KCOMM=YDWCTX%NCOMMWR, &
                     & CDSTRING='WRFLDCW_MOD:WRFLDCW_TABLE:')

  DO JFLDG = 1, IFNUMG
    KLONGDG (JFLDG) = IBUFG ((JFLDG-1)*IMULT+1)
    CDNOMAG (JFLDG) = TRANSFER (IBUFG ((JFLDG-1)*IMULT+2:JFLDG*IMULT), CDNOMAG (JFLDG))
  ENDDO

  IF (IFNUML > 0) THEN
    KFLDOFF = SUM (ILFNUMG (1:YDWCTX%NCOMMWR_RANK))
  ELSE
    KFLDOFF = 0
  ENDIF

ELSE

  JFLDG = 1
  DO JFLDL = 1, SIZE (KMASKL)
    IF (KMASKL (JFLDL) > 0) THEN
      KLONGDG (JFLDG) = KLONGDL (JFLDL)
      CDNOMAG (JFLDG) = CDNOMAL (JFLDL)
      JFLDG = JFLDG + 1
    ENDIF
  ENDDO
  
  KFLDOFF = 0

ENDIF


IF (IFNUMG > 0) THEN
  KPOSEXG (1) = 0
  DO JFLDG = 2, IFNUMG
    KPOSEXG (JFLDG) = KPOSEXG (JFLDG-1) + KLONGDG (JFLDG-1)
  ENDDO
ENDIF

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_TABLE',1,ZHOOK_HANDLE)

END SUBROUTINE WRFLDCW_TABLE

SUBROUTINE WRFLDCW_RD_LFI_H (YDLFI_F, YDLFI_H, KREP)

! Read LFI header

TYPE (LFI_F),        INTENT (INOUT) :: YDLFI_F
TYPE (LFI_H),        INTENT (INOUT) :: YDLFI_H
INTEGER( KIND=JPIM), INTENT (IN)    :: KREP

INTEGER (KIND=JPI8) :: I_LFI_S1_2 (2), I_LFI_S1_1
INTEGER (KIND=JPI8) :: IRD

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_RD_LFI_H',0,ZHOOK_HANDLE)

CALL FI_FSEEK (KREP, YDLFI_F%IFP, 0_JPI8, 0_JPIM)
CALL FI_FREAD (IRD, I_LFI_S1_2, 8_JPI8, 2_JPI8, YDLFI_F%IFP)
I_LFI_S1_1 = I_LFI_S1_2 (1)

YDLFI_F%LSWAP = I_LFI_S1_2 (2) > 128

IF (YDLFI_F%LSWAP) CALL JSWAP (I_LFI_S1_1, I_LFI_S1_1, JPI8, 1_JPIM)

ALLOCATE (YDLFI_H%I_S1 (I_LFI_S1_1),       &
        & YDLFI_H%C_S2 (I_LFI_S1_1 / 2),   &
        & YDLFI_H%I_S3 (2, I_LFI_S1_1 / 2))

CALL FI_FSEEK (KREP, YDLFI_F%IFP, 0_JPI8, 0_JPIM)

CALL FI_FREAD (IRD, YDLFI_H%I_S1, I_LFI_S1_1 * JPI8, 1_JPI8, YDLFI_F%IFP)
CALL FI_FREAD (IRD, YDLFI_H%C_S2, I_LFI_S1_1 * JPI8, 1_JPI8, YDLFI_F%IFP)
CALL FI_FREAD (IRD, YDLFI_H%I_S3, I_LFI_S1_1 * JPI8, 1_JPI8, YDLFI_F%IFP)

IF (YDLFI_F%LSWAP) THEN
  CALL JSWAP (YDLFI_H%I_S1, YDLFI_H%I_S1, JPI8, INT (I_LFI_S1_1, JPIM))
  CALL JSWAP (YDLFI_H%I_S3, YDLFI_H%I_S3, JPI8, INT (I_LFI_S1_1, JPIM))
ENDIF

YDLFI_H%I_AS = JPI8 * YDLFI_H%I_S1 (1)

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_RD_LFI_H',1,ZHOOK_HANDLE)

END SUBROUTINE WRFLDCW_RD_LFI_H

SUBROUTINE WRFLDCW_FR_LFI_H (YDLFI_H)

! Free LFI header

TYPE (LFI_H), INTENT (INOUT) :: YDLFI_H

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_FR_LFI_H',0,ZHOOK_HANDLE)

DEALLOCATE (YDLFI_H%I_S1, YDLFI_H%C_S2, YDLFI_H%I_S3)
NULLIFY (YDLFI_H%I_S1, YDLFI_H%C_S2, YDLFI_H%I_S3)

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_FR_LFI_H',1,ZHOOK_HANDLE)

END SUBROUTINE WRFLDCW_FR_LFI_H

SUBROUTINE WRFLDCW_WR_LFI_H (YDLFI_F, YDLFI_H, KREP)

! Write LFI header

TYPE (LFI_F),        INTENT (INOUT) :: YDLFI_F
TYPE (LFI_H),        INTENT (IN)    :: YDLFI_H
INTEGER (KIND=JPIM), INTENT (IN)    :: KREP

TYPE (LFI_H)        :: YLLFI_H
INTEGER (KIND=JPI8) :: IWR

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_WR_LFI_H',0,ZHOOK_HANDLE)


IF (YDLFI_F%LSWAP) THEN

  ALLOCATE (YLLFI_H%I_S1 (YDLFI_H%I_S1 (1)),       &
          & YLLFI_H%C_S2 (YDLFI_H%I_S1 (1) / 2),   &
          & YLLFI_H%I_S3 (2, YDLFI_H%I_S1 (1) / 2))

  CALL JSWAP (YLLFI_H%I_S1, YDLFI_H%I_S1, JPI8, INT (YDLFI_H%I_S1 (1), JPIM))
  CALL JSWAP (YLLFI_H%I_S3, YDLFI_H%I_S3, JPI8, INT (YDLFI_H%I_S1 (1), JPIM))

ELSE

  YLLFI_H%I_S1 => YDLFI_H%I_S1
  YLLFI_H%C_S2 => YDLFI_H%C_S2
  YLLFI_H%I_S3 => YDLFI_H%I_S3

ENDIF

CALL FI_FSEEK (KREP, YDLFI_F%IFP, 0_JPI8, 0_JPIM)

CALL FI_FWRITE (IWR, YLLFI_H%I_S1, YDLFI_H%I_S1 (1) * JPI8, 1_JPI8, YDLFI_F%IFP)
CALL FI_FWRITE (IWR, YDLFI_H%C_S2, YDLFI_H%I_S1 (1) * JPI8, 1_JPI8, YDLFI_F%IFP)
CALL FI_FWRITE (IWR, YLLFI_H%I_S3, YDLFI_H%I_S1 (1) * JPI8, 1_JPI8, YDLFI_F%IFP)

IF (YDLFI_F%LSWAP) CALL WRFLDCW_FR_LFI_H (YLLFI_H)

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_WR_LFI_H',1,ZHOOK_HANDLE)

END SUBROUTINE WRFLDCW_WR_LFI_H

SUBROUTINE WRFLDCW_OPEN (YDWCTX, KUNIT)

USE MPL_BROADCAST_MOD, ONLY : MPL_BROADCAST

TYPE (WRFLDCW_CTX),     INTENT (INOUT)      :: YDWCTX
INTEGER (KIND=JPIM),    INTENT (IN)         :: KUNIT

INTEGER (KIND=JPIM) :: IREP
INTEGER (KIND=JPIM) :: IERR
INTEGER (KIND=JPIM) :: IFD
INTEGER (KIND=JPI8) :: IBUF (13)

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE_OPEN
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE_CLOSE
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE_BROADCAST

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_OPEN',0,ZHOOK_HANDLE)

IF (YDWCTX%LROOT) THEN
  YDWCTX%IUNIT=KUNIT
  CALL FAIOPT (IREP, YDWCTX%IUNIT, YDWCTX%LLNOMM, YDWCTX%CLNOMF, YDWCTX%CLSTTU, &
             & YDWCTX%LLERFA, YDWCTX%LLIMST, YDWCTX%INIMES, YDWCTX%CLNOMC)
  IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_OPEN:CLOSE',0,ZHOOK_HANDLE_CLOSE)
  CALL FAIRME (IREP, YDWCTX%IUNIT, 'KEEP')
  IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_OPEN:CLOSE',1,ZHOOK_HANDLE_CLOSE)
ENDIF

IF (YDWCTX%LMPI) THEN
  IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_OPEN:BROADCAST',0,ZHOOK_HANDLE_BROADCAST)
  CALL MPL_BROADCAST (YDWCTX%CLNOMF, KTAG=0_JPIM, KCOMM=YDWCTX%NCOMMWR, &
                    & CDSTRING='WRFLDCW_MOD:WRFLDCW_OPEN')
  IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_OPEN:BROADCAST',1,ZHOOK_HANDLE_BROADCAST)
ENDIF

! All MPI tasks re-open as binary C file
IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_OPEN:OPEN',0,ZHOOK_HANDLE_OPEN)
CALL FI_FOPEN (YDWCTX%YLLFI_F%IFP, YDWCTX%CLNOMF, "r+")
IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_OPEN:OPEN',1,ZHOOK_HANDLE_OPEN)
! Read LFI headers
CALL WRFLDCW_RD_LFI_H (YDWCTX%YLLFI_F, YDWCTX%YLLFI_H, IREP)

CALL FI_FILENO (IFD, YDWCTX%YLLFI_F%IFP)
CALL FI_FSTAT (IERR, IFD, IBUF)
YDWCTX%ISIZF = IBUF (8)
! Current file size from LFI headers
!YDWCTX%ISIZF = YDWCTX%YLLFI_H%I_S1 (1) * YDWCTX%YLLFI_H%I_S1 (5) * JPI8

YDWCTX%LOPEN = .TRUE.

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_OPEN',1,ZHOOK_HANDLE)

END SUBROUTINE WRFLDCW_OPEN

SUBROUTINE WRFLDCW_CLOSE (YDWCTX)

USE MPL_BARRIER_MOD, ONLY : MPL_BARRIER

TYPE (WRFLDCW_CTX),     INTENT (INOUT)      :: YDWCTX

INTEGER (KIND=JPIM) :: IREP
INTEGER (KIND=JPIM) :: INBARP, INBARI

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE_OPEN
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE_CLOSE
REAL (KIND=JPHOOK) :: ZHOOK_HANDLE_BARRIER

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_CLOSE',0,ZHOOK_HANDLE)

IF (.NOT. YDWCTX%LOPEN) THEN
  IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_CLOSE',1,ZHOOK_HANDLE)
  RETURN
ENDIF

IF (YDWCTX%LROOT) THEN
! Write header
  CALL WRFLDCW_WR_LFI_H (YDWCTX%YLLFI_F, YDWCTX%YLLFI_H, IREP)
ENDIF

CALL WRFLDCW_FR_LFI_H (YDWCTX%YLLFI_H)

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_CLOSE:CLOSE',0,ZHOOK_HANDLE_CLOSE)
CALL FI_FCLOSE (IREP, YDWCTX%YLLFI_F%IFP)
IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_CLOSE:CLOSE',1,ZHOOK_HANDLE_CLOSE)

IF (YDWCTX%LMPI) THEN
  IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_CLOSE:BARRIER',0,ZHOOK_HANDLE_BARRIER)
  CALL MPL_BARRIER (KCOMM=YDWCTX%NCOMMWR, CDSTRING='WRFLDCW_MOD:WRFLDCW_CLOSE')
  IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_CLOSE:BARRIER',1,ZHOOK_HANDLE_BARRIER)
ENDIF

IF (YDWCTX%LROOT) THEN
! Re-open FA
  IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_CLOSE:OPEN',0,ZHOOK_HANDLE_OPEN)
  INBARP=0
  INBARI=0
  CALL FAITOU (IREP, YDWCTX%IUNIT, .TRUE., YDWCTX%CLNOMF, 'OLD', YDWCTX%LLERFA, &
             & YDWCTX%LLIMST, YDWCTX%INIMES, INBARP, INBARI, YDWCTX%CLNOMC)
  IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_CLOSE:OPEN',1,ZHOOK_HANDLE_OPEN)
ENDIF

YDWCTX%LOPEN = .FALSE.

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_CLOSE',1,ZHOOK_HANDLE)

END SUBROUTINE WRFLDCW_CLOSE

SUBROUTINE WRFLDCW_WRITE (YDWCTX, CDNOMAL, KLNOMAL, PVALCOL, KLONGDL, KMASKL)

TYPE (WRFLDCW_CTX),     INTENT (INOUT)                :: YDWCTX
CHARACTER (LEN=*),      INTENT (IN)                   :: CDNOMAL (:)
INTEGER (KIND=JPIM),    INTENT (IN)                   :: KLNOMAL (:)
REAL (KIND=JPRB),       INTENT (IN), TARGET           :: PVALCOL (:,:) ! Fields on this proc
INTEGER (KIND=JPIM),    INTENT (IN)                   :: KLONGDL (:)   ! Fields on this proc
INTEGER (KIND=JPIM),    INTENT (IN), TARGET, OPTIONAL :: KMASKL (:)    ! Fields on this proc

#include "abor1.intfb.h"

INTEGER (KIND=JPIM) :: IFNUL
INTEGER (KIND=JPIM) :: JFLDL
INTEGER (KIND=JPIM) :: IFLDG, JFLDG
INTEGER (KIND=JPIM) :: IREP
INTEGER (KIND=JPI8) :: IWR
INTEGER (KIND=JPI8) :: ISIZA
REAL (KIND=JPRB),    TARGET  :: ZVALCOL (SIZE (PVALCOL, 1))
REAL (KIND=JPRB),    POINTER :: ZVALCOP (:)
INTEGER (KIND=JPI8), POINTER :: ILONGDG (:)
INTEGER (KIND=JPI8), POINTER :: IPOSEXG (:)
CHARACTER (LEN=16),  POINTER :: CLNOMAG (:)
CHARACTER (LEN=16)  :: CLNOMAL (SIZE (CDNOMAL))
INTEGER (KIND=JPIM), POINTER :: IMASKL (:)
INTEGER (KIND=JPIM) :: IFLDOFF

REAL (KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_WRITE',0,ZHOOK_HANDLE)

IPOSEXG => NULL ()
ILONGDG => NULL ()
CLNOMAG => NULL ()

IFNUL = SIZE (PVALCOL, 2)

IF (PRESENT (KMASKL)) THEN
  IMASKL => KMASKL
ELSE
  ALLOCATE (IMASKL (IFNUL))
  IMASKL = 1
ENDIF

DO JFLDL = 1, IFNUL
  CLNOMAL (JFLDL) = ' '
  CLNOMAL (JFLDL)(1:KLNOMAL (JFLDL)) = CDNOMAL (JFLDL)(1:KLNOMAL (JFLDL))
ENDDO

CALL WRFLDCW_TABLE (YDWCTX,  KLONGDL, CLNOMAL, IMASKL,  &
                  & ILONGDG, IPOSEXG, CLNOMAG, IFLDOFF)

IF (SIZE (IPOSEXG) > 0) THEN

! Update offsets (fields at end of file)
  IPOSEXG = YDWCTX%ISIZF / JPRB + IPOSEXG 

! New file size; align on LFI page boundary
  YDWCTX%ISIZF = YDWCTX%ISIZF + SUM (ILONGDG) * JPRB 
!YDWCTX%ISIZF = YDWCTX%YLLFI_H%I_AS * ((YDWCTX%ISIZF + YDWCTX%YLLFI_H%I_AS - 1) / YDWCTX%YLLFI_H%I_AS)
  ISIZA = YDWCTX%YLLFI_H%I_AS * ((YDWCTX%ISIZF + YDWCTX%YLLFI_H%I_AS - 1) / YDWCTX%YLLFI_H%I_AS)

! Offset for this proc
  CALL FI_FSEEK (IREP, YDWCTX%YLLFI_F%IFP, INT (IPOSEXG (IFLDOFF+1) * JPI8, JPI8), 0_JPIM)

! Write fields
  DO JFLDL = 1, IFNUL

    IF (IMASKL (JFLDL) == 0) CYCLE

! Swap bytes if necessary

    IF (YDWCTX%YLLFI_F%LSWAP) THEN
      CALL JSWAP (ZVALCOL (1), PVALCOL (1, JFLDL), JPRB, KLONGDL (JFLDL))
      ZVALCOP => ZVALCOL
    ELSE
      ZVALCOP => PVALCOL (:, JFLDL)
    ENDIF
  
    CALL FI_FWRITE (IWR, ZVALCOP,                       &
                  & INT (KLONGDL (JFLDL) * JPRB, JPI8), &
                  & 1_JPI8, YDWCTX%YLLFI_F%IFP)
  
  ENDDO

! Update header
! YDWCTX%YLLFI_H%I_S1  (5) = YDWCTX%ISIZF / YDWCTX%YLLFI_H%I_AS                ! Number of physical articles
  YDWCTX%YLLFI_H%I_S1  (5) = ISIZA / YDWCTX%YLLFI_H%I_AS                       ! Number of physical articles
  YDWCTX%YLLFI_H%I_S1  (6) = YDWCTX%YLLFI_H%I_S1 (6) + SIZE (CLNOMAG)          ! Number of logical articles
  YDWCTX%YLLFI_H%I_S1  (8) = MAX (YDWCTX%YLLFI_H%I_S1 (8), MAXVAL (ILONGDG))   ! Max length of logical articles
  YDWCTX%YLLFI_H%I_S1  (9) = YDWCTX%YLLFI_H%I_S1 (9) + SUM (ILONGDG)           ! Total length of data
  YDWCTX%YLLFI_H%I_S1 (22) = YDWCTX%YLLFI_H%I_S1 (5)                           ! Number of physical articles

  JFLDG = 1
  DO IFLDG = 1, SIZE (CLNOMAG)
    DO 
      IF (YDWCTX%YLLFI_H%C_S2 (JFLDG) == CLFINDINDEX) EXIT
      JFLDG = JFLDG + 1
      IF (JFLDG > SIZE (YDWCTX%YLLFI_H%C_S2)) &
        & CALL ABOR1 ('WRFLDCW_WRITE: INDEX IS FULL')
    ENDDO
    YDWCTX%YLLFI_H%C_S2    (JFLDG) = CLNOMAG (IFLDG)
    YDWCTX%YLLFI_H%I_S3 (1, JFLDG) = ILONGDG (IFLDG)
    YDWCTX%YLLFI_H%I_S3 (2, JFLDG) = IPOSEXG (IFLDG) + 1
  ENDDO

ENDIF

DEALLOCATE (ILONGDG, IPOSEXG, CLNOMAG)

IF (PRESENT (KMASKL)) THEN
  IMASKL => NULL ()
ELSE
  DEALLOCATE (IMASKL)
  IMASKL => NULL ()
ENDIF

IF (LHOOK) CALL DR_HOOK ('WRFLDCW_MOD:WRFLDCW_WRITE',1,ZHOOK_HANDLE)

END SUBROUTINE WRFLDCW_WRITE

END MODULE WRFLDCW_MOD
