! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE YOMCOSJO

USE PARKIND1    , ONLY : JPIM, JPRB
USE PARDIMO     , ONLY : JPNOTP, JPHUBLEV
USE PARERR      , ONLY : JPMXESLV
USE PARCMA      , ONLY : JPMXTOCH, JPMXOCT, JP_NUMEV 
USE RTTOV_CONST , ONLY : NINST
USE PARERSCA    , ONLY : JPQCELL,JPOCELL,JPHCELL,JPRCELL,JPSCELL,JPFCELL,JPWCELL
USE YOMHOOK     , ONLY : LHOOK, DR_HOOK, JPHOOK
USE VARNO_MODULE, ONLY : NVNUMAX

IMPLICIT NONE

SAVE

!*
!      /YOMCOSJO/ - JO RELEVANT PARAMETERS

!     D. VASILJEVIC    90/02/21  ECMWF

!     modif. M.Jurasek 04/05/12  added radar reflectivity
!            K. Scipal 08/05/05 added scat soil moisture
!        Y.Tremolet    29-May-2008 Print Jo table by bins
!        C.Payan       Feb-2011 37t1 SIGMAO_COEF defined now by obstype
!        P. Lopez      07-Oct-2010 Added ln(rain+1) variable
!        A. Geer       22-Nov-2010 Event summary table 
!        C.Payan       06-Mar-2012 37t1_bf.04/38_main LSCATT_UPWDFLAG added
!        C. Lupu       19-Nov-2014  Updates to sensors and platform lists from rttov_consts
!        C.Payan       27-Apr-2015 Hscat and Rscat handling
!        N. Bormann    1-Aug-2016 CVarBC
!        G. De Chiara  25-Apr-2017 FSCAT and WSCAT handling
!        P. Weston     03-Jan-2018 Allow satellite specific error correlations
!        F.Suzat       4/4/18 add Td2m for canari
!        B. Ingleby    06-Aug-2019 Add q2m
!        M.Janiskova   16-Dec-2019 Added cloud radar and lidar
!        B. Ingleby    15-Apr-2020 Fix merge of last two changes
!        A. Geer       01-Feb-2021 Move NVAR to a dedicated module (and make it dynamic)
!        E. Holm       20-Aug-2021 Add REDJO
!*

INTEGER(KIND=JPIM), ALLOCATABLE :: NOTVAR(:,:)

!*       1.3.2 ARRAY HOLDING SUB-OBS. TYPES POINTERS

!                      Scatterometer cost is quadratic.
!                      Only the ambiguous wind nearer the
!                      high resolution first guess is used.
!     LSCATT_UPWDFLAG     L    .T.=>depar2big flag updated at each trajectory!
!                        Useful for Jo and other diagnostics (trHK,...)
!                        default value .F. in defrun

LOGICAL :: LSCATT_UPWDFLAG

!* Variational Quality Control
!     RAQC        R    VAR QC, PROB. FOR GROSS ERROR BY VAR. AND OBS-TYPE
!     RLQC        R    VAR QC, RANGE BY VARIABLE AND OBS-TYPE
!     RBGQC       R    BACKGROUND CHECK LIMITS
!     RBGQC_RAD1C R    BACKG. CHECK LIMITS FOR 1C RADIANCES
!     ROERR_RAD1C R    OBSERVATION ERRORS FOR 1C RADIANCES
!     ROERR_QSCAT R    OBSERVATION ERRORS FOR QUIKSCAT WINDS
!     ROERR_OSCAT R    OBSERVATION ERRORS FOR OCEANSAT-2/3 WINDS
!     ROERR_HSCAT R    OBSERVATION ERRORS FOR HSCAT (HY-2B/2C/2D) WINDS
!     ROERR_RSCAT R    OBSERVATION ERRORS FOR RapidSCAT WINDS
!     ROERR_SSCAT R    OBSERVATION ERRORS FOR ScatSAT-1 WINDS
!     ROERR_FSCAT R    OBSERVATION ERRORS FOR CFOSAT RFSCAT WINDS
!     ROERR_WSCAT R    OBSERVATION ERRORS FOR FY-3E WindRAD WINDS
!     LVARQCG     L    SWITCH VARIATIONAL QC ON/OFF GLOBALLY
!     LVARQC      L    SWITCH VARIATIONAL QC ON/OFF BY VAR. AND OBS-TYPE
!     NHLSFGOPT   I    OPTION FOR HLOS IN FGCHK
!     ZHLSFGOPT   R    PARAMETER FOR OPTION FOR HLOS IN FGCHK
REAL(KIND=JPRB), ALLOCATABLE :: RAQC(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: RLQC(:,:)
REAL(KIND=JPRB), ALLOCATABLE :: RBGQC(:,:,:)
REAL(KIND=JPRB) :: ROERR_RAD1C(0:NINST-1,JPMXTOCH)
REAL(KIND=JPRB) :: RAQC_RAD1C(0:NINST-1,JPMXTOCH)
REAL(KIND=JPRB) :: RLQC_RAD1C(0:NINST-1,JPMXTOCH)
REAL(KIND=JPRB) :: RBGQC_RAD1C(0:NINST-1,JPMXTOCH,3)
REAL(KIND=JPRB) :: ROERR_QSCAT(JPQCELL)
REAL(KIND=JPRB) :: ROERR_OSCAT(JPOCELL)
REAL(KIND=JPRB) :: ROERR_HSCAT(JPHCELL)
REAL(KIND=JPRB) :: ROERR_RSCAT(JPRCELL)
REAL(KIND=JPRB) :: ROERR_SSCAT(JPSCELL)
REAL(KIND=JPRB) :: ROERR_FSCAT(JPFCELL)
REAL(KIND=JPRB) :: ROERR_WSCAT(JPWCELL)
LOGICAL :: LVARQCG
LOGICAL, ALLOCATABLE :: LVARQC(:,:)
LOGICAL :: LVARQC_RAD1C(0:NINST-1)

!* Variational Quality Control with Huber
!     RHUBERLEFT            R    LEFT HUBER CUTOFF VALUES 
!     RHUBERRIGHT           R    RIGHT HUBER CUTOFF VALUES
!     RHUBERBGQC            R    BACKGROUND CHECK LIMITS FOR HUBER VARQC
!     RHUBERBGQC_SONDEGOOD  R    BACKGROUND CHECK LIMITS FOR HUBER VARQC FOR GOOD SONDES AND PILOTS
!     RHUBERBGQC_SONDEOK    R    BACKGROUND CHECK LIMITS FOR HUBER VARQC FOR OK SONDES AND PILOTS
!     RHUBEROETUNING        R    FACTOR TO REDUCE THE OBSERVATION ERROR WHEN USING HUBER VARQC
!     LHUBERMINQCG          L    SWITCH HUBER VARIATIONAL QC WEIGHTS ON/OFF GLOBALLY
!     LHUBERBGQCG           L    SWITCH CHANGE IN BGQC LIMITS FOR HUBER VARIATIONAL QC ON/OFF GLOBALLY
!     LHUBERMINQC           L    SWITCH HUBER VARIATIONAL QC WEIGHTS ON/OFF BY VAR. AND OBS-TYPE
!     LHUBERBGQC            L    SWITCH CAHNGE IN BGQC LIMITS FOR HUBER VARIATIONAL QC ON/OFF BY VAR. AND OBS-TYPE
!     NBDLAYER              I    BOUNDARY LAYER TOP (IN THE RANGE 1:JPMXESLV)
!     NTROPOP               I    TROPOPAUSE (IN THE RANGE 1:JPMXESLV)
! NBDLAYER and NTROPOP are the link between JPHUBLEV and JPMXESLV defined in sulevlay.F90
REAL(KIND=JPRB), ALLOCATABLE :: RHUBERLEFT(:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: RHUBERRIGHT(:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: RHUBERBGQC(:,:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: RHUBEROETUNING(:,:,:,:)

REAL(KIND=JPRB), ALLOCATABLE :: RHUBERBGQC_SONDEGOOD(:,:,:,:)
REAL(KIND=JPRB), ALLOCATABLE :: RHUBERBGQC_SONDEOK(:,:,:,:)
LOGICAL :: LHUBERMINQCG
LOGICAL :: LHUBERBGQCG
LOGICAL, ALLOCATABLE :: LHUBERMINQC(:,:)
LOGICAL, ALLOCATABLE :: LHUBERBGQC(:,:)

INTEGER(KIND=JPIM) :: NBDLAYER
INTEGER(KIND=JPIM) :: NTROPOP


INTEGER(KIND=JPIM) :: NHLSFGOPT
REAL(KIND=JPRB) :: ZHLSFGOPT 

REAL(KIND=JPRB) :: FGERRGROWTH

!* Modification of sigmaos by a global factor
REAL(KIND=JPRB)            :: SIGMAO_COEF(JPNOTP)    ! normalization coefficient of sigmaos
REAL(KIND=JPRB)            :: REDJO                  ! global normalization coefficient applied all sigmaos (cf REDNMC)

!     obs error correlation (general)
!     LOBSCOR                                         L  MAIN SWITCH TO ACCOUNT FOR OBS ERROR CORRELATIONS
!     LOBSCORDIAG                                     L  TURN ON SOME DIAGNOSTICS WHEN R MATRIX IS "SMALL"
!     LOBSCOR_PS                                      L  OBS CORRELATIONS FOR PS (VALIDATION)
!     LOBSCOR_SATOB                                   L  OBS CORRELATIONS FOR SATOB
!     LOBSCOR_AMSUA                                   L  OBS CORRELATIONS FOR AMSUA
!     LRANDOM_OBSCOR                                  L  OBS CORRELATIONS BY RANDOMIZATION (FOR VALIDATION)
!     LOBSCOR_SPLIT                                   L  SPLIT OBSCOR PB VERTICALLY AND TEMPORALLY
!     LPRINT_OBSCOR_MATR                              L  PRINT OUT OBSCOR MATRIX, EIGENSYSTEM, AND INVERSES
!     NBCORBLK                                        I  NUMBER OF CORRELATED BLOCKS IN OBS CORR MATRIX
!     OBSCOR_SCALPR(JP_NUMEV,NBCORBLK)                R  INNER PRODUCTS
!     OBSCOR_AUX(NSETOT,NBCORBLK)          DERIVED TYPE  PRODUCTS TO BE SUMMED UP OVER PE-s,
!                                          obscor_aux_t  SETS AND REPORTS REPRODUCIBLY TO CONSTITUTE OBSCOR_SCALPR
!     OBSCOR_EIGVAL(JP_NUMEV,NBCORBLK)                R  EIGENVALUES OF OBS CORR MATRIX BLOCK
!     OBSCOR_TRUN(NBCORBLK)                           R  TRUNCATION PARAMETER OF OBS CORR MATRIX BLOCK DUE TO JP_NUMEV < Rank
!     NOVERTRUN                                       I  PARAM TO OVERTRUN No OF RETAINED EIGVECS: Neigvecs=JP_NUMEV/NOVERTRUN
!     EIGMIN                                          R  LOWER LIMITER OF R EIGENVALUES R=(1-EIGMIN) * R + EIGMIN * I
!     OBSCOR_HOR_LSCALE(NBCORBLK)                     R  HORIZONTAL CORRELATION LENGTH SCALE OF OBS ERROR
!     OBSHSCALE                                       R  HORIZONTAL CORRELATION LENGTH SCALE OF OBS ERROR (global)
!     OBSCOR_P_UPPER      "                           R  UPPERMOST LEVEL FOR VERTICAL INTERPOLATION OF OBS ERR CORR
!     OBSCOR_P_LOWER      "                           R  LOWERMOST                            "
!     NOBSCOR_INLEVS      "                           I  NUMBER OF PRESSURE LEVELS FOR VERTICAL INTERPOLATION OF OBS ERR CORR
!     OBSCOR_AUTO_COR     "                           R  DECORRELATION TIME PARAMETER
!     LUV_OBSCOR          "                           L  TYPE OF OBS, WIND OR SCALAR
!     L3D_OBSCOR          "                           L  OBS IS 3D FIELD OR 2D
!     OBSCOR_GRID_DEF                      DERIVED TYPE  REDUCED RESOLUTION GRID DEFINITION FOR OBS ERR CORR
!     OBS_ARR_GL2(:,:)                                R  AUX ARRAY TO HOLD OBSERVATION INFO NEEDED BY THE CORRELATION MODEL
!     NACTIM_START, NACTIM_END   (:)                  I  WHEN SPLITTED TEMPORALLY, TIMESLOT LIMITS OF GIVEN BLOCK
!     NMASK                                           I  AUX VALUE FOR ACTUAL CORRELATED BLOCK NUMBER
!     NSMAX_OBSCOR                                    I  RESOLUTION FOR OBSCOR MODEL
LOGICAL :: LOBSCOR, LOBSCORDIAG, LPRINT_OBSCOR_MATR  , LRANDOM_OBSCOR
LOGICAL :: LOBSCOR_AMSUA, LOBSCOR_SATOB, LOBSCOR_SPLIT
LOGICAL, ALLOCATABLE:: L3D_OBSCOR(:),LUV_OBSCOR(:)
TYPE OBSCOR_AUX_T
  INTEGER(KIND=JPIM)       :: NOBSCOR_COUNT
  REAL(KIND=JPRB), POINTER :: OBSCOR_SCALPR_L(:,:) => NULL()
!  OBSCOR_SCALPR_L(JP_NUMEV,NOBSCOR_COUNT)
END TYPE OBSCOR_AUX_T
TYPE OBSARRTYPE
  REAL(KIND=JPRB), POINTER :: OBS_ARR_GL2(:,:) => NULL()
END TYPE OBSARRTYPE
TYPE(OBSCOR_AUX_T), ALLOCATABLE:: OBSCOR_AUX(:,:)

TYPE OBSCOR_GRID_STRUCT
   INTEGER(KIND=JPIM)  :: NSMAX, NSPEC2, NUMP, NDGLG, NGPTOT, NGPTOTG, NRESOL_ID
   INTEGER(KIND=JPIM), POINTER :: NPROCM(:)=>NULL()
   INTEGER(KIND=JPIM), POINTER :: NASM0G(:)=>NULL() 
   INTEGER(KIND=JPIM), POINTER :: NSPZERO(:)=>NULL() 
   REAL(KIND=JPRB), POINTER ::    RLAPDI(:)=>NULL() 
   INTEGER(KIND=JPIM), POINTER, DIMENSION(:)     :: NLOENG=>NULL(), NPTRFRSTLAT=>NULL(), NFRSTLAT=>NULL(), &
   & NLSTLAT=>NULL(), MYMS=>NULL(), NASM0=>NULL() 
  INTEGER(KIND=JPIM), POINTER, DIMENSION(:,:)   :: NSTA=>NULL(), NONL=>NULL(), NGPTOTL=>NULL() 
END TYPE OBSCOR_GRID_STRUCT
TYPE(OBSCOR_GRID_STRUCT) :: OBSCOR_GRID_DEF

INTEGER(KIND=JPIM) :: NBCORBLK, NMASK
INTEGER(KIND=JPIM) :: NOVERTRUN, NSMAX_OBSCOR
REAL(KIND=JPRB)    :: EIGMIN
REAL(KIND=JPRB),ALLOCATABLE:: OBSCOR_SCALPR(:,:)
REAL(KIND=JPRB),ALLOCATABLE:: OBSCOR_EIGVAL(:,:)
REAL(KIND=JPRB),ALLOCATABLE:: OBSCOR_TRUN(:)
REAL(KIND=JPRB),ALLOCATABLE :: OBSCOR_HOR_LSCALE(:)
REAL(KIND=JPRB),ALLOCATABLE :: OBSCOR_P_UPPER(:)
REAL(KIND=JPRB),ALLOCATABLE :: OBSCOR_P_LOWER(:)
REAL(KIND=JPRB),ALLOCATABLE :: OBSCOR_AUTO_COR(:)
REAL(KIND=JPRB),ALLOCATABLE :: OBS_ARR_GL2(:,:)
INTEGER(KIND=JPIM),ALLOCATABLE :: NOBSCOR_INLEVS(:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NRITZ_OBSCOR(:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NACTIM_START(:), NACTIM_END(:)
REAL(KIND=JPRB)    :: OBSLATDIAG
REAL(KIND=JPRB)    :: OBSLONDIAG
REAL(KIND=JPRB)    :: OBSHSCALE

!* Interchannel error correlations
!  LIC_OBSERR_COR_RAD1C   L  SWITCH INTER-CHANNEL CORRELATED OBS ERROR 
!                            ON/OFF FOR 1C RADIANCES
!  LIC_OBSERR_DIAG_RAD1C  L  SWITCH DIAGONAL (NOT CORRELATED) OBS ERROR READ
!                            IN FROM FILE ON/OFF FOR 1C RADIANCES (EG. AIRS)
!  NIC_OERRCOR_CHANS  Look-up table for channel numbers for error correlations
!  RIC_OERRCOR_RAD1C R CORRELATION MATRIX 
!  RIC_OERRDIAG_RAD1C OBSERVATION ERROR STANDARD DEVIATIONS
LOGICAL,ALLOCATABLE :: LIC_OBSERR_COR_RAD1C(:)
LOGICAL,ALLOCATABLE :: LIC_OBSERR_DIAG_RAD1C(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: NIC_OERRCOR_CHANS(:,:)
REAL(KIND=JPRB),ALLOCATABLE :: RIC_OERRCOR_RAD1C(:,:,:)
REAL(KIND=JPRB),ALLOCATABLE :: RIC_OERRDIAG_RAD1C(:,:)

REAL(KIND=JPRB)    :: REDSIGO_HEIGHT

!* SYNOP/DRIBU time correlation
!     LTC         L    SWITCH FOR TIME CORRELATION
!     NTCOBS      I    NUMBER OF TIME CORRELATED OBSERVATIONS
!     NTCOBS_L    I    NUMBER OF TIME CORRELATED OBSERVATIONS, THIS PE
!     NTCLOC      I    NUMBER OF TIME CORRELATED OBS-LOCATIONS
!     RTCEFT      R    E-FOLDING TIME OF CORRELATION FUNCTION
!     RTCPART     R    TIME CORRELATED PART OF OBS ERROR.
LOGICAL :: LTC
INTEGER(KIND=JPIM) :: NTCOBS
INTEGER(KIND=JPIM) :: NTCOBS_L
INTEGER(KIND=JPIM) :: NTCLOC
REAL(KIND=JPRB) :: RTCEFT
REAL(KIND=JPRB) :: RTCPART
!     NTCOFF      I    OFFSETS TO STATION LOCATIONS IN THE OTHER ARRAYS
!     NTCOWN      I    OWNER PROCESSOR
!     NTCTIM      I    REFERENCE TIME (In minutes as given by REFTIM)
!     NTCVOI      I    VARIOUS OBSERVATION INFORMATIONS, obtype, cdtype etc
!     NTCIXG_L    I    INDEX TO GLOBAL NTC-ARRAYS
!     NTCONM_L    I    UNIQUE OBSERVATION SEQUENCE NUMBERS, OWN PE ONLY
!     NTCABN_L    I    ABSOLUTE OBSERVATION NUMBER, OWN PE ONLY
!     NTCOPT_L    I    OBSERVATION POINTER, OWN PE ONLY
!     NTCDPT_L    I    DATUM POSITION POINTER, OWN PE ONLY
INTEGER(KIND=JPIM),ALLOCATABLE:: NTCOFF(:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NTCOWN(:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NTCTIM(:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NTCVOI(:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NTCIXG_L(:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NTCONM_L(:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NTCABN_L(:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NTCOPT_L(:)
INTEGER(KIND=JPIM),ALLOCATABLE:: NTCDPT_L(:)
!     RTCNDP      R    NORMALIZED DEPARTURES (PRESSURE OR GEOPOTENTIAL)
!     RTCNDPHR    R    NORMALIZED HIGH RES DEPARTURES
!     RTCAQC      R    PROBABILITY OF GROSS ERROR
!     RTCLQC      R    RANGE OF POSSIBLE VALUES
REAL(KIND=JPRB),ALLOCATABLE:: RTCNDP(:)
REAL(KIND=JPRB),ALLOCATABLE:: RTCNDPHR(:)
REAL(KIND=JPRB),ALLOCATABLE:: RTCAQC(:)
REAL(KIND=JPRB),ALLOCATABLE:: RTCLQC(:)

!     ------------------------------------------------------------------
!     JO TABLES
!     FJOS is the actual one (reproducible)
!     JO_TABLE in (jo_table_mod.F90) is for diagnostics only.

REAL(KIND=JPRB), ALLOCATABLE :: FJOS(:)
REAL(KIND=JPRB), ALLOCATABLE :: FJCVARBC(:) ! Contribution to the CVARBC cost function per hdr-entry
REAL(KIND=JPRB), ALLOCATABLE :: FJOADJ(:)
REAL(KIND=JPRB), ALLOCATABLE :: TIMEADJ(:)

LOGICAL :: LADJOBS = .FALSE.                    ! Save obs dep for adjoint test
INTEGER(KIND=JPIM) :: MOBSENS=0

INTEGER(KIND=JPIM), PARAMETER :: JPST = 4       ! number of basic statuses (AJGDB!)

!     ------------------------------------------------------------------
PUBLIC ALLOCATE_OBSCOR_AUX, DEALLOCATE_OBSCOR_AUX
CONTAINS


SUBROUTINE ALLOCATE_OBSCOR_AUX(YDOBSCOR_AUX,KCOUNT)
TYPE (OBSCOR_AUX_T), INTENT(OUT)  :: YDOBSCOR_AUX
INTEGER(KIND=JPIM), INTENT(IN) :: KCOUNT
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('YOMCOSJO:ALLOCATE_OBSCOR_AUX',0,ZHOOK_HANDLE)
ALLOCATE(YDOBSCOR_AUX%OBSCOR_SCALPR_L(JP_NUMEV,KCOUNT) )
YDOBSCOR_AUX%OBSCOR_SCALPR_L(1:JP_NUMEV,1:KCOUNT)=0._JPRB
YDOBSCOR_AUX%NOBSCOR_COUNT=KCOUNT
IF (LHOOK) CALL DR_HOOK('YOMCOSJO:ALLOCATE_OBSCOR_AUX',1,ZHOOK_HANDLE)
END SUBROUTINE ALLOCATE_OBSCOR_AUX

SUBROUTINE DEALLOCATE_OBSCOR_AUX(YDOBSCOR_AUX)
TYPE (OBSCOR_AUX_T), INTENT(INOUT)  :: YDOBSCOR_AUX
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE
IF (LHOOK) CALL DR_HOOK('YOMCOSJO:DEALLOCATE_OBSCOR_AUX',0,ZHOOK_HANDLE)
IF (ASSOCIATED(YDOBSCOR_AUX%OBSCOR_SCALPR_L   )) &
 & DEALLOCATE(YDOBSCOR_AUX%OBSCOR_SCALPR_L)
IF (LHOOK) CALL DR_HOOK('YOMCOSJO:DEALLOCATE_OBSCOR_AUX',1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_OBSCOR_AUX

END MODULE YOMCOSJO
