! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE YOMECTAB

USE PARKIND1  ,ONLY : JPIM

USE PARDIMO, ONLY : JPXTIM, JPNOTP

IMPLICIT NONE

SAVE

!**----------------------------------------------------------------
!** CD YOMECTAB : OBSERVATIONS TABLES DEFINITION (ECMWF ONLY)
!** ---------     DEFINITION DES TABLEAUX D'OBSERVATIONS (ECMWF
!**               SEULEMENT)
!*  AUTEURS               : D. VASILJEVIC                15/06/90
!**----------------------------------------------------------------
!*
!*  COMMENTS
!*  ----------
!*
!*    M..... : "INTEGER" POINTED ARRAY
!*    NM.... : "INTEGER" CORRESPONDING NON POINTED ARRAY
!*
!*    MTSLOTNO: CURRENT TIME SLOT NO. (IN THE RANGE)
!*    NTSLOTNOS: START TIME SLOT NO. (IN THE RANGE)
!*    NTSLOTNOE: END TIME SLOT NO. (IN THE RANGE)
!*    NTSLPT : ARRAY HOLDING ADDRESSES FOR DIFFERENT TIME SLOTS
!*    NTSLTOB: ARRAY HOLDING NO. OF OBS. FOR DIFFERENT TIME SLOTS
!*    NTSLTOBOFF:SUM(NTSLTOB(1:NTSLOTNO-1))
!*    NTSLTOBG: SUM OF NTSLTOB FOR ALL PROCESSORS
!*    NTSLTOBM: MAX OF NTSLTOB OVER ALL PROCESSORS
!*    NTSLTOV: ARRAY HOLDING NO. OF TOVS FOR DIFFERENT TIME SLOTS
!*    NTSLTOVOFF:SUM(NTSLTOV(1:NTSLOTNO-1))
!*    NTSLNTV: ARRAY HOLDING NO. OF NON-TOVS FOR DIFFERENT TIME SLOTS
!*    NTSLNTVOFF:SUM(NTSLNTV(1:NTSLOTNO-1))
!*    NTSLSCA: ARRAY HOLDING NO. OF SCATT. FOR DIFFERENT TIME SLOTS
!*    NTSLSCAOFF:SUM(NTSLSCA(1:NTSLOTNO-1))
!*    NTSLVSTST: TIMESLOT VS TIMESTEP
!*
!*    MAD... : ADDRESS OF THE ARRAY CORRESPONDING TO ... ( REFER TO
!*             THE COMMANDS "POINTER (  ,  )" )
!*
!* VARIABLES AND PARAMETERS USED AS DIMENSIONS IN THESE ARRAYS ARE
!* RESPECTIVELY DEFINED IN THE COMDECKS "YOMDIM"/"YOMDIMO" AND
!* "PARDIM"/"PARDIMO", OR ALSO IN THE GENERAL COMDECKS OF THE MODEL.
!*
!**----------------------------------------------------------------

TYPE TECVAR
  INTEGER(KIND=JPIM) :: NTSLOTNOS
  INTEGER(KIND=JPIM) :: NTSLOTNOE
END TYPE TECVAR

INTEGER(KIND=JPIM) :: MTSLOTNO
INTEGER(KIND=JPIM),ALLOCATABLE :: NOBTOTP(:)
INTEGER(KIND=JPIM),ALLOCATABLE :: NTSLTOBP(:,:)
INTEGER(KIND=JPIM),ALLOCATABLE :: NOBSTYP(:,:,:)

INTEGER(KIND=JPIM) :: NTSLPT(JPXTIM)
INTEGER(KIND=JPIM) :: NTSLTOB(JPXTIM)
INTEGER(KIND=JPIM) :: NTSLTOBOFF(JPXTIM)
INTEGER(KIND=JPIM) :: NTSLTOBG(JPXTIM)
INTEGER(KIND=JPIM) :: NTSLTOBM(JPXTIM)
INTEGER(KIND=JPIM) :: NTSLTOV(JPXTIM)
INTEGER(KIND=JPIM) :: NTSLTOVOFF(JPXTIM)
INTEGER(KIND=JPIM) :: NTSLNTV(JPXTIM)
INTEGER(KIND=JPIM) :: NTSLNTVOFF(JPXTIM)
INTEGER(KIND=JPIM) :: NTSLSCA(JPXTIM)
INTEGER(KIND=JPIM) :: NTSLSCAOFF(JPXTIM)
INTEGER(KIND=JPIM) :: NTSLVSTST(JPXTIM)

TYPE(TECVAR)       :: YECVAR

!     ------------------------------------------------------------------

END MODULE YOMECTAB
