! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

! This file is automatically generated; Please do not edit
MODULE YOMNMEV
USE PARKIND1  ,ONLY : JPIM     ,JPRB

USE PARCMA,  ONLY : JPMXRE2, JPMXOTP, JPMXDE2

IMPLICIT NONE

SAVE

!*     YOMNMEV - ODB EVENTS 

TYPE REPORT_EVENT1_T
INTEGER(KIND=JPIM) :: NO_DATA
INTEGER(KIND=JPIM) :: ALL_REJECTED
INTEGER(KIND=JPIM) :: BAD_PRACTICE
INTEGER(KIND=JPIM) :: RDB_REJECTED
INTEGER(KIND=JPIM) :: REDUNDANT
INTEGER(KIND=JPIM) :: STALT_MISSING
INTEGER(KIND=JPIM) :: QC_FAILED
INTEGER(KIND=JPIM) :: OVERCAST_IR
INTEGER(KIND=JPIM) :: THINNED

END TYPE REPORT_EVENT1_T

TYPE DATUM_EVENT1_T
INTEGER(KIND=JPIM) :: VERTCO_MISSING
INTEGER(KIND=JPIM) :: OBSVALUE_MISSING
INTEGER(KIND=JPIM) :: FG_MISSING
INTEGER(KIND=JPIM) :: RDB_REJECTED
INTEGER(KIND=JPIM) :: ASSIM_CLD_FLAG
INTEGER(KIND=JPIM) :: BAD_PRACTICE
INTEGER(KIND=JPIM) :: VERTPOS_OUTRANGE
INTEGER(KIND=JPIM) :: FG2BIG
INTEGER(KIND=JPIM) :: DEPAR2BIG
INTEGER(KIND=JPIM) :: OBS_ERROR2BIG
INTEGER(KIND=JPIM) :: DATUM_REDUNDANT
INTEGER(KIND=JPIM) :: LEVEL_REDUNDANT
INTEGER(KIND=JPIM) :: NOT_ANALYSIS_VARNO
INTEGER(KIND=JPIM) :: DUPLICATE
INTEGER(KIND=JPIM) :: LEVELS2MANY
INTEGER(KIND=JPIM) :: LEVEL_SELECTION
INTEGER(KIND=JPIM) :: VERTCO_CONSISTENCY
INTEGER(KIND=JPIM) :: VERTCO_TYPE_CHANGED
INTEGER(KIND=JPIM) :: COMBINED_FLAGGING
INTEGER(KIND=JPIM) :: REPORT_REJECTED
INTEGER(KIND=JPIM) :: VARQC_PERFORMED
INTEGER(KIND=JPIM) :: OBSERROR_INCREASED
INTEGER(KIND=JPIM) :: CONTAM_CLD_FLAG
INTEGER(KIND=JPIM) :: CONTAM_RAIN_FLAG
INTEGER(KIND=JPIM) :: CONTAM_AEROSOL_FLAG
INTEGER(KIND=JPIM) :: BAD_EMISSIVITY
INTEGER(KIND=JPIM) :: MODEL_CLD_FLAG
INTEGER(KIND=JPIM) :: CONTAM_TRGAS_FLAG
INTEGER(KIND=JPIM) :: LAND_SENSITIVITY
END TYPE DATUM_EVENT1_T


TYPE DATUM_SFC_EVENT_T
INTEGER(KIND=JPIM) :: STATID
INTEGER(KIND=JPIM) :: LSMASK
INTEGER(KIND=JPIM) :: STALT_MISSING
INTEGER(KIND=JPIM) :: OBSVALUE_MISSING
INTEGER(KIND=JPIM) :: FG_MISSING
INTEGER(KIND=JPIM) :: FG2BIG
INTEGER(KIND=JPIM) :: NOT_ANALYSIS_VARNO
INTEGER(KIND=JPIM) :: REDUNDANT
INTEGER(KIND=JPIM) :: REPORT_REJECTED
END TYPE DATUM_SFC_EVENT_T

INTEGER(KIND=JPIM)  :: NMXREV1
INTEGER(KIND=JPIM)  :: NOREV1
TYPE(REPORT_EVENT1_T) :: NR1EVENT
INTEGER(KIND=JPIM)  :: NMXDEV1
INTEGER(KIND=JPIM)  :: NODEV1
TYPE(DATUM_EVENT1_T)  :: ND1EVENT
TYPE(DATUM_SFC_EVENT_T)  :: NDSFCEVENT

!     REPORT EVENTS PART 2:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NMXREV2           I     MAX. NO. OF EVENTS

!     SYNOP EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NOREV2  ( 1)      I     NO. OF DEFINED EVENTS

!     AIREP EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NOREV2  ( 2)      I     NO. OF DEFINED EVENTS

!     SATOB EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NOREV2  ( 3)      I     NO. OF DEFINED EVENTS

!     DRIBU EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NOREV2  ( 4)      I     NO. OF DEFINED EVENTS

!     TEMP EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NOREV2  ( 5)      I     NO. OF DEFINED EVENTS
!     NR2EVENT( 1, 5)   I     OLD STYLE Z BIAS CORRECTION APPLIED
!     NR2EVENT( 2, 5)   I     NEW STYLE T BIAS CORRECTION APPLIED
!     NR2EVENT( 3, 5)   I     H BIAS CORRECTION APPLIED

!     PILOT EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NOREV2  ( 6)      I     NO. OF DEFINED EVENTS

!     SATEM EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NOREV2  ( 7)      I     NO. OF DEFINED EVENTS

!     PAOB EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NOREV2  ( 8)      I     NO. OF DEFINED EVENTS

!     SCATT. EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NOREV2  ( 9)      I     NO. OF DEFINED EVENTS
!     NR2EVENT( 1, 9)   I     THINNED REPORT
!     NR2EVENT( 2, 9)   I     REPORTED WIND DIRECTIONS ARE TOO CLOSE TOGETHER
!     NR2EVENT( 3, 9)   I     REPORT NOT IN SWEET SPOTS (ROTATING PENCIL BEAMS)
!     NR2EVENT( 4, 9)   I     REPORT RAIN CONTAMINATED

!     LIMB EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NOREV2  (10)      I     NO. OF DEFINED EVENTS

!-----------------------------------------------------
!     DATA EVENTS PART 2:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NMXDEV2           I     MAX. NO. OF EVENTS

!     SYNOP EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NODEV2  ( 1)      I     NO. OF DEFINED EVENTS

!     AIREP EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NODEV2  ( 2)      I     NO. OF DEFINED EVENTS

!     SATOB EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NODEV2  ( 3)      I     NO. OF DEFINED EVENTS

!     DRIBU EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NODEV2  ( 4)      I     NO. OF DEFINED EVENTS

!     TEMP EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NODEV2  ( 5)      I     NO. OF DEFINED EVENTS
!     ND2EVENT( 1, 5)   I     BIAS CORRECTED VALUE USED

!     PILOT EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NODEV2  ( 6)      I     NO. OF DEFINED EVENTS

!     SATEM EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NODEV2  ( 7)      I     NO. OF DEFINED EVENTS
!     ND2EVENT( 1, 7)   I     NOT PREDEFINED LAYER
!     ND2EVENT( 2, 7)   I     LAYER FORMED BY THINNING UP
!     ND2EVENT( 3, 7)   I     LAYER FORMED BY SUMMING UP
!     ND2EVENT( 4, 7)   I     CHANNEL NOT USED IN ANALYSIS
!     ND2EVENT( 5, 7)   I     OVERWRITTEN BY ADVAR

!     PAOB EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NODEV2  ( 8)      I     NO. OF DEFINED EVENTS

!     SCATT EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NODEV2  ( 9)      I     NO. OF DEFINED EVENTS

!     LIMB EVENTS:

!     NAME            TYPE                   MEANING
!     ----            ----                   -------
!     NODEV2  (10)      I     NO. OF DEFINED EVENTS

INTEGER(KIND=JPIM) :: NEVBITOC
INTEGER(KIND=JPIM) :: NEVUPLIM
INTEGER(KIND=JPIM) :: NEVLVLIM
INTEGER(KIND=JPIM) :: NMXREV2
INTEGER(KIND=JPIM) :: NOREV2(JPMXOTP)
INTEGER(KIND=JPIM) :: NR2EVENT(JPMXRE2,JPMXOTP)
INTEGER(KIND=JPIM) :: NMXDEV2
INTEGER(KIND=JPIM) :: NODEV2(JPMXOTP)
INTEGER(KIND=JPIM) :: ND2EVENT(JPMXDE2,JPMXOTP)

!-----------------------------------------------------------------------

END MODULE YOMNMEV
