! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction
! 
! (C) Copyright 1989- Meteo-France.
! 

MODULE YOMSPJB
!*     YOMSPJB - Reference (linearisation) state for Jb
!
! M. Fisher  9 July 2015: Collected SPA7, GP7A7 and BCKG into TBACKGROUND.
! M. Fisher  21 Aug 2015: Removed SPA7. BACKGROUND is now just a TRAJ_TYPE
! E. Holm & M. Bonavita    22 Jul 2016: Hacked BACKGR 04-10 and nuptra. need to generalise

USE PARKIND1  ,ONLY : JPIM, JPRB
USE SPECTRAL_FIELDS_MOD, ONLY : SPECTRAL_FIELD
USE YOMTRAJ , ONLY : TRAJ_TYPE

IMPLICIT NONE
SAVE

TYPE(SPECTRAL_FIELD) :: SPA7
!REAL(KIND=JPRB), ALLOCATABLE, TARGET :: GP7A3(:,:,:,:) ! 3D gridpoint variables

PRIVATE
PUBLIC :: BACKGROUND, ALLOCATE_JB_REF_STATE, DEALLOCATE_BACKGROUND, SPA7

! -   For IFS, we need a global...
! NB: USE OF THIS GLOBAL IS DEPRECATED. IT WILL BE REMOVED UNDER OOPS.
!     ALL NEW CODE SHOULD USE A TRAJ_TYPE STRUCTURE PASSED BY ARGUMENT.

TYPE(TRAJ_TYPE), POINTER :: BACKGROUND => NULL()

!     ------------------------------------------------------------------

CONTAINS

!     ------------------------------------------------------------------

SUBROUTINE ALLOCATE_JB_REF_STATE(YDGEOMETRY,YGFL,YD_BG,YDGMV,YDGMV5)

USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE YOMGMV,   ONLY : TGMV
USE YOMCT0,   ONLY : LIFSTRAJ, LIFSMIN, LECMWF
USE YOMVAR,   ONLY : MUPTRA
USE ALGORITHM_STATE_MOD  , ONLY : GET_NUPTRA
USE YOMTRAJ,  ONLY : LTRAJGP, NSMAX_BACKGR00, NSMAX_BACKGR01, NSMAX_BACKGR02, NSMAX_BACKGR03,&
 & NSMAX_BACKGR04, NSMAX_BACKGR05, NSMAX_BACKGR06, NSMAX_BACKGR07,&
 & NSMAX_BACKGR08, NSMAX_BACKGR09, NSMAX_BACKGR10,&
 & NSPTRAJ, LREADGPTRAJ
USE YOM_GRIB_CODES,  ONLY : NGRBVO, NGRBD, NGRBT, NGRBQ, NGRBO3, NGRBLNSP
USE YOM_YGFL, ONLY : TYPE_GFLD
USE YOMLUN,   ONLY : NULOUT, NULERR
USE TRAJECTORY_MOD, ONLY : LTRAJHR
USE SPECTRAL_FIELDS_MOD

TYPE(GEOMETRY) ,INTENT(IN)    :: YDGEOMETRY
TYPE(TGMV)     ,INTENT(IN)    :: YDGMV
TYPE(TGMV)     ,INTENT(IN)    :: YDGMV5
TYPE(TYPE_GFLD),INTENT(INOUT) :: YGFL
TYPE(TRAJ_TYPE),INTENT(INOUT) :: YD_BG
call abor1("oifs/fc-only - ALLOCATE_JB_REF_STATE should never be called")

END SUBROUTINE ALLOCATE_JB_REF_STATE

!     ------------------------------------------------------------------

SUBROUTINE DEALLOCATE_BACKGROUND(YDBG)

USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK, JPHOOK
USE SPECTRAL_FIELDS_MOD, ONLY : DEALLOCATE_SPEC

TYPE(TRAJ_TYPE), INTENT(INOUT) :: YDBG

INTEGER(KIND=JPIM) :: IFIRST, ILAST, JJ, IBLK
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

IF (LHOOK) CALL DR_HOOK('YOMSPJB:DEALLOCATE_BACKGROUND',0,ZHOOK_HANDLE)

IF (ASSOCIATED(YDBG%SPEC)) THEN
  IFIRST = LBOUND(YDBG%SPEC(:), 1)
  ILAST  = UBOUND(YDBG%SPEC(:), 1)
  DO JJ=IFIRST,ILAST
    CALL DEALLOCATE_SPEC(YDBG%SPEC(JJ))
  ENDDO
  DEALLOCATE(YDBG%SPEC)
ENDIF

IF (ASSOCIATED(YDBG%MAIN)) THEN
  IBLK = SIZE(YDBG%MAIN(:))
  !$OMP PARALLEL DO SCHEDULE(STATIC) PRIVATE(JJ)
  DO JJ=1,IBLK
    IF (ASSOCIATED(YDBG%MAIN(JJ)%GMV))  DEALLOCATE(YDBG%MAIN(JJ)%GMV)
    IF (ASSOCIATED(YDBG%MAIN(JJ)%GMVS)) DEALLOCATE(YDBG%MAIN(JJ)%GMVS)
    IF (ASSOCIATED(YDBG%MAIN(JJ)%GFL))  DEALLOCATE(YDBG%MAIN(JJ)%GFL)
  ENDDO
  !$OMP END PARALLEL DO
  DEALLOCATE(YDBG%MAIN)
ENDIF

IF (LHOOK) CALL DR_HOOK('YOMSPJB:DEALLOCATE_BACKGROUND',1,ZHOOK_HANDLE)
END SUBROUTINE DEALLOCATE_BACKGROUND

!     ------------------------------------------------------------------

END MODULE YOMSPJB
