! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE CPG1C(YDGEOMETRY,YDMODEL,YDFIELDS)

!**** *CPG1C* - Grid point calculations.

!     Purpose.
!     --------
!           Grid point calculations.
!           It calculates eulerian and semi-lagrangian advection 
!           (latter is no working) and calls the ECMWF physics (callpar).
!           The corresponding code in the IFS is found mostly in 
!           gp_model, ec_phys, cpg and others.

!**   Interface.
!     ----------
!        *CALL* *CPG1C*

!        Explicit arguments :
!        --------------------

!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!        Called by STEPO1C.

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the single column model

!     Author.
!     -------
!        Joao Teixeira   *ECMWF*

!     Modifications.
!     --------------
!        Original : 94-01-28
!        J.Teixeira, May-94 : Semi-Lagrangian vertical advection.
!        J.Teixeira, Jan-95 : new output files.
!        J.Teixeira, May-95 : vertical advection of cloud variables
!                             and two time-level scheme.
!        A. Tompkins Oct-2002 Bug correction to relaxation terms
!        M. Ko"hler  6-6-2006 Single Column Model integration within IFS 
!        P. de Rosnay 08-Mar-2008 Update CALLPAR argument list (changed for SEKF decoupling)
!        O.Marsden & R.Forbes Jan-2022 Update to work with 47r3 IFS
!     ------------------------------------------------------------------


USE PARKIND1     , ONLY : JPIM, JPRB
USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL   , ONLY : MODEL
USE FIELDS_MOD   , ONLY : FIELDS
USE YOMHOOK      , ONLY : LHOOK    ,DR_HOOK, JPHOOK
USE INTDYN_MOD   , ONLY : YYTHW0     , YYTCTY0 ,YYTRCP0 ,YYTRCP9, &
 &                        YYTXYB0_PHY, YYTXYB9_PHY, YYTXYB0 ,YYTXYB9
USE EINT_MOD     , ONLY : SL_STRUCT
USE YOMTRAJ      , ONLY : TRAJ_PHYS_TYPE, TRAJ_SLAG_TYPE
USE DDH_MIX      , ONLY : TYP_DDH, SETDDH, CLEANDDH
USE PARDIM1C
USE PARDIM
USE YOMCT0       , ONLY : NFRPOS
USE YOMCT2       , ONLY : NSTOP2
USE YOMCT3       , ONLY : NSTEP
!USE YOMPHYDS , ONLY : YRPHYDS
!USE YOMSLPHY , ONLY : YDSLPHY
!USE YOM_YGFL , ONLY : YGFL
!USE YOMDYN   , ONLY : YRDYN
!USE YOMDYNA  , ONLY : LRWSDLR
!USE YOERIP   , ONLY : YRERIP
!USE YOMPHY2  , ONLY : YRPHY2
!USE YOMDPHY  , ONLY : YRDPHY
!USE YOMPHY3  , ONLY : YRPHY3
!USE YOEPHY   , ONLY : YREPHY
!USE YOPHNC   , ONLY : YRPHNC
!USE YOMRADF  , ONLY : YDRADF
!USE YOEPHLI  , ONLY : YREPHLI
USE YOMLOG1C
USE YOMGT1C0
USE YOMGT1C1 , ONLY : UT1      ,VT1      ,TT1      ,QT1      ,&
           &WT1      ,ST1      ,AT1      ,RNT1     ,SNT1
USE YOMGT1C9 , ONLY : UT9      ,VT9      ,TT9      ,QT9      ,&
           &WT9      ,ST9      ,AT9      ,RNT9     ,SNT9
USE YOMGP1C0 , ONLY : GP0      ,SNS0     ,ASN0     ,RSN0     ,&
           &TSN0     ,TSA0     ,WSA0     ,TIA0     ,WL0      ,&
           &TL0
USE YOMGP1C1 , ONLY : GP1      ,SNS1     ,ASN1     ,RSN1     ,&
           &TSN1     ,TSA1     ,WSA1     ,TIA1     ,WL1      ,&
           &TL1      ,EXTRP1   ,XTRP21 
USE YOMGP1C9 , ONLY : GP9      ,SNS9     ,ASN9     ,RSN9     ,&
           &TSN9     ,TSA9     ,WSA9     ,TIA9     ,WL9      ,&
           &TL9
USE YOMGPD1C , ONLY : VEXTRA   ,VEXTR2   ,&
           &VUSTRTI  ,VVSTRTI  ,VAHFSTI  ,VEVAPTI  ,VTSKTI   ,&
           &VISUND   ,IPBLTYPE ,&
           &INTYPE   ,VI10FG   ,VILSPF   ,VQSAT    ,VFEMIS   ,&
           &NOGWFIELD!, GFLSLP
USE YOMGF1C  , ONLY : UG0      ,VG0      ,VVEL0    ,UADV     ,&
           &VADV     ,TADV     ,QADV     ,ETADOTDPDETA
USE SURFACE_FIELDS_MIX , ONLY : TSURF
USE YOMLUN   , ONLY : NULOUT
USE YOMCST   , ONLY : RG, RPI
USE YOMPHYDER, ONLY : SURF_AND_MORE_TYPE, PERTURB_TYPE,&
 & MODEL_STATE_TYPE, AUX_TYPE, AUX_RAD_TYPE,&
 & DIMENSION_TYPE,FLUX_TYPE, AUX_DIAG_TYPE, DDH_SURF_TYPE,&
 & AUX_DIAG_LOCAL_TYPE, KEYS_LOCAL_TYPE, PERTURB_LOCAL_TYPE, SURF_AND_MORE_LOCAL_TYPE
USE YOMLCZ   , ONLY : GPFORCEU, GPFORCEV, GPFORCET, GPFORCEQ
USE INTDYN_MOD,ONLY : YYTXYB
USE YOE_PHYS_MWAVE , ONLY : N_PHYS_MWAVE
USE ECPHYS_STATE_TYPE_MOD, ONLY: STATE_TYPE, mask_gfl_type
USE YOECLDP            , ONLY : NCLDQR,NCLDQS,NCLDQI,NCLDQL

USE YOE_AERODIAG       , ONLY : NPAERODIAG
!USE STOPH_MIX, ONLY : YRSTOPH
!USE YOE_TILE_PROP, ONLY : YRTILEPROP
!USE YOE_CUCONVCA, ONLY : YDECUCONVCA
!USE YOECLDP  , ONLY : YDECLDP
!USE YOMMDDH  , ONLY : YDMDDH
!USE YOERAD   , ONLY : YDERAD
!USE PTRSLB2  , ONLY : YRPTRSLB2


IMPLICIT NONE

TYPE (GEOMETRY),       INTENT(INOUT) :: YDGEOMETRY
TYPE (MODEL),  TARGET, INTENT(INOUT) :: YDMODEL
TYPE (FIELDS), TARGET, INTENT(INOUT) :: YDFIELDS
TYPE (SURF_AND_MORE_TYPE) :: ZSURF
TYPE (PERTURB_TYPE)       :: ZPERT
TYPE (MODEL_STATE_TYPE)   :: ZSLPHY9
TYPE (AUX_TYPE)           :: ZAUX
TYPE (AUX_RAD_TYPE)       :: ZRAD
TYPE (DIMENSION_TYPE)     :: IDIMS
TYPE (DDH_SURF_TYPE)      :: ZDDHS
TYPE (FLUX_TYPE)          :: FLUX
TYPE (AUX_DIAG_TYPE)      :: ZDIAG
TYPE (STATE_TYPE) :: STATE_T0, TENDENCY_DYN, TENDENCY_CML
TYPE (STATE_TYPE) :: STATE_TMP, TENDENCY_TMP
TYPE (STATE_TYPE) :: TENDENCY_SATADJ, TENDENCY_VDF, TENDENCY_LOC
TYPE (STATE_TYPE), ALLOCATABLE :: TENDENCY_PHY(:)
TYPE (KEYS_LOCAL_TYPE) :: ZLLKEYS
TYPE (AUX_DIAG_LOCAL_TYPE) :: ZAUXL
TYPE (PERTURB_LOCAL_TYPE) :: ZPERTL
TYPE (SURF_AND_MORE_LOCAL_TYPE) :: ZSURFL
TYPE (MASK_GFL_TYPE) :: KEYMASK

INTEGER(KIND=JPIM), PARAMETER :: KLON = 1
INTEGER(KIND=JPIM) :: ICSS, IBL, J2D, JARP

REAL(KIND=JPRB)   :: ZSPT0(1)  ! just duplication of SPT0

REAL(KIND=JPRB), ALLOCATABLE :: ZGMV(:,:,:), ZGMVT1(:,:,:)


!     --- TENDENCIES (updated, dynamics, physics) ---

REAL(KIND=JPRB) :: ZUTEND(YDGEOMETRY%YRDIMV%NFLEVG),   ZVTEND(YDGEOMETRY%YRDIMV%NFLEVG),   ZTTEND(YDGEOMETRY%YRDIMV%NFLEVG),&
                  &ZQTEND(YDGEOMETRY%YRDIMV%NFLEVG),&
                  &ZLTEND(YDGEOMETRY%YRDIMV%NFLEVG),   ZITEND(YDGEOMETRY%YRDIMV%NFLEVG),   ZATEND(YDGEOMETRY%YRDIMV%NFLEVG),&
                  &ZRTEND(YDGEOMETRY%YRDIMV%NFLEVG),   ZSTEND(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZUTEND_D(YDGEOMETRY%YRDIMV%NFLEVG), ZVTEND_D(YDGEOMETRY%YRDIMV%NFLEVG), ZTTEND_D(YDGEOMETRY%YRDIMV%NFLEVG),&
                  &ZQTEND_D(YDGEOMETRY%YRDIMV%NFLEVG),&
                  &ZLTEND_D(YDGEOMETRY%YRDIMV%NFLEVG), ZITEND_D(YDGEOMETRY%YRDIMV%NFLEVG), ZATEND_D(YDGEOMETRY%YRDIMV%NFLEVG),&
                  &ZRTEND_D(YDGEOMETRY%YRDIMV%NFLEVG),   ZSTEND_D(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZUTEND_P(YDGEOMETRY%YRDIMV%NFLEVG), ZVTEND_P(YDGEOMETRY%YRDIMV%NFLEVG), ZTTEND_P(YDGEOMETRY%YRDIMV%NFLEVG),&
                  &ZQTEND_P(YDGEOMETRY%YRDIMV%NFLEVG),&
                  &ZLTEND_P(YDGEOMETRY%YRDIMV%NFLEVG), ZITEND_P(YDGEOMETRY%YRDIMV%NFLEVG), ZATEND_P(YDGEOMETRY%YRDIMV%NFLEVG),&
                  &ZRTEND_P(YDGEOMETRY%YRDIMV%NFLEVG),   ZSTEND_P(YDGEOMETRY%YRDIMV%NFLEVG)

REAL(KIND=JPRB) :: ZPRE9  (0:YDGEOMETRY%YRDIMV%NFLEVG)      ! HALF LEVEL PRESSURE
REAL(KIND=JPRB) :: ZPRE9F (YDGEOMETRY%YRDIMV%NFLEVG)        ! FULL LEVEL PRESSURE
REAL(KIND=JPRB) :: ZR9    (YDGEOMETRY%YRDIMV%NFLEVG)        ! R
REAL(KIND=JPRB) :: ZCP9   (YDGEOMETRY%YRDIMV%NFLEVG)        ! CP
REAL(KIND=JPRB) :: ZKAP   (YDGEOMETRY%YRDIMV%NFLEVG)        ! K=R/CP
REAL(KIND=JPRB) :: ZPHI9  (0:YDGEOMETRY%YRDIMV%NFLEVG)      ! HALF LEVEL GEOPOTENTIAL
REAL(KIND=JPRB) :: ZPHIF9 (YDGEOMETRY%YRDIMV%NFLEVG)        ! FULL LEVEL GEOPOTENTIAL

!     --- SURFACE TENDENCIES ---

REAL(KIND=JPRB) :: ZEXTRE1 (YDMODEL%YRML_PHY_MF%YRPHYDS%JPCXP,YDMODEL%YRML_PHY_MF%YRPHYDS%JPVXP) , ZXTR2E1 (YDMODEL%YRML_PHY_MF%YRPHYDS%JPVXP2)

!     --- MISCELLANEOUS PARAMETERISATIONS, 2D ARRAYS ---

REAL(KIND=JPRB) :: ZNEB  (YDGEOMETRY%YRDIMV%NFLEVG) , ZQLI (YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZQICE (YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: ZETAP (YDGEOMETRY%YRDIMV%NFLEVG)

!     --- OZONE ---

REAL(KIND=JPRB) :: ZO3(YDGEOMETRY%YRDIMV%NFLEVG),ZTENO3(YDGEOMETRY%YRDIMV%NFLEVG)


!     --- dummy GFL variables for callpar ---

REAL(KIND=JPRB) :: ZGFL     (KLON,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM)
REAL(KIND=JPRB) :: ZPHTENGFL(KLON,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NUMFLDS) !QUERY: No longer used
REAL(KIND=JPRB) :: ZTENGFL  (KLON,YDGEOMETRY%YRDIMV%NFLEVG,YDMODEL%YRML_GCONF%YGFL%NDIM1)
REAL(KIND=JPRB) :: ZTENGMV  (KLON,YDGEOMETRY%YRDIMV%NFLEVG,YDFIELDS%YRGMV%YT1%NDIM)
REAL(KIND=JPRB) :: ZPHYS_MWAVE(KLON,YDGEOMETRY%YRDIMV%NFLEVG,N_PHYS_MWAVE)

REAL(KIND=JPRB), TARGET :: ZXYB9(KLON,YDGEOMETRY%YRDIMV%NFLEVG,YYTXYB%NDIM)

REAL(KIND=JPRB) :: WSN1(KLON) ! Liquid water in snow pack - set here for now

REAL(KIND=JPRB) :: ZCGPP(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) :: ZCREC(YDGEOMETRY%YRDIM%NPROMA,YDGEOMETRY%YRDIM%NGPBLKS)
REAL(KIND=JPRB) :: ZAG(KLON)
REAL(KIND=JPRB) :: ZRECO(KLON)

!     --- LOCAL INTEGER SCALARS ---

INTEGER(KIND=JPIM) :: IEND, IST, IA, J, JALEV, JJ, JLEV, JROF, JKGLO
INTEGER(KIND=JPIM) :: ILEVOML ! number of ocean model levels

!     --- LOCAL LOGICAL SCALARS ---

LOGICAL :: LLFSTEP, LLLSTEP
 
!     --- LOCAL REAL SCALARS ---

REAL(KIND=JPRB) :: ZBETA        ,ZDT          ,&
                  &ZCPR         ,ZCPS         ,ZSPR         ,ZSPS         ,ZIRUNOF      ,&
                  &ZISLHF       ,ZSWRF0       ,ZSWRFN       ,ZLWRF0       ,ZLWRFN

REAL(KIND=JPRB) :: ZBETA_SPONGE, RDTRELAX_SPONGE

REAL(KIND=JPRB) :: ZDUM(YDGEOMETRY%YRDIMV%NFLEVG), ZDUM1(KLON)


!  Arrays for pressure related quantities
!REAL(KIND=JPRB),ALLOCATABLE :: ZPRS1O(:,:),ZPRSF1O(:,:),ZSPD9(:,:)
!REAL(KIND=JPRB) :: ZASR2(YDGEOMETRY%YRDIM%NPROMDLR,YDGEOMETRY%YRDIMV%NFLEVG)
!REAL(KIND=JPRB) :: ZRSAH(YDGEOMETRY%YRDIM%NPROMDLR,0:YDGEOMETRY%YRDIMV%NFLEVG)

REAL(KIND=JPRB), DIMENSION(:,:,:,:,:), ALLOCATABLE, TARGET :: ZSPPTGFIX

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------
#include "gptfs1c.intfb.h"
#include "raddrv.intfb.h"
#include "callpar.intfb.h"
#include "gpgeo.intfb.h"
#include "gphpre.intfb.h"
#include "cpdyn1c.intfb.h"
#include "gpcty1c.intfb.h"
#include "wrtd1c.intfb.h"
#include "lacdyn1c.intfb.h"
#include "lapine1c.intfb.h"
#include "gptf11c.intfb.h"
#include "gptf21c.intfb.h"
#include "accum1c.intfb.h"
#include "wrtd1c_nc.intfb.h"
#include "cpspe.intfb.h"
#include "gprcp.intfb.h"
#include "phys_arrays_ini.intfb.h"
#include "phys_arrays_fin.intfb.h"
! #include "phys_dim_ini.intfb.h"
! #include "gnhdlrb.intfb.h"
#include "abor1.intfb.h"
!     ------------------------------------------------------------------


IF (LHOOK) CALL DR_HOOK('CPG1C',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM,YDMP=>YDGEOMETRY%YRMP, &
 & YDSURF=>YDFIELDS%YRSURF,YDDYN=>YDMODEL%YRML_DYN%YRDYN, YDECLDP=>YDMODEL%YRML_PHY_EC%YRECLDP, &
 & YDERAD=>YDMODEL%YRML_PHY_RAD%YRERAD, YDECUCONVCA=>YDMODEL%YRML_PHY_EC%YRECUCONVCA, &
 & YDRIP=>YDMODEL%YRML_GCONF%YRRIP, YDMDDH=>YDMODEL%YRML_DIAG%YRMDDH, &
 & YDERIP=>YDMODEL%YRML_PHY_RAD%YRERIP, YDSTOPH=>YDMODEL%YRML_PHY_STOCH%YRSTOPH, &
 & YDVAB=>YDGEOMETRY%YRVAB, YDSLPHY=>YDMODEL%YRML_PHY_G%YRSLPHY, &
 & YDDPHY=>YDMODEL%YRML_PHY_G%YRDPHY, YGFL=>YDMODEL%YRML_GCONF%YGFL, &
 & YDSTA=>YDGEOMETRY%YRSTA, YDRADF=>YDMODEL%YRML_PHY_RAD%YRRADF, &
 & YDGSGEOM=>YDGEOMETRY%YRGSGEOM,YDGSGEOM_NB=>YDGEOMETRY%YRGSGEOM_NB,  &
 & YDGMV=>YDFIELDS%YRGMV, &
 & YDEPHY=>YDMODEL%YRML_PHY_EC%YREPHY, YDEPHLI=>YDMODEL%YRML_PHY_SLIN%YREPHLI)
ASSOCIATE(NDIM=>YGFL%NDIM, NDIM1=>YGFL%NDIM1, NUMFLDS=>YGFL%NUMFLDS, &
 & YA=>YGFL%YA, YI=>YGFL%YI, YL=>YGFL%YL, YNOGW=>YGFL%YNOGW, YO3=>YGFL%YO3, &
 & YQ=>YGFL%YQ, YR=>YGFL%YR, YS=>YGFL%YS, YPH9=>YDGMV%YPH9, &
 & LTWOTL=>YDMODEL%YRML_DYN%YRDYNA%LTWOTL, &
 & LSLAG=>YDMODEL%YRML_DYN%YRDYNA%LSLAG, &
 & LSLDIA=>YDMODEL%YRML_DYN%YRDYNA%LSLDIA, &
 & NPROMA=>YDDIM%NPROMA, NSMAX=>YDDIM%NSMAX, &
 & NFLEVG=>YDDIMV%NFLEVG, &
 & NCEXTR=>YDDPHY%NCEXTR, NCOM=>YDDPHY%NCOM, NCSI=>YDDPHY%NCSI, &
 & NCSNEC=>YDDPHY%NCSNEC, NCXP=>YDDPHY%NCXP, NTILES=>YDDPHY%NTILES, &
 & NVCLIS=>YDDPHY%NVCLIS, NVEXTR=>YDDPHY%NVEXTR, NVEXTRDYN=>YDDPHY%NVEXTRDYN, &
 & NVXP=>YDDPHY%NVXP, NVXP2=>YDDPHY%NVXP2, NVXTR2=>YDDPHY%NVXTR2, &
 & REPSP1=>YDDYN%REPSP1, &
 & RAMIN=>YDECLDP%RAMIN, RLMIN=>YDECLDP%RLMIN, NRADFR=>YDERAD%NRADFR, &
 & RCAPECONVCA=>YDECUCONVCA%RCAPECONVCA, RCUCONVCA=>YDECUCONVCA%RCUCONVCA, &
 & RNLCONVCA=>YDECUCONVCA%RNLCONVCA,LCUCONV_CA=>YDECUCONVCA%LCUCONV_CA, &
 & LEPCLD=>YDEPHY%LEPCLD, LERADI=>YDEPHY%LERADI, LEPHYS=>YDEPHY%LEPHYS, &
 & YT1=>YDGMV%YT1, &
 & NDHFIIS=>YDMDDH%NDHFIIS, NDHFSSS=>YDMDDH%NDHFSSS, NDHFTIS=>YDMDDH%NDHFTIS, &
 & NDHFTLS=>YDMDDH%NDHFTLS, NDHFTSS=>YDMDDH%NDHFTSS, NDHFTTS=>YDMDDH%NDHFTTS, &
 & NDHFWLS=>YDMDDH%NDHFWLS, NDHVIIS=>YDMDDH%NDHVIIS, NDHVSSS=>YDMDDH%NDHVSSS, &
 & NDHVTIS=>YDMDDH%NDHVTIS, NDHVTLS=>YDMDDH%NDHVTLS, NDHVTSS=>YDMDDH%NDHVTSS, &
 & NDHVTTS=>YDMDDH%NDHVTTS, NDHVWLS=>YDMDDH%NDHVWLS, &
 & LENCLD2=>YDMODEL%YRML_PHY_SLIN%YRPHNC%LENCLD2, &
 & NSTART=>YDRIP%NSTART, RCODEC=>YDRIP%RCODEC, RCOVSR=>YDRIP%RCOVSR, &
 & RIP0=>YDRIP%RIP0, RSIDEC=>YDRIP%RSIDEC, RSIVSR=>YDRIP%RSIVSR, TDT=>YDRIP%TDT, &
 & SAVTEND=>YDSLPHY%SAVTEND, &
 & GPTEMP=>YDSTOPH%GPTEMP, GPTOTDISS_SMOOTH=>YDSTOPH%GPTOTDISS_SMOOTH, &
 & GPVORTGRAD=>YDSTOPH%GPVORTGRAD, RSTOPHCA=>YDSTOPH%RSTOPHCA, LFORCENL=>YDSTOPH%LFORCENL, &
 & LSTOPH_SPBS_T=>YDSTOPH%LSTOPH_SPBS_T, &
 & RCODECM=>YDERIP%RCODECM, RSIDECM=>YDERIP%RSIDECM, RCOVSRM=>YDERIP%RCOVSRM, &
 & RSIVSRM=>YDERIP%RSIVSRM, MSLB2VVEL=>YDMODEL%YRML_DYN%YRPTRSLB2%MSLB2VVEL, &
 & TSPHY=>YDMODEL%YRML_PHY_MF%YRPHY2%TSPHY,RII0=>YDMODEL%YRML_PHY_MF%YRPHY3%RII0, &
 & YSD_V2D=>YDFIELDS%YRSURF%YSD_V2D, YSD_V3D=>YDFIELDS%YRSURF%YSD_V3D, YSD_VF=>YDFIELDS%YRSURF%YSD_VF, &
 & YSD_WS=>YDFIELDS%YRSURF%YSD_WS, YSD_WSD=>YDFIELDS%YRSURF%YSD_WSD, YSD_WWD=>YDFIELDS%YRSURF%YSD_WWD, &
 & YSD_X2D=>YDFIELDS%YRSURF%YSD_X2D, YSD_XAD=>YDFIELDS%YRSURF%YSD_XAD, YSP_EPD=>YDFIELDS%YRSURF%YSP_EPD, &
 & YSP_OMD=>YDFIELDS%YRSURF%YSP_OMD, YSP_RR=>YDFIELDS%YRSURF%YSP_RR, YSP_RRD=>YDFIELDS%YRSURF%YSP_RRD, &
 & YSP_SB=>YDFIELDS%YRSURF%YSP_SB, YSP_SBD=>YDFIELDS%YRSURF%YSP_SBD, YSP_SG=>YDFIELDS%YRSURF%YSP_SG, &
 & YSP_SGD=>YDFIELDS%YRSURF%YSP_SGD, YSP_SL=>YDFIELDS%YRSURF%YSP_SL, YSP_X2D=>YDFIELDS%YRSURF%YSP_X2D, &
 & YSP_OM=>YDFIELDS%YRSURF%YSP_OM, &
 & SD_VF=>YDFIELDS%YRSURF%SD_VF,SD_VN=>YDFIELDS%YRSURF%SD_VN,SP_SL=>YDFIELDS%YRSURF%SP_SL, &
 & SD_VD=>YDFIELDS%YRSURF%SD_VD,SD_PF=>YDFIELDS%YRSURF%SD_PF,SP_SB=>YDFIELDS%YRSURF%SP_SB, &
 & SP_SG=>YDFIELDS%YRSURF%SP_SG,SP_RR=>YDFIELDS%YRSURF%SP_RR,SP_EP=>YDFIELDS%YRSURF%SP_EP, &
 & SP_X2=>YDFIELDS%YRSURF%SP_X2,SP_OM=>YDFIELDS%YRSURF%SP_OM,SD_WS=>YDFIELDS%YRSURF%SD_WS, &
 & SD_WW=>YDFIELDS%YRSURF%SD_WW,SD_V2=>YDFIELDS%YRSURF%SD_V2,SD_V3=>YDFIELDS%YRSURF%SD_V3)


!*       1.   INITIAL COMPUTATIONS.
!             ---------------------

ICSS=YSP_SBD%NLEVS
IST=1
IEND=1

IF(NSTEP > 0) THEN
  LLFSTEP=.FALSE.
ELSE
  LLFSTEP=.TRUE.
ENDIF
IF(NSTEP < NSTOP2) THEN
  LLLSTEP=.FALSE.
ELSE
  LLLSTEP=.TRUE.
ENDIF

ALLOCATE(ZSPPTGFIX(NPROMA,NFLEVG,4,2,1))

ZDUM1(1)=0.0_JPRB
ZDUM(1:NFLEVG)=0.0_JPRB


!*       1.1  TIME STEP.
!             ----------

ZDT= TDT

TSPHY=MAX(TDT,1.0_JPRB)

!*       1.3  SURFACE PRESSURE VARIABLES. 
!             NOTE THAT Ps DOES NOT CHANGE WITH TIME.
!             ---------------------------------------

ZPRE9 (NFLEVG)=EXP(SPT0) ! SPT0 is in YOMGT1C0

!*       1.5  INITIALIZING SURFACE VARIABLES AT T-DT IN THE FIRST 
!             TIME-STEP OR MAKING GP9=GP0 FOR THE TWO TIME LEVEL SCHEME.
!             ----------------------------------------------------------

IF (LLFSTEP.OR.LTWOTL) THEN

  !SP_SG(:,YSP_SG%YF%MP9,1) = SNS0(:)
  SNS9 = SNS0 
  SNS1 = SNS0

  !SP_SG(:,YSP_SG%YA%MP9,1) = ASN0(:)
  ASN9 = ASN0
  ASN1 = ASN0

  !SP_SG(:,YSP_SG%YR%MP9,1) = RSN0(:)
  RSN9 = RSN0
  RSN1 = RSN0

  !SP_SG(:,YSP_SG%YT%MP9,1) = TSN0(:)
  TSN9 = TSN0
  TSN1 = TSN0

  !SP_RR(:,YSP_RR%YW%MP9,1) = WL0(:)
  WL9  = WL0
  WL1  = WL0

  !SP_RR(:,YSP_RR%YT%MP9,1) = TL0(:)
  TL9  = TL0
  TL1  = TL0

  DO JJ=1,ICSS

    !SP_SB(1,JJ,YSP_SB%YT%MP9,1)  = TSA0(JJ)
    TSA9(JJ) = TSA0(JJ)
    TSA1(JJ) = TSA0(JJ)

    !SP_SB(1,JJ,YSP_SB%YQ%MP9,1)  = WSA0(JJ)
    WSA9(JJ) = WSA0(JJ)
    WSA1(JJ) = WSA0(JJ)

    !SP_SB(1,JJ,YSP_SB%YTL%MP9,1) = TIA0(JJ)
    TIA9(JJ) = TIA0(JJ)
    TIA1(JJ) = TIA0(JJ)

  ENDDO

ENDIF


!*       2.   PART 2 OF TIME FILTERING OR GT9=GT0 
!             IN THE TWO TIME TIME LEVEL SCHEME.
!             -----------------------------------

IF (LTWOTL) THEN

  DO JALEV=1,NFLEVG
    UT9(JALEV)=UT0(JALEV)
    VT9(JALEV)=VT0(JALEV)
    TT9(JALEV)=TT0(JALEV)
    QT9(JALEV)=QT0(JALEV)
    WT9(JALEV)=WT0(JALEV)
    ST9(JALEV)=ST0(JALEV)
    AT9(JALEV)=AT0(JALEV)
    RNT9(JALEV)=RNT0(JALEV)
    SNT9(JALEV)=SNT0(JALEV)
  ENDDO

ELSE

  CALL GPTF21C(YDGEOMETRY,YDMODEL,IST,IEND,LLFSTEP,&
   &UT0(1:NFLEVG),VT0(1:NFLEVG),TT0(1:NFLEVG),QT0(1:NFLEVG),ZDUM,ZDUM,ZDUM,ZDUM,ZDUM1,ZDUM1,ZDUM1,&
   &UT9(1:NFLEVG),VT9(1:NFLEVG),TT9(1:NFLEVG),QT9(1:NFLEVG),ZDUM,ZDUM,ZDUM,ZDUM,ZDUM1,ZDUM1,ZDUM1,&
   &WT0(1:NFLEVG),ST0(1:NFLEVG),AT0(1:NFLEVG),RNT0(1:NFLEVG),SNT0(1:NFLEVG),ZDUM,ZDUM,ZDUM,ZDUM,ZDUM,ZDUM,&
   &WT9(1:NFLEVG),ST9(1:NFLEVG),AT9(1:NFLEVG),RNT9(1:NFLEVG),SNT9(1:NFLEVG),ZDUM,ZDUM,ZDUM,ZDUM,ZDUM,ZDUM)

ENDIF


!*       3.   COMPUTATION OF PRESSURE AT HALF AND FULL LEVELS.
!             ---------------------------------------

CALL GPHPRE(NPROMA,NFLEVG,IST,IEND,YDVAB,YDGEOMETRY%YRCVER,ZPRE9,PXYB=ZXYB9,PRESF=ZPRE9F)


!*       6.   COMPUTATION OF R, CP AND KAPPA.
!             -------------------------------

CALL GPRCP(NPROMA,IST,IEND,NFLEVG,PQ=QT9,PQI=ST9,PQL=WT9,PCP=ZCP9,PR=ZR9,PKAP=ZKAP)



!*       7.   COMPUTATION OF HYDROSTATIC EQUATION.
!             ------------------------------------

ZPHI9(NFLEVG)=YDGEOMETRY%YROROG(1)%OROG(1)*RG

CALL GPGEO(NPROMA,IST,IEND,NFLEVG,ZPHI9,ZPHIF9,TT9,ZR9,&
      & ZXYB9(1,:,YYTXYB%M_LNPR), ZXYB9(1,:,YYTXYB%M_ALPH),YDGEOMETRY%YRVERT_GEOM) 


!*       7.1  COMPUTATION OF W AT HALF-LEVELS.
!             --------------------------------

!C      IF (LTWOTL) THEN

!C        DO JF=1,JPGF
!C          GF(JF)=0.5*(GF(JF)+GF1(JF))
!C        ENDDO

!C      ENDIF         

!... in case "etadotdpdeta" is not available (e.g. idealized setup):
!... etadotdpdeta ~ omega (needed at half levels) 
IF (.NOT. LETADOT) THEN
  CALL GPCTY1C(YDGEOMETRY%YRDIMV,NFLEVG, VVEL0(1,1:NFLEVG), ETADOTDPDETA(0:NFLEVG))
ENDIF


!*       8.   COMPUTATION OF ADIABATIC TENDENCIES.
!             ------------------------------------

! Interpolated physics tendencis for SLPHYS
ALLOCATE(ZSLPHY9%U(NPROMA,NFLEVG)) 
ALLOCATE(ZSLPHY9%V(NPROMA,NFLEVG))
ALLOCATE(ZSLPHY9%T(NPROMA,NFLEVG))
ALLOCATE(ZSLPHY9%GFL(NPROMA,NFLEVG,YGFL%NUMFLDS))

IF (LDYNFOR) THEN

  IF(LWADV) THEN

    IF (LSLAG) THEN

!*       8.1  SEMI-LAGRANGIAN.
!             ----------------
        
      CALL LACDYN1C(YDGEOMETRY%YRVETA,NFLEVG , VVEL0(1,1:NFLEVG),ETADOTDPDETA,ZXYB9(1,:,YYTXYB%M_DELP),&
        &  ZETAP)

      CALL LAPINE1C(YDGEOMETRY,YDMODEL, NFLEVG,ZDT,ZETAP,QT9(1:NFLEVG),TT9(1:NFLEVG)&
       & ,UT9(1:NFLEVG),VT9(1:NFLEVG),AT9(1:NFLEVG),WT9(1:NFLEVG),ST9(1:NFLEVG)&
       & ,ZKAP,ZPRE9F,VVEL0(1,1:NFLEVG),YDGSGEOM(1)%RCORI(1),UG0(1:NFLEVG),VG0(1:NFLEVG)&
       & ,TT0(1:NFLEVG), UT0(1:NFLEVG), VT0(1:NFLEVG)&
       & ,TADV(1:NFLEVG) , QADV(1:NFLEVG) , UADV(1:NFLEVG) , VADV(1:NFLEVG)&
       & ,ZUTEND,ZVTEND,ZTTEND,ZQTEND,ZATEND,ZLTEND,ZITEND&
       & ,SAVTEND(1,:,:,1),ydfields%yrgfl%GFLSLP(1,:,:,1),ZSLPHY9)

    ELSE

!*       8.2  EULERIAN.
!             ---------
      CALL CPDYN1C(YDGEOMETRY%YRDIMV,LTWOTL,NFLEVG,ZDT,ZPRE9F,VVEL0(1,1:NFLEVG), YDGSGEOM(1)%RCORI(1)&
       &,UT0(1:NFLEVG),VT0(1:NFLEVG),TT0(1:NFLEVG),QT0(1:NFLEVG)&
       &,AT0(1:NFLEVG),WT0(1:NFLEVG),ST0(1:NFLEVG)&
       &,ZKAP,UG0(1:NFLEVG),VG0(1:NFLEVG),ETADOTDPDETA,ZXYB9(1,:,YYTXYB%M_DELP)&
       &,UADV(1:NFLEVG),VADV(1:NFLEVG),TADV(1:NFLEVG),QADV(1:NFLEVG)&
       &,ZUTEND,ZVTEND,ZTTEND,ZQTEND,ZATEND,ZLTEND,ZITEND)
    
    ENDIF

  ELSE

    DO JLEV=1,NFLEVG
      ZUTEND(JLEV)=UADV(JLEV)
      ZVTEND(JLEV)=VADV(JLEV)
      ZTTEND(JLEV)=TADV(JLEV)
      ZQTEND(JLEV)=QADV(JLEV)
      ZATEND(JLEV)=0.0_JPRB
      ZLTEND(JLEV)=0.0_JPRB
      ZITEND(JLEV)=0.0_JPRB
    ENDDO

  ENDIF

ELSE

!*       8.3  ADIABATIC TENDENCIES SET TO ZERO.
!             ---------------------------------

  DO JLEV=1,NFLEVG
    ZUTEND(JLEV)=0.0_JPRB
    ZVTEND(JLEV)=0.0_JPRB
    ZTTEND(JLEV)=0.0_JPRB
    ZQTEND(JLEV)=0.0_JPRB
    ZATEND(JLEV)=0.0_JPRB
    ZLTEND(JLEV)=0.0_JPRB
    ZITEND(JLEV)=0.0_JPRB
  ENDDO

  ! Interpolated physics tendencies
  ZSLPHY9%U(:,:)     = 0.0_JPRB
  ZSLPHY9%V(:,:)     = 0.0_JPRB
  ZSLPHY9%T(:,:)     = 0.0_JPRB
  ZSLPHY9%GFL(:,:,:) = 0.0_JPRB

ENDIF

! rain, snow tendencies initialized to 0 in all cases
DO JLEV=1,NFLEVG
  ZRTEND(JLEV)=0.0_JPRB
  ZSTEND(JLEV)=0.0_JPRB
ENDDO

!*       8.4  DEFINE DYNAMICS TENDENCIES.
!             ---------------------------

ZQTEND_D = ZQTEND
ZTTEND_D = ZTTEND
ZUTEND_D = ZUTEND
ZVTEND_D = ZVTEND
ZLTEND_D = ZLTEND
ZITEND_D = ZITEND
ZATEND_D = ZATEND
ZRTEND_D = ZRTEND
ZSTEND_D = ZSTEND


!     SOLAR FLUX AT THE TOP (/YOMPHY3/)
!      introduce season correction

RII0 = RIP0


!*      11.   PROVISIONAL OZONE. 
!             ------------------  

DO JLEV=1,NFLEVG
  ZO3(JLEV)=0.0_JPRB
  ZTENO3(JLEV)=0.0_JPRB
ENDDO


!*      11.5  CALLPAR INPUT VALUES
!             --------------------

!       dummy GFL variables

ZGFL      = 0.0_JPRB
! The following commented out for Ozone and Non-orog gw fields for now
!ZGFL(1,1:NFLEVG,YO3%MP9_PH)= ZO3(1:NFLEVG)
ZGFL(1,1:NFLEVG,YQ%MP9_PH)= QT9(1:NFLEVG)
ZGFL(1,1:NFLEVG,YL%MP9_PH)= WT9(1:NFLEVG)
ZGFL(1,1:NFLEVG,YI%MP9_PH)= ST9(1:NFLEVG)
ZGFL(1,1:NFLEVG,YR%MP9_PH)= RNT9(1:NFLEVG)
ZGFL(1,1:NFLEVG,YS%MP9_PH)= SNT9(1:NFLEVG)
ZGFL(1,1:NFLEVG,YA%MP9_PH)= AT9(1:NFLEVG)
!ZGFL(1,1:NFLEVG,YNOGW(1)%MP)=NOGWFIELD(1:NFLEVG,1)
!ZGFL(1,1:NFLEVG,YNOGW(2)%MP)=NOGWFIELD(1:NFLEVG,2)

ZPHTENGFL = 0.0_JPRB ! QUERY: No longer used
ZTENGFL   = 0.0_JPRB

!ZTENGFL(1,1:NFLEVG,YO3%MP1)= ZTENO3_D(1:NFLEVG)
ZTENGFL(1,1:NFLEVG,YQ%MP1)= ZQTEND_D(1:NFLEVG) 
ZTENGFL(1,1:NFLEVG,YL%MP1)= ZLTEND_D(1:NFLEVG)
ZTENGFL(1,1:NFLEVG,YI%MP1)= ZITEND_D(1:NFLEVG)
ZTENGFL(1,1:NFLEVG,YA%MP1)= ZATEND_D(1:NFLEVG)
ZTENGFL(1,1:NFLEVG,YR%MP1)= ZRTEND_D(1:NFLEVG)
ZTENGFL(1,1:NFLEVG,YS%MP1)= ZSTEND_D(1:NFLEVG)

!IF (LEPHYS) THEN
!*      12.   CALL PHYSICS.
!             -------------

CALL IDIMS%INIT(YDGEOMETRY, YDMODEL, YDSURF)

IBL=1
IEND = 1
JKGLO = 1

!! point the YGFL pointer in self%yrgfl to that in the model passed in
YDFIELDS%YRGFL%YGFL => YDMODEL%YRML_GCONF%YGFL

IF (.NOT. ALLOCATED(YDFIELDS%YRGMV%GMVT1))  ALLOCATE(YDFIELDS%YRGMV%GMVT1(1,NFLEVG,YT1%NDIM,1))
IF (.NOT. ALLOCATED(YDFIELDS%YRGFL%GFLT1))  ALLOCATE(YDFIELDS%YRGFL%GFLT1(1,NFLEVG,NDIM1,1))
IF (.NOT. ALLOCATED(YDFIELDS%YRGMV%GMVT1S)) ALLOCATE(YDFIELDS%YRGMV%GMVT1S(1,YT1%NDIMS,1))
IF (.NOT. ALLOCATED(YDFIELDS%YRGMV%GMVS)) ALLOCATE(YDFIELDS%YRGMV%GMVS(1,1,1))

! Create field registry, if it hasn't been set up yet
IF (.NOT. ASSOCIATED(YDFIELDS%VARIABLES)) THEN
  CALL YDFIELDS%REGISTRY%INIT(YDGEOMETRY)
  CALL YDFIELDS%REGISTRY%REGISTER_GEOMETRY(YDFIELDS%VARIABLES, YDGEOMETRY)
  CALL YDFIELDS%REGISTRY%REGISTER_GMV_FIELDS(YDFIELDS%VARIABLES, YDFIELDS%YRGMV)
  CALL YDFIELDS%REGISTRY%REGISTER_GFL_FIELDS(YDFIELDS%VARIABLES, YDFIELDS%YRGFL, YDFIELDS%YRGFL%YGFL)
  CALL YDFIELDS%REGISTRY%REGISTER_SURFACE_FIELDS(YDFIELDS%SURFVARS, YDSURF)
  CALL YDFIELDS%REGISTRY%REGISTER_EC_PHYS_FIELDS(YDFIELDS%VARIABLES, YDFIELDS%YEC_PHYS_FIELDS)
  CALL YDFIELDS%REGISTRY%REGISTER_PHYSICS_RADIATION_FIELDS(YDFIELDS%VARIABLES, YDFIELDS%STATE_MODEL%YRML_PHY_RAD)
END IF


! Create keymask to signal which variables are active within a single state/tendency
CALL KEYMASK%INIT(Q=YDFIELDS%VARIABLES%Q%LACTIVE, O3=YDFIELDS%VARIABLES%O3%LACTIVE, A=YDFIELDS%VARIABLES%A%LACTIVE, &
 &                QL=YDFIELDS%VARIABLES%L%LACTIVE, QI=YDFIELDS%VARIABLES%I%LACTIVE, &
 &                QR=YDFIELDS%VARIABLES%R%LACTIVE, QS=YDFIELDS%VARIABLES%S%LACTIVE, TKE=YDFIELDS%VARIABLES%TKE%LACTIVE)


! Initialize STATE_T0 from PH9 field pointers and TENDENCY_DYN from T1 pointers
CALL STATE_T0%INIT(YDGEOMETRY, KEYMASK=KEYMASK, &
 &                 U=YDFIELDS%VARIABLES%U%FPH9, V=YDFIELDS%VARIABLES%V%FPH9, T=YDFIELDS%VARIABLES%T%FPH9, O3=YDFIELDS%VARIABLES%O3%FPH9, &
 &                 Q=YDFIELDS%VARIABLES%Q%FPH9, A=YDFIELDS%VARIABLES%A%FPH9, QL=YDFIELDS%VARIABLES%L%FPH9, QI=YDFIELDS%VARIABLES%I%FPH9, &
 &                 QR=YDFIELDS%VARIABLES%R%FPH9, QS=YDFIELDS%VARIABLES%S%FPH9, TKE=YDFIELDS%VARIABLES%TKE%FPH9)
CALL TENDENCY_DYN%INIT(YDGEOMETRY, KEYMASK=KEYMASK, &
 &                     U=YDFIELDS%VARIABLES%U%FT1, V=YDFIELDS%VARIABLES%V%FT1, T=YDFIELDS%VARIABLES%T%FT1, O3=YDFIELDS%VARIABLES%O3%FT1, &
 &                     Q=YDFIELDS%VARIABLES%Q%FT1, A=YDFIELDS%VARIABLES%A%FT1, QL=YDFIELDS%VARIABLES%L%FT1, QI=YDFIELDS%VARIABLES%I%FT1, &
 &                     QR=YDFIELDS%VARIABLES%R%FT1, QS=YDFIELDS%VARIABLES%S%FT1, TKE=YDFIELDS%VARIABLES%TKE%FT1)


! Initialize temporaries for all other state copies and tendencies
CALL TENDENCY_CML%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
!!  CALL TENDENCY_DYN%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
CALL STATE_TMP%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
!!CALL STATE_T0%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
CALL TENDENCY_TMP%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
CALL TENDENCY_VDF%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
CALL TENDENCY_SATADJ%INIT(YDGEOMETRY, KEYMASK=KEYMASK)
CALL TENDENCY_LOC%INIT(YDGEOMETRY, KEYMASK=KEYMASK)

!!--
! Initialize local views for surface state fields
CALL ZSURF%INIT(YDFIELDS%REGISTRY, YDFIELDS%VARIABLES, YDFIELDS%SURFVARS, &
 &              NLEVS=YSP_SBD%NLEVS, NLEVSN=NCSNEC, NLEVO=YSP_OMD%NLEVS)
CALL ZAUX%INIT(YDFIELDS%REGISTRY, YDFIELDS%VARIABLES, NLEV=NFLEVG)
CALL ZRAD%INIT(YDFIELDS%REGISTRY, YDFIELDS%VARIABLES, NLEV=NFLEVG)
CALL FLUX%INIT(YDFIELDS%REGISTRY, NLEV=YDDIMV%NFLEVG, NLEVS=YDSURF%YSP_SBD%NLEVS, &
 &              NACTAERO=YGFL%NACTAERO, NPAERODIAG=NPAERODIAG)
CALL ZDIAG%INIT(YDFIELDS%REGISTRY, NLEV=YDDIMV%NFLEVG)
CALL ZDDHS%INIT(YDFIELDS%REGISTRY, DIMS=IDIMS)
CALL ZAUXL%INIT(YDFIELDS%REGISTRY, NLEV=YDDIMV%NFLEVG)
CALL ZSURFL%INIT(YDFIELDS%REGISTRY, YDDPHY%NCSNEC, NTILES=YDDPHY%NTILES, &
 &               NTSW=YDMODEL%YRML_PHY_RAD%YRERAD%NTSW, NLWEMISS=YDERAD%NLWEMISS)
CALL ZLLKEYS%INIT(YDFIELDS%REGISTRY)
CALL ZPERTL%INIT(YDFIELDS%REGISTRY, NLEV=YDDIMV%NFLEVG)
!!----

!!  CALL YDFIELDS%VARIABLES%CLONE_ARRAYS()
!!  CALL YDFIELDS%VARIABLES%UPDATE_VIEW(BLOCK_INDEX=IBL)

CALL IDIMS%UPDATE(IBL, IEND, JKGLO, KGPLAT=YDGSGEOM(IBL)%NGPLAT)
!!CALL IDIMS%UPDATE(IBL, ICEND, JKGLO, KGPLAT=YDGSGEOM(IBL)%NGPLAT)
CALL ZSURF%UPDATE_VIEW(BLOCK_INDEX=IBL)
CALL ZAUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
CALL ZRAD%UPDATE_VIEW(BLOCK_INDEX=IBL)
CALL ZPERT%UPDATE_VIEW(YDMODEL, YDSTOPH, IBL, 1, 1, NPROMA, NFLEVG, ZSPPTGFIX)
CALL FLUX%UPDATE_VIEW(BLOCK_INDEX=IBL)
CALL ZDIAG%UPDATE_VIEW(BLOCK_INDEX=IBL)
CALL ZDDHS%UPDATE_VIEW(BLOCK_INDEX=IBL)
CALL ZAUXL%UPDATE_VIEW(BLOCK_INDEX=IBL)
CALL ZSURFL%UPDATE_VIEW(BLOCK_INDEX=IBL)
CALL ZLLKEYS%UPDATE_VIEW(BLOCK_INDEX=IBL)
CALL ZPERTL%UPDATE_VIEW(BLOCK_INDEX=IBL)

CALL TENDENCY_DYN%UPDATE_VIEW(IBL)
CALL TENDENCY_LOC%UPDATE_VIEW(IBL)
CALL TENDENCY_CML%UPDATE_VIEW(IBL)
CALL STATE_TMP%UPDATE_VIEW(IBL)
CALL STATE_T0%UPDATE_VIEW(IBL)
CALL TENDENCY_TMP%UPDATE_VIEW(IBL)
CALL TENDENCY_VDF%UPDATE_VIEW(IBL)
CALL TENDENCY_SATADJ%UPDATE_VIEW(IBL)

CALL YDFIELDS%VARIABLES%UPDATE_VIEW(BLOCK_INDEX=IBL)


YDFIELDS%YRGMV%GMV(1 , :, YDFIELDS%YRGMV%YPH9%MU, 1) = UT9(1:NFLEVG)
YDFIELDS%YRGMV%GMV(1 , :, YDFIELDS%YRGMV%YPH9%MV, 1) = VT9(1:NFLEVG)
YDFIELDS%YRGMV%GMV(1 , :, YDFIELDS%YRGMV%YPH9%MT, 1) = TT9(1:NFLEVG)


YDFIELDS%YRGFL%GFL(:,:,:,1) = ZGFL

!!===========================================
! Set up STATE_T0

STATE_T0%U(1,:) = UT0(1:NFLEVG)
STATE_T0%V(1,:) = VT0(1:NFLEVG)
STATE_T0%T(1,:) = TT0(1:NFLEVG)
STATE_T0%Q(1,:) = QT0(1:NFLEVG)
STATE_T0%A(1,:) = AT0(1:NFLEVG)
STATE_T0%CLD(1,:,NCLDQL) = WT0(1:NFLEVG)
STATE_T0%CLD(1,:,NCLDQI) = ST0(1:NFLEVG)
STATE_T0%CLD(1,:,NCLDQR) = RNT0(1:NFLEVG)
STATE_T0%CLD(1,:,NCLDQS) = SNT0(1:NFLEVG)

! Set up TENDENCY_DYN arrays
TENDENCY_DYN%U(1,:) = ZUTEND_D(1:NFLEVG)
TENDENCY_DYN%V(1,:) = ZVTEND_D(1:NFLEVG)
TENDENCY_DYN%T(1,:) = ZTTEND_D(1:NFLEVG)
TENDENCY_DYN%Q(1,:) = ZQTEND_D(1:NFLEVG)
TENDENCY_DYN%A(1,:) = ZATEND_D(1:NFLEVG)
TENDENCY_DYN%CLD(1,:,NCLDQL) = ZLTEND_D(1:NFLEVG)
TENDENCY_DYN%CLD(1,:,NCLDQI) = ZITEND_D(1:NFLEVG)
TENDENCY_DYN%CLD(1,:,NCLDQR) = ZRTEND_D(1:NFLEVG)
TENDENCY_DYN%CLD(1,:,NCLDQS) = ZSTEND_D(1:NFLEVG)

!! entry point to EC_PHYS


ALLOCATE(ZGMVT1(1,NFLEVG,YT1%NDIM))
ZGMVT1(1,1:NFLEVG,YT1%MU)=ZUTEND(1:NFLEVG)
ZGMVT1(1,1:NFLEVG,YT1%MV)=ZVTEND(1:NFLEVG)
ZGMVT1(1,1:NFLEVG,YT1%MT)=ZTTEND(1:NFLEVG)

ydfields%yrgmv%gmvt1(:,:,:,1) = zgmvt1

ZAUX%PVERVEL => VVEL0
ALLOCATE(ZAUX%PGELAM(1:NPROMA))
ALLOCATE(ZAUX%PGELAT(1:NPROMA))
ALLOCATE(ZAUX%PGAW(1:NPROMA))
ALLOCATE(ZAUX%PCLON(1:NPROMA))
ALLOCATE(ZAUX%PSLON(1:NPROMA))
ALLOCATE(ZAUX%PGEMU(1:NPROMA))
ALLOCATE(ZAUX%POROG(1:NPROMA))
ALLOCATE(ZAUX%PGNORDL(1:NPROMA))
ALLOCATE(ZAUX%PGNORDM(1:NPROMA))
ALLOCATE(ZAUX%PGSQM2(1:NPROMA))
ALLOCATE(ZAUX%PRS1(1:NPROMA,0:NFLEVG))
ALLOCATE(ZAUX%PRSF1(1:NPROMA,NFLEVG))
ALLOCATE(ZAUX%PAPRS(1:NPROMA,0:NFLEVG))
ALLOCATE(ZAUX%PAPRSF(1:NPROMA,NFLEVG))
ALLOCATE(ZAUX%PGEOM1(1:NPROMA,NFLEVG))
ALLOCATE(ZAUX%PGEOMH(1:NPROMA,0:NFLEVG))
ALLOCATE(ZAUX%PDELP(1:NPROMA,NFLEVG))
ALLOCATE(ZAUX%PAPHI(1:NPROMA,0:NFLEVG))
ALLOCATE(ZAUX%PAPHIF(1:NPROMA,NFLEVG))
ALLOCATE(ZAUX%PMU0(1:NPROMA))
ALLOCATE(ZAUX%PMU0M(1:NPROMA))
ALLOCATE(ZAUX%PMU0T(1:NPROMA))

ZAUX%PGELAM(1:NPROMA)  = YDGSGEOM(IBL)%GELAM(1:NPROMA)
ZAUX%PGELAT(1:NPROMA)  = YDGSGEOM(IBL)%GELAT(1:NPROMA)
! Fraction of globe covered by gridpoint area
ZAUX%PGAW(1:NPROMA)    = RPI/REAL(NSMAX*NSMAX,JPRB)
ZAUX%PCLON(1:NPROMA)   = YDGSGEOM(IBL)%GECLO(1:NPROMA)
ZAUX%PSLON(1:NPROMA)   = YDGSGEOM(IBL)%GESLO(1:NPROMA)
ZAUX%PGEMU(1:NPROMA)   = YDGSGEOM(IBL)%GEMU(1:NPROMA)
ZAUX%POROG(1:NPROMA)   = YDGEOMETRY%YROROG(IBL)%OROG(1:NPROMA)
ZAUX%PGNORDL(1:NPROMA) = 1._JPRB ! YDGSGEOM(IBL)%GNORDL(1:NPROMA)
ZAUX%PGNORDM(1:NPROMA) = 1._JPRB ! YDGSGEOM(IBL)%GNORDM(1:NPROMA)
ZAUX%PGSQM2(1:NPROMA)  = YDGSGEOM(IBL)%GSQM2(1:NPROMA)
!ZAUX%PRSF1(1:NPROMA) set in GPHPRE below

      ! Health warning: following four arrays are implicitly dimensioned from 1 to NFLEVG+1
      ZRAD%PISUND    => VISUND

      ZRAD%PEMTD     => YDRADF%EMTD(:,:,IBL)
      ZRAD%PTRSW     => YDRADF%TRSW(:,:,IBL)
      ZRAD%PEMTC     => YDRADF%EMTC(:,:,IBL)
      ZRAD%PTRSC     => YDRADF%TRSC(:,:,IBL)

      ZRAD%PTAUAER   => YDRADF%TAUAER(:,:,:,IBL)
      ZRAD%PSRLWD    => YDRADF%SRLWD(:,:,IBL)
      ZRAD%PSRLWDC   => YDRADF%SRLWDC(:,IBL)
      ZRAD%PSRSWD    => YDRADF%SRSWD (:,IBL)
      ZRAD%PSRSWDC   => YDRADF%SRSWDC(:,IBL)
      ZRAD%PSRSWDCS  => YDRADF%SRSWDCS(:,IBL)
      ZRAD%PEDRO     => YDRADF%EDRO(:,IBL)
      ZRAD%PSRSWPAR  => YDRADF%SRSWPAR(:,IBL)
      ZRAD%PSRSWUVB  => YDRADF%SRSWUVB(:,IBL)
      ZRAD%PSRSWPARC => YDRADF%SRSWPARC(:,IBL)
      ZRAD%PSRSWTINC => YDRADF%SRSWTINC(:,IBL)
      ZRAD%PSRFDIR   => YDRADF%SRFDIR(:,IBL)
      ZRAD%PSRCDIR   => YDRADF%SRCDIR(:,IBL)
      ZRAD%DERIVATIVELW => YDRADF%DERIVATIVELW(:,:,IBL)

      ! Interface to global arrays (through derived type variables)
      ! Note: It is better not to trust any model dimension and secure it here (to avoid bound checking pb).
      !       Still it would be much easier to expect, that dimensions are at least 1.

      ZSURF%PSD_XA => VEXTRA
      ZSURF%PSD_X2 => VEXTR2

      ZSURF%PSD_VF  => SD_VF(:,:,1)
      ZSURF%PSD_VN  => SD_VN(:,:,1)
      ZSURF%PSD_VD  => SD_VD(:,:,1)
      ZSURF%PSP_SL  => SP_SL(:,:,1)
      ZSURF%PSP_SB  => SP_SB(:,:,:,1)
      ZSURF%PSP_SG  => SP_SG(:,:,:,1)
      ZSURF%PSP_RR  => SP_RR(:,:,1)
      ZSURF%PSP_EP  => SP_EP(:,:,:,1)
      ZSURF%PSP_X2  => SP_X2(:,:,1)
      ZSURF%PSP_OM  => SP_OM(:,:,:,1)
      ZSURF%PSD_WS  => SD_WS(:,:,1)
      ZSURF%PSD_WW  => SD_WW(:,:,1)
      ZSURF%PSD_V2  => SD_V2(:,:,1)
      ZSURF%PSD_V3  => SD_V3(:,:,:,1)
      ZSURF%PCOVPTOT=> SD_PF(:,:,1,1) !???  Precipitation types (quite dirty and broken)

      ZSURF%PUSTRTI => VUSTRTI
      ZSURF%PVSTRTI => VVSTRTI
      ZSURF%PAHFSTI => VAHFSTI
      ZSURF%PEVAPTI => VEVAPTI
      ZSURF%PTSKTI  => VTSKTI

      SP_SB=0._JPRB
      SP_SG=0._JPRB
      SP_RR=0._JPRB
      SP_EP=0._JPRB
      SP_X2=0._JPRB
      SP_OM=0._JPRB
      SD_WS=0._JPRB
      SD_WW=0._JPRB
      SD_V2=0._JPRB
      SD_V3=0._JPRB
      SD_WS(:,YSD_WS%YCHAR%MP,1)=0.018_JPRB  ! Charnock param for the surface
      !SD_WS(:,YSD_WS%YUSTOKES%MP,1)=0._JPRB
      !SD_WS(:,YSD_WS%YVSTOKES%MP,1)=0._JPRB
      !SD_XA=0._JPRB
      !SD_X2=0._JPRB

      !       ocean current - set to 0 in SCM
      SD_VF(1,YSD_VF%YUCUR%MP,1)=0._JPRB
      SD_VF(1,YSD_VF%YVCUR%MP,1)=0._JPRB

      !ALLOCATE (ZSURF%PEXTRD(NPROMA,NFLEVG,MAX(NVEXTRDYN,1)))  ! is it truly needed?
      ALLOCATE (ZSURF%PEXTRD(NPROMA,NFLEVG,NVEXTRDYN))


!*       1.5  INITIALIZING SURFACE VARIABLES AT T-DT IN THE FIRST 
!             TIME-STEP OR MAKING GP9=GP0 FOR THE TWO TIME LEVEL SCHEME.
!             ----------------------------------------------------------

IF (LLFSTEP.OR.LTWOTL) THEN
!SCMEDIT - Are the dimensions the right way round?
 SP_SG(:,1,YSP_SG%YF%MP9,1) = SNS0(:)  !SURFRESERV.NEIGE    141
 SP_SG(:,1,YSP_SG%YA%MP9,1) = ASN0(:)  !SNOW ALBEDO          32
 SP_SG(:,1,YSP_SG%YR%MP9,1) = RSN0(:)  !SNOW DENSITY         33
 SP_SG(:,1,YSP_SG%YT%MP9,1) = TSN0(:)  !SNOW TEMPERATURE    238
 SP_RR(:,YSP_RR%YW%MP9,1) = WL0(:)   !SKINRESERV.EAU      198
 SP_RR(:,YSP_RR%YT%MP9,1) = TL0(:)   !SKINTEMPERATURE     235
  DO JJ=1,ICSS
    SP_SB(1,JJ,YSP_SB%YT%MP9,1)  = TSA0(JJ)  !LEV<JJ>TEMPARATURE
    SP_SB(1,JJ,YSP_SB%YQ%MP9,1)  = WSA0(JJ)  !LEV<JJ>RESERV.EAU
    SP_SB(1,JJ,YSP_SB%YTL%MP9,1) = TIA0(JJ)  !LEV<JJ>ICETEMP
  ENDDO
ENDIF


IF(ALLOCATED(YDSTOPH%RSTOPHCA))ZPERT%PSTOPHCA=> YDSTOPH%RSTOPHCA
IF (YDMODEL%YRML_GCONF%YRSPPT_CONFIG%LSPSDT) THEN
  ALLOCATE(ZPERT%PGP2DSDT(NPROMA,YDMODEL%YRML_SPPT%YGPSDT(1)%NG2D,YDMODEL%YRML_SPPT%N2D))
  DO J2D=1,YDMODEL%YRML_SPPT%N2D
    ZPERT%PGP2DSDT(:,:,J2D) = YDMODEL%YRML_SPPT%YGPSDT(J2D)%GP2D(:,:,IBL)
  ENDDO
ELSE
  ZPERT%PGP2DSDT => NULL()
ENDIF
IF (YDMODEL%YRML_GCONF%YRSPP_CONFIG%LSPP) THEN
  ALLOCATE(ZPERT%PGP2DSPP(NPROMA,YDMODEL%YRML_SPP%GP_ARP(1)%NG2D,YDMODEL%YRML_GCONF%YRSPP_CONFIG%SM%NRFTOTAL))
  DO JARP=1,YDMODEL%YRML_GCONF%YRSPP_CONFIG%SM%NRFTOTAL 
    ZPERT%PGP2DSPP(:,:,JARP) = YDMODEL%YRML_SPP%GP_ARP(JARP)%GP2D(:,:,IBL)
  ENDDO
ELSE
  ZPERT%PGP2DSPP=> null()
ENDIF
IF(ALLOCATED(YDSTOPH%GPTOTDISS))&
  & ZPERT%PTOTDISS_SMOOTH => YDSTOPH%GPTOTDISS_SMOOTH(:,:,IBL)
IF(ALLOCATED(YDSTOPH%GPVORTGRAD))&
  & ZPERT%PVORT           => YDSTOPH%GPVORTGRAD(:,1:NFLEVG,IBL)
IF(ALLOCATED(YDSTOPH%GPVORTGRAD))&
  & ZPERT%PVORTGRADX      => YDSTOPH%GPVORTGRAD(:,NFLEVG+1:2*NFLEVG,IBL)
IF(ALLOCATED(YDSTOPH%GPVORTGRAD))&
  & ZPERT%PVORTGRADY      => YDSTOPH%GPVORTGRAD(:,2*NFLEVG+1:3*NFLEVG,IBL)
IF(LFORCENL)THEN
  ZPERT%PFORCEU         => GPFORCEU(:,:,IBL,0)
  ZPERT%PFORCEV         => GPFORCEV(:,:,IBL,0)
  ZPERT%PFORCET         => GPFORCET(:,:,IBL,0)
  ZPERT%PFORCEQ         => GPFORCEQ(:,:,IBL,0)
ENDIF
!!IF (YSPPT_CONFIG%LSPSDT.AND.YSPPT_CONFIG%LSPPTGFIX) THEN
!!  ALLOCATE(ZPERT2%PSPPTGFIX(1,NFLEVG,4,2))
!!ENDIF
!!ZPERT2%PCUCONVCA   => RCUCONVCA
!!ZPERT2%PNLCONVCA   => RNLCONVCA
!!IF(LCUCONV_CA)ZPERT2%PCAPECONVCA => RCAPECONVCA
!!IF(ALLOCATED(YDSTOPH%GPSTREAM)) ZPERT2%PSTREAM => YDSTOPH%GPSTREAM(:,:,IBL)
!!IF(LSTOPH_SPBS_T) THEN
!!  ZPERT2%PTEMP       => GPTEMP(:,:,IBL)
!!ELSE
!!  ALLOCATE(ZPERT2%PTEMP(1,1))
!!ENDIF
!!IF(ALLOCATED(YDSTOPH%GPTOTDISS)) ZPERT2%PTOTDISS => YDSTOPH%GPTOTDISS(:,:,IBL)

!ZPERT%PSTOPHCA        => RSTOPHCA
!IF (YSPPT_CONFIG%LSPSDT) THEN
!  ALLOCATE(ZPERT%PGP2DSDT(NPROMA,YDMODEL%YRML_SPPT%YGPSDT(1)%NG2D,YDMODEL%YRML_SPPT%N2D))
!  DO J2D=1,YDMODEL%YRML_SPPT%N2D
!    ZPERT%PGP2DSDT(:,:,J2D) = YDMODEL%YRML_SPPT%YGPSDT(J2D)%GP2D(:,:,IBL)
!  ENDDO
! ELSE
!  ZPERT%PGP2DSDT      => NULL()
!ENDIF
!ZPERT%PTOTDISS_SMOOTH => NULL()  !GPTOTDISS_SMOOTH(:,:,IBL)
!ZPERT%PVORT           => NULL()  !GPVORTGRAD(:,1:NFLEVG,IBL)
!ZPERT%PVORTGRADX      => NULL()  !GPVORTGRAD(:,NFLEVG+1:2*NFLEVG,IBL)
!ZPERT%PVORTGRADY      => NULL()  !GPVORTGRAD(:,2*NFLEVG+1:3*NFLEVG,IBL)
!ZPERT%PFORCEU         => GPFORCEU(:,:,IBL,0)
!ZPERT%PFORCEV         => GPFORCEV(:,:,IBL,0)
!ZPERT%PFORCET         => GPFORCET(:,:,IBL,0)
!ZPERT%PFORCEQ         => GPFORCEQ(:,:,IBL,0)
!
!ZPERT2%PCUCONVCA   => RCUCONVCA
!ZPERT2%PNLCONVCA   => RNLCONVCA
!ZPERT2%PCAPECONVCA => RCAPECONVCA
!ZPERT2%PSTREAM     => NULL()  !GPSTREAM(:,:,IBL)
!ZPERT2%PTEMP       => GPTEMP(:,:,IBL)
!ZPERT2%PTOTDISS    => NULL()  !GPTOTDISS(:,:,IBL)

ZSPT0(1)=SPT0

!Setup of phys space arrays
CALL PHYS_ARRAYS_INI(YDSURF,YDEPHY,YGFL,IDIMS, ZAUX, ZDDHS, ZDIAG, ZSURF, ZRAD, FLUX)


! temporary fix pt1
ZSURF%PEMIS   = VFEMIS

ZAUX%PDELP => ZXYB9(:,:,YYTXYB%M_DELP)

!*      3.1   Compute pressure
ZAUX%PAPRS(1,IDIMS%KLEV) = EXP(ZSPT0(1))
CALL GPHPRE(IDIMS%KLON,IDIMS%KLEV,IDIMS%KIDIA,IDIMS%KFDIA,YDVAB,YDGEOMETRY%YRCVER,ZAUX%PAPRS, &
 &  PXYB=ZXYB9,PRESF=ZAUX%PAPRSF)

!*      3.3   Compute R, Cp 
CALL GPRCP(IDIMS%KLON,IDIMS%KIDIA,IDIMS%KFDIA,IDIMS%KLEV,PGFL=ZGFL,KGFLTYP=9,PR=ZR9)

!SCMEDIT
!*      3.4   Transform "presim" pressures into "prehyd" pressures
!             for input to the physics
!             (deep-layer NH equations in the dynamics, but physics keeps
!             the thin layer assumption and should see "prehyd" pressures
!             only). 
!IF (LRWSDLR) THEN
!  ALLOCATE(ZSPD9(IDIMS%KLON,IDIMS%KLEV))
!  ! Ignore (provisionally) the NH effects in this calculation,
!  ! because GMV attribute YPH9%MSPD is not ready for the time being.
!  ! Normally, ZSPD9 should be <=> PGMV(.,.,YPH9%MSPD,IBL) in EC_PHYS_DRV.
!  ZSPD9(:,:)=0.0_JPRB
!  ! Transform "presim" quantities into "prehyd" quantities.
!  CALL GNHDLRB(YDGEOMETRY,IDIMS%KLON,IDIMS%KIDIA,IDIMS%KFDIA,.TRUE.,ZAUX%POROG,TT9,ZR9,ZSPD9,&
!   & ZAUX%PAPRSF,ZAUX%PAPRS,ZAUX%PDELP,ZXYB9(1,1,YYTXYB%M_RDELP),ZXYB9(1,1,YYTXYB%M_LNPR),&
!   & ZXYB9(1,1,YYTXYB%M_ALPH),PASR2=ZASR2,PRSAH=ZRSAH)
!  DEALLOCATE(ZSPD9)
!  ! PSPT9 should not be used from now on in the remaining part of EC_PHYS.
!ENDIF
!SCMEDIT
!*      3.5   Integrate Hydrostatics

! ky: this calculation is done according to the thin layer equations 
!     (LRWSDLR=F) in all cases.
DO JROF=IDIMS%KIDIA,IDIMS%KFDIA
  ZAUX%PAPHI(JROF,IDIMS%KLEV) = ZAUX%POROG(JROF)
ENDDO

!!CALL GPGEO(IDIMS%KLON,IDIMS%KIDIA,IDIMS%KFDIA,IDIMS%KLEV,&
!! & ZAUX%PAPHI,ZAUX%PAPHIF,TT9,ZR9,ZXYB9(1,1,YYTXYB%M_LNPR),ZXYB9(1,1,YYTXYB%M_ALPH),&
!! & YDGEOMETRY%YRVERT_GEOM)

CALL GPGEO(IDIMS%KLON,IDIMS%KIDIA,IDIMS%KFDIA,IDIMS%KLEV,&
 & ZAUX%PAPHI,ZAUX%PAPHIF,ydfields%variables%T%ph9,ZR9,ZXYB9(1,1,YYTXYB%M_LNPR),ZXYB9(1,1,YYTXYB%M_ALPH),&
 & YDGEOMETRY%YRVERT_GEOM)

!RMF in 46r1
!ZPHI9(NFLEVG)=YDGEOMETRY%YROROG(1)%OROG(1)*RG
!CALL GPGEO(NPROMA,IST,IEND,NFLEVG,ZPHI9,ZPHIF9,TT9,ZR9,&
!      & ZXYB9(1,:,YYTXYB%M_LNPR), ZXYB9(1,:,YYTXYB%M_ALPH),YDGEOMETRY%YRVERT_GEOM) 


DO JLEV=1,IDIMS%KLEV
  DO JROF=IDIMS%KIDIA,IDIMS%KFDIA
    ZAUX%PGEOM1(JROF,JLEV)=ZAUX%PAPHIF(JROF,JLEV)-ZAUX%PAPHI(JROF,IDIMS%KLEV)
    ZAUX%PGEOMH(JROF,JLEV)=ZAUX%PAPHI(JROF,JLEV) -ZAUX%PAPHI(JROF,IDIMS%KLEV)
  ENDDO
ENDDO
DO JROF=IDIMS%KIDIA,IDIMS%KFDIA
  ZAUX%PGEOMH(JROF,0)=ZAUX%PAPHI(JROF,0)-ZAUX%PAPHI(JROF,IDIMS%KLEV)
ENDDO

!*      3.6   Astronomy.

DO JROF=IDIMS%KIDIA,IDIMS%KFDIA

  ZAUX%PMU0(JROF)=MAX( RSIDEC*ZAUX%PGEMU(JROF)&
   & -RCODEC*RCOVSR*SQRT(1.0_JPRB-ZAUX%PGEMU(JROF)**2)*COS(ZAUX%PGELAM(JROF))&
   & +RCODEC*RSIVSR*SQRT(1.0_JPRB-ZAUX%PGEMU(JROF)**2)*SIN(ZAUX%PGELAM(JROF))&
   & ,0.0_JPRB)  
  
  ZAUX%PMU0M(JROF)=MAX( RSIDECM*ZAUX%PGEMU(JROF)&
   & -RCODECM*RCOVSRM*SQRT(1.0_JPRB-ZAUX%PGEMU(JROF)**2)*COS(ZAUX%PGELAM(JROF))&
   & +RCODECM*RSIVSRM*SQRT(1.0_JPRB-ZAUX%PGEMU(JROF)**2)*SIN(ZAUX%PGELAM(JROF))&
   & ,0.0_JPRB)  

  ZAUX%PMU0T(JROF)=RSIDEC*ZAUX%PGEMU(JROF)&
   & -RCODEC*RCOVSR*SQRT(1.0_JPRB-ZAUX%PGEMU(JROF)**2)*COS(ZAUX%PGELAM(JROF))&
   & +RCODEC*RSIVSR*SQRT(1.0_JPRB-ZAUX%PGEMU(JROF)**2)*SIN(ZAUX%PGELAM(JROF))

ENDDO


!*       3.7  ADIABATIC TENDENCIES AS INPUT FOR PHYSICS

!*            COMPUTATION OF PRESSURE AT t+dt. NOTE THAT SINCE Ps
!             DOES NOT CHANGE WITH TIME, THE PRESSURE IS THE SAME  
!             AT t-dt,t OR t+dt. THIS COMPUTATION IS ONLY MADE 
!             BECAUSE OF SIMILARITY WITH THE IFS 3D MODEL.
!             ---------------------------------------------------

ZAUX%PRS1(1,IDIMS%KLEV) = EXP(ZSPT0(1))
CALL GPHPRE(IDIMS%KLON,IDIMS%KLEV,IDIMS%KIDIA,IDIMS%KFDIA,YDVAB,YDGEOMETRY%YRCVER,ZAUX%PRS1, &
 &  PRESF=ZAUX%PRSF1)

!QUERY: Do we keep this section of code - not sure whether it is ever used. 
!Calls abort as LRWSDLR not supported

!*      3.8   Transform "presim" pressures into "prehyd" pressures
!             for input to the physics
!             We do the approximation that we can re-use the (a**2/r**2)*(g/G)
!             previously computed in ZASR2 (even if it is not computed
!             at the right instant) to avoid tricky calculations.
!             (if we want to use GNHDLRB, need to change the previous call
!             of GPPRE into GPPREH+GPXYB+GPPREF+GPRCP).

!IF (LRWSDLR) THEN
!CALL ABOR1("LRWSDLR not supported")

!  ALLOCATE(ZPRS1O(IDIMS%KLON,0:IDIMS%KLEV))
!  ALLOCATE(ZPRSF1O(IDIMS%KLON,IDIMS%KLEV))
!  ! Convert half level pressure:
!  ZPRS1O(IDIMS%KIDIA:IDIMS%KFDIA,0)=ZAUX%PRS1(IDIMS%KIDIA:IDIMS%KFDIA,0)
!  DO JLEV=1,IDIMS%KLEV
!    DO JROF=IDIMS%KIDIA,IDIMS%KFDIA
!      ZPRS1O(JROF,JLEV)=ZPRS1O(JROF,JLEV-1)+ZASR2(JROF,JLEV)*&
!       & (ZAUX%PRS1(JROF,JLEV)-ZAUX%PRS1(JROF,JLEV-1))
!    ENDDO
!  ENDDO
!  ! Convert full level pressure:
!  DO JLEV=1,IDIMS%KLEV 
!    DO JROF=IDIMS%KIDIA,IDIMS%KFDIA
!      ZPRSF1O(JROF,JLEV)=ZPRS1O(JROF,JLEV)+ZASR2(JROF,JLEV)*&
!       & (ZAUX%PRSF1(JROF,JLEV)-ZAUX%PRS1(JROF,JLEV))
!    ENDDO
!  ENDDO
!  ! Memory transfer:
!  ZAUX%PRS1(IDIMS%KIDIA:IDIMS%KFDIA,0:IDIMS%KLEV)=ZPRS1O(IDIMS%KIDIA:IDIMS%KFDIA,0:IDIMS%KLEV)
!  ZAUX%PRSF1(IDIMS%KIDIA:IDIMS%KFDIA,1:IDIMS%KLEV)=ZPRSF1O(IDIMS%KIDIA:IDIMS%KFDIA,1:IDIMS%KLEV)
!  DEALLOCATE(ZPRS1O)
!  DEALLOCATE(ZPRSF1O)
!  ! PGMVT1S(.,YDGMV%YT1%MSP) should not be used from now on in the remaining part
!  !  of EC_PHYS.
!ENDIF


! The following are allocated in ifs/module/ecphys_flux_type_mod.F90:
! The rest of the PSURF variables are set to zero in ifs/phys_ec/phys_arrays_ini.F90
ZSURF%PUOE1 = 0._JPRB  
ZSURF%PVOE1 = 0._JPRB  
ZSURF%PTOE1 = 0._JPRB  
ZSURF%PSOE1 = 0._JPRB

! The following are allocated in ifs/module/ecphys_flux_type_mod.F90:
! The rest of the flux variables are set to zero in ifs/phys_ec/phys_arrays_ini.F90
FLUX%PFRSOD   = 0._JPRB
FLUX%PFRSODC  = 0._JPRB
FLUX%PUVDF    = 0._JPRB
FLUX%PPARF    = 0._JPRB
FLUX%PPARCF   = 0._JPRB
FLUX%PFRTHD   = 0._JPRB
FLUX%PFRTHDC  = 0._JPRB
FLUX%PTOFDU   = 0._JPRB
FLUX%PTOFDV   = 0._JPRB
FLUX%PFTG12   = 0._JPRB
FLUX%PFWEV    = 0._JPRB
FLUX%PFWSB    = 0._JPRB
FLUX%PFWG12   = 0._JPRB
FLUX%PFWMLT   = 0._JPRB
FLUX%PFWROD   = 0._JPRB
FLUX%PFWRO1   = 0._JPRB
FLUX%PFTLHEV  = 0._JPRB
FLUX%PFTLHSB  = 0._JPRB
FLUX%PFRSOC   = 0._JPRB
FLUX%PFRTHC   = 0._JPRB
FLUX%PDIFCQ   = 0._JPRB
FLUX%PDIFCS   = 0._JPRB
FLUX%PDIFTQ   = 0._JPRB
FLUX%PDIFTS   = 0._JPRB
FLUX%PFHPCL   = 0._JPRB
FLUX%PFHPCN   = 0._JPRB
FLUX%PFHPSL   = 0._JPRB
FLUX%PFHPSN   = 0._JPRB
FLUX%PFRSO    = 0._JPRB
FLUX%PFRTH    = 0._JPRB
FLUX%PSTRCU   = 0._JPRB
FLUX%PSTRCV   = 0._JPRB
FLUX%PSTRDU   = 0._JPRB
FLUX%PSTRDV   = 0._JPRB
FLUX%PSTRTU   = 0._JPRB
FLUX%PSTRTV   = 0._JPRB
FLUX%PENES    = 0._JPRB
FLUX%PAERODDF = 0._JPRB

ZRAD%PINCSR   = 0._JPRB

! The following are allocatd in ifs/module/ecphys_aux_diag_type_mod.F90:
! Do they need to be initialised? Many will be set in callpar, 
! either by a parametrization or to zero if param switched off.
! But if physics not called then won't be set and varwrite may fail.
! The rest of the ZDIAG variables are initialised to zero in phys_arrays_ini.F90
! Should the ones below also be zeroed in phys_arrays_ini?
ZDIAG%PCAPE     = 0._JPRB
ZDIAG%PCBASE    = 0._JPRB
ZDIAG%PCBASEA   = 0._JPRB
ZDIAG%PCTOPC    = 0._JPRB
ZDIAG%P0DEGL    = 0._JPRB
ZDIAG%PCIN      = 0._JPRB
ZDIAG%PVDIS     = 0._JPRB
ZDIAG%PVDISG    = 0._JPRB
ZDIAG%PUSTRG    = 0._JPRB
ZDIAG%PVSTRG    = 0._JPRB
ZDIAG%PI10FG    = 0._JPRB
ZDIAG%PPRECTYPE = 0._JPRB
ZDIAG%PFZRA     = 0._JPRB
ZDIAG%PCONVIND  = 0._JPRB
ZDIAG%PZTWETB   = 0._JPRB 
ZDIAG%PQSAT     = 0._JPRB
ZDIAG%PZTENT    = 0._JPRB
ZDIAG%PZTENQ    = 0._JPRB
ZDIAG%PKH_VDF   = 0._JPRB 
 
! GMV structure creation (should go to sugmv1c.F90)
YPH9%MSP = 1   ! required for GMVS
YPH9%MU  = 3
YPH9%MV  = 4
YPH9%MT  = 5
!YDGMV%NDIMGMV  = 9
!YDGMV%NDIMGMVS = 1

ALLOCATE(ZGMV(1,NFLEVG,YDGMV%NDIMGMV))
ZGMV(1,1:NFLEVG,YPH9%MU)=UT9(1:NFLEVG)
ZGMV(1,1:NFLEVG,YPH9%MV)=VT9(1:NFLEVG)
ZGMV(1,1:NFLEVG,YPH9%MT)=TT9(1:NFLEVG)

! Here we assume only MSLB2VVEL is used from PB2 buffer 
MSLB2VVEL=1

!! fill in ydfields stuff properly
YDFIELDS%YRGMV%GMV(:,:,:,1) = ZGMV
YDFIELDS%YRGFL%GFL(:,:,:,1) = ZGFL
YDFIELDS%YRGMV%GMVS(1,YPH9%MSP,1) = SPT0 
YDFIELDS%YRGMV%GMVT1S(1,YT1%MSP,1) = SPT0 

!===============================================================================
!
!
!*      12.   CALL PHYSICS
!
!
!===============================================================================
IF (LEPHYS) THEN

  ! Call full radiation scheme
  IF (LERADI.AND.(.NOT.YDEPHLI%LPHYLIN)) THEN
    IF (NRADFR == 0 ) THEN
      CALL ABOR1('CPG1C: NRADFR=0 !')
    ELSEIF (MOD(NSTEP,NRADFR) == 0) THEN

  !    CALL RADDRV(YDGEOMETRY,YDFIELDS%YRGMV,YDFIELDS%YRSURF,YDMODEL,1,1,1, &
  ! &              YDFIELDS%YRGMV%GMV,YDFIELDS%YRGMV%GMVS,VVEL0,YDFIELDS%YRGFL%GFL) !! PSLBUF2 replaced by VVEL0, is that right?
  !QUERY: YDFIELDS%YRGMV%GMVS not set - set to ZSPT0 - the latter works?!
!47r3:
!      CALL RADDRV(YDGEOMETRY,YDFIELDS%YRGMV,YDFIELDS%YRSURF,YDMODEL,1,1,1, &
!   &              YDFIELDS%YRGMV%GMV,ZSPT0,VVEL0,YDFIELDS%YRGFL%GFL) !! PSLBUF2 replaced by VVEL0, is that right?

      CALL RADDRV(YDGEOMETRY,YDFIELDS,YDMODEL,1,1,1,(/1._JPRB,1._JPRB,1._JPRB/) ) ! Is PGPIN correct?
    ENDIF
  ENDIF

  WRITE(NULOUT,*) 'CPC1C NSTEP',NSTEP
  WRITE(NULOUT,*) 'CPG1C SST ',ZSURF%PSD_VF(1,YSD_VF%YSST%MP)
  WRITE(NULOUT,*) 'CPG1C TL0 ',TL0(1)

  !*     4.2  CALL ECMWF PHYSICS
  CALL CALLPAR (YDGEOMETRY,YDFIELDS%VARIABLES,YDSURF,YDMODEL,IDIMS,&
    & ZAUX, ZRAD, FLUX, ZDIAG, ZSURF, &
    &    ZCGPP(1,1), ZCREC(1,1), ZAG, ZRECO,&
    & ZDDHS,  ZAUXL,ZSURFL, ZLLKEYS, ZPERTL,&
    ! - Quantities of current timestep
    & ZGFL,&
    ! Stochastics physics, cellular automata, SL physics quantities
    & ZPERT, ZSLPHY9,&
    ! - UPDATED TENDENCIES
  ! & YDFIELDS%YRGFL%GFLT1,&
    & ZTENGFL,&
    & ZPHYS_MWAVE,&
    ! Stored quantities
    & SAVTEND(:,:,:,IBL), ydfields%yrgfl%GFLSLP(:,:,:,1),&
    & STATE_T0, TENDENCY_DYN, TENDENCY_CML, STATE_TMP, TENDENCY_TMP,&
    & TENDENCY_VDF, TENDENCY_SATADJ, TENDENCY_LOC, TENDENCY_PHY&
    &)

  !QUERY: REmove?
  ! supress the physics (for tests only) 
  !IF (.NOT.LEPHYS) THEN
  !  ZGMVT1(1,1:NFLEVG,YDGMV%YT1%MU)=ZUTEND(1:NFLEVG)
  !  ZGMVT1(1,1:NFLEVG,YDGMV%YT1%MV)=ZVTEND(1:NFLEVG)
  !  ZGMVT1(1,1:NFLEVG,YDGMV%YT1%MT)=ZTTEND(1:NFLEVG)
  !  ZTENGFL(1,1:NFLEVG,YQ%MP1)= ZQTEND_D(1:NFLEVG) 
  !  !ZTENGFL(1,1:NFLEVG,YO3%MP1)= ZTENO3_D(1:NFLEVG)
  !  ZTENGFL(1,1:NFLEVG,YL%MP1)= ZLTEND_D(1:NFLEVG)
  !  ZTENGFL(1,1:NFLEVG,YI%MP1)= ZITEND_D(1:NFLEVG)
  !  ZTENGFL(1,1:NFLEVG,YA%MP1)= ZATEND_D(1:NFLEVG)
  !  ZTENGFL(1,1:NFLEVG,YR%MP1)= ZRTEND_D(1:NFLEVG)
  !  ZTENGFL(1,1:NFLEVG,YS%MP1)= ZSTEND_D(1:NFLEVG)
  !ENDIF


  ! Provisional conversion to history fields
  VI10FG =  ZDIAG%PI10FG
  VILSPF(:,1:NFLEVG) =  ZDIAG%PCOVPTOT(:,1:NFLEVG)
  ! Provisional conversion to diagnostic fields
  INTYPE = ZDIAG%ITYPE
  IPBLTYPE = ZDIAG%IPBLTYPE
  VQSAT(1:NFLEVG)  =  ZDIAG%PQSAT(1,1:NFLEVG)
  ! temporary fix pt2
  VFEMIS = ZSURF%PEMIS

  ZGMVT1 = YDFIELDS%YRGMV%GMVT1(:,:,:,1)

  !QUERY: remove?
  !UT9(1:NFLEVG) = YDFIELDS%VARIABLES%U%PH9(1,:)
  !VT9(1:NFLEVG) = YDFIELDS%VARIABLES%V%PH9(1,:)
  !TT9(1:NFLEVG) = YDFIELDS%VARIABLES%T%PH9(1,:)
  !QT9(1:NFLEVG) = YDFIELDS%VARIABLES%Q%PH9(1,:)
  !! NOT NEEDED map new objs back to old-style numbered arrays
  !UT0(1:NFLEVG) = state_t0%U(1,:)
  !VT0(1:NFLEVG) = state_t0%V(1,:)
  !TT0(1:NFLEVG) = state_t0%T(1,:)
  !QT0(1:NFLEVG) = state_t0%Q(1,:)

  !DEALLOCATE(ZRAD%PTAUAER,ZRAD%PSRLWDC,ZRAD%PSRSWD,ZRAD%PSRSWDC,ZRAD%PSRSWDCS,ZRAD%PEDRO,&
  ! & ZRAD%PSRSWPAR,ZRAD%PSRSWUVB,ZRAD%PSRSWPARC,ZRAD%PSRSWTINC,ZRAD%PSRFDIR,ZRAD%PSRCDIR)

  ! Keep this for future perturbation option?
  !!IF (YSPPT_CONFIG%LSPSDT.AND.YSPPT_CONFIG%LSPPTGFIX) THEN
  !!  IF(ASSOCIATED(ZPERT2%PSPPTGFIX)) DEALLOCATE(ZPERT2%PSPPTGFIX)
  !!ENDIF

ENDIF ! LEPHYS

DEALLOCATE(ZSLPHY9%U,ZSLPHY9%V,ZSLPHY9%T,ZSLPHY9%GFL)

!*       13.  DEFINE PHYSICS TENDENCIES.
!             --------------------------

!QUERY: Only L/I/R/S are put into ZTENGFL array, can change all Z*TEND to use tendency_cml?

!ZUTEND(1:NFLEVG)=ZGMVT1(1,1:NFLEVG,YT1%MU)
!ZVTEND(1:NFLEVG)=ZGMVT1(1,1:NFLEVG,YT1%MV)
!ZTTEND(1:NFLEVG)=ZGMVT1(1,1:NFLEVG,YT1%MT)
ZUTEND(1:NFLEVG)=TENDENCY_CML%U(1,:)
ZVTEND(1:NFLEVG)=TENDENCY_CML%V(1,:)
ZTTEND(1:NFLEVG)=TENDENCY_CML%T(1,:)

!ZQTEND(1:NFLEVG) = ZTENGFL(1,1:NFLEVG,YQ%MP1)
!ZTENO3(1:NFLEVG) = ZTENGFL(1,1:NFLEVG,YO3%MP1)
ZQTEND(1:NFLEVG) = TENDENCY_CML%Q(1,:)
ZATEND(1:NFLEVG) = TENDENCY_CML%A(1,:)
!IF ( LENCLD2 .AND. .NOT. LEPCLD ) THEN
!  !In this case it has to be reconstructed from already updated GFLs
!  ZLTEND(1:NFLEVG) = (ZGFL(1,1:NFLEVG,YL%MP9_PH) - WT9(1:NFLEVG))/ZDT
!  ZITEND(1:NFLEVG) = (ZGFL(1,1:NFLEVG,YI%MP9_PH) - ST9(1:NFLEVG))/ZDT
!!  ZATEND(1:NFLEVG) = (ZGFL(1,1:NFLEVG,YA%MP9_PH) - AT9(1:NFLEVG))/ZDT
!ELSE  
!  ZLTEND(1:NFLEVG) = ZTENGFL(1,1:NFLEVG,YL%MP1)
!  ZITEND(1:NFLEVG) = ZTENGFL(1,1:NFLEVG,YI%MP1)
!!  ZATEND(1:NFLEVG) = ZTENGFL(1,1:NFLEVG,YA%MP1)
!ENDIF
!ZRTEND(1:NFLEVG) = ZTENGFL(1,1:NFLEVG,YR%MP1)
!ZSTEND(1:NFLEVG) = ZTENGFL(1,1:NFLEVG,YS%MP1)
! Here TENDENCY_CML == ZTENGFL(:,:,Y*%MP1)
ZLTEND(1:NFLEVG) = TENDENCY_CML%CLD(1,:,NCLDQL)
ZITEND(1:NFLEVG) = TENDENCY_CML%CLD(1,:,NCLDQI)
ZRTEND(1:NFLEVG) = TENDENCY_CML%CLD(1,:,NCLDQR)
ZSTEND(1:NFLEVG) = TENDENCY_CML%CLD(1,:,NCLDQS)

ZQTEND_P = ZQTEND - ZQTEND_D
ZTTEND_P = ZTTEND - ZTTEND_D
ZUTEND_P = ZUTEND - ZUTEND_D
ZVTEND_P = ZVTEND - ZVTEND_D
ZLTEND_P = ZLTEND - ZLTEND_D
ZITEND_P = ZITEND - ZITEND_D
ZATEND_P = ZATEND - ZATEND_D
ZRTEND_P = ZRTEND - ZRTEND_D
ZSTEND_P = ZSTEND - ZSTEND_D

! Store history for non orog. gravity wave drag scheme
NOGWFIELD(1:NFLEVG,1)= ZGFL(1,1:NFLEVG,YNOGW(1)%MP)
NOGWFIELD(1:NFLEVG,2)= ZGFL(1,1:NFLEVG,YNOGW(2)%MP)

!*       14.  COMPUTATION OF T+DT VALUES FOR ATMOSPHERIC VARIABLES.
!             -----------------------------------------------------

ZBETA=EXP(-ZDT/RDTRELAX)
RDTRELAX_SPONGE=450.
ZBETA_SPONGE=EXP(-ZDT/RDTRELAX_SPONGE)

IF(LRELAX) THEN

!        RELAXATION WITH IMPLICIT SOLUTION.

  DO JLEV=1,NFLEVG

    IF(LUVREL) THEN

      ! Relax hard above 1 hPa
      IF(ZPRE9F(JLEV) .LE. 100._JPRB) THEN

      ! Implicit solution
        UT1(JLEV)=UT9(JLEV)*ZBETA_SPONGE+ &
                &(ZUTEND(JLEV)*RDTRELAX_SPONGE+UOBS(JLEV))*(1.0_JPRB-ZBETA_SPONGE)
        VT1(JLEV)=VT9(JLEV)*ZBETA_SPONGE+ &
                &(ZVTEND(JLEV)*RDTRELAX_SPONGE+VOBS(JLEV))*(1.0_JPRB-ZBETA_SPONGE)

      ! Only relax above pressure level RTQREL_PLEV (default all levels)
      ELSE IF(ZPRE9F(JLEV) .LE. RUVREL_PLEV) THEN

         IF (JLEV .EQ. 1 .AND. RUVREL_PLEV .LT. 110000.) &
             WRITE(6,*) ' WARNING: UV relaxation above:',RUVREL_PLEV

      ! Implicit solution
        UT1(JLEV)=UT9(JLEV)*ZBETA+ &
                 &(ZUTEND(JLEV)*RDTRELAX+UOBS(JLEV))*(1.0_JPRB-ZBETA)
        VT1(JLEV)=VT9(JLEV)*ZBETA+ &
                 &(ZVTEND(JLEV)*RDTRELAX+VOBS(JLEV))*(1.0_JPRB-ZBETA)

        ! Explicit solution
!        ZBETA=MIN(1.0_JPRB-ZDT/RDTRELAX,0.0_JPRB)
!        UT1(JLEV)=(UT9(JLEV)+ZUTEND(JLEV)*ZDT)*ZBETA+ &
!                 & UOBS(JLEV)*(1.0_JPRB-ZBETA)
!        VT1(JLEV)=(VT9(JLEV)+ZVTEND(JLEV)*ZDT)*ZBETA+ &
!                 & VOBS(JLEV)*(1.0_JPRB-ZBETA)

      ELSE

        UT1(JLEV)=UT9(JLEV)+ZDT*ZUTEND(JLEV)
        VT1(JLEV)=VT9(JLEV)+ZDT*ZVTEND(JLEV)

      ENDIF
    
    ELSE
      UT1(JLEV)=UT9(JLEV)+ZDT*ZUTEND(JLEV)
      VT1(JLEV)=VT9(JLEV)+ZDT*ZVTEND(JLEV)
    ENDIF

    IF(LTQREL) THEN

      ! Relax hard above 1 hPa
      IF(ZPRE9F(JLEV) .LE. 100._JPRB) THEN

      ! Implicit solution
        TT1(JLEV)=TT9(JLEV)*ZBETA_SPONGE+ &
                &(ZTTEND(JLEV)*RDTRELAX_SPONGE+TOBS(JLEV))*(1.0_JPRB-ZBETA_SPONGE)
        QT1(JLEV)=QT9(JLEV)*ZBETA_SPONGE+ &
                &(ZQTEND(JLEV)*RDTRELAX_SPONGE+QOBS(JLEV))*(1.0_JPRB-ZBETA_SPONGE)

      ELSE IF(ZPRE9F(JLEV) .LE. RTQREL_PLEV) THEN ! All levels

        IF (JLEV .EQ. 1.AND. RUVREL_PLEV .LT. 110000.) &
            WRITE(6,*) ' WARNING: TQ relaxation above:',RTQREL_PLEV

        ! Implicit solution
        TT1(JLEV)=TT9(JLEV)*ZBETA+ &
                 & (ZTTEND(JLEV)*RDTRELAX+TOBS(JLEV))*(1.0_JPRB-ZBETA)
        QT1(JLEV)=QT9(JLEV)*ZBETA+ &
                & (ZQTEND(JLEV)*RDTRELAX+QOBS(JLEV))*(1.0_JPRB-ZBETA)

        ! Explicit solution
!        ZBETA=MIN(1.0_JPRB-ZDT/RDTRELAX,0.0_JPRB)
!        TT1(JLEV)=(TT9(JLEV)+ZTTEND(JLEV)*ZDT)*ZBETA+ &
!                 & TOBS(JLEV)*(1.0_JPRB-ZBETA)
!        QT1(JLEV)=(QT9(JLEV)+ZQTEND(JLEV)*ZDT)*ZBETA+ &
!                & QOBS(JLEV)*(1.0_JPRB-ZBETA)
      ELSE
 
        TT1(JLEV)=TT9(JLEV)+ZDT*ZTTEND(JLEV)
        QT1(JLEV)=QT9(JLEV)+ZDT*ZQTEND(JLEV)
 
      ENDIF

    ELSE
      TT1(JLEV)=TT9(JLEV)+ZDT*ZTTEND(JLEV)
      QT1(JLEV)=QT9(JLEV)+ZDT*ZQTEND(JLEV)
    ENDIF

    WT1(JLEV)=WT9(JLEV)+ZDT*ZLTEND(JLEV)
    ST1(JLEV)=ST9(JLEV)+ZDT*ZITEND(JLEV)
    AT1(JLEV)=AT9(JLEV)+ZDT*ZATEND(JLEV)
    RNT1(JLEV)=RNT9(JLEV)+ZDT*ZRTEND(JLEV)
    SNT1(JLEV)=SNT9(JLEV)+ZDT*ZSTEND(JLEV)

  ENDDO

ELSE

  ! Set end of timestep variables (T1) to (T9) + tendency from dynamics and physics
  DO JLEV=1,NFLEVG

    UT1(JLEV) = UT9(JLEV) + ZDT*ZUTEND(JLEV) ! u-wind
    VT1(JLEV) = VT9(JLEV) + ZDT*ZVTEND(JLEV) ! v-wind
    TT1(JLEV) = TT9(JLEV) + ZDT*ZTTEND(JLEV) ! temperature
    QT1(JLEV) = QT9(JLEV) + ZDT*ZQTEND(JLEV) ! humidity
    WT1(JLEV) = WT9(JLEV) + ZDT*ZLTEND(JLEV) ! cloud liquid
    ST1(JLEV) = ST9(JLEV) + ZDT*ZITEND(JLEV) ! cloud ice
    AT1(JLEV) = AT9(JLEV) + ZDT*ZATEND(JLEV) ! cloud fraction
    RNT1(JLEV)= RNT9(JLEV)+ ZDT*ZRTEND(JLEV) ! rain
    SNT1(JLEV)= SNT9(JLEV)+ ZDT*ZSTEND(JLEV) ! snow

  ENDDO

ENDIF


! Security for cloud and humidity variables (see CPQTUV)
! Need to deal with this for moisture conservation/budget
DO JLEV=1,NFLEVG
  IF (WT1(JLEV)<RLMIN)  WT1(JLEV)  = 0.0_JPRB
  IF (ST1(JLEV)<RLMIN)  ST1(JLEV)  = 0.0_JPRB
  IF (RNT1(JLEV)<RLMIN) RNT1(JLEV) = 0.0_JPRB
  IF (SNT1(JLEV)<RLMIN) SNT1(JLEV) = 0.0_JPRB
  IF (QT1(JLEV)<RLMIN)  QT1(JLEV)  = RLMIN
  IF (AT1(JLEV)<RAMIN .OR. (WT1(JLEV)+ST1(JLEV) < RLMIN)) THEN
    AT1(JLEV) = 0.0_JPRB
    WT1(JLEV) = 0.0_JPRB
    ST1(JLEV) = 0.0_JPRB
  ENDIF
  IF (AT1(JLEV)> 1.0_JPRB) AT1(JLEV)= 1.0_JPRB
ENDDO


!*       15.  COMPUTATION OF T+DT VALUES FOR SURFACE VARIABLES.
!             -------------------------------------------------

SNS1 = SNS9
WSN1 = 0.0_JPRB
ASN1 = ASN9
RSN1 = RSN9
TSN1 = TSN9
WL1  = WL9
TL1  = TL9

! Loop over soil levels
DO JJ=1,ICSS

  TSA1(JJ) = TSA9(JJ)
  WSA1(JJ) = WSA9(JJ)
  TIA1(JJ) = TIA9(JJ)

ENDDO

IF (LEPHYS) THEN
 
  ! Number of ocean levels - currently hardwired to 0
  ILEVOML=0

  ! We do shortcut here in Lakes time-stepping by working directly with the T9 values.
  ! This meand the T1 level is totally by-passed.) 
  CALL CPSPE(&
    & NPROMA ,IST    ,IEND   ,ICSS   ,NCXP,  ILEVOML , YSP_OMD%NLEVS ,&
    & NVXP   ,NVXP2  ,ZDT ,&
    & ZSURF%PTSAE1 ,ZSURF%PTLE1  ,ZSURF%PWSAE1 ,&
    & ZSURF%PTIAE1 ,&
    & ZSURF%PWLE1  ,ZSURF%PSNSE1 ,ZSURF%PWSNE1 ,&
    & ZSURF%PASNE1 ,ZSURF%PRSNE1 ,ZSURF%PTSNE1 ,&
    & ZSURF%PTLICEE1, ZSURF%PTLMNWE1,&  !LAKE
    & ZSURF%PTLWMLE1, ZSURF%PTLBOTE1,&  !LAKE
    & ZSURF%PTLSFE1 ,&                  !LAKE
    & ZSURF%PHLICEE1, ZSURF%PHLMLE1,&   !LAKE
    & ZEXTRE1,ZXTR2E1,&
    & ZSURF%PUOE1  ,ZSURF%PVOE1  ,ZSURF%PTOE1  ,ZSURF%PSOE1,&!KPP
    & TSA1   ,TL1    ,WSA1   ,&
    & TIA1   ,&
    & WL1    ,SNS1   ,WSN1,&
    & ASN1   ,RSN1   ,TSN1   ,&
    & ZSURF%PSP_SL(:,YSP_SL%YLICT%MP9),ZSURF%PSP_SL(:,YSP_SL%YLTLT%MP9),&!LAKE 
    & ZSURF%PSP_SL(:,YSP_SL%YLMLT%MP9),ZSURF%PSP_SL(:,YSP_SL%YLBLT%MP9),&!LAKE
    & ZSURF%PSP_SL(:,YSP_SL%YLSHF%MP9),&!LAKE
    & ZSURF%PSP_SL(:,YSP_SL%YLICD%MP9),ZSURF%PSP_SL(:,YSP_SL%YLMLD%MP9),&!LAKE
    & EXTRP1 ,XTRP21 ,&
    & ZSURF%PSP_OM(:,:,YSP_OM%YUO%MP1),ZSURF%PSP_OM(:,:,YSP_OM%YVO%MP1),& 
    & ZSURF%PSP_OM(:,:,YSP_OM%YTO%MP1),ZSURF%PSP_OM(:,:,YSP_OM%YSO%MP1))

ENDIF ! LEPHYS

!*       16.  PART 1 OF TIME FILTER.
!             ----------------------

IF (.NOT.LTWOTL) THEN

  CALL GPTF11C(YDGEOMETRY,YDMODEL,IST,IEND,LLLSTEP&
   &,UT0(1:NFLEVG),VT0(1:NFLEVG),TT0(1:NFLEVG),QT0(1:NFLEVG),ZDUM,ZDUM,ZDUM,ZDUM,ZDUM1,ZDUM1,ZDUM1&
   &,UT9(1:NFLEVG),VT9(1:NFLEVG),TT9(1:NFLEVG),QT9(1:NFLEVG),ZDUM,ZDUM,ZDUM,ZDUM,ZDUM1,ZDUM1,ZDUM1&
   &,WT0(1:NFLEVG),ST0(1:NFLEVG),AT0(1:NFLEVG),RNT0(1:NFLEVG),SNT0(1:NFLEVG),ZDUM,ZDUM,ZDUM,ZDUM,ZDUM,ZDUM&
   &,WT9(1:NFLEVG),ST9(1:NFLEVG),AT9(1:NFLEVG),RNT9(1:NFLEVG),SNT9(1:NFLEVG),ZDUM,ZDUM,ZDUM,ZDUM,ZDUM,ZDUM)

ENDIF


!*       17.  TIME FILTERING AND SWAPPING OF SURFACE VARIABLES.
!             -------------------------------------------------

IF (LTWOTL) THEN

  SNS0 = SNS1
!  WSN0 = WSN1  !Liquid water in the snow pack - to include
  ASN0 = ASN1
  RSN0 = RSN1
  TSN0 = TSN1
  WL0  = WL1
  TL0  = TL1

  DO JJ=1,ICSS

    TSA0(JJ) = TSA1(JJ)
    WSA0(JJ) = WSA1(JJ)
    TIA0(JJ) = TIA1(JJ)

  ENDDO

ELSE

  CALL GPTFS1C(JPGPP ,REPSP1 ,GP9 ,GP0 ,GP1)

ENDIF


!===============================================================================
!
!
!*       18.  WRITE OUT DIAGNOSTIC VARIABLES, FLUXES AND TENDENCIES.
!
!
!===============================================================================

CALL ACCUM1C(&
  & YDMODEL, YDGEOMETRY%YRDIMV, FLUX%PFWROD(1),FLUX%PFWRO1(1)&
  & ,ZDIAG%PVDIS(1) ,ZDIAG%PVDISG(1) ,ZDIAG%PUSTRG(1) ,ZDIAG%PVSTRG(1) &
  & ,FLUX%PFTLHEV(1),FLUX%PFTLHSB(1) &
  & ,ZCPR     ,ZCPS      ,ZSPR      ,ZSPS     ,ZIRUNOF &
  & ,ZISLHF   ,ZSWRF0    ,ZSWRFN    ,ZLWRF0   ,ZLWRFN &
  & ,FLUX%PDIFTQ(1,:)   ,FLUX%PDIFTS(1,:) &
  & ,FLUX%PFPLCL(1,:)   ,FLUX%PFPLCN(1,:)    ,FLUX%PFPLSL(1,:)    ,FLUX%PFPLSN(1,:) &
  & ,FLUX%PFRSO(1,:)    ,FLUX%PFRTH(1,:) &
  & ,FLUX%PSTRTU(1,:)   ,FLUX%PSTRTV(1,:) )

IA = MOD(NSTEP,NFRPOS)     ! output frequency NFRPOS

IF (IA == 0) THEN

  IF ( OUTFORM .EQ. 'netcdf' ) THEN ! Write out in netcdf format

    CALL WRTD1C_NC( YDGEOMETRY,YDMODEL,YDFIELDS%YRSURF &
      & ,ZCPR    ,ZCPS    ,ZSPR    ,ZSPS    ,ZIRUNOF ,FLUX%PFWMLT(1),FLUX%PFWSB(1) &
      & ,ZISLHF  ,ZSWRF0  ,ZSWRFN  ,ZLWRF0  ,ZLWRFN  &
      & ,ZDIAG%PVDIS(1),ZDIAG%PVDISG(1)  ,ZDIAG%PUSTRG(1) ,ZDIAG%PVSTRG(1)   &
      & ,ZQTEND  ,ZTTEND  ,ZUTEND  ,ZVTEND  ,ZLTEND  ,ZITEND  ,ZATEND   &
      & ,ZQTEND_D,ZTTEND_D,ZUTEND_D,ZVTEND_D,ZLTEND_D,ZITEND_D,ZATEND_D &
      & ,ZQTEND_P,ZTTEND_P,ZUTEND_P,ZVTEND_P,ZLTEND_P,ZITEND_P,ZATEND_P &
      & ,FLUX%PDIFCQ(1,:)  ,FLUX%PDIFCS(1,:)  ,FLUX%PDIFTQ(1,:)  ,FLUX%PDIFTS  ,FLUX%PFCQNG  &
      & ,FLUX%PFPLCL  ,FLUX%PFPLCN  ,FLUX%PFPLSL  ,FLUX%PFPLSN  &
      & ,FLUX%PFHPCL  ,FLUX%PFHPCN  ,FLUX%PFHPSL  ,FLUX%PFHPSN  &
      & ,FLUX%PFRSO   ,FLUX%PFRSOC  ,FLUX%PFRSOD(1),FLUX%PFRTH,FLUX%PFRTHC,FLUX%PFRTHD(1),ZRAD%PINCSR(1) &
      & ,FLUX%PSTRCU  ,FLUX%PSTRCV  ,FLUX%PSTRDU  ,FLUX%PSTRDV  ,FLUX%PSTRTU  ,FLUX%PSTRTV  &
      & ,FLUX%PDIFTI  ,FLUX%PDIFTL  ,FLUX%PFCCQN  ,FLUX%PFCCQL  ,FLUX%PFCSQN  ,FLUX%PFCSQL  &
      & ,FLUX%PFCQLNG ,FLUX%PFCQNNG ,ZDIAG%ICBOT  ,ZDIAG%ICTOP  ,ZDIAG%ZLUDE(1,:), ZDIAG%ZLU(1,:)  &
      & ,ZPHIF9  ,ZPHI9   ,ZPRE9   ,ZPRE9F)

  ELSE

    CALL WRTD1C(YDGEOMETRY%YRDIMV,YDMODEL,YDFIELDS%YRSURF&
      & ,ZCPR    ,ZCPS    ,ZSPR    ,ZSPS    ,ZIRUNOF&
      & ,ZISLHF  ,ZSWRF0  ,ZSWRFN  ,ZLWRF0  ,ZLWRFN&
      & ,ZDIAG%PVDIS(1),ZDIAG%PVDISG(1) ,ZDIAG%PUSTRG(1) ,ZDIAG%PVSTRG(1)&
      & ,ZQTEND  ,ZTTEND  ,ZUTEND  ,ZVTEND  ,ZLTEND  ,ZITEND  ,ZATEND&
      & ,ZQTEND_D,ZTTEND_D,ZUTEND_D,ZVTEND_D,ZLTEND_D,ZITEND_D,ZATEND_D&
      & ,ZQTEND_P,ZTTEND_P,ZUTEND_P,ZVTEND_P,ZLTEND_P,ZITEND_P,ZATEND_P&
      & ,FLUX%PDIFCQ(1,:)  ,FLUX%PDIFCS(1,:)  ,FLUX%PDIFTQ(1,:)  ,FLUX%PDIFTS  ,FLUX%PFCQNG&
      & ,FLUX%PFPLCL  ,FLUX%PFPLCN  ,FLUX%PFPLSL  ,FLUX%PFPLSN&
      & ,FLUX%PFHPCL  ,FLUX%PFHPCN  ,FLUX%PFHPSL  ,FLUX%PFHPSN&
      & ,FLUX%PFRSO   ,FLUX%PFRTH&
      & ,FLUX%PSTRCU  ,FLUX%PSTRCV  ,FLUX%PSTRDU  ,FLUX%PSTRDV  ,FLUX%PSTRTU  ,FLUX%PSTRTV&
      & ,FLUX%PDIFTI  ,FLUX%PDIFTL  ,FLUX%PFCCQN  ,FLUX%PFCCQL  ,FLUX%PFCSQN  ,FLUX%PFCSQL&
      & ,FLUX%PFCQLNG ,FLUX%PFCQNNG&
      & ,ZPHIF9  ,ZPHI9   ,ZPRE9   ,ZPRE9F)

  ENDIF

ENDIF


!*       19.  SWAPPING VARIABLES.
!             -------------------
! Set start of timestep variables (T0) for next timestep to end of timestep values (T1) here 
DO JALEV=1,NFLEVG
  UT0(JALEV)  = UT1(JALEV) ! u-wind
  VT0(JALEV)  = VT1(JALEV) ! v-wind
  TT0(JALEV)  = TT1(JALEV) ! temperature
  QT0(JALEV)  = QT1(JALEV) ! humidity
  WT0(JALEV)  = WT1(JALEV) ! Cloud water
  ST0(JALEV)  = ST1(JALEV) ! Cloud ice
  AT0(JALEV)  = AT1(JALEV) ! Cloud fraction
  RNT0(JALEV) = RNT1(JALEV)! Rin
  SNT0(JALEV) = SNT1(JALEV)! Snow
ENDDO


!===============================================================================
!
! CLEANING/DEALLOCATION OF ARRAYS
!
!===============================================================================
! QUERY: Is everything deallocated that should be?

CALL STATE_T0%FINAL()
CALL TENDENCY_DYN%FINAL()
CALL TENDENCY_CML%FINAL()
CALL STATE_TMP%FINAL()
CALL TENDENCY_TMP%FINAL()
CALL TENDENCY_VDF%FINAL()
CALL TENDENCY_SATADJ%FINAL()
CALL TENDENCY_LOC%FINAL()


CALL ZSURF%FINAL()
CALL ZRAD%FINAL()
CALL FLUX%FINAL()
CALL ZDIAG%FINAL()
CALL ZDDHS%FINAL()
CALL ZAUXL%FINAL()
CALL ZSURFL%FINAL()
CALL ZLLKEYS%FINAL()
CALL ZPERTL%FINAL()
CALL ZAUX%FINAL()

DEALLOCATE(ZAUX%PGELAM, ZAUX%PGELAT,  ZAUX%PGAW,    ZAUX%PCLON, ZAUX%PSLON, ZAUX%PGEMU)
DEALLOCATE(ZAUX%POROG,  ZAUX%PGNORDL, ZAUX%PGNORDM, ZAUX%PGSQM2)
DEALLOCATE(ZAUX%PRS1,   ZAUX%PRSF1,   ZAUX%PAPRS,   ZAUX%PAPRSF)
DEALLOCATE(ZAUX%PGEOM1, ZAUX%PGEOMH,  ZAUX%PAPHI, ZAUX%PAPHIF)
DEALLOCATE(ZAUX%PMU0,   ZAUX%PMU0M,   ZAUX%PMU0T)
!,  ZAUX%PDELP !QUERY get a run failure if deallocate this variable- why ?!

DEALLOCATE(ZGMV,ZGMVT1) !! ,IDIMS_ARR)

DEALLOCATE(ZSURF%PEXTRD)

! Cleaning of local arrays to physics - QUERY:doesn't do anything anymore -remove?
CALL PHYS_ARRAYS_FIN(IDIMS, ZAUX, ZDDHS, ZDIAG, ZSURF, ZRAD, FLUX)

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('CPG1C',1,ZHOOK_HANDLE)
END SUBROUTINE CPG1C
