! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE GPTF21C(YDGEOMETRY,YDMODEL,KSTART,KPROF,LDFSTEP,&
 &PUT0,PVT0,PTT0,PQT0,PDIVT0,PTT0L,PTT0M,PSVT0,PSPT0,PSPT0L,PSPT0M,&
 &PUT9,PVT9,PTT9,PQT9,PDIVT9,PTT9L,PTT9M,PSVT9,PSPT9,PSPT9L,PSPT9M,&
 &PLT0,PIT0,PAT0,PRT0,PST0,PSPD0,PSVD0,PSPD0L,PSVD0L,PSPD0M,PSVD0M,&
 &PLT9,PIT9,PAT9,PRT9,PST9,PSPD9,PSVD9,PSPD9L,PSVD9L,PSPD9M,PSVD9M)

!**** *GPTF21C* - Timefilter part 2

!     Purpose.
!     --------
!           Performs part 2 of the time-filtering.

!**   Interface.
!     ----------
!        *CALL* *GPTF2(...)

!        Explicit arguments :
!        --------------------
!                              KSTART -  start of work
!                              KPROF  -  depth of work
!                              PGT0 - timestep t
!                              PGT9 - timestep t-dt
!                              LDFSTEP - .TRUE. if first step

!        Implicit arguments :  None
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.  None.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the single column model.

!     Author.
!     -------
!        Joao Teixeira  *ECMWF*

!     Modifications.
!     --------------
!        Original (based on gptf2.F) : Nov.96
!        M. Ko"hler  6-6-2006  Single Column Model integration within IFS 
!     ------------------------------------------------------------------

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL   , ONLY : MODEL
USE PARKIND1 , ONLY : JPIM, JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
IMPLICIT NONE

TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(MODEL),    INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM),PARAMETER :: NFPASS=1

!     DUMMY INTEGER SCALARS
INTEGER(KIND=JPIM) :: KPROF
INTEGER(KIND=JPIM) :: KSTART

!     DUMMY LOGICAL SCALARS
LOGICAL LDFSTEP


REAL(KIND=JPRB) :: PUT0(YDGEOMETRY%YRDIMV%NFLEVG),PUT9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PVT0(YDGEOMETRY%YRDIMV%NFLEVG),PVT9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PTT0(YDGEOMETRY%YRDIMV%NFLEVG),PTT9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PQT0(YDGEOMETRY%YRDIMV%NFLEVG),PQT9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PDIVT0(YDGEOMETRY%YRDIMV%NFLEVG), &
 & PDIVT9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PTT0L(YDGEOMETRY%YRDIMV%NFLEVG), &
 & PTT9L(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PTT0M(YDGEOMETRY%YRDIMV%NFLEVG), &
 & PTT9M(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PSVT0(YDGEOMETRY%YRDIMV%NFLEVG,NFPASS), &
 & PSVT9(YDGEOMETRY%YRDIMV%NFLEVG,NFPASS)
REAL(KIND=JPRB) :: PSPT0 (YDGEOMETRY%YRDIM%NPROMA),PSPT9 (YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: PSPT0L(YDGEOMETRY%YRDIM%NPROMA),PSPT9L(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: PSPT0M(YDGEOMETRY%YRDIM%NPROMA),PSPT9M(YDGEOMETRY%YRDIM%NPROMA)
REAL(KIND=JPRB) :: PLT0(YDGEOMETRY%YRDIMV%NFLEVG),PLT9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PIT0(YDGEOMETRY%YRDIMV%NFLEVG),PIT9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PAT0(YDGEOMETRY%YRDIMV%NFLEVG),PAT9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PRT0(YDGEOMETRY%YRDIMV%NFLEVG),PRT9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PST0(YDGEOMETRY%YRDIMV%NFLEVG),PST9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PSPD0(YDGEOMETRY%YRDIMV%NFLEVG), &
 & PSPD9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PSVD0(YDGEOMETRY%YRDIMV%NFLEVG), &
 & PSVD9(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PSPD0L(YDGEOMETRY%YRDIMV%NFLEVG), &
 & PSPD9L(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PSVD0L(YDGEOMETRY%YRDIMV%NFLEVG), &
 & PSVD9L(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PSPD0M(YDGEOMETRY%YRDIMV%NFLEVG), &
 & PSPD9M(YDGEOMETRY%YRDIMV%NFLEVG)
REAL(KIND=JPRB) :: PSVD0M(YDGEOMETRY%YRDIMV%NFLEVG), &
 & PSVD9M(YDGEOMETRY%YRDIMV%NFLEVG)

!     LOCAL INTEGER SCALARS
INTEGER(KIND=JPIM) :: JK, JROF, JVAR, RKROMA

REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('GPTF21C',0,ZHOOK_HANDLE)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM,YDMP=>YDGEOMETRY%YRMP, &
 & YDVAB=>YDGEOMETRY%YRVAB, YGFL=>YDMODEL%YRML_GCONF%YGFL, &
 & YDVETA=>YDGEOMETRY%YRVETA,YDVFE=>YDGEOMETRY%YRVFE,YDSTA=>YDGEOMETRY%YRSTA, &
 & YDLAP=>YDGEOMETRY%YRLAP, &
 & YDDYN=>YDMODEL%YRML_DYN%YRDYN,YDDIMF=>YDMODEL%YRML_GCONF%YRDIMF)
ASSOCIATE(NFTHER=>YDDIMF%NFTHER, &
 & LTWOTL=>YDMODEL%YRML_DYN%YRDYNA%LTWOTL, &
 & LNHDYN=>YDMODEL%YRML_DYN%YRDYNA%LNHDYN, &
 & NFLEVG=>YDDIMV%NFLEVG, &
 & REPS1=>YDDYN%REPS1, REPS2=>YDDYN%REPS2, REPSM1=>YDDYN%REPSM1, &
 & REPSM2=>YDDYN%REPSM2, &
 & YA=>YGFL%YA, YI=>YGFL%YI, YL=>YGFL%YL, YQ=>YGFL%YQ, YR=>YGFL%YR, YS=>YGFL%YS)
IF ( LTWOTL ) THEN 
   RKROMA = 0.      ! 0. if Matsuno
ELSE
   RKROMA = 1.      ! 1. if leap-frog timescheme
ENDIF


!*       1. PERFORM TIME FILTER (PART 2)
!           ----------------------------

IF(LDFSTEP) THEN
  DO JK=1,NFLEVG
      PUT9(JK)   = PUT0(JK)
      PVT9(JK)   = PVT0(JK)
      PDIVT9(JK) = PDIVT0(JK)
      IF(NFTHER >= 1) THEN
        PTT9(JK)  = PTT0(JK)
        PTT9L(JK) = PTT0L(JK)
        PTT9M(JK) = PTT0M(JK)
      ENDIF
      IF(YQ%LACTIVE) THEN
        PQT9(JK)  = PQT0(JK)
      ENDIF
      IF(YL%LACTIVE) THEN
        PLT9(JK)  = PLT0(JK)
      ENDIF
      IF(YI%LACTIVE) THEN
        PIT9(JK)  = PIT0(JK)
      ENDIF
      IF(YR%LACTIVE) THEN
        PRT9(JK)  = PRT0(JK)
      ENDIF
      IF(YS%LACTIVE) THEN
        PST9(JK)  = PST0(JK)
      ENDIF
      IF(YA%LACTIVE) THEN
        PAT9(JK) = PAT0(JK)
      ENDIF
      IF(LNHDYN) THEN
        PSPD9(JK) = PSPD0(JK)
        PSVD9(JK) = PSVD0(JK)
        PSPD9L(JK) = PSPD0L(JK)
        PSVD9L(JK) = PSVD0L(JK)
        PSPD9M(JK) = PSPD0M(JK)
        PSVD9M(JK) = PSVD0M(JK)
      ENDIF
  ENDDO
  DO JVAR=1,NFPASS
    DO JK=1,NFLEVG
        PSVT9(JK,JVAR) = PSVT0(JK,JVAR)
    ENDDO
  ENDDO
  DO JROF=KSTART,KPROF
    PSPT9(JROF)  = PSPT0(JROF)
    PSPT9L(JROF) = PSPT0L(JROF)
    PSPT9M(JROF) = PSPT0M(JROF)
  ENDDO
ELSE
  DO JK=1,NFLEVG
      PUT9(JK)   = RKROMA*PUT9(JK)  +REPS2*PUT0(JK)
      PVT9(JK)   = RKROMA*PVT9(JK)  +REPS2*PVT0(JK)
      PDIVT9(JK) = RKROMA*PDIVT9(JK)+REPS2*PDIVT0(JK)
      IF(NFTHER >= 1) THEN
        PTT9(JK)  = RKROMA*PTT9(JK)  +REPS2*PTT0(JK)
        PTT9L(JK) = RKROMA*PTT9L(JK) +REPS2*PTT0L(JK)
        PTT9M(JK) = RKROMA*PTT9M(JK) +REPS2*PTT0M(JK)
      ENDIF
      IF(YQ%LACTIVE) THEN
        PQT9(JK) = RKROMA*PQT9(JK)+REPSM2*PQT0(JK)
      ENDIF
      IF(YL%LACTIVE) THEN
        PLT9(JK) = RKROMA*PLT9(JK)+REPSM2*PLT0(JK)
      ENDIF
      IF(YI%LACTIVE) THEN
        PIT9(JK) = RKROMA*PIT9(JK)+REPSM2*PIT0(JK)
      ENDIF
      IF(YR%LACTIVE) THEN
        PRT9(JK) = RKROMA*PRT9(JK)+REPSM2*PRT0(JK)
      ENDIF
      IF(YS%LACTIVE) THEN
        PST9(JK) = RKROMA*PST9(JK)+REPSM2*PST0(JK)
      ENDIF
      IF(YA%LACTIVE) THEN
        PAT9(JK) = RKROMA*PAT9(JK)+REPSM2*PAT0(JK)
      ENDIF
      IF(LNHDYN) THEN
        PSPD9(JK) = RKROMA*PSPD9(JK)+REPSM2*PSPD0(JK)
        PSVD9(JK) = RKROMA*PSVD9(JK)+REPSM2*PSVD0(JK)
        PSPD9L(JK) = RKROMA*PSPD9L(JK)+REPSM2*PSPD0L(JK)
        PSVD9L(JK) = RKROMA*PSVD9L(JK)+REPSM2*PSVD0L(JK)
        PSPD9M(JK) = RKROMA*PSPD9M(JK)+REPSM2*PSPD0M(JK)
        PSVD9M(JK) = RKROMA*PSVD9M(JK)+REPSM2*PSVD0M(JK)
      ENDIF
  ENDDO
  DO JVAR=1,NFPASS
    DO JK=1,NFLEVG
        PSVT9(JK,JVAR) = RKROMA*PSVT9(JK,JVAR)&
         &+REPS2*PSVT0(JK,JVAR)
    ENDDO
  ENDDO
  DO JROF=KSTART,KPROF
    PSPT9(JROF)  = RKROMA*PSPT9(JROF) +REPS2*PSPT0(JROF)
    PSPT9L(JROF) = RKROMA*PSPT9L(JROF)+REPS2*PSPT0L(JROF)
    PSPT9M(JROF) = RKROMA*PSPT9M(JROF)+REPS2*PSPT0M(JROF)
  ENDDO
ENDIF

!     ------------------------------------------------------------------

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('GPTF21C',1,ZHOOK_HANDLE)

END SUBROUTINE GPTF21C
