! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE SUALLO1C(YDGEOMETRY,YDMODEL)

USE GEOMETRY_MOD , ONLY : GEOMETRY
USE TYPE_MODEL   , ONLY : MODEL
USE PARKIND1  ,ONLY : JPIM, JPRB
USE YOMHOOK   ,ONLY : LHOOK, DR_HOOK, JPHOOK
USE PARDIM   , ONLY : JPMXLE
USE YOMCT0   , ONLY : LECMWF
USE YOMLUN   , ONLY : NULOUT

#ifdef DOC

!**** *SUALLO1C * - Routine to allocate space for global variables

!     Purpose.
!     --------
!           Allocate space for the global fields.

!**   Interface.
!     ----------
!        *CALL* *SUALLO1C*

!     Explicit arguments :  None
!     --------------------
!        Called by SU0YOM1C.

!     Implicit arguments :
!     --------------------
!        Pointers of comdecks

!     Method.
!     -------
!     Externals.
!     ----------

!     Reference.
!     ----------
!        ECMWF Research Department documentation of the SCM.

!     Author.
!     -------
!        Joao Teixeira *ECMWF*

!     Modifications.
!     --------------
!        Original (based on suallo.F) : Nov.96
!        M. Ko"hler    6-6-2006  Single Column Model integration within IFS 
!     ------------------------------------------------------------------

#endif

IMPLICIT NONE

TYPE(GEOMETRY), INTENT(INOUT) :: YDGEOMETRY
TYPE(MODEL),    INTENT(INOUT) :: YDMODEL
INTEGER(KIND=JPIM) :: IU

LOGICAL ::  LLP
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('SUALLO1C',0,ZHOOK_HANDLE)
!ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM,YDMP=>YDGEOMETRY%YRMP, &
! & YDVAB=>YDGEOMETRY%YRVAB, &
! & YDVETA=>YDGEOMETRY%YRVETA,YDVFE=>YDGEOMETRY%YRVFE,YDSTA=>YDGEOMETRY%YRSTA, &
! & YDLAP=>YDGEOMETRY%YRLAP, &
! & YDCSGLEG=>YDGEOMETRY%YRCSGLEG,YDVSPLIP=>YDGEOMETRY%YRVSPLIP,YDVSLETA=>YDGEOMETRY%YRVSLETA, &
! & YDHSLMER=>YDGEOMETRY%YRHSLMER,YDCSGEOM=>YDGEOMETRY%YRCSGEOM, &
! & YDCSGEOM_NB=>YDGEOMETRY%YRCSGEOM_NB,YDGSGEOM=>YDGEOMETRY%YRGSGEOM,YDGSGEOM_NB=>YDGEOMETRY%YRGSGEOM_NB,  &
! & YDSPGEOM=>YDGEOMETRY%YSPGEOM,YDDYN=>YDMODEL%YRML_DYN%YRDYN)
!ASSOCIATE(NDGENG=>YDDIM%NDGENG, NDGSAG=>YDDIM%NDGSAG, &
! & NMSMAX=>YDDIM%NMSMAX, NSMAX=>YDDIM%NSMAX, &
! & NFLEVG=>YDDIMV%NFLEVG, &
! & NTOZ2D=>YRDPHY%NTOZ2D, NVCLIS=>YRDPHY%NVCLIS)
ASSOCIATE(YDDIM=>YDGEOMETRY%YRDIM,YDDIMV=>YDGEOMETRY%YRDIMV,YDGEM=>YDGEOMETRY%YRGEM, &
 & YDMP=>YDGEOMETRY%YRMP, YDPHY=>YDMODEL%YRML_PHY_MF%YRPHY,YDEPHY=>YDMODEL%YRML_PHY_EC%YREPHY, &
 & YDDPHY=>YDMODEL%YRML_PHY_G%YRDPHY, YDTOPH=>YDMODEL%YRML_PHY_MF%YRTOPH, YDECLD=>YDMODEL%YRML_PHY_EC%YRECLD, &
 & YDEAERD=>YDMODEL%YRML_PHY_RAD%YREAERD, &
 & YDERAD=>YDMODEL%YRML_PHY_RAD%YRERAD, YDEOVLP=>YDMODEL%YRML_PHY_RAD%YREOVLP,YDDYN=>YDMODEL%YRML_DYN%YRDYN)
ASSOCIATE(NDGENG=>YDDIM%NDGENG, NDGSAG=>YDDIM%NDGSAG, &
 & NVCLIS=>YDDPHY%NVCLIS, NTOZ2D=>YDDPHY%NTOZ2D, &
 & NFLEVG=>YDDIMV%NFLEVG, &
 & LRRMES=>YDPHY%LRRMES, LAGPHY=>YDEPHY%LAGPHY)
!     ------------------------------------------------------------------

!*       1.    ALLOCATE SPACE FOR ARRAYS.
!              --------------------------

!*       1.1   GRID POINT FIELDS.

LLP = .TRUE.
IU = NULOUT
IF (LLP) WRITE(NULOUT,'('' SUALLO PRINTOUTS '')')


!*       1.9   DYNAMICS

! * Rayleigh friction.
IF(YDDYN%LRFRIC) THEN
  ALLOCATE(YDDYN%RKRF(NFLEVG))
  IF(LLP)WRITE(IU,9) 'RKRF   ',SIZE(YDDYN%RKRF),SHAPE(YDDYN%RKRF)
ENDIF

!*       1.10  STANDARD ATMOSPHERE.

!ALLOCATE(YRSTA)
!ALLOCATE(YRSTA%STPREH(0:NFLEVG))
!IF(LLP)WRITE(IU,9) 'STPREH   ',SIZE(YRSTA%STPREH),SHAPE(YRSTA%STPREH)
!ALLOCATE(YRSTA%STPRE(NFLEVG))
!IF(LLP)WRITE(IU,9) 'STPRE    ',SIZE(YRSTA%STPRE),SHAPE(YRSTA%STPRE)
!ALLOCATE(YRSTA%STPHI(NFLEVG))
!IF(LLP)WRITE(IU,9) 'STPHI    ',SIZE(YRSTA%STPHI),SHAPE(YRSTA%STPHI)
!ALLOCATE(YRSTA%STTEM(NFLEVG))
!IF(LLP)WRITE(IU,9) 'STTEM    ',SIZE(YRSTA%STTEM),SHAPE(YRSTA%STTEM)
!ALLOCATE(YRSTA%STDEN(NFLEVG))
!IF(LLP)WRITE(IU,9) 'STDEN    ',SIZE(YRSTA%STDEN),SHAPE(YRSTA%STDEN)
!ALLOCATE(YRSTA%STZ  (NFLEVG))
!IF(LLP)WRITE(IU,9) 'STZ      ',SIZE(YRSTA%STZ),SHAPE(YRSTA%STZ)

!*       1.16  PHYSICS

ALLOCATE(YDTOPH%RMESOU(NFLEVG))
IF(LLP)WRITE(IU,9) 'RMESOU   ',SIZE(YDTOPH%RMESOU),SHAPE(YDTOPH%RMESOU)
ALLOCATE(YDTOPH%RMESOT(NFLEVG))
IF(LLP)WRITE(IU,9) 'RMESOT   ',SIZE(YDTOPH%RMESOT),SHAPE(YDTOPH%RMESOT)

!*       1.18  EC PHYSICS CONSTANTS.

!ALLOCATE(YRECLD%CEVAPCU(NFLEVG))
!IF(LLP)WRITE(IU,9) 'CEVAPCU  ',SIZE(YRECLD%CEVAPCU),SHAPE(YRECLD%CEVAPCU)
ALLOCATE(YDECLD%CETA(NFLEVG))
IF(LLP)WRITE(IU,9) 'CETA     ',SIZE(YDECLD%CETA),SHAPE(YDECLD%CETA)
ALLOCATE(YDEAERD%CVDAES(NFLEVG+1))
IF(LLP)WRITE(IU,9) 'CVDAES   ',SIZE(YDEAERD%CVDAES),SHAPE(YDEAERD%CVDAES)
ALLOCATE(YDEAERD%CVDAEL(NFLEVG+1))
IF(LLP)WRITE(IU,9) 'CVDAEL   ',SIZE(YDEAERD%CVDAEL),SHAPE(YDEAERD%CVDAEL)
ALLOCATE(YDEAERD%CVDAEU(NFLEVG+1))
IF(LLP)WRITE(IU,9) 'CVDAEU   ',SIZE(YDEAERD%CVDAEU),SHAPE(YDEAERD%CVDAEU)
ALLOCATE(YDEAERD%CVDAED(NFLEVG+1))
IF(LLP)WRITE(IU,9) 'CVDAED   ',SIZE(YDEAERD%CVDAED),SHAPE(YDEAERD%CVDAED)
ALLOCATE(YDEOVLP%RA1OVLP(NFLEVG))
IF(LLP)WRITE(IU,9) 'RA1OVLP  ',SIZE(YDEOVLP%RA1OVLP),SHAPE(YDEOVLP%RA1OVLP)

ALLOCATE(YDERAD%CVDAESS(NFLEVG+1))
IF(LLP)WRITE(IU,9) 'CVDAESS  ',SIZE(YDERAD%CVDAESS),SHAPE(YDERAD%CVDAESS)
ALLOCATE(YDERAD%CVDAEDU(NFLEVG+1))
IF(LLP)WRITE(IU,9) 'CVDAEDU  ',SIZE(YDERAD%CVDAEDU),SHAPE(YDERAD%CVDAEDU)
ALLOCATE(YDERAD%CVDAEOM(NFLEVG+1))
IF(LLP)WRITE(IU,9) 'CVDAEOM  ',SIZE(YDERAD%CVDAEOM),SHAPE(YDERAD%CVDAEOM)
ALLOCATE(YDERAD%CVDAEBC(NFLEVG+1))
IF(LLP)WRITE(IU,9) 'CVDAEBC  ',SIZE(YDERAD%CVDAEBC),SHAPE(YDERAD%CVDAEBC)
ALLOCATE(YDERAD%CVDAESU(NFLEVG+1))
IF(LLP)WRITE(IU,9) 'CVDAESU  ',SIZE(YDERAD%CVDAESU),SHAPE(YDERAD%CVDAESU)


!*       1.20  CLIMATOLOGICAL PHYSICS FIELDS

IF (LECMWF) THEN
  IF(NVCLIS*NTOZ2D > 0) THEN
    ALLOCATE(YDMODEL%YRML_CHEM%YROZO%TOZ2DG(NFLEVG*NVCLIS*NTOZ2D,NDGSAG:NDGENG))
    IF(LLP)WRITE(IU,9) 'TOZ2DG   ',SIZE(YDMODEL%YRML_CHEM%YROZO%TOZ2DG),SHAPE(YDMODEL%YRML_CHEM%YROZO%TOZ2DG)
  ENDIF
ENDIF


!     ------------------------------------------------------------------
9 FORMAT(1X,'ARRAY ',A10,' ALLOCATED ',8I8)

END ASSOCIATE
END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('SUALLO1C',1,ZHOOK_HANDLE)
END SUBROUTINE SUALLO1C
