! (C) Copyright 1989- ECMWF.
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! 
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction

SUBROUTINE WRTD1C(YDDIMV,YDMODEL,YDSURF,&
  & PCPR    ,PCPS    ,PSPR    ,PSPS    ,PIRUNOF&
  & ,PISLHF  ,PSWRF0  ,PSWRFN  ,PLWRF0  ,PLWRFN&
  & ,PVDIS   ,PVDISG  ,PUSTRG  ,PVSTRG&
  & ,PQTEND  ,PTTEND  ,PUTEND  ,PVTEND  ,PLTEND  ,PITEND  ,PATEND&
  & ,PQTEND_D,PTTEND_D,PUTEND_D,PVTEND_D,PLTEND_D,PITEND_D,PATEND_D&
  & ,PQTEND_P,PTTEND_P,PUTEND_P,PVTEND_P,PLTEND_P,PITEND_P,PATEND_P&
  & ,PDIFCQ  ,PDIFCS  ,PDIFTQ  ,PDIFTS  ,PFCQNG&
  & ,PFPLCL  ,PFPLCN  ,PFPLSL  ,PFPLSN&
  & ,PFHPCL  ,PFHPCN  ,PFHPSL  ,PFHPSN&
  & ,PFRSO   ,PFRTH&
  & ,PSTRCU  ,PSTRCV  ,PSTRDU  ,PSTRDV  ,PSTRTU  ,PSTRTV&
  & ,PDIFTQN ,PDIFTQL ,PFCCQN  ,PFCCQL  ,PFCSQN  ,PFCSQL  ,PFCQLNG ,PFCQNNG&
  &,PPHIF9  ,PPHI9   ,PPRESH9 ,PPRESF9)

!*****WRTD1C*  - Writes diagnostics of the one-column model

!     Purpose.
!     --------
!        writes diagnostics of the one-column model

!***  Interface.
!     ----------
!        *CALL* *WRTD1C

!        Explicit arguments :
!        --------------------


!        Implicit arguments :
!        --------------------

!     Method.
!     -------
!        See documentation

!     Externals.
!     ----------
!        None

!     Reference.
!     ----------
!        ECMWF Research Department documentation 
!        of the single column model

!     Author.
!     -------
!        Joao Teixeira  *ECMWF*

!     Modifications.
!     --------------
!        Original      94-01-26
!        J.Teixeira     Jan.-95  new output files.
!        M. Ko"hler    6-6-2006  Single Column Model integration within IFS 

!     ------------------------------------------------------------------


USE YOMDIMV  , ONLY : TDIMV
USE TYPE_MODEL, ONLY : MODEL
USE PARKIND1 , ONLY : JPIM     ,JPRB
USE YOMHOOK  , ONLY : LHOOK, DR_HOOK, JPHOOK
USE YOMCST   , ONLY : RG
USE YOMCT3   , ONLY : NSTEP
USE YOMGPD1C        !all
USE YOMLOG1C , ONLY : NPOSASC
USE SURFACE_FIELDS_MIX , ONLY : TSURF


IMPLICIT NONE

TYPE(TDIMV), INTENT(INOUT) :: YDDIMV
TYPE(MODEL), INTENT(INOUT) :: YDMODEL
TYPE(TSURF), INTENT(INOUT) :: YDSURF

REAL(KIND=JPRB) :: PCPR  ,PCPS  ,PSPR  ,PSPS  ,PIRUNOF
REAL(KIND=JPRB) :: PISLHF,PSWRF0,PSWRFN,PLWRF0,PLWRFN
REAL(KIND=JPRB) :: PVDIS ,PVDISG,PUSTRG,PVSTRG

REAL(KIND=JPRB) :: PPRESH9 (0:YDDIMV%NFLEVG )  ! HALF LEVEL PRESSURE
REAL(KIND=JPRB) :: PPRESF9 (  YDDIMV%NFLEVG )  ! FULL LEVEL PRESSURE
REAL(KIND=JPRB) :: PPHI9   (0:YDDIMV%NFLEVG )  ! HALF LEVEL GEOPOTENTIAL
REAL(KIND=JPRB) :: PPHIF9  (  YDDIMV%NFLEVG )  ! FULL LEVEL GEOPOTENTIAL
REAL(KIND=JPRB) :: DPRES   (  YDDIMV%NFLEVG )  ! LAYER PRESSURE THICKNESS

REAL(KIND=JPRB) :: PUTEND  (YDDIMV%NFLEVG), PVTEND  (YDDIMV%NFLEVG), PTTEND  (YDDIMV%NFLEVG),&
                  &PQTEND  (YDDIMV%NFLEVG),&
                  &PLTEND  (YDDIMV%NFLEVG), PITEND  (YDDIMV%NFLEVG), PATEND  (YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PUTEND_D(YDDIMV%NFLEVG), PVTEND_D(YDDIMV%NFLEVG), PTTEND_D(YDDIMV%NFLEVG),&
                  &PQTEND_D(YDDIMV%NFLEVG),&
                  &PLTEND_D(YDDIMV%NFLEVG), PITEND_D(YDDIMV%NFLEVG), PATEND_D(YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PUTEND_P(YDDIMV%NFLEVG), PVTEND_P(YDDIMV%NFLEVG), PTTEND_P(YDDIMV%NFLEVG),&
                  &PQTEND_P(YDDIMV%NFLEVG),&
                  &PLTEND_P(YDDIMV%NFLEVG), PITEND_P(YDDIMV%NFLEVG), PATEND_P(YDDIMV%NFLEVG)

!     --- FLUXES FROM PARAMETERISATIONS ---

REAL(KIND=JPRB) :: PDIFCQ (0:YDDIMV%NFLEVG) , PDIFCS (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PDIFTQ (0:YDDIMV%NFLEVG) , PDIFTS (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PFCQNG (0:YDDIMV%NFLEVG) , PFPLCL (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PFPLCN (0:YDDIMV%NFLEVG) , PFPLSL (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PFPLSN (0:YDDIMV%NFLEVG) , PFRSO  (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PFRTH  (0:YDDIMV%NFLEVG) , PSTRCU (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PSTRCV (0:YDDIMV%NFLEVG) , PSTRDU (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PSTRDV (0:YDDIMV%NFLEVG) , PSTRTU (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PSTRTV (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PDIFTQN(0:YDDIMV%NFLEVG) , PDIFTQL(0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PFCCQN (0:YDDIMV%NFLEVG) , PFCCQL (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PFCSQN (0:YDDIMV%NFLEVG) , PFCSQL (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PFCQLNG(0:YDDIMV%NFLEVG) , PFCQNNG(0:YDDIMV%NFLEVG)

!     --- FLUXES FROM PARAMETERISATIONS AND TENDENCIES COMP.

REAL(KIND=JPRB) :: PFHPSL (0:YDDIMV%NFLEVG) , PFHPSN (0:YDDIMV%NFLEVG)
REAL(KIND=JPRB) :: PFHPCL (0:YDDIMV%NFLEVG) , PFHPCN (0:YDDIMV%NFLEVG)

!     --- local variables
REAL(KIND=JPRB) :: ZDE,ZDSSHF,ZDSLHF,ZDEWSS,ZDNSSS
REAL(KIND=JPRB) :: ZDSSR,ZDSTR,ZDTSR,ZDTTR,ZDLSP,ZDCP,ZDCSF,ZDLSSF
REAL(KIND=JPRB) :: ZDRO,ZDBLD,ZDGWD,ZDLGWS,ZDMGWS

INTEGER(KIND=JPIM) :: JALEV
REAL(KIND=JPHOOK) :: ZHOOK_HANDLE

!     ------------------------------------------------------------------

IF (LHOOK) CALL DR_HOOK('WRTD1C',0,ZHOOK_HANDLE)
ASSOCIATE(NFLEVG=>YDDIMV%NFLEVG, &
 & TSTEP=>YDMODEL%YRML_GCONF%YRRIP%TSTEP, &
 & YSD_VD=>YDSURF%YSD_VD,SD_VD=>YDSURF%SD_VD)

!        1.   PREPARING THE OUTPUT.
!             ---------------------

ZDE   = VDE   (1)/((NSTEP+1)*TSTEP)
ZDSSHF= VDSSHF(1)/((NSTEP+1)*TSTEP)
ZDSLHF= VDSLHF(1)/((NSTEP+1)*TSTEP)
ZDEWSS= VDEWSS(1)/((NSTEP+1)*TSTEP)
ZDNSSS= VDNSSS(1)/((NSTEP+1)*TSTEP)
ZDSSR = VDSSR (1)/((NSTEP+1)*TSTEP)
ZDSTR = VDSTR (1)/((NSTEP+1)*TSTEP)
ZDTSR = VDTSR (1)/((NSTEP+1)*TSTEP)
ZDTTR = VDTTR (1)/((NSTEP+1)*TSTEP)
ZDLSP = VDLSP (1)/((NSTEP+1)*TSTEP)
ZDCP  = VDCP  (1)/((NSTEP+1)*TSTEP)
ZDCSF = VDCSF (1)/((NSTEP+1)*TSTEP)
ZDLSSF= VDLSSF(1)/((NSTEP+1)*TSTEP)
ZDRO  = VDRO  (1)/((NSTEP+1)*TSTEP)
ZDBLD = VDBLD (1)/((NSTEP+1)*TSTEP)
ZDGWD = VDGWD (1)/((NSTEP+1)*TSTEP)
ZDLGWS= VDLGWS(1)/((NSTEP+1)*TSTEP)
ZDMGWS= VDMGWS(1)/((NSTEP+1)*TSTEP)


!        3.   WRITE to standard output.
!             -------------------------

!        3.1  WRITE OUT PRECIPITATION.

WRITE(NPOSASC,*) 'DIAGNOSTIC VARIABLES'
WRITE(NPOSASC,'("ICR=",E12.6)')   PCPR
WRITE(NPOSASC,'("ICSF=",E12.6)')  PCPS
WRITE(NPOSASC,'("ILSR=",E12.6)')  PSPR
WRITE(NPOSASC,'("ILSF=",E12.6)')  PSPS

!        3.2  WRITE OUT RADIATIVE FLUXES.

WRITE(NPOSASC,'("ITSR=",E12.6)')  PSWRF0
WRITE(NPOSASC,'("ISSR=",E12.6)')  PSWRFN
WRITE(NPOSASC,'("ITTR=",E12.6)')  PLWRF0
WRITE(NPOSASC,'("ISTR=",E12.6)')  PLWRFN

!        3.3  WRITE OUT TURBULENT FLUXES.

WRITE(NPOSASC,'("IEWSS=",E12.6)')  VDIEWSS
WRITE(NPOSASC,'("INSSS=",E12.6)')  VDINSSS

!        3.4  WRITE OUT ALBEDO, Z0 AND RUN-OFF.

WRITE(NPOSASC,'("FAL=",E12.6)')  SD_VD(1,YSD_VD%YALB%MP,1)
WRITE(NPOSASC,'("FSR=",E12.6)')  SD_VD(1,YSD_VD%YZ0F%MP,1)/RG
WRITE(NPOSASC,'("IRO=",E12.6)')  PIRUNOF

!        3.5  WRITE OUT 10M WIND.

WRITE(NPOSASC,'("10U=",E12.6)')  SD_VD(1,YSD_VD%Y10U%MP,1)
WRITE(NPOSASC,'("10V=",E12.6)')  SD_VD(1,YSD_VD%Y10V%MP,1)

!        3.6  WRITE OUT 2M TEMPERATURE.

WRITE(NPOSASC,'("2T=",E12.6)')  SD_VD(1,YSD_VD%Y2T%MP,1)
WRITE(NPOSASC,'("2D=",E12.6)')  SD_VD(1,YSD_VD%Y2D%MP,1)

!        3.7  WRITE OUT CLOUD COVER.

WRITE(NPOSASC,'("TCC=",E12.6)')  SD_VD(1,YSD_VD%YTCC%MP,1)
WRITE(NPOSASC,'("LCC=",E12.6)')  SD_VD(1,YSD_VD%YLCC%MP,1)
WRITE(NPOSASC,'("MCC=",E12.6)')  SD_VD(1,YSD_VD%YMCC%MP,1)
WRITE(NPOSASC,'("HCC=",E12.6)')  SD_VD(1,YSD_VD%YHCC%MP,1)

!        3.8  WRITE OUT DISSIPATION AND STRESS.

WRITE(NPOSASC,'("IBLD=",E12.6)')   PVDIS
WRITE(NPOSASC,'("IGWD=",E12.6)')   PVDISG
WRITE(NPOSASC,'("ILGWS=",E12.6)')  PUSTRG
WRITE(NPOSASC,'("IMGWS=",E12.6)')  PVSTRG

!        3.9  WRITE OUT SURF.SENS.HEAT FLUX AND LAT.HEAT FLUX.

WRITE(NPOSASC,'("ISSHF=",E12.6)')  VDISSHF
WRITE(NPOSASC,'("ISLHF=",E12.6)')  PISLHF


!        4.   WRITE OUT IN DIAGVAR FILE.
!        ------------------------------- 


IF(NSTEP == 0) THEN
  WRITE(53,1119) 'STEP'&
    &,'ICR'  ,'ICSF' ,'ILSR' ,'ILSF' ,'ITSR'&
    &,'ISSR' ,'ITTR' ,'ISTR' ,'IEWSS','INSSS'&
    &,'FAL'  ,'FSR'  ,'IRO'  ,'10U'  ,'10V'&
    &,'2T'   ,'2D'   ,'TCC'  ,'LCC'  ,'MCC'&
    &,'HCC'  ,'IBLD' ,'IGWD' ,'ILGWS','IMGWS'&
    &,'ISSHF','ISLHF','CR'   ,'CSF'  ,'LSR'&
    &,'LSF'  ,'TSR'  ,'SSR'  ,'TTR'  ,'STR'&
    &,'EWSS' ,'NSSS' ,'RO'   ,'BLD'  ,'GWD'&
    &,'LGWS' ,'MGWS' ,'SSHF' ,'SLHF'
ENDIF
WRITE(53,1120) NSTEP,PCPR,PCPS,PSPR,PSPS,PSWRF0,PSWRFN,PLWRF0 &
  &,PLWRFN,VDIEWSS,VDINSSS,SD_VD(1,YSD_VD%YALB%MP,1),SD_VD(1,YSD_VD%YZ0F%MP,1)/RG,&
  & PIRUNOF,SD_VD(1,YSD_VD%Y10U%MP,1) &
  &,SD_VD(1,YSD_VD%Y10V%MP,1),SD_VD(1,YSD_VD%Y2T%MP,1),SD_VD(1,YSD_VD%Y2D%MP,1)&
  &,SD_VD(1,YSD_VD%YTCC%MP,1),SD_VD(1,YSD_VD%YLCC%MP,1),SD_VD(1,YSD_VD%YMCC%MP,1)&
  &,SD_VD(1,YSD_VD%YHCC%MP,1),PVDIS &
  &,PVDISG,PUSTRG,PVSTRG,VDISSHF,PISLHF &
  &,ZDCP,ZDCSF,ZDLSP,ZDLSSF,ZDTSR,ZDSSR,ZDTTR &
  &,ZDSTR,ZDEWSS,ZDNSSS,ZDRO,ZDBLD, ZDGWD &
  &,ZDLGWS, ZDMGWS,ZDSSHF,ZDSLHF

1119 FORMAT(1(2X,A8),44(2X,A12))
1120 FORMAT(1(2X,I8),44(2X,E12.6))


!       12.   WRITE OUT TENDENCIES.
!       ---------------------------


IF (NSTEP == 0) THEN
  WRITE(54,1219) ' LEVEL ',' STEP ','  DU  ','  DV  ','  DT  '&
    &,'  DQ  ','  DA  ','  DL  ','  DI  ' &
    !amk
  &,' PHIF  '
!xxx
ENDIF

DO JALEV=1,NFLEVG
  WRITE(54,1220) JALEV,NSTEP,PUTEND(JALEV),PVTEND(JALEV)&
    &,PTTEND(JALEV),PQTEND(JALEV) ,PATEND(JALEV)&
    &,PLTEND(JALEV) ,PITEND(JALEV) &
    !amk
  &,PPHIF9(JALEV)
!xxx
ENDDO

1219 FORMAT(2(2X,A8),8(2X,A12))
1220 FORMAT(2(2X,I8),8(2X,E12.6))


!      13.  WRITE OUT DIAGNOSTIC FLUXES.
!      ---------------------------------


IF(NSTEP == 0) THEN
  WRITE(55,1319) ' LEVEL ' ,' STEP '                          &
    &,' PDIFCQ ',' PDIFCS ' ,' PDIFTQ ' ,' PDIFTS ' ,' PFCQNG '&
    &,' PFPLCL ',' PFPLCN ' ,' PFPLSL ' ,' PFPLSN ' ,' PFHPCL '&
    &,' PFHPCN ',' PFHPSL ' ,' PFHPSN ' ,' PFRSO '  ,' PFRTH ' &
    &,' PSTRCU ',' PSTRCV ' ,' PSTRDU ' ,' PSTRDV ' ,' PSTRTU '&
    &,' PSTRTV ',' PDIFTQN ',' PDIFTQL ',' PFCCQN ' ,' PFCCQL '&
    &,' PFCSQN ',' PFCSQL ' ,' PFCQLNG ',' PFCQNNG '
ENDIF

DO JALEV=0,NFLEVG
  WRITE(55,1320)     JALEV ,NSTEP   ,PDIFCQ(JALEV)  ,PDIFCS(JALEV)  ,&
    &PDIFTQ(JALEV)  ,PDIFTS(JALEV)  ,PFCQNG(JALEV)  ,PFPLCL(JALEV)  ,&
    &PFPLCN(JALEV)  ,PFPLSL(JALEV)  ,PFPLSN(JALEV)  ,PFHPCL(JALEV)  ,&
    &PFHPCN(JALEV)  ,PFHPSL(JALEV)  ,PFHPSN(JALEV)  ,PFRSO(JALEV)   ,&
    &PFRTH(JALEV)   ,PSTRCU(JALEV)  ,PSTRCV(JALEV)  ,PSTRDU(JALEV)  ,&
    &PSTRDV(JALEV)  ,PSTRTU(JALEV)  ,PSTRTV(JALEV)  ,PDIFTQN(JALEV) ,&
    &PDIFTQL(JALEV) ,PFCCQN(JALEV)  ,PFCCQL(JALEV)  ,PFCSQN(JALEV)  ,&
    &PFCSQL(JALEV)  ,PFCQLNG(JALEV) ,PFCQNNG(JALEV)
ENDDO

1319 FORMAT(2(2X,A8),29(2X,A12))
1320 FORMAT(2(2X,I8),29(2X,E12.6))

!     ------------------------------------------------------------

END ASSOCIATE
IF (LHOOK) CALL DR_HOOK('WRTD1C',1,ZHOOK_HANDLE)

END SUBROUTINE WRTD1C
