! (C) Copyright 1989- Meteo-France.

C
C     CONTAINS THE FLOATING POINT, REAL AND INTEGER DATA
C
C     VAR       DIMENSION     CONTENTS
C
C  CHARACTER
C
C     CLDATA    2             CHARACTER DATA
C
C  REAL
C
C     DATA      JPLENFP,2     REAL DATA
C
C  INTEGER
C 
C     NDATA     JPLENI,2      INTEGER DATA
C     NLENCHBL                LENGTH OF CHARACTER DATA
C     NLENRBL                 LENGTH OF REAL DATA
C     NLENIBL                 LENGTH OF INTEGER DATA
C     NBLLEN                  BLOCK LENGTH
C
      COMMON /COMDAT/CLDATA,DATA,NDATA,NLENCHBL,NLENRBL,NLENIBL,NBLLEN
      CHARACTER*6000 CLDATA(2)
      REAL DATA(JPLENFP,2)
      INTEGER NDATA(JPLENIN,2)
