! (C) Copyright 1989- Meteo-France.

C
      CHARACTER PARAM(15)*3,PROCESS(100)*4
      CHARACTER CDU1*4,CDU2*4,CPARDUM*1,CPRODUM*4
      CHARACTER CUPAR(50)*1,CUPRO(50)*4,CUNITS(50)*8
      REAL RUINT(50),RUMIN(50),RUMAX(50),RULIST(50,15),
     *     UGAIN(50),UOFFSET(50)
      LOGICAL LUSHADE(50),LULIST(50),LUZERO(50)
      NAMELIST /NAMUS/NSTEPB,NSTEPE,NSTEPI,NLEVTOP,NLEVBOT,RLATS,RLATN,
     *                PARAM,PROCESS,MYTEXT,AREATYP,PLOTTYP,NUDOM,
     *                CUPAR,CUPRO,CUNITS,NLVTOT,NLVPTS,
     *                RUINT,RUMIN,RUMAX,RULIST,UGAIN,UOFFSET,
     *                LUSHADE,LULIST,LUZERO,LCOLOUR,ORNTATION,
     *                LPRFI,LPLOT,CARCSUI,LARCHIVE,lheader,llsm
